- src/pybind/mgr/dashboard/controllers/cluster.py
- src/pybind/mgr/dashboard/controllers/health.py
- src/pybind/mgr/dashboard/controllers/orchestrator.py
- src/pybind/mgr/dashboard/controllers/prometheus.py
- src/pybind/mgr/dashboard/controllers/settings.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cluster.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/health.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/orchestrator.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/prometheus.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/prometheus.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/settings.py
backport tracker: https://tracker.ceph.com/issues/61485
---
backport of https://github.com/ceph/ceph/pull/51396
parent tracker: https://tracker.ceph.com/issues/61418
> quincy: mgr/dashboard: fix issues with read-only user on landing page

- src/cls/rgw/cls_rgw_types.h
- src/rgw/driver/rados/rgw_cr_rados.cc
- src/rgw/driver/rados/rgw_cr_rados.h
- src/rgw/driver/rados/rgw_data_sync.cc
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
- src/rgw/driver/rados/rgw_sync_module.h
- src/rgw/driver/rados/rgw_sync_module_aws.cc
- src/rgw/driver/rados/rgw_sync_module_es.cc
- src/rgw/driver/rados/rgw_sync_module_log.cc
- src/rgw/rgw_common.h
- src/rgw/rgw_op.cc
- src/rgw/rgw_op.h
- src/rgw/rgw_rest_conn.cc
- src/rgw/rgw_rest_conn.h
- src/rgw/rgw_rest_s3.cc
rgw: fetch_remote_obj() adds x-rgw-replicated-from 
rgw/rados: pass source zone trace into fetch_remote_obj()
backport tracker: https://tracker.ceph.com/issues/61630
backport of: #51715
backport of: #49767
parent tracker: https://tracker.ceph.com/issues/58911
<details> …
> reef: RGW: Pass and check destination zone trace when fetching object

- src/include/neorados/RADOS.hpp
- src/librados/IoCtxImpl.cc
- src/librbd/neorbdrados/RADOS.cc
- src/mds/Server.cc
- src/neorados/RADOS.cc
- src/osdc/Objecter.cc
- src/osdc/Objecter.h
- src/test/librados_test_stub/NeoradosTestStub.cc
Since Asio has its own type-erased handler now, use it.
This also fixes the lambda neorados test failures by reserving work on the executor.
<details> …
> neorados: Use `asio::any_completion_handler` instead of `ceph::async::Completion`

- doc/rados/operations/crush-map-edits.rst
> doc/rados: edit crush-map-edits.rst (1 of x)

- doc/rados/operations/crush-map-edits.rst
(cherry picked from commit f447c290a877c84cb14f0141ff5330f7147b2f6a)
<details> …
> quincy: doc/rados: edit crush-map-edits.rst (1 of x)

- doc/rados/operations/crush-map-edits.rst
(cherry picked from commit f447c290a877c84cb14f0141ff5330f7147b2f6a)
<details> …
> reef: doc/rados: edit crush-map-edits.rst (1 of x)

- src/crimson/os/seastore/btree/fixed_kv_btree.h
- src/crimson/os/seastore/cached_extent.h
EXIST_CLEAN and EXIST_MUTATION_PENDING shuold not be treated as CLEAN in check_node because they are transaction private and the leafnode has been duplicated for write.
<details> …
> crimson/os/seastore: fix in check_node

- doc/radosgw/s3select.rst
Remove strange formatting introduced in
61d6813726fc08980903c6a6c50b0a5797ba7193.
Note to the documentation team: This is not a line-edit. This commit includes nothing but the removal of pipes added to the left of much of the text in this file. Several future commits will line-edit this file and correct its formatting. …
> doc/radosgw: remove pipes from s3select.rst

- doc/radosgw/s3select.rst
Remove strange formatting introduced in
61d6813726fc08980903c6a6c50b0a5797ba7193.
Note to the documentation team: This is not a line-edit. This commit includes nothing but the removal of pipes added to the left of much of the text in this file. Several future commits will line-edit this file and correct its formatting.
(cherry picked from commit a4d302ee1a6e2f71263a898109ebed28e7e8eaca)
- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper …
> reef: doc/radosgw: remove pipes from s3select.rst

- doc/radosgw/s3select.rst
Remove strange formatting introduced in
61d6813726fc08980903c6a6c50b0a5797ba7193.
Note to the documentation team: This is not a line-edit. This commit includes nothing but the removal of pipes added to the left of much of the text in this file. Several future commits will line-edit this file and correct its formatting.
(cherry picked from commit a4d302ee1a6e2f71263a898109ebed28e7e8eaca)
- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper …
> quincy: doc/radosgw: remove pipes from s3select.rst

- doc/dev/deduplication.rst
Add prerequisite for deduplication, example outputs, and chunk-repair operation.
Signed-off-by: Sungmin Lee <sung_min.lee@samsung.com>
<details>
- …
> doc:dev update how to use deduplication

- src/pybind/mgr/snap_schedule/module.py
Any unknown exception causes the module to be unloaded and unresponsive. So, it'll be ideal to catch all exceptions during command-line interaction and report them instead of crashing with a traceback.
Fixes: https://tracker.ceph.com/issues/58195
<details> …
> mgr/snap_schedule: catch all exceptions for cli

- qa/tasks/mon_thrash.py
backport tracker: https://tracker.ceph.com/issues/61451
---
backport of https://github.com/ceph/ceph/pull/51570
parent tracker: https://tracker.ceph.com/issues/52316
> quincy: test: monitor thrasher wait until quorum

- qa/tasks/cephfs/test_failover.py
Otherwise, the MDS that just got replaced can transition to a rank for another file system and the test cannot deterministically infer which MDS needs to checked.
Fixes: http://tracker.ceph.com/issues/61764
<details> …
> qa: assign file system affinity for replaced MDS

- src/mds/CInode.h
- src/mds/Server.cc
- src/mds/StrayManager.cc
backport tracker: https://tracker.ceph.com/issues/59384
---
backport of https://github.com/ceph/ceph/pull/47399
parent tracker: https://tracker.ceph.com/issues/56695
<details> …
> reef: mds: wait for unlink operation to finish

- src/mds/journal.cc
backport tracker: https://tracker.ceph.com/issues/59404
---
backport of https://github.com/ceph/ceph/pull/49970
parent tracker: https://tracker.ceph.com/issues/58489
<details> …
> reef: mds: force replay sessionmap version

- qa/suites/fs/functional/tasks/client-recovery.yaml
Backport tracker: https://tracker.ceph.com/issues/61187
Backport of https://github.com/ceph/ceph/pull/51386
Parent tracker: https://tracker.ceph.com/issues/59667
<details> …
> reef: qa: ignore cluster warning when fs flag refuse_client_session is set

- qa/tasks/cephfs/test_data_scan.py
https://tracker.ceph.com/issues/59723
<details>
- `jenkins …
> reef: qa: run scrub post file system recovery

- qa/tasks/cephfs/filesystem.py
- qa/tasks/cephfs/mount.py
- qa/tasks/cephfs/test_exports.py
- src/mds/MDCache.cc
- src/mds/MDCache.h
- src/mds/Server.cc
- src/mds/Server.h
https://tracker.ceph.com/issues/61234
<details>
- `jenkins …
> reef: mds: rdlock_path_xlock_dentry supports returning auth target inode

- doc/cephfs/health-messages.rst
- qa/suites/fs/functional/tasks/client-recovery.yaml
- qa/tasks/cephfs/test_client_recovery.py
- src/common/options/mds.yaml.in
- src/mds/Beacon.cc
- src/mds/MDSRank.cc
- src/mds/Server.cc
- src/mds/Server.h
- src/messages/MMDSBeacon.h
- src/osd/OSDMap.cc
- src/osd/OSDMap.h
Fixes: https://tracker.ceph.com/issues/58023
Signed-off-by: Dhairya Parmar [dparmar@redhat.com](mailto:dparmar@redhat.com)
<details> …
> mds: do not evict clients if OSDs are laggy

- doc/radosgw/s3select.rst
Edit the "Overview" section in doc/radosgw/s3select.rst.
<details> …
> doc/radosgw: edit "Overview" in s3select.rst

- src/tools/rbd_mirror/ClusterWatcher.cc
- src/tools/rbd_mirror/InstanceReplayer.cc
- src/tools/rbd_mirror/Mirror.cc
- src/tools/rbd_mirror/ServiceDaemon.cc
> rbd-mirror: add some assorted logs

- doc/radosgw/s3select.rst
Edit the "Basic Workflow" section in doc/radosgw/s3select.rst.
(cherry picked from commit 4d2c09b683421552cfb4df7f467f2d9a6c9c7c26)
<details> …
> reef: doc/radosgw: edit "Basic Workflow" in s3select.rst

- doc/radosgw/s3select.rst
Edit the "Overview" section in doc/radosgw/s3select.rst.
(cherry picked from commit e051dd1a753614fc829f2054a69eda185f190db6)
<details> …
> reef: doc/radosgw: edit "Overview" in s3select.rst

- doc/radosgw/s3select.rst
Edit the "Overview" section in doc/radosgw/s3select.rst.
(cherry picked from commit e051dd1a753614fc829f2054a69eda185f190db6)
<details> …
> quincy: doc/radosgw: edit "Overview" in s3select.rst

- src/crimson/os/seastore/omap_manager/btree/string_kv_node_layout.h
correct setting: https://www.gnu.org/software/emacs/manual/html_node/ccmode/Customizing-Indentation.html#index-c_002dbasic_002doffset
<details>
- …
> crimson/os/seastore/omap_manager: correct editor settings

- doc/radosgw/s3select.rst
Correct several misspelling of "S3 Select". Hat tip to Anthony D'Atri, who caught this in an earlier PR.
<details>
- …
> doc/radosgw: s/s3select/S3 Select/

- doc/radosgw/s3select.rst
Correct several misspelling of "S3 Select". Hat tip to Anthony D'Atri, who caught this in an earlier PR.
(cherry picked from commit 71c327ef4f56a6ec900a8c5ea071aaf8005a60a5)
<details>
- …
> quincy: doc/radosgw: s/s3select/S3 Select/

- doc/radosgw/s3select.rst
Correct several misspelling of "S3 Select". Hat tip to Anthony D'Atri, who caught this in an earlier PR.
(cherry picked from commit 71c327ef4f56a6ec900a8c5ea071aaf8005a60a5)
<details>
- …
> reef: doc/radosgw: s/s3select/S3 Select/

- doc/radosgw/multisite.rst
Describe in greater detail the function of Zones in serving S3 objects, as requested by Alexander Patrakov here:
https://github.com/ceph/ceph/pull/49981#issuecomment-1615866374.
<details>
- `jenkins …
> doc/radosgw: refine "Zones" in multisite.rst

- src/crimson/common/operation.h
- src/crimson/os/futurized_store.h
- src/crimson/osd/osd.cc
- src/crimson/osd/osd.h
- src/crimson/osd/osd_operations/replicated_request.cc
- src/crimson/osd/pg_map.h
- src/crimson/osd/pg_shard_manager.cc
- src/crimson/osd/pg_shard_manager.h
- src/crimson/osd/shard_services.cc
- src/crimson/osd/shard_services.h
- src/crimson/osd/state.h
based on multicore-seastore : https://github.com/ceph/ceph/pull/48717
based on local_shared_foreign_ptr : https://github.com/ceph/ceph/pull/50835 
<details> …
> Crimson/osd: support multicore osd

- src/crimson/osd/osd.cc
> crimson/osd: don't ignore start_pg_operation returned future

- src/rgw/driver/rados/rgw_rados.cc
As per https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html, the only way for users to modify object metadata is to make a copy of the object and set the metadata. Hence retain old mtime for any other attr changes via `set_attrs`.
Fixes: https://tracker.ceph.com/issues/61770
Signed-off-by: Soumya Koduri<skoduri@redhat.com>
<details>
- …
> rgw/set_attrs: Do not modify mtime

- doc/radosgw/lua-scripting.rst
> doc/rgw/lua: add info uploading a script in cephadm deployment

- doc/dev/health-reports.rst
Remove seqdiag assets to determine whether the docs can be built if they are absent. (Currently they cannot be built when they are present.) If this works, then these diagrams will be replaced, probably with .png files.
<details>
- …
> doc/dev: remove seqdiag assets

- doc/dev/health-reports.rst
Remove seqdiag assets to determine whether the docs can be built if they are absent. (Currently they cannot be built when they are present.) If this works, then these diagrams will be replaced, probably with .png files.
(cherry picked from commit ce96ddd4c7da65351deaf14dc4f8b42f5148a352)
- Tests …
> reef: doc/dev: remove seqdiag assets

- doc/rados/operations/crush-map-edits.rst
> doc/rados: edit crush-map-edits (2 of x)

- doc/rados/operations/crush-map-edits.rst
(cherry picked from commit ae04debe9e2fa18c1cb8745b0573ff56576fd3b0)
<details> …
> reef: doc/rados: edit crush-map-edits (2 of x)

- doc/rados/operations/crush-map-edits.rst
(cherry picked from commit ae04debe9e2fa18c1cb8745b0573ff56576fd3b0)
<details> …
> quincy: doc/rados: edit crush-map-edits (2 of x)

- doc/radosgw/lua-scripting.rst
Signed-off-by: Yuval Lifshitz <yuvalif@yahoo.com>
(cherry picked from commit 5cec4f719581e93760c22419e701c563a8688de9)
<details> …
> reef: doc/rgw/lua: add info uploading a script in cephadm deployment

- doc/radosgw/lua-scripting.rst
Signed-off-by: Yuval Lifshitz <yuvalif@yahoo.com>
(cherry picked from commit 5cec4f719581e93760c22419e701c563a8688de9)
<details> …
> quincy: doc/rgw/lua: add info uploading a script in cephadm deployment

- src/crimson/osd/watch.cc
- src/crimson/osd/watch.h
See: https://tracker.ceph.com/issues/61504
The issue does not appear often, so having logs for the next appearance will be useful for debugging.
<details> …
> crimson/osd/watch: Add logs around Watch/Notify 

- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/dimless-binary-per-second.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/formatter.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/formatter.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/number-formatter.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/number-formatter.service.ts
Previously:
Now:
fixes: https://tracker.ceph.com/issues/59088
Signed-off-by: Pedro Gonzalez Gomez [pegonzal@redhat.com](mailto:pegonzal@redhat.com)
<details>
- `jenkins …
> mgr/dashboard: fix a bug where data would plot wrongly

- doc/radosgw/multisite.rst
Describe in greater detail the function of Zones in serving S3 objects, as requested by Alexander Patrakov here:
https://github.com/ceph/ceph/pull/49981#issuecomment-1615866374.
(cherry picked from commit 8dab6c066c4dd3699c7b7c80f7a30a0e18326bba)
<details> …
> reef: doc/radosgw: refine "Zones" in multisite.rst

- doc/radosgw/multisite.rst
Describe in greater detail the function of Zones in serving S3 objects, as requested by Alexander Patrakov here:
https://github.com/ceph/ceph/pull/49981#issuecomment-1615866374.
(cherry picked from commit 8dab6c066c4dd3699c7b7c80f7a30a0e18326bba)
<details> …
> quincy: doc/radosgw: refine "Zones" in multisite.rst

- src/vstart.sh
Backport of https://github.com/ceph/ceph/pull/49763
(cherry picked from commit bdd7dd1dec93d09e089cd4d523f47b4525b6d3d5)
<details> …
> pacific: vstart: check mgr status after starting mgr

- src/cls/2pc_queue/cls_2pc_queue.cc
- src/cls/2pc_queue/cls_2pc_queue_client.cc
- src/cls/2pc_queue/cls_2pc_queue_client.h
- src/cls/2pc_queue/cls_2pc_queue_const.h
- src/cls/2pc_queue/cls_2pc_queue_types.h
- src/cls/queue/cls_queue_ops.h
- src/rgw/driver/rados/rgw_notify.cc
- src/rgw/driver/rados/rgw_notify.h
- src/rgw/rgw_admin.cc
- src/test/rgw/bucket_notification/test_bn.py
RGW: Add observability over the persistent topics queue
<details> …
> RGW: Add observability over the persistent topics queue

- doc/foundation.rst
> doc/foundation: Updating foundation members for July 2023

- doc/radosgw/multisite.rst
Add a note about the telos of zonegroups. The information added in this commit was originally sent to ceph-users by Casey Bodley on 30 Jun 2023 in response to a question from Yixin Jin. Alexander Patrakov then suggested that Casey's response should be added to doc/radsogw/multisite.rst.
<details>
<summary>Show …
> doc/radosgw: add Zonegroup purpose

- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/dimless-binary-per-second.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/formatter.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/formatter.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/number-formatter.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/number-formatter.service.ts
backport tracker: https://tracker.ceph.com/issues/61910
---
backport of https://github.com/ceph/ceph/pull/50558
parent tracker: https://tracker.ceph.com/issues/59088
> quincy: mgr/dashboard: fix a bug where data would plot wrongly

- doc/radosgw/multisite.rst
Add a note about the telos of zonegroups. The information added in this commit was originally sent to ceph-users by Casey Bodley on 30 Jun 2023 in response to a question from Yixin Jin. Alexander Patrakov then suggested that Casey's response should be added to doc/radsogw/multisite.rst.
Co-authored-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit 5c46a1a00962918c885e434986d0f846c3ee4730) …
> reef: doc/radosgw: add Zonegroup purpose

- doc/radosgw/multisite.rst
Add a note about the telos of zonegroups. The information added in this commit was originally sent to ceph-users by Casey Bodley on 30 Jun 2023 in response to a question from Yixin Jin. Alexander Patrakov then suggested that Casey's response should be added to doc/radsogw/multisite.rst.
Co-authored-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit 5c46a1a00962918c885e434986d0f846c3ee4730) …
> quincy: doc/radosgw: add Zonegroup purpose

- doc/foundation.rst
Signed-off-by: Mike Perez <thingee@gmail.com>
(cherry picked from commit 640390906f76da4bfd66bcd8006e964d6e73c98e)
<details> …
> reef: doc/foundation: Updating foundation members for July 2023

- doc/radosgw/multisite.rst
Add revised Zonegroup policy for "multi-zonegroups". This commit includes changes that Casey Bodley made in
https://github.com/ceph/ceph/pull/52324#discussion_r1253482258 and that I have integrated into the docs only now.
<details> …
> doc/radosgw: add Zonegroup policy explanation

- src/msg/async/AsyncMessenger.cc
backport tracker: https://tracker.ceph.com/issues/59102
---
backport of https://github.com/ceph/ceph/pull/50574
parent tracker: https://tracker.ceph.com/issues/59100
> reef: msg/async: don't abort when public addrs mismatch bind addrs

- src/os/bluestore/BlueStore.cc
> os/bluestore: get rid of inclusion-in-the-middle from BlueStore.cc

- doc/radosgw/multisite.rst
Add revised Zonegroup policy for "multi-zonegroups". This commit includes changes that Casey Bodley made in
https://github.com/ceph/ceph/pull/52324#discussion_r1253482258 and that I have integrated into the docs only now.
Co-authored-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit c6400ed79b1233a2238342e4931edf341f1c7b9f)
- Component …
> quincy: doc/radosgw: add Zonegroup policy explanation

- doc/radosgw/multisite.rst
Add revised Zonegroup policy for "multi-zonegroups". This commit includes changes that Casey Bodley made in
https://github.com/ceph/ceph/pull/52324#discussion_r1253482258 and that I have integrated into the docs only now.
Co-authored-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit c6400ed79b1233a2238342e4931edf341f1c7b9f)
- Component …
> reef: doc/radosgw: add Zonegroup policy explanation

- doc/cephfs/troubleshooting.rst
Fixes: https://tracker.ceph.com/issues/61865
<details>
- …
> doc: add information on expediting MDS recovery

- doc/cephfs/troubleshooting.rst
Fixes: https://tracker.ceph.com/issues/61865
(cherry picked from commit 0a15144c584d4445bd037340f053aa64b9c13f32)
<details> …
> reef: doc: add information on expediting MDS recovery

- doc/cephfs/troubleshooting.rst
Fixes: https://tracker.ceph.com/issues/61865
(cherry picked from commit 0a15144c584d4445bd037340f053aa64b9c13f32)
<details> …
> quincy: doc: add information on expediting MDS recovery

- src/crimson/tools/perf_async_msgr.cc
- src/crimson/tools/perf_crimson_msgr.cc
~~This PR is based on https://github.com/ceph/ceph/pull/51916 for performance tests.~~
~~Starting from the commit [crimson/tools/perf_async_msgr: support configure ms_async_op_threads](https://github.com/ceph/ceph/pull/52091/commits/0ea020cb01a72358d5258bfa2104f1257fb5a8e4).~~
Update: the dependent PR has been merged. …
> crimson/tools/perf_crimson_msgr: integrate multi-core msgr with various improvements

- src/crimson/os/seastore/cache.cc
- src/crimson/os/seastore/cache.h
> crimson/os/seastore: add metrics about total invalidated transactions

- src/rgw/driver/dbstore/common/dbstore.cc
The rados backend was just changed to preserve the existing mtime on PutObjectACL in https://github.com/ceph/ceph/pull/52160. This PR addresses changes needed in dbstore backend.
Fixes: https://tracker.ceph.com/issues/61915
<details>
- `jenkins …
> rgw/dbstore: Do not update mtime for attr change

- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/dimless-binary-per-second.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/formatter.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/formatter.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/number-formatter.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/number-formatter.service.ts
backport tracker: https://tracker.ceph.com/issues/61911
---
backport of https://github.com/ceph/ceph/pull/50558
parent tracker: https://tracker.ceph.com/issues/59088
> reef: mgr/dashboard: fix a bug where data would plot wrongly 

- doc/rados/troubleshooting/troubleshooting-mon.rst
Introduce the emdash character in
docs/rados/troubleshooting/troubleshooting-mon.rst.
<details> …
> doc/rados: introduce emdash

- doc/rados/troubleshooting/troubleshooting-mon.rst
Introduce the emdash character in
docs/rados/troubleshooting/troubleshooting-mon.rst.
(cherry picked from commit a971a3a66a93ce52898f201a41a9aa13e0dd8bfc)
<details> …
> quincy: doc/rados: introduce emdash

- doc/rados/troubleshooting/troubleshooting-mon.rst
Introduce the emdash character in
docs/rados/troubleshooting/troubleshooting-mon.rst.
(cherry picked from commit a971a3a66a93ce52898f201a41a9aa13e0dd8bfc)
<details> …
> reef: doc/rados: introduce emdash

- doc/rados/operations/add-or-rm-osds.rst
Edit docs/rados/operations/add-or-rm-osds.
<details>
- …
> doc/rados: edit add-or-rm-osds (1 of x)

- doc/rados/operations/add-or-rm-osds.rst
Edit docs/rados/operations/add-or-rm-osds.
(cherry picked from commit a3ab5a7ad8a44c702089294b107d09dca3a98139)
<details> …
> reef: doc/rados: edit add-or-rm-osds (1 of x)

- doc/rados/operations/add-or-rm-osds.rst
Edit docs/rados/operations/add-or-rm-osds.
(cherry picked from commit a3ab5a7ad8a44c702089294b107d09dca3a98139)
<details> …
> quincy: doc/rados: edit add-or-rm-osds (1 of x)

- src/pybind/mgr/dashboard/ci/cephadm/start-cluster.sh
Follows: https://github.com/ceph/ceph-build/pull/2145
<details> …
> mgr/dashboard: move cephadm e2e cleanup to jenkins job config

- src/rgw/rgw_lua_background.h
- src/rgw/rgw_lua_data_filter.cc
- src/rgw/rgw_lua_request.cc
- src/rgw/rgw_lua_utils.cc
- src/rgw/rgw_lua_utils.h
- src/test/rgw/test_rgw_lua.cc
Fixes: https://tracker.ceph.com/issues/59738
<details>
</details>
> rgw/lua: fix infinite loop in case of multimap iterations

- src/crimson/osd/osd_operations/client_request.cc
- src/crimson/osd/pg_backend.cc
- src/osd/object_state_fmt.h
https://gist.github.com/rzarzynski/267661b719c414126a713826175f445c
Fixes: https://tracker.ceph.com/issues/59429
<details> …
> crimson/osd: fix ENOENT on accessing RadosGW user's index of buckets

- src/osd/OSD.h
> osd/OSD.h: cleanup unused make_*_oid methods

- do_cmake.sh
do_cmake.sh: build with correct python version on rocky os 
Fixes: https://tracker.ceph.com/issues/57945
Signed-off-by: ShimTanny <shimon.tanny@nokia.com>
<details>
- …
> do_cmake.sh: build with correct python version on Rocky

- src/os/bluestore/BlueStore.cc
backport of https://github.com/ceph/ceph/pull/49958
backport tracker: https://tracker.ceph.com/issues/59011
parent tracker: https://tracker.ceph.com/issues/58421
<details>
- …
> reef: os/bluestore: report min_alloc_size through "ceph osd metadata"

- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
- src/rgw/driver/rados/rgw_sal_rados.cc
- src/rgw/driver/rados/rgw_tools.cc
- src/rgw/driver/rados/rgw_tools.h
backport tracker: https://tracker.ceph.com/issues/61434
backport of #51497
parent tracker: https://tracker.ceph.com/issues/58692
<details>
- …
> reef: rgw: set bulk pool flag when creating data pool

- src/rgw/driver/rados/rgw_d3n_datacache.cc
backport tracker: https://tracker.ceph.com/issues/61886
backport of #52249
parent tracker: https://tracker.ceph.com/issues/61661
<details>
- …
> reef: rgw: d3n: fix valgrind reported leak related to libaio ops

- src/rgw/driver/rados/rgw_d3n_datacache.cc
- src/rgw/driver/rados/rgw_d3n_datacache.h
- src/rgw/rgw_aio.cc
- src/rgw/rgw_d3n_cacherequest.h
backport tracker: https://tracker.ceph.com/issues/61767
backport of: #51819
parent tracker: https://tracker.ceph.com/issues/59739
<details>
- …
> reef: rgw: D3N cache objects which oid contains slash

- src/osd/OSD.cc
- src/osd/scheduler/OpSchedulerItem.h
- src/test/osd/TestMClockScheduler.cc
extracted, being a separate issue, from the scrub-scheduling PR
> osd: an fmtlib formatter for OpSchedulerItem

- src/os/bluestore/BlueStore.h
> os/bluestore: specify namespace for the std::floor usage in BlueStore.h

- qa/standalone/osd/divergent-priors.sh
When creating new pool, the current code pick the divergent osd by the first pg out of pg dump pgs, that can be in "unknown" status which means the up_primary = -1 and that will fail the test. We need to wait unitl the first pg is active+clean
Fixes: https://tracker.ceph.com/issues/56034
<details>
<summary>Show …
> qa/standalone/osd/divergent-prior.sh: Divergent test 3 with pg_autoscale_mode on pick divergent osd

- qa/tasks/cephfs/caps_helper.py
- qa/tasks/cephfs/cephfs_test_case.py
- qa/tasks/cephfs/filesystem.py
- qa/tasks/cephfs/mount.py
- qa/tasks/cephfs/test_admin.py
- qa/tasks/cephfs/test_damage.py
- qa/tasks/cephfs/test_data_scan.py
- qa/tasks/cephfs/test_failover.py
- qa/tasks/cephfs/test_fragment.py
- qa/tasks/cephfs/test_fstop.py
- qa/tasks/cephfs/test_full.py
- qa/tasks/cephfs/test_journal_repair.py
- qa/tasks/cephfs/test_mantle.py
- qa/tasks/cephfs/test_mds_metrics.py
- qa/tasks/cephfs/test_mirroring.py
- qa/tasks/cephfs/test_misc.py
- qa/tasks/cephfs/test_multifs_auth.py
- qa/tasks/cephfs/test_multimds_misc.py
- qa/tasks/cephfs/test_nfs.py
- qa/tasks/cephfs/test_pool_perm.py
- qa/tasks/cephfs/test_recovery_fs.py
- qa/tasks/cephfs/test_recovery_pool.py
- qa/tasks/cephfs/test_scrub_checks.py
- qa/tasks/cephfs/test_sessionmap.py
- qa/tasks/cephfs/test_snap_schedules.py
- qa/tasks/cephfs/test_snapshots.py
- qa/tasks/cephfs/test_strays.py
- qa/tasks/cephfs/test_volumes.py
- qa/tasks/cephfs/xfstests_dev.py
> qa/cephfs: add helper methods in CephFSTestCase

- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/number-formatter.service.ts
Fixes: https://tracker.ceph.com/issues/61930
Added up to 3 decimal numbers for the Latency chart.
<details>
- `jenkins …
> mgr/dashboard: Add more decimals in latency graph

- src/crimson/os/seastore/object_data_handler.cc
Fixes: https://tracker.ceph.com/issues/61952
<details> …
> crimson/os/object_data_handler: splitting right side doesn't mean splitting only one extent

- doc/cephfs/createfs.rst
- doc/rados/operations/crush-map.rst
> doc/cephfs: add note to isolate metadata pool osds

- doc/mgr/nfs.rst
The ceph prefix was missing from the command
example.
Signed-off-by: Paul Cuzner <pcuzner@ibm.com>
(cherry picked from commit 43b5f4b4f92341803753fcd3b67132546829e362)
<details> …
> reef: docs: fix nfs cluster create syntax

- doc/mgr/nfs.rst
The ceph prefix was missing from the command
example.
Signed-off-by: Paul Cuzner <pcuzner@ibm.com>
(cherry picked from commit 43b5f4b4f92341803753fcd3b67132546829e362)
<details> …
> quincy: docs: fix nfs cluster create syntax

- src/crimson/os/seastore/segment_manager/zbd.cc
> crimson/os/seastore/zbd: zbdsegmentmanager write path fixes.

- src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/cluster.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/upgrade.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/upgrade.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/upgrade.interface.ts
Follows #52222
https://github.com/ceph/ceph/assets/71764184/6fe41a25-e29b-4758-8d9f-4d8d236ad18c
**When the cluster is already updated**
- Base layout for the Upgrade Component
- Shows the Upgrade available button when an upgrade is available
Fixes: https://tracker.ceph.com/issues/61927
- Tests …
> mgr/dashboard: cluster upgrade base UI component 

- doc/rados/configuration/ceph-conf.rst
> doc/rados: edit ceph-conf.rst

- doc/rados/operations/add-or-rm-osds.rst
Edit doc/rados/operations/add-or-rm-osds.rst (2 of x).
<details> …
> doc/rados: edit add-or-rm-osds (2 of x)

- doc/rados/operations/add-or-rm-osds.rst
Edit doc/rados/operations/add-or-rm-osds.rst (2 of x).
(cherry picked from commit d83fa5352aa556c4e559e66dd461c200cc86c709)
<details> …
> reef: doc/rados: edit add-or-rm-osds (2 of x)

- doc/rados/operations/add-or-rm-osds.rst
Edit doc/rados/operations/add-or-rm-osds.rst (2 of x).
(cherry picked from commit d83fa5352aa556c4e559e66dd461c200cc86c709)
<details> …
> quincy: doc/rados: edit add-or-rm-osds (2 of x)

- doc/rados/configuration/ceph-conf.rst
(cherry picked from commit dd8d91b0ded8be70bec3f40f499d7cf9432c9f23)
<details>
- …
> quincy: doc/rados: edit ceph-conf.rst

- doc/rados/configuration/ceph-conf.rst
(cherry picked from commit dd8d91b0ded8be70bec3f40f499d7cf9432c9f23)
<details>
- …
> reef: doc/rados: edit ceph-conf.rst

- src/pybind/mgr/dashboard/ci/cephadm/start-cluster.sh
Follows: https://github.com/ceph/ceph-build/pull/2145
(cherry picked from commit a407f0b7834585c087001059d6cec613e524538b)
<details> …
> pacific: mgr/dashboard: move cephadm e2e cleanup to jenkins job config    

- src/pybind/mgr/dashboard/ci/cephadm/start-cluster.sh
Follows: https://github.com/ceph/ceph-build/pull/2145
(cherry picked from commit a407f0b7834585c087001059d6cec613e524538b)
<details> …
> quincy: mgr/dashboard: move cephadm e2e cleanup to jenkins job config  

- src/pybind/mgr/dashboard/ci/cephadm/start-cluster.sh
Follows: https://github.com/ceph/ceph-build/pull/2145
(cherry picked from commit a407f0b7834585c087001059d6cec613e524538b)
<details> …
> reef: mgr/dashboard: move cephadm e2e cleanup to jenkins job config 

- src/rgw/driver/rados/rgw_data_sync.cc
- src/rgw/driver/rados/rgw_data_sync.h
https://tracker.ceph.com/issues/61171
<details>
- `jenkins …
> rgw: data sync fairness

- doc/cephfs/createfs.rst
- doc/rados/operations/crush-map.rst
(cherry picked from commit 4e2e61f16438dcd5eb35854091114d18b6fe9a9e)
<details> …
> reef: doc/cephfs: add note to isolate metadata pool osds

- doc/cephfs/createfs.rst
- doc/rados/operations/crush-map.rst
(cherry picked from commit 4e2e61f16438dcd5eb35854091114d18b6fe9a9e)
<details> …
> quincy: doc/cephfs: add note to isolate metadata pool osds

- src/mds/MDSAuthCaps.cc
- src/mds/MDSAuthCaps.h
- src/test/mds/TestMDSAuthCaps.cc
Fixes: https://tracker.ceph.com/issues/59388
<details>
- …
> mds: allow all types of mds caps

- doc/rados/configuration/ceph-conf.rst
> doc/rados: edit ceph-conf.rst (2 of x)

- doc/rados/configuration/ceph-conf.rst
(cherry picked from commit 69b9b20be14c7775e434b25753678533eb163a3f)
<details>
- …
> reef: doc/rados: edit ceph-conf.rst (2 of x)

- doc/rados/configuration/ceph-conf.rst
(cherry picked from commit 69b9b20be14c7775e434b25753678533eb163a3f)
<details>
- …
> quincy: doc/rados: edit ceph-conf.rst (2 of x)

- doc/mgr/rgw.rst
Multisite is typed wrong as mutlisite so fix the spelling.
<details> …
> doc/mgr/rgw.rst: fix multisite typed wrong

- doc/mgr/rgw.rst
Multisite is typed wrong as mutlisite so fix the spelling.
(cherry picked from commit 33b8fdb20329342ef91a391a99065fdb88c16b23)
<details> …
> reef: doc/mgr/rgw.rst: multisite typed wrong

- doc/mgr/rgw.rst
Multisite is typed wrong as mutlisite so fix the spelling.
(cherry picked from commit 33b8fdb20329342ef91a391a99065fdb88c16b23)
<details> …
> quincy: doc/mgr/rgw.rst: multisite typed wrong

- src/pybind/mgr/dashboard/ci/cephadm/start-cluster.sh
This mirror apparently stopped working, breaking jobs that use this script.
Signed-off-by: Zack Cerza <zack@redhat.com>
(cherry picked from commit 3f32ab0fb3a54174a8a57681243cd944056c6ffb)
<details>
- …
> pacific: mgr/dashboard: Fix broken Fedora image URL    

- doc/mgr/rgw.rst
The line begins with a prompt so I would
expect it to be a "complete" command,
similarly to the next command example,
including the `ceph` binary to run with all
the various listed arguments.
Cannot test it since I do not seem to have
any `ceph rgw` commands available and
`ceph mgr module enable rgw` also does
not work (17.2.6)...
- Tests …
> doc/mgr/rgw.rst: add missing "ceph" command in cli specification

- doc/mgr/rgw.rst
The line begins with a prompt so I would
expect it to be a "complete" command,
including the `ceph` binary to run with all
the various listed arguments.
(cherry picked from commit 37ea3e50f09be5490d7ec614798822aa6f86eaec)
<details> …
> reef: doc/mgr/rgw.rst: add missing "ceph" command in cli specification

- src/mds/MDLog.cc
Fixes: https://tracker.ceph.com/issues/61201
<details>
- …
> mds: MDLog::_recovery_thread: handle the errors gracefully

- src/crimson/common/config_proxy.h
- src/crimson/mgr/client.cc
- src/crimson/mgr/client.h
Update the MMgrOpen message to include config_bl and config_defaults_bl
Fixes: https://tracker.ceph.com/issues/61846
<details> …
> crimson/mgr: Fix config show command

- src/mon/MonClient.cc
- src/test/librados/misc.cc
> mon/MonClient: resurrect original client_mount_timeout handling

- doc/cephfs/mds-config-ref.rst
- qa/suites/fs/multiclient/tasks/cephfs_misc_tests.yaml
- qa/tasks/cephfs/test_misc.py
- src/common/options/mds.yaml.in
- src/mds/CDir.cc
- src/mds/MDCache.cc
- src/mds/MDCache.h
- src/mds/Server.cc
- src/mds/events/EMetaBlob.h
- src/mds/journal.cc
backport tracker: https://tracker.ceph.com/issues/59708
---
backport of https://github.com/ceph/ceph/pull/43184
parent tracker: https://tracker.ceph.com/issues/52280
<details> …
> reef: mds: do not take the ino which has been used

- PendingReleaseNotes
- qa/tasks/cephfs/test_data_scan.py
- src/mds/CInode.h
- src/mds/Server.cc
https://tracker.ceph.com/issues/59724
<details>
- `jenkins …
> reef: mds: allow unlink from lost+found directory

- src/mds/CDentry.cc
- src/mds/CDentry.h
- src/mds/MDCache.cc
- src/mds/MDSRank.cc
- src/mds/MDSRank.h
- src/mds/Server.cc
- src/mds/Server.h
- src/mds/StrayManager.cc
- src/messages/MClientReply.h
backport tracker: https://tracker.ceph.com/issues/61347
---
backport of https://github.com/ceph/ceph/pull/49553
parent tracker: https://tracker.ceph.com/issues/58340
<details> …
> reef: mds: wait reintegrate to finish when unlinking

- debian/cephfs-mirror.install
Fixes: https://tracker.ceph.com/issues/61694
(cherry picked from commit ea087e6f16f2ba94ae65cc4d995b7a4a7b9baf46)
<details> …
> reef: debian: install cephfs-mirror systemd unit files and man page

- src/mon/MDSMonitor.cc
backport tracker: https://tracker.ceph.com/issues/61413
---
backport of https://github.com/ceph/ceph/pull/50501
parent tracker: https://tracker.ceph.com/issues/58971
> reef: mon/MDSMonitor: do not propose on error in prepare_update

- src/osd/PeeringState.cc
Fixes: https://tracker.ceph.com/issues/61650
<details> …
> osd/PeeringState: recheck pg readability when renewing leases for no-replica pools

- ceph.spec.in
- doc/install/get-packages.rst
Currently, as the openEuler OS has been used by more and more people. Users expect Ceph to support the compilation on the openEuler.
Signed-off-by: liuqinfei [lucas.liuqinfei@huawei.com](mailto:lucas.liuqinfei@huawei.com)
<details> …
> ceph.spec.in: add support for openEuler OS

- qa/suites/rados/perf/workloads/fio_4K_rand_read.yaml
- qa/suites/rados/perf/workloads/fio_4K_rand_rw.yaml
- qa/suites/rados/perf/workloads/fio_4M_rand_read.yaml
- qa/suites/rados/perf/workloads/fio_4M_rand_rw.yaml
- qa/suites/rados/perf/workloads/fio_4M_rand_write.yaml
- qa/suites/rados/perf/workloads/radosbench_4K_rand_read.yaml
- qa/suites/rados/perf/workloads/radosbench_4K_seq_read.yaml
- qa/suites/rados/perf/workloads/radosbench_4M_rand_read.yaml
- qa/suites/rados/perf/workloads/radosbench_4M_seq_read.yaml
- qa/suites/rados/perf/workloads/radosbench_4M_write.yaml
- qa/suites/rados/perf/workloads/sample_fio.yaml
- qa/suites/rados/perf/workloads/sample_radosbench.yaml
- qa/tasks/cbt.py
- qa/tasks/cbt_performance.py
- src/test/crimson/cbt/radosbench_4K_read.yaml
Adding cbt performance collection to rados/perf suites, so we can display results and analyze them in Grafana dashboard
<details> …
> cbt perf ci

- doc/governance.rst
Update David Orman's email address in doc/governance.rst.
<details> …
> doc: governance.rst - update D Orman

- src/osd/ECTransaction.cc
- src/osd/ECTransaction.h
> osd: drop the unused ECTransaction::requires_overwrite()

- src/client/Client.cc
backport tracker: https://tracker.ceph.com/issues/61797
---
backport of https://github.com/ceph/ceph/pull/51417
parent tracker: https://tracker.ceph.com/issues/59705
<details> …
> reef: client: only wait for write MDS OPs when unmounting

- src/test/rbd_mirror/image_replayer/test_mock_BootstrapRequest.cc
- src/test/rbd_mirror/test_mock_ImageReplayer.cc
- src/tools/rbd_mirror/ImageReplayer.cc
A race between the InstanceReplayer and ImageReplayer when a primary image is deleted may prevent the non-primary image from being deleted. This occurs because the ImageReplayer::handle_bootstrap function checks if the start has been cancelled before processing other scenarios. This commit sets m_deleted_requested to true if required before checking if the start has been interrupted in ImageReplayer::handle_bootstrap(). It also cancels the BootstrapRequest if a start has been interrupted before m_bootstrap_request is set.
Fixes:  https://tracker.ceph.com/issues/61672
> rbd-mirror: fix race preventing local image deletion

- doc/governance.rst
Update David Orman's email address in doc/governance.rst.
(cherry picked from commit 46f503975e124680b29333e3972c4c937a641c10)
<details> …
> reef: doc: governance.rst - update D Orman

- doc/governance.rst
Update David Orman's email address in doc/governance.rst.
(cherry picked from commit 46f503975e124680b29333e3972c4c937a641c10)
<details> …
> quincy: doc: governance.rst - update D Orman

- doc/rados/configuration/ceph-conf.rst
> doc/rados: edit ceph-conf.rst (3 of x)

- doc/rados/configuration/ceph-conf.rst
(cherry picked from commit b1fb80ae088e4f00f207454433111f6597715ed8)
<details>
- …
> reef: doc/rados: edit ceph-conf.rst (3 of x)

- doc/rados/configuration/ceph-conf.rst
(cherry picked from commit b1fb80ae088e4f00f207454433111f6597715ed8)
<details>
- …
> quincy: doc/rados: edit ceph-conf.rst (3 of x)

- src/os/bluestore/Allocator.cc
- src/os/bluestore/Allocator.h
- src/os/bluestore/BlueStore.cc
- src/test/objectstore/allocator_replay_test.cc
And access it through admin socket
<details> …
> os/bluestore: introduce allocator state histogram

- doc/rados/configuration/ceph-conf.rst
> doc/rados: edit ceph-conf.rst (4 of x)

- doc/rados/configuration/ceph-conf.rst
(cherry picked from commit ac47899863390ff9f2adf658273e1d61760a68c2)
<details>
- …
> quincy: doc/rados: edit ceph-conf.rst (4 of x)

- doc/rados/configuration/ceph-conf.rst
(cherry picked from commit ac47899863390ff9f2adf658273e1d61760a68c2)
<details>
- …
> reef: doc/rados: edit ceph-conf.rst (4 of x)

- src/crimson/os/seastore/collection_manager/collection_flat_node.cc
- src/crimson/os/seastore/collection_manager/collection_flat_node.h
- src/crimson/os/seastore/collection_manager/flat_collection_manager.cc
Otherwise, deltas of collection nodes can't be replayed correctly, because the data of nodes is not loaded to CollectionNode::decoded
<details>
- `jenkins …
> crimson/os/seastore/collection_manager: fill CollectionNode::decoded on clean reads

- src/cls/2pc_queue/cls_2pc_queue.cc
- src/cls/2pc_queue/cls_2pc_queue_client.cc
- src/cls/2pc_queue/cls_2pc_queue_client.h
- src/cls/2pc_queue/cls_2pc_queue_ops.h
- src/rgw/driver/rados/rgw_notify.cc
- src/test/cls_2pc_queue/test_cls_2pc_queue.cc
- src/test/cls_queue/test_cls_queue.cc
- src/test/rgw/bucket_notification/test_bn.py
RGW: fix issue in observability over the persistent topics queue
when releasing entires, we don't decrease them in the urgent data
Very recent bug, introduced in https://github.com/ceph/ceph/pull/52087
<details> …
> RGW: fix issue in observability over the persistent topics queue

- src/crimson/osd/osd_operations/logmissing_request.cc
- src/crimson/osd/osd_operations/logmissing_request.h
with ReplicateRequest
Fixes: https://tracker.ceph.com/issues/61943
<details> …
> crimson/osd/osd_operations: add pipeline to LogMissingRequest to sync it

- src/rgw/driver/rados/rgw_metadata.cc
- src/rgw/driver/rados/rgw_rest_log.cc
- src/rgw/driver/rados/rgw_sync.cc
- src/rgw/rgw_admin.cc
- src/rgw/rgw_mdlog.h
- src/rgw/services/svc_mdlog.cc
- src/rgw/services/svc_mdlog.h
- src/rgw/services/svc_meta_be_sobj.cc
> rgw: Thread optional_yield through RGWMetadataLog operations

- src/rgw/driver/rados/rgw_d3n_datacache.cc
1. D3nChunkDataInfo was allocated at the beginning of the function on the heap, and was not freed in case of errors. This memory allocation has been moved to where it is being utilised.
2. cache_file file descriptor was not closed if the write to the file failed. The file close snippet has been moved to the end of the function, and is called if the write fails, or if control flow reaches the end of the function.
Reference: Coverity Defect ID 1510684
https://scan5.scan.coverity.com/reports.htm#v59282/p10114/fileInstanceId=237731707&defectInstanceId=53014748&mergedDefectId=1510684
<details>
- …
> rgw: refactor D3nDataCache::d3n_io_write to avoid resource leaks

- src/rgw/rgw_rest_swift.cc
> rgw: When finding bucket owner info, handle account name being empty

- src/rgw/driver/rados/rgw_reshard.cc
- src/rgw/rgw_sal_dbstore.cc
> rgw: Remove logically dead code

- src/rgw/driver/dbstore/common/dbstore.cc
This is backport of https://github.com/ceph/ceph/pull/52372
Fixes: https://tracker.ceph.com/issues/61946
<details>
</details>
> [reef]rgw/dbstore: Do not update mtime for attr change

- doc/rados/configuration/ceph-conf.rst
- doc/rados/configuration/mon-lookup-dns.rst
Add two links to MON DNS lookup and an anchor in the destination document.
<details> …
> doc/rados/configuration: add links to MON DNS

- doc/rbd/rbd-cloudstack.rst
Edit doc/rbd/rbd-cloudstack.rst to include support for multiple monitors.
<details>
- …
> doc/rbd/rbd-cloudstack.rst: include support for multiple monitors

- qa/suites/crimson-rados/basic/centos_8.stream.yaml
- qa/suites/crimson-rados/basic/centos_latest.yaml
- qa/suites/crimson-rados/perf/centos_8.stream.yaml
- qa/suites/crimson-rados/perf/centos_latest.yaml
- qa/suites/crimson-rados/rbd/centos_8.stream.yaml
- qa/suites/crimson-rados/rbd/centos_latest.yaml
- qa/suites/crimson-rados/thrash/centos_8.stream.yaml
- qa/suites/crimson-rados/thrash/centos_latest.yaml
```
centos_latest was moved to centos9, we only schedule centos8 Crimson builds.
Use centos8 until Crimson will support 9.
```
Verified: 
http://pulpito.front.sepia.ceph.com/matan-2023-07-24_07:17:33-crimson-rados-main-distro-crimson-smithi/
<details>
- `jenkins …
> qa/suites/crimson-rados: Use centos8 for testing

- qa/suites/fs/upgrade/featureful_client/old_client/centos_8.yaml
- qa/suites/fs/upgrade/featureful_client/old_client/centos_latest.yaml
- qa/suites/fs/upgrade/featureful_client/upgraded_client/centos_8.yaml
- qa/suites/fs/upgrade/featureful_client/upgraded_client/centos_latest.yaml
- qa/suites/fs/upgrade/nofs/centos_8.yaml
- qa/suites/fs/upgrade/nofs/centos_latest.yaml
- qa/suites/fs/upgrade/upgraded_client/centos_8.yaml
- qa/suites/fs/upgrade/upgraded_client/centos_latest.yaml
https://tracker.ceph.com/issues/62146
fs:upgrade tests use n/o/p release packages which aren't available for centos 9.stream - switch using 8.stream instead.
<details>
- …
> qa: use centos 8.stream for fs:upgrade tests

- src/mds/Locker.cc
- src/mds/Locker.h
Fixes: cf5fdcd6e2d22f35b670d3c13ae8b7c9b9d2616d
<details> …
> mds: remove dead method

- src/os/bluestore/BlueStore.cc
> os/bluestore: Some in-code documentation for Onode / blob

- doc/rados/operations/cache-tiering.rst
(cherry picked from commit 12ccd294663b03f34a44424c6006248bb7469b73)
<details> …
> reef: doc/rados: remove redundant cache tiering deprecation note

- doc/rados/configuration/ceph-conf.rst
- doc/rados/configuration/mon-lookup-dns.rst
Add two links to MON DNS lookup and an anchor in the destination document.
(cherry picked from commit 06cb5652157a53b25e8ae588f375548b1df72d2d)
<details>
- …
> reef: doc/rados/configuration: add links to MON DNS

- doc/cephfs/health-messages.rst
- qa/tasks/ceph_manager.py
- qa/tasks/ceph_test_case.py
- qa/tasks/cephfs/test_client_limits.py
- src/mds/SessionMap.cc
- src/mds/SessionMap.h
https://tracker.ceph.com/issues/59021
<details>
- `jenkins …
> quincy: mds: record and dump last tid for trimming completed requests (or flushes)

- doc/cephfs/cephfs-top.rst
- src/tools/cephfs/top/CMakeLists.txt
Fixes: https://tracker.ceph.com/issues/59482
---
<details>
</details>
> pacific: cephfs-top: check the minimum compatible python version

- PendingReleaseNotes
- qa/tasks/cephfs/test_data_scan.py
- src/mds/CInode.h
- src/mds/Server.cc
https://tracker.ceph.com/issues/59725
<details>
- `jenkins …
> pacific: mds: allow unlink from lost+found directory

- src/mds/CDentry.cc
- src/mds/CDentry.h
- src/mds/MDCache.cc
- src/mds/MDSRank.cc
- src/mds/MDSRank.h
- src/mds/Server.cc
- src/mds/Server.h
- src/mds/StrayManager.cc
- src/messages/MClientReply.h
backport tracker: https://tracker.ceph.com/issues/61346
---
backport of https://github.com/ceph/ceph/pull/49553
parent tracker: https://tracker.ceph.com/issues/58340
<details> …
> pacific: mds: wait reintegrate to finish when unlinking

- doc/cephfs/scrub.rst
- qa/tasks/cephfs/mount.py
- qa/tasks/cephfs/test_scrub_checks.py
- src/mds/MDCache.cc
- src/mds/MDCache.h
- src/mds/MDSDaemon.cc
- src/mds/MDSRank.cc
- src/mds/ScrubHeader.h
- src/mds/ScrubStack.cc
- src/mds/ScrubStack.h
- src/mds/StrayManager.cc
Backport tracker: https://tracker.ceph.com/issues/59261, https://tracker.ceph.com/issues/59264
Backport of https://github.com/ceph/ceph/pull/47649
Parent tracker: https://tracker.ceph.com/issues/53724, https://tracker.ceph.com/issues/51824
<details>
- `jenkins …
> pacific: mds: fix stray evaluation using scrub and introduce new option

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.ts
Fixes: https://tracker.ceph.com/issues/62124
<details>
- …
> mgr/dashboard: add validations to zone access/secret key in zone creation/edit form

- README.md
Correct and improve ceph/README.md.
(cherry picked from commit ad1202be685c1d35026b5ba96ba3f5cf3aefdb3a)
<details>
- `jenkins …
> reef: doc: update README.md

- src/mds/MDLog.cc
Fixes: https://tracker.ceph.com/issues/61864
<details>
- …
> mds: update mdlog perf counters during replay

- src/mds/MDCache.cc
- src/mds/MDSRank.cc
- src/mds/MDSRank.h
- src/mds/Server.cc
When forwarding the requests, the corresponding session could be already closed.
https://tracker.ceph.com/issues/60625
<details> …
> mds: skip forwarning request if the session were removed

- README.md
Add instructions directing the reader to install the "python3-routes" package. This package is required in order to launch the dashboard after the installation procedure has completed, but is not yet included in the install-deps.sh script.
<details>
- `jenkins …
> doc: update README.md install procedure

- qa/suites/fs/upgrade/featureful_client/old_client/centos_8.yaml
- qa/suites/fs/upgrade/featureful_client/old_client/centos_latest.yaml
- qa/suites/fs/upgrade/featureful_client/upgraded_client/centos_8.yaml
- qa/suites/fs/upgrade/featureful_client/upgraded_client/centos_latest.yaml
- qa/suites/fs/upgrade/nofs/centos_8.yaml
- qa/suites/fs/upgrade/nofs/centos_latest.yaml
- qa/suites/fs/upgrade/upgraded_client/centos_8.yaml
- qa/suites/fs/upgrade/upgraded_client/centos_latest.yaml
https://tracker.ceph.com/issues/62147
<details>
- `jenkins …
> reef: qa: use centos 8.stream for fs:upgrade tests

- doc/radosgw/admin.rst
The start time and end time CLI option specification is missing a space between the date and the optional time value. Also expand the text to talk about "optional time" after the date.
(cherry picked from commit dd16ad9055f134433d9bd6410cd31eb0fc918723) …
> quincy: doc/radosgw: Add missing space to date option spec in admin.rst

- doc/radosgw/admin.rst
The start time and end time CLI option specification is missing a space between the date and the optional time value. Also expand the text to talk about "optional time" after the date.
(cherry picked from commit dd16ad9055f134433d9bd6410cd31eb0fc918723) …
> reef: doc/radosgw: Add missing space to date option spec in admin.rst

- README.md
Add instructions directing the reader to install the "python3-routes" package. This package is required in order to launch the dashboard after the installation procedure has completed, but is not yet included in the install-deps.sh script.
(cherry picked from commit 0b0009bf1fb0cd54cdf0014bd724b00805a3dbd1) …
> reef: doc: update README.md install procedure

- src/pybind/mgr/dashboard/module.py
Fixes: https://tracker.ceph.com/issues/62222
<details>
- …
> mgr/dashboard: allow PUT in CORS

- doc/radosgw/admin.rst
> doc/radosgw: correct emphasis in rate limit section

- doc/radosgw/admin.rst
(cherry picked from commit 50bfbab6d9a30b3ba6ec4f4c8df9059298c28a7f)
<details> …
> reef: doc/radosgw: correct emphasis in rate limit section

- doc/radosgw/admin.rst
(cherry picked from commit 50bfbab6d9a30b3ba6ec4f4c8df9059298c28a7f)
<details> …
> quincy: doc/radosgw: correct emphasis in rate limit section

- src/pybind/mgr/dashboard/controllers/cephfs.py
- src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-directories/cephfs-directories.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
Fixes: https://tracker.ceph.com/issues/62085
<details>
- …
> mgr/dashboard: cephfs volume creation form

- src/pybind/mgr/cephadm/tests/fixtures.py
- src/pybind/mgr/cephadm/tests/test_upgrade.py
- src/pybind/mgr/crash/module.py
(cherry picked from commit d199782fb5f3c22f1cd5fda6ddf1d64f40a92726)
<details> …
> reef: mgr: fix some flake8 complaints

- doc/dev/encoding.rst
> doc: improve doc/dev/encoding.rst

- src/exporter/DaemonMetricCollector.cc
- src/test/exporter/test_exporter.cc
Follows: https://github.com/ceph/ceph/pull/52191
<details> …
> exporter: fix instance_id labeld value for rgw in exporter

- install-deps.sh
https://tracker.ceph.com/issues/62097
<details>
- `jenkins …
> build: Remove ceph-libboost* packages in install-deps

- doc/rados/configuration/msgr2.rst
Instead of saying "[...] support is not supported" change the first "support" to "operation".
<details> …
> doc/rados/configuration: Avoid repeating "support" in msgr2.rst

- doc/dev/encoding.rst
Signed-off-by: Radosław Zarzyński <rzarzyns@redhat.com>
(cherry picked from commit 83bef6668d319685923df927f32590b4e1795746)
<details>
- `jenkins …
> quincy: doc: improve doc/dev/encoding.rst

- src/test/libcephfs/CMakeLists.txt
Fixes: http://tracker.ceph.com/issues/57206
<details>
- …
> test: explicitly link to ceph-common for some libcephfs tests

- src/rgw/driver/posix/bucket_cache.h
> rgw/posixdriver: fix a lock_guard typo

- src/pybind/mgr/dashboard/controllers/cephfs.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-tabs/cephfs-tabs.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-subvolume.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-subvolume.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/cd-label/cd-label.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/cd-label/cd-label.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/copy2clipboard-button/copy2clipboard-button.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/copy2clipboard-button/copy2clipboard-button.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/usage-bar/usage-bar.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/usage-bar/usage-bar.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/cell-template.enum.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/cephfs-subvolume.model.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/octal-to-human-readable.pipe.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/octal-to-human-readable.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/path.pipe.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/path.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/pipes.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/relative-date.pipe.ts
- src/pybind/mgr/dashboard/openapi.yaml
Fixes: https://tracker.ceph.com/issues/62182
https://github.com/ceph/ceph/assets/71764184/ae27ee50-e06a-4d50-a364-17495256b996
with namespace-isolation! 
Truncated path and copy to clipboard button
<details> …
> mgr/dashboard: cephfs subvolume list

- doc/dev/release-checklists.rst
- src/ceph_release
> reef: src/ceph_release, doc: mark reef stable

- install-deps.sh
- src/pybind/mgr/cephadm/tests/fixtures.py
- src/pybind/mgr/cephadm/tests/test_upgrade.py
backport tracker: https://tracker.ceph.com/issues/62103
---
backport of https://github.com/ceph/ceph/pull/52559 + a pacific-only patch
parent tracker: https://tracker.ceph.com/issues/62097
<details>
- …
> pacific: build: Remove ceph-libboost* packages in install-deps

- install-deps.sh
backport tracker: https://tracker.ceph.com/issues/62101
---
backport of https://github.com/ceph/ceph/pull/52559
parent tracker: https://tracker.ceph.com/issues/62097
<details> …
> reef: build: Remove ceph-libboost* packages in install-deps

- doc/radosgw/s3.rst
(cherry picked from commit ab6ec66a2f82c3dfb3807d5e76d3290ff30bf613)
<details> …
> quincy: doc/rgw: several response headers are supported

- doc/radosgw/s3.rst
(cherry picked from commit ab6ec66a2f82c3dfb3807d5e76d3290ff30bf613)
<details> …
> reef: doc/rgw: several response headers are supported

- src/mon/MDSMonitor.cc
backport tracker: https://tracker.ceph.com/issues/61415
---
backport of https://github.com/ceph/ceph/pull/50501
parent tracker: https://tracker.ceph.com/issues/58971
> quincy: mon/MDSMonitor: do not propose on error in prepare_update

- src/client/Client.cc
backport tracker: https://tracker.ceph.com/issues/62044
---
backport of https://github.com/ceph/ceph/pull/51383
parent tracker: https://tracker.ceph.com/issues/59343
<details> …
> reef: client: trigger to flush the buffer when making snapshot

- src/client/Client.cc
backport tracker: https://tracker.ceph.com/issues/62041
---
backport of https://github.com/ceph/ceph/pull/51850
parent tracker: https://tracker.ceph.com/issues/61523
<details> …
> reef: client: do not send metrics until the MDS rank is ready

- src/pybind/mgr/dashboard/services/cluster.py
Consider just the data pools for average object size calculation
Fixes: https://tracker.ceph.com/issues/62318
<details> …
> mgr/dashboard: fix average object size calculation in rgw overview dashboard

- src/rgw/rgw_aio.cc
- src/rgw/rgw_d3n_cacherequest.h
- src/rgw/rgw_d3n_datacache.cc
- src/rgw/rgw_d3n_datacache.h
backport tracker: https://tracker.ceph.com/issues/61766
backport of: #51819
parent tracker: https://tracker.ceph.com/issues/59739
<details>
- …
> quincy: rgw: D3N cache objects which oid contains slash

- doc/rados/operations/add-or-rm-mons.rst
Edit the second part of doc/rados/operations/add-or-rm-mons.rst.
<details>
- `jenkins …
> doc/rados: edit operations/add-or-rm-mons (2 of x)

- doc/rados/operations/add-or-rm-mons.rst
Edit the second part of doc/rados/operations/add-or-rm-mons.rst.
(cherry picked from commit 4e790603d9e4645234d3953e88a34dd3a8a10068)
<details>
- `jenkins …
> reef: doc/rados: edit operations/add-or-rm-mons (2 of x)

- doc/rados/operations/add-or-rm-mons.rst
Edit the second part of doc/rados/operations/add-or-rm-mons.rst.
(cherry picked from commit 4e790603d9e4645234d3953e88a34dd3a8a10068)
<details>
- `jenkins …
> quincy: doc/rados: edit operations/add-or-rm-mons (2 of x)

- doc/rados/troubleshooting/troubleshooting-mon.rst
> doc/rados: edit troubleshooting-mon.rst (2 of x)

- doc/rados/troubleshooting/troubleshooting-mon.rst
Edit the second part of
(cherry picked from commit 9938955c091274313c345d680001558810e33d2d)
<details>
- …
> quincy: doc/rados: edit troubleshooting-mon.rst (2 of x)

- doc/rados/troubleshooting/troubleshooting-mon.rst
Edit the second part of
(cherry picked from commit 9938955c091274313c345d680001558810e33d2d)
<details>
- …
> reef: doc/rados: edit troubleshooting-mon.rst (2 of x)

- doc/start/documenting-ceph.rst
Update the "External Links" section of doc/start/documenting-ceph.rst.
<details>
- …
> doc/start: update linking conventions

- README.md
Add instructions directing the reader to install the "python3-routes" package. This package is required in order to launch the dashboard after the installation procedure has completed, but is not yet included in the install-deps.sh script.
(cherry picked from commit 0b0009bf1fb0cd54cdf0014bd724b00805a3dbd1) …
> quincy: doc: update README.md install procedure

- doc/start/documenting-ceph.rst
Update the "External Links" section of doc/start/documenting-ceph.rst.
(cherry picked from commit 63750514d6ef7bf9dce6aa7c622664ea4310b59e)
<details>
- …
> reef: doc/start: update linking conventions

- doc/start/documenting-ceph.rst
Update the "External Links" section of doc/start/documenting-ceph.rst.
(cherry picked from commit 63750514d6ef7bf9dce6aa7c622664ea4310b59e)
<details>
- …
> quincy: doc/start: update linking conventions

- src/pybind/mgr/dashboard/controllers/rbd.py
- src/pybind/mgr/dashboard/controllers/rbd_mirroring.py
Fixes: https://tracker.ceph.com/issues/62172
<details>
- …
> mgr/dashboard: rbd type status

- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts
Fixes: https://tracker.ceph.com/issues/62296
Signed-off-by: Debjyoti Pandit <[dpandit@redhat.com]>
Fixes: https://tracker.ceph.com/issues/62295
<details> …
> mgr/dashboard: exposed the open api documentations to details card

- doc/cephfs/scrub.rst
- qa/tasks/cephfs/mount.py
- qa/tasks/cephfs/test_scrub_checks.py
- src/mds/MDCache.cc
- src/mds/MDCache.h
- src/mds/MDSDaemon.cc
- src/mds/MDSRank.cc
- src/mds/ScrubHeader.h
- src/mds/ScrubStack.cc
- src/mds/ScrubStack.h
- src/mds/StrayManager.cc
Backport tracker: https://tracker.ceph.com/issues/59260, https://tracker.ceph.com/issues/59263
Backport of https://github.com/ceph/ceph/pull/47649
Parent tracker: https://tracker.ceph.com/issues/53724, https://tracker.ceph.com/issues/51824
<details>
- `jenkins …
> reef: mds: fix stray evaluation using scrub and introduce new option

- qa/suites/rgw/crypt/2-kms/barbican.yaml
- qa/suites/rgw/crypt/supported-random-distro$
- qa/suites/rgw/crypt/ubuntu_latest.yaml
- qa/tasks/barbican.py
> qa: fix keystone in rgw/crypt/barbican.yaml

- .github/workflows/stale.yml
> .github/workflows: pin the stale bot to the latest version

- doc/releases/index.rst
- doc/releases/reef.rst
- doc/releases/releases.yml
Add release notes for the first stable release of Ceph Reef (18.2.0).
<details>
- …
> doc: Add Reef 18.2.0 release notes

- src/common/TrackedOp.cc
backport tracker: https://tracker.ceph.com/issues/52791
---
backport of https://github.com/ceph/ceph/pull/34624
parent tracker: https://tracker.ceph.com/issues/44715
> pacific: common/TrackedOp: fix osd reboot optracker coredump

- src/script/backport-resolve-issue
Fixes: https://tracker.ceph.com/issues/61746
<details>
- …
> script/backport-resolve-issue: fix script to handle RC versions

- src/mds/MDCache.cc
This was just left and forgot to be removed.
<details>
- …
> mds: remove unused C_MDC_OpenSnapRealms

- .github/workflows/pr-triage.yml
> .github: pr-triage fix

- .github/workflows/pr-triage.yml
The link I put was broken so replacing it with the correct one:
Fixes: https://github.com/ceph/ceph/pull/52455
<details> …
> .github: pr-triage broken link fix

- src/ceph-volume/ceph_volume/devices/lvm/deactivate.py
- src/ceph-volume/ceph_volume/devices/lvm/migrate.py
- src/ceph-volume/ceph_volume/devices/lvm/prepare.py
- src/ceph-volume/ceph_volume/devices/lvm/zap.py
- src/ceph-volume/ceph_volume/devices/raw/prepare.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_deactivate.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_migrate.py
- src/ceph-volume/ceph_volume/util/encryption.py
Fixes: https://tracker.ceph.com/issues/55167
> ceph_volume: support encrypted volumes for lvm new-db/new-wal/migrate  commands

- qa/tasks/cephfs/test_volumes.py
- src/mon/FSCommands.cc
- src/mon/MDSMonitor.cc
- src/pybind/mgr/volumes/fs/fs_util.py
- src/pybind/mgr/volumes/fs/operations/volume.py
Fixes https://tracker.ceph.com/issues/61595
<details>
</details>
> mgr/volumes: create bulk data pool for new volumes

- debian/cephfs-mirror.install
Fixes: https://tracker.ceph.com/issues/61696
(cherry picked from commit ea087e6f16f2ba94ae65cc4d995b7a4a7b9baf46)
---
<details>
</details>
> pacific: debian: install cephfs-mirror systemd unit files and man page

- src/mds/mdstypes.cc
Fixes: https://tracker.ceph.com/issues/61734
(cherry picked from commit 2ee9b3af82c788ecd68d09d5bd97d80f07dae0ca)
---
<details>
</details>
> pacific: mds: display sane hex value (0x0) for empty feature bit

- doc/rados/operations/add-or-rm-mons.rst
Edit the first part of doc/rados/operations/add-or-rm-mons.rst.
(cherry picked from commit a0e638129da344cecb551b603491d94c4483099a)
<details>
- `jenkins …
> reef: doc/rados: edit operations/add-or-rm-mons (1 of x)

- doc/rados/operations/add-or-rm-mons.rst
Edit the first part of doc/rados/operations/add-or-rm-mons.rst.
(cherry picked from commit a0e638129da344cecb551b603491d94c4483099a)
<details>
- `jenkins …
> quincy: doc/rados: edit operations/add-or-rm-mons (1 of x)

- doc/cephadm/host-management.rst
A minor typo fix found while skimming through the cephadm docs: "will no remove" -> "will not remove".
Signed-off-by: John Mulligan <jmulligan@redhat.com>
(cherry picked from commit 6e22b7b2d3a4ee11dfcc752f60563aabfe0cb9b3)
<details> …
> reef: doc/cephadm: fix typo in cephadm initial crush location section

- src/client/Client.cc
backport tracker: https://tracker.ceph.com/issues/61983
---
backport of https://github.com/ceph/ceph/pull/52175
parent tracker: https://tracker.ceph.com/issues/61782
<details> …
> pacific: client: force sending cap revoke ack always

- src/client/Client.cc
- src/client/Client.h
- src/client/Dentry.h
backport tracker: https://tracker.ceph.com/issues/62012
---
backport of https://github.com/ceph/ceph/pull/40787
parent tracker: https://tracker.ceph.com/issues/49912
Conflicts:
src/client/Client.h: a minor conflict.
<details>
- …
> pacific: client: wait rename to finish

- src/pybind/mgr/dashboard/controllers/host.py
- src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/hosts.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster-review.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/host-form/host-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/host.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/host.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.html
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/plugins/ttl_cache.py
- src/pybind/mgr/dashboard/tests/test_host.py
> mgr/dashboard: host pagination

- src/client/Client.cc
backport tracker: https://tracker.ceph.com/issues/62040
---
backport of https://github.com/ceph/ceph/pull/51850
parent tracker: https://tracker.ceph.com/issues/61523
<details> …
> pacific: client: do not send metrics until the MDS rank is ready

- doc/radosgw/lua-scripting.rst
- src/common/options/rgw.yaml.in
- src/rgw/rgw_lua.cc
- src/rgw/rgw_lua_background.cc
- src/rgw/rgw_lua_data_filter.cc
- src/rgw/rgw_lua_request.cc
- src/rgw/rgw_lua_utils.cc
- src/rgw/rgw_lua_utils.h
- src/test/rgw/test_rgw_lua.cc
> rgw/lua: add configurable memory limit for the lua state

- doc/radosgw/config-ref.rst
The "Topic persistency settings" section includes convoluted and incomplete sentences so attempt to improve the language. The section lacks context so add a link to the relevant documentation about Notifications.
The "Garbage Collection settings" note includes a sentence that looks incomplete so try to improve the language.
Don't capitalize "Ops" in "RGW Ops" especially when the same sentence talks about "op queue" with lower case "o".
Also improve formatting: indentation of a note and wrap several very long lines.
(cherry picked from commit 9dd86773b39582322a5577d7cc1521486c1bdaa9)
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst …
> reef: doc/radosgw: Improve language and formatting in config-ref.rst

- doc/radosgw/config-ref.rst
The "Topic persistency settings" section includes convoluted and incomplete sentences so attempt to improve the language. The section lacks context so add a link to the relevant documentation about Notifications.
The "Garbage Collection settings" note includes a sentence that looks incomplete so try to improve the language.
Don't capitalize "Ops" in "RGW Ops" especially when the same sentence talks about "op queue" with lower case "o".
Also improve formatting: indentation of a note and wrap several very long lines.
(cherry picked from commit 9dd86773b39582322a5577d7cc1521486c1bdaa9)
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst …
> quincy: doc/radosgw: Improve language and formatting in config-ref.rst

- src/rgw/rgw_lua_background.cc
- src/rgw/rgw_lua_background.h
- src/rgw/rgw_lua_data_filter.cc
- src/rgw/rgw_lua_request.cc
- src/rgw/rgw_lua_utils.h
- src/test/rgw/test_rgw_lua.cc
Fixes: https://tracker.ceph.com/issues/58412
<details>
</details>
> rgw/lua: give tables fully qualified names

- doc/releases/index.rst
- doc/releases/reef.rst
- doc/releases/releases.yml
Add release notes for the first stable release of Ceph Reef (18.2.0).
Co-authored-by: Ville Ojamo <14869000+bluikko@users.noreply.github.com>
Co-authored-by: Laura Flores <lflores@redhat.com>
(cherry picked from commit 411017878edf7804f84e8e7e763a9a307edc92ca) …
> reef: doc: Add Reef 18.2.0 release notes

- doc/radosgw/admin.rst
Improve the grammar and readability of the "Rate Limit Management" section of doc/radosgw/admin.rst. This commit follows from https://github.com/ceph/ceph/pull/52131.
<details> …
> doc/radosgw: update rate limit management

- doc/radosgw/admin.rst
Improve the grammar and readability of the "Rate Limit Management" section of doc/radosgw/admin.rst. This commit follows from https://github.com/ceph/ceph/pull/52131.
(cherry picked from commit 51b7ff76fce00264181f7d91b8333235be9562ab)
<details>
<summary>Show …
> quincy: doc/radosgw: update rate limit management

- doc/radosgw/admin.rst
Improve the grammar and readability of the "Rate Limit Management" section of doc/radosgw/admin.rst. This commit follows from https://github.com/ceph/ceph/pull/52131.
(cherry picked from commit 51b7ff76fce00264181f7d91b8333235be9562ab)
<details>
<summary>Show …
> reef: doc/radosgw: update rate limit management

- README.md
Correct and improve ceph/README.md.
(cherry picked from commit ad1202be685c1d35026b5ba96ba3f5cf3aefdb3a)
<details>
- `jenkins …
> quincy: doc: update README.md

- src/pybind/mgr/dashboard/controllers/cephfs.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-group/cephfs-subvolume-group.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-group/cephfs-subvolume-group.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-group/cephfs-subvolume-group.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-tabs/cephfs-tabs.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-subvolume-group.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-subvolume-group.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/cephfs-subvolume-group.model.ts
- src/pybind/mgr/dashboard/openapi.yaml
Added listing for subvolume groups.
I've worked on top of #52526, so that PR should be merged first.
Fixes: https://tracker.ceph.com/issues/62168
Signed-off-by: Pedro Gonzalez Gomez <pegonzal@redhat.com>
<details> …
> mgr/dashboard: List subvolume groups

- doc/cephfs/fs-volumes.rst
Fixes: https://tracker.ceph.com/issues/62407
<details>
- …
> doc: Add a note on possible deadlock on volume deletion

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.spec.ts
Fixes: https://tracker.ceph.com/issues/62377
[Screencast from 2023-08-09 16-04-23.webm](https://github.com/ceph/ceph/assets/6695156/13f3a4f4-a756-4740-83ae-10fd8d92ea00)
<details> …
> mgr/dashboard: RGW Details card cleanup

- doc/rados/operations/monitoring-osd-pg.rst
Clear up a confusing sentence that purports to explain OSDS that are both "down" and "in".
<details> …
> doc/rados/ops: question about down and in OSDS

- qa/suites/rgw/verify/tasks/mp_reupload.yaml
- qa/workunits/rgw/test_rgw_s3_mp_reupload.py
- qa/workunits/rgw/test_rgw_s3_mp_reupload.sh
backport tracker: https://tracker.ceph.com/issues/59064
---
backport of https://github.com/ceph/ceph/pull/50667
parent tracker: https://tracker.ceph.com/issues/16767
> reef: rgw: fix multipart upload object leaks due to re-upload

- src/cephadm/cephadm.py
Now that reef is out, we should tell users
that it's the latest stable release, rather
than quincy
<details>
- `jenkins …
> cephadm: bump LATEST_STABLE_RELEASE to "reef"

- src/pybind/mgr/dashboard/controllers/host.py
- src/pybind/mgr/dashboard/controllers/rbd.py
- src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/hosts.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster-review.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/host-form/host-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/host.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/host.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.html
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/plugins/ttl_cache.py
- src/pybind/mgr/dashboard/services/rbd.py
- src/pybind/mgr/dashboard/tests/test_cache.py
- src/pybind/mgr/dashboard/tests/test_host.py
conflicts: cache invalidation commit had to be backported too.
Backport tracker: https://tracker.ceph.com/issues/62375
<details> …
> quincy: mgr/dashboard: paginate hosts

- doc/rados/operations/monitoring-osd-pg.rst
Ingest Anthony D'Atri's notes from
https://github.com/ceph/ceph/pull/50856#discussion_r1289532902 which should have been included earlier.
<details> …
> doc/rados: update monitoring-osd-pg.rst

- doc/rados/operations/monitoring-osd-pg.rst
Ingest Anthony D'Atri's notes from
https://github.com/ceph/ceph/pull/50856#discussion_r1289532902 which should have been included earlier.
(cherry picked from commit 73503d4e2665bee9c49a055c11be1ffe2db253a1)
<details> …
> quincy: doc/rados: update monitoring-osd-pg.rst

- doc/rados/operations/monitoring-osd-pg.rst
Ingest Anthony D'Atri's notes from
https://github.com/ceph/ceph/pull/50856#discussion_r1289532902 which should have been included earlier.
(cherry picked from commit 73503d4e2665bee9c49a055c11be1ffe2db253a1)
<details> …
> reef: doc/rados: update monitoring-osd-pg.rst

- doc/rados/troubleshooting/cpu-profiling.rst
Improve the language in the "oprofile" section of the RADOS Troubleshooting Guide.
<details> …
> doc/troubleshooting: edit cpu-profiling.rst

- src/crimson/os/seastore/backref/btree_backref_manager.cc
- src/crimson/os/seastore/backref/btree_backref_manager.h
- src/crimson/os/seastore/backref_manager.h
- src/crimson/os/seastore/btree/btree_range_pin.h
- src/crimson/os/seastore/btree/fixed_kv_btree.h
- src/crimson/os/seastore/cache.h
- src/crimson/os/seastore/cached_extent.h
- src/crimson/os/seastore/lba_manager.h
- src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.cc
- src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.h
- src/crimson/os/seastore/lba_manager/btree/lba_btree_node.cc
- src/crimson/os/seastore/lba_manager/btree/lba_btree_node.h
- src/crimson/os/seastore/object_data_handler.cc
- src/crimson/os/seastore/object_data_handler.h
- src/crimson/os/seastore/onode.h
- src/crimson/os/seastore/onode_manager/staged-fltree/fltree_onode_manager.cc
- src/crimson/os/seastore/onode_manager/staged-fltree/fltree_onode_manager.h
- src/crimson/os/seastore/seastore.cc
- src/crimson/os/seastore/seastore.h
- src/crimson/os/seastore/seastore_types.cc
- src/crimson/os/seastore/seastore_types.h
- src/crimson/os/seastore/transaction_manager.cc
- src/crimson/os/seastore/transaction_manager.h
- src/test/crimson/seastore/onode_tree/test_fltree_onode_manager.cc
- src/test/crimson/seastore/test_btree_lba_manager.cc
- src/test/crimson/seastore/test_object_data_handler.cc
- src/test/crimson/seastore/test_seastore.cc
> crimson/os/seastore: OP_CLONE in seastore

- src/tools/rados/rados.cc
Clarify a line in ceph/src/tools/rados/rados.cc.
<details> …
> doc: update rados.cc

- src/pybind/mgr/dashboard/controllers/cephfs.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-form/cephfs-subvolume-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-form/cephfs-subvolume-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-form/cephfs-subvolume-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-subvolume.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/usage-bar/usage-bar.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/usage-bar/usage-bar.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/checked-table-form/checked-table-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/checked-table-form/checked-table-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/cephfs-subvolume.model.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/octal-to-human-readable.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
Currently only resizing is possible. Because once the item is created with the given values, then the metadata cannot be changed later on!
https://github.com/ceph/ceph/assets/71764184/b86c8b16-7aca-40b8-9ff4-4c358591d569
<details>
- …
> mgr/dashboard: provide ability to edit cephfs subvolume 

- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
[Screencast from 2023-08-07 23-39-28.webm](https://github.com/ceph/ceph/assets/6695156/932fc27d-1a42-4811-831b-789a5f32f7ae)
Fixes: https://tracker.ceph.com/issues/62351
<details> …
> mgr/dashboard: open popup with hover for cluster status

- src/tools/rados/rados.cc
Clarify a line in ceph/src/tools/rados/rados.cc.
(cherry picked from commit 152a0fdc6858f95dadb6c86fbb2f626f4a608309)
<details> …
> quincy: doc: update rados.cc

- src/common/options/mds.yaml.in
For production workloads, these defaults rarely help. Adjust accordingly. For a steady state "find" workload, these new throttles will prevent acquiring more than ~2300 caps/second which is quite manageable with typical recall rates.
-ln(0.5) / 30 * 100k = 2310
<details> …
> mds: adjust cap acquisition throttles

- src/tools/rados/rados.cc
Clarify a line in ceph/src/tools/rados/rados.cc.
(cherry picked from commit 152a0fdc6858f95dadb6c86fbb2f626f4a608309)
<details> …
> reef: doc: update rados.cc

- doc/cephfs/fs-volumes.rst
Fixes: https://tracker.ceph.com/issues/62407
(cherry picked from commit b93b3364ae00946b9eb1fa1406be0ee22e60baac)
<details> …
> quincy: doc: Add a note on possible deadlock on volume deletion

- src/crimson/osd/osd.cc
- src/crimson/osd/osd.h
- src/crimson/osd/pg_shard_manager.cc
- src/crimson/osd/pg_shard_manager.h
Follow up #52306 https://github.com/ceph/ceph/pull/52306/commits/4ecc58d0ff372420a780c41bcaa975a25719c207
Simplify multi-shard OSD implementation.
<details> …
> crimson/osd: cleanup and drop OSD::ShardDispatcher

- src/pybind/mgr/dashboard/controllers/cephfs.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-group/cephfs-subvolume-group.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-group/cephfs-subvolume-group.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolumegroup-form/cephfs-subvolumegroup-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolumegroup-form/cephfs-subvolumegroup-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-subvolume-group.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/cephfs-subvolumegroup.model.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
Fixes: https://tracker.ceph.com/issues/62370
https://github.com/ceph/ceph/assets/106810838/c1b2bcf5-b9b1-43fa-86ce-aba32b80a3bc
<details>
- `jenkins …
> mgr/dashboard: Cephfs subvolumegroup edit

- doc/install/get-packages.rst
First off, these instructions are wrong because the file has been
renamed to cephadm.py, and will not succeed as written. Amusingly, due
to curl's default behavior (and my lack of access to a time machine) the
initial command will seem to have succeeded until the user discovers
that HTML delivered as part of the body of a 404 response is not an
executable script.
Furthermore, in preparation for Reef we updated the documentation in the
cephadm subsection to use the results of a build, rather than source
files, because reef now contains a "compiled" cephadm. Currently, the
contents of the compilation is essentially the same-old cephadm script
but that will no longer be the case in the very near future (see
https://github.com/ceph/ceph/commit/7c6a2cad96405616719b85c740aabd98558c93ac). We …
> doc: do not recommend pulling cephadm from git

- doc/rados/configuration/msgr2.rst
Instead of saying "[...] support is not supported" change the first "support" to "operation".
(cherry picked from commit df43ab5ba626c49aad6d3aca59c9737b06f8bfd8)
<details> …
> quincy: doc/rados/configuration: Avoid repeating "support" in msgr2.rst

- doc/dev/balancer-design.rst
- doc/rados/operations/upmap.rst
In https://github.com/ceph/ceph/pull/51499, some language was added that refers to the upmap balancer as the "capacity" balancer, but we don't want to insinuate that there is anything "new" that was added or changed. It should be clear that this section refers to the existing upmap balancer, which has existed for several releases.
- Tests …
> doc: clarify upmap balancer documentation

- src/cephadm/cephadm.py
cephadm: Fix extra_container_args for iSCSI
extra_container_args where only applied for rbd_target_api container and not for
tcmu-runner container.
Signed-off-by: Raimund Sacherer <rsachere@redhat.com>
<details> …
> cephadm: Fix extra_container_args for iSCSI

- src/ceph-volume/ceph_volume/devices/lvm/deactivate.py
- src/ceph-volume/ceph_volume/devices/lvm/migrate.py
- src/ceph-volume/ceph_volume/devices/lvm/prepare.py
- src/ceph-volume/ceph_volume/devices/lvm/zap.py
- src/ceph-volume/ceph_volume/devices/raw/prepare.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_deactivate.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_migrate.py
- src/ceph-volume/ceph_volume/util/encryption.py
backport of https://github.com/ceph/ceph/pull/50427
backport tracker: https://tracker.ceph.com/issues/62360
parent tracker: https://tracker.ceph.com/issues/55167
<details>
- …
> pacific: ceph_volume: support encrypted volumes for lvm new-db/new-wal/migrate commands

- qa/suites/fs/multiclient/tasks/ior-shared-file.yaml
Fixes: https://tracker.ceph.com/issues/61399
<details>
- …
> qa/cephfs: fix ior build failure

- doc/cephfs/cache-configuration.rst
- src/common/options/mds.yaml.in
The config values picks the definition from the
description. Removed the duplicate description
in the doc.
<details>
- …
> doc: Fix doc for mds cap acquisition throttle

- doc/cephfs/cache-configuration.rst
- src/common/options/mds.yaml.in
The config values picks the definition from the
description. Removed the duplicate description
in the doc.
(cherry picked from commit 65b0e45dd702fdedcf66f64dd6c5b8ae11df430b)
<details> …
> quincy: doc: Fix doc for mds cap acquisition throttle

- doc/cephfs/cache-configuration.rst
- src/common/options/mds.yaml.in
The config values picks the definition from the
description. Removed the duplicate description
in the doc.
(cherry picked from commit 65b0e45dd702fdedcf66f64dd6c5b8ae11df430b)
<details> …
> reef: doc: Fix doc for mds cap acquisition throttle

- doc/dev/balancer-design.rst
- doc/rados/operations/upmap.rst
In https://github.com/ceph/ceph/pull/51499, some language was added that refers to the upmap balancer as the "capacity" balancer, but we don't want to insinuate that there is anything "new" that was added or changed. It should be clear that this section refers to the existing upmap balancer, which has existed for several releases.
Signed-off-by: Laura Flores <lflores@redhat.com>
(cherry picked from commit d378c06a93d4e69491eaad17273b36f69a895ba8)
- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the …
> reef: doc: clarify upmap balancer documentation

- src/pybind/mgr/prometheus/module.py
Probably the greatest log ever assembled in ceph is being deprecated in this PR.
RIP 2022/11/11 - 2023/04/18
<details>
- …
> mgr/prometheus: remove jeje log

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.ts
Some of the facts that are retrieved from hosts might be empty, so instead of displayed empty cells we display a "N/A" with a hover explaining that it wasn't retrievable from the orchestrator.
Fixes: https://tracker.ceph.com/issues/61221
<details>
- `jenkins …
> mgr/dashboard: add not avaialable with unpresent host facts

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade-form/upgrade-start-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade-form/upgrade-start-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade.component.html
Fixes: https://tracker.ceph.com/issues/62457
Signed-off-by: avanthakkar <avanjohn@gmail.com>
[Screencast from 2023-08-16 16-12-57.webm](https://github.com/ceph/ceph/assets/23611106/2a782674-c8b1-4139-9e08-b0cbe4d67da4)
<details>
- …
> mgr/dashboard: support cluster upgrade even if the check for upgrade fails

- src/mds/MDCache.cc
backport tracker: https://tracker.ceph.com/issues/62193
---
backport of https://github.com/ceph/ceph/pull/51536
parent tracker: https://tracker.ceph.com/issues/61217
<details> …
> pacific: mds: do not send split_realms for CEPH_SNAP_OP_UPDATE msg

- src/client/MetaRequest.h
https://tracker.ceph.com/issues/59720
We need MetaRequest's perms.gids keeps longer than syscal if mds reboot. When mds reboot we need to rebuild MClientRequest with MetaRequest.
Fixes: https://tracker.ceph.com/issues/59514
Signed-off-by: Mer Xuanyi <xuanyi.meng@xtaotech.com>
(cherry picked from commit b88f50d1e396dc546a7a760da522ad434325bcd8) …
> pacific: client: use deep-copy when setting permission during make_request

- src/mds/CDentry.cc
- src/mds/CDentry.h
- src/mds/MDCache.cc
- src/mds/MDSRank.cc
- src/mds/MDSRank.h
- src/mds/Server.cc
- src/mds/Server.h
- src/mds/StrayManager.cc
- src/messages/MClientReply.h
backport tracker: https://tracker.ceph.com/issues/61348
---
backport of https://github.com/ceph/ceph/pull/49553
parent tracker: https://tracker.ceph.com/issues/58340
<details> …
> quincy: mds: wait reintegrate to finish when unlinking

- src/client/Client.cc
backport tracker: https://tracker.ceph.com/issues/61796
---
backport of https://github.com/ceph/ceph/pull/51417
parent tracker: https://tracker.ceph.com/issues/59705
<details> …
> quincy: client: only wait for write MDS OPs when unmounting

- src/client/Client.cc
backport tracker: https://tracker.ceph.com/issues/62042
---
backport of https://github.com/ceph/ceph/pull/51850
parent tracker: https://tracker.ceph.com/issues/61523
<details> …
> quincy: client: do not send metrics until the MDS rank is ready

- src/crimson/os/seastore/seastore.cc
> crimson/os/seastore: fix daggling reference of oid in SeaStore::Shard::stat()

- README.md
Edit the "Contributing Code" section of the "ceph/README.md" file.
<details>
- …
> doc: edit README.md - contributing code

- README.md
Edit the "Contributing Code" section of the "ceph/README.md" file.
(cherry picked from commit 9433a3e62f7453926e4be2512639f94beb887a4c)
<details>
- …
> quincy: doc: edit README.md - contributing code

- README.md
Edit the "Contributing Code" section of the "ceph/README.md" file.
(cherry picked from commit 9433a3e62f7453926e4be2512639f94beb887a4c)
<details>
- …
> reef: doc: edit README.md - contributing code

- README.md
Improve the "Building Ceph" section of ceph/README.md.
<details> …
> doc/README.md - edit "Building Ceph"

- README.md
Improve the "Building Ceph" section of ceph/README.md.
(cherry picked from commit 5bb3942365c4829f0b6580dec5d37e45f2e51e9d)
<details> …
> reef: doc/README.md - edit "Building Ceph"

- src/client/Client.cc
backport tracker: https://tracker.ceph.com/issues/62045
---
backport of https://github.com/ceph/ceph/pull/51383
parent tracker: https://tracker.ceph.com/issues/59343
<details> …
> quincy: client: trigger to flush the buffer when making snapshot

- src/tools/cephfs/shell/cephfs-shell
Fixes: https://tracker.ceph.com/issues/62074
Signed-off-by: jie teng tengjie5@asiainfo.com
<details> …
> cephfs-shell: modify and add descriptions for commands

- doc/rados/troubleshooting/cpu-profiling.rst
Improve the language in the "oprofile" section of the RADOS Troubleshooting Guide.
(cherry picked from commit 513c436aefc3c0b2e7d784c5c00e744c255a95b1)
<details> …
> quincy: doc/troubleshooting: edit cpu-profiling.rst

- doc/rados/troubleshooting/cpu-profiling.rst
Improve the language in the "oprofile" section of the RADOS Troubleshooting Guide.
(cherry picked from commit 513c436aefc3c0b2e7d784c5c00e744c255a95b1)
<details> …
> reef: doc/troubleshooting: edit cpu-profiling.rst

- src/pybind/mgr/dashboard/controllers/host.py
- src/pybind/mgr/dashboard/controllers/rbd.py
- src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/hosts.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster-review.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/host-form/host-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/host.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/host.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.html
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/plugins/ttl_cache.py
- src/pybind/mgr/dashboard/services/rbd.py
- src/pybind/mgr/dashboard/tests/test_cache.py
- src/pybind/mgr/dashboard/tests/test_host.py
Backport tracker: https://tracker.ceph.com/issues/62376
<details> …
> reef: mgr/dashboard: paginate hosts

- doc/cephfs/health-messages.rst
- qa/suites/fs/functional/tasks/client-recovery.yaml
- qa/tasks/cephfs/test_client_recovery.py
- qa/tasks/mgr/mgr_test_case.py
- src/common/options.cc
- src/mds/Beacon.cc
- src/mds/MDSRank.cc
- src/mds/Server.cc
- src/mds/Server.h
- src/messages/MMDSBeacon.h
- src/osd/OSDMap.cc
- src/osd/OSDMap.h
backport tracker: https://tracker.ceph.com/issues/61841
parent tracker: https://tracker.ceph.com/issues/58023
backport of https://github.com/ceph/ceph/pull/49971
<details> …
> pacific: do not evict clients if OSDs are laggy

- src/crimson/tools/perf_crimson_msgr.cc
In case we want to start multiple clients simultaneously if the test client hits the process-wise scaling issue.
<details> …
> crimson/tools/perf_crimson_msgr: randomize client nonce

- qa/tasks/cephfs/xfstests_dev.py
Fixes: https://tracker.ceph.com/issues/62277
<details>
- …
> qa/cephfs: switch to python3 for centos stream 9

- src/common/options/osd.yaml.in
> osd: minor changes to the descriptions of some configuration items

- src/pybind/mgr/dashboard/frontend/cypress/e2e/ui/dashboard-v3.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-time-selector/dashboard-time-selector.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-time-selector/dashboard-time-selector.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/dashboard-promqls.enum.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/dimless-binary-per-second.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/dimless-binary.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/dimless.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/styles/defaults/_bootstrap-defaults.scss
1. Fixing Prometheus Queries.
2. Fixing step count for prometheus queries(which directly impact in number of data points that will be used to provide granularity).
3. Adding Legend on the Left.
- If we have max capacity available we will show as `used capacity`
- if we have two legends we are naming them. Example `OPS` and `IPS`
- If we have single graph without max, we will show as `Recovery Throughput`
5. Fixing tension and border with for line charts to look cleaner.
6. Removing Animation to make graph movement smooth.
7. Improving the date format in legend `DD/MM/YYYY - HH:MM:SS`.
8. Adding units n legends next to number.
9. Fixing timing issue related to graph plotting which was leading to plot 0 as last value and legends were also showing 0 instead of number.
10. Adding color to the …
> mgr/dashboard: Adding legends and fixing queries

- src/test/rbd_mirror/image_replayer/test_mock_BootstrapRequest.cc
- src/test/rbd_mirror/test_mock_ImageReplayer.cc
- src/tools/rbd_mirror/ImageReplayer.cc
backport tracker: https://tracker.ceph.com/issues/62113
---
backport of https://github.com/ceph/ceph/pull/52057
parent tracker: https://tracker.ceph.com/issues/61672
> reef: rbd-mirror: fix race preventing local image deletion

- src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.cc
> crimson/os/seastore/omap_manager: fix the entry leak issue in BtreeOMapManager::omap_list()

- qa/cephfs/overrides/ignorelist_health.yaml
Fixes: http://tracker.ceph.com/issues/62508
<details>
- …
> qa: add `POOL_APP_NOT_ENABLED` to ignorelist for cephfs tests

- src/pybind/mgr/dashboard/frontend/cypress/e2e/ui/dashboard-v3.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-time-selector/dashboard-time-selector.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-time-selector/dashboard-time-selector.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/dashboard-promqls.enum.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/dimless-binary-per-second.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/dimless-binary.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/dimless.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/styles/defaults/_bootstrap-defaults.scss
Fixes: https://tracker.ceph.com/issues/62367
Signed-off-by: cloudbehl <cloudbehl@gmail.com>
(cherry picked from commit 9fcc176162d39e5797042de301ffa0dea7f0254c)
<details>
- …
> reef: Overview graph improvements

- doc/cephfs/troubleshooting.rst
> doc: correct option name

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.html
- src/pybind/mgr/dashboard/services/cluster.py
1. Dashboard: Calling FSID as Cluster ID
2. Filesystem: Calling it Create Filesystem instead of Create Volume
3. Object Gateway dashboard: Calling Daemon as Gateways and fixing the logic of object calculation.
[Screencast from 2023-08-09 12-44-06.webm](https://github.com/ceph/ceph/assets/6695156/a7f12a8c-3e7c-4823-8226-f71c7455bc03)
Fixes: https://tracker.ceph.com/issues/62365
- …
> mgr/dashboard: Added some minor usability improvements

- doc/cephadm/services/mds.rst
- doc/cephfs/fs-volumes.rst
> doc: expand and consolidate mds placement

- src/test/libcephfs/deleg.cc
MDSs will allow multiple clients to do r/w at the same time and the filelock will be in LOCK_MIX state. So the open() in a second mounter in the open_breaker_func() thread won't guarantee that after it exiting the delegation in the mounter in main thread has already timedout.
Fixes: https://tracker.ceph.com/issues/62245 …
> libcephfs/deleg: Wait for the delegation to be timedout

- doc/cephadm/services/mds.rst
- doc/cephfs/fs-volumes.rst
> reef: doc: expand and consolidate mds placement

- src/pybind/mgr/dashboard/frontend/cypress/e2e/orchestrator/01-hosts.e2e-spec.ts
These host e2e test were failing, since we are already checking this on the Dashboard Cephadm e2e tests we can get rid of these ones.
Fixes: https://tracker.ceph.com/issues/62491
<details>
- `jenkins …
> mgr/dashboard: remove unnecessary failing hosts e2e

- doc/cephadm/install.rst
doc/cephadm: 
update cephadm reef version in install.rst
<details> …
> doc/cephadm: update cephadm reef version

- doc/cephadm/install.rst
(cherry picked from commit d9888a4223632e0e3f862b658699df8735ebda26)
<details> …
> reef: doc/cephadm: update cephadm reef version

- doc/cephadm/services/mgr.rst
Improve the grammar in the first sentence of
doc/cephadm/services/mgr.rst. This is a small change, but I could not resist.
<details> …
> doc/cephadm: edit sentence in mgr.rst

- doc/cephadm/services/mgr.rst
Improve the grammar in the first sentence of
doc/cephadm/services/mgr.rst. This is a small change, but I could not resist.
(cherry picked from commit 3b8877481a8de0a92a7b68a775915eb079744f23)
<details>
- `jenkins …
> reef: doc/cephadm: edit sentence in mgr.rst

- doc/cephadm/services/mgr.rst
Improve the grammar in the first sentence of
doc/cephadm/services/mgr.rst. This is a small change, but I could not resist.
(cherry picked from commit 3b8877481a8de0a92a7b68a775915eb079744f23)
<details>
- `jenkins …
> quincy: doc/cephadm: edit sentence in mgr.rst

- src/crimson/osd/pg.cc
> crimson/osd/pg: check if backfill_state exists when judging objects'

- doc/cephadm/services/mds.rst
- doc/cephfs/fs-volumes.rst
(cherry picked from commit 3a5f9dc37a72a83046a5749e42182322799e0306)
<details> …
> quincy: doc: expand and consolidate mds placement

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.html
- src/pybind/mgr/dashboard/services/cluster.py
backport tracker: https://tracker.ceph.com/issues/62365
Backport of https://github.com/ceph/ceph/pull/52895
Parent tracker: https://tracker.ceph.com/issues/62365
<details> …
> reef: mgr/dashboard: minor usability improvements  

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-list/rbd-snapshot-actions.model.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-list/rbd-snapshot-list.component.spec.ts
Fixes: https://tracker.ceph.com/issues/62498
Signed-off-by: avanthakkar <avanjohn@gmail.com>
<details> …
> mgr/dashboard: disable protect if layering is not enabled on the image

- src/pybind/mgr/dashboard/controllers/rbd_mirroring.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/mirroring/image-list/image-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/mirroring/image-list/image-list.component.ts
> mgr/dashboard: n/a entries behind primary snapshot mode

- doc/start/os-recommendations.rst
Improve the grammar in one sentence of the "Platforms" section of doc/start/os-recommendations.rst. Improving that grammar involved splitting the sentence into two sentences, but that's life.
<details> …
> doc/start: edit os-recommendations.rst

- doc/start/os-recommendations.rst
Improve the grammar in one sentence of the "Platforms" section of doc/start/os-recommendations.rst. Improving that grammar involved splitting the sentence into two sentences, but that's life. Update: Anthony substantially rewrote this, so credit for this should rightly go to him.
(cherry picked from commit e19b9cea62c56cbd73049957d69d5aac16a97c08)
- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for …
> reef: doc/start: edit os-recommendations.rst

- doc/cephfs/troubleshooting.rst
> doc: reformat so note is not part of code

- src/osd/PGLog.cc
> osd/PGLog: return a ready future when found missing objects

- src/crimson/osd/object_context_loader.cc
- src/crimson/osd/object_context_loader.h
- src/crimson/osd/osd_operations/snaptrim_event.cc
- src/crimson/osd/osd_operations/snaptrim_event.h
- src/crimson/osd/pg.h
Fixes: https://tracker.ceph.com/issues/61825
<details> …
> crimson/osd/object_context: consider clones found as long as they're in SnapSet::clones

- doc/cephadm/install.rst
Add a note instructing the reader to have ssh running before the "cephadm bootstrap" command is run.
<details>
- …
> doc/cephadm: add ssh note to install.rst

- src/pybind/mgr/dashboard/services/auth.py
Fixes: https://tracker.ceph.com/issues/62612
<details>
- …
> mgr/dashboard: set CORS header for unauthorized access

- src/stop.sh
kill cephfs-mirror/rbd-mirror daemon during vstart cluster stop, instead of having multiple mirror daemons on restart.
<details> …
> stop.sh: kill cephfs-mirror, rbd-mirror

- src/pybind/mgr/dashboard/frontend/src/app/shared/components/usage-bar/usage-bar.component.html
Dynamically changing the text color depending on the percentage value.
Side effect of a recent change https://github.com/ceph/ceph/pull/52915/files#diff-747a9554e053df3b4d3fcc144bfb5c002654dc0fd5aa59b0ec18db56d85d5b28R29
**BEFORE**
**AFTER**
Fixes: https://tracker.ceph.com/issues/62614
<details>
<summary>Show …
> mgr/dashboard: fix progress bar color visibility

- PendingReleaseNotes
- doc/cephfs/snap-schedule.rst
- qa/tasks/cephfs/test_snap_schedules.py
- src/pybind/mgr/snap_schedule/module.py
Fixes: https://tracker.ceph.com/issues/62218
<details>
- `jenkins …
> mgr/snap_schedule: make fs argument mandatory if more than one filesystem exists

- doc/cephadm/install.rst
Edit the English in the "Adding Hosts" section of
doc/cephadm/install.rst.
<details>
- …
> doc/cephadm: edit "Adding Hosts" in install.rst

- src/pybind/mgr/dashboard/controllers/_crud.py
- src/pybind/mgr/dashboard/controllers/ceph_users.py
- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/users.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/users.po.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/roles.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/roles.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
- src/pybind/mgr/dashboard/openapi.yaml
backport tracker: https://tracker.ceph.com/issues/61492
---
backport of https://github.com/ceph/ceph/pull/51748
parent tracker: https://tracker.ceph.com/issues/61421
> quincy: mgr/dashboard: fix the rgw roles page 

- src/pybind/mgr/dashboard/run-frontend-e2e-tests.sh
Fixes: https://tracker.ceph.com/issues/61703
<details>
- …
> mgr/dashboard: cleanup rbd-mirror process in dashboard e2e 

- doc/cephadm/install.rst
Edit the English in the "Adding Hosts" section of
doc/cephadm/install.rst.
(cherry picked from commit f0df9e1ea95362b28ca516e3a2efaab6365de5ea)
<details>
- …
> reef: doc/cephadm: edit "Adding Hosts" in install.rst

- doc/cephadm/install.rst
Edit the English in the "Adding Hosts" section of
doc/cephadm/install.rst.
(cherry picked from commit f0df9e1ea95362b28ca516e3a2efaab6365de5ea)
<details>
- …
> quincy: doc/cephadm: edit "Adding Hosts" in install.rst

- doc/cephadm/install.rst
Add a note instructing the reader to have ssh running before the "cephadm bootstrap" command is run.
(cherry picked from commit f10781a281ef6a00a69d45dd6b78f29fd219f049)
<details> …
> reef: doc/cephadm: add ssh note to install.rst

- src/client/Client.cc
- src/mds/FSMap.cc
- src/mds/FSMap.h
- src/mds/MDSMap.cc
- src/mds/MDSMap.h
- src/mon/AuthMonitor.cc
- src/mon/FSCommands.cc
- src/mon/MDSMonitor.cc
- src/mon/MDSMonitor.h
- src/mon/PaxosFSMap.h
- src/tools/cephfs/DataScan.cc
- src/tools/cephfs/Dumper.cc
- src/tools/cephfs/JournalTool.cc
- src/tools/cephfs/MetaTool.cc
- src/tools/cephfs/Resetter.cc
- src/tools/cephfs/RoleSelector.cc
- src/tools/cephfs/TableTool.cc
- src/tools/cephfs_mirror/ClusterWatcher.cc
There's zero reason to complicate the interface with shared_ptr<Filesystem> when a Filesystem's lifetime is tied to the FSMap.
<details>
- `jenkins …
> mds: rework FSMap to avoid shared_ptrs

- doc/releases/pacific.rst
Address review comments that remained outstanding in https://github.com/ceph/ceph/pull/53107:
- CephFS capitalization
- missing PR in the list of changes
<details>
- …
> doc: 16.2.14 release notes follow-up

- README.md
Improve the English in the section "Running a test cluster in the ceph/README.md file.
<details> …
> doc/README.md - improve "Running a test cluster"

- README.md
Improve the English in the section "Running a test cluster in the ceph/README.md file.
(cherry picked from commit 420ecc7addaad1969cb634289c2399ea38ea9a90)
<details> …
> quincy: doc/README.md - improve "Running a test cluster"

- README.md
Improve the English in the section "Running a test cluster in the ceph/README.md file.
(cherry picked from commit 420ecc7addaad1969cb634289c2399ea38ea9a90)
<details> …
> reef: doc/README.md - improve "Running a test cluster"

- qa/config/crimson_qa_overrides.yaml
Fixes: https://tracker.ceph.com/issues/62595
<details>
- …
> qa/config/crimson_qa_overrides: ignore POOL_APP_NOT_ENABLED

- doc/man/8/radosgw-admin.rst
Improve wording, capitalization, indentation in the radosgw-admin man page.
<details> …
> doc/man/8: improve radosgw-admin.rst

- doc/man/8/radosgw-admin.rst
(cherry picked from commit d986537f9b06e7e848b9624718a2eda21bb54f70)
<details> …
> quincy: doc/man/8: improve radosgw-admin.rst

- doc/man/8/radosgw-admin.rst
(cherry picked from commit d986537f9b06e7e848b9624718a2eda21bb54f70)
<details> …
> reef: doc/man/8: improve radosgw-admin.rst

- qa/workunits/rbd/rbd_mirror_helpers.sh
- qa/workunits/rbd/rbd_mirror_journal.sh
- qa/workunits/rbd/rbd_mirror_snapshot.sh
- src/librbd/mirror/snapshot/CreatePrimaryRequest.cc
- src/librbd/operation/SnapshotRemoveRequest.cc
- src/test/librbd/mirror/snapshot/test_mock_CreatePrimaryRequest.cc
- src/test/librbd/operation/test_mock_SnapshotRemoveRequest.cc
> librbd: make CreatePrimaryRequest remove any unlinked mirror snapshots

- src/test/objectstore/allocsim/variable_load.py
The tool is dedicated to create highly variable workloads. The intended audience is
1) scraper testing - tool to sniff on OSD ops
2) CoDel testing - bandwidth/latency optimization algorithm in BS Initial commit.
<details>
- `jenkins …
> tools: Add generator of variable workload

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-list/rbd-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-list/rbd-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-list/rbd-list.component.ts
Fixes: https://tracker.ceph.com/issues/62697
<details>
- …
> mgr/dashboard: remove used and total used columns in favor of usage bar

- src/pybind/mgr/dashboard/frontend/src/app/core/auth/login-password-form/login-password-form.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/core/auth/user-password-form/user-password-form.component.scss
a green tick is showing to the field where we enter the old password in login password change form. It starts showing green tick as soon as we start typing on it. Removing that because its misleads the user.
Fixes: https://tracker.ceph.com/issues/62644
<details> …
> mgr/dashboard: remove green tick on old password field

- PendingReleaseNotes
- doc/cephfs/standby.rst
- qa/tasks/cephfs/filesystem.py
- qa/tasks/cephfs/test_failover.py
- qa/tasks/mgr/dashboard/test_health.py
- src/include/ceph_fs.h
- src/mds/FSMap.cc
- src/mds/MDSMap.cc
- src/mds/MDSMap.h
- src/mon/FSCommands.cc
- src/mon/MonCommands.h
Fixes: https://tracker.ceph.com/issues/61599
<details>
- …
> mds: optionally forbid to use standby for another fs as last resort

- doc/man/8/radosgw-admin.rst
Edit the text in the "bucket radoslist" entry.
<details>
- …
> doc/man: radosgw-admin.rst typo

- doc/rados/operations/placement-groups.rst
- doc/rados/operations/pools.rst
Add a link in pools.rst to the section in placement-groups.rst describing the commands used to manage pools that are flagged "--bulk".
<details>
- …
> doc/rados: add bulk flag to pools.rst

- doc/man/8/radosgw-admin.rst
Edit the text in the "bucket radoslist" entry.
(cherry picked from commit fb808732e8c8f9b64a443aa3ea30a677b1347be3)
<details> …
> reef: doc/man: radosgw-admin.rst typo

- doc/man/8/radosgw-admin.rst
Edit the text in the "bucket radoslist" entry.
(cherry picked from commit fb808732e8c8f9b64a443aa3ea30a677b1347be3)
<details> …
> quincy: doc/man: radosgw-admin.rst typo

- doc/rados/operations/placement-groups.rst
- doc/rados/operations/pools.rst
Add a link in pools.rst to the section in placement-groups.rst describing the commands used to manage pools that are flagged "--bulk".
(cherry picked from commit 31f1224f611b560af7c42131ef38f0aa6dcdffb3)
<details>
- …
> reef: doc/rados: add bulk flag to pools.rst

- src/osd/PeeringState.cc
> osd: fix typo in WaitDeleteReserved's name

- src/osd/ECTransaction.cc
- src/osd/ECTransaction.h
> osd: make encode_and_write() in ECTransaction.cc static 

- src/osd/PeeringState.cc
PeeringState::choose_async_recovery_ec may remove OSDs from the acting set as long as PeeringState::recoverable evaluates to true. Prior to 90022b35 (merge of PR 17619), the condition was
PeeringState::recoverable_and_ge_min_size, which behaved as the name indicates. 7cb818a85 weakened the condition in
PeeringState::recoverable_and_ge_min_size to only check min_size if !cct->_conf.get_val<bool>("osd_allow_recovery_below_min_size") (name was changed to PeeringState::recoverable in a subsequent commit in that PR e4c8bee88). PeeringState::recoverable_and_ge_min_size had (and has) two callers: choose_acting and choose_async_recovery_ec. For choose_acting, this change is correct. However, for choose_async_recovery_ec, we don't want to reduce the acting set size below min_size as it would …
> osd: ensure async recovery does not drop a pg below min_size

- src/mds/Server.cc
Fixes: https://tracker.ceph.com/issues/62057
<details>
- …
> mds: add event for batching getattr/lookup

- src/mds/Locker.cc
> mds: remove stray space

- src/os/bluestore/bluestore_tool.cc
db/wal
backport of https://github.com/ceph/ceph/pull/52193
backport tracker: https://tracker.ceph.com/issues/62069
parent tracker: https://tracker.ceph.com/issues/55261
(cherry picked from commit 9c3a8980bab0dd98185b0bb751c0dac09a9ab79e) …
> reef: os/bluestore: don't require bluestore_db_block_size when attaching new

- qa/suites/fs/multiclient/tasks/ior-shared-file.yaml
Original PR is PR #52416. But it was merged accidentally.
Fixes: https://tracker.ceph.com/issues/61399
<details>
- …
> qa/cephfs: fix ior project build failure

- src/test/cls_2pc_queue/test_cls_2pc_queue.cc
this is happening when all producers are finished before the consumer starts.
Fixes: https://tracker.ceph.com/issues/62449
<details>
</details>
> test/cls_2pc_queue: fix race condition with producers

- src/cls/rgw/cls_rgw.cc
After convert plain entry to versioned, the converted entry epoch is 1.
Setting this ensures that there is only one null version.
Fixes: https://tracker.ceph.com/issues/62013
Signed-off-by: rui ma <marui1@chinatelecom.cn>
Signed-off-by: zhuo li <lizhuo@chinatelecom.cn>
<details> …
> rgw: fix 2 null versionID after convert_plain_entry_to_versioned

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.scss
Toplology view in multi-site dashboard displaying blank table regarding realm, zonegroup and zones in chrome browser
Fixes: https://tracker.ceph.com/issues/62677
<details> …
> mgr/dashboard: rgw multisite topology view shows blank table for multisite entities

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
Inventory(Buckets and users) data is wrong when you have buckets across multiple daemons.
Fixes: https://tracker.ceph.com/issues/62565
<details>
- …
> mgr/dashboard: Object gateway inventory card incorrect Buckets and user count

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.ts
- src/pybind/mgr/dashboard/services/rgw_client.py
Fixes: https://tracker.ceph.com/issues/62665
<details>
- …
> mgr/dashboard: Object gateway sync status cards keeps loading when multisite is not configured

- src/os/bluestore/BtreeAllocator.cc
- src/test/objectstore/Allocator_bench.cc
- src/test/objectstore/Allocator_test.cc
Fixes: https://tracker.ceph.com/issues/61949
<details>
- `jenkins …
> os/bluestore: fix btree allocator

- src/ceph_mon.cc
- src/common/Finisher.cc
- src/common/Finisher.h
- src/mon/MonitorDBStore.h
Fixes: https://tracker.ceph.com/issues/61820
<details>
- …
> ceph_mon: Fix MonitorDBStore usage

- doc/rados/configuration/mon-config-ref.rst
Edit the English in the section "Background" in
doc/rados/configuration/mon-config-ref.rst.
<details> …
> doc/configuration: edit "bg" in mon-config-ref.rst

- README.md
The "rbd" pool has not been created by default since Luminous. This commit removes a command that assumed the existence of the "rbd" pool.
<details> …
> doc: update test cluster commands in README.md

- doc/rados/configuration/mon-config-ref.rst
Edit the English in the section "Background" in
doc/rados/configuration/mon-config-ref.rst.
(cherry picked from commit d009f0757cb34cf1cc9ac107905235d1b2ac65cd)
<details>
- `jenkins …
> quincy: doc/configuration: edit "bg" in mon-config-ref.rst

- doc/rados/configuration/mon-config-ref.rst
Edit the English in the section "Background" in
doc/rados/configuration/mon-config-ref.rst.
(cherry picked from commit d009f0757cb34cf1cc9ac107905235d1b2ac65cd)
<details>
- `jenkins …
> reef: doc/configuration: edit "bg" in mon-config-ref.rst

- qa/cephfs/overrides/ignorelist_health.yaml
Partially reverts ceph/ceph#53037
> qa/cephfs: add back POOL_APP_NOT_ENABLED to ignorelist (partial revert)

- README.md
The "rbd" pool has not been created by default since Luminous. This commit removes a command that assumed the existence of the "rbd" pool.
(cherry picked from commit 8d606003af59cac2cd8f6f9ca02e6506bde705f0)
<details> …
> reef: doc: update test cluster commands in README.md

- doc/architecture.rst
Edit doc/architecture.rst up to "Cluster Map", but not including "Cluster Map".
<details> …
> doc/architecture.rst - edit up to "Cluster Map"

- doc/architecture.rst
Edit doc/architecture.rst up to "Cluster Map", but not including "Cluster Map".
(cherry picked from commit b3538f8ade14014f6d34c7d6271cb37a0fdd8bb5)
<details> …
> reef: doc/architecture.rst - edit up to "Cluster Map"

- doc/architecture.rst
Edit doc/architecture.rst up to "Cluster Map", but not including "Cluster Map".
(cherry picked from commit b3538f8ade14014f6d34c7d6271cb37a0fdd8bb5)
<details> …
> quincy: doc/architecture.rst - edit up to "Cluster Map"

- doc/architecture.rst
Change the sentence structure of a sentence because the verb "experience" looked like the abstract noun "experience" when I read it with fresh eyes. I chose the perhaps TESOL-unfriendly verb "incur", but I believe  it is right.
<details> …
> doc/architecture.rst - edit a sentence

- doc/architecture.rst
Change the sentence structure of a sentence because the verb "experience" looked like the abstract noun "experience" when I read it with fresh eyes. I chose the perhaps TESOL-unfriendly verb "incur", but I believe it is right.
(cherry picked from commit 436fbf7a3e0960ebb51a0dc66d9c1d405bf6875f)
- …
> quincy: doc/architecture.rst - edit a sentence

- doc/architecture.rst
Change the sentence structure of a sentence because the verb "experience" looked like the abstract noun "experience" when I read it with fresh eyes. I chose the perhaps TESOL-unfriendly verb "incur", but I believe it is right.
(cherry picked from commit 436fbf7a3e0960ebb51a0dc66d9c1d405bf6875f)
- …
> reef: doc/architecture.rst - edit a sentence

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-form/cephfs-subvolume-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolumegroup-form/cephfs-subvolumegroup-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-modal/form-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/directives/dimless-binary.directive.ts
**BEFORE**
https://github.com/ceph/ceph/assets/71764184/35ff4d95-64a6-4b69-9a2f-886c7543110f
**AFTER**
https://github.com/ceph/ceph/assets/71764184/266cd612-0289-4322-9d07-1ce5f0370cfc
Fixes: https://tracker.ceph.com/issues/62655
<details> …
> mgr/dashboard: add validator for size field in the forms 

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-feature.interface.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.ts
Fixes: https://tracker.ceph.com/issues/62502
Signed-off-by: avanthakkar <avanjohn@gmail.com>
[Screencast from 2023-08-31 12-10-31.webm](https://github.com/ceph/ceph/assets/23611106/67825440-4969-45d5-8429-60f4373954d8)
Deep-flatten helper:
Layering helper:
<details> …
> mgr/dashboard: images -> edit -> disable checkboxes for layering and deef-flatten

- src/pybind/mgr/dashboard/controllers/cephfs.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-form/cephfs-subvolume-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-form/cephfs-subvolume-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-subvolume.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-subvolume.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
The PR adds subvolume groups into the subvolume tabs in order to select the subvolumes from the appropiate group.
Also adds the capabilities to manage the subvolume groups of the subvolume in the different actions, create, edit, remove.
[screen-capture (32).webm](https://github.com/ceph/ceph/assets/106810838/0234137c-a882-4dc9-9572-81877898fac4)
Fixes: https://tracker.ceph.com/issues/62675
- …
> mgr/dashboard: display the groups in cephfs subvolume tab

- doc/architecture.rst
- doc/glossary.rst
Link to the "Ceph Clients" section of doc/architecture.rst from the "Ceph Clients" entry in the glossary. A glossary entry should be a short summary of the topic with which it deals, and it should direct the reader to further and more detailed reading if the reader is interested. This does that.
<details> …
> doc/glossary: link to "ceph clients" from entry

- doc/radosgw/notifications.rst
- src/rgw/rgw_admin.cc
Add opttion to filter notification topic lists based on uid.
<details> …
> rgw/notification: Filter topic list based on uid

- src/rgw/driver/rados/rgw_bucket.cc
Publish notification topics subscribed by bucket in the bucket stats output
As part of notification discussion (https://gist.github.com/yuvalif/15af72d2abf9493cc83f56b94ae5f9cb), it was decided to publish notificaiton information on bucket stats.
<details>
- …
> rgw/notification: Publish notification information in bucket stats

- src/rgw/rgw_rest_pubsub.cc
testing instructions:
https://gist.github.com/yuvalif/60063dc67d981b387b382ff0f7f88d91
Fixes: https://tracker.ceph.com/issues/62784
<details>
</details>
> rgw/notifications: allow cross tenant notification management

- doc/cephfs/administration.rst
We write CephFS commands incompletely in docs. For example, "ceph tell
mds.a help" is simply written as "tell mds.a help". This might confuse
the reader and it won't harm to write the command in full.
Fixes: https://tracker.ceph.com/issues/62791
<details>
- …
> doc/cephfs: write cephfs commands fully in docs

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
backport tracker: https://tracker.ceph.com/issues/62767
---
backport of https://github.com/ceph/ceph/pull/53239
parent tracker: https://tracker.ceph.com/issues/62565
> reef: mgr/dashboard: Object gateway inventory card incorrect Buckets and user count

- src/crimson/os/seastore/object_data_handler.cc
- src/test/crimson/seastore/onode_tree/test_fltree_onode_manager.cc
- src/test/crimson/seastore/onode_tree/test_staged_fltree.cc
- src/test/crimson/seastore/test_collection_manager.cc
- src/test/crimson/seastore/test_object_data_handler.cc
- src/test/crimson/seastore/test_omap_manager.cc
- src/test/crimson/seastore/test_seastore.cc
- src/test/crimson/seastore/test_transaction_manager.cc
- src/test/crimson/seastore/transaction_manager_test_state.h
> test/crimson/seastore/rbm: add sub-tests regarding RBM to the existing tests

- doc/glossary.rst
- doc/rados/operations/crush-map.rst
Add "Primary Affinity" to the glossary and link to the information in the RADOS documentation that (more or less) explains it.
<details>
- `jenkins …
> doc/glossary: add "primary affinity" to glossary

- doc/rados/operations/erasure-code-profile.rst
Add warning for "osd erasure-code-profile rm" section under rados/operations.
Signed-off-by: Alvin Owyong <70066269+alvinowyong@users.noreply.github.com>
(cherry picked from commit f944fa8ddb022656dac3f1faebe81a7de37380f6)
<details> …
> doc: Add warning on manual CRUSH rule removal

- doc/rados/operations/erasure-code-profile.rst
Add warning for "osd erasure-code-profile rm" section under rados/operations.
Signed-off-by: Alvin Owyong <70066269+alvinowyong@users.noreply.github.com>
(cherry picked from commit f944fa8ddb022656dac3f1faebe81a7de37380f6)
<details> …
> quincy: doc: Add warning on manual CRUSH rule removal

- doc/glossary.rst
- doc/rados/operations/crush-map.rst
Add "Primary Affinity" to the glossary and link to the information in the RADOS documentation that (more or less) explains it.
(cherry picked from commit f3a3f10e9ce0bf96d5eba25a786cdd254340878b)
<details>
- `jenkins …
> reef: doc/glossary: add "primary affinity" to glossary

- doc/glossary.rst
- doc/rados/operations/crush-map.rst
Add "Primary Affinity" to the glossary and link to the information in the RADOS documentation that (more or less) explains it.
(cherry picked from commit f3a3f10e9ce0bf96d5eba25a786cdd254340878b)
<details>
- `jenkins …
> quincy: doc/glossary: add "primary affinity" to glossary

- doc/architecture.rst
Edit the section "Cluster Map" in doc/architecture.rst.
<details> …
> doc/architecture: edit "Cluster Map"

- doc/architecture.rst
Edit the section "Cluster Map" in doc/architecture.rst.
(cherry picked from commit cc8dce2531e8fac64345c4b85087f52149e9a9d0)
<details> …
> reef: doc/architecture: edit "Cluster Map"

- qa/tasks/cephfs/test_client_recovery.py
To fix tox error.
Fixes: c09558d8de0defb2695bb345c30387843e65cd93
Fixes: 469f3502d48d6ccfeba4d2ac2446ef4e47665f53
<details> …
> qa: remove duplicate import

- src/common/options/global.yaml.in
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/os/bluestore/bluestore_types.cc
- src/os/bluestore/bluestore_types.h
- src/test/objectstore/store_test.cc
This is part 3/4 of ESB work.
It modifies ExtentMap::dup() and adds all sub-functions required to make reuse of shared blobs.
This part can be enabled / disabled in runtime.
#51439 
#51440 
#51441 
#51442
<details> …
> bluestore: Elastic Shared Blobs 3 - main part

- src/common/options/global.yaml.in
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/os/bluestore/bluestore_types.cc
- src/os/bluestore/bluestore_types.h
- src/test/objectstore/store_test.cc
- src/test/objectstore/test_bluestore_types.cc
This is part 4/4 of ESB work.
It encompasses all tests that had been modified / added for this feature.
#51439 
#51440 
#51441 
#51442
<details>
- …
> bluestore: Elastic Shared Blobs 4 - tests

- doc/architecture.rst
Improve the sentence structure in the "High Availability Monitors" section of doc/architecture.rst.
(cherry picked from commit 57019c346917e6f155d89452d768bd93bdd2e51c)
<details> …
> quincy: doc/architecture: edit "High Avail. Monitors"

- src/crimson/tools/CMakeLists.txt
- src/test/crimson/seastore/transaction_manager_test_state.h
> crimson/tools/perf_staged_fltree: fix compile error

- PendingReleaseNotes
- doc/cephfs/snap-schedule.rst
- qa/suites/fs/workload/tasks/3-snaps/yes.yaml
- qa/tasks/cephfs/test_snap_schedules.py
- src/pybind/mgr/snap_schedule/fs/schedule.py
- src/pybind/mgr/snap_schedule/fs/schedule_client.py
* swap 'M' and 'm' specifiers to mean 'm' for minutes and 'M' for months
* add period mutlipliers for months and years
* add test case to test: minute, hourly, daily, weekly, monthly, yearly and bad period specifiers
Fixes: https://tracker.ceph.com/issues/62494 …
> mgr/snap_schedule: add support for monthly snapshots

- src/osd/OSD.cc
Removed unused variables to prevent compiler warnings.
Protected the shard lock.
> osd: cleaning stop_for_fast_shutdown()

- doc/man/8/ceph-monstore-tool.rst
Clean up the English in doc/man/8/ceph-monstore-tool.rst. Put all commands in the imperative mood; make sentences more direct.
<details>
- `jenkins …
> doc/man: edit ceph-monstore-tool.rst

- doc/man/8/ceph-monstore-tool.rst
Clean up the English in doc/man/8/ceph-monstore-tool.rst. Put all commands in the imperative mood; make sentences more direct.
Follows https://github.com/ceph/ceph/pull/52860.
(cherry picked from commit 02177f6368532c14b09f84e22efd64a7f7936b34)
<details> …
> reef: doc/man: edit ceph-monstore-tool.rst

- doc/architecture.rst
> doc/architecture: Edit "HA Auth"

- doc/architecture.rst
> doc/architecture: "Edit HA Auth" (one of several)

- doc/architecture.rst
(cherry picked from commit 4cbef54bbaf363dd26a7d1711f3d839f88d4c2a8)
<details>
- `jenkins …
> quincy: doc/architecture: Edit "HA Auth"

- doc/architecture.rst
(cherry picked from commit 4cbef54bbaf363dd26a7d1711f3d839f88d4c2a8)
<details>
- `jenkins …
> reef: doc/architecture: Edit "HA Auth"

- doc/architecture.rst
(cherry picked from commit e50c3e1c08ff09f44bb3a3b6f733b612b9f838d7)
<details>
- `jenkins …
> reef: doc/architecture: "Edit HA Auth" (one of several)

- doc/architecture.rst
(cherry picked from commit e50c3e1c08ff09f44bb3a3b6f733b612b9f838d7)
<details>
- `jenkins …
> quincy: doc/architecture: "Edit HA Auth" (one of several)

- src/test/rgw/test_posix_bucket_cache.cc
The CI appears to be really slow, and even a second of wait for inotify sometimes fails.  Add an exponential backoff wait of up to ~25 seconds to hopefully make the test pass reliably.
<details>
- …
> RGW - Add wait backoff to posix bucket cache test

- doc/dev/cephfs-mirroring.rst
- doc/dev/deduplication.rst
Typo Error in Doc cephfs-mirroring.rst , replace RAODS with RADOS Typo Error in Doc deduplication.rst , replace RAODS with RADOS
Signed-off-by: Daniel Parkes <dparkes@redhat.com>
(cherry picked from commit 06358e8d17a0e0fbd5d94b14595ade778a4fb5eb)
<details>
- …
> reef: doc/dev: Fix typos in files cephfs-mirroring.rst and deduplication.rst

- src/mds/CInode.cc
- src/mds/Server.cc
* dump the subvolume flag for inodes
* add debug logs when doing setxattr for ceph.dir.subvolume
Fixes: https://tracker.ceph.com/issues/61958
<details> …
> mds: add debug logs during setxattr ceph.dir.subvolume

- src/crimson/os/seastore/journal/circular_journal_space.cc
- src/crimson/os/seastore/seastore_types.h
CircularBoundedJournal is similar to circular queue, so segment_seq increases after rolling. However, current implementation always increases segment_seq_t when rolling occurs, resulting in the overflow if segment_seq_t hits MAX_SEG_SEQ.
<details> …
> crimson/os/seastore/cbj: fix a potential overflow bug on segment_seq

- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.ts
Aligns all the charts vertically, regardless of the values of the yAxes legend.
Fixes: https://tracker.ceph.com/issues/62813
<details>
- `jenkins …
> mgr/dashboard: align charts of landing page

- doc/man/8/ceph-monstore-tool.rst
s/kvstore-tool/monstore-tool/ in accordance with Ilya's remark here: https://github.com/ceph/ceph/pull/53450#discussion_r1329804085
<details>
- …
> doc/man: s/kvstore-tool/monstore-tool/

- doc/man/8/ceph-monstore-tool.rst
s/kvstore-tool/monstore-tool/ in accordance with Ilya's remark here: https://github.com/ceph/ceph/pull/53450#discussion_r1329804085
(cherry picked from commit 231afc83131c366db46e9d0345f6928c1871ce4d)
<details>
- …
> reef: doc/man: s/kvstore-tool/monstore-tool/

- doc/dev/deduplication.rst
Backport doc/dev/deduplication.rst to Quincy.
<details>
- …
> quincy: doc/dev: backport deduplication.rst to Quincy

- qa/suites/fs/thrash/multifs/overrides/client-shutdown.yaml
- qa/suites/fs/thrash/workloads/overrides/client-shutdown.yaml
Fixes: https://tracker.ceph.com/issues/62579
<details>
- …
> qa: lengthen shutdown timeout for thrashed MDS

- src/cephadm/cephadm.py
- src/cephadm/cephadmlib/daemon_identity.py
> cephadm: move get data dir function to daemonidentity method

- src/mds/MDSDaemon.cc
- src/mds/MDSRank.cc
This pull request contains 2 commits to fix 2 log-output lines of MDS-service.
- Commit 3172ed6a6762f1c5390cc9457eae72d235183261 fixes a uppercase/lowercase text-fomat of a personal pronoun
- Commit e8acf94175635e899b643125d369ca09a9151f11 fixes the last character of a specific MDS log-line which is wrongly a dot "."
Best regards
Michael Schmaltz …
> mds: fix dout log typo is MDSDaemon/MDSRank

- doc/cephfs/multimds.rst
Signed-off-by: Venky Shankar <vshankar@redhat.com>
(cherry picked from commit 20d027eb9d54ab4f6ba03dfc17d1c4c42eac1055)
<details> …
> reef: doc: add note for removing (automatic) partitioning policy

- monitoring/ceph-mixin/dashboards_out/ceph-cluster.json
not count / sum
For example, with 3 mons total, all in quorum, original will do 3/3 = 1, showing 1 out of quorum (likely just fixing a typo)
Signed-off-By: Paul Reece <paulreece42@gmail.com>
<details>
- …
> monitoring: grafana mons out of quorum should be count - sum

- src/crimson/os/seastore/cached_extent.h
> crimson/os/seastore: create page aligned bufferptr in copy ctor of CachedExtent

- doc/cephfs/multimds.rst
Signed-off-by: Venky Shankar <vshankar@redhat.com>
(cherry picked from commit 20d027eb9d54ab4f6ba03dfc17d1c4c42eac1055)
<details> …
> quincy: doc: add note for removing (automatic) partitioning policy

- src/rgw/driver/rados/rgw_data_sync.cc
This reverts commit 30cbf6691bf2006fae21cb4626b440aec2068659.
https://tracker.ceph.com/issues/62298
<details>
- `jenkins …
> rgw/multisite: fixes assertion failure during realm reload

- qa/suites/fs/multiclient/tasks/mdtest.yaml
Purge mpich package and then install it again.
Fixes: https://tracker.ceph.com/issues/61574
<details> …
> qa/cephfs: fix build failure for mdtest project

- src/tools/cephfs_mirror/FSMirror.h
- src/tools/cephfs_mirror/InstanceWatcher.cc
- src/tools/cephfs_mirror/InstanceWatcher.h
- src/tools/cephfs_mirror/Mirror.cc
- src/tools/cephfs_mirror/Mirror.h
- src/tools/cephfs_mirror/MirrorWatcher.cc
- src/tools/cephfs_mirror/MirrorWatcher.h
> cephfs-mirror: do not run concurrent C_RestartMirroring context

- src/client/Client.cc
Since a return of 0 indicates a blocking read, if the length is 0, we must make an async completion call back and then return 0 indicating an async return rather than 0 bytes.
<details> …
> Client: Fix nonblocking-io zero by read

- src/tools/cephfs_mirror/Mirror.cc
address non-zero return code first and then perform further
actions.
<details> …
> tools/cephfs_mirror: only perform actions if init succeed

- src/script/lib-build.sh
now that clang-17 has been released, let's use it if available.
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
<details> …
> run-make-check.sh: use clang-17 if available

- doc/architecture.rst
Rewrite the explanation of how a client authenticates against a monitor. This is a rewrite of a single paragraph, and has been set apart in its own PR so that it can receive the maximum amount of scrutiny that the upstream Ceph community can muster.
<details>
- …
> doc/architecture: "Edit HA Auth"

- doc/architecture.rst
Rewrite the explanation of how a client authenticates against a monitor. This is a rewrite of a single paragraph, and has been set apart in its own PR so that it can receive the maximum amount of scrutiny that the upstream Ceph community can muster.
(cherry picked from commit c71cd84ec9e579ba0913c4952570bba6082e03b5)
- Tracker …
> quincy: doc/architecture: "Edit HA Auth"

- doc/architecture.rst
Rewrite the explanation of how a client authenticates against a monitor. This is a rewrite of a single paragraph, and has been set apart in its own PR so that it can receive the maximum amount of scrutiny that the upstream Ceph community can muster.
(cherry picked from commit c71cd84ec9e579ba0913c4952570bba6082e03b5)
- Tracker …
> reef: doc/architecture: "Edit HA Auth"

- doc/architecture.rst
> doc/architecture: edit "HA Authentication"

- doc/architecture.rst
(cherry picked from commit cb680a7865c4766d54d535889ec1517a0e84b5b5)
<details>
- `jenkins …
> reef: doc/architecture: edit "HA Authentication"

- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/prometheus.service.ts
Fixes: https://tracker.ceph.com/issues/62868
<details>
- …
> mgr/dashboard: fix prometheus queries subscriptions

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade.component.spec.ts
**BEFORE**
**AFTER**
Fixes: https://tracker.ceph.com/issues/62846
<details>
- `jenkins …
> mgr/dashboard: remove empty popover when there are no health warns

- doc/architecture.rst
Edit the front matter of the "Smart Daemons Enable Hyperscale" section of doc/architecture.rst.
<details>
- `jenkins …
> doc/architecture: edit "SDEH"

- src/crimson/os/seastore/cache.cc
- src/crimson/os/seastore/cache.h
- src/crimson/os/seastore/cached_extent.h
> crimson/os/seastore/cache: don't add EXIST_CLEAN extents to lru

- src/crimson/os/seastore/cached_extent.h
- src/crimson/os/seastore/transaction_manager.h
> crimson/os/seastore/transaction_manager: move intermediate_key by "remap_offset" when remapping the "back" half of the original pin

- src/client/Client.cc
- src/client/Client.h
- src/common/CommandTable.h
- src/mgr/MgrClient.h
- src/test/client/CMakeLists.txt
- src/test/client/commands.cc
- src/test/pybind/test_cephfs.py
https://tracker.ceph.com/issues/61819
<details>
- `jenkins …
> client: append to buffer list to save all result from wildcard command

- doc/architecture.rst
Edit the front matter of the "Smart Daemons Enable Hyperscale" section of doc/architecture.rst.
(cherry picked from commit 5054f6c7538e1e3b0ffd3c0badf0fcd3a95c8d92)
<details> …
> quincy: doc/architecture: edit "SDEH"

- doc/architecture.rst
Edit the front matter of the "Smart Daemons Enable Hyperscale" section of doc/architecture.rst.
(cherry picked from commit 5054f6c7538e1e3b0ffd3c0badf0fcd3a95c8d92)
<details> …
> reef: doc/architecture: edit "SDEH"

- doc/architecture.rst
Edit "OSDs service clients directly" in the list in "Smart Daemons Enable Hyperscale" in doc/architecure.rst.
<details> …
> doc/architecture: edit "OSDs service clients directly"

- doc/man/8/cephfs-shell.rst
- src/tools/cephfs/shell/cephfs-shell
Fixes: https://tracker.ceph.com/issues/62739
<details>
- …
> cephfs-shell: drop LooseVersion for version.parse

- src/pybind/mgr/dashboard/frontend/cypress/e2e/filesystems/filesystems.e2e-spec.feature
- src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-form/cephfs-subvolume-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-form/cephfs-subvolume-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolumegroup-form/cephfs-subvolumegroup-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolumegroup-form/cephfs-subvolumegroup-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
1. CephFS Edit Form didnt had any validation for name eventhough the create had. So reused the Create form to display the Edit as well
2. Add Name Validations to Subvoume and Subvolume group forms
3. Removed the datePipe from the cephfs list template since we are using the relativeDate.
Fixes: https://tracker.ceph.com/issues/62939
- Tests …
> mgr/dashboard: fix cephfs forms validations

- src/exporter/DaemonMetricCollector.cc
- src/exporter/DaemonMetricCollector.h
- src/test/exporter/test_exporter.cc
Fixes: https://tracker.ceph.com/issues/62874
<details>
- …
> exporter: add ceph_daemon labels to labeled counters as well

- doc/architecture.rst
Edit "OSDs service clients directly" in the list in "Smart Daemons Enable Hyperscale" in doc/architecure.rst.
(cherry picked from commit 6f9dfd75b50f7793d2ff9bc3003c35efa6d6da04)
<details> …
> quincy: doc/architecture: edit "OSDs service clients directly"

- doc/architecture.rst
Edit "OSDs service clients directly" in the list in "Smart Daemons Enable Hyperscale" in doc/architecure.rst.
(cherry picked from commit 6f9dfd75b50f7793d2ff9bc3003c35efa6d6da04)
<details> …
> reef: doc/architecture: edit "OSDs service clients directly"

- src/test/rgw/test_rgw_amqp.cc
backport tracker: https://tracker.ceph.com/issues/62284
---
backport of https://github.com/ceph/ceph/pull/52762
parent tracker: https://tracker.ceph.com/issues/62264
> reef: rgw/amqp: skip idleness tests since it needs to sleep longer than 30s

- doc/architecture.rst
Edit "OSD Membership and Status" in the "Smart Daemons Enable Hyperscale" section of doc/architecture.rst.
<details>
- …
> doc/architecture: edit "OSD Membership and Status"

- doc/architecture.rst
Edit "OSD Membership and Status" in the "Smart Daemons Enable Hyperscale" section of doc/architecture.rst.
(cherry picked from commit dbd85336b1aa3ef42cfc12495b3dc5142d4b8a28)
<details> …
> reef: doc/architecture: edit "OSD Membership and Status"

- doc/architecture.rst
Edit the "Data Scrubbing" listitem in the list of benefits conferred by the use by OSDs of the aggregate power of the cluster, in the section "Smart Daemons Enable Hyperscale" in doc/architecture.rst.
<details> …
> doc/architecture: edit "Data Scrubbing"

- qa/tasks/cephfs/mount.py
- qa/tasks/cephfs/test_client_recovery.py
backport tracker: https://tracker.ceph.com/issues/62269
---
backport of https://github.com/ceph/ceph/pull/51995
parent tracker: https://tracker.ceph.com/issues/61409
> reef: qa: wait for file to have correct size

- src/mds/MDCache.cc
- src/mds/MDSRank.cc
- src/mds/MDSRank.h
- src/mds/Server.cc
backport tracker: https://tracker.ceph.com/issues/62201
---
backport of https://github.com/ceph/ceph/pull/52376
parent tracker: https://tracker.ceph.com/issues/60625
<details> …
> reef: mds: skip forwarding request if the session were removed

- src/rgw/rgw_lc.cc
backport tracker: https://tracker.ceph.com/issues/58788
---
backport of https://github.com/ceph/ceph/pull/48683
parent tracker: https://tracker.ceph.com/issues/57951
> quincy: rgwlc: prevent lc for one bucket from exceeding time budget

- src/script/backport-resolve-issue
Updated the script `backport-resolve-issue` with all the latest versions.
Fixes: https://tracker.ceph.com/issues/61745
Signed-off-by: Sayantani Saha<ii.sayantani.ii@gmail.com>
<details> …
> script/backport-resolve-issue: Update script with latest versions

- doc/architecture.rst
Edit the "Data Scrubbing" listitem in the list of benefits conferred by the use by OSDs of the aggregate power of the cluster, in the section "Smart Daemons Enable Hyperscale" in doc/architecture.rst.
(cherry picked from commit d7b991646fcd36a1df7456e8e82c9d54a01e50f9)
- …
> reef: doc/architecture: edit "Data Scrubbing"

- doc/architecture.rst
Edit the "Data Scrubbing" listitem in the list of benefits conferred by the use by OSDs of the aggregate power of the cluster, in the section "Smart Daemons Enable Hyperscale" in doc/architecture.rst.
(cherry picked from commit d7b991646fcd36a1df7456e8e82c9d54a01e50f9)
- …
> quincy: doc/architecture: edit "Data Scrubbing"

- doc/architecture.rst
Edit "Replication" in the "Smart Daemons Enable Hyperscale" section of doc/architecture.rst.
<details> …
> doc/architecture: edit "Replication"

- doc/architecture.rst
Edit "Replication" in the "Smart Daemons Enable Hyperscale" section of doc/architecture.rst.
(cherry picked from commit 4cf22e195ab367eb65f95c2578d06919ebcd108f)
<details>
- `jenkins …
> reef: doc/architecture: edit "Replication"

- doc/architecture.rst
Edit "Replication" in the "Smart Daemons Enable Hyperscale" section of doc/architecture.rst.
(cherry picked from commit 4cf22e195ab367eb65f95c2578d06919ebcd108f)
<details>
- `jenkins …
> quincy: doc/architecture: edit "Replication"

- src/cephadm/cephadm.py
- src/cephadm/cephadmlib/context_getters.py
- src/cephadm/tests/test_cephadm.py
As per the refactoring plan.
<details>
</details>
> cephadm: move context getters

- src/cephadm/cephadm.py
- src/cephadm/cephadmlib/data_utils.py
- src/cephadm/tests/test_cephadm.py
> cephadm: move more funcs into data_utils.py

- src/cephadm/cephadm.py
- src/cephadm/cephadmlib/container_engines.py
- src/cephadm/tests/test_cephadm.py
Signed-off-by: Adam King <adking@redhat.com>
<details>
- …
> cephadm: move registry_login to container_engines.py

- doc/architecture.rst
Edit the following sections in doc/architecture.rst:
1. Dynamic Cluster Management
2. About Pools
3. Mapping PGs to OSDs
The tone of "Dynamic Cluster Management" remains a bit too close to the
tone of marketing material, in my opinion, but I will return to firm it
up when I have finished a once-over of architecture.rst. …
> doc/architecture: edit several sections

- src/mgr/DaemonServer.cc
This commit fix the throttle parameter of osd does not take effect for mgr Fixes: https://tracker.ceph.com/issues/61942
<details> …
> mgr: add throttle policy for DaemonServer

- doc/architecture.rst
Edit the following sections in doc/architecture.rst:
1. Dynamic Cluster Management
2. About Pools
3. Mapping PGs to OSDs
The tone of "Dynamic Cluster Management" remains a bit too close to the tone of marketing material, in my opinion, but I will return to firm it up when I have finished a once-over of architecture.rst.
(cherry picked from commit 9657c45fc12cd8522df72c9bb8820320758305e4) …
> reef: doc/architecture: edit several sections

- doc/architecture.rst
Edit the following sections in doc/architecture.rst:
1. Dynamic Cluster Management
2. About Pools
3. Mapping PGs to OSDs
The tone of "Dynamic Cluster Management" remains a bit too close to the tone of marketing material, in my opinion, but I will return to firm it up when I have finished a once-over of architecture.rst.
(cherry picked from commit 9657c45fc12cd8522df72c9bb8820320758305e4) …
> quincy: doc/architecture: edit several sections

- doc/architecture.rst
Edit the section "Calcluating PG IDs" in doc/architecture.rst.
<details>
- `jenkins …
> doc/architecture: edit "Calculating PG IDs"

- doc/architecture.rst
Edit the section "Calcluating PG IDs" in doc/architecture.rst.
(cherry picked from commit 69a585fbf4fbf50eed784a248442f622f01120c9)
<details>
- `jenkins …
> quincy: doc/architecture: edit "Calculating PG IDs"

- doc/architecture.rst
Edit the section "Calcluating PG IDs" in doc/architecture.rst.
(cherry picked from commit 69a585fbf4fbf50eed784a248442f622f01120c9)
<details>
- `jenkins …
> reef: doc/architecture: edit "Calculating PG IDs"

- src/rgw/driver/rados/rgw_data_sync.cc
https://tracker.ceph.com/issues/62988
<details>
- `jenkins …
> rgw/multisite: call drain before flushing markers in incremental sync

- src/rgw/rgw_log.cc
https://tracker.ceph.com/issues/62871 explains why we need this evidence.
<details>
- …
> rgw/logging: add bucket and object names to the log line for ops-log

- src/pybind/mgr/dashboard/frontend/cypress/e2e/ui/dashboard-v3.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-pie/dashboard-pie.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/card/card.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/card/card.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/card/card.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/health-icon.enum.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/prometheus-alert.service.ts
We were following a row-col grid layout for the landing page. First row includes Details, Status and Capacity
Second row for Inventory and Cluster Utilization
So if one of the item in the first row increases, it pushes the entire second row downwards.
To fix this, I made a col-row grid.
First col has Details and Inventory in two rows.
Second col has Status and Capacity as a col and Cluster Utilization as a single row
https://github.com/ceph/ceph/assets/71764184/079d2656-b6f1-4b63-9e54-a0fc005e03b7
**Without Alerts**
**Previous one** …
> mgr/dashboard: fix the landing page layout issues

- src/cephadm/cephadm.py
- src/cephadm/cephadmlib/ssh.py
Part of general cephadm refactoring plan phase 2 https://pad.ceph.com/p/cephadm-refactoring
~~Depends on https://github.com/ceph/ceph/pull/53682, will rebase this after that is merged (I currently have the commit from that PR cherry-picked in so tests will pass)~~
Signed-off-by: Adam King <adking@redhat.com> …
> cephadm: start ssh.py in cephadmlib

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-migrate/rgw-multisite-migrate.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-sync-data-info/rgw-sync-data-info.component.html
- src/pybind/mgr/dashboard/services/cluster.py
Fixes: https://tracker.ceph.com/issues/62984
<details>
- …
> mgr/dashboard: show a message to restart the rgw daemons after moving from single-site to multi-site

- src/rgw/driver/rados/rgw_notify.cc
- src/test/rgw/bucket_notification/test_bn.py
backport tracker: https://tracker.ceph.com/issues/59693
---
backport of https://github.com/ceph/ceph/pull/51308
parent tracker: https://tracker.ceph.com/issues/59592
> reef: rgw/notification: remove non x-amz-meta-* attributes from bucket notifications

- src/rgw/rgw_kafka.cc
backport tracker: https://tracker.ceph.com/issues/59496
---
backport of https://github.com/ceph/ceph/pull/50965
parent tracker: https://tracker.ceph.com/issues/59383
> reef: rgw/kafka: failed to reconnect to broker after idle timeout

- src/osd/OSDMap.cc
Fixes: https://tracker.ceph.com/issues/62833
<details>
- …
> osd: fix read balancer logic to avoid redundant primary assignment

- src/mon/AuthMonitor.cc
- src/mon/AuthMonitor.h
- src/mon/KVMonitor.cc
- src/mon/OSDMonitor.cc
- src/mon/OSDMonitor.h
Fixes: https://tracker.ceph.com/issues/59813
<details>
- …
> osd/OSDMonitor: check svc is writeable before changing pending

- src/mon/ConfigMonitor.cc
To make it easier to read.
<details> …
> mon: refactor loop variable names

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/create-rgw-service-entities/create-rgw-service-entities.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-multisite-zonegroup-deletion-form/rgw-multisite-zonegroup-deletion-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-export/rgw-multisite-export.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-import/rgw-multisite-import.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-migrate/rgw-multisite-migrate.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zonegroup-form/rgw-multisite-zonegroup-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
This PR intends to do the following fixes-
1. Multi-site" should always be hyphenated
2. Multi-site Sync Status as all of the other titles on the dashboard are capitalized
3. Update Enable RGW Module description on details page
4. Update helper text for import multisite token functionality
5. Update Zonegroup mentions to Zone Group
6. Update access key to S3access key and secret key to S3 secret key
7. Add helpers for access/secret keys
Fixes: https://tracker.ceph.com/issues/62721 …
> mgr/dashboard: Rgw Multi-site naming improvements

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-list/rbd-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-list/rbd-list.component.ts
Fixes: https://tracker.ceph.com/issues/63037
<details>
- …
> mgr/dashboard: rbd image hide usage bar when disk usage is not provided

- doc/cephfs/mds-config-ref.rst
- src/common/options/mds.yaml.in
- src/mds/MDBalancer.cc
Add an option to configure the number of epochs the overload lasts before migrating,
setting it to a higher value can avoid frequent migrations caused by load fluctuations.
Signed-off-by: Zhansong Gao <zhsgao@hotmail.com>
<details> …
> mds: add option mds_bal_overload_epochs

- doc/rados/operations/control.rst
Edit doc/rados/operations/control.rst (1 of x).
<details> …
> doc/rados: edit ops/control.rst (1 of x)

- doc/rados/operations/control.rst
Edit doc/rados/operations/control.rst (2 of x).
<details> …
> doc/rados: edit ops/control.rst (2 of x)

- doc/rados/operations/control.rst
Edit doc/rados/operations/control.rst (2 of x).
(cherry picked from commit 03ed13930661628c10f185af1a3949548bdc8288)
<details>
<summary>Show …
> quincy: doc/rados: edit ops/control.rst (2 of x)

- doc/rados/operations/control.rst
Edit doc/rados/operations/control.rst (2 of x).
(cherry picked from commit 03ed13930661628c10f185af1a3949548bdc8288)
<details>
<summary>Show …
> reef: doc/rados: edit ops/control.rst (2 of x)

- qa/tasks/cephfs/xfstests_dev.py
backport tracker: https://tracker.ceph.com/issues/62271
---
backport of https://github.com/ceph/ceph/pull/59683
parent tracker: https://tracker.ceph.com/issues/51703
<details> …
> reef: xfstests_dev: install extra packages from powertools repo for xfsprogs

- qa/suites/fs/workload/tasks/5-workunit/postgres.yaml
backport tracker: https://tracker.ceph.com/issues/62947
---
backport of https://github.com/ceph/ceph/pull/53279
parent tracker: https://tracker.ceph.com/issues/62700
<details> …
> reef: qa: descrease pgbench scale factor to 32 for postgresql database test

- src/mds/MDCache.cc
- src/mds/MDSRank.cc
- src/mds/MDSRank.h
- src/mds/Server.cc
backport tracker: https://tracker.ceph.com/issues/62200
---
backport of https://github.com/ceph/ceph/pull/52376
parent tracker: https://tracker.ceph.com/issues/60625
<details> …
> quincy: mds: skip forwarding request if the session were removed

- src/mds/MDCache.cc
backport tracker: https://tracker.ceph.com/issues/62194
---
backport of https://github.com/ceph/ceph/pull/51536
parent tracker: https://tracker.ceph.com/issues/61217
Conflicts:
- Misses a dependent commit 7a4c509f7289ff4
<details>
- …
> quincy: mds: do not send split_realms for CEPH_SNAP_OP_UPDATE msg

- qa/standalone/osd/divergent-priors.sh
backport tracker: https://tracker.ceph.com/issues/62252
---
backport of https://github.com/ceph/ceph/pull/51909
parent tracker: https://tracker.ceph.com/issues/56034
> quincy: qa/standalone/osd/divergent-prior.sh: Divergent test 3 with pg_autoscale_mode on pick divergent osd

- src/rgw/rgw_rest_swift.cc
https://tracker.ceph.com/issues/58818
<details>
- `jenkins …
> quincy: rgw: swift : check for valid key in POST forms

- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/card-row/card-row.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/card-row/card-row.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/card/card.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/card/card.component.ts
Mess up of the dashboard landing page layout fixes PR
<details> …
> mgr/dashboard: fix rgw inventory card and broken shadows

- src/rgw/rgw_admin.cc
- src/test/cli/radosgw-admin/help.t
> RGW: add the missing help print for command 'topic stats'

- doc/rados/operations/control.rst
Edit doc/rados/operations/control.rst (1 of x).
(cherry picked from commit 89c9584f8a1633b5ad1936af09529657d81b7134)
<details>
<summary>Show …
> quincy: doc/rados: edit ops/control.rst (1 of x)

- doc/rados/operations/control.rst
Edit doc/rados/operations/control.rst (1 of x).
(cherry picked from commit 89c9584f8a1633b5ad1936af09529657d81b7134)
<details>
<summary>Show …
> reef: doc/rados: edit ops/control.rst (1 of x)

- doc/rados/troubleshooting/index.rst
Edit doc/rads/troubleshooting.rst to remove some language that sounds quite close to marketing language.
<details>
- …
> doc/rados: edit troubleshooting.rst

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-directories/cephfs-directories.component.ts
- src/pybind/mgr/dashboard/frontend/src/styles.scss
fixes: https://tracker.ceph.com/issues/63007
<details>
- …
> mgr/dashboard: Fixed cephfs snapshot listing in directories

- doc/rados/troubleshooting/index.rst
Edit doc/rads/troubleshooting.rst to remove some language that sounds quite close to marketing language.
(cherry picked from commit 9d9d92837e44e3af233bc228850be09e8f64eb7c)
<details>
- …
> quincy: doc/rados: edit troubleshooting.rst

- src/blk/kernel/KernelDevice.cc
backport tracker: https://tracker.ceph.com/issues/59177
---
backport of https://github.com/ceph/ceph/pull/49132
parent tracker: https://tracker.ceph.com/issues/58113
> quincy: blk/kernel: Add O_EXCL for block devices

- src/pybind/mgr/dashboard/frontend/cypress/e2e/ui/dashboard-v3.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-pie/dashboard-pie.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/card-row/card-row.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/card-row/card-row.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/card/card.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/card/card.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/card/card.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/health-icon.enum.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/prometheus-alert.service.ts
backport tracker: https://tracker.ceph.com/issues/63074
---
backport of https://github.com/ceph/ceph/pull/53522
parent tracker: https://tracker.ceph.com/issues/62961
> reef: mgr/dashboard: fix the landing page layout issues

- src/rgw/driver/rados/rgw_d3n_datacache.cc
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/rgw_file_int.h
- src/rgw/rgw_http_client.cc
> rgw: Add coverity annotations for missing mutex locks

- doc/rados/troubleshooting/index.rst
Edit doc/rads/troubleshooting.rst to remove some language that sounds quite close to marketing language.
(cherry picked from commit 9d9d92837e44e3af233bc228850be09e8f64eb7c)
<details>
- …
> reef: doc/rados: edit troubleshooting.rst

- doc/architecture.rst
Edit the English in the section "Peering and Sets" in the file doc/architecture.rst.
<details> …
> doc/architecture: edit "Peering and Sets"

- doc/architecture.rst
Edit the English in the section "Peering and Sets" in the file doc/architecture.rst.
(cherry picked from commit c69b111966f190ac4a1ebd5244a9cf9f61970dd7)
<details> …
> reef: doc/architecture: edit "Peering and Sets"

- doc/architecture.rst
Edit the English in the section "Peering and Sets" in the file doc/architecture.rst.
(cherry picked from commit c69b111966f190ac4a1ebd5244a9cf9f61970dd7)
<details> …
> quincy: doc/architecture: edit "Peering and Sets"

- src/client/Client.cc
- src/client/MetaSession.h
backport tracker: https://tracker.ceph.com/issues/62519
---
backport of https://github.com/ceph/ceph/pull/52335
parent tracker: https://tracker.ceph.com/issues/56698
<details> …
> quincy: client: move the Inode to new auth mds session when changing auth cap

- doc/rados/troubleshooting/troubleshooting-mon.rst
Follows https://github.com/ceph/ceph/pull/52827
<details>
- …
> doc/rados: edit troubleshooting-mon.rst (3 of x)

- doc/rados/troubleshooting/community.rst
Edit doc/rados/troubleshooting/community.rst.
<details>
- …
> doc/rados: edit troubleshooting/community.rst

- doc/rados/troubleshooting/community.rst
Edit doc/rados/troubleshooting/community.rst.
(cherry picked from commit fabfec273474a85cf3687ddf89183f0607c2ad71)
<details>
- …
> reef: doc/rados: edit troubleshooting/community.rst

- doc/rados/troubleshooting/troubleshooting-mon.rst
Follows https://github.com/ceph/ceph/pull/52827
(cherry picked from commit fc45a0c4dd0247f472a940d6c92e7acdb0cdc354)
<details> …
> reef: doc/rados: edit troubleshooting-mon.rst (3 of x)

- doc/rados/troubleshooting/troubleshooting-mon.rst
Follows https://github.com/ceph/ceph/pull/52827
(cherry picked from commit fc45a0c4dd0247f472a940d6c92e7acdb0cdc354)
<details> …
> quincy: doc/rados: edit troubleshooting-mon.rst (3 of x)

- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/prometheus-alert.service.ts
fixes: https://tracker.ceph.com/issues/62990
<details>
- …
> mgr/dashboard: Filter active alerts

- doc/rados/troubleshooting/troubleshooting-mon.rst
Follows https://github.com/ceph/ceph/pull/53875
<details>
- …
> doc/rados: edit troubleshooting-mon.rst (4 of x)

- src/script/ceph-debug-docker.sh
> script: update ceph-debug-docker for centos 9.stream

- qa/tasks/cephfs/test_admin.py
- src/mds/MDSAuthCaps.cc
- src/mon/AuthMonitor.cc
- src/mon/AuthMonitor.h
Fix this method so that error messages are printed to stderr.
<details>
- `jenkins …
> mon/AuthMonitor: make "ceph auth caps" print error messsages

- src/mon/MDSMonitor.cc
> mon/MDSMonitor: clean up MDSMonitor

- src/mon/AuthMonitor.cc
> mon/AuthMonitor: clean up AuthMonitor

- PendingReleaseNotes
- qa/tasks/cephfs/test_client_limits.py
- src/common/options/mds.yaml.in
- src/mds/MDSRank.cc
- src/mds/SessionMap.cc
- src/mds/SessionMap.h
https://tracker.ceph.com/issues/62585
https://tracker.ceph.com/issues/62873
<details> …
> quincy: mds: blocklist clients with "bloated" session metadata

- src/pybind/mgr/orchestrator/module.py
backport tracker: https://tracker.ceph.com/issues/62910
---
backport of https://github.com/ceph/ceph/pull/52251
parent tracker: https://tracker.ceph.com/issues/61856
> reef: mgr/cephadm: Adding sort-by support for ceph orch ps

- doc/rados/troubleshooting/troubleshooting-mon.rst
Follows https://github.com/ceph/ceph/pull/53875
(cherry picked from commit 99e92fb94b2c29e565e3f4e04658e103a09ef125)
<details> …
> quincy: doc/rados: edit troubleshooting-mon.rst (4 of x)

- doc/rados/troubleshooting/troubleshooting-mon.rst
Follows https://github.com/ceph/ceph/pull/53875
(cherry picked from commit 99e92fb94b2c29e565e3f4e04658e103a09ef125)
<details> …
> reef: doc/rados: edit troubleshooting-mon.rst (4 of x)

- src/os/bluestore/Allocator.cc
- src/os/bluestore/Allocator.h
- src/os/bluestore/AvlAllocator.cc
- src/os/bluestore/AvlAllocator.h
- src/os/bluestore/BitmapAllocator.cc
- src/os/bluestore/BitmapAllocator.h
- src/os/bluestore/BlueFS.cc
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BtreeAllocator.cc
- src/os/bluestore/BtreeAllocator.h
- src/os/bluestore/HybridAllocator.cc
- src/os/bluestore/HybridAllocator.h
- src/os/bluestore/StupidAllocator.cc
- src/os/bluestore/StupidAllocator.h
- src/os/bluestore/ZonedAllocator.cc
- src/os/bluestore/ZonedAllocator.h
- src/os/bluestore/fastbmap_allocator_impl.cc
- src/os/bluestore/fastbmap_allocator_impl.h
- src/test/objectstore/Allocator_test.cc
Fixes: https://tracker.ceph.com/issues/55301
(cherry picked from commit d7aa5decf369f48616a7b9b83136f2bbbd82ff60)
<details> …
> quincy: os/bluestore: proper locking for Allocators' dump methods

- src/blk/kernel/KernelDevice.cc
backport of https://github.com/ceph/ceph/pull/47774
backport tracker: https://tracker.ceph.com/issues/57604
parent tracker: https://tracker.ceph.com/issues/57271
<details>
- …
> quincy: blk/KernelDevice: Modify the rotational and discard check log message

- src/kv/RocksDBStore.cc
- src/kv/RocksDBStore.h
backport of https://github.com/ceph/ceph/pull/49870
backport of https://github.com/ceph/ceph/pull/49748
backport tracker: https://tracker.ceph.com/issues/59140
parent tracker: https://tracker.ceph.com/issues/58463
<details> …
> quincy: kv/RocksDBStore: cumulative backport for rm_range_keys and around

- src/os/bluestore/BlueStore.cc
backport of https://github.com/ceph/ceph/pull/50095
backport tracker: https://tracker.ceph.com/issues/59336
parent tracker: https://tracker.ceph.com/issues/57855
(cherry picked from commit 25c8df3df138b9f85a36b4d2bbc582e16e58ed0b)
Conflicts:
src/os/bluestore/BlueStore.cc
Missing backport
- …
> quincy: os/bluestore: allow 'fit_to_fast' selector for single-volume osd

- PendingReleaseNotes
- qa/suites/fs/workload/delegate_inos/default.yaml
- qa/suites/fs/workload/delegate_inos/enabled.yaml
- src/common/options/mds.yaml.in
> Revert "mds: disable delegating inode ranges to clients"

- src/mon/FSCommands.cc
>  mon/FSCommands: clean up FSCommands

- qa/crontab/teuthology-cronjobs
> qa/tests: Added upgrade/reef-x to the mix

- doc/rados/troubleshooting/memory-profiling.rst
Edit doc/rados/troubleshooting/memory-profiling.rst.
<details> …
> doc/rados: edit memory-profiling.rst

- doc/rados/troubleshooting/memory-profiling.rst
Edit doc/rados/troubleshooting/memory-profiling.rst.
(cherry picked from commit 3be932425e3020085db5abff6f914938015d8590)
<details> …
> reef: doc/rados: edit memory-profiling.rst

- doc/rados/troubleshooting/memory-profiling.rst
Edit doc/rados/troubleshooting/memory-profiling.rst.
(cherry picked from commit 3be932425e3020085db5abff6f914938015d8590)
<details> …
> quincy: doc/rados: edit memory-profiling.rst

- doc/start/get-involved.rst
Add a link to the Ceph Slack to doc/start/get-involved.rst.
<details> …
> doc/start: add Slack to get-involved

- doc/rados/troubleshooting/troubleshooting-osd.rst
Edit doc/rados/troubleshooting/troubleshooting-osd.
<details> …
> doc/rados: edit troubleshooting-osd (1 of x)

- src/crimson/os/seastore/onode_manager/staged-fltree/fltree_onode_manager.cc
- src/crimson/os/seastore/seastore.cc
- src/crimson/os/seastore/seastore.h
- src/test/crimson/seastore/test_seastore.cc
> crimson/os/seastore: return ghobject_t::max as the end when list_objects reaches the end of the listing

- doc/rados/troubleshooting/troubleshooting-osd.rst
Edit doc/rados/troubleshooting/troubleshooting-osd.
(cherry picked from commit 0fc663d793fe34e42e19b251fcc79b5af52581c6)
<details> …
> reef: doc/rados: edit troubleshooting-osd (1 of x)

- doc/rados/troubleshooting/troubleshooting-osd.rst
Edit doc/rados/troubleshooting/troubleshooting-osd.
(cherry picked from commit 0fc663d793fe34e42e19b251fcc79b5af52581c6)
<details> …
> quincy: doc/rados: edit troubleshooting-osd (1 of x)

- qa/crontab/teuthology-cronjobs
> qa/tests: fixed typo and added `--force-priority` in missing places

- src/crimson/os/seastore/object_data_handler.cc
- src/crimson/os/seastore/onode.h
- src/crimson/os/seastore/onode_manager.h
- src/crimson/os/seastore/onode_manager/staged-fltree/fltree_onode_manager.cc
- src/crimson/os/seastore/onode_manager/staged-fltree/fltree_onode_manager.h
- src/crimson/os/seastore/seastore.cc
- src/crimson/os/seastore/seastore.h
- src/test/crimson/seastore/onode_tree/test_fltree_onode_manager.cc
- src/test/crimson/seastore/test_object_data_handler.cc
Fixes: https://tracker.ceph.com/issues/62454
<details> …
> crimson/os/seastore/onode_manager: populate delta recorders for each onode modification

- doc/rados/troubleshooting/troubleshooting-osd.rst
Edit doc/rados/troubleshooting/troubleshooting.rst (2 of x).
<details> …
> doc/rados: Edit troubleshooting-osd (2 of x)

- doc/rados/troubleshooting/troubleshooting-osd.rst
Edit doc/rados/troubleshooting/troubleshooting.rst (2 of x).
Follows https://github.com/ceph/ceph/pull/53936.
(cherry picked from commit 37e7099267996a3075b4902a10a19d94fc738c08)
<details>
<summary>Show …
> quincy: doc/rados: Edit troubleshooting-osd (2 of x)

- doc/rados/configuration/filestore-config-ref.rst
- doc/releases/reef.rst
Remove FileStore-related material because FileStore is not supported in Reef.
<details> …
> doc/rados: remove FileStore material (in Reef)

- doc/rados/troubleshooting/troubleshooting-osd.rst
Edit doc/rados/troubleshooting/troubleshooting-osd.rst (3 of x).
Follows https://github.com/ceph/ceph/pull/53986.
<details> …
> doc/rados: Edit troubleshooting-osd (3 of x)

- doc/rados/troubleshooting/troubleshooting-osd.rst
Edit doc/rados/troubleshooting/troubleshooting-osd.rst (3 of x).
Follows https://github.com/ceph/ceph/pull/53986.
(cherry picked from commit 01b5aa5d27a97a02cef03b9eb0ee9dbcd55684f1)
<details> …
> reef: doc/rados: Edit troubleshooting-osd (3 of x)

- doc/rados/troubleshooting/troubleshooting-osd.rst
Edit doc/rados/troubleshooting/troubleshooting-osd.rst (3 of x).
Follows https://github.com/ceph/ceph/pull/53986.
(cherry picked from commit 01b5aa5d27a97a02cef03b9eb0ee9dbcd55684f1)
<details> …
> quincy: doc/rados: Edit troubleshooting-osd (3 of x)

- src/pybind/mgr/rbd_support/mirror_snapshot_schedule.py
- src/pybind/rbd/rbd.pyx
> pybind/rbd: don't produce info on errors in aio_mirror_image_get_info()

- doc/foundation.rst
Backport to Quincy requested by Mark Nelson, because a Google search was returning the Quincy page, which as of 2023 is outdated.
Signed-off-by: Mike Perez <thingee@gmail.com>
(cherry picked from commit 640390906f76da4bfd66bcd8006e964d6e73c98e)
<details>
- …
> quincy: doc/foundation: Updating foundation members for July 2023

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.spec.ts
Even though the Placement field was disabled, the Host field was still showing up in UI while Editing. That option is not possible in fs form.
Fixes: https://tracker.ceph.com/issues/63193
<details>
- …
> mgr/dashboard: disable hosts field while editing the filesystem 

- doc/start/hardware-recommendations.rst
doc/start: Modernize and clarify hardware-recommendations.rst
Hardware recommendations evolve over time, and Marvin K. Mooney, the time is now.
Included are clarifications of resources per daemon vs per system and the strong recommendation
that at the very least mon DBs, RGW index pools, and CephFS metadata pools reside on nonrotational devices.
- Tracker …
> doc/start: Modernize and clarify hardware-recommendations.rst

- doc/rados/troubleshooting/troubleshooting-pg.rst
> doc/rados: edit troubleshooting-pg.rst

- src/pybind/mgr/rook/module.py
- src/pybind/mgr/rook/tests/fixtures.py
- src/pybind/mgr/rook/tests/test_rook.py
Fixes: https://tracker.ceph.com/issues/63123
<details>
- …
> mgr/rook: fixing rook-ceph-exporter daemon type handling

- src/client/Client.cc
- src/client/Client.h
- src/common/ceph_strings.cc
- src/include/ceph_fs.h
- src/include/cephfs/libcephfs.h
- src/include/compat.h
- src/include/win32/fs_compat.h
- src/libcephfs.cc
- src/mds/MDCache.cc
- src/mds/Mutation.h
- src/mds/Server.cc
- src/mds/Server.h
- src/mds/SnapRealm.cc
- src/pybind/cephfs/c_cephfs.pxd
- src/pybind/cephfs/cephfs.pyx
- src/pybind/cephfs/mock_cephfs.pxi
- src/test/libcephfs/CMakeLists.txt
- src/test/libcephfs/snapdiff.cc
- src/test/pybind/test_cephfs.py
Backport of https://github.com/ceph/ceph/pull/43546
<details>
- …
> reef: cephfs: implement snapdiff

- src/pybind/mgr/dashboard/frontend/cypress/e2e/ui/navigation.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/icons.enum.ts
**NEW**
[Screencast from 2023-10-06 01-58-48.webm](https://github.com/ceph/ceph/assets/6695156/bedfe2f3-b19a-47e9-8154-0e8f89911393)
OLD:
[Screencast from 2023-08-24 15-05-22.webm](https://github.com/ceph/ceph/assets/6695156/a06e46dc-5362-48e9-8787-d727a6df13d5)
Fixes: https://tracker.ceph.com/issues/62366 …
> mgr/dashboard: Left navigation improvements

- doc/rados/troubleshooting/troubleshooting-pg.rst
(cherry picked from commit fbde0a441ee753c06afe3723584d6c9686ceef21)
<details>
- `jenkins …
> quincy: doc/rados: edit troubleshooting-pg.rst (1 of x)

- doc/rados/troubleshooting/troubleshooting-pg.rst
(cherry picked from commit fbde0a441ee753c06afe3723584d6c9686ceef21)
<details>
- `jenkins …
> reef: doc/rados: edit troubleshooting-pg.rst (1 of x)

- doc/start/hardware-recommendations.rst
(cherry picked from commit 83bd3a8dfb83c46a2ba84d9f309a6dbe72c64ea9)
<details> …
> reef: doc/start: Modernize and clarify hardware-recommendations.rst

- doc/start/hardware-recommendations.rst
(cherry picked from commit 83bd3a8dfb83c46a2ba84d9f309a6dbe72c64ea9)
<details> …
> quincy: doc/start: Modernize and clarify hardware-recommendations.rst

- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_reshard.cc
- src/rgw/driver/rados/rgw_reshard.h
- src/rgw/rgw_admin.cc
- src/rgw/rgw_bucket_layout.h
Adds a test for an indexless bucket when a bucket is considered for dynamic resharding.
Resolves: https://tracker.ceph.com/issues/63170
<details>
- …
> rgw: only buckets with reshardable layouts need to be considered for resharing

- doc/rados/configuration/mon-config-ref.rst
- doc/rados/configuration/pool-pg-config-ref.rst
- doc/rados/operations/placement-groups.rst
- doc/rados/troubleshooting/troubleshooting-pg.rst
Follows https://github.com/ceph/ceph/pull/54052.
<details> …
> doc/rados: edit troubleshooting-pg (2 of x)

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-import/rgw-multisite-import.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-import/rgw-multisite-import.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-realm.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/ceph_service.py
- src/pybind/mgr/rgw/module.py
Add port and zone endpoints to import realm token form in rgw multisite
[Screencast from 2023-10-16 09-51-37.webm](https://github.com/ceph/ceph/assets/66050535/a81c8c85-77fc-495d-910d-5f899481dc4d)
<details> …
> mgr/dashboard: add port and zone endpoints to import realm token form in rgw multisite

- qa/tasks/cephfs/test_client_recovery.py
- src/mds/Beacon.cc
- src/mds/Server.cc
Fixes: https://tracker.ceph.com/issues/63105
<details>
- …
> mds: report clients laggy due laggy OSDs only after checking any OSD is laggy

- src/client/Client.cc
Client::C_Read_Async_Finisher::finish() doesn't need to take the lock because ObjectCacher has already assured the lock is held.
Of course when we immediately complete, we don't need to unlock.
<details> …
> Client: C_Read_Async_Finisher should assume client_lock is held

- src/pybind/mgr/cephadm/tests/test_upgrade.py
This is actually meant to make sure we don't screw up the image base. 
See https://tracker.ceph.com/issues/63150 to see what we're trying to avoid happening again
<details> …
> mgr/cephadm: add unit test to for upgrade check with --ceph-version

- qa/crontab/teuthology-cronjobs
> qa/tests: enabled smoke tests on main, quincy and reef

- doc/rados/configuration/mon-config-ref.rst
- doc/rados/configuration/pool-pg-config-ref.rst
- doc/rados/operations/placement-groups.rst
- doc/rados/troubleshooting/troubleshooting-pg.rst
Follows https://github.com/ceph/ceph/pull/54052.
(cherry picked from commit d0cdfc1d72c4edefb060f8ba9ab130189617cab1)
<details>
<summary>Show …
> reef: doc/rados: edit troubleshooting-pg (2 of x)

- .github/pull_request_template.md
We've seen on occasion PRs that fail checks due to not knowing the nuances of ticking checklist items.
<details>
- …
> .github: Clarify checklist details

- .github/pull_request_template.md
(cherry picked from commit 1ca356a916910a4016d5d3460d68ea3732f3bad9) …
> quincy: .github: Clarify checklist details

- src/crimson/tools/perf_crimson_msgr.cc
backport of https://github.com/ceph/ceph/pull/53046
See: https://gist.github.com/Matan-B/3366024c130634942d0b1227112663e1
> reef: crimson/tools/perf_crimson_msgr: randomize client nonce

- doc/radosgw/s3-notification-compatibility.rst
most pubsub docs were removed in
0fecbe2476afbb06de7ea731b7c92066ae40cfc4
however, the text removed described functionality that is only supported bia pubsub
Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>
(cherry picked from commit c479f2e6caa1f8f736eedb6f0036dbaa4649a204) …
> reef: doc/rgw: pubsub capabilities reference was removed from docs

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-import/rgw-multisite-import.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-import/rgw-multisite-import.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-realm.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/ceph_service.py
- src/pybind/mgr/rgw/module.py
backport tracker: https://tracker.ceph.com/issues/63272
---
backport of https://github.com/ceph/ceph/pull/53994
parent tracker: https://tracker.ceph.com/issues/63267
> reef: mgr/dashboard: add port and zone endpoints to import realm token form in rgw multisite

- src/mds/CDentry.cc
- src/mds/CDentry.h
- src/mds/CInode.h
- src/mds/MDCache.cc
- src/mds/MDCache.h
- src/mds/MDSRank.cc
- src/mds/MDSRank.h
- src/mds/Server.cc
- src/mds/Server.h
- src/mds/StrayManager.cc
- src/messages/MDentryUnlink.h
- src/msg/Message.cc
- src/msg/Message.h
backport tracker: https://tracker.ceph.com/issues/62860
---
backport of https://github.com/ceph/ceph/pull/52199
parent tracker: https://tracker.ceph.com/issues/61818
<details> …
> reef: mds: fix deadlock between unlinking and linkmerge

- qa/tasks/cephfs/xfstests_dev.py
backport tracker: https://tracker.ceph.com/issues/62515
---
backport of https://github.com/ceph/ceph/pull/52741
parent tracker: https://tracker.ceph.com/issues/62277
<details> …
> reef: qa/cephfs: switch to python3 for centos stream 9

- src/mds/Locker.cc
- src/mds/SimpleLock.h
backport tracker: https://tracker.ceph.com/issues/62524
---
backport of https://github.com/ceph/ceph/pull/52111
parent tracker: https://tracker.ceph.com/issues/44565
<details> …
> reef: ceph: allow xlock state to be LOCK_PREXLOCK when putting it

- src/client/Client.cc
- src/client/MetaSession.h
backport tracker: https://tracker.ceph.com/issues/62521
---
backport of https://github.com/ceph/ceph/pull/52335
parent tracker: https://tracker.ceph.com/issues/56698
<details> …
> reef: client: move the Inode to new auth mds session when changing auth cap

- qa/tasks/cephfs/test_failover.py
backport tracker: https://tracker.ceph.com/issues/61828
---
backport of https://github.com/ceph/ceph/pull/52170
parent tracker: https://tracker.ceph.com/issues/61764
> reef: qa: assign file system affinity for replaced MDS

- src/mon/OSDMonitor.cc
backport tracker: https://tracker.ceph.com/issues/62611
---
backport of https://github.com/ceph/ceph/pull/50502
parent tracker: https://tracker.ceph.com/issues/58972
> reef: mon/OSDMonitor: do not propose on error in prepare_update

- src/include/object_fmt.h
- src/osd/scrubber/pg_scrubber.cc
This commit is specific to quincy. …
> quincy: osd: bring the missed fmt::formatter for snapid_t to address FTBFS

- src/test/objectstore/test_kv.cc
We need to use random content to estimate DB size. Otherwise, compression will cause DB to be unreasonably small.
Fixes: https://tracker.ceph.com/issues/63121
<details>
- …
> os/kv_test: Fix estimate functions

- doc/rados/configuration/mon-config-ref.rst
- doc/rados/operations/pools.rst
Remove HitSet-related key information from
doc/rados/operations/pools.rst. HitSet-related keys are relevant only to releases of Ceph that support cache tiering. Only Quincy and earlier (inclusive) releases of Ceph support cache tiering. Backport this commit from main to Reef, but not to Quincy or to release branches earlier than Quincy.
(cherry picked from commit 78878511a3e782d5cde63bfb71409c46244402f7) …
> reef: doc/rados: remove HitSet-related key information

- doc/rados/troubleshooting/troubleshooting-pg.rst
s/placement group/pool/ in a sentence that, prior to this change, was confusing. Suitable for backports prior to Reef.
(cherry picked from commit 97512a3e3c28d9aae7e61c30bbe66987298960a9) …
> quincy: doc/rados: edit troubleshooting-pg.rst

- doc/rados/troubleshooting/troubleshooting-pg.rst
s/placement group/pool/ in a sentence that, prior to this change, was confusing. Suitable for backports prior to Reef.
(cherry picked from commit 97512a3e3c28d9aae7e61c30bbe66987298960a9) …
> reef: doc/rados: edit troubleshooting-pg.rst

- doc/install/index.rst
Simplify the explanation of cephadm. …
> doc/install: simplify cephadm docs

- doc/ceph-volume/lvm/activate.rst
Improve the grammar of a note explaining that the execution of the call that activates ceph-volume is idempotent.
- …
> doc/ceph-volume: explain idempotence

- doc/ceph-volume/lvm/activate.rst
Improve the grammar of a note explaining that the execution of the call that activates ceph-volume is idempotent.
(cherry picked from commit e58bc3e4df97d950d96d006b6336e10dbe9327a2) …
> reef: doc/ceph-volume: explain idempotence

- doc/ceph-volume/lvm/activate.rst
Simplify and improve the readability of the front matter of doc/ceph-volume/lvm/activate.rst. …
> doc/ceph-volume: improve front matter

- doc/ceph-volume/lvm/activate.rst
Simplify and improve the readability of the front matter of doc/ceph-volume/lvm/activate.rst.
(cherry picked from commit 23190dd91861d1dcb8d03b78fb378e042394dfad) …
> reef: doc/ceph-volume: improve front matter

- doc/ceph-volume/lvm/activate.rst
Simplify and improve the readability of the front matter of doc/ceph-volume/lvm/activate.rst.
(cherry picked from commit 23190dd91861d1dcb8d03b78fb378e042394dfad) …
> quincy: doc/ceph-volume: improve front matter

- src/pybind/mgr/rook/rook_cluster.py
Fixes: https://tracker.ceph.com/issues/63291 …
> mgr/rook: fix the namespaces used in rook and removes hard-coded references

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-import/rgw-multisite-import.component.html
Change 'To obtain the token, generate it from your secondary Ceph cluster' to 'To obtain the token, generate it from your primary Ceph cluster' in rgw multisite import form helper
Fixes: https://tracker.ceph.com/issues/63348 …
> mgr/dashboard: update rgw multisite import form helper info

- src/pybind/mgr/rbd_support/mirror_snapshot_schedule.py
- src/pybind/rbd/rbd.pyx
backport tracker: https://tracker.ceph.com/issues/63226
---
backport of https://github.com/ceph/ceph/pull/54002
parent tracker: https://tracker.ceph.com/issues/63028
> pacific: pybind/rbd: don't produce info on errors in aio_mirror_image_get_info()

- .github/workflows/create-backport-trackers.yml
See https://docs.python.org/3.10/whatsnew/3.10.html#distutils-deprecated.
- …
> create-backport-trackers: pin to Python <3.12

- doc/releases/quincy.rst
> doc: Release notes 17.2.7 with updated dashboard info

- src/os/bluestore/bluestore_tool.cc
db
This actually reimplements https://github.com/ceph/ceph/pull/52193 through legacy stat/S_ISBLK call to avoid major code updates.
backport tracker: https://tracker.ceph.com/issues/62062
parent tracker: https://tracker.ceph.com/issues/55260
<details> …
> pacific: os/bluestore: don't require bluestore_db_block_size when attaching new

- src/common/legacy_config_opts.h
- src/common/options.cc
- src/os/bluestore/BlueFS.cc
- src/os/bluestore/BlueFS.h
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
backport tracker: https://tracker.ceph.com/issues/62928
backport of https://github.com/ceph/ceph/pull/44713
parent tracker: https://tracker.ceph.com/issues/53907
<details> …
> pacific: bluestore: Fix problem with volume selector

- doc/dev/release-process.rst
> docs: revised Distro Codemap, removed `octopus`, added `reef`

- src/os/bluestore/BlueStore.cc
High fragmentation is one of the factors affecting performance decrease, add it to prometheus, it helps to us monitor fragmentation changes. …
> os/bluestore: add bluestore fragmentation micros to prometheus

- src/pybind/mgr/dashboard/frontend/tsconfig.json
The BlockUi element is failing in angular with target es2022..change it to es2020
Fixes: https://tracker.ceph.com/issues/63347 …
> mgr/dashboard: Block Ui fails in angular with target es2022 

- src/os/bluestore/BlueStore.cc
- src/osd/OSD.cc
Let's be more verbose when loading bluestore collections.
Related-to: https://tracker.ceph.com/issues/61193
<details>
- …
> pacific: osd,bluestore: gracefully handle a failure during meta collection load

- doc/glossary.rst
Initially s/backend/back end/ but then I added a little more information about BlueStore's use of RocksDB to map object names to block locations on disk. …
> doc/glossary: improve "BlueStore" entry

- src/osd/OSDMap.cc
The logic was changed in check_pg_upmaps
in a Reef refactor, which results in recommendations made by the upmap balancer even when it says there are no optimizations.
Fixes: https://tracker.ceph.com/issues/63029
<details>
- `jenkins …
> osd: fix logic in check_pg_upmaps

- doc/glossary.rst
Initially s/backend/back end/ but then I added a little more information about BlueStore's use of RocksDB to map object names to block locations on disk.
(cherry picked from commit 8713cca328c9373636efdb92449d743b5bd56584) …
> reef: doc/glossary: improve "BlueStore" entry

- doc/glossary.rst
Initially s/backend/back end/ but then I added a little more information about BlueStore's use of RocksDB to map object names to block locations on disk.
(cherry picked from commit 8713cca328c9373636efdb92449d743b5bd56584) …
> quincy: doc/glossary: improve "BlueStore" entry

- install-deps.sh
Allow install_deps.sh to continue if `ceph-libbost` install fails.
- Component …
> build: Fix ARM build and make install-deps.sh more robust

- src/crimson/osd/osd_operations/internal_client_request.cc
- src/crimson/osd/pg.cc
- src/crimson/osd/pg.h
Preliminary refactor around `do_osd_ops_execute()` in preparation for: https://tracker.ceph.com/issues/61651.
Mainly for separating the two returned futures (`submitted` and `all_completed`).
<details> …
> crimson/osd/pg: do_osd_ops_execute refactor

- doc/cephadm/troubleshooting.rst
Edit doc/cephadm/troubleshooting.rst. This commit and the PR of which it is a part was raised in response to
https://github.com/ceph/ceph/pull/53976. The limits of reStructuredText are particularly visible here in every instance of a BASH for-loop and in every instance of a command stretched over multiple lines.
(cherry picked from commit 69472c26af5419faa9ed93c071ed5933d03fa67f) …
> reef: doc/cephadm: edit troubleshooting.rst (1 of x)

- doc/cephadm/troubleshooting.rst
Edit doc/cephadm/troubleshooting.rst. This commit and the PR of which it is a part was raised in response to
https://github.com/ceph/ceph/pull/53976. The limits of reStructuredText are particularly visible here in every instance of a BASH for-loop and in every instance of a command stretched over multiple lines.
(cherry picked from commit 69472c26af5419faa9ed93c071ed5933d03fa67f) …
> quincy: doc/cephadm: edit troubleshooting.rst (1 of x)
