ceph/ceph

src/tools/ceph_dedup_tool.cc

This PR improves the progress reports during chunk scrub and sample dedup.
<details>
- …

tool/ceph-dedup-tool: improve the progress report

---

qa/workunits/rados/test_envlibrados_for_rocksdb.sh

subscription-manager repos will fail with 'does not match a valid repository ID' we should use dnf config-manager --set-enabled instead
Fixes: https://tracker.ceph.com/issues/58560
Signed-off-by: Nitzan Mordechai <nmordec@redhat.com>
<details> …

qa/*/test_envlibrados_for_rocksdb.sh: subscribe repo

---

qa/workunits/rados/test_dedup_tool.sh
src/tools/ceph_dedup_tool.cc

Perform dedup on snapshotted object during sample dedup work if snapshot option is enabled
<details> …

tool/ceph-dedup-tool: perform dedup on snapshotted object during sample dedup

---

src/rgw/rgw_admin.cc

https://tracker.ceph.com/issues/62845
<details>
- `jenkins …

rgw/multisite: fix sync_error_trim command

---

src/rgw/rgw_file.cc

Reported by Leonid Usov <leonid.usov@ibm.com>.
Fixes: https://tracker.ceph.com/issues/63409 …

rgwfile: fix lock_guard decl

---

doc/cephadm/troubleshooting.rst

Edit doc/cephadm/troubleshooting.rst. This commit and the PR of which it is a part was raised in response to https://github.com/ceph/ceph/pull/53976. …

doc/cephadm: edit troubleshooting.rst (2 of x)

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.ts
src/pybind/mgr/dashboard/services/rgw_client.py

Getting the bucket details will also fetch the bucket policy if its set.
For testing purpose, I exposed a set_bucket_policy endpoint in the RESTAPI which will set the policy to a bucket.
**Bucket Details without policy**
**Bucket Details with policy**
To set bucket policy, the request can be made like
```
curl -X 'PUT' \
'https://127.0.0.1:4200/api/rgw/bucket/set_bucket_policy' \
-H 'accept: application/vnd.ceph.api.v1.0+json' \
-H 'Content-Type: application/json' \
-d '{
"bucket_name": "test",
"policy": "{\"Version\": \"2012-10-17\", \"Statement\": [{ \"Sid\": \"id-1\",\"Effect\": \"Allow\",\"Principal\": {\"AWS\": \"arn:aws:iam::123456789012:root\"}, \"Action\": [ \"s3:PutObject\",\"s3:PutObjectAcl\"], \"Resource\": [\"arn:aws:s3:::acl3/*\" ] } ]}"
}'
```
Fixes: …

mgr/dashboard: get object bucket policies for a bucket

---

src/crimson/os/seastore/btree/btree_range_pin.cc
src/crimson/os/seastore/btree/btree_range_pin.h
src/crimson/os/seastore/btree/fixed_kv_btree.h
src/crimson/os/seastore/btree/fixed_kv_node.h
src/crimson/os/seastore/cached_extent.cc
src/crimson/os/seastore/cached_extent.h
src/crimson/os/seastore/collection_manager/flat_collection_manager.cc
src/crimson/os/seastore/lba_manager.h
src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.cc
src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.h
src/crimson/os/seastore/object_data_handler.cc
src/crimson/os/seastore/omap_manager/btree/btree_omap_manager.cc
src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.cc
src/crimson/os/seastore/onode_manager/staged-fltree/node_extent_manager/seastore.h
src/crimson/os/seastore/transaction_manager.cc
src/crimson/os/seastore/transaction_manager.h
src/test/crimson/seastore/test_transaction_manager.cc

crimson/os/seastore: add unittests for transaction manager's clone/remap/read_pin and fix bugs

---

src/mds/MDSRank.cc

Debugging for https://tracker.ceph.com/issues/59119
<details> …

mds: respawn standby-replay if read_pos is <= expire_pos

---

qa/tasks/cephfs/xfstests_dev.py

Dependencies listed in xfstests_dev.py for xfstests-dev project are
outdated. This leads the xfstests_dev.py based integration tests to
fail. Update this dependency list using README of xfstests-dev project.
Fixes: https://tracker.ceph.com/issues/62556
<details> …

qa/cephfs: update dependencies for xfstests-dev

---

doc/radosgw/dynamicresharding.rst

"3, After resharding completed:" should be 
"3. After resharding completed:"
- …

doc: Update dynamicresharding.rst

---

doc/rados/configuration/bluestore-config-ref.rst

Letters "L P" got lowcased to "l p".
Reverted that.
Partially fixes:
https://tracker.ceph.com/issues/63353
- …

Fixing example of BlueStore resharding.

---

doc/cephadm/troubleshooting.rst

Edit doc/cephadm/troubleshooting.rst. This commit and the PR of which it is a part was raised in response to https://github.com/ceph/ceph/pull/53976.
Co-authored-by: John Mulligan <jmulligan@redhat.com>
(cherry picked from commit b096c21c7c4df2bf177f3ba84093cc75ecd71d49) …

reef: doc/cephadm: edit troubleshooting.rst (2 of x)

---

doc/cephadm/troubleshooting.rst

Edit doc/cephadm/troubleshooting.rst. This commit and the PR of which it is a part was raised in response to https://github.com/ceph/ceph/pull/53976.
Co-authored-by: John Mulligan <jmulligan@redhat.com>
(cherry picked from commit b096c21c7c4df2bf177f3ba84093cc75ecd71d49) …

quincy: doc/cephadm: edit troubleshooting.rst (2 of x)

---

doc/radosgw/dynamicresharding.rst

"3, After resharding completed:" should be
"3. After resharding completed:"
Signed-off-by: Aliaksei Makarau <aliaksei.makarau@ibm.com>
(cherry picked from commit e96cef78bb97491e6488999d6bc4a068cd1c5a8d) …

quincy: doc: Update dynamicresharding.rst

---

doc/radosgw/dynamicresharding.rst

"3, After resharding completed:" should be
"3. After resharding completed:"
Signed-off-by: Aliaksei Makarau <aliaksei.makarau@ibm.com>
(cherry picked from commit e96cef78bb97491e6488999d6bc4a068cd1c5a8d) …

reef: doc: Update dynamicresharding.rst

---

doc/rados/configuration/bluestore-config-ref.rst

Letter "O" got lowcased to "o".
Reverted that.
https://tracker.ceph.com/issues/63436 …

doc/rados/configuration/bluestore-config-ref: Fix lowcase typo

---

src/pybind/mgr/rook/ci/Dockerfile
src/pybind/mgr/rook/ci/run-rook-e2e-tests.sh
src/pybind/mgr/rook/ci/scripts/bootstrap-rook-cluster.sh
src/pybind/mgr/rook/ci/tests/features/rook.feature
src/pybind/mgr/rook/ci/tests/features/steps/implementation.py
src/pybind/mgr/rook/ci/tests/features/steps/utils.py
src/pybind/mgr/tox.ini

mgr/rook: adding e2e testing for rook orchestrator

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Format a Q&A list in doc/rados/troubleshooting/troubleshooting.rst, in the "Clock Skews" section.
(cherry picked from commit aadb87aeb5cd8b413937ddfe4562411d424c4bb1) …

quincy: doc/rados: format Q&A list in t-mon.rst

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Format a Q&A list in doc/rados/troubleshooting/troubleshooting.rst, in the "Clock Skews" section.
(cherry picked from commit aadb87aeb5cd8b413937ddfe4562411d424c4bb1) …

reef: doc/rados: format Q&A list in t-mon.rst

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Clarify the text in the "Clock Skew" section of
- Tracker …

doc/rados: edit t-mon.rst text

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Clarify the text in the "Clock Skew" section of
(cherry picked from commit 5496bd426f35c0ab91ae7d544ae92ed3b517c7eb) …

reef: doc/rados: edit t-mon.rst text

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Clarify the text in the "Clock Skew" section of
(cherry picked from commit 5496bd426f35c0ab91ae7d544ae92ed3b517c7eb) …

quincy: doc/rados: edit t-mon.rst text

---

src/crimson/os/seastore/transaction_manager.cc

see https://github.com/ceph/ceph/pull/54036#discussion_r1381391263
- Component …

crimson/os/seastore/transaction_manager: add the missing UNIT_TESTS_BUILT guard

---

doc/cephfs/mount-using-fuse.rst

Fixes missing dash that lead to unnecessary debugging.
Signed-off-by: Jaanus Torp <jaanus@saun.ee>
- Tracker …

doc: Update mount-using-fuse.rst

---

src/crimson/os/seastore/btree/fixed_kv_btree.h
src/crimson/os/seastore/btree/fixed_kv_node.h
src/crimson/os/seastore/cached_extent.h
src/test/crimson/seastore/test_transaction_manager.cc

The cleanup part of https://github.com/ceph/ceph/pull/54326
- …

crimson/os/seastore: cleanup, be explicit about stable and stable_written

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Bold the questions in a Q&A list in the "Most Common Monitor Issues" section of doc/rados/troubleshooting/troubleshooting-mon.rst. …

doc/rados: format Q&A list in tshooting-mon.rst

---

doc/radosgw/s3-notification-compatibility.rst
src/rgw/rgw_lc.cc
src/test/rgw/bucket_notification/test_bn.py

Fixes: https://tracker.ceph.com/issues/58641
<details>
- …

rgwlc: dispatch S3 notifications on transition and mpu abort

---

src/cephadm/cephadm.py

As discussed in the orch weekly, instead of having the two flags, we'll just have the --no-cleanup-on-failure flag on its own. This commit does not change the behavior at all. It will still do the cleanup if --no-cleanup-on-failure is not provided and not do the cleanup if it was. This just removes the additional flag. …

cephadm: remove --cleanup-on-failure flag

---

src/pybind/mgr/cephadm/ssl_cert_utils.py
src/pybind/mgr/mgr_util.py

mgr/dashboard: discovery service (port 8765) fails on ipv6 only clusters
Tracker ticket: https://tracker.ceph.com/issues/63388 …

mgr/cephadm: discovery service (port 8765) fails on ipv6 only clusters

---

src/rgw/driver/rados/rgw_notify.cc
src/rgw/rgw_perf_counters.cc
src/rgw/rgw_perf_counters.h

RGW: perf counters for persistent topic stats

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Bold the questions in a Q&A list in the "Most Common Monitor Issues" section of doc/rados/troubleshooting/troubleshooting-mon.rst.
(cherry picked from commit 0d953d27cb6503dfde7f4f7ecb9a386c533c30c9) …

quincy: doc/rados: format Q&A list in tshooting-mon.rst

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Bold the questions in a Q&A list in the "Most Common Monitor Issues" section of doc/rados/troubleshooting/troubleshooting-mon.rst.
(cherry picked from commit 0d953d27cb6503dfde7f4f7ecb9a386c533c30c9) …

reef:doc/rados: format Q&A list in tshooting-mon.rst

---

doc/radosgw/dynamicresharding.rst

(cherry picked from commit a9bf0c13e3dc866bd1cb724a10e23ae215e15437) …

reef: doc/radosgw: Improve dynamicresharding.rst

---

doc/radosgw/dynamicresharding.rst

(cherry picked from commit a9bf0c13e3dc866bd1cb724a10e23ae215e15437) …

quincy: doc/radosgw: Improve dynamicresharding.rst

---

src/rgw/rgw_admin.cc

Currently errors are displayed on STDERR but do not get into the appropriate log. This duplicates the STDERR messages to the log. …

rgw: log errors during "bi list"

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/formatter.service.ts

Fixes: https://tracker.ceph.com/issues/63243
<details>
- …

mgr/dashboard: dashboard area chart unit test

---

qa/suites/orch/cephadm/orchestrator_cli/orchestrator_cli.yaml
qa/suites/perf-basic/objectstore/bluestore.yaml
qa/suites/smoke/basic/tasks/test/cfuse_workunit_suites_blogbench.yaml
qa/suites/smoke/basic/tasks/test/cfuse_workunit_suites_fsstress.yaml
qa/suites/smoke/basic/tasks/test/cfuse_workunit_suites_iozone.yaml
qa/suites/smoke/basic/tasks/test/cfuse_workunit_suites_pjd.yaml
qa/suites/smoke/basic/tasks/test/kclient_workunit_direct_io.yaml
qa/suites/smoke/basic/tasks/test/kclient_workunit_suites_dbench.yaml
qa/suites/smoke/basic/tasks/test/kclient_workunit_suites_fsstress.yaml
qa/suites/smoke/basic/tasks/test/kclient_workunit_suites_pjd.yaml
qa/suites/smoke/basic/tasks/test/libcephfs_interface_tests.yaml
qa/suites/smoke/basic/tasks/test/rados_cls_all.yaml
qa/suites/smoke/basic/tasks/test/rbd_cli_import_export.yaml
qa/suites/smoke/basic/tasks/test/rbd_python_api_tests.yaml
qa/suites/smoke/basic/tasks/test/rbd_workunit_suites_iozone.yaml
qa/suites/smoke/basic/tasks/test/rgw_ec_s3tests.yaml
qa/suites/smoke/basic/tasks/test/rgw_s3tests.yaml

Some of the smoke, orch and perf-basic tests are failing due to POOL_APP_NOT_ENABLED health check failure. Add
POOL_APP_NOT_ENABLED to ignorelist for these tests.
Signed-off-by: Prashant D <pdhange@redhat.com>
(cherry picked from commit 4ecec7a777e90fce31317bc805fc70e1b40cba74)
Backport of #54082 …

reef: qa/smoke,orch,perf-basic: add POOL_APP_NOT_ENABLED to ignorelist

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-import/rgw-multisite-import.component.html

Before : To obtain the token, generate it from your primary Ceph cluster. This token includes encoded information about the secondary cluster's endpoint, access key, and secret key.
Fix: To obtain the token, generate it from your primary Ceph cluster. This token includes encoded information about the primary cluster's endpoint, access key, and secret key.
Fixes: https://tracker.ceph.com/issues/63469 …

mgr/dashboard: fix rgw multi-site import form helper

---

doc/cephadm/troubleshooting.rst

(cherry picked from commit e9654b77eda12a3862eefb93c65dc5f15715833d) …

reef: doc/cephadm: fix typo in set ssh key command

---

doc/cephadm/troubleshooting.rst

(cherry picked from commit e9654b77eda12a3862eefb93c65dc5f15715833d) …

quincy: doc/cephadm: fix typo in set ssh key command

---

.github/pull_request_template.md

github: adding command for rook e2e jenkins job

---

qa/cephfs/begin/1-ceph.yaml
qa/cephfs/overrides/ignorelist_health.yaml

https://tracker.ceph.com/issues/62539 …

reef: qa: add POOL_APP_NOT_ENABLED to ignorelist for cephfs tests 

---

src/client/Client.cc
src/client/Client.h
src/client/Dentry.h

Fixes: https://github.com/ceph/ceph/pull/48027#issuecomment-1741019086
Fixes: https://github.com/ceph/ceph/pull/48027#issuecomment-1752324457
<details> …

client: two fix for checking mds auth access in client side

---

src/messages/MClientRequest.h

Fix for https://github.com/ceph/ceph/pull/53139#issuecomment-1771388202
Reproducer:
1. use old enough Linux kernel ceph client (Linux kernel v5.4 works fine for this purpose)
2. mount ceph on `/mnt/ceph`
3. `touch /mnt/ceph/123`
4. MDS will crash with assertion on `ceph_assert(_inode->gid != (unsigned)-1)`.
https://tracker.ceph.com/issues/63288 …

MClientRequest: properly handle ceph_mds_request_head_legacy for ext_num_retry, ext_num_fwd, owner_uid, owner_gid

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the first part of the section "Most Common Monitor Issues" in doc/rados/troubleshooting/troublehsooting-mon.rst. …

doc/rados: edit t-mon "common issues" (1 of x)

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the first part of the section "Most Common Monitor Issues" in doc/rados/troubleshooting/troublehsooting-mon.rst.
(cherry picked from commit 434d8967a37d49bdce3effae4e9b4c69a8586a56) …

reef: doc/rados: edit t-mon "common issues" (1 of x)

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the first part of the section "Most Common Monitor Issues" in doc/rados/troubleshooting/troublehsooting-mon.rst.
(cherry picked from commit 434d8967a37d49bdce3effae4e9b4c69a8586a56) …

quincy: doc/rados: edit t-mon "common issues" (1 of x)

---

doc/rados/troubleshooting/troubleshooting-mon.rst

doc/rados: edit t-mon "common issues" (2 of x)

---

doc/rados/troubleshooting/troubleshooting-mon.rst

(cherry picked from commit 7dcfa9132ce6ca97d2c414014fc5de0a0c7e106e) …

reef: doc/rados: edit t-mon "common issues" (2 of x)

---

doc/rados/troubleshooting/troubleshooting-mon.rst

(cherry picked from commit 7dcfa9132ce6ca97d2c414014fc5de0a0c7e106e) …

quincy: doc/rados: edit t-mon "common issues" (2 of x)

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Improve the front matter of the section "Troubleshooting Monitors" in doc/rados/troubleshooting/troubleshooting-mon.rst. …

doc/rados: edit t-shooting-mon.rst

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Improve the front matter of the section "Troubleshooting Monitors" in doc/rados/troubleshooting/troubleshooting-mon.rst.
(cherry picked from commit e6e3fda2efb8f4a4345ba5f939baade844c5d582) …

reef: doc/rados: edit t-shooting-mon.rst

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Improve the front matter of the section "Troubleshooting Monitors" in doc/rados/troubleshooting/troubleshooting-mon.rst.
(cherry picked from commit e6e3fda2efb8f4a4345ba5f939baade844c5d582) …

quincy: doc/rados: edit t-shooting-mon.rst

---

doc/dev/mon-elections.rst
doc/rados/troubleshooting/troubleshooting-mon.rst

Follows https://github.com/ceph/ceph/pull/54417. …

doc/rados: edit t-mon "common issues" (3 of x)

---

src/mds/Locker.cc
src/mds/SimpleLock.h

backport tracker: https://tracker.ceph.com/issues/62523
---
backport of https://github.com/ceph/ceph/pull/52111
parent tracker: https://tracker.ceph.com/issues/44565
<details> …

pacific: ceph: allow xlock state to be LOCK_PREXLOCK when putting it

---

qa/suites/upgrade/quincy-x/filestore-remove-check/0-cluster/start.yaml

qa/tests: added - \(POOL_APP_NOT_ENABLED\) to the ignore list

---

doc/dev/mon-elections.rst
doc/rados/troubleshooting/troubleshooting-mon.rst

Follows https://github.com/ceph/ceph/pull/54417.
(cherry picked from commit 91ed10bc734bd93605b60c87037393d2704a16bc) …

quincy: doc/rados: edit t-mon "common issues" (3 of x)

---

doc/dev/mon-elections.rst
doc/rados/troubleshooting/troubleshooting-mon.rst

Follows https://github.com/ceph/ceph/pull/54417.
(cherry picked from commit 91ed10bc734bd93605b60c87037393d2704a16bc) …

reef: doc/rados: edit t-mon "common issues" (3 of x)

---

src/cls/CMakeLists.txt

cls: fix unable to link with system-installed fmt

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the fourth part of the section "Most Common Monitor Issues" in doc/rados/troubleshooting/troubleshooting-mon.rst.
Follows https://github.com/ceph/ceph/pull/54432. …

doc/rados: edit t-mon "common issues" (4 of x)

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the fourth part of the section "Most Common Monitor Issues" in doc/rados/troubleshooting/troubleshooting-mon.rst.
Follows https://github.com/ceph/ceph/pull/54432.
(cherry picked from commit f6b686ac3118507baab719f1587c8c360499e929) …

reef: doc/rados: edit t-mon "common issues" (4 of x)

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the fourth part of the section "Most Common Monitor Issues" in doc/rados/troubleshooting/troubleshooting-mon.rst.
Follows https://github.com/ceph/ceph/pull/54432.
(cherry picked from commit f6b686ac3118507baab719f1587c8c360499e929) …

quincy: doc/rados: edit t-mon "common issues" (4 of x)

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the fifth part of the section "Most Common Monitor Issues" in doc/rados/troubleshooting/troubleshooting-mon.rst.
Follows https://github.com/ceph/ceph/pull/54440. …

doc/rados: edit t-mon "common issues" (5 of x)

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the fifth part of the section "Most Common Monitor Issues" in doc/rados/troubleshooting/troubleshooting-mon.rst.
Follows https://github.com/ceph/ceph/pull/54440.
(cherry picked from commit d98222db9b4436841102d23c979f05a9d958bb1f) …

quincy: doc/rados: edit t-mon "common issues" (5 of x)

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the fifth part of the section "Most Common Monitor Issues" in doc/rados/troubleshooting/troubleshooting-mon.rst.
Follows https://github.com/ceph/ceph/pull/54440.
(cherry picked from commit d98222db9b4436841102d23c979f05a9d958bb1f) …

reef: doc/rados: edit t-mon "common issues" (5 of x)

---

doc/rados/configuration/ceph-conf.rst

Edit the first section of doc/rados/configuration/ceph-conf.rst. Initially I just wanted to change "series" to "set", but once I got my hands dirty I ended up simplifying some sentences. …

doc/config: edit "ceph-conf.rst"

---

doc/rados/configuration/ceph-conf.rst

Edit the first section of doc/rados/configuration/ceph-conf.rst. Initially I just wanted to change "series" to "set", but once I got my hands dirty I ended up simplifying some sentences.
(cherry picked from commit c886e05404ce9c50454d40e692ababdc55f346c6) …

quincy: doc/config: edit "ceph-conf.rst"

---

doc/rados/configuration/ceph-conf.rst

Edit the first section of doc/rados/configuration/ceph-conf.rst. Initially I just wanted to change "series" to "set", but once I got my hands dirty I ended up simplifying some sentences.
(cherry picked from commit c886e05404ce9c50454d40e692ababdc55f346c6) …

reef: doc/config: edit "ceph-conf.rst"

---

src/script/ptl-tool.py

ptl-tool: enable checkout of specific sha1 as base

---

src/client/Client.cc
src/mds/Capability.cc
src/mds/Capability.h
src/test/libcephfs/multiclient.cc

backport tracker: https://tracker.ceph.com/issues/61166
---
backport of https://github.com/ceph/ceph/pull/51500 and https://github.com/ceph/ceph/pull/52176
parent tracker: https://tracker.ceph.com/issues/57244 and https://tracker.ceph.com/issues/61781
<details>
- …

pacific: client: issue a cap release immediately if no cap exists

---

src/mgr/ActivePyModules.cc
src/mon/ConfigMap.cc
src/mon/ConfigMap.h
src/mon/ConfigMonitor.cc
src/test/mon/CMakeLists.txt
src/test/mon/test_config_map.cc

Taken out of #44069 to be excluded from future config profile support.
<details>
- …

mon/Config*: Cleanups and ConfigMap unit test

---

src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h

Plus a bit more effective file_map handling.
<details>
- `jenkins …

os/bluestore: add more bluefs perf counters

---

doc/start/hardware-recommendations.rst

doc/start: fix typo in hardware-recommendations.rst …

doc/start: fix typo in hardware-recommendations.rst

---

doc/start/hardware-recommendations.rst

(cherry picked from commit 48fd7ff1e13ccfeca04b9283b13641ce59316723) …

reef: doc/start: fix typo in hardware-recommendations.rst

---

doc/start/hardware-recommendations.rst

(cherry picked from commit 48fd7ff1e13ccfeca04b9283b13641ce59316723) …

quincy: doc/start: fix typo in hardware-recommendations.rst

---

doc/radosgw/notifications.rst
doc/radosgw/s3/bucketops.rst

Fixes: https://tracker.ceph.com/issues/63530
<details>
</details>

doc/rgw/notifications: specify which event types are enabled by default

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the text in the "Initial Troubleshooting" section of doc/rados/troubleshooting/troubleshooting-mon.rst.
- …

doc/rados: edit "troubleshooting-mon"

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the text in the "Initial Troubleshooting" section of doc/rados/troubleshooting/troubleshooting-mon.rst.
(cherry picked from commit fa8129a7466b3b48b56124eaf1d9ca8e8fd51fbc) …

reef: doc/rados: edit "troubleshooting-mon"

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the text in the "Initial Troubleshooting" section of doc/rados/troubleshooting/troubleshooting-mon.rst.
(cherry picked from commit fa8129a7466b3b48b56124eaf1d9ca8e8fd51fbc) …

quincy: doc/rados: edit "troubleshooting-mon"

---

src/client/Client.cc
src/mds/Server.cc
src/mds/Server.h
src/messages/MClientSession.h

Update the oldest_client_tid via the session renew caps msg to
make sure that the MDSs won't pile up the completed request list
in a very large size.
Fixes: https://tracker.ceph.com/issues/63364 …

mds,client: update the oldest_client_tid via the renew caps

---

qa/tasks/cephfs/test_snap_schedules.py

Fixes: https://tracker.ceph.com/issues/62706 …

qa: use correct imports to resolve fuse_mount and kernel_mount

---

qa/suites/rbd/mirror-thrash/workloads/rbd-mirror-journal-stress-workunit.yaml
qa/suites/rbd/mirror-thrash/workloads/rbd-mirror-snapshot-stress-workunit-exclusive-lock.yaml
qa/suites/rbd/mirror-thrash/workloads/rbd-mirror-snapshot-stress-workunit-fast-diff.yaml
qa/suites/rbd/mirror-thrash/workloads/rbd-mirror-snapshot-stress-workunit-minimum.yaml
qa/suites/rbd/mirror/workloads/rbd-mirror-journal-bootstrap-workunit.yaml
qa/suites/rbd/mirror/workloads/rbd-mirror-snapshot-bootstrap-workunit.yaml
qa/workunits/rbd/rbd_mirror_helpers.sh
qa/workunits/rbd/rbd_mirror_stress.sh

With the introduction of RBD_MIRROR_MODE environment variable in https://github.com/ceph/ceph/pull/48508, RBD_MIRROR_MODE & MIRROR_IMAGE_MODE were largely duplicating each other.
Fixes: https://tracker.ceph.com/issues/63431
Signed-off-by: Suyash Dongre suyashd999@gmail.com …

qa/suites/rbd: Cleanup of MIRROR_IMAGE_MODE

---

src/rgw/services/svc_notify.cc

backport tracker: https://tracker.ceph.com/issues/59361
---
backport of https://github.com/ceph/ceph/pull/50707
parent tracker: https://tracker.ceph.com/issues/59217

pacific: rgw: fix rgw cache invalidation after unregister_watch() error

---

src/rgw/driver/rados/rgw_bucket.cc

https://tracker.ceph.com/issues/63296 …

rgw/multisite: set versioning status in archive zone upon bucket creation

---

src/cephadm/cephadmlib/templating.py

Implement a workaround for the jinja2 package loader not correctly finding a template inside the cephadmlib package when run as a zipapp. See docstring in the shim class for more details.
<details>
- …

cephadm: workaround issues running cephadm with relative path

---

monitoring/ceph-mixin/dashboards_out/ceph-cluster.json

Fixes: https://tracker.ceph.com/issues/62969
[Screencast from 2023-10-11 12-22-17.webm](https://github.com/ceph/ceph/assets/66050535/1aa0da8d-5029-4217-b695-bdd6a9b87178)
<details> …

mgr/dashboard: Show the OSDs Out and Down panels as red whenever an OSD is in Out or Down state in Ceph Cluster grafana dashboard

---

PendingReleaseNotes

Adds release notes for the fix added in #47560
Signed-off-by: Prashant D <pdhange@redhat.com> …

PendingReleaseNotes: Add note for POOL_APP_NOT_ENABLED

---

ceph-menv/README

ceph-menv:fix typo in README
Signed-off-by: yu.wang <wangyu@wyu.space>
- Component …

ceph-menv:fix typo in README

---

qa/workunits/rados/test_dedup_tool.sh
src/tools/ceph_dedup_tool.cc

Current fpstore unconditionally adds a pair <fingerprint, count> without consdiering meemory usage. This might lead to out of memory situation, so this commit added threshold logic.
<details>
- `jenkins …

tools/ceph-dedup-tool: set memory threshold not to cause excessive  memory usage

---

doc/man/8/ceph-osd.rst

Improve the English grammar and reduce the ambiguity and unclear writing in the "Description" section of doc/man/8/ceph-osd.rst. …

doc/man: edit ceph-osd description

---

doc/man/8/ceph-osd.rst

Improve the English grammar and reduce the ambiguity and unclear writing in the "Description" section of doc/man/8/ceph-osd.rst.
(cherry picked from commit 2921dacf1e7b7ad2aa62f52d6e8914d8ec50a610) …

reef: doc/man: edit ceph-osd description

---

doc/man/8/ceph-osd.rst

Improve the English grammar and reduce the ambiguity and unclear writing in the "Description" section of doc/man/8/ceph-osd.rst.
(cherry picked from commit 2921dacf1e7b7ad2aa62f52d6e8914d8ec50a610) …

quincy: doc/man: edit ceph-osd description

---

qa/workunits/kernel_untar_build.sh

Replace old tarball with url link to linux-6.5.10.tar.xz
Fixes: https://tracker.ceph.com/issues/57655 …

qa: run kernel_untar_build with newer tarball

---

doc/start/documenting-ceph.rst

Update "Quincy" to "Reef" and "Pacific" to "Quincy" in the section "Viewing Old Ceph Documentation" in /doc/start/documenting-ceph.rst. …

doc/start: update release names

---

doc/start/documenting-ceph.rst

Update "Quincy" to "Reef" and "Pacific" to "Quincy" in the section "Viewing Old Ceph Documentation" in /doc/start/documenting-ceph.rst.
(cherry picked from commit 83ff8f2b67f1a784ebb3ca7d0b7ca2c385f99343) …

quincy: doc/start: update release names

---

doc/start/documenting-ceph.rst

Update "Quincy" to "Reef" and "Pacific" to "Quincy" in the section "Viewing Old Ceph Documentation" in /doc/start/documenting-ceph.rst.
(cherry picked from commit 83ff8f2b67f1a784ebb3ca7d0b7ca2c385f99343) …

reef: doc/start: update release names

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the section "Understanding mon_status" in …

doc/rados: edit "understanding mon_status"

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the section "Using the Monitor's Admin Socket" in doc/rados/troubleshooting/troubleshooting-mon.rst.
(cherry picked from commit f627445806dadcc956fe1256cfc3886cb5b8e1ef) …

reef: doc/rados: edit "Using the Monitor's Admin Socket"

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the section "Understanding mon_status" in
(cherry picked from commit 08c16aa113dc22dfec3387f575752a5049b7af42) …

reef: doc/rados: edit "understanding mon_status"

---

src/crimson/osd/osd_operations/logmissing_request.cc
src/crimson/osd/osd_operations/logmissing_request_reply.cc
src/crimson/osd/osd_operations/snaptrim_event.cc
src/crimson/osd/pg.cc

Sanitized backtraces attached to each commit. …

crimson/osd/osd_operations/snaptrim_event: lifetime fixes

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the section "Recovering a monitor's broken monmap" in doc/rados/troubleshooting/troubleshooting-mon.rst.
(cherry picked from commit 6ccb9f3ca10e814c42effb49c8441c23da911adc) …

reef: doc/rados: edit "recovering broken monmap"

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the section "Recovering a monitor's broken monmap" in doc/rados/troubleshooting/troubleshooting-mon.rst.
(cherry picked from commit 6ccb9f3ca10e814c42effb49c8441c23da911adc) …

quincy: doc/rados: edit "recovering broken monmap"

---

src/rgw/rgw_flight.cc

The interface to the load_buckt call changed when tenant and bucket name are specified. This updates the flight call to that change. …

rgw: fix flight load_bucket call

---

do_cmake.sh

If do_cmake.sh is being exeuted on Fedora 39 set Python version to 3.12.
- …

do_cmake.sh: set python version for Fedora 39

---

src/osd/PrimaryLogPG.cc

backport of https://github.com/ceph/ceph/pull/54571
parent tracker: https://tracker.ceph.com/issues/63586
- Tracker …

pacific: osd: log the number of extents for sparse read

---

src/osd/PrimaryLogPG.cc

backport of https://github.com/ceph/ceph/pull/54571
parent tracker: https://tracker.ceph.com/issues/63586
- Tracker …

reef: osd: log the number of extents for sparse read

---

src/osd/PrimaryLogPG.cc

backport of https://github.com/ceph/ceph/pull/54571
parent tracker: https://tracker.ceph.com/issues/63586
- Tracker …

quincy: osd: log the number of extents for sparse read

---

src/msg/async/AsyncMessenger.cc

(cherry picked from commit 36fc1f353436193a0b3e95af27edbf0e6cc4f4c2)
Fixes (Backport): https://tracker.ceph.com/issues/63023
Original ticket: https://tracker.ceph.com/issues/62395
Original PR: https://github.com/ceph/ceph/pull/52930
<details> …

pacific: msg/AsyncMessenger: re-evaluate the stop condition when woken up in 'wait()'

---

doc/cephfs/health-messages.rst
qa/tasks/ceph_manager.py
qa/tasks/ceph_test_case.py
qa/tasks/cephfs/test_client_limits.py
src/mds/SessionMap.cc
src/mds/SessionMap.h

backport tracker: https://tracker.ceph.com/issues/63339
---
backport of https://github.com/ceph/ceph/pull/49844 and https://github.com/ceph/ceph/pull/49766
parent tracker: https://tracker.ceph.com/issues/57985 …

reef: qa: fix incorrectly using the wait_for_health() helper

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Format definition lists in the section "Do I need to restart a monitor to adjust debug levels?" in …

doc/rados: format sections in tshooting-mon.rst

---

doc/radosgw/session-tags.rst

doc/radosgw: Fix JSON typo in Principal Tag example code snippet

---

doc/radosgw/session-tags.rst

Signed-off-by: Daniel Parkes <dparkes@redhat.com>
(cherry picked from commit 68729c951dd3acdbdf86c3ce895a55bbab1aeb89) …

quincy: doc/radosgw: Fix JSON typo in Principal Tag example code snippet

---

doc/radosgw/session-tags.rst

Signed-off-by: Daniel Parkes <dparkes@redhat.com>
(cherry picked from commit 68729c951dd3acdbdf86c3ce895a55bbab1aeb89) …

reef: doc/radosgw: Fix JSON typo in Principal Tag example code snippet

---

src/rgw/CMakeLists.txt

In particular, do not link intermediate dependencies nor librgw.so.2 with a custom allocator (normally tcmalloc).
This prevents illegal behavior due to mismatched allocators when run under nfs-ganesha or other consumers.
Fixes: https://tracker.ceph.com/issues/63394 …

rgw: link only radosgw with ALLOC_LIBS

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the section "Client can't connect or mount" in the file doc/rados/troubleshooting/troubleshooting-mon.rst.
- …

doc/rados: edit "client can't connect..."

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the section "Client can't connect or mount" in the file doc/rados/troubleshooting/troubleshooting-mon.rst.
(cherry picked from commit ec298091b5e754293e798c90fc8afc3e4504d632) …

reef: doc/rados: edit "client can't connect..."

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the section "Monitor Store Failures" in …

doc/rados: edit "monitor store failures"

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the section "Monitor Store Failures" in
(cherry picked from commit 0a1ce0016871dc2ce29d4e7eff564a199d54c6e3) …

reef: doc/rados: edit "monitor store failures"

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the section "Monitor Store Failures" in
(cherry picked from commit 0a1ce0016871dc2ce29d4e7eff564a199d54c6e3) …

quincy: doc/rados: edit "monitor store failures"

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the section "Everything Failed! Now what?" in doc/rados/troubleshooting/troubleshooting-mon.rst.
- Tracker …

doc/rados: edit "Everything Failed! Now What?"

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the section "Everything Failed! Now what?" in doc/rados/troubleshooting/troubleshooting-mon.rst.
Co-authored-by: Anthoy D'Atri <anthony.datri@gmail.com>
(cherry picked from commit d8cd49259d797304adfbdb8eb46110e8b749256e) …

reef: doc/rados: edit "Everything Failed! Now What?"

---

doc/rados/troubleshooting/troubleshooting-mon.rst

Edit the section "Everything Failed! Now what?" in doc/rados/troubleshooting/troubleshooting-mon.rst.
Co-authored-by: Anthoy D'Atri <anthony.datri@gmail.com>
(cherry picked from commit d8cd49259d797304adfbdb8eb46110e8b749256e) …

quincy: doc/rados: edit "Everything Failed! Now What?"

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/tests/test_rgw.py

Fixes: https://tracker.ceph.com/issues/63564 …

mgr/dashboard: get rgw port from ssl_endpoint

---

src/pybind/mgr/dashboard/plugins/feature_toggles.py

Fixes: https://tracker.ceph.com/issues/63357 …

quincy: mgr/dashboard: disable dashboard v3 in quincy

---

src/rgw/rgw_rest_sts.cc

backport tracker: https://tracker.ceph.com/issues/52778
---
backport of https://github.com/ceph/ceph/pull/41174
parent tracker: https://tracker.ceph.com/issues/50721

pacific: rgw/sts: code to fetch certs using .well-known/openid-configuration url

---

doc/rados/operations/placement-groups.rst

Change "power of 2" to "power of two" in …

doc/rados: ops/pgs: s/power of 2/power of two

---

doc/rados/operations/placement-groups.rst

Change "power of 2" to "power of two" in
(cherry picked from commit ca819633219b7978ece2201b1ab0d7dc9c0faee8) …

quincy: doc/rados: ops/pgs: s/power of 2/power of two

---

doc/rados/operations/placement-groups.rst

Change "power of 2" to "power of two" in
(cherry picked from commit ca819633219b7978ece2201b1ab0d7dc9c0faee8) …

reef: doc/rados: ops/pgs: s/power of 2/power of two

---

qa/tasks/radosgw_admin.py

Fixes: https://tracker.ceph.com/issues/63583 …

qa: remove vstart runner from radosgw_admin task

---

src/pybind/mgr/volumes/fs/async_cloner.py
src/pybind/mgr/volumes/fs/operations/versions/subvolume_v1.py
src/pybind/mgr/volumes/fs/operations/versions/subvolume_v2.py

mgr/vol: make some improvements

---

src/pybind/mgr/dashboard/ci/cephadm/start-cluster.sh

The old link points to a directory that now only contains a README saying
---
ATTENTION
======================================
The contents of this directory have been moved to our archives available at:
http://archives.fedoraproject.org/pub/archive/fedora/
If you are having troubles finding something there please stop by #fedora-admin on irc.freenode.net
---
so I think we either need to start using a newer fedora or point to the archive link. This commit is currently doing the latter.
Signed-off-by: Adam King <adking@redhat.com>
(cherry picked from commit f317cef9e3f6255898a67528ab0e421899d5d3f5)
- If you are submitting a fix for a stable branch …

reef: mgr/dashboard: update fedora link for dashboard-cephadm-e2e test

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/bucket-tag-modal/bucket-tag-modal.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/bucket-tag-modal/bucket-tag-modal.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/bucket-tag-modal/bucket-tag-modal.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/rgw_client.py

Add the tags field when creating and editing a bucket
Fixes: https://tracker.ceph.com/issues/63412
Signed-off-by: Pedro Gonzalez Gomez <pegonzal@redhat.com> …

mgr/dashboard: add tags to edit bucket

---

doc/glossary.rst

Add the term "Monitor Store" to the glossary.
(cherry picked from commit 35d168826fd7b96cb73c6d799f7267a92f3453e9) …

quincy: doc/glossary.rst: add "Monitor Store"

---

doc/glossary.rst

Add the term "Monitor Store" to the glossary.
(cherry picked from commit 35d168826fd7b96cb73c6d799f7267a92f3453e9) …

reef: doc/glossary.rst: add "Monitor Store"

---

src/pybind/rados/rados.pyx
src/test/pybind/test_rados.py

backport tracker: https://tracker.ceph.com/issues/63401
backport of https://github.com/ceph/ceph/pull/49486
parent tracker: https://tracker.ceph.com/issues/58304
(cherry picked from commit 1c64c6be303f5ed4110468101a01576508468a74) …

pacific: pybind/rados: fix missed changes for PEP484 style type annotations

---

src/crimson/common/shared_lru.h
src/crimson/mgr/client.h
src/crimson/osd/osd.cc
src/crimson/osd/osd.h
src/crimson/osd/osd_meta.cc
src/crimson/osd/osd_meta.h
src/crimson/osd/pg.h
src/crimson/osd/pg_shard_manager.cc
src/crimson/osd/pg_shard_manager.h
src/crimson/osd/shard_services.cc
src/crimson/osd/shard_services.h

Following #52545 classic counterpart. …

crimson/osd: introduce osdmap trimming 

---

doc/rados/operations/stretch-mode.rst

Remove a section of doc/rados/operations/stretch-mode.rst that I wrongly re-included after its removal. The request for this (re)-removal is here: https://github.com/ceph/ceph/pull/54689#discussion_r1413007655. …

doc/rados: repair stretch-mode.rst

---

doc/cephfs/health-messages.rst
qa/suites/fs/functional/tasks/client-recovery.yaml
qa/tasks/cephfs/test_client_recovery.py
qa/tasks/mgr/mgr_test_case.py
src/common/options/mds.yaml.in
src/mds/Beacon.cc
src/mds/MDSRank.cc
src/mds/Server.cc
src/mds/Server.h
src/messages/MMDSBeacon.h
src/osd/OSDMap.cc
src/osd/OSDMap.h

backport tracker: https://tracker.ceph.com/issues/61842, https://tracker.ceph.com/issues/62443, https://tracker.ceph.com/issues/63271
parent tracker: https://tracker.ceph.com/issues/58023, https://tracker.ceph.com/issues/61907, https://tracker.ceph.com/issues/63105
backport of https://github.com/ceph/ceph/pull/49971, https://github.com/ceph/ceph/pull/52342, https://github.com/ceph/ceph/pull/53839/ …

reef: mds: do not evict clients if OSDs are laggy

---

doc/cephfs/quota.rst
qa/tasks/cephfs/test_quota.py
qa/workunits/fs/quota/quota.sh
src/mds/Server.cc

backport tracker: https://tracker.ceph.com/issues/62738
parent tracker: https://tracker.ceph.com/issues/55940
backport of https://github.com/ceph/ceph/pull/49008, https://github.com/ceph/ceph/pull/50493
<details> …

reef: mds: accept human readable values for quotas

---

doc/man/8/cephfs-shell.rst
src/tools/cephfs/shell/cephfs-shell

Fixes: https://tracker.ceph.com/issues/62998
Parent Tracker: https://tracker.ceph.com/issues/62739
Parent PR: https://github.com/ceph/ceph/pull/53529
<details>
- `jenkins …

reef: cephfs-shell: remove distutils Version classes because they're deprecated

---

src/client/Client.cc
src/client/Client.h
src/client/Inode.cc
src/client/MetaSession.h

backport tracker: https://tracker.ceph.com/issues/62916 and https://tracker.ceph.com/issues/62520
---
backport of https://github.com/ceph/ceph/pull/44255 and https://github.com/ceph/ceph/pull/52335
parent tracker: https://tracker.ceph.com/issues/44916 and https://tracker.ceph.com/issues/56698
<details> …

pacific: client: fix sync fs to force flush mdlog for all sessions

---

doc/radosgw/multisite.rst

Repair the formatting of a string that had a string inside backticks that itself was inside double asterisks. The presence of the asterisks around the entire string caused the backticks to appear in the rendered documentation.
(cherry picked from commit 08ac3114e9fdb4fe7260002639058ded6e47a5ee) …

reef: doc/radosgw: fix formatting

---

src/pybind/rbd/setup.py
src/test/pybind/test_rbd.py

This fixes errors like below when compiling with cython 3:
```
Error compiling Cython file:
------------------------------------------------------------ ...
"""
name = cstr(name, 'name')
cdef:
rados_ioctx_t _ioctx = convert_ioctx(ioctx)
char *_name = name
librbd_progress_fn_t _prog_cb = &no_op_progress_callback
^
------------------------------------------------------------
rbd.pyx:760:44: Cannot assign type 'int (*)(uint64_t, uint64_t, void *) except? -1' to 'librbd_progress_fn_t'. Exception values are incompatible. Suggest adding 'noexcept' to type 'int (uint64_t, uint64_t, void *) except? -1'.
Error compiling Cython file:
------------------------------------------------------------
...
cdef:
rbd_completion_t completion
PyObject* p_completion_obj= <PyObject*>completion_obj
with nogil: …
```

 pybind/rbd: fix compilation with cython3

---

src/librados/snap_set_diff.cc
src/librbd/io/ObjectRequest.cc
src/test/librbd/io/test_mock_ObjectRequest.cc
src/test/librbd/test_librbd.cc

librbd: fix regressions in ObjectListSnapsRequest

---

doc/cephfs/cephfs-mirroring.rst

doc: add supported file types in cephfs-mirroring.rst

---

doc/cephfs/cephfs-mirroring.rst

(cherry picked from commit 3d44e5dfdc83e33167ee2b63caf7c4fb2d34f6ba) …

reef: doc: add supported file types in cephfs-mirroring.rst

---

src/rgw/driver/rados/rgw_data_sync.cc

https://tracker.ceph.com/issues/63378 …

rgw/multisite: fix marker_tracker flush() call in incremental sync

---

src/os/bluestore/AvlAllocator.cc
src/os/bluestore/BlueFS.cc
src/os/bluestore/BtreeAllocator.cc
src/os/bluestore/StupidAllocator.cc
src/os/bluestore/StupidAllocator.h
src/os/bluestore/fastbmap_allocator_impl.cc
src/test/objectstore/Allocator_test.cc
src/test/objectstore/fastbmap_allocator_test.cc
src/test/objectstore/store_test.cc

Fixes: https://tracker.ceph.com/issues/63618
Fixes: https://tracker.ceph.com/issues/62815 …

reef: os/bluestore: get rid off resulting lba alignment in allocators

---

src/rgw/rgw_lib.cc
src/rgw/rgw_main.cc

fixes: https://tracker.ceph.com/issues/63644 …

add checking for rgw frontend init

---

src/vstart.sh

enables dbstore for rgw_backend_store and rgw_config_store, allowing vstart to run without any mons or osds. database files are put under the dev subdirectory
when rgw_store=posix, the posix filter is added on top of dbstore
<details>
</details>

vstart: add --rgw_store option for rados|dbstore|posix

---

doc/radosgw/role.rst

Format the POST methods so that they appear in the rendered text as examples of POST API calls and not as plain old unformatted text, which is how they looked before this commit. The content of these API calls remains to be tested and confirmed to work, but this is a first step. …

doc/radosgw: format POST statements

---

doc/radosgw/role.rst

Format the POST methods so that they appear in the rendered text as examples of POST API calls and not as plain old unformatted text, which is how they looked before this commit. The content of these API calls remains to be tested and confirmed to work, but this is a first step.
(cherry picked from commit 1c0901cf8503ca8486dee8875ce85adaa464b127) …

reef: doc/radosgw: format POST statements

---

doc/radosgw/role.rst

Format the POST methods so that they appear in the rendered text as examples of POST API calls and not as plain old unformatted text, which is how they looked before this commit. The content of these API calls remains to be tested and confirmed to work, but this is a first step.
(cherry picked from commit 1c0901cf8503ca8486dee8875ce85adaa464b127) …

quincy: doc/radosgw: format POST statements

---

doc/radosgw/role.rst

Clarify the front matter in doc/radosgw/role.rst.
- …

doc/radosgw: edit front matter - role.rst

---

doc/radosgw/role.rst

Clarify the front matter in doc/radosgw/role.rst.
(cherry picked from commit 9d10361961e01c4d60f600f6e7ed106d6203e554) …

reef: doc/radosgw: edit front matter - role.rst

---

doc/radosgw/role.rst

Clarify the front matter in doc/radosgw/role.rst.
(cherry picked from commit 9d10361961e01c4d60f600f6e7ed106d6203e554) …

quincy: doc/radosgw: edit front matter - role.rst

---

src/common/mempool.cc
src/include/mempool.h
src/test/test_c2c.cc
src/test/test_mempool.cc

Follow up https://github.com/ceph/ceph/pull/52404 (as REF)
By globally disabling mempool counters, the peak performance (OPT, this PR) is ~1.8x better than REF, ~6.7x better than Async for the same set of tests:
<details>
- `jenkins …

mempool: avoid true sharing for the counters, with crimson

---

src/crimson/osd/object_context_loader.cc
src/crimson/osd/object_context_loader.h
src/crimson/osd/osd_operations/client_request.cc
src/crimson/osd/osd_operations/client_request.h
src/crimson/osd/osd_operations/client_request_common.cc
src/crimson/osd/osd_operations/client_request_common.h
src/crimson/osd/osd_operations/common/pg_pipeline.h
src/crimson/osd/osd_operations/internal_client_request.cc
src/crimson/osd/pg.cc
src/crimson/osd/pg.h
src/crimson/osd/pg_backend.cc
src/crimson/osd/pg_recovery.cc
src/crimson/osd/pg_recovery.h
src/crimson/osd/pg_recovery_listener.h
src/crimson/osd/replicated_recovery_backend.cc
src/crimson/osd/replicated_recovery_backend.h

crimson/osd/osd_operations/client_request: recover the head and other necessary objects before proceeding

---

src/crimson/osd/pg_recovery.cc

crimson/osd/pg_recovery: recover head before recovering clones

---

src/crimson/osd/pg.cc

Discarding watches' states while iterating cached obcs might have the following problem:
1. discard a watch's state
2. the corresponding object context's use_count drops to zero
3. the object context is unreferenced by obc lru
4. obc is deleted from obc lru by lru's evict()
5. obc iteration is corrupted …

crimson/osd/pg: discard watches' states after iterating all cached obcs

---

src/crimson/osd/pg_recovery.cc
src/crimson/osd/recovery_backend.h

UrgentRecovery and other recoveries may collide when doing `PGRecovery::add_recovering`, which is not an error. We should allow this to happen
<details>
- …

crimson/osd/pg_recovery: avoiding duplicated object recovering

---

src/crimson/osd/ops_executer.cc
src/crimson/osd/osd_operations/snaptrim_event.cc
src/crimson/osd/osd_operations/snaptrim_event.h
src/crimson/osd/pg.cc
src/crimson/osd/pg.h

Otherwise, PG::projected_last_update's epoch is always outdated, which would cause failure of asserts in the backfilling code
Xuehan Xu <xuxuehan@qianxin.com>
<details>
- …

crimson/osd/pg: set PG::projected_last_update when submitting transactions

---

src/test/librbd/journal/test_Stress.cc

test/librbd: avoid config-related crashes in DiscardWithPruneWriteOverlap

---

src/test/librbd/test_librbd.cc

... to avoid valgrind reporting a memory leak on ImageCtx.
- …

test/librbd: close image in DiffIterateDeterministic

---

PendingReleaseNotes
ceph.spec.in
qa/cephfs/begin/0-install.yaml
qa/suites/fs/shell/distro
qa/suites/fs/shell/tasks/cephfs-shell.yaml

qa: add support/qa for cephfs-shell on CentOS 9 / RHEL9

---

src/pybind/mgr/dashboard/controllers/cephfs.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-tabs/cephfs-tabs.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-snapshot-schedule.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-snapshot-schedule.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/snapshot-schedule.ts
src/pybind/mgr/dashboard/openapi.yaml

Added ```api/cephfs/snaphost/schedule``` list endpoint to cephfs API. Added basic list of snapshot schedules under a new tab named "Snapshot schedules" for each cephfs item. …

mgr/dashboard: added snap-schedule api and ui list

---

src/pybind/mgr/devicehealth/module.py

Where DATETIME means "seconds since epoch".
Fixes: https://tracker.ceph.com/issues/63433 …

pybind/mgr/devicehealth: replace SMART data if exists for same DATETIME

---

src/ceph-volume/ceph_volume/util/device.py

Fixes: https://tracker.ceph.com/issues/63502
Signed-off-by: Dillon Amburgey <dillona@dillona.com> …

ceph-volume: Use safe accessor to get TYPE info

---

doc/radosgw/role.rst

Properly format the section "Create a Role" in the file doc/radosgw/role.rst.
(cherry picked from commit fa6ad94f3afc6d11c3ed243d66c96a666e973bde) …

reef: doc/radosgw: format "Create a Role"

---

doc/radosgw/role.rst

Properly format the section "Create a Role" in the file doc/radosgw/role.rst.
(cherry picked from commit fa6ad94f3afc6d11c3ed243d66c96a666e973bde) …

quincy: doc/radosgw: format "Create a Role"

---

qa/suites/fs/fscrypt/overrides/osd.yaml

We need to get more debug logs from bluestore to know what exactly has happened for the extent map.
URL: https://tracker.ceph.com/issues/63586 …

qa/fscrypt: enable debug log for bluestore

---

src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/test/objectstore/store_test.cc

Plus refactor spillover test cases.
<details> …

os/bluestore: rework vselector calls.

---

src/cephadm/cephadm.py

The meaning of the `--volume` option is to bind mount a volume. …

cephadm: Fix `cephadm shell` command help message

---

src/rgw/driver/daos/rgw_sal_daos.cc
src/rgw/driver/motr/rgw_sal_motr.cc
src/rgw/driver/posix/rgw_sal_posix.cc
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/rgw_op.cc
src/rgw/rgw_op.h
src/rgw/rgw_sal_dbstore.cc
src/test/rgw/bucket_notification/test_bn.py

Fixes: https://tracker.ceph.com/issues/63532 …

RGW: pubsub publish commit with etag populated

---

src/librados/snap_set_diff.cc
src/librbd/api/DiffIterate.cc
src/librbd/deep_copy/ImageCopyRequest.cc
src/librbd/object_map/DiffRequest.cc
src/librbd/object_map/DiffRequest.h
src/librbd/object_map/Types.h
src/test/cli-integration/rbd/snap-diff.t
src/test/librbd/deep_copy/test_mock_ImageCopyRequest.cc
src/test/librbd/object_map/test_mock_DiffRequest.cc
src/test/librbd/test_librbd.cc
src/test/pybind/test_rbd.py

librbd: don't report HOLE_UPDATED when diffing against a hole

---

src/rgw/driver/dbstore/dbstore_main.cc
src/rgw/rgw_admin.cc
src/rgw/rgw_es_main.cc
src/rgw/rgw_jsonparser.cc
src/rgw/rgw_main.cc
src/rgw/rgw_multiparser.cc
src/rgw/rgw_object_expirer.cc
src/rgw/rgw_polparser.cc
src/rgw/rgw_token.cc

rgw: Add coverity annotations for uncaught exceptions in standalone binaries

---

.gitignore
doc/architecture.rst
doc/install/index.rst
doc/rbd/index.rst
doc/rbd/libvirt.rst
doc/rbd/rbd-snapshot.rst
doc/start/documenting-ceph.rst
doc/start/hardware-recommendations.rst

doc: Improve documentation regarding OpenNebula integration with ceph

---

.gitignore
doc/architecture.rst
doc/install/index.rst
doc/rbd/index.rst
doc/rbd/libvirt.rst
doc/rbd/rbd-snapshot.rst
doc/start/documenting-ceph.rst
doc/start/hardware-recommendations.rst

- Exclude doc build output from git
- Fix missing doc build dependency
- Also includes some involuntary automatically persistent linting by vscode
Co-authored-by: Ilya Dryomov <idryomov@redhat.com>
Signed-off-by: Daniel Clavijo <dclavijo@opennebula.io>
(cherry picked from commit ee2ee31d3f72a2ee63f9d28bbaf6045657f43ee6)
- When …

reef: docs: Add information about OpenNebula integration

---

doc/releases/index.rst
doc/releases/reef.rst
doc/releases/releases.yml

doc: Add Reef 18.2.1 release notes

---

src/crimson/osd/osd_operations/client_request.h
src/crimson/osd/osd_operations/client_request_common.cc
src/crimson/osd/osd_operations/client_request_common.h
src/crimson/osd/pg.cc
src/os/bluestore/BlueStore.cc

crimson: misc fixes

---

doc/releases/reef.rst

Followup to https://github.com/ceph/ceph/pull/54506.
- …

doc/releases: specify dashboard improvements

---

src/common/weighted_shuffle.h
src/test/test_weighted_shuffle.cc

https://tracker.ceph.com/issues/62645
<details>
- `jenkins …

 common/weighted_shuffle: don't feed std::discrete_distribution with all-zero weights

---

src/kv/rocksdb_cache/ShardedCache.h

Resolve three warning issues in the derived classes overriding base class virtual functions with mismatched parameter lists at lines 69, 72, and 74 in src/kv/rocksdb_cache/ShardedCache.h.
```
with ../src/kv/rocksdb_cache/ShardedCache.h:74:16: warning:   by 'virtual bool rocksdb_cache::ShardedCache::Release(rocksdb::Cache::Handle*, bool)' [-Woverloaded-virtual]
virtual bool Release(rocksdb::Cache::Handle* handle, bool force_erase = false) override;
^~~~~~~
../src/kv/rocksdb_cache/ShardedCache.h:72:35: warning:   by 'virtual rocksdb::Cache::Handle* rocksdb_cache::ShardedCache::Lookup(const rocksdb::Slice&, rocksdb::Statistics*)' [-Woverloaded-virtual]
virtual rocksdb::Cache::Handle* Lookup(const rocksdb::Slice& key, rocksdb::Statistics* stats) override;
^~~~~~ …
```

kv: resolve three compilation warnings

---

src/common/buffer.cc
src/os/bluestore/BlueStore.cc

core: silent a couple of compiler warnings on uninitialized vars.

---

doc/man/8/ceph-objectstore-tool.rst
src/tools/ceph_objectstore_tool.cc

tools/ceph_objectstore_tool: Support get/set/superblock

---

doc/radosgw/compression.rst

Improve the grammar and simplify the sentence structure of doc/radosgw/compression.rst. This commit is made in anticipation of a near-future commit that will list the compression algorithms available to users of Ceph. …

doc/radosgw: edit compression.rst

---

.gitignore
doc/architecture.rst
doc/install/index.rst
doc/rbd/index.rst
doc/rbd/libvirt.rst
doc/rbd/rbd-snapshot.rst
doc/start/documenting-ceph.rst
doc/start/hardware-recommendations.rst

- Exclude doc build output from git
- Fix missing doc build dependency
- Also includes some involuntary automatically persistent linting by vscode
Co-authored-by: Ilya Dryomov <idryomov@redhat.com>
Signed-off-by: Daniel Clavijo <dclavijo@opennebula.io>
(cherry picked from commit ee2ee31d3f72a2ee63f9d28bbaf6045657f43ee6)
- When …

quincy: docs: Add information about OpenNebula integration

---

doc/radosgw/compression.rst

Improve the grammar and simplify the sentence structure of doc/radosgw/compression.rst. This commit is made in anticipation of a near-future commit that will list the compression algorithms available to users of Ceph.
(cherry picked from commit 84c5d2c828c2fbd70bdeadedd341ca42ddb1c20c) …

reef: doc/radosgw: edit compression.rst

---

doc/radosgw/compression.rst

Improve the grammar and simplify the sentence structure of doc/radosgw/compression.rst. This commit is made in anticipation of a near-future commit that will list the compression algorithms available to users of Ceph.
(cherry picked from commit 84c5d2c828c2fbd70bdeadedd341ca42ddb1c20c) …

quincy: doc/radosgw: edit compression.rst

---

doc/radosgw/compression.rst

List supported compression plugins in doc/radosgw/compression.rst.
- Component …

doc/radosgw: list supported plugins-compression.rst

---

src/pybind/mgr/balancer/module.py

RCOS Project
Related Trello: https://trello.com/c/pCFe06hW/589-balancer-report-last-change-that-was-made
Signed-off-by: Christopher Poon <poon3@rpi.edu>
Signed-off-by: Zuriel Aviles <avilez@rpi.edul>
Signed-off-by: Nico Wang <wangn4@rpi.edu>
We have recently introduced a detailed command to check the status of our balancer. This command displays the location of pg_up_map items where they are being transferred when the balancer runs. The primary objective of this command is to obtain a better understanding of the balancer's behavior in terms of transferring pgs. This will help us identify when the balancing is taking place in the effort to improve the balancing process to evenly distribute pgs in the balancing process.
- To sign and title your commits, please refer to [Submitting Patches …

Improve Ceph Balancer Status Output

---

doc/radosgw/compression.rst

List supported compression plugins in doc/radosgw/compression.rst.
(cherry picked from commit 64b0eb7d050755aab58a4ec7bcb218f9ced19921) …

reef: doc/radosgw: list supported plugins-compression.rst

---

doc/radosgw/admin.rst

Edit doc/radosgw/admin.rst to the end of the section "User Management". Correct grammar (mostly awkward prepositions) and tidy up weird clauses.
(cherry picked from commit 819b2974e64548fcf66423cca94a785887fd7d07) …

reef: doc/radosgw: edit admin.rst 1 of x

---

doc/radosgw/admin.rst

Edit doc/radosgw/admin.rst to the end of the section "User Management". Correct grammar (mostly awkward prepositions) and tidy up weird clauses.
(cherry picked from commit 819b2974e64548fcf66423cca94a785887fd7d07) …

quincy: doc/radosgw: edit admin.rst 1 of x

---

doc/radosgw/notifications.rst
doc/radosgw/s3/bucketops.rst

Fixes: https://tracker.ceph.com/issues/63530
Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>
(cherry picked from commit 4ea87307e7af088dc056c1c7785aef7ca9be78b1) …

quincy: doc/rgw/notifications: specify which event types are enabled by default

---

doc/radosgw/admin.rst

Edit the section "Create a User" in doc/radosgw/admin.rst.
- …

doc/radosgw: admin.rst - edit "Create a User"

---

doc/radosgw/admin.rst

Edit the section "Create a User" in doc/radosgw/admin.rst.
(cherry picked from commit 46139c8fa9d4ae0e493bca17ba1199e3a67c39f8) …

reef: doc/radosgw: admin.rst - edit "Create a User"

---

doc/radosgw/admin.rst

Edit the section "Create a User" in doc/radosgw/admin.rst.
(cherry picked from commit 46139c8fa9d4ae0e493bca17ba1199e3a67c39f8) …

quincy: doc/radosgw: admin.rst - edit "Create a User"

---

src/pybind/mgr/rbd_support/mirror_snapshot_schedule.py
src/pybind/rbd/rbd.pyx

backport tracker: https://tracker.ceph.com/issues/63227
---
backport of https://github.com/ceph/ceph/pull/54002
parent tracker: https://tracker.ceph.com/issues/63028

quincy: pybind/rbd: don't produce info on errors in aio_mirror_image_get_info()

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-directories/cephfs-directories.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-directories/cephfs-directories.component.scss
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-directories/cephfs-directories.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-tabs/cephfs-tabs.component.html

Increased the precedence for Directories
Expand the node by default and select them as well
https://github.com/ceph/ceph/assets/71764184/3e0102a1-4e8c-4793-8b38-d8d6ddfff42a
Fixes: https://tracker.ceph.com/issues/63754 …

mgr/dashboard: small fixes to directories view

---

doc/radosgw/admin.rst

- Get User Info
- Modify User Info
- User Suspend/Enable (I split this into two sections) …

doc/radosgw: admin.rst - edit sections

---

doc/radosgw/admin.rst

- Get User Info
- Modify User Info
- User Suspend/Enable (I split this into two sections)
(cherry picked from commit 21ebd2e855a4dd2d2d1244bb3688db0c6613dc30) …

quincy: doc/radosgw: admin.rst - edit sections

---

doc/radosgw/admin.rst

- Get User Info
- Modify User Info
- User Suspend/Enable (I split this into two sections)
(cherry picked from commit 21ebd2e855a4dd2d2d1244bb3688db0c6613dc30) …

reef: doc/radosgw: admin.rst - edit sections

---

doc/radosgw/admin.rst

Edit the section "Create a Subuser" in doc/radosgw/admin.rst.
- …

doc/radosgw: admin.rst - edit "Create a Subuser"

---

doc/radosgw/admin.rst

Edit the section "Create a Subuser" in doc/radosgw/admin.rst.
(cherry picked from commit 3c7a6c41df540f935b0b0b2c4fdc7375327a7662) …

quincy: doc/radosgw: admin.rst - edit "Create a Subuser"

---

doc/radosgw/admin.rst

Edit the section "Create a Subuser" in doc/radosgw/admin.rst.
(cherry picked from commit 3c7a6c41df540f935b0b0b2c4fdc7375327a7662) …

reef: doc/radosgw: admin.rst - edit "Create a Subuser"

---

PendingReleaseNotes
qa/workunits/mon/rbd_snaps_ops.sh
src/include/rados/librados.hpp
src/librados/RadosClient.cc
src/librados/RadosClient.h
src/librados/librados_cxx.cc
src/test/librados/snapshots_cxx.cc
src/tools/rados/rados.cc

librados: make querying pools for selfmanaged snaps reliable

---

src/osd/PGBackend.h
src/osd/PrimaryLogPG.cc
src/osd/ReplicatedBackend.cc
src/osd/ReplicatedBackend.h

Just clean up the code and nothing fixed to make the code to be
more readable.
Fixes: https://tracker.ceph.com/issues/63318
<details>
- `jenkins …

osd: clean up the sparse-read related code

---

src/messages/MMgrBeacon.h

It's possible mgr beacons can get stuck in the dispatch queue long enough for an Mgr to be removed from the MgrMap, increase the priority to ensure processing ahead of monitor commands and other low-priority messages.
Fixes:  https://tracker.ceph.com/issues/63615
Signed-off-by: wanwencong <wanwc@chinatelecom.cn> …

mgr: set MMgrBeacon high priority

---

doc/radosgw/admin.rst

* Remove a User
* Remove a Subuser …

doc/radosgw: edit sections

---

doc/radosgw/admin.rst

* Remove a User
* Remove a Subuser
(cherry picked from commit 8631dc58f7144b32febadd9072c6691456ac8f28) …

reef: doc/radosgw: edit sections

---

doc/radosgw/admin.rst

* Remove a User
* Remove a Subuser
(cherry picked from commit 8631dc58f7144b32febadd9072c6691456ac8f28) …

quincy: doc/radosgw: edit sections

---

doc/radosgw/admin.rst

Edit the English language in the section "Remove a Subuser" in doc/radosgw/admin.rst. This commit is made in response to Matt Benjamin's request for improvement of this section (https://github.com/ceph/ceph/pull/55028#discussion_r1438599833). …

doc/radosgw: edit "remove a subuser"

---

doc/mgr/nfs.rst

Document that no version of Microsoft Windows supports mounting an NFS v4.x export natively, as of the time of this commit.
This commit has been made in response to an anonymous note left on https://pad.ceph.com/p/Report_Documentation_Bugs. …

doc/mgr: document lack of MSWin NFS 4.x support

---

doc/mgr/nfs.rst

Document that no version of Microsoft Windows supports mounting an NFS v4.x export natively, as of the time of this commit.
This commit has been made in response to an anonymous note left on https://pad.ceph.com/p/Report_Documentation_Bugs.
(cherry picked from commit 03656c02a70d4ab719cbcf605517f8a2e9e81117) …

quincy: doc/mgr: document lack of MSWin NFS 4.x support

---

doc/mgr/nfs.rst

Document that no version of Microsoft Windows supports mounting an NFS v4.x export natively, as of the time of this commit.
This commit has been made in response to an anonymous note left on https://pad.ceph.com/p/Report_Documentation_Bugs.
(cherry picked from commit 03656c02a70d4ab719cbcf605517f8a2e9e81117) …

reef: doc/mgr: document lack of MSWin NFS 4.x support

---

doc/radosgw/admin.rst

Edit the English language in the section "Remove a Subuser" in doc/radosgw/admin.rst. This commit is made in response to Matt Benjamin's request for improvement of this section (https://github.com/ceph/ceph/pull/55028#discussion_r1438599833).
(cherry picked from commit 8fc3c488861887490f6ec6bac8f49770664b49a6) …

quincy: doc/radosgw: edit "remove a subuser"

---

doc/radosgw/admin.rst

Edit the English language in the section "Remove a Subuser" in doc/radosgw/admin.rst. This commit is made in response to Matt Benjamin's request for improvement of this section (https://github.com/ceph/ceph/pull/55028#discussion_r1438599833).
(cherry picked from commit 8fc3c488861887490f6ec6bac8f49770664b49a6) …

reef: doc/radosgw: edit "remove a subuser"

---

doc/cephfs/disaster-recovery-experts.rst

doc/cephfs: Update disaster-recovery-experts.rst to mention Slack

---

doc/cephfs/disaster-recovery-experts.rst

(cherry picked from commit 6601e7f38c0b2c1326d40f3bb0599069e38421ff) …

reef: doc/cephfs: Update disaster-recovery-experts.rst to mention Slack

---

doc/cephfs/disaster-recovery-experts.rst

(cherry picked from commit 6601e7f38c0b2c1326d40f3bb0599069e38421ff) …

quincy: doc/cephfs: Update disaster-recovery-experts.rst to mention Slack

---

doc/rados/troubleshooting/log-and-debug.rst

Change the title of "Logging Settings" to "Logging and Debugging Settings" in doc/rados/troubleshooting/log-and-debug.rst. …

doc/rados: improve subsection title in log-and-debug.rst

---

src/mds/MDSRank.cc

mds_cache_mem_rss perf counter can be a useful metric to detect the usage of mds cache and detect mds cache oversize before it happens. The PR changes the priority of the mds_rss metric from Debug to useful …

mds: change priority of mds rss perf counter to useful

---

qa/tasks/cephfs/test_mirroring.py
src/client/Client.cc

Fixes: https://tracker.ceph.com/issues/63475 …

quincy: client: call _getattr() for -ENODATA returned _getvxattr() calls

---

.github/workflows/stale.yml

.github/workflows: upgrade stale bot

---

doc/releases/reef.rst

Make minor corrections to doc/releases/reef.rst. These corrections were suggested by Anthony D'Atri in https://github.com/ceph/ceph/pull/55049. …

doc/releases: edit reef.rst

---

doc/start/kube-helm.rst

Fix 404 link of helm install doc, to make the ceph doc better.
<details>
- `jenkins …

mimic/doc: Fix 404 link of helm install doc

---

doc/radosgw/admin.rst

Edit the section "Add/Remove a Key" in doc/radosgw/admin.rst. Each operation (e.g. "Adding an S3 key pair for a user", "Removing an S3 key pair for a user") now has its own subsection. This increased granularity should make it easier in the future to link to each of these specific operations, if needed. …

doc/radosgw: edit "Add/Remove a Key"

---

doc/radosgw/admin.rst

Edit the section "Add/Remove a Key" in doc/radosgw/admin.rst. Each operation (e.g. "Adding an S3 key pair for a user", "Removing an S3 key pair for a user") now has its own subsection. This increased granularity should make it easier in the future to link to each of these specific operations, if needed.
(cherry picked from commit f62e93cbe73cd8f624a6c99497051c1a0aaf3ab6)
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatch …

reef: doc/radosgw: edit "Add/Remove a Key"

---

src/os/memstore/MemStore.cc

os/memstore: 
Deep copy on partial bufferptrs on setattrs.
Otherwise we may inadvertantly pin larger buffers in memory. …

os/memstore: deep copy on partial bufferptrs on setattrs

---

src/common/options/rgw.yaml.in
src/rgw/rgw_kafka.cc

Fixes: https://tracker.ceph.com/issues/63901
<details>
</details>

rgw/kafka: make the connection idle timeout configurable

---

src/rgw/rgw_lc.cc

Follow the same formula to build up obj_state and version_id in all call sites.
- …

rgwlc:  additional lc notify cleanups

---

doc/radosgw/admin.rst

Edit "Add / Remove Admin Capabilities" in doc/radosgw/admin.rst. …

doc/radosrgw: edit admin.rst

---

src/mon/ConnectionTracker.cc

Problem:
1. peer_reports contain the unexpected rank of -1
Solution:
2. We check the rank of the
monitor that is trying to send us a message
to see if it is -1. If so, we just don't add
their score to ours (including creating a new
key/value for them).
Fixes: https://tracker.ceph.com/issues/59564
<details> …

mon/ConnectionTracker.cc: disregard connection scores from mon_rank = -1 

---

PendingReleaseNotes
doc/rados/operations/balancer.rst

Followup to https://github.com/ceph/ceph/pull/54801
- …

doc/rados/operations: document `ceph balancer status detail`

---

doc/radosgw/adminops.rst

doc: update rgw admin api req params for get user info

---

doc/radosgw/admin.rst

Edit "Add / Remove Admin Capabilities" in doc/radosgw/admin.rst.
(cherry picked from commit 1f0ff27898dfd06a17b18fadd52f68dfb73ccb94) …

reef: doc/radosrgw: edit admin.rst

---

doc/radosgw/admin.rst

Edit "Add / Remove Admin Capabilities" in doc/radosgw/admin.rst.
(cherry picked from commit 1f0ff27898dfd06a17b18fadd52f68dfb73ccb94) …

quincy: doc/radosrgw: edit admin.rst

---

doc/radosgw/adminops.rst

Signed-off-by: Ali Maredia <amaredia@redhat.com>
(cherry picked from commit e6c58dcd614f71efa4de2f781b8425c480af285e) …

reef: doc: update rgw admin api req params for get user info

---

doc/radosgw/adminops.rst

Signed-off-by: Ali Maredia <amaredia@redhat.com>
(cherry picked from commit e6c58dcd614f71efa4de2f781b8425c480af285e) …

quincy: doc: update rgw admin api req params for get user info

---

src/crimson/osd/heartbeat.cc
src/crimson/osd/osd_meta.cc
src/crimson/osd/osd_meta.h
src/crimson/osd/osdmap_service.h
src/crimson/osd/shard_services.cc
src/crimson/osd/shard_services.h

crimson/osd: Support incremental maps

---

doc/radosgw/admin.rst

Edit the "Quota Management" section (all of it) in doc/radosgw/admin.rst.
- …

doc/radosgw: edit admin.rst - quota

---

doc/radosgw/admin.rst

Edit the "Quota Management" section (all of it) in doc/radosgw/admin.rst.
(cherry picked from commit 22fce3c7a55591f6755355751157bc7231776137) …

quincy: doc/radosgw: edit admin.rst - quota

---

doc/radosgw/admin.rst

Edit the "Quota Management" section (all of it) in doc/radosgw/admin.rst.
(cherry picked from commit 22fce3c7a55591f6755355751157bc7231776137) …

reef: doc/radosgw: edit admin.rst - quota

---

src/pybind/rbd/setup.py
src/test/pybind/test_rbd.py

backport tracker: https://tracker.ceph.com/issues/63733
---
backport of https://github.com/ceph/ceph/pull/54670
parent tracker: https://tracker.ceph.com/issues/62140

reef:  pybind/rbd: fix compilation with cython3

---

src/pybind/mgr/rook/rook_cluster.py

Fixes: https://tracker.ceph.com/issues/63694
Fix was tested and validated by an upstream user, plz see comment https://github.com/rook/rook/issues/12858#issuecomment-1828154514 …

mgr/rook: fixing devices listing on rook

---

src/crimson/common/config_proxy.h
src/global/global_context.cc

crimson/ alienstore: 
add set_val and rm_val to global conf.
- …

crimson: add set_val and rm_val to global conf

---

src/rgw/driver/rados/rgw_sal_rados.cc
src/test/rgw/rgw_multi/tests.py
src/test/rgw/rgw_multi/zone_cloud.py
src/test/rgw/rgw_multi/zone_es.py
src/test/rgw/rgw_multi/zone_rados.py

When deleting a role in the primary zone, the delete does not get replicated. This solution addresses https://tracker.ceph.com/issues/63755 …

rgw/iam: fix role deletion replication

---

src/pybind/mgr/dashboard/controllers/cephfs.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-snapshots-list/cephfs-subvolume-snapshots-form/cephfs-subvolume-snapshots-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-snapshots-list/cephfs-subvolume-snapshots-form/cephfs-subvolume-snapshots-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-snapshots-list/cephfs-subvolume-snapshots-form/cephfs-subvolume-snapshots-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-snapshots-list/cephfs-subvolume-snapshots-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-snapshots-list/cephfs-subvolume-snapshots-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-subvolume.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-subvolume.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/cd-date.pipe.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/cd-date.pipe.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
src/pybind/mgr/dashboard/openapi.yaml

https://github.com/ceph/ceph/assets/71764184/07177283-c3b6-4ec9-8c69-05b2c42b4255
- …

mgr/dashboard: subvolume snapshot creation form

---

src/pybind/mgr/dashboard/frontend/cypress/e2e/orchestrator/04-osds.e2e-spec.ts

Update e2e to fix test failure
Fixes:https://tracker.ceph.com/issues/59142
- …

mgr/dashboard: fix e2e failure related to landing page

---

doc/radosgw/admin.rst

Edit the "Rate Limit Management" section in doc/radosgw/admin.rst.
- Component …

doc/rgw: edit admin.rst - rate limit management

---

qa/suites/orch/cephadm/mgr-nfs-upgrade/4-final.yaml

I believe this check was originally added because
the 2->3 migration migrated some nfs related bits. Since then we've had to update the migration this checks for every time we bump the max migration. This change is intended to instead just have it check for a
miration > 2 so we don't have to keep updating it. …

qa/cephadm: mgr-nfs-upgrade, match any migration > 2

---

doc/radosgw/admin.rst

Edit the "Rate Limit Management" section in doc/radosgw/admin.rst.
(cherry picked from commit 47fabe757cff630aaf23a85d268b7406057244e2) …

reef: doc/rgw: edit admin.rst - rate limit management

---

doc/radosgw/admin.rst

Edit the "Rate Limit Management" section in doc/radosgw/admin.rst.
(cherry picked from commit 47fabe757cff630aaf23a85d268b7406057244e2) …

quincy: doc/rgw: edit admin.rst - rate limit management

---

src/crimson/common/subop_blocker.h
src/crimson/osd/osd_operations/background_recovery.cc
src/crimson/osd/osd_operations/pg_advance_map.cc
src/crimson/osd/osd_operations/pg_advance_map.h
src/crimson/osd/osd_operations/snaptrim_event.cc
src/crimson/osd/osd_operations/snaptrim_event.h
src/crimson/osd/shard_services.cc

Cleanup (previous fix attempt) and possible regression fix 9c0432b456a69e0fbf2d9ee8135db7c0386c59b5
- Tracker …

crimson/osd/osd_operations: snaptrim_event cleanup

---

src/rgw/rgw_op.cc

backport tracker: https://tracker.ceph.com/issues/63773
---
backport of https://github.com/ceph/ceph/pull/54738
parent tracker: https://tracker.ceph.com/issues/63485

reef: rgw/iam: admin/system users ignore iam policy parsing errors

---

doc/radosgw/admin.rst

Edit "Get User Rate Limit" in doc/radosgw/admin.rst.
- …

doc/radosgw: edit admin.rst "get user rate limit"

---

doc/radosgw/admin.rst

Edit "Set User Rate Limit" in doc/radosgw/admin.rst.
- …

doc/radosgw - edit admin.rst "set user rate limit"

---

src/mon/HealthMonitor.cc

backport tracker: https://tracker.ceph.com/issues/63987
---
backport of https://github.com/ceph/ceph/pull/48799
parent tracker: https://tracker.ceph.com/issues/58003 …

pacific: mon: add exception handling to ceph health mute

---

doc/radosgw/admin.rst

Edit "Set User Rate Limit" in doc/radosgw/admin.rst.
(cherry picked from commit 8660b4edc71113d5d2d51438c9fd6f388b35a214) …

reef: doc/radosgw - edit admin.rst "set user rate limit"

---

doc/radosgw/admin.rst

Edit "Set User Rate Limit" in doc/radosgw/admin.rst.
(cherry picked from commit 8660b4edc71113d5d2d51438c9fd6f388b35a214) …

quincy: doc/radosgw - edit admin.rst "set user rate limit"

---

doc/radosgw/admin.rst

Edit "Get User Rate Limit" in doc/radosgw/admin.rst.
(cherry picked from commit 1c561e2beac67c85c40f2adf387c42aba8175ecb) …

reef: doc/radosgw: edit admin.rst "get user rate limit"

---

doc/radosgw/admin.rst

Edit "Get User Rate Limit" in doc/radosgw/admin.rst.
(cherry picked from commit 1c561e2beac67c85c40f2adf387c42aba8175ecb) …

quincy: doc/radosgw: edit admin.rst "get user rate limit"

---

src/rgw/rgw_pubsub_push.cc

backport tracker: https://tracker.ceph.com/issues/63702
---
backport of https://github.com/ceph/ceph/pull/54697
parent tracker: https://tracker.ceph.com/issues/63314

quincy: rgw/kafka/amqp: fix race conditionn in async completion handlers

---

ceph-menv/README

Signed-off-by: yu.wang <wangyu@wyu.space>
(cherry picked from commit 4efd9317b83eca48c1a92724e7ebe304650fbc04)
- …

reef: ceph-menv:fix typo in README

---

ceph-menv/README

Signed-off-by: yu.wang <wangyu@wyu.space>
(cherry picked from commit 4efd9317b83eca48c1a92724e7ebe304650fbc04)
- …

quincy: ceph-menv:fix typo in README

---

src/pybind/mgr/dashboard/controllers/cephfs.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-snapshots-list/cephfs-subvolume-snapshots-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-snapshots-list/cephfs-subvolume-snapshots-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-subvolume.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
src/pybind/mgr/dashboard/openapi.yaml

Fixes: https://tracker.ceph.com/issues/63990
https://github.com/ceph/ceph/assets/71764184/7fd1e7a1-a5a9-4e4a-a0e8-2015649bc2d8 …

mgr/dashboard: delete cephfs snapshot

---

src/pybind/mgr/dashboard/module.py
src/pybind/mgr/dashboard/settings.py

This reverts commit 219c62bea60083c0e59a86454b0cecf8afaf9780.
- …

Revert "mgr/dashboard: allow tls 1.2 with a config option"

---

src/pybind/mgr/dashboard/controllers/multi_cluster.py
src/pybind/mgr/dashboard/module.py
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/settings.py
src/pybind/mgr/dashboard/tools.py

mgr/dashboard: multi-cluster authentication

---

qa/tasks/cephfs/test_data_scan.py
src/mds/MDBalancer.cc

https://tracker.ceph.com/issues/57087 …

qa: set mds config with `config set` for a particular test

---

qa/suites/fs/nfs/conf

Fixes: http://tracker.ceph.com/issues/63482 …

qa: enable debug mds/client for fs/nfs suite

---

src/mds/MDSAuthCaps.cc
src/test/libcephfs/access.cc

Once the caller_gid is matched it will make no sense to do the following caller gid list check. …

mds: misc fixes for MDSAuthCaps code

---

qa/tasks/cephfs/filesystem.py

Fixes: https://tracker.ceph.com/issues/63176
- Tracker …

qa: fix rank_asok() to handle errors from asok commands

---

src/mds/Locker.cc
src/mds/Locker.h
src/mds/MDCache.cc
src/mds/MDCache.h
src/mds/MDSRank.cc
src/mds/MDSRank.h
src/mds/Migrator.cc
src/mds/Migrator.h
src/mds/Server.cc
src/mds/Server.h

The ref should be const even if its contents are not.
- …

mds: use const qualifier for MDRequestRef

---

doc/radosgw/admin.rst

Edit "Enable/Disable User Rate Limit" in doc/radosgw/admin.rst. …

docs/radosgw: edit admin.rst "enable/disable user rate limit"

---

src/rgw/rgw_op.cc

Fixes: https://tracker.ceph.com/issues/63855
<details>
</details>

rgw/notifications: dont send notifications if op has failed

---

qa/tasks/cephfs/test_failover.py

backport tracker: https://tracker.ceph.com/issues/61830
---
backport of https://github.com/ceph/ceph/pull/52170
parent tracker: https://tracker.ceph.com/issues/61764

quincy: qa: assign file system affinity for replaced MDS

---

src/mds/locks.c

backport tracker: https://tracker.ceph.com/issues/63808
---
backport of https://github.com/ceph/ceph/pull/54669
parent tracker: https://tracker.ceph.com/issues/63646 …

quincy: mds: set the loner to true for LOCK_EXCL_XSYN

---

admin/doc-requirements.txt

```
Running Sphinx v4.5.0
Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
```
(cherry picked from commit a916feeee757e4e196967944feeb1e9b1f92c398) …

reef: admin/doc-requirements: bump Sphinx to 5.0.2

---

qa/tasks/ceph.py

Fixes: https://tracker.ceph.com/issues/63967 …

qa/tasks: fix syntax for deep-scrub command

---

doc/radosgw/admin.rst

Edit "Enable/Disable User Rate Limit" in doc/radosgw/admin.rst.
(cherry picked from commit 1cd996b6fe2e3c923001a69772c7b7635d058f2b) …

reef: docs/radosgw: edit admin.rst "enable/disable user rate limit"

---

admin/doc-requirements.txt

```
Running Sphinx v4.5.0
Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
```
(cherry picked from commit a916feeee757e4e196967944feeb1e9b1f92c398) …

quincy: admin/doc-requirements: bump Sphinx to 5.0.2

---

src/crimson/os/seastore/transaction_manager.h

When intermediate_key is not equal to intermediate_base, the lba can not find the correct mapping to update refcount. …

crimson/os/seastore: correct the parameter passed to LBAManager::clone_mapping

---

src/crimson/osd/osd_operations/client_request.cc
src/crimson/osd/pg.cc

See NeoRadosCls.DNE or LibRadosCls.DNE
Fixes: https://tracker.ceph.com/issues/64000 …

crimson/osd/osd_operations/client_request: return OpInfo errors

---

src/pybind/mgr/rook/module.py
src/pybind/mgr/rook/rook_cluster.py

Backport of:  [54676](https://github.com/ceph/ceph/pull/54676) and [54715](https://github.com/ceph/ceph/pull/54715)
Fixes: https://tracker.ceph.com/issues/63957
Fixes: https://tracker.ceph.com/issues/63958 …

reef: backport of fixes for 63678 and 63694

---

src/crimson/osd/pg.cc
src/crimson/osd/pg.h

Following: #54287
~https://pulpito.ceph.com/matan-2023-12-04_08:39:13-crimson-rados-wip-matanb-crimson-submit-error-cleanup-testing-distro-crimson-smithi/~ …

crimson/osd: submit_error_log cleanup

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-sync-data-info/rgw-sync-data-info.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-sync-metadata-info/rgw-sync-metadata-info.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-sync-primary-zone/rgw-sync-primary-zone.component.spec.ts

Add frontend unit tests for rgw multisite sync status
Fixes: https://tracker.ceph.com/issues/64039
<details>
- `jenkins …

mgr/dashboard: add frontend unit tests for rgw multisite sync status card

---

doc/radosgw/admin.rst

Edit "Enable/Disable User Rate Limit" in doc/radosgw/admin.rst.
(cherry picked from commit 1cd996b6fe2e3c923001a69772c7b7635d058f2b) …

quincy: docs/radosgw: edit admin.rst "enable/disable user rate limit"

---

qa/tasks/ceph_test_case.py

Fixes: https://tracker.ceph.com/issues/63217
<details>
- …

qa: fix error reporting string in assert_cluster_log

---

src/osd/OSD.cc
src/osd/OSD.h
src/osd/osd_types.h

Backport of https://github.com/ceph/ceph/pull/50326
- …

reef: osd: improve OSD robustness.

---

doc/rados/operations/erasure-code.rst

doc/rados/operations: add EC overhead table to erasure-code.rst …

doc/rados/operations: add EC overhead table to erasure-code.rst

---

src/mds/MDSTableServer.cc

... when tid isn't found in pending_notifies.
Found this by code reading when trying to RCA
https://tracker.ceph.com/issues/54741 …

mds: func name fixup, plus, and additional log message

---

src/mds/journal.cc

mds/journal: make used_preallocated_ino crash more graceful

---

monitoring/ceph-mixin/dashboards/osd.libsonnet
monitoring/ceph-mixin/dashboards/rbd.libsonnet
monitoring/ceph-mixin/dashboards/rgw.libsonnet
monitoring/ceph-mixin/dashboards/utils.libsonnet
monitoring/ceph-mixin/dashboards_out/ceph-cluster.json
monitoring/ceph-mixin/dashboards_out/cephfs-overview.json
monitoring/ceph-mixin/dashboards_out/host-details.json
monitoring/ceph-mixin/dashboards_out/hosts-overview.json
monitoring/ceph-mixin/dashboards_out/osd-device-details.json
monitoring/ceph-mixin/dashboards_out/osds-overview.json
monitoring/ceph-mixin/dashboards_out/pool-detail.json
monitoring/ceph-mixin/dashboards_out/pool-overview.json
monitoring/ceph-mixin/dashboards_out/radosgw-detail.json
monitoring/ceph-mixin/dashboards_out/radosgw-overview.json
monitoring/ceph-mixin/dashboards_out/radosgw-sync-overview.json
monitoring/ceph-mixin/dashboards_out/rbd-details.json
monitoring/ceph-mixin/dashboards_out/rbd-overview.json

The graph panel type is deprecated, and disappears after Grafana v9.1 (current version is 10.0) to prevent more old type panels being created. The current graph panels should be migrated to the timeseries panel type, to avoid potential problems with future Grafana versions.
Before - 
[Screencast from 2023-10-06 15-12-51.webm](https://github.com/ceph/ceph/assets/66050535/34acc740-3379-45fe-a53e-7a8f2479760a)
After -
[Screencast from 2023-10-11 12-52-17.webm](https://github.com/ceph/ceph/assets/66050535/8bb1a20b-4872-4001-832f-86c4ab71c969)
Fixes: https://tracker.ceph.com/issues/61720
- If you are submitting a fix for a stable branch (e.g. "pacific"), …

mgr/dashboard: upgrade from old 'graph' type panels to the new 'timeseries' panel

---

src/crimson/osd/replicated_recovery_backend.cc

crimson/osd/pg: set obc's ssc when handling pull responses

---

doc/rados/operations/control.rst

Description of examples was off by one
Signed-off-by: tobydarling <anothercoffee@gmail.com>
(cherry picked from commit c636e3ed2d459a063ae6ab0e2dc876db5c58c7e6) …

reef: doc/rados/operations: Fix off-by-one errors in control.rst

---

src/osd/PrimaryLogPG.cc

osd/osd/PrimaryLogPG: use should_whiteout helper in _delete_oid()

---

src/os/bluestore/BlueStore.cc

Fixes: https://tracker.ceph.com/issues/63858 …

os/bluestore: fix free space update after bdev-expand in NCB mode.

---

doc/radosgw/admin.rst

Edit "Set Bucket Rate Limit" in doc/radosgw/admin.rst.
- …

doc/radosgw: edit admin.rst "set bucket rate limit"

---

src/mds/CInode.cc

mds: dump sr objects in debug output

---

doc/rados/operations/erasure-code.rst

(cherry picked from commit 9e1999c13d5cab65e88200aa2bfc5ce385d98679) …

quincy: doc/rados/operations: add EC overhead table to erasure-code.rst

---

doc/radosgw/admin.rst

Edit "Set Bucket Rate Limit" in doc/radosgw/admin.rst.
(cherry picked from commit e9b3ef4cb11760392ff7f766d652289636fcf5eb) …

reef: doc/radosgw: edit admin.rst "set bucket rate limit"

---

doc/radosgw/admin.rst

Edit "Get Bucket Rate Limit" in doc/radosgw/admin.rst.
- …

doc/radosgw: edit admin.rst "Get Bucket Rate Limit"

---

doc/radosgw/admin.rst

Edit "Get Bucket Rate Limit" in doc/radosgw/admin.rst.
(cherry picked from commit 7c4fdd3762831cb86993b1b4a814ea68a9ea2401) …

reef: doc/radosgw: edit admin.rst "Get Bucket Rate Limit"

---

doc/radosgw/admin.rst

Edit "Get Bucket Rate Limit" in doc/radosgw/admin.rst.
(cherry picked from commit 7c4fdd3762831cb86993b1b4a814ea68a9ea2401) …

quincy: doc/radosgw: edit admin.rst "Get Bucket Rate Limit"

---

PendingReleaseNotes
src/common/bit_vector.hpp
src/include/intarith.h
src/librbd/ImageCtx.h
src/librbd/ObjectMap.h
src/librbd/api/DiffIterate.cc
src/librbd/api/DiffIterate.h
src/librbd/deep_copy/ImageCopyRequest.cc
src/librbd/object_map/DiffRequest.cc
src/librbd/object_map/DiffRequest.h
src/test/librbd/deep_copy/test_mock_ImageCopyRequest.cc
src/test/librbd/mock/MockObjectMap.h
src/test/librbd/object_map/test_mock_DiffRequest.cc
src/test/librbd/test_librbd.cc

librbd: improve rbd_diff_iterate2() performance in fast-diff mode

---

src/crimson/mgr/client.cc
src/crimson/mgr/client.h
src/crimson/mon/MonClient.cc

src/crimson: Add support for the OSD to receive config changes

---

doc/radosgw/admin.rst

Edit "Enable/Disable Bucket Rate Limit" in doc/radosgw/admin.rst.
- Component …

doc/radosgw: edit "Enable/Disable Bucket Rate Limit"

---

doc/radosgw/admin.rst

Edit "Enable/Disable Bucket Rate Limit" in doc/radosgw/admin.rst.
(cherry picked from commit a1fca50dfdcb30e58ebcc4ef60ef921b977efc81) …

quincy: doc/radosgw: edit "Enable/Disable Bucket Rate Limit"

---

doc/radosgw/admin.rst

Edit "Enable/Disable Bucket Rate Limit" in doc/radosgw/admin.rst.
(cherry picked from commit a1fca50dfdcb30e58ebcc4ef60ef921b977efc81) …

reef: doc/radosgw: edit "Enable/Disable Bucket Rate Limit"

---

PendingReleaseNotes
doc/rados/operations/balancer.rst

Document change in https://github.com/ceph/ceph/pull/54801
Signed-off-by: Laura Flores <lflores@ibm.com>
(cherry picked from commit 159751b68085fbe0fe10a881ff8bedecda11142f) …

quincy: doc/rados/operations: document `ceph balancer status detail`

---

PendingReleaseNotes
doc/rados/operations/balancer.rst

Document change in https://github.com/ceph/ceph/pull/54801
Signed-off-by: Laura Flores <lflores@ibm.com>
(cherry picked from commit 159751b68085fbe0fe10a881ff8bedecda11142f) …

reef: doc/rados/operations: document `ceph balancer status detail`

---

src/crimson/os/alienstore/alien_log.cc

Taken out of #55039
Re-pushing after discussing it in the perf meeting, we should not "stall" bluestore logs for log line synchronization. …

crimson/os/alienstore/alien_log: _flush concurrently

---

qa/workunits/test_telemetry_quincy.sh
qa/workunits/test_telemetry_quincy_x.sh

To be merged after #49414!!!
Signed-off-by: Laura Flores <ljflores@redhat.com>
<details> …

qa/workunits: update telemetry quincy workunits with `basic_pool_options_bluestore` collection

---

src/mon/mon_types.h

The add_to_ceph_s field was not initialized causing unit test failures from check-generated.sh:
```
**** ProgressEvent test 1 dump_json check failed ****
ceph-dencoder type ProgressEvent select_test 1 dump_json > /tmp/typ-akwRrjNtt
ceph-dencoder type ProgressEvent select_test 1 encode decode dump_json > /tmp/typ-iDmGaq17A
4c4
<     "add_to_ceph_s": false
---
>     "add_to_ceph_s": true
```
Fixes: https://tracker.ceph.com/issues/63950 …

mon: initialize ProgressEvent::add_to_ceph_s

---

doc/radosgw/admin.rst

Edit "Set Bucket Rate Limit" in doc/radosgw/admin.rst.
(cherry picked from commit e9b3ef4cb11760392ff7f766d652289636fcf5eb) …

quincy: doc/radosgw: edit admin.rst "set bucket rate limit"

---

doc/radosgw/admin.rst

Edit "Reading/Writing Global Rate Limit Configuration" in doc/radosgw/admin.rst.
- …

doc/radosgw: edit "read/write global rate limit" admin.rst

---

doc/radosgw/admin.rst

Edit "Reading/Writing Global Rate Limit Configuration" in doc/radosgw/admin.rst.
(cherry picked from commit c67a5e5d4bad17e7ae799dd62a66d1e23ec18942) …

reef: doc/radosgw: edit "read/write global rate limit" admin.rst

---

doc/radosgw/admin.rst

Edit "Reading/Writing Global Rate Limit Configuration" in doc/radosgw/admin.rst.
(cherry picked from commit c67a5e5d4bad17e7ae799dd62a66d1e23ec18942) …

quincy: doc/radosgw: edit "read/write global rate limit" admin.rst

---

doc/cephfs/health-messages.rst
qa/suites/fs/functional/tasks/client-recovery.yaml
qa/tasks/cephfs/test_client_recovery.py
qa/tasks/mgr/mgr_test_case.py
src/common/options/mds.yaml.in
src/mds/Beacon.cc
src/mds/MDSRank.cc
src/mds/Server.cc
src/mds/Server.h
src/messages/MMDSBeacon.h
src/osd/OSDMap.cc
src/osd/OSDMap.h

backport tracker: https://tracker.ceph.com/issues/61840, https://tracker.ceph.com/issues/62441, https://tracker.ceph.com/issues/63270
parent tracker: https://tracker.ceph.com/issues/58023, https://tracker.ceph.com/issues/61907, https://tracker.ceph.com/issues/63105
backport of https://github.com/ceph/ceph/pull/49971, https://github.com/ceph/ceph/pull/52342, https://github.com/ceph/ceph/pull/53839/ …

quincy: do not evict clients if OSDs are laggy

---

src/client/Client.cc

backport tracker: https://tracker.ceph.com/issues/63284
---
backport of https://github.com/ceph/ceph/pull/54030
parent tracker: https://tracker.ceph.com/issues/63188

quincy: client: always refresh mds feature bits on session open

---

src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h

Allocator performance is the performance limiting factor on performance storage. This performance count can help us intuitively observe the reasons for changes in bluestore performance.
<details>
- …

os/bluestore: add perfcount for bluestore/bluefs allocator

---

qa/tasks/mgr/mgr_test_case.py
qa/tasks/mgr/test_cli.py
qa/tasks/mgr/test_devicehealth.py
src/mon/MgrMap.h
src/mon/MgrMonitor.cc
src/mon/MgrMonitor.h
src/mon/MonCommands.h
src/pybind/mgr/devicehealth/module.py

Fixes: https://tracker.ceph.com/issues/63882 …

pybind/mgr/devicehealth: skip legacy objects that cannot be loaded

---

src/pybind/mgr/rook/ci/cluster-specs/cluster-on-pvc-minikube.yaml
src/pybind/mgr/rook/ci/scripts/bootstrap-rook-cluster.sh
src/pybind/mgr/rook/ci/tests/features/rook.feature
src/pybind/mgr/rook/ci/tests/features/steps/implementation.py
src/pybind/mgr/rook/ci/tests/features/steps/utils.py

Fixes: https://tracker.ceph.com/issues/64029 …

mgr/rook: adding some basic rook e2e testing

---

doc/radosgw/admin.rst

Edit "Usage" in doc/radosgw/admin.rst. …

doc/radosgw: edit "Usage" admin.rst

---

src/common/async/context_pool.h
src/include/inline_memory.h
src/rgw/CMakeLists.txt
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/driver/rados/rgw_sal_rados.h
src/rgw/driver/rados/rgw_service.cc
src/rgw/driver/rados/rgw_service.h
src/rgw/driver/rados/rgw_zone.cc
src/rgw/driver/rados/rgw_zone.h
src/rgw/rgw_admin.cc
src/rgw/rgw_appmain.cc
src/rgw/rgw_asio_frontend.cc
src/rgw/rgw_asio_frontend.h
src/rgw/rgw_main.h
src/rgw/rgw_object_expirer.cc
src/rgw/rgw_realm_reloader.cc
src/rgw/rgw_realm_reloader.h
src/rgw/rgw_sal.cc
src/rgw/rgw_sal.h
src/test/rgw/rgw_cr_test.cc
src/test/rgw/test_d4n_filter.cc
src/test/rgw/test_rgw_common.h
src/test/rgw/test_rgw_iam_policy.cc
src/test/rgw/test_rgw_lua.cc

Make neorados available within RGW.
This should require *only* RGW tests.
<details>
- …

rgw: Surface neorados

---

doc/radosgw/admin.rst

Edit "Usage" in doc/radosgw/admin.rst.
(cherry picked from commit d8df6f61e817a34c2c3282224cff117ae43e3f98) …

reef: doc/radosgw: edit "Usage" admin.rst

---

doc/radosgw/admin.rst

Edit "Usage" in doc/radosgw/admin.rst.
(cherry picked from commit d8df6f61e817a34c2c3282224cff117ae43e3f98) …

quincy: doc/radosgw: edit "Usage" admin.rst

---

doc/radosgw/index.rst

Fix a tricky verb disagreement and rewrite a few sentences for what I hope is greater clarity. …

doc/radosgw: fix verb disagreement - index.html

---

src/crimson/os/cyanstore/cyan_store.cc
src/crimson/os/cyanstore/cyan_store.h

crimson/os/cyanstore: support OP_RMCOLL

---

doc/radosgw/index.rst

Fix a tricky verb disagreement and rewrite a few sentences for what I hope is greater clarity.
(cherry picked from commit 9f271093f4331381dc024cb4309f9f486d366818) …

quincy: doc/radosgw: fix verb disagreement - index.html

---

doc/architecture.rst

Improve the definition of RADOS, and link to information about RADOS.
- Component …

doc/architecture.rst: improve rados definition

---

doc/architecture.rst

Improve the definition of RADOS, and link to information about RADOS.
(cherry picked from commit 763f6b7a22e846962f388d58fd7e699cbf16ffe7) …

reef: doc/architecture.rst: improve rados definition

---

doc/architecture.rst

Improve the definition of RADOS, and link to information about RADOS.
(cherry picked from commit 763f6b7a22e846962f388d58fd7e699cbf16ffe7) …

quincy: doc/architecture.rst: improve rados definition

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.ts

Fixes https://tracker.ceph.com/issues/64150
**Issue:** Due to absence of null checks, the overview page was failing to load.
**Fix:** Added, null check at relevant places to ensure data availability before accessing the data.
**Before:**
**After:**
<details>
- …

mgr/dashboard: Fix issue with Object's Overview page

---

src/crimson/osd/pg_map.cc
src/crimson/osd/pg_map.h
src/crimson/osd/pg_shard_manager.cc
src/crimson/osd/pg_shard_manager.h
src/crimson/osd/shard_services.h

groundwork for multicore pg creation and deletion bugs we encounter
- Component …

crimson/osd/pg_map: Refactor

---

src/mds/Beacon.cc
src/messages/MMDSBeacon.h

mds: adhere to mds_health_summarize_threshold config when reporting laggy clients

---

qa/tasks/ceph_manager.py
qa/tasks/cephfs/filesystem.py
qa/tasks/vstart_runner.py

Fixes: https://tracker.ceph.com/issues/63411 …

qa: bump up scrub status command timeout

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html

Added snap-schedule module detection and UI message feedback with option to enable it from the snapshot schedules screen.
Also change RGW enable action from link to button for better semantics and consistency with snap schedule screen
Fixes: https://tracker.ceph.com/issues/63768 …

mgr/dashboard: snap schedule module detect/enable 

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/icons.enum.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/forms/crud-form/formly-textarea-type/formly-textarea-type.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/text-area-json-formatter.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/text-area-json-formatter.service.ts
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/rgw_client.py

This PR:
- Adds support to set bucket policies through the Dashboard.
- Rename rgw bucket policy from 'policy' to 'bucket policy'
- Fix: hide Tags when none are present on bucket list details and sets the form dirty after deleting a tag
- Added service to manage the formatting of a textArea that works with json
Fixes: https://tracker.ceph.com/issues/63942 …

mgr/dashboard: set bucket policies

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts

Remove a bucket policy throught the bucket form
[remove_bucket_policy.webm](https://github.com/ceph/ceph/assets/106810838/7138bffd-8228-4c5a-8dcf-e183692bc872)
PR based on top of #55062
Fixes: https://tracker.ceph.com/issues/64096 …

mgr/dashboard: Remove bucket policy

---

qa/tasks/cephfs/test_volumes.py

See - https://github.com/ceph/ceph/pull/53899/files#r1382869363 …

qa: remove redundant test test_volumes.TestRenameCmd.test_rename_when_fs_is_online

---

PendingReleaseNotes
src/common/options/mds.yaml.in
src/mds/MDLog.cc
src/mds/MDLog.h
src/mds/MDSRank.cc

mds: add mdlog trimming threshold and decay counter

---

src/pybind/mgr/dashboard/controllers/auth.py
src/pybind/mgr/dashboard/controllers/multi_cluster.py
src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/cluster.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-form/multi-cluster-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-form/multi-cluster-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-form/multi-cluster-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.scss
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.ts
src/pybind/mgr/dashboard/frontend/src/app/core/auth/login/login.component.ts
src/pybind/mgr/dashboard/frontend/src/app/core/layouts/workbench-layout/workbench-layout.component.html
src/pybind/mgr/dashboard/frontend/src/app/core/layouts/workbench-layout/workbench-layout.component.ts
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.scss
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/multi-cluster.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/multi-cluster.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/modal/modal.component.scss
src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/api-interceptor.service.ts
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/tests/test_auth.py

Allow the user to add a cluster using a form for multi-cluster management and add a context switcher at the top of the navigation bar to allow the user to switch between the clusters that are connected.
[Screencast from 2024-01-19 13-38-37.webm](https://github.com/ceph/ceph/assets/66050535/b12c0af8-9896-42fc-b488-acce7bbc3151) …

mgr/dashboard: add multi-cluster management using context switcher in dashboard

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
src/pybind/mgr/dashboard/openapi.yaml

Export rgw multisite status via the API
Fixes: https://tracker.ceph.com/issues/64081 …

mgr/dashboard: Export rgw multisite status via the API

---

src/pybind/mgr/dashboard/controllers/cephfs.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-snapshots-list/cephfs-subvolume-snapshots-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-subvolume.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-modal/form-modal.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/cd-form-modal-field-config.ts
src/pybind/mgr/dashboard/openapi.yaml

Fixes: https://tracker.ceph.com/issues/64175
https://github.com/ceph/ceph/assets/71764184/28783a30-a476-457f-891c-36f1555b2e48 …

mgr/dashboard: create cephfs snapshot clone

---

src/pybind/mgr/rook/ci/scripts/bootstrap-rook-cluster.sh
src/pybind/mgr/rook/ci/tests/features/cluster-prometheus-monitoring.feature
src/pybind/mgr/rook/ci/tests/features/steps/implementation.py

Fixes: https://tracker.ceph.com/issues/64183 …

mgr/rook: adding metrics monitoring e2e testing

---

doc/man/8/ceph-bluestore-tool.rst

Added valid options for fsck deep flag (*(on|off) or (yes|no) or (1|0) or (true|false)*)
Fixes:  https://tracker.ceph.com/issues/62912
Signed-off-by: Patty8122 <divyapattisapu@uchicago.edu>
doc/man/8/ceph-bluestore-tool.rst edited. …

doc/man/8: Add valid options in ceph-bluestore-tool.rst

---

.github/workflows/pr-triage.yml

`sync-labels` is defined as "Whether or not to remove labels when matching files are reverted or no longer changed by the PR".
We should disable this in case someone manually adds a label, so the label doesn't get removed. …

.github/workflows: disable sync-labels in pr-triage

---

doc/architecture.rst

doc/architecture.rst - fix typo

---

doc/architecture.rst

s/requies/requires
(cherry picked from commit 6c0417fbcbe6b9760b3836e5166d6bd929578096) …

reef: doc/architecture.rst - fix typo

---

doc/architecture.rst

s/requies/requires
(cherry picked from commit 6c0417fbcbe6b9760b3836e5166d6bd929578096) …

quincy: doc/architecture.rst - fix typo

---

.github/workflows/pr-triage.yml

.github/workflows: revert version bump to labler action

---

src/crimson/osd/pg.cc
src/crimson/osd/pg_map.cc
src/crimson/osd/shard_services.cc

Fixes ceph_test_cls_rbd (cyanstore) crash. …

crimson/osd/pg: do_delete_work use claim_and_reset 

---

doc/architecture.rst

Improve paragraphs under the heading "The Ceph Storage Cluster". Remove a sentence that was pleonastic in its context in the paragraph. …

doc/architecture: improve some paragraphs

---

doc/architecture.rst

Improve paragraphs under the heading "The Ceph Storage Cluster". Remove a sentence that was pleonastic in its context in the paragraph.
(cherry picked from commit 2f0542d66901295cf875893de0ac15304578d917) …

reef: doc/architecture: improve some paragraphs

---

src/pybind/mgr/dashboard/controllers/cephfs.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-tabs/cephfs-tabs.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-snapshot-schedule.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/icons.enum.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/repeat-frequency.enum.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/retention-frequency.enum.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/snapshot-schedule.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
src/pybind/mgr/dashboard/openapi.yaml

Fixes: https://tracker.ceph.com/issues/63827
Added create snapshot schedule endpoint and modal form to create snapshot schedules and retention policies at the same time. …

added snap schedule form

---

src/pybind/mgr/rook/ci/Dockerfile
src/pybind/mgr/rook/ci/scripts/bootstrap-rook-cluster.sh

Fixes: https://tracker.ceph.com/issues/64266 …

mgr/rook: adding deployment to ceph image built for rook e2e testing

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/directory-store.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/directory-store.service.ts

Fixes: https://tracker.ceph.com/issues/64246
Added typeahead input for directory field. Added directory store.
- …

Snapshot schedule form directory typeahead

---

qa/cephfs/mount/kclient/overrides/distro/stock/centos_9.stream.yaml
qa/cephfs/mount/kclient/overrides/distro/stock/rhel_8.yaml

qa: use centos9 for cephfs stock kernel testing

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.ts
src/pybind/mgr/dashboard/services/rgw_client.py

backport tracker: https://tracker.ceph.com/issues/63426
---
backport of https://github.com/ceph/ceph/pull/54048
parent tracker: https://tracker.ceph.com/issues/63221

reef: mgr/dashboard: get object bucket policies for a bucket

---

src/rgw/rgw_keystone.cc

This changes so that we don't return before even checking if the request failed by checking the response code like was done for other methods in [1].
[1] https://github.com/ceph/ceph/pull/53846 …

rgw: fix http error check in keystone issue_admin_token_request

---

src/rgw/rgw_rest.h
src/rgw/rgw_rest_s3.cc

when encoding-type=url given, 
aws sdk will try to decode next marker returned in a list obj response.
if it is not actually encoded and the marker obj just have an encoding symbol in its name, 
aws sdk may get error when trying to decode it. …

rgw: fix list obj v1 nextmarker

---

doc/radosgw/notifications.rst

(cherry picked from commit ecbd8376675c39893c55ceb7fa8653458d3fc6ed) …

quincy: doc/rgw: fix Attributes index in CreateTopic example

---

doc/radosgw/notifications.rst

(cherry picked from commit ecbd8376675c39893c55ceb7fa8653458d3fc6ed) …

reef: doc/rgw: fix Attributes index in CreateTopic example

---

qa/config/crimson_qa_overrides.yaml
qa/suites/crimson-rados/basic/clusters/fixed-2.yaml
qa/suites/crimson-rados/perf/clusters/fixed-2.yaml
qa/suites/crimson-rados/rbd/clusters/fixed-1.yaml
qa/suites/crimson-rados/singleton/all/osd-backfill.yaml
qa/suites/crimson-rados/thrash/clusters/fixed-2.yaml
src/common/options/crimson.yaml.in
src/crimson/os/alienstore/alien_store.cc
src/crimson/os/alienstore/alien_store.h
src/crimson/osd/main_config_bootstrap_helpers.cc
src/crimson/osd/osd.cc
src/vstart.sh

crimson: rework CPU pinning

---

src/common/options/rgw.yaml.in

src/common/options: Correct typo in rgw.yaml.in
Signed-off-by: Anthony D'Atri anthony.datri@gmail.com
- Tracker …

src/common/options: Correct typo in rgw.yaml.in

---

src/common/options/rgw.yaml.in

(cherry picked from commit 1796022aa4778226c2d7e04c1cb989ab9d025272) …

reef: src/common/options: Correct typo in rgw.yaml.in

---

qa/tasks/cephfs/test_mirroring.py
src/client/Client.cc

Fixes: https://tracker.ceph.com/issues/63474 …

reef: client: call _getattr() for -ENODATA returned _getvxattr() calls

---

src/mds/locks.c

backport tracker: https://tracker.ceph.com/issues/63809
---
backport of https://github.com/ceph/ceph/pull/54669
parent tracker: https://tracker.ceph.com/issues/63646 …

reef: mds: set the loner to true for LOCK_EXCL_XSYN

---

src/rgw/driver/rados/rgw_gc.cc

Reduce time complexity of gc chain size calculation from O(n^2) to O(n). 
The time cost of deleting a 50GB object reduces from 20s to 0.05s with this patch. …

rgw: optimize gc chain size calculation

---

src/pybind/mgr/dashboard/frontend/cypress/integration/block/mirroring.po.ts
src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.po.ts
src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/services.po.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts

This is already reverted in reef and quincy. Since its not needed reverting it in pacific as well
Fixes: https://tracker.ceph.com/issues/57829
This reverts commit 3bdb929bab8f3eda32dcf9e46bb54a221ea54d3b. …

pacifc: Revert "mgr/dashboard: unselect rows in datatables" 

---

PendingReleaseNotes
src/common/options/rgw.yaml.in
src/rgw/rgw_iam_policy.cc
src/rgw/rgw_iam_policy.h
src/rgw/rgw_rest_pubsub.cc
src/test/rgw/bucket_notification/test_bn.py

Fixes: https://tracker.ceph.com/issues/64124 …

rgw: add topic owner user check when creating

---

PendingReleaseNotes
ceph.spec.in
qa/cephfs/begin/0-install.yaml
qa/suites/fs/shell/distro
qa/suites/fs/shell/tasks/cephfs-shell.yaml

Revert "reef: qa: add support/qa for cephfs-shell on CentOS 9 / RHEL9"

---

doc/cephadm/troubleshooting.rst

Edit "Running Repeated Debugging Sessions" in
doc/cephadm/troubleshooting.rst. Improve grammar. Fix a misspelling. …

doc/cephadm - edit t11ing.

---

doc/radosgw/metrics.rst
src/rgw/rgw_perf_counters.cc

The rgw_op section of `counter dump/schema` becomes:
- rgw_op_global for the global op counters
- rgw_op_user for the user labeled counters
- rgw_op_bucket for the bucket labeled counters …

rgw: change section name of rgw_op counters

---

doc/cephadm/troubleshooting.rst

Edit "Running Repeated Debugging Sessions" in
doc/cephadm/troubleshooting.rst. Improve grammar. Fix a misspelling.
(cherry picked from commit f5b8afe981650f5072294303b0e488b91fc65fe8) …

reef: doc/cephadm - edit t11ing.

---

doc/radosgw/admin.rst

Add confval directives to the documentation of "quota cache" options. This addresses a request made by Antony D'Atri in https://github.com/ceph/ceph/pull/55075/files#r1444006246.
(cherry picked from commit 6504732e1b5b34756a119bc1547d22c07bd6458a) …

reef: doc/radosgw: add confval directives

---

doc/radosgw/admin.rst

Add confval directives to the documentation of "quota cache" options. This addresses a request made by Antony D'Atri in https://github.com/ceph/ceph/pull/55075/files#r1444006246.
(cherry picked from commit 6504732e1b5b34756a119bc1547d22c07bd6458a) …

quincy: doc/radosgw: add confval directives

---

src/pybind/mgr/dashboard/controllers/cephfs.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-snapshot-schedule.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
src/pybind/mgr/dashboard/openapi.yaml

mgr/dashboard: added edit functionality

---

qa/tasks/cephadm.conf

Backport of https://github.com/ceph/ceph/pull/41479 and https://github.com/ceph/ceph/pull/54312. …

pacific: qa/tasks/cephadm: enable mon_cluster_log_to_file

---

src/pybind/mgr/dashboard/controllers/multi_cluster.py
src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/cluster.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-form/multi-cluster-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-form/multi-cluster-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-list/multi-cluster-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-list/multi-cluster-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-list/multi-cluster-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.ts
src/pybind/mgr/dashboard/frontend/src/app/core/layouts/workbench-layout/workbench-layout.component.ts
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/multi-cluster.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/multi-cluster.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/api-interceptor.service.ts
src/pybind/mgr/dashboard/openapi.yaml

Add a manage clusters page to the multi-cluster nav to list/connect/disconnect/edit clusters in multi-cluster setup …

Add a manage clusters page to the multi-cluster nav to list/connect/disconnect/edit clusters in multi-cluster setup

---

src/ceph-volume/ceph_volume/devices/lvm/migrate.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_migrate.py

Fixes: https://tracker.ceph.com/issues/64260

ceph-volume: Fix migration from WAL to data with no DB

---

doc/start/hardware-recommendations.rst

doc/start: fix typo in hw-recs

---

src/client/Client.h

there are no usages of this function in entire codebase
- …

client: remove unused/undefined fake_write_size()

---

src/mds/MDCache.cc

mds: Add debug messages in replica handling
Fixes: https://tracker.ceph.com/issues/64241 …

mds: Add debug messages in replica handling

---

monitoring/ceph-mixin/dashboards.libsonnet
monitoring/ceph-mixin/dashboards/multi-cluster.libsonnet
monitoring/ceph-mixin/dashboards/utils.libsonnet
monitoring/ceph-mixin/dashboards_out/multi-cluster-overview.json
monitoring/ceph-mixin/tests_dashboards/util.py

Add a Multi-Cluster Overview Dashboard in grafana
Fixes: https://tracker.ceph.com/issues/64358 …

mgr/dashboard: add multi-cluster overview grafana dashboard

---

doc/start/hardware-recommendations.rst

s/power less/power loss/
Signed-off-by: Eduardo Roldan <trazor@gmail.com>
(cherry picked from commit b80c12d080275e3c221a1e305c345fbc1caa3c8e) …

reef: doc:start.rst fix typo in hw-recs

---

doc/start/hardware-recommendations.rst

s/power less/power loss/
Signed-off-by: Eduardo Roldan <trazor@gmail.com>
(cherry picked from commit b80c12d080275e3c221a1e305c345fbc1caa3c8e) …

quincy: doc:start.rst fix typo in hw-recs

---

qa/suites/upgrade/pacific-p2p/pacific-p2p-stress-split/6-final-workload/rbd-python.yaml

pacific: qa/suites/upgrade/pacific-p2p: run librbd python API tests from pacific tip

---

qa/suites/orch/cephadm/smoke/start.yaml
qa/suites/orch/cephadm/workunits/task/test_host_drain.yaml
qa/suites/orch/cephadm/workunits/task/test_monitoring_stack_basic.yaml
qa/suites/orch/cephadm/workunits/task/test_orch_cli_mon.yaml
qa/suites/orch/cephadm/workunits/task/test_rgw_multisite.yaml
qa/suites/orch/cephadm/workunits/task/test_set_mon_crush_locations.yaml
qa/tasks/thrashosds-health.yaml

The idea here is to ignore warnings that we know are happening because of deliberate testing conditions.
An alternative to the solution proposed in https://github.com/ceph/ceph/pull/55498.
Fixes: https://tracker.ceph.com/issues/64343 …

qa/suites/orch: whitelist warnings that are expected in test environments

---

doc/radosgw/lua-scripting.rst

Roll back the docs changes made in
https://github.com/ceph/ceph/pull/55524, in accordance with Casey Bodley's instructions to me here:
https://github.com/ceph/ceph/pull/55524#issuecomment-1937020543. …

doc/radosgw: undo 55524

---

src/rgw/rgw_rest_s3.cc

when is_v4_payload_empty(), we return a null completer so never try to validate the x-amz-content-sha256 for signed payloads. add this checksum comparison to get_auth_data_v4() before we create the completer
Fixes: https://tracker.ceph.com/issues/64084
<details>
</details>

rgw/auth/s3: validate x-amz-content-sha256 for empty payloads

---

src/rgw/rgw_auth.cc
src/rgw/rgw_auth_s3.cc
src/rgw/rgw_common.h

clearly that a pre-signed URL has expired. …

rgw/auth: correcting the error message to indicate

---

src/rgw/driver/rados/rgw_notify.cc

Notification reservations are now committed asynchronously (this only applies to persistent notifications).
Fixes: https://tracker.ceph.com/issues/63390
Signed-off-by: Igor Gomon igomon@bloomberg.net …

rgw/s3-notifications: async commit to persistent notification queue

---

src/pybind/mgr/dashboard/controllers/cephfs.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-snapshot-schedule.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
src/pybind/mgr/dashboard/openapi.yaml

Fixes: https://tracker.ceph.com/issues/64355 …

mgr/dashboard: added delete and activation actions

---

monitoring/ceph-mixin/dashboards.libsonnet
monitoring/ceph-mixin/dashboards/rgw-s3-analytics.libsonnet
monitoring/ceph-mixin/dashboards/utils.libsonnet
monitoring/ceph-mixin/dashboards_out/rgw-s3-analytics.json
monitoring/ceph-mixin/tests_dashboards/util.py

Fixes: https://tracker.ceph.com/issues/64359 …

mgr/dashboard: Add RGW per user/bucket panels in  grafana

---

doc/rados/configuration/ms-ref.rst
src/common/legacy_config_opts.h
src/common/options.cc
src/msg/async/PosixStack.h
src/msg/async/Stack.cc
src/msg/async/Stack.h
src/msg/async/dpdk/DPDKStack.cc
src/msg/async/dpdk/DPDKStack.h
src/msg/async/rdma/RDMAStack.cc
src/msg/async/rdma/RDMAStack.h

fixes: https://tracker.ceph.com/issues/64311 …

pacific: msg/async: initialize worker in RDMAStack::create_worker() and drop Stack::num_workers

---

src/tools/ceph_objectstore_tool.cc

```
$ bin/ceph-objectstore-tool --version
Must provide --data-path
Allowed options:
--help                      produce help message
--type arg                  Arg is one of [bluestore (default), memstore]
```
```
$ bin/ceph-bluestore-tool --version
ceph version 19.0.0-642-g6d93c157068 (6d93c1570681fbf25fff5c48a9ff5bcb7d6d2210) squid (dev)
```
Fixes: https://tracker.ceph.com/issues/64104 …

tools/cot: respect generic, Ceph-wide argvs

---

src/rgw/driver/rados/rgw_rados.cc

Fixes: https://tracker.ceph.com/issues/64340 …

rgw: do not copy olh attributes in versioning suspended bucket

---

doc/glossary.rst

Add a link in the CRUSH definition to the original CRUSH paper. …

doc/glossary: Add link to CRUSH paper

---

doc/cephadm/install.rst

Explain how to deal with the error message "Non-zero exit code 22" when using cephadm to install a Ceph cluster.
- …

quincy: doc/cephadm: add note about ceph-exporter (Quincy)

---

monitoring/ceph-mixin/dashboards/rgw.libsonnet
monitoring/ceph-mixin/dashboards_out/radosgw-detail.json
monitoring/ceph-mixin/dashboards_out/radosgw-overview.json
monitoring/ceph-mixin/tests_dashboards/features/radosgw-detail.feature
monitoring/ceph-mixin/tests_dashboards/features/radosgw_overview.feature
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/dashboard-promqls.enum.ts

- Fixing grafana panels for rgw dashboards
- Fixing RGW overview dashboard queries
fixes: https://tracker.ceph.com/issues/64177 …

mgr/dashboard: Fixing RGW graph panels

---

src/pybind/mgr/dashboard/controllers/multi_cluster.py
src/pybind/mgr/dashboard/controllers/prometheus.py
src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/cluster.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-v3.module.ts
src/pybind/mgr/dashboard/frontend/src/app/core/layouts/workbench-layout/workbench-layout.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/api/prometheus.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/card-group/card-group.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/card-group/card-group.component.scss
src/pybind/mgr/dashboard/frontend/src/app/shared/components/card-group/card-group.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/card-group/card-group.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/components.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/dashboard-promqls.enum.ts
src/pybind/mgr/dashboard/openapi.yaml

https://github.com/ceph/ceph/assets/71764184/880beb6c-a5be-4352-a840-494d4bc24530
- …

mgr/dashboard: introduce multi-cluster overview page 

---

src/pybind/mgr/dashboard/controllers/cephfs.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.scss
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-snapshot-schedule.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/repeat-frequency.enum.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/retention-frequency.enum.ts
src/pybind/mgr/dashboard/openapi.yaml

Fixes: https://tracker.ceph.com/issues/64372 …

mgr/dashboard: snapshot schedule added subvolume and translations

---

src/client/Client.cc
src/client/Client.h
src/test/client/nonblocking.cc

Fixes: https://tracker.ceph.com/issues/63734 …

client: handle callback when async io fails

---

monitoring/ceph-mixin/dashboards/multi-cluster.libsonnet
monitoring/ceph-mixin/dashboards_out/multi-cluster-overview.json
src/pybind/mgr/dashboard/controllers/multi_cluster.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-form/multi-cluster-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-form/multi-cluster-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/multi-cluster.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/multi-cluster.ts
src/pybind/mgr/dashboard/openapi.yaml

mgr/dashboard: enable ssl for multi-cluster authentication

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/package-lock.json
src/pybind/mgr/dashboard/frontend/package.json
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-acl-permissions.enum.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
src/pybind/mgr/dashboard/frontend/tsconfig.json
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/rgw_client.py

Adding acl management through canned ACLs into the dashboard
Set ACL on bucket form:
Video example (video not updated to latest look:
[screen-capture (18).webm](https://github.com/ceph/ceph/assets/106810838/dc8ad15e-cc48-45de-a350-00de297c9a3d)
Fixes: https://tracker.ceph.com/issues/63547
Signed-off-by: Pedro Gonzalez Gomez <pegonzal@redhat.com> …

mgr/dashboard: add ACLs

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-mount-details/cephfs-mount-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-mount-details/cephfs-mount-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-mount-details/cephfs-mount-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/code-block/code-block.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/code-block/code-block.component.scss
src/pybind/mgr/dashboard/frontend/src/app/shared/components/code-block/code-block.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/copy2clipboard-button/copy2clipboard-button.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts

Fixes: https://tracker.ceph.com/issues/64405 …

mgr/dashboard: added cephfs mount details

---

src/script/backport-create-issue

script: add squid release to backport-create-issue

---

doc/rados/operations/placement-groups.rst

Add a link in the "Placement Groups" section that links to Sage Weil's April 5, 2019 blog post "New in Nautilus: PG merging and autotuning". …

doc/rados: add link to pg blog post

---

src/ceph-node-proxy/ceph_node_proxy/main.py
src/ceph-node-proxy/ceph_node_proxy/reporter.py
src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/serve.py
src/pybind/mgr/orchestrator/_interface.py
src/pybind/mgr/orchestrator/module.py

This makes the daemon handle the error nicer in fetch_oob_details()

node-proxy: improve http error handling in fetch_oob_details

---

src/ceph-node-proxy/ceph_node_proxy/main.py
src/ceph-node-proxy/ceph_node_proxy/reporter.py
src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/serve.py
src/pybind/mgr/orchestrator/_interface.py
src/pybind/mgr/orchestrator/module.py

This makes the daemon handle the error nicer in fetch_oob_details()
Signed-off-by: Guillaume Abrioux <gabrioux@ibm.com>

(reef) node-proxy: improve http error handling in fetch_oob_details

---

doc/cephadm/services/nfs.rst

s/nfs-ganesha/.nfs/ in doc/cephadm/services/nfs, in accordance with information given to me by John Mulligan over Slack. …

doc/cephadm: correct nfs config pool name

---

qa/workunits/mon/config.sh
src/common/ceph_mutex.h
src/common/config_obs_mgr.h
src/common/config_proxy.h
src/crimson/common/config_proxy.h

backport tracker: https://tracker.ceph.com/issues/63456
---
backport of https://github.com/ceph/ceph/pull/53568
parent tracker: https://tracker.ceph.com/issues/62832

reef: common: resolve config proxy deadlock using refcounted pointers

---

doc/glossary.rst

Add a link in the CRUSH definition to the original CRUSH paper.
(cherry picked from commit aa1e6352d0c2c77c299a16f93e16e83903fb9d54) …

reef: doc/glossary: Add link to CRUSH paper

---

doc/cephadm/services/nfs.rst

s/nfs-ganesha/.nfs/ in doc/cephadm/services/nfs, in accordance with information given to me by John Mulligan over Slack.
(cherry picked from commit 574421aeec3bdd502c64e87102846e5181b18415) …

quincy: doc/cephadm: correct nfs config pool name

---

doc/cephadm/services/nfs.rst

s/nfs-ganesha/.nfs/ in doc/cephadm/services/nfs, in accordance with information given to me by John Mulligan over Slack.
(cherry picked from commit 574421aeec3bdd502c64e87102846e5181b18415) …

reef: doc/cephadm: correct nfs config pool name

---

src/osd/OSDMap.cc

Fix compilation warnings for PR https://github.com/ceph/ceph/pull/55198
- Component …

osd: Fix compilation warnings for PR https://github.com/ceph/ceph/pull/55198

---

PendingReleaseNotes
qa/workunits/rbd/cli_generic.sh
src/test/cli/rbd/help.t
src/tools/rbd/action/Children.cc

Fixes: https://tracker.ceph.com/issues/64376 …

tools/rbd: make 'children' command support --image-id

---

src/librbd/io/Types.h
src/test/librbd/io/test_mock_ObjectRequest.cc

librbd: fix split() for SparseExtent and SparseBufferlistExtent

---

doc/rados/operations/placement-groups.rst

Add a link in the "Placement Groups" section that links to Sage Weil's April 5, 2019 blog post "New in Nautilus: PG merging and autotuning".
(cherry picked from commit 9344893e0857be8c6ae134f6d4d5e9057e2cb99e) …

reef: doc/rados: add link to pg blog post

---

doc/rados/operations/placement-groups.rst

Add a link in the "Placement Groups" section that links to Sage Weil's April 5, 2019 blog post "New in Nautilus: PG merging and autotuning".
(cherry picked from commit 9344893e0857be8c6ae134f6d4d5e9057e2cb99e) …

quincy: doc/rados: add link to pg blog post

---

qa/cephfs/overrides/ignorelist_health.yaml
qa/cephfs/overrides/ignorelist_wrongly_marked_down.yaml
qa/suites/orch/cephadm/dashboard/task/test_e2e.yaml
qa/suites/orch/cephadm/mgr-nfs-upgrade/1-start.yaml
qa/suites/orch/cephadm/osds/2-ops/repave-all.yaml
qa/suites/orch/cephadm/osds/2-ops/rm-zap-add.yaml
qa/suites/orch/cephadm/osds/2-ops/rm-zap-flag.yaml
qa/suites/orch/cephadm/osds/2-ops/rm-zap-wait.yaml
qa/suites/orch/cephadm/osds/2-ops/rmdir-reactivate.yaml
qa/suites/orch/cephadm/smoke/start.yaml
qa/suites/orch/cephadm/thrash/2-thrash.yaml
qa/suites/orch/cephadm/upgrade/4-wait.yaml
qa/suites/orch/cephadm/workunits/task/test_nfs.yaml
qa/suites/orch/cephadm/workunits/task/test_orch_cli.yaml
qa/suites/orch/cephadm/workunits/task/test_orch_cli_mon.yaml
qa/suites/rados/basic/tasks/rados_api_tests.yaml
qa/suites/rados/basic/tasks/rados_cls_all.yaml
qa/suites/rados/basic/tasks/rados_python.yaml
qa/suites/rados/verify/tasks/rados_cls_all.yaml
qa/tasks/thrashosds-health.yaml

Semi-backport of 00fc7960f682a16aa7a02aeb0300780a1bf56476. (#55507) Some changes had to be made though for yaml files and warnings that are specific to pacific.
The motivation is that we are still testing stuff for pacific, i.e. in https://trello.com/c/3cEnuGqr/1952-wip-yuri10-testing-2024-02-08-0854-pacific, so we'll need clean results.
Fixes: https://tracker.ceph.com/issues/64343 …

pacific: qa/suites/orch: whitelist warnings that are expected in test environments

---

doc/rados/operations/placement-groups.rst

Add a definition of Placement Groups to …

doc/rados: add PG definition

---

doc/rados/operations/placement-groups.rst

Add a definition of Placement Groups to
(cherry picked from commit 39c809b33fe27064277292b721639cbb144fac6a) …

quincy: doc/rados: add PG definition

---

doc/rados/operations/placement-groups.rst

Add a definition of Placement Groups to
(cherry picked from commit 39c809b33fe27064277292b721639cbb144fac6a) …

reef: doc/rados: add PG definition

---

doc/man/8/ceph-objectstore-tool.rst

Edit the section "Manipulating the Object Map Key" in doc/man/8/ceph-objectstore-tool.rst. …

doc/man: edit "manipulating the omap key"

---

doc/man/8/ceph-objectstore-tool.rst

Edit the section "Manipulating the Object Map Key" in doc/man/8/ceph-objectstore-tool.rst.
(cherry picked from commit 44ec668d43951c2710271fb3ca1799c4c4ded940) …

reef: doc/man: edit "manipulating the omap key"

---

doc/man/8/ceph-objectstore-tool.rst

Edit the section "Manipulating the Object Map Key" in doc/man/8/ceph-objectstore-tool.rst.
(cherry picked from commit 44ec668d43951c2710271fb3ca1799c4c4ded940) …

quincy: doc/man: edit "manipulating the omap key"

---

doc/cephfs/add-remove-mds.rst

Disambiguate a note in doc/cephfs/add-remove-mds.rst to help readers distinguish between cases in which they might want to use an automated tool such as cephadm to deploy MDSes and cases in which they might want to manually deploy MDSes.
See: https://github.com/ceph/ceph/pull/45639
Tracker: https://tracker.ceph.com/issues/54551 …

doc/cephfs: edit add-remove-mds

---

doc/man/8/radosgw-admin.rst
src/rgw/rgw_admin.cc
src/rgw/rgw_obj_types.h

Adds a new sub-command to radosgw-admin to list the manifest of RADOS objects that contain the RGW object's data.
- …

rgw: add new `object manifest` sub-command

---

doc/radosgw/multisite.rst

Edit "Varieties of Multi-Site Configuration" in
doc/radosgw/multisite.rst.
(cherry picked from commit 8af910f877d1c7b873c2a13cec5d4ea1a4de4a79) …

quincy: doc/radosgw: edit multisite.rst

---

doc/radosgw/multisite.rst

Edit "Varieties of Multi-Site Configuration" in
doc/radosgw/multisite.rst.
(cherry picked from commit 8af910f877d1c7b873c2a13cec5d4ea1a4de4a79) …

reef: doc/radosgw: edit multisite.rst

---

doc/rados/configuration/osd-config-ref.rst

doc/rados/configuration/osd-config-ref: fix typo

---

doc/rados/configuration/osd-config-ref.rst

Signed-off-by: Pierre Riteau <pierre@stackhpc.com>
(cherry picked from commit d25b6b9dd2cee81d33f2ad2f0718c6ccdeadbe2b) …

quincy: doc/rados/configuration/osd-config-ref: fix typo

---

doc/rados/configuration/osd-config-ref.rst

Signed-off-by: Pierre Riteau <pierre@stackhpc.com>
(cherry picked from commit d25b6b9dd2cee81d33f2ad2f0718c6ccdeadbe2b) …

reef: doc/rados/configuration/osd-config-ref: fix typo

---

doc/rados/operations/add-or-rm-mons.rst

Fix broken links in doc/rados/operations/add-or-rm-mons.rst.
(cherry picked from commit 2e2519367099461415248353d7c7725c0567511d) …

reef: doc/rados: fix broken links

---

qa/tasks/cephfs/test_volumes.py

https://tracker.ceph.com/issues/59714 …

qa: disable snapshot_clone_no_wait for some tests

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/nvmeof_client.py
src/pybind/mgr/dashboard/services/proto/gateway.proto
src/pybind/mgr/dashboard/services/proto/gateway_pb2.py
src/pybind/mgr/dashboard/services/proto/gateway_pb2_grpc.py

Fixes: https://tracker.ceph.com/issues/64384 …

mgr/dashboard: update nvmeof protoc to 1.0.0

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolumegroup-form/cephfs-subvolumegroup-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolumegroup-form/cephfs-subvolumegroup-form.component.ts

Fixes: https://tracker.ceph.com/issues/64487 …

mgr/dashboard: fix subvolume group edit

---

doc/cephfs/add-remove-mds.rst

Disambiguate a note in doc/cephfs/add-remove-mds.rst to help readers distinguish between cases in which they might want to use an automated tool such as cephadm to deploy MDSes and cases in which they might want to manually deploy MDSes.
See: https://github.com/ceph/ceph/pull/45639
Tracker: https://tracker.ceph.com/issues/54551
(cherry picked from commit 39ad6264aa1c97b04974e04046033887325ed2b2) …

reef: doc/cephfs: edit add-remove-mds

---

doc/cephfs/add-remove-mds.rst

Disambiguate a note in doc/cephfs/add-remove-mds.rst to help readers distinguish between cases in which they might want to use an automated tool such as cephadm to deploy MDSes and cases in which they might want to manually deploy MDSes.
See: https://github.com/ceph/ceph/pull/45639
Tracker: https://tracker.ceph.com/issues/54551
(cherry picked from commit 39ad6264aa1c97b04974e04046033887325ed2b2) …

quincy: doc/cephfs: edit add-remove-mds

---

src/pybind/mgr/rook/module.py
src/pybind/mgr/rook/rook_cluster.py

Backport of: https://github.com/ceph/ceph/pull/55350
Tracker: https://tracker.ceph.com/issues/6452
Backport of: https://github.com/ceph/ceph/pull/55686
Tracker: https://tracker.ceph.com/issues/64521
**Note:** the last commit `removing HostPattern references` is to accommodate for some mypy enhancements changes that were not backported from main to reef. …

reef: backport rook/mgr recent changes

---

src/crimson/osd/shard_services.cc

crimson/osd/shard_services: make sure that only up/acting members can create pgs
Fixes: https://tracker.ceph.com/issues/64282 …

crimson/osd/shard_services: make sure that only up/acting members can create pgs

---

src/common/options/global.yaml.in
src/os/bluestore/BitmapFreelistManager.cc
src/os/bluestore/BitmapFreelistManager.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/FreelistManager.h

parameter.
This allows to override persistent min_alloc_size if needed. This might be helpful to troubleshoot and work around issues like https://tracker.ceph.com/issues/63618 …

os/bluestore: introduce bluestore_debug_enforce_min_alloc_size config

---

doc/rbd/nvmeof-initiator-esx.rst
doc/rbd/nvmeof-initiator-linux.rst
doc/rbd/nvmeof-initiators.rst
doc/rbd/nvmeof-overview.rst
doc/rbd/nvmeof-requirements.rst
doc/rbd/nvmeof-target-configure.rst
doc/rbd/rbd-integrations.rst

doc: Initial NVMe-oF gateway docs

---

doc/rbd/nvmeof-initiator-esx.rst
doc/rbd/nvmeof-initiator-linux.rst
doc/rbd/nvmeof-initiators.rst
doc/rbd/nvmeof-overview.rst
doc/rbd/nvmeof-requirements.rst
doc/rbd/nvmeof-target-configure.rst
doc/rbd/rbd-integrations.rst

- Add nvmeof-initiator-esx.rst
- Add nvmeof-initiator-linux.rst
- Add nvmeof-initiators.rst
- Add nvmeof-overview.rst
- Add nvmeof-requirements.rst
- Add nvmeof-target-configure.rst
- Add links to rbd-integrations.rst
Co-authored-by: Ilya Dryomov <idryomov@redhat.com>
Signed-off-by: Orit Wasserman <owasserm@ibm.com>
(cherry picked from commit 9f86c35a0d308c6ff24d3a033f5314ec86bf896b) …

squid: doc: Add NVMe-oF gateway documentation

---

doc/rbd/nvmeof-initiator-esx.rst
doc/rbd/nvmeof-initiator-linux.rst
doc/rbd/nvmeof-initiators.rst
doc/rbd/nvmeof-overview.rst
doc/rbd/nvmeof-requirements.rst
doc/rbd/nvmeof-target-configure.rst
doc/rbd/rbd-integrations.rst

- Add nvmeof-initiator-esx.rst
- Add nvmeof-initiator-linux.rst
- Add nvmeof-initiators.rst
- Add nvmeof-overview.rst
- Add nvmeof-requirements.rst
- Add nvmeof-target-configure.rst
- Add links to rbd-integrations.rst
Co-authored-by: Ilya Dryomov <idryomov@redhat.com>
Signed-off-by: Orit Wasserman <owasserm@ibm.com>
(cherry picked from commit 9f86c35a0d308c6ff24d3a033f5314ec86bf896b) …

reef: doc: Add NVMe-oF gateway documentation

---

doc/dev/crimson/crimson.rst

doc/crimson: cleanup duplicate seastore description.
- …

doc/crimson: cleanup duplicate seastore description

---

doc/dev/crimson/crimson.rst

(cherry picked from commit 8d766c57173cf6bdea0d8fcfa8fa3c1b61fd10ef) …

reef: doc/crimson: cleanup duplicate seastore description

---

doc/dev/crimson/crimson.rst

Repair a confusing sentence in doc/dev/crimson.rst.
- …

doc/dev: fix spelling in crimson.rst

---

doc/rbd/nvmeof-target-configure.rst

Fix the numbering in an ordered list. The numbering was thrown off because a ".. prompt" directive was improperly indented (it wasn't indented at all).
See https://github.com/ceph/ceph/pull/55540#discussion_r1500051264
(cherry picked from commit 6df12da2cd0946092fa49f8dbb7661e4487c3c22) …

reef: doc/rbd: repair ordered list

---

doc/rbd/nvmeof-target-configure.rst

Fix the numbering in an ordered list. The numbering was thrown off because a ".. prompt" directive was improperly indented (it wasn't indented at all).
See https://github.com/ceph/ceph/pull/55540#discussion_r1500051264
(cherry picked from commit 6df12da2cd0946092fa49f8dbb7661e4487c3c22) …

squid: doc/rbd: repair ordered list

---

doc/dev/crimson/crimson.rst

Repair a confusing sentence in doc/dev/crimson.rst.
(cherry picked from commit dfdb5e124a19e0c5ce1e7ba47e574e0504e7091f) …

squid: doc/dev: fix spelling in crimson.rst

---

doc/dev/crimson/crimson.rst

Repair a confusing sentence in doc/dev/crimson.rst.
(cherry picked from commit dfdb5e124a19e0c5ce1e7ba47e574e0504e7091f) …

reef: doc/dev: fix spelling in crimson.rst

---

doc/dev/crimson/crimson.rst

Repair a confusing sentence in doc/dev/crimson.rst.
(cherry picked from commit dfdb5e124a19e0c5ce1e7ba47e574e0504e7091f) …

quincy: doc/dev: fix spelling in crimson.rst

---

doc/glossary.rst

Add an entry for "OMAP" to the glossary. This commit represents only the first improvement to the documentation of OMAP in the Ceph docs suite. …

doc/glossary: Add "OMAP" to glossary

---

doc/glossary.rst

Add an entry for "OMAP" to the glossary. This commit represents only the first improvement to the documentation of OMAP in the Ceph docs suite.
(cherry picked from commit 1d8baa1d4c3583f4a8dc0f46d81f198a3d027e4d) …

quincy: doc/glossary: Add "OMAP" to glossary

---

doc/glossary.rst

Add an entry for "OMAP" to the glossary. This commit represents only the first improvement to the documentation of OMAP in the Ceph docs suite.
(cherry picked from commit 1d8baa1d4c3583f4a8dc0f46d81f198a3d027e4d) …

reef: doc/glossary: Add "OMAP" to glossary

---

doc/glossary.rst

Add an entry for "OMAP" to the glossary. This commit represents only the first improvement to the documentation of OMAP in the Ceph docs suite.
(cherry picked from commit 1d8baa1d4c3583f4a8dc0f46d81f198a3d027e4d) …

squid: doc/glossary: Add "OMAP" to glossary

---

src/crimson/os/seastore/seastore.cc

Fixes: https://tracker.ceph.com/issues/64535 …

crimson/os/seastore: fix wrong-positioned asserts

---

doc/man/8/mount.ceph.rst

Fixes: https://tracker.ceph.com/issues/62837 …

doc/man/8/mount.ceph.rst: add more mount options

---

doc/man/8/mount.ceph.rst

Fixes: https://tracker.ceph.com/issues/62837
Signed-off-by: Xiubo Li <xiubli@redhat.com>
(cherry picked from commit d5639cc670d248da7c84e6f2eaf73ce40bd93db4) …

squid: doc/man/8/mount.ceph.rst: add more mount options

---

doc/man/8/mount.ceph.rst

Fixes: https://tracker.ceph.com/issues/62837
Signed-off-by: Xiubo Li <xiubli@redhat.com>
(cherry picked from commit d5639cc670d248da7c84e6f2eaf73ce40bd93db4) …

quincy: doc/man/8/mount.ceph.rst: add more mount options

---

qa/cephfs/overrides/ignorelist_health.yaml
qa/cephfs/overrides/ignorelist_wrongly_marked_down.yaml
qa/suites/orch/cephadm/dashboard/task/test_e2e.yaml
qa/suites/orch/cephadm/mgr-nfs-upgrade/1-start.yaml
qa/suites/orch/cephadm/osds/2-ops/rmdir-reactivate.yaml
qa/suites/orch/cephadm/thrash/2-thrash.yaml
qa/suites/orch/cephadm/workunits/task/test_nfs.yaml
qa/suites/orch/cephadm/workunits/task/test_orch_cli.yaml
qa/suites/rados/basic/tasks/rados_api_tests.yaml
qa/tasks/thrashosds-health.yaml

Problem:
1. Not enough whitelisting for certain Cephadm failures
2. previous PR that landed has a typo that
causes https://tracker.ceph.com/issues/64452
Solution:
1. Add more whitelisting
2. Fix typo in https://tracker.ceph.com/issues/64452
Fixes: https://tracker.ceph.com/issues/64452
Signed-off-by: Kamoltat <ksirivad@redhat.com> …

pacific: qa/suites: added more whitelisting + fix typo

---

qa/tasks/cephfs/test_nfs.py
src/pybind/mgr/nfs/export.py

mgr/nfs: validate path before updating a cephfs export

---

src/pybind/mgr/dashboard/controllers/cephfs.py

Fixes: https://tracker.ceph.com/issues/64559 …

mgr/dashboard: fix volume creation with multiple hosts

---

src/common/options/global.yaml.in
src/osd/PeeringState.cc

Fixes: https://tracker.ceph.com/issues/64002 …

osd/PeeringState: introduce osd_skip_check_past_interval_bounds

---

doc/rados/operations/add-or-rm-mons.rst

Add a procedure to /doc/rados/operations/add-or-rm-mons.rst that explains how to change the public_network in a Ceph cluster deployed with cephadm. This procedure was developed by Eugen Block, and can be seen in its original form here:
https://heiterbiswolkig.blogs.nde.ag/2024/02/22/cephadm-change-public-network/
(cherry picked from commit 0b6739a4aa2dd931d97b8af9b3a352969f8767c2)
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches- …

reef: doc/rados: add "change public network" procedure

---

doc/rados/operations/add-or-rm-mons.rst

Add a procedure to /doc/rados/operations/add-or-rm-mons.rst that explains how to change the public_network in a Ceph cluster deployed with cephadm. This procedure was developed by Eugen Block, and can be seen in its original form here:
https://heiterbiswolkig.blogs.nde.ag/2024/02/22/cephadm-change-public-network/
(cherry picked from commit 0b6739a4aa2dd931d97b8af9b3a352969f8767c2)
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches- …

squid: doc/rados: add "change public network" procedure

---

src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.cc
src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/seastore.h

crimson/os/seastore: two attrs related bug fixes

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.ts

Fixes: https://tracker.ceph.com/issues/64613 …

mgr/dashboard: fix snap schedule date format

---

src/script/ceph-backport.sh

Problem:
Current backport script lacks PR template
Solution:
Add PR template to backport script …

src/scripts/ceph-backport.sh: Add PR checklist

---

qa/suites/upgrade/reef-p2p/reef-p2p-parallel/point-to-point-upgrade.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-parallel/supported-all-distro/centos_8.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-parallel/supported-all-distro/ubuntu_latest.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/0-cluster/openstack.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/0-cluster/start.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/1-ceph-install/reef.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/1.1.short_pg_log.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/2-partial-upgrade/firsthalf.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/3-thrash/default.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/4-workload/fsx.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/4-workload/radosbench.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/4-workload/rbd-cls.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/4-workload/rbd-import-export.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/4-workload/rbd_api.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/4-workload/readwrite.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/4-workload/snaps-few-objects.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/5-finish-upgrade.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/6-final-workload/rbd-python.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/6-final-workload/snaps-many-objects.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/objectstore/bluestore-bitmap.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/objectstore/bluestore-comp.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/objectstore/bluestore-stupid.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/supported-all-distro/ubuntu_latest.yaml
qa/suites/upgrade/reef-p2p/reef-p2p-stress-split/thrashosds-health.yaml

qa/tests: added the initial reef-p2p suite

---

src/mds/Server.cc
src/mds/Server.h

Fixes: https://tracker.ceph.com/issues/64061
Signed-off-by: Xue Yantao <xueyantao2114@163.com> …

mds: check file layout in mknod

---

src/pybind/mgr/dashboard/frontend/src/app/shared/enum/repeat-frequency.enum.ts

Added M and Y (month and year) repeat frequencies to snap schedule create form.
Fixes: https://tracker.ceph.com/issues/64614 …

mgr/dashboard: add snap schedule M, Y frequencies

---

src/cephadm/cephadmlib/daemons/nvmeof.py

nvmeof: Add mount for log location

---

doc/cephadm/services/monitoring.rst

Fixes: https://tracker.ceph.com/issues/64596 …

doc: adding documentation for secure monitoring stack configuration

---

doc/dev/release-process.rst

doc/dev/release-process.rst: modify for prerelease mechanism

---

src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/seastore.h

At present, we just copy attrs and omaps one by one, which is not efficient but very important in terms of functionality especially for the teuthology tests …

crimson/os/seastore: copy attrs and omaps when cloning objects

---

src/rgw/rgw_lc.cc

Backport tracker: https://tracker.ceph.com/issues/64510
- …

squid: backport: rgw/lc: decorating log events with more details

---

src/os/bluestore/BlueStore.cc
src/test/objectstore/store_test.cc

Fixes: https://tracker.ceph.com/issues/64443 …

test/store_test: fix DeferredWrite test when prefer_deferred_size=0

---

doc/glossary.rst
doc/man/8/ceph-mds.rst

Improve the entry for "MDS" in doc/glossary.rst by linking to the "ceph-mds" man page and mentioning the relationship between clients and MDS (or MDSes). …

doc/glossary: improve "MDS" entry

---

doc/glossary.rst
doc/man/8/ceph-mds.rst

Improve the entry for "MDS" in doc/glossary.rst by linking to the "ceph-mds" man page and mentioning the relationship between clients and MDS (or MDSes).
(cherry picked from commit 2c6983d8b4e841f2bfbc4e4f82bb0e41e10aec7e) …

squid: doc/glossary: improve "MDS" entry

---

doc/glossary.rst
doc/man/8/ceph-mds.rst

Improve the entry for "MDS" in doc/glossary.rst by linking to the "ceph-mds" man page and mentioning the relationship between clients and MDS (or MDSes).
(cherry picked from commit 2c6983d8b4e841f2bfbc4e4f82bb0e41e10aec7e) …

quincy: doc/glossary: improve "MDS" entry

---

doc/glossary.rst
doc/man/8/ceph-mds.rst

Improve the entry for "MDS" in doc/glossary.rst by linking to the "ceph-mds" man page and mentioning the relationship between clients and MDS (or MDSes).
(cherry picked from commit 2c6983d8b4e841f2bfbc4e4f82bb0e41e10aec7e) …

reef: doc/glossary: improve "MDS" entry

---

doc/dev/internals.rst

Edit doc/dev/internals.rst. Make a few sentences pithier.
- …

doc/dev: edit internals.rst

---

doc/dev/internals.rst

Edit doc/dev/internals.rst. Make a few sentences pithier.
(cherry picked from commit e16ab1df72c3640db907e377da7ca97ce3eaa26e) …

quincy: doc/dev: edit internals.rst

---

doc/dev/internals.rst

Edit doc/dev/internals.rst. Make a few sentences pithier.
(cherry picked from commit e16ab1df72c3640db907e377da7ca97ce3eaa26e) …

reef: doc/dev: edit internals.rst

---

doc/dev/internals.rst

Edit doc/dev/internals.rst. Make a few sentences pithier.
(cherry picked from commit e16ab1df72c3640db907e377da7ca97ce3eaa26e) …

squid: doc/dev: edit internals.rst

---

src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/seastore.h

crimson/os/seastore: adjust SeaStore::_omap_set_kvs() params

---

src/rgw/rgw_op.cc

AWSv4ComplMulti::complete() throws exceptions on errors, but nothing catches these
Fixes: https://tracker.ceph.com/issues/64549
<details>
</details>

rgw/auth: do_aws4_auth_completion() catches exceptions

---

.github/workflows/create-backport-trackers.yml

Getting warning about node16 being deprecated.  The workflow doesn't use node directly, but through the external actions.  Moving to node20 requires changing setup-python version; Bhacaz/checkout-files is deprecated and recommends actions/checkout. …

.github/workflows/create-backport-trackers.yml: update actions

---

doc/rados/operations/placement-groups.rst
doc/rados/operations/pools.rst
doc/radosgw/pools.rst

Remove mention of the "PG calc" tool from the documentation. I have removed all mention of this in one fell swoop to help posterity restore mention of this tool if we decide we need to do so.
(cherry picked from commit ccb851d2a431647124754e1252df66ed11d0e900) …

reef: doc/rados: remove PGcalc from docs

---

doc/rados/operations/placement-groups.rst
doc/rados/operations/pools.rst
doc/radosgw/pools.rst

Remove mention of the "PG calc" tool from the documentation. I have removed all mention of this in one fell swoop to help posterity restore mention of this tool if we decide we need to do so.
(cherry picked from commit ccb851d2a431647124754e1252df66ed11d0e900) …

squid: doc/rados: remove PGcalc from docs

---

src/client/Client.cc

Importantly: do this before any locks are to be acquired.
Fixes: https://tracker.ceph.com/issues/64503
- Tracker …

client: log debug message when requesting unmount

---

doc/architecture.rst

Remove the word "detailed" in a sentence immediately following a sentence containing the word "detail".
- Tracker …

doc/architecture: remove pleonasm

---

src/script/ceph-backport.sh

This reverts commit 4aba45e2374168e4485f31fea4fa1c441c35443e
commit causes backport script to fail
reverting and recommiting is the best option
Fixes: https://tracker.ceph.com/issues/64674 …

Revert "src/scripts/ceph-backport.sh: Add PR checklist"

---

src/rgw/rgw_s3select.cc

https://tracker.ceph.com/issues/63245
https://github.com/ceph/s3select/pull/151
https://github.com/ceph/s3select/pull/148
https://github.com/ceph/s3select/pull/144
https://github.com/ceph/s3select/pull/130
<details>
- `jenkins …

rgw/S3select: remove assert from csv-parser, adding updates

---

src/os/bluestore/AvlAllocator.cc
src/os/bluestore/BlueFS.cc
src/os/bluestore/BtreeAllocator.cc
src/os/bluestore/StupidAllocator.cc
src/os/bluestore/StupidAllocator.h
src/os/bluestore/fastbmap_allocator_impl.cc
src/test/objectstore/Allocator_test.cc
src/test/objectstore/fastbmap_allocator_test.cc
src/test/objectstore/store_test.cc

Parent tracker: https://tracker.ceph.com/issues/63618
Parent tracker: https://tracker.ceph.com/issues/62815
Backport of: https://github.com/ceph/ceph/pull/53483
Backport tracker: https://tracker.ceph.com/issues/63758
Backport tracker: https://tracker.ceph.com/issues/63761 …

quincy: os/bluestore: get rid off resulting lba alignment in allocators

---

src/mon/ConnectionTracker.cc

There are certain situations where we would
come across rank -1 in our MON connection scores;
- New MON sends probe message to existing MON, existing MON handle probe message by adding -1
to existing peer_scores.
This is not good because we want to implement
a connection scores check mechanism where we
should not have to take into account the possibility of having rank -1 in our score.
Fixes: https://tracker.ceph.com/issues/59564
Signed-off-by: Kamoltat <ksirivad@redhat.com>
(cherry picked from commit 6ffc70a1b7f3dbe9237c2379c477d7dc4898024f)
Backporting relevant commits from main PR:
https://github.com/ceph/ceph/pull/52380/
- If you are submitting …

quincy: mon/ConnectionTracker.cc: disregard connection scores from mon_rank = -1

---

src/common/options/rgw.yaml.in

(cherry picked from commit 1796022aa4778226c2d7e04c1cb989ab9d025272) …

quincy: src/common/options: Correct typo in rgw.yaml.in

---

doc/architecture.rst

Remove the word "detailed" in a sentence immediately following a sentence containing the word "detail".
(cherry picked from commit 7791509741d8c21e273a46374a087dcca53a2816) …

reef: doc/architecture: remove pleonasm

---

doc/architecture.rst

Remove the word "detailed" in a sentence immediately following a sentence containing the word "detail".
(cherry picked from commit 7791509741d8c21e273a46374a087dcca53a2816) …

quincy: doc/architecture: remove pleonasm

---

doc/architecture.rst

Remove the word "detailed" in a sentence immediately following a sentence containing the word "detail".
(cherry picked from commit 7791509741d8c21e273a46374a087dcca53a2816) …

squid: doc/architecture: remove pleonasm

---

doc/rados/operations/pools.rst

Link to the instructions for manually setting the number of PGs per pool, from the mention of placement groups. These instructions are included here in response to a request from Ronen Friedman on the occasion of the removal of links to the PGcalc (see https://github.com/ceph/ceph/pull/55899#pullrequestreview-1912940118).
(cherry picked from commit 9da81b87ca161370c869b49f5d4e6b50edd54a0e) …

squid: doc/rados: link to pg setting commands

---

doc/rados/operations/pools.rst

Link to the instructions for manually setting the number of PGs per pool, from the mention of placement groups. These instructions are included here in response to a request from Ronen Friedman on the occasion of the removal of links to the PGcalc (see https://github.com/ceph/ceph/pull/55899#pullrequestreview-1912940118).
(cherry picked from commit 9da81b87ca161370c869b49f5d4e6b50edd54a0e)
<details>
- …

quincy: doc/rados: link to pg setting commands

---

src/exporter/util.cc
src/exporter/util.h

- initialize member variable in-class
- use string_view for file and function name
- remove BlockTimer::ms
- use std::chrono::high_resolution_clock for timing
- drop unused macro
- drop unused function …

ceph-exporter: cleanups

---

src/crimson/os/seastore/omap_manager.h

Teuthology tests can issue large omap kvs …

crimson/os/seastore/omap_manager: expand omap tree nodes

---

src/crimson/os/seastore/async_cleaner.cc

This could prevent future developers from rendering the cleaner abnormal unexpectedly …

crimson/os/seastore/async_cleaner: add comments to clarify what kind of extents would be considered dead by the cleaner

---

src/pybind/mgr/dashboard/controllers/hardware.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/hardware.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/hardware.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/card-row/card-row.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/card-row/card-row.component.scss
src/pybind/mgr/dashboard/frontend/src/app/shared/components/card-row/card-row.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/hardware.enum.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/pipes.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/pluralize.pipe.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/pluralize.pipe.ts
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/hardware.py
src/pybind/mgr/dashboard/services/orchestrator.py

On the landing page of the Dashboard, add the hardware status summary
Error:
[screen-capture (19).webm](https://github.com/ceph/ceph/assets/106810838/56f01649-dd32-4414-9d29-11fddc10d8c2)
No errors:
[screen-capture (20).webm](https://github.com/ceph/ceph/assets/106810838/35647317-d060-4c5f-a204-3e27b78ec535)
Fixes:https://tracker.ceph.com/issues/64329 …

mgr/dashboard: add hardware status summary

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-mount-details/cephfs-mount-details.component.ts

Fixes: https://tracker.ceph.com/issues/64716 …

mgr/dashboard: fixed cephfs mount command

---

src/client/Client.cc
src/client/Client.h
src/test/client/nonblocking.cc

client: do not proceed with I/O if filehandle is invalid

---

src/crimson/os/alienstore/thread_pool.h

std::counting_semaphore has the bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104928, go back to our homebrew version …

crimson/os/alienstore: use homebrew counting_semaphore

---

doc/dev/developer_guide/testing_integration_tests/tests-integration-testing-teuthology-workflow.rst

Improve a couple of sentences in
doc/dev/developer_guide_testing_integration_tests/tests-integration-testing-teutology-workflow.rst.
<details>
</details>

doc/dev: edit teuthology workflow

---

qa/crontab/teuthology-cronjobs

This is a fairly big overhaul of nightlies. We're bringing back weekly testing of the main and release branches. Squid pre-release will have suites tested twice a week and at higher priority (-p 100) which is the highest QE priority [1].
[1] https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/tests-integration-testing-teuthology-intro/#testing-priority …

qa/crontab: update crontab for nightlies to include squid (+)

---

src/mds/CDentry.h
src/mds/MDSMetaRequest.h
src/mds/MDSRank.cc
src/mds/MDSRank.h
src/mds/Server.cc
src/mds/Server.h
src/mds/StrayManager.cc
src/mds/StrayManager.h

backport tracker: https://tracker.ceph.com/issues/63262
---
backport of https://github.com/ceph/ceph/pull/53280
parent tracker: https://tracker.ceph.com/issues/62702 …

reef: mds: fix issuing redundant reintegrate/migrate_stray requests

---

qa/tasks/cephfs/test_multifs_auth.py

backport tracker: https://tracker.ceph.com/issues/64705
---
backport of https://github.com/ceph/ceph/pull/55346
parent tracker: https://tracker.ceph.com/issues/64700

reef: qa: remove error string checks and check w/ return value

---

doc/dev/developer_guide/testing_integration_tests/tests-integration-testing-teuthology-workflow.rst

Improve a couple of sentences in
doc/dev/developer_guide_testing_integration_tests/tests-integration-testing-teutology-workflow.rst.
(cherry picked from commit 51796e80f35da8ca13b72f31eeafefd4c1e40773) …

reef: doc/dev: edit teuthology workflow

---

doc/dev/developer_guide/testing_integration_tests/tests-integration-testing-teuthology-workflow.rst

Improve a couple of sentences in
doc/dev/developer_guide_testing_integration_tests/tests-integration-testing-teutology-workflow.rst.
(cherry picked from commit 51796e80f35da8ca13b72f31eeafefd4c1e40773) …

squid: doc/dev: edit teuthology workflow

---

qa/distros/all/centos_7.6.yaml
qa/distros/all/centos_8.0.yaml
qa/distros/all/centos_8.1.yaml
qa/distros/all/centos_8.2.yaml
qa/distros/all/centos_8.3.yaml
qa/distros/all/centos_8.stream.yaml
qa/distros/all/centos_9.stream.yaml
qa/distros/all/rhel_7.6.yaml
qa/distros/all/rhel_7.7.yaml
qa/distros/all/rhel_8.0.yaml
qa/distros/all/rhel_8.1.yaml
qa/distros/all/rhel_8.3.yaml
qa/distros/all/rhel_8.4.yaml
qa/distros/all/rhel_8.5.yaml
qa/distros/all/rhel_8.6.yaml
qa/distros/container-hosts/centos_8.stream_container_tools.yaml
qa/distros/container-hosts/centos_8.stream_container_tools_crun.yaml
qa/distros/container-hosts/centos_9.stream.yaml
qa/distros/container-hosts/centos_9.stream_runc.yaml
qa/distros/podman/centos_8.stream_container_tools.yaml
qa/distros/podman/centos_9.stream.yaml

Fixes: http://tracker.ceph.com/issues/64616 …

qa: ignore container checkpoint/restore related selinux denials for centos9

---

qa/cephfs/overrides/ignorelist_health.yaml
qa/cephfs/overrides/ignorelist_wrongly_marked_down.yaml

Seems like a fallout from https://github.com/ceph/ceph/pull/54312
- Component …

qa/cephfs: add more ignorelist entries

---

src/crimson/os/seastore/transaction_manager.h

crimson/os/seastore: allow to remap the dirty extent

---

src/rgw/rgw_auth_s3.cc

https://tracker.ceph.com/issues/64676 …

rgw_sigv4: handle '0;' as trailer-chunk boundary

---

doc/architecture.rst

s/client/clients/ where necessary, and add a link to the glossary.
- Component …

doc/architecture: correct typo

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/nvmeof_client.py
src/pybind/mgr/dashboard/services/proto/gateway_pb2_grpc.py

Even if the traddr is passed from the API, it gets overriden by the None hard-coded in the code.
Fixes: https://tracker.ceph.com/issues/64714 …

mgr/dashboard: listener addr is always none

---

qa/tasks/cephfs/test_nfs.py
src/pybind/mgr/nfs/export.py
src/pybind/mgr/object_format.py
src/pybind/mgr/tests/test_object_format.py

Backport tracker: https://tracker.ceph.com/issues/63691
Parent tracker: https://tracker.ceph.com/issues/62641
Backport of https://github.com/ceph/ceph/pull/53431 …

reef: mgr/(object_format && nfs/export): enhance nfs export update failure response

---

doc/dev/crimson/crimson.rst

doc/dev/crimson: add Code Walkthroughs

---

doc/start/get-involved.rst

Add a link to the ceph-storage Slack invitation page. Previously the link went to a plain old "this is the ceph-storage Slack" page that did not direct the reader to sign up. …

doc/start: add Slack invite link

---

doc/architecture.rst

s/client/clients/ where necessary, and add a link to the glossary.
(cherry picked from commit ae08855cf870173dce2a47a28f3bbb22e7ae0ca2) …

squid: doc/architecture: correct typo

---

doc/architecture.rst

s/client/clients/ where necessary, and add a link to the glossary.
(cherry picked from commit ae08855cf870173dce2a47a28f3bbb22e7ae0ca2) …

quincy: doc/architecture: correct typo

---

src/crimson/os/seastore/object_data_handler.cc
src/crimson/os/seastore/transaction_manager.h
src/test/crimson/seastore/test_object_data_handler.cc

https://github.com/ceph/ceph/pull/54326 …

crimson/os/seastore: cleanup and use LBAMapping::is_stable()

---

src/crimson/os/seastore/collection_manager/collection_flat_node.h

Fixes: https://tracker.ceph.com/issues/64728 …

crimson/os/seastore/collection_manager: allow empty-delta-buffer collection nodes

---

doc/_static/js/pgcalc.js
doc/rados/operations/index.rst
doc/rados/operations/pgcalc/index.rst
doc/rados/operations/placement-groups.rst

Restore the PGcalc tool to the documentation suite.
- …

doc/rados: restore PGcalc tool

---

src/test/cls_rbd/test_cls_rbd.cc

test/cls_rbd/test_cls_rbd: change to check for 4KB-aligned sparse read

---

doc/_static/js/pgcalc.js
doc/rados/operations/index.rst
doc/rados/operations/pgcalc/index.rst
doc/rados/operations/placement-groups.rst

Restore the PGcalc tool to the documentation suite.
Co-authored-by: Josh Durgin <jdurgin@redhat.com>
(cherry picked from commit eaaf72253123de1a66f163f651046817faa97a1a) …

squid: doc/rados: restore PGcalc tool

---

doc/_static/js/pgcalc.js
doc/rados/operations/index.rst
doc/rados/operations/pgcalc/index.rst
doc/rados/operations/placement-groups.rst

Restore the PGcalc tool to the documentation suite.
Co-authored-by: Josh Durgin <jdurgin@redhat.com>
(cherry picked from commit eaaf72253123de1a66f163f651046817faa97a1a) …

reef: doc/rados: restore PGcalc tool

---

doc/_static/js/pgcalc.js
doc/rados/operations/index.rst
doc/rados/operations/pgcalc/index.rst
doc/rados/operations/placement-groups.rst

Restore the PGcalc tool to the documentation suite.
Co-authored-by: Josh Durgin <jdurgin@redhat.com>
(cherry picked from commit eaaf72253123de1a66f163f651046817faa97a1a) …

quincy: doc/rados: restore PGcalc tool

---

qa/crontab/teuthology-cronjobs

qa: fix syntax bug with invalid 60 minute specification

---

doc/start/get-involved.rst

Add a link to the ceph-storage Slack invitation page. Previously the link went to a plain old "this is the ceph-storage Slack" page that did not direct the reader to sign up.
(cherry picked from commit dee319e61204b2ee9ac13562c2c7075ef0f2ea4b) …

quincy: doc/start: add Slack invite link

---

doc/start/get-involved.rst

Add a link to the ceph-storage Slack invitation page. Previously the link went to a plain old "this is the ceph-storage Slack" page that did not direct the reader to sign up.
(cherry picked from commit dee319e61204b2ee9ac13562c2c7075ef0f2ea4b) …

reef: doc/start: add Slack invite link

---

doc/start/get-involved.rst

Add a link to the ceph-storage Slack invitation page. Previously the link went to a plain old "this is the ceph-storage Slack" page that did not direct the reader to sign up.
(cherry picked from commit dee319e61204b2ee9ac13562c2c7075ef0f2ea4b) …

squid: doc/start: add Slack invite link

---

doc/dev/crimson/index.rst
doc/glossary.rst

Add a "Crimson" entry to the glossary. …

doc/glossary: add "Crimson" entry

---

doc/dev/crimson/index.rst
doc/glossary.rst

Add a "Crimson" entry to the glossary.
(cherry picked from commit b31e061cc087b31a7e9e841dd21e7403a2197378) …

squid: doc/glossary: add "Crimson" entry

---

doc/dev/crimson/index.rst
doc/glossary.rst

Add a "Crimson" entry to the glossary.
(cherry picked from commit b31e061cc087b31a7e9e841dd21e7403a2197378) …

reef: doc/glossary: add "Crimson" entry

---

doc/dev/crimson/index.rst
doc/glossary.rst

Add a "Crimson" entry to the glossary.
(cherry picked from commit b31e061cc087b31a7e9e841dd21e7403a2197378) …

quincy: doc/glossary: add "Crimson" entry

---

doc/glossary.rst

Improve the glossary entry for "Crimson" in accordance with Anthony D'Atri's suggestions here:
https://github.com/ceph/ceph/pull/56068#discussion_r1518580402 …

doc/glossary: improve "Crimson" entry

---

doc/cephadm/host-management.rst

doc/cephadm: improve host-management.rst
Wordsmithing and formatting.
- Component …

doc/cephadm: improve host-management.rst

---

doc/cephadm/host-management.rst

(cherry picked from commit 9fb51bb537e8bd9ea60633091acfc48a58262c3b) …

squid: doc/cephadm: improve host-management.rst 

---

doc/cephadm/host-management.rst

(cherry picked from commit 9fb51bb537e8bd9ea60633091acfc48a58262c3b) …

reef: doc/cephadm: improve host-management.rst

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/models/cd-table-column.ts

Added isInvisible property to CdColumnTable interface to hide column from 'toggle columns' drop down checkboxes.
Fixes: https://tracker.ceph.com/issues/64813 …

mgr/dashboard: fix snap schedule list toggle cols

---

src/pybind/mgr/dashboard/requirements.txt

mgr/dashboard: debugging make check failure

---

doc/releases/index.rst
doc/releases/reef.rst
doc/releases/releases.yml

doc: reef 18.2.2 release notes

---

doc/cephadm/adoption.rst
doc/cephadm/client-setup.rst
doc/cephadm/compatibility.rst
doc/cephadm/install.rst
doc/cephadm/operations.rst
doc/cephadm/troubleshooting.rst
doc/cephadm/upgrade.rst

doc/cephadm: Improve multiple files

---

src/rgw/rgw_s3select.cc

backport tracker: https://tracker.ceph.com/issues/64694
backport from: https://github.com/ceph/ceph/pull/55891 
parent tracker: https://tracker.ceph.com/issues/63245

squid: rgw/s3select: Wip 64694 squid

---

doc/cephadm/adoption.rst
doc/cephadm/client-setup.rst
doc/cephadm/compatibility.rst
doc/cephadm/install.rst
doc/cephadm/operations.rst
doc/cephadm/troubleshooting.rst
doc/cephadm/upgrade.rst

(cherry picked from commit 800dd29e60fcd2bcd27db56d3fe45c58ddf10c8a) …

squid: doc/cephadm: Improve multiple files

---

doc/cephadm/adoption.rst
doc/cephadm/client-setup.rst
doc/cephadm/compatibility.rst
doc/cephadm/install.rst
doc/cephadm/operations.rst
doc/cephadm/troubleshooting.rst
doc/cephadm/upgrade.rst

(cherry picked from commit 800dd29e60fcd2bcd27db56d3fe45c58ddf10c8a) …

reef: doc/cephadm: Improve multiple files

---

doc/radosgw/adminops.rst
src/rgw/driver/rados/rgw_rest_user.cc
src/rgw/driver/rados/rgw_user.cc
src/rgw/driver/rados/rgw_user.h
src/rgw/rgw_acl_types.h
src/rgw/rgw_admin.cc
src/rgw/rgw_common.cc
src/rgw/services/svc_user_rados.cc
src/test/cli/radosgw-admin/help.t

backport tracker: https://tracker.ceph.com/issues/64493
---
backport of https://github.com/ceph/ceph/pull/55508
parent tracker: https://tracker.ceph.com/issues/59186

squid: rgw/user: add 'active' flag to RGWAccessKey

---

src/cephadm/cephadm.py

Backport of https://github.com/ceph/ceph/pull/55531
Conflicts:
src/cephadm/cephadmlib/daemons/nvmeof.py
src/cephadm/cephadm.py …

reef: cephadm: Add mount for nvmeof log location

---

qa/suites/orch/cephadm/workunits/task/test_extra_daemon_features.yaml
src/python-common/ceph/deployment/service_spec.py

Backport of https://github.com/ceph/ceph/pull/52122
- …

reef: qa/cephadm: testing for extra daemon/container features

---

src/pybind/mgr/orchestrator/module.py

backport tracker: https://tracker.ceph.com/issues/63985
---
backport of https://github.com/ceph/ceph/pull/54978
parent tracker: https://tracker.ceph.com/issues/63864

reef: orchestrator: Add summary line to orch device ls output

---

src/crimson/os/seastore/btree/fixed_kv_btree.h
src/crimson/os/seastore/btree/fixed_kv_node.h
src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/cache.h
src/crimson/os/seastore/cached_extent.h
src/crimson/os/seastore/root_block.cc
src/crimson/os/seastore/transaction_manager.h
src/test/crimson/seastore/test_seastore.cc
src/test/crimson/seastore/test_seastore_cache.cc
src/test/crimson/seastore/test_transaction_manager.cc

crimson/os/seastore: cleanups around lba parent-child pointer

---

doc/cephadm/adoption.rst
doc/cephadm/client-setup.rst
doc/cephadm/compatibility.rst
doc/cephadm/install.rst
doc/cephadm/operations.rst
doc/cephadm/troubleshooting.rst
doc/cephadm/upgrade.rst

(cherry picked from commit 800dd29e60fcd2bcd27db56d3fe45c58ddf10c8a) …

quincy: doc/cephadm: Improve multiple files

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.ts

Fixes: https://tracker.ceph.com/issues/64831 …

mgr/dashboard: fix snap schedule time format

---

qa/suites/orch/cephadm/workunits/task/test_cephadm_timeout.yaml
qa/workunits/cephadm/test_cephadm_timeout.py
src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/ssh.py

Backport of https://github.com/ceph/ceph/pull/51963
- …

quincy: mgr/cephadm: fixups for asyncio based timeout

---

src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/seastore.h
src/test/crimson/seastore/test_seastore.cc

crimson/os/seastore: handle OP_COLL_MOVE_RENAME

---

src/pybind/mgr/volumes/fs/volume.py

Introduced-by: 079f722c37ef6cc8bd3cc26c49ae119dd83431f9
- …

mgr/vol: don't import IndexException since it's unused

---

src/pybind/mgr/dashboard/frontend/cypress/e2e/visualTests/dashboard.vrt-spec.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/visualTests/login.vrt-spec.ts

Temporarily disabling this so the CI could turn green. Meanwhile I'll research for a proper way to handle the applitools e2es which I'll track on https://tracker.ceph.com/issues/64783 …

mgr/dashboard: disable applitools e2e

---

src/librados/snap_set_diff.cc
src/librbd/io/ObjectRequest.cc
src/test/librbd/io/test_mock_ObjectRequest.cc
src/test/librbd/test_librbd.cc

librbd: account for discards that truncate in ObjectListSnapsRequest

---

qa/tasks/cephfs/test_mirroring.py
src/tools/cephfs_mirror/PeerReplayer.cc

s/current_sycning_snap/current_syncing_snap …

cephfs_mirror, qa: fix typo in current_syncing_snap status

---

qa/tasks/cephfs/test_mirroring.py

Fixes: https://tracker.ceph.com/issues/64486 …

qa: enhance labeled perf counters test for cephfs-mirror

---

src/mds/CDentry.cc

Fixes: https://tracker.ceph.com/issues/64058 …

mds: ensure snapclient is synced before corruption check

---

src/common/options/mds.yaml.in

This config can result in a single client holding up mds to service other clients since once a client is deferred from eviction due to laggy OSD(s), a new clients cap acquire request can be possibly blocked until the other laggy client resumes operation, i.e., when the laggy OSD is considered non-laggy anymore.
Disable the config by default till the issue is fixed.
Fixes: http://tracker.ceph.com/issues/64685 …

mds: disable `defer_client_eviction_on_laggy_osds' by default

---

src/pybind/mgr/dashboard/controllers/cephfs.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-auth-modal/cephfs-auth-modal.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-auth-modal/cephfs-auth-modal.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-auth-modal/cephfs-auth-modal.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-tabs/cephfs-tabs.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
src/pybind/mgr/dashboard/openapi.yaml

[screen-capture (28).webm](https://github.com/ceph/ceph/assets/106810838/e5ab134e-ec8f-4683-b76f-4e2600967028)
Fixes: https://tracker.ceph.com/issues/64660 …

mgr/dashboard: ceph authenticate user from fs

---

doc/rbd/rbd-encryption.rst

Add a command that explains how to map a formatted clone when the parent image and the formatted clone have different encryption types. …

doc/rbd: add clone mapping command

---

qa/tasks/cephfs/test_admin.py

Fixes: https://tracker.ceph.com/issues/64641 …

qa: Add multifs root_squash testcase

---

qa/tasks/cephfs/test_fstop.py
src/tools/cephfs/top/cephfs-top

Fixes: https://tracker.ceph.com/issues/63553 …

reef: cephfs-top: include the missing fields in --dump output

---

src/mds/Capability.h
src/mds/OpenFileTable.h
src/messages/MClientCaps.h
src/messages/MClientSession.h
src/messages/MMDSScrub.h
src/messages/MMDSScrubStats.h

backport tracker: https://tracker.ceph.com/issues/64045
---
backport of https://github.com/ceph/ceph/pull/54519
parent tracker: https://tracker.ceph.com/issues/63552 …

reef: mds: use explicitly sized types for network and disk encoding

---

src/mds/Locker.cc

backport tracker: https://tracker.ceph.com/issues/64075
---
backport of https://github.com/ceph/ceph/pull/53238
parent tracker: https://tracker.ceph.com/issues/62580 …

reef: mds: just wait the client flushes the snap and dirty buffer

---

qa/tasks/cephfs/test_misc.py

backport tracker: https://tracker.ceph.com/issues/64222
---
backport of https://github.com/ceph/ceph/pull/54683
parent tracker: https://tracker.ceph.com/issues/63587 …

reef: qa/tasks/cephfs/test_misc: switch duration to timeout

---

doc/dev/developer_guide/testing_integration_tests/tests-integration-testing-teuthology-intro.rst
qa/crontab/teuthology-cronjobs

qa/crontab: use historically normal priorities for nightlies

---

doc/glossary.rst
doc/rados/api/librados-intro.rst
doc/rados/api/python.rst

Add a "librados" entry to the glossary. …

doc/glossary: add "librados" entry

---

doc/glossary.rst
doc/rados/api/librados-intro.rst
doc/rados/api/python.rst

Add a "librados" entry to the glossary.
(cherry picked from commit 2a93a8e837a42559f8a81c6fd9274b24f4fdf7f6) …

quincy: doc/glossary: add "librados" entry

---

doc/glossary.rst
doc/rados/api/librados-intro.rst
doc/rados/api/python.rst

Add a "librados" entry to the glossary.
(cherry picked from commit 2a93a8e837a42559f8a81c6fd9274b24f4fdf7f6) …

squid: doc/glossary: add "librados" entry

---

doc/glossary.rst
doc/rados/api/librados-intro.rst
doc/rados/api/python.rst

Add a "librados" entry to the glossary.
(cherry picked from commit 2a93a8e837a42559f8a81c6fd9274b24f4fdf7f6) …

reef: doc/glossary: add "librados" entry

---

src/librados/snap_set_diff.cc
src/librbd/io/ObjectRequest.cc
src/test/librbd/io/test_mock_ObjectRequest.cc
src/test/librbd/test_librbd.cc

backport tracker: https://tracker.ceph.com/issues/64914
---
backport of https://github.com/ceph/ceph/pull/56064
parent tracker: https://tracker.ceph.com/issues/63770

squid: librbd: account for discards that truncate in ObjectListSnapsRequest

---

src/test/crimson/seastore/test_block.h

non-fully-loaded TestBlocks
Before this commit, all TestBlocks are fully-loaded whether they do have data or not. …

test/crimson/sesastore/test_block: add constructor to construct

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-mount-details/cephfs-mount-details.component.ts

Fixes: https://tracker.ceph.com/issues/64933 …

mgr/dashboard: fixed nfs attach command

---

doc/rbd/rados-rbd-cmds.rst

Replace "{image-}" with "{image-id}" in the "rbd trash rm" command description.
- …

docs/rbd: fix typos in the rbd basic cmds documentation

---

src/ceph-node-proxy/ceph_node_proxy/redfish_client.py

After some tests, it turns out that depending on the hardware, the header 'Location' which is returned by the server after logged can be different. I could notice the following:
either:
Location: scheme://address:port/redfish/v1/SessionService/Session
or
Location: /redfish/v1/SessionService/Session
a previous tracker [1] was opened because I thought only the first one existed, which is wrong.
[1] https://tracker.ceph.com/issues/64894

node-proxy: support more Location value formats

---

doc/man/8/rbd.rst

Fixes typos and grammar for some commands. Adds
additional details for some commandds. …

doc/rbd: minor changes to the rbd man page

---

doc/man/8/rbd.rst

Fixes typos and grammar for some commands. Adds
additional details for some commandds.
(cherry picked from commit 5dcff6a4b8d835fc55e454af977dc5ebad99d37f) …

squid: doc/rbd: minor changes to the rbd man page

---

doc/man/8/rbd.rst

Fixes typos and grammar for some commands. Adds
additional details for some commandds.
(cherry picked from commit 5dcff6a4b8d835fc55e454af977dc5ebad99d37f) …

reef: doc/rbd: minor changes to the rbd man page

---

doc/man/8/rbd.rst

Fixes typos and grammar for some commands. Adds
additional details for some commandds.
(cherry picked from commit 5dcff6a4b8d835fc55e454af977dc5ebad99d37f) …

quincy: doc/rbd: minor changes to the rbd man page

---

doc/rados/configuration/common.rst

Clarify some overwritten paragraphs in
doc/rados/configuration/common.rst. Cf.
https://github.com/ceph/ceph/pull/50795/files#r1153897231. …

doc/rados: update common.rst

---

qa/suites/rados/verify/validater/valgrind.yaml

Fixes: https://tracker.ceph.com/issues/62992 …

qa/suites/rados/verify/validater/valgrind: increase op thread timeout

---

src/os/bluestore/bluefs_types.cc

+ simplify op_bl size estimation
+ fix seq size estimation
+ skip useless calculation of crc32c …

os/bluestore: Mute warnings

---

src/pybind/mgr/dashboard/tools.py

Allow DELETE method api request, X-TOTAL-COUNT header in CORS config in dashboard
Fixes: https://tracker.ceph.com/issues/64913 …

mgr/dashboard: Allow DELETE method api request, X-TOTAL-COUNT header in CORS config in dashboard
