ceph/ceph

- doc/cephadm/services/osd.rst
Backport of https://github.com/ceph/ceph/pull/56177
- …
> squid: doc: cephadm/services/osd: fix typo

- doc/cephadm/services/osd.rst
Backport of https://github.com/ceph/ceph/pull/56177
- …
> reef: doc: cephadm/services/osd: fix typo

- doc/cephadm/services/monitoring.rst
(cherry picked from commit ead944be18781ddccd52af5aa5cff414d15bb39d) …
> reef: doc/cephadm/services: Improve monitoring.rst

- src/test/encoding/check-generated.sh
Fixes: https://tracker.ceph.com/issues/64210 …
> test/encoding/check-generated: parallel testing by type

- src/pybind/mgr/dashboard/controllers/cephfs.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-auth-modal/cephfs-auth-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-auth-modal/cephfs-auth-modal.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-auth-modal/cephfs-auth-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-tabs/cephfs-tabs.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
conflict in: `shared/constants/app.constants.ts`
backport tracker: https://tracker.ceph.com/issues/64930
---
backport of https://github.com/ceph/ceph/pull/55870
parent tracker: https://tracker.ceph.com/issues/64660
> reef: mgr/dashboard: ceph authenticate user from fs

- src/pybind/mgr/dashboard/controllers/cephfs.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-auth-modal/cephfs-auth-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-auth-modal/cephfs-auth-modal.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-auth-modal/cephfs-auth-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-tabs/cephfs-tabs.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
conflict in: `shared/constants/app.constants.ts`
backport tracker: https://tracker.ceph.com/issues/64929
---
backport of https://github.com/ceph/ceph/pull/55870
parent tracker: https://tracker.ceph.com/issues/64660
> squid: mgr/dashboard: ceph authenticate user from fs

- doc/cephfs/cephfs-io-path.rst
> doc/cephfs: fix architecture link to correct relative path

- src/rgw/rgw_rest_swift.cc
Fixes: https://tracker.ceph.com/issues/63684
---
backport of https://github.com/ceph/ceph/pull/46719
parent tracker: https://tracker.ceph.com/issues/56029
When a bucket list is retargeted to an object get, then the object may not yet have it's bucket set.  Ensure the bucket is set on the object. …
> reef: RGW - Swift retarget needs bucket set on object

- src/mds/MDSRank.cc
Fixes: https://tracker.ceph.com/issues/64744 …
> squid: mds: fix `dump dir` indicate dir is not cached

- src/client/Client.cc
- src/client/Client.h
- src/test/client/nonblocking.cc
Backport of https://github.com/ceph/ceph/pull/55457
Backport tracker: https://tracker.ceph.com/issues/64741
Parent tracker: https://tracker.ceph.com/issues/64313 …
> squid: client: do not proceed with I/O if filehandle is invalid

- src/mds/Locker.cc
backport tracker: https://tracker.ceph.com/issues/64585
---
backport of https://github.com/ceph/ceph/pull/54687
parent tracker: https://tracker.ceph.com/issues/54833 …
> squid: mds: allow lock state to be LOCK_MIX_SYNC in replica for filelock

- qa/tasks/cephfs/test_mirroring.py
Implements checks for labeled perf counters in the appropriate tests.
This patch verifies snaps_synced, snaps_renamed, snaps_deleted and sync_failures metrics are
updated correctly based on the tests.
Fixes: https://tracker.ceph.com/issues/64486
(cherry picked from commit 7b7e5d4221389ce077780450d78a4a1e6a3d0a43) …
> squid: qa: enhance labeled perf counters test for cephfs-mirror

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
Fixes: https://tracker.ceph.com/issues/64911 …
> mgr/dashboard: fix empty tags 

- qa/suites/rados/singleton/all/mon-config-keys.yaml
Applies to the mon-config-keys.yaml file.
Fixes: https://tracker.ceph.com/issues/64725 …
> qa/suites/rados/singleton: add POOL_APP_NOT_ENABLED to ignorelist

- doc/rados/configuration/common.rst
Clarify some overwritten paragraphs in
doc/rados/configuration/common.rst. Cf.
https://github.com/ceph/ceph/pull/50795/files#r1153897231.
Reviewed-by: Anthony D'Atri <anthony.datri@gmail.com>
(cherry picked from commit 233b670704d15c3a69b8d91885b60f3fb101ec58) …
> squid: doc/rados: update common.rst

- doc/rados/configuration/common.rst
Clarify some overwritten paragraphs in
doc/rados/configuration/common.rst. Cf.
https://github.com/ceph/ceph/pull/50795/files#r1153897231.
Reviewed-by: Anthony D'Atri <anthony.datri@gmail.com>
(cherry picked from commit 233b670704d15c3a69b8d91885b60f3fb101ec58) …
> reef: doc/rados: update common.rst

- doc/rados/configuration/common.rst
Clarify some overwritten paragraphs in
doc/rados/configuration/common.rst. Cf.
https://github.com/ceph/ceph/pull/50795/files#r1153897231.
Reviewed-by: Anthony D'Atri <anthony.datri@gmail.com>
(cherry picked from commit 233b670704d15c3a69b8d91885b60f3fb101ec58) …
> quincy: doc/rados: update common.rst

- doc/cephfs/cephfs-io-path.rst
Signed-off-by: molpako <35787116+molpako@users.noreply.github.com>
(cherry picked from commit ceeb1ca4b38dc307e493b04a59d5d07fed23971f) …
> squid: doc/cephfs: fix architecture link to correct relative path

- doc/cephfs/cephfs-io-path.rst
Signed-off-by: molpako <35787116+molpako@users.noreply.github.com>
(cherry picked from commit ceeb1ca4b38dc307e493b04a59d5d07fed23971f) …
> reef: doc/cephfs: fix architecture link to correct relative path

- doc/cephfs/cephfs-io-path.rst
Signed-off-by: molpako <35787116+molpako@users.noreply.github.com>
(cherry picked from commit ceeb1ca4b38dc307e493b04a59d5d07fed23971f) …
> quincy: doc/cephfs: fix architecture link to correct relative path

- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/retention-frequency.enum.ts
Fix snap schedule list monthly retention frequency display
Fixes: https://tracker.ceph.com/issues/64982
- Tracker …
> mgr/dashboard: fix M retention frequency display

- src/common/SubProcess.cc
- src/common/fork_function.h
Fix rook/rook#10110, which occurs when _SC_OPEN_MAX/RLIMIT_NOFILE is set to very large values (2^30), leaving fork_function pegging a core busylooping.
The glibc wrappers closefrom(3)/close_range(3) are not available before glibc 2.34, so we invoke the syscall directly. When glibc 2.34 is old enough to be a reasonable hard minimum dependency, we should switch to using closefrom.
If we're not running on (recent enough) Linux, we fall back to the existing approach.
<details>
- …
> common: use close_range on Linux

- src/librados/IoCtxImpl.cc
librados::OPERATION_FULL_FORCE should be translated to CEPH_OSD_FLAG_FULL_FORCE before calling IoCtxImpl::remove(). …
> librados: use CEPH_OSD_FLAG_FULL_FORCE for IoCtxImpl::remove

- src/pybind/mgr/dashboard/controllers/cephfs.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-snapshot-schedule.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
Fixes: https://tracker.ceph.com/issues/64524 …
> mgr/dashboard: fix retention add for subvolume

- src/crimson/os/seastore/btree/btree_range_pin.cc
- src/crimson/os/seastore/btree/fixed_kv_btree.h
- src/crimson/os/seastore/btree/fixed_kv_node.cc
- src/crimson/os/seastore/btree/fixed_kv_node.h
- src/crimson/os/seastore/cache.h
- src/crimson/os/seastore/cached_extent.h
Fixes: https://tracker.ceph.com/issues/64957 …
> crimson/os/seastore/btree: check for reserved ptrs when determining children stability

- doc/install/get-packages.rst
fix typos in openEuler-installation doc as @anthonyeleven mentioned in #54156 
- …
> doc/install: fix typos in openEuler-installation doc

- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/dashboard-help/dashboard-help.component.html
Fixes: https://tracker.ceph.com/issues/62350 …
> mgr/dashboard: open api swagger in new tab

- qa/suites/fs/nfs/overrides/ignorelist_health.yaml
Fixes: https://tracker.ceph.com/issues/64987 …
> qa/suites/fs/nfs: use standard health ignorelist

- qa/cephfs/overrides/ignorelist_health.yaml
Fixes: https://tracker.ceph.com/issues/64986 …
> qa/cephfs: ignorelist clog of MDS_UP_LESS_THAN_MAX

- qa/suites/fs/functional/tasks/snap-schedule.yaml
- qa/suites/fs/functional/tasks/snap_schedule_snapdir.yaml
- qa/suites/netsplit/ceph.yaml
Fixes: https://tracker.ceph.com/issues/64947 …
> qa: change log-whitelist to log-ignorelist

- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/buckets.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
Fixes https://tracker.ceph.com/issues/64708
- adds info text explaining about placement targets
- adds fieldset to security, policy and tags for a11y
- removes placement target as required field
- when no placement target provided, request omits placement_target
field
- hides placement atrgets ection for edit form since its not possible to
edit after creation
- updates rgw-bucket.service.spec.ts unit test
- minor cleanups related to unncesseary css present, and changes in help
text for object locking
[Screencast from 2024-03-20 17-36-38.webm](https://github.com/ceph/ceph/assets/25664409/df6213eb-68c0-46a1-a7ec-e181357ec87f)
<details> …
> mgr/dashboard: Mark placement targets as non-required

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolumegroup-form/cephfs-subvolumegroup-form.component.ts
Removed the 'infinite' string which was set when no value was provided
Fixes: https://tracker.ceph.com/issues/65049 …
> mgr/dashboard: fix subvolume group edit size

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.ts
Show full subvolume path when adding snap schedule
Fixes: https://tracker.ceph.com/issues/65000 …
> Snapshot schedule show subvolume path

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
[screen-capture (29).webm](https://github.com/ceph/ceph/assets/106810838/5d01063d-0cef-4cff-96fc-1a758bd2dfc9)
Fixes: https://tracker.ceph.com/issues/64855 …
> mgr/dashboard: add a notification when deleting rgw bucket

- qa/cephfs/conf/mon.yaml
- qa/cephfs/overrides/ignorelist_wrongly_marked_down.yaml
- qa/tasks/mgr/dashboard/test_health.py
- src/common/options/mon.yaml.in
- src/mon/HealthMonitor.cc
- src/mon/Monitor.cc
- src/mon/Monitor.h
Fixes: https://tracker.ceph.com/issues/64968 …
> mon: do not log MON_DOWN if monitor uptime is less than threshold

- src/pybind/mgr/dashboard/frontend/cypress/e2e/visualTests/dashboard.vrt-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/visualTests/login.vrt-spec.ts
Temporarily disabling this so the CI could turn green. Meanwhile I'll research for a proper way to handle the applitools e2es which I'll track on https://tracker.ceph.com/issues/64783
(cherry picked from commit 09c50063a3763fc5d29f604a9daeb844252a31da) …
> reef: mgr/dashboard: disable applitools e2e

- src/pybind/mgr/dashboard/frontend/cypress/e2e/visualTests/dashboard.vrt-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/visualTests/login.vrt-spec.ts
Temporarily disabling this so the CI could turn green. Meanwhile I'll research for a proper way to handle the applitools e2es which I'll track on https://tracker.ceph.com/issues/64783
(cherry picked from commit 09c50063a3763fc5d29f604a9daeb844252a31da) …
> squid: mgr/dashboard: disable applitools e2e

- qa/cephfs/conf/mgr.yaml
Fixes: https://tracker.ceph.com/issues/64985 …
> qa/cephfs: add mgr debugging

- src/crimson/osd/osd_operations/scrub_events.cc
seastar::repeat may or may not move the passed action after the first invocation, so we can't actually rely on references to variables captured by value being stable.  Instead, allocate with std::make_unique and move into a finally lambda.
Fixes: https://tracker.ceph.com/issues/64996
https://pulpito.ceph.com/sjust-2024-03-21_02:35:36-crimson-rados-wip-sjust-crimson-testing-2024-03-20-distro-default-smithi/
Failures unrelated, caused by existing known bugs.
<details>
- `jenkins …
> crimson/.../scrub_events: fix progress lifetime in deep_scan_object

- doc/start/intro.rst
Remove a prolix "on behalf of" and streamline some sentences explaining the benefits of MDS. …
> doc/start: improve MDS explanation

- doc/rados/operations/monitoring.rst
- doc/start/intro.rst
Link to the "ceph mon stat" command when "Intro to Ceph" document first mentions Monitor Maps.
(cherry picked from commit 5d300db825316db25706111bbe577d41d41ab4b3) …
> squid: doc/start: link to mon map command

- doc/rados/operations/monitoring.rst
- doc/start/intro.rst
Link to the "ceph mon stat" command when "Intro to Ceph" document first mentions Monitor Maps.
(cherry picked from commit 5d300db825316db25706111bbe577d41d41ab4b3) …
> reef: doc/start: link to mon map command

- doc/rados/operations/monitoring.rst
- doc/start/intro.rst
Link to the "ceph mon stat" command when "Intro to Ceph" document first mentions Monitor Maps.
(cherry picked from commit 5d300db825316db25706111bbe577d41d41ab4b3) …
> quincy: doc/start: link to mon map command

- doc/start/intro.rst
Remove a prolix "on behalf of" and streamline some sentences explaining the benefits of MDS.
(cherry picked from commit 2da1812a1de7e32395cb95c2e0ebeea689c1b810) …
> squid: doc/start: improve MDS explanation

- doc/start/intro.rst
Remove a prolix "on behalf of" and streamline some sentences explaining the benefits of MDS.
(cherry picked from commit 2da1812a1de7e32395cb95c2e0ebeea689c1b810) …
> reef: doc/start: improve MDS explanation

- doc/start/intro.rst
Remove a prolix "on behalf of" and streamline some sentences explaining the benefits of MDS.
(cherry picked from commit 2da1812a1de7e32395cb95c2e0ebeea689c1b810) …
> quincy: doc/start: improve MDS explanation

- doc/rados/operations/erasure-code-profile.rst
- src/mon/OSDMonitor.cc
This is per https://tracker.ceph.com/issues/64333#note-17 describing driving factors of a catastrophic cluster failure. …
> mon, doc: overriding ec profile requires --yes-i-really-mean-it

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.ts
backport tracker: https://tracker.ceph.com/issues/65077
---
backport of https://github.com/ceph/ceph/pull/56335
parent tracker: https://tracker.ceph.com/issues/65000
> squid: mgr/dashboard: Snapshot schedule show subvolume path

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.ts
backport tracker: https://tracker.ceph.com/issues/65078
---
backport of https://github.com/ceph/ceph/pull/56335
parent tracker: https://tracker.ceph.com/issues/65000
> reef: Snapshot schedule show subvolume path

- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/settings.service.ts
do a force refresh on the settings service so it picks up the new api url of grafana …
> mgr/dashboard: update grafana api url when switching cluster

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-daemon-list/service-daemon-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/usage-bar/usage-bar.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/usage-bar/usage-bar.component.ts
for multi-core cpu's the value can be more than 100% so it doesn't make sense to show warning/error when the usage is at or more than 100%. hence removing it
Fixes: https://tracker.ceph.com/issues/58838 …
> mgr/dashboard: rm warning/error threshold for cpu usage

- src/pybind/mgr/dashboard/controllers/__init__.py
- src/pybind/mgr/dashboard/controllers/_docs.py
- src/pybind/mgr/dashboard/controllers/_endpoint.py
- src/pybind/mgr/dashboard/controllers/_rest_controller.py
- src/pybind/mgr/dashboard/controllers/auth.py
- src/pybind/mgr/dashboard/controllers/docs.py
- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/model/nvmeof.py
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/requirements.txt
- src/pybind/mgr/dashboard/services/exception.py
- src/pybind/mgr/dashboard/services/nvmeof_client.py
- src/pybind/mgr/dashboard/services/proto/gateway.proto
- src/pybind/mgr/dashboard/services/proto/gateway_pb2.py
[REST API Design doc.](https://docs.google.com/document/d/13zjDcdAzrWBMhODVkvAOb1htJ5uJBsWLbo3oXOaYRio/edit)
* Update NVMe-oF gRPC Proto to 1.0.0
* Error handling,
* Missing PATCH for certain namespace ops (resize, set QoS, set balance
groups),
* Stop bypassing gRPC payloads and validate those in the back-end,
* Fix incorrect HTTP 1.1 semantics for some POST/DELETE and URIs.
* Catch errors/exceptions.
* Clean-up EndpointDoc Params
* Run Black linter.
* Remove most of NVMeoFClient glue code between gRPC and controller.
* Fix namespace delete endpoint by exposing trsvcid
* nvmeof io_stats support
Fixes: https://tracker.ceph.com/issues/64890
- If you …
> mgr/dashboard: fix NVMeoF API

- qa/cephfs/overrides/pg_health.yaml
- qa/suites/fs/32bits/overrides/pg_health.yaml
- qa/suites/fs/fscrypt/overrides/pg_health.yaml
- qa/suites/fs/full/overrides/pg_health.yaml
- qa/suites/fs/functional/overrides/pg_health.yaml
- qa/suites/fs/libcephfs/overrides/pg_health.yaml
- qa/suites/fs/mirror-ha/overrides/pg_health.yaml
- qa/suites/fs/mirror/overrides/pg_health.yaml
- qa/suites/fs/mixed-clients/overrides/pg_health.yaml
- qa/suites/fs/multiclient/overrides/pg_health.yaml
- qa/suites/fs/multifs/overrides/pg_health.yaml
- qa/suites/fs/nfs/overrides/pg_health.yaml
- qa/suites/fs/permission/overrides/pg_health.yaml
- qa/suites/fs/shell/overrides/pg_health.yaml
- qa/suites/fs/snaps/overrides/pg_health.yaml
- qa/suites/fs/top/overrides/pg_health.yaml
- qa/suites/fs/traceless/overrides/pg_health.yaml
- qa/suites/fs/verify/overrides/pg_health.yaml
- qa/suites/fs/volumes/overrides/pg_health.yaml
- qa/suites/fs/workload/overrides/pg_health.yaml
> qa/cephfs: add probabilistic ignorelist for pg_health

- src/mds/MetricAggregator.cc
Small typo fix for MDS metrics …
> mds: fix typo in MetricAggregator

- src/pybind/mgr/dashboard/frontend/src/app/core/auth/auth.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/auth/user-form/user-form.component.html
[screen-capture (39).webm](https://github.com/ceph/ceph/assets/106810838/8814c73b-fb04-469c-ac4c-d29ad3f7f033)
Fixes: https://tracker.ceph.com/issues/65030 …
> mgr/dashboard: sanitize dashboard user creation

- src/osd/SnapMapper.cc
We should verify that the snap we are looking for matches the pool also.
Same as we are checking in OSDMonitor:
https://github.com/ceph/ceph/pull/28865/commits/0a48392ce066471233cc1e81e957b2999b9c411c
RCA: https://tracker.ceph.com/issues/64347#note-3
Fixes: https://tracker.ceph.com/issues/64347 …
> osd/SnapMapper: fix _lookup_purged_snap

- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.ts
By default now we have enabled support for both v3,v4 protocols for NFS exports
[Screencast from 2024-03-12 14-31-17.webm](https://github.com/ceph/ceph/assets/23611106/ed8761a7-5615-4e10-8cea-c34db2741633)
Fixes: https://tracker.ceph.com/issues/64812
Signed-off-by: Avan Thakkar <athakkar@redhat.com> …
> mgr/dashboard: add support for NFSv3 exports

- src/pybind/mgr/dashboard/frontend/src/app/core/auth/auth.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/auth/user-form/user-form.component.html
backport tracker: https://tracker.ceph.com/issues/65111
---
backport of https://github.com/ceph/ceph/pull/56357
parent tracker: https://tracker.ceph.com/issues/65030
> reef: mgr/dashboard: sanitize dashboard user creation

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.ts
- src/pybind/mgr/dashboard/openapi.yaml
[screen-capture (37).webm](https://github.com/ceph/ceph/assets/106810838/423a6a92-da37-4944-8cbf-704e83479852)
Fixes: https://tracker.ceph.com/issues/65074 …
> mgr/dashboard: add system users to rgw user form

- src/pybind/mgr/dashboard/module.py
The benefit is that this will take care of cherrypy reconfiguration
Fixes: https://tracker.ceph.com/issues/65104
- …
> mgr/dashboard: introduce cli commands to set cors urls

- doc/rados/operations/erasure-code-profile.rst
- src/mon/OSDMonitor.cc
This is per https://tracker.ceph.com/issues/64333#note-17 describing driving factors of a catastrophic cluster failure.
(cherry picked from commit 629ba7bd349d48cdaa6d094751e7cfce651ba2bc) …
> squid: mon, doc: overriding ec profile requires --yes-i-really-mean-it

- src/crimson/os/seastore/seastore.cc
> crimson/os/seastore: fix use after free error

- src/osd/OSD.cc
- src/osd/OSD.h
- src/osd/osd_types.h
Backport of https://github.com/ceph/ceph/pull/50326
- …
> quincy: osd: improve OSD robustness.

- qa/tasks/cephfs/test_nfs.py
- src/pybind/mgr/nfs/export.py
Backport tracker: https://tracker.ceph.com/issues/64220
Parent tracker: https://tracker.ceph.com/issues/62626
Backport of https://github.com/ceph/ceph/pull/53177 …
> reef: mgr/nfs: include pseudo in JSON output when nfs export apply -i fails

- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/buckets.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
Fixes https://tracker.ceph.com/issues/65110
- renamed Security to Encryption
- aligned security fieldset with rest of the form using `cd-help-text` and aligning it with object locking in UX
- aligned security fieldset top use `cd-help-text`
- changed help text of Tags
[Screencast from 2024-03-25 14-14-23.webm](https://github.com/ceph/ceph/assets/25664409/4bb1d39f-6805-4848-a541-1964ed1fb1c1)
<details> …
> mgr/dashboard:Update encryption and tags in bucket form

- doc/rados/operations/placement-groups.rst
The removed line was (incorrectly changed) output of the previous command.
Signed-off-by: Taha Jahangir <mtjahangir@gmail.com>
(cherry picked from commit 3cd39e3582ed830f86c55d2203ece72fa0f9426b) …
> squid: docs/rados: remove incorrect ceph command

- doc/rados/operations/placement-groups.rst
The removed line was (incorrectly changed) output of the previous command.
Signed-off-by: Taha Jahangir <mtjahangir@gmail.com>
(cherry picked from commit 3cd39e3582ed830f86c55d2203ece72fa0f9426b) …
> reef: docs/rados: remove incorrect ceph command

- doc/rados/operations/placement-groups.rst
The removed line was (incorrectly changed) output of the previous command.
Signed-off-by: Taha Jahangir <mtjahangir@gmail.com>
(cherry picked from commit 3cd39e3582ed830f86c55d2203ece72fa0f9426b) …
> quincy: docs/rados: remove incorrect ceph command

- src/cephadm/cephadmlib/daemons/nvmeof.py
Backport of https://github.com/ceph/ceph/pull/55531
- …
> squid: cephadm: Add mount for nvmeof log location

- src/cephadm/cephadmlib/agent.py
- src/cephadm/cephadmlib/container_daemon_form.py
- src/cephadm/cephadmlib/container_types.py
- src/cephadm/cephadmlib/daemons/ceph.py
- src/cephadm/cephadmlib/daemons/node_proxy.py
- src/cephadm/cephadmlib/firewalld.py
- src/cephadm/cephadmlib/sysctl.py
- src/cephadm/cephadmlib/systemd_unit.py
- src/cephadm/tox.ini
Backport of https://github.com/ceph/ceph/pull/56075
<details>
</details>
> squid: cephadm: enforce black formatting for cephadmlib

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.ts
the dot(.) character is allowed in full name
Fixes: https://tracker.ceph.com/issues/65146 …
> mgr/dashboard: fix rgw display name validation

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-snapshots-list/cephfs-subvolume-snapshots-list.component.ts
Fixes: https://tracker.ceph.com/issues/65145
https://github.com/ceph/ceph/assets/71764184/27202630-c07b-454c-9aa0-3300e6f68de0 …
> mgr/dashboard: fix clone unique validator for name validation

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-mount-details/cephfs-mount-details.component.ts
Fixes: https://tracker.ceph.com/issues/65173 …
> mgr/dashboard: s/active_mds/active_nfs in fs attach form

- src/os/bluestore/HybridAllocator.cc
> os/bluestore: remove unnecessary std::hex in dout

- src/mds/Locker.cc
backport tracker: https://tracker.ceph.com/issues/64586
---
backport of https://github.com/ceph/ceph/pull/54687
parent tracker: https://tracker.ceph.com/issues/54833 …
> quincy: mds: allow lock state to be LOCK_MIX_SYNC in replica for filelock

- qa/tasks/cephfs/test_quiesce.py
- src/mds/MDCache.cc
- src/mds/MDSDaemon.cc
> mds: do not dispatch aborted internal requests

- doc/dev/release-checklists.rst
To include note that release notes must be removed after forking the release branch. …
> doc: update release checklist

- doc/dev/release-checklists.rst
Updating the releases documentation existed already but that section should be moved to after dev freeze when the branch is forked.
Fixes: 7b5017913a9ecf27ca7281367a5472a9b9b043ec …
> doc: reconcile release checklist

- src/test/librados/io_cxx.cc
Just test more with a larger size to test the sparse-read to find some corner case bugs. …
> ceph_test_rados_api_io_pp: add multiple extents test for sparse-read

- src/pybind/mgr/dashboard/frontend/src/app/core/auth/auth.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/auth/user-form/user-form.component.html
backport tracker: https://tracker.ceph.com/issues/65197
---
backport of https://github.com/ceph/ceph/pull/56357
parent tracker: https://tracker.ceph.com/issues/65030
> quincy: mgr/dashboard: sanitize dashboard user creation

- doc/dev/osd_internals/manifest.rst
- doc/dev/osd_internals/snaps.rst
snapdir concept was removed in: https://github.com/ceph/ceph/pull/17579
(cherry picked from commit 6a7f2b0fda74aedb213067abe5c0a64b68fbbdc7) …
> quincy: doc/dev: osd_internals/snaps.rst: add clone_overlap doc

- doc/dev/osd_internals/manifest.rst
- doc/dev/osd_internals/snaps.rst
snapdir concept was removed in: https://github.com/ceph/ceph/pull/17579
(cherry picked from commit 6a7f2b0fda74aedb213067abe5c0a64b68fbbdc7) …
> reef: doc/dev: osd_internals/snaps.rst: add clone_overlap doc

- doc/dev/osd_internals/manifest.rst
- doc/dev/osd_internals/snaps.rst
snapdir concept was removed in: https://github.com/ceph/ceph/pull/17579
(cherry picked from commit 6a7f2b0fda74aedb213067abe5c0a64b68fbbdc7) …
> squid: doc/dev: osd_internals/snaps.rst: add clone_overlap doc

- doc/rados/operations/erasure-code-profile.rst
- src/mon/OSDMonitor.cc
This is per https://tracker.ceph.com/issues/64333#note-17 describing driving factors of a catastrophic cluster failure.
(cherry picked from commit 629ba7bd349d48cdaa6d094751e7cfce651ba2bc) …
> reef: mon, doc: overriding ec profile requires --yes-i-really-mean-it

- doc/dev/developer_guide/essentials.rst
Update the list of component leads in
doc/dev/developer_guide/essentials.rst.
- …
> doc/dev: update leads list

- doc/dev/developer_guide/essentials.rst
Update the list of component leads in
doc/dev/developer_guide/essentials.rst.
(cherry picked from commit 57e9427eac08b4057999f5afc44cf0fc77a3068f) …
> quincy: doc/dev: update leads list

- doc/dev/developer_guide/essentials.rst
Update the list of component leads in
doc/dev/developer_guide/essentials.rst.
(cherry picked from commit 57e9427eac08b4057999f5afc44cf0fc77a3068f) …
> reef: doc/dev: update leads list

- doc/dev/developer_guide/essentials.rst
Update the list of component leads in
doc/dev/developer_guide/essentials.rst.
(cherry picked from commit 57e9427eac08b4057999f5afc44cf0fc77a3068f) …
> squid: doc/dev: update leads list

- doc/dev/release-process.rst
> doc: added jammy to the supported distro list for quincy

- src/pybind/mgr/dashboard/controllers/auth.py
- src/pybind/mgr/dashboard/controllers/multi_cluster.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-form/multi-cluster-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-form/multi-cluster-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-list/multi-cluster-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-list/multi-cluster-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/multi-cluster.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/multi-cluster.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/auth.py
Provide an option to the user to select the ttl for the cluster that is going to be connected.
https://tracker.ceph.com/issues/65055
[Screencast from 2024-03-01 14-38-21.webm](https://github.com/ceph/ceph/assets/66050535/74828cf4-62f8-4df3-b211-fb5238032f6a)
Signed-off-by: Aashish Sharma …
> mgr/dashboard: Add multi cluster token ttl

- src/os/ObjectStore.h
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/os/bluestore/bluestore_tool.cc
- src/test/objectstore/store_test.cc
- src/test/objectstore/store_test_fixture.h
- src/tools/ceph_kvstore_tool.cc
- src/tools/ceph_objectstore_tool.cc
- src/tools/ceph_objectstore_tool.h
- src/tools/kvstore_tool.cc
- src/tools/kvstore_tool.h
> tools/ceph-objectstore-tool: tricks to tolerate disk errors for "pg export" command.

- doc/mgr/zabbix.rst
Include information from John Jasen about how to install Zabbix. …
> doc/mgr: update zabbix information

- src/pybind/mgr/dashboard/controllers/__init__.py
- src/pybind/mgr/dashboard/controllers/_docs.py
- src/pybind/mgr/dashboard/controllers/_endpoint.py
- src/pybind/mgr/dashboard/controllers/_rest_controller.py
- src/pybind/mgr/dashboard/controllers/auth.py
- src/pybind/mgr/dashboard/controllers/docs.py
- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/model/nvmeof.py
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/requirements.txt
- src/pybind/mgr/dashboard/services/exception.py
- src/pybind/mgr/dashboard/services/nvmeof_client.py
- src/pybind/mgr/dashboard/services/proto/gateway.proto
- src/pybind/mgr/dashboard/services/proto/gateway_pb2.py
- src/pybind/mgr/dashboard/services/proto/gateway_pb2_grpc.py
backport tracker: https://tracker.ceph.com/issues/64515, https://tracker.ceph.com/issues/64775, https://tracker.ceph.com/issues/65100
---
backport of https://github.com/ceph/ceph/pull/55535, #55804, https://github.com/ceph/ceph/pull/56164/
parent tracker: https://tracker.ceph.com/issues/64384, https://tracker.ceph.com/issues/64714, https://tracker.ceph.com/issues/64890
> squid: mgr/dashboard: nvmeof api batch fixes

- src/rgw/rgw_s3select.cc
- src/rgw/rgw_s3select_private.h
-- refactor of s3select response handler
-- adding continuation-response to parquet flow (with very big Parquet it causes a Timeout)
-- refactor of error response
https://bugzilla.redhat.com/show_bug.cgi?id=2242924
https://bugzilla.redhat.com/show_bug.cgi?id=2254582
https://github.com/ceph/s3select/pull/152
https://github.com/ceph/s3select/pull/153
<details>
- …
> rgw/s3select: s3select response handler refactor

- doc/mgr/zabbix.rst
Include information from John Jasen about how to install Zabbix.
(cherry picked from commit ebe7651dd85ae1f1570d8c34479b9bdd1249d83c) …
> squid: doc/mgr: update zabbix information

- doc/mgr/zabbix.rst
Include information from John Jasen about how to install Zabbix.
(cherry picked from commit ebe7651dd85ae1f1570d8c34479b9bdd1249d83c) …
> reef: doc/mgr: update zabbix information

- doc/mgr/zabbix.rst
Include information from John Jasen about how to install Zabbix.
(cherry picked from commit ebe7651dd85ae1f1570d8c34479b9bdd1249d83c) …
> quincy: doc/mgr: update zabbix information

- src/mds/Server.cc
>  mds: some request errors come from errno.h rather than fs_types.h

- src/mds/MDCache.cc
> mds: minor quiesce refactor changes

- src/msg/Dispatcher.h
See: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-five
- …
> msg: trivial destructor should be default

- doc/cephfs/fs-volumes.rst
Fixes: https://tracker.ceph.com/issues/65267
- Tracker …
> doc: fixing Configurables section in doc/cephfs/fs-volumes

- doc/dev/peering.rst
Refine the text in the first third of the entries in the section "Concepts" in doc/dev/peering.rst.
- Tracker …
> doc/dev: refine "Concepts"

- doc/dev/peering.rst
Refine the text in the first third of the entries in the section "Concepts" in doc/dev/peering.rst.
(cherry picked from commit 530b11be24c6e702d4d9b9227649db8ca34591e4) …
> reef: doc/dev: refine "Concepts"

- doc/dev/peering.rst
Refine the text in the first third of the entries in the section "Concepts" in doc/dev/peering.rst.
(cherry picked from commit 530b11be24c6e702d4d9b9227649db8ca34591e4) …
> quincy: doc/dev: refine "Concepts"

- qa/suites/rgw/notifications/overrides.yaml
- qa/suites/rgw/notifications/tasks/others/0-install.yaml
- qa/tasks/notification_tests.py
- src/rgw/CMakeLists.txt
- src/rgw/driver/rados/rgw_notify.cc
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
- src/rgw/driver/rados/rgw_sal_rados.cc
- src/rgw/driver/rados/rgw_sal_rados.h
- src/rgw/driver/rados/topic_migration.cc
- src/rgw/driver/rados/topic_migration.h
- src/rgw/rgw_obj_types.h
- src/test/rgw/bucket_notification/test_bn.py
RGW: Migrate topics to data path v2 …
> RGW: Migrate topics to data path v2

- src/osd/OSDMap.cc
- src/osd/OSDMap.h
backport tracker: https://tracker.ceph.com/issues/65198
---
backport of https://github.com/ceph/ceph/pull/55401
parent tracker: https://tracker.ceph.com/issues/63389 …
> squid: src/osd/OSDMap.cc: Fix encoder to produce same bytestream

- src/os/bluestore/BlueStore.cc
High fragmentation is one of the factors affecting performance decrease, add it to prometheus, it helps to us monitor fragmentation changes.
Signed-off-by: Yite Gu <yitegu0@gmail.com>
(cherry picked from commit 8fed26a185215d1a92c88544fd64f84a94bb106e) …
> reef: os/bluestore: add bluestore fragmentation micros to prometheus

- src/os/bluestore/BlueStore.cc
Parent tracker: https://tracker.ceph.com/issues/63858
Backports: https://github.com/ceph/ceph/pull/54990
Backport tracker: https://tracker.ceph.com/issues/64091 …
> reef: os/bluestore: fix free space update after bdev-expand in NCB mode

- src/test/objectstore/test_kv.cc
We need to use random content to estimate DB size. Otherwise, compression will cause DB to be unreasonably small.
Parent tracker: https://tracker.ceph.com/issues/63121
Backport tracker: https://tracker.ceph.com/issues/64928
Backports: https://github.com/ceph/ceph/pull/53909
(cherry picked from commit f987b4daa097a84ca35db4037de1985fc0acaf01) …
> reef: os/kv_test: Fix estimate functions

- doc/mgr/zabbix.rst
Credit John Jasen for the development of the procedures describing the installation of Zabbix 2. …
> doc/mgr: credit John Jasen for Zabbix 2

- src/mds/Locker.cc
backport tracker: https://tracker.ceph.com/issues/64584
---
backport of https://github.com/ceph/ceph/pull/54687
parent tracker: https://tracker.ceph.com/issues/54833 …
> reef: mds: allow lock state to be LOCK_MIX_SYNC in replica for filelock

- doc/dev/peering.rst
Refine the text in the first third of the entries in the section "Concepts" in doc/dev/peering.rst.
(cherry picked from commit 530b11be24c6e702d4d9b9227649db8ca34591e4) …
> squid: doc/dev: refine "Concepts"

- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/buckets.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
backport tracker: https://tracker.ceph.com/issues/65211
---
backport of https://github.com/ceph/ceph/pull/55953
parent tracker: https://tracker.ceph.com/issues/64708
> reef: mgr/dashboard: Mark placement targets as non-required

- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/buckets.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
backport tracker: https://tracker.ceph.com/issues/65210
---
backport of https://github.com/ceph/ceph/pull/55953
parent tracker: https://tracker.ceph.com/issues/64708
> squid: mgr/dashboard: Mark placement targets as non-required

- qa/tasks/cephfs/test_data_scan.py
> qa: Test lost+found object removal without unmounting client

- src/mds/CInode.cc
- src/mds/CInode.h
- src/mds/Locker.cc
- src/mds/MDCache.cc
> mds: do not use item item_caps in two different lists

- doc/mgr/zabbix.rst
Credit John Jasen for the development of the procedures describing the installation of Zabbix 2.
(cherry picked from commit 28aa556448cf02dc943653e76a7ef89e10ae93e9) …
> quincy: doc/mgr: credit John Jasen for Zabbix 2

- doc/mgr/zabbix.rst
Credit John Jasen for the development of the procedures describing the installation of Zabbix 2.
(cherry picked from commit 28aa556448cf02dc943653e76a7ef89e10ae93e9) …
> reef: doc/mgr: credit John Jasen for Zabbix 2

- doc/mgr/zabbix.rst
Credit John Jasen for the development of the procedures describing the installation of Zabbix 2.
(cherry picked from commit 28aa556448cf02dc943653e76a7ef89e10ae93e9) …
> squid: doc/mgr: credit John Jasen for Zabbix 2

- doc/cephfs/createfs.rst
- qa/tasks/cephfs/filesystem.py
- qa/tasks/cephfs/test_misc.py
- qa/tasks/vstart_runner.py
- src/mds/FSMap.cc
- src/mds/FSMap.h
- src/mon/FSCommands.cc
- src/mon/FSCommands.h
- src/mon/MonCommands.h
> mon/MDSMonitor: enable 'ceph fs new' use 'ceph fs set' options

- src/tools/cephfs_mirror/FSMirror.h
- src/tools/cephfs_mirror/InstanceWatcher.cc
- src/tools/cephfs_mirror/InstanceWatcher.h
- src/tools/cephfs_mirror/Mirror.cc
- src/tools/cephfs_mirror/MirrorWatcher.cc
- src/tools/cephfs_mirror/MirrorWatcher.h
- src/tools/cephfs_mirror/PeerReplayer.cc
- src/tools/cephfs_mirror/PeerReplayer.h
- src/tools/cephfs_mirror/Types.h
Fixes: https://tracker.ceph.com/issues/62265 …
> cephfs-mirror: use monotonic clocks

- doc/cephfs/fs-volumes.rst
Fixes: https://tracker.ceph.com/issues/65279
(cherry picked from commit 906ff4e4c240856d2e27cf9ac8c059479a86c5c9) …
> reef: doc: fixing doc/cephfs/fs-volumes

- src/pybind/mgr/dashboard/frontend/cypress/e2e/orchestrator/workflow/10-nfs-exports.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/buckets.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/buckets.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/components.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-advanced-fieldset/form-advanced-fieldset.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-advanced-fieldset/form-advanced-fieldset.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-advanced-fieldset/form-advanced-fieldset.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-advanced-fieldset/form-advanced-fieldset.component.ts
backport tracker: https://tracker.ceph.com/issues/65304
---
backport of https://github.com/ceph/ceph/pull/56351
parent tracker: https://tracker.ceph.com/issues/65024
> reef: mgr/dashboard: Add advanced fieldset component

- src/pybind/mgr/dashboard/frontend/cypress/e2e/orchestrator/workflow/10-nfs-exports.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/buckets.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/buckets.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/components.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-advanced-fieldset/form-advanced-fieldset.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-advanced-fieldset/form-advanced-fieldset.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-advanced-fieldset/form-advanced-fieldset.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-advanced-fieldset/form-advanced-fieldset.component.ts
backport tracker: https://tracker.ceph.com/issues/65156
---
backport of https://github.com/ceph/ceph/pull/56351
parent tracker: https://tracker.ceph.com/issues/65024
> squid: mgr/dashboard: Add advanced fieldset component

- src/rgw/rgw_lc.cc
Fixes: https://tracker.ceph.com/issues/63995 …
> rgw/lc: delete expired delete-marker when processing Expiration lc action with Days specified

- doc/dev/peering.rst
Refine the second third of the entries in the section "Concepts" in doc/dev/peering.rst. …
> doc/dev: refine "Concepts" 2 of 3

- doc/dev/peering.rst
Refine the third third of the entries in the section "Concepts" in doc/dev/peering.rst. …
> doc/dev: refine "Concepts" 3 of 3

- src/rgw/rgw_lc.cc
Avoids trivial segfault deferencing the bucket pointer.
Fixes: https://tracker.ceph.com/issues/65188
- Tracker …
> rgwlc: check for no-bucket at bucket_lc_process() preamble

- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/buckets.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
backport tracker: https://tracker.ceph.com/issues/65208
---
backport of https://github.com/ceph/ceph/pull/56449
parent tracker: https://tracker.ceph.com/issues/65110
> squid: mgr/dashboard:Update encryption and tags in bucket form

- doc/dev/peering.rst
Refine the third third of the entries in the section "Concepts" in doc/dev/peering.rst.
(cherry picked from commit 512e2dc9d52fdd14dfdd87ccd141e535d3098fb7) …
> reef: doc/dev: refine "Concepts" 3 of 3

- doc/dev/peering.rst
Refine the third third of the entries in the section "Concepts" in doc/dev/peering.rst.
(cherry picked from commit 512e2dc9d52fdd14dfdd87ccd141e535d3098fb7) …
> quincy: doc/dev: refine "Concepts" 3 of 3

- doc/dev/peering.rst
Refine the third third of the entries in the section "Concepts" in doc/dev/peering.rst.
(cherry picked from commit 512e2dc9d52fdd14dfdd87ccd141e535d3098fb7) …
> squid: doc/dev: refine "Concepts" 3 of 3

- src/test/rgw/test_posix_bucket_cache.cc
before this change, we use individual tests to setup/teardown the fixtures. this renders it difficult to run a certain test.
in this change, we structure the tests with fixtures, so that we can run any test without worrying the dependencies between them. …
> test/rgw/test_posix_bucket_cache: structure tests with fixture

- doc/dev/peering.rst
s/PG's PG logs/PG's logs/
re https://github.com/ceph/ceph/pull/56727#discussion_r1553541922 …
> doc/dev: refine "Concepts" 4 of 3

- doc/dev/peering.rst
s/PG's PG logs/PG's logs/
re https://github.com/ceph/ceph/pull/56727#discussion_r1553541922
(cherry picked from commit 221d734760b6f680e4d17cd2f0bfcd39f914c8d6) …
> squid: doc/dev: refine "Concepts" 4 of 3

- doc/dev/peering.rst
s/PG's PG logs/PG's logs/
re https://github.com/ceph/ceph/pull/56727#discussion_r1553541922
(cherry picked from commit 221d734760b6f680e4d17cd2f0bfcd39f914c8d6) …
> reef: doc/dev: refine "Concepts" 4 of 3

- doc/dev/peering.rst
s/PG's PG logs/PG's logs/
re https://github.com/ceph/ceph/pull/56727#discussion_r1553541922
(cherry picked from commit 221d734760b6f680e4d17cd2f0bfcd39f914c8d6) …
> quincy: doc/dev: refine "Concepts" 4 of 3

- monitoring/ceph-mixin/dashboards/utils.libsonnet
Backport of #56509 in reef didn't include the Table Schema in the utils.libsonnet because of which the json generation ias failing. This PR tends to add the Table Schema …
> mgr/dashboard: add Table Schema to grafonnet

- qa/suites/orch/cephadm/smoke/start.yaml
- qa/suites/orch/cephadm/workunits/task/test_host_drain.yaml
- qa/suites/orch/cephadm/workunits/task/test_monitoring_stack_basic.yaml
- qa/suites/orch/cephadm/workunits/task/test_rgw_multisite.yaml
- qa/suites/orch/cephadm/workunits/task/test_set_mon_crush_locations.yaml
- qa/suites/upgrade/reef-x/parallel/1-tasks.yaml
- qa/tasks/thrashosds-health.yaml
Fixes: https://tracker.ceph.com/issues/64864 …
> qa/suites: add "mon down" log variations to ignorelist

- src/cephadm/tox.ini
5.4.0 seems to have caused a number of permission issues in the test. In order to unblock make check, let's pin it to 5.3.5 for now. …
> cephadm: pin pyfakefs version for tox tests

- src/cephadm/tox.ini
Backport of https://github.com/ceph/ceph/pull/56760
5.4.0 seems to have caused a number of permission issues in the test. In order to unblock make check, let's pin it to 5.3.5 for now.
Signed-off-by: Adam King <adking@redhat.com>
(cherry picked from commit ce71ce10b7551a649c9a64be992c0eddfa7e7243) …
> squid: cephadm: pin pyfakefs version for tox tests

- src/pybind/mgr/cephadm/upgrade.py
A change to the `ceph osd require-osd-release` command made it so it fails if no OSDs are up unless --yes-i-really-mean-it is passed. For real clusters this is likely not an issue, but it can be an annoyance for trying upgrades on test clusters that may not have OSDs deployed. This patch is to try and just pass the flag in cases where we have no OSDs rather than failing the upgrade. …
> mgr/cephadm: handle setting required osd release with no OSDs during upgrade

- doc/releases/index.rst
- doc/releases/releases.yml
> doc: moved pacific release to Archived Releases

- src/crimson/os/seastore/btree/btree_range_pin.cc
- src/crimson/os/seastore/btree/fixed_kv_node.h
> crimson/os/seastore/btree: clean up `FixedKVLeafNode::get_logical_child()`

- src/mds/QuiesceDbManager.cc
backport tracker: https://tracker.ceph.com/issues/65289
---
backport of https://github.com/ceph/ceph/pull/56542
parent tracker: https://tracker.ceph.com/issues/65276
> squid: mds/quiesce: prevent an overflow of the wait duration

- doc/cephfs/client-auth.rst
Refine the first third of doc/cephfs/client-auth.rst.
- …
> doc/cephfs: refine client-auth (1 of 3)

- src/tools/rbd_mirror/ImageReplayer.cc
- src/tools/rbd_mirror/ImageReplayer.h
- src/tools/rbd_mirror/Types.cc
- src/tools/rbd_mirror/Types.h
> rbd-mirror: rename on_stop_journal_replay() and some operator<< arguments

- doc/cephfs/client-auth.rst
Refine the first third of doc/cephfs/client-auth.rst.
(cherry picked from commit 82c5bac5df553f1e13a2df3a107b2692efa6fc27) …
> squid: doc/cephfs: refine client-auth (1 of 3)

- doc/cephfs/client-auth.rst
Refine the first third of doc/cephfs/client-auth.rst.
(cherry picked from commit 82c5bac5df553f1e13a2df3a107b2692efa6fc27) …
> reef: doc/cephfs: refine client-auth (1 of 3)

- doc/cephfs/client-auth.rst
Refine the first third of doc/cephfs/client-auth.rst.
(cherry picked from commit 82c5bac5df553f1e13a2df3a107b2692efa6fc27) …
> quincy: doc/cephfs: refine client-auth (1 of 3)

- doc/releases/releases.yml
The Gantt diagram currently shows "reef (latest 18.2.0)" instead of 18.2.2.
- …
> doc: reorder "releases" entries for reef to fix the diagram

- src/test/rgw/bucket_notification/api.py
- src/test/rgw/bucket_notification/test_bn.py
Fixes: https://tracker.ceph.com/issues/63909
<details>
</details>
> test/rgw/notifications: do not delay http responses to notifications

- qa/suites/orch/cephadm/osds/1-start.yaml
- qa/suites/orch/cephadm/smoke-singlehost/1-start.yaml
Some of the tests failed after OSD_DOWN warning appear in the log. those OSD_DOWN happened during the tests and osd remove and destroy.
Fixes: https://tracker.ceph.com/issues/64865 …
> suites/rados/cephadm: adding OSD_DOWN to the log-ignorelist

- src/cephadm/samples/nfs.json
Otherwise deployment using this sample will fail with
"ERROR: required file missing from config-json: idmap.conf"
Fixes: https://tracker.ceph.com/issues/65155 …
> cephadm: add idmap.conf to nfs sample file

- src/script/ptl-tool.py
and
* add the release name to the branch name via a switch
* push the branch to shaman to build …
> script/ptl-tool: avoid user-configured remote names

- doc/cephfs/client-auth.rst
Refine the second third of doc/cephfs/client-auth.rst.
- …
> doc/cephfs: refine client-auth (2 of 3)

- doc/cephfs/client-auth.rst
Refine the second third of doc/cephfs/client-auth.rst.
(cherry picked from commit 083f56352b4fff662dff3c78b6a0c455605d02ff) …
> quincy: doc/cephfs: refine client-auth (2 of 3)

- doc/cephfs/client-auth.rst
Refine the second third of doc/cephfs/client-auth.rst.
(cherry picked from commit 083f56352b4fff662dff3c78b6a0c455605d02ff) …
> reef: doc/cephfs: refine client-auth (2 of 3)

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-snapshot-schedule.service.ts
Fixes: https://tracker.ceph.com/issues/65370 …
> mgr/dashboard: fix snap schedule delete retention

- qa/tasks/cephfs/caps_helper.py
- qa/tasks/cephfs/test_admin.py
- src/mds/MDSAuthCaps.cc
- src/mds/MDSAuthCaps.h
- src/mon/AuthMonitor.cc
https://tracker.ceph.com/issues/64127
https://tracker.ceph.com/issues/64182
https://tracker.ceph.com/issues/64417
- …
> cephfs,mon: fix bugs related to updating MDS caps

- doc/cephfs/client-auth.rst
Refine the final third of doc/cephfs/client-auth.rst.
(cherry picked from commit 44d1eeed703e968b374ec4d12fff3a2466a4c276) …
> squid: doc/cephfs: refine client-auth (3 of 3)

- doc/cephfs/client-auth.rst
Refine the final third of doc/cephfs/client-auth.rst.
(cherry picked from commit 44d1eeed703e968b374ec4d12fff3a2466a4c276) …
> reef: doc/cephfs: refine client-auth (3 of 3)

- doc/cephfs/client-auth.rst
Refine the final third of doc/cephfs/client-auth.rst.
(cherry picked from commit 44d1eeed703e968b374ec4d12fff3a2466a4c276) …
> quincy: doc/cephfs: refine client-auth (3 of 3)

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs-snapshot-schedule.service.ts
Fixed snap schedule repeat frequency validation
Fixes: https://tracker.ceph.com/issues/64980 …
> mgr/dashboard: snapshot schedule repeat frequency validation

- src/script/ptl-tool.py
> script/ptl-tool: add switch for adding tags to QA Run

- doc/cephfs/client-auth.rst
Make a few sentences clearer in doc/cephfs/ceph-auth.rst.
- …
> doc/cephfs: disambiguate "Reporting Free Space"

- doc/cephfs/client-auth.rst
Make a few sentences clearer in doc/cephfs/ceph-auth.rst.
(cherry picked from commit 788ccff18149b16cb01947c5bcf3bde380090df0) …
> squid: doc/cephfs: disambiguate "Reporting Free Space"

- doc/cephfs/client-auth.rst
Make a few sentences clearer in doc/cephfs/ceph-auth.rst.
(cherry picked from commit 788ccff18149b16cb01947c5bcf3bde380090df0) …
> reef: doc/cephfs: disambiguate "Reporting Free Space"

- doc/cephfs/client-auth.rst
Make a few sentences clearer in doc/cephfs/ceph-auth.rst.
(cherry picked from commit 788ccff18149b16cb01947c5bcf3bde380090df0) …
> quincy: doc/cephfs: disambiguate "Reporting Free Space"

- src/cephadm/tests/test_util_funcs.py
test/cephadm: fix timeout issue
When run make check(arm64) on omani series servers, eg.
https://jenkins.ceph.com/job/ceph-pull-requests-arm64/54751/
Shows:
python: timeout after 30 seconds
INFO     root:call_wrappers.py:284 Non-zero exit code 124 from /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/src/cephadm/.tox/py3/bin/python -c for i in range(1000000): print(i, flush=True)
Fixes: https://tracker.ceph.com/issues/65355 …
> test/cephadm: fix timeout issue

- src/pybind/mgr/dashboard/controllers/multi_cluster.py
- src/pybind/mgr/dashboard/openapi.yaml
Check if the PROMETHEUS_API_HOST value has the ip addr of the host if not replace hostnmame with ip addr
Fixes: https://tracker.ceph.com/issues/65302 …
> mgr/dashboard: fetch prometheus api host with ip addr

- doc/security/index.rst
Remove a GPG key that was lost in a server upgrade, and remove the text that describes it. …
> doc/security: remove old GPG information

- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/retention-frequency.enum.ts
Removed "minutely" from retention policy dropdown
Fixes: https://tracker.ceph.com/issues/65493 …
> mgr/dashboard: remove minutely from retention 

- src/pybind/mgr/dashboard/controllers/multi_cluster.py
When adding a cluster to the multi-cluster setup, set all the mgr IP's as cross_origin_url in the connected cluster to provide HA for the hub cluster in case of a mgr failover
Fixes: https://tracker.ceph.com/issues/65499
[Screencast from 2024-04-12 11-16-07.webm](https://github.com/ceph/ceph/assets/66050535/dc8dc11b-da8f-456a-8ffd-f3e62b3bebba) …
> mgr/dashboard: provide hub Cluster HA for multi-cluster setup

- doc/security/index.rst
Remove a GPG key that was lost in a server upgrade, and remove the text that describes it.
(cherry picked from commit 95ec06a59a29ad2528471312ebc2931f7097213b) …
> reef: doc/security: remove old GPG information

- src/pybind/mgr/cephadm/templates/services/prometheus/prometheus.yml.j2
- src/pybind/mgr/cephadm/tests/test_services.py
Fixes: https://tracker.ceph.com/issues/64970 …
> mgr/dashboard: fix duplicate grafana panels when on mgr failover

- src/pybind/mgr/cephadm/services/cephadmservice.py
- src/pybind/mgr/rgw/module.py
- src/python-common/ceph/deployment/service_spec.py
- src/python-common/ceph/rgw/rgwam_core.py
Backport of https://github.com/ceph/ceph/pull/56458
<details>
</details>
> squid: mgr/cephadm: update rgw zonegroup w/ zonegroup_hostnames from rgw spec

- qa/cephfs/overrides/ignorelist_health.yaml
Fixes: https://tracker.ceph.com/issues/65271 …
> qa: ignore human-friendly POOL_APP_NOT_ENABLED in clog

- monitoring/ceph-mixin/Makefile
- monitoring/ceph-mixin/alerts.jsonnet
- monitoring/ceph-mixin/config.libsonnet
- monitoring/ceph-mixin/lint-jsonnet.sh
- monitoring/ceph-mixin/prometheus_alerts.libsonnet
- monitoring/ceph-mixin/prometheus_alerts.yml
- monitoring/ceph-mixin/tests_alerts/test_alerts.yml
- monitoring/ceph-mixin/tox.ini
- monitoring/snmp/CEPH-MIB.txt
This is a backport of PR: https://github.com/ceph/ceph/pull/50132 to reef branch, adding RBD Mirror monitoring alerts …
> add RBD Mirror monitoring alerts

- src/pybind/mgr/dashboard/frontend/cypress/e2e/pools/pools.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-configuration-form/rbd-configuration-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.html
backport tracker: https://tracker.ceph.com/issues/65504
---
backport of https://github.com/ceph/ceph/pull/56694
parent tracker: https://tracker.ceph.com/issues/65207
> reef: mgr/dashboard: Move features to advanced section and expand by default rbd config section

- src/pybind/mgr/dashboard/frontend/cypress/e2e/pools/pools.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-configuration-form/rbd-configuration-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.html
backport tracker: https://tracker.ceph.com/issues/65505
---
backport of https://github.com/ceph/ceph/pull/56694
parent tracker: https://tracker.ceph.com/issues/65207
> squid: mgr/dashboard: Move features to advanced section and expand by default rbd config section

- src/script/ptl-tool.py
> script/ptl-tool: add comment to PRs under QA

- src/pybind/mgr/dashboard/frontend/src/app/shared/components/grafana/grafana.component.ts
When the anonymous access is disabled, the dashboards will have a password so the verification error code can be 401 (Unauthorized)
Fixes: https://tracker.ceph.com/issues/65534 …
> mgr/dashboard: fix dashboard not visible on disabled anonymous access  

- src/librbd/Utils.cc
- src/librbd/api/Group.cc
> librbd: make group and group snapshot IDs more random

- src/python-common/setup.py
this changeset addresses some PEP8 compliance issues in python-common.
- Component …
> python-common: PEP8 related cleanups

- src/crimson/osd/osd_meta.cc
Fixes: https://tracker.ceph.com/issues/65474 …
> crimson/osd/osd_meta: load incremental osdmap from "inc_osdmap.XXX"

- src/crimson/osd/replicated_recovery_backend.cc
- src/crimson/osd/replicated_recovery_backend.h
Don't use peer's info on prepare_pull.
Fixes: https://tracker.ceph.com/issues/65200 …
> crimson/osd/replicated_recovery_backend: prepare_pull use pg_info

- src/crimson/osd/pg.h
- src/crimson/osd/recovery_backend.cc
- src/crimson/osd/replicated_recovery_backend.cc
Fixes: https://tracker.ceph.com/issues/65453 …
> crimson/osd/recovery_backends: discard outdated recovery ops

- src/crimson/osd/osd_operations/client_request.cc
- src/crimson/osd/osd_operations/client_request_common.cc
- src/crimson/osd/osd_operations/client_request_common.h
- src/crimson/osd/osd_operations/internal_client_request.cc
- src/crimson/osd/replicated_backend.cc
- src/crimson/osd/replicated_recovery_backend.cc
Found while investigating https://tracker.ceph.com/issues/65491 …
> crimson/osd/replicated_backend: misc fixes

- src/crimson/osd/osd_operations/client_request.cc
- src/test/librados/misc_cxx.cc
- src/test/neorados/misc.cc
- src/test/pybind/test_rados.py
Fixes: https://tracker.ceph.com/issues/64782 …
> crimson/osd/osd_operations/client_requests: we don't support rados locator keys

- doc/rados/operations/crush-map.rst
Add "ceph osd crush rename bucket" command. This commit is made in response to a request from Michele Giacomoli.
Fixes: https://tracker.ceph.com/issues/65599 …
> doc/rados: add bucket rename command

- doc/radosgw/dynamicresharding.rst
this will render the config options with their descriptions/defaults taken directly from common/options/rgw.yaml.in
(cherry picked from commit 50ebbc538c02352950d9c04e8b41b2d88701c552) …
> squid: doc/radosgw: use 'confval' directive for reshard config options

- doc/radosgw/metrics.rst
> doc/radosgw: fix typo in metrics.rst

- doc/rados/operations/crush-map.rst
Add "ceph osd crush rename bucket" command. This commit is made in response to a request from Michele Giacomoli.
Fixes: https://tracker.ceph.com/issues/65599
(cherry picked from commit 1030b572fa1680792b4c5843a6cf517bd31511ae) …
> quincy: doc/rados: add bucket rename command

- doc/rados/operations/crush-map.rst
Add "ceph osd crush rename bucket" command. This commit is made in response to a request from Michele Giacomoli.
Fixes: https://tracker.ceph.com/issues/65599
(cherry picked from commit 1030b572fa1680792b4c5843a6cf517bd31511ae) …
> reef: doc/rados: add bucket rename command

- doc/rados/operations/crush-map.rst
Add "ceph osd crush rename bucket" command. This commit is made in response to a request from Michele Giacomoli.
Fixes: https://tracker.ceph.com/issues/65599
(cherry picked from commit 1030b572fa1680792b4c5843a6cf517bd31511ae) …
> squid: doc/rados: add bucket rename command

- doc/radosgw/dynamicresharding.rst
this will render the config options with their descriptions/defaults taken directly from common/options/rgw.yaml.in
(cherry picked from commit 50ebbc538c02352950d9c04e8b41b2d88701c552) …
> reef: doc/radosgw: use 'confval' directive for reshard config options

- doc/radosgw/dynamicresharding.rst
this will render the config options with their descriptions/defaults taken directly from common/options/rgw.yaml.in
(cherry picked from commit 50ebbc538c02352950d9c04e8b41b2d88701c552) …
> quincy: doc/radosgw: use 'confval' directive for reshard config options

- src/mds/MDCache.cc
Fixes: https://tracker.ceph.com/issues/65342 …
> mds: use mds_cache_quiesce_decay_rate to init quiesce_counter

- qa/tasks/cephfs/mount.py
- qa/tasks/cephfs/test_client_recovery.py
- qa/tasks/cephfs/test_misc.py
- qa/tasks/cephfs/test_openfiletable.py
- qa/tasks/cephfs/test_strays.py
Fixes: https://tracker.ceph.com/issues/65022 …
> qa: do not iterate list being modified

- monitoring/ceph-mixin/config.libsonnet
Recommendation from the nvmeof team …
> monitoring/ceph-mixin: set NVMeoFMaxGatewaysPerGroup to 4

- src/test/osd/safe-to-destroy.sh
The test script is not detecting the build env vars and not checking 
return code from start osds\mon\mgr.
This will add those checks to prevent false results from the test. …
> test/osd/safe-to-destroy.sh: Add checks for the test

- src/tools/rados/rados.cc
> tools: rados get takes --offset now

- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
> os/bluestore: add omap_set* perf counters

- src/crimson/osd/ops_executer.cc
- src/crimson/osd/ops_executer.h
- src/crimson/osd/pg_backend.cc
- src/test/librados/snapshots_cxx.cc
Fixes: https://tracker.ceph.com/issues/65113 …
> crimson/osd/ops_executer: fix snap overlap range error

- src/rgw/rgw_log.cc
As per AWS doc (https://docs.aws.amazon.com/AmazonS3/latest/userguide/RequesterPaysBuckets.html#ChargeDetails), request payer should not incur charges for 403 requests.
Fixes: https://tracker.ceph.com/issues/65473
> rgw: exclude logging of request payer for 403 requests

- src/crimson/common/tri_mutex.cc
- src/crimson/common/tri_mutex.h
- src/crimson/osd/object_context.h
Fixes: https://tracker.ceph.com/issues/65451
- Tracker …
> crimson/common/tri_mutex: make locking/promotion atomic if possible

- src/crimson/os/seastore/btree/btree_range_pin.cc
- src/test/crimson/seastore/test_object_data_handler.cc
Fixes: https://tracker.ceph.com/issues/65610 …
> test/crimson/seastore/test_object_data_handler: remap pins through the transaction that created the pins

- doc/mgr/dashboard.rst
Explain that an error message received in response to "redirect_resolve_ip_addr True" might be caused by having an insufficiently recent release of Ceph running in your cluster.
Fixes: https://tracker.ceph.com/issues/61312 …
> doc/mgr: explain error message - dashboard.rst

- doc/mgr/dashboard.rst
Explain that an error message received in response to "redirect_resolve_ip_addr True" might be caused by having an insufficiently recent release of Ceph running in your cluster.
Fixes: https://tracker.ceph.com/issues/61312
(cherry picked from commit 78545030761330c44168dbb3f8d1e4c3c9a9a3bd) …
> reef: doc/mgr: explain error message - dashboard.rst

- doc/mgr/dashboard.rst
Explain that an error message received in response to "redirect_resolve_ip_addr True" might be caused by having an insufficiently recent release of Ceph running in your cluster.
Fixes: https://tracker.ceph.com/issues/61312
(cherry picked from commit 78545030761330c44168dbb3f8d1e4c3c9a9a3bd) …
> quincy: doc/mgr: explain error message - dashboard.rst

- doc/mgr/dashboard.rst
Explain that an error message received in response to "redirect_resolve_ip_addr True" might be caused by having an insufficiently recent release of Ceph running in your cluster.
Fixes: https://tracker.ceph.com/issues/61312
(cherry picked from commit 78545030761330c44168dbb3f8d1e4c3c9a9a3bd) …
> squid: doc/mgr: explain error message - dashboard.rst

- doc/cephfs/client-auth.rst
Clarify the front matter in doc/cephfs/client-auth.rst.
- …
> doc/cephfs: edit front matter in client-auth.rst

- src/test/ceph_crypto.cc
Fixes: https://tracker.ceph.com/issues/65673 …
> test/ceph_crypto: define __has_feature if the compiler doesn't have it

- src/crimson/os/seastore/seastore.cc
> crimson/os/seastore: only update onode sizes when necessary

- src/common/options/crimson.yaml.in
- src/crimson/common/fixed_kv_node_layout.h
- src/crimson/os/seastore/btree/fixed_kv_btree.h
- src/crimson/os/seastore/btree/fixed_kv_node.h
- src/crimson/os/seastore/cache.cc
- src/crimson/os/seastore/cache.h
- src/crimson/os/seastore/cached_extent.h
- src/crimson/os/seastore/extent_placement_manager.cc
- src/crimson/os/seastore/extent_placement_manager.h
- src/crimson/os/seastore/lba_manager.cc
- src/crimson/os/seastore/lba_manager.h
- src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.cc
- src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.h
- src/crimson/os/seastore/lba_manager/btree/lba_btree_node.h
- src/crimson/os/seastore/ordering_handle.h
- src/crimson/os/seastore/transaction.h
- src/crimson/os/seastore/transaction_manager.cc
- src/crimson/os/seastore/transaction_manager.h
- src/test/crimson/seastore/onode_tree/test_fltree_onode_manager.cc
- src/test/crimson/seastore/onode_tree/test_staged_fltree.cc
- src/test/crimson/seastore/test_block.h
- src/test/crimson/seastore/test_btree_lba_manager.cc
- src/test/crimson/seastore/test_collection_manager.cc
- src/test/crimson/seastore/test_object_data_handler.cc
- src/test/crimson/seastore/test_omap_manager.cc
- src/test/crimson/seastore/test_seastore.cc
- src/test/crimson/seastore/test_seastore_cache.cc
- src/test/crimson/seastore/test_transaction_manager.cc
- src/test/crimson/seastore/transaction_manager_test_state.h
> crimson/os/seastore: support extent checksum verification

- doc/radosgw/bucketpolicy.rst
Rewrite two sentences so that they explain precisely what was added to Ceph and when it was added to Ceph.
This commit is made in response to a request made by Dr Per Mildner on https://pad.ceph.com/p/Report_Documentation_Bugs. …
> doc/radosgw: disambiguate version-added remarks

- doc/cephfs/client-auth.rst
Clarify the front matter in doc/cephfs/client-auth.rst.
(cherry picked from commit 713c7304d15279cbc2031efc05cc9e49911974fe) …
> squid: doc/cephfs: edit front matter in client-auth.rst

- doc/cephfs/client-auth.rst
Clarify the front matter in doc/cephfs/client-auth.rst.
(cherry picked from commit 713c7304d15279cbc2031efc05cc9e49911974fe) …
> reef: doc/cephfs: edit front matter in client-auth.rst

- doc/cephfs/client-auth.rst
Clarify the front matter in doc/cephfs/client-auth.rst.
(cherry picked from commit 713c7304d15279cbc2031efc05cc9e49911974fe) …
> quincy: doc/cephfs: edit front matter in client-auth.rst

- doc/radosgw/bucketpolicy.rst
Rewrite two sentences so that they explain precisely what was added to Ceph and when it was added to Ceph.
This commit is made in response to a request made by Dr Per Mildner on https://pad.ceph.com/p/Report_Documentation_Bugs.
(cherry picked from commit 586e8e6577c6b62062d6ed60c439088705fbd2c1) …
> squid: doc/radosgw: disambiguate version-added remarks

- doc/radosgw/bucketpolicy.rst
Rewrite two sentences so that they explain precisely what was added to Ceph and when it was added to Ceph.
This commit is made in response to a request made by Dr Per Mildner on https://pad.ceph.com/p/Report_Documentation_Bugs.
(cherry picked from commit 586e8e6577c6b62062d6ed60c439088705fbd2c1) …
> reef: doc/radosgw: disambiguate version-added remarks

- doc/radosgw/bucketpolicy.rst
Rewrite two sentences so that they explain precisely what was added to Ceph and when it was added to Ceph.
This commit is made in response to a request made by Dr Per Mildner on https://pad.ceph.com/p/Report_Documentation_Bugs.
(cherry picked from commit 586e8e6577c6b62062d6ed60c439088705fbd2c1) …
> quincy: doc/radosgw: disambiguate version-added remarks

- doc/install/get-packages.rst
> reef: doc/install: fix typos in openEuler-installation doc

- src/crimson/os/seastore/transaction_manager.h
Indirect mappings always hold the checksums of the corresponding intermediate mappings, which may have non-zero …
> crimson/os/seastore/transaction_manager: remove incorrect assertions

- src/crimson/osd/object_context.cc
- src/crimson/osd/object_context.h
- src/crimson/osd/object_context_loader.cc
- src/crimson/osd/object_context_loader.h
- src/crimson/osd/osd_operations/snaptrim_event.cc
- src/crimson/osd/replicated_recovery_backend.cc
Previously, only the head obc had ssc reference. Let clone obc also reference it's head ssc.
Fixes: https://tracker.ceph.com/issues/65203
Fixes: https://tracker.ceph.com/issues/65201
Follow-up PR: #56752 …
> crimson/osd/replicated_recovery_backend: Fix recovery obc usage

- src/crimson/osd/osd_operations/client_request_common.cc
- src/crimson/osd/replicated_recovery_backend.cc
> crimson/osd/osd_operations/client_request: retrieve the correct version for objects to be recovered urgently

- doc/install/get-packages.rst
(cherry picked from commit 593ab1ad41467898c57c44baeb947bd238cba645) …
> squid: doc/install: fix typos in openEuler-installation doc

- src/crimson/osd/osd_operations/snaptrim_event.cc
- src/crimson/osd/osd_operations/snaptrim_event.h
- src/crimson/osd/pg.cc
- src/crimson/osd/pg.h
Fixes: https://tracker.ceph.com/issues/65568 …
> crimson/osd/pg: only kick off snap trimming when PGs are clean

- src/crimson/osd/osd_operation.h
- src/crimson/osd/pg_recovery.cc
Fixes: https://tracker.ceph.com/issues/65399 …
> crimson/osd/pg_recovery: backoff if the recovery/backfill is deferred

- src/test/librbd/test_internal.cc
> test/librbd/test_internal: change to check for 4KB-aligned sparse read

- doc/rados/operations/monitoring-osd-pg.rst
> doc/rados/operations: rephrase OSDs peering

- doc/man/8/radosgw-admin.rst
Add command to documentation to get lifecycle command for a bucket.
- Component …
> doc/man/8/radosgw-admin: add get lifecycle command

- doc/man/8/radosgw-admin.rst
Signed-off-by: rkhudov <rhudov@gmail.com>
(cherry picked from commit 04393ec3c1a12d6a9405272ab2cffe9dfa67aa92)
- …
> squid: doc/man/8/radosgw-admin: add get lifecycle command

- doc/man/8/radosgw-admin.rst
Signed-off-by: rkhudov <rhudov@gmail.com>
(cherry picked from commit 04393ec3c1a12d6a9405272ab2cffe9dfa67aa92)
- …
> reef: doc/man/8/radosgw-admin: add get lifecycle command

- doc/man/8/radosgw-admin.rst
Signed-off-by: rkhudov <rhudov@gmail.com>
(cherry picked from commit 04393ec3c1a12d6a9405272ab2cffe9dfa67aa92)
- …
> quincy: doc/man/8/radosgw-admin: add get lifecycle command

- doc/rados/operations/monitoring-osd-pg.rst
(cherry picked from commit 048f6e539b3035175479a88a4cf6f774cca68ddb) …
> squid: doc/rados/operations: rephrase OSDs peering

- doc/rados/operations/monitoring-osd-pg.rst
(cherry picked from commit 048f6e539b3035175479a88a4cf6f774cca68ddb) …
> reef: doc/rados/operations: rephrase OSDs peering

- doc/rados/operations/monitoring-osd-pg.rst
(cherry picked from commit 048f6e539b3035175479a88a4cf6f774cca68ddb) …
> quincy: doc/rados/operations: rephrase OSDs peering

- src/client/Client.cc
The client may not be able to immediately send the request after learning the target; e.g. the target rank has no session yet or is otherwise temporarily unavailable.
Fixes: https://tracker.ceph.com/issues/65614 …
> client: clear resend_mds only after sending request

- src/cephadm/cephadm.py
cephadm deploys the cluster, fails and does a rollback. If the passed file doesn't exist we can make the CLI fail early instead.
```
... omitted output ...
Applying ../host-spec.yaml to cluster
FileNotFoundError: [Errno 2] No such file or directory: '../host-spec.yaml'
***************
Cephadm hit an issue during cluster installation. Current cluster files will be deleted automatically.
To disable this behaviour you can pass the --no-cleanup-on-failure flag. In case of any previous
broken installation, users must use the following command to completely delete the broken cluster:
> cephadm rm-cluster --force --zap-osds --fsid <fsid>
for more information please refer to https://docs.ceph.com/en/latest/cephadm/operations/#purging-a-cluster
***************
Deleting cluster with fsid: …
```
> cephadm: check if file exists when passing `--apply_spec`

- src/pybind/mgr/cephadm/module.py
Non-functional cleanup as it was pointed out this
block was written in an unintuitive way. …
> mgr/cephadm: cleanup service size logic block

- src/pybind/rados/rados.pyx
- src/test/pybind/test_rados.py
backport tracker: https://tracker.ceph.com/issues/63400
backport of https://github.com/ceph/ceph/pull/49486
parent tracker: https://tracker.ceph.com/issues/58304
(cherry picked from commit 1c64c6be303f5ed4110468101a01576508468a74) …
> reef: pybind/rados: fix missed changes for PEP484 style type annotations

- src/script/ptl-tool.py
> script/ptl-tool: add switch to update existing qa ticket

- monitoring/ceph-mixin/dashboards_out/ceph-cluster.json
Fixes: https://tracker.ceph.com/issues/65218 …
> monitoring/ceph-mixin: Add cluster variable to ceph-cluster.json

- src/pybind/mgr/cephadm/services/nvmeof.py
Otherwise it is impossible to make rbd snapshots
Fixes: https://tracker.ceph.com/issues/65691 …
> mgr/cephadm: set OSD cap for NVMEoF daemon to "profile rbd"

- doc/cephfs/snap-schedule.rst
- qa/tasks/cephfs/test_snap_schedules.py
- src/pybind/mgr/snap_schedule/fs/schedule.py
- src/pybind/mgr/snap_schedule/fs/schedule_client.py
Fixes: https://tracker.ceph.com/issues/65350 …
> mgr/snap_schedule: restore yearly spec to lowercase y

- monitoring/ceph-mixin/dashboards/multi-cluster.libsonnet
- monitoring/ceph-mixin/dashboards_out/multi-cluster-overview.json
Fix extra braces in multi cluster overview grafana json
Fixes: https://tracker.ceph.com/issues/65760
- Tracker …
> mgr/dashboard: fix cluster filter typo in multi-cluster-overview grafana dashboard

- doc/rados/troubleshooting/troubleshooting-pg.rst
Make the changes suggested by Anthony D'Atri in
https://github.com/ceph/ceph/pull/57022. …
> doc/rados: PR#57022 unfinished business

- doc/cephadm/services/monitoring.rst
Address Adam King's request for version-specific
cephadm-container-image-retrieval procedures, which he requested here: https://github.com/ceph/ceph/pull/57208#discussion_r1586614140 …
> reef: doc/cephadm: Reef default images procedure

- doc/cephadm/services/monitoring.rst
Address Adam King's request for version-specific
cephadm-container-image-retrieval procedures, which he requested here: https://github.com/ceph/ceph/pull/57208#discussion_r1586614140 …
> pacific: doc/cephadm: Pacific default images procedure

- doc/rados/troubleshooting/troubleshooting-pg.rst
Make the changes suggested by Anthony D'Atri in
https://github.com/ceph/ceph/pull/57022.
(cherry picked from commit 93898d80836ac41041f75b5bf5398f9388abb52f) …
> squid: doc/rados: PR#57022 unfinished business

- doc/cephadm/services/monitoring.rst
- doc/rados/troubleshooting/troubleshooting-pg.rst
Make the changes suggested by Anthony D'Atri in
https://github.com/ceph/ceph/pull/57022.
(cherry picked from commit 93898d80836ac41041f75b5bf5398f9388abb52f) …
> reef: doc/rados: PR#57022 unfinished business

- doc/cephadm/services/monitoring.rst
- doc/rados/troubleshooting/troubleshooting-pg.rst
Make the changes suggested by Anthony D'Atri in
https://github.com/ceph/ceph/pull/57022.
(cherry picked from commit 93898d80836ac41041f75b5bf5398f9388abb52f) …
> quincy: doc/rados: PR#57022 unfinished business

- doc/foundation.rst
> doc/foundation: Updating members for Jan 2024

- src/crimson/osd/ops_executer.cc
- src/crimson/osd/ops_executer.h
>  crimson/osd: make osd_op_params::at_version coherent with last log entry 

- doc/mgr/dashboard.rst
Edit the section "Resolve IP address to hostname before redirect" in doc/mgr/dashboard.rst. …
> doc/mgr: edit "Resolve IP address to hostname before redirect"

- qa/workunits/rbd/rbd_mirror_bootstrap.sh
- qa/workunits/rbd/rbd_mirror_helpers.sh
- src/test/rbd_mirror/test_mock_PoolReplayer.cc
- src/tools/rbd_mirror/Mirror.cc
- src/tools/rbd_mirror/PoolReplayer.cc
> rbd-mirror: clean up stale pool replayers and callouts better

- src/os/bluestore/BlueFS.cc
In BlueFS::_estimate_log_size_N, the total size of the dir was calculated incorrectly.
It should be the number of dirs multiplied by (avg_size+1).
Fixes: https://tracker.ceph.com/issues/65176
co-author: Jrchyang Yu <yuzhiqiang_yewu@cmss.chinamobile.com>
Signed-off-by: Wang Linke <wanglinke_yewu@cmss.chinamobile.com> …
> os/bluestore: fix the problem that _estimate_log_size_N calculates the log size incorrectly

- src/test/rgw/bucket_notification/test_bn.py
RGW: test for exact match if the test is not persistent
- …
> RGW: test for exact match if the test is not persistent

- qa/cephfs/overrides/pg_health.yaml
Fixes: https://tracker.ceph.com/issues/65700
<details>
</details>
> qa: ignore variation of PG_DEGRADED health warning

- doc/mgr/dashboard.rst
Edit and update the "Overview" section in doc/mgr/dashboard.rst. …
> doc/mgr: edit "Overview" in dashboard.rst

- src/os/ObjectStore.h
- src/os/bluestore/BlueStore.cc
- src/osd/PGBackend.cc
- src/osd/osd_types.h
backport tracker: https://tracker.ceph.com/issues/65593
---
backport of https://github.com/ceph/ceph/pull/56995
parent tracker: https://tracker.ceph.com/issues/65185 …
> squid: osd/PGBackend::be_scan_list: only call stat, getattrs once per object

- src/exporter/DaemonMetricCollector.cc
- src/exporter/DaemonMetricCollector.h
ceph exporter crashes, and fails to handle exceptions in dump_asok_metrics(). add try and catch blocks to handle the exceptions gracefully. …
> exporter: handle exceptions gracefully

- src/rgw/rgw_asio_frontend.cc
Fixes: https://tracker.ceph.com/issues/65664
(details in https://tracker.ceph.com/issues/65664#note-3)
- Tracker …
> rgw/beast: fix crash observed in SSL stream.async_shutdown()

- doc/cephfs/fs-volumes.rst
Fixes: https://tracker.ceph.com/issues/65881
<details>
</details>
> doc/cephfs: expand the role of quiesce in consistent backups

- doc/mgr/dashboard.rst
Edit the section "Resolve IP address to hostname before redirect" in doc/mgr/dashboard.rst.
(cherry picked from commit e0838daa9bc1d549a8da2b21608153c77b15455a) …
> squid: doc/mgr: edit "Resolve IP address to hostname before redirect"

- doc/mgr/dashboard.rst
Edit the section "Resolve IP address to hostname before redirect" in doc/mgr/dashboard.rst.
(cherry picked from commit e0838daa9bc1d549a8da2b21608153c77b15455a) …
> reef: doc/mgr: edit "Resolve IP address to hostname before redirect"

- doc/mgr/dashboard.rst
Edit the section "Resolve IP address to hostname before redirect" in doc/mgr/dashboard.rst.
(cherry picked from commit e0838daa9bc1d549a8da2b21608153c77b15455a) …
> quincy: doc/mgr: edit "Resolve IP address to hostname before redirect"

- doc/mgr/dashboard.rst
Edit and update the "Overview" section in doc/mgr/dashboard.rst.
(cherry picked from commit 6cf06c60f7c3f87707c7dc47cde2346cec7cf00f) …
> squid: doc/mgr: edit "Overview" in dashboard.rst

- doc/mgr/dashboard.rst
Edit and update the "Overview" section in doc/mgr/dashboard.rst.
(cherry picked from commit 6cf06c60f7c3f87707c7dc47cde2346cec7cf00f) …
> reef: doc/mgr: edit "Overview" in dashboard.rst

- doc/mgr/dashboard.rst
Edit and update the "Overview" section in doc/mgr/dashboard.rst.
(cherry picked from commit 6cf06c60f7c3f87707c7dc47cde2346cec7cf00f) …
> quincy: doc/mgr: edit "Overview" in dashboard.rst

- doc/radosgw/bucketpolicy.rst
Update the list of S3 actions supported in the Squid release of Ceph.
Note: The list of S3 actions supported in Squid is not the list of S3 actions supported in Reef or in Quincy. …
> squid: doc/radosgw: update Squid S3 action list

- doc/radosgw/bucketpolicy.rst
Update the list of S3 actions supported in the Quincy release of Ceph.
Note: the list of S3 actions supported in Reef is not the list of S3 actions supported in Squid or in Reef. …
> quincy: doc/radosgw: update S3 action list

- src/pybind/mgr/cephadm/autotune.py
- src/pybind/mgr/cephadm/serve.py
- src/pybind/mgr/cephadm/tests/test_autotune.py
This came from trying to debug behavior of the autotuner in the upstream mailing list. The test case being added was what that user was seeing. The debug logging being added was useful in getting a full understanding of how the autotuner got the result it did. Therefore, why not add the logging to the actual codebase so we can make use of it to debug autotuner issues in the future …
> mgr/cephadm: additional debug logging for autotuner

- qa/suites/orch/cephadm/workunits/task/test_host_drain.yaml
These warnings are unsurprising during this test
as we clear all the daemons off of a host. They
shouldn't result in the test failing. …
> qa/cephadm: ignore stray warnings on host drain test

- qa/suites/orch/cephadm/no-agent-workunits/task/test_cephadm_timeout.yaml
This test tests the timeout by explicitly causing the refresh of the devices to timeout, which will always raise this health warning …
> qa/cephadm: ignore CEPHADM_REFRESH_FAILED on timeout test

- src/pybind/mgr/cephadm/services/iscsi.py
- src/pybind/mgr/cephadm/services/nvmeof.py
The parent class (CephService) handles the cleanup of
the auth keyring. The parent class post_remove also
does the debug log that is getting removed
Fixes: https://tracker.ceph.com/issues/65717 …
> mgr/cephadm: cleanup iscsi and nvmeof keyrings upon daemon removal

- doc/radosgw/config-ref.rst
- src/common/options/rgw.yaml.in
- src/rgw/driver/d4n/d4n_policy.cc
- src/rgw/driver/d4n/rgw_sal_d4n.cc
- src/rgw/rgw_redis_driver.cc
- src/test/rgw/test_d4n_directory.cc
- src/test/rgw/test_d4n_policy.cc
- src/test/rgw/test_redis_driver.cc
Add long descriptions to the D4N config variables and improve naming where applicable …
> d4n: Add more in-depth config descriptions and improve naming

- doc/radosgw/bucketpolicy.rst
Update the list of S3 actions supported in the Reef release of Ceph.
Note: the list of S3 actions supported in Reef is not the list of S3 actions supported in Squid or in Quincy. …
> reef: doc/radosgw: update Reef S3 action list

- doc/cephfs/fs-volumes.rst
Signed-off-by: Leonid Usov <leonid.usov@ibm.com>
Fixes: https://tracker.ceph.com/issues/65897
Original-Issue: https://tracker.ceph.com/issues/65881
Original-PR: #57390
(cherry picked from commit 34ec2a4c6a065028d593b1e959600a3ce87541a8)
<details> …
> squid: doc/cephfs: expand the role of quiesce in consistent backups

- doc/cephfs/fs-volumes.rst
Include the suggestions for improving doc/cephfs/fs-volumes.rst made by Anthony D'Atri here
https://github.com/ceph/ceph/pull/57415#discussion_r1597362110 …
> doc/cephfs: edit fs-volumes.rst (1 of x) followup

- doc/dev/developer_guide/dash-devel.rst
s/to asses/to assess/ in doc/deve/developer_guide/dash-devel.
- …
> doc/dev: s/to asses/to assess/

- doc/dev/developer_guide/dash-devel.rst
s/to asses/to assess/ in doc/deve/developer_guide/dash-devel.
(cherry picked from commit 832358b072ec5cb4672de8a7a7aebf10a39fd0e5) …
> squid: doc/dev: s/to asses/to assess/

- doc/dev/developer_guide/dash-devel.rst
s/to asses/to assess/ in doc/deve/developer_guide/dash-devel.
(cherry picked from commit 832358b072ec5cb4672de8a7a7aebf10a39fd0e5) …
> reef: doc/dev: s/to asses/to assess/

- doc/dev/developer_guide/dash-devel.rst
s/to asses/to assess/ in doc/deve/developer_guide/dash-devel.
(cherry picked from commit 832358b072ec5cb4672de8a7a7aebf10a39fd0e5) …
> quincy: doc/dev: s/to asses/to assess/

- doc/cephfs/fs-volumes.rst
Edit doc/cephfs/fs-volumes to the section "FS Subvolumes" (but not including the section "FS Subvolumes").
(cherry picked from commit 0acbb278fc712c32334fd7340b887d2865dbfb86) …
> squid: doc/cephfs: edit fs-volumes.rst (1 of x)

- doc/cephfs/fs-volumes.rst
Include the suggestions for improving doc/cephfs/fs-volumes.rst made by Anthony D'Atri here
https://github.com/ceph/ceph/pull/57415#discussion_r1597362110
(cherry picked from commit cb700d804b4390fd9f55444dcfc04dfebac3a1bf) …
> reef: doc/cephfs: edit fs-volumes.rst (1 of x) followup

- qa/erasure-code/ec-rados-plugin=jerasure-k=8-m=6-crush.yaml
Fixes: https://tracker.ceph.com/issues/65517 …
> suites/ec-rados-plugin=jerasure-k=8-m=6-crush: roles set

- src/tools/cephfs_mirror/PeerReplayer.cc
- src/tools/cephfs_mirror/PeerReplayer.h
> cephfs_mirror: increment sync_failures when sync_perms() and sync_snaps() fails

- src/pybind/mgr/stats/fs/perf_stats.py
Fixes: https://tracker.ceph.com/issues/65073 …
> mgr/stats: initialize mx_last_updated in FSPerfStats

- src/common/options/crimson.yaml.in
- src/crimson/os/seastore/btree/btree_range_pin.cc
- src/crimson/os/seastore/btree/btree_range_pin.h
- src/crimson/os/seastore/btree/fixed_kv_node.h
- src/crimson/os/seastore/cache.h
- src/crimson/os/seastore/cached_extent.h
- src/crimson/os/seastore/object_data_handler.cc
- src/crimson/os/seastore/transaction_manager.h
- src/test/crimson/seastore/test_object_data_handler.cc
Follow-up: https://github.com/ceph/ceph/pull/56353#discussion_r1571627206 …
> crimson/os/seastore: add is_data_stable() to allow delta-overwrite on EXIST_CLEAN

- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.html
Fixes: https://tracker.ceph.com/issues/63124
Before:
[Screencast from 2023-10-06 19-00-09.webm](https://github.com/ceph/ceph/assets/23611106/67aa5bf3-ba11-4190-b5e5-cb0786d0a7b7)
After:
<details>
- …
> mgr/dashboard: add absolute path validation for pseudo path of nfs export

- examples/rgw/boto3/put-bucket-replication.py
- examples/rgw/boto3/service-2.sdk-extras.json
> Add new sync-policy related params to boto3 extension

- .github/workflows/create-backport-trackers.yml
- README.md
> .github: document where runs/output can be examined

- src/crimson/osd/osd_operations/scrub_events.cc
backport of https://github.com/ceph/ceph/pull/56375
> squid: crimson/.../scrub_events: fix progress lifetime in deep_scan_object

- .github/workflows/create-backport-trackers.yml
It is rejected by github's parser.
See: https://github.com/ceph/ceph/actions/runs/9096324277/workflow
- Tracker …
> .github: remove description for action

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/upgrade.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/components.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/upgradable/upgradable.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/upgradable/upgradable.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/upgradable/upgradable.component.ts
[screen-capture (44).webm](https://github.com/ceph/ceph/assets/106810838/1c3296e7-08d5-4444-9e94-3d824ba35c13)
Fixes: https://tracker.ceph.com/issues/65012 …
> mgr/dashboard: add upgrade notification

- src/crimson/os/seastore/transaction_manager.cc
> crimson/os/seastore/transaction_manager: drop unused code

- src/crimson/os/seastore/object_data_handler.cc
* Refactor based on the read range, pin range and extent range.
* MISC: Logs, variable names, asserts and indentions. …
> crimson/os/seastore/object_data_handler: cleanup read()

- src/crimson/common/errorator.h
- src/crimson/common/interruptible_future.h
- src/crimson/os/cyanstore/cyan_store.h
- src/crimson/os/seastore/async_cleaner.h
- src/crimson/os/seastore/journal/record_submitter.cc
- src/crimson/os/seastore/onode_manager/staged-fltree/node.cc
- src/crimson/os/seastore/onode_manager/staged-fltree/node_extent_accessor.h
- src/crimson/os/seastore/onode_manager/staged-fltree/node_layout.h
- src/crimson/os/seastore/onode_manager/staged-fltree/tree_utils.h
- src/crimson/os/seastore/seastore.cc
- src/crimson/os/seastore/seastore.h
- src/crimson/os/seastore/transaction_manager.cc
- src/crimson/osd/heartbeat.cc
- src/crimson/osd/osd.cc
- src/crimson/osd/osd_meta.cc
- src/crimson/osd/osd_operations/scrub_events.cc
- src/crimson/osd/replicated_recovery_backend.cc
- src/crimson/tools/perf_crimson_msgr.cc
- src/crimson/tools/store_nbd/fs_driver.cc
- src/osd/PGLog.cc
- src/test/crimson/seastore/onode_tree/test_staged_fltree.cc
- src/test/crimson/seastore/test_btree_lba_manager.cc
- src/test/crimson/seastore/test_seastore.cc
- src/test/crimson/seastore/test_seastore_cache.cc
- src/test/crimson/seastore/test_seastore_journal.cc
- src/test/crimson/test_alien_echo.cc
- src/test/crimson/test_interruptible_future.cc
- src/test/crimson/test_messenger.cc
- src/test/crimson/test_messenger_thrash.cc
- src/test/crimson/test_socket.cc
Fixes: https://tracker.ceph.com/issues/64556 …
> crimson/common/errorator: disallow void-returning error handlers

- src/test/common/test_back_trace.cc
if ASan is enabled, backtrace() returns one more frame, so we need to skip one more frame when testing backtrace facility. this change addresses the following test failure:
```
[ RUN      ] BackTrace.Basic
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/common/test_back_trace.cc:43: Failure
Value of: std::regex_match(lines[lineno], e)
Actual: false
Expected: true
[  FAILED  ] BackTrace.Basic (5 ms)
```
it only manifests itself when testing with ASan enabled.
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatc …
> test/common/test_back_trace: skip one more frame when testing w/ ASan

- src/crimson/os/seastore/btree/fixed_kv_btree.h
- src/crimson/os/seastore/transaction_manager.cc
> crimson/os/seastore/transaction_manager: correct the offset of the data copied from the original extents

- qa/workunits/windows/py_tests/internal/exception.py
- qa/workunits/windows/py_tests/internal/rbd_image.py
- qa/workunits/windows/py_tests/internal/task_group.py
- qa/workunits/windows/py_tests/internal/tracer.py
- qa/workunits/windows/py_tests/internal/utils.py
- qa/workunits/windows/py_tests/rbd_wnbd/service_restart_test.py
- qa/workunits/windows/py_tests/rbd_wnbd/stress_test.py
- qa/workunits/windows/run-tests.ps1
We're adding a test that:
* maps a configurable number of images
* runs a specified test - we're reusing the ones from stress_test, making just a few minor changes to allow running the same test   multiple times
* restarts the ceph-rbd Windows service
* waits for the images to be reconnected and refreshes the mount information
* reruns the test
* repeats the above workflow for a specified number of times, reusing the same images
This test ensures that:
* mounted images are still available after a service restart
* drive letters are retained
* the image content is retained
* there are no race conditions when connecting or disconnecting a large number of images in parallel
* the driver is capable of mapping a specified number of images simultaneously
While at it, we're splitting the …
> qa: add ceph-rbd windows service restart test 

- src/common/options/rbd.yaml.in
"number of seconds to blocklist - set to 0 for OSD default" in the description of rbd_blocklist_expire_seconds refers to the value that is controlled by mon_osd_blocklist_default_expire. …
> common/options: link to mon_osd_blocklist_default_expire from RBD

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/dashboard-promqls.enum.ts
Fixes: https://tracker.ceph.com/issues/66058 …
> mgr/dashboard: Fix host count per cluster and total hosts count on multi-cluster overview page

- doc/cephfs/fs-volumes.rst
Edit doc/cephfs/fs-volumes to the section "Cloning Snapshots" (but not including the section "Cloning Snapshots".
Follows https://github.com/ceph/ceph/pull/57415 …
> doc/cephfs: edit fs-volumes.rst (2 of x)

- doc/cephfs/fs-volumes.rst
Edit doc/cephfs/fs-volumes to the section "Cloning Snapshots" (but not including the section "Cloning Snapshots".
Follows https://github.com/ceph/ceph/pull/57415
(cherry picked from commit 0a3981a011d5e768ab8a5782884283b6650af28a) …
> reef: doc/cephfs: edit fs-volumes.rst (2 of x)

- doc/cephfs/fs-volumes.rst
Add a note to the "Subvolume quiesce" section that says that the information in the section applies only to the Squid and later releases of Ceph. This is included here so that I don't overwrite the Reef and Quincy documentation with irrelevant information, and so that I don't overwrite the Squid information with blank space where the "Subvolume quiesce" section should be. …
> doc/cephfs: Squid and later - subvolume quiesce

- doc/cephfs/fs-volumes.rst
Edit doc/cephfs/fs-volumes to the section "Cloning Snapshots" (but not including the section "Cloning Snapshots").
Follows https://github.com/ceph/ceph/pull/57415
(cherry picked from commit 0a3981a011d5e768ab8a5782884283b6650af28a) …
> squid: doc/cephfs: edit fs-volumes.rst (2 of x)

- .github/milestone.yml
add squid for github actions to automatically add milestone to backports
- …
> .github/milestone.yml: add squid

- src/pybind/mgr/k8sevents/module.py
- src/pybind/mgr/requirements.txt
backport tracker: https://tracker.ceph.com/issues/66092
backport https://github.com/ceph/ceph/pull/57253
- Tracker …
> squid: mgr/k8sevents: update V1Events to CoreV1Events

- src/crimson/os/seastore/btree/fixed_kv_btree.h
- src/crimson/os/seastore/btree/fixed_kv_node.h
- src/crimson/os/seastore/cache.cc
- src/crimson/os/seastore/cached_extent.cc
- src/crimson/os/seastore/cached_extent.h
- src/crimson/os/seastore/lba_manager/btree/lba_btree_node.h
- src/crimson/os/seastore/root_block.cc
- src/crimson/os/seastore/root_block.h
- src/crimson/os/seastore/transaction_manager.cc
- src/test/crimson/seastore/test_block.h
> crimson/os/seastore: lba pointer consolidation

- monitoring/ceph-mixin/requirements-alerts.txt
- monitoring/ceph-mixin/requirements-lint.txt
- monitoring/ceph-mixin/tests_dashboards/requirements.txt
Move to 6.0.1 to overcome https://github.com/yaml/pyyaml/issues/601
Fixes: https://tracker.ceph.com/issues/63591
- …
> install-deps: Update Pyyaml version

- src/msg/async/AsyncMessenger.cc
(cherry picked from commit 36fc1f353436193a0b3e95af27edbf0e6cc4f4c2)
Fixes (Backport): https://tracker.ceph.com/issues/63022
Original ticket: https://tracker.ceph.com/issues/62395
Original PR: https://github.com/ceph/ceph/pull/52930
<details> …
> reef: msg/AsyncMessenger: re-evaluate the stop condition when woken up in 'wait()'

- src/common/Formatter.cc
- src/common/Formatter.h
See: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-five
Pulled out of #57215 …
> common/Formatter: trivial cons/des should be default

- src/crimson/osd/osd_operation.h
- src/crimson/osd/pg_recovery.cc
backport of https://github.com/ceph/ceph/pull/56806
> squid: crimson/osd/pg_recovery: backoff if the recovery/backfill is deferred

- doc/dev/release-process.rst
Support added to the release scripts (from ceph-build.git) to work for ceph-iscsi, so 'project' must be passed to these scripts, and will appear in the prerelease pathnames.  See also https://github.com/ceph/ceph-build/pull/2243 and
https://github.com/ceph/ceph-container/pull/2210
(cherry picked from commit 7e64c6386e3571c657e0889ef12449e5b43f751a) …
> reef: doc/dev/release-process.rst: note new 'project' arguments

- qa/workunits/windows/py_tests/internal/exception.py
- qa/workunits/windows/py_tests/internal/rbd_image.py
- qa/workunits/windows/py_tests/internal/task_group.py
- qa/workunits/windows/py_tests/internal/tracer.py
- qa/workunits/windows/py_tests/internal/utils.py
- qa/workunits/windows/py_tests/rbd_wnbd/service_restart_test.py
- qa/workunits/windows/py_tests/rbd_wnbd/stress_test.py
- qa/workunits/windows/run-tests.ps1
backport tracker: https://tracker.ceph.com/issues/66204
---
backport of https://github.com/ceph/ceph/pull/52560
parent tracker: https://tracker.ceph.com/issues/66202
> squid: qa: add ceph-rbd windows service restart test 

- src/crimson/os/seastore/cache.cc
> crimson/os/seastore: fix compile error in release build

- src/script/ceph-backport.sh
> script/ceph-backport: update Ceph PR id

- doc/cephfs/fs-volumes.rst
Edit the section "Pinning Subvolumes and Subvolume Groups" in doc/cephfs/fs-volumes.rst. This is merely a grammar edit.
(cherry picked from commit b319ead00e17a3a6d734e305454c8cfc403619ea) …
> reef: doc/cephfs: edit "Pinning Subvolumes..."

- doc/cephfs/fs-volumes.rst
Rewrite two sentences so that they are unambgiuously in the indicative mood and not, as they previously seemed, in the imperative mood. …
> doc/cephfs: disambiguate two sentences

- src/rgw/rgw_kafka.cc
fixes: https://tracker.ceph.com/issues/66017
as well as other simplifications:
* do not store temporary configuration in the connection object. just use as a local variable
* do not create a connection without a producer
other improvements:
* copy to a local list before publishing
* convert internal error codes to errno
<details>
- …
> rgw/kafka: do not destroy the connection on errors

- doc/man/8/ceph.rst
> doc/man: add missing long option switches

- PendingReleaseNotes
Updating the PendingReleaseNotes with the major changes in dashboard for squid
- …
> doc: Update pendingreleasenotes for dashboard

- doc/man/8/ceph.rst
(cherry picked from commit ad710c1f9395917310046a810176fca37b286fab) …
> squid: doc/man: add missing long option switches

- doc/man/8/ceph.rst
(cherry picked from commit ad710c1f9395917310046a810176fca37b286fab) …
> reef: doc/man: add missing long option switches

- doc/dev/perf_counters.rst
Add target links to perf_counters.rst, to remedy the failure to backport the docs changes in https://github.com/ceph/ceph/pull/53003. (https://github.com/ceph/ceph/pull/53003 mixed code and docs changes, so it is understandable why the backport was not achieved back in October, when the merge to main occurred.) …
> reef: doc/dev: add target links to perf_counters.rst

- doc/cephfs/index.rst
Add a link to doc/cephfs/index.rst to cause "Metrics" to appear in the left pane.
- …
> reef: doc/cephfs: add metrics to left pane

- PendingReleaseNotes
(cherry picked from commit ef3e179b99f5816f5ecd55844337f54ef563a93f)
- …
> squid: doc: Update pendingreleasenotes for dashboard

- src/pybind/mgr/dashboard/controllers/health.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/layouts/workbench-layout/workbench-layout.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/health.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
Fixes: https://tracker.ceph.com/issues/65643
[screen-capture (42).webm](https://github.com/ceph/ceph/assets/106810838/a3a1f488-0b11-4135-be81-30de87d89719) …
> mgr/dashboard: fix readonly landingpage

- src/tools/cephfs/first-damage.py
> tools/first-damage: Don't skip stray directory object

- doc/dev/perf_counters.rst
Add a note to the "perf counter" section of doc/dev/perf_counters.rst that explains that this feature was introduced in the Reef release of Ceph. This note will prevent us from accidentally backporting perf-counter-related PRs to Quincy. …
> doc/dev: add note about intro of perf counters

- src/crimson/os/seastore/random_block_manager/avlallocator.cc
> crimson/os/seastore/rbm/avlallocator: return enough regions when request size is greater than max_alloc_size

- PendingReleaseNotes
- doc/cephfs/cephfs-journal-tool.rst
- doc/cephfs/disaster-recovery-experts.rst
- qa/tasks/cephfs/test_damage.py
- qa/tasks/cephfs/test_data_scan.py
- qa/tasks/cephfs/test_flush.py
- qa/tasks/cephfs/test_forward_scrub.py
- qa/tasks/cephfs/test_journal_migration.py
- qa/tasks/cephfs/test_journal_repair.py
- qa/tasks/cephfs/test_recovery_pool.py
- qa/workunits/fs/damage/test-first-damage.sh
- qa/workunits/suites/cephfs_journal_tool_smoke.sh
- src/tools/cephfs/JournalTool.cc
- src/tools/cephfs/first-damage.py
> cephfs-journal-tool: Add preventive measures to avoid fs corruption

- src/test/rgw/bucket_notification/test_bn.py
> test/rgw/notification: verify network access to http server

- doc/dev/perf_counters.rst
Add a note to the "perf counter" section of doc/dev/perf_counters.rst that explains that this feature was introduced in the Reef release of Ceph. This note will prevent us from accidentally backporting perf-counter-related PRs to Quincy.
(cherry picked from commit 55e41bc679aeee9119dc815b456bb76880f61ea2) …
> squid: doc/dev: add note about intro of perf counters

- doc/dev/perf_counters.rst
Add a note to the "perf counter" section of doc/dev/perf_counters.rst that explains that this feature was introduced in the Reef release of Ceph. This note will prevent us from accidentally backporting perf-counter-related PRs to Quincy.
(cherry picked from commit 55e41bc679aeee9119dc815b456bb76880f61ea2) …
> reef: doc/dev: add note about intro of perf counters

- doc/cephfs/mantle.rst
Improve the structure and grammar of the front matter in the doc/cephfs/mantle.rst file. …
> doc/cephfs: edit front matter in mantle.rst

- doc/cephfs/mantle.rst
Improve the structure and grammar of the front matter in the doc/cephfs/mantle.rst file.
(cherry picked from commit 559d4849ecd6f93b5812f3d8d0448115c5b5beab) …
> quincy: doc/cephfs: edit front matter in mantle.rst

- doc/cephfs/mantle.rst
Improve the structure and grammar of the front matter in the doc/cephfs/mantle.rst file.
(cherry picked from commit 559d4849ecd6f93b5812f3d8d0448115c5b5beab) …
> reef: doc/cephfs: edit front matter in mantle.rst

- doc/cephfs/mantle.rst
Improve the structure and grammar of the front matter in the doc/cephfs/mantle.rst file.
(cherry picked from commit 559d4849ecd6f93b5812f3d8d0448115c5b5beab) …
> squid: doc/cephfs: edit front matter in mantle.rst

- src/pybind/mgr/dashboard/controllers/multi_cluster.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-form/multi-cluster-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/multi-cluster.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
fixes: https://tracker.ceph.com/issues/66303 …
> mgr/dashboard: read cert from in-memory file

- src/rgw/driver/d4n/rgw_sal_d4n.cc
- src/rgw/driver/daos/rgw_sal_daos.cc
- src/rgw/driver/daos/rgw_sal_daos.h
- src/rgw/driver/motr/rgw_sal_motr.cc
- src/rgw/driver/motr/rgw_sal_motr.h
- src/rgw/driver/posix/rgw_sal_posix.cc
- src/rgw/driver/posix/rgw_sal_posix.h
- src/rgw/driver/rados/rgw_bucket.cc
- src/rgw/driver/rados/rgw_cr_rados.cc
- src/rgw/driver/rados/rgw_lc_tier.cc
- src/rgw/driver/rados/rgw_rados.h
- src/rgw/driver/rados/rgw_sal_rados.cc
- src/rgw/driver/rados/rgw_sal_rados.h
- src/rgw/rgw_admin.cc
- src/rgw/rgw_lc.cc
- src/rgw/rgw_lua_request.cc
- src/rgw/rgw_op.cc
- src/rgw/rgw_rest_s3.cc
- src/rgw/rgw_rest_swift.cc
- src/rgw/rgw_sal.cc
- src/rgw/rgw_sal.h
- src/rgw/rgw_sal_dbstore.cc
- src/rgw/rgw_sal_dbstore.h
- src/rgw/rgw_sal_filter.cc
- src/rgw/rgw_sal_filter.h
- src/rgw/rgw_sal_store.h
> RGW: Remove RGWObjState and get_obj_state()/put_obj_state() from the SAL API

- doc/cephfs/mantle.rst
Improve the English in the vstart warning in doc/cephfs/mantle.rst.
- Component …
> doc/cephfs: edit vstart warning text

- doc/cephfs/mantle.rst
Improve the English in the vstart warning in doc/cephfs/mantle.rst.
(cherry picked from commit 9ce7f9bd6c006ede6e1d563f4273376e2dbc1d03) …
> reef: doc/cephfs: edit vstart warning text

- doc/cephfs/mantle.rst
Improve the English in the vstart warning in doc/cephfs/mantle.rst.
(cherry picked from commit 9ce7f9bd6c006ede6e1d563f4273376e2dbc1d03) …
> squid: doc/cephfs: edit vstart warning text

- doc/start/beginners-guide.rst
- doc/start/intro.rst
Add a Beginner's Guide to docs.ceph.com. …
> doc/start: Add Beginner's Guide

- doc/start/beginners-guide.rst
- doc/start/intro.rst
Add a Beginner's Guide to docs.ceph.com.
(cherry picked from commit 91aafc6a7f72c105fbf3aa8419863e931d5b9e00) …
> squid: doc/start: Add Beginner's Guide

- doc/start/beginners-guide.rst
- doc/start/intro.rst
Add a Beginner's Guide to docs.ceph.com.
(cherry picked from commit 91aafc6a7f72c105fbf3aa8419863e931d5b9e00) …
> reef: doc/start: Add Beginner's Guide

- doc/start/beginners-guide.rst
- doc/start/intro.rst
Add a Beginner's Guide to docs.ceph.com.
(cherry picked from commit 91aafc6a7f72c105fbf3aa8419863e931d5b9e00) …
> quincy: doc/start: Add Beginner's Guide

- doc/rados/troubleshooting/troubleshooting-mon.rst
Add the command for stopping a monitor to the procedure that explains how to inject a monmap into a monitor.
Zac of the future: cf. 05 Aug 2023. …
> doc/rados: add stop monitor command

- doc/cephfs/mantle.rst
Improve the English in the vstart warning in doc/cephfs/mantle.rst.
(cherry picked from commit 9ce7f9bd6c006ede6e1d563f4273376e2dbc1d03) …
> quincy: doc/cephfs: edit vstart warning text

- src/test/rgw/bucket_notification/test_bn.py
> RGW\bucket notification tests: end-point agnostic + refactoring

- doc/start/beginners-guide.rst
Make some improvements to the basic text of the Beginner's Guide.
(cherry picked from commit f484a156bed655909617f4e351b692d7a23d0e87) …
> squid: doc/start: Edit Beginner's Guide

- doc/start/beginners-guide.rst
Make some improvements to the basic text of the Beginner's Guide.
(cherry picked from commit f484a156bed655909617f4e351b692d7a23d0e87) …
> reef: doc/start: Edit Beginner's Guide

- doc/start/beginners-guide.rst
Make some improvements to the basic text of the Beginner's Guide.
(cherry picked from commit f484a156bed655909617f4e351b692d7a23d0e87) …
> quincy: doc/start: Edit Beginner's Guide

- doc/rados/troubleshooting/troubleshooting-mon.rst
Add the command for stopping a monitor to the procedure that explains how to inject a monmap into a monitor.
Zac of the future: cf. 05 Aug 2023.
(cherry picked from commit c032188d66539a78ab0e4de2a5f5fc4329927bf6) …
> squid: doc/rados: add stop monitor command

- doc/rados/troubleshooting/troubleshooting-mon.rst
Add the command for stopping a monitor to the procedure that explains how to inject a monmap into a monitor.
Zac of the future: cf. 05 Aug 2023.
(cherry picked from commit c032188d66539a78ab0e4de2a5f5fc4329927bf6) …
> reef: doc/rados: add stop monitor command

- do_cmake.sh
> do_cmake.sh: Use shallow submodule clones

- doc/monitoring/index.rst
Based on the new metrics introduced in rgw https://github.com/ceph/ceph/pull/54623/ , updating the metrics name in rgw metrics monitoring doc
Fixes: https://tracker.ceph.com/issues/66242 …
> doc/monitoring: update rgw metrics names

- doc/start/get-involved.rst
Replace "http" with "https" in doc/start/get-involved.rst.
This commit is, in a way, a repeat of
https://github.com/ceph/ceph/pull/57213/
(1c5383b91bd7dbfa9670c6485fcc5ff28b79f40d), which targeted the Reef branch instead of the main branch. When this commit has been merged and backported, I will close https://github.com/ceph/ceph/pull/57213/.
I am listing Casey Cain here as the co-author, but he is in fact the true author of this change. …
> doc/start: s/http/https/ in links

- src/common/options/rgw.yaml.in
> doc: correct typo (ma npage -> man page)

- doc/start/get-involved.rst
Replace "http" with "https" in doc/start/get-involved.rst.
This commit is, in a way, a repeat of
https://github.com/ceph/ceph/pull/57213/
(1c5383b91bd7dbfa9670c6485fcc5ff28b79f40d), which targeted the Reef branch instead of the main branch. When this commit has been merged and backported, I will close https://github.com/ceph/ceph/pull/57213/.
I am listing Casey Cain here as the co-author, but he is in fact the true author of this change.
Co-authored-by: Casey Cain <ccain@linuxfoundation.org>
(cherry picked from commit 922f23f0f30da856a661376527f413dc9424382d) …
> squid: doc/start: s/http/https/ in links

- doc/start/get-involved.rst
Replace "http" with "https" in doc/start/get-involved.rst.
This commit is, in a way, a repeat of
https://github.com/ceph/ceph/pull/57213/
(1c5383b91bd7dbfa9670c6485fcc5ff28b79f40d), which targeted the Reef branch instead of the main branch. When this commit has been merged and backported, I will close https://github.com/ceph/ceph/pull/57213/.
I am listing Casey Cain here as the co-author, but he is in fact the true author of this change.
Co-authored-by: Casey Cain <ccain@linuxfoundation.org>
(cherry picked from commit 922f23f0f30da856a661376527f413dc9424382d) …
> reef: doc/start: s/http/https/ in links

- doc/start/get-involved.rst
Replace "http" with "https" in doc/start/get-involved.rst.
This commit is, in a way, a repeat of
https://github.com/ceph/ceph/pull/57213/
(1c5383b91bd7dbfa9670c6485fcc5ff28b79f40d), which targeted the Reef branch instead of the main branch. When this commit has been merged and backported, I will close https://github.com/ceph/ceph/pull/57213/.
I am listing Casey Cain here as the co-author, but he is in fact the true author of this change.
Co-authored-by: Casey Cain <ccain@linuxfoundation.org>
(cherry picked from commit 922f23f0f30da856a661376527f413dc9424382d) …
> quincy: doc/start: s/http/https/ in links

- doc/dev/perf_counters.rst
Note that Labeled Perf Counters were introduced in Reef.
Fixes: https://github.com/ceph/ceph/pull/57753#discussion_r1626483732 …
> doc/dev: origin of Labeled Perf Counters

- src/common/options/rgw.yaml.in
(cherry picked from commit 4769493887e9f99f990122135d7cab6caee27f71) …
> quincy: doc: correct typo

- doc/index.rst
- doc/start/index.rst
Change the filename "doc/start/intro.rst" to "doc/start/index.rst" so that Sphinx finds the root filename for the "/start" directory in the default location. …
> doc/start: s/intro.rst/index.rst/

- doc/index.rst
- doc/start/index.rst
Change the filename "doc/start/intro.rst" to "doc/start/index.rst" so that Sphinx finds the root filename for the "/start" directory in the default location.
(cherry picked from commit 84ce2212e87a4b6b2416eeab7e8e1718ae3ce87b) …
> reef: doc/start: s/intro.rst/index.rst/

- src/common/ceph_strings.cc
- src/osd/OSDMap.cc
This is reef backport of #57776.
Backport tracker: https://tracker.ceph.com/issues/66299.
Parent tracker: https://tracker.ceph.com/issues/61948. …
> reef: mon, osd, *: expose upmap-primary in OSDMap::get_features() 

- src/rgw/driver/rados/rgw_sal_rados.cc
- src/test/rgw/rgw_multi/tests.py
fixes https://tracker.ceph.com/issues/64022 …
> rgw/multisite: allow PutACL replication.

- doc/index.rst
- doc/start/index.rst
Change the filename "doc/start/intro.rst" to "doc/start/index.rst" so that Sphinx finds the root filename for the "/start" directory in the default location.
(cherry picked from commit 84ce2212e87a4b6b2416eeab7e8e1718ae3ce87b) …
> squid: doc/start: s/intro.rst/index.rst/

- src/tools/cephfs/first-damage.py
Make CEPH_NOSNAP int64 and also add the
'first == CEPH_NOSNAP' corruption check seperately. …
> tools/first-damage: Make CEPH_NOSNAP int64

- doc/dev/perf_counters.rst
Note that Labeled Perf Counters were introduced in Reef.
Fixes: https://github.com/ceph/ceph/pull/57753#discussion_r1626483732
(cherry picked from commit 36e09fb6894dcec56224d483d36a7315b8d19d60) …
> reef: doc/dev: origin of Labeled Perf Counters

- doc/dev/perf_counters.rst
Note that Labeled Perf Counters were introduced in Reef.
Fixes: https://github.com/ceph/ceph/pull/57753#discussion_r1626483732
(cherry picked from commit 36e09fb6894dcec56224d483d36a7315b8d19d60) …
> squid: doc/dev: origin of Labeled Perf Counters

- src/mds/CDir.cc
These should just init with properly forwarded arguments.
<details>
</details>
> mds: avoid use of swap to initialize

- qa/cephfs/conf/mon.yaml
- qa/suites/fs/cephadm/renamevolume/conf
- qa/suites/fs/mirror-ha/conf
- qa/suites/fs/mirror/conf
- qa/suites/fs/top/conf
> qa: disable mon_warn_on_pool_no_app in fs suite

- src/common/options/rgw.yaml.in
(cherry picked from commit 4769493887e9f99f990122135d7cab6caee27f71) …
> squid: doc: correct typo

- src/common/options/rgw.yaml.in
(cherry picked from commit 4769493887e9f99f990122135d7cab6caee27f71) …
> reef: doc: correct typo

- doc/dev/developer_guide/dash-devel.rst
- make-dist
- src/pybind/mgr/dashboard/frontend/CMakeLists.txt
Fixes: https://tracker.ceph.com/issues/66249
Update nodejs to current LTS version v20.13.1 …
> mgr/dashboard: update node js version  

- qa/suites/rgw/notifications/tasks/http/0-install.yaml
- qa/suites/rgw/notifications/tasks/http/supported-distros
- qa/suites/rgw/notifications/tasks/http/test_http.yaml
- qa/tasks/notification_tests.py
> RGW|BN: make http tests run on a seperate task

- src/mds/MDSRank.cc
Pulled out of https://github.com/ceph/ceph/pull/48130
- …
> mds: add debug message when conf changes are processed

- src/pybind/mgr/dashboard/controllers/pool.py
- src/pybind/mgr/dashboard/controllers/rbd_mirroring.py
- src/pybind/mgr/dashboard/frontend/cypress/e2e/pools/pools.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/pools/pools.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.ts
- src/pybind/mgr/dashboard/openapi.yaml
Fixes: https://tracker.ceph.com/issues/66267
[Screencast from 2024-05-29 10-09-24.webm](https://github.com/ceph/ceph/assets/66050535/2190f4b7-71dd-419b-8f9c-e26fab6744df) …
> mgr/dashboard: provide option to enable pool based mirroring mode while creating a pool

- qa/cephfs/conf/client.yaml
- qa/cephfs/conf/mds.yaml
- qa/cephfs/conf/mon.yaml
- qa/cephfs/conf/osd.yaml
- qa/cephfs/overrides/frag.yaml
- qa/cephfs/overrides/prefetch_entire_dirfrags/no.yaml
- qa/cephfs/overrides/prefetch_entire_dirfrags/yes.yaml
- qa/suites/fs/functional/tasks/fragment.yaml
- qa/suites/fs/libcephfs/tasks/ino_release_cb.yaml
- qa/suites/fs/workload/tasks/3-snaps/yes.yaml
- qa/tasks/ceph.py
- qa/tasks/ceph_manager.py
- qa/tasks/ceph_test_case.py
- qa/tasks/cephadm.py
- qa/tasks/cephfs/mount.py
- qa/tasks/cephfs/test_exports.py
- qa/tasks/cephfs/test_fragment.py
- qa/tasks/vstart_runner.py
- src/common/options/mds.yaml.in
- src/mds/CDir.cc
- src/mds/CDir.h
- src/mds/CInode.cc
- src/mds/MDBalancer.cc
- src/mds/MDBalancer.h
- src/mds/MDCache.cc
- src/mds/MDCache.h
- src/mds/MDSRank.cc
- src/mds/mdstypes.h
Successor to #35178
<details>
- …
> qa: add killpoint testing for dirfrags

- doc/glossary.rst
Add "OpenStack Swift" and "Swift" entries to the glossary.
- …
> doc/glossary.rst: add "OpenStack Swift" and "Swift"

- doc/glossary.rst
Add "OpenStack Swift" and "Swift" entries to the glossary.
(cherry picked from commit b2d413ee9db1d68392f29db148a7bc2e87a7b419) …
> quincy: doc/glossary.rst: add "OpenStack Swift" and "Swift"

- doc/glossary.rst
Add "OpenStack Swift" and "Swift" entries to the glossary.
(cherry picked from commit b2d413ee9db1d68392f29db148a7bc2e87a7b419) …
> reef: doc/glossary.rst: add "OpenStack Swift" and "Swift"

- src/crimson/common/operation.h
- src/crimson/osd/osd_operations/client_request.cc
- src/crimson/osd/osd_operations/client_request.h
Fixes: https://tracker.ceph.com/issues/65632 …
> crimson/common/operation: detach blockers from blocking events when they are destroyed

- src/crimson/osd/pg_backend.cc
> crimson/osd: clamp reads to object size and bring full read trimming

- src/crimson/osd/pg_backend.cc
Fixes: https://tracker.ceph.com/issues/65773 …
> crimson/osd/pg_backend: only create new onode when it doesn't exist

- src/crimson/osd/recovery_backend.cc
- src/crimson/osd/recovery_backend.h
Fixes: https://tracker.ceph.com/issues/65894 …
> crimson/osd/recovery_backend: change recovery waiters' promises into optional ones

- src/crimson/osd/replicated_backend.cc
Fixes: https://tracker.ceph.com/issues/66002 …
> crimson/osd/replicated_backend: no need to set_rollback_to for repops

- src/crimson/osd/pg.cc
Fixes: https://tracker.ceph.com/issues/65972 …
> crimson/osd/pg: hold PGs' references to the last minute of snap trim events executions

- src/crimson/osd/ops_executer.cc
- src/crimson/osd/ops_executer.h
- src/crimson/osd/pg.h
- src/test/librados/snapshots_cxx.cc
fixes: https://tracker.ceph.com/issues/65663 …
> crimson/osd/ops_executer: LIST_SNAPS only on CEPH_SNAPDIR

- src/crimson/osd/pg_shard_manager.h
Fixing the following compilation issue:
```
/home/xuxuehan/src/ceph/src/crimson/osd/pg_shard_manager.h:236:7: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
236 |       );
|       ^
/home/xuxuehan/src/ceph/src/crimson/osd/pg_shard_manager.h:236:7: note: remove ‘std::move’ call
```
Signed-off-by: Xuehan Xu [xuxuehan@qianxin.com](mailto:xuxuehan@qianxin.com) …
> crimson/osd/pg_shard_manager: remove the unnecessary "std::move" call

- src/crimson/osd/osd_operations/logmissing_request.cc
- src/crimson/osd/osd_operations/peering_event.cc
- src/crimson/osd/osd_operations/recovery_subrequest.cc
- src/crimson/osd/osd_operations/replicated_request.cc
Fixes: https://tracker.ceph.com/issues/66374 …
> crimson/osd/osd_operations: correct connection pipelines for osd operations

- doc/glossary.rst
Add "OpenStack Swift" and "Swift" entries to the glossary.
(cherry picked from commit b2d413ee9db1d68392f29db148a7bc2e87a7b419) …
> squid: doc/glossary.rst: add "OpenStack Swift" and "Swift"

- src/common/options/global.yaml.in
Add inline-literal RST markup (``) (double backticks) around variable names in src/common/options/global.yaml.in.
This follows https://github.com/ceph/ceph/pull/57887.
(cherry picked from commit 6cdf9439c777ecac8915189a8e38a718f5013f7a) …
> reef: doc/src: add inline literals (``) to variables

- src/crimson/osd/pg.h
This is used to unblock localized/balanced reads issued when the pg is not active yet.
Fixes: https://tracker.ceph.com/issues/65806 …
> crimson/osd/pg: trigger wait_for_active_blocker on replica osds when the activate event is committed

- doc/rados/troubleshooting/troubleshooting-mon.rst
Add an explanation of leader-peon conditions that obtain when the cluster is in the "HEALTH_OK" state. Previously, the text discussed these two monitor states only in the context of a health detail entry.
This improvement to the documentation was suggested on the [ceph-users] email list by Joel Davidow. This email, an absolute model of user engagement with an upstream project, can be reviewed here: https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/message/KF67F5TXFSSTPXV7EKL6JKLA5KZQDLDQ/
I will list Joel Davidow here as the co-author for the sake of more expediently getting this change into the documentation, but though he is listed as the co-author, he is the true author.
Co-authored-by: Joel Davidow <jdavidow@nso.edu>
(cherry picked …
> reef: doc/rados: improve leader/peon monitor explanation

- doc/rados/troubleshooting/troubleshooting-mon.rst
Add an explanation of leader-peon conditions that obtain when the cluster is in the "HEALTH_OK" state. Previously, the text discussed these two monitor states only in the context of a health detail entry.
This improvement to the documentation was suggested on the [ceph-users] email list by Joel Davidow. This email, an absolute model of user engagement with an upstream project, can be reviewed here: https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/message/KF67F5TXFSSTPXV7EKL6JKLA5KZQDLDQ/
I will list Joel Davidow here as the co-author for the sake of more expediently getting this change into the documentation, but though he is listed as the co-author, he is the true author.
Co-authored-by: Joel Davidow <jdavidow@nso.edu>
(cherry picked …
> squid: doc/rados: improve leader/peon monitor explanation

- doc/glossary.rst
Add "S3" entry to the glossary. …
> doc/glossary: Add "S3"

- doc/glossary.rst
Add "S3" entry to the glossary.
(cherry picked from commit be6d0645c40431e8312244019c0331e4076bd5f2) …
> squid: doc/glossary: Add "S3"

- doc/glossary.rst
Add "S3" entry to the glossary.
(cherry picked from commit be6d0645c40431e8312244019c0331e4076bd5f2) …
> reef: doc/glossary: Add "S3"

- doc/glossary.rst
Add "S3" entry to the glossary.
(cherry picked from commit be6d0645c40431e8312244019c0331e4076bd5f2) …
> quincy: doc/glossary: Add "S3"

- src/pybind/mgr/smb/tests/test_smb.py
source_type should be resource …
> test/ smb: modify source_type to fix run-tox-mgr failed

- src/include/rbd/librbd.h
- src/include/rbd/librbd.hpp
- src/librbd/api/Group.cc
- src/librbd/api/Group.h
- src/librbd/librbd.cc
- src/pybind/rbd/c_rbd.pxd
- src/pybind/rbd/mock_rbd.pxi
- src/pybind/rbd/rbd.pyx
- src/test/cli/rbd/help.t
- src/test/librbd/test_Groups.cc
- src/test/pybind/test_rbd.py
- src/tools/rbd/action/Group.cc
fixes: https://tracker.ceph.com/issues/66010 …
> rbd: add group info command to output group id

- PendingReleaseNotes
- src/pybind/rbd/rbd.pyx
- src/test/pybind/test_rbd.py
> pybind/rbd: parse access and modify timestamps in UTC

- src/tools/cephfs_mirror/FSMirror.h
- src/tools/cephfs_mirror/InstanceWatcher.cc
- src/tools/cephfs_mirror/InstanceWatcher.h
- src/tools/cephfs_mirror/Mirror.cc
- src/tools/cephfs_mirror/MirrorWatcher.cc
- src/tools/cephfs_mirror/MirrorWatcher.h
- src/tools/cephfs_mirror/PeerReplayer.cc
- src/tools/cephfs_mirror/PeerReplayer.h
- src/tools/cephfs_mirror/Types.h
Fixes: https://tracker.ceph.com/issues/62265
(cherry picked from commit 7f0e7feea52c2917a6c234fffce1e5d9ff8ef791)
- …
> squid: cephfs-mirror: use monotonic clock

- src/ceph-volume/ceph_volume/devices/lvm/migrate.py
Fixes: https://tracker.ceph.com/issues/66315
Please enter the commit message for your changes. Lines starting …
> ceph-volume: do source devices zapping if they're detached.

- doc/rados/operations/index.rst
Add "pg-states" and "pg-concepts" to the left tree pane on docs.ceph.com.
This commit has been made in response to a request from the upstream made in https://pad.ceph.com/p/Report_Documentation_Bugs. …
> doc/rados: add pg-states and pg-concepts to tree

- qa/tasks/rados.py
Fixes: https://tracker.ceph.com/issues/66321 …
> qa/rados: don't pass --max_attr_len to ceph_test_rados unconditionally

- PendingReleaseNotes
- qa/tasks/mgr/dashboard/test_rbd.py
- qa/workunits/rbd/cli_generic.sh
- qa/workunits/rbd/rbd_mirror_helpers.sh
- src/include/rbd/librbd.h
- src/include/rbd/librbd.hpp
- src/librbd/api/Snapshot.cc
- src/librbd/api/Snapshot.h
- src/librbd/image/CloneRequest.cc
- src/librbd/internal.cc
- src/librbd/internal.h
- src/librbd/librbd.cc
- src/pybind/rbd/c_rbd.pxd
- src/pybind/rbd/mock_rbd.pxi
- src/pybind/rbd/rbd.pyx
- src/test/cli/rbd/help.t
- src/test/pybind/test_rbd.py
- src/test/rbd_mirror/test_ImageDeleter.cc
- src/tools/rbd/ArgumentTypes.cc
- src/tools/rbd/ArgumentTypes.h
- src/tools/rbd/action/Children.cc
- src/tools/rbd/action/Clone.cc
- src/tools/rbd/action/Device.cc
- src/tools/rbd/action/Snap.cc
- src/tracing/librbd.tp
> librbd: allow cloning from non-user snapshots

- qa/suites/fs/thrash/workloads/ranks/1.yaml
- qa/suites/fs/thrash/workloads/tasks/1-thrash/exports.yaml
Fixes: https://tracker.ceph.com/issues/18154 …
> qa: add export thrashing to fs:thrash

- doc/rados/operations/index.rst
Add "pg-states" and "pg-concepts" to the left tree pane on docs.ceph.com.
This commit has been made in response to a request from the upstream made in https://pad.ceph.com/p/Report_Documentation_Bugs.
(cherry picked from commit 0629f47faf73a5b88adbeceaf022ee23111bae7d) …
> quincy: doc/rados: add pg-states and pg-concepts to tree

- doc/rados/operations/index.rst
Add "pg-states" and "pg-concepts" to the left tree pane on docs.ceph.com.
This commit has been made in response to a request from the upstream made in https://pad.ceph.com/p/Report_Documentation_Bugs.
(cherry picked from commit 0629f47faf73a5b88adbeceaf022ee23111bae7d) …
> reef: doc/rados: add pg-states and pg-concepts to tree

- doc/rados/operations/index.rst
Add "pg-states" and "pg-concepts" to the left tree pane on docs.ceph.com.
This commit has been made in response to a request from the upstream made in https://pad.ceph.com/p/Report_Documentation_Bugs.
(cherry picked from commit 0629f47faf73a5b88adbeceaf022ee23111bae7d) …
> squid: doc/rados: add pg-states and pg-concepts to tree

- src/crimson/osd/osd_operations/client_request.cc
Fixes: https://tracker.ceph.com/issues/65872 …
> crimson/osd/osd_operations/client_request: check "can_serve_replica_reads" before getting obc

- src/crimson/os/seastore/random_block_manager/avlallocator.cc
backport of https://github.com/ceph/ceph/pull/57694
> squid: crimson/os/seastore/rbm/avlallocator: return enough regions when request size is greater than max_alloc_size

- src/vstart.sh
Add two new command line options to
1. set number of alien threads,` --crimson-alien-num-threads `, other than the default value(6),
2. set number of cpu cores for alien threads,  `--crimson-alien-num-cores` -- the default is to use all the other cores in the system not used by crimson/seastar.
This is an example of the added functionality, and the verification via inspection at the debug output, as well as via ps below
```
-o session_timeout=10000 --bluestore --crimson --redirect-output --bluestore-devs /dev/sdc --crimson-smp 4\
--crimson-alien-num-threads 2 --crimson-alien-num-cores 1
DEBUG 2024-04-15 15:34:41,816 [shard 0:main] monc - set_mon_vals crimson_alien_op_num_threads = 2
DEBUG 2024-04-15 15:34:41,816 [shard 0:main] monc - set_mon_vals crimson_alien_thread_cpu_cores = 4-4 <- …
```
> vstart.sh: add options to set number of alien threads, and number of cpu cores for alien threads

- src/crimson/os/seastore/cache.h
- src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.cc
- src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.h
- src/crimson/os/seastore/transaction_manager.h
> crimson/os/seastore/lba_manager: do batch mapping allocs when remapping multiple mappings

- src/pybind/mgr/cephadm/configchecks.py
- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/tests/test_cephadm.py
Backport https://github.com/ceph/ceph/pull/58062 to squid to unblock `make check`.
> squid: mgr/cephadm: fix flake8 test failures

- src/crimson/os/seastore/object_data_handler.cc
backport of https://github.com/ceph/ceph/pull/57432
> squid: crimson/os/seastore/object_data_handler: cleanup read()

- src/crimson/osd/osd_operations/background_recovery.cc
- src/crimson/osd/pg.cc
- src/crimson/osd/pg.h
- src/crimson/osd/pg_recovery.cc
Fixes: https://tracker.ceph.com/issues/65696 …
> crimson/osd/pg_recovery: skip unfound objects when recovering the primary

- doc/dev/developer_guide/essentials.rst
Remove the docs.ceph.com list of team leads, and link to the list of leads on ceph.io.
Fixes: https://tracker.ceph.com/issues/66392 …
> doc/dev: link to ceph.io leads list

- doc/dev/developer_guide/essentials.rst
Remove the docs.ceph.com list of team leads, and link to the list of leads on ceph.io.
Fixes: https://tracker.ceph.com/issues/66392
(cherry picked from commit 5134aeb78bb1d9d956442333ad372e1f397ff7b3) …
> reef: doc/dev: link to ceph.io leads list

- doc/dev/developer_guide/essentials.rst
Remove the docs.ceph.com list of team leads, and link to the list of leads on ceph.io.
Fixes: https://tracker.ceph.com/issues/66392
(cherry picked from commit 5134aeb78bb1d9d956442333ad372e1f397ff7b3) …
> quincy: doc/dev: link to ceph.io leads list

- src/ceph-volume/ceph_volume/tests/devices/lvm/test_listing.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_migrate.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_zap.py
- src/ceph-volume/ceph_volume/tests/objectstore/test_lvmbluestore.py
ae5ef432845 broke some unit tests.
This commit fixes that.
> ceph-volume: fix TestMigrate tests

- src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/services.po.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/orchestrator/05-services.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/service.interface.ts
backport tracker: https://tracker.ceph.com/issues/66345
---
backport of https://github.com/ceph/ceph/pull/57134
parent tracker: https://tracker.ceph.com/issues/65681
> squid: mgr/dashboard: add smb service management support

- doc/dev/crimson/crimson.rst
> doc/dev/crimson: CPU cores allocation

- doc/rbd/nvmeof-requirements.rst
- doc/rbd/nvmeof-target-configure.rst
> doc/rbd: fix typos in NVMe-oF docs

- doc/architecture.rst
Add clarifying language for data availability vs integrity for EC shards. Availability requires min size `K+1`.
- …
> doc: clarify availability vs integrity

- src/crimson/os/seastore/extent_placement_manager.cc
- src/crimson/os/seastore/extent_placement_manager.h
- src/crimson/os/seastore/journal/record_submitter.cc
- src/crimson/os/seastore/seastore_types.cc
- src/crimson/os/seastore/seastore_types.h
https://github.com/ceph/ceph/pull/57788/files#r1625414185
- …
> crimson/os/seastore: add writer level stats to RBM

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard/health/health.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/shared/ceph-shared.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/shared/health-checks/health-checks.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/shared/health-checks/health-checks.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/shared/health-checks/health-checks.component.ts
Show which daemons failed in CEPHADM_FAILED_DAEMON healthcheck
Fixes: https://tracker.ceph.com/issues/63792
<details>
- …
> mgr/dashboard: Show which daemons failed in CEPHADM_FAILED_DAEMON healthcheck

- doc/dev/developer_guide/essentials.rst
Remove the docs.ceph.com list of team leads, and link to the list of leads on ceph.io.
Fixes: https://tracker.ceph.com/issues/66392
(cherry picked from commit 5134aeb78bb1d9d956442333ad372e1f397ff7b3) …
> squid: doc/dev: link to ceph.io leads list

- doc/dev/crimson/crimson.rst
CPU cores allocation and
add crimson-smp vstart flag
(cherry picked from commit 35d257bfaa5ed7cf91c8a8b523ed4494fdd27667) …
> squid: doc/dev/crimson: CPU cores allocation

- doc/architecture.rst
(cherry picked from commit 3888cf77075eceb079b1d5a8ce19092d12fd82bd)
- Component …
> reef: doc: clarify availability vs integrity

- doc/architecture.rst
(cherry picked from commit 3888cf77075eceb079b1d5a8ce19092d12fd82bd)
- Component …
> quincy: doc: clarify availability vs integrity

- src/cls/rbd/cls_rbd_types.h
- src/librbd/api/Group.cc
- src/test/librados_test_stub/TestMemIoCtxImpl.cc
- src/test/librbd/test_Groups.cc
- src/test/pybind/test_rbd.py
> librbd: disallow group snap rollback if memberships don't match

- src/librbd/api/DiffIterate.cc
- src/test/librbd/test_librbd.cc
> librbd: diff-iterate shouldn't crash on an empty byte range

- qa/suites/rbd/basic/tasks/rbd_python_api_tests_old_format.yaml
- qa/suites/rbd/device/workloads/diff-continuous-krbd.yaml
- qa/suites/rbd/device/workloads/diff-continuous-nbd.yaml
- qa/suites/rbd/librbd/workloads/python_api_tests.yaml
- qa/suites/rbd/librbd/workloads/python_api_tests_with_defaults.yaml
- qa/suites/rbd/librbd/workloads/python_api_tests_with_journaling.yaml
- qa/suites/rbd/mirror/workloads/compare-mirror-image-alternate-primary-krbd.yaml
- qa/suites/rbd/mirror/workloads/compare-mirror-image-alternate-primary-nbd.yaml
- qa/suites/rbd/mirror/workloads/compare-mirror-images-krbd.yaml
- qa/suites/rbd/mirror/workloads/compare-mirror-images-nbd.yaml
- qa/suites/rbd/valgrind/workloads/python_api_tests.yaml
- qa/suites/rbd/valgrind/workloads/python_api_tests_with_defaults.yaml
- qa/suites/rbd/valgrind/workloads/python_api_tests_with_journaling.yaml
backport tracker: https://tracker.ceph.com/issues/66262
---
backport of https://github.com/ceph/ceph/pull/57729
parent tracker: https://tracker.ceph.com/issues/66232
> squid: qa/suites/rbd: override extra_system_packages directly on install task

- doc/architecture.rst
(cherry picked from commit 3888cf77075eceb079b1d5a8ce19092d12fd82bd)
- Component …
> squid: doc: clarify availability vs integrity

- doc/start/beginners-guide.rst
Add the Redmine Ceph Wiki to the Ceph Beginner's Guide.
- …
> doc/start: add wiki to Beginner's Guide

- qa/tasks/qemu.py
See: https://sentry.ceph.com/share/issue/21ed88d705854238bdafbf6711e795ee/ 
They're not floats. …
> qa/tasks/qemu: Fix OS version comparison

- src/cephadm/cephadm.py
Backport of https://github.com/ceph/ceph/pull/56817
<details>
</details>
> squid: cephadm: check if file exists when passing `--apply_spec`

- src/pybind/mgr/cephadm/upgrade.py
backport tracker: https://tracker.ceph.com/issues/66429
---
backport of https://github.com/ceph/ceph/pull/57292
parent tracker: https://tracker.ceph.com/issues/65809
> squid: mgr/cephadm: make SMB and NVMEoF upgrade last in staggered upgrade

- src/script/backport-create-issue
> script/backport-create-issue: update tag custom field

- doc/rados/operations/stretch-mode.rst
Add a method for defining a CRUSH rule that returns the actual value of the total available size. …
> doc/rados: add stretch_rule workaround

- src/common/options/global.yaml.in
changed to inadvisable on line 4997 …
> doc/src: invadvisable is not a word

- .github/labeler.yml
> .github/labeler: add script label to script changes

- doc/rbd/nvmeof-requirements.rst
- doc/rbd/nvmeof-target-configure.rst
(cherry picked from commit 0cd415c53b49b2e9168df488340dab91d4c6badc) …
> reef: doc/rbd: fix typos in NVMe-oF docs.

- doc/rbd/nvmeof-requirements.rst
- doc/rbd/nvmeof-target-configure.rst
(cherry picked from commit 0cd415c53b49b2e9168df488340dab91d4c6badc) …
> squid: doc/rbd: fix typos in NVMe-oF docs.

- src/common/options/global.yaml.in
changed to inadvisable on line 4997
Signed-off-by: Doug Whitfield <douglasawh@gmail.com>
(cherry picked from commit fb4a5d09e11b75a2f38c42c489af7e6f148916a7) …
> squid: doc/src: invadvisable is not a word

- src/common/options/global.yaml.in
changed to inadvisable on line 4997
Signed-off-by: Doug Whitfield <douglasawh@gmail.com>
(cherry picked from commit fb4a5d09e11b75a2f38c42c489af7e6f148916a7) …
> quincy: doc/src: invadvisable is not a word

- doc/rados/troubleshooting/troubleshooting-mon.rst
Incorporate Anthony D'Atri's suggestions in
https://github.com/ceph/ceph/pull/58057
(cherry picked from commit 2e999a26ef2d3c12d81bd54c187a6225a5fcd7a6) …
> squid: doc/rados: followup to PR#58057

- doc/rados/troubleshooting/troubleshooting-mon.rst
Incorporate Anthony D'Atri's suggestions in
https://github.com/ceph/ceph/pull/58057
(cherry picked from commit 2e999a26ef2d3c12d81bd54c187a6225a5fcd7a6) …
> reef: doc/rados: followup to PR#58057

- doc/rados/troubleshooting/troubleshooting-mon.rst
Incorporate Anthony D'Atri's suggestions in
https://github.com/ceph/ceph/pull/58057
(cherry picked from commit 2e999a26ef2d3c12d81bd54c187a6225a5fcd7a6) …
> quincy: doc/rados: followup to PR#58057

- doc/rados/troubleshooting/troubleshooting-mon.rst
Incorporate Anthony D'Atri's suggestions in
https://github.com/ceph/ceph/pull/58057 …
> doc/rados: followup to PR#58057

- doc/rados/operations/stretch-mode.rst
Add a method for defining a CRUSH rule that returns the actual value of the total available size.
(cherry picked from commit 007385a3ef05bd92e006fc7d6aba3fbb51792ef7) …
> quincy: doc/rados: add stretch_rule workaround

- doc/rados/operations/stretch-mode.rst
Add a method for defining a CRUSH rule that returns the actual value of the total available size.
(cherry picked from commit 007385a3ef05bd92e006fc7d6aba3fbb51792ef7) …
> reef: doc/rados: add stretch_rule workaround

- doc/rados/operations/stretch-mode.rst
Add a method for defining a CRUSH rule that returns the actual value of the total available size.
(cherry picked from commit 007385a3ef05bd92e006fc7d6aba3fbb51792ef7) …
> squid: doc/rados: add stretch_rule workaround

- src/pybind/mgr/dashboard/controllers/rbd.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-feature.interface.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form-edit-request.model.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rbd.py
Fixes: https://tracker.ceph.com/issues/66348
Signed-off-by: Aashish Sharma  aasharma@redhat.com …
> mgr/dashboard: Block -> Images -> Create form improvements

- src/crimson/osd/object_context.h
Fixes: https://tracker.ceph.com/issues/66308
<details>
</details>
> crimson: fix ObjectContext::_with_lock to only unlock if lock is taken

- src/common/options/global.yaml.in
changed to inadvisable on line 4997
Signed-off-by: Doug Whitfield <douglasawh@gmail.com>
(cherry picked from commit fb4a5d09e11b75a2f38c42c489af7e6f148916a7) …
> reef: doc/src: invadvisable is not a word

- doc/start/beginners-guide.rst
Add two links to Sage Weil's overview talks about Ceph.
- …
> doc/start: add links to Beginner's Guide

- src/mds/QuiesceDb.h
- src/mds/QuiesceDbManager.h
Fixes: https://tracker.ceph.com/issues/66449
<details>
</details>
> mds: initialize epoch for quiescedb

- PendingReleaseNotes
- doc/rados/operations/user-management.rst
- qa/workunits/cephtool/test.sh
- src/mon/AuthMonitor.cc
- src/mon/MonCommands.h
> mon/AuthMonitor: provide command to rotate the key for a user credential

- src/common/TrackedOp.cc
If an op is marked as nowarn then it won't be counted as the slow requests, but currently it will count the initiated time when iterating the inflight ops.
For example:
[WRN] : 1 slow requests, 1 included below; oldest blocked for > 38.764892 secs
[WRN] : slow request 33.875059 seconds old, received at 2024-06-17T14:14:34.228261+0000: client_request(client.78109915:11369251 mkdir #0x1008ecedea2/chk-89588 2024-06-17T14:14:34.097825+0000 caller_uid=1002960000, caller_gid=0{0,1002960000,}) currently failed to wrlock, waiting
The oldest blocked request is 38.764892 old, but the oldest slow request reported is 33.875059 old.
This will fix the old commit from https://github.com/ceph/ceph/pull/21715.
Fixes: https://tracker.ceph.com/issues/66557 …
> common/TrackedOp: do not count the ops marked as nowarn

- doc/start/beginners-guide.rst
Add two links to Sage Weil's overview talks about Ceph.
(cherry picked from commit 785020f212504cdbf374e0d3ca843fd92309de98) …
> squid: doc/start: add links to Beginner's Guide

- doc/start/beginners-guide.rst
Add two links to Sage Weil's overview talks about Ceph.
(cherry picked from commit 785020f212504cdbf374e0d3ca843fd92309de98) …
> reef: doc/start: add links to Beginner's Guide

- doc/start/beginners-guide.rst
Add two links to Sage Weil's overview talks about Ceph.
(cherry picked from commit 785020f212504cdbf374e0d3ca843fd92309de98) …
> quincy: doc/start: add links to Beginner's Guide

- src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/create-cluster.po.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/osds.po.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/common/urls.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster-review.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster-review.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-form/osd-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-form/osd-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/auth/login/login.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/auth/login/login.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/osd.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/icons.enum.ts
Fixes: https://tracker.ceph.com/issues/66344
https://github.com/ceph/ceph/assets/30312016/12db1407-1b90-478a-a354-eb077797d0a4 …
> mgr/dashboard: Expand Cluster improvements

- src/pybind/mgr/dashboard/constraints.txt
> mgr/dashboard: bump cheroot to > 10.0

- qa/tasks/cephfs/test_snap_schedules.py
Fixes: https://tracker.ceph.com/issues/65564
Introduced-by: 006c68f4920 …
> qa: cleanup snapshots before subvolume delete

- src/mds/FSMap.cc
- src/mds/MDCache.cc
- src/mds/MDSRank.cc
Fixes: https://tracker.ceph.com/issues/65094
<details>
</details>
> mds: fix bug and error handling of mds STATE_STARTING

- qa/suites/fs/functional/tasks/admin.yaml
- qa/tasks/cephfs/test_admin.py
Fixes: https://tracker.ceph.com/issues/65497 …
> qa: enhance per-client labelled perf counters test

- qa/tasks/mgr/dashboard/test_rgw.py
- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rgw_client.py
- src/pybind/mgr/dashboard/tests/__init__.py
- src/pybind/mgr/dashboard/tests/test_rgw.py
> mgr/dashboard: get and update bucket replication policies

- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.ts
Fixes: https://tracker.ceph.com/issues/66538 …
> mgr/dashboard: fix (multi) cluster switcher disappearance after carbon UI shell

- doc/rados/operations/stretch-mode.rst
Credit Prashant D for creating the stretch-mode workaround procedure for retrieving the correct size of datacenters.
Follows: https://github.com/ceph/ceph/pull/58109 …
> doc/rados: credit Prashant for a procedure

- src/pybind/mgr/dashboard/frontend/src/app/shared/api/multi-cluster.service.ts
> mgr/dashboard: fix token status being polled continously

- doc/rados/operations/stretch-mode.rst
Credit Prashant D for creating the stretch-mode workaround procedure for retrieving the correct size of datacenters.
Follows: https://github.com/ceph/ceph/pull/58109
(cherry picked from commit 2e777cb4f8bd682b807b97074f930826aa902db9) …
> squid: doc/rados: credit Prashant for a procedure

- doc/rados/operations/stretch-mode.rst
Credit Prashant D for creating the stretch-mode workaround procedure for retrieving the correct size of datacenters.
Follows: https://github.com/ceph/ceph/pull/58109
(cherry picked from commit 2e777cb4f8bd682b807b97074f930826aa902db9) …
> reef: doc/rados: credit Prashant for a procedure

- doc/rados/operations/stretch-mode.rst
Credit Prashant D for creating the stretch-mode workaround procedure for retrieving the correct size of datacenters.
Follows: https://github.com/ceph/ceph/pull/58109
(cherry picked from commit 2e777cb4f8bd682b807b97074f930826aa902db9) …
> quincy: doc/rados: credit Prashant for a procedure

- src/test/admin_socket.cc
fixes: https://tracker.ceph.com/issues/66638 …
> test/admin_socket: increase slack

- qa/suites/orch/cephadm/smoke/start.yaml
- qa/suites/orch/cephadm/workunits/task/test_monitoring_stack_basic.yaml
- qa/suites/orch/cephadm/workunits/task/test_rgw_multisite.yaml
Few tests that deploying osds that causing the test fail beacuse of warning during the period time that the osds restart. adding to ignore list.
Fixes: https://tracker.ceph.com/issues/64872 …
> suites: adding ignore list for stray daemon

- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
Regression from https://github.com/ceph/ceph/pull/56658
Fixes: https://tracker.ceph.com/issues/66697
- Tracker …
> mgr/dashboard: fix nav urls for cephfs and nfs 

- doc/rados/api/librados-intro.rst
In this example librados2-devel only install C header files on fedora 40, therefore I added libradospp-devel to the command to include C++ header files. …
> doc/rados: update how to install c++ header files

- doc/dev/encoding.rst
(cherry picked from commit 9f43c67a639958a13fef198ffe62cf5241f1f53c) …
> quincy: doc/dev: Fix typos in encoding.rst

- qa/suites/fs/upgrade/featureful_client/old_client/README
- qa/suites/fs/upgrade/featureful_client/upgraded_client/README
- qa/suites/fs/upgrade/mds_upgrade_sequence/README
- qa/suites/fs/upgrade/mds_upgrade_sequence/tasks/0-from/squid.yaml
- qa/suites/fs/upgrade/nofs/README
- qa/suites/fs/upgrade/upgraded_client/README
> qa: manual upgrade from n-1/n-2 to main

- .gitmodules
- CMakeLists.txt
- cmake/modules/BuildBoost.cmake
- cmake/modules/FindBoost.cmake
- install-deps.sh
- make-dist
- src/mds/BoostUrlImpl.cc
- src/mds/CMakeLists.txt
- src/rgw/CMakeLists.txt
- src/test/mds/CMakeLists.txt
- win32_deps_build.sh
Needed to fix some bugs in Boost.Asio, particularly one related to `asio::spawn`.
- …
> build: Bump boost version to 1.85

- doc/dev/encoding.rst
(cherry picked from commit 9f43c67a639958a13fef198ffe62cf5241f1f53c) …
> squid: doc/dev: Fix typos in encoding.rst

- doc/dev/encoding.rst
(cherry picked from commit 9f43c67a639958a13fef198ffe62cf5241f1f53c) …
> reef: doc/dev: Fix typos in encoding.rst

- doc/rados/api/librados-intro.rst
In this example librados2-devel only install C header files on fedora 40, therefore I added libradospp-devel to the command to include C++ header files.
Signed-off-by: Pere Diaz Bou <pere-altea@hotmail.com>
(cherry picked from commit 7e87441601db2379488fab62e900cd834086f26d) …
> squid: doc/rados: update how to install c++ header files

- doc/rados/api/librados-intro.rst
In this example librados2-devel only install C header files on fedora 40, therefore I added libradospp-devel to the command to include C++ header files.
Signed-off-by: Pere Diaz Bou <pere-altea@hotmail.com>
(cherry picked from commit 7e87441601db2379488fab62e900cd834086f26d) …
> reef: doc/rados: update how to install c++ header files

- src/librbd/api/DiffIterate.cc
- src/test/librbd/test_librbd.cc
> librbd: make diff-iterate in fast-diff mode aware of encryption

- src/test/librbd/test_Groups.cc
> test/librbd: avoid caching effects TestGroup.add_snapshot{,PP}

- src/cls/rgw/cls_rgw.cc
- src/cls/rgw/cls_rgw_client.cc
- src/cls/rgw/cls_rgw_client.h
- src/cls/rgw/cls_rgw_ops.h
- src/cls/rgw/cls_rgw_types.h
- src/rgw/driver/rados/rgw_bucket.cc
- src/rgw/driver/rados/rgw_cr_rados.cc
- src/rgw/driver/rados/rgw_data_sync.cc
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
- src/rgw/driver/rados/rgw_sal_rados.cc
- src/rgw/rgw_op.cc
- src/rgw/rgw_sal.h
- src/test/rgw/rgw_multi/tests.py
Fixes [ tracker.ceph.com/issues/55179](url) …
> src/rgw: Deleting an object with null version fix

- doc/cephfs/fs-volumes.rst
Incorporate Anthony's suggestion in
https://github.com/ceph/ceph/pull/57567#discussion_r1607016050 into doc/cephfs/fs-volumes.rst. …
> doc/cephfs: take Anthony's suggestion

- doc/cephfs/fs-volumes.rst
Incorporate Anthony's suggestion in
https://github.com/ceph/ceph/pull/57567#discussion_r1607016050 into doc/cephfs/fs-volumes.rst.
(cherry picked from commit 7a78dda0a92339db27359f91f0cb081703e2e7f9) …
> squid: doc/cephfs: take Anthony's suggestion

- doc/cephfs/fs-volumes.rst
Incorporate Anthony's suggestion in
https://github.com/ceph/ceph/pull/57567#discussion_r1607016050 into doc/cephfs/fs-volumes.rst.
(cherry picked from commit 7a78dda0a92339db27359f91f0cb081703e2e7f9) …
> reef: doc/cephfs: take Anthony's suggestion

- doc/cephfs/fs-volumes.rst
Incorporate Anthony's suggestion in
https://github.com/ceph/ceph/pull/57567#discussion_r1607016050 into doc/cephfs/fs-volumes.rst.
(cherry picked from commit 7a78dda0a92339db27359f91f0cb081703e2e7f9) …
> quincy: doc/cephfs: take Anthony's suggestion

- doc/start/hardware-recommendations.rst
Restore a missing "i" in "overprovisioning" in
doc/start/hardware-recommendations.rst. …
> doc/start: s/overprovsioning/overprovisioning/

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.e2e.spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.po.ts
- src/pybind/mgr/dashboard/frontend/jest.config.cjs
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/cell-template.enum.ts
- src/pybind/mgr/dashboard/openapi.yaml
Fixes: https://tracker.ceph.com/issues/66576
https://github.com/ceph/ceph/assets/30312016/341d5461-b9d8-430f-81af-78811c4f1765 …
> mgr/dashborad: RGW sync policy

- doc/start/hardware-recommendations.rst
(cherry picked from commit a8b27af84910d324023a37e616f42d6d3faa4ecf) …
> quincy: doc/start: fix wording & syntax

- doc/start/hardware-recommendations.rst
(cherry picked from commit a8b27af84910d324023a37e616f42d6d3faa4ecf) …
> reef: doc/start: fix wording & syntax

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/pipes.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/xml.pipe.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/xml.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/json-to-xml.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/json-to-xml.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/text-area-json-formatter.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/text-area-xml-formatter.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/text-area-xml-formatter.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rgw_client.py
- src/pybind/mgr/dashboard/tests/test_rgw_client.py
Fixes: https://tracker.ceph.com/issues/50327
[screen-capture (1).webm](https://github.com/ceph/ceph/assets/106810838/a0f377c3-7939-4e9b-b735-0502c94c2aff) …
> mgr/dashboard: add RGW lifecycle management

- src/pybind/mgr/orchestrator/module.py
Fixes: https://tracker.ceph.com/issues/66574
Signed-off-by: teng jie <tengjie5@asiainfo.com>
mgr: excute cmd 'ceph orch apply osd' returned without error info
Fixes: https://tracker.ceph.com/issues/66574
Signed-off-by: teng jie <tengjie5@asiainfo.com> …
> mgr: excute cmd 'ceph orch apply osd' returned without error info

- doc/start/os-recommendations.rst
Remove information so that it is clear that Centos 8 will no longer be supported by Ceph. …
> doc/start: remove mention of Centos 8 support

- src/pybind/mgr/cephadm/agent.py
- src/pybind/mgr/cephadm/inventory.py
- src/pybind/mgr/cephadm/migrations.py
- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/serve.py
- src/pybind/mgr/cephadm/service_discovery.py
- src/pybind/mgr/cephadm/services/monitoring.py
- src/pybind/mgr/cephadm/tests/test_cephadm.py
- src/pybind/mgr/cephadm/tests/test_migration.py
- src/pybind/mgr/cephadm/tests/test_services.py
- src/pybind/mgr/orchestrator/_interface.py
- src/pybind/mgr/orchestrator/module.py
> mgr/cephadm: Add Cert/Key Store 

- src/rgw/rgw_pubsub.cc
Fixes: https://tracker.ceph.com/issues/65861 …
> notifications: report an error when persistent queue deletion failed

- doc/start/os-recommendations.rst
Remove information so that it is clear that Centos 8 will no longer be supported by Ceph.
(cherry picked from commit 6b149e4f6ab2ac716e73f42b0d6c67482a768da9) …
> squid: doc/start: remove mention of Centos 8 support

- doc/start/os-recommendations.rst
Remove information so that it is clear that Centos 8 will no longer be supported by Ceph.
(cherry picked from commit 6b149e4f6ab2ac716e73f42b0d6c67482a768da9) …
> reef: doc/start: remove mention of Centos 8 support

- qa/crontab/teuthology-cronjobs
The lab can't keep up with current nightly load; reduce fs runs on main branch to once a month but raise priority so we have a reliable baseline. …
> qa/crontab: convert fs main run to monthly at higher priority

- doc/start/os-recommendations.rst
Remove information so that it is clear that Centos 8 will no longer be supported by Ceph.
(cherry picked from commit 6b149e4f6ab2ac716e73f42b0d6c67482a768da9) …
> quincy: doc/start: remove mention of Centos 8 support

- qa/workunits/rbd/rbd_mirror_helpers.sh
Corrected paths and added missing spaces. …
> qa/workunits/rbd: minor rbd_mirror_helpers.sh fixes

- src/test/objectstore/allocsim/ops_replayer.cc
For now this is a simple single threaded replayer with a 64 iodepth where we load all ops from a file and try to push them in order as soon as we can. …
> test/allocsim: osd op scraper replayer

- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/buckets.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.ts
backport tracker: https://tracker.ceph.com/issues/66486
---
backport of https://github.com/ceph/ceph/pull/57698
parent tracker: https://tracker.ceph.com/issues/66221
> squid: mgr/dashboard: add dueTime to rgw bucket validator

- src/pybind/mgr/dashboard/controllers/multi_cluster.py
- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/module.py
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/orchestrator.py
- src/pybind/mgr/dashboard/services/rgw_client.py
- src/pybind/mgr/dashboard/services/service.py
- src/pybind/mgr/dashboard/tests/test_rgw_client.py
Fixes: https://tracker.ceph.com/issues/66227
https://github.com/ceph/ceph/assets/66050535/675b67c3-b9f9-4d3c-9242-ae716d9eb5ee …
> mgr/dashboard: add api for rgw multisite replication wizard

- qa/suites/rgw/notifications/tasks/kafka/test_kafka.yaml
- qa/tasks/notification_tests.py
- src/test/rgw/bucket_notification/test_bn.py
> RGW|BN : change endpoint for http failing tests

- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.e2e.spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-multisite.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-form/rgw-multisite-sync-policy-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-form/rgw-multisite-sync-policy-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-form/rgw-multisite-sync-policy-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
sync group create functionality
Fixes: https://tracker.ceph.com/issues/66798
CRUD ops demo:
https://github.com/ceph/ceph/assets/30312016/4b05417e-e52f-4a05-963b-1e4ecf165081 …
> mgr/dashboard: RGW sync policy crud operations

- src/crimson/os/seastore/onode.cc
- src/crimson/os/seastore/onode.h
- src/crimson/os/seastore/onode_manager/staged-fltree/fltree_onode_manager.cc
- src/crimson/os/seastore/onode_manager/staged-fltree/fltree_onode_manager.h
- src/crimson/os/seastore/onode_manager/staged-fltree/tree.h
- src/crimson/os/seastore/onode_manager/staged-fltree/value.h
- src/test/crimson/seastore/onode_tree/test_value.h
- src/test/crimson/seastore/test_object_data_handler.cc
So that we can see the onodes' identities in the logs
- Tracker …
> crimson/os/seastore/onode: add hobject_t into Onode

- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/buckets.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/buckets.po.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/configuration.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/configuration.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-bucket-encryption.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-config-details/rgw-config-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-config-details/rgw-config-details.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-config-details/rgw-config-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-config-modal/rgw-config-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-config-modal/rgw-config-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-configuration-page/rgw-configuration-page.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-configuration-page/rgw-configuration-page.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-configuration-page/rgw-configuration-page.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/rgw-encryption-config-keys.ts
- src/pybind/mgr/dashboard/services/ceph_service.py
Fixes: https://tracker.ceph.com/issues/66543
https://github.com/ceph/ceph/assets/66050535/0febb211-b944-499d-9fbd-6285d735c953 …
> mgr/dashboard: add a new configuration page in side nav bar  Object > Configuration

- src/test/objectstore/CMakeLists.txt
- src/test/objectstore/allocsim/CMakeLists.txt
- src/test/objectstore/allocsim/ops_replayer.cc
```
fedora :: pere/scrapper-replayer/build 130 » ./bin/replayer -h
All options:
Options:
-h [ --help ]                 produce help message
-i arg (=input.txt)           Input file (output of op_scraper.py)
--ceph-conf arg (=ceph.conf)  Path to ceph conf
--io-depth arg (=64)          I/O depth
--parser-threads arg (=16)    Number of parser threads
--worker-threads arg (=16)    Number of I/O worker threads
--pool arg (=test_pool)       Pool to use for I/O
``` …
> test/allocsim: ops scrapper arg parsing

- doc/cephfs/multimds.rst
> doc/cephfs: fix typo

- src/librbd/api/DiffIterate.cc
- src/test/librbd/test_librbd.cc
backport tracker: https://tracker.ceph.com/issues/66743
---
backport of https://github.com/ceph/ceph/pull/58201
parent tracker: https://tracker.ceph.com/issues/66570
> reef: librbd: make diff-iterate in fast-diff mode aware of encryption

- src/test/objectstore/allocsim/ops_replayer.cc
Fix import from rados inside src/test/objectstore/allocism/ops_replayer.cc to fix following error during Ceph build:
```
fatal error: rados/buffer_fwd.h: No such file or directory
```
Commit reference: https://github.com/ceph/ceph/commit/3f4ffe0703e8482d2784102ea3a3cb57b8364673 …
> src/test/objectstore/allocism/ops_replayer.cc: fix rados import

- src/pybind/mgr/dashboard/controllers/cephfs.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.ts
Fixes: https://tracker.ceph.com/issues/66718
[Screencast from 2024-07-04 12-48-02.webm](https://github.com/ceph/ceph/assets/23611106/bfe593e9-739c-40d1-9d13-29a7c7f9df11) …
> mgr/dashboard: nfs export enhancement for CEPHFS

- doc/man/8/ceph-bluestore-tool.rst
- src/blk/BlockDevice.h
- src/blk/kernel/KernelDevice.cc
- src/os/bluestore/BlueFS.cc
- src/os/bluestore/BlueFS.h
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/os/bluestore/bluestore_tool.cc
Add command 'trim' to ceph-bluestore-tool. …
> tools/bluestore: Add command 'trim' to ceph-bluestore-tool

- src/os/bluestore/BlueStore.cc
In case of corrupted data invalid iterator could be dereferenced. 
Fixes: https://tracker.ceph.com/issues/66361
- …
> os/bluestore: Fix ExtentDecoderPartial::_consume_new_blob

- src/test/objectstore/store_test.cc
Introduce TEST_RANDOM_SEED env variable to help with debugging synthetic tests.
- …
> os/bluestore: store_test reproducible tests with seeds

- src/os/bluestore/BlueStore.cc
- src/test/objectstore/store_test.cc
Parent tracker: https://tracker.ceph.com/issues/64443
Backport tracker: https://tracker.ceph.com/issues/64648
Backports: https://github.com/ceph/ceph/pull/55594
(cherry picked from commit ac4a48c4be1791a32cfd2cf3cf5af51eee581d21) …
> squid: test/store_test: fix DeferredWrite test when prefer_deferred_size=0

- doc/cephfs/multimds.rst
blanacer -> balancer
Signed-off-by: spdfnet <32593931+spdfnet@users.noreply.github.com>
(cherry picked from commit d94f90b757189e269882523178a401cd4411a946) …
> squid: doc/cephfs: fix typo

- doc/cephfs/multimds.rst
blanacer -> balancer
Signed-off-by: spdfnet <32593931+spdfnet@users.noreply.github.com>
(cherry picked from commit d94f90b757189e269882523178a401cd4411a946) …
> reef: doc/cephfs: fix typo

- doc/cephadm/services/osd.rst
The current link goes to `cephadm/services/rados/operations/devices` which is a 404, it instead needs to be `rados/operations/devices/`.
(cherry picked from commit d1a7cc4978adacd4e11df2d3e0886b191b118cc1) …
> squid: doc: Correct link to "Device management"

- doc/cephadm/services/osd.rst
The current link goes to `cephadm/services/rados/operations/devices` which is a 404, it instead needs to be `rados/operations/devices/`.
(cherry picked from commit d1a7cc4978adacd4e11df2d3e0886b191b118cc1) …
> reef: doc: Correct link to "Device management"

- doc/cephadm/services/osd.rst
The current link goes to `cephadm/services/rados/operations/devices` which is a 404, it instead needs to be `rados/operations/devices/`.
(cherry picked from commit d1a7cc4978adacd4e11df2d3e0886b191b118cc1) …
> quincy: doc: Correct link to "Device management"

- qa/standalone/erasure-code/test-erasure-eio.sh
- qa/tasks/rados.py
- src/common/options/osd.yaml.in
- src/erasure-code/ErasureCode.cc
- src/erasure-code/ErasureCode.h
- src/erasure-code/ErasureCodeInterface.h
- src/erasure-code/clay/ErasureCodeClay.cc
- src/osd/ECBackend.cc
- src/osd/ECBackend.h
- src/osd/ECCommon.cc
- src/osd/ECCommon.h
- src/osd/ECUtil.cc
- src/osd/ECUtil.h
- src/osd/PGBackend.h
- src/osd/PrimaryLogPG.cc
- src/osd/ReplicatedBackend.cc
- src/osd/ReplicatedBackend.h
- src/test/erasure-code/TestErasureCodeClay.cc
- src/test/erasure-code/TestErasureCodeExample.cc
- src/test/erasure-code/TestErasureCodeJerasure.cc
- src/test/osd/CMakeLists.txt
- src/test/osd/Object.cc
- src/test/osd/Object.h
- src/test/osd/RadosModel.h
- src/test/osd/TestECBackend.cc
- src/test/osd/TestRados.cc
- src/tools/erasure-code/ceph-erasure-code-tool.cc
This PR is a resurrection of #52746 rebased on top of https://github.com/ceph/ceph/pull/54930. …
> osd: EC Partial Stripe Reads (Retry of #23138 and #52746)

- src/test/objectstore/store_test.cc
Created ch = CollectionHandle was not reset, causing valgrind & other problems.
- …
> test/objectstore: Fix DeferredReplayTest

- src/cephadm/cephadmlib/templating.py
That version is what's currently being shipped in
RPMs on rhel9 …
> cephadm: make cephadm compatible with jinja2 2.11.3

- src/pybind/mgr/rgw/module.py
- src/python-common/ceph/rgw/rgwam_core.py
Fixes https://tracker.ceph.com/issues/66750 …
> mgr/rgw: Adding a retry config while calling zone_create()

- qa/suites/orch/cephadm/upgrade/1-start-distro/1-start-centos_9.stream-reef.yaml
- qa/suites/orch/cephadm/upgrade/1-start-distro/1-start-centos_9.stream-squid.yaml
- qa/suites/orch/cephadm/upgrade/1-start-distro/1-start-ubuntu_22.04-reef.yaml
- qa/suites/orch/cephadm/upgrade/1-start-distro/1-start-ubuntu_22.04-squid.yaml
Since main is now what will become the T release,
we only need to be testing upgrades from reef and
squid. Upgrades from quincy won't be valid once
we've branched off …
> qa/cephadm: change upgrade test start point to reef/squid

- qa/tasks/mgr/dashboard/test_crush_rule.py
- src/pybind/mgr/dashboard/controllers/crush_rule.py
- src/pybind/mgr/dashboard/openapi.yaml
Fixes: https://tracker.ceph.com/issues/66490
Signed-off-by: sunlan <sunlan@asiainfo.com> …
> mgr/dashboard: add restful api for creating crush rule with type of 'erasure'

- qa/suites/crimson-rados/basic/tasks/rados_python.yaml
Fixes: https://tracker.ceph.com/issues/66382 …
> suite/crimson: enable stats tests

- qa/tasks/mgr/dashboard/test_rgw.py
- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-daemon.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-daemon-list/rgw-daemon-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rgw_client.py
- src/pybind/mgr/dashboard/tests/__init__.py
- src/pybind/mgr/dashboard/tests/test_rgw.py
backport tracker: https://tracker.ceph.com/issues/66254
https://tracker.ceph.com/issues/66484
https://tracker.ceph.com/issues/66676
https://tracker.ceph.com/issues/66677
---
backport of https://github.com/ceph/ceph/pull/57462, #57930, #57713
parent tracker: https://tracker.ceph.com/issues/66238
> squid: mgr/dashboard: rgw bucket replication management

- src/crimson/osd/osd_operation.cc
- src/crimson/osd/osd_operation.h
Fixes: https://tracker.ceph.com/issues/66644 …
> crimson/osd/osd_operation: fix dump_historic_slow_ops command works

- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/buckets.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.ts
backport tracker: https://tracker.ceph.com/issues/66487
---
backport of https://github.com/ceph/ceph/pull/57698
parent tracker: https://tracker.ceph.com/issues/66221
> reef: mgr/dashboard: add dueTime to rgw bucket validator

- qa/tasks/ceph.py
- qa/tasks/cephadm.py
- qa/workunits/rbd/krbd_data_pool.sh
This was missed in https://github.com/ceph/ceph/pull/56310 because krbd suite wasn't run. …
> qa: account for rbd_trash object in krbd_data_pool.sh + related ceph{,adm} task fixes

- doc/radosgw/s3/authentication.rst
s/http/HTTP/ in doc/radosgw/s3/authentication.rst, as suggested by Anthony D'Atri in the location linked in the "Fixes:" line below.
Fixes: https://github.com/ceph/ceph/pull/58436#discussion_r1667088045 …
> doc/radosgw: s/http/HTTP/

- src/pybind/mgr/volumes/fs/operations/clone_index.py
In async_cloner.py, clone index entry is fetched to get next clone job
that needs to be executed. It might happen that the clone job was
cancelled just when it was going to be picked for execution (IOW, when
it was about to move from pending state to in-progress state).
Currently, in such a case MGR hangs because the exception ObjectNotFound
from CephFS Python bindings is raised and is left uncaught. To prevent
this issue catch an exception, log it and return None to tell get_job()
of async_job.py to look for next job in the queue.
Fixes: https://tracker.ceph.com/issues/66560 …
> mgr/vol: handle case where clone index entry goes missing

- src/pybind/mgr/dashboard/frontend/cypress/e2e/multi-cluster/multi-cluster.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/multi-cluster/multi-cluster.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
- src/pybind/mgr/dashboard/run-frontend-e2e-tests.sh
auth, edit, reconnect and disconnect another cluster
- …
> mgr/dashboard: multicluster management e2e tests

- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/configuration.po.ts
Fix rgw configuration page e2e test failure
Fixes: https://tracker.ceph.com/issues/66901 …
> mgr/dashboard: fix rgw configuration e2e test  

- doc/dev/release-process.rst
> docs: removed centos 8 and added squid to the build matrix

- doc/install/get-packages.rst
(cherry picked from commit 593ab1ad41467898c57c44baeb947bd238cba645) …
> quincy: doc/install: fix typos in openEuler-installation doc

- doc/dev/encoding.rst
Improve "Principles for format change" in doc/dev/encoding.rst. This commit started as a response to Anthony D'Atri's suggestion here: https://github.com/ceph/ceph/pull/58299/files#r1656985564
Review of this section suggested to me that certain minor English usage improvements would be of benefit. The numbered lists in this section could still be made a bit clearer. …
> doc/dev: edit "Principles for format change"

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/block.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-gateway/nvmeof-gateway.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-gateway/nvmeof-gateway.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-details/nvmeof-subsystems-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-details/nvmeof-subsystems-details.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-details/nvmeof-subsystems-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-tabs/nvmeof-tabs.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-tabs/nvmeof-tabs.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-tabs/nvmeof-tabs.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/nvmeof.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
Fixes https://tracker.ceph.com/issues/66659
- adds subsytems tab
- adds subsystem listing view
- adds create subsystem modal
- adds delete subsystem
- adds unit tests
[Screencast from 2024-06-25 06-03-50.webm](https://github.com/ceph/ceph/assets/25664409/5b37f84b-42a6-4994-8372-fb12f29f8af6)
<details>
- `jenkins …
> mgr/dashboard: Configure subsystems from dashboard 

- src/mds/Server.cc
- src/messages/MClientReclaimReply.h
debug for https://tracker.ceph.com/issues/66003 …
> mds: derr log and dump sessionmap when reclaim session uuid isn't found

- qa/tasks/cephfs/test_mirroring.py
- src/tools/cephfs_mirror/FSMirror.cc
- src/tools/cephfs_mirror/FSMirror.h
- src/tools/cephfs_mirror/InstanceWatcher.cc
- src/tools/cephfs_mirror/InstanceWatcher.h
- src/tools/cephfs_mirror/Mirror.cc
- src/tools/cephfs_mirror/MirrorWatcher.cc
- src/tools/cephfs_mirror/MirrorWatcher.h
- src/tools/cephfs_mirror/Watcher.h
Fixes: https://tracker.ceph.com/issues/64927
Fixes: https://tracker.ceph.com/issues/51964
Fixes: https://tracker.ceph.com/issues/63931
Fixes: https://tracker.ceph.com/issues/63089 …
> cephfs_mirror, qa: fix mirror daemon doesn't restart when blocklisted or failed

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/services.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/services.component.ts
[screen-capture (3).webm](https://github.com/ceph/ceph/assets/106810838/03799695-31f4-4f49-b7e2-7c2111e7b781)
- …
> mgr/dashboard: adds links to the services 

- qa/tasks/ceph.py
- qa/tasks/cephadm.py
- qa/workunits/rbd/krbd_data_pool.sh
backport tracker: https://tracker.ceph.com/issues/66910
---
backport of https://github.com/ceph/ceph/pull/58507
parent tracker: https://tracker.ceph.com/issues/66886
> squid: qa: account for rbd_trash object in krbd_data_pool.sh + related ceph{,adm} task fixes

- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/serve.py
- src/pybind/mgr/cephadm/services/cephadmservice.py
- src/pybind/mgr/cephadm/services/nfs.py
Add a spec argument to the `ranked` function. If this function returns true the service will use ranks. In some cases we want 'rankedness' to be conditional on parameters of the given service spec. …
> mgr/cephadm: allow services to be conditionally ranked

- qa/suites/fs/functional/tasks/admin.yaml
- qa/tasks/cephfs/test_admin.py
Fixes: https://tracker.ceph.com/issues/66674
Fixes: https://tracker.ceph.com/issues/66679 …
> squid: qa: enhance per-client labelled perf counters test

- src/osdc/Journaler.cc
See: https://tracker.ceph.com/issues/58878#note-4
- …
> osdc/Journaler: derr log when header update get (possibly) overwritten out-of-order

- doc/cephfs/mount-prerequisites.rst
- doc/cephfs/mount-using-fuse.rst
> doc: clarify superuser note for ceph-fuse

- src/mds/PurgeQueue.cc
- src/mds/PurgeQueue.h
Fixes: https://tracker.ceph.com/issues/65926 …
> reef: mds/purgequeue: add l_pq_executed_ops counter

- qa/suites/fs/functional/tasks/admin.yaml
- qa/tasks/cephfs/test_admin.py
Fixes: https://tracker.ceph.com/issues/66673
Fixes: https://tracker.ceph.com/issues/66680 …
> reef: qa: enhance per-client labelled perf counters test

- PendingReleaseNotes
- doc/cephfs/cephfs-journal-tool.rst
- doc/cephfs/disaster-recovery-experts.rst
- qa/tasks/cephfs/test_damage.py
- qa/tasks/cephfs/test_data_scan.py
- qa/tasks/cephfs/test_flush.py
- qa/tasks/cephfs/test_forward_scrub.py
- qa/tasks/cephfs/test_journal_migration.py
- qa/tasks/cephfs/test_journal_repair.py
- qa/tasks/cephfs/test_recovery_pool.py
- qa/workunits/fs/damage/test-first-damage.sh
- qa/workunits/suites/cephfs_journal_tool_smoke.sh
- src/tools/cephfs/JournalTool.cc
- src/tools/cephfs/first-damage.py
Fixes: https://tracker.ceph.com/issues/66278 …
> reef: cephfs-journal-tool: Add preventive measures to avoid fs corruption

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/back-button/back-button.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/back-button/back-button.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/wizard/wizard.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
Fixes: https://tracker.ceph.com/issues/66227
https://github.com/ceph/ceph/assets/66050535/ba7ba6cf-5e34-4952-8aaf-630f482835f5 …
> mgr/dashboard: add a wizard to setup rgw multisite replication

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/cypress/e2e/page-helper.po.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.e2e.spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-multisite-zone-selector.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-multisite.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-details/rgw-multisite-sync-policy-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-details/rgw-multisite-sync-policy-details.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-details/rgw-multisite-sync-policy-details.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-details/rgw-multisite-sync-policy-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rgw_client.py
Fixes: https://tracker.ceph.com/issues/66915
Sync Flow Demo - 
https://github.com/user-attachments/assets/be20ac03-c182-44c9-bb3d-1a9bd6825bc2
Directional Sync flow edit/delete is not possible yet as the core backend does not sends flow_id in response, which is necessary for the operations. Hence, kept disabled for now. …
> mgr/dashboard: RGW multisite sync flow

- src/common/options/global.yaml.in
BtreeAllocator was added in the commit
https://github.com/ceph/ceph/pull/41828.
Its performance has advantages in some scenarios,
but we cannot configure to use btree mode.
Fixes: https://tracker.ceph.com/issues/65678
Signed-off-by: tan changzhi <544463199@qq.com> …
> os/bluestore: allow use BtreeAllocator 

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/pipes.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/xml.pipe.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/xml.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/json-to-xml.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/json-to-xml.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/text-area-json-formatter.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/text-area-xml-formatter.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/text-area-xml-formatter.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rgw_client.py
- src/pybind/mgr/dashboard/tests/test_rgw_client.py
backport tracker: https://tracker.ceph.com/issues/66785
---
backport of https://github.com/ceph/ceph/pull/57238
parent tracker: https://tracker.ceph.com/issues/50327
> squid: mgr/dashboard: add RGW lifecycle management

- src/osd/PrimaryLogPG.cc
fixes: https://tracker.ceph.com/issues/65241
- Tracker …
> osd: fix use-after-free before calling finish_unreadable_object()

- src/mds/Locker.cc
Fixes: https://tracker.ceph.com/issues/66667 …
> reef: mds: set the correct WRLOCK flag always in wrlock_force()

- qa/tasks/cephfs/test_scrub_checks.py
- src/mds/MDSRank.cc
Fixes: https://tracker.ceph.com/issues/66868 …
> reef: mds: prevent scrubbing for standby-replay MDS

- doc/cephfs/mount-prerequisites.rst
- doc/cephfs/mount-using-fuse.rst
> squid: doc: clarify superuser note for ceph-fuse

- src/pybind/mgr/dashboard/controllers/rbd.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-feature.interface.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form-edit-request.model.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rbd.py
backport tracker: https://tracker.ceph.com/issues/66993
---
backport of https://github.com/ceph/ceph/pull/57866
parent tracker: https://tracker.ceph.com/issues/66348
> squid: mgr/dashboard: Block -> Images -> Create form improvements

- doc/cephfs/mount-prerequisites.rst
- doc/cephfs/mount-using-fuse.rst
> reef: doc: clarify superuser note for ceph-fuse

- src/pybind/mgr/dashboard/controllers/cephfs.py
- src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-group/cephfs-subvolume-group.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/icons.enum.ts
Depends on https://github.com/ceph/ceph/pull/58303/
NFS export route from subvolume group
[Screencast from 2024-07-10 15-38-43.webm](https://github.com/ceph/ceph/assets/23611106/1ff9b7d5-9037-4b38-b54e-3fd60ade723e)
NFS export route from subvolume
[Screencast from 2024-07-10 16-59-33.webm](https://github.com/ceph/ceph/assets/23611106/a1c1aa4a-0484-4ead-a09c-2778f24546f6) …
> mgr/dashboard: add NFS export button for subvolume/ grp

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/block.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-form/nvmeof-listeners-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-form/nvmeof-listeners-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-form/nvmeof-listeners-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-list/nvmeof-listeners-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-list/nvmeof-listeners-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-list/nvmeof-listeners-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-details/nvmeof-subsystems-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-details/nvmeof-subsystems-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/cell-template.enum.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/nvmeof.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
- src/pybind/mgr/dashboard/services/nvmeof_conf.py
Fixes https://tracker.ceph.com/issues/66996
- list listener under subsystems
- delete listener
- create listener
[Screencast from 2024-07-17 20-48-19.webm](https://github.com/user-attachments/assets/8788b551-2a78-4e6c-8b7f-277f8d21735d)
<details> …
> Allow listeners creation and deletion

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/cypress/e2e/page-helper.po.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.e2e.spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-details/rgw-multisite-sync-policy-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-details/rgw-multisite-sync-policy-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rgw_client.py
Fixes: https://tracker.ceph.com/issues/66926
https://github.com/user-attachments/assets/674f405c-0041-4d86-80f7-a17b00af7cd9 …
>  mgr/dashboard: RGW multisite sync pipe

- monitoring/ceph-mixin/dashboards/rgw.libsonnet
- monitoring/ceph-mixin/dashboards_out/radosgw-sync-overview.json
Add a new chart for replication delta per shard in rgw sync overview grafana dashboard
Fixes: https://tracker.ceph.com/issues/66994 …
> mgr/dashboard: Add a new chart for replication delta per shard in rgw sync overview grafana dashboard

- src/os/bluestore/bluestore_types.h
bluestore/bluestore_types: avoid heap-buffer-overflow in another way to keep code uniformity
This commit modifies end iterator to  keep code uniformity as `items container` did.
Ref: https://github.com/ceph/ceph/pull/56890/files/19104a6fffe24a6debfd8492c90b3027126eb352#r1567083822
Fixes: https://tracker.ceph.com/issues/65482 …
> bluestore/bluestore_types: avoid heap-buffer-overflow in another way to keep code uniformity

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/block.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-list/nvmeof-namespaces-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-list/nvmeof-namespaces-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-list/nvmeof-namespaces-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-details/nvmeof-subsystems-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/nvmeof.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/mbpersecond.pipe.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/mbpersecond.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/pipes.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
Fixes https://tracker.ceph.com/issues/66990
- list namespaces
- create namespaces
- edit namespaces
- delete namespaces
- update NQN regex
[Screencast from 2024-07-17 08-17-48.webm](https://github.com/user-attachments/assets/c00e5ef7-1b15-4f76-ae52-b50301ef9609)
<details> …
> mgr/dashboard: Add namespaces views in dashboard     

- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.e2e.spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-form/rgw-multisite-sync-policy-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-form/rgw-multisite-sync-policy-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-tabs/rgw-multisite-tabs.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-tabs/rgw-multisite-tabs.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-tabs/rgw-multisite-tabs.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
Added routed tabs for rgw multisite and openend modal inside router-outlet.
Fixes: https://tracker.ceph.com/issues/66977 …
> mgr/dashboard: Rgw sync policy routing fix

- src/test/rgw/test_rgw_amqp.cc
not really a fix, mainly a workaround until we do
the amqp refactoring: https://tracker.ceph.com/issues/67011
Fixes: https://tracker.ceph.com/issues/64690
<details>
</details>
> test/rgw/amqp: skip TestAMQP.MaxConnections test

- doc/start/get-involved.rst
Update the User and Dev mailing list subscription links. This commit is made in response to a request from Dan van der Ster. …
> doc/start: update mailing list links

- doc/start/get-involved.rst
Update the User and Dev mailing list subscription links. This commit is made in response to a request from Dan van der Ster.
(cherry picked from commit a242fe3d940d5764cd766dba8e42449501986765) …
> reef: doc/start: update mailing list links

- doc/start/get-involved.rst
Update the User and Dev mailing list subscription links. This commit is made in response to a request from Dan van der Ster.
(cherry picked from commit a242fe3d940d5764cd766dba8e42449501986765) …
> quincy: doc/start: update mailing list links

- doc/cephadm/upgrade.rst
(cherry picked from commit 9c77963300fee804f249d512c980cdeac06f14f7) …
> squid: doc/cephadm/upgrade: ceph-ci containers are hosted by quay.ceph.io

- doc/cephadm/upgrade.rst
(cherry picked from commit 9c77963300fee804f249d512c980cdeac06f14f7) …
> reef: doc/cephadm/upgrade: ceph-ci containers are hosted by quay.ceph.io

- doc/cephadm/upgrade.rst
(cherry picked from commit 9c77963300fee804f249d512c980cdeac06f14f7) …
> quincy: doc/cephadm/upgrade: ceph-ci containers are hosted by quay.ceph.io

- qa/valgrind.supp
Fixes: https://tracker.ceph.com/issues/61774
<details>
- …
> qa: suppress Leak_StillReachable mon leak in centos 9 jobs

- src/librbd/api/Image.cc
- src/librbd/image/CloneRequest.cc
- src/librbd/internal.cc
- src/test/librbd/test_librbd.cc
- src/test/pybind/test_rbd.py
Fixes: https://tracker.ceph.com/issues/65744 …
> rbd: add the validate of the format and clone_format

- src/librbd/io/AioCompletion.cc
- src/librbd/io/AioCompletion.h
> librbd: fix inconsistency between AioCompletion is_complete() and wait_for_complete()

- doc/dev/internals.rst
- [x ] Doc update (no ticket needed)
- [x ] Updates relevant documentation
- [ x] No tests
> doc: Amend dev mailing list subscribe instructions.

- doc/dev/internals.rst
Signed-off-by: Paulo E. Castro <pecastro@wormholenet.com>
(cherry picked from commit 3b0360bc2ea1e0b5f7a7c6b04ade483f77e4b5c6) …
> squid: doc: Amend dev mailing list subscribe instructions.

- doc/dev/internals.rst
Signed-off-by: Paulo E. Castro <pecastro@wormholenet.com>
(cherry picked from commit 3b0360bc2ea1e0b5f7a7c6b04ade483f77e4b5c6) …
> reef: doc: Amend dev mailing list subscribe instructions.

- doc/dev/internals.rst
Signed-off-by: Paulo E. Castro <pecastro@wormholenet.com>
(cherry picked from commit 3b0360bc2ea1e0b5f7a7c6b04ade483f77e4b5c6) …
> quincy: doc: Amend dev mailing list subscribe instructions.

- qa/workunits/rbd/luks-encryption.sh
> qa/workunits/rbd: avoid caching effects in luks-encryption.sh
