doc/cephfs/mount-prerequisites.rst
doc/man/8/cephfs-shell.rst

Repair the link to cephfs-shell.rst in doc/cephfs/cephfs-shell.rst that was broken in https://github.com/ceph/ceph/pull/41165/ when doc/cephfs/cephfs-shell.rst was moved to doc/man/8/cephfs-shell.rst.
(cherry picked from commit 4f8903cf80a94596a1b17b4a07affb874f21ae76) …

quincy: doc/cephfs: update cephfs-shell link

---

doc/cephfs/mount-prerequisites.rst
doc/man/8/cephfs-shell.rst

Repair the link to cephfs-shell.rst in doc/cephfs/cephfs-shell.rst that was broken in https://github.com/ceph/ceph/pull/41165/ when doc/cephfs/cephfs-shell.rst was moved to doc/man/8/cephfs-shell.rst.
(cherry picked from commit 4f8903cf80a94596a1b17b4a07affb874f21ae76) …

reef: doc/cephfs: update cephfs-shell link

---

doc/cephfs/mount-prerequisites.rst
doc/man/8/cephfs-shell.rst

Repair the link to cephfs-shell.rst in doc/cephfs/cephfs-shell.rst that was broken in https://github.com/ceph/ceph/pull/41165/ when doc/cephfs/cephfs-shell.rst was moved to doc/man/8/cephfs-shell.rst.
(cherry picked from commit 4f8903cf80a94596a1b17b4a07affb874f21ae76) …

squid: doc/cephfs: update cephfs-shell link

---

src/ceph-volume/ceph_volume/tests/util/test_encryption.py
src/ceph-volume/ceph_volume/util/encryption.py

backport tracker: https://tracker.ceph.com/issues/66464
---
backport of https://github.com/ceph/ceph/pull/57925
parent tracker: https://tracker.ceph.com/issues/66393

squid: ceph-volume: fix set_dmcrypt_no_workqueue()

---

src/ceph-volume/ceph_volume/objectstore/lvmbluestore.py

backport tracker: https://tracker.ceph.com/issues/66026
---
backport of https://github.com/ceph/ceph/pull/56882
parent tracker: https://tracker.ceph.com/issues/65477

squid: ceph-volume: create LVs when using partitions

---

qa/distros/container-hosts/centos_9.stream.yaml
qa/distros/container-hosts/centos_9.stream_runc.yaml
qa/tasks/nvme_loop.py

backport tracker: https://tracker.ceph.com/issues/66746
---
backport of https://github.com/ceph/ceph/pull/58290
parent tracker: https://tracker.ceph.com/issues/66707

squid: tests: make sure nvmetcli and nvme-cli are up to date

---

src/pybind/mgr/smb/fs.py
src/pybind/mgr/smb/handler.py
src/pybind/mgr/smb/internal.py
src/pybind/mgr/smb/module.py
src/pybind/mgr/smb/proto.py
src/pybind/mgr/smb/resourcelib.py
src/pybind/mgr/smb/resources.py
src/pybind/mgr/smb/results.py
src/pybind/mgr/smb/tests/test_enums.py
src/pybind/mgr/smb/tests/test_fs.py
src/pybind/mgr/smb/tests/test_handler.py
src/pybind/mgr/smb/tests/test_resources.py
src/pybind/mgr/smb/tests/test_smb.py
src/pybind/mgr/smb/tests/test_utils.py
src/pybind/mgr/smb/utils.py
src/pybind/mgr/smb/validation.py

Depends on #57339 
After adding a bunch of features and changing this we lacked test coverage in some areas. While it's not anywhere near 100% a bunch more things, esp with regards to error handling, are now covered.
In addition, I moved some stuff into a utils.py because it was easier to add/move tests for these utils to a new file. Stuff like proto.py and enums.py do not need test functions otherwise (they're largely mypy or import-time things). …

smb: improve smb module test coverage

---

src/pybind/mgr/CMakeLists.txt
src/pybind/mgr/mgr_module.py
src/pybind/mgr/mgr_util.py
src/pybind/mgr/tox.ini

Update the *.py files in src/pybind/mgr to be pep8 clean (via flake8).
Update the tox.ini so these file will be checked by flake8 in the future.
Update the tox.ini file to have an improved default envlist. Use that envlist when running "make check" via cmake - much like #56304 did for the src/cephadm dir. This allows the python to be checked with a simple `tox r` that will match what the CI will run, hopefully leading to fewer surprises. …

pybind/mgr: mgr_module.py pep8/flake8 cleanups & tox updates

---

src/pybind/mgr/cephadm/services/ingress.py
src/pybind/mgr/cephadm/tests/test_services.py

In some special conditions, such as ingress service reconfiguration, cepham would list the network IPs and pick the VIP as the unicast IP of the peer. It would then generate buggy config causing service misbehavior.

cephadm/services/ingress: fixed keepalived config bug

---

src/cephadm/cephadm.py

While bootstrapping an ipv6 cluster with an ipv6 initial mon, cephadm correctly enables ms_bind_ipv6=true. However it leaves ms_bind_ipv4 as it's default (true).
As a result, daemons (osd, mds, ...) will attempt to bind to both ipv6 and ipv4. Usually this results in an osdmap and fsmap like the following:
```
osd.2 up in weight 1 up_from 26 up_thru 909 down_at 0 last_clean_interval [0,0) [v2:[xxxx:4f8:d0:4401:3::29]:6800/3680761436,v1:[xxxx:4f8:d0:4401:3::29]:6801/3680761436,v2:0.0.0.0:6802/3680761436,v1:0.0.0.0:6803/3680761436] [v2:[xxxx:4f8:d0:4401:3::29]:6804/3680761436,v1:[xxxx:4f8:d0:4401:3::29]:6805/3680761436,v2:0.0.0.0:6806/3680761436,v1:0.0.0.0:6807/3680761436] exists,up 0978a571-cd00-4eba-b00b-f863603a9a70
```
```
[mds.cephfs.ceph-test-3.isityv{-1:793154} state up:standby seq 1 …
```

cephadm: disable ms_bind_ipv4 if we will enable ms_bind_ipv6

---

src/pybind/mgr/cephadm/serve.py
src/pybind/mgr/cephadm/tests/test_services.py

previous code was failing to redeploy in some scenarios when daemons are removed. The new check takes into account both when services are add or removed plus changes on the secure_monitoring_stack value. …

mgr/cephadm: redeploy when some dependency daemon is add/removed

---

src/osd/ECBackend.cc

backport tracker: https://tracker.ceph.com/issues/66694
---
backport of https://github.com/ceph/ceph/pull/58139
parent tracker: https://tracker.ceph.com/issues/64437

squid: osd/ECBackend.cc: Fix double increment of num_shards_repaired stat

---

PendingReleaseNotes
src/rgw/driver/rados/rgw_notify.cc
src/rgw/driver/rados/rgw_pubsub_push.cc
src/rgw/rgw_kafka.cc
src/rgw/rgw_kafka.h
src/test/rgw/bucket_notification/test_bn.py

Fixes https://tracker.ceph.com/issues/66036
<details>
</details>

rgw/notification: Fix the caching issues of notification brokers, where the cache was not invalidated if topic attributes were changed

---

qa/tasks/cbt.py

Initialize 'monitoring_profiles' to an empty python dictionary instead of 'None' to
prevent the cbt task from failing due to the TypeError exception when attempting
to iterate a 'NoneType'.
The bug was introduced as part of https://github.com/ceph/ceph/pull/51438 and
commit e174c6e2cf6c90bd130320eb1f251b62d4b4d6c2.
Signed-off-by: Sridhar Seshasayee <sseshasa@redhat.com>
Fixes: https://tracker.ceph.com/issues/66799
- When filling …

qa/tasks: Initialize 'monitoring_profiles' spec to an empty dict

---

src/rgw/driver/rados/rgw_log_backing.cc

Fitting a retry loop around a call that took the lock changed the logic to potentially have the lock be used after moving.
Thanks to Suyash Dongre suyashd999@gmail.com for finding it.
This patch also fixes a lock being held across an I/O operation.
Fixes: https://tracker.ceph.com/issues/66340 …

rgw/multisite: Fix use-after-move in retry logic in logbacking

---

doc/radosgw/adminops.rst
src/rgw/driver/rados/rgw_rest_user.cc

In the `radosgw-admin user` command, the default storage class can defined. This capability is missing in the adminops api.
Fixes https://tracker.ceph.com/issues/66439 …

rgw/adminops: add option to provide storageclass adminops user apis

---

src/tools/cephfs/shell/cephfs-shell

backport tracker: https://tracker.ceph.com/issues/66500
---
backport of https://github.com/ceph/ceph/pull/55711
parent tracker: https://tracker.ceph.com/issues/64538

squid: cephfs-shell: prints warning, hangs and aborts when launched

---

src/client/fuse_ll.cc

Backport of https://github.com/ceph/ceph/pull/57170
Backport tracker: https://tracker.ceph.com/issues/66191
Parent tracker: https://tracker.ceph.com/issues/62664
This is a workaround for libmount 2.38 or later on linux kernel 5.1 or later.
libmount defaults to the new fsconfig interface which does not support remounting the way the old mount(2) syscall did. Thus, dentry trimming fails.
Fixes: https://tracker.ceph.com/issues/62664
Signed-off-by: Jakob Haufe <sur5r@sur5r.net>
(cherry picked from commit 9ca1d4be2b587ce1d3e6c10dc2a98195b2ab3ba9) …

squid: client: set LIBMOUNT_FORCE_MOUNT2=always

---

src/mds/MDCache.cc
src/mds/MDSRank.cc

backport tracker: https://tracker.ceph.com/issues/65404
---
backport of https://github.com/ceph/ceph/pull/56629
parent tracker: https://tracker.ceph.com/issues/65260

squid: mds: log at a lower level when stopping

---

src/cls/rgw/cls_rgw_types.h

9302fbb3f5416871c1978af5d45f3bf568c2c190 bumped the version in ENCODE_START() but missed DECODE_START(). i don't _think_ that would cause any decode failures, unless we later raise ENCODE_START's compat_v above 2
<details>
</details>

cls/rgw: bump cls_rgw_reshard_entry decode version to match encode

---

src/rgw/rgw_rest.cc

If the Host header is missing, but the s3website API is enabled and has a higher priority than the regular S3 API, then we should still treat the request as a website request.
Fixes: https://tracker.ceph.com/issues/66748

rgw: use s3website REST when higher priority and no host header

---

src/rgw/driver/rados/rgw_user.cc

Adding clear would put `keys` back in a defined state 
clang-tidy warning for `rgw_user.cc`:
```
/home/suyash/ceph/src/rgw/driver/rados/rgw_user.cc:1558:5: warning: 'keys' used after it was moved [bugprone-use-after-move]
keys[id] = std::move(key);  
^
/home/suyash/ceph/src/rgw/driver/rados/rgw_user.cc:1554:22: note: move occurred here
auto modify_keys = std::move(keys);
^
```
Fixes: https://tracker.ceph.com/issues/66553
Signed-off-by: Suyash Dongre <suyashd999@gmail.com>
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatche …

rgw_user: 'keys' is in undefined state after being moved.

---

src/rgw/rgw_asio_frontend.cc

Hi, we have encountered a problem where one of our internal users reached their bucket quota. This caused a Denial of Service (DoS) on all RGW instances in the installation.
1. Create a bucket and set a quota for it.
2. Reach the quota by uploading objects (or set it to zero).
3. Start uploading large (25+ MiB) objects to the bucket in parallel (50-100 workers).
4. Observe how the RGW instance becomes completely unresponsive.
When the quota is reached, the RGW quickly returns from the `process_request` method, but it still needs to dump all the data present in the socket. It does this in a loop, but only drains 1 KiB per read. The CPU starts spending all its time on context switches.
We can increase the buffer size to a larger value. I have checked and found that a 1 MiB buffer is …

rgw: DoS when QuotaExceeded

---

src/rgw/rgw_quota.cc

A signed value was read in as an unsigned value, so -1 was interpreted as a very large value. This made the thread wait period in the bucket sync thread inordinately long, preventing bucket sync and dynamic resharding (unless values appropriate for debugging were set).
Fixes: https://tracker.ceph.com/issues/66812 …

rgw: fix bucket sync thread waiting inordinate amount of time

---

qa/suites/upgrade/reef-p2p/reef-p2p-parallel/point-to-point-upgrade.yaml

Instead of installing 18.2.0, which still contains the osdmap crc bug tracked in https://tracker.ceph.com/issues/63389, we should install v18.2.2 since this contains the fix. Then, we upgrade to reef_latest. In this scenario, we do not expect to see the crc bug. If we test any upgrade path before that, we will hit the warning and the test will fail.
Fixes: https://tracker.ceph.com/issues/66505 …

qa/suites/upgrade/reef-p2p/reef-p2p-parallel: increment upgrade to 18.2.2

---

src/tools/cephfs/shell/cephfs-shell

backport tracker: https://tracker.ceph.com/issues/66502
---
backport of https://github.com/ceph/ceph/pull/55711
parent tracker: https://tracker.ceph.com/issues/64538

reef: cephfs-shell: prints warning, hangs and aborts when launched

---

src/tools/cephfs_mirror/FSMirror.h

Fixes the crash:
```
std::scoped_lock<std::mutex>::scoped_lock (__m=..., this=<optimized out>, this=<optimized out>, __m=...) at /usr/include/c++/11/mutex:655
cephfs::mirror::MirrorWatcher::is_failed (this=0x0) at /usr/src/debug/ceph-19.0.0-1578.g3d482f42.el9.x86_64/src/tools/cephfs_mirror/MirrorWatcher.h:56
cephfs::mirror::FSMirror::is_failed (this=0x557478284340) at /usr/src/debug/ceph-19.0.0-1578.g3d482f42.el9.x86_64/src/tools/cephfs_mirror/FSMirror.h:52
cephfs::mirror::Mirror::update_fs_mirrors (this=0x5574773c3e60) at /usr/src/debug/ceph-19.0.0-1578.g3d482f42.el9.x86_64/src/tools/cephfs_mirror/Mirror.cc:515
```
Fixes: https://tracker.ceph.com/issues/64751
(cherry picked from commit 5b8b9c2f7738e0341807c1e0971c3dec90ac5491)

reef: cephfs_mirror: fix crash in update_fs_mirrors()

---

src/test/rgw/bucket_notification/test_bn.py

backport tracker: https://tracker.ceph.com/issues/66772
---
backport of https://github.com/ceph/ceph/pull/57655
parent tracker: https://tracker.ceph.com/issues/66206

squid: RGW|Bucket notification: reload realm correctly

---

doc/rados/api/librados-intro.rst

In this example librados2-devel only install C header files on fedora 40, therefore I added libradospp-devel to the command to include C++ header files.
Signed-off-by: Pere Diaz Bou <pere-altea@hotmail.com>
(cherry picked from commit 7e87441601db2379488fab62e900cd834086f26d) …

quincy: doc/rados: update how to install c++ header files

---

src/rgw/CMakeLists.txt

rgw enables the XXH_INLINE_ALL define, but this causes debug builds to fail with errors like:
```
In file included from /home/cbodley/ceph/src/rgw/rgw_blake3_digest.h:23,
from /home/cbodley/ceph/src/rgw/rgw_cksum_digest.h:19:
In function ‘void XXH3_hashLong_internal_loop(xxh_u64*, const xxh_u8*, size_t, const xxh_u8*, size_t, XXH3_f_accumulate, XXH3_f_scrambleAcc)’,
inlined from ‘XXH64_hash_t XXH3_hashLong_64b_internal(const void*, size_t, const void*, size_t, XXH3_f_accumulate, XXH3_f_scrambleAcc)’ at /home/cbodley/ceph/src/xxHash/xxhash.h:5607:32,
inlined from ‘XXH64_hash_t XXH3_hashLong_64b_withSeed_internal(const void*, size_t, XXH64_hash_t, XXH3_f_accumulate, XXH3_f_scrambleAcc, XXH3_f_initCustomSecret)’ at /home/cbodley/ceph/src/xxHash/xxhash.h:5666:42,
inlined from ‘XXH64_hash_t …
```

cmake: work around xxhash 'inlining failed' errors in debug builds

---

doc/radosgw/s3/authentication.rst

authentication.rst described the steps to generate a v2 signature, without reference to aws docs. replace that with sections that reference aws docs for v2 and v4 signatures. list which values of the request header x-amz-content-sha256 are supported for v4
Fixes: https://tracker.ceph.com/issues/42888
<details>
- `jenkins …

doc/rgw: update s3 authentication

---

.gitmodules

b6d585645ca7d469fd9fe453ff37ca6bdb914d98 accidentally added back the boost_redis submodule that was removed in 862246cdefc12acfbd2711c7677a252c59634c9d
<details>
</details>

submodule: remove the boost_redis submodule again

---

doc/rados/configuration/mon-lookup-dns.rst

Document how to manually pass the search domain to "mon_dns_srv_name" in doc/rados/configuration/mon-lookup-dns.rst.
(cherry picked from commit 98938a0312dd0c8e0b293ed9aa2e0760cc9619fa) …

squid: doc/rados: document manually passing search domain

---

doc/rados/configuration/mon-lookup-dns.rst

Document how to manually pass the search domain to "mon_dns_srv_name" in doc/rados/configuration/mon-lookup-dns.rst.
(cherry picked from commit 98938a0312dd0c8e0b293ed9aa2e0760cc9619fa) …

reef: doc/rados: document manually passing search domain

---

doc/rados/configuration/mon-lookup-dns.rst

Document how to manually pass the search domain to "mon_dns_srv_name" in doc/rados/configuration/mon-lookup-dns.rst.
(cherry picked from commit 98938a0312dd0c8e0b293ed9aa2e0760cc9619fa) …

quincy: doc/rados: document manually passing search domain

---

src/compressor/CMakeLists.txt
src/crush/CMakeLists.txt
src/erasure-code/jerasure/CMakeLists.txt
src/mgr/CMakeLists.txt
src/test/objectstore/CMakeLists.txt

tracking down missing cmake dependencies that lead to compilation failures like:
```
src/common/options/legacy_config_opts.h:10:10: fatal error: 'immutable-object-cache_legacy_options.h' file not found
#include "immutable-object-cache_legacy_options.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
followup to https://github.com/ceph/ceph/pull/57011, https://github.com/ceph/ceph/pull/57693, https://github.com/ceph/ceph/pull/57583, etc
<details>
- `jenkins …

cmake: more object libraries depend on legacy-option-headers

---

src/ceph-volume/ceph_volume/devices/lvm/prepare.py

backport tracker: https://tracker.ceph.com/issues/66024
---
backport of https://github.com/ceph/ceph/pull/56882
parent tracker: https://tracker.ceph.com/issues/65477

reef: ceph-volume: create LVs when using partitions

---

qa/suites/orch/cephadm/mgr-nfs-upgrade/4-final.yaml
qa/suites/orch/cephadm/osds/1-start.yaml
qa/suites/orch/cephadm/smoke-roleless/1-start.yaml
qa/suites/orch/cephadm/smoke-small/start.yaml
qa/suites/orch/cephadm/smoke/start.yaml
qa/suites/orch/cephadm/thrash/1-start.yaml
qa/suites/orch/cephadm/upgrade/3-upgrade/simple.yaml
qa/suites/orch/cephadm/upgrade/3-upgrade/staggered.yaml
qa/suites/orch/cephadm/workunits/task/test_extra_daemon_features.yaml
qa/suites/orch/cephadm/workunits/task/test_host_drain.yaml
qa/suites/orch/cephadm/workunits/task/test_iscsi_container/test_iscsi_container.yaml
qa/suites/orch/cephadm/workunits/task/test_set_mon_crush_locations.yaml

backport tracker: https://tracker.ceph.com/issues/66831
---
backport of https://github.com/ceph/ceph/pull/58344
parent tracker: https://tracker.ceph.com/issues/66751

reef: qa: fix log errors for cephadm tests

---

qa/suites/fs/nfs/overrides/ignore_mgr_down.yaml
qa/suites/orch/cephadm/mgr-nfs-upgrade/4-final.yaml
qa/suites/orch/cephadm/osds/1-start.yaml
qa/suites/orch/cephadm/smoke-roleless/1-start.yaml
qa/suites/orch/cephadm/smoke-small/start.yaml
qa/suites/orch/cephadm/smoke/start.yaml
qa/suites/orch/cephadm/thrash/1-start.yaml
qa/suites/orch/cephadm/upgrade/3-upgrade/simple.yaml
qa/suites/orch/cephadm/upgrade/3-upgrade/staggered.yaml
qa/suites/orch/cephadm/workunits/task/test_extra_daemon_features.yaml
qa/suites/orch/cephadm/workunits/task/test_host_drain.yaml
qa/suites/orch/cephadm/workunits/task/test_iscsi_container/test_iscsi_container.yaml
qa/suites/orch/cephadm/workunits/task/test_monitoring_stack_basic.yaml
qa/suites/orch/cephadm/workunits/task/test_set_mon_crush_locations.yaml
qa/suites/rados/basic/tasks/rados_api_tests.yaml

backport tracker: https://tracker.ceph.com/issues/66830
---
backport of https://github.com/ceph/ceph/pull/58344
parent tracker: https://tracker.ceph.com/issues/66751

squid: qa: fix log errors for cephadm tests

---

src/common/options/rgw.yaml.in
src/rgw/rgw_s3select.cc
src/rgw/rgw_s3select_private.h

-- add the option to reject s3select-requests 
`ceph config set client.rgw.8000 rgw_s3select_disable true`
-- in some cases the error message does not return to client, connection got broken (invalid chunk length)
https://bugzilla.redhat.com/show_bug.cgi?id=2252396
https://bugzilla.redhat.com/show_bug.cgi?id=2275323
https://github.com/ceph/s3-tests/pull/561  NOTE:  the s3-tests PR must merged with this PR
https://tracker.ceph.com/issues/65828  …

rgw/s3select : fix for error flow. add an option to disable s3select-request.

---

src/rgw/driver/rados/rgw_rados.cc

the RGWObjManifest for multipart uploads is subtly different when there's only a single part. in that case, get_cur_part_id() for the final rule returns 1 where it otherwise returns (parts_count + 1)
this caused two problems for the 'get part' feature from https://github.com/ceph/ceph/pull/50148:
* we returned a parts_count of 0 instead 1, and
* the do-while loop got stuck in an infinite loop expecting the last rule's part id to be higher than the requested part id
Fixes: https://tracker.ceph.com/issues/66705
<details> …

rgw: fix multipart get part when count==1

---

src/crimson/os/seastore/btree/fixed_kv_btree.h
src/crimson/os/seastore/btree/fixed_kv_node.h

crimson/os/seastore/btree: improve lba pointer related UT checks

---

debian/ceph-base.postinst

A rather recent PR made `ceph-crash` run as `ceph` user instead of root[^0]. However, because `/var/lib/ceph/crash/posted` belongs to root, `ceph-crash` cannot actually post any crash logs now.
This commit fixes this by recursively updating the permissions of `/var/lib/ceph/crash`, which ensures that all files and directories used by `ceph-crash.service` are actually owned by the user configured for Ceph.
The previously existing loop has also been replaced by an invocation of `find | xargs`.
Fixes: https://tracker.ceph.com/issues/64548
I'm not 100% sure if this is the best way to fix this issue, so please let me know if you prefer a different solution. This patch is …

debian: recursively adjust permissions of /var/lib/ceph/crash

---

src/crush/CrushWrapper.cc
src/crush/CrushWrapper.h

When sanitizer is enabled, unittest_erasure_code_shec shows:
```
=================================================================
==437976==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 2021708 byte(s) in 29731 object(s) allocated from:
#0 0xaaaab0144820 in malloc (/root/ceph-19.0.0/build/bin/unittest_erasure_code_shec+0x1d4820) (BuildId: c0999ecf82504ed7e184ea4b4b9ae9d32faa1c46)
#1 0xffffa770057c in crush_make_rule /root/ceph-19.0.0/src/crush/builder.c:104:9
#2 0xffffa7751638 in CrushWrapper::add_simple_rule_at(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, …
```

crush/builder: free 'crush_rule' before return

---

src/rgw/rgw_kafka.cc

backport tracker: https://tracker.ceph.com/issues/66288
---
backport of https://github.com/ceph/ceph/pull/56033
parent tracker: https://tracker.ceph.com/issues/66017

squid: rgw/kafka: do not destroy the connection on errors

---

src/rgw/driver/rados/rgw_notify.cc
src/rgw/rgw_amqp.cc
src/rgw/rgw_kafka.cc
src/rgw/rgw_lua_background.cc
src/rgw/rgw_ratelimit.h

backport tracker: https://tracker.ceph.com/issues/66499
---
backport of https://github.com/ceph/ceph/pull/57969
parent tracker: https://tracker.ceph.com/issues/64305

squid: rgw: do not assert on thread name setting failures

---

src/osdc/Striper.cc
src/test/librbd/fsx.cc
src/test/librbd/test_librbd.cc

backport tracker: https://tracker.ceph.com/issues/66113
---
backport of https://github.com/ceph/ceph/pull/57433
parent tracker: https://tracker.ceph.com/issues/65813

reef: librbd: don't crash on a zero-length read if buffer is NULL

---

qa/suites/rbd/basic/tasks/rbd_python_api_tests_old_format.yaml
qa/suites/rbd/device/workloads/diff-continuous-krbd.yaml
qa/suites/rbd/device/workloads/diff-continuous-nbd.yaml
qa/suites/rbd/librbd/workloads/python_api_tests.yaml
qa/suites/rbd/librbd/workloads/python_api_tests_with_defaults.yaml
qa/suites/rbd/librbd/workloads/python_api_tests_with_journaling.yaml
qa/suites/rbd/mirror/workloads/compare-mirror-image-alternate-primary-krbd.yaml
qa/suites/rbd/mirror/workloads/compare-mirror-image-alternate-primary-nbd.yaml
qa/suites/rbd/mirror/workloads/compare-mirror-images-krbd.yaml
qa/suites/rbd/mirror/workloads/compare-mirror-images-nbd.yaml
qa/suites/rbd/valgrind/workloads/python_api_tests.yaml
qa/suites/rbd/valgrind/workloads/python_api_tests_with_defaults.yaml
qa/suites/rbd/valgrind/workloads/python_api_tests_with_journaling.yaml

backport tracker: https://tracker.ceph.com/issues/66263
---
backport of https://github.com/ceph/ceph/pull/57729
parent tracker: https://tracker.ceph.com/issues/66232

reef: qa/suites/rbd: override extra_system_packages directly on install task

---

src/librbd/api/DiffIterate.cc
src/test/librbd/test_librbd.cc

backport tracker: https://tracker.ceph.com/issues/66583
---
backport of https://github.com/ceph/ceph/pull/57973
parent tracker: https://tracker.ceph.com/issues/66418

reef: librbd: diff-iterate shouldn't crash on an empty byte range

---

src/cls/rbd/cls_rbd_types.h
src/librbd/api/Group.cc
src/test/librados_test_stub/TestMemIoCtxImpl.cc
src/test/librbd/test_Groups.cc
src/test/pybind/test_rbd.py

backport tracker: https://tracker.ceph.com/issues/66588
---
backport of https://github.com/ceph/ceph/pull/58074 and https://github.com/ceph/ceph/pull/58300
parent tracker: https://tracker.ceph.com/issues/66300

reef: librbd: disallow group snap rollback if memberships don't match

---

qa/tasks/cephfs/test_scrub_checks.py
src/mds/MDSRank.cc

Fixes: https://tracker.ceph.com/issues/62537
<details>
- …

mds: prevent scrubbing for standby-replay MDS

---

src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/os/bluestore/bluestore_types.h
src/test/objectstore/store_test.cc
src/test/objectstore/test_bluestore_types.cc

Instead of indexing buffers by blob offset we do it by logical offset. Previously we tried using physical offsets but it was a pretty bad idea is it required extra bound checks of physical extents and extra loops for to add them, that includes chopping off buffer data.
Logical offsets don't have these problems but we have different ones. Bufferlist data is padded before being used in `_do_alloc_write` which means before adding it to BufferSpace, we are required to get the unpadded substr_of data because padded data might overflow to an invalid logical offset in contrast to when we used blob offsets where padded data was wonderful. This is true in in `generate_read_result_bl` too, we read by regions of blob extents but we must translate it back to logical offsets, that means an extra loop …

os/bluestore: BufferSpace per Onode

---

src/test/librbd/exclusive_lock/test_mock_PostAcquireRequest.cc
src/test/librbd/exclusive_lock/test_mock_PreAcquireRequest.cc
src/test/librbd/exclusive_lock/test_mock_PreReleaseRequest.cc

Clean it up because
```
/home/jenkins-build/build/workspace/ceph-pull-requests-arm64/src/test/librbd/exclusive_lock/test_mock_PreAcquireRequest.cc:47:26: error: unused variable 'TEST_COOKIE' [-Werror,-Wunused-const-variable]
static const std::string TEST_COOKIE("auto 123");
^
1 error generated.
```
Ref: https://jenkins.ceph.com/job/ceph-pull-requests-arm64/59242/consoleFull#-5120798632a811ea2-3e7b-466b-84b4-d13df7e35809
- When …

test/librbd: clean up unused TEST_COOKIE variable

---

src/os/bluestore/BlueStore.cc

backport tracker: https://tracker.ceph.com/issues/65937
--------
backport of #49438
parent tracker: https://tracker.ceph.com/issues/58274

squid: os/bluestore: set rocksdb iterator bounds for Bluestore::_collection_list()

---

src/osd/scrubber/osd_scrub.cc
src/osd/scrubber/osd_scrub.h
src/osd/scrubber/osd_scrub_sched.cc
src/osd/scrubber/osd_scrub_sched.h
src/osd/scrubber/pg_scrubber.cc
src/osd/scrubber/pg_scrubber.h
src/osd/scrubber/scrub_machine.cc
src/osd/scrubber/scrub_machine.h
src/osd/scrubber/scrub_machine_lstnr.h

allow new scrub sessions to be initiated by an OSD even while a PG is
in the process of reserving scrub resources.
The existing restriction made sense when the replica reservation process
was expected to succeed or fail within a few milliseconds. It makes less
sense now that the reservation process is queue-based (Reserver based)
and can take unlimited time (hours, days, ...) to complete.
Backport of https://github.com/ceph/ceph/pull/57865
Fixes: https://tracker.ceph.com/issues/66524
Original tracker: https://tracker.ceph.com/issues/66351

squid: osd/scrub: allow new scrubs while reserving

---

doc/cephadm/services/osd.rst

The current link goes to `cephadm/services/rados/operations/devices` which is a 404, it instead needs to be `rados/operations/devices/`.
This could usefully be backported to at least reef. …

doc: Correct link to "Device management"

---

src/mgr/Mgr.cc

Reverts the change from https://github.com/ceph/ceph/pull/53993 and directly clears daemon health metrics for down and out OSDs. The former approach of removing down/out OSDs from the daemon state has undesirable consequences for stat output, including the prometheus exporter.
For example, the approach of removing the daemon from the daemon state causes the down/out OSD to not appear in prometheus output at all. An alert for detecting down/out OSDs that triggers when `count(ceph_osd_up = 0) > 1` no longer works.
Fixes: https://tracker.ceph.com/issues/66168 …

mgr/Mgr.cc: clear daemon health metrics instead of removing down/out osd from daemon state

---

src/osd/OSDMap.cc

In e9921ee76c06 new revisions for client-usable data of `OSDMap` (rev 10) and `OSDMap::Incremental` (rev 9) have been introduced. However, corresponding `DECODE_START` in decoders haven't been bumped up.
The net effect is a blur between the schemas when somebody would intentionally (with `malformed_input` being thrown) want to break compatibility with decoders on those versions (refer to `struct_compat`).
```
/**
* start a decoding block
*
* @param v current version of the encoding that the code supports/encodes
* @param bl bufferlist::iterator for the encoded data
*/
__u8 struct_v, struct_compat;						\
using ::ceph::decode;							\
decode(struct_v, bl);						\
decode(struct_compat, bl);						\
if (v < struct_compat)						\
throw …
```

osd: bump versions of decoders for upmap-primary

---

src/mgr/MgrOpRequest.h

During restart of osd and run a command "ceph tell mgr dump_historic_ops_by_duration" the flag_point shows some garbage characters. The garbage character is showing due to having garbage value of last_event_detail string variable.
The data type of last_event_detail is const char* not a std::string so the value can become garbage during call op->mark_reched so to avoid an issue change the data type.
Fixes: https://tracker.ceph.com/issues/66268 …

mgr: the mojibake characters in the MGR OP tracker output

---

src/python-common/ceph/rgw/rgwam_core.py

This was setting a field called "rgw_token" in the rgw spec but this is not a real field in rgw specs. Instead we should be setting "rgw_realm_token" which is what the field is actually called.
Setting this nonexistent field causes the spec to be deleted the first time cephadm needs to convert it from a json string back into a python object (which happens whenever the module restarts or the active mgr changes) which then causes all the rgw daemons attached to the service to be removed
Fixes: https://tracker.ceph.com/issues/66824 …

mgr/rgw: fix setting rgw realm token in secondary site rgw spec

---

src/cephadm/cephadm.py

Backport of https://github.com/ceph/ceph/pull/57829
<details>
</details>

squid: cephadm: the user config is preferred during the bootstrap

---

doc/radosgw/s3/authentication.rst

backport tracker: https://tracker.ceph.com/issues/66839
---
backport of https://github.com/ceph/ceph/pull/58434
parent tracker: https://tracker.ceph.com/issues/42888

squid: doc/rgw: update s3 authentication

---

src/pybind/mgr/dashboard/frontend/cypress/e2e/common/global.feature.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/filesystems/snapshots.e2e-spec.feature
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-snapshots-list/cephfs-subvolume-snapshots-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-modal/form-modal.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/cd-form-modal-field-config.ts

backport tracker: https://tracker.ceph.com/issues/66737
---
backport of https://github.com/ceph/ceph/pull/58286
parent tracker: https://tracker.ceph.com/issues/66703

squid: mgr/dashboard: fix clone async validators with different groups

---

src/pybind/mgr/dashboard/controllers/rgw.py

backport tracker: https://tracker.ceph.com/issues/66425
---
backport of https://github.com/ceph/ceph/pull/57931
parent tracker: https://tracker.ceph.com/issues/66395

squid: mgr/dashboard: fix edit bucket failing in other selected gateways

---

src/pybind/mgr/dashboard/controllers/health.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/health.service.ts
src/pybind/mgr/dashboard/openapi.yaml

backport tracker: https://tracker.ceph.com/issues/66246
Conflicts:
mgr/dashboard/frontend/src/app/core/layouts/workbench-layout/workbench-layout.component.ts
mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts
- Hardware status and multi-cluster features are not included in reef, therefore this only affects the telemetry status
---
backport of https://github.com/ceph/ceph/pull/57070
parent tracker: https://tracker.ceph.com/issues/65643

reef: mgr/dashboard: fix readonly landingpage

---

qa/tasks/cephfs/test_admin.py

**NOTE:** Originally part of PR #57333 but these commits are moved here to keep only inter-dependent bug fixes in it.
First couple of commits on this PR branch are kept here for since latter commits depend on them. They'll vanish when this PR is rebased on latest main after merging of PR #57333. …

qa/cephfs: improvements for "mds fail" and "fs fail"

---

src/rgw/driver/rados/rgw_log_backing.h

initialize `fifo_tmp` to prevent the race on member variable `fifo` that was identified in 8fa844383f9c22e758f39ecdda74f70de054ad68
Fixes: https://tracker.ceph.com/issues/66880
<details>
</details>

rgw/datalog: fix LazyFIFO race fix

---

src/pybind/mgr/dashboard/frontend/cypress/e2e/common/urls.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/orchestrator/workflow/10-nfs-exports.e2e-spec.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/orchestrator/workflow/nfs/nfs-export.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/page-helper.po.ts
src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/models/nfs.fsal.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.scss
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-list/nfs-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-list/nfs-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/utils.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nfs.service.ts

Batch backport of nfs route separation PR with its regression and also carbon changes are not required therefore a conflict in navigation file.
https://tracker.ceph.com/issues/66643
https://tracker.ceph.com/issues/66875
Original PRs:
https://github.com/ceph/ceph/pull/56658
https://github.com/ceph/ceph/pull/58279
<details> …

Batch backport NFS route separation for cephfs and rgw             

---

do_cmake.sh
install-deps.sh

backport tracker: https://tracker.ceph.com/issues/66896
---
backport of https://github.com/ceph/ceph/pull/53849
parent tracker: https://tracker.ceph.com/issues/66895

reef: install-deps.sh, do_cmake.sh: almalinux is another el flavour

---

src/cephadm/cephadmlib/daemons/nvmeof.py
src/pybind/mgr/cephadm/inventory.py
src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/services/nvmeof.py
src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
src/pybind/mgr/cephadm/tests/test_cephadm.py
src/pybind/mgr/cephadm/tests/test_services.py
src/pybind/mgr/dashboard/services/nvmeof_client.py
src/pybind/mgr/dashboard/services/nvmeof_conf.py
src/pybind/mgr/dashboard/services/orchestrator.py
src/pybind/mgr/orchestrator/_interface.py
src/pybind/mgr/orchestrator/module.py
src/python-common/ceph/deployment/service_spec.py

Store the certificates to config-key stores and then later on used by dashboard 
to set-up the secure_channel for grpc nvmeof requests
By storing the certificates we can ensure that the dashboard nvmeof apis
will be configurable even if the deployments are not cephadm based …

mgr/dashboard: use secure_channel for grpc requests

---

src/pybind/mgr/dashboard/frontend/cypress/e2e/common/global.feature.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/filesystems/snapshots.e2e-spec.feature
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-snapshots-list/cephfs-subvolume-snapshots-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-modal/form-modal.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/cd-form-modal-field-config.ts

backport tracker: https://tracker.ceph.com/issues/66738
---
backport of https://github.com/ceph/ceph/pull/58286
parent tracker: https://tracker.ceph.com/issues/66703

reef: mgr/dashboard: fix clone async validators with different groups

---

src/pybind/mgr/dashboard/frontend/package-lock.json

backport tracker: https://tracker.ceph.com/issues/65170
---
backport of https://github.com/ceph/ceph/pull/56239
parent tracker: https://tracker.ceph.com/issues/65167

reef: mgr/dashboard: bump follow-redirects from 1.15.3 to 1.15.6 in /src/pybind/mgr/dashboard/frontend 

---

qa/tasks/mgr/dashboard/test_cephfs.py
src/pybind/mgr/dashboard/controllers/cephfs.py
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/cephfs.py

Introduce rename for the cephfs REST API controller, we can rename the existing file or directory by it.
Fixes: https://tracker.ceph.com/issues/66797 …

mgr/dashboard: add cephfs rename REST API

---

qa/tasks/cephfs/test_admin.py

This test deletes the CephFS already present on the cluster at the very
beginning and unmounts the first client beforehand. But it leaves the
second client mounted on this deleted CephFS that doesn't exist for the
rest of the test. And then at the very end of this test it attempts to
remount the second client (during tearDown()) which hangs and causes
test runner to crash.
Unmount the second client beforehand to prevent the bug and delete
mount_b object to avoid confusion for the readers in future about
whether or not 2nd mountpoint exists.
Fixes: https://tracker.ceph.com/issues/66077 …

qa/cephfs: fix test_single_path_authorize_on_nonalphanumeric_fsname

---

do_cmake.sh
install-deps.sh

backport tracker: https://tracker.ceph.com/issues/66897
---
backport of https://github.com/ceph/ceph/pull/53849
parent tracker: https://tracker.ceph.com/issues/66895

squid: install-deps.sh, do_cmake.sh: almalinux is another el flavour

---

src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/services.po.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts

Backporting nvmeof service confoguration with its regressions.
Hence,  a manual cherrypick of:
https://tracker.ceph.com/issues/66480
https://tracker.ceph.com/issues/66856
https://tracker.ceph.com/issues/66876
original PRs:
https://github.com/ceph/ceph/pull/57801
https://github.com/ceph/ceph/pull/58068/commits/1da0a4f8cb234ef84729c24cc9a82397361e9534
https://github.com/ceph/ceph/pull/57864/commits/27a8b2f2883fcc1fc4128b3e8995a7819a5ae51e
<details>
- …

Batch backport of nvmeof service configuration

---

src/pybind/mgr/dashboard/controllers/rgw.py

backport tracker: https://tracker.ceph.com/issues/66424
---
backport of https://github.com/ceph/ceph/pull/57931
parent tracker: https://tracker.ceph.com/issues/66395

reef: mgr/dashboard: fix edit bucket failing in other selected gateways

---

src/test/librbd/exclusive_lock/test_mock_PostAcquireRequest.cc
src/test/librbd/exclusive_lock/test_mock_PreAcquireRequest.cc
src/test/librbd/exclusive_lock/test_mock_PreReleaseRequest.cc

Backport https://github.com/ceph/ceph/pull/58466 to quincy as this popped up in regular (not arm64) `make check`.

quincy: test/librbd: clean up unused TEST_COOKIE variable

---

src/test/librbd/exclusive_lock/test_mock_PostAcquireRequest.cc
src/test/librbd/exclusive_lock/test_mock_PreAcquireRequest.cc
src/test/librbd/exclusive_lock/test_mock_PreReleaseRequest.cc

Backport https://github.com/ceph/ceph/pull/58466 to reef as this popped up in regular (not arm64) `make check`.

reef: test/librbd: clean up unused TEST_COOKIE variable

---

src/test/librbd/exclusive_lock/test_mock_PostAcquireRequest.cc
src/test/librbd/exclusive_lock/test_mock_PreAcquireRequest.cc
src/test/librbd/exclusive_lock/test_mock_PreReleaseRequest.cc

Backport https://github.com/ceph/ceph/pull/58466 to reef as this popped up in regular (not arm64) `make check`.

squid: test/librbd: clean up unused TEST_COOKIE variable

---

qa/standalone/mon/mkfs.sh
qa/standalone/mon/mon-cluster-log.sh

Fixing various failures in MON standalone test, e.g.,
test case involving mkfs command
and monitor + journal logs.
Fixes: https://tracker.ceph.com/issues/63784 …

qa/standalone/mon: Fix mkfs  test & TEST_LOG failures

---

do_cmake.sh
install-deps.sh

backport tracker: https://tracker.ceph.com/issues/66898
---
backport of https://github.com/ceph/ceph/pull/53849
parent tracker: https://tracker.ceph.com/issues/66895

quincy: install-deps.sh, do_cmake.sh: almalinux is another el flavour

---

ceph.spec.in
doc/install/get-packages.rst

backport tracker: https://tracker.ceph.com/issues/65031
---
backport of https://github.com/ceph/ceph/pull/50301
parent tracker: https://tracker.ceph.com/issues/65029

quincy: ceph.spec.in: add support for openEuler OS

---

src/librbd/Utils.cc
src/librbd/api/Group.cc

backport tracker: https://tracker.ceph.com/issues/65588
---
backport of https://github.com/ceph/ceph/pull/56987
parent tracker: https://tracker.ceph.com/issues/65573

quincy: librbd: make group and group snapshot IDs more random

---

qa/workunits/rbd/rbd_mirror_bootstrap.sh
qa/workunits/rbd/rbd_mirror_helpers.sh
src/test/rbd_mirror/test_mock_PoolReplayer.cc
src/tools/rbd_mirror/Mirror.cc
src/tools/rbd_mirror/PoolReplayer.cc

backport tracker: https://tracker.ceph.com/issues/65818
---
backport of https://github.com/ceph/ceph/pull/57082
parent tracker: https://tracker.ceph.com/issues/65487

quincy: rbd-mirror: clean up stale pool replayers and callouts better

---

src/osdc/Striper.cc
src/test/librbd/fsx.cc
src/test/librbd/test_librbd.cc

backport tracker: https://tracker.ceph.com/issues/66112
---
backport of https://github.com/ceph/ceph/pull/57433
parent tracker: https://tracker.ceph.com/issues/65813

quincy: librbd: don't crash on a zero-length read if buffer is NULL

---

src/common/options/rbd.yaml.in
src/librbd/api/Namespace.cc
src/librbd/api/Pool.cc
src/test/librbd/test_librbd.cc

backport tracker: https://tracker.ceph.com/issues/66115
---
backport of https://github.com/ceph/ceph/pull/56310
parent tracker: https://tracker.ceph.com/issues/64800

quincy: librbd: create rbd_trash object during pool initialization and namespace creation

---

src/librbd/api/DiffIterate.cc
src/test/librbd/test_librbd.cc

backport tracker: https://tracker.ceph.com/issues/66582
---
backport of https://github.com/ceph/ceph/pull/57973
parent tracker: https://tracker.ceph.com/issues/66418

quincy: librbd: diff-iterate shouldn't crash on an empty byte range

---

qa/tasks/ceph.py
qa/tasks/cephadm.py
qa/workunits/rbd/krbd_data_pool.sh

backport tracker: https://tracker.ceph.com/issues/66909
---
backport of https://github.com/ceph/ceph/pull/58507
parent tracker: https://tracker.ceph.com/issues/66886

quincy: qa: account for rbd_trash object in krbd_data_pool.sh + related ceph{,adm} task fixes

---

src/librbd/api/DiffIterate.cc
src/test/librbd/test_librbd.cc

backport tracker: https://tracker.ceph.com/issues/66745
---
backport of https://github.com/ceph/ceph/pull/58201
parent tracker: https://tracker.ceph.com/issues/66570

quincy: librbd: make diff-iterate in fast-diff mode aware of encryption

---

src/rgw/driver/rados/rgw_sal_rados.cc
src/test/rgw/rgw_multi/tests.py

backport tracker: https://tracker.ceph.com/issues/66919
---
backport of https://github.com/ceph/ceph/pull/56275
parent tracker: https://tracker.ceph.com/issues/64022

squid: rgw/multisite: allow PutACL replication.

---

src/rgw/driver/rados/rgw_log_backing.h

backport tracker: https://tracker.ceph.com/issues/66913
---
backport of https://github.com/ceph/ceph/pull/58491
parent tracker: https://tracker.ceph.com/issues/66880

squid: rgw/datalog: fix LazyFIFO race fix

---

src/rgw/driver/rados/rgw_notify.cc
src/rgw/rgw_admin.cc
src/rgw/rgw_pubsub.cc
src/rgw/rgw_pubsub.h
src/test/cli/radosgw-admin/help.t
src/test/rgw/bucket_notification/test_bn.py

backport tracker: https://tracker.ceph.com/issues/66497
---
backport of https://github.com/ceph/ceph/pull/57898
parent tracker: https://tracker.ceph.com/issues/66404

squid: rgw/admin/notification: add command to dump notifications

---

doc/cephfs/mount-using-kernel-driver.rst

Edit the section called "Is mount helper present?", the title of which prior to this commit was "Is mount helper is present?". Other small disambiguating improvements have been made to the text in the section. An unselectable prompt has been added before a command. …

doc/cephfs: edit "is mount helper present"

---

src/os/bluestore/BlueFS.cc

backport tracker: https://tracker.ceph.com/issues/64591
---
backport of https://github.com/ceph/ceph/pull/55700
parent tracker: https://tracker.ceph.com/issues/64533

squid: os/bluestore: fix the problem of l_bluefs_log_compactions double recording

---

src/osd/ECBackend.cc

backport tracker: https://tracker.ceph.com/issues/66143
--------
backport of #57137
parent tracker: https://tracker.ceph.com/issues/65686

squid: osd: CEPH_OSD_OP_FLAG_BYPASS_CLEAN_CACHE flag is passed from ECBackend

---

src/osd/OSD.cc
src/osd/OSD.h
src/osd/scheduler/OpScheduler.h
src/osd/scheduler/mClockScheduler.h
src/osd/scrubber/pg_scrubber.cc
src/osd/scrubber/pg_scrubber.h

backport tracker: https://tracker.ceph.com/issues/66421
---
backport of https://github.com/ceph/ceph/pull/51171
parent tracker: https://tracker.ceph.com/issues/66420

squid: osd/scrub: Change scrub cost to average object size

---

doc/cephfs/mount-using-kernel-driver.rst

Edit the section called "Is mount helper present?", the title of which prior to this commit was "Is mount helper is present?". Other small disambiguating improvements have been made to the text in the section. An unselectable prompt has been added before a command.
(cherry picked from commit 0ebfb3eda8e2fc88662530bbddc84f2efcc4e13c) …

squid: doc/cephfs: edit "is mount helper present"

---

doc/cephfs/mount-using-kernel-driver.rst

Edit the section called "Is mount helper present?", the title of which prior to this commit was "Is mount helper is present?". Other small disambiguating improvements have been made to the text in the section. An unselectable prompt has been added before a command.
(cherry picked from commit 0ebfb3eda8e2fc88662530bbddc84f2efcc4e13c) …

reef: doc/cephfs: edit "is mount helper present"

---

doc/cephfs/mount-using-kernel-driver.rst

Edit the section called "Is mount helper present?", the title of which prior to this commit was "Is mount helper is present?". Other small disambiguating improvements have been made to the text in the section. An unselectable prompt has been added before a command.
(cherry picked from commit 0ebfb3eda8e2fc88662530bbddc84f2efcc4e13c) …

quincy: doc/cephfs: edit "is mount helper present"

---

src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/extent_placement_manager.cc
src/crimson/os/seastore/journal/record_submitter.cc
src/crimson/os/seastore/seastore_types.cc
src/crimson/os/seastore/seastore_types.h

Follow up https://github.com/ceph/ceph/pull/57788, quote:
```
tier-main: iops=3969.97,depth=1.01,batch=1.32,bwMiB=29.62,sizeB=7824.19(3460.97,1448.24,2914.98)
inline: iops=2077.98,depth=1.02,batch=1.42,bwMiB=13.24,sizeB=6682.12(2075.60,2667.54,1938.98)
...
ooldata: iops=1891.98,depth=1.00,batch=1.22,bwMiB=16.38,sizeB=9078.53(4982.53,*109.08,3986.92*)
...
```
Under a short-time fio-rbd random write workload, the OSD log (SeaStore) roughly shows ~55% of the bandwidth comes from "ooldata", and ~45% of which comes from the unnecessary metadata+padding. This means ~25% of the bandwidth in this workload is unnecessary.
----
This PR tries to remove the unnecessary padding,
before this PR (the same random-write workload), e.g.:
```
tier-main: …
```

crimson/os/seastore: write ool extents without padding

---

src/crimson/os/seastore/async_cleaner.cc
src/crimson/os/seastore/async_cleaner.h
src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/seastore.h
src/crimson/os/seastore/seastore_types.h
src/crimson/os/seastore/transaction_manager.cc
src/crimson/os/seastore/transaction_manager.h
src/crimson/osd/osd.cc
src/crimson/tools/store_nbd/tm_driver.cc
src/crimson/tools/store_nbd/tm_driver.h
src/test/crimson/seastore/transaction_manager_test_state.h

Also minor improvements to the original stats to make them clear.
Now the report looks like (included https://github.com/ceph/ceph/pull/58250, fio random writes):
```
INFO  2024-07-09 10:40:21,725 [shard  0:main] seastore_epm - ExtentPlacementManager::get_device_stats:
tier-main: iops=5734.93,depth=1.25,batch=1.11,bwMiB=29.04,sizeB=5309.09(3009.69,828.42,1470.98)
inline: iops=3097.46,depth=1.01,batch=1.21,bwMiB=18.73,sizeB=6342.02(2084.70,1533.81,2723.52)
oolmdat: iops=0.00,depth=-nan,batch=-nan,bwMiB=0.00,sizeB=-nan(-nan,-nan,-nan)
ooldata: iops=2637.47,depth=1.54,batch=1.00,bwMiB=10.30,sizeB=4096.00(4096.00,0.00,0.00)
mainmdat: iops=0.00,depth=-nan,batch=-nan,bwMiB=0.00,sizeB=-nan(-nan,-nan,-nan)
maindata: iops=0.00,depth=-nan,batch=-nan,bwMiB=0.00,sizeB=-nan(-nan,-nan,-nan)
MUTATE: …
```

crimson/os/seastore: track transactions/conflicts/outstanding periodically

---

src/crimson/os/seastore/btree/fixed_kv_btree.h

crimson/os/seastore/btree: interrupt transactions immediately when getting children

---

src/pybind/mgr/dashboard/controllers/multi_cluster.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-form/multi-cluster-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-form/multi-cluster-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/multi-cluster.service.ts
src/pybind/mgr/dashboard/openapi.yaml

After testing multi-cluster feature with new mgtm-gateway service, some workflows were not properly set to have the multi-cluster feature behind a proxy or could be improven, this PR cleans and fixes the following:
- Fix multi-cluster form password field as required
- Enable editing of Cluster API URL field on multi-cluster's edit form …

mgr/dashboard: Multi-cluster cleanup

---

src/pybind/mgr/dashboard/controllers/cephfs.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.ts

backport tracker: https://tracker.ceph.com/issues/66871
---
backport of https://github.com/ceph/ceph/pull/58303
parent tracker: https://tracker.ceph.com/issues/66718

reef: mgr/dashboard: nfs export enhancement for CEPHFS 

---

src/client/Client.cc

cephfs: fix issues/56288
fix a crash in cephfs client：when doing a readdir operation in _readdir_cache_cb, the memory that dir pointed maybe already  freeed
Fixes: https://tracker.ceph.com/issues/56288
Signed-off-by: Tod Chen <chentao.2022@bytedance.com>
@vshankar

client: retry readdir if dir is invalidated

---

qa/suites/fs/multiclient/clusters/1-mds-2-client.yaml
qa/tasks/cephfs/test_misc.py
src/mds/MDSDaemon.cc
src/mds/MDSRank.cc
src/mds/SessionMap.cc

Daemon commands are getting executed ignoring the ceph flags
like `--help, --status` etc.
For eg: `ceph --admin-daemon $socketfile client evict --help` is run 
ignoring the `--help` flag which the user doesn't want and can be 
dangerous sometimes as with the above command which will
terminate all active connections which isn't supposed to be. 
This PR fixes the issues using these solutions:
(1) client evict without filter is forbidden
(2) SessionFilter::parse is modified to support id=* (id=0 is not allowed)
(3) Invalid id error is handled
User can use client evict id=* to evict all clients.
Fixes: https://tracker.ceph.com/issues/58619 …

mds: fix session/client evict command.

---

src/test/rgw/test_multi.md

Update test_multi.md documentation with configuration example file and example on how to filter tests based on attributes. …

src/test/rgw/test_multlti.md:update documentation for multi tests run

---

doc/dev/encoding.rst

Improve "Principles for format change" in doc/dev/encoding.rst. This commit started as a response to Anthony D'Atri's suggestion here: https://github.com/ceph/ceph/pull/58299/files#r1656985564
Review of this section suggested to me that certain minor English usage improvements would be of benefit. The numbered lists in this section could still be made a bit clearer.
(cherry picked from commit 570797e5588b67b8c72e5297b61f84d9aa48dc45) …

squid: doc/dev: edit "Principles for format change"

---

doc/dev/encoding.rst

Improve "Principles for format change" in doc/dev/encoding.rst. This commit started as a response to Anthony D'Atri's suggestion here: https://github.com/ceph/ceph/pull/58299/files#r1656985564
Review of this section suggested to me that certain minor English usage improvements would be of benefit. The numbered lists in this section could still be made a bit clearer.
(cherry picked from commit 570797e5588b67b8c72e5297b61f84d9aa48dc45) …

reef: doc/dev: edit "Principles for format change"

---

doc/dev/encoding.rst

Improve "Principles for format change" in doc/dev/encoding.rst. This commit started as a response to Anthony D'Atri's suggestion here: https://github.com/ceph/ceph/pull/58299/files#r1656985564
Review of this section suggested to me that certain minor English usage improvements would be of benefit. The numbered lists in this section could still be made a bit clearer.
(cherry picked from commit 570797e5588b67b8c72e5297b61f84d9aa48dc45) …

quincy: doc/dev: edit "Principles for format change"

---

src/cls/rbd/cls_rbd_types.h
src/librbd/api/Group.cc
src/test/librados_test_stub/TestMemIoCtxImpl.cc
src/test/librbd/test_Groups.cc
src/test/pybind/test_rbd.py

backport tracker: https://tracker.ceph.com/issues/66589
---
backport of https://github.com/ceph/ceph/pull/58074 and https://github.com/ceph/ceph/pull/58300
parent tracker: https://tracker.ceph.com/issues/66300

squid: librbd: disallow group snap rollback if memberships don't match

---

src/librbd/api/DiffIterate.cc
src/test/librbd/test_librbd.cc

backport tracker: https://tracker.ceph.com/issues/66584
---
backport of https://github.com/ceph/ceph/pull/57973
parent tracker: https://tracker.ceph.com/issues/66418

squid: librbd: diff-iterate shouldn't crash on an empty byte range

---

qa/tasks/thrashosds-health.yaml

RADOS main suite has been failing due to
a lack of whitelisting for
`noscrub` and `nodeep-scrub`
Fixes: https://tracker.ceph.com/issues/65824 …

qa/suites/rados/thrash-old-clients: Add noscrub, nodeep-scrub to ignorelist

---

qa/workunits/cephtool/test.sh

This is more of a workaround to an issue in the infrastructure
where files are made with root privileges, causing permission
issues when operations are used on them without sudo.
Fixes: https://tracker.ceph.com/issues/66881 …

qa/workunits/cephtool: add extra privileges to cephtool script

---

src/pybind/mgr/smb/fs.py
src/pybind/mgr/smb/module.py
src/pybind/mgr/smb/tests/test_fs.py

Depends on #57394
Implement custom TTL cache for CephFS path resolver
- Added TTLCache class to manage cache with time-to-live expiration.
- Integrated TTLCache into CachingCephFSPathResolver. …

mgr/smb: cache subvolume (& subvolume group) path lookups

---

src/pybind/mgr/smb/handler.py
src/pybind/mgr/smb/tests/test_smb.py

Fix an error condition in the `ceph smb show` command.  When the ceph smb show command was run after creating a usersgroups and cluster resource but no shares resources the following traceback was seen:
```
Error EINVAL: Traceback (most recent call last):
File "/usr/share/ceph/mgr/mgr_module.py", line 1910, in
_handle_command
return CLICommand.COMMANDS[cmd['prefix']].call(self, cmd, inbuf)
File "/usr/share/ceph/mgr/mgr_module.py", line 507, in call
return self.func(mgr, **kwargs)
File "/usr/share/ceph/mgr/object_format.py", line 592, in
_format_response
robj = f(*args, **kwargs)
File "/usr/share/ceph/mgr/smb/module.py", line 258, in show
resources = self._handler.matching_resources(resource_names)
File "/usr/share/ceph/mgr/smb/handler.py", line 403, in
matching_resources
return …
```

mgr/smb: fix ceph smb show when a cluster has not associated shares

---

qa/tasks/cephfs/test_scrub_checks.py
src/common/admin_finisher.h
src/common/admin_socket.cc
src/common/admin_socket.h
src/mds/MDSDaemon.cc
src/mds/MDSDaemon.h
src/mds/MDSRank.cc
src/mds/MDSRank.h
src/mds/MDSRankQuiesce.cc
src/messages/MMonCommandAck.h
src/osd/OSD.cc
src/osd/OSD.h
src/osd/PG.h
src/osd/PrimaryLogPG.cc
src/osd/PrimaryLogPG.h

backport tracker: https://tracker.ceph.com/issues/66542
---
backport of https://github.com/ceph/ceph/pull/57673
parent tracker: https://tracker.ceph.com/issues/66184

squid: mds: dump formatter even for errors

---

src/mds/QuiesceDbManager.cc
src/test/mds/TestQuiesceDb.cc

backport tracker: https://tracker.ceph.com/issues/66572
---
backport of https://github.com/ceph/ceph/pull/57980
parent tracker: https://tracker.ceph.com/issues/66438

squid: mds/quiesce-db: calculate_quiesce_map: aggregate quiesce roots' TTL as `max`

---

src/mds/QuiesceDbManager.cc
src/mds/QuiesceDbManager.h
src/test/mds/TestQuiesceDb.cc

backport tracker: https://tracker.ceph.com/issues/66585
---
backport of https://github.com/ceph/ceph/pull/57946
parent tracker: https://tracker.ceph.com/issues/66406

squid: mds: QuiesceDbManager: mark next retry event during bootstrap

---

src/mds/Locker.cc

backport tracker: https://tracker.ceph.com/issues/66623
---
backport of https://github.com/ceph/ceph/pull/56828
parent tracker: https://tracker.ceph.com/issues/64977

squid: mds: do remove the cap when seqs equal or larger than last issue

---

src/mds/QuiesceDb.h
src/mds/QuiesceDbManager.h

backport tracker: https://tracker.ceph.com/issues/66619
---
backport of https://github.com/ceph/ceph/pull/57993
parent tracker: https://tracker.ceph.com/issues/66449

squid: mds: initialize epoch for quiescedb

---

qa/suites/fs/cephadm/multivolume/conf

backport tracker: https://tracker.ceph.com/issues/66325
---
backport of https://github.com/ceph/ceph/pull/57477
parent tracker: https://tracker.ceph.com/issues/66029

squid: qa: enable debug logs for fs:cephadm:multivolume subsuite

---

qa/tasks/cephfs/test_subvolume.py

backport tracker: https://tracker.ceph.com/issues/66385
---
backport of https://github.com/ceph/ceph/pull/57877
parent tracker: https://tracker.ceph.com/issues/66355

squid: qa: correct json lookup for new `lock path` output

---

qa/cephfs/conf/mon.yaml
qa/suites/fs/cephadm/renamevolume/conf
qa/suites/fs/mirror-ha/conf
qa/suites/fs/mirror/conf
qa/suites/fs/top/conf

backport tracker: https://tracker.ceph.com/issues/66386
---
backport of https://github.com/ceph/ceph/pull/57879
parent tracker: https://tracker.ceph.com/issues/65976

squid: qa: disable mon_warn_on_pool_no_app in fs suite

---

qa/suites/fs/functional/tasks/forward-scrub.yaml

backport tracker: https://tracker.ceph.com/issues/65988
---
backport of https://github.com/ceph/ceph/pull/56699
parent tracker: https://tracker.ceph.com/issues/48562

squid: qa: ignore cluster warnings generated from forward-scrub task

---

src/cephadm/cephadm.py

use importlib.metadata for querying ceph_iscsi's version and fallback to pkg_resources. as the former is only available in Python 3.8, while the latter is deprecated.
Refs https://tracker.ceph.com/issues/66201
This commit is functionally equivalent to a Reef-targeted backport of https://github.com/ceph/ceph/pull/57685. …

reef: cephadm: use importlib.metadata for querying ceph_iscsi's version

---

src/mds/Locker.cc

backport tracker: https://tracker.ceph.com/issues/66625
---
backport of https://github.com/ceph/ceph/pull/56828
parent tracker: https://tracker.ceph.com/issues/64977

reef: mds: do remove the cap when seqs equal or larger than last issue

---

qa/cephfs/overrides/pg_health.yaml

backport tracker: https://tracker.ceph.com/issues/65845
---
backport of https://github.com/ceph/ceph/pull/57165
parent tracker: https://tracker.ceph.com/issues/65700

reef: qa: ignore variation of PG_DEGRADED health warning

---

qa/suites/fs/cephadm/multivolume/conf

backport tracker: https://tracker.ceph.com/issues/66324
---
backport of https://github.com/ceph/ceph/pull/57477
parent tracker: https://tracker.ceph.com/issues/66029

reef: qa: enable debug logs for fs:cephadm:multivolume subsuite

---

qa/tasks/cephfs/test_failover.py

backport tracker: https://tracker.ceph.com/issues/66043
---
backport of https://github.com/ceph/ceph/pull/57329
parent tracker: https://tracker.ceph.com/issues/65837

reef: qa: unmount clients before damaging the fs

---

src/mds/MetricAggregator.cc
src/mds/MetricAggregator.h
src/messages/MClientMetrics.h

backport tracker: https://tracker.ceph.com/issues/66190
---
backport of https://github.com/ceph/ceph/pull/57081
parent tracker: https://tracker.ceph.com/issues/65658

reef: mds: use regular dispatch for processing metrics

---

src/mds/Beacon.cc
src/mds/Beacon.h
src/mds/MDSDaemon.cc
src/mds/MDSRank.cc
src/mds/MetricAggregator.cc
src/mon/MonClient.cc
src/msg/Dispatcher.h
src/msg/Messenger.h

backport tracker: https://tracker.ceph.com/issues/66194
---
backport of https://github.com/ceph/ceph/pull/57469
parent tracker: https://tracker.ceph.com/issues/66014

reef: mds: use regular dispatch for processing beacons

---

qa/cephfs/conf/mon.yaml
qa/suites/fs/cephadm/renamevolume/conf
qa/suites/fs/mirror-ha/conf
qa/suites/fs/mirror/conf
qa/suites/fs/top/conf

backport tracker: https://tracker.ceph.com/issues/66387
---
backport of https://github.com/ceph/ceph/pull/57879
parent tracker: https://tracker.ceph.com/issues/65976

reef: qa: disable mon_warn_on_pool_no_app in fs suite

---

qa/suites/fs/fscrypt/tasks/1-tests/fscrypt-common.yaml
qa/tasks/cephfs/test_fscrypt.py
src/mds/CDentry.cc
src/mds/CDir.cc
src/tools/cephfs/JournalTool.cc
src/tools/cephfs/JournalTool.h

backport tracker: https://tracker.ceph.com/issues/66592
---
backport of https://github.com/ceph/ceph/pull/55792
parent tracker: https://tracker.ceph.com/issues/64602

reef: tools/cephfs: recover alternate_name of dentries from journal

---

src/librbd/api/DiffIterate.cc
src/test/librbd/test_librbd.cc

backport tracker: https://tracker.ceph.com/issues/66744
---
backport of https://github.com/ceph/ceph/pull/58201
parent tracker: https://tracker.ceph.com/issues/66570

squid: librbd: make diff-iterate in fast-diff mode aware of encryption

---

src/os/bluestore/BlueRocksEnv.h

Fixes https://tracker.ceph.com/issues/66717.
How is it possible that we are mixing BlueFS and posix operations?
BlueRocksEnv implements rocksdb::Env interface.
To make things simpler it inherits from rocksdb::EnvWrapper. The rocksdb::EnvWrapper is initialized from DefaultEnv, which brings default implementation for threads and files.
We override file-related interface.
The problem is when we forget to implement something, or if rocksdb::Env interface gets expanded. The function returns ENOTSUPP, and rocksdb can handle it. But it does not matter, because it is implemented in DefaultEnv.
In future we should drop inheriting from EnvWrapper and call DefaultEnv directly wherever we need. …

os/bluestore: Fix BlueRocksEnv attempts to use POSIX

---

src/cephadm/cephadmlib/daemons/nvmeof.py
src/pybind/mgr/cephadm/agent.py
src/pybind/mgr/cephadm/inventory.py
src/pybind/mgr/cephadm/migrations.py
src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/serve.py
src/pybind/mgr/cephadm/service_discovery.py
src/pybind/mgr/cephadm/services/monitoring.py
src/pybind/mgr/cephadm/services/nvmeof.py
src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
src/pybind/mgr/cephadm/tests/test_cephadm.py
src/pybind/mgr/cephadm/tests/test_migration.py
src/pybind/mgr/cephadm/tests/test_services.py
src/pybind/mgr/dashboard/services/nvmeof_client.py
src/pybind/mgr/dashboard/services/nvmeof_conf.py
src/pybind/mgr/dashboard/services/orchestrator.py
src/pybind/mgr/orchestrator/_interface.py
src/pybind/mgr/orchestrator/module.py
src/python-common/ceph/deployment/service_spec.py

Backport of https://github.com/ceph/ceph/pull/55564 and https://github.com/ceph/ceph/pull/57712
<details>
</details>

squid: mgr/cephadm: Cert Store + use secure_channel for grpc requests

---

doc/man/8/radosgw-admin.rst
src/rgw/driver/rados/rgw_bucket.cc
src/rgw/driver/rados/rgw_reshard.cc

Adds reshard status to `radosgw-admin bucket stats ...`. Renames the variable max_entries to max_op_entries to clarify that it's not the maximum number of entries wanted in a bucket index shard. Does some other minor clean-ups. …

rgw: add reshard status to bucket stats plus minor misc items

---

src/rgw/driver/rados/rgw_period.cc
src/rgw/driver/rados/rgw_rest_realm.cc
src/rgw/driver/rados/rgw_zone.cc
src/rgw/rgw_admin.cc
src/rgw/rgw_asio_frontend.cc

outstanding requests may take arbitrarily long to complete. instead of waiting for everything to complete successfully before pause() returns, close all client connections so their requests fail quickly
this matches the behavior of stop() for radosgw shutdown/restart. this should help to minimize the downtime of realm reloads where the frontend isn't accepting connections or processing new requests
<details>
- …

rgw/beast: realm reload closes connections so requests drain quickly

---

src/rgw/rgw_rest_s3.cc

GetBucketLocation API is returning an XML as a body so it deserves to have a content-type in the headers.
Fixes: https://tracker.ceph.com/issues/66842

rgw: add missing content-type for RGWGetBucketLocation

---

src/rgw/driver/rados/rgw_reshard.cc

The admin has control over the rgw_max_objs_per_shard configuration option. Currently the minimum objects per shard is hard-coded. If that max is lowered then we need to be certain that the minimum is an appropriate value, certainly less than the max.
Fixes: https://tracker.ceph.com/issues/66757 …

rgw: make sure min objs per shard is appropriate

---

src/test/neorados/watch_notify.cc

Watch-notify tests involve waiting for a notification within a certain timeout period. However, if an error occurs before receiving the notification acknowledgment, attempting to reconnect may lead to unpredictable errors.
Fixes: https://tracker.ceph.com/issues/65449 …

test/neorados: timeout test won't reconnect at timeout

---

src/erasure-code/ErasureCodePlugin.cc
src/erasure-code/clay/ErasureCodePluginClay.cc
src/erasure-code/isa/ErasureCodePluginIsa.cc
src/erasure-code/jerasure/ErasureCodePluginJerasure.cc
src/erasure-code/lrc/ErasureCodePluginLrc.cc
src/erasure-code/shec/ErasureCodePluginShec.cc

When sanitizer is enabled, unittest_erasure_code_shec_thread shows,
```
=================================================================
==737674==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 1360 byte(s) in 5 object(s) allocated from:
#0 0xaaaadddffb08 in operator new(unsigned long) (/root/ceph/build/bin/unittest_erasure_code_shec_thread+0x1bfb08) (BuildId: 187a0067c45bf30f4d0bd2df83a32e0127ef03a1)
https://github.com/ceph/ceph/pull/1 0xffff800bb004 in __erasure_code_init /root/ceph/src/erasure-code/shec/ErasureCodePluginShec.cc:81:36
https://github.com/ceph/ceph/pull/2 0xaaaadde08de0 in thread1(void*) /root/ceph/src/test/erasure-code/TestErasureCodeShec_thread.cc:100:5
https://github.com/ceph/ceph/pull/3 0xffff7f45d5c4 in start_thread nptl/./nptl/pthread_create.c:442:8 …
```

ec: free plugin memory when it destructs and repeated loads

---

src/script/cpatch
src/script/cpatch.py

Often the differences between a base container image and the build being used as the cpatch source result in a new image that fails to bootstrap a cluster.  This is usually caused by incompatibilities between the binaries and libraries in the new image or (in the case of centos 9 based images) by python packages being patched into the wrong directory for the base image)
This PR changes cpatch to ensure that a more complete set of binaries and libraries are replaced in the base image.
It initially changed only the shell script version of cpatch and then when the python replacement was discovered, the same changes were made to that script.
Both versions of the script were tested with multiple components selected to patch and with no components selected (equivalent to --all)
- To sign and …

cpatch: Search base image when patching files.

---

src/client/fuse_ll.cc

backport tracker: https://tracker.ceph.com/issues/66200
---
backport of https://github.com/ceph/ceph/pull/57170
parent tracker: https://tracker.ceph.com/issues/62664

reef: client: set LIBMOUNT_FORCE_MOUNT2=always

---

src/mds/Server.cc
src/mds/Server.h

backport tracker: https://tracker.ceph.com/issues/66614
---
backport of https://github.com/ceph/ceph/pull/57754
parent tracker: https://tracker.ceph.com/issues/63265

reef: mds: set the proper extra bl for the create request

---

src/mds/CInode.cc
src/mds/CInode.h

backport tracker: https://tracker.ceph.com/issues/66275
---
backport of https://github.com/ceph/ceph/pull/57354
parent tracker: https://tracker.ceph.com/issues/64730

reef: mds: relax divergent backtrace scrub failures for replicated ancestor inodes

---

qa/tasks/cephfs/test_snap_schedules.py

backport tracker: https://tracker.ceph.com/issues/66670
---
backport of https://github.com/ceph/ceph/pull/57034
parent tracker: https://tracker.ceph.com/issues/65564

reef: qa: cleanup snapshots before subvolume delete

---

qa/suites/fs/functional/tasks/forward-scrub.yaml

backport tracker: https://tracker.ceph.com/issues/65987
---
backport of https://github.com/ceph/ceph/pull/56699
parent tracker: https://tracker.ceph.com/issues/48562

reef: qa: ignore cluster warnings generated from forward-scrub task

---

src/pybind/mgr/dashboard/controllers/cephfs.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.ts

backport tracker: https://tracker.ceph.com/issues/66872
---
backport of https://github.com/ceph/ceph/pull/58303
parent tracker: https://tracker.ceph.com/issues/66718

squid: mgr/dashboard: nfs export enhancement for CEPHFS 

---

doc/cephfs/mount-using-fuse.rst
doc/cephfs/mount-using-kernel-driver.rst

Improve the first twenty percent of doc/cephfs/mount-using-fuse.rst. This commit changes the text so that it is clearer that FUSE is an alternative to mounting CephFS with the kernel driver. This commit also links to the kernel driver page from the "FUSE-mount" page. …

doc/cephfs: improve mount-using-fuse

---

src/mds/MetricAggregator.cc
src/mds/MetricAggregator.h
src/messages/MClientMetrics.h

backport tracker: https://tracker.ceph.com/issues/66188
---
backport of https://github.com/ceph/ceph/pull/57081
parent tracker: https://tracker.ceph.com/issues/65658

squid: mds: use regular dispatch for processing metrics

---

doc/rados/operations/health-checks.rst
src/blk/BlockDevice.cc
src/blk/BlockDevice.h
src/blk/kernel/KernelDevice.cc
src/common/options/global.yaml.in
src/mon/PGMap.cc
src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h

Warning added for slow operations and stalled read in BlueStore. User can control how much time the warning should persist after last occurence and maximum number of operations as a threshold will be considered for the warning.
Fixes: https://tracker.ceph.com/issues/62500 …

os/bluestore: Warning added for slow operations and stalled read

---

src/os/bluestore/BlueStore.cc

backport tracker: https://tracker.ceph.com/issues/63316
---
backport of https://github.com/ceph/ceph/pull/54155
parent tracker: https://tracker.ceph.com/issues/63308

quincy: os/bluestore: fix crash caused by dividing by 0

---

src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/os/bluestore/bluefs_types.cc
src/os/bluestore/bluefs_types.h
src/test/objectstore/test_bluefs.cc

backport tracker: https://tracker.ceph.com/issues/65358
--------
backport of #50216 
parent tracker: https://tracker.ceph.com/issues/58759

quincy: os/bluestore: expand BlueFS log if available space is insufficient

---

PendingReleaseNotes
qa/standalone/ceph-helpers.sh
qa/standalone/mon/mon-cluster-log.sh
src/common/options/mon.yaml.in
src/mon/LogMonitor.cc
src/mon/LogMonitor.h

backport tracker: https://tracker.ceph.com/issues/65942
---
backport of https://github.com/ceph/ceph/pull/47502
parent tracker: https://tracker.ceph.com/issues/57061

quincy: mon/LogMonitor: Use generic cluster log level config

---

src/osd/ECBackend.cc

backport tracker: https://tracker.ceph.com/issues/66144
--------
backport of #57137
parent tracker: https://tracker.ceph.com/issues/65686

quincy: osd: CEPH_OSD_OP_FLAG_BYPASS_CLEAN_CACHE flag is passed from ECBackend

---

src/pybind/mgr/pg_autoscaler/module.py

backport tracker: https://tracker.ceph.com/issues/66000
---
backport of https://github.com/ceph/ceph/pull/54708
parent tracker: https://tracker.ceph.com/issues/59670

quincy: mgr/pg_autoscaler: add check for norecover flag

---

src/os/bluestore/BlueStore.cc

backport tracker: https://tracker.ceph.com/issues/65936
--------
backport of #49438
parent tracker: https://tracker.ceph.com/issues/58274

quincy: os/bluestore: set rocksdb iterator bounds for Bluestore::_collection_list()

---

src/crimson/os/seastore/transaction_manager.cc

Consider the following scene:
1. Trans.A writes the final record of Segment S, in which it overwrite another extent E in the same segment S;
2. Before Trans.A "complete_commit", Trans.B tries to rewrite new records and roll the segments, which closes Segment S;
3. Before Trans.A "complete_commit", a new cleaner Transaction C tries to clean the segment;
In this scenario, C might see a part of extent E's laddr space mapped to another location within the same segment S. This is actually a valid case.
Fixes: https://tracker.ceph.com/issues/66924 …

crimson/os/seastore/transaction_manager: consider inconsistency between backrefs and lbas acceptable when cleaning segments

---

src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/create-cluster.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/osds.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/common/urls.po.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster-review.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster-review.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-form/osd-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-form/osd-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/core/auth/login/login.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/core/auth/login/login.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/osd.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/icons.enum.ts

backport tracker:
https://tracker.ceph.com/issues/66645
<hr style="borser:2px solid grey"/>
backport of #57927
parent tracker: https://tracker.ceph.com/issues/66344
<hr style="borser:2px solid grey"/>
**Conflicts**
File - `app.constants.ts`
removed below code - 
`this.CONNECT = $localize`Connect`;
this.DISCONNECT = $localize`Disconnect`;
this.RECONNECT = $localize`Reconnect`;`
<hr style="borser:2px solid grey"/>
worked on expand cluster screen hide/show and persisting osd form values
Fixes: https://tracker.ceph.com/issues/66344
(cherry picked from commit aa4d6b58459079a3b59ffdd1c9913c0a07a1549a)
- If …

squid: mgr/dashboard: Expand Cluster improvements   

---

src/pybind/mgr/dashboard/controllers/cephfs.py
src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-group/cephfs-subvolume-group.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/icons.enum.ts

backport tracker: https://tracker.ceph.com/issues/67003
---
backport of https://github.com/ceph/ceph/pull/58441
parent tracker: https://tracker.ceph.com/issues/67001

reef: mgr/dashboard: add NFS export button for subvolume/ grp

---

src/rgw/driver/rados/rgw_rados.cc

set_attrs() needs the ACLOwner, etag, content-type and storage class for the bucket index update. if those attrs aren't being updated, consult their existing attrs in state->attrset
Fixes: https://tracker.ceph.com/issues/64173
<details>
</details>

rgw/rados: set_attrs() falls back to existing attrs for index update

---

qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_basic.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_domain.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_res_basic.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_res_dom.yaml
src/pybind/mgr/mgr_module.py
src/pybind/mgr/smb/config_store.py
src/pybind/mgr/smb/handler.py
src/pybind/mgr/smb/module.py
src/pybind/mgr/smb/proto.py
src/pybind/mgr/smb/sqlite_store.py
src/pybind/mgr/smb/tests/test_handler.py

Add a new store backend for internal smb module configuration resources. This layer is based on the Ceph MGR's sqlite3 db stored in RADOS. The aim is to improve the performance with regards to searching certain fields of the resources for duplicate values, mainly to prevent the same cluster + share name pair being used for different share resources. This uses sqlite3's JSON support and indexes to achieve the performance improvement.
In order to to significantly change the module's stance with regards to potentially sensitive information the db store provides a subclass that can mirror objects in a different store. We use this to keep all the possibly sensitive info in the mon config key store (like how cephadm stores certs etc). …

mgr/smb: add sqlite internal store backend for smb mgr module

---

src/osd/OSD.cc
src/osd/OSD.h

* `track_pools_and_pg_num_changes()` is moved into a separate method
* `track_pools_and_pg_num_changes()` inner logic is moved into a separate method 
* Map gap case is now properly handled, `last_map` should start with the newest map we have.
Fixes: https://tracker.ceph.com/issues/63881
_Example fix usage after letting osd.2 hit a map gap while creating 2 pools and changing pg_num in the meanwhile:_
```
2023-12-21T14:23:22.252+0000 7faea797f700 10 osd.2 23 track_pools_and_pg_num_changes can't get previous map 122 first start of this osd after a map gap
2023-12-21T14:23:22.252+0000 7faea797f700 10 osd.2 23 track_pools_and_pg_num_changes recording pool 2 pg_num 1 -> 3
2023-12-21T14:23:22.252+0000 7faea797f700 10 osd.2 23 track_pools_and_pg_num_changes recording new pool 3 pg_num 1 …
```

osd/OSD: rewrite track_pools_and_pg_num_changes logic

---

src/blk/aio/aio.cc
src/blk/aio/aio.h
src/blk/kernel/KernelDevice.cc
src/blk/kernel/io_uring.cc
src/blk/kernel/io_uring.h
src/test/objectstore/store_test.cc

This is a revival of https://github.com/ceph/ceph/pull/44065
Includes some fixes and UT.
Fixes: https://tracker.ceph.com/issues/64966 …

blk/aio: fix long batch (64+K entries) submission.

---

src/rgw/driver/rados/rgw_rados.cc
src/test/rgw/rgw_multi/tests.py

if a copy_object is executed on a replicated object, it fails to sync the copied object to the original source zone where the source object was first written and replicated from. this is because copy_object retains source attrs by default. when a get_obj() is issued from a fetch_remote_obj() call during sync, we check for this RGW_ATTR_OBJ_REPLICATION_TRACE and if that destination zone is already present in the trace, we return NOT_MODIFIED error, thus failing to replicate the copied object.
https://tracker.ceph.com/issues/66983 …

rgw/multisite: don't retain RGW_ATTR_OBJ_REPLICATION_TRACE attr on copy_object

---

src/test/lazy-omap-stats/CMakeLists.txt
src/test/lazy-omap-stats/lazy_omap_stats_test.cc
src/test/lazy-omap-stats/lazy_omap_stats_test.h

This test is currently plagued by
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86164 so let's move to boost::regex, at least until that bug is resolved.
Fixes: https://tracker.ceph.com/issues/59196
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>
(cherry picked from commit 0dcee433c2e62978b1281b27ad6425723d94b508)

squid: test/lazy-omap-stats: Convert to boost::regex 

---

src/pybind/mgr/dashboard/controllers/cephfs.py
src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-group/cephfs-subvolume-group.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/icons.enum.ts

backport tracker: https://tracker.ceph.com/issues/67002
---
backport of https://github.com/ceph/ceph/pull/58441
parent tracker: https://tracker.ceph.com/issues/67001

squid: mgr/dashboard: add NFS export button for subvolume/ grp

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/erasure-code-profile-form/erasure-code-profile-form-modal.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/erasure-code-profile-form/erasure-code-profile-form-modal.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/erasure-code-profile.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/erasure-code-profile.ts

backport tracker: https://tracker.ceph.com/issues/66982
---
backport of https://github.com/ceph/ceph/pull/58143
parent tracker: https://tracker.ceph.com/issues/66571

squid: mgr/dashboard: add fields to EC profile form

---

src/kv/RocksDBStore.cc

backport tracker: https://tracker.ceph.com/issues/65915
---
backport of https://github.com/ceph/ceph/pull/55676
parent tracker: https://tracker.ceph.com/issues/64511

squid: kv/RocksDBStore: Configure compact-on-deletion for all CFs

---

src/rgw/rgw_amqp.cc

When sanitizer is enabled, unittest_rgw_amqp shows,
```
=================================================================
==1429129==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 416 byte(s) in 1 object(s) allocated from:
#0 0xaaaab56a0008 in operator new(unsigned long) (/root/ceph/build/bin/unittest_rgw_amqp+0x1c0008) (BuildId: a20c317434e8d5f2ec33bbb71a69d81eb751c494)
#1 0xaaaab57eecfc in amqp_new_connection /root/ceph/src/test/rgw/amqp_mock.cc:110:12
#2 0xaaaab58095d8 in rgw::amqp::new_state(rgw::amqp::connection_t*, rgw::amqp::connection_id_t const&) /root/ceph/src/rgw/rgw_amqp.cc:373:16
#3 0xaaaab5813c70 in rgw::amqp::Manager::run() /root/ceph/src/rgw/rgw_amqp.cc:684:18
#4 0xaaaab5849e50 in void std::__invoke_impl<void, void (rgw::amqp::Manager::*)() noexcept, …
```

rgw/amqp: lock erase and create connection before emplace

---

doc/cephadm/upgrade.rst

relates to https://tracker.ceph.com/issues/66937#note-13 where:
> docker pull quay.io/ceph-ci/ceph:wip-66937-squid
Error response from daemon: unauthorized: access to the requested resource is not authorized
https://docs.ceph.com/en/latest/cephadm/upgrade/#using-customized-container-images recommended this url format for development builds
but that doc also links to https://docs.ceph.com/en/latest/install/containers/#development-builds which refers to `https://quay.ceph.io/organization/ceph-ci`
<details>
- …

doc/cephadm/upgrade: ceph-ci containers are hosted at quay.ceph.io

---

src/msg/async/rdma/RDMAConnectedSocketImpl.cc

Addresses clang 17 error message about -Wunused-but-set-variable
Fixes: 2fb8be43fa2a758cc7934f7a82a48ad2d47d1112
- …

msg/async/rdma: cleanup unused variables

---

qa/suites/crimson-rados/basic/tasks/rados_python.yaml
src/crimson/osd/osd.cc

when committed osdmap is complete, it will check if should restart.
in case we shouldn't restart but we are still active, we need
the next osdmap to continue the process.
Fixes: https://tracker.ceph.com/issues/66381 …

crimson/osd: adding osdmap subscribe

---

src/mds/Server.cc
src/mds/Server.h

backport tracker: https://tracker.ceph.com/issues/66626
---
backport of https://github.com/ceph/ceph/pull/57754
parent tracker: https://tracker.ceph.com/issues/63265

squid: mds: set the proper extra bl for the create request

---

qa/workunits/libcephfs/test.sh
src/client/Client.cc
src/include/ceph_fs.h
src/mds/Server.cc
src/test/libcephfs/CMakeLists.txt
src/test/libcephfs/test.cc
src/test/libcephfs/vxattr.cc

backport tracker: https://tracker.ceph.com/issues/66777
---
backport of https://github.com/ceph/ceph/pull/55945
parent tracker: https://tracker.ceph.com/issues/64679

squid: mds/client: return -ENODATA when xattr doesn't exist for removexattr

---

PendingReleaseNotes
doc/cephfs/administration.rst
qa/tasks/cephfs/test_admin.py
qa/tasks/mgr/dashboard/test_health.py
src/common/options/mon.yaml.in
src/mds/FSMap.cc
src/mds/FSMap.h
src/mon/MDSMonitor.cc
src/mon/MonCommands.h
src/mon/PaxosFSMap.h
src/pybind/mgr/dashboard/controllers/health.py
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/tox.ini

backport tracker: https://tracker.ceph.com/issues/66781
---
backport of https://github.com/ceph/ceph/pull/53503
parent tracker: https://tracker.ceph.com/issues/62849

squid: mon/MDSMonitor: set birth time on FSMap during encode

---

qa/tasks/cephfs/test_admin.py

Fixes: https://tracker.ceph.com/issues/66728 …

squid: qa/cephfs: mark file system joinable for fs rename tests before unmounting clients

---

qa/tasks/cephfs/test_snap_schedules.py

backport tracker: https://tracker.ceph.com/issues/66669
---
backport of https://github.com/ceph/ceph/pull/57034
parent tracker: https://tracker.ceph.com/issues/65564

squid: qa: cleanup snapshots before subvolume delete

---

qa/tasks/cephfs/test_mirroring.py
src/tools/cephfs_mirror/FSMirror.cc
src/tools/cephfs_mirror/FSMirror.h
src/tools/cephfs_mirror/InstanceWatcher.cc
src/tools/cephfs_mirror/InstanceWatcher.h
src/tools/cephfs_mirror/Mirror.cc
src/tools/cephfs_mirror/MirrorWatcher.cc
src/tools/cephfs_mirror/MirrorWatcher.h
src/tools/cephfs_mirror/Watcher.h

backport tracker: https://tracker.ceph.com/issues/66975
backport tracker: https://tracker.ceph.com/issues/66969
backport tracker: https://tracker.ceph.com/issues/66972
backport tracker: https://tracker.ceph.com/issues/66979
---
backport of https://github.com/ceph/ceph/pull/56193
parent tracker: https://tracker.ceph.com/issues/51964
parent tracker: https://tracker.ceph.com/issues/63089
parent tracker: https://tracker.ceph.com/issues/63931
parent tracker: https://tracker.ceph.com/issues/64927

squid: cephfs_mirror, qa: fix mirror daemon doesn't restart when blocklisted or failed

---

qa/tasks/cephfs/test_admin.py

backport tracker: https://tracker.ceph.com/issues/66935
---
backport of https://github.com/ceph/ceph/pull/57492
parent tracker: https://tracker.ceph.com/issues/66933

squid: qa/cephfs: improvements for "mds fail" and "fs fail"

---

qa/tasks/cephfs/test_admin.py

backport tracker: https://tracker.ceph.com/issues/66932
---
backport of https://github.com/ceph/ceph/pull/58311
parent tracker: https://tracker.ceph.com/issues/66077

squid: qa/cephfs: fix test_single_path_authorize_on_nonalphanumeric_fsname

---

qa/tasks/cephfs/test_mirroring.py
src/tools/cephfs_mirror/FSMirror.cc
src/tools/cephfs_mirror/FSMirror.h
src/tools/cephfs_mirror/InstanceWatcher.cc
src/tools/cephfs_mirror/InstanceWatcher.h
src/tools/cephfs_mirror/Mirror.cc
src/tools/cephfs_mirror/MirrorWatcher.cc
src/tools/cephfs_mirror/MirrorWatcher.h
src/tools/cephfs_mirror/Watcher.h

backport tracker: https://tracker.ceph.com/issues/66976
backport tracker: https://tracker.ceph.com/issues/66970
backport tracker: https://tracker.ceph.com/issues/66973
backport tracker: https://tracker.ceph.com/issues/66980
---
backport of https://github.com/ceph/ceph/pull/56193
parent tracker: https://tracker.ceph.com/issues/51964
parent tracker: https://tracker.ceph.com/issues/63089
parent tracker: https://tracker.ceph.com/issues/63931
parent tracker: https://tracker.ceph.com/issues/64927

reef: cephfs_mirror, qa: fix mirror daemon doesn't restart when blocklisted or failed

---

qa/tasks/cephfs/test_admin.py

backport tracker: https://tracker.ceph.com/issues/66936
---
backport of https://github.com/ceph/ceph/pull/57492
parent tracker: https://tracker.ceph.com/issues/66933

reef: qa/cephfs: improvements for "mds fail" and "fs fail"

---

qa/tasks/cephfs/test_admin.py

backport tracker: https://tracker.ceph.com/issues/66931
---
backport of https://github.com/ceph/ceph/pull/58311
parent tracker: https://tracker.ceph.com/issues/66077

reef: qa/cephfs: fix test_single_path_authorize_on_nonalphanumeric_fsname

---

PendingReleaseNotes
doc/cephfs/quota.rst
qa/tasks/cephfs/mount.py
qa/tasks/cephfs/test_subvolume.py
qa/workunits/fs/misc/general_vxattrs.sh
qa/workunits/fs/misc/layout_vxattrs.sh
src/mds/Server.cc
src/mds/Server.h

backport tracker: https://tracker.ceph.com/issues/66732
---
backport of https://github.com/ceph/ceph/pull/53755
parent tracker: https://tracker.ceph.com/issues/62793

reef: mds: Implement remove for ceph vxattrs 

---

qa/suites/rados/objectstore/backends/objectstore-bluestore-a.yaml
qa/suites/rados/objectstore/backends/objectstore-bluestore-b.yaml
src/test/objectstore/store_test.cc

Modified structure of matrix-based unit tests.
Now each test case can be invoked separately.
New matrix tests are hard bound to "BlueStore".
Now:
...
BlueStore/SyntheticShardingLimited.
Test/0  # GetParam() = { 65536, 10000, 65536, 262144, 4096, 1000, 65536, 60, 300, 150, true, true }
Test/1  # GetParam() = { 4096, 10000, 65536, 262144, 4096, 1000, 65536, 60, 300, 150, true, true }
Test/2  # GetParam() = { 65536, 10000, 65536, 262144, 4096, 200, 65536, 60, 300, 150, true, true }
Test/3  # GetParam() = { 4096, 10000, 65536, 262144, 4096, 200, 65536, 60, 300, 150, true, true }
Test/4  # GetParam() = { 65536, 10000, 65536, 262144, 4096, 50, 65536, 60, 300, 150, true, true }
Test/5  # GetParam() = { 4096, 10000, 65536, 262144, 4096, 50, 65536, 60, 300, 150, true, true } …

Improved structure for objectstore unit tests.

---

doc/start/os-recommendations.rst

This shows Ceph 16.2.z support on CentOS 7 as A.
But I did not find the Ceph 16.2.z package for CentOS 7 at https://download.ceph.com/ .
And the cephadm tool also prompts that Ceph 16.y.z cannot run on CentOS 7.
```shell
$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
$ uname -r
5.4.54-2.0.4.std7c.el7.x86_64
$ cephadm add-repo --version 16.2.15
ERROR: Ceph does not support 16.y.z or later for this version of this linux distro and therefore cannot add a repo for it
``` …

doc/start/os-recommendations: remove 16.2.z support for CentOS 7

---

src/cephadm/cephadm

to prepare for a change to use importlib, then fallback to pkg_resources. as the former is only available in Python 3.8, while the latter is deprecated.
NOTE: This is a backport to the Quincy branch of the commits in https://github.com/ceph/ceph/pull/57685/commits. Those commits are:
1. be1a8c2c43e97f91bd26554ba9dadc71c499865d
2. cbd4bede7f258823462f27cb15d86e13eb52c359 The alteration to the "def get_version(ctx, container_id):" function introduced by be1a8c is not in the same file in the main branch as in the Quincy branch, which makes a backport using cherry-picks impossible.
Refs https://tracker.ceph.com/issues/66201
(cherry picked from commit be1a8c2c43e97f91bd26554ba9dadc71c499865d) …

quincy: cephadm: use importlib.metadata for querying ceph_iscsi's version

---

qa/suites/rados/thrash/thrashers/careful_host.yaml
qa/suites/rados/thrash/thrashers/default.yaml
qa/suites/rados/thrash/thrashers/default_host.yaml
qa/suites/rados/thrash/thrashers/mapgap_host.yaml
qa/suites/rados/thrash/thrashers/pggrow.yaml
qa/suites/rados/thrash/thrashers/pggrow_host.yaml
qa/tasks/ceph_manager.py

We need to check if taking host out will cause the total in osds to be less then min_in
Fixes: https://tracker.ceph.com/issues/66657 …

suites: host thrasher should check min_in before thrashing host

---

doc/dev/crimson/crimson.rst

This began as just fixing a few small things, however it was then recommended to me that I make any other changes I felt could be appropriate, since I am probably the target audience for this kind of document - a new user/developer of Crimson. A summary of the changes are as follows:
- Moving the section about setting essential flags which activate Crimson to its own place
- Making the commands safer and more appropriate; in particular the cmake and vstart commands
- Re-arranging the chapters to flow in order of the user's actions in setting up; that is, building Ceph for Crimson, starting the cluster, then setting the flags, then learning about extras and Crimson in general
- Fixing some typos   
- Emphasising the danger of activating Crimson in its own 'note' box for extra highlighting …

doc/dev/crimson: making it more user-friendly, re-arranging chapters and fixing typos

---

src/test/rgw/bucket_notification/test_bn.py

backport tracker: https://tracker.ceph.com/issues/66243
---
backport of https://github.com/ceph/ceph/pull/57638
parent tracker: https://tracker.ceph.com/issues/66033

squid: test/rgw/notifications: allow http server to buffer more requests

---

src/rgw/driver/rados/rgw_notify.cc
src/rgw/driver/rados/rgw_notify.h
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/driver/rados/rgw_sal_rados.h
src/rgw/driver/rados/topic.cc
src/rgw/rgw_pubsub.cc
src/rgw/rgw_rest_pubsub.cc
src/rgw/rgw_sal.h
src/rgw/rgw_sal_dbstore.cc
src/rgw/rgw_sal_dbstore.h
src/rgw/rgw_sal_filter.cc
src/rgw/rgw_sal_filter.h
src/test/rgw/bucket_notification/test_bn.py

backport tracker: https://tracker.ceph.com/issues/66210
---
backport of https://github.com/ceph/ceph/pull/57249
parent tracker: https://tracker.ceph.com/issues/65668

squid: rgw/notify: decouple add/remove_persistent_topic() from Manager

---

src/rgw/driver/rados/rgw_rados.cc

backport tracker: https://tracker.ceph.com/issues/67024
---
backport of https://github.com/ceph/ceph/pull/58649
parent tracker: https://tracker.ceph.com/issues/64173

squid: rgw/rados: set_attrs() falls back to existing attrs for index update

---

src/common/options/crimson.yaml.in
src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/cache.h
src/crimson/os/seastore/device.h
src/crimson/os/seastore/extent_placement_manager.h
src/crimson/os/seastore/journal.h
src/crimson/os/seastore/journal/circular_bounded_journal.h
src/crimson/os/seastore/journal/circular_journal_space.cc
src/crimson/os/seastore/journal/circular_journal_space.h
src/crimson/os/seastore/journal/segmented_journal.h
src/crimson/os/seastore/lba_manager.cc
src/crimson/os/seastore/random_block_manager.h
src/crimson/os/seastore/random_block_manager/block_rb_manager.cc
src/crimson/os/seastore/random_block_manager/block_rb_manager.h
src/crimson/os/seastore/random_block_manager/nvme_block_device.cc
src/crimson/os/seastore/random_block_manager/nvme_block_device.h
src/crimson/os/seastore/random_block_manager/rbm_device.cc
src/crimson/os/seastore/random_block_manager/rbm_device.h
src/crimson/os/seastore/seastore_types.h
src/crimson/os/seastore/transaction_manager.cc
src/crimson/os/seastore/transaction_manager.h
src/test/crimson/seastore/test_randomblock_manager.cc

The goal of this PR is to introduce checksum offload by using end to end data protection specified by NVMe spec.
Reference: https://nvmexpress.org/specification/nvm-command-set-specification/
https://en.wikipedia.org/wiki/Data_Integrity_Field …

crimson/os/seastore: add checksum offload to RBM

---

src/crimson/os/seastore/btree/btree_range_pin.cc
src/crimson/os/seastore/btree/btree_range_pin.h
src/crimson/os/seastore/btree/fixed_kv_btree.h
src/crimson/os/seastore/btree/fixed_kv_node.h
src/crimson/os/seastore/cached_extent.h
src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.h
src/crimson/os/seastore/lba_manager/btree/lba_btree_node.cc
src/crimson/os/seastore/lba_manager/btree/lba_btree_node.h
src/crimson/os/seastore/root_block.h
src/crimson/os/seastore/transaction.h
src/crimson/os/seastore/transaction_manager.cc
src/crimson/os/seastore/transaction_manager.h
src/test/crimson/seastore/test_block.h
src/test/crimson/seastore/test_transaction_manager.cc

So that we don't have to re-iterate through the whole lba tree to get a "parent-viewable" mapping in most cases.
This PR is a performance optimization for #57709, and is also the first step toward the lba mapping updating optimization discussed in https://github.com/ceph/ceph/pull/55449#discussion_r1479151298 …

crimson/os/seastore/cached_extent: add the "refresh" ability to lba mappings

---

src/pybind/mgr/dashboard/tests/test_iscsi.py

Python asks in multiple places to use assertEqual instead of assertEquals:
DeprecationWarning: Please use assertEqual instead. …

mgr/dashboard: use assertEqual in test_iscsi

---

qa/suites/rados/verify/validater/valgrind.yaml

OSD_DOWN cluster log warning is raised on rare occasions due to the osd_hearbeat_grace timeout getting exceeded. The warning is soon cleared. Given the nature of the test (valgrind), the grace timeout is increased to 90 secs to avoid generating the warning.
Fixes: https://tracker.ceph.com/issues/65768
Signed-off-by: Sridhar Seshasayee <sseshasa@redhat.com> …

qa/suites/rados/verify/validater: increase heartbeat grace timeout

---

src/msg/async/AsyncMessenger.cc

The counter (msgr_active_connections) can be an anomaly in case if a server daemon is blocked on accept_conn and the client sends a disconnect request to the server daemon. As the server receives an unregister_conn request it decrease the counter without checking the connection status so decreases the counter only if the previous value is positive.
Fixes: https://tracker.ceph.com/issues/66231
Signed-off-by: Mohit Agrawal <moagrawa@redhat.com> …

AsyncMessenger: Don't decrease l_msgr_active_connections if it is negative

---

qa/suites/rados/singleton-nomsgr/all/admin_socket_output.yaml

IO is frozen when the injectfull command is sent as part of the test which causes the cleanup to hang so we need to clear it.
Fixes: https://tracker.ceph.com/issues/59380 …

qa/suites/rados: Cancel injectfull to allow cleanup

---

ceph.spec.in
debian/ceph-mgr-modules-core.requires
src/pybind/mgr/prometheus/module.py

backport tracker: https://tracker.ceph.com/issues/66413
---
backport of https://github.com/ceph/ceph/pull/57700
parent tracker: https://tracker.ceph.com/issues/66201

squid: mgr/prometheus: s/pkg_resources.packaging/packaging/

---

src/erasure-code/clay/ErasureCodeClay.cc

Addresses clang 17 error with  count_retrieved_sub_chunks:
/home/rocky/ceph/src/erasure-code/clay/ErasureCodeClay.cc:481:7: error: variable 'count_retrieved_sub_chunks' set but not used [-Werror,-Wunused-but-set-variable] …

erasure-code/clay: cleanup unused but set variable

---

qa/cephfs/conf/mds.yaml
qa/suites/fs/full/tasks/mgr-osd-full.yaml
qa/suites/fs/libcephfs/tasks/client.yaml
qa/suites/fs/libcephfs/tasks/ino_release_cb.yaml
qa/suites/fs/libcephfs/tasks/libcephfs/test.yaml
src/msg/async/ProtocolV1.cc
src/msg/async/ProtocolV2.cc

The bug is for many time the MDS sent out the `beacon` msg to monitors,
and from the mds and msgr logs we can see that the `beacon` msg was
really sent out, more exactly is the msg had been enqueued to the protocol
sender queue. But we don't know whether this msg had been sent out or
stuck in the route, and the monitors received it after minutes.
We need to know whether it's a bug in protocol code and need more debug
logs from it. …

msg/mds: print more debug logs from protocol layer

---

src/rgw/rgw_rest.cc

According to RFC 9110, The HEAD method is identical to GET except that the server MUST NOT send content in the response.
The following HEAD OP is using chunked encoding and send the final chunk
| HTTP Request                 | Function                            |
|------------------------------|-------------------------------------|
| HEAD /bucket?uploads         | RGWListBucketMultiparts_ObjStore_S3 |
| HEAD /bucket/abc?uploadId    | RGWListMultipart_ObjStore_S3        |
| HEAD /                       | RGWListBuckets_ObjStore_S3          |
Clients using persistent connections, such as nginx, will be unable to handle subsequent requests after processing such requests because the final chunk remains in the TCP byte stream, preventing the next HTTP response from being correctly parsed. …

[RGW] Fix the handling of HEAD requests that do not comply with RFC standards

---

debian/ceph-base.postinst

backport tracker: https://tracker.ceph.com/issues/66860
---
backport of https://github.com/ceph/ceph/pull/55917
parent tracker: https://tracker.ceph.com/issues/64548

reef: debian: recursively adjust permissions of /var/lib/ceph/crash

---

src/pybind/mgr/test_orchestrator/module.py

so that when we are testing things with test_orchestrator as the orch back-end and do volume creation, it won't raise the below error
```
2024-07-19T13:40:46.349+0000 7f2d11a00640  0 [test_orchestrator ERROR orchestrator._interface]
File "/ceph/src/pybind/mgr/orchestrator/_interface.py", line 139, in wrapper
return OrchResult(f(*args, **kwargs))
File "/ceph/src/pybind/mgr/orchestrator/_interface.py", line 618, in apply
return raise_if_exception(reduce(merge, [fns[spec.service_type](spec) for spec in specs], OrchResult([])))
File "/ceph/src/pybind/mgr/orchestrator/_interface.py", line 618, in <listcomp>
return raise_if_exception(reduce(merge, [fns[spec.service_type](spec) for spec in specs], OrchResult([])))
File …
```

mgr/test_orchestrator: add apply_mds command in the test_orch

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster.component.ts

Fixes: https://tracker.ceph.com/issues/67074
Fixed: While opening the expand cluster page from the cluster >> hosts page, and then clicking back button on expand-cluster page, it was taking to dashboard instead of the page from which user has come …

mgr/dashboard: expand-cluster back navigation fix

---

src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.e2e-spec.ts

Fixes: https://tracker.ceph.com/issues/67070
Fixed: multisite-e2es were not considered while running dashboard e2e because of the file name variation. …

mgr/dashboard: multisite e2e fixes 

---

src/crimson/admin/pg_commands.cc
src/crimson/osd/osd_operations/background_recovery.cc
src/crimson/osd/osd_operations/client_request.cc
src/crimson/osd/osd_operations/internal_client_request.cc
src/crimson/osd/osd_operations/internal_client_request.h
src/crimson/osd/osd_operations/logmissing_request.cc
src/crimson/osd/osd_operations/logmissing_request_reply.cc
src/crimson/osd/osd_operations/peering_event.cc
src/crimson/osd/osd_operations/recovery_subrequest.cc
src/crimson/osd/osd_operations/replicated_request.cc
src/crimson/osd/osd_operations/scrub_events.cc
src/crimson/osd/pg.cc
src/crimson/osd/pg_interval_interrupt_condition.cc
src/crimson/osd/pg_interval_interrupt_condition.h

crimson: audit and correct epoch captured by IOInterruptCondition

---

src/librbd/io/AioCompletion.cc
src/librbd/io/AioCompletion.h

This PR proposes the following performance improvements to AioCompletion:
1. Replace the conditional variable with the atomic wait/notify functions introduced in C++20.
2. Remove the mutex lock which was previously required to update the conditional variable.
3. Relax the memory order of the atomic operations to update the AioCompletion state.
Flame graph analysis of `rbd bench` indicates an almost 1% performance improvement on average in the function AioCompletion::notify_callbacks_complete().
Before:
After:
This data was captured by running a workload of 4K sequential writes to a 200G volume.
I have ran `bin/ceph_test_librbd `to validate that the code reliant on the conditional variable still works and specifically ran -`-gtest_filter=TestLibRBD.TestIO` with valgrind to validate that …

librbd: Modify locks and atomics in AioCompletion to improve performance

---

src/script/backport-create-issue

Resolves:
WARNING:root:Missing issues will be created in Backport tracker of the relevant Redmine project
INFO:root:Redmine key was read from '$REDMINE_API_KEY'; using it
INFO:root:Processing 35 issues with status Pending Backport
File "/home/runner/work/ceph/ceph/src/script/backport-create-issue", line 411, in <module>
iterate_over_backports(redmine, issues, dry_run=args.dry_run)
File "/home/runner/work/ceph/ceph/src/script/backport-create-issue", line 354, in iterate_over_backports
update_relations(r, issue, dry_run)
File "/home/runner/work/ceph/ceph/src/script/backport-create-issue", line 242, in update_relations
other = r.issue.create(project_id=issue['project']['id'],
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …

script/backport-create-issue: retry without if assignee is invalid

---

qa/workunits/rgw/test_rgw_reshard.py

The testing code does a `reshard add` followed by a `reshard list`. On the narrow chance that the reshard was completed between those two commands, we need to be able to handle the case where the reshard list is empty. In that case we'll do a `bucket stats` to verify the reshard completed successfully.
Fixes: https://tracker.ceph.com/issues/66367 …

test/rgw: address potential race condition in reshard testing

---

src/cephadm/cephadmlib/daemons/ceph.py
src/pybind/mgr/rook/ci/Dockerfile

after centos9 our python version is 3.9 so shouldn't we use the python3.9 path instead of python3.6?
- Tracker …

cephadm: update shared folder python packages dir

---

src/pybind/mgr/nfs/export.py
src/pybind/mgr/nfs/utils.py

Early handling of `NoOrchestrator` exception via a2192c73e41e prevented us from looking for namespaces containing conf objects in _.nfs_ pool. This would mean that we fail to recognize such namespaces as clusters thereby prohibiting the creation of nfs exports. We could instead search for such namespaces while handling the `NoOrchestrator` exception within _available_clusters()_ before returning the final list of clusters.
Fixes: https://tracker.ceph.com/issues/66800

mgr/nfs: Do not ignore clusters from rados pool conf objects

---

src/osd/OSDMap.cc

This is a minimal fix to ensure only peers understanding `pg-upmap-primary` are able to connect, and thus to exclude the possibility of running into the `pg_upmap_primaries.empty()` assertion in encoders.
Fixes for other problems will follow up.
The intention is to ship this patch in the very next minor release of reef.
Fixes: https://tracker.ceph.com/issues/61948 …

mon, osd, *: expose upmap-primary in OSDMap::get_features()

---

src/crimson/os/alienstore/alien_store.cc
src/crimson/os/alienstore/alien_store.h

crimson: access coll_map under alien tp with a lock

---

src/cephadm/cephadm.py

backport tracker: https://tracker.ceph.com/issues/66958
---
backport of https://github.com/ceph/ceph/pull/58379
parent tracker: https://tracker.ceph.com/issues/66848

squid: cephadm: turn off cgroups_split setting  when bootstrapping with --no-cgroups-split

---

src/python-common/ceph/rgw/rgwam_core.py

backport tracker: https://tracker.ceph.com/issues/66892
---
backport of https://github.com/ceph/ceph/pull/58326
parent tracker: https://tracker.ceph.com/issues/66824

squid: mgr/rgw: fix setting rgw realm token in secondary site rgw spec

---

src/pybind/mgr/rgw/module.py
src/python-common/ceph/rgw/rgwam_core.py

backport tracker: https://tracker.ceph.com/issues/66648
---
backport of https://github.com/ceph/ceph/pull/58142
parent tracker: https://tracker.ceph.com/issues/66568

squid: mgr/rgw: fix error handling in rgw zone create

---

qa/suites/krbd/mirror/tasks/compare-mirror-image-alternate-primary.yaml
qa/suites/krbd/mirror/tasks/compare-mirror-images.yaml
qa/suites/krbd/singleton/tasks/krbd_watch_errors_exclusive.yaml
qa/suites/krbd/thrash/workloads/krbd_diff_continuous.yaml
qa/workunits/rbd/krbd_watch_errors_exclusive.sh

qa/suites/krbd: stress test for recovering from watch errors for -o exclusive

---

src/tools/ceph_dedup/ceph_dedup_daemon.cc

Follow-up: https://github.com/ceph/ceph/pull/56067
This is 2nd PR to rename and refactor globals. …

tool: renaming and refactoring global variables in ceph-dedup-daemon

---

src/test/osd/TestOSDMap.cc

In the case of creating a ParallelPGMapper object after starting the threadpool 
the test case might crash. The test case is crash while worker thread is trying to
delete a job but the object is still in the construction phase not fully constructed.
Solution: To avoid a crash create the object before start a threadpool.
Fixes: https://tracker.ceph.com/issues/42884 …

test: Create ParallelPGMapper object before start threadpool

---

src/rgw/rgw_iam_policy.cc

cf. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_notprincipal.html
> NotPrincipal must be used with "Effect":"Deny". Using it with "Effect":"Allow" is not supported.
Fixes: https://tracker.ceph.com/issues/67047

rgw: donot allow NotPrincipal with Allow Effect

---

src/common/async/co_spawn_group.h
src/common/async/co_throttle.h
src/common/async/co_waiter.h
src/common/async/detail/co_spawn_group.h
src/common/async/detail/co_throttle_impl.h
src/common/async/max_concurrent_for_each.h
src/common/async/parallel_for_each.h
src/test/common/CMakeLists.txt
src/test/common/test_async_co_spawn_group.cc
src/test/common/test_async_co_throttle.cc
src/test/common/test_async_max_concurrent_for_each.cc
src/test/common/test_async_parallel_for_each.cc

squashed/cleaned up commits that were initially part of the wip-coro-after-reef feature branch
more recently, a similar set of primitives were merged for stackful coroutines in https://github.com/ceph/ceph/pull/57188
<details>
</details>

common/async: add primitives for structured concurrency with c++20 coroutines

---

src/common/async/detail/shared_mutex.h

the linker complains that several SharedMutexImpl functions are duplicated, if "common/async/shared_mutex.h" is included by more than one translation unit
added 'inline' to the function definitions so they're shared instead of duplicated
<details>
</details>

common/async: fix duplicate definition errors from SharedMutexImpl

---

monitoring/ceph-mixin/dashboards/rgw.libsonnet
monitoring/ceph-mixin/dashboards_out/radosgw-sync-overview.json

backport tracker: https://tracker.ceph.com/issues/67101
---
backport of https://github.com/ceph/ceph/pull/58644
parent tracker: https://tracker.ceph.com/issues/66994

squid: mgr/dashboard: Add a new chart for replication delta per shard in rgw sync overview grafana dashboard

---

qa/suites/krbd/mirror/tasks/compare-mirror-image-alternate-primary.yaml
qa/suites/krbd/mirror/tasks/compare-mirror-images.yaml
qa/suites/krbd/singleton/tasks/krbd_watch_errors_exclusive.yaml
qa/suites/krbd/thrash/workloads/krbd_diff_continuous.yaml
qa/workunits/rbd/krbd_watch_errors_exclusive.sh

backport tracker: https://tracker.ceph.com/issues/67172
---
backport of https://github.com/ceph/ceph/pull/58781
parent tracker: https://tracker.ceph.com/issues/67097

squid: qa/suites/krbd: stress test for recovering from watch errors for -o exclusive

---

src/rgw/rgw_iam_policy_keywords.gperf
src/rgw/rgw_iam_policy_keywords.h
src/rgw/rgw_op.cc

Allow restricting requests regarding SSE-C encryption with bucket policy.
cf. https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html#ssec-require-condition-key
Fixes: https://tracker.ceph.com/issues/67053

rgw: add support sse-c to bucket policy conditions

---

src/rgw/rgw_kms.cc

Typically, the HashiCorp Vault token is refreshed by another process, such as the Vault Agent. This process needs ownership of the file to write the new token. Since Ceph primarily runs with its own user, it cannot access the token file unless it has group read permissions. This requires either assigning the correct group to the file by the Vault Agent or ensuring Ceph is part of the appropriate group.
By eliminating the restriction on group read permissions, this can be achievable.
Fixes: https://tracker.ceph.com/issues/66121

rgw: eliminate vault token perm for group read

---

src/common/options/global.yaml.in
src/compressor/QatAccel.cc
src/compressor/QatAccel.h
src/compressor/zlib/ZlibCompressor.cc
src/rgw/driver/daos/rgw_sal_daos.cc
src/rgw/driver/motr/rgw_sal_motr.cc
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/rgw_file.cc
src/rgw/rgw_op.cc

QAT zlib 'QZ_DEFLATE_RAW' data format cannot decompress by QAT hardware. So there is 'QZ_DEFLATE_GZIP_EXT' data
format added.
'QZ_DEFLATE_GZIP_EXT' data format need to add gz_header by deflateSetHeader() in QATzip. And it may lead multi stream
in one compression because for hardware buffer. So the windows bit is important information for decompression, which related to
if the inflate remove header.
Add busy_polling setting for reducing latency when busy_polling is true
When I upload a object to RGW by multipart, the head object xattr(user.rgw.compression) don't have compressor_message
when the value should be valid and part object xattr(user.rgw.compression) have compressor_message.  …

Compressor: Add data format(QZ_DEFLATE_GZIP_EXT) for QAT Zlib

---

src/cls/rgw/cls_rgw_client.cc
src/cls/rgw/cls_rgw_client.h
src/rgw/driver/rados/rgw_gc.cc
src/test/cls_rgw/test_cls_rgw.cc

clean up the only gc function that was hidden with CLS_CLIENT_HIDE_IOCTX
this allows rgw to use it asynchonously with rgw_rados_operate() and optional_yield, and warn about blocking calls that should be async
<details>
</details>

cls/rgw: gc_list uses ObjectOperation instead of IoCtx

---

src/common/async/max_concurrent_for_each.h
src/common/async/spawn_throttle.h
src/rgw/rgw_op.cc
src/test/common/test_async_spawn_throttle.cc

(relates to discussion from https://github.com/ceph/ceph/pull/58348)
cancellation of the parent must immediately cancel its children, which only works if the children are on the same executor as the parent
prohibit child coroutines from being spawned on a different executor by wrapping the call to asio::spawn() in a new spawn_throttle::spawn() interface
expose an overload for asio::spawn()'s optional StackAllocator argument
<details> …

common/async: spawn_throttle wraps call to asio::spawn()

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/block.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-initiators-form/nvmeof-initiators-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-initiators-form/nvmeof-initiators-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-initiators-form/nvmeof-initiators-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-initiators-list/nvmeof-initiators-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-initiators-list/nvmeof-initiators-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-initiators-list/nvmeof-initiators-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-form/nvmeof-listeners-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-details/nvmeof-subsystems-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-details/nvmeof-subsystems-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/nvmeof.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts

backport tracker: https://tracker.ceph.com/issues/67202
---
backport of https://github.com/ceph/ceph/pull/58534
parent tracker: https://tracker.ceph.com/issues/66907

squid: mgr/dashboard: Add initiators

---

src/cephadm/cephadmlib/daemons/smb.py
src/cephadm/tests/test_deploy.py

Remove the line hard-coding the samba debuglevel to 6. It is a leftover from testing the early versions of the containers on ceph. …

cephadm: do not hard code samba debuglevel 6

---

qa/suites/krbd/mirror/tasks/compare-mirror-image-alternate-primary.yaml
qa/suites/krbd/mirror/tasks/compare-mirror-images.yaml
qa/suites/krbd/singleton/tasks/krbd_watch_errors_exclusive.yaml
qa/suites/krbd/thrash/workloads/krbd_diff_continuous.yaml
qa/workunits/rbd/krbd_watch_errors_exclusive.sh

backport tracker: https://tracker.ceph.com/issues/67170
---
backport of https://github.com/ceph/ceph/pull/58781
parent tracker: https://tracker.ceph.com/issues/67097

reef: qa/suites/krbd: stress test for recovering from watch errors for -o exclusive

---

ceph.spec.in
debian/control
src/pybind/mgr/mgr_util.py
src/pybind/mgr/prometheus/module.py

backport tracker: https://tracker.ceph.com/issues/66412
---
backport of https://github.com/ceph/ceph/pull/57700
parent tracker: https://tracker.ceph.com/issues/66201

quincy: mgr/prometheus: s/pkg_resources.packaging/packaging/

---

src/rgw/rgw_amqp.cc

backport tracker: https://tracker.ceph.com/issues/67071
---
backport of https://github.com/ceph/ceph/pull/57737
parent tracker: https://tracker.ceph.com/issues/66266

squid: rgw/amqp: lock erase and create connection before emplace

---

qa/suites/krbd/mirror/tasks/compare-mirror-image-alternate-primary.yaml
qa/suites/krbd/mirror/tasks/compare-mirror-images.yaml
qa/suites/krbd/singleton/tasks/krbd_watch_errors_exclusive.yaml
qa/suites/krbd/thrash/workloads/krbd_diff_continuous.yaml
qa/workunits/rbd/krbd_watch_errors_exclusive.sh

backport tracker: https://tracker.ceph.com/issues/67171
---
backport of https://github.com/ceph/ceph/pull/58781
parent tracker: https://tracker.ceph.com/issues/67097

quincy: qa/suites/krbd: stress test for recovering from watch errors for -o exclusive

---

src/crimson/osd/pg.cc
src/crimson/osd/pg.h
src/crimson/osd/replicated_backend.cc

Fixes: https://tracker.ceph.com/issues/61761
Signed-off-by: Md Mahamudur Rahaman Sajib <mahamudur.sajib@croit.io>
- …

crimson: PG stats are not synced between osds after object update

---

src/crimson/osd/osd_operations/background_recovery.cc
src/crimson/osd/pg.cc
src/crimson/osd/pg.h
src/crimson/osd/pg_recovery.cc

backport of https://github.com/ceph/ceph/pull/57147

squid: crimson/osd/pg_recovery: skip unfound objects when recovering the primary

---

src/crimson/osd/osd_operations/client_request_common.cc

backport of https://github.com/ceph/ceph/pull/57691

squid: crimson/osd/osd_operations/client_request_common: `PeeringState::needs_recovery()` may fail if the object is under backfill

---

src/crimson/os/seastore/btree/fixed_kv_btree.h
src/crimson/os/seastore/btree/fixed_kv_node.h

backport of https://github.com/ceph/ceph/pull/57828

squid: crimson/os/seastore/btree: improve lba pointer related UT checks

---

src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/extent_placement_manager.cc
src/crimson/os/seastore/journal/record_submitter.cc
src/crimson/os/seastore/seastore_types.cc
src/crimson/os/seastore/seastore_types.h

backport of https://github.com/ceph/ceph/pull/58250

squid: crimson/os/seastore: write ool extents without padding

---

src/crimson/os/seastore/btree/fixed_kv_btree.h

backport of https://github.com/ceph/ceph/pull/58357

squid: crimson/os/seastore/btree: interrupt transactions immediately when getting children

---

src/crimson/osd/pg_backend.h
src/crimson/osd/recovery_backend.cc
src/crimson/osd/recovery_backend.h

backport of https://github.com/ceph/ceph/pull/58694

squid: crimson/osd/recovery_backend: cleanup PGBackend::temp_contents when pg interval changes

---

src/crimson/osd/pg.cc
src/crimson/osd/pg.h
src/crimson/osd/replicated_backend.cc

backport of https://github.com/ceph/ceph/pull/58510

squid: crimson: PG stats are not synced between osds after object update

---

src/vstart.sh

backport of https://github.com/ceph/ceph/pull/57359

squid: vstart.sh: add options to set number of alien threads, and number of cpu cores for alien threads

---

qa/suites/crimson-rados/basic/tasks/rados_python.yaml

backport of https://github.com/ceph/ceph/pull/58396

squid: suite/crimson: enable stats tests

---

doc/dev/release-process.rst

Signed-off-by: Yuri Weinstein <yweinste@redhat.com>
(cherry picked from commit 8761bbe16c2a6d19e136254c26d1d67ebe839e3b) …

quincy: docs: removed centos 8 and added squid to the build matrix

---

doc/cephadm/services/index.rst
src/pybind/mgr/cephadm/tests/test_scheduling.py
src/pybind/mgr/rook/rook_cluster.py
src/python-common/ceph/deployment/service_spec.py
src/python-common/ceph/tests/test_service_spec.py

Backport of https://github.com/ceph/ceph/pull/53803
<details>
</details>

quincy: mgr/cephadm: support for regex based host patterns

---

src/ceph-volume/ceph_volume/util/device.py

backport tracker: https://tracker.ceph.com/issues/64843
---
backport of https://github.com/ceph/ceph/pull/54608
parent tracker: https://tracker.ceph.com/issues/63502

quincy: ceph-volume: Use safe accessor to get TYPE info

---

src/pybind/mgr/cephadm/configchecks.py
src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/serve.py
src/pybind/mgr/cephadm/tests/test_configchecks.py

backport tracker: https://tracker.ceph.com/issues/64992
---
backport of https://github.com/ceph/ceph/pull/56178
parent tracker: https://tracker.ceph.com/issues/64902

quincy: mgr/cephadm: refresh public_network for config checks before checking

---

src/pybind/mgr/cephadm/serve.py

backport tracker: https://tracker.ceph.com/issues/65957
---
backport of https://github.com/ceph/ceph/pull/57259
parent tracker: https://tracker.ceph.com/issues/65799

quincy: mgr/cephadm: Fix unfound progress events

---

src/pybind/mgr/orchestrator/module.py

backport tracker: https://tracker.ceph.com/issues/66787
---
backport of https://github.com/ceph/ceph/pull/58154
parent tracker: https://tracker.ceph.com/issues/66574

squid: mgr: excute cmd 'ceph orch apply osd' returned without error info

---

src/cephadm/cephadm.py

backport tracker: https://tracker.ceph.com/issues/66789
---
backport of https://github.com/ceph/ceph/pull/57975
parent tracker: https://tracker.ceph.com/issues/66436

squid: cephadm: disable ms_bind_ipv4 if we will enable ms_bind_ipv6

---

src/blk/kernel/KernelDevice.cc
src/blk/kernel/KernelDevice.h

Fixes: https://tracker.ceph.com/issues/66817
Test cases I've run:
```
Boot with class-masked bdev_enable_discard=true, global bdev_async_discard_threads=1:
* Discards issued
* 2 discard threads running (this is not seen before these changes; two because two KernelDevices exist)
PASS
Set bdev_enable_discard=false:
* Discards stop
* Discard threads disappear
PASS
Set bdev_enable_discard=true:
* Discards issued
* 2 discard threads running
PASS
Set bdev_async_discard_threads=2:
* Discards issued
* 4 discard threads running
PASS
Set bdev_async_discard_threads=1:
* Discards issued
* 2 discard threads running
PASS
```
<details> …

blk/KernelDevice: React to bdev_enable_discard changes in handle_conf_change(); Fix several issues with stopping discard threads

---

src/osd/OSDMap.cc

backport tracker: https://tracker.ceph.com/issues/67128
---
backport of https://github.com/ceph/ceph/pull/57777
parent tracker: https://tracker.ceph.com/issues/66285

squid: osd: bump versions of decoders for upmap-primary

---

qa/workunits/rgw/test_rgw_reshard.py

backport tracker: https://tracker.ceph.com/issues/67156
---
backport of https://github.com/ceph/ceph/pull/58670
parent tracker: https://tracker.ceph.com/issues/66367

squid: test/rgw: address potential race condition in reshard testing

---

PendingReleaseNotes
src/rgw/driver/rados/rgw_notify.cc
src/test/rgw/bucket_notification/test_bn.py

backport tracker: https://tracker.ceph.com/issues/66805
---
backport of https://github.com/ceph/ceph/pull/57537
parent tracker: https://tracker.ceph.com/issues/66036

squid: rgw/notification: Fix the caching issues of notification brokers, where the cache was not invalidated if topic attributes were changed

---

src/mon/OSDMonitor.cc

backport tracker: https://tracker.ceph.com/issues/67160
---
backport of https://github.com/ceph/ceph/pull/57843
parent tracker: https://tracker.ceph.com/issues/66329

squid: mon: validate also mons and osds on {rm-,}pg-upmap-primary

---

qa/valgrind.supp

backport tracker: https://tracker.ceph.com/issues/67055
---
backport of https://github.com/ceph/ceph/pull/52639
parent tracker: https://tracker.ceph.com/issues/61774

squid: qa: suppress Leak_StillReachable mon leak in centos 9 jobs

---

qa/crontab/teuthology-cronjobs

Although main rados nightlies are scheduled to run weekly, they are so low in the queue that they take weeks to run, and when they finally do, most of the jobs die (likely due to waiting in the queue so long).
This commit increases the priority of main rados runs since these are most important for debugging new failures. To compliment this increase in priority, this commit also decreases the frequency of squid rados runs from twice a week to once a week, since once is more than enough. It also decreases the priority of squid runs. …

qa/crontab: update frequency and priority for rados nightlies

---

src/crimson/osd/osd_operation.cc
src/crimson/osd/osd_operation.h

backport of https://github.com/ceph/ceph/pull/58225

squid: crimson/osd/osd_operation: fix dump_historic_slow_ops command works

---

qa/suites/crimson-rados/basic/tasks/rados_python.yaml
src/crimson/osd/osd.cc

backport of https://github.com/ceph/ceph/pull/58256

squid: crimson/osd: adding osdmap subscribe

---

src/rgw/rgw_s3select.cc
src/rgw/rgw_s3select_private.h

Previously, these fields remained constant despite the possibility of populating them with appropriate values.
Fixes: https://tracker.ceph.com/issues/65468

rgw: set correct requestId and hostId on s3select error

---

src/mon/MonCommands.h
src/mon/OSDMonitor.cc

```
*  Forces removal of snapshots in the range of
*  [lower_snapid_bound, upper_snapid_bound) on pool <pool>
*  in order to cause OSDs to re-trim them.
*  The command has two mutually exclusive variants:
*  * Default: All the snapids in the given range which are not
*    marked as purged in the Monitor will be removed. Mostly useful
*    for cases in which the snapid is leaked in the client side.
*    See: https://tracker.ceph.com/issues/64646
```
Fixes: https://tracker.ceph.com/issues/66122
Possibly Fixes: https://tracker.ceph.com/issues/64519
---
Useful for leaks such as: https://tracker.ceph.com/issues/64646
Example usage:
```
POOL_NAME         USED  OBJECTS  CLONES  COPIES
unique_pool_0    8 KiB        2       1       2
$ rados lssnap -p unique_pool_0
0 snaps
$ ceph osd pool …
```

mon/OSDMonitor: Add force-remove-snap mon command

---

src/crimson/os/seastore/btree/btree_range_pin.cc
src/crimson/os/seastore/btree/btree_range_pin.h
src/crimson/os/seastore/btree/fixed_kv_node.h
src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/cached_extent.h
src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.h
src/crimson/os/seastore/lba_manager/btree/lba_btree_node.cc
src/crimson/os/seastore/lba_manager/btree/lba_btree_node.h
src/crimson/os/seastore/transaction.h
src/crimson/os/seastore/transaction_manager.h
src/test/crimson/seastore/test_transaction_manager.cc

backport of https://github.com/ceph/ceph/pull/57709

squid: crimson/os/seastore: avoid getting wrong logical extents through "parent-invalid" lba mappings

---

qa/standalone/osd/osd-recovery-space.sh

The osd-recovery-space test involves writing objects and expecting to receive the "toofull" flag.
If we don't wait long enough, we might check the "toofull" flag before all objects have completed writing, and the "toofull" status hasn't been activated yet.
The change will extend the waiting time and will also incorporate additional checks for the return code from the status wait.
Fixes: https://tracker.ceph.com/issues/44510
- When …

Test: osd-recovery-space.sh extends the wait time for "recovery toofull"

---

src/pybind/mgr/pg_autoscaler/module.py

Problem:
`ceph osd pool autoscale-status -f json`
and `ceph osd pool autoscale-status`
shows discrepeencies between each other
in the `pg_autoscale_mode` section,
when `no_autoscale` flag is set.
This is due to not showing
the output correctly.
Solution:
shows `false` in `pg_autoscale_mode` for
both `ceph osd pool autoscale-status` and
the json version of the command if `no_autoscale`
is set.
it sounds like a simple solution, but the problem
is more of a display problem rather than logic.
Fixes: https://tracker.ceph.com/issues/63860 …

src/pybind/mgr/pg_autoscaler/module.py: fix 'pg_autoscale_mode' output

---

src/osd/PrimaryLogPG.cc

valgrind errors show when we are erasing entry and then trying to use it. we need to keep the soid before the erase happen.
Fixes: https://tracker.ceph.com/issues/64942 …

PrimaryLogPG: Keep soid before erase entry

---

src/common/options/global.yaml.in
src/os/ObjectStore.cc
src/os/ObjectStore.h

The motivation behind this patch is to let users control the number of sweeps / number of objects per sweep during PG deletion which is currently restricited to `64` at max.
```
std::pair<ghobject_t, bool> PG::do_delete_work(
ObjectStore::Transaction &t,
ghobject_t _next)
{
// ...
int max = std::min(osd->store->get_ideal_list_max(),
(int)cct->_conf->osd_target_transaction_size);
``` …

osd: make the chunking in e.g. PG deletion controlable

---

src/rgw/rgw_auth.cc
src/rgw/rgw_auth.h

RemoteApplier::load_acct_info() and create_account() decide whether to add the implicit tenant. store the resulting rgw_user for use in get_aclowner(), is_owner_of(), and get_tenant()
potential fix for https://tracker.ceph.com/issues/66937? i don't know how to test this
<details>
</details>

rgw/auth: RemoteApplier respects implicit tenants

---

qa/workunits/rgw/test_rgw_orphan_list.sh
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/driver/rados/rgw_sal_rados.cc
src/tools/rados/rados.cc

Server-side copy copies the manifest from SRC->DST after incrementing the ref_count on the SRC tail-objects. The problem was that it uses the task-id as ref_tag and it got lost after the ref increment.When deleting the tail-objects from the COPY it passed in the obj_tag as ref_tag and since it was different from the one used during ref_inc it was ignored and the tail objects were never removed. This PR changes the ref_tag used for ref increment passing an MD5 of the bucket-name and the oid which is recreated when the COPY object is deleted
Fixes: https://tracker.ceph.com/issues/66286 …

rgw/rgw_rados: fix server side-copy orphans tail-objects

---

src/rgw/driver/rados/rgw_rados.cc
src/test/rgw/rgw_multi/tests.py

backport tracker: https://tracker.ceph.com/issues/67025
---
backport of https://github.com/ceph/ceph/pull/58519
parent tracker: https://tracker.ceph.com/issues/66983

squid: rgw/multisite: don't retain RGW_ATTR_OBJ_REPLICATION_TRACE attr on copy_object

---

doc/rados/operations/crush-map.rst

doc/rados/operations: remove obsolete vanity cluster name reference from crush-map.rst …

doc/rados/operations: remove vanity cluster name reference from crush-map.rst

---

src/ceph-volume/ceph_volume/tests/devices/lvm/test_migrate.py
src/ceph-volume/ceph_volume/tests/util/test_device.py
src/ceph-volume/ceph_volume/util/device.py
src/ceph-volume/ceph_volume/util/disk.py

This:
- Adds a new function `get_lvm_mappers` in `ceph_volume/util/disk.py` to retrieve a list of LVM device mappers.
- Updates the `is_lv` property in `ceph_volume/util/device.py` to use the new `get_lvm_mappers` function for better accuracy.
- Modifies the symlink handling in `Device` class to properly identify LVM logical volumes.
- Adds a new test `test_reject_lv_symlink_to_device` to ensure LVM symlinks are correctly identified and handled.
- Updates relevant tests to cover the changes in LVM device detection.
These changes improve the reliability and accuracy of LVM device detection and handling, ensuring that symlinks to LVM logical volumes are correctly processed.
Signed-off-by: Jerry Pu <jerrypu@qnap.com>
Co-Authored-by: Guillaume Abrioux <gabrioux@ibm.com>

ceph-volume: do not convert LVs's symlink to real path

---

src/crimson/common/tri_mutex.h

`squid` FTBFS:
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/fmt/include/fmt/core.h:1756:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
static_assert(
^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/fmt/include/fmt/core.h:1777:10: note: in instantiation of function template specialization 'fmt::detail::make_value<fmt::basic_format_context<fmt::appender, char>, const hobject_t &>' requested here
return make_value<Context>(val);
^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/fmt/include/fmt/core.h:1899:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, …
```

crimson/common/tri_mutex: avoid hobject_t formatting

---

src/common/map_cacher.hpp
src/common/sharedptr_registry.hpp
src/crimson/osd/pg.cc
src/osd/SnapMapper.h

backport of https://github.com/ceph/ceph/pull/57125

squid: crimson/osd/pg: reset the snap mapper's backend when pg interval changes

---

qa/tasks/cephfs/caps_helper.py
qa/tasks/cephfs/test_admin.py
src/client/Client.cc

The "Client::mds_check_access" expects the target_path without leading '/' as it eventually calls the "MDSCapMatch::match_path" which expects the target_path passed to be with out leading '/' as well.
The single leading '/' was being removed. But absolute path constructed did have leading '//', so removing all the leading '/' was necessary. 
This causes the clients not to be able to access a particular path even though it has a rw permission on the specific path.
The patches fixes the leading '//' issue.
Fixes: https://tracker.ceph.com/issues/67212 …

client: Fix leading / issue with mds_check_access

---

src/common/LogEntry.cc

This breaks `squid` branch makecheck
C++23 disallows conversion from 'int' to 'string'. That includes returning '0' from a function that returns a string.
(cherry picked from commit b854bfcc70ff372cd087c068e0302d36ad86391f) …

squid: common: fix string creation from '0' in LogEntry

---

src/rgw/driver/posix/bucket_cache.h
src/rgw/driver/posix/rgw_sal_posix.cc
src/rgw/driver/posix/rgw_sal_posix.h
src/test/rgw/CMakeLists.txt
src/test/rgw/test_posix_bucket_cache.cc
src/test/rgw/test_rgw_posix_driver.cc

This is a rework of the POSIXDriver.  It refactors out the actual posix parts into a set of classes that provide access to underlying directory/file/symlink, etc.  These primatives are used to build up full support for Bucket, Object, Multipart, and VersionedObjects. …

RGW - Add Multipart and Versioned POSIX

---

src/osd/PrimaryLogPG.cc
src/osd/osd_perf_counters.cc
src/osd/osd_perf_counters.h

For example, rbd send a watch ping to the header object every 5 seconds to keep watch, if the primary OSD is unable to receive the watch ping of the header object due to rbd network interruption, this means that rbd's I/O has already been hang. This way, we can quickly detect disconnection rbds on the osd, and reflected in metrics.
Sign-off-by: Yite Gu <yitegu0@gmail.com> …

osd: add watch ping timeout count in osd

---

qa/suites/rgw/notifications/valgrind.yaml

to help debug crashes like https://tracker.ceph.com/issues/65337
<details>
</details>

qa/rgw: enable valgrind in rgw/notifications suite

---

cmake/modules/BuildBoost.cmake

partial backport of https://github.com/ceph/ceph/pull/57581
backport tracker: https://tracker.ceph.com/issues/66724
original tracker: https://tracker.ceph.com/issues/66598
<details>
</details>

squid: build: Make boost_url a list

---

qa/tasks/cbt.py

backport tracker: https://tracker.ceph.com/issues/66807
---
backport of https://github.com/ceph/ceph/pull/58388
parent tracker: https://tracker.ceph.com/issues/66799

squid: qa/tasks: Initialize 'monitoring_profiles' spec to an empty dict

---

qa/tasks/cephfs/test_misc.py
src/pybind/ceph_argparse.py

$ceph tell cephfs_1.magna023.yvyxvl client ls
error handling command target: local variable 'poolid' referenced before assignment
The error message `local variable 'poolid' referenced before assignment` looks not  descriptive. The exception was not getting raised by the usage of `ArgumentValid` which was getting bypassed and hence code asks for poolid when no type has been provided in tell commands.
Now after this fix, we are getting the proper error message as type is unknown for above example. 
Fixes: https://tracker.ceph.com/issues/59624
- If you are submitting a fix for a stable branch …

pybind/ceph_argparse: Fix error message for ceph tell command

---

src/cls/rbd/cls_rbd_types.h
src/librbd/api/Group.cc
src/test/librados_test_stub/TestMemIoCtxImpl.cc
src/test/librbd/test_Groups.cc
src/test/pybind/test_rbd.py

backport tracker: https://tracker.ceph.com/issues/66590
---
backport of https://github.com/ceph/ceph/pull/58074 and https://github.com/ceph/ceph/pull/58300
parent tracker: https://tracker.ceph.com/issues/66300

quincy: librbd: disallow group snap rollback if memberships don't match

---

src/msg/Messenger.h

avoid calling stable_sort() after every insertion by inserting directly into the sorted position. use lower_bound() to insert at the head and upper_bound() to insert at the tail
this generally only happens during startup so isn't a performance problem, but std::stable_sort() was triggering strange valgrind warnings for "Mismatched free() / delete / delete []" when it allocates a temporary buffer
Fixes: https://tracker.ceph.com/issues/66336
<details>
- …

msg: insert PriorityDispatchers in sorted position

---

src/rgw/driver/rados/rgw_pubsub_push.cc
src/test/common/test_async_yield_waiter.cc

Fixes: https://tracker.ceph.com/issues/64184
<details>
</details>

rgw/async/notifications: use common async waiter in pubsub push

---

qa/workunits/rgw/test_rgw_orphan_list.sh
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/driver/rados/rgw_sal_rados.cc
src/tools/rados/rados.cc

backport tracker: https://tracker.ceph.com/issues/67269
---
backport of https://github.com/ceph/ceph/pull/58213
parent tracker: https://tracker.ceph.com/issues/66286

squid: rgw/rgw_rados: fix server side-copy orphans tail-objects

---

qa/workunits/rbd/luks-encryption.sh

backport tracker: https://tracker.ceph.com/issues/67059
---
backport of https://github.com/ceph/ceph/pull/58688 (with prerequisite commit from https://github.com/ceph/ceph/pull/40363)
parent tracker: https://tracker.ceph.com/issues/67051

quincy: qa/workunits/rbd: avoid caching effects in luks-encryption.sh

---

src/rgw/driver/posix/bucket_cache.h

resolves compiler warning:
```
rgw/driver/posix/bucket_cache.h: In instantiation of ‘bool file::listing::BucketCacheEntry<D, B>::reclaim(const cohort::lru::ObjectFactory*) [with D = rgw::sal::POSIXDriver; B = rgw::sal::POSIXBucket]’:
src/rgw/driver/posix/bucket_cache.h:139:8:   required from here
139 |   bool reclaim(const cohort::lru::ObjectFactory* newobj_fac) {
|        ^~~~~~~
src/rgw/driver/posix/bucket_cache.h:147:7: warning: ignoring return value of ‘std::lock_guard<_Mutex>::lock_guard(mutex_type&) [with _Mutex = std::mutex; mutex_type = std::mutex]’, declared with attribute ‘nodiscard’ [-Wunused-result]
147 |       lock_guard{mtx};
|       ^~~~~~~~~~
```
<details>
- …

rgw/posix: name the lock_guard in BucketCacheEntry::reclaim()

---

src/rgw/rgw_auth.cc
src/rgw/rgw_auth.h

backport tracker: https://tracker.ceph.com/issues/67267
---
backport of https://github.com/ceph/ceph/pull/58606
parent tracker: https://tracker.ceph.com/issues/66937

squid: rgw/auth: RemoteApplier respects implicit tenants

---

src/librbd/api/Migration.cc
src/librbd/migration/FileStream.cc
src/librbd/migration/FormatInterface.h
src/librbd/migration/HttpClient.cc
src/librbd/migration/ImageDispatch.cc
src/librbd/migration/ImageDispatch.h
src/librbd/migration/NativeFormat.cc
src/librbd/migration/NativeFormat.h
src/librbd/migration/OpenSourceImageRequest.cc
src/librbd/migration/OpenSourceImageRequest.h
src/librbd/migration/QCOWFormat.cc
src/librbd/migration/QCOWFormat.h
src/librbd/migration/RawFormat.cc
src/librbd/migration/RawFormat.h
src/librbd/migration/RawSnapshot.cc
src/librbd/migration/SourceSpecBuilder.cc
src/librbd/migration/SourceSpecBuilder.h
src/test/librbd/migration/test_mock_QCOWFormat.cc
src/test/librbd/migration/test_mock_RawFormat.cc

librbd/migration: don't instantiate NativeFormat, handle it via dispatch

---

src/script/backport-create-issue

Older versions of python-redmine may raise ResourceAttrError here instead of returning None, see [1].  Being prepared for an exception seems like a good idea regardless given how this field recently got recreated.
[1] https://github.com/maxtepkeev/python-redmine/commit/0de5689ef5891c1be263c0b3deb8b03966a9c5bd

script/backport-create-issue: handle ResourceAttrError when getting CF_TAGS

---

src/ceph-volume/ceph_volume/tests/devices/lvm/test_listing.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_migrate.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_zap.py
src/ceph-volume/ceph_volume/tests/objectstore/test_lvmbluestore.py
src/ceph-volume/ceph_volume/tests/util/test_device.py
src/ceph-volume/ceph_volume/util/device.py
src/ceph-volume/ceph_volume/util/disk.py

backport tracker: https://tracker.ceph.com/issues/67287
---
backport of https://github.com/ceph/ceph/pull/58424
parent tracker: https://tracker.ceph.com/issues/61597

squid: ceph-volume: do not convert LVs's symlink to real path

---

src/osd/scheduler/mClockScheduler.cc
src/osd/scheduler/mClockScheduler.h
src/test/osd/TestMClockScheduler.cc

feature: https://tracker.ceph.com/issues/66714
```
Author: zhangjianwei2 <zhangjianwei2_yewu@cmss.chinamobile.com>
Date:   Thu Jun 27 16:20:00 2024 +0800
osd/scheduler: add mclock queue length perfcounter
Easy to visualize the number of ops in each subqueue of mclock.
Add request statistics for each op_scheduler_class
daemon or tell command:
ceph daemon osd.0 perf dump mclock-shard-queue-0
{
"mclock-shard-queue-0": {
"mclock_immediate_queue_len": 0,
"mclock_client_queue_len": 0,
"mclock_recovery_queue_len": 6,
"mclock_best_effort_queue_len": 4,
"mclock_all_type_queue_len": 10
}
}
Signed-off-by: zhangjianwei2 <zhangjianwei2@cmss.chinamobile.com>
```

osd/scheduler: add mclock queue length perfcounter

---

src/mon/OSDMonitor.cc

The pg_upmap_primary items are not deleted after the pool is deleted from the cluster.
Fixes: https://tracker.ceph.com/issues/66867 …

mon: Remove any pg_upmap_primary mapping during remove a pool

---

src/rgw/rgw_amqp.cc

backport tracker: https://tracker.ceph.com/issues/67072
---
backport of https://github.com/ceph/ceph/pull/57737
parent tracker: https://tracker.ceph.com/issues/66266

reef: rgw/amqp: lock erase and create connection before emplace

---

src/crush/CrushWrapper.cc

When sanitizer is enabled, a part of 'run-cli-tests' output shows,
```
=================================================================
==1263095==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60c00000c000 at pc 0x7f80a4b0a040 bp 0x7ffe3176d550 sp 0x7ffe3176d548
READ of size 8 at 0x60c00000c000 thread T0
#0 0x7f80a4b0a03f in CrushWrapper::get_new_bucket_id() /home/jenkins-build/build/workspace/ceph-pull-requests/src/crush/CrushWrapper.cc:2189:10
#1 0x7f80a4b03f20 in CrushWrapper::reclassify(ceph::common::CephContext*, std::ostream&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, …
```

crush: avoid out-of-bound access and simplify enlarging buckets 

---

qa/suites/fs/multiclient/clusters/1-mds-2-client.yaml
qa/tasks/cephfs/test_misc.py
src/mds/MDSDaemon.cc
src/mds/MDSRank.cc
src/mds/SessionMap.cc

backport tracker: https://tracker.ceph.com/issues/67078
---
backport of https://github.com/ceph/ceph/pull/49974
parent tracker: https://tracker.ceph.com/issues/58619

squid: mds: fix session/client evict command.

---

src/common/MemoryModel.cc
src/common/MemoryModel.h
src/mds/MDCache.cc
src/mds/MDCache.h

**Performance:** per my off-line (code snippets) benchmarks
(see [benchtest](https://github.com/ronen-fr/memorymodel)):
- the parsing of /proc/status improved by 
1. only opening the proc file once (saves almost 40%)
2. using charconv
- for /proc/maps:
1. opening once (most of the improvement);
2. faster discarding of lines;
3. using charconv
**The API changes:**
- no output parameters;
- no internally-maintained samples;
- not issuing warning messages to the log directly;
The PR includes work by @athanatos & @shreekarSS,
picked from https://github.com/ceph/ceph/pull/54698

common: MemoryModel: performance improvements and API changes

---

src/pybind/mgr/osd_perf_query/module.py
src/pybind/mgr/rook/rook_cluster.py
src/pybind/mgr/zabbix/module.py

Get rid of DepricationWarning which according to https://docs.python.org/3.11/library/re.html
is going to become a SyntaxError. …

mgr: fix invalid escape sequence

---

src/script/ptl-tool.py

* Renames .github.key to .github_token to make it identical to ceph-backport.sh script.
This fix eliminates creating 2 files that stores the same thing.
* Rename the variables with the github/redmine conventions. …

ptl-tool: Fix token file name and variable names

---

qa/tasks/ceph_manager.py
qa/tasks/daemonwatchdog.py
qa/tasks/mon_thrash.py
qa/tasks/scrub.py
qa/tasks/thrasher.py
qa/tasks/thrashosds.py

If a thrasher exception occurs, the do_dump_ops thread will continue looping until the Teuthology timeout is reached.
The watchdog should terminate the thrasher to free up resources.
Fixes: https://tracker.ceph.com/issues/66698 …

qa/tasks: watchdog should terminate thrasher

---

.gitmodules

5843c6b04bacf9a7c981fca5d874ab3400f855db accidentally added back to the boost_redis submodule that was last removed in 924f2e9f87f0ee940eff363c26a714a309639d26
<details>
</details>

submodule: remove the boost_redis submodule again (again)

---

src/rgw/rgw_kafka.cc
src/rgw/rgw_kafka.h
src/rgw/rgw_pubsub_push.cc

backport tracker: https://tracker.ceph.com/issues/61478
---
backport of https://github.com/ceph/ceph/pull/51575
parent tracker: https://tracker.ceph.com/issues/61254

quincy: rgw/kafka: remove potential race condition between creation and deletion of endpoint

---

doc/radosgw/cloud-transition.rst
src/rgw/rgw_admin.cc
src/rgw/rgw_bucket_sync.cc
src/rgw/rgw_bucket_sync.h
src/rgw/rgw_common.h
src/rgw/rgw_lc_tier.cc
src/rgw/rgw_obj_manifest.cc
src/rgw/rgw_op.cc
src/rgw/rgw_op.h
src/rgw/rgw_putobj_processor.cc
src/rgw/rgw_rados.cc
src/rgw/rgw_rest_conn.cc
src/rgw/rgw_rest_conn.h
src/rgw/rgw_rest_s3.cc
src/rgw/rgw_zone.cc
src/rgw/services/svc_bucket_sync_sobj.cc
src/rgw/services/svc_zone.cc

This PR contains backports of below fixes -
https://github.com/ceph/ceph/pull/50098
https://github.com/ceph/ceph/pull/50172
https://github.com/ceph/ceph/pull/51192
https://github.com/ceph/ceph/pull/50676
https://github.com/ceph/ceph/pull/51511
https://github.com/ceph/ceph/pull/49803
https://github.com/ceph/ceph/pull/52160
Fixes: https://tracker.ceph.com/issues/59674
Fixes: https://tracker.ceph.com/issues/59644
Fixes: https://tracker.ceph.com/issues/61391
Fixes: https://tracker.ceph.com/issues/61389
Fixes: https://tracker.ceph.com/issues/58897
Fixes: https://tracker.ceph.com/issues/61481
Fixes: https://tracker.ceph.com/issues/61877 …

[quincy] RGW backports

---

src/rgw/rgw_asio_frontend.cc

backport tracker: https://tracker.ceph.com/issues/64767
---
backport of https://github.com/ceph/ceph/pull/55967
parent tracker: https://tracker.ceph.com/issues/64719

quincy: rgw/beast: Enable SSL session-id reuse speedup mechanism

---

src/rgw/rgw_admin.cc
src/rgw/rgw_bucket.cc
src/rgw/rgw_bucket.h
src/rgw/rgw_rados.cc
src/rgw/rgw_rados.h
src/rgw/services/svc_bi_rados.h

backport tracker: https://tracker.ceph.com/issues/65891
---
backport of https://github.com/ceph/ceph/pull/57083
parent tracker: https://tracker.ceph.com/issues/65769

quincy: rgw: make incomplete multipart upload part of bucket check efficient

---

src/crimson/osd/pg.cc
src/crimson/osd/pg.h
src/crimson/osd/replicated_backend.cc

Fixes: https://tracker.ceph.com/issues/67327 …

crimson/osd: send empty transactions to backfill targets that haven't backfilled the objects yet

---

src/os/bluestore/BlueStore.cc

I just find it hard to deal with bazillion abbreviations on a single function that spans hundreds of lines. This prs renames the following variables:
* previous_p -> previous_shard
* p -> shard
* sp -> current_shard
* esp -> end_shard
* si_begin -> shard_index_begin
* si_end -> shard_index_end
* e -> extent
* bs -> blob_start
* be -> blob_end
* sv -> extent_map_shards …

os/bluestore: Improve Readability of Extent Map Sharding

---

qa/suites/rgw/notifications/tasks/0-install.yaml
qa/tasks/kafka.py
qa/tasks/rabbitmq.py
src/test/rgw/bucket_notification/test_bn.py

backport tracker: https://tracker.ceph.com/issues/66711
---
backport of https://github.com/ceph/ceph/pull/54025
parent tracker: https://tracker.ceph.com/issues/63205

quincy: rgw/notifications/test: fix rabbitmq and kafka issues in centos9

---

src/rgw/rgw_rest_iam.cc
src/rgw/rgw_rest_pubsub.cc
src/rgw/rgw_rest_sts.cc
src/rgw/rgw_rest_user_policy.cc

backport tracker: https://tracker.ceph.com/issues/64227
---
backport of https://github.com/ceph/ceph/pull/55329
parent tracker: https://tracker.ceph.com/issues/64189

quincy: rgw/rest: fix url decode of post params for iam/sts/sns

---

src/rgw/rgw_rados.cc

backport tracker: https://tracker.ceph.com/issues/55502
---
backport of https://github.com/ceph/ceph/pull/45882
parent tracker: https://tracker.ceph.com/issues/55131

quincy: rgw: address crash and race in RGWIndexCompletionManager

---

qa/workunits/cephtool/test.sh
src/mon/FSCommands.cc

Applying `fs set down false` on an up cluster will set the cluster's max_mds to 1, regardless of the cluster's current max_mds.
`fs set down false` should only change max_mds when the cluster was set to down. Otherwise, the cluster should remain unchanged. …

mon: fix `fs set down` to adjust max_mds only when cluster is not down

---

doc/dev/peering.rst

This commit updates the peering doc page with the changed [2,1,2] to [3,1,2]

doc/dev/peering: Change acting set num

---

qa/suites/fs/valgrind/mirror/cephfs-mirror/one-per-cluster.yaml

Drop `--show-reachable=yes` from fs:valgrind tests as it shows CommandFailedError, which fails starting cephfs-mirror daemon and prevents the valgrind checks and reports. rbd:valgrind tests doesn't use `--show-reachable=yes` too.
So dropping `--show-reachable=yes` to make it analogous to rbd:valgrind.
Fixes: https://tracker.ceph.com/issues/64752
Fixes: https://tracker.ceph.com/issues/62221 …

qa/suites: drop --show-reachable=yes from fs:valgrind tests

---

qa/tasks/cephfs/test_sessionmap.py
src/mds/Server.cc

When evicting the clients or sessions during the
mds_session_blocklist_on_evict option is disabled the clients should reconnect to MDS successfully later after new IOs being sent.
URL: https://tracker.ceph.com/issues/65647 …

qa/cephfs: add test_session_evict_non_blocklisted test case

---

src/ceph-volume/ceph_volume/util/encryption.py

backport tracker: https://tracker.ceph.com/issues/66465
---
backport of https://github.com/ceph/ceph/pull/57925
parent tracker: https://tracker.ceph.com/issues/66393

reef: ceph-volume: fix set_dmcrypt_no_workqueue()

---

src/common/options/global.yaml.in
src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/os/bluestore/bluestore_common.h
src/os/bluestore/bluestore_tool.cc
src/test/objectstore/store_test.cc
src/test/objectstore/store_test_fixture.cc
src/test/objectstore/store_test_fixture.h
src/test/objectstore/test_bluefs.cc

Corruption of bdev label makes it very hard to recover OSD.
This PR copies bdev label to 4 potential replica places on device: 
0(original), 1GB, 10GB, 100GB, 1000GB.
If all replicas do not match system refuses to start.
Fsck (repair mode) is the way to fix it.
This is an alternative version for #53095. Borrows many concepts and some code from it. …

os/bluestore: Multiple bdev labels on main block device

---

src/script/cpu-map.sh

This PR adds a set of utility scripts (inspired/based on previous existing scripts), adapted for learning exercises.
tool (based on `scripts/seastar-cpu-map.sh`) to set the CPU core affinity for a group of threads within a process. This is useful when experimenting to set different groups of threads on different CPU cores.
` cpu-map.sh -p <process_PIDs comma separated> -n <process_Name> -g <group-name:affinity-range>`
The user needs to edit the associative arrays in the script to suit for particular requirements.
There are examples at the top of the script, which should make it easier to edit accordingly.
This is an example of the execution and the resulting CPU core assignment.
Lets assume you create a cluster with vstart as follows:
`MDS=0 MON=1 OSD=1 MGR=1 ../src/vstart.sh --new -x …

script/: add cpu-map.sh to aid manual selection of CPU cores for threads for profiling

---

src/os/bluestore/BlueFS.cc

backport tracker: https://tracker.ceph.com/issues/64592
---
backport of https://github.com/ceph/ceph/pull/55700
parent tracker: https://tracker.ceph.com/issues/64533

quincy: os/bluestore: fix the problem of l_bluefs_log_compactions double recording

---

src/kv/RocksDBStore.cc

backport tracker: https://tracker.ceph.com/issues/65914
---
backport of https://github.com/ceph/ceph/pull/55676
parent tracker: https://tracker.ceph.com/issues/64511

quincy: kv/RocksDBStore: Configure compact-on-deletion for all CFs

---

src/os/bluestore/bluestore_types.h

backport tracker: https://tracker.ceph.com/issues/67136
---
backport of https://github.com/ceph/ceph/pull/56937
parent tracker: https://tracker.ceph.com/issues/65482

quincy: bluestore/bluestore_types: avoid heap-buffer-overflow in another way to keep code uniformity

---

src/librbd/io/QosImageDispatch.cc
src/librbd/io/QosImageDispatch.h

The function `QosImageDispatch::set_throttle_flag` performs 2 atomic operations (`load` and `compare_exchange_weak`) and may be called up to 6 times per I/O by `QosImageDispatch::needs_throttle`  for each of the QOS limits documented here: https://docs.ceph.com/en/quincy/rbd/rbd-config-ref/#qos-settings. 
The end result is up to 12 atomic operations per I/O to process throttling, which seems quite excessive considering that this happens even in the default case where all the QOS limits are disabled.
This PR proposes the following improvements:
1. Skip calling `needs_throttle` in the default case where no QOS limits are enabled (reduces atomic ops per I/O from 12 to 0).
2. If QOS limits are enabled, modify `needs_throttle` to set all of the flags in a single call to `set_throttle_flag` …

librbd: Reduce use of atomics in librbd throttling

---

src/ceph-volume/ceph_volume/devices/lvm/listing.py

backport tracker: https://tracker.ceph.com/issues/64642
---
backport of https://github.com/ceph/ceph/pull/53841
parent tracker: https://tracker.ceph.com/issues/62320

reef: src/ceph-volume/ceph_volume/devices/lvm/listing.py : lvm list filters with vg name

---

doc/cephfs/snap-schedule.rst
qa/tasks/cephfs/test_snap_schedules.py
src/pybind/mgr/snap_schedule/fs/schedule.py
src/pybind/mgr/snap_schedule/fs/schedule_client.py

backport tracker: https://tracker.ceph.com/issues/65900
---
backport of https://github.com/ceph/ceph/pull/56732
parent tracker: https://tracker.ceph.com/issues/65350

quincy: mgr/snap_schedule: restore yearly spec to lowercase y

---

qa/tasks/cephfs/test_nfs.py

The patches that add object formatting / decorators to the nfs module also made error handling more generic when accessing an nfs cluster and now returns a nonzero exit code. A test was after the PR adding the object format support that only checked an error message. Update the test to match the new nfs module behavior as well as fixing a typo.
Signed-off-by: John Mulligan <jmulligan@redhat.com>
(cherry picked from commit e03331e7c4412e33fe55d7a41a22dfeba17cb463)
Fixes: https://tracker.ceph.com/issues/65644 …

quincy: qa/test_nfs: fix test failure when cluster does not exist

---

qa/tasks/cephfs/cephfs_test_case.py

Replace call to run_ceph_cmd() by call to get_ceph_cmd_stdout() in
method qa.tasks.cephfs.cephfs_test_case.CephFSTestCase.create_client().
run_ceph_cmd() will not return keyring which is wrong.
get_ceph_cmd_stdout() will return the stdout of "ceph auth add"
command, which is the keyring that is expected to be returned by
CephFSTestCase.create_client().
Fixes: https://tracker.ceph.com/issues/62246
(cherry picked from commit c9058dc7a57530df592b9945d36cf71459946f4f)
Conflicts:
* qa/tasks/cephfs/cephfs_test_case.py
Conflict occurred because class RunCephCmd hasn't been backported.
This PR is getting it done - https://github.com/ceph/ceph/pull/54946.
Parent ticket - https://tracker.ceph.com/issues/65441 …

quincy: qa/cephfs: CephFSTestCase.create_client() must keyring

---

src/cephadm/cephadm.py
src/cephadm/cephadmlib/daemons/smb.py

Implement a `get_version()` method to figure out the version of samba running inside the container using _smbd_. This will help us to avoid reporting version as **_\<unknown\>_** while listing the daemons via `ceph orch ps`.
```
NAME                            HOST      PORTS  STATUS        REFRESHED  AGE  MEM USE  MEM LIM  VERSION    IMAGE ID      CONTAINER ID  
smb.smbcluster.storage2.zxdpon  storage2  *:445  running (4d)     8m ago   4d        -        -  <unknown>  45fed2ab2897  a495f053efe8  
```

cephadm/smb: Determine samba version within container

---

doc/cephadm/operations.rst
src/pybind/mgr/cephadm/inventory.py
src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/serve.py
src/pybind/mgr/cephadm/tests/test_cephadm.py

backport tracker: https://tracker.ceph.com/issues/65380
---
backport of https://github.com/ceph/ceph/pull/56713
parent tracker: https://tracker.ceph.com/issues/65335

quincy: mgr/cephadm: make client-keyring deploying ceph.conf optional

---

src/cephadm/cephadm
src/cephadm/tests/test_cephadm.py

backport tracker: https://tracker.ceph.com/issues/65419
---
backport of https://github.com/ceph/ceph/pull/56561
parent tracker: https://tracker.ceph.com/issues/65122

quincy: cephadm: fix host-maintenance command always exiting with a failure

---

src/pybind/mgr/cephadm/services/iscsi.py

backport tracker: https://tracker.ceph.com/issues/65950
---
backport of https://github.com/ceph/ceph/pull/57181
parent tracker: https://tracker.ceph.com/issues/65717

quincy: mgr/cephadm: cleanup iscsi keyring upon daemon removal

---

src/cephadm/cephadm

backport tracker: https://tracker.ceph.com/issues/65967
---
backport of https://github.com/ceph/ceph/pull/57205
parent tracker: https://tracker.ceph.com/issues/65739

quincy: mgr/cephadm: make setting --cgroups=split configurable for adopted daemons

---

src/cephadm/cephadm

backport tracker: https://tracker.ceph.com/issues/66790
---
backport of https://github.com/ceph/ceph/pull/57975
parent tracker: https://tracker.ceph.com/issues/66436

quincy: cephadm: disable ms_bind_ipv4 if we will enable ms_bind_ipv6

---

src/osd/PeeringState.cc

Currently, in `calc_replicated_acting_stretch` 
we would call `pop_ancester` before checking whether 
the next OSD we populate in the want_acting set would have
the ancestor count that is >= bucket_max.
Fixes: https://tracker.ceph.com/issues/65371
THIS PR SHOULD BE TESTED IN CONJUNCTION WITH https://github.com/ceph/ceph/pull/56233 …

PeeringState.cc: Only populate want_acting when num_osds < bucket_max

---

doc/rados/operations/pools.rst
doc/rados/operations/stretch-mode.rst
qa/suites/rados/singleton/all/3-az-stretch-cluster-netsplit.yaml
qa/suites/rados/singleton/all/mon-stretch-pool.yaml
qa/tasks/ceph_manager.py
qa/tasks/ceph_test_case.py
qa/tasks/stretch_cluster.py
qa/tasks/test_netsplit_3az_stretch_pool.py
qa/workunits/mon/mon-stretch-pool.sh
src/mon/MonCommands.h
src/mon/OSDMonitor.cc
src/mon/OSDMonitor.h
src/osd/osd_types.cc

THIS PR SHOULD BE TESTED IN CONJUNCTION WITH https://github.com/ceph/ceph/pull/57381
Recommend merging https://github.com/ceph/ceph/pull/57381 before this PR.
In the command `ceph osd pool stretch set`
```
<pool> <peering_crush_bucket_count>
<peering_crush_bucket_target> <peering_crush_bucket_barrier> <crush_rule> <size> <min_size>
```
user has the option of setting the value of `peering_crush_bucket_{count|target|barrier}`.
This will then allow the utilization `calc_replicated_acting_stretch`,
since with `peering_crush_bucket_count != 0`
the pool is now a stretch_pool and we can handle pg_temp
better by setting barriers and limits to how much OSDs
should be in a `pg_temp`.
This will enable the specify pool to
handle `pg_temp` properly during `create_acting`, as a stretch pool
should. …

RADOS: Generalize stretch mode pg temp handling to be usable without stretch mode

---

doc/cephadm/services/smb.rst

`user_sources` option to smb service spec was missing from the [docs](https://docs.ceph.com/en/latest/cephadm/services/smb/#service-spec-options).

doc/cephadm/smb: Add missing user_sources option to service spec

---

src/mon/OSDMonitor.cc
src/mon/OSDMonitor.h

backport tracker: https://tracker.ceph.com/issues/64649
---
backport of https://github.com/ceph/ceph/pull/54999
parent tracker: https://tracker.ceph.com/issues/63883

quincy: mon/OSDMonitor: fix get_min_last_epoch_clean()

---

src/osd/SnapMapper.cc

backport tracker: https://tracker.ceph.com/issues/65307
---
backport of https://github.com/ceph/ceph/pull/55562
parent tracker: https://tracker.ceph.com/issues/64347

quincy: osd/SnapMapper: fix _lookup_purged_snap

---

cmake/modules/BuildBoost.cmake

partial backport of https://github.com/ceph/ceph/pull/57581
backport tracker: https://tracker.ceph.com/issues/66725
original tracker: https://tracker.ceph.com/issues/66598
required additional backport of f356cc8869eb7233865faea65351851c5e38fe18 which was present on reef but not quincy
<details> …

quincy: build: Make boost_url a list

---

qa/tasks/cephfs/test_data_scan.py
src/mds/MDBalancer.cc

backport tracker: https://tracker.ceph.com/issues/64046
---
backport of https://github.com/ceph/ceph/pull/54590
parent tracker: https://tracker.ceph.com/issues/57087

quincy: qa: set mds config with `config set` for a particular test

---

qa/tasks/cephfs/test_mirroring.py
src/pybind/mgr/mirroring/fs/snapshot_mirror.py

Fixes: https://tracker.ceph.com/issues/64074 …

quincy: pybind/mgr/mirroring: drop mon_host from peer_list

---

src/mount.fuse.ceph

Backport tracker: https://tracker.ceph.com/issues/62426
<details>
</details>

quincy: nofail option in fstab not supported

---

qa/cephfs/conf/mgr.yaml

backport tracker: https://tracker.ceph.com/issues/66633
---
backport of https://github.com/ceph/ceph/pull/56296
parent tracker: https://tracker.ceph.com/issues/64985

quincy: qa/cephfs: add mgr debugging

---

qa/suites/fs/nfs/overrides/ignorelist_health.yaml

backport tracker: https://tracker.ceph.com/issues/66635
---
backport of https://github.com/ceph/ceph/pull/56299
parent tracker: https://tracker.ceph.com/issues/64987

quincy: qa/suites/fs/nfs: use standard health ignorelist

---

qa/workunits/kernel_untar_build.sh

backport tracker: https://tracker.ceph.com/issues/66636
---
backport of https://github.com/ceph/ceph/pull/54414
parent tracker: https://tracker.ceph.com/issues/57655

quincy: qa: run kernel_untar_build with newer tarball

---

src/pybind/mgr/stats/fs/perf_stats.py

Fixes the error in teuthology log:
AttributeError: 'FSPerfStats' object has no attribute 'mx_last_updated'
Fixes: https://tracker.ceph.com/issues/65073
(cherry picked from commit b96ad6126110b292fca053fdfc6a956a6eb0f01e)

quincy: mgr/stats: initialize mx_last_updated in FSPerfStats

---

src/cephadm/cephadm

Backport of https://github.com/ceph/ceph/pull/56143
<details>
</details>

quincy: cephadm: add timemaster to timesync services list

---

src/python-common/ceph/deployment/service_spec.py
src/python-common/ceph/tests/test_service_spec.py

backport tracker: https://tracker.ceph.com/issues/65726
---
backport of https://github.com/ceph/ceph/pull/56928
parent tracker: https://tracker.ceph.com/issues/65511

quincy: python-common: handle "anonymous_access: false" in to_json of Grafana spec

---

src/cephadm/cephadm

backport tracker: https://tracker.ceph.com/issues/66957
---
backport of https://github.com/ceph/ceph/pull/58379
parent tracker: https://tracker.ceph.com/issues/66848

quincy: cephadm: turn off cgroups_split setting  when bootstrapping with --no-cgroups-split

---

qa/suites/orch/cephadm/smoke/start.yaml
qa/suites/orch/cephadm/workunits/task/test_host_drain.yaml
qa/suites/orch/cephadm/workunits/task/test_rgw_multisite.yaml
qa/suites/orch/cephadm/workunits/task/test_set_mon_crush_locations.yaml
qa/suites/upgrade/pacific-x/parallel/1-tasks.yaml
qa/tasks/thrashosds-health.yaml

backport tracker: https://tracker.ceph.com/issues/66477
---
backport of https://github.com/ceph/ceph/pull/56619
parent tracker: https://tracker.ceph.com/issues/64864

quincy: qa/suites: add "mon down" log variations to ignorelist

---

src/cls/rbd/cls_rbd.cc
src/cls/rbd/cls_rbd_client.cc
src/cls/rbd/cls_rbd_client.h
src/test/cls_rbd/test_cls_rbd.cc

To make this possible the snapshot order is stored on a snapshot
creation and the shapshot list result is sorted using this order
before returning to the caller.
This change adds a restriction on start_after parameter: now it
may be either the empty string id (to start at the beginning) or
an existing snapshot id. Otherwise -ERESTART is returned to inform
the caller that the "start_after" snapshot is invalid/removed and
the listing should be restarted.
Fixes: https://tracker.ceph.com/issues/51686
Original Author:  Mykola Golub [mgolub@suse.com](mailto:mgolub@suse.com) …

cls/rbd: add group_snap_list_order method to enable sorting snapshots in creation order

---

qa/workunits/rbd/luks-encryption.sh
src/librbd/io/ReadResult.cc
src/librbd/io/ReadResult.h
src/librbd/migration/ImageDispatch.cc
src/librbd/migration/OpenSourceImageRequest.cc

See bug report here:
https://tracker.ceph.com/issues/53674
This PR depends on #43804 
<details>
</details>

librbd/crypto: fix issue when live-migrating from encrypted export

---

src/osd/scrubber/osd_scrub_sched.cc
src/osd/scrubber/pg_scrubber.cc
src/osd/scrubber/scrub_job.h

Existing code exempts all 'high priority' scrubs, including for example 'after_repair' and 'mandatory on invalid history' scrubs from the limit.
PGs that do not have valid last-scrub data (which is what we have when a pool is first created) - are set to shallow-scrub immediately. Unfortunately - this type of scrub is (in the low granularity implemented in existing code) is 'high priority'.
Which means that a newly created pool will have all its PGs start scrubbing, regardless of concurrency (or any other) limits.
Backport of https://github.com/ceph/ceph/pull/58929
Original tracker: https://tracker.ceph.com/issues/67253
Backport tracker: https://tracker.ceph.com/issues/67305

squid: osd/scrub: exempt only operator scrubs from max_scrubs limit

---

src/crimson/os/seastore/async_cleaner.h
src/crimson/os/seastore/btree/fixed_kv_btree.h
src/crimson/os/seastore/cache.h
src/crimson/os/seastore/cached_extent.h
src/crimson/os/seastore/transaction.h
src/crimson/os/seastore/transaction_manager.cc

I'm looking at the boundary of Cache component.
This might be a good basis to proceed to fix cache metrics and fine-grained-cache (https://github.com/ceph/ceph/pull/57787)
Manual rough tests looks good. @xxhdx1985126 Does the revised version of `get_extent_viewable_by_trans()` look reasonable to you? …

crimson/os/seastore/cache: cleanups and comments

---

src/pybind/mgr/dashboard/controllers/pool.py
src/pybind/mgr/dashboard/controllers/rbd_mirroring.py
src/pybind/mgr/dashboard/frontend/cypress/e2e/pools/pools.e2e-spec.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/pools/pools.po.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.ts
src/pybind/mgr/dashboard/openapi.yaml

backport tracker: https://tracker.ceph.com/issues/66396
---
backport of https://github.com/ceph/ceph/pull/57755
parent tracker: https://tracker.ceph.com/issues/66267

squid: mgr/dashboard: provide option to enable pool based mirroring mode while creating a pool

---

src/include/elist.h
src/mds/CDentry.cc
src/mds/CDentry.h
src/mds/CDir.cc
src/mds/Capability.cc
src/mds/Capability.h
src/mds/Locker.cc
src/mds/Locker.h
src/mds/MDCache.cc
src/mds/MDSCacheObject.h
src/mds/SnapRealm.h

This is a partial revival of @ukernel's optimization PR: https://github.com/ceph/ceph/pull/43126
which has 
- reducing RAM consumption in Capability tracking.
- doing some performance optimization in ClientLease tracking. 
- optimize sending cap messages by using target session directly instead of looking it up through Inode's client_caps.
The last commit from myself switches ClientLease tracking from std::map to boost::intrusive::set to reduce amount of lookups over client_leases collection . …

mds: some optimizations around client Capability and Lease tracking

---

src/crimson/os/seastore/async_cleaner.cc
src/crimson/os/seastore/async_cleaner.h
src/crimson/os/seastore/journal/segment_allocator.cc
src/crimson/os/seastore/seastore_types.cc
src/crimson/os/seastore/seastore_types.h

OOL segments don't contain record headers anymore, we use segment_header_t::modify_time as the approximation of segment modify_time
Fixes: https://tracker.ceph.com/issues/67106 …

crimson/os/seastore: consider segment_header_t::modify_time as the segments' modify_time for no-tail OOL segments

---

src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/extent_placement_manager.cc
src/crimson/os/seastore/extent_placement_manager.h
src/crimson/os/seastore/journal/circular_bounded_journal.cc
src/crimson/os/seastore/journal/circular_journal_space.cc
src/crimson/os/seastore/journal/circular_journal_space.h
src/crimson/os/seastore/journal/record_submitter.cc
src/crimson/os/seastore/journal/record_submitter.h
src/crimson/os/seastore/journal/segment_allocator.cc
src/crimson/os/seastore/journal/segment_allocator.h
src/crimson/os/seastore/journal/segmented_journal.cc
src/crimson/os/seastore/ordering_handle.h
src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/segment_manager/block.cc
src/crimson/os/seastore/transaction.h

Essential changes:
1. Refactor `RecordSubmitter` to make the write base available upon submitting ool writes.
2. Refactors in ool to move necessary updates before ool writes, see commits:
* "`RandomBlockOolWriter` to update extents upon submitting writes".
* "`SegmentedOolWriter` to update ool paddr upon submitting writes".
3. Move ool write futures into the concurrent `DeviceSubmission` phase, see commit:
* "wait ool writes in `DeviceSubmission` phase".
----
The issue was observed from https://github.com/ceph/ceph/pull/58467, that there are many waiters blocked by the collection lock, and this PR tries to decouple (maybe slow) IO writes out of the lock.
The observed benefits are:
1. The random write end-performance was improved by ~3 ~6% from local fio-rbd tests (1 OSD, 32 cores, …

crimson/os/seastore: move ool writes from collection lock to concurrent DeviceSubmission phase

---

README.md

Add information in the "Building Ceph" procedure to the steps where it belongs. Add information about "do_cmake.sh" to the step about "do_cmake.sh". Add information about Ninja to the step about Ninja. …

doc/README.md - allocate information correctly

---

src/crimson/os/seastore/async_cleaner.cc
src/crimson/os/seastore/async_cleaner.h
src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/seastore.h
src/crimson/os/seastore/seastore_types.h
src/crimson/os/seastore/transaction_manager.cc
src/crimson/os/seastore/transaction_manager.h
src/crimson/osd/osd.cc
src/crimson/tools/store_nbd/tm_driver.cc
src/crimson/tools/store_nbd/tm_driver.h
src/test/crimson/seastore/transaction_manager_test_state.h

backport of https://github.com/ceph/ceph/pull/58467

squid: crimson/os/seastore: track transactions/conflicts/outstanding periodically

---

src/crimson/os/seastore/transaction_manager.cc

backport of https://github.com/ceph/ceph/pull/58551

squid: crimson/os/seastore/transaction_manager: consider inconsistency between backrefs and lbas acceptable when cleaning segments

---

src/crimson/admin/pg_commands.cc
src/crimson/osd/osd_operations/background_recovery.cc
src/crimson/osd/osd_operations/client_request.cc
src/crimson/osd/osd_operations/internal_client_request.cc
src/crimson/osd/osd_operations/internal_client_request.h
src/crimson/osd/osd_operations/logmissing_request.cc
src/crimson/osd/osd_operations/logmissing_request_reply.cc
src/crimson/osd/osd_operations/peering_event.cc
src/crimson/osd/osd_operations/recovery_subrequest.cc
src/crimson/osd/osd_operations/replicated_request.cc
src/crimson/osd/osd_operations/scrub_events.cc
src/crimson/osd/pg.cc
src/crimson/osd/pg_interval_interrupt_condition.cc
src/crimson/osd/pg_interval_interrupt_condition.h

backport of https://github.com/ceph/ceph/pull/58463

squid: crimson: audit and correct epoch captured by IOInterruptCondition

---

src/crimson/os/alienstore/alien_store.cc
src/crimson/os/alienstore/alien_store.h

backport of https://github.com/ceph/ceph/pull/58766

squid: crimson: access coll_map under alien tp with a lock

---

src/crimson/osd/scrub/scrub_validator.cc

backport of https://github.com/ceph/ceph/pull/58471

squid: src/crimson/osd/scrub: fix the null pointer error

---

src/crimson/osd/pg_recovery.cc

backport of https://github.com/ceph/ceph/pull/58504

squid: crimson/osd/pg_recovery: push the iteration forward after finding unfound objects when starting primary recoveries

---

doc/man/8/ceph.rst
qa/workunits/cephtool/test.sh
src/mon/MonCommands.h
src/mon/OSDMonitor.cc

backport tracker: https://tracker.ceph.com/issues/59084
---
backport of https://github.com/ceph/ceph/pull/45409
parent tracker: https://tracker.ceph.com/issues/54576

quincy: mon: add proxy to cache tier options

---

qa/crontab/teuthology-cronjobs

Followup to https://github.com/ceph/ceph/pull/58800/commits/3f62db0393b2d1516a447fd13d83f6bf26bbd99b. The suite is large, so we need to force the priority. This is warranted since the rados team makes a lot of use of the main runs. …

qa/crontab: force priority for main rados nightlies

---

qa/suites/rados/singleton/all/mon-config-keys.yaml

backport tracker: https://tracker.ceph.com/issues/66040
---
backport of https://github.com/ceph/ceph/pull/56146
parent tracker: https://tracker.ceph.com/issues/64725

quincy: qa/suites/rados/singleton: add POOL_APP_NOT_ENABLED to ignorelist

---

src/mgr/Mgr.cc

backport tracker: https://tracker.ceph.com/issues/63365
---
backport of https://github.com/ceph/ceph/pull/53993
parent tracker: https://tracker.ceph.com/issues/63195

reef: mgr: remove out&down osd from mgr daemons

---

doc/man/8/ceph-objectstore-tool.rst
src/tools/ceph_objectstore_tool.cc

backport tracker: https://tracker.ceph.com/issues/63880
---
backport of https://github.com/ceph/ceph/pull/54023
parent tracker: https://tracker.ceph.com/issues/63877

reef: tools/ceph_objectstore_tool: Support get/set/superblock

---

README.md

Add "tip" alert styling (what in Docbook XML is called "an admonition") to information about Ninja in an ordered list (which is what markdown has here instead of procedures). …

doc/README.md - add "tip" alert styling

---

src/os/ObjectStore.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/os/kstore/KStore.h
src/os/memstore/MemStore.h
src/test/objectstore/store_test.cc

This allows to get rid off relevant sleep() calls in store_test.
Parent tracker: https://tracker.ceph.com/issues/63106
Backport of: https://github.com/ceph/ceph/pull/54194
Backport tracker: https://tracker.ceph.com/issues/63322 …

reef: os: introduce ObjectStore::refresh_perf_counters() method 

---

qa/tasks/cephadm.py
src/cephadm/cephadm.py
src/cephadm/cephadmlib/daemons/ceph.py
src/cephadm/tests/test_cephadm.py

This drops the /sys, /dev, and / (on rootfs) mounts from the shell, as these shouldn't be required and it also makes the ceph-volume commands monut of / a slave mount so there isn't an issue unmounting things on the host due to the container having this mount. …

cephadm: limit mounts for shell and ceph-volume commands

---

src/rgw/rgw_rest_client.cc

backport tracker: https://tracker.ceph.com/issues/64326
---
backport of https://github.com/ceph/ceph/pull/54311
parent tracker: https://tracker.ceph.com/issues/63438

reef: RGW: fix cloud-sync not being able to sync folders

---

qa/suites/rgw/tempest/tasks/rgw_tempest.yaml
src/rgw/rgw_common.cc
src/rgw/rgw_common.h
src/rgw/rgw_op.cc
src/rgw/rgw_rest.cc
src/rgw/rgw_rest_swift.cc

backport tracker: https://tracker.ceph.com/issues/63621
----
backport of https://github.com/ceph/ceph/pull/50790
parent tracker: https://tracker.ceph.com/issues/51772 …

reef: rgw/swift: preserve dashes/underscores in swift user metadata names

---

src/cls/rgw/cls_rgw.cc
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/rgw_op.cc

backport tracker: https://tracker.ceph.com/issues/64325
---
backport of https://github.com/ceph/ceph/pull/55252
parent tracker: https://tracker.ceph.com/issues/21800

reef: rgw/multisite: avoid writing multipart parts to the bucket index log

---

src/rgw/rgw_asio_frontend.cc

backport tracker: https://tracker.ceph.com/issues/65886
---
backport of https://github.com/ceph/ceph/pull/57155
parent tracker: https://tracker.ceph.com/issues/65664

reef: rgw/beast: fix crash observed in SSL stream.async_shutdown()

---

qa/workunits/rgw/test_rgw_reshard.py

backport tracker: https://tracker.ceph.com/issues/67155
---
backport of https://github.com/ceph/ceph/pull/58670
parent tracker: https://tracker.ceph.com/issues/66367

reef: test/rgw: address potential race condition in reshard testing

---

src/rgw/rgw_rest_s3.cc

backport tracker: https://tracker.ceph.com/issues/54201
---
backport of https://github.com/ceph/ceph/pull/44678
parent tracker: https://tracker.ceph.com/issues/53945

quincy: rgw: CopyObject works with x-amz-copy-source-if-* headers

---

src/rgw/rgw_rados.cc

backport tracker: https://tracker.ceph.com/issues/55151
---
backport of https://github.com/ceph/ceph/pull/45300
parent tracker: https://tracker.ceph.com/issues/54499

quincy: rgw: Update "CEPH_RGW_DIR_SUGGEST_LOG_OP" for remove entries

---

src/rgw/rgw_admin.cc

backport tracker: https://tracker.ceph.com/issues/55062
---
backport of https://github.com/ceph/ceph/pull/45309
parent tracker: https://tracker.ceph.com/issues/54504

quincy: radosgw-admin: fix segfault on pipe modify without source/dest zone specified

---

src/rgw/rgw_op.cc

backport tracker: https://tracker.ceph.com/issues/59730
---
backport of https://github.com/ceph/ceph/pull/50627
parent tracker: https://tracker.ceph.com/issues/58879

quincy: RGW: Solving the issue of not populating etag in Multipart upload result

---

src/rgw/rgw_rados.cc

backport tracker: https://tracker.ceph.com/issues/61431
---
backport of https://github.com/ceph/ceph/pull/51516
parent tracker: https://tracker.ceph.com/issues/61198

quincy: rgw: multisite data log flag not used

---

src/rgw/rgw_object_lock.cc

backport tracker: https://tracker.ceph.com/issues/62139
---
backport of https://github.com/ceph/ceph/pull/52056
parent tracker: https://tracker.ceph.com/issues/56993

quincy: rgw: s3 object lock avoids overflow in retention date

---

src/rgw/rgw_op.cc

backport tracker: https://tracker.ceph.com/issues/54610
---
backport of https://github.com/ceph/ceph/pull/45343
parent tracker: https://tracker.ceph.com/issues/54488

quincy: RGW - Get quota on OPs with a bucket

---

src/rgw/rgw_op.cc

backport tracker: https://tracker.ceph.com/issues/58904
---
backport of https://github.com/ceph/ceph/pull/49962
parent tracker: https://tracker.ceph.com/issues/58627

quincy: rgw: Fix Browser POST content-length-range min value

---

src/rgw/rgw_trim_bilog.cc

backport tracker: https://tracker.ceph.com/issues/59025
---
backport of https://github.com/ceph/ceph/pull/50346
parent tracker: https://tracker.ceph.com/issues/57938

quincy: rgw: use unique_ptr for flat_map emplace in BucketTrimWatche

---

src/rgw/rgw_notify.cc
src/test/rgw/bucket_notification/test_bn.py

backport tracker: https://tracker.ceph.com/issues/59694
---
backport of https://github.com/ceph/ceph/pull/51308
parent tracker: https://tracker.ceph.com/issues/59592

quincy: rgw/notification: remove non x-amz-meta-* attributes from bucket notifications

---

src/rgw/rgw_rest_s3.cc

backport tracker: https://tracker.ceph.com/issues/62824
---
backport of https://github.com/ceph/ceph/pull/53391
parent tracker: https://tracker.ceph.com/issues/62737

quincy: RadosGW API: incorrect bucket quota in response to HEAD /{bucket}/?usage

---

src/rgw/rgw_log.cc
src/rgw/rgw_log.h
src/rgw/rgw_s3select.cc

backport tracker: https://tracker.ceph.com/issues/55678
---
backport of https://github.com/ceph/ceph/pull/46265
parent tracker: https://tracker.ceph.com/issues/55657

quincy: rgw: remove potentially conficting definition of dout_subsys

---

src/rgw/rgw_rados.cc
src/rgw/services/svc_rados.cc
src/rgw/services/svc_rados.h

backport tracker: https://tracker.ceph.com/issues/57636
---
backport of https://github.com/ceph/ceph/pull/48021
parent tracker: https://tracker.ceph.com/issues/49666

quincy: rgw: Drain async_processor request queue during shutdown

---

src/rgw/services/svc_notify.cc

backport tracker: https://tracker.ceph.com/issues/59362
---
backport of https://github.com/ceph/ceph/pull/50707
parent tracker: https://tracker.ceph.com/issues/59217

quincy: rgw: fix rgw cache invalidation after unregister_watch() error

---

qa/cephfs/overrides/ignorelist_health.yaml

backport tracker: https://tracker.ceph.com/issues/65062
---
backport of https://github.com/ceph/ceph/pull/56298
parent tracker: https://tracker.ceph.com/issues/64986

quincy: qa/cephfs: ignorelist clog of MDS_UP_LESS_THAN_MAX

---

qa/tasks/cephfs/test_misc.py

backport tracker: https://tracker.ceph.com/issues/64221
---
backport of https://github.com/ceph/ceph/pull/54683
parent tracker: https://tracker.ceph.com/issues/63587 …

quincy: qa/tasks/cephfs/test_misc: switch duration to timeout

---

qa/tasks/ceph_test_case.py

Backport tracker: https://tracker.ceph.com/issues/64067
Parent tracker: https://tracker.ceph.com/issues/63217
Backport of https://github.com/ceph/ceph/pull/54041 …

quincy: qa: fix error reporting string in assert_cluster_log

---

qa/tasks/cephfs/kernel_mount.py

backport tracker: https://tracker.ceph.com/issues/64249
---
backport of https://github.com/ceph/ceph/pull/54515
parent tracker: https://tracker.ceph.com/issues/63488

quincy: qa: correct usage of DEBUGFS_META_DIR in dedent

---

qa/valgrind.supp

backport tracker: https://tracker.ceph.com/issues/62142
---
backport of https://github.com/ceph/ceph/pull/52521
parent tracker: https://tracker.ceph.com/issues/62059

reef: valgrind: update suppression for SyscallParam under call_init

---

src/rgw/rgw_op.cc
src/rgw/rgw_op.h

backport tracker: https://tracker.ceph.com/issues/65822
---
backport of https://github.com/ceph/ceph/pull/57257
parent tracker: https://tracker.ceph.com/issues/65746

reef: rgw: fix CompleteMultipart error handling regression

---

qa/suites/upgrade/quincy-x/parallel/upgrade-sequence.yaml
qa/suites/upgrade/quincy-x/stress-split/1-start.yaml
qa/suites/upgrade/reef-x/parallel/upgrade-sequence.yaml
qa/suites/upgrade/reef-x/stress-split/1-start.yaml
qa/suites/upgrade/telemetry-upgrade/quincy-x/1-tasks.yaml
qa/suites/upgrade/telemetry-upgrade/reef-x/1-tasks.yaml

Without checking both for the upgrade being in progress and that
the status isn't reporting an error, we can end up in a scenario
where the test is just waiting for an upgrade that has already
been marked failed and will never complete. This same sort of
change was already done in the orch suite upgrade tests and
has helped with jobs timing out there
Fixes: https://tracker.ceph.com/issues/65546
This also updates the reef-x stress-split test to make use of staggered
upgrade parameters since we can be sure any given reef image has
access to them …

qa/upgrade: fix checks to make sure upgrade is still in progress

---

qa/distros/all/centos_9.stream.yaml
qa/distros/podman/centos_9.stream.yaml

With teuthology.git commit 2edcefaa5da1 ("teuthology/task/selinux: ignore denials in agetty"), it's ignored globally.  This effectively reverts commit 7a6389272aff ("qa: ignore container checkpoint/restore related selinux denials for centos9"). …

qa: agetty entry in selinux allowlist is redundant now

---

src/mon/PGMap.cc
src/test/mon/PGMap.cc

The scaling of max_avail by the ratio of non-degraded to total objects count results in the reported max_avail increasing proportionally to the number of OSDs marked `down` but not `out`.  This is counter intuitive since OSDs going `down` should never result in more space being available.
Removing the scale factor allows max_avail to remain unchanged until the OSDs are marked `out`.
Example:
- Cluster with 4 OSD nodes, 10 OSDs each
- 3x replicated pool
- `max_avail` from `ceph df detail --format=json` output with all OSDs `up+in`: 72158076207104
- `max_avail` with 1 OSD node (10 OSDs) `down+in`: 96042674552832
Fixes: https://tracker.ceph.com/issues/65591
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.r …

PGMap: remove pool max_avail scale factor

---

qa/tasks/mgr/test_progress.py

backport tracker: https://tracker.ceph.com/issues/66689
---
backport of https://github.com/ceph/ceph/pull/57401
parent tracker: https://tracker.ceph.com/issues/65826

squid: qa/tasks/mgr/test_progress.py: deal with pre-exisiting pool

---

qa/config/crimson_qa_overrides.yaml
src/crimson/mgr/client.cc

backport of https://github.com/ceph/ceph/pull/58592

squid: mgr/client: validate connection before sending

---

doc/cephfs/cache-configuration.rst

Add information to doc/cephfs/cache-configuration.rst about how to deal with a message that reads "clients failing to respond to cache pressure". This procedure explains how to slow the growth of the recall_caps value so that it does not exceed the
mds_recall_warning_threshold.
The information in this commit was developed by Eugen Block. See https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/5ROH5CWKKOEIQMVXOVRT5OO7CWK2HPM3/#J65DFUPP4BY57MICPANXKI7KAXSZ5Z5P 
and https://www.spinics.net/lists/ceph-users/msg73188.html.
Fixes: https://tracker.ceph.com/issues/57115 …

doc/cephfs: add cache pressure information

---

qa/tasks/ceph.py
qa/tasks/cephadm.py
qa/workunits/rbd/krbd_data_pool.sh

backport tracker: https://tracker.ceph.com/issues/66911
---
backport of https://github.com/ceph/ceph/pull/58507
parent tracker: https://tracker.ceph.com/issues/66886

reef: qa: account for rbd_trash object in krbd_data_pool.sh + related ceph{,adm} task fixes

---

doc/cephfs/cache-configuration.rst

Add information to doc/cephfs/cache-configuration.rst about how to deal with a message that reads "clients failing to respond to cache pressure". This procedure explains how to slow the growth of the recall_caps value so that it does not exceed the
mds_recall_warning_threshold.
The information in this commit was developed by Eugen Block. See https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/5ROH5CWKKOEIQMVXOVRT5OO7CWK2HPM3/#J65DFUPP4BY57MICPANXKI7KAXSZ5Z5P and https://www.spinics.net/lists/ceph-users/msg73188.html.
Fixes: https://tracker.ceph.com/issues/57115
(cherry picked from commit bf26274ae4737417193f8c2b56bea20eb2a358aa) …

squid: doc/cephfs: add cache pressure information

---

doc/cephfs/cache-configuration.rst

Add information to doc/cephfs/cache-configuration.rst about how to deal with a message that reads "clients failing to respond to cache pressure". This procedure explains how to slow the growth of the recall_caps value so that it does not exceed the
mds_recall_warning_threshold.
The information in this commit was developed by Eugen Block. See https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/5ROH5CWKKOEIQMVXOVRT5OO7CWK2HPM3/#J65DFUPP4BY57MICPANXKI7KAXSZ5Z5P and https://www.spinics.net/lists/ceph-users/msg73188.html.
Fixes: https://tracker.ceph.com/issues/57115
(cherry picked from commit bf26274ae4737417193f8c2b56bea20eb2a358aa) …

reef: doc/cephfs: add cache pressure information

---

doc/cephfs/cache-configuration.rst

Add information to doc/cephfs/cache-configuration.rst about how to deal with a message that reads "clients failing to respond to cache pressure". This procedure explains how to slow the growth of the recall_caps value so that it does not exceed the
mds_recall_warning_threshold.
The information in this commit was developed by Eugen Block. See https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/5ROH5CWKKOEIQMVXOVRT5OO7CWK2HPM3/#J65DFUPP4BY57MICPANXKI7KAXSZ5Z5P and https://www.spinics.net/lists/ceph-users/msg73188.html.
Fixes: https://tracker.ceph.com/issues/57115
(cherry picked from commit bf26274ae4737417193f8c2b56bea20eb2a358aa) …

quincy: doc/cephfs: add cache pressure information

---

src/crimson/os/alienstore/alien_store.cc
src/crimson/osd/osd.cc

A recent BlueStore change added an assert validating that there are no open CollectionRef's at umount time.
<details>
</details>

crimson: clear AlienStore::coll_map in umount rather than in stop

---

src/crimson/os/seastore/onode.cc
src/crimson/os/seastore/onode.h
src/crimson/os/seastore/onode_manager/staged-fltree/fltree_onode_manager.cc
src/crimson/os/seastore/onode_manager/staged-fltree/fltree_onode_manager.h
src/crimson/os/seastore/onode_manager/staged-fltree/tree.h
src/crimson/os/seastore/onode_manager/staged-fltree/value.h
src/test/crimson/seastore/onode_tree/test_value.h
src/test/crimson/seastore/test_object_data_handler.cc

backport of https://github.com/ceph/ceph/pull/58356

squid: crimson/os/seastore/onode: add hobject_t into Onode

---

src/os/CMakeLists.txt
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/os/bluestore/BlueStore_debug.cc

Introduce printer class that allows to select parts of Blob that are to be printed.
It severly reduced amount of clutter in output.
Usage:
using P = Bluestore::Blob::printer;
dout << blob->printer(P::nick + P::sdisk + P::schk);
Now the Blob printout can look like this:
`Blob(rtrvlad disk=0x[12503~e,19589~1,12512~1]000 track=16*4K{4K}[] )`
instead of
`Blob(0x55555e735790 blob([0x12503000~e000,0x19589000~1000,0x12512000~1000] llen=0x10000 csum crc32c/0x1000/64) use_tracker(0x10*0x1000 0x[1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000]) SharedBlob(0x55555e9e8680 sbid 0x0))`
https://github.com/ceph/ceph/pull/54075 Nice debugs.
https://github.com/ceph/ceph/pull/54504 New write path.
https://github.com/ceph/ceph/pull/57448 Segmented onode. …

os/bluestore: Recompression, part 1. Nice debugs.

---

qa/tasks/workunit.py

The comment was unclear without looking at previous version of code.
Therefore improve comment a bit and add link to commit ID due to which
this comment was introduced to give future readers context. …

qa: improve and add commit ID to comment for context

---

src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/driver/rados/rgw_sal_rados.cc

IoCtx::operate() will always block. use rgw_rados_operate() so that we can suspend the coroutine when optional_yield is not empty
and a similar change for RGWRados::Object::Read::read()
<details>
</details>

rgw/rados: delete_objs_inline() uses rgw_rados_operate()

---

debian/control

Since commit 0985e201342 ("ceph-volume: use 'no workqueue' options with dmcrypt") the python "packaging" module is used to parse the cryptsetup version output, but the debian packaging was not updated to record that new dependency.
Simply record this in the d/control file, adding a <pkg>.requires file could be also an option, but not really sure if that wins us anything here. But if that's preferred I can change to that quite quickly, so just holler at me if I should do so.
Fixes: https://tracker.ceph.com/issues/67290 and do well with getting backported once applied, as the patch causing this got backported to (at least) squid and reef too.

debian pkg: record python3-packaging dependency for ceph-volume

---

doc/ceph-volume/lvm/prepare.rst
doc/cephadm/services/osd.rst
src/ceph-volume/ceph_volume/__init__.py
src/ceph-volume/ceph_volume/devices/lvm/batch.py
src/ceph-volume/ceph_volume/devices/lvm/common.py
src/ceph-volume/ceph_volume/devices/raw/activate.py
src/ceph-volume/ceph_volume/devices/raw/common.py
src/ceph-volume/ceph_volume/devices/raw/list.py
src/ceph-volume/ceph_volume/devices/raw/prepare.py
src/ceph-volume/ceph_volume/objectstore/__init__.py
src/ceph-volume/ceph_volume/objectstore/baseobjectstore.py
src/ceph-volume/ceph_volume/objectstore/bluestore.py
src/ceph-volume/ceph_volume/objectstore/lvmbluestore.py
src/ceph-volume/ceph_volume/objectstore/rawbluestore.py
src/ceph-volume/ceph_volume/tests/conftest.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_prepare.py
src/ceph-volume/ceph_volume/tests/devices/raw/test_prepare.py
src/ceph-volume/ceph_volume/tests/objectstore/test_lvmbluestore.py
src/ceph-volume/ceph_volume/tests/objectstore/test_rawbluestore.py
src/ceph-volume/ceph_volume/tests/test_ceph_volume.py
src/ceph-volume/ceph_volume/tests/util/test_disk.py
src/ceph-volume/ceph_volume/tests/util/test_encryption.py
src/ceph-volume/ceph_volume/tests/util/test_prepare.py
src/ceph-volume/ceph_volume/util/arg_validators.py
src/ceph-volume/ceph_volume/util/device.py
src/ceph-volume/ceph_volume/util/disk.py
src/ceph-volume/ceph_volume/util/encryption.py
src/python-common/ceph/deployment/drive_group.py
src/python-common/ceph/deployment/translate.py

This adds the required changes to ceph-volume and cephadm in order to support deploying tpm2 token enrolled encrypted OSDs.
Adding `--with-tpm` when deploying with `--dmcrypt` will enroll a tpm2 token to the corresponding LUKS2 devices.
Example of a osd service spec:
```
service_type: osd
service_id: tpm2_osds
placement:
host_pattern: '*'
spec:
data_devices:
paths:
- /dev/sdb
encrypted: true
tpm2: true
```

ceph-volume: add TPM2 token enrollment support for encrypted OSDs

---

src/tools/rados/rados.cc

Recent code refactor caused extra "std::endl" output.
Detected by teuthology:
https://pulpito.ceph.com/akupczyk-2024-08-02_13:56:25-rados-aclamk-testing-phoebe-2024-08-01-1249-distro-default-smithi/7832308/ …

tools/rados: Fix extra NL in getxattr

---

doc/cephfs/cache-configuration.rst

Improve the text in the section about dealing with cache-pressure alerts that was added in https://github.com/ceph/ceph/pull/59077. The changes in this commit were suggested by Anthony D'Atri. …

doc/cephfs: improve cache-configuration.rst

---

src/crimson/common/tri_mutex.cc
src/crimson/common/tri_mutex.h
src/crimson/osd/object_context.h
src/crimson/osd/object_context_loader.cc
src/crimson/osd/object_context_loader.h
src/crimson/osd/pg_recovery.cc
src/crimson/osd/replicated_recovery_backend.cc

backport of https://github.com/ceph/ceph/pull/57977

squid: crimson: simplify obc loading by locking excl for load and demoting to needed lock

---

qa/standalone/ceph-helpers.sh

When pg repair is called manully, a deep-scrub will be executed firstly, and requeue DoRecovery() if there are inconsistent objects. But in repair() of ceph-helpers.sh, it use scrub_stamp to determine repair completing time. This will leads to the repair is not completed before another test case.
https://tracker.ceph.com/issues/66360
Signed-off-by: Mingyuan Liang <liangmingyuan@baidu.com>

qa/standalone: bugfix for latecy repair after scrub

---

qa/tasks/s3tests.py
src/rgw/rgw_op.cc

while bucket ARNs in iam policies don't include account names, policy evaluation does need to differentiate between buckets in different tenant namespaces
when requests pass bucket/object ARNs into verify_bucket/object_permission(), those do include the bucket's tenant name. to match against those ARNs, we also need to pass the requested bucket's tenant name into get_iam_policy_from_attr()
Fixes: https://tracker.ceph.com/issues/67464
<details>
- `jenkins …

rgw: revert account-related changes to get_iam_policy_from_attr()

---

doc/cephfs/cache-configuration.rst

Improve the text in the section about dealing with cache-pressure alerts that was added in https://github.com/ceph/ceph/pull/59077. The changes in this commit were suggested by Anthony D'Atri.
Co-authored-by: Patrick Donnelly <pdonnelly@redhat.com>
(cherry picked from commit aa3bdae2314fef2fca8fc12dca006af657235e17)
- When …

quincy: doc/cephfs: improve cache-configuration.rst

---

doc/cephfs/cache-configuration.rst

Improve the text in the section about dealing with cache-pressure alerts that was added in https://github.com/ceph/ceph/pull/59077. The changes in this commit were suggested by Anthony D'Atri.
Co-authored-by: Patrick Donnelly <pdonnelly@redhat.com>
(cherry picked from commit aa3bdae2314fef2fca8fc12dca006af657235e17)
- When …

reef: doc/cephfs: improve cache-configuration.rst

---

qa/standalone/osd/osd-recovery-space.sh

backport tracker: https://tracker.ceph.com/issues/67350
---
backport of https://github.com/ceph/ceph/pull/57193
parent tracker: https://tracker.ceph.com/issues/44510

quincy: Test: osd-recovery-space.sh extends the wait time for "recovery toofull"

---

doc/ceph-volume/lvm/prepare.rst
doc/cephadm/services/osd.rst
src/ceph-volume/ceph_volume/__init__.py
src/ceph-volume/ceph_volume/devices/lvm/batch.py
src/ceph-volume/ceph_volume/devices/lvm/common.py
src/ceph-volume/ceph_volume/devices/raw/activate.py
src/ceph-volume/ceph_volume/devices/raw/common.py
src/ceph-volume/ceph_volume/devices/raw/list.py
src/ceph-volume/ceph_volume/devices/raw/prepare.py
src/ceph-volume/ceph_volume/objectstore/__init__.py
src/ceph-volume/ceph_volume/objectstore/baseobjectstore.py
src/ceph-volume/ceph_volume/objectstore/bluestore.py
src/ceph-volume/ceph_volume/objectstore/lvmbluestore.py
src/ceph-volume/ceph_volume/objectstore/rawbluestore.py
src/ceph-volume/ceph_volume/tests/conftest.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_prepare.py
src/ceph-volume/ceph_volume/tests/devices/raw/test_prepare.py
src/ceph-volume/ceph_volume/tests/objectstore/test_lvmbluestore.py
src/ceph-volume/ceph_volume/tests/objectstore/test_rawbluestore.py
src/ceph-volume/ceph_volume/tests/test_ceph_volume.py
src/ceph-volume/ceph_volume/tests/util/test_disk.py
src/ceph-volume/ceph_volume/tests/util/test_encryption.py
src/ceph-volume/ceph_volume/tests/util/test_prepare.py
src/ceph-volume/ceph_volume/util/arg_validators.py
src/ceph-volume/ceph_volume/util/device.py
src/ceph-volume/ceph_volume/util/disk.py
src/ceph-volume/ceph_volume/util/encryption.py
src/python-common/ceph/deployment/drive_group.py
src/python-common/ceph/deployment/translate.py

ceph-volume: add TPM2 token enrollment support for encrypted OSDs
This adds the required changes to ceph-volume and cephadm in order to support
deploying tpm2 token enrolled encrypted OSDs.
Adding `--with-tpm` when deploying with `--dmcrypt` will enroll a tpm2
token to the corresponding LUKS2 devices.
Example of a osd service spec:
```
service_type: osd
service_id: tpm2_osds
placement:
host_pattern: '*'
spec:
data_devices:
paths:
- /dev/sdb
encrypted: true
tpm2: true
```

squid: ceph-volume: add TPM2 token enrollment support for encrypted OSDs

---

src/cls/rgw/cls_rgw_client.cc
src/cls/rgw/cls_rgw_client.h
src/rgw/driver/rados/rgw_bucket.cc
src/rgw/driver/rados/rgw_cr_tools.cc
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/driver/rados/rgw_sal_rados.h
src/rgw/rgw_lc.cc
src/rgw/rgw_lc.h
src/rgw/rgw_op.cc
src/rgw/rgw_sal.h
src/rgw/rgw_sal_dbstore.cc
src/rgw/rgw_sal_dbstore.h
src/rgw/rgw_sal_filter.cc
src/rgw/rgw_sal_filter.h

the IoCtx functions are synchronous and not meant to be used in rgw. replace them with ObjectOperation arguments for use with rgw_rados_operate() and optional_yield
these IoCtx functions _should_ have been hidden by the `CLS_CLIENT_HIDE_IOCTX` define, but that was never added to the `rgw_common` target which uses them
when enabling `rgw_asio_assert_yielding` from https://github.com/ceph/ceph/pull/58179 and running s3-tests, `test_lifecycle_set` triggers an assertion because `RGWLC::set_bucket_config()` didn't support `optional_yield`
<details> …

cls/rgw: define lc ops in terms of ObjectOperation instead of IoCtx

---

src/common/numa.cc

backport tracker: https://tracker.ceph.com/issues/67064
---
backport of https://github.com/ceph/ceph/pull/44794
parent tracker: https://tracker.ceph.com/issues/67063

quincy: common: fix compilation warnings in numa.cc

---

src/rgw/driver/rados/rgw_notify.cc

return a copy of the owner string to work around compiler warning:
```
ceph/src/rgw/driver/rados/rgw_notify.cc: In function ‘int rgw::notify::publish_reserve(const DoutPrefixProvider*, const rgw::SiteConfig&, const EventTypeList&, reservation_t&, const RGWObjTags*)’: ceph/src/rgw/driver/rados/rgw_notify.cc:1113:26: warning: possibly dangling reference to a temporary [-Wdangling-reference]
1113 |       const std::string& topic_tenant = std::visit(fu2::overload(
|                          ^~~~~~~~~~~~
ceph/src/rgw/driver/rados/rgw_notify.cc:1113:51: note: the temporary was destroyed at the end of the full expression ‘std::visit<fu2::abi_310::detail::overloading::overload_impl<rgw::notify::publish_reserve(const DoutPrefixProvider*, const rgw::SiteConfig&, const EventTypeList&, …
```

rgw/notify: visit() returns copy of owner string

---

doc/radosgw/notifications.rst

Fixes: https://tracker.ceph.com/issues/50610
<details>
</details>

doc/rgw/notification: persistent notification queue full behavior

---

qa/suites/rgw/verify/tasks/cls.yaml
src/cls/2pc_queue/cls_2pc_queue.cc
src/test/cls_2pc_queue/test_cls_2pc_queue.cc

* make sure that the queue full condition is covered
* add cls debugging to test
Fixes: https://tracker.ceph.com/issues/67229
<details>
</details>

test/cls_2pc_queue: prevent list+remove race between consumers

---

src/crimson/osd/backfill_state.cc
src/crimson/osd/backfill_state.h
src/crimson/osd/pg_recovery.h
src/crimson/osd/recovery_backend.cc
src/test/crimson/test_backfill.cc

1. BACKFILL_FINISH messages may be dropped by replicas, if osdmap updates get processed by replicas before BACKFILL_FINISH messages; in this case, the peering for the osdmap updates will find replicas' backfills not finished, and try to do another round of backfilling, but, since there's nothing to be backfilled, there's no way to update peer backfill infos, which means the pg may never go clean.
2. The last round of scan may produce no objects that need to be backfilled; in this case, the current implementation doesn't set backfill infos for the primary and replicas and leaves the pg as unclean forever.
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst) …

crimson/osd/backfill_state: fixes two corner cases in backfilling

---

src/crimson/osd/osd_operation_external_tracking.h
src/crimson/osd/osd_operations/client_request.cc
src/crimson/osd/osd_operations/client_request.h
src/crimson/osd/osd_operations/common/pg_pipeline.h

Otherwise, UrgentRecovery requests within the same pg can only be processed sequentially …

crimson/osd/osd_operations: make the "recover_missing" phase concurrent

---

src/crimson/os/seastore/cache.h
src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.cc
src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.h
src/crimson/os/seastore/transaction_manager.h

backport of https://github.com/ceph/ceph/pull/57818

squid: crimson/os/seastore/lba_manager: do batch mapping allocs when remapping multiple mappings

---

src/tools/ceph_objectstore_tool.cc

backport tracker: https://tracker.ceph.com/issues/63650
---
backport of https://github.com/ceph/ceph/pull/54663
parent tracker: https://tracker.ceph.com/issues/63640

quincy: tools/ceph_objectstore_tool: action_on_all_objects_in_pg to skip pgmeta

---

src/pybind/mgr/nfs/export.py
src/pybind/mgr/nfs/utils.py

backport trackers: 
https://tracker.ceph.com/issues/66700
https://tracker.ceph.com/issues/67195
---
backport of https://github.com/ceph/ceph/pull/56876 and https://github.com/ceph/ceph/pull/58535
parent trackers: 
https://tracker.ceph.com/issues/56246
https://tracker.ceph.com/issues/66800

quincy: mgr/nfs: Don't crash ceph-mgr if NFS clusters are unavailable.

---

qa/suites/upgrade/quincy-x/parallel/1-tasks.yaml
qa/suites/upgrade/quincy-x/stress-split/1-start.yaml
qa/suites/upgrade/reef-x/parallel/1-tasks.yaml
qa/suites/upgrade/reef-x/stress-split/1-start.yaml

These warnings are expected since we restart daemons during upgrades, which means that mons are temporarily down, and pgs temporarily lose availability.
Fixes: https://tracker.ceph.com/issues/66809 and https://tracker.ceph.com/issues/64460 …

qa/suites/upgrade: ignore PG_AVAILABILITY and MON_DOWN for quincy-x and reef-x upgrade suites

---

doc/cephfs/file-layouts.rst

Improve "layout fields" text in doc/cephfs/file-layouts.rst, as suggesed by Anthony D'Atri in these comments:
https://github.com/ceph/ceph/pull/59021#discussion_r1704108581 https://github.com/ceph/ceph/pull/59021#discussion_r1704112320 …

doc/cephfs: improve "layout fields" text

---

src/script/ceph-backport.sh

script/ceph-backport: robustness adjustments for local git repo quirks

---

doc/cephfs/file-layouts.rst

Improve "layout fields" text in doc/cephfs/file-layouts.rst, as suggesed by Anthony D'Atri in these comments:
https://github.com/ceph/ceph/pull/59021#discussion_r1704108581 https://github.com/ceph/ceph/pull/59021#discussion_r1704112320
(cherry picked from commit 0949b410433837f0509fb73169fa7f22c8f6c256) …

quincy: doc/cephfs: improve "layout fields" text

---

doc/cephfs/file-layouts.rst

Improve "layout fields" text in doc/cephfs/file-layouts.rst, as suggesed by Anthony D'Atri in these comments:
https://github.com/ceph/ceph/pull/59021#discussion_r1704108581 https://github.com/ceph/ceph/pull/59021#discussion_r1704112320
(cherry picked from commit 0949b410433837f0509fb73169fa7f22c8f6c256) …

squid: doc/cephfs: improve "layout fields" text

---

doc/cephfs/client-auth.rst
doc/cephfs/mount-using-fuse.rst

Change the string "mountpoint" to "mount point" in English-language strings (as opposed to in commands, where the string "mountpoint" sometimes appears and is correct).
cf. https://github.com/ceph/ceph/pull/58908#discussion_r1697715486 in which page 345 of The IBM Style Guide is referenced to back up this change.
This commit alters only English-language text and example commands in which the string "{mount point}" is meant to be replaced. No commands meant for cutting-and-pasting have been altered in this commit. …

doc/cephfs: s/mountpoint/mount point/

---

doc/cephfs/client-auth.rst
doc/cephfs/mount-using-fuse.rst

Change the string "mountpoint" to "mount point" in English-language strings (as opposed to in commands, where the string "mountpoint" sometimes appears and is correct).
cf. https://github.com/ceph/ceph/pull/58908#discussion_r1697715486 in which page 345 of The IBM Style Guide is referenced to back up this change.
This commit alters only English-language text and example commands in which the string "{mount point}" is meant to be replaced. No commands meant for cutting-and-pasting have been altered in this commit.
(cherry picked from commit a0f81cfb5094164630f55a717efbbcdce45bce58)
- If you are …

quincy: doc/cephfs: s/mountpoint/mount point/

---

doc/cephfs/client-auth.rst
doc/cephfs/mount-using-fuse.rst

Change the string "mountpoint" to "mount point" in English-language strings (as opposed to in commands, where the string "mountpoint" sometimes appears and is correct).
cf. https://github.com/ceph/ceph/pull/58908#discussion_r1697715486 in which page 345 of The IBM Style Guide is referenced to back up this change.
This commit alters only English-language text and example commands in which the string "{mount point}" is meant to be replaced. No commands meant for cutting-and-pasting have been altered in this commit.
(cherry picked from commit a0f81cfb5094164630f55a717efbbcdce45bce58)
- If you are …

reef: doc/cephfs: s/mountpoint/mount point/

---

doc/cephfs/client-auth.rst
doc/cephfs/mount-using-fuse.rst

Change the string "mountpoint" to "mount point" in English-language strings (as opposed to in commands, where the string "mountpoint" sometimes appears and is correct).
cf. https://github.com/ceph/ceph/pull/58908#discussion_r1697715486 in which page 345 of The IBM Style Guide is referenced to back up this change.
This commit alters only English-language text and example commands in which the string "{mount point}" is meant to be replaced. No commands meant for cutting-and-pasting have been altered in this commit.
(cherry picked from commit a0f81cfb5094164630f55a717efbbcdce45bce58)
- If you are …

squid: doc/cephfs: s/mountpoint/mount point/

---

qa/workunits/rbd/luks-encryption.sh
src/librbd/api/Migration.cc
src/librbd/io/ReadResult.cc
src/librbd/io/ReadResult.h
src/librbd/migration/FileStream.cc
src/librbd/migration/FormatInterface.h
src/librbd/migration/HttpClient.cc
src/librbd/migration/ImageDispatch.cc
src/librbd/migration/ImageDispatch.h
src/librbd/migration/NativeFormat.cc
src/librbd/migration/NativeFormat.h
src/librbd/migration/OpenSourceImageRequest.cc
src/librbd/migration/OpenSourceImageRequest.h
src/librbd/migration/QCOWFormat.cc
src/librbd/migration/QCOWFormat.h
src/librbd/migration/RawFormat.cc
src/librbd/migration/RawFormat.h
src/librbd/migration/RawSnapshot.cc
src/librbd/migration/SourceSpecBuilder.cc
src/librbd/migration/SourceSpecBuilder.h
src/test/librbd/migration/test_mock_QCOWFormat.cc
src/test/librbd/migration/test_mock_RawFormat.cc

backport tracker: https://tracker.ceph.com/issues/67442
---
backport of https://github.com/ceph/ceph/pull/58882 and https://github.com/ceph/ceph/pull/44366
parent tracker: https://tracker.ceph.com/issues/53674

quincy: librbd/crypto: fix issue when live-migrating from encrypted export

---

src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/cache.h
src/crimson/os/seastore/cached_extent.h
src/crimson/os/seastore/extent_placement_manager.cc
src/crimson/os/seastore/extent_placement_manager.h
src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/seastore.h
src/crimson/os/seastore/seastore_types.cc
src/crimson/os/seastore/seastore_types.h
src/crimson/os/seastore/transaction.h
src/crimson/os/seastore/transaction_manager.cc
src/crimson/os/seastore/transaction_manager.h
src/test/crimson/seastore/test_transaction_manager.cc

The main change refer to the last commit, the rest are related refactors/cleanups.
The report looks like:
```
INFO  2024-08-14 15:46:35,714 [shard 0:main] seastore_cache - Cache::LRU::get_stats:
lru total(64.00MiB,4.52KiB,14501)
data(55.79MiB,4.00KiB,14283)
mdat(7.88MiB,60.63KiB,133)
phys(0.33MiB,4.00KiB,85)
lru io: trans-in(0.40MiB/s,5.71KiB,72.50ps) out(0.28MiB/s,5.06KiB,56.50ps); other-in(0.00MiB/s,-nanKiB,0.00ps) out(0.12MiB/s,7.76KiB,16.50ps)
MUTATE: in(0.37MiB/s,5.95KiB,63.50ps) out(0.23MiB/s,4.59KiB,51.00ps)
data: in(0.22MiB/s,4.00KiB,57.50ps) out(0.20MiB/s,4.00KiB,50.50ps)
mdat: in(0.13MiB/s,45.33KiB,3.00ps) out(0.03MiB/s,64.00KiB,0.50ps)
phys: in(0.01MiB/s,4.00KiB,3.00ps) out(0.00MiB/s,-nanKiB,0.00ps)
TRIM_DIRTY: in(0.02MiB/s,4.00KiB,4.50ps) out(0.02MiB/s,4.00KiB,4.00ps)
data: …
```

crimson/os/seastore/cache: report lru usage/in/out with trans and extent type

---

qa/cephfs/overrides/ignorelist_health.yaml

backport tracker: https://tracker.ceph.com/issues/67120
---
backport of https://github.com/ceph/ceph/pull/58214
parent tracker: https://tracker.ceph.com/issues/66612

squid: qa/cephfs: ignore variant of MDS_UP_LESS_THAN_MAX

---

src/mds/MDCache.cc
src/mds/Server.cc

backport tracker: https://tracker.ceph.com/issues/66363
---
backport of  https://github.com/ceph/ceph/pull/57553
parent tracker: https://tracker.ceph.com/issues/66124
<details>
</details>

squid: mds: find a new head for the batch ops when the head is dead

---

src/crimson/os/seastore/btree/btree_range_pin.cc
src/crimson/os/seastore/btree/btree_range_pin.h
src/crimson/os/seastore/btree/fixed_kv_btree.h
src/crimson/os/seastore/btree/fixed_kv_node.h
src/crimson/os/seastore/cached_extent.h
src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.h
src/crimson/os/seastore/lba_manager/btree/lba_btree_node.cc
src/crimson/os/seastore/lba_manager/btree/lba_btree_node.h
src/crimson/os/seastore/root_block.h
src/crimson/os/seastore/transaction.h
src/crimson/os/seastore/transaction_manager.cc
src/crimson/os/seastore/transaction_manager.h
src/test/crimson/seastore/test_block.h
src/test/crimson/seastore/test_transaction_manager.cc

backport of https://github.com/ceph/ceph/pull/58367

squid: crimson/os/seastore/cached_extent: add the "refresh" ability to lba mappings

---

qa/suites/fs/nfs/overrides/ignore_mgr_down.yaml

Backport of https://github.com/ceph/ceph/pull/56944
Backport tracker: https://tracker.ceph.com/issues/66062
Parent tracker: https://tracker.ceph.com/issues/65265
RCA showed that it is not the NFS code that lead to the warning since the warning occurred before the test cases started to execute, later on after some discussion with the venky and greg, it was found that there were some clog changes made recently which leads to this warning being added to the clog.
Digging more further, it was found that the warning is generated when mgr fail is run when there is no mgr available. The reason for unavailability is when `setup_mgrs()` in class `MgrTestCase` stops the mgr daemons, sometimes the mgr just crashes - `mgr handle_mgr_signal  *** Got signal Terminated ***`  and after which `mgr fail` …

quincy: qa: add a YAML to ignore MGR_DOWN warning

---

qa/tasks/cephfs/test_failover.py

backport tracker: https://tracker.ceph.com/issues/66045
---
backport of https://github.com/ceph/ceph/pull/57329
parent tracker: https://tracker.ceph.com/issues/65837

quincy: qa: unmount clients before damaging the fs

---

qa/tasks/ceph_manager.py
qa/tasks/cephfs/filesystem.py
qa/tasks/vstart_runner.py

backport tracker: https://tracker.ceph.com/issues/64224
---
backport of https://github.com/ceph/ceph/pull/54446
parent tracker: https://tracker.ceph.com/issues/63411

quincy: qa: bump up scrub status command timeout

---

qa/tasks/cephfs/filesystem.py

backport tracker: https://tracker.ceph.com/issues/64143
---
backport of https://github.com/ceph/ceph/pull/54208
parent tracker: https://tracker.ceph.com/issues/63176

quincy: qa: fix rank_asok() to handle errors from asok commands

---

doc/rados/configuration/bluestore-config-ref.rst

backport tracker: https://tracker.ceph.com/issues/63662
---
backport of https://github.com/ceph/ceph/pull/54339
parent tracker: https://tracker.ceph.com/issues/63436

quincy: doc/rados/configuration/bluestore-config-ref: Fix lowcase typo

---

qa/tasks/barbican.py

We install barbican by doing a pip install directly on the cloned git repository but we don't honor the upper-constraints from the OpenStack Requirements project that handles what versions is supported.
This changes the pip install command that we issue when installing barbican to honor the requirements for the version (derived from the branch) that we use, in
this case it's the 2023.1 release upper-constraints [1].
This prevents us from pulling in untested Python packages.
This only updates Barbican because for the Keystone job we dont directly issue pip but install using tox using the `venv` environment which already by default sets the constraints as you can see in [2].
[1] https://releases.openstack.org/constraints/upper/2023.1
[2] …

qa: barbican: restrict python packages with upper-constraints

---

src/test/CMakeLists.txt

backport tracker: https://tracker.ceph.com/issues/59494
---
backport of https://github.com/ceph/ceph/pull/51068
parent tracker: https://tracker.ceph.com/issues/59269

quincy: cmake/rgw: librgw tests depend on ALLOC_LIBS

---

src/mon/PGMap.cc
src/mon/PGMap.h

backport tracker: https://tracker.ceph.com/issues/62927
---
backport of https://github.com/ceph/ceph/pull/49332
parent tracker: https://tracker.ceph.com/issues/51688

reef: mon: stuck peering since warning is misleading

---

src/mgr/Mgr.cc

backport tracker: https://tracker.ceph.com/issues/66890
---
backport of https://github.com/ceph/ceph/pull/57005
parent tracker: https://tracker.ceph.com/issues/66168

reef: mgr/Mgr.cc: clear daemon health metrics instead of removing down/out osd from daemon state

---

src/crimson/os/seastore/extent_placement_manager.cc
src/crimson/os/seastore/extent_placement_manager.h
src/crimson/os/seastore/journal/circular_bounded_journal.cc
src/crimson/os/seastore/journal/segmented_journal.cc
src/crimson/os/seastore/ordering_handle.h

This reverts commit c9e423facea79d42f0496264f267adee5d911b87.
The commit starts to submit OOL writes before submitting the journal write, true, but it cannot guarantee that OOL writes finish before the journal write.
Thus it is possible that during SeaStore restart, a journal record appears valid but its dependent OOL records are partial written, which leads to corruption. …

Revert "crimson/os/seastore: wait ool writes in DeviceSubmission phase"

---

qa/workunits/rbd/rbd_groups.sh
src/librbd/api/Group.cc
src/test/librbd/test_Groups.cc
src/test/pybind/test_rbd.py
src/tools/rbd/action/Group.cc

Before the fix (copied from https://tracker.ceph.com/issues/67436)
```
[root@server1 build]# rbd group snap info data/grp1@snap1
rbd group snapshot 'snap1':
id: 102c5329c35a
state: complete
image snap: .group.2_102a9283e0ec_102c5329c35a
images:
```
**See below for outputs with the fix**
```
$ rbd group create gp3
$ rbd group snap create gp3@snap3
$ # omitted 'images' and 'image snap' fields from the `rbd group snap info` output
$ rbd group snap info gp3@snap3
rbd group snapshot 'snap3':
id: 1038d0c5cddc
state: complete
$ rbd group snap info gp3@snap3 --format=json --pretty-format
{
"id": "1038d0c5cddc",
"name": "snap3",
"state": "complete",
"image_snap_name": "",
"images": []
}
$ rbd create -s 10M img3
$ rbd group image add gp3 img3
$ rbd group snap create gp3@snap4
$ rbd group snap info …
```

rbd: fix CLI output of `rbd group snap info` command when a group snapshot with no member images

---

src/common/options/crimson.yaml.in
src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/cache.h
src/crimson/os/seastore/device.h
src/crimson/os/seastore/extent_placement_manager.h
src/crimson/os/seastore/journal.h
src/crimson/os/seastore/journal/circular_bounded_journal.h
src/crimson/os/seastore/journal/circular_journal_space.cc
src/crimson/os/seastore/journal/circular_journal_space.h
src/crimson/os/seastore/journal/segmented_journal.h
src/crimson/os/seastore/lba_manager.cc
src/crimson/os/seastore/random_block_manager.h
src/crimson/os/seastore/random_block_manager/block_rb_manager.cc
src/crimson/os/seastore/random_block_manager/block_rb_manager.h
src/crimson/os/seastore/random_block_manager/nvme_block_device.cc
src/crimson/os/seastore/random_block_manager/nvme_block_device.h
src/crimson/os/seastore/random_block_manager/rbm_device.cc
src/crimson/os/seastore/random_block_manager/rbm_device.h
src/crimson/os/seastore/seastore_types.h
src/crimson/os/seastore/transaction_manager.cc
src/crimson/os/seastore/transaction_manager.h
src/test/crimson/seastore/test_randomblock_manager.cc

backport of https://github.com/ceph/ceph/pull/57782

squid: crimson/os/seastore: add checksum offload to RBM

---

qa/suites/orch/cephadm/smoke-roleless/2-services/nvmeof.yaml
src/pybind/mgr/cephadm/inventory.py
src/pybind/mgr/cephadm/migrations.py
src/pybind/mgr/cephadm/services/nvmeof.py
src/pybind/mgr/cephadm/tests/test_migration.py
src/pybind/mgr/orchestrator/module.py
src/python-common/ceph/deployment/service_spec.py

This includes the work from https://github.com/ceph/ceph/pull/54671 for testing purposes, but the commits that matter are the last couple that make the group field required in nvmeof specs and add a migration for existing specs where the group field is not set …

mgr/cephadm: require "group" parameter in nvmeof specs

---

qa/standalone/osd/osd-recovery-space.sh

backport tracker: https://tracker.ceph.com/issues/67349
---
backport of https://github.com/ceph/ceph/pull/57193
parent tracker: https://tracker.ceph.com/issues/44510

squid: Test: osd-recovery-space.sh extends the wait time for "recovery toofull"

---

src/common/dout.h

backport tracker: https://tracker.ceph.com/issues/67364
---
backport of https://github.com/ceph/ceph/pull/55306
parent tracker: https://tracker.ceph.com/issues/64050

squid: common/dout: fix FTBFS on GCC 14

---

PendingReleaseNotes
doc/mgr/restful.rst
src/pybind/mgr/restful/module.py

Presently, the requests array in the REST module has the potential to grow indefinitely, leading to excessive memory consumption, particularly when dealing with lengthy and intricate request results.
To address this issue, a limit will be imposed on the requests array within the REST module.
This limitation will be governed by the `mgr/restful/x/max_requests` configuration parameter specific to the REST module.
I ran a few thousand pg dump commands with and without the trimming of the requests array, there is a big improvement with the trimming when the cluster returns a large output from the pg dump command.
with the trimming:
image
without the trimming:
image
Fixes: https://tracker.ceph.com/issues/59580 …

mgr/rest: Trim  requests array and limit size

---

src/test/rgw/bucket_notification/test_bn.py

backport tracker: https://tracker.ceph.com/issues/67308
---
backport of https://github.com/ceph/ceph/pull/58747
parent tracker: https://tracker.ceph.com/issues/67205

squid: RGW|BN: fix lifecycle test issue

---

src/test/rgw/bucket_notification/test_bn.py

there are other tests for queue length, so we can skip this check if test takes too long.
also remove unnecessary delays from the test.
Fixes: https://tracker.ceph.com/issues/67514?tab=history
<details>
- …

test/rgw/notifications: don't check for full queue if topics expired

---

src/pybind/mgr/cephadm/services/nvmeof.py
src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
src/pybind/mgr/cephadm/tests/test_services.py
src/python-common/ceph/deployment/service_spec.py

mgr/cephadm: change SPDK RPC fields in nvmeof configuration
python-common/ceph/deployment: change SPDK RPC fields in nvmeof configuration
Fixes https://tracker.ceph.com/issues/67629 …

mgr/cephadm: change SPDK RPC fields in nvmeof configuration

---

src/rgw/rgw_rest_oidc_provider.cc

backport tracker: https://tracker.ceph.com/issues/58327
---
backport of https://github.com/ceph/ceph/pull/49426
parent tracker: https://tracker.ceph.com/issues/53171

quincy: rgw: fix ListOpenIDConnectProviders XML format

---

src/rgw/rgw_log.cc

backport tracker: https://tracker.ceph.com/issues/59144
---
backport of https://github.com/ceph/ceph/pull/50486
parent tracker: https://tracker.ceph.com/issues/59059

quincy: Do not duplicate query-string in ops-log

---

src/rgw/rgw_rest_s3.cc

backport tracker: https://tracker.ceph.com/issues/59376
---
backport of https://github.com/ceph/ceph/pull/50235
parent tracker: https://tracker.ceph.com/issues/45789

quincy: rgw: handle old clients with transfer-encoding: chunked.

---

src/rgw/rgw_op.cc

backport tracker: https://tracker.ceph.com/issues/57658
---
backport of https://github.com/ceph/ceph/pull/48012
parent tracker: https://tracker.ceph.com/issues/57468

quincy: rgw: set requestPayment in slave zone

---

src/rgw/rgw_auth_keystone.cc
src/rgw/rgw_auth_keystone.h

backport tracker: https://tracker.ceph.com/issues/59357
---
backport of https://github.com/ceph/ceph/pull/50550
parent tracker: https://tracker.ceph.com/issues/58908

quincy: rgw/keystone: use secret key from EC2 for sigv4 streaming mode

---

src/mon/PGMap.cc
src/mon/PGMap.h

backport tracker: https://tracker.ceph.com/issues/62926
---
backport of https://github.com/ceph/ceph/pull/49332
parent tracker: https://tracker.ceph.com/issues/51688

quincy: mon: stuck peering since warning is misleading

---

src/osd/PrimaryLogPG.cc
src/osd/Watch.cc

backport tracker: https://tracker.ceph.com/issues/67166
---
backport of https://github.com/ceph/ceph/pull/50861
parent tracker: https://tracker.ceph.com/issues/58120

reef: osd: avoid watcher remains after "rados watch" is interrupted

---

ceph.spec.in
debian/control
src/ceph-volume/setup.py

in 0985e201, "packaging" was introduced as a runtime dependency of ceph-volume, and `ceph.spec.in` was updated accordingly to note this new dependency. but the debian packaging was not updated.
in 80edcd40, the missing dependency was added to debian/control as one of ceph-volume's runtime dependency.
but dh_python3 is able to figure out the dependencies by reading the egg's metadata of the ceph-volume python module. and as a python project, ceph-volume is using its `setup.py` for tracking its dependencies.
so in order to be more consistent, and keep all of its dependencies in one place, let's move this dependency to setup.py .
- If you are …

ceph-volume: add "packaging" to install_requires

---

qa/workunits/rados/test_envlibrados_for_rocksdb.sh

This workunit was still trying to enable
"codeready-builder-for-rhel-8-x86_64-rpms", which is a repo specific to centos 8 stream. After changing the repo name, I found that there is no libarchive-3.3.3 package available for centos 9 stream, so I changed it to the generic version.
This test is only run in quincy, so this would be a direct merge to quincy.
Fixes: https://tracker.ceph.com/issues/67562 …

quincy: qa/workunits/rados: enable crb and install generic package for c9

---

src/rgw/rgw_rados.cc

backport tracker: https://tracker.ceph.com/issues/57198
---
backport of https://github.com/ceph/ceph/pull/47228
parent tracker: https://tracker.ceph.com/issues/56673

quincy: rgw: 'bucket check' deletes index of multipart meta when its pending_map is nonempty

---

src/rgw/rgw_sts.cc

backport tracker: https://tracker.ceph.com/issues/63256
---
backport of https://github.com/ceph/ceph/pull/53801
parent tracker: https://tracker.ceph.com/issues/63085

quincy: RGW/STS: when generating keys, take the trailing null character into account

---

src/rgw/rgw_amqp.cc

backport tracker: https://tracker.ceph.com/issues/57888
---
backport of https://github.com/ceph/ceph/pull/48444
parent tracker: https://tracker.ceph.com/issues/57850

quincy: rgw/amqp: store CA location string in connection object

---

src/rgw/rgw_auth_s3.cc

backport tracker: https://tracker.ceph.com/issues/63625
---
backport of https://github.com/ceph/ceph/pull/53504
parent tracker: https://tracker.ceph.com/issues/62105

quincy: rgw: SignatureDoesNotMatch for certain RGW Admin Ops endpoints w/v4 auth

---

src/rgw/rgw_auth.cc
src/rgw/rgw_rest_s3.cc

backport tracker: https://tracker.ceph.com/issues/62414
---
backport of https://github.com/ceph/ceph/pull/52510
parent tracker: https://tracker.ceph.com/issues/61916

quincy: rgw/auth: Fix the return code returned by AuthStrategy,

---

qa/suites/rgw/notifications/tasks/0-install.yaml
qa/tasks/kafka.py
qa/tasks/rabbitmq.py
src/test/rgw/bucket_notification/test_bn.py

backport tracker: https://tracker.ceph.com/issues/66710
---
backport of https://github.com/ceph/ceph/pull/54025
parent tracker: https://tracker.ceph.com/issues/63205

reef: rgw/notifications/test: fix rabbitmq and kafka issues in centos9

---

src/os/bluestore/BlueStore.cc

The formula checking if all the cache sizes sum up to <= 1 did not take cache_kv_onode_ratio into account.
The last dout line did also not take cache_kv_onode_ratio into account.
Parent tracker: https://tracker.ceph.com/issues/50992
Backports: https://github.com/ceph/ceph/pull/51784
Backport tracker: https://tracker.ceph.com/issues/64071
Signed-off-by: Raimund Sacherer <rsachere@redhat.com>
(cherry picked from commit 8d32e586dcbf355ea7155a4a8c06389be07a2fe8) …

reef: osd: make _set_cache_sizes ratio aware of cache_kv_onode_ratio

---

src/test/objectstore/store_test.cc

When bitmap allocator is in use different space fragmentation and allocation strategy cause blob fragmentation. Which in turn impacts the decision on deferred write applicability.
Fixing by using standalone DB volume to reduce main device space fragmentation.
Parent tracker: https://tracker.ceph.com/issues/63795
Backports: https://github.com/ceph/ceph/pull/54876
Backport tracker: https://tracker.ceph.com/issues/63913
(cherry picked from commit fd3be76ecc2c6b1f436cda19ba961f8f45014b02) …

reef: test/store_test: fix deferred writing test cases

---

src/mon/OSDMonitor.cc
src/mon/OSDMonitor.h

backport tracker: https://tracker.ceph.com/issues/65096
---
backport of https://github.com/ceph/ceph/pull/55841
parent tracker: https://tracker.ceph.com/issues/64646

reef: mon/OSDMonitor: fix rmsnap command

---

src/os/bluestore/BlueFS.cc

backport tracker: https://tracker.ceph.com/issues/64590
---
backport of https://github.com/ceph/ceph/pull/55700
parent tracker: https://tracker.ceph.com/issues/64533

reef: os/bluestore: fix the problem of l_bluefs_log_compactions double recording

---

src/os/bluestore/BlueStore.cc

backport tracker: https://tracker.ceph.com/issues/63315
---
backport of https://github.com/ceph/ceph/pull/54155
parent tracker: https://tracker.ceph.com/issues/63308

reef: os/bluestore: fix crash caused by dividing by 0

---

src/rgw/rgw_op.cc
src/rgw/rgw_op.h

PutObj is not loading the source bucket's attrs, which prevents the associated policies from being loaded. As a result, the permissions granted to the user to read from the source bucket are not being properly evaluated.
Fixes: https://tracker.ceph.com/issues/67590

rgw: load copy source bucket attrs in putobj

---

src/mds/Server.cc

When the previous client's setattr request is still holding the xlock for the linklock/authlock/xattrlock/filelock locks, if the same client send a getattr request it will use the projected inode to fill the reply, while for other clients the getattr requests will use the none projected inode to fill replies. This just cause inconsistent file mode across multiple clients.
This will just let the getattr wait until the previous client release the xlock.
Fixes: https://tracker.ceph.com/issues/63906 …

mds: getattr just waits the xlock to be released by the previous client

---

doc/rados/operations/cache-tiering.rst

Explain how to deal with "unfound objects" when restarting OSDs in a cache-tiered environment.
Fixes: https://tracker.ceph.com/issues/44286
(cherry picked from commit f01d7a8d5b85170c034acb962b9833913853a1c5) …

quincy: doc/rados: document unfound object cache-tiering scenario

---

src/pybind/mgr/orchestrator/module.py

The current implementation incorrectly parses this `encrypted` flag as a string rather than a boolean value. This leads to unintended behavior causing an LVM encryption layer to be created regardless of whether `encrypted=True` or `encrypted=False` is passed. The only way to prevent this behavior is by omitting the `encrypted` flag entirely. This change prevents potential errors, aligning the behavior with user expectations.
Fixes: https://tracker.ceph.com/issues/67372
Signed-off-by: Yonatan Zaken <yonatan.zaken@gmail.com> …

mgr/orchestrator: fix encrypted flag handling in orch daemon add osd

---

CMakeLists.txt
ceph.spec.in
cmake/modules/Builduadk.cmake
src/common/options/global.yaml.in
src/compressor/CMakeLists.txt
src/compressor/UadkAccel.cc
src/compressor/UadkAccel.h
src/compressor/zlib/CMakeLists.txt
src/compressor/zlib/ZlibCompressor.cc
src/compressor/zlib/ZlibCompressor.h
src/include/config-h.in.cmake
src/test/compressor/test_compression.cc

This patch add UADK Acceleration for zlib compressor
[UADK: Userspace Acceleration Development Kit](https://github.com/Linaro/uadk)
1. Unity: one set of interfaces to support enc and comp acceleration
2. Efficiency: userspace zerocopy based on IOMMU & SVA(shared virtual address)
3. Security: the IOMMU limits the access rights and security boundaries of devices and processes
4. Compatibility: all acc devices can join this opensource project
Test on Kunpeng 920 platform, compression offload based on UadkAccel:
1. save almost 50% cpu usage compared with no-isal compression in RBD 4M workload
2. save almost 40% cpu usage compared with no-isal compression in RGW put op (4M) workload
3. lower cpu usage, better performance …

Compressor: add UADK support

---

src/pybind/mgr/cephadm/services/osd.py

backport tracker: https://tracker.ceph.com/issues/67682
---
backport of https://github.com/ceph/ceph/pull/59318
parent tracker: https://tracker.ceph.com/issues/67329

reef: mgr/cephadm: add "original_weight" parameter to OSD class

---

src/test/rgw/bucket_notification/test_bn.py

backport tracker: https://tracker.ceph.com/issues/61521
---
backport of https://github.com/ceph/ceph/pull/51810
parent tracker: https://tracker.ceph.com/issues/61477

quincy: test/rgw/notifications: fix kafka consumer shutdown issue

---

src/rgw/rgw_lua_utils.cc

backport tracker: https://tracker.ceph.com/issues/61190
---
backport of https://github.com/ceph/ceph/pull/51453
parent tracker: https://tracker.ceph.com/issues/59733

quincy: rgw/lua: add lib64 to the package search path

---

src/rgw/rgw_op.cc

backport tracker: https://tracker.ceph.com/issues/59608
---
backport of https://github.com/ceph/ceph/pull/50924
parent tracker: https://tracker.ceph.com/issues/58594

quincy: rgw: add crypt attrs for iam policy to PostObj and Init/CompleteMultipart

---

src/rgw/rgw_op.cc

backport tracker: https://tracker.ceph.com/issues/59605
---
backport of https://github.com/ceph/ceph/pull/49965
parent tracker: https://tracker.ceph.com/issues/58628

quincy: rgw/sts: changing identity to boost::none, when role policy

---

src/rgw/rgw_admin.cc

backport tracker: https://tracker.ceph.com/issues/63404
---
backport of https://github.com/ceph/ceph/pull/53828
parent tracker: https://tracker.ceph.com/issues/62845

quincy: rgw/multisite: fix sync_error_trim command

---

src/rgw/rgw_file.cc

backport tracker: https://tracker.ceph.com/issues/63424
---
backport of https://github.com/ceph/ceph/pull/54309
parent tracker: https://tracker.ceph.com/issues/63409

quincy: rgwfile: fix lock_guard decl

---

src/rgw/rgw_op.cc

backport tracker: https://tracker.ceph.com/issues/63584
---
backport of https://github.com/ceph/ceph/pull/54528
parent tracker: https://tracker.ceph.com/issues/63580

quincy: rgw/notifications: cleanup all coroutines after sending the notification

---

qa/workunits/rgw/test_rgw_versioning.py
src/cls/rgw/cls_rgw.cc
src/common/options/rgw.yaml.in
src/rgw/rgw_rados.cc

backport tracker: https://tracker.ceph.com/issues/64304
---
backport of https://github.com/ceph/ceph/pull/55162
parent tracker: https://tracker.ceph.com/issues/64014

quincy: rgw: fix issue with concurrent versioned deletes leaving behind olh entries

---

src/rgw/rgw_rados.cc
src/rgw/services/svc_rados.cc

backport tracker: https://tracker.ceph.com/issues/67483
---
backport of https://github.com/ceph/ceph/pull/50016
parent tracker: https://tracker.ceph.com/issues/54802

quincy: rgw: catches nobjects_begin() exceptions

---

src/mgr/BaseMgrModule.cc

backport tracker: https://tracker.ceph.com/issues/63977
---
backport of https://github.com/ceph/ceph/pull/54634
parent tracker: https://tracker.ceph.com/issues/59580

reef: mgr/BaseMgrModule: Optimize CPython Call in Finish Function

---

src/osd/ECBackend.cc

backport tracker: https://tracker.ceph.com/issues/66145
--------
backport of #57137
parent tracker: https://tracker.ceph.com/issues/65686

reef: osd: CEPH_OSD_OP_FLAG_BYPASS_CLEAN_CACHE flag is passed from ECBackend

---

src/common/options/global.yaml.in
src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/os/bluestore/bluestore_common.h
src/os/bluestore/bluestore_tool.cc
src/test/objectstore/store_test.cc
src/test/objectstore/store_test_fixture.cc
src/test/objectstore/store_test_fixture.h
src/test/objectstore/test_bluefs.cc

backport tracker: https://tracker.ceph.com/issues/67454
backport of #55374
parent tracker: https://tracker.ceph.com/issues/67451
This backport was manually created. …

squid: os/bluestore: Multiple bdev labels on main block device

---

src/nvmeof/NVMeofGwMonitorClient.cc
src/nvmeof/NVMeofGwMonitorClient.h

Add beacon_lock to mitigate potential beacon delays caused by slow message handling, particularly in handle_nvmeof_gw_map.
CI Run: https://github.com/ceph/ceph-nvmeof/pull/784 …

nvmeof/NVMeofGwMonitorClient: use a separate mutex for beacons

---

src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/transaction_manager.cc

Extracted from https://github.com/ceph/ceph/pull/59391 for discussions.
- Component …

crimson/os/seastore: refine documents related to inplace rewrite

---

doc/cephadm/services/osd.rst

Add instructions for retrieving the exact size of block devices.
Fixes: https://tracker.ceph.com/issues/66754
- …

doc/cephadm: how to get exact size_spec from device

---

qa/tasks/mgr/dashboard/test_crush_rule.py
src/pybind/mgr/dashboard/controllers/crush_rule.py
src/pybind/mgr/dashboard/openapi.yaml

backport tracker: https://tracker.ceph.com/issues/67123
---
backport of https://github.com/ceph/ceph/pull/58224
parent tracker: https://tracker.ceph.com/issues/66490

squid: mgr/dashboard: add restful api for creating crush rule with type of 'erasure'

---

src/crimson/common/tri_mutex.cc
src/crimson/common/tri_mutex.h
src/crimson/osd/osd_operations/client_request.cc

Fixes: https://tracker.ceph.com/issues/67604 …

crimson/common/tri_mutex: also wake up waiters when demoting

---

src/pybind/mgr/cephadm/services/osd.py

backport tracker: https://tracker.ceph.com/issues/67683
---
backport of https://github.com/ceph/ceph/pull/59318
parent tracker: https://tracker.ceph.com/issues/67329

quincy: mgr/cephadm: add "original_weight" parameter to OSD class

---

doc/cephadm/services/osd.rst

Add instructions for retrieving the exact size of block devices.
Fixes: https://tracker.ceph.com/issues/66754
(cherry picked from commit d00d1b52d50b5575d918c3be7b7a8249ef31f0a8) …

squid: doc/cephadm: how to get exact size_spec from device

---

doc/cephadm/services/osd.rst

Add instructions for retrieving the exact size of block devices.
Fixes: https://tracker.ceph.com/issues/66754
(cherry picked from commit d00d1b52d50b5575d918c3be7b7a8249ef31f0a8) …

reef: doc/cephadm: how to get exact size_spec from device

---

doc/cephadm/services/osd.rst

Add instructions for retrieving the exact size of block devices.
Fixes: https://tracker.ceph.com/issues/66754
(cherry picked from commit d00d1b52d50b5575d918c3be7b7a8249ef31f0a8) …

quincy: doc/cephadm: how to get exact size_spec from device

---

doc/radosgw/config-ref.rst
src/common/options/rgw.yaml.in
src/rgw/rgw_auth_keystone.cc
src/rgw/rgw_keystone.cc
src/rgw/rgw_keystone.h

The v2.0 API was removed from Keystone [1] in
the Queens release back in 2018 so we can
safely remove it for the next release.
This helps cleanup a lot of code and removes
the need for the rgw_keystone_api_version
configuration option.
[1] https://docs.openstack.org/keystone/latest/contributor/http-api.html …

rgw/auth: Remove Keystone v2.0 API support

---

src/pybind/mgr/cephadm/services/osd.py

backport tracker: https://tracker.ceph.com/issues/67681
---
backport of https://github.com/ceph/ceph/pull/59318
parent tracker: https://tracker.ceph.com/issues/67329

squid: mgr/cephadm: add "original_weight" parameter to OSD class

---

src/rgw/rgw_op.cc

RGWGetBucketPolicy, RGWGetBucketPublicAccessBlock, RGWGetBucketEncryption logs with level 0 when the bucket doesn't have those documents. As this is a normal client error, this can be logged with level 20 as this does not indicate any serious error.
Fixes: https://tracker.ceph.com/issues/67500

rgw: increase log level for enoent caused by clients

---

src/rgw/driver/rados/rgw_bucket.cc

> rgw_bucket.cc:962:19: warning: ‘shard_count’ may be used uninitialized [-Wmaybe-uninitialized]
Fixes: https://tracker.ceph.com/issues/67468
<details>
</details>

rgw/rados: zero-init shard_count in RGWBucket::check_index_unlinked()

---

PendingReleaseNotes
src/rgw/driver/rados/rgw_zone.cc
src/rgw/rgw_admin.cc
src/test/cli/radosgw-admin/help.t
src/test/rgw/test_multi.py

multisite configuration was simplified with squid, but may cause configurations that were valid in reef to fail on startup. when no `rgw_realm` or `rgw_zone` options are specifically requested and we fail to load the default zone of the default realm, try to fall back to the global "default" zone/zonegroup
Fixes: https://tracker.ceph.com/issues/67697
<details> …

rgw: ignore zoneless default realm when not configured

---

qa/standalone/ceph-helpers.sh
qa/standalone/crush/crush-classes.sh
qa/workunits/rbd/cli_generic.sh
qa/workunits/rbd/cli_migration.sh
qa/workunits/rbd/journal.sh
qa/workunits/rbd/rbd-ggate.sh
qa/workunits/rbd/rbd-nbd.sh
qa/workunits/rbd/rbd_mirror_helpers.sh
qa/workunits/rbd/test_admin_socket.sh

The variable was added in commit 9b6b7c35d03f ("Handle differently-named xmlstarlet binary for *suse") but this compatibility business is long outdated:
Mon Oct 13 08:52:37 UTC 2014 - toms@opensuse.org
- SPEC file changes
- Added link from /usr/bin/xml to /usr/bin/xmlstarlet as other distributions do the same
- Did the same for the manpage …

qa: drop XMLSTARLET variable, use xmlstarlet directly

---

qa/suites/crimson-rados/basic/tasks/rados_python.yaml
src/crimson/admin/osd_admin.cc
src/crimson/admin/osd_admin.h
src/crimson/osd/osd.cc
src/crimson/osd/osd.h
src/include/types.h

this commit adds support for the 'bench' admin command in the OSD,
allowing administrators to perform benchmark tests on the OSD. The
'bench' command accepts 4 optional parameters with the following
default values:
1. count - Total number of bytes to write (default: 1GB).
2. size - Block size for each write operation (default: 4MB).
3. object_size - Size of each object to write (default: 0).
4. object_num - Number of objects to write (default: 0).
The results of the benchmark are returned in a JSON formatted output,
which includes the following fields:
1. bytes_written - Total number of bytes written during the benchmark.
2. blocksize - Block size used for each write operation.
3. elapsed_sec - Total time taken to complete the benchmark in seconds.
4. bytes_per_sec - Write throughput in …

crimson: Add support for bench osd command

---

qa/distros/container-hosts/centos_9.stream.yaml
qa/distros/container-hosts/centos_9.stream_runc.yaml

To work around a potential linking issue between
nvme-cli ad libnvme that prevents nvme-cli from
correctly generating a hostnqn, causing
nvme_fabrics: found same hostid edb4e426-766f-44c6-b127-da2a5b7446ef but different hostnqn hostnqn
messages in dmesg and the inability to setup nvme
loop devices
Fixes: https://tracker.ceph.com/issues/67684 …

qa/distros: reinstall nvme-cli on centos 9 nodes

---

src/client/Client.cc

In the ll_sync_inode function, the entire Inode structure is printed without holding a lock. This can lead to a race condition when evaluating the assertion in xlist<ObjectCacher::Object*>::size(), resulting in abnormal behavior.
Fixes: https://tracker.ceph.com/issues/67491

client: Prevent race condition when printing Inode in ll_sync_inode

---

qa/cephfs/overrides/ignorelist_health.yaml

In following 2 jobs from a Squid QA run we see cluster errors/warnings
which are expected but not added to ignorelist which causes these jobs
to fail.
From https://pulpito.ceph.com/xiubli-2024-07-29_02:08:56-fs-wip-xiubli-testing-20240726.021939-squid-distro-default-smithi/7823678 -
"2024-07-29T05:10:00.000118+0000 mon.smithi057 (mon.0) 879 : cluster [WRN] Health detail: HEALTH_WARN insufficient standby MDS daemons available" in cluster log
From https://pulpito.ceph.com/xiubli-2024-07-29_02:08:56-fs-wip-xiubli-testing-20240726.021939-squid-distro-default-smithi/7823724 -
"2024-07-29T06:00:00.000144+0000 mon.smithi104 (mon.0) 600 : cluster [ERR] fs cephfs is degraded" in cluster log
"FS_DEGRADED" and "MDS_INSUFFICIENT_STANDBY" are already present in the
ignorelist for these jobs bit these …

qa/cephfs: update ignorelist

---

PendingReleaseNotes
src/rgw/driver/rados/rgw_zone.cc
src/rgw/rgw_admin.cc
src/test/cli/radosgw-admin/help.t
src/test/rgw/test_multi.py

backport tracker: https://tracker.ceph.com/issues/67723
---
backport of https://github.com/ceph/ceph/pull/59422
parent tracker: https://tracker.ceph.com/issues/67697

squid: rgw: ignore zoneless default realm when not configured

---

qa/suites/fs/upgrade/mds_upgrade_sequence/tasks/0-from/squid.yaml

The approach to pull from github stopped working after quincy. We need to use this new compiled_cephadm_branch option to pull the binary for reef or squid unless the cephadm we want is the one from the actual build we're testing (so basically just pre-upgrade in upgrade tests)
Fixes: https://tracker.ceph.com/issues/66786 …

qa/suites/fs: pull compiled cephadm for squid branch in mds_upgrade_sequence

---

src/rgw/rgw_auth.cc

Clang-tidy warning re strategy_result is incorrect. No path leads to a moved-from object
being reused. strategy_result is immediately being re-assigned after the move.
Added annotations to prevent the false detection.
reference: https://github.com/ceph/ceph/blob/e879ce83c084f1a96e5dd0ab2b57bf909cfa423d/src/rgw/rgw_auth.cc#L461-L463
clang-tidy warning for `rgw_auth.cc`:
```
/home/suyash/ceph/src/rgw/rgw_auth.cc:493:10: warning: 'strategy_result' used after it was moved [bugprone-use-after-move]
return strategy_result; 
^
/home/suyash/ceph/src/rgw/rgw_auth.cc:462:11: note: move occurred here
strategy_handle_rejected(std::move(engine_result), policy,
^
```
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rs …

rgw: rgw_auth.cc: disable false use-after-move clang-tidy warning

---

src/test/rbd_mirror/test_mock_PoolReplayer.cc
src/tools/rbd_mirror/PoolReplayer.cc

The PoolReplayer uses the ioctx for the default namespace to check if other namespaces are enabled for mirroring, causing it to incorrectly conclude that they are all enabled.
Fixes: https://tracker.ceph.com/issues/67676 …

rbd-mirror: use correct ioctx for namespace

---

qa/suites/nvmeof/basic/workloads/nvmeof_initiator.yaml
qa/suites/nvmeof/thrash/gateway-initiator-setup/3-subsys-60-namespace.yaml
qa/tasks/nvmeof.py

This PR adds nvmeof gateway groups to it's deployment in "nvmeof" teuthology test. 
Groups was made a required parameter to `ceph orch apply nvmeof <pool> <group>` in https://github.com/ceph/ceph/pull/58860. That broke the `nvmeof` suite so this PR fixes that.
Right now, all gateway are deployed in a single group. Later, this would be changed to have 2 gateway groups for a better test.
Results: 
Thrasher (passed): https://pulpito.ceph.com/vallariag-2024-08-26_08:49:55-nvmeof-wip-sjust-nvmeof-testing-nvmeof-reenable-2024-08-24-distro-default-smithi/
Other tests (queued): https://pulpito.ceph.com/vallariag-2024-08-26_09:57:21-nvmeof-wip-sjust-nvmeof-testing-nvmeof-reenable-2024-08-24-distro-default-smithi/ …

qa/tasks/nvmeof.py: add nvmeof gw-group to deployment

---

doc/cephadm/services/smb.rst
doc/mgr/smb.rst
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_ctdb_res_ips.yaml
src/cephadm/cephadmlib/daemons/smb.py
src/pybind/mgr/cephadm/services/smb.py
src/pybind/mgr/smb/handler.py
src/pybind/mgr/smb/module.py
src/pybind/mgr/smb/resources.py
src/python-common/ceph/deployment/service_spec.py

Depends on: <s>https://github.com/samba-in-kubernetes/sambacc/pull/133</s> pr merged
Add support for IPs managed by Samba's CTDB clustering system that can move due to cluster events. The IPs are configured in "interface form" (with a /<prefixlength>), and these values are passed down to ctdb through sambacc after being converted to device names by cephadm.
The cephadm service and the smb mgr module resource have basically the same YAML/JSON configuration. Example:
```yaml
- resource_type: ceph.smb.cluster
cluster_id: adipctdb 
auth_mode: active-directory
domain_settings:
realm: DOMAIN1.SINK.TEST
join_sources:
- source_type: resource
ref: join1-admin
public_addrs:
- address: 192.168.76.50/24
- address: 192.168.76.51/24
- address: 192.168.76.51/24
placement:
count: 3
```
These can also …

smb: cluster public ip addresses support

---

qa/distros/container-hosts/centos_9.stream.yaml
qa/distros/container-hosts/centos_9.stream_runc.yaml

backport tracker: https://tracker.ceph.com/issues/67732
---
backport of https://github.com/ceph/ceph/pull/59409
parent tracker: https://tracker.ceph.com/issues/67684

squid: qa/distros: reinstall nvme-cli on centos 9 nodes

---

src/rgw/rgw_sts.cc

to indicate that the key needs to be alphanumeric.
- …

rgw/sts: correcting the error message returned for an sts key

---

src/osd/PeeringState.cc

Currently, in `calc_replicated_acting_stretch` we would call `pop_ancester` before checking whether the next OSD we populate in the want_acting set would have
the ancestor count that is >= bucket_max.
Fixes: https://tracker.ceph.com/issues/65371
Backporting relevant commit(s) from main PR(s):
https://github.com/ceph/ceph/pull/57381
Signed-off-by: Kamoltat <ksirivad@redhat.com> …

squid: PeeringState.cc: Only populate want_acting when num_osds < bucket_max

---

doc/radosgw/account.rst

Add a subsection under "Migrate an existing User into an Account" to describe how a client can seamlessly migrate the notification topics after account migration.
Fixes https://tracker.ceph.com/issues/67656 …

doc/rgw/account: Handling notification topics when migrating an existing user into an account

---

qa/tasks/s3tests.py
src/rgw/rgw_op.cc

backport tracker: https://tracker.ceph.com/issues/67554
---
backport of https://github.com/ceph/ceph/pull/59169
parent tracker: https://tracker.ceph.com/issues/67464

squid: rgw: revert account-related changes to get_iam_policy_from_attr()

---

doc/rados/operations/pools.rst
doc/rados/operations/stretch-mode.rst
qa/suites/rados/singleton/all/3-az-stretch-cluster-netsplit.yaml
qa/suites/rados/singleton/all/mon-stretch-pool.yaml
qa/tasks/ceph_manager.py
qa/tasks/ceph_test_case.py
qa/tasks/stretch_cluster.py
qa/tasks/test_netsplit_3az_stretch_pool.py
qa/workunits/mon/mon-stretch-pool.sh
src/mon/MonCommands.h
src/mon/OSDMonitor.cc
src/mon/OSDMonitor.h
src/osd/osd_types.cc

THIS PR SHOULD BE TESTED IN CONJUNCTION WITH https://github.com/ceph/ceph/pull/57381
Recommend merging https://github.com/ceph/ceph/pull/57381 before this PR.
In the command `ceph osd pool stretch set`
```
<pool> <peering_crush_bucket_count>
<peering_crush_bucket_target> <peering_crush_bucket_barrier> <crush_rule> <size> <min_size>
```
user has the option of setting the value of `peering_crush_bucket_{count|target|barrier}`.
This will then allow the utilization `calc_replicated_acting_stretch`,
since with `peering_crush_bucket_count != 0`
the pool is now a stretch_pool and we can handle pg_temp
better by setting barriers and limits to how much OSDs
should be in a `pg_temp`.
This will enable the specify pool to
handle `pg_temp` properly during `create_acting`, as a stretch pool
should. …

squid: RADOS: Generalize stretch mode pg temp handling to be usable without stretch mode

---

qa/suites/rados/thrash-erasure-code/thrashers/minsize_recovery.yaml
qa/tasks/ceph_manager.py
qa/tasks/rados.py
qa/tasks/thrashosds.py

backport tracker: https://tracker.ceph.com/issues/64671
---
backport of https://github.com/ceph/ceph/pull/52891
parent tracker: https://tracker.ceph.com/issues/59172

reef: qa/tasks/ceph_manager.py: Rewrite test_pool_min_size

---

src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/cache.h
src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/seastore_types.cc
src/crimson/os/seastore/seastore_types.h
src/crimson/os/seastore/transaction.h
src/crimson/os/seastore/transaction_manager.cc

Example output:
```
INFO  2024-08-22 11:02:40,358 [shard 0:main] seastore_cache - Cache::get_stats:
dirty total(34.21MiB,36.27KiB,966)
data(0.00MiB,-nanKiB,0)
mdat(32.64MiB,59.47KiB,562)
phys(1.57MiB,3.99KiB,404)
dirty io: in(0.23MiB/s,43.64KiB,5.50ps) replaces=448.46ps out(0.26MiB/s,48.73KiB,5.50ps) outv=209.45
MUTATE: in(0.23MiB/s,47.60KiB,5.00ps) replaces=423.46ps out(0.07MiB/s,34.00KiB,2.00ps) outv=79.00
data: in(0.00MiB/s,-nanKiB,0.00ps) replaces=0.00ps out(0.00MiB/s,-nanKiB,0.00ps) outv=-nan
mdat: in(0.23MiB/s,52.44KiB,4.50ps) replaces=316.47ps out(0.06MiB/s,64.00KiB,1.00ps) outv=119.00
phys: in(0.00MiB/s,4.00KiB,0.50ps) replaces=106.99ps out(0.00MiB/s,4.00KiB,1.00ps) outv=39.00
TRIM_DIRTY: in(0.00MiB/s,4.00KiB,0.50ps) replaces=3.00ps out(0.20MiB/s,57.14KiB,3.50ps) outv=284.00
data: …
```

crimson/os/seastore/cache: report dirty cache usage and rewrite stats

---

src/crimson/osd/pg.h

```
ceph-osd.1.log:ERROR 2024-08-28 08:07:50,260 [shard 0:main] osd - /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/19.3.0-4509-g9d230727/rpm/el9/BUILD/ceph-19.3.0-4509-g9d230727/src/crimson/osd/pg.h:265 @virtual void crimson::osd::PG::request_local_background_io_reservation(unsigned int, PGPeeringEventURef, PGPeeringEventURef): failed to log message: fmt='{} {}: priority {} on_grant {} on_preempt {}': fmt::v11::format_error (argument not found)
``` …

crimson/osd/pg: fix missing priority argument

---

src/cephadm/cephadmlib/daemons/nvmeof.py

https://github.com/ceph/ceph/commit/2946b195edfc0b6a5cfcc661079e351601707ecb incorrectly removed this line and since then these certs are not being properly mounted into the container. This commit adds the line back …

cephadm: mount nvmeof certs into container

---

src/cephadm/cephadm.py
src/cephadm/tests/test_cephadm.py

backport tracker: https://tracker.ceph.com/issues/64991
---
backport of https://github.com/ceph/ceph/pull/56147
parent tracker: https://tracker.ceph.com/issues/64879

reef: cephadm: fix `cephadm shell --name <daemon-name>` for stopped/failed daemon

---

src/pybind/mgr/cephadm/services/nvmeof.py

backport tracker: https://tracker.ceph.com/issues/65763
---
backport of https://github.com/ceph/ceph/pull/57143
parent tracker: https://tracker.ceph.com/issues/65691

reef: mgr/cephadm: set OSD cap for NVMEoF daemon to "profile rbd"

---

src/cephadm/cephadm.py

Backport of https://github.com/ceph/ceph/pull/54158
<details>
</details>

reef: cephadm: added check for `--skip-firewalld` to section on adding explicit Ports to firewalld

---

src/cephadm/cephadm.py

backport tracker: https://tracker.ceph.com/issues/65723
---
backport of https://github.com/ceph/ceph/pull/56961
parent tracker: https://tracker.ceph.com/issues/65553

reef: cephadm: have agent check for errors before json loading mgr response

---

src/cephadm/cephadm.py

backport tracker: https://tracker.ceph.com/issues/65969
---
backport of https://github.com/ceph/ceph/pull/57205
parent tracker: https://tracker.ceph.com/issues/65739

reef: mgr/cephadm: make setting --cgroups=split configurable for adopted daemons

---

src/cephadm/cephadm.py

backport tracker: https://tracker.ceph.com/issues/66426
---
backport of https://github.com/ceph/ceph/pull/57389
parent tracker: https://tracker.ceph.com/issues/65896

reef: cephadm: CephExporter doesn't bind to IPv6 in dual stack

---

src/pybind/mgr/cephadm/upgrade.py

backport tracker: https://tracker.ceph.com/issues/66428
---
backport of https://github.com/ceph/ceph/pull/57292
parent tracker: https://tracker.ceph.com/issues/65809

reef: mgr/cephadm: make SMB and NVMEoF upgrade last in staggered upgrade

---

doc/radosgw/account.rst

backport tracker: https://tracker.ceph.com/issues/67782
---
backport of https://github.com/ceph/ceph/pull/59390
parent tracker: https://tracker.ceph.com/issues/67656

squid: doc/rgw/account: Handling notification topics when migrating an existing user into an account

---

src/common/options/rgw.yaml.in
src/rgw/rgw_kafka.cc

backport tracker: https://tracker.ceph.com/issues/64886
---
backport of https://github.com/ceph/ceph/pull/55952
parent tracker: https://tracker.ceph.com/issues/64710

quincy: rgw/kafka: set message timeout to 5 seconds

---

qa/tasks/cephfs/test_fscrypt.py

The journal reset effectively cleared the cache so the rank may not have the dirfrag in memory when we verify alternate name recovery.
Fixes: https://tracker.ceph.com/issues/67511 …

qa: load all dirfrags before testing altname recovery

---

src/common/options/rgw.yaml.in
src/rgw/rgw_bucket.cc
src/rgw/rgw_bucket.h
src/rgw/rgw_data_sync.cc
src/rgw/rgw_lc.cc
src/rgw/rgw_lc.h
src/rgw/rgw_lc_s3.cc
src/rgw/rgw_lc_s3.h
src/rgw/rgw_sal.h
src/rgw/rgw_sal_dbstore.h
src/rgw/rgw_sal_rados.cc
src/rgw/rgw_sal_rados.h
src/rgw/rgw_service.cc
src/rgw/rgw_sync_module.cc
src/rgw/rgw_sync_module.h
src/test/rgw/CMakeLists.txt
src/test/rgw/test_rgw_lc.cc

backport tracker: https://tracker.ceph.com/issues/63776
---
backport of https://github.com/ceph/ceph/pull/54622
parent tracker: https://tracker.ceph.com/issues/63613
This PR is based on https://github.com/ceph/ceph/pull/54873 backport to avoid unnecessary conflicts. So it will need rebase when that PR is merged.
Also if PR https://github.com/ceph/ceph/pull/49527 is merged before this PR, then  the conflict in "rgw/lc: [non-functional change] use const expr to represent seconds in a day" could be resolved.

quincy: [rgw][lc][rgw_lifecycle_work_time] adjust timing if the configured end time is less than the start time

---

qa/tasks/barbican.py

backport tracker: https://tracker.ceph.com/issues/67618
---
backport of https://github.com/ceph/ceph/pull/59241
parent tracker: https://tracker.ceph.com/issues/67444

quincy: qa: barbican: restrict python packages with upper-constraints

---

src/rgw/rgw_rados.cc

backport tracker: https://tracker.ceph.com/issues/64447
---
backport of https://github.com/ceph/ceph/pull/55486
parent tracker: https://tracker.ceph.com/issues/64340

quincy: rgw: do not copy olh attributes in versioning suspended bucket

---

src/mgr/BaseMgrModule.cc

backport tracker: https://tracker.ceph.com/issues/63979
---
backport of https://github.com/ceph/ceph/pull/54634
parent tracker: https://tracker.ceph.com/issues/59580

quincy: mgr/BaseMgrModule: Optimize CPython Call in Finish Function

---

src/osd/OSD.cc
src/osd/OSD.h

backport tracker: https://tracker.ceph.com/issues/66147
--------
backport of #56804
parent tracker: https://tracker.ceph.com/issues/64373

quincy: osd: fix for segmentation fault on OSD fast shutdown

---

src/osd/PrimaryLogPG.cc

backport tracker: https://tracker.ceph.com/issues/64576
---
backport of https://github.com/ceph/ceph/pull/55570
parent tracker: https://tracker.ceph.com/issues/64192

quincy: osd: always send returnvec-on-errors for client's retry

---

src/rgw/rgw_data_sync.cc

backport tracker: https://tracker.ceph.com/issues/57421
---
backport of https://github.com/ceph/ceph/pull/47904
parent tracker: https://tracker.ceph.com/issues/57329

quincy: rgw: avoid use-after-move in RGWDataSyncSingleEntryCR ctor

---

src/rgw/rgw-orphan-list

backport tracker: https://tracker.ceph.com/issues/58507
---
backport of https://github.com/ceph/ceph/pull/49734
parent tracker: https://tracker.ceph.com/issues/58442

quincy: rgw/rgw-orphan-list: refactor and add more checks to the tool

---

src/rgw/rgw_admin.cc
src/test/rgw/bucket_notification/api.py
src/test/rgw/bucket_notification/test_bn.py

backport tracker: https://tracker.ceph.com/issues/58364
---
backport of https://github.com/ceph/ceph/pull/48598
parent tracker: https://tracker.ceph.com/issues/57899

quincy: rgw/admin/notifications: support admin operations on topics with tenants

---

src/rgw/rgw_lua_request.cc

backport tracker: https://tracker.ceph.com/issues/59499
---
backport of https://github.com/ceph/ceph/pull/50975
parent tracker: https://tracker.ceph.com/issues/59381

quincy: rgw/lua: fix CopyFrom crash

---

src/rgw/rgw_rados.cc

backport tracker: https://tracker.ceph.com/issues/62759
---
backport of https://github.com/ceph/ceph/pull/52866
parent tracker: https://tracker.ceph.com/issues/59400

quincy: rgw: when there are a large number of multiparts, the unorder list result may miss objects

---

src/rgw/store/dbstore/CMakeLists.txt
src/rgw/store/dbstore/sqlite/CMakeLists.txt

backport tracker: https://tracker.ceph.com/issues/54464
---
backport of https://github.com/ceph/ceph/pull/45022
parent tracker: https://tracker.ceph.com/issues/54266

quincy: rgw: cmake configure error on fedora-37/rawhide

---

src/rgw/rgw_datalog.cc

backport tracker: https://tracker.ceph.com/issues/55289
---
backport of https://github.com/ceph/ceph/pull/45357
parent tracker: https://tracker.ceph.com/issues/54531

quincy: rgw: disable RGWDataChangesLog::add_entry() when log_data is off

---

src/rgw/librgw.cc

backport tracker: https://tracker.ceph.com/issues/55483
---
backport of https://github.com/ceph/ceph/pull/46022
parent tracker: https://tracker.ceph.com/issues/55430

quincy: librgw: teach librgw about rgw_backend_store

---

src/rgw/rgw_putobj_processor.cc

backport tracker: https://tracker.ceph.com/issues/57415
---
backport of https://github.com/ceph/ceph/pull/44610
parent tracker: https://tracker.ceph.com/issues/53902

quincy: rgw: Use STANDARD storage class in objects appending operation when the

---

src/pybind/mgr/dashboard/frontend/src/app/core/layouts/workbench-layout/workbench-layout.component.scss

- includes fix to make banner visible again
- includes fix to allow scrolling on longer pages like, expand cluster and upgrade
Fixes https://tracker.ceph.com/issues/67795
*banner issue*
*scroll issue*
[Screencast from 2024-08-29 17-28-54.webm](https://github.com/user-attachments/assets/60455c30-7d4c-48b2-b8d8-a9903fcb4d25)

mgr/dashboard: Fix banner and scroll issue

---

qa/cephfs/conf/mgr.yaml
qa/suites/fs/functional/tasks/snap-schedule.yaml

During teuthology tests, the tearing down of the cluster between two tests causes the config to be reset and a config_notify generated. This leads to a race to create a new mount using the old fscid. But by the time the mount is attempted the new fs gets created with a new fscid. This situation leads to the client mount waiting for a connection completion notification from the mds for 5 minutes (default timeout) and eventually giving up.
However, the default teuthology command timeout is 2 minutes. So, teuthology fails the command and declares the job as failed way before the mount can timeout.
The resolution to this case is to lower the client mount timeout to 30 seconds so that the config_notify fails fast paving the way for successive commands to get executed with the new fs.
An …

qa: failfast mount for better performance and unblock `fs volume ls`

---

src/rgw/rgw-gap-list

backport tracker: https://tracker.ceph.com/issues/58592
---
backport of https://github.com/ceph/ceph/pull/49735
parent tracker: https://tracker.ceph.com/issues/58453

quincy: rgw/rgw-gap-list: refactoring and adding more error checking

---

src/test/cls_lock/test_cls_lock.cc

backport tracker: https://tracker.ceph.com/issues/63064
---
backport of https://github.com/ceph/ceph/pull/47148
parent tracker: https://tracker.ceph.com/issues/56575

quincy: test/cls_lock: expired lock before unlock and start check

---

src/librados/IoCtxImpl.cc

backport tracker: https://tracker.ceph.com/issues/65041
---
backport of https://github.com/ceph/ceph/pull/55348
parent tracker: https://tracker.ceph.com/issues/64558

quincy: librados: use CEPH_OSD_FLAG_FULL_FORCE for IoCtxImpl::remove

---

src/osd/ECTransaction.cc

backport tracker: https://tracker.ceph.com/issues/67133
---
backport of https://github.com/ceph/ceph/pull/56924
parent tracker: https://tracker.ceph.com/issues/65509

quincy: osd/ECTransaction: Remove incorrect asserts in generate_transactions

---

src/rgw/rgw_rest_s3.cc

backport tracker: https://tracker.ceph.com/issues/64380
---
backport of https://github.com/ceph/ceph/pull/55250
parent tracker: https://tracker.ceph.com/issues/64084

quincy: rgw/auth/s3: validate x-amz-content-sha256 for empty payloads

---

doc/ceph-volume/lvm/newdb.rst

Add a procedure that explains how, after an upgrade, to move bytes that have spilled over to a relatively slow device back to the faster device.
This procedure was developed by Chris Dunlop on the [ceph-users] mailing list, here: https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/message/POPUFSZGXR3P2RPYPJ4WJ4HGHZ3QESF6/
Eugen Block requested the addition of this procedure to the documentation on 30 Aug 2024.
- When filling …

doc/ceph-volume: add spillover fix procedure

---

src/test/rbd_mirror/image_replayer/test_mock_BootstrapRequest.cc

When run with debug_rbd_mirror >= 10, is_linked() is also called as part of printing a log message. This causes the tests using expect_is_linked() to fail. …

test/rbd-mirror: fix BootstrapReplayer tests that use expect_is_linked()

---

doc/ceph-volume/lvm/newdb.rst

Add a procedure that explains how, after an upgrade, to move bytes that have spilled over to a relatively slow device back to the faster device.
This procedure was developed by Chris Dunlop on the [ceph-users] mailing list, here: https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/message/POPUFSZGXR3P2RPYPJ4WJ4HGHZ3QESF6/
Eugen Block requested the addition of this procedure to the documentation on 30 Aug 2024.
(cherry picked from commit 98618aaa1c8b786c7d240a210b62cc737fdb048d) …

squid: doc/ceph-volume: add spillover fix procedure

---

doc/ceph-volume/lvm/newdb.rst

Add a procedure that explains how, after an upgrade, to move bytes that have spilled over to a relatively slow device back to the faster device.
This procedure was developed by Chris Dunlop on the [ceph-users] mailing list, here: https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/message/POPUFSZGXR3P2RPYPJ4WJ4HGHZ3QESF6/
Eugen Block requested the addition of this procedure to the documentation on 30 Aug 2024.
(cherry picked from commit 98618aaa1c8b786c7d240a210b62cc737fdb048d) …

reef: doc/ceph-volume: add spillover fix procedure

---

doc/ceph-volume/lvm/newdb.rst

Add a procedure that explains how, after an upgrade, to move bytes that have spilled over to a relatively slow device back to the faster device.
This procedure was developed by Chris Dunlop on the [ceph-users] mailing list, here: https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/message/POPUFSZGXR3P2RPYPJ4WJ4HGHZ3QESF6/
Eugen Block requested the addition of this procedure to the documentation on 30 Aug 2024.
(cherry picked from commit 98618aaa1c8b786c7d240a210b62cc737fdb048d) …

quincy: doc/ceph-volume: add spillover fix procedure

---

doc/mgr/alerts.rst
src/pybind/mgr/alerts/module.py

---
This code change involves the alerts module in mgr:
+ **Before the change**: The current alerts can send the cluster's health status to a configured email recipient, but currently, only one recipient can be configured.
+ **After the change**: It supports setting multiple recipients, with each recipient separated by a comma.
--- …

mgr/dashboard: alerts module supports setting multiple email recipients

---

doc/rados/operations/health-checks.rst
src/blk/BlockDevice.cc
src/blk/BlockDevice.h
src/blk/kernel/KernelDevice.cc
src/common/options/global.yaml.in
src/mon/PGMap.cc
src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h

backport tracker: https://tracker.ceph.com/issues/67037
--------
backport of #57722
parent tracker: https://tracker.ceph.com/issues/62500

squid: os/bluestore: Warning added for slow operations and stalled read

---

src/pybind/mgr/cephadm/services/nvmeof.py
src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
src/pybind/mgr/cephadm/tests/test_services.py
src/python-common/ceph/deployment/service_spec.py

mgr/cephadm: revertSPDK RPC fields in nvmeof configuration
python-common/ceph/deployment: revertSPDK RPC fields in nvmeof configuration
Fixes https://tracker.ceph.com/issues/67844 …

Revert SPDK rpc fields in nvmeof configuration

---

qa/tasks/cephfs/test_admin.py
src/mds/MDSAuthCaps.cc

Removing root_squasn from MDS auth caps through "fs authorize" command
should not be allowed as this command it not allowed to/meant for
removing caps.
Fixes: https://tracker.ceph.com/issues/65808 …

cephfs: disallow removing root_squash via "fs authorize" cmd

---

doc/cephadm/services/monitoring.rst

The link is to the `#http_sd_config` anchor in the prometheus config docs; that link only works without the trailing `/`.
This correction would ideally get backported to at least reef & squid.
<details>
- …

doc: Correct link to Prometheus docs

---

doc/cephadm/services/monitoring.rst

The link is to the `#http_sd_config` anchor in the prometheus config docs; that link only works without the trailing `/`.
This correction would ideally get backported to at least reef & squid.
(cherry picked from commit 84a30ba6b94b34806faac8217ccaa299c9ee68d6) …

squid: doc: Correct link to Prometheus docs

---

doc/cephadm/services/monitoring.rst

The link is to the `#http_sd_config` anchor in the prometheus config docs; that link only works without the trailing `/`.
This correction would ideally get backported to at least reef & squid.
(cherry picked from commit 84a30ba6b94b34806faac8217ccaa299c9ee68d6) …

reef: doc: Correct link to Prometheus docs

---

src/test/cli/rbd/help.t
src/tools/rbd/action/Group.cc
src/tools/rbd/action/MirrorPool.cc
src/tools/rbd/action/Rename.cc

Make it clearer that, despite a full image or group spec being taken for source and destination, an image or a group can be renamed only within its pool or namespace.
Rename across pools or namespaces within the same pool is unsupported.
Fixes: https://tracker.ceph.com/issues/67752 …

rbd: amend "rbd {group,} rename" and "rbd mirror pool" command descriptions

---

qa/suites/rgw/multisite/realms/three-zones.yaml.disabled
qa/suites/rgw/multisite/realms/two-zonegroup.yaml.disabled
qa/suites/rgw/multisite/realms/two-zones.yaml
qa/tasks/rgw_multisite.py
qa/tasks/rgw_multisite_tests.py

in the rgw/multisite suite, jobs fail on user creation:
> radosgw-admin --cluster c1 account create --account-id RGW11111111111111111
> radosgw-admin --cluster c1 user create --uid rgw-multisite-test-user --account-id RGW11111111111111111 --account-root --rgw-zone test-zone1 --rgw-zonegroup test-zonegroup --rgw-realm test-realm --display-name TestUser --gen-access-key --gen-secret
> could not create user: unable to create user, Failed to load account by id
realms/two-zones.yaml misspells `is_default` as `is default` for the realm, so it doesn't get set as default. the `account create` command doesn't specify a realm/zonegroup/zone, so operates on the "default" zone and zonegroup
use `zone_args()` to add the explicit realm/zonegroup/zone arguments
Fixes: …

qa/rgw/multisite: specify realm/zonegroup/zone args for 'account create'

---

doc/cephadm/services/monitoring.rst

The link is to the `#http_sd_config` anchor in the prometheus config docs; that link only works without the trailing `/`.
This correction would ideally get backported to at least reef & squid.
(cherry picked from commit 84a30ba6b94b34806faac8217ccaa299c9ee68d6) …

quincy: doc: Correct link to Prometheus docs

---

src/cls/rgw/cls_rgw.cc

Fixes: https://tracker.ceph.com/issues/67780
clang-tidy original warning:
```
src/cls/rgw/cls_rgw.cc: warning: an integer is interpreted as a character code when assigning it to a string; 
if this is intended, cast the integer to the appropriate character type; if you want a string representation, 
use the appropriate conversion facility [bugprone-string-integer-assignment] key = BI_PREFIX_CHAR;
^
/home/suyash/ceph/src/cls/rgw/cls_rgw.cc:51:24: note: expanded from macro 'BI_PREFIX_CHAR' 
#define BI_PREFIX_CHAR 0x80
```
**On the following lines we are getting the warning:**
1. 138
2. 319
3. 342
4. 2875
5. 2966
6. 3294
7. 3304
8. 3307
9. 3418
10. 3421 …

rgw/cls_rgw: integer is being interpreted as a character code when assigning it to a string

---

src/cls/queue/cls_queue_src.cc

`bufferlist` must be declared in the top of the loop to avoid `use-after-move`
clang-tidy original warning:
```
/home/suyash/ceph/src/cls/queue/cls_queue_src.cc:330:50: warning: 'bl' used after it was moved [bugprone-use-after-move]
uint64_t entry_start_offset = start_offset - bl.length();
^
/home/suyash/ceph/src/cls/queue/cls_queue_src.cc:333:14: note: move occurred here
bl_chunk = std::move(bl);
^
/home/suyash/ceph/src/cls/queue/cls_queue_src.cc:330:50: note: the use happens in a later loop iteration than the move
uint64_t entry_start_offset = start_offset - bl.length();
^
```
Fixes: https://tracker.ceph.com/issues/66356
- If you are submitting a …

cls: avoid reusing moved-from buffers in cls_queue_src.cc

---

src/script/ptl-tool.py

Using ptl-tool.py on Fedora 40 with Python 3.12.3 produces the following:
```
mchangir:ORIG-mchangir-ceph.git$ ./src/script/ptl-tool.py --help
/home/mchangir/work/ORIG-mchangir-ceph.git/./src/script/ptl-tool.py:181: SyntaxWarning: invalid escape sequence '\w'
re.compile("(Reviewed-by: .+ <[\w@.-]+>)", re.IGNORECASE),
/home/mchangir/work/ORIG-mchangir-ceph.git/./src/script/ptl-tool.py:182: SyntaxWarning: invalid escape sequence '\w'
re.compile("(Acked-by: .+ <[\w@.-]+>)", re.IGNORECASE),
/home/mchangir/work/ORIG-mchangir-ceph.git/./src/script/ptl-tool.py:183: SyntaxWarning: invalid escape sequence '\w'
re.compile("(Tested-by: .+ <[\w@.-]+>)", re.IGNORECASE),
/home/mchangir/work/ORIG-mchangir-ceph.git/./src/script/ptl-tool.py:221: SyntaxWarning: invalid escape sequence '\s'
comment = …
```

ptl-tool.py: replace regular strings with raw string literal for regular expressions

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/service.interface.ts

backport tracker: https://tracker.ceph.com/issues/67724
---
backport of https://github.com/ceph/ceph/pull/59332
parent tracker: https://tracker.ceph.com/issues/67223

squid: mgr/dashboard: Add group field in nvmeof service form

---

src/ceph-volume/ceph_volume/activate/main.py

Typical failure:
```
Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/ceph-authtool --gen-print-key
--> Failed to activate via raw: activate() takes 1 positional argument but 5 were given
Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/ceph-authtool --gen-print-key
--> Failed to activate via LVM: could not find osd.0 with osd_fsid 1e764f4a-db4b-4b41-86eb-468efe4c3f44
--> Failed to activate via simple: 'Namespace' object has no attribute 'json_config'
--> Failed to activate any OSD(s)
```
04c93a1ed42 seems to have broken it.
This commit fixes it.
Fixes: https://tracker.ceph.com/issues/67873

ceph-volume: fix generic activation with raw osds

---

qa/tasks/mgr/dashboard/test_mgr_module.py

This test deals with enabling/disabling the modules. The assumption I have is after enabling the
module, test will wait for an active mgr where dashboard runs but its not able to find it in time and it fails. so taking inspiration from https://github.com/ceph/ceph/pull/58995/commits/6c7253be6f6fbfa6faed7a539cb78847fec04580 adding retries and logs to see if that's the case
Fixes: https://tracker.ceph.com/issues/62972
- When filling …

qa/tests: fix test_list_enabled_modules timeout error

---

qa/suites/rgw/tempest/tasks/rgw_tempest.yaml
src/rgw/rgw_common.cc
src/rgw/rgw_common.h
src/rgw/rgw_op.cc
src/rgw/rgw_rest.cc
src/rgw/rgw_rest_swift.cc

backport tracker: https://tracker.ceph.com/issues/63620
----
backport of https://github.com/ceph/ceph/pull/50790
parent tracker: https://tracker.ceph.com/issues/51772 …

quincy: rgw/swift: preserve dashes/underscores in swift user metadata names

---

src/crimson/os/seastore/extent_placement_manager.cc
src/crimson/os/seastore/extent_placement_manager.h

This commit intens to write meraged-able ool extents, each of which is located at consecutive address, to the ool at once. …

crimson/os/seastore/rbm: write merge-able ool extents at once
