ceph/ceph

- src/common/TrackedOp.cc
Fixes: https://tracker.ceph.com/issues/66615 …
> squid: common/TrackedOp: do not count the ops marked as nowarn

- src/mds/Locker.cc
Fixes: https://tracker.ceph.com/issues/66666 …
> squid: mds: set the correct WRLOCK flag always in wrlock_force()

- qa/tasks/cephfs/test_scrub_checks.py
- src/mds/MDSRank.cc
Fixes: https://tracker.ceph.com/issues/66869 …
> squid: mds: prevent scrubbing for standby-replay MDS

- src/mds/FSMap.cc
- src/mds/MDCache.cc
- src/mds/MDSRank.cc
Fixes: https://tracker.ceph.com/issues/66774 …
> squid: mds: fix bug and error handling of mds STATE_STARTING

- src/pybind/mgr/volumes/fs/operations/clone_index.py
backport tracker: https://tracker.ceph.com/issues/66928
---
backport of https://github.com/ceph/ceph/pull/58101
parent tracker: https://tracker.ceph.com/issues/66560
> squid: mgr/vol: handle case where clone index entry goes missing

- src/pybind/mgr/volumes/fs/operations/clone_index.py
backport tracker: https://tracker.ceph.com/issues/66927
---
backport of https://github.com/ceph/ceph/pull/58101
parent tracker: https://tracker.ceph.com/issues/66560
> reef: mgr/vol: handle case where clone index entry goes missing

- src/tools/ceph_objectstore_tool.cc
Add missing error checks on open_collection. Before it caused too many seg faults on null collections.
before:
```bash
[pdiazbou@o08 build]$ bin/ceph-objectstore-tool --data-path ../build/dev/osd1 --op list-pgs
1.0s0
[pdiazbou@o08 build]$ 
[pdiazbou@o08 build]$ bin/ceph-objectstore-tool --data-path ../build/dev/osd1 --op list | grep benchmark_data_o08_2468610_object299
["1.0s0",{"oid":"benchmark_data_o08_2468610_object299","key":"","snapid":-2,"hash":1448370175,"max":0,"pool":1,"namespace":"","shard_id":0,"max":0}]
[pdiazbou@o08 build]$ ugdb -- bin/ceph-objectstore-tool --data-path ../build/dev/osd1 --pgid 1.0 benchmark_data_o08_2468610_object299 list-omap
[pdiazbou@o08 build]$ bin/ceph-objectstore-tool --data-path ../build/dev/osd1 --pgid 1.0 benchmark_data_o08_2468610_object299 …
```
> tools/objectstore: check for wrong coll open_collection

- qa/suites/rados/objectstore/backends/objectstore-bluestore-b.yaml
When FileStore was removed, numbering changed.
As the result, we completely disabled compression-relates bluestore tests. …
> teuthology/bluestore: Fix running of compressed tests

- doc/start/os-recommendations.rst
(cherry picked from commit 92b07ddece5f717454e5aeaa00ec70e5649539c0)
- Component …
> squid: doc/start/os-recommendations: remove 16.2.z support for CentOS 7

- doc/dev/developer_guide/basic-workflow.rst
Add an explanation of the "needs-upgrade-testing" label and explain when to use it.
Laura is the true author of this text. …
> doc/dev_guide: add needs-upgrade-testing label info

- qa/suites/upgrade/quincy-x/filestore-remove-check/1-ceph-install/quincy.yaml
- qa/suites/upgrade/quincy-x/parallel/0-start.yaml
- qa/suites/upgrade/quincy-x/stress-split/1-start.yaml
Our upgared suites failed beacuse of those warning without good reason, we can ignore them and continue testings.
Fixes: https://tracker.ceph.com/issues/65422 …
> suites/upgrade/quincy-x: update the ignore list

- qa/tasks/thrashosds-health.yaml
The current ignore-list have \(SLOW_OPS\)  but missing SLOW_OPS
Fixes: https://tracker.ceph.com/issues/66604
- …
> suites: thrash old client missing SLOW_OPS in the ignore-list

- doc/dev/developer_guide/basic-workflow.rst
Add an explanation of the "needs-upgrade-testing" label and explain when to use it.
Laura is the true author of this text.
(cherry picked from commit 02d5a6a3371c9fa52a32124cf07da16b89a11e27) …
> squid: doc/dev_guide: add needs-upgrade-testing label info

- doc/dev/developer_guide/basic-workflow.rst
Add an explanation of the "needs-upgrade-testing" label and explain when to use it.
Laura is the true author of this text.
(cherry picked from commit 02d5a6a3371c9fa52a32124cf07da16b89a11e27) …
> reef: doc/dev_guide: add needs-upgrade-testing label info

- doc/dev/developer_guide/basic-workflow.rst
Add an explanation of the "needs-upgrade-testing" label and explain when to use it.
Laura is the true author of this text.
(cherry picked from commit 02d5a6a3371c9fa52a32124cf07da16b89a11e27) …
> quincy: doc/dev_guide: add needs-upgrade-testing label info

- src/blk/kernel/io_uring.cc
See https://github.com/ceph/ceph/pull/56352 …
> blk/aio: fix compile issue when HAVE_LIBURING isn't defined

- src/cephadm/cephadmlib/templating.py
Backport of https://github.com/ceph/ceph/pull/58321
<details>
</details>
> squid: cephadm: make cephadm compatible with jinja2 2.11.3

- PendingReleaseNotes
- doc/man/8/rbd.rst
- qa/workunits/rbd/rbd_groups.sh
- src/include/rbd/librbd.h
- src/include/rbd/librbd.hpp
- src/librbd/api/Group.cc
- src/librbd/api/Group.h
- src/librbd/librbd.cc
- src/pybind/rbd/c_rbd.pxd
- src/pybind/rbd/mock_rbd.pxi
- src/pybind/rbd/rbd.pyx
- src/test/cli/rbd/help.t
- src/test/librbd/test_Groups.cc
- src/test/pybind/test_rbd.py
- src/tools/rbd/action/Group.cc
See https://github.com/ceph/ceph/pull/57797#issuecomment-2233172495 for example outputs …
> rbd: add `group snap info` command

- src/tools/cephfs/shell/cephfs-shell
cephfs-shell: excute cmd 'rmdir_helper' reported error
Fixes: https://tracker.ceph.com/issues/66735
Signed-off-by: teng jie <tengjie5@asiainfo.com> …
> cephfs-shell: excute cmd 'rmdir_helper' reported error

- qa/cephfs/overrides/ignorelist_health.yaml
Fixes: https://tracker.ceph.com/issues/66612 …
> qa/cephfs: ignore variant of MDS_UP_LESS_THAN_MAX

- src/rgw/rgw_rest_role.cc
when issued against a secondary zone in multisite, the CreateRole request is first forwarded to the metadata master zone and created there
once that forwarded request succeeds, the secondary zone creates the same role. between these two events, metadata sync may race to replicate that role from the master. this causes the local role creation to fail with EEXIST
ignore EEXIST errors from local role creation if we know that our forwarded request succeeded
Fixes: https://tracker.ceph.com/issues/67012
<details>
- …
> rgw/iam: CreateRole ignores EEXIST after forwarded request

- doc/dev/crimson/crimson.rst
Signed-off-by: gitkenan <kenan.mth@gmail.com>
(cherry picked from commit 92fea64c1f28a010336b3696863d3f003cd684ef) …
> squid: doc/dev/crimson: clarify and rearrange for userability

- doc/cephfs/index.rst
Streamline a paragraph in doc/cephfs/index.rst. …
> doc/cephfs: streamline a paragraph

- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.e2e.spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-form/rgw-multisite-sync-policy-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-form/rgw-multisite-sync-policy-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-tabs/rgw-multisite-tabs.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-tabs/rgw-multisite-tabs.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-tabs/rgw-multisite-tabs.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
backport tracker: https://tracker.ceph.com/issues/67046
backport of: #58656
Parent tracker: https://tracker.ceph.com/issues/66977
(cherry picked from commit ca4759b8f48fc62ff61fd290657586abd75c293c)
Conflicts:
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html (replaced nav tabs with multisite tabs component & removed Multisite replication options dialog)
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts (removed qizard component imports) 
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.ts (file not needed in backporting) …
> squid: mgr/dashboard: rgw sync policy routing fixes

- qa/distros/container-hosts/centos_9.stream.yaml
Fixes: http://tracker.ceph.com/issues/66640 …
> qa: ignore container checkpoint/restore related selinux denials for container-hosts/centos9

- doc/cephfs/index.rst
Streamline a paragraph in doc/cephfs/index.rst.
(cherry picked from commit 820f8ead8919483df37c751400bd6842d4c1bd92) …
> squid: doc/cephfs: streamline a paragraph

- doc/cephfs/index.rst
Streamline a paragraph in doc/cephfs/index.rst.
(cherry picked from commit 820f8ead8919483df37c751400bd6842d4c1bd92) …
> reef: doc/cephfs: streamline a paragraph

- doc/cephfs/index.rst
Streamline a paragraph in doc/cephfs/index.rst.
(cherry picked from commit 820f8ead8919483df37c751400bd6842d4c1bd92) …
> quincy: doc/cephfs: streamline a paragraph

- doc/cephadm/services/osd.rst
Backport of https://github.com/ceph/ceph/pull/56177
- …
> quincy: doc: cephadm/services/osd: fix typo

- doc/rbd/rbd-exclusive-locks.rst
This is due to both using the same name for the lock at the RADOS level ("rbd_lock"). …
> doc/rbd/rbd-exclusive-locks: mention incompatibility with advisory locks

- doc/rbd/rbd-exclusive-locks.rst
This is due to both using the same name for the lock at the RADOS level ("rbd_lock").
(cherry picked from commit 2e83b77c9f610f42765266ff4d4d7bc2a635eac8) …
> squid: doc/rbd/rbd-exclusive-locks: mention incompatibility with advisory locks

- doc/rbd/rbd-exclusive-locks.rst
This is due to both using the same name for the lock at the RADOS level ("rbd_lock").
(cherry picked from commit 2e83b77c9f610f42765266ff4d4d7bc2a635eac8) …
> quincy: doc/rbd/rbd-exclusive-locks: mention incompatibility with advisory locks

- doc/rbd/rbd-exclusive-locks.rst
This is due to both using the same name for the lock at the RADOS level ("rbd_lock").
(cherry picked from commit 2e83b77c9f610f42765266ff4d4d7bc2a635eac8) …
> reef: doc/rbd/rbd-exclusive-locks: mention incompatibility with advisory locks

- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.e2e-spec.ts
backport tracker: https://tracker.ceph.com/issues/67104
backport of: #58710
parent tracker: https://tracker.ceph.com/issues/67070 …
> squid: mgr/dashboard: multisite e2e test case fix

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster.component.ts
backport tracker: https://tracker.ceph.com/issues/67168
backport of: #58716
parent tracker: https://tracker.ceph.com/issues/67074
(cherry picked from commit 6241be164dc1f764b66bf63ca4e42a4f3931c07a) …
> squid: mgr/dashboard: expand-cluster back navigation fix

- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/identity/identity.component.html
Fixes: https://tracker.ceph.com/issues/67075 
Signed-off-by: Prachi <prgoel@redhat.com> …
> mgr/dashboard: Changes for Sign out text to Login out

- doc/radosgw/qat-accel.rst
Update out-of-tree driver CMake options and add QATlib information
tracker: https://tracker.ceph.com/issues/66879
- …
> doc/radosgw/qat-accel: Update and Add QATlib information

- doc/cephfs/client-auth.rst
Fix a broken link to the "File Layouts" page on
doc/cephfs/client-auth.rst.
Fixes: https://tracker.ceph.com/issues/67190 …
> doc/cephfs: fix "file layouts" link

- qa/suites/rados/dashboard/tasks/e2e.yaml
Fixes: https://tracker.ceph.com/issues/64870 …
> suites: test should ignore osd_down warnings

- src/rgw/rgw_rest_role.cc
backport tracker: https://tracker.ceph.com/issues/67098
---
backport of https://github.com/ceph/ceph/pull/58665
parent tracker: https://tracker.ceph.com/issues/67012
> squid: rgw/iam: CreateRole ignores EEXIST after forwarded request

- doc/cephfs/client-auth.rst
Fix a broken link to the "File Layouts" page on
doc/cephfs/client-auth.rst.
Fixes: https://tracker.ceph.com/issues/67190
(cherry picked from commit 6bb5ce94c6a2cbfdf978a66d00f428ad4cd4c312) …
> quincy: doc/cephfs: fix "file layouts" link

- doc/cephfs/client-auth.rst
Fix a broken link to the "File Layouts" page on
doc/cephfs/client-auth.rst.
Fixes: https://tracker.ceph.com/issues/67190
(cherry picked from commit 6bb5ce94c6a2cbfdf978a66d00f428ad4cd4c312) …
> reef: doc/cephfs: fix "file layouts" link

- doc/cephfs/client-auth.rst
Fix a broken link to the "File Layouts" page on
doc/cephfs/client-auth.rst.
Fixes: https://tracker.ceph.com/issues/67190
(cherry picked from commit 6bb5ce94c6a2cbfdf978a66d00f428ad4cd4c312) …
> squid: doc/cephfs: fix "file layouts" link

- src/crimson/osd/scrub/scrub_validator.cc
Fixes: https://tracker.ceph.com/issues/66405 …
> src/crimson/osd/scrub: fix the null pointer error

- src/crimson/osd/pg_recovery.cc
Fixes: https://tracker.ceph.com/issues/66885 …
> crimson/osd/pg_recovery: push the iteration forward after finding unfound objects when starting primary recoveries

- qa/config/crimson_qa_overrides.yaml
- src/crimson/mgr/client.cc
During the connection's lifecycle, it can be reset and set to nullptr by other functions.
We need to verify that the connection is still available before attempting to send data.
Fixes: https://tracker.ceph.com/issues/62162 …
> mgr/client: validate connection before sending

- src/crimson/osd/pg_backend.h
- src/crimson/osd/recovery_backend.cc
- src/crimson/osd/recovery_backend.h
All temp objects are added to PGBackend::temp_contents, cleaning RecoveryBackend::temp_contents is wrong …
> crimson/osd/recovery_backend: cleanup PGBackend::temp_contents when pg interval changes

- doc/cephfs/client-auth.rst
Fix a broken link from the "OSD capabilites" reference on doc/cephfs/client-auth.rst.
Fixes: https://tracker.ceph.com/issues/67218 …
> doc/cephfs: fix "OSD capabilities" link

- doc/cephfs/client-auth.rst
Fix a broken link from the "OSD capabilites" reference on doc/cephfs/client-auth.rst.
Fixes: https://tracker.ceph.com/issues/67218
(cherry picked from commit 74b03a8cb2f196171b10d8cbde27324240649e70) …
> squid: doc/cephfs: fix "OSD capabilities" link

- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
> os/bluestore: remove not used zone_adjustments

- src/crimson/osd/osd_operations/client_request.cc
backport of https://github.com/ceph/ceph/pull/57367
> squid: crimson/osd/osd_operations/client_request: check "can_serve_replica_reads" before getting obc

- src/crimson/osd/object_context.h
backport of https://github.com/ceph/ceph/pull/58099
> squid: crimson: fix ObjectContext::_with_lock to only unlock if lock is taken

- doc/dev/release-process.rst
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>
(cherry picked from commit 8761bbe16c2a6d19e136254c26d1d67ebe839e3b) …
> reef: docs: removed centos 8 and added squid to the build matrix

- doc/dev/release-process.rst
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>
(cherry picked from commit 8761bbe16c2a6d19e136254c26d1d67ebe839e3b) …
> squid: docs: removed centos 8 and added squid to the build matrix

- qa/workunits/rbd/luks-encryption.sh
backport tracker: https://tracker.ceph.com/issues/67060
---
backport of https://github.com/ceph/ceph/pull/58688
parent tracker: https://tracker.ceph.com/issues/67051
> squid: qa/workunits/rbd: avoid caching effects in luks-encryption.sh

- doc/cephfs/multimds.rst
Edit the section "Dynamic Subtree Partitioning" in doc/cephfs/multimds.rst.
(cherry picked from commit d14119e37e01bd06eed668d9e3606a66ef205b30) …
> squid: doc/cephfs: edit "Dynamic Subtree Partitioning"

- doc/cephfs/multimds.rst
Edit the section "Dynamic Subtree Partitioning" in doc/cephfs/multimds.rst.
(cherry picked from commit d14119e37e01bd06eed668d9e3606a66ef205b30) …
> reef: doc/cephfs: edit "Dynamic Subtree Partitioning"

- qa/suites/fs/functional/tasks/admin.yaml
Fixes: http://tracker.ceph.com/issues/66639 …
> qa: some test set `refuse_client_session`, so the cluster log is expected

- src/test/objectstore/allocsim/ops_replayer.cc
> test/allocsim: Replayer merge files

- src/test/objectstore/allocsim/ops_replayer.cc
remake of https://github.com/ceph/ceph/pull/58426 so we can run make check again
- …
> test/allocsim: faster parser

- src/common/options/global.yaml.in
- src/compressor/QatAccel.cc
- src/compressor/QatAccel.h
- src/compressor/zlib/ZlibCompressor.cc
- src/rgw/driver/daos/rgw_sal_daos.cc
- src/rgw/driver/motr/rgw_sal_motr.cc
- src/rgw/driver/rados/rgw_sal_rados.cc
- src/rgw/rgw_file.cc
- src/rgw/rgw_op.cc
backport tracker:  https://tracker.ceph.com/issues/66878
---------------
backport of https://github.com/ceph/ceph/pull/58046 …
> Squid Compressor: Add data format(QZ_DEFLATE_GZIP_EXT) for QAT Zlib

- src/common/ceph_strings.cc
- src/osd/OSDMap.cc
This is squid backport of #57776.
Backport tracker: https://tracker.ceph.com/issues/66298.
Parent tracker: https://tracker.ceph.com/issues/61948. …
> squid: mon, osd, *: expose upmap-primary in OSDMap::get_features()

- doc/dev/developer_guide/basic-workflow.rst
- doc/dev/developer_guide/essentials.rst
- doc/dev/developer_guide/tests-unit-tests.rst
Make various improvements to doc/dev/developer_guide/basic-workflow.rst.
- …
> doc/dev: improve basic-workflow.rst

- doc/cephadm/services/monitoring.rst
Edit the section "Using Custom Images" in
doc/cephadm/services/monitoring.rst.
- …
> doc/cephadm: edit "Using Custom Images"

- doc/glossary.rst
- doc/man/8/ceph-fuse.rst
Add a "ceph-fuse" entry to the glossary. …
> doc/glossary: add "ceph-fuse" entry

- doc/dev/developer_guide/basic-workflow.rst
- doc/dev/developer_guide/essentials.rst
- doc/dev/developer_guide/tests-unit-tests.rst
Make various improvements to doc/dev/developer_guide/basic-workflow.rst.
(cherry picked from commit b81d6af1b488cdb87143e13da519d70c3a090679) …
> squid: doc/dev: improve basic-workflow.rst

- doc/dev/developer_guide/basic-workflow.rst
- doc/dev/developer_guide/essentials.rst
- doc/dev/developer_guide/tests-unit-tests.rst
Make various improvements to doc/dev/developer_guide/basic-workflow.rst.
(cherry picked from commit b81d6af1b488cdb87143e13da519d70c3a090679) …
> reef: doc/dev: improve basic-workflow.rst

- doc/dev/developer_guide/basic-workflow.rst
- doc/dev/developer_guide/essentials.rst
- doc/dev/developer_guide/tests-unit-tests.rst
Make various improvements to doc/dev/developer_guide/basic-workflow.rst.
(cherry picked from commit b81d6af1b488cdb87143e13da519d70c3a090679) …
> quincy: doc/dev: improve basic-workflow.rst

- doc/glossary.rst
- doc/man/8/ceph-fuse.rst
Add a "ceph-fuse" entry to the glossary.
(cherry picked from commit d1c049d24befedc396221dafcc66db8c40acf5ab) …
> squid: doc/glossary: add "ceph-fuse" entry

- doc/glossary.rst
- doc/man/8/ceph-fuse.rst
Add a "ceph-fuse" entry to the glossary.
(cherry picked from commit d1c049d24befedc396221dafcc66db8c40acf5ab) …
> reef: doc/glossary: add "ceph-fuse" entry

- doc/glossary.rst
- doc/man/8/ceph-fuse.rst
Add a "ceph-fuse" entry to the glossary.
(cherry picked from commit d1c049d24befedc396221dafcc66db8c40acf5ab) …
> quincy: doc/glossary: add "ceph-fuse" entry

- doc/cephadm/services/monitoring.rst
Edit the section "Using Custom Images" in
doc/cephadm/services/monitoring.rst.
(cherry picked from commit e99fc5c82fd698c222a489a1ebc26c8fcbca321d) …
> reef: doc/cephadm: edit "Using Custom Images"

- doc/cephadm/services/monitoring.rst
Edit the section "Using Custom Images" in
doc/cephadm/services/monitoring.rst.
(cherry picked from commit e99fc5c82fd698c222a489a1ebc26c8fcbca321d) …
> quincy: doc/cephadm: edit "Using Custom Images"

- src/mon/OSDMonitor.cc
Fixes: https://tracker.ceph.com/issues/66329 …
> mon: validate also mons and osds on {rm-,}pg-upmap-primary

- src/common/TrackedOp.cc
- src/common/TrackedOp.h
1. TrackedOp is a common class, mon and mds alse use it.
2. Set prio level of l_trackedop_slow_op_count to PRIO_USEFUL, we can get change of slow op of daemon from prometheus metrics, it's very interesting
<details> …
> common/TrackedOp: rename and raise prio of slow op perfcounter

- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/test/objectstore/store_test.cc
> test/store_test: get rid off explicit offset specifications in shared

- doc/radosgw/placement.rst
Change ``GLACIER`` in the storage class example so that users of certain clients and libraries do not experience unexpected behavior. …
> doc: Improve doc/radosgw/placement.rst

- doc/glossary.rst
Add a glossary entry for "Prometheus". …
> doc/glossary: add "Prometheus"

- doc/radosgw/placement.rst
(cherry picked from commit 5890a156524b8d1fe3a51ea1c76d800e5903a01c) …
> quincy: doc: Improve doc/radosgw/placement.rst

- doc/radosgw/placement.rst
(cherry picked from commit 5890a156524b8d1fe3a51ea1c76d800e5903a01c) …
> reef: doc: Improve doc/radosgw/placement.rst

- doc/radosgw/placement.rst
(cherry picked from commit 5890a156524b8d1fe3a51ea1c76d800e5903a01c) …
> squid: doc: Improve doc/radosgw/placement.rst

- doc/glossary.rst
Add a glossary entry for "Prometheus".
(cherry picked from commit 1a76464999cb2d2cc748d69e1bb0567544a0bb8b) …
> reef: doc/glossary: add "Prometheus"

- doc/glossary.rst
Add a glossary entry for "Prometheus".
(cherry picked from commit 1a76464999cb2d2cc748d69e1bb0567544a0bb8b) …
> quincy: doc/glossary: add "Prometheus"

- src/test/rgw/bucket_notification/test_bn.py
By polling on the bucket objects until empty, we make sure that we don't check for notification until we are sure that we should be receiving notifications about objects deletion …
> RGW|BN: fix lifecycle test issue

- qa/erasure-code/ec-rados-plugin=jerasure-k=2-m=2-crush.yaml
- qa/erasure-code/ec-rados-plugin=jerasure-k=8-m=6-crush.yaml
- qa/suites/rados/thrash-erasure-code-crush-4-nodes/clusters
roles being set without overrides causing too many values to unpack (expected 1)
Fixes: https://tracker.ceph.com/issues/66209 …
> suites/ec-rados-plugin=jerasure-k=8-m=6-crush: roles set with overrides

- src/mon/OSDMonitor.cc
> mon/osdmonitor: cleanup the code for preprocess_mark_me_dead

- src/ceph-volume/ceph_volume/devices/lvm/migrate.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_migrate.py
backport tracker: https://tracker.ceph.com/issues/66448
---
backport of https://github.com/ceph/ceph/pull/57807
parent tracker: https://tracker.ceph.com/issues/66315
> squid: ceph-volume: do source devices zapping if they're detached.

- src/pybind/mgr/cephadm/services/nvmeof.py
- src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
- src/pybind/mgr/cephadm/tests/test_services.py
- src/python-common/ceph/deployment/service_spec.py
mgr/cephadm: add SPDK log level to nvmeof configuration
python-common/ceph/deployment: add SPDK log level to nvmeof configuration
Fixes [https://tracker.ceph.com/issues/67258](https://tracker.ceph.com/issues/67258) …
> mgr/cephadm: Add SPDK log level to nvmeof configuration file

- doc/radosgw/qat-accel.rst
Signed-off-by: Feng, Hualong <hualong.feng@intel.com>
(cherry picked from commit 98723d51b969041a672d505a26d4e0a8df4115d3) …
> squid: doc/radosgw/qat-accel: Update and Add QATlib information

- doc/glossary.rst
Add a "ceph-ansible" entry to the glossary. …
> doc/glossary: add "ceph-ansible"

- doc/glossary.rst
Add a "ceph-ansible" entry to the glossary.
(cherry picked from commit 484e9d2b9d81b6de498ac08125c9a458730dd444) …
> squid: doc/glossary: add "ceph-ansible"

- doc/glossary.rst
Add a "ceph-ansible" entry to the glossary.
(cherry picked from commit 484e9d2b9d81b6de498ac08125c9a458730dd444) …
> reef: doc/glossary: add "ceph-ansible"

- doc/glossary.rst
Add a "ceph-ansible" entry to the glossary.
(cherry picked from commit 484e9d2b9d81b6de498ac08125c9a458730dd444) …
> quincy: doc/glossary: add "ceph-ansible"

- src/kv/RocksDBStore.cc
- Added the function of printing all cf's rocksdb level information.
- Currently, only the default cf information is printed.
- Print all cf information to facilitate observation of the level to which rocksdb is written.
- The main purpose is to observe the usage of db/ssd.
co-author: Jrchyang Yu <yuzhiqiang_yewu@cmss.chinamobile.com>
Signed-off-by: Wang Linke <wanglinke_yewu@cmss.chinamobile.com> …
> kv/RocksDBStore: add kv_stats function to print all CF info

- src/tools/cephfs/shell/cephfs-shell
backport tracker: https://tracker.ceph.com/issues/67113
---
backport of https://github.com/ceph/ceph/pull/58327
parent tracker: https://tracker.ceph.com/issues/66735 …
> squid: cephfs-shell: excute cmd 'rmdir_helper' reported error

- src/mds/CInode.cc
- src/mds/CInode.h
- src/mds/Locker.cc
- src/mds/MDCache.cc
Backport of https://github.com/ceph/ceph/pull/55914
Backport tracker: https://tracker.ceph.com/issues/65316
Parent tracker: https://tracker.ceph.com/issues/64008 …
> squid: mds: CInode::item_caps used in two different lists

- src/rgw/rgw_amqp.cc
Revert https://github.com/ceph/ceph/pull/58715 until qa passed. …
> Revert "reef: rgw/amqp: lock erase and create connection before emplace"

- doc/cephfs/file-layouts.rst
Improve the English in the "Layout Fields" section of doc/cephfs/file-layouts.rst. …
> doc/cephfs: edit "Layout Fields" text

- qa/tasks/ceph.py
Fixes: https://tracker.ceph.com/issues/10797 …
> qa: ceph.py mkfs.ext4 has no -f

- doc/mgr/dashboard.rst
Change "SSL/TSL" to "SSL/TLS"
Signed-off-by: Mindy Preston <mcpreston@icecube.wisc.edu>
> doc/mgr/dashboard: fix TLS typo

- doc/mgr/dashboard.rst
Change "SSL/TSL" to "SSL/TLS"
Signed-off-by: Mindy Preston <mcpreston@icecube.wisc.edu>
(cherry picked from commit e63b967aeb00a667ab5c91b9b526c7a19a9539ec) …
> quincy: doc/mgr/dashboard: fix TLS typo

- doc/mgr/dashboard.rst
Change "SSL/TSL" to "SSL/TLS"
Signed-off-by: Mindy Preston <mcpreston@icecube.wisc.edu>
(cherry picked from commit e63b967aeb00a667ab5c91b9b526c7a19a9539ec) …
> reef: doc/mgr/dashboard: fix TLS typo

- doc/mgr/dashboard.rst
Change "SSL/TSL" to "SSL/TLS"
Signed-off-by: Mindy Preston <mcpreston@icecube.wisc.edu>
(cherry picked from commit e63b967aeb00a667ab5c91b9b526c7a19a9539ec) …
> squid: doc/mgr/dashboard: fix TLS typo

- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.scss
https://github.com/user-attachments/assets/c721406e-464d-4580-87c4-9fb5727ab35c
Fixes: https://tracker.ceph.com/issues/67069 …
> mgr/dashboard: make multi-cluster context switcher scrollable if we have many entries in it

- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.ts
Add undefined checks wherever necessary to the updateChartData method in dashboard-area-chart component
Fixes: https://tracker.ceph.com/issues/67009 …
> mgr/dashboard: Dashboard not showing Object/Overview correctly.

- qa/suites/rados/objectstore/backends/objectstore-bluestore-a.yaml
- qa/suites/rados/objectstore/backends/objectstore-bluestore-b.yaml
- qa/suites/rados/objectstore/backends/objectstore-memstore.yaml
- qa/suites/rados/perf/objectstore/bluestore-basic-min-osd-mem-target.yaml
- qa/suites/rados/perf/objectstore/bluestore-bitmap.yaml
- qa/suites/rados/perf/objectstore/bluestore-comp.yaml
- qa/suites/rados/perf/objectstore/bluestore-low-osd-mem-target.yaml
- qa/suites/rados/perf/objectstore/bluestore-stupid.yaml
Having debug 20 is impractical. Slows down execution and takes disk space, but gives little help in eventual debugging. …
> qa/suites/rados: Reduced BlueStore log levels

- README.md
Add ordered-list formatting to the "Building Ceph" section of README.md.
- …
> doc/README.md - add ordered list

- src/rgw/rgw_common.cc
- src/rgw/rgw_common.h
- src/rgw/rgw_iam_policy.cc
- src/rgw/rgw_string.cc
- src/rgw/rgw_string.h
- src/test/rgw/test_rgw_iam_policy.cc
Fixes: https://tracker.ceph.com/issues/62292
(cherry picked from commit 94fa9bd2d90857ca2c6a956a79406318ab2fa485)
Fixes: https://tracker.ceph.com/issues/63972 …
> quincy: rgw: modify string match_wildcards with fnmatch

- src/rgw/driver/posix/zpp_bits.h
zpp_bits included code that required a newere compiler.  Pull in the upstream fix from:
https://github.com/eyalz800/zpp_bits/pull/170
Fixes: https://tracker.ceph.com/issues/67321 …
> RGW - Zipper: pull in upstream fix for zpp_bits

- src/crimson/osd/osd_operations/background_recovery.cc
- src/crimson/osd/osd_operations/client_request.cc
- src/crimson/osd/osd_operations/client_request_common.cc
- src/crimson/osd/osd_operations/client_request_common.h
- src/crimson/osd/osd_operations/internal_client_request.cc
- src/crimson/osd/pg_recovery.cc
- src/crimson/osd/recovery_backend.cc
- src/crimson/osd/recovery_backend.h
Fixes: https://tracker.ceph.com/issues/65696 …
> crimson/osd/osd_operations: hang requests if the objects are unfound

- src/crimson/osd/osd_operations/client_request.cc
This avoids the possible destructions of client requests during the iteration of ClientRequest::Orderer::list
Fixes: https://tracker.ceph.com/issues/67068 …
> crimson/osd/osd_operation/client_request: requeue client requests from a temporary queue other than ClientRequest::Orderer::list

- src/os/bluestore/BlueStore.cc
- src/test/objectstore/store_test.cc
- src/tools/ceph_objectstore_tool.cc
> os/bluestore: assert CollectionRef count is 1 on umount

- src/mds/MDCache.cc
> mds: remove the misleading and redundant logs

- src/mds/MDSDaemon.cc
- src/mds/MDSDaemon.h
- src/mgr/DaemonServer.cc
- src/mgr/DaemonServer.h
- src/mon/MonClient.cc
- src/mon/Monitor.cc
- src/mon/Monitor.h
- src/msg/Dispatcher.h
- src/osd/OSD.cc
- src/osd/OSD.h
- src/test/fio/fio_ceph_messenger.cc
- src/test/msgr/perf_msgr_client.cc
- src/test/msgr/perf_msgr_server.cc
- src/test/msgr/test_msgr.cc
Fixes: https://tracker.ceph.com/issues/62382
<details>
- …
> mon/MonClient: handle ms_handle_fast_authentication return

- doc/dev/peering.rst
This commit updates the peering doc page with the changed [2,1,2] to [3,1,2]
Signed-off-by: qn2060 <qn2060@users.noreply.github.com>
(cherry picked from commit 103d65ea6787ab16d1824f71578264e0abb9820c) …
> quincy: doc/dev/peering: Change acting set num

- doc/dev/peering.rst
This commit updates the peering doc page with the changed [2,1,2] to [3,1,2]
Signed-off-by: qn2060 <qn2060@users.noreply.github.com>
(cherry picked from commit 103d65ea6787ab16d1824f71578264e0abb9820c) …
> squid: doc/dev/peering: Change acting set num

- doc/dev/peering.rst
This commit updates the peering doc page with the changed [2,1,2] to [3,1,2]
Signed-off-by: qn2060 <qn2060@users.noreply.github.com>
(cherry picked from commit 103d65ea6787ab16d1824f71578264e0abb9820c) …
> reef: doc/dev/peering: Change acting set num

- src/client/Client.cc
- src/client/Client.h
> client: eliminate duplicate lookups wherever possible

- doc/cephfs/cephfs-mirroring.rst
- qa/tasks/cephfs/test_mirroring.py
- src/tools/cephfs_mirror/PeerReplayer.cc
- src/tools/cephfs_mirror/PeerReplayer.h
Fixes: https://tracker.ceph.com/issues/65171
Fixes: https://tracker.ceph.com/issues/64483
Fixes: https://tracker.ceph.com/issues/65629 …
> cephfs_mirror: provide metrics for last successful snapshot sync

- src/ceph-volume/ceph_volume/devices/lvm/migrate.py
backport tracker: https://tracker.ceph.com/issues/66446
---
backport of https://github.com/ceph/ceph/pull/57807
parent tracker: https://tracker.ceph.com/issues/66315
> reef: ceph-volume: do source devices zapping if they're detached.

- src/crimson/osd/pg.cc
- src/crimson/osd/pg.h
- src/crimson/osd/pg_shard_manager.cc
> crimson/osd: clear ondisk temp objects on startup

- qa/clusters/2-node-mgr.yaml
- qa/clusters/extra-client.yaml
- qa/clusters/fixed-1.yaml
- qa/clusters/fixed-2.yaml
- qa/clusters/fixed-3-cephfs.yaml
- qa/clusters/fixed-3.yaml
- qa/clusters/fixed-4.yaml
- qa/suites/rados/thrash/workloads/rados_api_tests.yaml
- qa/suites/rados/verify/tasks/rados_api_tests.yaml
and avoid errors when "clusternodes" is not defined.
Fixes: https://tracker.ceph.com/issues/67352 …
> qa: simplify postmerge construction

- src/crimson/os/seastore/lba_manager/btree/lba_btree_node.cc
> crimson/os/seastore/lba_manager: correct the range end of lba mappings

- src/osd/OSD.cc
Parent tracker: https://tracker.ceph.com/issues/61140
Backport of: https://github.com/ceph/ceph/pull/53530
Backport tracker: https://tracker.ceph.com/issues/63527
(cherry picked from commit f004def5b7cb8aa31e7f428f5be9bcf1aee2f30c) …
> reef: osd: do not assert on fast shutdown timeout

- src/os/bluestore/BlueFS.cc
- src/os/bluestore/BlueFS.h
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/test/objectstore/store_test.cc
Parent tracker: https://tracker.ceph.com/issues/62401
Backport of: https://github.com/ceph/ceph/pull/54102
Backport tracker: https://tracker.ceph.com/issues/63812 …
> reef: test/store_test: refactor spillover tests

- src/mds/Locker.cc
For example:
2024-07-22T21:48:18.372+0000 7f4751a3d700  7 mds.6.server dispatch_client_request client_request(client.4748:62187 create owner_uid=1000, owner_gid=1000 #0x1000000148d/file.mdtest.145.31073 2024-07-22T21:48:18.371416+0000 caller_uid=1000, caller_gid=1000{})
2024-07-22T21:48:18.372+0000 7f4751a3d700  7 mds.6.server open w/ O_CREAT on #0x1000000148d/file.mdtest.145.31073
2024-07-22T21:48:18.372+0000 7f4751a3d700 10 mds.6.server rdlock_path_xlock_dentry request(client.4748:62187 nref=2 cr=0x55649752bc00) #0x1000000148d/file.mdtest.145.31073
2024-07-22T21:48:18.372+0000 7f4751a3d700  7 mds.6.cache traverse: opening base ino 0x1000000148d snap head
2024-07-22T21:48:18.372+0000 7f4751a3d700 10 mds.6.locker try_rdlock_snap_layout request(client.4748:62187 nref=3 cr=0x55649752bc00) …
> mds: only authpin on wrlock when not a locallock

- src/rgw/driver/rados/rgw_gc.cc
backport tracker: https://tracker.ceph.com/issues/66580
---
backport of https://github.com/ceph/ceph/pull/54661
parent tracker: https://tracker.ceph.com/issues/66579
> reef: rgw: optimize gc chain size calculation

- qa/suites/rados/dashboard/tasks/e2e.yaml
Eventually, the PG_DEGRADED warning goes away and cluster goes back to healthy state before the end of the test
Fixes: https://tracker.ceph.com/issues/66922 …
> qa/rados/dashboard: Add PG_DEGRADED to ignorelist

- doc/rados/operations/stretch-mode.rst
**Problem:**
Currently, stretch mode doesn't support device class, however, it was never
mentioned in the document
**Solution:**
Mention this in the document.
Fixes: https://tracker.ceph.com/issues/64817 …
> docs/rados/operations/stretch-mode: warn device class is not supported

- doc/rados/operations/stretch-mode.rst
Signed-off-by: Kamoltat Sirivadhna <ksirivad@redhat.com>
(cherry picked from commit aa1d8cf4fa321e24e850bd5f687a6ddad3ce05e3) …
> squid: docs/rados/operations/stretch-mode: warn device class is not supported

- doc/rados/operations/stretch-mode.rst
Signed-off-by: Kamoltat Sirivadhna <ksirivad@redhat.com>
(cherry picked from commit aa1d8cf4fa321e24e850bd5f687a6ddad3ce05e3) …
> reef: docs/rados/operations/stretch-mode: warn device class is not supported

- doc/rados/operations/stretch-mode.rst
Signed-off-by: Kamoltat Sirivadhna <ksirivad@redhat.com>
(cherry picked from commit aa1d8cf4fa321e24e850bd5f687a6ddad3ce05e3) …
> quincy: docs/rados/operations/stretch-mode: warn device class is not supported

- qa/workunits/fs/snaps/snaptest-git-ceph.sh
backport tracker: https://tracker.ceph.com/issues/62867
---
backport of https://github.com/ceph/ceph/pull/53175
parent tracker: https://tracker.ceph.com/issues/59413
<details> …
> quincy: qa: increase the http postBuffer size and disable sslVerify

- qa/tasks/cephfs/xfstests_dev.py
backport tracker: https://tracker.ceph.com/issues/62513
---
backport of https://github.com/ceph/ceph/pull/52741
parent tracker: https://tracker.ceph.com/issues/62277
<details> …
> quincy: qa/cephfs: switch to python3 for centos stream 9

- src/script/backport-create-issue
> script/backport-create-issue: add debug messages for retry

- src/rgw/rgw_sync_module_aws.cc
This fixes the following issues:
https://tracker.ceph.com/issues/57306
rgw: cloud sync crash
https://tracker.ceph.com/issues/57307
rgw: cloud sync: target objects are not created correctly
Signed-off-by: RaminNietzsche [Ramin.Najarbashi@gmail.com](mailto:Ramin.Najarbashi@gmail.com)
- Tracker
- Tests
<details>
- …
> cloud sync: fix crash due to objs on cr stack

- src/rgw/rgw_common.cc
- src/rgw/rgw_common.h
- src/rgw/rgw_iam_policy.cc
- src/rgw/rgw_string.cc
- src/rgw/rgw_string.h
- src/test/rgw/test_rgw_iam_policy.cc
Fixes: https://tracker.ceph.com/issues/62292
(cherry picked from commit 94fa9bd2d90857ca2c6a956a79406318ab2fa485)
https://tracker.ceph.com/issues/63971 …
> reef: rgw: modify string match_wildcards with fnmatch

- qa/tasks/thrashosds-health.yaml
RADOS main suite has been failing due to
a lack of whitelisting for
`noscrub` and `nodeep-scrub`
Backporting relevant commits from main PR(s):
https://github.com/ceph/ceph/pull/58374
backport tracker: https://tracker.ceph.com/issues/66984
Fixes: https://tracker.ceph.com/issues/65824
Signed-off-by: Kamoltat <ksirivad@redhat.com> …
> squid: qa/suites/rados/thrash-old-clients: Add noscrub, nodeep-scrub to ignorelist

- src/mon/NVMeofGwMap.cc
- src/mon/NVMeofGwMap.h
- src/mon/NVMeofGwMon.cc
- src/mon/NVMeofGwMon.h
- src/mon/NVMeofGwSerialize.h
- src/mon/NVMeofGwTypes.h
> mon: cosmetic fixes for NVMeofGwMon files

- src/pybind/mgr/dashboard/controllers/ceph_users.py
- src/pybind/mgr/dashboard/openapi.yaml
Fixes: https://tracker.ceph.com/issues/67224 …
> mgr/dashboard: fix ceph-users api doc

- qa/workunits/rbd/luks-encryption.sh
backport tracker: https://tracker.ceph.com/issues/67058
---
backport of https://github.com/ceph/ceph/pull/58688
parent tracker: https://tracker.ceph.com/issues/67051
> reef: qa/workunits/rbd: avoid caching effects in luks-encryption.sh

- doc/governance.rst
with the consent of my colleagues
- Dan van der Ster
- João Eduardo Luis
- Mark Nelson
changed their e-mail addresses to the current one
Signed-off-by: Tobias Fischer <tobias.fischer@clyso.com> …
> doc:update e-mail addresses governance

- doc/radosgw/qat-accel.rst
> doc/radosgw: improve qat-accel.rst

- doc/dev/osd_internals/erasure_coding.rst
- doc/dev/osd_internals/erasure_coding/enhancements.rst
Erasure coding enhancements design document
Design document discussing proposed changed to erasure coding to improve performance
Signed-off-by: Bill Scales <bill_scales@uk.ibm.com> …
> doc: doc/dev/osd_interals/erasure_coding/enhancements.rst

- qa/rbd/krbd_discard_granularity.t
> qa: adjust expected io_opt in krbd_discard_granularity.t

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.ts
fixes: https://tracker.ceph.com/issues/67193 …
> mgr/dashboard: replace individual cluster's capacity info with Usage bar in Multi-Cluster

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.html
fixes: https://tracker.ceph.com/issues/67536 …
> mgr/dashboard: fix multi-cluster usage bar error after carbon changes

- src/rgw/rgw_lc_s3.cc
- [x ] Code cleanup (no ticket needed)
- [ x] No impact that …
> rgwlc: fix typo in getlc (ObjectSizeGreaterThan)

- doc/glossary.rst
- doc/rados/troubleshooting/troubleshooting-osd.rst
Add an entry for "Flapping OSD" to the glossary. …
> doc/glossary: add "flapping OSD"

- src/crimson/osd/backfill_state.cc
- src/crimson/osd/backfill_state.h
- src/crimson/osd/pg.h
- src/crimson/osd/pg_recovery.cc
- src/crimson/osd/pg_recovery.h
Fixes: https://tracker.ceph.com/issues/67470 …
> crimson/osd/backfill_state: support backfill cancellation

- src/rgw/rgw_pubsub.cc
- src/test/rgw/bucket_notification/test_bn.py
Fixes: https://tracker.ceph.com/issues/67525
<details>
</details>
> rgw/notifications: fixing radosgw-admin notification json

- qa/workunits/rbd/luks-encryption.sh
- src/librbd/api/Migration.cc
- src/librbd/io/ReadResult.cc
- src/librbd/io/ReadResult.h
- src/librbd/migration/FileStream.cc
- src/librbd/migration/FormatInterface.h
- src/librbd/migration/HttpClient.cc
- src/librbd/migration/ImageDispatch.cc
- src/librbd/migration/ImageDispatch.h
- src/librbd/migration/NativeFormat.cc
- src/librbd/migration/NativeFormat.h
- src/librbd/migration/OpenSourceImageRequest.cc
- src/librbd/migration/OpenSourceImageRequest.h
- src/librbd/migration/QCOWFormat.cc
- src/librbd/migration/QCOWFormat.h
- src/librbd/migration/RawFormat.cc
- src/librbd/migration/RawFormat.h
- src/librbd/migration/RawSnapshot.cc
- src/librbd/migration/SourceSpecBuilder.cc
- src/librbd/migration/SourceSpecBuilder.h
- src/test/librbd/migration/test_mock_QCOWFormat.cc
- src/test/librbd/migration/test_mock_RawFormat.cc
backport tracker: https://tracker.ceph.com/issues/67440
---
backport of https://github.com/ceph/ceph/pull/58882 and https://github.com/ceph/ceph/pull/44366
parent tracker: https://tracker.ceph.com/issues/53674
> reef: librbd/crypto: fix issue when live-migrating from encrypted export

- src/os/bluestore/BlueStore.cc
- src/test/objectstore/store_test.cc
Parent tracker: https://tracker.ceph.com/issues/64443
Backport tracker: https://tracker.ceph.com/issues/64936
Backports: https://github.com/ceph/ceph/pull/55594
(cherry picked from commit ac4a48c4be1791a32cfd2cf3cf5af51eee581d21) …
> quincy: test/store_test: fix DeferredWrite test when prefer_deferred_size=0

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/crud-table/crud-table.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts
- src/pybind/mgr/dashboard/frontend/src/styles/themes/_content.scss
Fixes: https://tracker.ceph.com/issues/67544,
https://tracker.ceph.com/issues/67538,
https://tracker.ceph.com/issues/67542, https://tracker.ceph.com/issues/67545 …
> mgr/dashboard: carbon datatables impr and cleanups

- qa/rbd/krbd_discard_granularity.t
backport tracker: https://tracker.ceph.com/issues/67521
---
backport of https://github.com/ceph/ceph/pull/59112
parent tracker: https://tracker.ceph.com/issues/67353
> quincy: qa: adjust expected io_opt in krbd_discard_granularity.t

- qa/rbd/krbd_discard_granularity.t
backport tracker: https://tracker.ceph.com/issues/67520
---
backport of https://github.com/ceph/ceph/pull/59112
parent tracker: https://tracker.ceph.com/issues/67353
> reef: qa: adjust expected io_opt in krbd_discard_granularity.t

- doc/radosgw/notifications.rst
Fixes: https://tracker.ceph.com/issues/50610
Signed-off-by: Yuval Lifshitz <ylifshit@ibm.com>
(cherry picked from commit d12ba11741dc749bcce315bf467078595fa95b24) …
> quincy: doc/rgw/notification: persistent notification queue full behavior

- doc/radosgw/notifications.rst
Fixes: https://tracker.ceph.com/issues/50610
Signed-off-by: Yuval Lifshitz <ylifshit@ibm.com>
(cherry picked from commit d12ba11741dc749bcce315bf467078595fa95b24) …
> reef: doc/rgw/notification: persistent notification queue full behavior

- doc/radosgw/notifications.rst
Fixes: https://tracker.ceph.com/issues/50610
Signed-off-by: Yuval Lifshitz <ylifshit@ibm.com>
(cherry picked from commit d12ba11741dc749bcce315bf467078595fa95b24) …
> squid: doc/rgw/notification: persistent notification queue full behavior

- src/crimson/os/seastore/btree/fixed_kv_node.h
> crimson/os/seastore/btree: fix minor corner case issue

- src/client/Client.cc
Fixes: https://tracker.ceph.com/issues/67221 …
> client: flush the caps release in filesystem sync

- qa/rbd/krbd_discard_granularity.t
backport tracker: https://tracker.ceph.com/issues/67519
---
backport of https://github.com/ceph/ceph/pull/59112
parent tracker: https://tracker.ceph.com/issues/67353
> squid: qa: adjust expected io_opt in krbd_discard_granularity.t

- doc/cephfs/file-layouts.rst
Improve the English in the "Layout Fields" section of doc/cephfs/file-layouts.rst.
(cherry picked from commit 9607b66e97f73b5b7c53c2610b928cd6a420c9f2) …
> squid: doc/cephfs: edit "Layout Fields" text

- doc/cephfs/file-layouts.rst
Improve the English in the "Layout Fields" section of doc/cephfs/file-layouts.rst.
(cherry picked from commit 9607b66e97f73b5b7c53c2610b928cd6a420c9f2) …
> reef: doc/cephfs: edit "Layout Fields" text

- doc/cephfs/file-layouts.rst
Improve the English in the "Layout Fields" section of doc/cephfs/file-layouts.rst.
(cherry picked from commit 9607b66e97f73b5b7c53c2610b928cd6a420c9f2) …
> quincy: doc/cephfs: edit "Layout Fields" text

- doc/cephfs/file-layouts.rst
Improve "layout fields" text in doc/cephfs/file-layouts.rst, as suggesed by Anthony D'Atri in these comments:
https://github.com/ceph/ceph/pull/59021#discussion_r1704108581 https://github.com/ceph/ceph/pull/59021#discussion_r1704112320
(cherry picked from commit 0949b410433837f0509fb73169fa7f22c8f6c256) …
> reef: doc/cephfs: improve "layout fields" text

- doc/radosgw/qat-accel.rst
(cherry picked from commit a6f311a5f3b33fbe31ce898dc746199d233069f0) …
> squid: doc/radosgw: improve qat-accel.rst

- doc/cephfs/ceph-dokan.rst
- doc/man/8/mount.ceph.rst
- doc/man/8/mount.fuse.ceph.rst
- doc/rados/configuration/common.rst
- doc/radosgw/qat-accel.rst
doc: Harmonize 'mountpoint'
Change a few instances of 'mountpoint' to 'mount point', and a QAT straggler. …
> doc: Harmonize 'mountpoint'

- doc/cephfs/ceph-dokan.rst
- doc/man/8/mount.ceph.rst
- doc/man/8/mount.fuse.ceph.rst
- doc/rados/configuration/common.rst
- doc/radosgw/qat-accel.rst
(cherry picked from commit fda2db5ac7baedc9460cd1d313413c9445518163) …
> squid: doc: Harmonize 'mountpoint'

- qa/tasks/mgr/dashboard/helper.py
- qa/tasks/mgr/dashboard/test_osd.py
Fixes: https://tracker.ceph.com/issues/66844
Given the random nature/irreproducibility of this failure, it's hard to know whether this fixed it or not. In case a retry happens, it'll be printed to the Jenkins console logs (I can even create a Jenkins Build Failure parser to detect this condition). …
> qa/mgr/dashboard: fix test race condition

- src/test/objectstore/store_test.cc
Apparently caused by https://github.com/ceph/ceph/pull/58511
- …
> test/store_test: fix assertions due to unclosed collection refs.

- qa/suites/fs/workload/tasks/workunit/suites/iogen.yaml
Fixes: https://tracker.ceph.com/issues/56590 …
> quincy: qa/suites/fs: skip check-counters for iogen workload

- src/pybind/mgr/volumes/fs/operations/clone_index.py
backport tracker: https://tracker.ceph.com/issues/66929
---
backport of https://github.com/ceph/ceph/pull/58101
parent tracker: https://tracker.ceph.com/issues/66560
> quincy: mgr/vol: handle case where clone index entry goes missing

- qa/workunits/dencoder/test_readable.py
PR https://github.com/ceph/ceph-object-corpus/pull/20 should merge before that PR
- …
> workunit/dencoder: dencoder test forward incompat fix

- src/kv/RocksDBStore.cc
backport tracker: https://tracker.ceph.com/issues/65916
---
backport of https://github.com/ceph/ceph/pull/55676
parent tracker: https://tracker.ceph.com/issues/64511
> reef: kv/RocksDBStore: Configure compact-on-deletion for all CFs

- qa/workunits/rados/test_rados_tool.sh
Fixes: https://tracker.ceph.com/issues/67419 …
> test: test_rados_tools compare output without trimming newline

- src/rgw/rgw_auth_keystone.cc
- src/rgw/rgw_keystone.cc
- src/rgw/rgw_keystone.h
backport of pr: https://github.com/ceph/ceph/pull/55236
tracker: https://tracker.ceph.com/issues/64495
- Tracker …
> quincy: rgw: invalidate and retry keystone admin token

- doc/rados/operations/balancer.rst
This reverts commit 7fff8e9a981c366390f61cf1eaeba6524fd6d365.
- …
> quincy: doc/rados: revert "doc/rados/operations: document `ceph balancer status detail`"

- qa/tasks/mon_thrash.py
stopping was set by PR #58282 to bool instead of set()
Fixes: https://tracker.ceph.com/issues/67496
- Tracker …
> mon/thrasher: set stopping

- doc/cephfs/cephfs-mirroring.rst
- qa/tasks/cephfs/test_mirroring.py
- src/tools/cephfs_mirror/PeerReplayer.cc
- src/tools/cephfs_mirror/PeerReplayer.h
Fixes: https://tracker.ceph.com/issues/65317
Fixes: https://tracker.ceph.com/issues/65226 …
> cephfs_mirror: update peer status for invalid metadata in remote snapshot

- src/client/Client.cc
- src/test/client/nonblocking.cc
> client: fix file cache cap leak which can stall async read call

- src/rgw/rgw_auth_keystone.cc
- src/rgw/rgw_keystone.cc
- src/rgw/rgw_keystone.h
backport of pr: https://github.com/ceph/ceph/pull/55236
tracker: https://tracker.ceph.com/issues/64494
- Tracker …
> reef: rgw: invalidate and retry keystone admin token

- src/pybind/mgr/cephadm/services/osd.py
Fixes: https://tracker.ceph.com/issues/67329 …
> mgr/cephadm: add "original_weight" parameter to OSD class

- doc/rados/operations/cache-tiering.rst
Explain how to deal with "unfound objects" when restarting OSDs in a cache-tiered environment.
Fixes: https://tracker.ceph.com/issues/44286
(cherry picked from commit f01d7a8d5b85170c034acb962b9833913853a1c5) …
> reef: doc/rados: document unfound object cache-tiering scenario

- src/os/bluestore/BlueStore.cc
backport tracker: https://tracker.ceph.com/issues/65938
--------
backport of #49438
parent tracker: https://tracker.ceph.com/issues/58274
> reef: os/bluestore: set rocksdb iterator bounds for Bluestore::_collection_list()

- doc/glossary.rst
Add a (very basic) definition of object storage.
(cherry picked from commit 43057b88538e868b817acb04d5e6c4e95b4c716e) …
> quincy: doc/glossary: add "object storage"

- doc/glossary.rst
Add a (very basic) definition of object storage.
(cherry picked from commit 43057b88538e868b817acb04d5e6c4e95b4c716e) …
> squid: doc/glossary: add "object storage"

- doc/glossary.rst
Add a (very basic) definition of object storage.
(cherry picked from commit 43057b88538e868b817acb04d5e6c4e95b4c716e) …
> reef: doc/glossary: add "object storage"

- src/crimson/net/Messenger.h
- src/crimson/net/SocketMessenger.h
- src/crimson/osd/osd.cc
Fixes: https://tracker.ceph.com/issues/66372 …
> crimson/osd/osd: mark down connections to downed osds

- src/crimson/osd/pg.cc
- src/crimson/osd/pg.h
- src/crimson/osd/recovery_backend.cc
- src/crimson/osd/replicated_backend.cc
- src/crimson/osd/replicated_recovery_backend.cc
Fixes: https://tracker.ceph.com/issues/67564 …
> crimson/osd/pg: implement PG::PGLogEntryHandler::remove()

- qa/suites/rados/thrash-erasure-code/thrashers/minsize_recovery.yaml
- qa/tasks/ceph_manager.py
- qa/tasks/rados.py
- qa/tasks/thrashosds.py
backport tracker: https://tracker.ceph.com/issues/64673
---
backport of https://github.com/ceph/ceph/pull/52891
parent tracker: https://tracker.ceph.com/issues/59172
<details>
</details>
> quincy: qa/tasks/ceph_manager.py: Rewrite test_pool_min_size

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/service.interface.ts
Fixes https://tracker.ceph.com/issues/67223
[Screencast from 2024-08-20 14-54-41.webm](https://github.com/user-attachments/assets/6e38f993-ccc3-466a-af83-52c32c199d80)
<details> …
> mgr/dashboard: Add group field in nvmeof service form

- src/pybind/mgr/dashboard/frontend/src/app/core/layouts/workbench-layout/workbench-layout.component.scss
Fixes: https://tracker.ceph.com/issues/67549
https://tracker.ceph.com/issues/67550
Signed-off-by: Dnyaneshwari Talwekar<dtalweka@redhat.com> …
> mgr/dashboard: can't scroll to the end of the page

- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.spec.ts
This PR fixes regression caused by this commit - https://github.com/ceph/ceph/commit/24b2716ae46aa8483625e01163668f8735b9e63b
Fixes: https://tracker.ceph.com/issues/67194 …
> mgr/dashboard: fix typo in Multi-Cluster > Manager Cluster to Manage Clusters

- src/crimson/common/interruptible_future.h
- src/crimson/osd/pg.h
- src/crimson/osd/recovery_backend.h
- src/crimson/osd/replicated_recovery_backend.cc
- src/test/crimson/test_interruptible_future.cc
Fixes: https://tracker.ceph.com/issues/67508 …
> crimson/osd/recovery_backend: restart object pulls that are blocked by down osds

- src/mds/QuiesceAgent.cc
> mds: fix spelling typo

- qa/workunits/fs/snaps/snaptest-double-null.sh
Fixes: http://tracker.ceph.com/issues/67408 …
> qa: wait for file creation before changing mode

- qa/tasks/cephfs/test_snapshots.py
- src/mds/Server.cc
- src/mds/SessionMap.cc
> mds: cephx path restriction incorrectly rejects snapshots of deleted directory

- src/mds/MDSRankQuiesce.cc
- src/messages/MMDSQuiesceDbAck.h
- src/messages/MMDSQuiesceDbListing.h
> mds: encode quiesce payload on demand

- src/client/Client.cc
- src/client/Client.h
- src/client/Inode.h
- src/client/MetaRequest.h
- src/client/MetaSession.h
To avoid an allocation for each Context and improved cache locality.
- Component …
> client: use vectors for context lists

- qa/tasks/cephadm.py
The cephadm_from_container allows one to do a single container build and then point teuthology at that image as the "single source of truth". I find this extremely convenient when running teuthology locally and I keep carrying this patch around - I figure having it upstream will simplify my workflow. Maybe someday it'll benefit others too.
To use it I set up a yaml overrides file with the following content:
```yaml
overrides:
cephadm:
image: "quay.io/phlogistonjohn/ceph:dev"
cephadm_from_container: true
verify_ceph_hash: false
verify_ceph_hash: false
```
This let's me test my custom builds fairly easily! …
> qa/tasks: add a new cephadm_from_container feature to cephadm task

- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.ts
backport tracker: https://tracker.ceph.com/issues/67359
---
backport of https://github.com/ceph/ceph/pull/58963
parent tracker: https://tracker.ceph.com/issues/67009
> squid: mgr/dashboard: Dashboard not showing Object/Overview correctly.

- monitoring/ceph-mixin/dashboards/multi-cluster.libsonnet
- monitoring/ceph-mixin/dashboards_out/ceph-cluster.json
- monitoring/ceph-mixin/dashboards_out/multi-cluster-overview.json
- src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/cluster.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-details/multi-cluster-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-details/multi-cluster-details.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-details/multi-cluster-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-list/multi-cluster-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-list/multi-cluster-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-list/multi-cluster-list.component.ts
Fixes: https://tracker.ceph.com/issues/67192
https://github.com/user-attachments/assets/4d7b2a2b-4a45-45da-bb0b-ab92673c4629 …
> mgr/dashboard: Add Performance Details grafana charts for individual clusters in Manage-clusters page

- src/client/Client.cc
Credit to Brad Hubbard for grabbing the stack trace.
Fixes: https://tracker.ceph.com/issues/67565 …
> client: calls to _ll_fh_exists() should hold client_lock

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.ts
https://github.com/user-attachments/assets/8fdbc404-03e6-4979-b21f-21bb57a07108
Fixes: https://tracker.ceph.com/issues/67103 …
> mgr/dashboard: Zone details showing incorrect data for data pool values and compression info for Storage Classes

- src/test/rgw/test-rgw-common.sh
otherwise it throws 'failed to init realm: (2) No such file or directory' after #59422 …
> test-rgw-multisite: create default realm in multisite test script

- src/mds/MDCache.cc
- src/mds/Server.cc
Fixes: https://tracker.ceph.com/issues/67280 …
> mds: add more debug logs and log events

- src/rgw/rgw_bucket.cc
- src/rgw/rgw_bucket.h
- src/rgw/rgw_data_sync.cc
- src/rgw/rgw_lc.cc
- src/rgw/rgw_lc.h
- src/rgw/rgw_lc_s3.cc
- src/rgw/rgw_lc_s3.h
- src/rgw/rgw_sal.h
- src/rgw/rgw_sal_dbstore.h
- src/rgw/rgw_sal_rados.cc
- src/rgw/rgw_sal_rados.h
- src/rgw/rgw_service.cc
- src/rgw/rgw_sync_module.cc
- src/rgw/rgw_sync_module.h
- src/test/rgw/CMakeLists.txt
- src/test/rgw/test_rgw_lc.cc
backport tracker: https://tracker.ceph.com/issues/56628
---
backport of https://github.com/ceph/ceph/pull/46928
parent tracker: https://tracker.ceph.com/issues/53361
> quincy: rgwlc: permit lifecycle to reduce data conditionally in archive zone

- doc/man/8/rbd.rst
Clarifies that some mirror commands hold for either pools or namespaces.
- …
> doc/rbd: add namespace information for mirror commands

- qa/cephfs/overrides/ignorelist_health.yaml
Fixes: https://tracker.ceph.com/issues/67601 …
> qa: ignore warnings variations

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.ts
Fixes: https://tracker.ceph.com/issues/67067 …
> mgr/dashboard: improve prometheus service request handling

- doc/dev/release-checklists.rst
- src/ceph_release
> squid: src/ceph_release, doc: mark squid stable

- examples/rgw/boto3/README.md
- src/test/rgw/bucket_notification/README.rst
Update RabbitMQ setup documentation for RGW notification tests. …
> src/test/rgw/bucket_notification/README.rst: update RabbitMQ documentation for RGW notification tests

- doc/dev/developer_guide/testing_integration_tests/tests-integration-testing-teuthology-workflow.rst
1. Add "Infrastructure" section.
2. Move "Naming the ceph-ci branch" section under "Getting binaries - Build Ceph". Also mention about centos9-only trick.
3. In "Teuthology Archives", mention about developer playground machines and log files. …
> doc: update tests-integration-testing-teuthology-workflow.rst

- doc/dev/developer_guide/testing_integration_tests/tests-integration-testing-teuthology-workflow.rst
* add "Infrastructure" section.
* move "Naming the ceph-ci branch" section under "Getting binaries - Build Ceph". Also mention about centos9-only trick.
* in "Teuthology Archives", mention about developer playground machines and ceph log files.
Signed-off-by: Vallari Agrawal <val.agl002@gmail.com>
(cherry picked from commit 9bfcb8e17db8c61e523e10856d12b237433d831a) …
> reef: doc: update tests-integration-testing-teuthology-workflow.rst

- doc/dev/developer_guide/testing_integration_tests/tests-integration-testing-teuthology-workflow.rst
* add "Infrastructure" section.
* move "Naming the ceph-ci branch" section under "Getting binaries - Build Ceph". Also mention about centos9-only trick.
* in "Teuthology Archives", mention about developer playground machines and ceph log files.
Signed-off-by: Vallari Agrawal <val.agl002@gmail.com>
(cherry picked from commit 9bfcb8e17db8c61e523e10856d12b237433d831a) …
> squid: doc: update tests-integration-testing-teuthology-workflow.rst

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.html
Fixes: https://tracker.ceph.com/issues/67850
Signed-off-by: Dnyaneshwari Talwekar<dtalweka@redhat.com>
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2271812 …
> mgr/dashboard: Wrong(half) uid is observed in dashboard

- src/crimson/osd/backfill_state.cc
- src/crimson/osd/backfill_state.h
- src/crimson/osd/pg.cc
- src/crimson/osd/pg_recovery.cc
- src/crimson/osd/pg_recovery.h
- src/test/crimson/test_backfill.cc
> crimson/osd: support backfill cancellation ---- part2

- doc/radosgw/config-ref.rst
doc/radosgw: Improve config-ref.rst
- …
> doc/radosgw: Improve config-ref.rst

- doc/rados/operations/health-checks.rst
doc/rados/operations: Improve health-checks.rst …
> doc/rados/operations: Improve health-checks.rst

- src/crimson/osd/ec_backend.cc
- src/crimson/osd/ec_backend.h
- src/crimson/osd/osd_operations/snaptrim_event.cc
- src/crimson/osd/pg.cc
- src/crimson/osd/pg.h
- src/crimson/osd/pg_backend.cc
- src/crimson/osd/pg_backend.h
- src/crimson/osd/replicated_backend.cc
- src/crimson/osd/replicated_backend.h
Fixes: https://tracker.ceph.com/issues/67675 …
> crimson/osd/pg: only mutate obc for user triggerred transactions

- src/common/version.cc
- src/crimson/osd/main_config_bootstrap_helpers.cc
Fixes: https://tracker.ceph.com/issues/67376
https://tracker.ceph.com/issues/67227 …
> crimson: early config checks and version

- doc/cephfs/add-remove-mds.rst
> doc/mds: improve wording

- doc/radosgw/config-ref.rst
(cherry picked from commit 8e743fc603310a802b8553af5e73266a9caf6554) …
> squid: doc/radosgw: Improve config-ref.rst

- src/neorados/RADOS.cc
Missing returns in error handling would cause execution to continue and attempt to reuse a moved-from completion
Thanks to Suyash Dongre <suyashd999@gmail.com> for finding it.
Fixes: https://tracker.ceph.com/issues/66335 …
> neorados: Fix use-after-move in Builder::build_

- src/crimson/osd/pg.cc
Fixes: https://tracker.ceph.com/issues/67450 …
> crimson/osd/pg: fix wrong lambda capture of transactions in `PG::submit_error_log()`

- PendingReleaseNotes
Fixes: https://tracker.ceph.com/issues/67857
<details>
</details>
> rgw/notifications: update release notes with fix to principalId

- qa/workunits/rbd/cli_migration.sh
- src/librbd/ImageCtx.cc
- src/librbd/io/Utils.cc
- src/librbd/io/Utils.h
- src/librbd/migration/NativeFormat.cc
- src/librbd/migration/QCOWFormat.cc
- src/librbd/migration/RawFormat.cc
- src/test/librbd/migration/test_mock_RawFormat.cc
> librbd/migration: prune snapshot extents in RawFormat::list_snaps()

- doc/cephfs/add-remove-mds.rst
(cherry picked from commit 332804bad58c892d01d2d2da557e42104365ef8a) …
> quincy: doc/mds: improve wording

- doc/cephfs/add-remove-mds.rst
(cherry picked from commit 332804bad58c892d01d2d2da557e42104365ef8a) …
> reef: doc/mds: improve wording

- doc/cephfs/add-remove-mds.rst
(cherry picked from commit 332804bad58c892d01d2d2da557e42104365ef8a) …
> squid: doc/mds: improve wording

- doc/rados/operations/health-checks.rst
(cherry picked from commit 2aa82539ede8ade095ad0b22e973eac538354711) …
> squid: doc/rados/operations: Improve health-checks.rst

- doc/rados/operations/health-checks.rst
(cherry picked from commit 2aa82539ede8ade095ad0b22e973eac538354711) …
> reef: doc/rados/operations: Improve health-checks.rst

- src/common/options/rgw.yaml.in
- src/rgw/rgw_auth.cc
- src/rgw/rgw_common.h
- src/rgw/rgw_rest_s3.cc
backport tracker: https://tracker.ceph.com/issues/65005
backport of #56044
parent tracker: https://tracker.ceph.com/issues/64797
> quincy: RGW: allow user disabling presigned urls in rgw configuration

- src/rgw/rgw_aio.cc
Fixes: https://tracker.ceph.com/issues/67781
clang-tidy original warning:
```
warning: forwarding reference passed to std::move(), which may unexpectedly cause lvalues to be moved; use std::forward() instead [bugprone-move-forwarding-reference] 
return [ctx = std::move(ctx), op = std::move(op), trace_ctx] (Aio* aio, AioResult& r) mutable { ^~~~~~~~~
std::forward<Op>
``` …
> rgw/rgw_aio: forwarding reference passed to std::move()

- src/rgw/rgw_kafka.cc
backport tracker: https://tracker.ceph.com/issues/64793
---
backport of https://github.com/ceph/ceph/pull/54215
parent tracker: https://tracker.ceph.com/issues/63335
> quincy: rgw/notification: Kafka persistent notifications not retried and removed even when the broker is down 

- src/crimson/common/fixed_kv_node_layout.h
- src/crimson/os/seastore/backref/backref_tree_node.h
- src/crimson/os/seastore/btree/btree_range_pin.h
- src/crimson/os/seastore/lba_manager/btree/lba_btree_node.h
@cyx1231st LEAF_NODE_CAPACITY for backref leaf node is not correct in main branch, so this part is divided from original PR. …
> crimson/os/seastore: cleanup lba/backref node capacity

- src/include/buffer.h
- src/include/cephfs/types.h
- src/mds/CInode.cc
- src/mds/Locker.cc
- src/mds/MDCache.cc
- src/mds/Server.cc
> mds: move fscrypt inode_t metadata to mds_co mempool

- doc/rados/configuration/mon-lookup-dns.rst
Add a link to the page about Messenger v2 to the end of doc/rados/configuration/mon-lookup-dns.rst.
Fixes: https://tracker.ceph.com/issues/58752 …
> doc/rados: add link to messenger v2 info in mon-lookup-dns.rst

- src/rgw/rgw_process.cc
like for example
```
2024-08-21T16:01:59.146+0000 7fffe6348640  0 ERROR: client_io->complete_request() returned Broken pipe
```
Fixes: https://tracker.ceph.com/issues/48358 …
> rgw: decrement qlen/qactive perf counters on error

- src/test/cli/rbd/help.t
- src/tools/rbd/action/Group.cc
- src/tools/rbd/action/MirrorPool.cc
- src/tools/rbd/action/Rename.cc
backport tracker: https://tracker.ceph.com/issues/67862
---
backport of https://github.com/ceph/ceph/pull/59478
parent tracker: https://tracker.ceph.com/issues/67752
> quincy: rbd: amend "rbd {group,} rename" and "rbd mirror pool" command descriptions

- README.md
Make the sentences in the "Build Prerequisites" section of README.md more direct.
- …
> doc/README.md: edit "Build Prerequisites"

- src/mon/NVMeofGwMap.cc
- src/mon/NVMeofGwMap.h
- src/mon/NVMeofGwMon.cc
- src/mon/NVMeofGwMon.h
- src/mon/NVMeofGwSerialize.h
- src/mon/NVMeofGwTypes.h
>  gw deleting state

- qa/tasks/cephfs/test_snap_schedules.py
- src/pybind/mgr/snap_schedule/fs/schedule_client.py
Fixes: https://tracker.ceph.com/issues/65895 …
> mgr/snap_schedule: correctly fetch mds_max_snaps_per_dir from mds

- README.md
Make the sentences in the "Build Prerequisites" section of README.md more direct.
(cherry picked from commit 0b277fe3809c2eae7bfced002ac85f7e1629fa30) …
> squid: doc/README.md: edit "Build Prerequisites"

- src/mon/NVMeofGwMap.cc
> leonidc0409 blocklist fix

- doc/dev/release-checklists.rst
Add a step to the section called "First Stable Release" that explains how to activate the latest release in Read the Docs. …
> doc/dev: add "activate latest release" RTD step

- doc/dev/release-checklists.rst
Add a step to the section called "First Stable Release" that explains how to activate the latest release in Read the Docs.
(cherry picked from commit e7bd4bcdd074a3defae5866a6c035559bf210271) …
> squid: doc/dev: add "activate latest release" RTD step

- src/test/cli/rbd/help.t
- src/tools/rbd/action/Group.cc
- src/tools/rbd/action/MirrorPool.cc
- src/tools/rbd/action/Rename.cc
backport tracker: https://tracker.ceph.com/issues/67863
---
backport of https://github.com/ceph/ceph/pull/59478
parent tracker: https://tracker.ceph.com/issues/67752
> reef: rbd: amend "rbd {group,} rename" and "rbd mirror pool" command descriptions

- doc/cephadm/upgrade.rst
Add instructions for removing malformed JSON that causes the cephadm module to fail to start, which in turn makes the orchestrator fail to start. …
> doc/cephadm: add malformed-JSON removal instructions

- src/tools/rbd_ggate/ggate_drv.c
I am not familiar with the ceph source code but at a first glance it looks like `errno` should be a positive number. …
> tools/rbd_ggate: fix sign of errno

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.ts
backport tracker: https://tracker.ceph.com/issues/67792
---
backport of https://github.com/ceph/ceph/pull/58778
parent tracker: https://tracker.ceph.com/issues/67103
> squid: mgr/dashboard: Zone details showing incorrect data for data pool values and compression info for Storage Classes

- README.md
Make the sentences in the "Build Prerequisites" section of README.md more direct.
(cherry picked from commit 0b277fe3809c2eae7bfced002ac85f7e1629fa30) …
> quincy: doc/README.md: edit "Build Prerequisites"

- src/pybind/mgr/rgw/module.py
- src/python-common/ceph/rgw/rgwam_core.py
backport tracker: https://tracker.ceph.com/issues/67110
---
backport of https://github.com/ceph/ceph/pull/58343
parent tracker: https://tracker.ceph.com/issues/66750
> squid: mgr/rgw: Adding a retry config while calling zone_create()

- README.md
Improve the formatting of the section "Building Ceph" in the file README.md.
- …
> doc/README.md: improve formatting

- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/ssh.py
It was found on some larger clusters that these settings were two low and hosts were getting temporarily marked offline …
> mgr/cephadm: make ssh keepalive settings configurable

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-gateway/nvmeof-gateway.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-initiators-list/nvmeof-initiators-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-list/nvmeof-listeners-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
- As per the review from the stakeholders , updating the microcopies in nvmeof.
- in task service file changed casing of `Service` to align with rest.
Fixes https://tracker.ceph.com/issues/67728
<details> …
> mgr/dashboard: Update nvmeof microcopies

- src/crimson/osd/osd_operations/background_recovery.cc
- src/crimson/osd/osd_operations/background_recovery.h
- src/crimson/osd/pg.cc
- src/crimson/osd/pg.h
- src/crimson/osd/pg_recovery.cc
- src/crimson/osd/pg_recovery.h
- src/crimson/osd/pg_recovery_listener.h
- src/osd/PG.h
- src/osd/PeeringState.cc
- src/osd/PeeringState.h
Fixes: https://tracker.ceph.com/issues/67380 …
> crimson/osd: cancel ongoing pglog-based recoveries on recovery defering

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.html
backport tracker: https://tracker.ceph.com/issues/67870
backport of: #59554
parent tracker: https://tracker.ceph.com/issues/67850 …
> Squid: mgr/dashboard: Wrong(half) uid is observed in dashboard when user created via cli contains $ in its name 

- doc/dev/release-checklists.rst
Add a step to the section called "First Stable Release" that explains how to activate the latest release in Read the Docs.
(cherry picked from commit e7bd4bcdd074a3defae5866a6c035559bf210271) …
> reef: doc/dev: add "activate latest release" RTD step

- README.md
Improve the formatting of the section "Building Ceph" in the file README.md.
(cherry picked from commit 7171f73c81d603f8ff62198fc1e5f50c20a0aa05) …
> squid: doc/README.md: improve formatting

- src/crimson/osd/pg.cc
- src/crimson/osd/pg_recovery.cc
- src/crimson/osd/pg_recovery.h
Fixes: https://tracker.ceph.com/issues/67731 …
> crimson/osd/pg: clear backfill_state when the PG goes clean

- doc/radosgw/d3n_datacache.rst
Fixes: https://tracker.ceph.com/issues/66492 …
> doc/rgw/d3n: pass cache dir volume to extra_container_args

- src/os/bluestore/HybridAllocator_impl.h
> os/bluestore: perfect comments in hybrid_allocator

- doc/radosgw/d3n_datacache.rst
Fixes: https://tracker.ceph.com/issues/66492
Signed-off-by: Mark Kogan <mkogan@ibm.com>
(cherry picked from commit 4594e38bf19a8f73191904f5f373a3707cddd2f3) …
> quincy: doc/rgw/d3n: pass cache dir volume to extra_container_args

- doc/radosgw/d3n_datacache.rst
Fixes: https://tracker.ceph.com/issues/66492
Signed-off-by: Mark Kogan <mkogan@ibm.com>
(cherry picked from commit 4594e38bf19a8f73191904f5f373a3707cddd2f3) …
> reef: doc/rgw/d3n: pass cache dir volume to extra_container_args

- doc/radosgw/d3n_datacache.rst
Fixes: https://tracker.ceph.com/issues/66492
Signed-off-by: Mark Kogan <mkogan@ibm.com>
(cherry picked from commit 4594e38bf19a8f73191904f5f373a3707cddd2f3) …
> squid: doc/rgw/d3n: pass cache dir volume to extra_container_args

- README.md
Make the sentences in the "Build Prerequisites" section of README.md more direct.
(cherry picked from commit 0b277fe3809c2eae7bfced002ac85f7e1629fa30) …
> reef: doc/README.md: edit "Build Prerequisites"

- README.md
Improve the formatting of the section "Building Ceph" in the file README.md.
(cherry picked from commit 7171f73c81d603f8ff62198fc1e5f50c20a0aa05) …
> reef: doc/README.md: improve formatting

- README.md
Add ordered-list formatting to the "Building Ceph" section of README.md.
(cherry picked from commit 1f21057e4166f2ea9f51ee037eb8e234c1390cfb) …
> reef: doc/README.md - add ordered list

- doc/rados/configuration/mon-lookup-dns.rst
Add a link to the page about Messenger v2 to the end of doc/rados/configuration/mon-lookup-dns.rst.
Fixes: https://tracker.ceph.com/issues/58752
(cherry picked from commit 81f9d064f714f42ff27bf620df526f87b393402b) …
> squid: doc/rados: add link to messenger v2 info in mon-lookup-dns.rst

- doc/rados/configuration/mon-lookup-dns.rst
Add a link to the page about Messenger v2 to the end of doc/rados/configuration/mon-lookup-dns.rst.
Fixes: https://tracker.ceph.com/issues/58752
(cherry picked from commit 81f9d064f714f42ff27bf620df526f87b393402b) …
> reef: doc/rados: add link to messenger v2 info in mon-lookup-dns.rst

- doc/rados/configuration/mon-lookup-dns.rst
Add a link to the page about Messenger v2 to the end of doc/rados/configuration/mon-lookup-dns.rst.
Fixes: https://tracker.ceph.com/issues/58752
(cherry picked from commit 81f9d064f714f42ff27bf620df526f87b393402b) …
> quincy: doc/rados: add link to messenger v2 info in mon-lookup-dns.rst

- src/pybind/mgr/cephadm/services/oauth2_proxy.py
- src/pybind/mgr/cephadm/templates/services/oauth2-proxy/oauth2-proxy.conf.j2
- src/python-common/ceph/deployment/service_spec.py
Fixes: https://tracker.ceph.com/issues/68052 …
> mgr/cephadm: renaming whitelist_domains field to allowlist_domains

- src/pybind/mgr/dashboard/frontend/cypress/e2e/orchestrator/05-services.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/cluster.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/service.interface.ts
Adds service management support for the mgmt-gateway.
[screen-capture (23).webm](https://github.com/user-attachments/assets/75100ff1-e3fc-44db-8156-0d29049c1901)
Video's spec file
```[ceph: root@ceph-node-00 /]# ceph orch ls --service_name mgmt-gateway --export
service_type: mgmt-gateway
service_name: mgmt-gateway
placement:
count: 1
spec:
ssl_ciphers:
- ECDHE-ECDSA-AES128-GCM-SHA256
- ECDHE-RSA-AES128-GCM-SHA256
```
Fixes: https://tracker.ceph.com/issues/66963 …
> mgr/dashboard: add service management for mgmt-gateway

- README.md
Add ordered-list formatting to the "Building Ceph" section of README.md.
(cherry picked from commit 1f21057e4166f2ea9f51ee037eb8e234c1390cfb) …
> squid: doc/README.md - add ordered list

- src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/inventory.po.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/orchestrator/workflow/11-inventory.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/inventory/inventory-devices/inventory-devices.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/administration/administration.component.html
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/breadcrumbs/breadcrumbs.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/breadcrumbs/breadcrumbs.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-modal/form-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table-actions/table-actions.component.html
- src/pybind/mgr/dashboard/frontend/src/styles/ceph-custom/_forms.scss
- Fix bs-modal getting hidden behind navbar
- Reuse the project name for tab title
- Readonly user shows an empty space in the administration dropdown
- Physical Disks Identify modal not opening up
- add e2e in cephadm to make sure the modal always comes up
- Primary action doesn't need to be displayed for the read-only user
Fixes: https://tracker.ceph.com/issues/67547
**BEFORE**
**AFTER** …
> mgr/dashboard: fix UI modal issues

- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts
Fixes: https://tracker.ceph.com/issues/68063 …
> mgr/dashboard: fix table filter

- src/pybind/mgr/cephadm/services/nvmeof.py
- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/nvmeof_cli.py
- src/pybind/mgr/dashboard/services/nvmeof_client.py
- src/pybind/mgr/dashboard/services/nvmeof_conf.py
backport tracker: https://tracker.ceph.com/issues/68041
---
backport of https://github.com/ceph/ceph/pull/59482
parent tracker: https://tracker.ceph.com/issues/67774
> squid: mgr/dashboard: add gw_groups support to nvmeof api 

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.ts
Fixes: https://tracker.ceph.com/issues/68024 …
> mgr/dashboard: fix start time format

- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts
Fixes: https://tracker.ceph.com/issues/68062 …
> mgr/dashboard: fix table column pipe transform

- qa/tasks/cephfs/test_mirroring.py
mount_b wasn't mounted with the remote filesystem.
- …
> qa: do the set/get attribute on the remote filesystem

- src/kv/RocksDBStore.cc
if relevant config settings result in no output. …
> kv/rocksdb: return error for dump_objectstore_kv_stats asok command

- qa/suites/orch/cephadm/workunits/task/test_monitoring_stack_basic.yaml
the v1 endpoint is deprecated and v2 is suggested to use.
Fixes: https://tracker.ceph.com/issues/67183
- Tracker …
> qa/task: update alertmanager endpoints version

- src/cephadm/cephadmlib/constants.py
- src/cephadm/tests/test_util_funcs.py
> squid: cephadm: update default image and latest stable release

- src/pybind/mgr/dashboard/controllers/host.py
https://tracker.ceph.com/issues/68101 …
> mgr/dashboard: remove orch required decorator from host UI router (list) 

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-details/pool-details.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/service.interface.ts
- src/pybind/mgr/dashboard/frontend/src/testing/unit-test-helper.ts
Backport trackers:
https://tracker.ceph.com/issues/68096
https://tracker.ceph.com/issues/68095
Backport of: https://github.com/ceph/ceph/pull/59805
Conflict in https://github.com/ceph/ceph/pull/59819/commits/d4fb21735a5112ff7121957fc86b68f07eea4682 due to SSO changes in service form which are not required to be backported
test faiulure due to usage of same spec name `enable_auth` for SSO and mTLS. Hence some extra modifications.
Comments below highlight the issues for the test failures.
<details>
- `jenkins …
> squid: mgr/dashboard: Nvme mTLS support and service name changes 

- src/crimson/osd/object_context.h
- src/crimson/osd/object_context_loader.cc
- src/crimson/osd/ops_executer.h
- src/crimson/osd/pg.cc
- src/crimson/osd/pg.h
- src/crimson/osd/pg_backend.cc
- src/osd/osd_types.h
Option 3 in https://tracker.ceph.com/issues/63844#note-8
Fixes: https://tracker.ceph.com/issues/63844 …
> crimson/osd/pg: do_osd_ops_execute fixes

- doc/man/8/rbd.rst
- qa/workunits/rbd/rbd_mirror.sh
- qa/workunits/rbd/rbd_mirror_bootstrap.sh
- qa/workunits/rbd/rbd_mirror_ha.sh
- qa/workunits/rbd/rbd_mirror_helpers.sh
- qa/workunits/rbd/rbd_mirror_stress.sh
- src/cls/rbd/cls_rbd.cc
- src/cls/rbd/cls_rbd_client.cc
- src/cls/rbd/cls_rbd_client.h
- src/include/rbd/librbd.h
- src/include/rbd/librbd.hpp
- src/librbd/api/Mirror.cc
- src/librbd/api/Mirror.h
- src/librbd/librbd.cc
- src/pybind/rbd/c_rbd.pxd
- src/pybind/rbd/mock_rbd.pxi
- src/pybind/rbd/rbd.pyx
- src/test/cli/rbd/help.t
- src/test/cls_rbd/test_cls_rbd.cc
- src/test/pybind/test_rbd.py
- src/test/rbd_mirror/test_mock_NamespaceReplayer.cc
- src/test/rbd_mirror/test_mock_PoolReplayer.cc
- src/tools/rbd/action/MirrorPool.cc
- src/tools/rbd_mirror/NamespaceReplayer.cc
- src/tools/rbd_mirror/NamespaceReplayer.h
- src/tools/rbd_mirror/PoolReplayer.cc
- src/tools/rbd_mirror/PoolReplayer.h
Allows mirroring of different namespaces between pools.
- …
> rbd-mirror: allow mirroring to a different namespace

- src/mon/NVMeofGwMap.cc
- src/mon/NVMeofGwMap.h
- src/mon/NVMeofGwMon.cc
- src/mon/NVMeofGwMon.h
> Gw no subsystems

- doc/dev/release-checklists.rst
> squid: doc/dev/release-checklist: check telemetry validation

- doc/dev/release-checklists.rst
https://docs.ceph.com/en/squid/dev/release-checklists/
- …
> squid: doc/dev/release-checklists.rst: enable rtd for squid

- src/cephadm/cephadmlib/constants.py
> cephadm: update LATEST_STABLE_RELEASE to squid

- .githubmap
- .mailmap
- .organizationmap
Add Naveen Naidu (@Naveenaidu) to mailmap, githubmap and organizationmap. This was recommended in the [ceph on-boarding docs](https://pad.ceph.com/p/ceph-team-onboarding#L148). 
<details> …
> mailmap, githubmap, organizationmap: add Naveen Naidu

- src/pybind/mgr/dashboard/controllers/host.py
backport tracker: https://tracker.ceph.com/issues/68127
backport of: https://github.com/ceph/ceph/pull/59823
parent tracker: https://tracker.ceph.com/issues/68101
(cherry picked from commit 21454d08484cefefef7803c250d4d0511ae4415b) …
> Reef: mgr/dashboard: remove orch required decorator from host UI router (list)

- src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/cluster.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster-review.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/components.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/wizard/wizard.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/wizard/wizard.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/wizard/wizard.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/wizard-steps.service.ts
- src/pybind/mgr/dashboard/frontend/src/styles/themes/_content.scss
Fixes: https://tracker.ceph.com/issues/68103 …
> mgr/dashboard: carbonize the wizard component

- src/pybind/mgr/dashboard/controllers/host.py
backport tracker: https://tracker.ceph.com/issues/68128
backport of: https://github.com/ceph/ceph/pull/59823
parent tracker: https://tracker.ceph.com/issues/68101
(cherry picked from commit 21454d08484cefefef7803c250d4d0511ae4415b) …
> Squid: mgr/dashboard: remove orch required decorator from host UI router (list)

- src/blk/kernel/KernelDevice.cc
Value discard_stop could be uninitialized.
Detected by:
https://pulpito.ceph.com/akupczyk-2024-08-02_13:56:25-rados-aclamk-testing-phoebe-2024-08-01-1249-distro-default-smithi/7832297/ …
> blk/kernel: Fix uninitialized discard_stop

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/iscsi-target-list/iscsi-target-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/active-alert-list/active-alert-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/rules-list/rules-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/silence-list/silence-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-realm-form/rgw-multisite-realm-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zonegroup-form/rgw-multisite-zonegroup-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.html
- src/pybind/mgr/dashboard/frontend/src/app/core/error/error.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/grafana/grafana.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/orchestrator-doc-panel/orchestrator-doc-panel.component.html
Fixes: https://tracker.ceph.com/issues/68098
Signed-off-by: Prachi prgoel@redhat.com
Fixes:
Fix space between the text in below sections
Observability/Alerts —> Active Alerts 
Observability/ Alerts —> Alerts 
Observability/Alerts —> Silences
Cluster/Pools —> overall performance
Cluster/Hosts/ —> overall performance  
Cluster/ OSDs —> overall performance
Block/iSCSI/ —> Targets
Object/Overview —> Multi-Site Sync Status
- When …
> mgr/dashboard: Fix space between the text in few sections 

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/block.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-gateway/nvmeof-gateway.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-gateway/nvmeof-gateway.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-gateway/nvmeof-gateway.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/daemon.interface.ts
- adds a group selection component for gateways
- fetch gateway using daemons info
- added tests
fixes https://tracker.ceph.com/issues/68135
[Screencast from 2024-09-19 15-35-09.webm](https://github.com/user-attachments/assets/44c5bcec-5927-4bbf-8c67-3c62a1bdf47c)
<details> …
> mgr/dashboard: List gateways in a group 

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-initiators-list/nvmeof-initiators-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/services.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-list/nfs-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/core/auth/role-list/role-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/doc/doc.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts
- fixes selectAll checkbox behavior in table
- fixes form modals in osd edit and role clone
- fixes single select highlight issue
- fix row getting automatically collapsed when search has any value
- fix nfs exports table list where bucket is not shown
- fix ceph user and rgw role page show/hide col issue
- fix listner addr and intiator col in nvme
Fixes: https://tracker.ceph.com/issues/68126
https://github.com/user-attachments/assets/dbd27ebe-ca65-46ea-b6ed-e4cf0a3cd53f
https://github.com/user-attachments/assets/e3f14c91-92c5-46f3-b77b-6c3fb5eb10e8
https://github.com/user-attachments/assets/47c648f3-71af-4e31-b65c-5897e622db15
https://github.com/user-attachments/assets/9dea95ba-7c34-4554-99f5-abe86dc34253
https://github.com/user-attachments/assets/52725d36-3a04-43e8-9e0f-288f9561733c …
> mgr/dashboard: fix checkbox selection and role clone modal

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.ts
backport tracker: https://tracker.ceph.com/issues/68145
---
backport of https://github.com/ceph/ceph/pull/58778
parent tracker: https://tracker.ceph.com/issues/67103
> reef: mgr/dashboard: Zone details showing incorrect data for data pool values and compression info for Storage Classes

- qa/suites/fs/upgrade/mds_upgrade_sequence/overrides/ignorelist_upgrade.yaml
Fixes: https://tracker.ceph.com/issues/67879 …
> upgrade/cephfs/mds_upgrade_sequence: ignore osds down 

- doc/index.rst
Currently the "Getting Started" link points at the install page, not the "Intro to Ceph" section, which seems more appropriate.
If you're happy with this, can it get backported to the still-supported releases, please?
(cherry picked from commit d257eacb05a463c93872ae8aa8210806affda4ec) …
> reef: doc: Update "Getting Started" to link to start not install

- src/crimson/common/gated.h
- src/crimson/mgr/client.cc
- src/crimson/mgr/client.h
- src/crimson/mon/MonClient.cc
- src/crimson/mon/MonClient.h
Fixes: https://tracker.ceph.com/issues/67773 …
> common/gated: enable ceph_assert on shard id

- qa/standalone/ceph-helpers.sh
Recent changes to the scrub scheduling mechanism, especially regarding the 'must_scrub' flag, cause operator scrub commands issued on a not-clean PG to be rejected - and forgotten.
This commit changes the tests to issue a scrub command only after the target PG is clean.
> test/scrub: only instruct clean PGs to scrub

- src/rgw/rgw_iam_policy.cc
Fixes: https://tracker.ceph.com/issues/68029 …
> rgw/rgw_iam_policy: Checking for dereference of a null pointer (loaded from variable 't')

- src/rgw/driver/rados/rgw_log_backing.cc
Fixes: https://tracker.ceph.com/issues/68031 …
> rgw_log_backing: error code not returned 

- src/compressor/QatAccel.cc
Fixes: https://tracker.ceph.com/issues/67631 …
> warn when QAT switches to software [de]compression

- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/orchestrator/_interface.py
- src/pybind/mgr/orchestrator/module.py
This is mostly intended for automation that wants to check for these certificates and handle the results themselves. Without this flag an exception will be logged which isn't great for automation tools that may check for this repeatedly …
> mgr/cephadm: add --no-exception-when-missing flag to cert-store cert/key get

- doc/cephadm/services/oauth2-proxy.rst
- src/pybind/mgr/cephadm/module.py
adding IMAGE to the end of the variable name to put it in line with all the other variables of this type
Fixes: https://tracker.ceph.com/issues/68119 …
> mgr/cephadm: update oauth2 proxy image variable name

- qa/tasks/nvme_loop.py
We must ensure BlueStore signatures are removed altogether since multiple BlueStore label replications have been introduced.
Fixes: https://tracker.ceph.com/issues/68171
> qa: remove all bluestore signatures on devices

- ceph.spec.in
> ceph.spec.in: we need jsonnet for all distroes for make check

- doc/mgr/nfs.rst
Update nfs doc for Kerberos setup of ganesha in Ceph , only for `FSAL_CEPH`
- …
> doc: update nfs doc for Kerberos setup of ganesha in Ceph

- src/pybind/mgr/dashboard/services/rgw_client.py
- src/python-common/ceph/rgw/rgwam_core.py
period update method currently uses default zonegroup/zone for period update commit. This PR is to use realm/zg/zone provided in the arguments for period update. Also modify the `set-rgw-credentials`command to save the initial "default" zone's access creds in the dashboard config even if a realm is created in the setup
Fixes: https://tracker.ceph.com/issues/67897
- When filling …
> mgr/rgwam: use realm/zonegroup/zone method arguments for period update

- src/pybind/mgr/dashboard/services/rgw_client.py
Fixes: https://tracker.ceph.com/issues/68161 …
> mgr/dashboard: update period after migrating to multi-site 

- src/pybind/mgr/dashboard/frontend/src/app/shared/api/prometheus.service.ts
Fixes: https://tracker.ceph.com/issues/68162
https://github.com/user-attachments/assets/f4986063-3de4-4daf-9ebb-230ee0ddb9ca …
> mgr/dashboard: fix handling NaN values in dashboard charts

- doc/mgr/nfs.rst
Signed-off-by: Avan Thakkar <athakkar@redhat.com>
(cherry picked from commit 0f6039f9afa223ad70601d4dc36fc99f6fd78b49) …
> squid: doc: update nfs doc for Kerberos setup of ganesha in Ceph

- doc/mgr/nfs.rst
Signed-off-by: Avan Thakkar <athakkar@redhat.com>
(cherry picked from commit 0f6039f9afa223ad70601d4dc36fc99f6fd78b49) …
> reef: doc: update nfs doc for Kerberos setup of ganesha in Ceph

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-snapshots-list/cephfs-subvolume-snapshots-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/constants/cephfs.ts
backport tracker: https://tracker.ceph.com/issues/68199
backport of: https://github.com/ceph/ceph/pull/59595
parent tracker: https://tracker.ceph.com/issues/67891 …
> Squid: mgr/dashboard: Cloning subvolume not listing _nogroup if no subvolume

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-snapshots-list/cephfs-subvolume-snapshots-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/constants/cephfs.ts
backport tracker: https://tracker.ceph.com/issues/68200
backport of: https://github.com/ceph/ceph/pull/59595
parent tracker: https://tracker.ceph.com/issues/67891 …
> reef: mgr/dashboard: Cloning subvolume not listing _nogroup if no subvolume

- src/ceph-volume/ceph_volume/devices/lvm/zap.py
BlueStore now writes its metadata at multiple offset on devices [1]. It means `ceph-volume lvm zap` doesn't remove BlueStore signature altogether. This can confuse ceph-volume when redeploying an OSD on a previously zapped device because there is still old BlueStore metadata on it.
ceph-volume should call `ceph-bluestore-tool zap-device` [2] in addition to the existing calls when wiping a device.
[1] https://github.com/ceph/ceph/pull/55374
[2] https://github.com/ceph/ceph/pull/59632
Fixes: https://tracker.ceph.com/issues/68035
> ceph-volume: add call to `ceph-bluestore-tool zap-device`

- src/pybind/mgr/orchestrator/module.py
- make service_id better alligned with default/empty group (https://github.com/ceph/ceph/commit/f6d552d7c777f1160545188dcffa6b685b05ca8a)
- fix service_id in nvmeof daemon add …
> pybind/mgr/orchestrator/module.py: NvmeofServiceSpec service_id

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.ts
- src/pybind/mgr/dashboard/services/rgw_client.py
backport tracker: https://tracker.ceph.com/issues/68216
backport of: #59820
parent tracker: https://tracker.ceph.com/issues/68097
<hr style="border:2px solid #eeeeee" />
https://tracker.ceph.com/issues/68097
Changes for this PR includes:
1) Populating the destination zones select option with a set of options to choose from, for flow and pipe so that user can't enter any invalid zone name 2) Provided zone option as 'All Zones (*)' in pipe, if user want to select all zones for source and destination zones 3) We are hiding the UniqueId column on sync policy table as we do not want to show it as this column is introduced just to uniquely identify a row in the table and should not be displayed to users as it is part of the internal logic to work. …
> Squid: mgr/dashboard: multisite sync policy improvements

- src/blk/BlockDevice.cc
- src/blk/BlockDevice.h
- src/blk/kernel/KernelDevice.cc
- src/blk/kernel/KernelDevice.h
- src/os/bluestore/BlueFS.cc
- src/os/bluestore/BlueFS.h
- src/os/bluestore/BlueStore.cc
> blk/kerneldevice: add perfcounter for block async discard

- src/pybind/mgr/dashboard/controllers/auth.py
- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade-progress/upgrade-progress.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/multisite-wizard-steps.enum.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/components.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/progress/progress.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/progress/progress.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/progress/progress.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/wizard/wizard.component.ts
- src/pybind/mgr/dashboard/services/rgw_client.py
- src/pybind/mgr/dashboard/services/service.py
- src/pybind/mgr/rgw/module.py
Fixes: https://tracker.ceph.com/issues/67829
Fixes: https://tracker.ceph.com/issues/67830
Multi-site with multi-cluster
https://github.com/user-attachments/assets/31583be1-3c4d-4c79-991d-539b22f439f7
Multi-site without multi-cluster
https://github.com/user-attachments/assets/b22dee94-6d3d-49ca-83e6-3c9d5d7828c7 …
> mgr/dashboard: Add progress step to multisite automation wizard

- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/services/monitoring.py
- src/pybind/mgr/cephadm/templates/services/prometheus/prometheus.yml.j2
- src/pybind/mgr/cephadm/tests/test_cephadm.py
- src/pybind/mgr/cephadm/tests/test_services.py
- src/pybind/mgr/dashboard/controllers/auth.py
- src/pybind/mgr/dashboard/controllers/multi_cluster.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-list/multi-cluster-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/multi-cluster.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/dashboard-promqls.enum.ts
- src/pybind/mgr/dashboard/module.py
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/orchestrator/_interface.py
- src/pybind/mgr/orchestrator/module.py
Add basic(username/password) authentication and TLS authentication to the newly added federate job in the prometheus config. This PR exposes a new endpoint to get the prometheus access info of the target cluster and sets it in the prometheus.yml file.
Fixes: https://tracker.ceph.com/issues/65057
Signed-off-by: Aashish Sharma [aasharma@redhat.com](mailto:aasharma@redhat.com) …
> mgr/dashboard: Add ssl prometheus federate

- src/pybind/mgr/dashboard/frontend/src/app/core/auth/auth.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/auth/role-form/role-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/checked-table-form/checked-table-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/checked-table-form/checked-table-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/checked-table-form/checked-table-form.component.ts
Fixes: https://tracker.ceph.com/issues/68123
Signed-off-by: Puja Shahu <pshahu@redhat.com> …
> mgr/dashboard: carbonize user management-role form

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-form/rbd-snapshot-form-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-form/rbd-snapshot-form-modal.component.ts
Fixes: https://tracker.ceph.com/issues/68198
Signed-off-by: Dnyaneshwari talwekar dtalweka@redhat.com
Tracker: https://tracker.ceph.com/issues/68198
https://github.com/user-attachments/assets/9f53e0a4-2288-42f5-9c1b-80f072d88bf3 …
> mgr/dashboard: Forbid snapshot name "." and any containing "/".

- doc/man/8/ceph-bluestore-tool.rst
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/os/bluestore/bluestore_tool.cc
Fixes:
https://tracker.ceph.com/issues/68217 …
> squid: ceph-bluestore-tool: Fixes for multilple bdev label

- src/test/rgw/bucket_notification/__init__.py
- src/test/rgw/bucket_notification/test_bn.py
Tests https://tracker.ceph.com/issues/67656
PR https://github.com/ceph/ceph/pull/59390 introduces the policy and this PR provides an integration test to verify the procedure. …
> test/rgw/notifications: integration test for the procedure of migrating an existing v2 topic to an account

- src/mon/Monitor.cc
Fixes: https://tracker.ceph.com/issues/64824 …
> mon/scrub: log error details of store access failures

- src/rgw/driver/rados/rgw_data_sync.cc
https://tracker.ceph.com/issues/63378 …
> rg/multisite: handle errors properly in RGWDataFullSyncSingleEntryCR()

- doc/_ext/ceph_releases.py
- doc/releases/index.rst
- doc/releases/releases.yml
- doc/releases/squid.rst
Add release notes for the first stable release of Ceph Squid (19.2.0).
- Component …
> doc: Add Squid 19.2.0 release notes

- src/common/options/mgr.yaml.in
- src/mon/PGMap.cc
Fixes: https://tracker.ceph.com/issues/63192 …
> src/mon/PGMap: raise POOL_APP_NOT_ENABLED after some time for new pool

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-form/rbd-snapshot-form-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-form/rbd-snapshot-form-modal.component.ts
backport tracker: https://tracker.ceph.com/issues/68276
backport of: https://github.com/ceph/ceph/pull/59946
parent tracker: https://tracker.ceph.com/issues/68198 …
> Squid: mgr/dashboard: Forbid snapshot name "." and any containing "/".

- src/osdc/Journaler.h
Fixes: 55652f0819761d410bddcf3688b1c3e10ed64f5b …
> osdc: fix mutex assert for !debug builds

- src/common/Formatter.cc
- src/common/Formatter.h
- src/test/common/test_json_formatter.cc
Fixes: https://tracker.ceph.com/issues/66215
Reference PR: https://github.com/ceph/ceph/pull/57695
- Tracker …
> common/Formatter: dump inf/nan as null

- doc/releases/squid.rst
Move three dashboard-related items from beneath a heading reading "CephFS" and put them beneath a heading reading "Dashboard".
Fixes: https://github.com/ceph/ceph/pull/59539#discussion_r1777960130 …
> doc/releases: move Dashboard items from CephFS

- src/mon/NVMeofGwMap.cc
- src/mon/NVMeofGwMon.cc
> mon/nvmeofgw*: fix tracking gateways in DELETING state

- doc/rados/troubleshooting/troubleshooting-pg.rst
Make grammar improvements (and correct a verb disagreement) in the section "Placement Groups Never Get Clean" in
doc/rados/troubleshooting/troubleshooting-pg.rst.
(cherry picked from commit 2baa027b13c0b4ac8b9fb864858a42e010ca8948) …
> squid: doc/rados: edit "Placement Groups Never Get Clean"

- doc/rados/troubleshooting/troubleshooting-pg.rst
Make grammar improvements (and correct a verb disagreement) in the section "Placement Groups Never Get Clean" in
doc/rados/troubleshooting/troubleshooting-pg.rst.
(cherry picked from commit 2baa027b13c0b4ac8b9fb864858a42e010ca8948) …
> reef: doc/rados: edit "Placement Groups Never Get Clean"

- doc/rados/troubleshooting/troubleshooting-pg.rst
Make grammar improvements (and correct a verb disagreement) in the section "Placement Groups Never Get Clean" in
doc/rados/troubleshooting/troubleshooting-pg.rst.
(cherry picked from commit 2baa027b13c0b4ac8b9fb864858a42e010ca8948) …
> quincy: doc/rados: edit "Placement Groups Never Get Clean"

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-form/rbd-snapshot-form-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-form/rbd-snapshot-form-modal.component.ts
backport tracker: https://tracker.ceph.com/issues/68275
backport of https://github.com/ceph/ceph/pull/59946
parent tracker: https://tracker.ceph.com/issues/68198 …
> reef: mgr/dashboard: Forbid snapshot name "." and any containing "/".

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zonegroup-form/rgw-multisite-zonegroup-form.component.html
Fixes: https://tracker.ceph.com/issues/68295
[screen-capture (31).webm](https://github.com/user-attachments/assets/f6bd14a4-4c7c-4637-82f2-68148d00a1d9) …
> mgr/dashboard: fix doc links in rgw-multisite

- qa/tasks/cephfs/test_misc.py
- src/mds/MDSRank.cc
Introduced-by: 0ef5941a2e79
Fixes: http://tracker.ceph.com/issues/68132
- Component …
> mds: invalid id for client eviction is to be treated as success

- src/tools/rbd/Utils.cc
Previously, "rbd create --mirror-image-mode journal" requires specifying the
journaling feature. Now the user specifying "--mirror-image-mode journal"
is enough of a cue to enable the journaling feature.
Fixes: http://tracker.ceph.com/issues/58683 …
> rbd: set journaling feature when --mirror-image-mode is journal

- doc/cephfs/cephfs-mirroring.rst
- qa/tasks/cephfs/test_mirroring.py
- src/tools/cephfs_mirror/PeerReplayer.cc
Fixes: https://tracker.ceph.com/issues/68131 …
> cephfs_mirror: revert sync_duration to seconds

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-contants.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-list/rbd-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-list/rbd-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/help-text/help-text.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table-actions/table-actions.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/cd-table-action.ts
Fixes:https://tracker.ceph.com/issues/67198
Signed-off-by: Prachi prgoel@redhat.com
Below are the changes:-
Delete option moved to last in list.
Delete is disabled in case image is not primary.
Move to trash should be second last option.
Tooltip is added for ‘Move to Trash’ and ‘Delete’
Tooltip is added for Copy option
Subheading is added for Copy Form.
Tooltip is added for ‘Flatten’ option. …
> mgr/dashboard: rbd table actions enhancements

- src/tools/rados/rados.cc
> tools/rados: allow to read setomapheader value from file

- src/mgr/Mgr.cc
backport tracker: https://tracker.ceph.com/issues/66889
---
backport of https://github.com/ceph/ceph/pull/57005
parent tracker: https://tracker.ceph.com/issues/66168
> quincy: mgr/Mgr.cc: clear daemon health metrics instead of removing down/out osd from daemon state

- doc/governance.rst
with the consent of my colleagues
- Dan van der Ster
- João Eduardo Luis
- Mark Nelson
changed their e-mail addresses to the current ones
Signed-off-by: Tobias Fischer <tobias.fischer@clyso.com>
Signed-off-by: Tobias Fischer <138117964+toficly@users.noreply.github.com>
(cherry picked from commit 180378b5adee303fe57ecd4951b0f0ff46afa5e1) …
> squid: doc:update e-mail addresses governance

- doc/governance.rst
with the consent of my colleagues
- Dan van der Ster
- João Eduardo Luis
- Mark Nelson
changed their e-mail addresses to the current ones
Signed-off-by: Tobias Fischer <tobias.fischer@clyso.com>
Signed-off-by: Tobias Fischer <138117964+toficly@users.noreply.github.com>
(cherry picked from commit 180378b5adee303fe57ecd4951b0f0ff46afa5e1) …
> reef: doc:update e-mail addresses governance

- doc/governance.rst
with the consent of my colleagues
- Dan van der Ster
- João Eduardo Luis
- Mark Nelson
changed their e-mail addresses to the current ones
Signed-off-by: Tobias Fischer <tobias.fischer@clyso.com>
Signed-off-by: Tobias Fischer <138117964+toficly@users.noreply.github.com>
(cherry picked from commit 180378b5adee303fe57ecd4951b0f0ff46afa5e1) …
> quincy: doc:update e-mail addresses governance

- qa/suites/rbd/iscsi/0-single-container-host.yaml
- qa/suites/rbd/iscsi/base/install.yaml
- qa/suites/rbd/iscsi/supported-container-hosts$
- qa/tasks/ceph_iscsi_client.py
- src/test/cli-integration/rbd/gwcli_create.t
- src/test/cli-integration/rbd/gwcli_delete.t
- src/test/cli-integration/rbd/iscsi_client.t
> qa/suites/rbd/iscsi: enable all supported container hosts

- src/mon/NVMeofGwMap.cc
>  mon/nvmeofgw*:fix monitor database corruption upon add gw

- qa/standalone/scrub/osd-scrub-test.sh
To prevent test timeouts.
Also - remove a failing assertion on a specific 'pg query' output, as it is not central to the test.
Backport of https://github.com/ceph/ceph/pull/59944.
Original tracker: https://tracker.ceph.com/issues/61385
Backport tracker: https://tracker.ceph.com/issues/68219
(cherry picked from commit 6850bce554330d09f476d4e2aa8ac6d5e3f8bf12)
Conflict resolution:
- removed references to perf counters (not part of the original fix)
- related conf values in TEST_scrub_test - not removed (as directly related)
> reef: qa/standalone/scrub: increase status updates frequency

- src/ceph-volume/ceph_volume/devices/lvm/zap.py
backport tracker: https://tracker.ceph.com/issues/68220
---
backport of https://github.com/ceph/ceph/pull/59742
parent tracker: https://tracker.ceph.com/issues/68035
> squid: ceph-volume: add call to `ceph-bluestore-tool zap-device`

- src/common/options/rgw.yaml.in
- src/rgw/rgw_appmain.cc
backport tracker: https://tracker.ceph.com/issues/65340
backport of https://github.com/ceph/ceph/pull/56645
parent tracker: https://tracker.ceph.com/issues/65277 …
> reef: rgw: update options yaml file so LDAP uri isn't an invalid example

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
Fixes: https://tracker.ceph.com/issues/68290
Signed-off-by: Dnyaneshwari talwekar <dtalweka@redhat.com>
Solution -> Replacing Bootstrap Modal Service (ModalService) with Carbon Modal Service (ModalCdsService)
https://github.com/user-attachments/assets/7ca8f80f-7c70-4b24-8d74-378756f95de2 …
> mgr/dashboard: Unable to delete realm via dashboard

- .githubmap
- .mailmap
- .organizationmap
Adding Shweta Bhosale to mailmap, githubmap and organizationmap as per the onboarding docs
<details>
</details>
> mailmap, githubmap, organisationmap: Add Shweta

- qa/suites/rbd/iscsi/0-single-container-host.yaml
- qa/suites/rbd/iscsi/base/install.yaml
- qa/suites/rbd/iscsi/supported-container-hosts$
- qa/tasks/ceph_iscsi_client.py
- src/test/cli-integration/rbd/gwcli_create.t
- src/test/cli-integration/rbd/gwcli_delete.t
- src/test/cli-integration/rbd/iscsi_client.t
backport tracker: https://tracker.ceph.com/issues/68365
---
backport of https://github.com/ceph/ceph/pull/60005
parent tracker: https://tracker.ceph.com/issues/68213
> reef: qa/suites/rbd/iscsi: enable all supported container hosts

- src/pybind/mgr/smb/handler.py
This fix resolves the "list index out of range" error that occurs when the earmark is simply "smb". 
The issue was caused by attempting to access an index beyond the available elements in the earmark string. 
A parsing function is now used to handle the earmark safely, ensuring correct behavior even when there are no additional scopes present. …
> mgr/smb: fix condition for smb earmark when cluster_id doesn't match

- src/global/global_init.cc
Fixes: https://tracker.ceph.com/issues/40692 …
> global: Call getnam_r with a 64KiB buffer on the heap

- src/rgw/driver/rados/rgw_data_sync.cc
> rgw/multisite: avoid redundant error repo entry logging

- src/pybind/mgr/cephadm/templates/services/mgmt-gateway/external_server.conf.j2
- src/pybind/mgr/cephadm/templates/services/mgmt-gateway/internal_server.conf.j2
- src/python-common/ceph/deployment/service_spec.py
> mgr/cephadm: adding health check endpoint for mgmt-gateway

- doc/governance.rst
Update Zac Dover's email address. …
> doc/governance: add Zac Dover's updated email

- README.md
This effort was started long time ago by @Thingee .[1] I now completed the remaining steps to achieve the Passing level of the OpenSSF Best Practices Badge.[2]
[![OpenSSF Best Practices](https://www.bestpractices.dev/projects/2220/badge)](https://www.bestpractices.dev/projects/2220)
It should be used as an opportunity to implement best practices in the Ceph community. For example, the Passing level was achieved without meeting the optional compliance with Dynamic Analysis or Security Scanning.
[1] https://www.bestpractices.dev/en/projects/2220
[2] https://www.bestpractices.dev/en/criteria/0 …
> README: add OpenSSF Best Practices Badge

- doc/governance.rst
Update Zac Dover's email address.
(cherry picked from commit 322c1a792062a72e958a9cfbd6a24a3e7333908d) …
> squid: doc/governance: add Zac Dover's updated email

- doc/governance.rst
Update Zac Dover's email address.
(cherry picked from commit 322c1a792062a72e958a9cfbd6a24a3e7333908d) …
> reef: doc/governance: add Zac Dover's updated email

- doc/governance.rst
Update Zac Dover's email address.
(cherry picked from commit 322c1a792062a72e958a9cfbd6a24a3e7333908d) …
> quincy: doc/governance: add Zac Dover's updated email

- doc/governance.rst
Add the Ceph Executive Council's responsibilties to the doc/governance.rst document. It was decided during the weekly CLT meeting on 30 Sep 2024 to add this to the ceph/ceph git repository. …
> doc/governance: add exec council responsibilites

- doc/governance.rst
Add the Ceph Executive Council's responsibilties to the doc/governance.rst document. It was decided during the weekly CLT meeting on 30 Sep 2024 to add this to the ceph/ceph git repository.
(cherry picked from commit 31a5d5f2f97b8fb6a0cd560fe510dbb95f637f3b) …
> squid: doc/governance: add exec council responsibilites

- doc/governance.rst
Add the Ceph Executive Council's responsibilties to the doc/governance.rst document. It was decided during the weekly CLT meeting on 30 Sep 2024 to add this to the ceph/ceph git repository.
(cherry picked from commit 31a5d5f2f97b8fb6a0cd560fe510dbb95f637f3b) …
> reef: doc/governance: add exec council responsibilites

- qa/tasks/cephfs/test_mirroring.py
- src/tools/cephfs_mirror/PeerReplayer.cc
Fixes: https://tracker.ceph.com/issues/64711
Fixes: https://tracker.ceph.com/issues/65115 …
> cephfs_mirror, qa: fix test failure test_cephfs_mirror_cancel_mirroring_and_readd

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
Fixes: https://tracker.ceph.com/issues/68307
https://github.com/user-attachments/assets/c57a461c-79e0-437a-a1ef-92bbd4f24b91 …
> mgr/dashboard: Do not display restart gateway message on completion of Setup Multisite Replication wizard

- doc/cephadm/services/smb.rst
We support SMB2, SMB2.1 and SMB 3 at the moment. We are not limited to just SMB3 as noted in the documentation.
- …
> doc: remove note for smb3 support

- qa/workunits/rbd/luks-encryption.sh
- src/librbd/crypto/LoadRequest.cc
- src/librbd/crypto/LoadRequest.h
> librbd/crypto/LoadRequest: clone format for migration source image

- src/blk/aio/aio.cc
- src/blk/aio/aio.h
- src/blk/kernel/KernelDevice.cc
- src/blk/kernel/io_uring.cc
- src/blk/kernel/io_uring.h
- src/test/objectstore/store_test.cc
Parent tracker: https://tracker.ceph.com/issues/64966
Backport tracker: https://tracker.ceph.com/issues/67036
Backports: https://github.com/ceph/ceph/pull/56352 …
> quincy: blk/aio: fix long batch (64+K entries) submission

- src/test/objectstore/store_test.cc
Fixes: https://tracker.ceph.com/issues/67838 …
> quincy: test/store_test: enforce sync compactions for spillover tests

- doc/governance.rst
Revert the commit (manually, by restoring the file by hand to the state it was in prior to d7c144c) to the state that it was in before I added the Executive Council Responsibilities document to governance.rst. This document cannot be edited at will, but must be voted on by the Leadership Team. …
> doc/governance: revert d7c144c0d7e490bfda9715a0c8462bb67cffc764

- src/common/ceph_mutex.h
- src/common/config_proxy.h
- src/common/mutex_debug.h
- src/osdc/Journaler.h
- src/test/common/test_mutex_debug.cc
> common: assert debug mutex lock is not held if !recursive

- src/mds/CInode.cc
Fixes: https://tracker.ceph.com/issues/68243 …
> mds: do not dump empty bufptr

- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/openapi.yaml
This was missed in the previous implementation …
> mgr/dashboard: add gw_groups to all nvmeof endpoints

- qa/cephfs/overrides/pg_health.yaml
> qa: ignore pg availability/degraded warnings

- doc/governance.rst
> doc: fix email

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rgw_client.py
Show non default realm sync status in rgw overview page
Fixes: https://tracker.ceph.com/issues/68329
https://github.com/user-attachments/assets/945921cf-d08a-4b21-a1b3-023b491547b1 …
> mgr/dashboard: show non default realm sync status in rgw overview page

- src/pybind/mgr/dashboard/services/rgw_client.py
Fixes: https://tracker.ceph.com/issues/68376
https://github.com/user-attachments/assets/5408fe12-ca4a-4ca4-ab72-922d08c4e23a …
> mgr/dashboard: fix gateways section error:”404 - Not Found RGW Daemon not found: None”

- src/common/cohort_lru.h
In file included from src/rgw/driver/posix/bucket_cache.h:19,
from src/test/rgw/test_posix_bucket_cache.cc:4:
src/common/cohort_lru.h: In member function _void cohort::lru::TreeX<T, TTree, CLT, CEQ, K, LK>::lock()_: src/common/cohort_lru.h:334:14: error: _for_each_ is not a member of _std_
334 |         std::for_each(locks.begin(), locks.end(),
|              ^~~~~~~~
src/common/cohort_lru.h: In member function _void cohort::lru::TreeX<T, TTree, CLT, CEQ, K, LK>::unlock()_:
/home/yuvalif/ceph5/src/common/cohort_lru.h:339:14: error: _for_each_ is not a member of _std_
339 |         std::for_each(locks.begin(), locks.end(),
|              ^~~~~~~~
<details>
<summary>Show …
> test/rgw/posix: missing std include with GCC 14

- src/crimson/os/futurized_store.h
- src/crimson/os/seastore/cached_extent.cc
- src/crimson/os/seastore/cached_extent.h
- src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.h
- src/crimson/os/seastore/onode_manager/staged-fltree/node_layout.h
- src/crimson/os/seastore/seastore.cc
- src/crimson/os/seastore/seastore.h
- src/crimson/os/seastore/seastore_types.cc
- src/crimson/os/seastore/transaction_manager.cc
- src/crimson/os/seastore/transaction_manager.h
- src/osd/osd_types_fmt.h
Follow up https://github.com/ceph/ceph/pull/59506
This should make the debug logs easier to understand about what SeaStore is doing. …
> crimson/os/seastore: refine seastore and transaction_manager logs, cleanups

- qa/suites/crimson-rados/perf/deploy/ceph.yaml
cbt use ssh connection by defualt, without ssh_keys the task won't generate public key and the cbt task will fail
Fixes: https://tracker.ceph.com/issues/68421 …
> qa/suites/crimson-rados/perf: add ssh keys

- qa/cephfs/overrides/ignorelist_health.yaml
Fixes: https://tracker.ceph.com/issues/68283 …
> qa: do not fail cephfs QA tests for slow bluestore ops

- doc/governance.rst
Signed-off-by: Ernesto Puerta <37327689+epuertat@users.noreply.github.com>
(cherry picked from commit 512eea1af52126e9b082744ee7b870c12c23d55d) …
> squid: doc: fix email

- doc/governance.rst
Signed-off-by: Ernesto Puerta <37327689+epuertat@users.noreply.github.com>
(cherry picked from commit 512eea1af52126e9b082744ee7b870c12c23d55d) …
> reef: doc: fix email

- doc/governance.rst
Signed-off-by: Ernesto Puerta <37327689+epuertat@users.noreply.github.com>
(cherry picked from commit 512eea1af52126e9b082744ee7b870c12c23d55d) …
> quincy: doc: fix email

- qa/suites/nvmeof/basic/workloads/nvmeof_initiator.yaml
- qa/suites/nvmeof/basic/workloads/nvmeof_namespaces.yaml
- qa/suites/nvmeof/basic/workloads/nvmeof_scalability.yaml
- qa/suites/nvmeof/thrash/gateway-initiator-setup/3-subsys-60-namespace.yaml
- qa/workunits/nvmeof/setup_subsystem.sh
> qa/suites/nvmeof: Fix broken suite by using --no-group-append tag

- qa/suites/upgrade/reef-x/parallel/0-start.yaml
- qa/suites/upgrade/reef-x/parallel/1-tasks.yaml
Fixes: https://tracker.ceph.com/issues/67182 …
> qa/rados/upgrade: ignore PG_DEGRADED

- src/pybind/mgr/dashboard/services/rgw_client.py
backport tracker: https://tracker.ceph.com/issues/68479
---
backport of https://github.com/ceph/ceph/pull/60101
parent tracker: https://tracker.ceph.com/issues/68376
> squid: mgr/dashboard: fix gateways section error:”404 - Not Found RGW Daemon not found: None”

- doc/man/8/rbd.rst
Updates the rbd man page to clarify  that some mirror commands can apply to pools and namespaces.
(cherry picked from commit 5e64748927d029ceffc27edbc6cbf7c774a7b291) …
> reef: doc/rbd: add namespace information for mirror commands

- src/crimson/osd/osd.cc
- src/crimson/osd/osd.h
- src/crimson/osd/pg.cc
- src/crimson/osd/pg.h
> crimson/osd: purge strays when PGs go clean

- src/crimson/osd/backfill_state.cc
Fixes: https://tracker.ceph.com/issues/68175 …
> crimson/osd/backfill_state: do at least one time of replica scanning if necessary in the Enqueuing state

- src/crimson/osd/backfill_facades.h
- src/crimson/osd/backfill_state.cc
- src/crimson/osd/backfill_state.h
- src/crimson/osd/pg_recovery.cc
- src/crimson/osd/pg_recovery.h
- src/test/crimson/test_backfill.cc
Fixes: https://tracker.ceph.com/issues/67874 …
> crimson/osd/backfill_state: add the object to be pushed in the peer missing set of PeeringState

- qa/tasks/mgr/dashboard/test_osd.py
- src/pybind/mgr/dashboard/controllers/osd.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/osd.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/osd.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/paginate.model.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/classes/paginate-params.class.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/cd-table-fetch-data-context.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/osd.model.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/tests/test_osd.py
Fixes: https://tracker.ceph.com/issues/56511 …
> mgr/dashboard: introduce server side pagination for osds

- doc/dev/developer_guide/essentials.rst
Remove mention of "Stable Releases and Backports" from doc/dev/developer_guide/essentials.rst.
(cherry picked from commit 95916c91906604c516e78b550010e9de511fc1e9) …
> squid: doc/dev: remove "Stable Releases and Backports"

- doc/dev/developer_guide/essentials.rst
Remove mention of "Stable Releases and Backports" from doc/dev/developer_guide/essentials.rst.
(cherry picked from commit 95916c91906604c516e78b550010e9de511fc1e9) …
> reef: doc/dev: remove "Stable Releases and Backports"

- doc/dev/developer_guide/essentials.rst
Remove mention of "Stable Releases and Backports" from doc/dev/developer_guide/essentials.rst.
(cherry picked from commit 95916c91906604c516e78b550010e9de511fc1e9) …
> quincy: doc/dev: remove "Stable Releases and Backports"

- SubmittingPatches-backports.rst
Remove all references to the "Stable Releases and Backports Team", which as of October 2024 does not exist.
Fixes: https://tracker.ceph.com/issues/68471
(cherry picked from commit 0317b5f87ac22399f6242d72f0bb9924794687de) …
> reef: doc: SubmittingPatches-backports - remove backports team

- src/crimson/osd/pg.cc
- src/crimson/osd/shard_services.cc
Fixes: https://tracker.ceph.com/issues/68174 …
> crimson/osd/pg: remove snapmapper objects when eventually removing collections at the last moment of pg deleting, just as pg meta objects

- doc/governance.rst
Congratulations!
Election: https://vote.heliosvoting.org/helios/elections/f276a15a-84c5-11ef-a0e4-b69e035002b0/view …
> doc/governance: add new CSC members

- .github/labeler.yml
> labeler: add nvmeof labelers

- src/os/bluestore/BlueFS.cc
- src/os/bluestore/BlueFS.h
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/test/objectstore/store_test.cc
Parent tracker: https://tracker.ceph.com/issues/62401
Backport of: https://github.com/ceph/ceph/pull/54102
Backport tracker: https://tracker.ceph.com/issues/63813 …
> quincy: test/store_test: refactor spillover tests

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rgw_client.py
backport tracker:  https://tracker.ceph.com/issues/68520
backport of: #60147
parent tracker: https://tracker.ceph.com/issues/68387
https://github.com/user-attachments/assets/cb11f29e-cdae-4b9c-aacf-02c1b5441e0c …
> Squid: mgr/dashboard: unable to edit pipe config for bucket level policy of bucket

- src/pybind/mgr/dashboard/controllers/ceph_users.py
- src/pybind/mgr/dashboard/openapi.yaml
Fixes: https://tracker.ceph.com/issues/67224
(cherry picked from commit d8ce3dae808392e19a4be2e89a132d833a70ee84) …
> squid: mgr/dashboard: fix ceph-users api doc             

- doc/radosgw/notifications.rst
- doc/radosgw/s3/bucketops.rst
Fixes: https://tracker.ceph.com/issues/63530
Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>
(cherry picked from commit 4ea87307e7af088dc056c1c7785aef7ca9be78b1) …
> reef: doc/rgw/notifications: specify which event types are enabled by default

- .githubmap
- .mailmap
- .organizationmap
- .peoplemap
- doc/governance.rst
> doc,mailmap: update my email / association to ibm

- src/osd/PG.cc
```
https://github.com/ceph/ceph/pull/58868 introduced SnapMapper::update_snap_map
to be used both by Crimson and Classic.
No change in behavior.
``` …
> osd/PG: make use of SnapMapper::update_snap_map

- doc/dev/radosgw/bucket_index.rst
a177935165e83a1bec2cc731e128f585fce75acd moved rgw_rados.cc and rgw_reshard.cc into src/rgw/driver/rados/
<details>
</details>
> doc/dev/radosgw: update paths that moved under src/rgw/driver/rados/

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.ts
Fixes: https://tracker.ceph.com/issues/68355
Fixes Includes: Added default zonegroup name with the sync policy details
**BEFORE:**
**AFTER:** …
> mgr/dashboard: sync policy's in Object >> Multi-site >> Sync-policy does not show the zonegroup to which policy belongs to  

- doc/dev/cephfs-mirroring.rst
* Updates the snapdiff feature and it's url. …
> doc: update Key Idea in cephfs-mirroring.rst

- src/pybind/mgr/dashboard/services/nvmeof_conf.py
- src/pybind/mgr/dashboard/services/orchestrator.py
backport tracker: https://tracker.ceph.com/issues/68410
---
backport of https://github.com/ceph/ceph/pull/59870
parent tracker: https://tracker.ceph.com/issues/68141
> squid: mgr/dashboard: ignore exceptions raised when no cert/key found

- doc/dev/cephfs-mirroring.rst
Updates the snapdiff feature and it's url.
(cherry picked from commit 629922bf6a0905cc87707f5e2d027f6320aafd99) …
> squid: doc: update Key Idea in cephfs-mirroring.rst

- src/pybind/mgr/cephadm/services/smb.py
Fixes: https://tracker.ceph.com/issues/68527
Signed-off-by: Avan Thakkar <athakkar@redhat.com> …
> mgr/cephadm: add ok_to_stop func for smb service

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.ts
Fixes: https://tracker.ceph.com/issues/68355
Fixes Includes: Added default zonegroup name with the sync policy details
Signed-off-by: Naman Munet <namanmunet@li-ff83bccc-26af-11b2-a85c-a4b04bfb1003.ibm.com>
(cherry picked from commit 517ab013e2a9bd23b482134121bcb85c5a32f028) …
> Squid: mgr/dashboard: sync policy's in Object >> Multi-site >> Sync-policy, does not show the zonegroup to which policy belongs to

- container/Containerfile
> quincy: ceph-node-proxy not present, not part of container

- .githubmap
- .mailmap
- .organizationmap
- .peoplemap
- doc/governance.rst
> reef: doc,mailmap: update my email / association to ibm

- .githubmap
- .mailmap
- .organizationmap
- Afreen Misbah
- Dnyaneshwari Talwekar
- Naman Munet
- Prachi Goel
- Puja Shahu
<details>
</details>
> mailmap: Add dashboard new joinees in maps

- src/pybind/mgr/volumes/fs/operations/versions/metadata_manager.py
- src/pybind/mgr/volumes/fs/operations/versions/subvolume_v1.py
Introduced by: https://github.com/ceph/ceph/pull/55838#discussion_r1573655512 and https://github.com/ceph/ceph/pull/55838#issuecomment-2178673729
Fixes: https://tracker.ceph.com/issues/66815 …
> mgr/vol : shortening the name of helper method

- doc/radosgw/index.rst
- doc/radosgw/uadk-accel.rst
The #58336 to support UADK in Ceph compressor zlib is merged, this PR is to submit a document for for the UADK and Ceph integration work. …
> Compressor: Add UADK document

- src/common/Thread.cc
- src/common/Thread.h
- src/log/Entry.h
- src/log/Log.cc
> squid: log: save/fetch thread name infra

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/xml.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/json-to-xml.service.ts
- src/pybind/mgr/dashboard/services/rgw_client.py
backport tracker: https://tracker.ceph.com/issues/68597
---
backport of https://github.com/ceph/ceph/pull/60173
parent tracker: https://tracker.ceph.com/issues/68434
> squid: mgr/dashboard: fix lifecycle issues

- src/pybind/mgr/dashboard/frontend/i18n.config.json
- src/pybind/mgr/dashboard/frontend/src/locale/messages.cs.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.de-DE.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.es-ES.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.fr-FR.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.id-ID.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.it-IT.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.ja-JP.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.ko-KR.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.pl-PL.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.pt-BR.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.zh-CN.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.zh-TW.xlf
not a backport, missed this on the release so its reef based commit
> reef: mgr/dashboard: update translations for reef

- src/pybind/mgr/mgr_util.py
> mgr/mgr_util: improvements for RTimer

- qa/tasks/cephfs/test_volumes.py
snapshot is retained despite of deletion (using --retain-snapshots option of "subvolume rm" command).
Fixes: https://tracker.ceph.com/issues/67988 …
> qa/cephfs: test clone progress reporter after subvol is deleted but...      

- qa/suites/orch/cephadm/workunits/task/test_mgmt_gateway.yaml
New mgmt-gateway (https://github.com/ceph/ceph/pull/57535) Teuthology test scenario
> mgmt-gateway: add e2e testing

- PendingReleaseNotes
- doc/cephfs/administration.rst
- doc/cephfs/troubleshooting.rst
- qa/tasks/cephfs/filesystem.py
- qa/tasks/cephfs/test_admin.py
- src/mon/FSCommands.cc
- src/mon/MDSMonitor.cc
- src/mon/MDSMonitor.h
Fixes: https://tracker.ceph.com/issues/66301 …
> mon,cephfs: require confirmation when changing max_mds on unhealthy cluster

- .githubmap
- .mailmap
- .organizationmap
- .peoplemap
- doc/governance.rst
> squid: doc,mailmap: update my email / association to ibm

- qa/workunits/rbd/luks-encryption.sh
- src/librbd/crypto/LoadRequest.cc
- src/librbd/crypto/LoadRequest.h
backport tracker: https://tracker.ceph.com/issues/68432
---
backport of https://github.com/ceph/ceph/pull/60109
parent tracker: https://tracker.ceph.com/issues/63184
> reef: librbd/crypto/LoadRequest: clone format for migration source image

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-snapshots-list/cephfs-subvolume-snapshots-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/constants/cephfs.ts
Fixes: https://tracker.ceph.com/issues/68623
Signed-off-by: Dnyaneshwari Talwekar <dtalweka@redbat.com>
- Tracker …
> mgr/dashboard: Removing duplicate cephfs constant file & importing correct default_subvolumegroup.

- monitoring/ceph-mixin/prometheus_alerts.libsonnet
- monitoring/ceph-mixin/prometheus_alerts.yml
- monitoring/ceph-mixin/tests_alerts/test_alerts.yml
- monitoring/ceph-mixin/tox.ini
Following PR https://github.com/ceph/ceph/pull/55495 fixing the dashboard in regards to multiple clusters storing their metrics in a single Prometheus instance, this PR addresses the issues for alerts.
Fixes: https://tracker.ceph.com/issues/64321 …
> Add multi-cluster support (showMultiCluster=True) to alerts

- doc/dev/kclient.rst
Specifically, an opinionated walkthrough of how to setup an environment for a built kernel, networking a VM to sepia, and mounting a remote Ceph cluster. …
> doc/dev: add walkthrough for CephFS kernel development

- src/mds/MDCache.cc
- src/mds/Server.cc
Backport PR https://tracker.ceph.com/issues/67163.
This will fix the crash bug in https://tracker.ceph.com/issues/66967. Just drop the batch head ref before dropping all the `mdr` pins when killing the `mdr. …
> quincy: mds: try to choose a new batch head in request_clientup()

- qa/workunits/rbd/luks-encryption.sh
- src/librbd/api/Migration.cc
- src/librbd/io/ReadResult.cc
- src/librbd/io/ReadResult.h
- src/librbd/migration/FileStream.cc
- src/librbd/migration/FormatInterface.h
- src/librbd/migration/HttpClient.cc
- src/librbd/migration/ImageDispatch.cc
- src/librbd/migration/ImageDispatch.h
- src/librbd/migration/NativeFormat.cc
- src/librbd/migration/NativeFormat.h
- src/librbd/migration/OpenSourceImageRequest.cc
- src/librbd/migration/OpenSourceImageRequest.h
- src/librbd/migration/QCOWFormat.cc
- src/librbd/migration/QCOWFormat.h
- src/librbd/migration/RawFormat.cc
- src/librbd/migration/RawFormat.h
- src/librbd/migration/RawSnapshot.cc
- src/librbd/migration/SourceSpecBuilder.cc
- src/librbd/migration/SourceSpecBuilder.h
- src/test/librbd/migration/test_mock_QCOWFormat.cc
- src/test/librbd/migration/test_mock_RawFormat.cc
backport tracker: https://tracker.ceph.com/issues/67441
---
backport of https://github.com/ceph/ceph/pull/58882 and https://github.com/ceph/ceph/pull/44366
parent tracker: https://tracker.ceph.com/issues/53674
> squid: librbd/crypto: fix issue when live-migrating from encrypted export

- qa/workunits/rbd/luks-encryption.sh
- src/librbd/api/Migration.cc
- src/librbd/crypto/LoadRequest.cc
- src/librbd/crypto/LoadRequest.h
- src/librbd/io/ReadResult.cc
- src/librbd/io/ReadResult.h
- src/librbd/migration/FileStream.cc
- src/librbd/migration/FormatInterface.h
- src/librbd/migration/HttpClient.cc
- src/librbd/migration/ImageDispatch.cc
- src/librbd/migration/ImageDispatch.h
- src/librbd/migration/NativeFormat.cc
- src/librbd/migration/NativeFormat.h
- src/librbd/migration/OpenSourceImageRequest.cc
- src/librbd/migration/OpenSourceImageRequest.h
- src/librbd/migration/QCOWFormat.cc
- src/librbd/migration/QCOWFormat.h
- src/librbd/migration/RawFormat.cc
- src/librbd/migration/RawFormat.h
- src/librbd/migration/RawSnapshot.cc
- src/librbd/migration/SourceSpecBuilder.cc
- src/librbd/migration/SourceSpecBuilder.h
- src/test/librbd/migration/test_mock_QCOWFormat.cc
- src/test/librbd/migration/test_mock_RawFormat.cc
backport tracker: https://tracker.ceph.com/issues/68433
---
backport of https://github.com/ceph/ceph/pull/60109
parent tracker: https://tracker.ceph.com/issues/63184
> squid: librbd/crypto/LoadRequest: clone format for migration source image

- src/mds/Beacon.cc
This used to be part of https://github.com/ceph/ceph/pull/60320
> mds/Beacon: set a thread name

- src/msg/Message.h
- src/msg/async/AsyncConnection.cc
- src/msg/async/AsyncConnection.h
- src/msg/async/Event.h
- src/msg/async/ProtocolV1.cc
- src/msg/async/ProtocolV1.h
- src/msg/async/ProtocolV2.cc
- src/msg/async/ProtocolV2.h
- src/msg/async/frames_v2.cc
> msg: Code cleanup and optimizations

- src/common/HeartbeatMap.cc
- src/common/HeartbeatMap.h
- src/common/LRUSet.h
- src/common/SloppyCRCMap.cc
- src/common/TrackedOp.h
- src/common/config.cc
- src/common/config_obs_mgr.h
- src/common/intrusive_lru.h
- src/common/options.h
- src/mon/ConfigMap.cc
- src/mon/MgrMonitor.cc
common-specific parts of https://github.com/ceph/ceph/pull/60175 (split upon @batrick's request)
> common: Various optimizations

- src/mds/CDir.cc
- src/mds/MDCache.cc
- src/mds/MDCache.h
MDS-specific parts of https://github.com/ceph/ceph/pull/60175 (split upon @batrick's request)
> MDS: Small optimizations

- doc/cephfs/fs-volumes.rst
Rearranging the documentation to align it with CephFS encapsulation design.
- …
> doc/cephfs: rearrange subvolume group information

- doc/cephadm/services/smb.rst
s/orch apply/ceph orch apply/ in a command where "ceph" was missing.
This was reported by Eugen Block to Zac Dover on 22 Oct 2024 through Slack.
(cherry picked from commit c42066766428c72884ed6f5dd6fa88244f436a1f) …
> squid: doc/cephadm: correct "ceph orch apply" command

- doc/cephfs/fs-volumes.rst
Rearranging the documentation to align it with CephFS encapsulation design.
Signed-off-by: Indira Sawant <indira.sawant@ibm.com>
(cherry picked from commit f6cf7ae5281f5740ac78bfa5e2a22913353b8167) …
> reef: doc/cephfs: rearrange subvolume group information

- doc/cephfs/fs-volumes.rst
Rearranging the documentation to align it with CephFS encapsulation design.
Signed-off-by: Indira Sawant <indira.sawant@ibm.com>
(cherry picked from commit f6cf7ae5281f5740ac78bfa5e2a22913353b8167) …
> quincy: doc/cephfs: rearrange subvolume group information

- doc/cephfs/fs-volumes.rst
Rearranging the documentation to align it with CephFS encapsulation design.
Signed-off-by: Indira Sawant <indira.sawant@ibm.com>
(cherry picked from commit f6cf7ae5281f5740ac78bfa5e2a22913353b8167) …
> squid: doc/cephfs: rearrange subvolume group information

- qa/suites/nvmeof/basic/workloads/nvmeof_mtls.yaml
- qa/tasks/nvmeof.py
- qa/workunits/nvmeof/mtls_test.sh
Also add qa/workunits/nvmeof/mtls_test.sh which enables mtls config and redeploy, then verify and disables mtls config. …
> qa/suites/nvmeof: add mtls test

- PendingReleaseNotes
- doc/cephfs/fs-volumes.rst
- doc/cephfs/troubleshooting.rst
- qa/cephfs/overrides/ignorelist_health.yaml
- qa/tasks/cephfs/test_admin.py
- src/mgr/PyModuleRegistry.cc
- src/mon/MgrMap.h
- src/mon/MgrMonitor.cc
- src/mon/MonCommands.h
Fixes: https://tracker.ceph.com/issues/66005 …
> mgr: allow disabling always-on modules

- .github/workflows/check-license.yml
> ci: fix typo in check-license

- doc/start/beginners-guide.rst
Add "vstart Cluster Installation and Configuration Procedure" to the Beginner's Guide.
(cherry picked from commit a42be085bd7b9159f4924853ac2b2d92c37884b0) …
> squid: doc/start: add vstart install guide

- doc/start/beginners-guide.rst
Add "vstart Cluster Installation and Configuration Procedure" to the Beginner's Guide.
(cherry picked from commit a42be085bd7b9159f4924853ac2b2d92c37884b0) …
> reef: doc/start: add vstart install guide

- src/global/global_init.cc
backport tracker: https://tracker.ceph.com/issues/68389
---
backport of https://github.com/ceph/ceph/pull/60095
parent tracker: https://tracker.ceph.com/issues/40692
Conflicts:
src/global/global_init.cc
- Replace `make_unique_for_overwrite` which is C++20 with `make_unique` …
> reef: global: Call getnam_r with a 64KiB buffer on the heap

- src/rgw/rgw_kafka.cc
backport tracker: https://tracker.ceph.com/issues/68046
---
backport of https://github.com/ceph/ceph/pull/59741
parent tracker: https://tracker.ceph.com/issues/68033
> reef: rgw/kafka: refactor topic creation to avoid rd_kafka_topic_name()

- src/test/rgw/bucket_notification/test_bn.py
backport tracker: https://tracker.ceph.com/issues/67648
---
backport of https://github.com/ceph/ceph/pull/59323
parent tracker: https://tracker.ceph.com/issues/67514
> squid: test/rgw/notifications: don't check for full queue if topics expired

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/cluster.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/host-form/host-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/host-form/host-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/host-form/host-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.ts
Fixes: https://tracker.ceph.com/issues/68264
Signed-off-by: Dnyaneshwari Talwekar <dtalweka@redbat.com>
- Tracker …
> mgr/dashboard: carbonize Cluster > Hosts form

- doc/man/8/rbd.rst
- doc/rbd/rbd-mirroring.rst
Updates the rbd docs with the new remote-namespace mirroring configuration option. …
> doc/rbd: namespace mirroring updates

- qa/workunits/rbd/cli_migration.sh
[RBD] : Added tests related to migration with namespace
-  Migration of images from namespace to namespace 
-  Migration of images from namespace to non-namespace
-  Migration of images from non-namespace to namespace …
> qa/workunits/rbd: cover native migration between namespaces

- qa/tasks/fwd_scrub.py
Removing unnecessary tracebacks from qa/tasks/fwd_scrub.py
Fixes: https://tracker.ceph.com/issues/65820 …
> qa/tasks/fwd_scrub: remove unnecessary traceback

- .github/workflows/check-license.yml
In the absence of `name`, GH uses the `job` ID of the action to select which checks are required, and `pull_request` is rather confusing. …
> .github/check-license: add friendly name

- .githubmap
- .mailmap
- .organizationmap
Adding Anuradha Gadge to mailmap, githubmap and organizationmap as per the onboarding docs …
> mailmap, githubmap, organisationmap: Add Anuradha Gadge

- doc/cephfs/client-auth.rst
- doc/cephfs/file-layouts.rst
Remind users that clients must use the 'p' flag when writing file layouts.
This PR is made in response to
https://www.reddit.com/r/ceph/comments/1gbad51/comment/ltkgd5v/
Signed-off-by: TruongSinh Tran-Nguyen <i@truongsinh.pro>
(cherry picked from commit 13c7c9d99881c7b4491ba1a693283c047161ea8a) …
> squid: doc/cephfs: use 'p' flag to set layouts or quotas

- src/pybind/mgr/volumes/fs/async_job.py
Class AsyncJob's attribute "self.waiting" is not used anywere in the
codebase. Therefore, remove it.
- Tracker …
> mgr/vol: remove unused variable

- doc/cephfs/fs-volumes.rst
- doc/cephfs/troubleshooting.rst
Signed-off-by: Rishabh Dave <ridave@redhat.com>
(cherry picked from commit 373910de34fc9e1d98218aed0361cd9bf3badffa) …
> squid: doc/cephfs: add doc for disabling mgr/volumes plugin

- doc/cephfs/fs-volumes.rst
- doc/cephfs/troubleshooting.rst
Signed-off-by: Rishabh Dave <ridave@redhat.com>
(cherry picked from commit 373910de34fc9e1d98218aed0361cd9bf3badffa) …
> reef: doc/cephfs: add doc for disabling mgr/volumes plugin

- doc/glossary.rst
> doc/glossary: add "PLP" to glossary

- doc/glossary.rst
Add "PLP" to the glossary.
(cherry picked from commit 599bdbf0a240ee718ed6da4104141b0f23330fbe) …
> quincy: doc/glossary: add "PLP" to glossary

- doc/glossary.rst
Add "PLP" to the glossary.
(cherry picked from commit 599bdbf0a240ee718ed6da4104141b0f23330fbe) …
> reef: doc/glossary: add "PLP" to glossary

- doc/glossary.rst
Add "PLP" to the glossary.
(cherry picked from commit 599bdbf0a240ee718ed6da4104141b0f23330fbe) …
> squid: doc/glossary: add "PLP" to glossary

- .github/workflows/check-license.yml
Change "Check Incompatible Licenses" to "Check for Incompatible Licenses".
This commit is made as part of a project to separate the changes in https://github.com/ceph/ceph/pull/60448 into individual pull requests. …
> .github/check-license: correct grammar in "license check"

- qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_clustering_ips.yaml
Depends on https://github.com/ceph/ceph/pull/59844/
- …
> qa/suites/orch: add a tests for testing public_addr for smb cluster create cmd

- doc/cephfs/cephfs-mirroring.rst
> doc: explain the consequence of enabling mirroring through monitor commands

- src/pybind/mgr/dashboard/frontend/src/app/core/auth/role-details/role-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/auth/role-list/role-list.component.ts
Fixes: https://tracker.ceph.com/issues/68706
Signed-off-by: Puja Shahu pshahu@redhat.com …
> mgr/dashboard:Roles section is not aligned with column name

- src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.spec.ts
Fixes: https://tracker.ceph.com/issues/68551
Signed-off-by: Achint Kaur <ackaur@redhat.com> …
> Add API tests for nvmeof service.ts file

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-realm-form/rgw-multisite-realm-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-realm-form/rgw-multisite-realm-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-realm-form/rgw-multisite-realm-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
Fixes: https://tracker.ceph.com/issues/68317
Signed-off-by: Dnyaneshwari talwekar <dtalweka@redhat.com>
https://github.com/user-attachments/assets/ad2ec810-961e-469a-8b2d-bee6c92c4698
https://github.com/user-attachments/assets/aba24168-a44a-41c9-a79c-2d0e5fdb79a7 …
> mgr/dashboard: Carbon Design - Create realm popup

- src/script/ceph-debug-docker.sh
> script/ceph-debug-docker: ubuntu core improvmenets

- doc/governance.rst
https://vote.heliosvoting.org/helios/elections/e03494ce-e04c-41d0-bb05-ec5ccc632ce4/view
Question #1
Update election requirements for Ceph Executive Council Elections?
Remove "ranked-choice" requirement	13
Keep "ranked-choice" requirement (no change)	16
Question #2
Require periodic elections in governance charter?
No (no change)	8
Annual	15
Semi-annual	3
Quarterly	2
Question #3
Update the Ceph Executive Council term length?
Change to 3 years	14
Keep 2 years (no change)	14
Question #4
Amend governance document to require a supermajority of votes for amendments to the governance model? The current requirement is a simple majority.
Require a supermajority	20
Require a simple majority (no change)	9
Question #5
Clarify "supermajority" and "majority" election requirements?
Of members voting on …
> doc/governance: updates based on 2024q4 election

- qa/tasks/cephfs/test_exports.py
- src/mds/CDir.h
- src/mds/MDSCacheObject.h
- src/mds/MDSDaemon.cc
- src/mds/MDSRank.cc
- src/mds/Migrator.cc
- src/mds/Migrator.h
Task to export subtree may be blocked, use this command to find out what's going on.
Fixes: https://tracker.ceph.com/issues/58835
Signed-off-by: Zhansong Gao <zhsgao@hotmail.com>
<details>
- `jenkins …
> mds: add an asok command to dump export states

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/silence-list/silence-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/silence-list/silence-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade-progress/upgrade-progress.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/auth/user-form/user-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/auth/user-form/user-form.component.ts
Fixes: https://tracker.ceph.com/issues/68650
Signed-off-by: Dnyaneshwari Talwekar  <dtalweka@redbat.com>
- Tracker …
> mgr/dashboard: Replacing bootstrap modal service with cds modal service

- qa/suites/upgrade/reef-x/parallel/overrides/ignorelist_health.yaml
- qa/suites/upgrade/reef-x/stress-split/overrides/ignorelist_health.yaml
Start with a reasonable list so we don't mask genuine issues.
Fixes: https://tracker.ceph.com/issues/65235
- …
> qa: Add ignorelist entries for reef-x tests

- src/cephadm/cephadm.py
Fixes: https://tracker.ceph.com/issues/68212 …
> cephadm: make bootstrap default to "global" section for public_network setting

- src/pybind/mgr/cephadm/services/nvmeof.py
- src/pybind/mgr/dashboard/services/nvmeof_cli.py
- src/pybind/mgr/dashboard/services/nvmeof_conf.py
don't remove an entire entry of a service from the config if only the daemon is removed, instead just remove the entry of that particular daemon. and once all the entry are succesfully removed, remove the entry for service …
> mgr/dashboard: rm nvmeof conf based on its daemon name

- doc/cephfs/fs-volumes.rst
doc/cephfs: add note to remind user about snap-schedule during volume delete #60362  …
> doc/cephfs: add note to remind user about snap-schedule during volume delete

- doc/architecture.rst
- doc/rados/api/python.rst
- doc/rados/configuration/mon-config-ref.rst
- doc/start/documenting-ceph.rst
Change the subordinating conjunction "Whereas" followed by a comma to the less grammatically-incorrect "Although". I've been meaning to do this since 22 Mar 2023. …
> doc: s/Whereas,/Although/

- .githubmap
- .mailmap
- .organizationmap
- .peoplemap
- doc/governance.rst
> quincy: doc,mailmap: update my email / association to ibm

- doc/architecture.rst
- doc/rados/api/python.rst
- doc/rados/configuration/mon-config-ref.rst
- doc/start/documenting-ceph.rst
Change the subordinating conjunction "Whereas" followed by a comma to the less grammatically-incorrect "Although". I've been meaning to do this since 22 Mar 2023.
(cherry picked from commit ea1a470fb4809d312f854e72fc5f8081cbcb2c49) …
> squid: doc: s/Whereas,/Although/

- doc/architecture.rst
- doc/rados/api/python.rst
- doc/rados/configuration/mon-config-ref.rst
- doc/start/documenting-ceph.rst
Change the subordinating conjunction "Whereas" followed by a comma to the less grammatically-incorrect "Although". I've been meaning to do this since 22 Mar 2023.
(cherry picked from commit ea1a470fb4809d312f854e72fc5f8081cbcb2c49) …
> reef: doc: s/Whereas,/Although/

- doc/architecture.rst
- doc/rados/api/python.rst
- doc/rados/configuration/mon-config-ref.rst
- doc/start/documenting-ceph.rst
Change the subordinating conjunction "Whereas" followed by a comma to the less grammatically-incorrect "Although". I've been meaning to do this since 22 Mar 2023.
(cherry picked from commit ea1a470fb4809d312f854e72fc5f8081cbcb2c49) …
> quincy: doc: s/Whereas,/Although/

- src/crimson/osd/pg.cc
Fixes: https://tracker.ceph.com/issues/68541 …
> crimson/osd/pg: trigger PG::wait_for_active_blocker only when the pg is going active

- src/crimson/osd/shard_services.cc
Fixes: https://tracker.ceph.com/issues/68662 …
> crimson/osd/shard_services: fix dangling reference caused by rvalue reference of ShardSercies::dispatch_context()

- src/crimson/osd/backfill_state.h
Fixes: https://tracker.ceph.com/issues/68719 …
> crimson/osd/backfill_state: discard CancelBackfill events when the backfill is done

- src/crimson/osd/osd_operations/client_request.cc
- src/crimson/osd/osd_operations/client_request.h
Fixes: https://tracker.ceph.com/issues/68737 …
> crimson/osd/osd_operations/client_request: no need to hold head's obc lock throughout the recovery of clones

- src/pybind/mgr/dashboard/frontend/i18n.config.json
- src/pybind/mgr/dashboard/frontend/src/locale/messages.cs.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.de-DE.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.es-ES.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.fr-FR.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.id-ID.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.it-IT.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.ja-JP.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.ko-KR.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.pl-PL.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.pt-BR.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.zh-CN.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.zh-TW.xlf
this is not a backport. its intended for squid release
> squid: mgr/dashboard: update translations for squid

- src/mds/Locker.cc
backport tracker: https://tracker.ceph.com/issues/67438
---
backport of https://github.com/ceph/ceph/pull/58861
parent tracker: https://tracker.ceph.com/issues/65851
> squid: mds: only authpin on wrlock when not a locallock

- qa/suites/rados/singleton-nomsgr/all/admin_socket_output.yaml
IO is frozen when the injectfull command is sent as part of the test which causes the cleanup to hang so we need to clear it.
Fixes: https://tracker.ceph.com/issues/59380
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>
(cherry picked from commit 4c5d0e30d2c077729385aab8bf446b04b62b12e5) …
> squid: qa/suites/rados: Cancel injectfull to allow cleanup

- PendingReleaseNotes
- qa/workunits/fs/misc/fallocate.sh
- src/client/Client.cc
- src/pybind/cephfs/cephfs.pyx
- src/test/pybind/test_cephfs.py
Fixes: https://tracker.ceph.com/issues/68026 …
> client: return EOPNOTSUPP for fallocate with mode 0

- doc/man/8/radosgw-admin.rst
- doc/radosgw/notifications.rst
also remove obsolete admin commands
Fixes: https://tracker.ceph.com/issues/68818
Signed-off-by: Yuval Lifshitz <ylifshit@ibm.com>
(cherry picked from commit ec272797c4caa5cf62319cdec104cf11575727b1) …
> squid: doc/rgw/notification: add missing admin commands

- src/os/bluestore/bluefs_types.cc
Parent tracker: https://tracker.ceph.com/issues/62850
Backport tracker: https://tracker.ceph.com/issues/67541
Backports: https://github.com/ceph/ceph/pull/55872
+ simplify op_bl size estimation
+ fix seq size estimation
+ skip useless calculation of crc32c
(cherry picked from commit 4acd7beed7b3f5b457e8641313f9384c36ae6140) …
> squid: os/bluestore: Mute warnings

- src/pybind/mgr/dashboard/frontend/i18n.config.json
- src/pybind/mgr/dashboard/frontend/src/locale/messages.cs.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.de-DE.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.es-ES.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.fr-FR.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.id-ID.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.it-IT.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.ja-JP.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.ko-KR.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.pl-PL.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.pt-BR.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.zh-CN.xlf
- src/pybind/mgr/dashboard/frontend/src/locale/messages.zh-TW.xlf
this is not a backport. its intended for quincy release
- …
> quincy: mgr/dashboard: update translations for quincy 

- qa/suites/upgrade/quincy-x/filestore-remove-check/0-cluster/start.yaml
- qa/suites/upgrade/quincy-x/filestore-remove-check/1-ceph-install/quincy.yaml
- qa/suites/upgrade/quincy-x/filestore-remove-check/2 - upgrade.yaml
we are starting to check the logs before all osds are down. that can cause the test to fail, we are missing the excpected failure message.
Fixes: https://tracker.ceph.com/issues/67999 …
> qa/tasks/ceph: wait the osds down before start check the logs

- doc/cephadm/operations.rst
Fixed typo 'no' to 'not' in sentence "If this test fails, cephadm will no be able to manage services on that host."
Signed-off-by: rhkelson <119636079+rhkelson@users.noreply.github.com>
(cherry picked from commit 34bc35a73443fa56908395a83ea2dd404a8fc4a6) …
> quincy: doc/cephadm: Update operations.rst

- doc/cephadm/services/index.rst
- doc/cephadm/services/osd.rst
Link to the "Placement by Pattern Matching" section in doc/cephadm/services/index.rst from the "Advanced OSD Service Specifications" section in doc/cephadm/services/osd.rst.
Fixes: https://tracker.ceph.com/issues/68812 …
> doc/cephadm: link to "host pattern" matching sect

- doc/cephadm/services/index.rst
- doc/cephadm/services/osd.rst
Link to the "Placement by Pattern Matching" section in doc/cephadm/services/index.rst from the "Advanced OSD Service Specifications" section in doc/cephadm/services/osd.rst.
Fixes: https://tracker.ceph.com/issues/68812
(cherry picked from commit cdfa299a2511ee35dfe0a857702af6d3ba257efd) …
> squid: doc/cephadm: link to "host pattern" matching sect

- doc/cephadm/services/index.rst
- doc/cephadm/services/osd.rst
Link to the "Placement by Pattern Matching" section in doc/cephadm/services/index.rst from the "Advanced OSD Service Specifications" section in doc/cephadm/services/osd.rst.
Fixes: https://tracker.ceph.com/issues/68812
(cherry picked from commit cdfa299a2511ee35dfe0a857702af6d3ba257efd) …
> reef: doc/cephadm: link to "host pattern" matching sect

- doc/cephadm/services/index.rst
- doc/cephadm/services/osd.rst
Link to the "Placement by Pattern Matching" section in doc/cephadm/services/index.rst from the "Advanced OSD Service Specifications" section in doc/cephadm/services/osd.rst.
Fixes: https://tracker.ceph.com/issues/68812
(cherry picked from commit cdfa299a2511ee35dfe0a857702af6d3ba257efd) …
> quincy: doc/cephadm: link to "host pattern" matching sect

- qa/suites/crimson-rados/basic/tasks/rados_python.yaml
This reverts commit a9de8be0f4633ac825f364f8b7ddcd4c4d5b6a2c.
Re-disable "wait" tests until https://tracker.ceph.com/issues/67791 is resolved to avoid entire job failure.  …
> Revert "suites: crimson basic adding wait for test"

- PendingReleaseNotes
doc: improve pending release notes and CephFS …
> doc: improve pending release notes and CephFS

- ceph.spec.in
> ceph.spec.in: Add option to enable sccache

- doc/cephadm/services/osd.rst
Clean the English grammar and the .RST in the section "Advanced OSD Service Specifications" in the file doc/cephadm/services/osd.rst. …
> doc/cephadm: clean "Adv. OSD Service Specs"

- src/mon/NVMeofGwMon.cc
- src/mon/NVMeofGwMon.h
>  mon/nvmeofgw*: monitors publish in nvme-gw show ana group responsible

- doc/cephadm/services/osd.rst
Clean the English grammar and the .RST in the section "Advanced OSD Service Specifications" in the file doc/cephadm/services/osd.rst.
(cherry picked from commit f6b56f9ee5d9f0b54dcaf1832d7a977895eb9c94) …
> squid: doc/cephadm: clean "Adv. OSD Service Specs"

- doc/cephadm/services/osd.rst
Clean the English grammar and the .RST in the section "Advanced OSD Service Specifications" in the file doc/cephadm/services/osd.rst.
(cherry picked from commit f6b56f9ee5d9f0b54dcaf1832d7a977895eb9c94) …
> reef: doc/cephadm: clean "Adv. OSD Service Specs"

- qa/suites/fs/mixed-clients/distro/centos_8.yaml
- qa/suites/fs/mixed-clients/distro/centos_9.stream.yaml
- qa/suites/fs/mixed-clients/distro/rhel_8.yaml
- qa/suites/fs/upgrade/featureful_client/old_client/centos_8.stream.yaml
- qa/suites/fs/upgrade/featureful_client/upgraded_client/centos_8.stream.yaml
- qa/suites/fs/upgrade/nofs/centos_8.stream.yaml
- qa/suites/fs/upgrade/upgraded_client/centos_8.stream.yaml
- qa/suites/fs/verify/distro/centos_8.yaml
- qa/suites/fs/verify/distro/centos_9.stream.yaml
- qa/suites/fs/verify/distro/rhel_8.yaml
commit 0efa15a19606a127bca6dfb4bcb60c829b690e02 introduced it back in fs suite and there were some leftovers - clean them up. …
> reef: qa/cephfs: remove dependency on centos8/rhel8 entirely

- qa/workunits/libcephfs/test.sh
- src/client/Client.cc
- src/include/ceph_fs.h
- src/mds/Server.cc
- src/test/libcephfs/CMakeLists.txt
- src/test/libcephfs/test.cc
- src/test/libcephfs/vxattr.cc
backport tracker: https://tracker.ceph.com/issues/66778
---
backport of https://github.com/ceph/ceph/pull/55945
parent tracker: https://tracker.ceph.com/issues/64679 …
> reef: mds/client: return -ENODATA when xattr doesn't exist for removexattr

- src/common/TrackedOp.cc
backport tracker: https://tracker.ceph.com/issues/66616
---
backport of https://github.com/ceph/ceph/pull/58125
parent tracker: https://tracker.ceph.com/issues/66557 …
> reef: common/TrackedOp: do not count the ops marked as nowarn

- qa/tasks/cephfs/test_cephfs_shell.py
backport tracker: https://tracker.ceph.com/issues/65348
backport of https://github.com/ceph/ceph/pull/55725
parent tracker: https://tracker.ceph.com/issues/63699 …
> reef: qa: fixing tests in test_cephfs_shell.TestShellOpts

- doc/dev/cephfs-mirroring.rst
Updates the snapdiff feature and it's url.
Blocked by: https://github.com/ceph/ceph/pull/58985
(cherry picked from commit 629922bf6a0905cc87707f5e2d027f6320aafd99) …
> reef: doc: update Key Idea in cephfs-mirroring.rst

- src/client/Client.cc
- src/client/Client.h
- src/test/client/CMakeLists.txt
- src/test/client/syncio.cc
Backport of https://github.com/ceph/ceph/pull/57576 and some commits from https://github.com/ceph/ceph/pull/55457
Backport tracker: https://tracker.ceph.com/issues/64740
Parent tracker: https://tracker.ceph.com/issues/64313 …
> reef: client: do not proceed with I/O if filehandle is invalid

- qa/tasks/mgr/dashboard/test_cephfs.py
- src/client/Client.cc
- src/pybind/mgr/dashboard/controllers/cephfs.py
backport tracker: https://tracker.ceph.com/issues/64604
- …
> reef: client: check mds down status before getting mds_gid_t from mdsmap

- qa/tasks/mgr/dashboard/helper.py
- qa/tasks/mgr/dashboard/test_mgr_module.py
- qa/tasks/mgr/mgr_test_case.py
- src/pybind/mgr/dashboard/run-backend-api-tests.sh
as per: https://tracker.ceph.com/issues/47612#note-14
Fixes: https://tracker.ceph.com/issues/47612
Fixes: https://tracker.ceph.com/issues/62972 …
> qa/dashboard: fix tasks.mgr.dashboard.test_health.HealthTest

- src/pybind/mgr/dashboard/frontend/package-lock.json
- src/pybind/mgr/dashboard/frontend/package.json
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/mirroring/bootstrap-create-modal/bootstrap-create-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-auth-modal/cephfs-auth-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table-key-value/table-key-value.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts
update carbon-components-angular pkg to v5.48.0
Fixes: https://tracker.ceph.com/issues/68837 …
> mgr/dashboard: update carbon-components-angular

- src/rgw/driver/rados/rgw_d3n_datacache.cc
Fixes: https://tracker.ceph.com/issues/67616 …
> rgw: d3n: set access permissions for the D3N cache directory when creating

- doc/start/os-recommendations.rst
Separate the packages-and-containers chart into two charts:
(1) a chart that shows which OSes Ceph builds packages for
(2) a chart that shows which OSes support Ceph's containers …
> doc/start: separate package chart from container chart

- doc/radosgw/account.rst
Correct "AttachGroupPoliicy" to "AttachGroupPolicy".
Fixes: https://tracker.ceph.com/issues/68902 …
> doc/radosgw: s/Poliicy/Policy/

- doc/start/hardware-recommendations.rst
Fix typo reading "They are are single-threaded".
s/are are/are/
Fixes: https://tracker.ceph.com/issues/68901
- …
> doc/start: fix "are are" typo

- doc/start/os-recommendations.rst
Separate the packages-and-containers chart into two charts:
(1) a chart that shows which OSes Ceph builds packages for
(2) a chart that shows which OSes support Ceph's containers
(cherry picked from commit e5ff1916e3d5e2cc3f47b4cea2762730dfd335c0) …
> squid: doc/start: separate package chart from container chart

- doc/start/hardware-recommendations.rst
Fix typo reading "They are are single-threaded".
s/are are/are/
Fixes: https://tracker.ceph.com/issues/68901
(cherry picked from commit 22010719d7edf2a6cf7de7b115ed797e7942ec47) …
> squid: doc/start: fix "are are" typo

- doc/start/hardware-recommendations.rst
Fix typo reading "They are are single-threaded".
s/are are/are/
Fixes: https://tracker.ceph.com/issues/68901
(cherry picked from commit 22010719d7edf2a6cf7de7b115ed797e7942ec47) …
> reef: doc/start: fix "are are" typo

- doc/start/hardware-recommendations.rst
Fix typo reading "They are are single-threaded".
s/are are/are/
Fixes: https://tracker.ceph.com/issues/68901
(cherry picked from commit 22010719d7edf2a6cf7de7b115ed797e7942ec47) …
> quincy: doc/start: fix "are are" typo

- doc/radosgw/account.rst
Correct "AttachGroupPoliicy" to "AttachGroupPolicy".
Fixes: https://tracker.ceph.com/issues/68902
(cherry picked from commit 961aef1bb4e59912ac1c8827a392c18b912c71f0) …
> squid: doc/radosgw: s/Poliicy/Policy/

- make-dist
> make-dist: Quiet submodule operations in Jenkins

- src/client/Client.cc
- src/client/MetaSession.cc
- src/include/ceph_fs.h
- src/mds/Capability.h
- src/mds/Locker.cc
- src/mds/MDCache.cc
- src/messages/MClientCaps.h
First set of changes I'd like to do for
https://tracker.ceph.com/issues/66704
- …
> mds,client: correct last_issue struct fields and consistently send last_issue in cap messages

- doc/cephfs/mds-journaling.rst
- src/common/options/mds.yaml.in
- src/mds/Beacon.cc
- src/mds/MDLog.cc
- src/mds/MDLog.h
Should have explained the intent in the commit message, but pushing this out for reviews. See https://tracker.ceph.com/issues/66948#note-9 for an explanation. …
> mds: trim mdlog when segments exceed threshold and trim was idle

- src/mon/MonMap.cc
Using the same logic for constructing MonMap::mon_info and mon_addr.
- Component …
> Make mon_info_t consistent with mon_addr

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rgw_client.py
- src/pybind/mgr/dashboard/services/rgw_iam.py
backport tracker: https://tracker.ceph.com/issues/68686
---
backport of https://github.com/ceph/ceph/pull/60399
parent tracker: https://tracker.ceph.com/issues/68622
verified manually in squid
https://github.com/user-attachments/assets/165b86fc-cad0-4439-b862-3ca201e42028
> squid: mgr/dashboard: fix bucket get for s3 account owned bucket 

- src/pybind/mgr/dashboard/services/rgw_client.py
- src/python-common/ceph/rgw/rgwam_core.py
backport tracker: https://tracker.ceph.com/issues/68201
---
backport of https://github.com/ceph/ceph/pull/59716
parent tracker: https://tracker.ceph.com/issues/67897
> squid: mgr/rgwam: use realm/zonegroup/zone method arguments for period update

- doc/start/os-recommendations.rst
Separate the packages-and-containers chart into two charts:
(1) a chart that shows which OSes Ceph builds packages for
(2) a chart that shows which OSes support Ceph's containers
(cherry picked from commit e5ff1916e3d5e2cc3f47b4cea2762730dfd335c0) …
> reef: doc/start: separate package chart from container chart

- src/rgw/rgw_kafka.cc
backport tracker: https://tracker.ceph.com/issues/68047
---
backport of https://github.com/ceph/ceph/pull/59741
parent tracker: https://tracker.ceph.com/issues/68033
> squid: rgw/kafka: refactor topic creation to avoid rd_kafka_topic_name()

- src/crimson/osd/ops_executer.h
- src/crimson/osd/pg.cc
> crimson/osd: minor bug fixes misc

- doc/rados/operations/balancer.rst
- src/pybind/mgr/balancer/module.py
Before, we were updating the balancer status by
iterating through all pg upmap entires. This was
affecting the loading time of other mgr modules
on clusters with a large number of pgs (600+).
This can be optimized by simply pulling from
the incremental.
Fixes: https://tracker.ceph.com/issues/68657
This PR also ties "ceph balancer status detail"
to a configurable. To test out the configurable,
you can run `ceph config set mgr mgr/balancer/update_pg_upmap_activity <True|False>`.
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingP …
> mgr/balancer: optimize 'balancer status detail'

- qa/standalone/ceph-helpers.sh
Further fix for https://github.com/ceph/ceph/pull/57888
https://tracker.ceph.com/issues/67818
Signed-off-by: Mingyuan Liang <liangmingyuan@baidu.com>
> qa/standalone: bugfix for wait_for_scrub

- src/exporter/DaemonMetricCollector.cc
- src/exporter/DaemonMetricCollector.h
- src/exporter/ceph_exporter.cc
- src/exporter/web_server.cc
- src/exporter/web_server.h
Ceph exporter manages SIGINT, SIGTERM and SIGHUP signals
Fixes: https://tracker.ceph.com/issues/68721
--------------------------------------------
Unit test executed succesfully
**manual tests:**
**Before the change:**
terminal A
==========
```
jolmomar:~/.../build/bin$ ./ceph-exporter -c /home/jolmomar/Code/ceph/build/ceph.conf --sock-dir /home/jolmomar/Code/ceph/build/asok
2024-10-23T12:37:54.538+0200 7f1c4fe990c0 -1 WARNING: all dangerous and experimental features are enabled.
2024-10-23T12:37:54.543+0200 7f1c4fe990c0 -1 WARNING: all dangerous and experimental features are enabled.
2024-10-23T12:37:54.543+0200 7f1c4fe990c0 -1 WARNING: all dangerous and experimental features are enabled.
system:0
...
system:0
Terminated
jolmomar:~/.../build/bin$ echo $?
143 …
```
> exporter: SIGTERM/SIGINT/SIGHUP management

- doc/cephadm/install.rst
Change the title of the section "Deploying a new Ceph cluster" to "Using cephadm to Deploy a New Ceph Cluster". This is part of the initiative to separate package-related documentation from container-based documenation. …
> doc/cephadm: Clarify "Deploying a new Cluster"

- doc/cephadm/install.rst
> doc/cephadm: Improve "Curl-based Installation"

- doc/cephadm/install.rst
Change the title of the section "Deploying a new Ceph cluster" to "Using cephadm to Deploy a New Ceph Cluster". This is part of the initiative to separate package-related documentation from container-based documenation.
(cherry picked from commit 8cf77d03a1f3ecb73931ddf96d13ef098aa61c1a) …
> squid: doc/cephadm: Clarify "Deploying a new Cluster"

- doc/cephadm/install.rst
Change the title of the section "Deploying a new Ceph cluster" to "Using cephadm to Deploy a New Ceph Cluster". This is part of the initiative to separate package-related documentation from container-based documenation.
(cherry picked from commit 8cf77d03a1f3ecb73931ddf96d13ef098aa61c1a) …
> reef: doc/cephadm: Clarify "Deploying a new Cluster"

- doc/cephadm/install.rst
Change the title of the section "Deploying a new Ceph cluster" to "Using cephadm to Deploy a New Ceph Cluster". This is part of the initiative to separate package-related documentation from container-based documenation.
(cherry picked from commit 8cf77d03a1f3ecb73931ddf96d13ef098aa61c1a) …
> quincy: doc/cephadm: Clarify "Deploying a new Cluster"

- qa/tasks/cephfs/test_mirroring.py
backport tracker: https://tracker.ceph.com/issues/68107
---
backport of https://github.com/ceph/ceph/pull/59093
parent tracker: https://tracker.ceph.com/issues/67435
> reef: qa: do the set/get attribute on the remote filesystem

- doc/rados/troubleshooting/log-and-debug.rst
doc/rados/troubleshooting: Improve log-and-debug.rst …
> doc/rados/troubleshooting: Improve log-and-debug.rst

- src/rgw/driver/rados/rgw_sync.cc
backport tracker: https://tracker.ceph.com/issues/69003
---
backport of https://github.com/ceph/ceph/pull/52568
parent tracker: https://tracker.ceph.com/issues/61743
> squid: rgw/multisite: metadata polling event based on unmodified mdlog_marker

- doc/rados/troubleshooting/log-and-debug.rst
(cherry picked from commit 44c9519cc3eb013104c52014c302ba71ba806f8f) …
> quincy: doc/rados/troubleshooting: Improve log-and-debug.rst

- doc/rados/troubleshooting/log-and-debug.rst
(cherry picked from commit 44c9519cc3eb013104c52014c302ba71ba806f8f) …
> squid: doc/rados/troubleshooting: Improve log-and-debug.rst

- doc/rados/troubleshooting/log-and-debug.rst
(cherry picked from commit 44c9519cc3eb013104c52014c302ba71ba806f8f) …
> reef: doc/rados/troubleshooting: Improve log-and-debug.rst

- doc/releases/index.rst
- doc/releases/quincy.rst
- doc/releases/releases.yml
> doc: 17.2.8 Release Notes

- src/client/Client.cc
Backport tracker: https://tracker.ceph.com/issues/67586
- …
> reef: client: flush the caps release in filesystem sync

- PendingReleaseNotes
> doc: add pendingreleasenotes for cephfs subvolume earmarking feature

- src/mds/MDCache.cc
- src/mds/Server.cc
Backport PR https://tracker.ceph.com/issues/67162.
This will fix the crash bug in https://tracker.ceph.com/issues/66967. Just drop the batch head ref before dropping all the `mdr` pins when killing the `mdr. …
> reef: mds: try to choose a new batch head in request_clientup()

- src/tools/cephfs/shell/cephfs-shell
backport tracker: https://tracker.ceph.com/issues/67114
---
backport of https://github.com/ceph/ceph/pull/58327
parent tracker: https://tracker.ceph.com/issues/66735 …
> reef: cephfs-shell: excute cmd 'rmdir_helper' reported error

- doc/radosgw/archive-sync-module.rst
Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>
(cherry picked from commit 303ce155a34fdf2cde63b948d204aca339dd5682) …
> squid: doc/radosgw: Improve archive-sync-module.rst

- doc/radosgw/archive-sync-module.rst
Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>
(cherry picked from commit 303ce155a34fdf2cde63b948d204aca339dd5682) …
> reef: doc/radosgw: Improve archive-sync-module.rst

- doc/radosgw/archive-sync-module.rst
Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>
(cherry picked from commit 303ce155a34fdf2cde63b948d204aca339dd5682) …
> quincy: doc/radosgw: Improve archive-sync-module.rst

- cmake/modules/Builduadk.cmake
Make uadk's repo fixed to avoid potential make fail.
- …
> build/uadk: fix uadk repo's commit id

- src/mds/Capability.h
- src/mds/OpenFileTable.h
- src/messages/MClientCaps.h
- src/messages/MClientSession.h
- src/messages/MMDSScrub.h
- src/messages/MMDSScrubStats.h
backport tracker: https://tracker.ceph.com/issues/64043
---
backport of https://github.com/ceph/ceph/pull/54519
parent tracker: https://tracker.ceph.com/issues/63552 …
> quincy: mds: use explicitly sized types for network and disk encoding

- doc/radosgw/archive-sync-module.rst
doc/radosgw: Improve archive-sync-module.rst more …
> doc/radosgw: Improve archive-sync-module.rst more

- doc/glossary.rst
Add the initialism "DC" (Data Center) to the glossary.
- …
> doc/glossary: add "DC" (Data Center) to glossary

- doc/glossary.rst
- doc/rados/troubleshooting/troubleshooting-osd.rst
Add an entry for "Flapping OSD" to the glossary.
(cherry picked from commit 1ca89e6ca3d9e0042702b7ac3af9a3e596330c1d) …
> squid: doc/glossary: add "flapping OSD"

- doc/glossary.rst
- doc/rados/troubleshooting/troubleshooting-osd.rst
Add an entry for "Flapping OSD" to the glossary.
(cherry picked from commit 1ca89e6ca3d9e0042702b7ac3af9a3e596330c1d) …
> reef: doc/glossary: add "flapping OSD"

- doc/glossary.rst
- doc/rados/troubleshooting/troubleshooting-osd.rst
Add an entry for "Flapping OSD" to the glossary.
(cherry picked from commit 1ca89e6ca3d9e0042702b7ac3af9a3e596330c1d) …
> quincy: doc/glossary: add "flapping OSD"

- src/mds/MDCache.cc
- src/mds/MDCache.h
backport tracker: https://tracker.ceph.com/issues/65322
---
backport of https://github.com/ceph/ceph/pull/52648
parent tracker: https://tracker.ceph.com/issues/62036 …
> quincy: mds: defer trim() until after the last cache_rejoin ack being received

- doc/radosgw/archive-sync-module.rst
(cherry picked from commit c24dc78484cbca8660c87742a6612c15935953c4) …
> quincy: doc/radosgw: Improve archive-sync-module.rst more

- src/mds/Locker.cc
backport tracker: https://tracker.ceph.com/issues/64076
---
backport of https://github.com/ceph/ceph/pull/53238
parent tracker: https://tracker.ceph.com/issues/62580 …
> quincy: mds: just wait the client flushes the snap and dirty buffer

- src/blk/BlockDevice.cc
- src/blk/BlockDevice.h
- src/blk/kernel/KernelDevice.cc
- src/common/options/global.yaml.in
- src/mon/PGMap.cc
- src/os/bluestore/BlueFS.cc
- src/os/bluestore/BlueFS.h
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
backport tracker: https://tracker.ceph.com/issues/67038
--------
backport of #57722
parent tracker: https://tracker.ceph.com/issues/62500
> reef: os/bluestore: Warning added for slow operations and stalled read

- doc/glossary.rst
Add the initialism "DC" (Data Center) to the glossary.
(cherry picked from commit e595f353b53d50291f7cf58e6d782adf30449704) …
> reef: doc/glossary: add "DC" (Data Center) to glossary

- doc/glossary.rst
Add the initialism "DC" (Data Center) to the glossary.
(cherry picked from commit e595f353b53d50291f7cf58e6d782adf30449704) …
> quincy: doc/glossary: add "DC" (Data Center) to glossary

- doc/radosgw/archive-sync-module.rst
(cherry picked from commit c24dc78484cbca8660c87742a6612c15935953c4) …
> reef: doc/radosgw: Improve archive-sync-module.rst more

- doc/radosgw/archive-sync-module.rst
(cherry picked from commit c24dc78484cbca8660c87742a6612c15935953c4) …
> squid: doc/radosgw: Improve archive-sync-module.rst more

- src/pybind/mgr/dashboard/frontend/package-lock.json
- src/pybind/mgr/dashboard/frontend/package.json
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/block.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/iscsi-target-details/iscsi-target-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/iscsi-target-details/iscsi-target-details.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/iscsi-target-details/iscsi-target-details.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/iscsi-target-details/iscsi-target-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/iscsi-target-list/iscsi-target-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-directories/cephfs-directories.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-directories/cephfs-directories.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-directories/cephfs-directories.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-directories/cephfs-directories.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-tabs/cephfs-tabs.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/cluster.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/crushmap/crushmap.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/crushmap/crushmap.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/crushmap/crushmap.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/crushmap/crushmap.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.scss
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/tree-view.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/tree-view.service.ts
- src/pybind/mgr/dashboard/frontend/src/styles.scss
- src/pybind/mgr/dashboard/frontend/src/styles/themes/_content.scss
Replaces the deprecated npm package '@circlon/angular-tree-component' by Carbon Tree component.
Fixes: https://tracker.ceph.com/issues/68249 …
> mgr/dashboard: carbon tree component

- doc/radosgw/s3/commons.rst
Update doc/radosgw/s3/commons.rst with the changes made by Jiffin Tony Thottan in https://github.com/ceph/ceph/pull/54524 and the suggestions made in that same PR by Anthony D'Atri.
Explain how to set rgw_dns_name to a domain name in order to configure access to virtual hosted buckets.
(cherry picked from commit 45ff7e3365eaaa01ccb4ead71a14dd1dd9741c2f) …
> squid: doc/radosgw: update rgw_dns_name doc

- doc/radosgw/s3/commons.rst
Update doc/radosgw/s3/commons.rst with the changes made by Jiffin Tony Thottan in https://github.com/ceph/ceph/pull/54524 and the suggestions made in that same PR by Anthony D'Atri.
Explain how to set rgw_dns_name to a domain name in order to configure access to virtual hosted buckets.
(cherry picked from commit 45ff7e3365eaaa01ccb4ead71a14dd1dd9741c2f) …
> reef: doc/radosgw: update rgw_dns_name doc

- doc/rados/operations/health-checks.rst
- src/common/options/global.yaml.in
os/bluestore: Improve documentation introduced by #57722
This includes what look like some copy/paste errors as well as use of the `confval` directive and removing embedded default values in accordance with the DRY principle.
@aclamk please review carefully in case I have inadvertently introduced errors. …
> os/bluestore: Improve documentation introduced by #57722

- doc/glossary.rst
Add an entry below the (Mimic-era and therefore outdated but nonetheless historically important) Dashboard Plugin key word in the glosssary, which before now had never been added to the glossary. …
> doc/glossary.rst: add "Dashboard Plugin"

- doc/glossary.rst
Add an entry below the (Mimic-era and therefore outdated but nonetheless historically important) Dashboard Plugin key word in the glosssary, which before now had never been added to the glossary.
(cherry picked from commit a1cec3de5704cedd7f7c8ce185144a96d72520d3) …
> quincy: doc/glossary.rst: add "Dashboard Plugin"

- doc/glossary.rst
Add an entry below the (Mimic-era and therefore outdated but nonetheless historically important) Dashboard Plugin key word in the glosssary, which before now had never been added to the glossary.
(cherry picked from commit a1cec3de5704cedd7f7c8ce185144a96d72520d3) …
> reef: doc/glossary.rst: add "Dashboard Plugin"

- doc/glossary.rst
Add an entry below the (Mimic-era and therefore outdated but nonetheless historically important) Dashboard Plugin key word in the glosssary, which before now had never been added to the glossary.
(cherry picked from commit a1cec3de5704cedd7f7c8ce185144a96d72520d3) …
> squid: doc/glossary.rst: add "Dashboard Plugin"

- doc/rados/operations/health-checks.rst
- src/common/options/global.yaml.in
(cherry picked from commit b6eb98cc10895e0cdc4bc147f6f83145c10cba41) …
> squid: os/bluestore: Improve documentation introduced by #57722

- doc/rados/operations/health-checks.rst
- src/common/options/global.yaml.in
(cherry picked from commit b6eb98cc10895e0cdc4bc147f6f83145c10cba41) …
> quincy: os/bluestore: Improve documentation introduced by #57722

- doc/rados/operations/health-checks.rst
- src/common/options/global.yaml.in
(cherry picked from commit b6eb98cc10895e0cdc4bc147f6f83145c10cba41) …
> reef: os/bluestore: Improve documentation introduced by #57722

- src/pybind/mgr/dashboard/controllers/cephfs.py
- src/pybind/mgr/dashboard/controllers/smb.py
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/security.py
- src/pybind/mgr/dashboard/services/access_control.py
- src/pybind/mgr/dashboard/tests/test_smb.py
> mgr/dashboard: add smb endpoints

- doc/man/8/rbd.rst
> doc/rbd: Add mirror snapshot schedule information

- doc/cephadm/services/mon.rst
s/ceph/Ceph/ in doc/cephadm/services/mon.rst where appropriate. …
> doc/cephadm: s/ceph/Ceph/ in mon.rst

- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/rgw_admin.cc
- src/rgw/rgw_op.cc
- src/rgw/rgw_op.h
- src/rgw/rgw_rest_s3.cc
Added x-amz-restore header and fixed status codes for both restore-cli and read_through.
Fixes: https://tracker.ceph.com/issues/68013
Signed-off-by: shreyanshjain7174 <ssanchet@redhat.com> …
> rgw/restore: Fixed status codes and response headers

- src/blk/aio/aio.cc
- src/blk/aio/aio.h
- src/blk/kernel/KernelDevice.cc
- src/blk/kernel/io_uring.cc
- src/blk/kernel/io_uring.h
- src/test/objectstore/store_test.cc
Parent tracker: https://tracker.ceph.com/issues/64966
Backport tracker: https://tracker.ceph.com/issues/67034
Backports: https://github.com/ceph/ceph/pull/56352 …
> reef: blk/aio: fix long batch (64+K entries) submission

- src/pybind/mgr/dashboard/frontend/cypress/e2e/ui/navigation.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/ceph.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-list/smb-cluster-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-list/smb-cluster-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-list/smb-cluster-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb.model.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/permission.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/permissions.ts
Tracker: https://tracker.ceph.com/issues/69080
Signed-off-by: Dnyaneshwari Talwekar <dtalweka@redbat.com>
- Tracker …
> mgr/dashboard: list smb

- doc/rados/operations/health-checks.rst
This commit edits the first third of …
> doc/rados: make sentences agree in health-checks.rst

- doc/rados/operations/health-checks.rst
This commit edits the first third of
(cherry picked from commit aec87b9188a92d2722c7310e753462a054cb12c7) …
> quincy: doc/rados: make sentences agree in health-checks.rst
