ceph/ceph

- src/ceph-volume/ceph_volume/objectstore/rawbluestore.py
This fixes a regression
(most likely introduced with 04c93a1ed42)
Current (broken) behavior:
```
[root@devel1-1 /]# ceph osd tree
ID  CLASS  WEIGHT  TYPE NAME     STATUS     REWEIGHT  PRI-AFF
-1              0  root default
0              0  osd.0         destroyed         0  1.00000
[root@devel1-1 /]# ceph-volume raw prepare --bluestore --data /dev/vdb --osd-id 0
Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new 543e0268-ea66-451f-a2f6-95ae60ab6146
Running command: /usr/bin/mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-1
Running command: /usr/sbin/restorecon /var/lib/ceph/osd/ceph-1
Running …
```
> ceph-volume: pass self.osd_id to create_id() call

- src/ceph-volume/ceph_volume/devices/lvm/batch.py
The automatic disk sorting behavior is deprecated. The new behavior should be the default since Ceph Pacific but it got pushed back multiple times.
Fixes: https://tracker.ceph.com/issues/67497
> ceph-volume: switch over to new disk sorting behavior

- ceph.spec.in
- debian/control
- src/ceph-volume/setup.py
backport tracker: https://tracker.ceph.com/issues/67529
---
backport of https://github.com/ceph/ceph/pull/58956
parent tracker: https://tracker.ceph.com/issues/67290
> squid: debian pkg: record python3-packaging dependency for ceph-volume

- src/ceph-volume/ceph_volume/objectstore/rawbluestore.py
backport tracker: https://tracker.ceph.com/issues/67923
---
backport of https://github.com/ceph/ceph/pull/59604
parent tracker: https://tracker.ceph.com/issues/67898
> squid: ceph-volume: pass self.osd_id to create_id() call

- src/ceph-volume/ceph_volume/activate/main.py
backport tracker: https://tracker.ceph.com/issues/67892
---
backport of https://github.com/ceph/ceph/pull/59573
parent tracker: https://tracker.ceph.com/issues/67873
> squid: ceph-volume: fix generic activation with raw osds

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-details/rbd-details.component.ts
Fixes: https://tracker.ceph.com/issues/67849
The Performance tab of the dashboard is passing the `pool` and `image` variables to the Grafana iframe with the first letter in uppercase, but in the `monitoring/ceph-mixin/dashboards_out/rbd-details.json` dashboard file they are defined in lowercase, this causes them not to be recognized and the graphics display _No data_.
Example of current (wrong) generated URL:
`https://mycephdashboard.com/d/eRtdGrFfgT/rbd-details?var-Pool=pve_rbd_ssd&var-Image=base-501-disk-0&refresh=5s&var-datasource=Dashboard1&kiosk&from=now-1h&to=now&orgId=1`
It should be:
`https://mycephdashboard.com/d/eRtdGrFfgT/rbd-details?var-pool=pve_rbd_ssd&var-image=base-501-disk-0&refresh=5s&var-datasource=Dashboard1&kiosk&from=now-1h&to=now&orgId=1`
_Note that the `var-Image` …
> mgr/dashboard: Fix variable capitalization in embedded rbd-details panel  

- src/ceph-volume/ceph_volume/devices/lvm/batch.py
backport tracker: https://tracker.ceph.com/issues/67924
---
backport of https://github.com/ceph/ceph/pull/59170
parent tracker: https://tracker.ceph.com/issues/67497
> squid: ceph-volume: switch over to new disk sorting behavior

- qa/distros/container-hosts/centos_9.stream.yaml
- qa/distros/container-hosts/centos_9.stream_runc.yaml
backport tracker: https://tracker.ceph.com/issues/67733
---
backport of https://github.com/ceph/ceph/pull/59409
parent tracker: https://tracker.ceph.com/issues/67684
> reef: qa/distros: reinstall nvme-cli on centos 9 nodes

- ceph.spec.in
- debian/control
- src/ceph-volume/setup.py
backport tracker: https://tracker.ceph.com/issues/67528
---
backport of https://github.com/ceph/ceph/pull/58956
parent tracker: https://tracker.ceph.com/issues/67290
> reef: debian pkg: record python3-packaging dependency for ceph-volume

- src/ceph-volume/ceph_volume/util/disk.py
backport tracker: https://tracker.ceph.com/issues/63920
---
backport of https://github.com/ceph/ceph/pull/53327
parent tracker: https://tracker.ceph.com/issues/63918
> reef: ceph-volume: Fix unbound var in disk.get_devices()

- qa/standalone/scrub/osd-recovery-scrub.sh
- qa/standalone/scrub/scrub-helpers.sh
- src/common/options/osd.yaml.in
- src/osd/scrubber/pg_scrubber.cc
- src/osd/scrubber/scrub_job.cc
- src/osd/scrubber/scrub_job.h
- src/osd/scrubber/scrub_machine.cc
- src/osd/scrubber/scrub_machine.h
- src/osd/scrubber_common.h
to apply to a scrub target following a scrub failure
Specific configuration parameters are added to control the duration
of the delay to apply to the 'not-before' attribute of the failed scrub
target following a scrub failure.  Some failure causes now have
their own delay values, while others share a common duration.
> osd/scrub: add configuration parameters to control delay duration

- src/crimson/os/seastore/backref/btree_backref_manager.cc
- src/crimson/os/seastore/btree/fixed_kv_node.h
- src/crimson/os/seastore/cache.cc
- src/crimson/os/seastore/cache.h
- src/crimson/os/seastore/cached_extent.h
- src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.cc
- src/crimson/os/seastore/seastore.cc
- src/crimson/os/seastore/seastore_types.cc
- src/crimson/os/seastore/seastore_types.h
- src/crimson/os/seastore/transaction_manager.h
* Report stats from the cache index.
* Cache hit stats: hit as pending extents, hit from dirty/lru, get from dirty/lru, absent&load from lru, access by transactions and extent types, etc.
```
The report looks like:
...
cache total(100.41MiB,6.57KiB,15653)
access: total(13.34K, trans-hit=70.04%(p0.18,d0.80,l0.02), cache-hit=99.97%(d0.89,l0.11), load/absent=100.00%, load-present/absent=0.00)
MUTATE: (12.21K, trans-hit=72.38%(p0.16,d0.82,l0.02), cache-hit=99.97%(d0.87,l0.13), load/absent=100.00%, load-present/absent=0.00)
data(~0.00K, trans-hit=~-nan%(p-nan,d-nan,l-nan), cache-hit=~-nan%(d-nan,l-nan), load-present/absent=-nan)
mdat(~1.91K, trans-hit=~26.76%(p0.50,d0.36,l0.13), cache-hit=~99.93%(d0.76,l0.24), load-present/absent=0.00)
phys(~10.30K, trans-hit=~80.82%(p0.14,d0.85,l0.01), …
```
> crimson/os/seastore/cache: report cache access stats

- doc/cephfs/cephfs-mirroring.rst
- qa/tasks/cephfs/test_mirroring.py
- src/tools/cephfs_mirror/PeerReplayer.cc
- src/tools/cephfs_mirror/PeerReplayer.h
backport tracker: https://tracker.ceph.com/issues/67387
---
backport of https://github.com/ceph/ceph/pull/56782
parent tracker: https://tracker.ceph.com/issues/65171
> squid: cephfs_mirror: provide metrics for last successful snapshot sync

- qa/suites/fs/valgrind/mirror/cephfs-mirror/one-per-cluster.yaml
backport tracker: https://tracker.ceph.com/issues/67382
---
backport of https://github.com/ceph/ceph/pull/57987
parent tracker: https://tracker.ceph.com/issues/64752
> squid: qa/suites: drop --show-reachable=yes from fs:valgrind tests

- src/tools/cephfs_mirror/PeerReplayer.cc
- src/tools/cephfs_mirror/PeerReplayer.h
backport tracker: https://tracker.ceph.com/issues/65223
---
backport of https://github.com/ceph/ceph/pull/54633
parent tracker: https://tracker.ceph.com/issues/61334
> squid: cephfs_mirror: use snapdiff api for incremental syncing

- src/rgw/driver/rados/rgw_notify.cc
also fix access to possible dpp dangling pointer
Fixes: https://tracker.ceph.com/issues/67658
<details>
</details>
> rgw/notifications: free completion pointer using unique_ptr

- src/test/cli/rbd/help.t
- src/tools/rbd/action/Bench.cc
As of today, when RBD bench writes an IO, it writes a single character for the size of the IO buffer. This makes it a bit hard to get meaningful results when performing EC tests as all of the data strips are the same (and will generate duplicate parities as a result, depending on which technique is used). This small change makes RBD bench write out a string of random lower case characters instead. 
```
[root@ceph build]# bin/ceph-objectstore-tool --no-mon-config --data-path dev/osd1 rbd_data.4.10635972f3e4.0000000000000039 get-bytes
fscrwqtyuynmxwvbqxorquowzhpmdzjlrlcncyoywbmvzhxpenhvivthfivkhfxbqaquyetwifthnsxrggoqbhxiqsvzzscqutmszfqjnmtaeqtmykcbrzkjuhltznluiyok…
```
Fixes: https://tracker.ceph.com/issues/67319
Signed-off by: Connor Fawcett <connorfa@uk.ibm.com> …
> rbd/bench: Add ability to write a random string of bytes or a specific byte with --pattern-byte option

- src/rgw/rgw_asio_frontend.cc
It is not suitable to stop accept socket when meeting any error in previous socket listen and accept. This will results in radosgw stop work after a occasional case. For example, Too many open files warning may occur at high iops(or just after reshard, sockets opened may increase for doing operations blocked).
based on work https://github.com/ceph/ceph/pull/59059 from cbodley
https://tracker.ceph.com/issues/67338
Signed-off-by: Mingyuan Liang <liangmingyuan@baidu.com>
> rgw/beast: optimize for accept when meeting error in listenning

- src/common/options/rgw.yaml.in
allow clients to request more than the default 1000 keys per request
bucket listing of large buckets (with many shards) can be more efficient with larger batches. raising max-keys also improves the balls-into-bins algorithm (see https://github.com/ceph/ceph/pull/30853) which we artificially cap at a minimum of 8 keys per shard
with the default max-keys=1000, we reach this min=8 at around 350 shards. above that shard count, we're always requesting more than the optimal number of entries per shard, so wasting i/o and bandwidth
as we raise the max-keys, we push this minimum to higher shard counts:
| max-keys | shard count |
|----------|-------------|
|     1000 |         350 |
|     2000 |         720 |
|     3000 |        1100 |
|     4000 |        1500 |
|     5000 |        1900 |
this …
> rgw: raise default rgw_max_listing_results=5000

- src/cephadm/cephadmlib/constants.py
- src/cephadm/cephadmlib/daemons/smb.py
- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/service_discovery.py
- src/pybind/mgr/cephadm/services/monitoring.py
- src/pybind/mgr/cephadm/services/smb.py
- src/pybind/mgr/cephadm/templates/services/prometheus/prometheus.yml.j2
- src/pybind/mgr/cephadm/tests/test_service_discovery.py
- src/pybind/mgr/cephadm/tests/test_services.py
Implement metrics-exporter from smb service using side-car container. Exports metrics to Prometheus via port [9922](https://github.com/prometheus/prometheus/wiki/Default-port-allocations). Follow same scrape pattern as used for [NFS-Ganesha](https://github.com/ceph/ceph/pull/55050) metrics exporting. …
> cephadm: samba metrics exporter

- src/pybind/mgr/object_format.py
backport tracker: https://tracker.ceph.com/issues/65949
---
backport of https://github.com/ceph/ceph/pull/56963
parent tracker: https://tracker.ceph.com/issues/65554
> reef: mgr/pybind/object_format: fix json-pretty being marked invalid

- src/cephadm/samples/nfs.json
backport tracker: https://tracker.ceph.com/issues/65416
---
backport of https://github.com/ceph/ceph/pull/56481
parent tracker: https://tracker.ceph.com/issues/65155
> reef: cephadm: add idmap.conf to nfs sample file

- doc/cephadm/upgrade.rst
Add instructions for removing malformed JSON that causes the cephadm module to fail to start, which in turn makes the orchestrator fail to start.
(cherry picked from commit 93d90ea358cf17b08e502caf8529061a10008fad) …
> squid: doc/cephadm: add malformed-JSON removal instructions

- doc/cephadm/upgrade.rst
Add instructions for removing malformed JSON that causes the cephadm module to fail to start, which in turn makes the orchestrator fail to start.
(cherry picked from commit 93d90ea358cf17b08e502caf8529061a10008fad) …
> reef: doc/cephadm: add malformed-JSON removal instructions

- doc/cephadm/upgrade.rst
Add instructions for removing malformed JSON that causes the cephadm module to fail to start, which in turn makes the orchestrator fail to start.
(cherry picked from commit 93d90ea358cf17b08e502caf8529061a10008fad) …
> quincy: doc/cephadm: add malformed-JSON removal instructions

- src/cephadm/cephadm.py
- src/cephadm/tests/test_cephadm.py
backport tracker: https://tracker.ceph.com/issues/65418
---
backport of https://github.com/ceph/ceph/pull/56561
parent tracker: https://tracker.ceph.com/issues/65122
> reef: cephadm: fix host-maintenance command always exiting with a failure

- src/pybind/mgr/orchestrator/module.py
backport tracker: https://tracker.ceph.com/issues/67695
---
backport of https://github.com/ceph/ceph/pull/59175
parent tracker: https://tracker.ceph.com/issues/67372
> squid: mgr/orchestrator: fix encrypted flag handling in orch daemon add osd

- src/pybind/mgr/cephadm/serve.py
- src/pybind/mgr/cephadm/tests/test_services.py
Backport of https://github.com/ceph/ceph/pull/58230
<details>
</details>
> squid: mgr/cephadm: redeploy when some dependency daemon is add/removed

- doc/man/8/ceph-bluestore-tool.rst
Edit the section "bluefs-bdev-migrate" in
doc/man/8/ceph-bluestore-tool.rst to add the information that this operation expands the target storage by updating its size label, making "bluefs-bdev-expand" unnecessary.
Improve the subject-verb agreement in this section, and supply some absent definite articles. …
> doc/man: edit ceph-bluestore-tool.rst

- src/crimson/osd/ec_backend.cc
- src/crimson/osd/object_metadata_helper.cc
- src/crimson/osd/ops_executer.cc
- src/crimson/osd/ops_executer.h
- src/crimson/osd/osd_operations/snaptrim_event.cc
- src/crimson/osd/osd_operations/snaptrim_event.h
- src/crimson/osd/pg.cc
- src/crimson/osd/pg.h
- src/crimson/osd/pg_backend.h
- src/crimson/osd/replicated_backend.cc
- src/osd/SnapMapper.cc
- src/osd/SnapMapper.h
- src/test/crimson/test_calc_subsets.cc
This is a POC draft.
Fixes: https://tracker.ceph.com/issues/67057
- …
> crimson/osd/pg: properly propagate snap mapper updates and do clean-region-based clone objects recovery

- src/crimson/common/gated.h
- src/crimson/net/io_handler.h
- src/crimson/os/alienstore/alien_store.cc
- src/crimson/os/alienstore/alien_store.h
- src/crimson/osd/osd.cc
- src/crimson/osd/osd.h
This change modifies AlienStore and OSD to use a gate per seastar
shard instead of a shared gate.
It introduces a new `gate_per_shard` class in `Gated` to manage
a vector of gates, ensuring proper gate handling across shards.
Fixes: https://tracker.ceph.com/issues/64332
Signed-off-by: NitzanMordhai <nmordech@redhat.com> …
> crimson: use gate per shard for AlienStore and OSD

- src/cls/rbd/cls_rbd_client.cc
- src/cls/rbd/cls_rbd_client.h
- src/librbd/CMakeLists.txt
- src/librbd/api/Group.cc
- src/librbd/api/Group.h
- src/librbd/group/ListSnapshotsRequest.cc
- src/librbd/group/ListSnapshotsRequest.h
- src/librbd/librbd.cc
- src/test/librados_test_stub/LibradosTestStub.cc
- src/test/librbd/test_Groups.cc
Adds methods for asynchronous cls group_snap_list and group_snap_list_order, a helper class to list group snaps asynchronously, and modifies librbd::Group::group_snap_list() to use the async methods.
Credit to Mykola Golub <mgolub@suse.com> for the initial work.
Fixes: https://tracker.ceph.com/issues/51686 …
> librbd: make "group snap list" async and optionally sorted by snap creation time

- src/pybind/mgr/smb/handler.py
It was found during testing that a sequence of commands like:
```
ceph smb cluster create slow1 user --define-user-pass=user1%badf00d --clustering=always
--placement=3
sleep 0.5
ceph smb share create slow1 share1 cephfs --subvolume=g1/sv1 --path=/
sleep 0.5
ceph smb share create slow1 share2 cephfs --subvolume=g1/sv2 --path=/
```
would create a CTDB enabled cluster that would fail to start up correctly. The issue was due to the call to `external.rm_other_in_ns` during the cluster sync operation. In the CTDB enabled mode, objects are written to the pool outside of the smb mgr module's direct control and this function, intended to keep the pool & namespace tidy, was removing files needed by CTDB-enabled mode. The failure is somewhat timing sensitive due to the ctdb enablement sidecars …
> mgr/smb: stop trying to clean external store during cluster sync

- src/cephadm/cephadm.py
The grafana-server command is deprecated in grafana v10.4.0. It is advised to use grafan server in place of it.
Fixes: https://tracker.ceph.com/issues/65479 …
> mgr/dashboard: use grafana server instead of grafana-server in grafana 10.4.0

- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
Fixes https://tracker.ceph.com/issues/67871
The maximum namespace count will be 1024 for subsystems now.
<details>
</details>
> mgr/dashboard: Increase maximum namespace count to 1024

- doc/man/8/ceph-bluestore-tool.rst
Edit the section "bluefs-bdev-migrate" in
doc/man/8/ceph-bluestore-tool.rst to add the information that this operation expands the target storage by updating its size label, making "bluefs-bdev-expand" unnecessary.
Improve the subject-verb agreement in this section, and supply some absent definite articles.
Co-authored-by: Peter Gervai <grin@drop.grin.hu>
(cherry picked from commit 6b34707f827b2b197f53fe2e430d173b30b81401)
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-b …
> quincy: doc/man: edit ceph-bluestore-tool.rst

- doc/man/8/ceph-bluestore-tool.rst
Edit the section "bluefs-bdev-migrate" in
doc/man/8/ceph-bluestore-tool.rst to add the information that this operation expands the target storage by updating its size label, making "bluefs-bdev-expand" unnecessary.
Improve the subject-verb agreement in this section, and supply some absent definite articles.
Co-authored-by: Peter Gervai <grin@drop.grin.hu>
(cherry picked from commit 6b34707f827b2b197f53fe2e430d173b30b81401)
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-b …
> reef: doc/man: edit ceph-bluestore-tool.rst

- doc/man/8/ceph-bluestore-tool.rst
Edit the section "bluefs-bdev-migrate" in
doc/man/8/ceph-bluestore-tool.rst to add the information that this operation expands the target storage by updating its size label, making "bluefs-bdev-expand" unnecessary.
Improve the subject-verb agreement in this section, and supply some absent definite articles.
Co-authored-by: Peter Gervai <grin@drop.grin.hu>
(cherry picked from commit 6b34707f827b2b197f53fe2e430d173b30b81401)
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-b …
> squid: doc/man: edit ceph-bluestore-tool.rst

- README.md
Improve the formatting of the section "Building Ceph" in the file README.md.
(cherry picked from commit 7171f73c81d603f8ff62198fc1e5f50c20a0aa05) …
> quincy: doc/README.md: improve formatting

- src/cephadm/cephadm.py
If an image is not specified, cephadm shell will use the image corresponding to a Ceph daemon running on the host (and will log a debug message to that effect).
However, it will only use that image if it appears in the output of:
podman images --filter label=ceph=True --filter dangling=false
This commit means that cephadm will emit a warning if the container image it was going to use fails this check, so the operator has more of a clue to what is going on.
Fixes: https://tracker.ceph.com/issues/67778
<details> …
> cephadm: emit warning if daemon's image is not to be used

- src/ceph-volume/ceph_volume/devices/lvm/listing.py
backport tracker: https://tracker.ceph.com/issues/64643
---
backport of https://github.com/ceph/ceph/pull/53841
parent tracker: https://tracker.ceph.com/issues/62320
> quincy: src/ceph-volume/ceph_volume/devices/lvm/listing.py : lvm list filters with vg name

- src/ceph-volume/ceph_volume/devices/lvm/prepare.py
backport tracker: https://tracker.ceph.com/issues/66025
---
backport of https://github.com/ceph/ceph/pull/56882
parent tracker: https://tracker.ceph.com/issues/65477
> quincy: ceph-volume: create LVs when using partitions

- doc/rados/operations/health-checks.rst
Add a procedure to doc/rados/operations/health-warnings.rst that explains how to remedy the "X PGs not deep-scrubbed in time" health warning. …
> doc/rados: add "pgs not deep scrubbed in time" info

- src/cephadm/cephadm.py
There have been occasional failures when bootstrapping with error messages like
```
Module 'orchestrator' is not enabled/loaded (required by command 'orch set backend'): use `ceph mgr module enable orchestrator` to enable it
```
despite the orchestrator being meant to be an always on module.
Since trying to enable an already enabled module causes no issues, trying to enable it ourselves seems like a sensible workaround.
Fixes: https://tracker.ceph.com/issues/67969
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backpo …
> cephadm: bootstrap: verify orch module is running before setting cephadm backend

- doc/rados/operations/health-checks.rst
Add a procedure to doc/rados/operations/health-warnings.rst that explains how to remedy the "X PGs not deep-scrubbed in time" health warning.
(cherry picked from commit d620a51c306d1ebcdfc974dc0b85dc46cfde8d40) …
> reef: doc/rados: add "pgs not deep scrubbed in time" info

- doc/rados/operations/health-checks.rst
Add a procedure to doc/rados/operations/health-warnings.rst that explains how to remedy the "X PGs not deep-scrubbed in time" health warning.
(cherry picked from commit d620a51c306d1ebcdfc974dc0b85dc46cfde8d40) …
> squid: doc/rados: add "pgs not deep scrubbed in time" info

- doc/rados/operations/health-checks.rst
Add a procedure to doc/rados/operations/health-warnings.rst that explains how to remedy the "X PGs not deep-scrubbed in time" health warning.
(cherry picked from commit d620a51c306d1ebcdfc974dc0b85dc46cfde8d40) …
> quincy: doc/rados: add "pgs not deep scrubbed in time" info

- src/pybind/mgr/cephadm/services/nvmeof.py
- src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
- src/python-common/ceph/deployment/service_spec.py
mgr/cephadm: Make the discovery and gateway IPs configurable in NVMEof configuration
python-common/ceph/deployment: Make the discovery and gateway IPs configurable in NVMEof configuration
Fixes https://tracker.ceph.com/issues/68030 …
> Make the discovery and gateway IPs configurable in NVMEof configuration

- doc/dev/release-checklists.rst
Add a step to the section called "First Stable Release" that explains how to activate the latest release in Read the Docs.
(cherry picked from commit e7bd4bcdd074a3defae5866a6c035559bf210271) …
> quincy: doc/dev: add "activate latest release" RTD step

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.html
backport tracker: https://tracker.ceph.com/issues/67996
---
backport of https://github.com/ceph/ceph/pull/59599
parent tracker: https://tracker.ceph.com/issues/67893
> squid: mgr/dashboard: Rephrase dedicated pool helper in rbd create form

- src/pybind/mgr/dashboard/controllers/host.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-form/nvmeof-listeners-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-import/rgw-multisite-import.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/host.service.ts
Fixes: https://tracker.ceph.com/issues/67413
We have exposed UIRouter API to fetch all hosts information!
https://github.com/user-attachments/assets/19dad62b-5761-453c-9e5b-7a4f2e6faf74
form with dummy values …
> mgr/dashboard: service form hosts selection only show up to 10 entries

- src/pybind/mgr/cephadm/services/nvmeof.py
- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/nvmeof_cli.py
- src/pybind/mgr/dashboard/services/nvmeof_client.py
- src/pybind/mgr/dashboard/services/nvmeof_conf.py
Introduces a gw_group query-param to gateway and subsystem requests.
Modified the dashboard config to support adding more than one gateway to the list.
Fixes: https://tracker.ceph.com/issues/67774
API Req with different gw_groups
**group: test2t`**
```
╰─$ curl -kX GET "https://192.168.100.100:8443/api/nvmeof/gateway?gw_group=test2t" \
-H "Accept: application/vnd.ceph.api.v1.0+json" \
-H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" | jq .
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   206  100   206    0     0   1065      0 --:--:-- --:--:-- --:--:--  1067
{
"cli_version": "",
"version": "1.2.17",
"name": "client.nvmeof.test2t.ceph-node-00.usrpwk",
"group": "test2t",
"addr": …
```
> mgr/dashboard: add gw_groups support to nvmeof api

- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
backport tracker: https://tracker.ceph.com/issues/67993
---
backport of https://github.com/ceph/ceph/pull/59569
parent tracker: https://tracker.ceph.com/issues/67871
> squid: mgr/dashboard: Increase maximum namespace count to 1024 

- ceph.spec.in
- src/ceph-volume/ceph_volume/__init__.py
- src/ceph-volume/ceph_volume/devices/lvm/activate.py
- src/ceph-volume/ceph_volume/devices/lvm/batch.py
- src/ceph-volume/ceph_volume/devices/lvm/common.py
- src/ceph-volume/ceph_volume/devices/raw/common.py
- src/ceph-volume/ceph_volume/tests/util/test_encryption.py
- src/ceph-volume/ceph_volume/util/arg_validators.py
- src/ceph-volume/ceph_volume/util/device.py
- src/ceph-volume/ceph_volume/util/disk.py
- src/ceph-volume/ceph_volume/util/encryption.py
backport tracker: https://tracker.ceph.com/issues/64196
---
backport of https://github.com/ceph/ceph/pull/54423
parent tracker: https://tracker.ceph.com/issues/64195
> quincy: ceph-volume: use 'no workqueue' options with dmcrypt

- src/rgw/rgw_kafka.cc
also, use unique_ptr for safer memory management.
Fixes: https://tracker.ceph.com/issues/68033
<details>
</details>
> rgw/kafka: refactor topic creation to avoid rd_kafka_topic_name()

- src/crimson/osd/osd.cc
- src/crimson/osd/osd.h
Otherwise, we would invoke _write_bdev_label on each committed map:
```
DEBUG 2024-08-14 17:12:55,789 [shard 0:main] bluestore - bluestore(/var/lib/ceph/osd/ceph-2/block) _write_bdev_label path /var/lib/ceph/osd/ceph-2/block label bdev(osd_uuid d2ce936a-24b4-415d-9979-c8d75a9ea0f4, size 0x1680000000, btime 2024-08-14T17:10:52.823128+0000, desc main, 16 meta) locations [0,1073741824,10737418240]
DEBUG 2024-08-14 17:12:56,792 [shard 0:main] bluestore - bluestore(/var/lib/ceph/osd/ceph-2/block) _write_bdev_label path /var/lib/ceph/osd/ceph-2/block label bdev(osd_uuid d2ce936a-24b4-415d-9979-c8d75a9ea0f4, size 0x1680000000, btime 2024-08-14T17:10:52.823128+0000, desc main, 16 meta) locations [0,1073741824,10737418240]
DEBUG 2024-08-14 17:12:57,800 [shard 0:main] bluestore - …
```
> crimson/osd: write require_osd_release only when needed

- src/pybind/mgr/cephadm/services/oauth2_proxy.py
- src/python-common/ceph/deployment/service_spec.py
this field is needed in order to configure which domains are allowed for redirection during login and/or logout
Fixes: https://tracker.ceph.com/issues/67934
Configuration example:
```
service_type: oauth2-proxy
placement:
hosts:
- ceph-node-2
spec:
https_address: "0.0.0.0:4180"
provider_display_name: "My OIDC Provider"
client_id: "oauth2-proxy"
client_secret: "vwCLTITb2rtem583523uXcuSNItDsz1I"
cookie_secret: "kbAEM9opAmuHskQvt0AW8oeJRaOM2BYy5Loba0kZ0SQ="
oidc_issuer_url: "http://192.168.100.1:8080/realms/ceph"
whitelist_domains:
- domain1.com
- 192.168.100.1:8080
``` …
> mgr/cephadm: adding spec fields for oauth2-proxy whitelist_domains

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-gateway/nvmeof-gateway.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-initiators-list/nvmeof-initiators-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-list/nvmeof-listeners-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
backport tracker: https://tracker.ceph.com/issues/67994
---
backport of https://github.com/ceph/ceph/pull/59447
parent tracker: https://tracker.ceph.com/issues/67728
> squid: mgr/dashboard: Update nvmeof microcopies 

- src/rgw/rgw_gc.cc
backport tracker: https://tracker.ceph.com/issues/61633
---
backport of https://github.com/ceph/ceph/pull/49316
parent tracker: https://tracker.ceph.com/issues/57323
> quincy: rgw : fix add initialization for RGWGC::process()

- qa/suites/rgw/tempest/tasks/rgw_tempest.yaml
- src/common/ceph_crypto.h
- src/rgw/rgw_rest_swift.cc
- src/rgw/rgw_rest_swift.h
- src/rgw/rgw_swift_auth.cc
- src/rgw/rgw_swift_auth.h
backport tracker: https://tracker.ceph.com/issues/64276
---
backport of https://github.com/ceph/ceph/pull/47723
parent tracker: https://tracker.ceph.com/issues/56564
> quincy: rgw: swift: tempurl fixes for ceph

- src/ceph-volume/ceph_volume/util/disk.py
backport tracker: https://tracker.ceph.com/issues/63919
---
backport of https://github.com/ceph/ceph/pull/53327
parent tracker: https://tracker.ceph.com/issues/63918
> quincy: ceph-volume: Fix unbound var in disk.get_devices()

- src/common/options/osd.yaml.in
Based on observing a specific large customer's cluster:
The previous default of 25 objects per chunk proved to take too long (many hundreds of milliseconds) on a busy cluster. As the scrubber locks all objects in the chunk for the duration, a large chunk size can cause a significant impact on the client ops' latencies.
Fixes: https://tracker.ceph.com/issues/68057
> osd/scrub: decrease default deep scrub chunk size

- doc/rados/operations/health-checks.rst
Add a second method of changing the value of osd_deep_scrub_interval to remedy the condition indicated by the "PGs not deep-scrubbed in time" warning. …
> doc/rados: add osd_deep_scrub_interval setting operation

- README.md
Add ordered-list formatting to the "Building Ceph" section of README.md.
(cherry picked from commit 1f21057e4166f2ea9f51ee037eb8e234c1390cfb) …
> quincy: doc/README.md - add ordered list

- doc/install/install-storage-cluster.rst
Add prompts to doc/install/install-storage-cluster.rst.
- …
> doc/install: add prompts to install-storage-cluster

- doc/rados/operations/health-checks.rst
Add a second method of changing the value of osd_deep_scrub_interval to remedy the condition indicated by the "PGs not deep-scrubbed in time" warning.
(cherry picked from commit f57e99e1731af3affee1c299bb9a79852e31f5ea) …
> squid: doc/rados: add osd_deep_scrub_interval setting operation

- doc/rados/operations/health-checks.rst
Add a second method of changing the value of osd_deep_scrub_interval to remedy the condition indicated by the "PGs not deep-scrubbed in time" warning.
(cherry picked from commit f57e99e1731af3affee1c299bb9a79852e31f5ea) …
> reef: doc/rados: add osd_deep_scrub_interval setting operation

- doc/rados/operations/health-checks.rst
Add a second method of changing the value of osd_deep_scrub_interval to remedy the condition indicated by the "PGs not deep-scrubbed in time" warning.
(cherry picked from commit f57e99e1731af3affee1c299bb9a79852e31f5ea) …
> quincy: doc/rados: add osd_deep_scrub_interval setting operation

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-multisite.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-details/rgw-multisite-sync-policy-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-details/rgw-multisite-sync-policy-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rgw_client.py
This PR fixes the issue of removing/editing zones from symmetrical flow and Pipe. Previously we were not able to remove zones from either flow & pipe, but after this PR we will be able to do so.
Fixes: https://tracker.ceph.com/issues/66945
https://github.com/user-attachments/assets/222d2e9c-768a-4469-a958-ac20a7e55a54
**NOTE:** removed 'edit' button from the directional flow as we can't edit the zones, so everytime we need to create a new zone or either delete it, its the functionality set from core backend. …
> mgr/dashboard: RGW multisite sync remove zones fix

- src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/services.po.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/orchestrator/05-services.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/service.interface.ts
Fixes: https://tracker.ceph.com/issues/67651
[screen-capture (24).webm](https://github.com/user-attachments/assets/a6aefe30-1278-4e52-90c1-30eec4c57137)
Video's spec file:
```
[ceph: root@ceph-node-00 /]# ceph orch ls --service_name oauth2-proxy --export
service_type: oauth2-proxy
service_name: oauth2-proxy
placement:
count: 1
spec:
allowlist_domains:
- domain1.com
- 192.168.1.1:433
- 192.168.100.100
- ceph-node-00
client_id: clientid
client_secret: clientsecret
oidc_issuer_url: https://0.0.0.0
provider_display_name: My OIDC provider
``` …
> mgr/dashboard: add service management for oauth2-proxy

- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/crush-rule-form-modal/crush-rule-form-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/erasure-code-profile-form/erasure-code-profile-form-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/erasure-code-profile-form/erasure-code-profile-form-modal.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/erasure-code-profile-form/erasure-code-profile-form-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/crush-rule.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/erasure-code-profile.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/classes/crush.node.selection.class.ts
Fixes https://tracker.ceph.com/issues/67853
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2305949
When EC pools are created with device class specified, the pools are created with just 1 PG and autoscaler does not work. PG autoscaler not working on a cluster where pools have multiple overlapping roots is a known issue, and bug is raised for same 
Issue documented already : https://docs.ceph.com/en/reef/rados/operations/placement-groups/#viewing-pg-scaling-recommendations
Also renames "let ceph decide" option to "All devices" in crush rule and ec profile component.
Updates Unit tests for ec profile modal
[Screencast from 2024-09-02 15-27-54.webm](https://github.com/user-attachments/assets/6cdaed19-0e7f-4855-aad1-07008c95b1ec)
[Screencast from 2024-09-10 …
> mgr/dashboard: mgr/dashboard: Select no device by default in EC profile

- src/pybind/mgr/orchestrator/module.py
The intent of 42721c03ee6f was to address an issue where boolean parameters weren't handled correctly.
I noticed that a parameter (`tpm2`) was missed, which made me realize that maintaining a list of these boolean parameters is necessary.
To simplify things, we should only accept `"true"` or `"false"` (in any case), allowing us to avoid the need to maintain a list of boolean parameters.
This change introduces a `list_drive_group_spec_bool_arg` to store boolean arguments related to drive group specifications, simplifying the validation process for boolean values by directly checking if the values are 'true' or 'false'.
Fixes: https://tracker.ceph.com/issues/68045
> orch: refactor boolean handling in drive group spec

- src/pybind/mgr/dashboard/controllers/host.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-form/nvmeof-listeners-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-import/rgw-multisite-import.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/host.service.ts
backport tracker: https://tracker.ceph.com/issues/68042
backport of: https://github.com/ceph/ceph/pull/59576
parent tracker: https://tracker.ceph.com/issues/67413
<hr style="border: 2px solid #eeeeee" />
exposed new UIRouter API to get all hosts
Fixes: https://tracker.ceph.com/issues/67413
(cherry picked from commit ec3e4abeeb7feebd996681a7d8d4e950de5cf518)
Conflicts:
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts (resolved conflicts) …
> Squid: mgr/dashboard: service form hosts selection only show up to 10 entries 

- src/cephadm/cephadm.py
backport tracker: https://tracker.ceph.com/issues/67990
---
backport of https://github.com/ceph/ceph/pull/56858
parent tracker: https://tracker.ceph.com/issues/65479
> squid: mgr/dashboard: use grafana server instead of grafana-server in grafana 10.4.0

- src/pybind/mgr/dashboard/controllers/host.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-import/rgw-multisite-import.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/host.service.ts
backport tracker: https://tracker.ceph.com/issues/68043
backport of: #59576
parent tracker: https://tracker.ceph.com/issues/67413
<hr style="border: 2px solid #eeeeee" />
exposed new UIRouter API to get all hosts
Fixes: https://tracker.ceph.com/issues/67413
(cherry picked from commit ec3e4abeeb7feebd996681a7d8d4e950de5cf518)
Conflicts:
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-form/nvmeof-listeners-form.component.ts (file deleted)
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts (resolved conflicts) …
> Reef: mgr/dashboard: service form hosts selection only show up to 10 entries 

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-details/pool-details.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/service.interface.ts
- src/pybind/mgr/dashboard/frontend/src/testing/unit-test-helper.ts
[mgr/dashboard: Adding group and pool name to service name](https://github.com/ceph/ceph/commit/551b6b2924933f5a43acc1aea98978e41193cfab) 
- Pre-populating the service name field with the format `nvmeof.<pool_name>.<group_name>`.
- This can be changed by user but by default this value will be there.
- This will help user to quickly fill form and proceed hence improving usability.
- cephadm also uses this format as of now this convention so it will make UI aligned with CLI experience
- updates unit tests to improve coverage
- hides`count` values as that is not needed for 'nvmeof' only hosts and labels required.
Fixes https://tracker.ceph.com/issues/68065
[mgr/dashboard: Add mTLS support](https://github.com/ceph/ceph/commit/4db35e8a4f8884d93874cd06da826ba0746974dd) 
- enables mTLS support …
> mgr/dashboard: Nvme mTLS support and  service name changes

- PendingReleaseNotes
- doc/mgr/nfs.rst
- qa/tasks/cephfs/test_nfs.py
- src/pybind/mgr/nfs/export.py
- src/pybind/mgr/nfs/ganesha_conf.py
- src/pybind/mgr/nfs/module.py
- src/pybind/mgr/nfs/tests/test_nfs.py
1. Introduction of cmount_path
- Added the cmount_path field to the FSAL block for CephFS-based exports. 
2. Validation Logic Enhancement:
- Simplified the validation function to ensure that cmount_path is a superset of the specified path.
3. F-String Refactoring: 
- Replaced the old string formatting methods with f-strings throughout the code.
4. User ID Generation:
- Introduced a new generate_user_id function that creates user IDs using SHA-1 hashing
5. Error Handling:
- Improved error handling with more descriptive messages, particularly for issues related to cmount_path validation. …
> mgr/nfs: generate user_id & access_key for apply_export(CephFS)

- README.md
An indentation of five spaces relative to the previous line creates a command that is copyable with a single mouse click. This commit adds those copyabale commands to the procedure in the section "Building Ceph". …
> doc/README.md: create selectable commands

- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/crush-rule-form-modal/crush-rule-form-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/erasure-code-profile-form/erasure-code-profile-form-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/erasure-code-profile-form/erasure-code-profile-form-modal.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/erasure-code-profile-form/erasure-code-profile-form-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/crush-rule.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/erasure-code-profile.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/classes/crush.node.selection.class.ts
backport tracker: https://tracker.ceph.com/issues/68079
---
backport of https://github.com/ceph/ceph/pull/59557
parent tracker: https://tracker.ceph.com/issues/67853
> squid: mgr/dashboard: mgr/dashboard: Select no device by default in EC profile

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-detail/cephfs-detail.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/services.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/shared/device-list/device-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/doc/doc.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts
- src/pybind/mgr/dashboard/frontend/src/styles.scss
- src/pybind/mgr/dashboard/frontend/src/styles/_carbon-defaults.scss
- fixes table in table structure's unusual padding
- fixes the ceph fs details page where table was getting hidden
- improving the subvolume list page by changing the spacings there
- hide the refresh button where it shouldn't be shown.
- fixes the osd details view where disks and osds are not shown in it.
- fixes the service count issue in the expand cluster view.
Fixes: https://tracker.ceph.com/issues/68050
**BEFORE**
**AFTER** …
> mgr/dashboard: fix minor issues in carbon tables

- doc/cephfs/fs-volumes.rst
- qa/tasks/cephfs/test_volumes.py
- src/pybind/mgr/volumes/fs/operations/subvolume.py
- src/pybind/mgr/volumes/fs/operations/template.py
- src/pybind/mgr/volumes/fs/operations/versions/subvolume_base.py
- src/pybind/mgr/volumes/fs/operations/versions/subvolume_v1.py
- src/pybind/mgr/volumes/fs/operations/versions/subvolume_v2.py
- src/pybind/mgr/volumes/fs/volume.py
- src/pybind/mgr/volumes/module.py
- src/python-common/ceph/fs/__init__.py
- src/python-common/ceph/fs/earmarking.py
- src/python-common/ceph/tests/test_earmarking.py
Purpose:
- To prevent data corruption and ensure protocol compatibility, subvolumes must be restricted to a single protocol scope—either NFS-ganesha or SMB. Currently, our system does not support mixed protocol use within the same subvolume  and attempting to do so could lead to data corruption.
Solution:
- Implemented earmarking functionality for subvolumes upon creation, ensuring that they do not share the same subvolume to avoid data corruption due to unsupported mixed protocol use.
- Added commands to set get/set/rm earmark from a given subvolume 
```
[ceph: root@ceph-node-00 /]# ceph fs subvolume create fs1 sv1 --earmark smb   
[ceph: root@ceph-node-00 /]# ceph fs subvolume info fs1 sv1              
{
"atime": "2024-08-19 11:33:20",
"bytes_pcent": "undefined",
"bytes_quota": …
```
> mgr/volumes: add earmarking for subvol

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-multisite.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-details/rgw-multisite-sync-policy-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-details/rgw-multisite-sync-policy-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rgw_client.py
backport tracker: https://tracker.ceph.com/issues/68074
backport of: #59061
parent tracker: https://tracker.ceph.com/issues/66945
<hr style="border:2px solid #eeeeee" />
Fixes: https://tracker.ceph.com/issues/66945
(cherry picked from commit 5eee7e8105167dc4f0542f62d041fbcb143611d0)
Conflicts:
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-details/rgw-multisite-sync-policy-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
Tested Locally:
https://github.com/user-attachments/assets/3d7b3d81-c9bb-4b3a-8852-49c78a0f39f8
- If you are …
> Squid: mgr/dashboard: RGW multisite sync remove zones fix

- README.md
An indentation of five spaces relative to the previous line creates a command that is copyable with a single mouse click. This commit adds those copyabale commands to the procedure in the section "Building Ceph".
(cherry picked from commit 36c620b04f3a88562d75955b46cc1864de60ce70) …
> reef: doc/README.md: create selectable commands

- README.md
An indentation of five spaces relative to the previous line creates a command that is copyable with a single mouse click. This commit adds those copyabale commands to the procedure in the section "Building Ceph".
(cherry picked from commit 36c620b04f3a88562d75955b46cc1864de60ce70) …
> quincy: doc/README.md: create selectable commands

- qa/tasks/cephfs/caps_helper.py
- qa/tasks/cephfs/test_admin.py
- src/mds/MDSAuthCaps.cc
- src/mds/MDSAuthCaps.h
- src/mon/AuthMonitor.cc
backport tracker: https://tracker.ceph.com/issues/67961
backport tracker: https://tracker.ceph.com/issues/67962
backport tracker: https://tracker.ceph.com/issues/67964
backport tracker: https://tracker.ceph.com/issues/67854
---
backport of https://github.com/ceph/ceph/pull/55320 and https://github.com/ceph/ceph/pull/58543
parent tracker: https://tracker.ceph.com/issues/64417
parent tracker: https://tracker.ceph.com/issues/64182
parent tracker: https://tracker.ceph.com/issues/64127
parent tracker: https://tracker.ceph.com/issues/65808
this backport was staged using ceph-backport.sh version 16.0.0.6848 *and a commit was added to it later using git*
> squid: cephfs,mon: fix bugs related to updating MDS caps

- src/common/CMakeLists.txt
- src/common/crc32c_ppc_fast_zero_asm.S
Building Ceph on IBM Power is failing with the error:
```
[ 46%] Linking CXX executable ../../bin/ceph-authtool
cd /builddir/build/BUILD/ceph-19.0.0-2896-g6f942bab/redhat-linux-build/src/tools && /usr/bin/cmake -E cmake_link_script CMakeFiles/ceph-authtool.dir/link.txt --verbose=1
/usr/bin/c++ -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong   -m64 -mcpu=power9 -mtune=power9 -fasynchronous-unwind-tables -fstack-clash-protection -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -rdynamic -pie "CMakeFiles/ceph-authtool.dir/ceph_authtool.cc.o" -o ../../bin/ceph-authtool …
```
> Change code from non-PIC to PIC for ppc64

- src/pybind/mgr/orchestrator/module.py
- Correct usage examples for 'ceph orch daemon add osd'
- Fix boolean argument handling for drive group specifications
Fixes: https://tracker.ceph.com/issues/68045
> orch: Fix `daemon add osd` boolean param handling

- src/pybind/mgr/cephadm/cert_mgr.py
- src/pybind/mgr/cephadm/services/cephadmservice.py
- src/pybind/mgr/cephadm/ssl_cert_utils.py
- src/pybind/mgr/cephadm/tests/test_node_proxy.py
- src/python-common/ceph/deployment/service_spec.py
If users are okay with a self-signed cert and would prefer to
just let cephadm generate it for them rather than creating it
themselves. Additionally, if the zonegroup_hostnames field is
set, add those entries to the SANs entries for the cert in
order to facilitate virtual host bucket access
Docs and Teuthology test TODO after initial testing …
> mgr/cephadm: add ability for cephadm to generate frontend cert for rgw

- src/pybind/mgr/cephadm/tests/test_services.py
- src/python-common/ceph/deployment/service_spec.py
ceph-exporter port was not opened properly during daemon deployment forcing the user to open it manually. This change fixes the logic to open the port automatically.
Fixes: https://tracker.ceph.com/issues/67975 …
> mgr/cephadm: open ceph-exporter when firewalld is enabled

- doc/rados/operations/health-checks.rst
Add confval directives to doc/rados/operations/health-checks.rst, as requested by Anthony D'Atri here: https://github.com/ceph/ceph/pull/59635#pullrequestreview-2286205705 …
> doc/rados: add confval directives to health-checks

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
Due to conflicts with SSO PR, mTLS fields are not updated properly in code. This is happening only in main as noted: https://github.com/ceph/ceph/pull/59819#issuecomment-2356523491
The effect of this issue is mtls based fields not showing in service form
Fixes https://tracker.ceph.com/issues/68133
[Screencast from 2024-09-18 19-12-23.webm](https://github.com/user-attachments/assets/fe94c4de-9704-46b0-9864-4b7b7dafffae)
[Screencast from 2024-09-18 19-09-45.webm](https://github.com/user-attachments/assets/4e3f69ed-3fd2-492a-91a8-7ca0f0619684)
<details>
- `jenkins …
> mgr/dashboard: Service form fixes for mTLS 

- src/test/rbd_mirror/test_mock_PoolReplayer.cc
- src/tools/rbd_mirror/PoolReplayer.cc
backport tracker: https://tracker.ceph.com/issues/67762
---
backport of https://github.com/ceph/ceph/pull/59401
parent tracker: https://tracker.ceph.com/issues/67676
> quincy: rbd-mirror: use correct ioctx for namespace

- qa/workunits/rbd/cli_migration.sh
- src/librbd/ImageCtx.cc
- src/librbd/io/Utils.cc
- src/librbd/io/Utils.h
- src/librbd/migration/NativeFormat.cc
- src/librbd/migration/QCOWFormat.cc
- src/librbd/migration/RawFormat.cc
- src/test/librbd/migration/test_mock_RawFormat.cc
backport tracker: https://tracker.ceph.com/issues/67896
---
backport of https://github.com/ceph/ceph/pull/59551
parent tracker: https://tracker.ceph.com/issues/67845
> quincy: librbd/migration: prune snapshot extents in RawFormat::list_snaps()

- src/tools/rbd/action/Bench.cc
backport tracker: https://tracker.ceph.com/issues/67734
---
backport of https://github.com/ceph/ceph/pull/59423
parent tracker: https://tracker.ceph.com/issues/67698
> quincy: rbd: "rbd bench" always writes the same byte

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.html
backport tracker: https://tracker.ceph.com/issues/68143
---
backport of https://github.com/ceph/ceph/pull/59554
parent tracker: https://tracker.ceph.com/issues/67850
> reef: mgr/dashboard: Wrong(half) uid is observed in dashboard

- qa/crontab/teuthology-cronjobs
This commit adds the Crimson-RADOS suite to the crontab jobs that run weekly, matching the priority of the RADOS
Signed-off-by: Nitzan Mordechai nmordech@redhat.com …
> qa/crontab: Add weekly crimson-rados suites

- src/pybind/mgr/tox.ini
For some reason mypy on python 3.12 can no longer automatically find imports from python-common. Help it out by expanding the MYPYPATH value for the tox.ini. …
> pybind/mgr: attempt to fix mypy importing from python-common

- doc/rados/operations/health-checks.rst
Add confval directives to doc/rados/operations/health-checks.rst, as requested by Anthony D'Atri here: https://github.com/ceph/ceph/pull/59635#pullrequestreview-2286205705
(cherry picked from commit a159821ddfcecaa75f5a92af7e22ea198d82a8db) …
> quincy: doc/rados: add confval directives to health-checks

- doc/rados/operations/health-checks.rst
Add confval directives to doc/rados/operations/health-checks.rst, as requested by Anthony D'Atri here: https://github.com/ceph/ceph/pull/59635#pullrequestreview-2286205705
(cherry picked from commit a159821ddfcecaa75f5a92af7e22ea198d82a8db) …
> reef: doc/rados: add confval directives to health-checks

- doc/rados/operations/health-checks.rst
Add confval directives to doc/rados/operations/health-checks.rst, as requested by Anthony D'Atri here: https://github.com/ceph/ceph/pull/59635#pullrequestreview-2286205705
(cherry picked from commit a159821ddfcecaa75f5a92af7e22ea198d82a8db) …
> squid: doc/rados: add confval directives to health-checks

- src/osd/PG.cc
- src/osd/PG.h
- src/osd/PrimaryLogPG.cc
- src/osd/scrubber/osd_scrub.cc
- src/osd/scrubber/pg_scrubber.cc
- src/osd/scrubber/pg_scrubber.h
- src/osd/scrubber/scrub_job.cc
- src/osd/scrubber/scrub_job.h
- src/osd/scrubber/scrub_queue_entry.h
- src/osd/scrubber_common.h
The previous steps in the refactoring of the scheduler have
created simple constructs to hold the desired characteristics
of the next shallow and deep scrubs of each PG.
For example: whenever a shallow scrubs ends with errors that
require a recovery process, a deep scrub should be scheduled
to follow it. Previously - that was done by setting some
requested_scrub flags. Now - the urgency of the deep scrub
is set to 'repairing', and the scheduler will take care of
the rest.
The requested_scrub flags are no longer needed, and can be
removed.
Also in this PR:
Completing the refactoring of the on_mid_scrub_abort() method,
which was only partially done in the previous PRs.
> osd/scrub: remove the requested_scrub flags set

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/block.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-form/nvmeof-listeners-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-list/nvmeof-listeners-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-details/nvmeof-subsystems-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-details/nvmeof-subsystems-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts
- Allows listing the subsystems per gateway group.
- Using carbon combobox component for the selector.
- Adds unit tests for switcher and updates existing.
Fixes https://tracker.ceph.com/issues/68129
Signed-off-by: Afreen Misbah <afreen23.git@gmail.com>
[Screencast from 2024-09-18 18-27-06.webm](https://github.com/user-attachments/assets/652ce122-010e-4eca-997e-d530546d54ea)
<details>
- …
> mgr/dashboard: Add group selector in subsystems views

- src/common/options/global.yaml.in
No scrub messages should have a higher priority than client op messages. The default value should therefore be below osd_client_op_priority, which is 63.
But as a followup PR would eliminate the special queue priority for 'requested' scrub messages, the default value is set to equal osd_scrub_priority.
Fixes: https://tracker.ceph.com/issues/68072
Note: in 'main', this change is to be superseded by https://github.com/ceph/ceph/pull/59641.
#59793 was created (and will be merged) as a path for backporting only this part of change to
squid & reef.
> osd/scrub: reduce osd_requested_scrub_priority default value

- src/pybind/mgr/dashboard/ci/cephadm/bootstrap-cluster.sh
Update test environment image to squid
Recent errors shown due to image/code disparity:
Previous test failures: https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12492/consoleFull#2998473994b0cfa0c-a892-49e0-a359-82544e1a192e
Main image being used for squid testing:
```
Sep 19 05:54:42 ceph-node-00 cloud-init[840]: Internal network (--cluster-network) has not been provided, OSD replication will default to the public_network
Sep 19 05:54:42 ceph-node-00 cloud-init[840]: Pulling container image quay.ceph.io/ceph-ci/ceph:main...
Sep 19 05:55:50 ceph-node-00 cloud-init[840]: Ceph version: ceph version 19.3.0-5022-gc37a00af (c37a00af2113d089d40b9d6df347fcb940efa41a) squid (dev)
```
So main only code failing the build:
```
Sep 19 05:57:19 ceph-node-00 cloud-init[840]: /usr/bin/ceph: …
```
> squid: mgr/dashboard: custom image for kcli bootstrap script 

- doc/cephadm/install.rst
- src/cephadm/cephadmlib/templates/ceph.service.j2
- src/cephadm/cephadmlib/templates/init_ctr.service.j2
- src/cephadm/cephadmlib/templates/sidecar.service.j2
- src/cephadm/tests/test_unit_file.py
Currently with Docker Live Restore [1] enabled and while restarting Docker Engine - all Ceph container images will get restarted, while the feature allows restarting docker.service without containers downtime.
This is due to Requires=docker.service in systemd units templates, which mandates that on docker.service restart - the ceph container systemd units will be restarted as well.
Leaving After= entries, because they should allow systemd to correctly order the startup (first docker, then ceph containers).
[1]: https://docs.docker.com/engine/daemon/live-restore/
Fixes: https://tracker.ceph.com/issues/68028 …
> cephadm: Support Docker Live Restore

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.po.ts
- src/pybind/mgr/dashboard/services/rgw_client.py
added period update for zonegroup level changes so as to sync them
Fixes: https://tracker.ceph.com/issues/68049
https://github.com/user-attachments/assets/1dd9a28d-fda0-4c12-96c7-a974d778dd86
Video Description: After creating sync policy in first cluster (with zone1-zg-1realm1 set as default), it is propogating changes to the second cluster (with zone3-zg1-realm1 as default), it means the policy is synced across zones.
**NOTE**:  This PR is being worked upon commits from another [PR](https://github.com/ceph/ceph/pull/59061), please review only the latest commit which belongs to the current PR.
- If you …
> mgr/dashboard: zonegroup level policy created at master zone did not sync to non-master zone

- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/constants/cephfs.constant.ts
Fixes: https://tracker.ceph.com/issues/67400
https://tracker.ceph.com/issues/68105
Signed-off-by: Dnyaneshwari talwekar <dtalweka@redhat.com>
Tracker: https://bugzilla.redhat.com/show_bug.cgi?id=2303196
https://bugzilla.redhat.com/show_bug.cgi?id=2269104
https://bugzilla.redhat.com/show_bug.cgi?id=2302756
Steps: 
1.Navigate to Dashboard -> File -> NFS
2.Create NFS
3.On Create NFS page we can see "CephFS Path" as non-editable and Pseudo as blank field.
Updated Requirement:-
1. On Create NFS SubVolume selection should be required if SubVolume group is "_nogroup".
2. CephFS path should never be single "/" …
> mgr/dashboard: NFS Export form fixes

- src/tools/cephfs/top/cephfs-top
* Fixes `exception: curses function returned NULL` when the window width is larger than expected.
Reproduced this issue on a 32 inch horizontal monitor. Tested the fix on 32 inch horizontal + 24 inch vertical monitor(s) (dual).
* Fixes `exception: addwstr() returned ERR`  when the window width is smaller than expected.
Fixes: https://tracker.ceph.com/issues/67859 …
> cephfs-top: fix exceptions on small/large sized windows

- doc/index.rst
Currently the "Getting Started" link points at the install page, not the "Intro to Ceph" section, which seems more appropriate.
If you're happy with this, can it get backported to the still-supported releases, please?
<details>
- …
> Doc: Update "Getting Started" to link to start not install

- doc/index.rst
Currently the "Getting Started" link points at the install page, not the "Intro to Ceph" section, which seems more appropriate.
If you're happy with this, can it get backported to the still-supported releases, please?
(cherry picked from commit d257eacb05a463c93872ae8aa8210806affda4ec) …
> quincy: doc: Update "Getting Started" to link to start not install

- doc/index.rst
Currently the "Getting Started" link points at the install page, not the "Intro to Ceph" section, which seems more appropriate.
If you're happy with this, can it get backported to the still-supported releases, please?
(cherry picked from commit d257eacb05a463c93872ae8aa8210806affda4ec) …
> squid: doc: Update "Getting Started" to link to start not install

- src/common/options/global.yaml.in
- src/osd/scrubber/pg_scrubber.cc
Prior to this fix, scrub-related messages were queued with one of four priorities:
- if part of a regular, periodic scrub, the messages were queued with a very low priority (osd_scrub_priority. Default: 5), unless:
- if the pool configuration specified a higher priority for the scrub, the messages were queued with that priority (the SCRUB_PRIORITY pool configuration option);
- if a client operation was waiting for the scrub to complete, the messages were queued with the higher priority of the client ops (osd_client_op_priority. Default: 63); 
- and if the scrub was a high-priority one, e.g. initiated by the operator, the messages were queued with the highest priority (osd_requested_scrub_priority. Default: 120).
That last priority is too high, as scrubs should not have precedence over …
> osd/scrub: disable high work-queue priority for high-prio scrubs

- src/common/options/osd.yaml.in
- src/osd/scrubber/pg_scrubber.cc
- src/osd/scrubber/scrub_job.cc
- src/osd/scrubber/scrub_job.h
The interaction between the various configuration parameters controlling the scheduling of deep scrubs is not clearly defined nor clearly documented.
The existing set of parameters creates unnecessary code complexity, is surprising to the operators, and does not provide the level of control desired by Ceph users.
This is a proposed change to the deep scrub interval randomization:
Pre this PR, deep scrubs scheduling is controlled by the following set of parameters:
The desired interval between deep scrubs is determined by 'osd_deep_scrub_interval'. To prevent a "thundering herd" problem if multiple PGs were created at the same time, a randomization effect was added: any shallow scrub may (with a configurable frequency) be "upgraded" to a deep scrub.
As mentioned above, the interaction …
> osd/scrub: modify deep scrub interval randomization

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.po.ts
- src/pybind/mgr/dashboard/services/rgw_client.py
backport tracker: https://tracker.ceph.com/issues/68164
backport of: #59763 
parent tracker: https://tracker.ceph.com/issues/68049
<hr style="2px solid #eeeeee" />
added period update for zonegroup level changes so as to sync them
Fixes: https://tracker.ceph.com/issues/68049
(cherry picked from commit 52278f169fe94136c474a1758d4d0048e65edb50)
Tested on local - 
https://github.com/user-attachments/assets/b1f7f127-e9df-48eb-860a-7bac3335d741 …
> Squid: mgr/dashboard: zonegroup level policy created at master zone did not sync to non-master zone

- src/include/rbd/librbd.h
- src/include/rbd/librbd.hpp
- src/librbd/api/Group.cc
- src/librbd/librbd.cc
- src/pybind/rbd/c_rbd.pxd
- src/pybind/rbd/mock_rbd.pxi
- src/pybind/rbd/rbd.pyx
- src/test/librbd/test_Groups.cc
- src/test/pybind/test_rbd.py
Commit e5ccce14c4b0 ("rbd: add group snap info command") added a commented out field in rbd_group_snap_info2_t struct but didn't define the corresponding enum, expecting it to be brought in with the patchset that introduces mirror group snapshots.  That work is still in progress, but there is already interest in the new command and APIs that use rbd_group_snap_info2_t struct and even a backport request.
Finalize the struct definition to avoid a breaking change for those users in the future.  RBD_GROUP_SNAP_NAMESPACE_TYPE_USER can be treated as dummy in terms of meaning until RBD_GROUP_SNAP_NAMESPACE_TYPE_MIRROR is added.
- If you are submitting a …
> librbd: introduce rbd_group_snap_namespace_type_t enum

- qa/suites/orch/cephadm/workunits/task/test_iscsi_container/test_iscsi_container.yaml
- qa/workunits/cephadm/test_iscsi_setup.sh
This extends the basic cephadm iscsi deployment test to do some very basic gw and client setup. The iscsi service setup is likely to be altered with the future addition of sidecar containers in cephadm, so the
hope is this will provide a bit more coverage …
> qa/cephadm: extend iscsi teuth test

- src/common/options/osd.yaml.in
The previous default of 25 objects per chunk proved to take too long (many hundreds of milliseconds) on a busy cluster. As the scrubber locks all objects in the chunk for the duration, a large chunk size can cause a significant impact on the client ops' latencies.
Backport of https://github.com/ceph/ceph/pull/59636
Original tracker: https://tracker.ceph.com/issues/68057
Backport tracker: https://tracker.ceph.com/issues/68070
(cherry picked from commit 8c2ed94e9cbc7b1ed84b034a65b126e16b18a596)
> reef: osd/scrub: decrease default deep scrub chunk size

- src/common/options/osd.yaml.in
The previous default of 25 objects per chunk proved to take too long (many hundreds of milliseconds) on a busy cluster. As the scrubber locks all objects in the chunk for the duration, a large chunk size can cause a significant impact on the client ops' latencies.
Backport of [PR#59636](https://github.com/ceph/ceph/pull/59636)
Original tracker: https://tracker.ceph.com/issues/68057
Backport tracker: https://tracker.ceph.com/issues/68069
(cherry picked from commit 8c2ed94e9cbc7b1ed84b034a65b126e16b18a596)
> squid: osd/scrub: decrease default deep scrub chunk size

- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-snapshots-list/cephfs-subvolume-snapshots-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/constants/cephfs.ts
Fixes: https://tracker.ceph.com/issues/67891
Signed-off-by: Dnyaneshwari talwekar <dtalweka@redhat.com>
Tracker: https://tracker.ceph.com/issues/67891 …
> mgr/dashboard: Cloning subvolume not listing _nogroup if no subvolume

- src/pybind/mgr/dashboard/ci/cephadm/bootstrap-cluster.sh
- src/pybind/mgr/dashboard/ci/cephadm/run-cephadm-e2e-tests.sh
- src/pybind/mgr/dashboard/ci/cephadm/start-cluster.sh
the tests seems waiting to fetch the prometheus details incase the cephadm ran into error and it just waits there for more than an hour without any progress. fixing that and some minor improvements.
an example log: https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12287/consoleFull …
> mgr/dashboard: fix indefinite loop in cephadm dashboard e2e

- src/test/crimson/test_messenger_thrash.cc
test_messenger_thrash UT shows,
```
==461141==ERROR: AddressSanitizer: stack-use-after-return on address 0xffffb0b37c20 at pc 0xaaaad7239508 bp 0xffffeb113c50 sp 0xffffeb113c48
READ of size 4 at 0xffffb0b37c20 thread T0
#0 0xaaaad7239504 in (anonymous namespace)::SyntheticWorkload::wait_for_done()::'lambda0'()::operator()() const /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/src/test/crimson/test_messenger_thrash.cc:455:13
https://github.com/ceph/ceph/pull/1 0xaaaad723a1c0 in seastar::internal::do_until_state<(anonymous namespace)::SyntheticWorkload::wait_for_done()::'lambda'(), (anonymous namespace)::SyntheticWorkload::wait_for_done()::'lambda0'()>::run_and_dispose() /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/src/seastar/include/seastar/core/loop.hh:303:26 …
```
> test/crimson/test_messenger_thrash: fix a local variable scope issue

- src/crimson/os/seastore/random_block_manager.h
- src/crimson/os/seastore/random_block_manager/block_rb_manager.cc
- src/crimson/os/seastore/random_block_manager/block_rb_manager.h
- src/crimson/os/seastore/random_block_manager/nvme_block_device.cc
- src/crimson/os/seastore/random_block_manager/nvme_block_device.h
- src/crimson/os/seastore/random_block_manager/rbm_device.cc
- src/crimson/os/seastore/random_block_manager/rbm_device.h
- src/test/crimson/seastore/test_randomblock_manager.cc
This PR eliminates unnecessary memory copy during the ool write in rbm.write() …
> crimson/os/seastore: remove unnecessary memory copy during ool write

- src/pybind/mgr/cephadm/serve.py
During Import zone endpoint automatically fetches hostname instead of ip resulting in sync error. This PR is to fix this issue
Fixes: https://tracker.ceph.com/issues/68027 …
> mgr/cephadm: use host address while updating rgw zone endpoints

- ceph.spec.in
Fix the following warning while building source rpm with `rpmbuild`:
> warning: line 1187: It's not recommended to have unversioned Obsoletes: Obsoletes: ceph-libcephfs
> ceph.spec.in: Fix unversioned Obsoletes: rpmbuild warning

- doc/cephfs/fs-volumes.rst
- src/pybind/mgr/mgr_util.py
- src/pybind/mgr/smb/handler.py
- src/pybind/mgr/smb/module.py
- src/pybind/mgr/smb/proto.py
- src/pybind/mgr/smb/tests/test_handler.py
- src/pybind/mgr/smb/tests/test_smb.py
- src/pybind/mgr/tests/test_mgr_util.py
- src/pybind/mgr/volumes/fs/operations/versions/subvolume_base.py
- src/pybind/mgr/volumes/fs/volume.py
- src/python-common/ceph/fs/earmarking.py
- src/python-common/ceph/tests/test_earmarking.py
Depends on https://github.com/ceph/ceph/pull/59111/
- Inter module level scope handling: 
```
[ceph: root@ceph-node-00 /]# ceph smb share create  cls1 shr7 fs1  / --subvolume sv1
{
"resource": {
"resource_type": "ceph.smb.share",
"cluster_id": "cls1",
"share_id": "shr7",
"intent": "present",
"name": "shr7",
"readonly": false,
"browseable": true,
"cephfs": {
"volume": "fs1",
"path": "/",
"subvolume": "sv1",
"provider": "samba-vfs"
}
},
"msg": "earmark has already been set by nfs",
"success": false
}
Error EAGAIN: resource failed to apply (see response data for details)
```
- Intra module level scope handling: 
```
[ceph: root@ceph-node-00 /]# ceph smb share create  cls2 shr6 fs1  / --subvolume sv1
{
"resource": {
"resource_type": "ceph.smb.share",
"cluster_id": "cls2",
"share_id": "shr6", …
```
> mgr/smb: earmark resolver for subvolume

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-flow-modal/rgw-multisite-sync-flow-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.ts
- src/pybind/mgr/dashboard/services/rgw_client.py
https://tracker.ceph.com/issues/68097
https://github.com/user-attachments/assets/dffe18a3-5704-4542-b33c-015094e899c7
**Changes made in this PR:**
1. destination zone selection does not show any zones to select from, user need to type and select zones, this issue seen in both directional flow creation and pipe creation
`For this issue we are populating the destination zones select option with a set of options to choose from`
2. In pipe creation if user want to select all zones for source and destination zones provide filter option *
`For this issue we have added another All Zones (*) option while creating/editing a pipe `
3. one of the table column name is not listing under column selection filter under object->multisite->sync policy section …
> mgr/dashboard: multisite sync policy improvements 

- doc/man/8/ceph-bluestore-tool.rst
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/os/bluestore/bluestore_tool.cc
This PR consists of:
ZAP:
https://github.com/ceph/ceph/pull/59632
show-label:
https://github.com/ceph/ceph/pull/59714
really-really-mean-it:
https://github.com/ceph/ceph/pull/59627
+
-zap-size param is removed
+
documentation added
Fixes:
https://tracker.ceph.com/issues/68048 …
> ceph-bluestore-tool: Fixes for multilple bdev label

- qa/standalone/scrub/osd-scrub-test.sh
To prevent test timeouts.
Also - remove a failing assertion on a specific 'pg query' output, as it is not central to the test.
Fixes: https://tracker.ceph.com/issues/61385
Fixes: https://tracker.ceph.com/issues/64346
> qa/standalone/scrub: increase status updates frequency

- PendingReleaseNotes
- doc/rados/configuration/mclock-config-ref.rst
- doc/rados/configuration/osd-config-ref.rst
- doc/rados/troubleshooting/troubleshooting-osd.rst
- src/common/options/osd.yaml.in
Based on tests performed at scale on a HDD based cluster, it was found that scheduling with mClock was not optimal with multiple OSD shards. For e.g., in the scaled cluster with multiple OSD node failures, the client throughput was found to be inconsistent across test runs coupled with multiple reported slow requests.
However, the same test with a single OSD shard and with multiple worker threads yielded significantly better results in terms of consistency of client and recovery throughput across multiple test runs.
For more details see https://tracker.ceph.com/issues/66289.
Therefore, as an interim measure until the issue with multiple OSD shards (or multiple mClock queues per OSD) is investigated and fixed, the following change to the default HDD OSD shard configuration is made:
- …
> common/options: Change HDD OSD shard configuration defaults for mClock

- src/pybind/mgr/dashboard/frontend/src/app/shared/api/prometheus.service.ts
backport tracker: https://tracker.ceph.com/issues/68207
---
backport of https://github.com/ceph/ceph/pull/59891
parent tracker: https://tracker.ceph.com/issues/68162
> squid: mgr/dashboard: fix handling NaN values in dashboard charts 

- src/os/bluestore/BlueStore.cc
Move reservation of bdev label to proper place.
Reservation (alloc->init_rm_free) was after reopening DB in r/w mode. This was a problem - as soon as DB is in r/w it can flush sst or compact, which will make allocations.
Fixes: https://tracker.ceph.com/issues/67911 …
> os/bluestore: Fix BlueFS allocating bdev label reserved location.

- src/pybind/mgr/dashboard/services/rgw_client.py
backport tracker: https://tracker.ceph.com/issues/68209
---
backport of https://github.com/ceph/ceph/pull/59890
parent tracker: https://tracker.ceph.com/issues/68161
> squid: mgr/dashboard: update period after migrating to multi-site 

- src/pybind/mgr/dashboard/services/rgw_client.py
On editing a zone if compression type is an empty string, it causes Unrecognized compression type error
Fixes: https://tracker.ceph.com/issues/68176 …
> mgr/dashboard: fix setting compression type while editing rgw zone

- src/pybind/mgr/tox.ini
Prior to this patch if you ran `tox` in src/pybind/mgr it would include a test that runs the units tests using python 3.7. These no longer pass and there is no longer any reason to support python 3.7 on main. …
> pybind/mgr: drop py37 test from  tox.ini

- src/include/rbd/librbd.h
Make it easier to test if rbd_group_snap_get_info() and by extension also rbd_group_snap_list2() APIs are available at compile time.  This wasn't done in commit e5ccce14c4b0 ("rbd: add group snap info command") because backporting wasn't intended. …
> librbd: add LIBRBD_SUPPORTS_GROUP_SNAP_GET_INFO define

- src/mds/CDentry.cc
next_snap is missing from the logs to make sense of the corruption
Fixes: https://tracker.ceph.com/issues/67770 …
> mds: dump next_snap when checking dentry corruption

- qa/cephfs/conf/mgr.yaml
- qa/cephfs/conf/mon.yaml
- qa/tasks/ceph.py
- qa/tasks/cephadm.py
The mgr emits this health check instead of the mons.
Fixes: https://tracker.ceph.com/issues/67737 …
> qa: correct daemon for warning conf 

- src/client/Client.cc
Based on the man page of readdir(3), the d_reclen field should contain the total size of the record, which varies depending on the length of the returned name. However, the previous implementation was returning a hardcoded '1' in all cases.
This patch computes the right size of the record and returns it.
Fixes: https://tracker.ceph.com/issues/65389 …
> client: fix d_reclen for readdir

- src/pybind/mgr/dashboard/services/rgw_client.py
backport tracker: https://tracker.ceph.com/issues/68226
---
backport of https://github.com/ceph/ceph/pull/59918
parent tracker: https://tracker.ceph.com/issues/68176
> squid: mgr/dashboard: fix setting compression type while editing rgw zone 

- src/ceph-volume/ceph_volume/tests/conftest.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_batch.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_listing.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_migrate.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_zap.py
- src/ceph-volume/ceph_volume/tests/devices/raw/test_list.py
- src/ceph-volume/ceph_volume/tests/devices/raw/test_prepare.py
- src/ceph-volume/ceph_volume/tests/devices/simple/test_activate.py
- src/ceph-volume/ceph_volume/tests/util/test_arg_validators.py
- src/ceph-volume/ceph_volume/tests/util/test_disk.py
- src/ceph-volume/ceph_volume/tests/util/test_encryption.py
- src/ceph-volume/ceph_volume/util/arg_validators.py
This fixes unit tests errors in ceph-volume.
This commit squashes :
c68fbf01c33 ceph-volume: tests shouldn't require lvm2 to pass
9390592c343 ceph-volume: fix TestMigrate tests
> ceph-volume: fix unit tests errors

- doc/jaegertracing/index.rst
Fixed a typo in the jaeger traces documentation.
(cherry picked from commit 5a11bc00e6c068c965bb7d961feeb47353cc893c) …
> squid: doc: fix typo

- doc/jaegertracing/index.rst
Fixed a typo in the jaeger traces documentation.
(cherry picked from commit 5a11bc00e6c068c965bb7d961feeb47353cc893c) …
> reef: doc: fix typo

- doc/jaegertracing/index.rst
Fixed a typo in the jaeger traces documentation.
(cherry picked from commit 5a11bc00e6c068c965bb7d961feeb47353cc893c) …
> quincy: doc: fix typo

- src/rgw/driver/rados/rgw_rados.cc
no changes to the bucket index should be allowed while resharding. these rados ops are fire-and-forget, so we want to fail them until reshard completes. the next listing after that should resend the suggestions
<details>
</details>
> rgw/rados: guard against dir suggest during reshard

- qa/suites/rados/singleton/all/mon-connection-score.yaml
- qa/tasks/ceph_test_case.py
- qa/tasks/mon_connection_score.py
- src/mon/ConnectionTracker.cc
**Problem:**
Currently, the ConnectionTracker::dump()
will dump a duplicate key which is not
ideal when you want to write a test that
converts the dump into a JSON since
each key must be unique. Basically without resolving this,
you cannot do something like:
json.load(connection_score) because the dump is not a valid JSON format
e.g.,
`ceph daemon mon.a connection scores dump`
`peer` is a duplicate key.
```
"peer_scores": {
"peer": {
"peer_rank": 0,
"peer_score": 0.99966364610282044,
"peer_alive": true
},
"peer": {
"peer_rank": 2,
"peer_score": 0.9941396935402752,
"peer_alive": false
}
}
```
`report` is a duplicate key
```
"report": {
"rank": 0,
"epoch": 6,
"version": 3940,
"peer_scores": {...}
},
"report": {
"rank": 1,
"epoch": 6,
"version": 345,
"peer_scores": {...}
},
"report": { …
```
> src/mon/ConnectionTracker.cc: Fix dump function

- src/cls/rgw/cls_rgw_types.h
- src/rgw/driver/rados/rgw_gc.cc
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/rgw_admin.cc
- src/test/cls_rgw/test_cls_rgw.cc
use concurrent deletes to speed up inline garbage collection
Fixes: https://tracker.ceph.com/issues/68134
<details>
</details>
> rgw/rados: RGWRados::delete_objs_inline() uses AioThrottle

- src/rgw/rgw_lc.cc
backport tracker: https://tracker.ceph.com/issues/57417
---
backport of https://github.com/ceph/ceph/pull/44589
parent tracker: https://tracker.ceph.com/issues/53878
> quincy: rgw: Get canonical storage class when storage class is empty in

- src/pybind/mgr/nfs/export.py
- src/pybind/mgr/nfs/module.py
- src/python-common/ceph/fs/earmarking.py
Depends on https://github.com/ceph/ceph/pull/54277. https://github.com/ceph/ceph/pull/59111, https://github.com/ceph/ceph/pull/59387
- Inter module level scope handling for `nfs export create cephfs` :
```
[ceph: root@ceph-node-00 /]# ceph nfs export create cephfs foo /ex1  fs1 /volumes/_nogroup/sv1/df544de8-9437-46ea-a1e3-9fb500b77663
Error EAGAIN: earmark has already been set by smb
```
- Inter module level scope handling for `nfs export apply` :
```
[ceph: root@ceph-node-00 /]# ceph nfs export apply foo -i ex2 
[
{
"msg": "Failed to apply export: earmark has already been set by smb",
"pseudo": "/ex2",
"state": "error"
}
]
```
- If you are …
> mgr/nfs: earmark resolver for subvolume

- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/services/svc_bi_rados.cc
- src/rgw/services/svc_bilog_rados.cc
bucket index operations that need to visit every index shard object use this CLSRGWConcurrentIO class to issue several requests in parallel, then wait on a condition variable for completions. this wait causes asio threads to block, so add warnings to all call sites
<details>
</details>
> cls/rgw: warn about CLSRGWConcurrentIO use in asio threads

- src/ceph-node-proxy/ceph_node_proxy/baseredfishsystem.py
backport tracker: https://tracker.ceph.com/issues/68277
---
backport of https://github.com/ceph/ceph/pull/59981
parent tracker: https://tracker.ceph.com/issues/68231
> squid: node-proxy: fix a regression when processing the RedFish API

- src/common/options/rgw.yaml.in
- src/rgw/rgw_asio_frontend.cc
Configurably (off by default) wait for up to `rgw_exit_timeout_secs` for all outstanding requests
to complete before exiting the RGW process unconditionally.
(new HTTP requests will not be accepted during this time.)
Fixes: https://tracker.ceph.com/issues/66205 …
> rgw: delay the RGW process exit until all actice requests have completed

- .gitmodules
shallow=true seems to prevent the checkout from actually finding the correct sha1.
Fixes: https://tracker.ceph.com/issues/67640
<details>
</details>
> .gitmodules: remove shallow=true config from nvmeof/gateway

- doc/releases/reef.rst
The only place that I've been able to find release dates are on https://ceph.io/en/news/blog/category/release/. Including the release date in the release notes would be a welcome reduction in clicking and searching to find this information. 
This PR adds a subsection to reef.rst that contains the release dates as shown on the blog posts. If there's a different way to include the release date in the release notes, that's fine with me. My main ask to consolidate that information into the release notes.
Thanks!
Signed-off-on-by: Joel Davidow <jdavidow@nso.edu> …
> reef: doc: Adds release date.

- run-make-check.sh
Makes it possible to run make check in container.
backport
Signed-off-by: John Mulligan <jmulligan@redhat.com>
(cherry picked from commit 7edc4309f4781362f86fd83fd2d53eba42e5f73f)
Conflicts:
run-make-check.sh …
> reef: run-make-check: use get_processors in run-make-check script

- run-make-check.sh
Makes it possible to run make check in container.
backport
Signed-off-by: John Mulligan <jmulligan@redhat.com>
(cherry picked from commit 7edc4309f4781362f86fd83fd2d53eba42e5f73f)
Conflicts:
run-make-check.sh …
> quincy: run-make-check: use get_processors in run-make-check script

- doc/rados/troubleshooting/troubleshooting-pg.rst
Make grammar improvements (and correct a verb disagreement) in the section "Placement Groups Never Get Clean" in
doc/rados/troubleshooting/troubleshooting-pg.rst. …
> doc/rados: edit "Placement Groups Never Get Clean"

- src/include/cephfs/metrics/Types.h
- src/include/cephfs/types.h
- src/mds/Capability.cc
- src/mds/Capability.h
- src/mds/FSMap.cc
- src/mds/FSMap.h
- src/mds/PurgeQueue.cc
- src/mds/PurgeQueue.h
- src/mds/SessionMap.h
- src/mds/SimpleLock.cc
- src/mds/SimpleLock.h
- src/mds/flock.cc
- src/mds/flock.h
- src/mds/mdstypes.cc
- src/mds/mdstypes.h
- src/messages/MMDSBeacon.h
- src/mgr/DaemonHealthMetric.h
- src/mgr/MDSPerfMetricTypes.h
- src/mgr/MetricTypes.h
- src/mgr/OSDPerfMetricTypes.h
- src/tools/ceph-dencoder/mds_types.h
…code-decode comparison
Currently, ceph-dencoder lacks certain mds types, preventing us from accurately checking the ceph corpus for encode-decode mismatches. This pull request aims to address this issue by adding the missing types to ceph-dencoder.
To successfully incorporate these types into ceph-dencoder, we need to introduce the necessary `dump` and `generate_test_instances` functions that was missing in some types. These functions are essential for proper encode and decode of the added types.
This PR will enhance the functionality of ceph-dencoder by including the missing types, enabling a comprehensive analysis of encode-decode consistency. With the addition of these types, we can ensure the robustness and correctness of the ceph corpus.
This update will significantly contribute to …
> ceph-dencoder: MDS - Add missing types

- src/pybind/mgr/dashboard/frontend/cypress/e2e/ui/login.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/identity/identity.component.html
backport tracker: https://tracker.ceph.com/issues/67200
---
backport of https://github.com/ceph/ceph/pull/58844
parent tracker: https://tracker.ceph.com/issues/67075
> squid: mgr/dashboard: Changes for Sign out text to Login out

- src/ceph-volume/ceph_volume/util/disk.py
This corrects some error in disk.py:
- get_partitions has an incorrect typing
+ adding docstring for this function.
- get_lvm_mapper_path_from_dm docstring is wrong
> ceph-volume: docstring and typing corrections

- doc/radosgw/config-ref.rst
- src/common/options/rgw.yaml.in
- src/rgw/driver/rados/rgw_datalog.h
The evaluation based on rgw_data_log_obj_prefix had a logical error not considering the value and always was returning "data_log". As the config had the dev level and apparently it was useless and fixing the logic could break the existing clusters (if they don't adopt before the upgrade), it was decided to remove the config.
Fixes: https://tracker.ceph.com/issues/67861
> rgw: remove rgw_data_log_obj_prefix

- src/pybind/mgr/dashboard/frontend/cypress/e2e/ui/login.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/identity/identity.component.html
backport tracker: https://tracker.ceph.com/issues/67201
---
backport of https://github.com/ceph/ceph/pull/58844
parent tracker: https://tracker.ceph.com/issues/67075
> reef: mgr/dashboard: Changes for Sign out text to Login out

- src/crimson/osd/osd_operations/client_request_common.cc
- src/crimson/osd/osd_operations/client_request_common.h
- src/crimson/osd/osd_operations/internal_client_request.cc
Fixes: https://tracker.ceph.com/issues/68068
<details>
</details>
> crimson: don't retain InternalClientRequest on interval change even if primary does not change

- src/librados/librados_asio.h
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
- src/rgw/driver/rados/rgw_tools.cc
- src/rgw/driver/rados/rgw_tools.h
- src/rgw/rgw_aio.cc
- src/rgw/services/svc_sys_obj_core.cc
- src/test/librados/asio.cc
rgw uses `IoCtx::get_last_version()` in a few places to determine the order of racing operations. most importantly, the rgw bucket index relies on this version number to detect racing writes/deletes so it can cancel the operations that lose the race
but the value of `get_last_version()` is only updated by synchronous calls to `IoCtx::operate()`. after switching to `rgw_rados_operate()` for these operations so that coroutines could suspend instead of block, `get_last_version()` is returning 0 because we're using `IoCtx::aio_operate()` under the hood
in the coroutine case, `rgw_rados_operate()` uses `librados::async_operate()` from librados_asio.h. these librados_asio.h functions now get the version number out of `AioCompletion` and return it to the caller
`rgw_rados_operate()` now receives …
> rgw/rados: don't rely on IoCtx::get_last_version() for async ops

- src/common/TrackedOp.cc
- src/common/TrackedOp.h
It's already the case that `osd_op_history_slow_op_threshold` as well as the computed op duration are floating-point, but we were losing this precision within OpHistory.
Fixes: https://tracker.ceph.com/issues/62169
> TrackedOp: Make history_slow_op_threshold a float

- src/common/TrackedOp.h
- src/osd/OpRequest.cc
backport tracker: https://tracker.ceph.com/issues/61396
---
backport of https://github.com/ceph/ceph/pull/51668
parent tracker: https://tracker.ceph.com/issues/61388
> quincy: osd/TrackedOp: Fix TrackedOp event order

- src/common/options/global.yaml.in
No scrub messages should have a higher priority than client op messages. The default value should therefore be below osd_client_op_priority, which is 63.
But as a followup PR would eliminate the special queue priority for 'requested' scrub messages, the default value is set to equal osd_scrub_priority.
Backport of https://github.com/ceph/ceph/pull/59793
Original tracker: https://tracker.ceph.com/issues/68072
Backport tracker: https://tracker.ceph.com/issues/68155
Signed-off-by: Ronen Friedman [rfriedma@redhat.com](mailto:rfriedma@redhat.com)
(cherry picked from commit b98a46582e5e21de13e51017ea35dabdc19db71d)
> reef: osd/scrub: reduce osd_requested_scrub_priority default value

- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-gateway/nvmeof-gateway.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.ts
- src/pybind/mgr/dashboard/services/nvmeof_client.py
This PR intorduces two commits handling two separate issues:
[mgr/dashboard: Allow adding all listeners unders a subsystems](https://github.com/ceph/ceph/commit/d89dc859c779f3114c3d20fab71e44d2a8a72d32) 
Issue:
- Currently a user cannot add all listeners under a subsystem, only one gateway node can be added as listener.
- This results into an error: `Failure adding nqn.2001-07.com.ceph:1725013182540 listener at 10.70.44.140:4420: Gateway's host name must match current host (dhcp47-54)`
Reason:
- The gateway address used while creating listener is random now in nvmeof client
- After checking the gateway logs of each node, its is found that no grpc request recieved for adding listener on the respective node rather going to the node that is chosen by default in nvmeof client.
- But nvmeof …
> mgr/dashboard: Fix adding listener and null issue for groups 

- src/osd/OSD.cc
class:device-class config database mask does not work for osd_compact_on_start for wrong boot sequence of osd. In the `OSD::init` function compaction is called before authentication of monClient. Store compaction now is moved after authentication of monClient.
Fixes: https://tracker.ceph.com/issues/65228 …
> osd: class:device-class config database mask does not work for osd_compact_on_start

- PendingReleaseNotes
- doc/mgr/restful.rst
- src/pybind/mgr/restful/module.py
backport tracker: https://tracker.ceph.com/issues/67643
---
backport of https://github.com/ceph/ceph/pull/54984
parent tracker: https://tracker.ceph.com/issues/67642
> quincy: mgr/rest: Trim  requests array and limit size

- PendingReleaseNotes
- qa/standalone/ceph-helpers.sh
- qa/standalone/mon/mon-cluster-log.sh
- src/common/options/mon.yaml.in
- src/mon/LogMonitor.cc
- src/mon/LogMonitor.h
backport tracker: https://tracker.ceph.com/issues/65944
---
backport of https://github.com/ceph/ceph/pull/47502
parent tracker: https://tracker.ceph.com/issues/57061
> reef: mon/LogMonitor: Use generic cluster log level config

- src/test/osd/TestOSDMap.cc
backport tracker: https://tracker.ceph.com/issues/67236
---
backport of https://github.com/ceph/ceph/pull/58406
parent tracker: https://tracker.ceph.com/issues/42884
> quincy: test: Create ParallelPGMapper object before start threadpool

- ceph.spec.in
backport tracker: https://tracker.ceph.com/issues/68349
---
backport of https://github.com/ceph/ceph/pull/59640
parent tracker: https://tracker.ceph.com/issues/67938
> quincy: ceph.spec.in: we need jsonnet for all distroes for make check

- src/osd/PrimaryLogPG.cc
- src/osd/Watch.cc
backport tracker: https://tracker.ceph.com/issues/67165
---
backport of https://github.com/ceph/ceph/pull/50861
parent tracker: https://tracker.ceph.com/issues/58120
> quincy: osd: avoid watcher remains after "rados watch" is interrupted

- qa/suites/rgw/multifs/0-install.yaml
- qa/suites/rgw/multifs/tasks/rgw_bucket_quota.yaml
- qa/suites/rgw/multifs/tasks/rgw_multipart_upload.yaml
- qa/suites/rgw/multifs/tasks/rgw_ragweed.yaml
- qa/suites/rgw/multifs/tasks/rgw_s3tests.yaml
- qa/suites/rgw/multifs/tasks/rgw_user_quota.yaml
- qa/workunits/rgw/s3_utilities.pm
uses the same strategy from rgw/verify in https://github.com/ceph/ceph/pull/22249 to reduce the number of jobs in rgw/multifs
rgw/multifs/tasks/ contains yaml files for 5 different test cases. instead treating each test case as a separate dimension of the teuthology job matrix, combine them together in a single job
now the only dimensions come from `rgw/multifs/rgw_pool_type/{ec-profile.yaml ec.yaml replicated.yaml}`. this reduces the number of jobs in the rgw/multifs subsuite from 15 to 3
<details>
- `jenkins …
> qa/rgw/multifs: add tasks/+ to concatenate tasks into same job

- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/services/nvmeof_client.py
backport tracker: https://tracker.ceph.com/issues/68357
---
backport of https://github.com/ceph/ceph/pull/59978
parent tracker: https://tracker.ceph.com/issues/68229
> squid: mgr/dashboard: Fix adding listener and null issue for groups 

- src/ceph-volume/ceph_volume/objectstore/lvmbluestore.py
- src/ceph-volume/ceph_volume/objectstore/rawbluestore.py
- src/ceph-volume/ceph_volume/tests/objectstore/test_lvmbluestore.py
- src/ceph-volume/ceph_volume/tests/util/test_disk.py
- src/ceph-volume/ceph_volume/tests/util/test_encryption.py
- src/ceph-volume/ceph_volume/util/disk.py
- src/ceph-volume/ceph_volume/util/encryption.py
backport tracker: https://tracker.ceph.com/issues/68192
---
backport of https://github.com/ceph/ceph/pull/59915
parent tracker: https://tracker.ceph.com/issues/68150
> squid: ceph-volume: fix OSD lvm/tpm2 activation

- src/pybind/mgr/orchestrator/module.py
backport tracker: https://tracker.ceph.com/issues/68080
---
backport of https://github.com/ceph/ceph/pull/59752
parent tracker: https://tracker.ceph.com/issues/68045
> squid: orch: refactor boolean handling in drive group spec

- src/ceph_osd.cc
- src/common/Preforker.h
clang-tidy generated use-after-move warning on `store` which is present in different if blocks. We exit in both of the blocks.
Fixed by adding the `[[noreturn]]` attribute to the `exit()` function. 
clang-tidy original warning:
```
/home/suyash/ceph/src/ceph_osd.cc:385:15: warning: 'store' used after it was moved [bugprone-use-after-move]
int err = store->mkjournal();
^
/home/suyash/ceph/src/ceph_osd.cc:367:41: note: move occurred here
int err = OSD::mkfs(g_ceph_context, std::move(store), g_conf().get_val<uuid_d>("fsid"),
^
```
Fixes: https://tracker.ceph.com/issues/66709 …
> ceph_osd: false use-after-move on store

- qa/suites/rbd/iscsi/0-single-container-host.yaml
- qa/suites/rbd/iscsi/base/install.yaml
- qa/suites/rbd/iscsi/container-hosts$
- qa/tasks/ceph_iscsi_client.py
- src/test/cli-integration/rbd/gwcli_create.t
- src/test/cli-integration/rbd/gwcli_delete.t
- src/test/cli-integration/rbd/iscsi_client.t
backport tracker: https://tracker.ceph.com/issues/68364
---
backport of https://github.com/ceph/ceph/pull/60005
parent tracker: https://tracker.ceph.com/issues/68213
> quincy: qa/suites/rbd/iscsi: enable all supported container hosts

- src/blk/kernel/KernelDevice.cc
- src/blk/kernel/KernelDevice.h
Using join() to wait discard thread end is more safe, it can ensure that resource releases are sequential, to avoid potential race conditions. …
> blk/KernelDevice: using join() to wait thread end is more safe

- cmake/modules/BuildISAL.cmake
- cmake/modules/BuildISALCrypto.cmake
- src/crypto/isa-l/CMakeLists.txt
- src/erasure-code/isa/CMakeLists.txt
instead of building isa-l source files directly into the `ec_isa` and `ceph_crypto_isal` plugins, use cmake ExternalProjects to build the libraries with their own makefiles, and expose the static libraries as cmake targets `ISAL::ISAL` and `ISAL::Crypto`
as pointed out in https://github.com/ceph/ceph/pull/59494, the current cmake scripts don't include any of the avx512 sources. after switching to ExternalProjects, i've confirmed that the resulting plugins do contain avx512 symbols:
> ~/ceph/build $ nm lib/libceph_crypto_isal.so | grep avx512 | wc -l
3
>
> ~/ceph/build $ nm lib/libec_isa.so | grep avx512 | wc -l
61
Fixes: https://tracker.ceph.com/issues/67943
<details>
- `jenkins …
> cmake: use ExternalProjects to build isa-l and isa-l_crypto libraries

- qa/suites/orch/cephadm/workunits/task/test_rgw_multisite.yaml
backport tracker: https://tracker.ceph.com/issues/66695
---
backport of https://github.com/ceph/ceph/pull/58126
parent tracker: https://tracker.ceph.com/issues/64872
> squid: suites: adding ignore list for stray daemon

- src/cls/cas/cls_cas_internal.h
backport tracker: https://tracker.ceph.com/issues/67572
---
backport of https://github.com/ceph/ceph/pull/56136
parent tracker: https://tracker.ceph.com/issues/64854
> reef: cls/cas/cls_cas_internal: Initialize 'hash' value before decoding

- src/osd/PrimaryLogPG.cc
backport tracker: https://tracker.ceph.com/issues/64575
---
backport of https://github.com/ceph/ceph/pull/55570
parent tracker: https://tracker.ceph.com/issues/64192
> reef: osd: always send returnvec-on-errors for client's retry

- qa/standalone/mon/osd-erasure-code-profile.sh
- qa/workunits/cephtool/test.sh
- qa/workunits/rados/test_rados_tool.sh
- src/mon/MonCommands.h
backport tracker: https://tracker.ceph.com/issues/66691
---
backport of https://github.com/ceph/ceph/pull/56531
parent tracker: https://tracker.ceph.com/issues/65183
> reef: mon, qa: suites override ec profiles with --yes_i_really_mean_it; monitors accept that

- src/mon/OSDMonitor.cc
backport tracker: https://tracker.ceph.com/issues/67159
---
backport of https://github.com/ceph/ceph/pull/57843
parent tracker: https://tracker.ceph.com/issues/66329
> reef: mon: validate also mons and osds on {rm-,}pg-upmap-primary

- qa/suites/rbd/iscsi/0-single-container-host.yaml
- qa/suites/rbd/iscsi/base/install.yaml
- qa/suites/rbd/iscsi/supported-container-hosts$
- qa/tasks/ceph_iscsi_client.py
- src/test/cli-integration/rbd/gwcli_create.t
- src/test/cli-integration/rbd/gwcli_delete.t
- src/test/cli-integration/rbd/iscsi_client.t
backport tracker: https://tracker.ceph.com/issues/68366
---
backport of https://github.com/ceph/ceph/pull/60005
parent tracker: https://tracker.ceph.com/issues/68213
> squid: qa/suites/rbd/iscsi: enable all supported container hosts

- ceph.spec.in
backport tracker: https://tracker.ceph.com/issues/68348
---
backport of https://github.com/ceph/ceph/pull/59640
parent tracker: https://tracker.ceph.com/issues/67938
> squid: ceph.spec.in: we need jsonnet for all distroes for make check

- ceph.spec.in
backport tracker: https://tracker.ceph.com/issues/68347
---
backport of https://github.com/ceph/ceph/pull/59640
parent tracker: https://tracker.ceph.com/issues/67938
> reef: ceph.spec.in: we need jsonnet for all distroes for make check

- qa/tasks/tox.py
noticed when debugging https://tracker.ceph.com/issues/67986 that our tox has been pinned to an old version. after unpinning, 4.18.1 appears to be the current version from pip
<details>
</details>
> qa/tasks/tox: unpin tox version

- src/rgw/rgw_auth_s3.cc
- src/rgw/rgw_auth_s3.h
- src/rgw/rgw_rest_client.cc
- src/rgw/rgw_rest_s3.cc
If we get a HTTP OPTIONS request for a presigned URL that contains credentials we need to compute the signature using the method given in the access-control-request-method http header.
This is the same as performed for v4 auth in [1].
[1] https://github.com/ceph/ceph/pull/52673 …
> rgw: handle http options CORS with v2 auth

- src/rgw/driver/rados/rgw_rados.cc
If the multipart object is encrypted by SSE-C or SSE-S3, get object with partNumber doesn't decrypt the part.
This patch enables rgw to decrypt the part for get object request with partNumber. …
> rgw: decrypt multipart get part when encrypted

- container/Containerfile
- container/build.sh
- container/make-manifest-list.py
The intent is to replace ceph-container.git, at first for ci containers only, and eventually production containers as well.
There is code present for production containers, including a separate "make-manifest-list.py" to scan for and glue the two arch-specific containers into a 'manifest-list' 'fat' container, but that code is not yet fully tested.
This code will not be used until a corresponding change to the Jenkins jobs in ceph-build.git is pushed.
Currently marked "draft" until the final CI build after cleanup is clean and tested.  Previously tested with a copy of the ceph-dev-new family of Jenkins jobs modified to use this container build mechanism, and run through these teuthology suites to validate basic container functionality as well as iscsi and nfs-ganesha: …
> Add Containerfile and build.sh to build it.

- src/pybind/mgr/dashboard/services/nvmeof_conf.py
- src/pybind/mgr/dashboard/services/orchestrator.py
for nvmeof client, when there are no cert found, it raises an exception which gets logged more often because the dashboard polls the client frequently.
```
Sep 18 13:40:54 ceph-node-00 ceph-mgr[2716]: log_channel(cephadm) log [ERR] : No secret found for entity nvmeof_root_ca_cert with service name nvmeof.rbd.default
File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 140, in wrapper
return OrchResult(f(*args, **kwargs))
File "/usr/share/ceph/mgr/cephadm/module.py", line 3271, in cert_store_get_cert
raise OrchSecretNotFound(entity=entity, service_name=service_name, hostname=hostname)
cephadm.inventory.OrchSecretNotFound: No secret found for entity nvmeof_root_ca_cert with service name nvmeof.rbd.default
Sep 18 13:40:54 ceph-node-00 ceph-mgr[2716]: …
```
> mgr/dashboard: ignore exceptions raised when no cert/key found

- qa/tasks/cephfs/test_admin.py
- src/pybind/mgr/status/module.py
Fix rank field of standby-replay mds daemon in 'ceph fs status'
json output. The rank field for standby-replay mds daemons
were incorrect. It should be of the format '{rank}-s',
where {rank} is the active mds which the standby-replay is
following.
Fixes: https://tracker.ceph.com/issues/67978 …
> mgr/status: Fix 'fs status' json output

- src/pybind/mgr/dashboard/services/rgw_client.py
backport tracker: https://tracker.ceph.com/issues/68225
---
backport of https://github.com/ceph/ceph/pull/59918
parent tracker: https://tracker.ceph.com/issues/68176
> reef: mgr/dashboard: fix setting compression type while editing rgw zone 

- src/pybind/mgr/dashboard/frontend/src/app/shared/api/prometheus.service.ts
backport tracker: https://tracker.ceph.com/issues/68208
---
backport of https://github.com/ceph/ceph/pull/59891
parent tracker: https://tracker.ceph.com/issues/68162
> reef: mgr/dashboard: fix handling NaN values in dashboard charts

- make-dist
Otherwise, a version like 'vX.Y.Z-foo-bar-baz' would end up as an rpm release of 'foo.bar-baz' in the spec file, and rpm will not like that very much because of that extra '-'.
Signed-off-by: Joao Eduardo Luis \<joao@clyso.com>
> make-dist: replace all '-' for '.' for rpm release

- src/pybind/mgr/dashboard/services/rgw_client.py
Increase timeout to detect replication user in the secondary cluster in rgw multisite automation wizard. Currently its set to 2 mins, increase it to 5 minutes.
When you import realm token to the secondary cluster, we wait for the replication/system user we created in the primary cluster to be present in the secondary cluster and when we find that user we set the credentials in the secondary cluster using ceph dashboard set-rgw-crdentials . The timeout for this is set to 2 minutes and sometimes it takes more than 2 minutes for the user to be replicated in the secondary cluster
Fixes: https://tracker.ceph.com/issues/68384 …
> mgr/dashboard: increase timeout to detect replication user in the secondary cluster

- src/rgw/rgw_auth.cc
We have special error handling for these cases but we don't check the negative value of the error so it
instead gets caught as an error not defined with a response and throws a http 500.
This was implement by [1] and the same way done
with [2].
[1] https://github.com/ceph/ceph/pull/55371
[2] https://github.com/ceph/ceph/pull/56044 …
> rgw/auth: fix internal server error for presigned urls

- src/cls/user/cls_user.cc
the returned marker is a bucket name. when bucket names are long, the response can overflow the 64-byte limit on responses to write operations with librados::OPERATION_RETURNVEC. this leads to errors like:
> ERROR: could not reset user stats: (75) Value too large for defined data type
however, the client only needs this marker string to resume listing after a truncated response. if the listing is not truncated, we can omit the marker to save space
in general, users will have less than MAX_ENTRIES=1000 buckets, so won't get truncated listings
Fixes: https://tracker.ceph.com/issues/51786
<details>
- …
> cls/user: reset stats only returns marker when truncated

- qa/workunits/rgw/test_rgw_bucket_check.py
relates to https://tracker.ceph.com/issues/65654
<details>
</details>
> qa/rgw: add debug log to help diagnose 'bucket check unlinked' failure

- src/osd/PeeringState.cc
pg stat are not synced between osds after deep-scrub. So if primary osd is killed, next primary osd has wrong stats. Reason behind it is PeeringState::proc_primary_info does not process or update any pg stats of secondary osds after deep-scrub. 
Fixes: https://tracker.ceph.com/issues/66059 …
> OSD: PG stat is not synchronized between osds after deep-scrub

- src/os/ObjectStore.h
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/os/filestore/FileStore.h
- src/os/kstore/KStore.h
- src/os/memstore/MemStore.h
- src/test/objectstore/store_test.cc
This allows to get rid off relevant sleep() calls in store_test.
Parent tracker: https://tracker.ceph.com/issues/63106
Backport of: https://github.com/ceph/ceph/pull/54194
Backport tracker: https://tracker.ceph.com/issues/63321 …
> quincy: os: introduce ObjectStore::refresh_perf_counters() method

- src/os/bluestore/BlueStore.cc
- src/test/objectstore/store_test.cc
Parent tracker: https://tracker.ceph.com/issues/62330
Partial backport of: https://github.com/ceph/ceph/pull/53178
Backport tracker: https://tracker.ceph.com/issues/64858
After introduction of lazy statfs updates and mechanism to store them at exit, some tests required tune-up.
(cherry picked from commit 85f03d314e7ea5a3ed22fdd3eaca1349e5c23710) …
> quincy: os/store_test: Retune tests to current code

- src/blk/BlockDevice.cc
- src/blk/BlockDevice.h
- src/blk/kernel/KernelDevice.cc
- src/common/options/global.yaml.in
- src/mon/PGMap.cc
- src/os/bluestore/BlueFS.cc
- src/os/bluestore/BlueFS.h
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
backport tracker: https://tracker.ceph.com/issues/67039
--------
backport of #57722
parent tracker: https://tracker.ceph.com/issues/62500
> quincy: os/bluestore: Warning added for slow operations and stalled read

- src/common/Formatter.cc
- src/common/Formatter.h
- src/test/common/test_json_formatter.cc
backport tracker: https://tracker.ceph.com/issues/68325
--------
backport of #58598
parent tracker: https://tracker.ceph.com/issues/66215
> quincy: common/Formatter: dump inf/nan as null

- doc/man/8/mount.ceph.rst
Change the default from "wsync" to "nowsync". "nowsync" has been the default since kernel version 5.16.
This information was reported on
https://pad.ceph.com/p/Report_Documentation_Bugs by Benjamin Mare on 07 Oct 2024.
The commit relevant to this change can be seen here, in Linus's main branch:  https://github.com/torvalds/linux/commit/f7a67b463fb83a4b9b11ceaa8ec4950b8fb7f902 …
> doc/man: supplant "wsync" with "nowsync" as the default

- src/mgr/ActivePyModules.cc
backport tracker: https://tracker.ceph.com/issues/58806
---
backport of https://github.com/ceph/ceph/pull/49487
parent tracker: https://tracker.ceph.com/issues/58269
> quincy: mgr: don't dump global config holding gil

- src/mgr/DaemonServer.cc
backport tracker: https://tracker.ceph.com/issues/63036
---
backport of https://github.com/ceph/ceph/pull/52509
parent tracker: https://tracker.ceph.com/issues/61942
> quincy: mgr: add throttle policy for DaemonServer

- src/mgr/DaemonServer.cc
backport tracker: https://tracker.ceph.com/issues/57473
---
backport of https://github.com/ceph/ceph/pull/47002
parent tracker: https://tracker.ceph.com/issues/45591
> quincy: mgr: fix a race condition in DaemonServer::handle_report()

- src/tools/rados/rados.cc
backport tracker: https://tracker.ceph.com/issues/63976
---
backport of https://github.com/ceph/ceph/pull/54518
parent tracker: https://tracker.ceph.com/issues/63541
> quincy: Tools/rados: Improve Error Messaging for Object Name Resolution

- src/common/io_exerciser/RadosIo.cc
common/io_exerciser: Add version argument to callbacks in ceph_radios_io_sequence
Add new version that was missing from ceph_test_rados_io_sequence async_operate callbacks due to interface changes.
Fixes issue breaking compilation introduced in #59857, commit 54e0865cd6ed5242b6cc02a8b942c2527c77f244 (src/test/osd: create ceph_test_rados_io_sequence testing tool)
Signed-off-by: Jon Bailey <jonathan.bailey1@ibm.com>
- When filling …
> common/io_exerciser: Add version argument to callbacks in ceph_radios_io_sequence

- doc/cephfs/cephfs-journal-tool.rst
Fixed this based on the review of https://github.com/ceph/ceph/pull/59096.
- …
> doc: update 'header get' output in cephfs-journal-tool.rst

- src/common/io_exerciser/RadosIo.cc
Fixes issue introduced in #59857 (54e0865cd6ed5242b6cc02a8b942c2527c77f244)
is_locked_by_me() is a function of ceph::mutex which is only used in debug builds. By using the ceph_mutex_is_locked_by_me macro, we can neatly make sure we only run this function in debug mode, allowing compilation to no longer fail due to missing ceph::mutex specific functions when running in release mode.
Signed-off-by: JonBailey1993 <jonathan.bailey1@ibm.com> …
> common/io_exerciser: Modify is_locked_by_me call in ceph_test_rados_io_sequence

- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/constants/cephfs.constant.ts
backport tracker: https://tracker.ceph.com/issues/68163
backport of: https://github.com/ceph/ceph/pull/59074
parent tracker: https://tracker.ceph.com/issues/67400
https://github.com/user-attachments/assets/d5cea3a6-08f6-4290-9fe8-259e889566a9
Conflicts snapshots->
For adding error message fro CephFS path replaced ng-template with span. …
> Squid: mgr/dashboard: NFS Export form fixes

- src/rgw/rgw_lua_background.h
- src/test/rgw/test_rgw_lua.cc
this makes the test more consistent as well as faster
fixes: https://tracker.ceph.com/issues/68335
<details>
</details>
> test/rgw/lua: use stats polling instead of sleep

- qa/suites/fs/libcephfs/tasks/client.yaml
- qa/tasks/cephfs/test_nfs.py
- qa/workunits/client/test_oc_disabled.sh
- src/client/Client.cc
- src/client/Client.h
- src/test/client/nonblocking.cc
Problem:
With cephfs nfs-ganesha, there were following
asserts hit while doing write on a file.
1. FAILED ceph_assert((bool)_front == (bool)_size)
2. FAILED ceph_assert(cap_refs[c] > 0)
Cause:
In aio path, the client_lock was not being held
in the internal callback after the io is done where it's expected to be taken leading to corruption.
Fix:
Take client_lock in the callback
Fixes: https://tracker.ceph.com/issues/68146
Fixes: https://tracker.ceph.com/issues/68308
Fixes: https://tracker.ceph.com/issues/68309 …
> client: Fix libcephfs aio metadata corruption.

- doc/dev/developer_guide/essentials.rst
Remove mention of "Stable Releases and Backports" from doc/dev/developer_guide/essentials.rst. …
> doc/dev: remove "Stable Releases and Backports"

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-pipe-modal/rgw-multisite-sync-pipe-modal.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rgw_client.py
Fixes: https://tracker.ceph.com/issues/68387
Fixes Includes:
1) Passing additional parameter for 'user' and 'mode' as the user can be either system/dashboard or other values while creating pipe. 2) Previously while removing the src/dest bucket field, we were getting same old values on editing pipe, but now it will become '*' if empty value passed from frontend.
**BEFORE:**
https://github.com/user-attachments/assets/d4d0d802-96f3-4c88-b963-9510fc079d1b
**AFTER:**
https://github.com/user-attachments/assets/30429edc-51f5-451e-98a1-47f6e22e7ecd …
> mgr/dashboard: unable to edit pipe config for bucket level policy of bucket

- src/crimson/os/seastore/cache.cc
- src/crimson/os/seastore/extent_placement_manager.cc
- src/crimson/os/seastore/transaction.h
In RBM, seastore issues ool writes with allocated address. If a transaction conflict occurs at this point, the allocated address is freed, allowing the address to be reused.
However, data inconsistency can occur if seastore issues ool writes with the freed address before the preceding ool write has not been complete.
To fix this issue, this commit frees the allocated address after ool writes is done in the event of the transaction conflict after ool write is issued. …
> crimson/os/seastore: fix data inconsistency during ool writes

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rgw_client.py
backport tracker: https://tracker.ceph.com/issues/68480
---
backport of https://github.com/ceph/ceph/pull/60050
parent tracker: https://tracker.ceph.com/issues/68329
> squid: mgr/dashboard: show non default realm sync status in rgw overview page        

- src/pybind/mgr/cephadm/templates/services/mgmt-gateway/internal_server.conf.j2
- src/pybind/mgr/cephadm/tests/test_services.py
Fixes: https://tracker.ceph.com/issues/68310
https://bugzilla.redhat.com/show_bug.cgi?id=2317833 …
> mgr/cephadm: adding config to enforce clients cert check for internal nginx (mTLS)

- container/build.sh
The wrong string was used for comparison, and for tagging, so the arm64 branch and sha1 images overwrote and destroyed the amd64 images. …
> container/build.sh: fix arm architecture tagging

- doc/man/8/rbd.rst
Updates the rbd man page to clarify  that some mirror commands can apply to pools and namespaces.
(cherry picked from commit 5e64748927d029ceffc27edbc6cbf7c774a7b291) …
> squid: doc/rbd: add namespace information for mirror commands

- doc/man/8/rbd.rst
Updates the rbd man page to clarify  that some mirror commands can apply to pools and namespaces.
(cherry picked from commit 5e64748927d029ceffc27edbc6cbf7c774a7b291) …
> quincy: doc/rbd: add namespace information for mirror commands

- src/crimson/osd/backfill_state.cc
- src/crimson/osd/backfill_state.h
- src/test/crimson/test_backfill.cc
Fixes: https://tracker.ceph.com/issues/68061 …
> crimson/osd/backfill_state: always go to Enqueuing when object is pushed during Waiting

- src/crimson/osd/backfill_state.cc
Fixes: https://tracker.ceph.com/issues/68147 …
> crimson/osd/backfill_state: push peer pg infos' last_backfills only when all objects before them are backfilled

- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-list/nvmeof-listeners-list.component.ts
Listener deletion is broken due to passing wrong gateway address. Including `traddr` in DELETE API of listener to choose correct gateway address for deletion.
The same fix we did for POST API here: https://github.com/afreen23/ceph/commit/287ff3b3603291763b3cd08f9b1543fe60d5f3b9
Fixes: https://tracker.ceph.com/issues/68506
[Screencast from 2024-10-11 14-48-53.webm](https://github.com/user-attachments/assets/95c968e9-32b2-4e28-bfae-fb3e992557ea)
<details> …
> mgr/dashboard: Fix listener deletion

- src/pybind/mgr/dashboard/services/rgw_client.py
backport tracker: https://tracker.ceph.com/issues/68210
---
backport of https://github.com/ceph/ceph/pull/59890
parent tracker: https://tracker.ceph.com/issues/68161
> reef: mgr/dashboard: update period after migrating to multi-site 

- qa/tasks/cephfs/test_volumes.py
`smb.test` is an invalid earmark now(after #59387 ) it should be either `smb` or `smb.cluster.<cluster_id>`. 
Updated the test_volumes.py to  valid earmarks wherever used.
Fixes: https://tracker.ceph.com/issues/68448 …
> qa/cephfs: update earmark values to valid ones in test_volumes.py

- doc/cephfs/fs-volumes.rst
- qa/tasks/cephfs/test_volumes.py
- src/pybind/mgr/volumes/fs/operations/subvolume.py
- src/pybind/mgr/volumes/fs/operations/template.py
- src/pybind/mgr/volumes/fs/operations/versions/subvolume_base.py
- src/pybind/mgr/volumes/fs/operations/versions/subvolume_v1.py
- src/pybind/mgr/volumes/fs/operations/versions/subvolume_v2.py
- src/pybind/mgr/volumes/fs/volume.py
- src/pybind/mgr/volumes/module.py
- src/python-common/ceph/fs/__init__.py
- src/python-common/ceph/fs/earmarking.py
- src/python-common/ceph/tests/test_earmarking.py
backport tracker: https://tracker.ceph.com/issues/68125
---
backport of https://github.com/ceph/ceph/pull/59111
parent tracker: https://tracker.ceph.com/issues/67460
> squid: mgr/volumes: add earmarking for subvol

- SubmittingPatches-backports.rst
Remove all references to the "Stable Releases and Backports Team", which as of October 2024 does not exist.
Fixes: https://tracker.ceph.com/issues/68471 …
> doc: SubmittingPatches-backports - remove backports team

- qa/standalone/scrub/osd-scrub-repair.sh
- src/common/map_cacher.hpp
- src/common/scrub_types.cc
- src/common/scrub_types.h
- src/osd/scrubber/ScrubStore.cc
- src/osd/scrubber/ScrubStore.h
- src/osd/scrubber/pg_scrubber.cc
- src/osd/scrubber/pg_scrubber.h
The ScrubStore now holds two separate error databases,
one for the shallow errors and one for the deep errors.
The shallow errors DB is recreated at the start of every scrub,
while the deep errors DB is only recreated at the start of a
deep scrub.
When queried by the operator for known scrub errors, the
ScrubStore returns the union of the errors from both
DBs.
co-author: Shreekara <sshreeka@redhat.com>
> osd/scrub: separate shallow vs deep errors storage

- SubmittingPatches-backports.rst
Remove all references to the "Stable Releases and Backports Team", which as of October 2024 does not exist.
Fixes: https://tracker.ceph.com/issues/68471
(cherry picked from commit 0317b5f87ac22399f6242d72f0bb9924794687de) …
> quincy: doc: SubmittingPatches-backports - remove backports team

- src/common/options/global.yaml.in
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/os/kstore/KStore.cc
- src/os/kstore/KStore.h
- src/os/memstore/MemStore.cc
- src/test/objectstore/store_test.cc
- src/test/objectstore/store_test_fixture.cc
- src/test/objectstore/store_test_fixture.h
Looks like death assertions aren't 100% reliable and might cause deadlock sometimes.
Hence getting rid of them and enabling optional sending exception from *Store::queue_transaction()
Parent tracker: https://tracker.ceph.com/issues/61193
Backports: https://github.com/ceph/ceph/pull/53154
Backport tracker: https://tracker.ceph.com/issues/64115
(cherry picked from commit 46f01d832487d3a3183783d41450fd8f49347097) …
> quincy: test/store_test: get rid off assert_death.

- qa/README
- qa/tasks/cbt.py
This is my first PR so please be gentle with me :-) 
[component]: qa/tasks
Cosbench support is being deleted from the Ceph Benchmarking Tool (CBT) (github.com/ceph/cbt.git) in favour of using HSBench and Elbencho.
Cosbench tests using CBT were implemented in Mimic, Nautilus,Octopus  and Pacific releases, but was then removed in  Quincy.
Pacific and older releases have now been Archived and no longer in support.
Later on we will add teuthology tests to add object tests to teuthology once the CBT work has been developed.
The python code in this PR is dormant infrastructure code to enable use of cosbench tests if a CBT test plan YAML was specified in the qa/suites/xxxx/ directories however there isn't any CBT test plan YAMLs enabling this function. Therefore the code to use cosbench in CBT …
> qa/suites/tasks/cbt.py: Deprecating cosbench from Teuthology in preparation for deletion of cosbench from CBT

- src/common/options/global.yaml.in
- src/log/Entry.h
- src/log/Log.cc
- src/log/Log.h
backport tracker: https://tracker.ceph.com/issues/56637
---
backport of https://github.com/ceph/ceph/pull/46736
parent tracker: https://tracker.ceph.com/issues/56093
> quincy: log: Make log_max_recent have an effect again.

- doc/rados/operations/monitoring.rst
- src/common/admin_socket.cc
- src/common/admin_socket.h
- src/test/admin_socket.cc
Backport ticket: https://tracker.ceph.com/issues/63362
Original ticket: https://tracker.ceph.com/issues/63362
Original PR: https://github.com/ceph/ceph/pull/53689
---
The new command "raise <signal> [--after X]" accepts signals in the forms: '9', '-9', 'kill', '-KILL'
When --after is specified, the program will fork to wait for the timeout
The forked instance will bail out if it detects that the parent PID has changed which would indicate that the original parent has terminated.
Forking an instance allows to schedule delivery of signals even if the original process is suspended, e.g.:
```
ceph tell mds.a raise CONT --after 10
ceph tell mds.a raise STOP
```
<details>
- `jenkins …
> quincy: common/admin_socket: add a command to raise a signal

- SubmittingPatches-backports.rst
Remove all references to the "Stable Releases and Backports Team", which as of October 2024 does not exist.
Fixes: https://tracker.ceph.com/issues/68471
(cherry picked from commit 0317b5f87ac22399f6242d72f0bb9924794687de) …
> squid: doc: SubmittingPatches-backports - remove backports team

- src/mon/OSDMonitor.cc
- src/mon/OSDMonitor.h
backport tracker: https://tracker.ceph.com/issues/64651
---
backport of https://github.com/ceph/ceph/pull/54999
parent tracker: https://tracker.ceph.com/issues/63883
> squid: mon/OSDMonitor: fix get_min_last_epoch_clean()

- container/Containerfile
- container/build.sh
- container/make-manifest-list.py
backport tracker: https://tracker.ceph.com/issues/68469
---
backport of https://github.com/ceph/ceph/pull/59868 and https://github.com/ceph/ceph/pull/60255
parent tracker: https://tracker.ceph.com/issues/68467
> squid: Add Containerfile and build.sh to build it.

- container/Containerfile
- container/build.sh
- container/make-manifest-list.py
backport tracker: https://tracker.ceph.com/issues/68470
---
backport of https://github.com/ceph/ceph/pull/59868 and https://github.com/ceph/ceph/pull/60255
parent tracker: https://tracker.ceph.com/issues/68467
> quincy: Add Containerfile and build.sh to build it.

- qa/tasks/mgr/dashboard/test_osd.py
- src/pybind/mgr/dashboard/controllers/osd.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/osd.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/osd.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/paginate.model.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/classes/paginate-params.class.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/cd-table-fetch-data-context.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/osd.model.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/tests/test_osd.py
backport tracker: https://tracker.ceph.com/issues/68523
---
backport of https://github.com/ceph/ceph/pull/59905
parent tracker: https://tracker.ceph.com/issues/56511
> squid: mgr/dashboard: introduce server side pagination for osds

- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/openapi.yaml
backport of #60150
This was missed in the previous implementation
(cherry picked from commit 485cb051192a6142104756ed88a900a5ba455179)
<details>
</details>
> squid: mgr/dashboard: add gw_groups to all nvmeof endpoints  

- qa/tasks/mgr/dashboard/test_osd.py
- src/pybind/mgr/dashboard/controllers/osd.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/osd.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/osd.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/paginate.model.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/classes/paginate-params.class.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/cd-table-fetch-data-context.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/osd.model.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/tests/test_osd.py
backport tracker: https://tracker.ceph.com/issues/68522
---
backport of https://github.com/ceph/ceph/pull/59905
parent tracker: https://tracker.ceph.com/issues/56511
> reef: mgr/dashboard: introduce server side pagination for osds

- container/Containerfile
- container/build.sh
- container/make-manifest-list.py
backport tracker: https://tracker.ceph.com/issues/68468
---
backport of https://github.com/ceph/ceph/pull/59868 and https://github.com/ceph/ceph/pull/60255
parent tracker: https://tracker.ceph.com/issues/68467
> reef: Add Containerfile and build.sh to build it.

- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-list/nvmeof-listeners-list.component.ts
backport tracker: https://tracker.ceph.com/issues/68521
---
backport of https://github.com/ceph/ceph/pull/60259
parent tracker: https://tracker.ceph.com/issues/68506
> squid: mgr/dashboard: Fix listener deletion 

- doc/man/8/mount.ceph.rst
Change the default from "wsync" to "nowsync". "nowsync" has been the default since kernel version 5.16.
This information was reported on
https://pad.ceph.com/p/Report_Documentation_Bugs by Benjamin Mare on 07 Oct 2024.
The commit relevant to this change can be seen here, in Linus's main branch:
https://github.com/torvalds/linux/commit/f7a67b463fb83a4b9b11ceaa8ec4950b8fb7f902
(cherry picked from commit 9f0af5d75dc64ef0520fd78f29815d2a824a859b) …
> reef: doc/man: supplant "wsync" with "nowsync" as the default

- doc/man/8/mount.ceph.rst
Change the default from "wsync" to "nowsync". "nowsync" has been the default since kernel version 5.16.
This information was reported on
https://pad.ceph.com/p/Report_Documentation_Bugs by Benjamin Mare on 07 Oct 2024.
The commit relevant to this change can be seen here, in Linus's main branch:
https://github.com/torvalds/linux/commit/f7a67b463fb83a4b9b11ceaa8ec4950b8fb7f902
(cherry picked from commit 9f0af5d75dc64ef0520fd78f29815d2a824a859b) …
> quincy: doc/man: supplant "wsync" with "nowsync" as the default

- src/cephadm/cephadmlib/daemons/smb.py
CTDB heavily depends on raw sockets to send [gratuitous ARPs](https://wiki.wireshark.org/Gratuitous_ARP)(see the second point from the list of reasons to use gratuitous ARPs). As per the current design it is also inevitable while sending [tickle ACKs](https://ctdb.samba.org/manpages/ctdb.1.html) in the event of an IP failover. man [capabilities(7)](https://www.man7.org/linux/man-pages/man7/capabilities.7.html) further mandates `CAP_NET_RAW` to use raw sockets. Therefore append `NET_RAW` to the list of capabilities while deploying _ctdbd_ containers.
> cephadm/smb: Add NET_RAW capability to deploy ctdbd

- doc/mgr/smb.rst
- src/pybind/mgr/smb/module.py
We can set the public ip address to set for the cluster using the declarative method by providing the information in the resource description. The corresponding functionality is not available with the imperative method of creating the smb cluster.
This patch adds this functionality by allowing the user the option of providing the a public address on the command line when creating the smb cluster. …
> mgr/smb: accept public_addrs on cli when creating cluster

- src/mon/Monitor.cc
- src/mon/MonitorDBStore.h
backport tracker: https://tracker.ceph.com/issues/65258
---
backport of https://github.com/ceph/ceph/pull/53858
parent tracker: https://tracker.ceph.com/issues/57515
> reef: mon: add created_at and ceph_version_when_created meta

- src/common/TrackedOp.h
- src/osd/OpRequest.cc
backport tracker: https://tracker.ceph.com/issues/61395
---
backport of https://github.com/ceph/ceph/pull/51668
parent tracker: https://tracker.ceph.com/issues/61388
> reef: osd/TrackedOp: Fix TrackedOp event order

- qa/suites/rados/dashboard/tasks/e2e.yaml
backport tracker: https://tracker.ceph.com/issues/67472
---
backport of https://github.com/ceph/ceph/pull/58205
parent tracker: https://tracker.ceph.com/issues/64870
> reef: suites: test should ignore osd_down warnings

- src/os/bluestore/Allocator.cc
- src/test/objectstore/Allocator_test.cc
backport tracker: https://tracker.ceph.com/issues/61465
---
backport of https://github.com/ceph/ceph/pull/49885
parent tracker: https://tracker.ceph.com/issues/58022
> reef: BlueStore: Improve fragmentation score metric

- src/mds/MDSDaemon.cc
- src/mds/MDSDaemon.h
- src/mgr/DaemonServer.cc
- src/mgr/DaemonServer.h
- src/mon/MonClient.cc
- src/mon/Monitor.cc
- src/mon/Monitor.h
- src/msg/Dispatcher.h
- src/osd/OSD.cc
- src/osd/OSD.h
- src/test/fio/fio_ceph_messenger.cc
- src/test/msgr/perf_msgr_client.cc
- src/test/msgr/perf_msgr_server.cc
- src/test/msgr/test_msgr.cc
backport tracker: https://tracker.ceph.com/issues/67476
---
backport of https://github.com/ceph/ceph/pull/52939
parent tracker: https://tracker.ceph.com/issues/62382
> quincy: mon/MonClient: handle ms_handle_fast_authentication return

- src/mon/MonCommands.h
- src/mon/OSDMonitor.cc
backport tracker: https://tracker.ceph.com/issues/67665
---
backport of https://github.com/ceph/ceph/pull/57548
parent tracker: https://tracker.ceph.com/issues/66122
> quincy: mon/OSDMonitor: Add force-remove-snap mon command

- src/librados/IoCtxImpl.cc
backport tracker: https://tracker.ceph.com/issues/65040
---
backport of https://github.com/ceph/ceph/pull/55348
parent tracker: https://tracker.ceph.com/issues/64558
> reef: librados: use CEPH_OSD_FLAG_FULL_FORCE for IoCtxImpl::remove

- doc/radosgw/multisite.rst
this was copy/pasted from Configuring a Master Zone -> Update the Period but still referred to the 'master zone'
<details>
</details>
> doc/radosgw/multisite: fix Configuring Secondary Zones -> Updating the Period

- src/pybind/mgr/cephadm/services/nvmeof.py
- src/pybind/mgr/dashboard/services/nvmeof_conf.py
there are 2 issues
1. in cephadm, i was always using the first daemon to populate the group in all the services for the dashboard config.
2. in the API, if there are more than 1 gateways listed in the config, rather than chosing a random gateway from the group, raise an exception and warn user to specify the gw_group parameter in the api request
Fixes: https://tracker.ceph.com/issues/68463
API call without providing a `gw_group` parameter in the request when there are more than one service or gw-group.
```
╰─$ curl -skX GET "https://192.168.100.100:8443/api/nvmeof/gateway" \
-H "Accept: application/vnd.ceph.api.v1.0+json" \
-H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" | jq .
{
"detail": "Multiple NVMe-oF gateways are configured. Please specify the 'gw_group' …
```
> mgr/dashboard: fix group name bugs in the nvmeof API

- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/serve.py
- src/pybind/mgr/cephadm/services/cephadmservice.py
backport tracker: https://tracker.ceph.com/issues/68546
---
backport of https://github.com/ceph/ceph/pull/60221
parent tracker: https://tracker.ceph.com/issues/68461
> squid: mgr/cephadm: Update multi-site configs before deploying  daemons on rgw service create 

- qa/tasks/cephfs/test_scrub_checks.py
- src/mds/MDSRank.cc
backport tracker: https://tracker.ceph.com/issues/66870
---
backport of https://github.com/ceph/ceph/pull/53301
parent tracker: https://tracker.ceph.com/issues/62537
> quincy: mds: prevent scrubbing for standby-replay MDS

- src/mds/Locker.cc
Fixes: https://tracker.ceph.com/issues/66668 …
> quincy: mds: set the correct WRLOCK flag always in wrlock_force()

- qa/suites/fs/multiclient/clusters/1-mds-2-client.yaml
- qa/tasks/cephfs/test_misc.py
- src/mds/MDSDaemon.cc
- src/mds/MDSRank.cc
- src/mds/SessionMap.cc
backport tracker: https://tracker.ceph.com/issues/67076
---
backport of https://github.com/ceph/ceph/pull/49974
parent tracker: https://tracker.ceph.com/issues/58619
> quincy: mds: fix session/client evict command.

- qa/tasks/cephfs/test_snap_schedules.py
backport tracker: https://tracker.ceph.com/issues/66671
---
backport of https://github.com/ceph/ceph/pull/57034
parent tracker: https://tracker.ceph.com/issues/65564
> quincy: qa: cleanup snapshots before subvolume delete

- doc/cephfs/cephfs-mirroring.rst
- qa/tasks/cephfs/test_mirroring.py
- src/tools/cephfs_mirror/FSMirror.cc
- src/tools/cephfs_mirror/FSMirror.h
- src/tools/cephfs_mirror/InstanceWatcher.cc
- src/tools/cephfs_mirror/InstanceWatcher.h
- src/tools/cephfs_mirror/Mirror.cc
- src/tools/cephfs_mirror/MirrorWatcher.cc
- src/tools/cephfs_mirror/MirrorWatcher.h
- src/tools/cephfs_mirror/PeerReplayer.cc
- src/tools/cephfs_mirror/PeerReplayer.h
- src/tools/cephfs_mirror/Types.h
- src/tools/cephfs_mirror/Watcher.h
This backport PR includes fixes:
* use monotonic clock
* fix mirror daemon doesn't restart when blocklisted/failed
* update peer status for invalid metadata in remote snapshot
These are backported together to avoid cherry-pick conflicts.
Fixes: https://tracker.ceph.com/issues/62265
Fixes: https://tracker.ceph.com/issues/66981
Fixes: https://tracker.ceph.com/issues/66978
Fixes: https://tracker.ceph.com/issues/66974
Fixes: https://tracker.ceph.com/issues/66971
Fixes: https://tracker.ceph.com/issues/67669
Fixes: https://tracker.ceph.com/issues/67672 …
> quincy: cephfs-mirror: various fixes

- src/client/Client.cc
- src/test/libcephfs/test.cc
Following are the two misbehaviours observed:
- Opening an already existing symlink with `O_PATH` and `O_NOFOLLOW` results in ELOOP.
- after _path_walk()_ we shouldn't blindly return ELOOP without checking for `O_PATH` in _may_open()_.
- see man [open(2)](https://www.man7.org/linux/man-pages/man2/open.2.html) for `O_PATH` explanation.
- Reading a symlink using _ceph_readlinkat()_ with empty path results in SIGABRT.
- there is a missing check for empty pathname
- see man [readlinkat(2)](https://www.man7.org/linux/man-pages//man2/readlinkat.2.html) under DESCRIPTION.
Fixes: https://tracker.ceph.com/issues/67833
> client: Fix opening and reading of symlinks

- src/msg/Messenger.h
backport tracker: https://tracker.ceph.com/issues/67307
---
backport of https://github.com/ceph/ceph/pull/58631
parent tracker: https://tracker.ceph.com/issues/66336
> squid: msg: insert PriorityDispatchers in sorted position

- doc/radosgw/multisite.rst
backport of https://github.com/ceph/ceph/pull/60128, no tracker issue
<details>
</details>
> quincy: doc/radosgw/multisite: fix Configuring Secondary Zones -> Updating the Period

- doc/radosgw/multisite.rst
backport of https://github.com/ceph/ceph/pull/60128, no tracker issue
<details>
</details>
> reef: doc/radosgw/multisite: fix Configuring Secondary Zones -> Updating the Period

- doc/radosgw/multisite.rst
backport of https://github.com/ceph/ceph/pull/60128, no tracker issue
<details>
</details>
> squid: doc/radosgw/multisite: fix Configuring Secondary Zones -> Updating the Period

- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-initiators-form/nvmeof-initiators-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-initiators-list/nvmeof-initiators-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-form/nvmeof-listeners-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-list/nvmeof-listeners-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-list/nvmeof-namespaces-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-details/nvmeof-subsystems-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-form/nvmeof-subsystems-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts
- Added gateway group param in namespace request - GET, POST, PATCH, DELETE
- Added gateway group param in namespace request - GET, POST, PATCH, DELETE
- Added gateway group param in Listeners request - GET
- Added gateway group param in Initiators - GET, POST, DELETE
Fixes https://tracker.ceph.com/issues/68510
Signed-off-by: Afreen Misbah <afreen@ibm.com>
Errors on creating, deleting, listing resources on other group as only default gateway being chosen.
[Screencast from 2024-10-15 21-50-09.webm](https://github.com/user-attachments/assets/c83efd5a-1dcc-4b9c-ad62-f5c784bb8e00)
[Screencast from 2024-10-15 21-38-08.webm](https://github.com/user-attachments/assets/572776ea-1d74-4091-8634-94e3e7ecf3a4)
- …
> mgr/dashboard: Adapt gateway group changes in nvmeof UI

- src/pybind/mgr/cephadm/services/nvmeof.py
- src/pybind/mgr/dashboard/services/nvmeof_conf.py
backport tracker: https://tracker.ceph.com/issues/68559
---
backport of https://github.com/ceph/ceph/pull/60222
parent tracker: https://tracker.ceph.com/issues/68463
> squid: mgr/dashboard: fix group name bugs in the nvmeof API

- src/pybind/mgr/cephadm/templates/services/nfs/ganesha.conf.j2
- src/pybind/mgr/cephadm/tests/test_services.py
This is necessary for ganesha 6.1 running in a container to start up without hitting a permission failure (without having to run the container as --privileged)  and doesn't seem to cause any damage when read in by ganesha v5.9 (the current version in the main branch containers) …
> mgr/cephadm: add "allow_set_io_flusher_fail = true;" to ganesha conf

- src/cephadm/cephadm.py
- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/orchestrator/_interface.py
- src/pybind/mgr/orchestrator/module.py
Additionally, add the flag that does so when cephadm applies a spec during bootstrap. Bootstrap will continue to completion regardless of whether applying the spec fails, so we might as well try applying all of it while reporting errors we do see back to the user
Fixes: https://tracker.ceph.com/issues/65338 …
> cephadm: add ability to continue on failure when applying multiple specs

- src/pybind/mgr/cephadm/templates/services/grafana/grafana.ini.j2
- src/pybind/mgr/cephadm/templates/services/mgmt-gateway/external_server.conf.j2
- src/pybind/mgr/cephadm/tests/test_services.py
Error message when Grafana fails to load:
Fixes: https://tracker.ceph.com/issues/68315
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2317794
So far, Grafana's subpath handling has been managed on the Nginx server side using a rewrite rule. Let's move this logic to the Grafana side to make it consistent with the rest of the monitoring services. …
> mgr/cephadm: move Grafana's subpath handling logic to grafan config

- .github/workflows/check-license.yml
Tested with [PR](https://github.com/epuertat/ceph/pull/2) in [fork](https://github.com/epuertat/ceph/actions/runs/11345807054/job/31553505960?pr=2):
It uses an [action that simply matches text in PR diff](https://github.com/JJ/github-pr-contains-action) (supports regex).
BTW, it fails in this very PR because it contains the text 😆  …
> .github: detect GPL license in PRs

- src/common/Thread.cc
- src/common/Thread.h
- src/log/Entry.h
- src/log/Log.cc
pthread name is saved against the pthread ID in a class-wide static unordered_map as part of the Thread class
save/fetch methods are implemented to manage the thread names
thread names are never removed from the map
Fixes: https://tracker.ceph.com/issues/50743 …
> log: save/fetch thread name infra

- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.ts
backport tracker: https://tracker.ceph.com/issues/68565
backport of: https://github.com/ceph/ceph/pull/60291
parent tracker: https://tracker.ceph.com/issues/68519 …
> Squid: mgr/dashboard: The subvolumes are missing from the dropdown menu on the "Create NFS export" page

- src/tools/cephfs/shell/cephfs-shell
Seeing cephfs-shell failures in Ubuntu22.04 due to its weird behaviour with python3-cmd2's version
Fixes: https://tracker.ceph.com/issues/63700 …
> cephfs-shell: fixing cephfs-shell test failures

- src/cephadm/cephadm.py
- src/cephadm/cephadmlib/container_types.py
Cephadm: Added new cephadm command to list all the default images
Fixes: https://tracker.ceph.com/issues/68438
Testing logs:
```
[root@ceph-node-0 ~]# cephadm list_images
[mgr]
mgr/cephadm/container_image_prometheus = quay.io/prometheus/prometheus:v2.51.0
mgr/cephadm/container_image_alertmanager = quay.io/prometheus/alertmanager:v0.27.0
mgr/cephadm/container_image_graphana = quay.io/ceph/grafana:10.4.8
mgr/cephadm/container_image_loki = docker.io/grafana/loki:3.0.0
mgr/cephadm/container_image_promtail = docker.io/grafana/promtail:3.0.0
mgr/cephadm/container_image_node_exporter = quay.io/prometheus/node-exporter:v1.7.0
mgr/cephadm/container_image_haproxy = quay.io/ceph/haproxy:2.3
mgr/cephadm/container_image_keepalived = …
```
> cephadm: Added cephadm command to list all the default images

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/xml.pipe.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/json-to-xml.service.ts
- src/pybind/mgr/dashboard/frontend/src/styles/_carbon-defaults.scss
- src/pybind/mgr/dashboard/services/rgw_client.py
Fixes: https://tracker.ceph.com/issues/68434
- Now lifecycles properly display multiple rules, before only one rule was being shown even if the lifecycle had multiple rules
- Now JSON formatted lifecycles are properly applied without the need to include 'LifecycleConfiguration' as the first element of the dictionary
[screen-capture (2).webm](https://github.com/user-attachments/assets/51f81f06-7125-4dd1-bcbb-6cd09e6a4b83)
updated video using carbon's `code-snippet` showing a lifecycle with 20 rules
[screen-capture (3).webm](https://github.com/user-attachments/assets/eb46b2c4-7be5-4ea6-9100-6e9e7a19ec7d)
--------
Regarding the code fixes:
- Main issue was due to the `Rule:` key being repeated in the json, which is not allowed, therefore only the last `Rule` was showing up, fixed it with : ` …
> mgr/dashboard: fix lifecycle issues

- src/common/intrusive_lru.h
- src/test/common/test_intrusive_lru.cc
backport tracker: https://tracker.ceph.com/issues/57795
---
backport of https://github.com/ceph/ceph/pull/48128
parent tracker: https://tracker.ceph.com/issues/57573
> quincy: common:  intrusive_lru destructor add

- src/common/options/global.yaml.in
- src/msg/async/ProtocolV2.cc
backport tracker: https://tracker.ceph.com/issues/58815
---
backport of https://github.com/ceph/ceph/pull/49843
parent tracker: https://tracker.ceph.com/issues/58410
> quincy: rados: Set snappy as default value in ms_osd_compression_algorithm

- src/common/options/global.yaml.in
backport tracker: https://tracker.ceph.com/issues/67606
---
backport of https://github.com/ceph/ceph/pull/57120
parent tracker: https://tracker.ceph.com/issues/65678
> quincy: os/bluestore: allow use BtreeAllocator 

- src/global/global_init.cc
backport tracker: https://tracker.ceph.com/issues/68390
---
backport of https://github.com/ceph/ceph/pull/60095
parent tracker: https://tracker.ceph.com/issues/40692
Conflicts:
src/global/global_init.cc
- Replace `make_unique_for_overwrite` which is C++20 with `make_unique` …
> quincy: global: Call getnam_r with a 64KiB buffer on the heap

- doc/monitoring/index.rst
- src/exporter/DaemonMetricCollector.cc
- src/exporter/DaemonMetricCollector.h
- src/test/exporter/test_exporter.cc
Ceph exporter provide metrics to report ceph daemons communication health using
the admin socket
Fixes: 
https://bugzilla.redhat.com/show_bug.cgi?id=2146728
https://tracker.ceph.com/issues/68428
**Evidences:**
**Manual tests:**
```
--> launch of ceph exporter
jolmomar:~/.../build/bin$ ./ceph-exporter -c /home/jolmomar/Code/ceph/build/ceph.conf --sock-dir /home/jolmomar/Code/ceph/build/asok
--> Verify daemons running:
jolmomar:~/.../build/bin$ ls -lrt /home/jolmomar/Code/ceph/build/asok
total 0
srwxr-xr-x 1 jolmomar jolmomar 0 oct  7 16:17 mon.a.asok
srwxr-xr-x 1 jolmomar jolmomar 0 oct  7 16:17 mon.b.asok
srwxr-xr-x 1 jolmomar jolmomar 0 oct  7 16:17 mon.c.asok
srwxr-xr-x 1 jolmomar jolmomar 0 oct  7 16:17 mgr.x.asok
srwxr-xr-x 1 jolmomar jolmomar 0 oct  7 16:17 client.admin.24910.asok …
```
> exporter: New metric for report ceph daemons health

- src/os/bluestore/BlueStore.cc
BlueStore::read_allocation_from_drive_for_bluestore_tool was not informed that multiple bdev labels can exist and reserve space. Comparison real alloc vs recovered alloc was failing.
Fixes: https://tracker.ceph.com/issues/67596 …
> os/bluestore: Fix ceph-bluestore-tool allocmap command

- src/pybind/mgr/volumes/fs/stats_util.py
Orignally, when the feature was in development, IDs for clone progress
bars were set to randomly generated UUID strings. But, eventually, it
was decided to assign fixed strings to them. Unlike UUIDs, these strings
stay the same even when progress bars are destroyed and re-created.
Therefore, instead of re-assigning the same strings every time
initiate_reporting() is called, move them to __init__() so that both the
IDs are defined only once. …
> mgr/vol: don't define progress bar ID repeatedly

- qa/suites/fs/upgrade/mds_upgrade_sequence/overrides/ignorelist_upgrade.yaml
We already ignore health warning regarding OSD being down during upgrade
but health warning regarding specific OSD being down is not added to the
ignorelist which causes upgrade jobs to be marked as failed even though
they were successful.
Fixes: https://tracker.ceph.com/issues/66877 …
> qa/cephfs: ignore when specific OSD is reported down during upgrade

- .github/CODEOWNERS
- .github/labeler.yml
- src/mrgw.sh
- src/mrun
- src/mstart.sh
- src/mstop.sh
> rgw: document and label mstart.sh and related scripts

- PendingReleaseNotes
- src/osd/PeeringState.cc
backport tracker: https://tracker.ceph.com/issues/62817
---
backport of https://github.com/ceph/ceph/pull/52823
parent tracker: https://tracker.ceph.com/issues/62338
> quincy: osd: ensure async recovery does not drop a pg below min_size

- src/os/bluestore/BlueStore.cc
This is both regression and cleanup.
Regression = appeared after merging #59850
Cleanup = now logic of `bdev_label_valid_locations` is more direct.
Fixes: https://tracker.ceph.com/issues/68528 …
> os/bluestore: Fix repair of multilabel when collides with BlueFS

- qa/suites/rados/singleton/all/mon-connection-score.yaml
- qa/tasks/ceph_test_case.py
- qa/tasks/mon_connection_score.py
- src/mon/ConnectionTracker.cc
backport tracker: https://tracker.ceph.com/issues/68280
---
backport of https://github.com/ceph/ceph/pull/57146
parent tracker: https://tracker.ceph.com/issues/65695
<details>
- `jenkins …
> squid: src/mon/ConnectionTracker.cc: Fix dump function

- src/test/rbd_mirror/test_mock_PoolReplayer.cc
- src/tools/rbd_mirror/PoolReplayer.cc
backport tracker: https://tracker.ceph.com/issues/67763
---
backport of https://github.com/ceph/ceph/pull/59401
parent tracker: https://tracker.ceph.com/issues/67676
> reef: rbd-mirror: use correct ioctx for namespace

- src/os/bluestore/BlueStore.cc
The problem was that BDEV_FIRST_LABEL_POSITION was removed from bdev_label_valid_locations set.
Now, if label at BDEV_FIRST_LABEL_POSITION is valid, it is in the set.
Fixes: https://tracker.ceph.com/issues/68558
(cherry picked from commit 3536ca7eb08d8c6e2964622644780b11f6b7399b) …
> squid: os/bluestore: Fix repair of multilabel when collides with BlueFS

- src/os/bluestore/BlueStore.cc
Reservation (alloc->init_rm_free) was after reopening DB in r/w mode. This was a problem - as soon as DB is in r/w it can flush sst or compact, which will make allocations.
Fixes: https://tracker.ceph.com/issues/68222
(cherry picked from commit 9dd0b2369f9c07548074f778ad47614f9d7caa4e) …
> squid: os/bluestore: Fix BlueFS allocating bdev label reserved location

- src/common/io_exerciser/RadosIo.cc
- src/test/osd/ceph_test_rados_io_sequence.cc
- src/test/osd/ceph_test_rados_io_sequence.h
test/osd/ceph_test_rados_io_sequence: Add interactive mode
This pull request is a follow on to https://github.com/ceph/ceph/pull/59857 and contains/requires the commits in that PR before this can be merged.
Adds a new "interactive" test mode to ceph_test_rados_io_sequence that allows you to direct the order of operations rather than using the preset sequences. This allows complete precise control of the tool when you want to test specific IOs.
Signed-off-by: Jon Bailey [jonathan.bailey1@ibm.com](mailto:jonathan.bailey1@ibm.com) …
> test/osd: Add interactive mode to ceph_test_rados_io_sequence

- qa/workunits/rbd/cli_migration.sh
- src/librbd/ImageCtx.cc
- src/librbd/io/Utils.cc
- src/librbd/io/Utils.h
- src/librbd/migration/NativeFormat.cc
- src/librbd/migration/QCOWFormat.cc
- src/librbd/migration/RawFormat.cc
- src/test/librbd/migration/test_mock_RawFormat.cc
backport tracker: https://tracker.ceph.com/issues/67895
---
backport of https://github.com/ceph/ceph/pull/59551
parent tracker: https://tracker.ceph.com/issues/67845
> reef: librbd/migration: prune snapshot extents in RawFormat::list_snaps()

- src/tools/rbd/action/Bench.cc
backport tracker: https://tracker.ceph.com/issues/67736
---
backport of https://github.com/ceph/ceph/pull/59423
parent tracker: https://tracker.ceph.com/issues/67698
> reef: rbd: "rbd bench" always writes the same byte

- src/os/bluestore/BlueStore.cc
BlueStore::read_allocation_from_drive_for_bluestore_tool was not informed that multiple bdev labels can exist and reserve space. Comparison of real alloc vs recovered alloc was failing.
Fixes: https://tracker.ceph.com/issues/68560
(cherry picked from commit 358f33a148c9a65478e33648f16e8c8af73c98f2) …
> squid: os/bluestore: Fix ceph-bluestore-tool allocmap command

- src/mds/Locker.cc
backport tracker: https://tracker.ceph.com/issues/66624
---
backport of https://github.com/ceph/ceph/pull/56828
parent tracker: https://tracker.ceph.com/issues/64977
> quincy: mds: do remove the cap when seqs equal or larger than last issue

- src/tools/rbd/action/Bench.cc
backport tracker: https://tracker.ceph.com/issues/67735
---
backport of https://github.com/ceph/ceph/pull/59423
parent tracker: https://tracker.ceph.com/issues/67698
> squid: rbd: "rbd bench" always writes the same byte

- src/test/rbd_mirror/test_mock_PoolReplayer.cc
- src/tools/rbd_mirror/PoolReplayer.cc
backport tracker: https://tracker.ceph.com/issues/67764
---
backport of https://github.com/ceph/ceph/pull/59401
parent tracker: https://tracker.ceph.com/issues/67676
> squid: rbd-mirror: use correct ioctx for namespace

- src/common/Finisher.cc
- src/common/Finisher.h
- src/mgr/ActivePyModule.h
- src/mgr/ActivePyModules.cc
Several patches which reduce lock contention and eliminate system calls in the `Finisher` thread, similar to what commit cc7ec3e18d1 did five years ago.
> Optimize lock contention in the `Finisher` thread

- src/msg/async/ProtocolV2.cc
- src/msg/async/ProtocolV2.h
All callers really pass a C string literal, and declaring a `std::string` parameter will implicitly create two `std::string` instances: one on the caller's stack, and another one inside write() as parameter to the continuation lambda.  This causes considerable and unnecessary overhead.
This patch reduces the code size by nearly 2 kB.
> msg/async/ProtocolV2: pass `desc` as C string to write()

- src/client/Client.cc
- src/test/libcephfs/suidsgid.cc
An unprivileged user can `chmod 777` a directory owned by root and gain access. Fix this bug and also add a test case for the same. …
> quincy: client: disallow unprivileged users to escalate root privileges

- qa/workunits/rbd/cli_migration.sh
- src/librbd/ImageCtx.cc
- src/librbd/io/Utils.cc
- src/librbd/io/Utils.h
- src/librbd/migration/NativeFormat.cc
- src/librbd/migration/QCOWFormat.cc
- src/librbd/migration/RawFormat.cc
- src/test/librbd/migration/test_mock_RawFormat.cc
backport tracker: https://tracker.ceph.com/issues/67894
---
backport of https://github.com/ceph/ceph/pull/59551
parent tracker: https://tracker.ceph.com/issues/67845
> squid: librbd/migration: prune snapshot extents in RawFormat::list_snaps()

- doc/cephadm/services/smb.rst
s/orch apply/ceph orch apply/ in a command where "ceph" was missing.
This was reported by Eugen Block to Zac Dover on 22 Oct 2024 through Slack. …
> doc/cephadm: correct "ceph orch apply" command

- src/ceph-volume/ceph_volume/api/lvm.py
- src/ceph-volume/ceph_volume/tests/api/test_lvm.py
- src/ceph-volume/ceph_volume/tests/util/test_disk.py
- src/ceph-volume/ceph_volume/util/disk.py
backport tracker: https://tracker.ceph.com/issues/68343
---
backport of https://github.com/ceph/ceph/pull/60006
parent tracker: https://tracker.ceph.com/issues/64353
> squid: ceph-volume: add new class UdevData

- src/ceph-volume/ceph_volume/devices/lvm/zap.py
backport tracker: https://tracker.ceph.com/issues/68566
---
backport of https://github.com/ceph/ceph/pull/60055
parent tracker: https://tracker.ceph.com/issues/68312
> squid: ceph-volume: drop unnecessary call to `get_single_lv()`

- src/os/bluestore/bluestore_tool.cc
It was possible to give multiple devices to cbt:
> ceph-bluestore-tool show-label --dev /dev/sda --dev /dev/sdb
But is any of devices cannot provide valid label, nothing was printed.
Now, always print results. Non readable labels are output as empty dictionaries. Exit code:
- 0 if any label properly read
- 1 if all labels failed
Fixes: https://tracker.ceph.com/issues/68505 …
> os/bluestore/ceph-bluestore-tool: Modify show-label for many devs

- src/rgw/driver/rados/rgw_lc_tier.cc
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
- src/rgw/driver/rados/rgw_sal_rados.cc
- src/rgw/rgw_lc.cc
When the bucket versioning is enabled, old plain object entry is converted to versioned by updating its instance as "null" in its raw head/old object. However its instance remains empty in the bi list entry. Same is the case for the entries created after versioning is suspended and re-enabled.
So to access such objects which are non-current, we need to set rgw_obj_key.instance as
1) "null" to read the actual raw obj and
2) empty while accessing/updating their bi entry.
Tests: https://github.com/ceph/s3-tests/pull/593/file
Fixes: https://tracker.ceph.com/issues/68402
<details> …
> rgw/lc: Fix issues with non-current objects with instance empty

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rgw_iam.py
- src/pybind/mgr/dashboard/services/service.py
**Issue 1:**
When a bucket is created with a user that is owner by the account user,
it fails to fetch the info for the bucket because the owner of that
bucket is considered as owned by the account rather than the user.
dashboard api try to fetch some info for the bucket on the basis of the
bucket owner which in this case fails since its not a real user.
To keep the existing behavior as it is and fix the current issue, I am
doing a check to make sure the user id exists or not. if it doesn't
exist, we goes on to fetch using the dashboard user.
**Issue 2**
Editing the bucket owner by the account is broken. So disabling the
ownership change for the bucket owned by account until we have user
account management for rgw in the dashboard
disabling the owner change in the form for account owned …
> mgr/dashboard: fix bucket get for s3 account owned bucket 

- doc/start/beginners-guide.rst
Add "vstart Cluster Installation and Configuration Procedure" to the Beginner's Guide. …
> doc/start: add vstart install guide

- src/test/crimson/seastar_runner.h
Ceph crimson uses seastar on debug mode which would enable ASAN, while stall-detector uses glibc backtrace function which would cause ASAN failures on aarch64.
Reason see https://github.com/scylladb/scylladb/issues/15090#issuecomment-1763355796
Because arm ci servers in lab are "elderly", causing stall happened often, this PR is to disable stall-detector until seastar upstream migrated to libunwind, see https://github.com/scylladb/seastar/issues/1878
Seastar does not provide a function to disable stall-detector, at present, increase stall-detector time to avoid stall-detector timeout on arm platform.
fixes: https://tracker.ceph.com/issues/65635
After dozen times of triggering arm make check, all crimson/seastar related tests passed. …
> test/crimson: disable stall-detector on aarch64 to fix asan failures

- doc/start/beginners-guide.rst
Add "vstart Cluster Installation and Configuration Procedure" to the Beginner's Guide.
(cherry picked from commit a42be085bd7b9159f4924853ac2b2d92c37884b0) …
> quincy: doc/start: add vstart install guide

- src/client/Client.cc
The Fc cap refs is no-zero(get_cap_ref by a previous readahead). 
Fc cap is being revoked by the mds, and in handle_cap_grant it misses to call check_caps to update cap->issued and cap->implemented
Then a new read operation comes, and in Client::get_caps the reader wants a Fc cap, it will wait for a notification after the Fc revocation finished.
So after the readahead finished, it calls put_cap_ref to released Fc cap，whilch should notify the waiting reader after check_caps
Fixes: https://tracker.ceph.com/issues/65971
Signed-off-by: Tod Chen <chentao.2022@bytedance.com>
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer …
> client: fixed a bug that read operation hung

- qa/suites/rgw/tempest/tasks/rgw_tempest.yaml
- src/common/ceph_crypto.h
- src/rgw/rgw_rest_swift.cc
- src/rgw/rgw_rest_swift.h
- src/rgw/rgw_swift_auth.cc
- src/rgw/rgw_swift_auth.h
backport tracker: https://tracker.ceph.com/issues/64277
---
backport of https://github.com/ceph/ceph/pull/47723
parent tracker: https://tracker.ceph.com/issues/56564
> reef: rgw: swift: tempurl fixes for ceph

- src/rgw/rgw_http_client.cc
backport tracker: https://tracker.ceph.com/issues/67713
---
backport of https://github.com/ceph/ceph/pull/59243
parent tracker: https://tracker.ceph.com/issues/67522
> reef: rgw/http: finish_request() after logging errors

- src/rgw/rgw_process.cc
backport tracker: https://tracker.ceph.com/issues/67921
---
backport of https://github.com/ceph/ceph/pull/59386
parent tracker: https://tracker.ceph.com/issues/48358
> reef: rgw: decrement qlen/qactive perf counters on error

- src/rgw/rgw_lc_s3.cc
backport tracker: https://tracker.ceph.com/issues/67557
---
backport of https://github.com/ceph/ceph/pull/58965
parent tracker: https://tracker.ceph.com/issues/67556
> squid: rgwlc: fix typo in getlc (ObjectSizeGreaterThan)

- doc/cephfs/troubleshooting.rst
Improve the English language in the section 'Disabling Volumes Plugin" (which here becomes "Disabling the Volumes Plugin") in the doc/cephfs/troubleshooting.rst file.
The change here is similar to a change introduced in https://github.com/ceph/ceph/pull/60448/. That PR seems to be unable to pass the "make check", and this PR is part of a test to see if breaking the changes in that PR into several smaller changes results in mergeable PRs. …
> doc/cephfs: edit "Disabling Volumes Plugin"

- src/rgw/driver/rados/rgw_notify.cc
backport tracker: https://tracker.ceph.com/issues/67558
---
backport of https://github.com/ceph/ceph/pull/59028
parent tracker: https://tracker.ceph.com/issues/67326
> squid: rgw/notify: visit() returns copy of owner string

- qa/tasks/rabbitmq.py
- src/test/rgw/bucket_notification/test_bn.py
backport tracker: https://tracker.ceph.com/issues/67609
---
backport of https://github.com/ceph/ceph/pull/59239
parent tracker: https://tracker.ceph.com/issues/67206
> squid: test/rgw/notification: use real ip address instead of localhost

- src/rgw/rgw_op.cc
- src/rgw/rgw_op.h
backport tracker: https://tracker.ceph.com/issues/67686
---
backport of https://github.com/ceph/ceph/pull/59253
parent tracker: https://tracker.ceph.com/issues/67590
> squid: rgw: load copy source bucket attrs in putobj

- src/rgw/rgw_http_client.cc
backport tracker: https://tracker.ceph.com/issues/67712
---
backport of https://github.com/ceph/ceph/pull/59243
parent tracker: https://tracker.ceph.com/issues/67522
> squid: rgw/http: finish_request() after logging errors

- src/rgw/rgw_process.cc
backport tracker: https://tracker.ceph.com/issues/67922
---
backport of https://github.com/ceph/ceph/pull/59386
parent tracker: https://tracker.ceph.com/issues/48358
> squid: rgw: decrement qlen/qactive perf counters on error

- src/librados/librados_asio.h
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
- src/rgw/driver/rados/rgw_tools.cc
- src/rgw/driver/rados/rgw_tools.h
- src/rgw/rgw_aio.cc
- src/rgw/services/svc_sys_obj_core.cc
- src/test/librados/asio.cc
backport tracker: https://tracker.ceph.com/issues/68330
---
backport of https://github.com/ceph/ceph/pull/59998
parent tracker: https://tracker.ceph.com/issues/63935
> squid: rgw/rados: don't rely on IoCtx::get_last_version() for async ops

- src/rgw/rgw_asio_frontend.cc
backport tracker: https://tracker.ceph.com/issues/67957
---
backport of https://github.com/ceph/ceph/pull/59014
parent tracker: https://tracker.ceph.com/issues/67338
> squid: rgw/beast: optimize for accept when meeting error in listenning

- src/rgw/driver/rados/rgw_notify.cc
- src/rgw/rgw_amqp.cc
- src/rgw/rgw_kafka.cc
- src/rgw/rgw_lua_background.cc
- src/rgw/rgw_ratelimit.h
backport tracker: https://tracker.ceph.com/issues/66498
---
backport of https://github.com/ceph/ceph/pull/57969
parent tracker: https://tracker.ceph.com/issues/64305
> reef: rgw: do not assert on thread name setting failures

- src/rgw/driver/rados/rgw_rados.cc
- src/test/rgw/rgw_multi/tests.py
backport tracker: https://tracker.ceph.com/issues/67026
---
backport of https://github.com/ceph/ceph/pull/58519
parent tracker: https://tracker.ceph.com/issues/66983
> reef: rgw/multisite: don't retain RGW_ATTR_OBJ_REPLICATION_TRACE attr on copy_object

- src/rgw/rgw_op.cc
- src/rgw/rgw_op.h
backport tracker: https://tracker.ceph.com/issues/67685
---
backport of https://github.com/ceph/ceph/pull/59253
parent tracker: https://tracker.ceph.com/issues/67590
> reef: rgw: load copy source bucket attrs in putobj

- qa/suites/rgw/multisite/realms/three-zones.yaml.disabled
- qa/suites/rgw/multisite/realms/two-zonegroup.yaml.disabled
- qa/suites/rgw/multisite/realms/two-zones.yaml
- qa/tasks/rgw_multisite.py
- qa/tasks/rgw_multisite_tests.py
backport tracker: https://tracker.ceph.com/issues/67882
---
backport of https://github.com/ceph/ceph/pull/59535
parent tracker: https://tracker.ceph.com/issues/67839
> squid: qa/rgw/multisite: specify realm/zonegroup/zone args for 'account create'

- src/os/bluestore/bluestore_types.h
backport tracker: https://tracker.ceph.com/issues/67135
---
backport of https://github.com/ceph/ceph/pull/56937
parent tracker: https://tracker.ceph.com/issues/65482
> reef: bluestore/bluestore_types: avoid heap-buffer-overflow in another way to keep code uniformity

- qa/tasks/cephfs/test_quota.py
- src/common/strtol.cc
- src/test/strtol.cc
ceph.quota.max_bytes accepting invalid values like TG, GT, KT and setting the values to first letter.
Fixes: https://tracker.ceph.com/issues/67169 …
> src/common : proper handling of units in `strict_iec_cast`

- qa/tasks/barbican.py
backport tracker: https://tracker.ceph.com/issues/67619
---
backport of https://github.com/ceph/ceph/pull/59241
parent tracker: https://tracker.ceph.com/issues/67444
> reef: qa: barbican: restrict python packages with upper-constraints

- doc/cephfs/client-auth.rst
- doc/cephfs/file-layouts.rst
Remind users that clients must use the 'p' flag when writing file layouts.
This PR is made in response to https://www.reddit.com/r/ceph/comments/1gbad51/comment/ltkgd5v/
<details>
- `jenkins test rook …
> doc/cephfs: Note that to set layouts or quotas, clients require the `p` flag

- doc/cephfs/client-auth.rst
- doc/cephfs/file-layouts.rst
Remind users that clients must use the 'p' flag when writing file layouts.
This PR is made in response to
https://www.reddit.com/r/ceph/comments/1gbad51/comment/ltkgd5v/
Signed-off-by: TruongSinh Tran-Nguyen <i@truongsinh.pro>
(cherry picked from commit 13c7c9d99881c7b4491ba1a693283c047161ea8a) …
> reef: doc/cephfs: use 'p' flag to set layouts or quotas

- doc/cephfs/client-auth.rst
- doc/cephfs/file-layouts.rst
Remind users that clients must use the 'p' flag when writing file layouts.
This PR is made in response to
https://www.reddit.com/r/ceph/comments/1gbad51/comment/ltkgd5v/
Signed-off-by: TruongSinh Tran-Nguyen <i@truongsinh.pro>
(cherry picked from commit 13c7c9d99881c7b4491ba1a693283c047161ea8a) …
> quincy: doc/cephfs: use 'p' flag to set layouts or quotas

- src/pybind/mgr/volumes/fs/async_job.py
Same block of code is written twice to spawn threads in async_job.py.
This has already created an inconsistency in naming of threads. Have
a single method for this and use it instead.
This allows not allows reusing code but also reduces such inconsistency. …
> mgr/vol: reuse code to spawn threads

- src/pybind/mgr/volumes/fs/async_cloner.py
- src/pybind/mgr/volumes/fs/async_job.py
- src/pybind/mgr/volumes/fs/purge_queue.py
It is a good practice and a common convention to call base class's
__init__() method at the beginning of derived class's __init__(). It
ensures proper initialization of base class's attributes and methods. …
> mgr/vol: better to call base class __init__() at beginning

- qa/cephfs/begin/3-kernel.yaml
- qa/cephfs/mount/kclient/overrides/distro/testing/k-testing.yaml
- qa/suites/fs/upgrade/featureful_client/old_client/kernel.yaml
- qa/suites/fs/upgrade/featureful_client/upgraded_client/kernel.yaml
- qa/suites/fs/upgrade/mds_upgrade_sequence/kernel.yaml
- qa/suites/fs/upgrade/nofs/kernel.yaml
- qa/suites/fs/upgrade/upgraded_client/kernel.yaml
- qa/suites/fs/workload/begin/3-kernel.yaml
Normally, the fs suite overrides the kernel branch whenever the kernel client
is used, according to the matrix of configs. This prevents easily testing a new
kernel with the -k option to teuthology-suite. So, using the base config passed
to the script, detect if an alternate testing kernel is desired and use that
instead.
The scheduler still needs to do some work:
$ teuthology-suite ... --verbose -k wip-pdonnell-i66704 --filter k-testing
...
2024-10-18 00:29:43,875.875 DEBUG:teuthology.suite.merge:base kernel {'branch': 'wip-pdonnell-i66704', 'kdb': 1, 'sha1': '745cacd8f31e50d7f3b6039bbd8c9a8dfc07bf03', 'flavor': 'default'}
2024-10-18 00:29:43,875.875 DEBUG:teuthology.suite.merge:overriding testing kernel with {'branch': 'wip-pdonnell-i66704', 'kdb': 1, 'sha1': …
> qa/cephfs: override testing kernel with -k option

- doc/cephfs/fs-volumes.rst
- doc/cephfs/troubleshooting.rst
Signed-off-by: Rishabh Dave <ridave@redhat.com>
(cherry picked from commit 373910de34fc9e1d98218aed0361cd9bf3badffa) …
> quincy: doc/cephfs: add doc for disabling mgr/volumes plugin

- doc/rados/operations/health-checks.rst
Standardize the markup around the status "clean" in the documentation so that readers don't mistakenly get the idea that inconsistent presentation of the word "clean" implies a never-stated difference between one instance and the other. …
> doc/rados: standardize markup of "clean"

- doc/cephfs/fs-volumes.rst
Improve the English language in the section 'Disabling Volumes Plugin" (which here becomes "Disabling the Volumes Plugin") in the doc/cephfs/troubleshooting.rst file.
The change here is similar to a change introduced in https://github.com/ceph/ceph/pull/60448/. That PR seems to be unable to pass the "make check", and this PR is part of a test to see if breaking the changes in that PR into several smaller changes results in mergeable PRs.
(cherry picked from commit 3e043a903ca26ce153093cbd7c498e2577c41d8a) …
> reef: doc/cephfs: edit "Disabling Volumes Plugin"

- doc/rados/operations/health-checks.rst
Standardize the markup around the status "clean" in the documentation so that readers don't mistakenly get the idea that inconsistent presentation of the word "clean" implies a never-stated difference between one instance and the other.
(cherry picked from commit c8b4155d2d27228917d4be1f11514504100c55c7) …
> squid: doc/rados: standardize markup of "clean"

- doc/rados/operations/health-checks.rst
Standardize the markup around the status "clean" in the documentation so that readers don't mistakenly get the idea that inconsistent presentation of the word "clean" implies a never-stated difference between one instance and the other.
(cherry picked from commit c8b4155d2d27228917d4be1f11514504100c55c7) …
> reef: doc/rados: standardize markup of "clean"

- doc/rados/operations/health-checks.rst
Standardize the markup around the status "clean" in the documentation so that readers don't mistakenly get the idea that inconsistent presentation of the word "clean" implies a never-stated difference between one instance and the other.
(cherry picked from commit c8b4155d2d27228917d4be1f11514504100c55c7) …
> quincy: doc/rados: standardize markup of "clean"

- src/common/options/global.yaml.in
No scrub messages should have a higher priority than client op messages. The default value should therefore be below osd_client_op_priority, which is 63.
But as a followup PR would eliminate the special queue priority for 'requested' scrub messages, the default value is set to equal osd_scrub_priority.
Backport of https://github.com/ceph/ceph/pull/59793
Original tracker: https://tracker.ceph.com/issues/68072
Backport tracker: https://tracker.ceph.com/issues/68154
(cherry picked from commit b98a46582e5e21de13e51017ea35dabdc19db71d)
> squid: osd/scrub: reduce osd_requested_scrub_priority default value

- src/common/options/osd.yaml.in
- src/osd/scrubber/osd_scrub.cc
- src/osd/scrubber/osd_scrub_sched.cc
- src/osd/scrubber/scrub_queue_entry.h
- src/osd/scrubber_common.h
The comparator used to sort the scrub targets wasn't transitive, which
can lead to undefined behavior (and likely - to a crash of the _sort_
algorithm in some implementations).  That - due to the clause comparing
the two targets of the same PG.
This commit fixes the comparator.  The sorted queue is no longer
guaranteed to have a ripe deep target before the corresponding
shallow one, which is less than optimal - but it won't crash.
Also included are minor fixes to the - now dead - code involving
overdue scrub jobs. As we no longer allow overdue targets to
ignore time/load constraints, the relevant flag is removed.
The documentation for the relevant configuration
options is fixed to reflect the change.
> osd/scrub: make sched-targets comparator transitive

- src/rgw/driver/rados/rgw_notify.cc
backport tracker: https://tracker.ceph.com/issues/67952
---
backport of https://github.com/ceph/ceph/pull/59607
parent tracker: https://tracker.ceph.com/issues/67658
> squid: rgw/notifications: free completion pointer using unique_ptr

- src/rgw/rgw_auth_keystone.cc
- src/rgw/rgw_auth_keystone.h
- src/rgw/rgw_rest_s3.cc
backport tracker: https://tracker.ceph.com/issues/64399
---
backport of https://github.com/ceph/ceph/pull/55458
parent tracker: https://tracker.ceph.com/issues/64308
> quincy: rgw/auth: ignoring signatures for HTTP OPTIONS calls

- src/mon/FSCommands.cc
Like rest of the code blocks, this code block too should be preceded by
4 spaces. It is preceded by 2 spaces right now which is incorrect. …
> mon,cephfs: fix indentation level of a code block

- src/osd/scrubber/pg_scrubber.cc
- src/osd/scrubber/pg_scrubber.h
- src/osd/scrubber_common.h
... PG log line references
When "mentioning" a PG in a log message, a set of data items is included.
That set contains some scrub related information. This commit improves the scrubber information conveyed,
as required following changes to the scrub scheduler.
> osd/scrub: improve scrub information conveyed in standard

- doc/rados/operations/erasure-code-jerasure.rst
Direct Ceph administrators using blaum_roth coding for erasure-coded pools to change the default value of w=7 to a different value in order to ensure that w+1 is prime.
This information was provided to the Ceph upstream by Benjamin Mare in September of 2024. …
> doc/rados: add blaum_roth coding guidance

- doc/rados/operations/erasure-code-jerasure.rst
Direct Ceph administrators using blaum_roth coding for erasure-coded pools to change the default value of w=7 to a different value in order to ensure that w+1 is prime.
This information was provided to the Ceph upstream by Benjamin Mare in September of 2024.
(cherry picked from commit 6648d94aed5ff5643f50fcd4f3f07d97b846e885) …
> squid: doc/rados: add blaum_roth coding guidance

- doc/rados/operations/erasure-code-jerasure.rst
Direct Ceph administrators using blaum_roth coding for erasure-coded pools to change the default value of w=7 to a different value in order to ensure that w+1 is prime.
This information was provided to the Ceph upstream by Benjamin Mare in September of 2024.
(cherry picked from commit 6648d94aed5ff5643f50fcd4f3f07d97b846e885) …
> reef: doc/rados: add blaum_roth coding guidance

- src/common/options/global.yaml.in
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/os/kstore/KStore.cc
- src/os/kstore/KStore.h
- src/os/memstore/MemStore.cc
- src/test/objectstore/store_test.cc
- src/test/objectstore/store_test_fixture.cc
- src/test/objectstore/store_test_fixture.h
Looks like death assertions aren't 100% reliable and might cause deadlock sometimes.
Hence getting rid of them and enabling optional sending exception from *Store::queue_transaction()
Parent tracker: https://tracker.ceph.com/issues/61193
Backports: https://github.com/ceph/ceph/pull/53154
Backport tracker: https://tracker.ceph.com/issues/64116
(cherry picked from commit 46f01d832487d3a3183783d41450fd8f49347097) …
> reef: test/store_test: get rid off assert_death.

- src/os/bluestore/BlueFS.cc
- src/os/bluestore/BlueFS.h
- src/os/bluestore/bluefs_types.cc
- src/os/bluestore/bluefs_types.h
- src/test/objectstore/test_bluefs.cc
backport tracker: https://tracker.ceph.com/issues/65356
--------
backport of #50216 
parent tracker: https://tracker.ceph.com/issues/58759
> reef: os/bluestore: expand BlueFS log if available space is insufficient

- src/test/lazy-omap-stats/CMakeLists.txt
- src/test/lazy-omap-stats/lazy_omap_stats_test.cc
- src/test/lazy-omap-stats/lazy_omap_stats_test.h
This test is currently plagued by
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86164 so let's move to boost::regex, at least until that bug is resolved.
Fixes: https://tracker.ceph.com/issues/59196
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>
(cherry picked from commit 0dcee433c2e62978b1281b27ad6425723d94b508)
> reef: test/lazy-omap-stats: Convert to boost::regex

- src/osd/OSD.cc
- src/osd/OSD.h
backport tracker: https://tracker.ceph.com/issues/66148
--------
backport of #56804
parent tracker: https://tracker.ceph.com/issues/64373
> reef: osd: fix for segmentation fault on OSD fast shutdown

- src/pybind/mgr/nfs/export.py
- src/pybind/mgr/nfs/utils.py
backport trackers: 
https://tracker.ceph.com/issues/66699
https://tracker.ceph.com/issues/67196
---
backport of https://github.com/ceph/ceph/pull/56876 and https://github.com/ceph/ceph/pull/58535
parent trackers: 
https://tracker.ceph.com/issues/56246
https://tracker.ceph.com/issues/66800
> reef: mgr/nfs: Don't crash ceph-mgr if NFS clusters are unavailable.

- qa/workunits/fs/snaps/snaptest-git-ceph.sh
Fixes: https://tracker.ceph.com/issues/66991
Signed-off-by: Xiubo Li <xiubli@redhat.com> …
> qa: increase the http.maxRequestBuffer to 100MB and enable the git debug logs

- .github/CODEOWNERS
While it's not perfectly correct to say the orchestration team owns src/python-common, it's closer to the truth than not. It also ensures that someone with domain specific knowledge is looking at the rest of python-common outside just the deployment section (short of creating some sort of new python-sig type group). This is relevant due to the changes in PR #60377 as python-common's ceph package will be included in cephadm.
(PS. Is there a way to avoid running jenkins jobs on a PR like this?) …
> CODEOWNERS: let orchestration cover all of python-common

- src/osd/PrimaryLogPG.cc
- src/test/librados/io_cxx.cc
- src/test/librados/test_cxx.cc
- src/test/librados/test_cxx.h
- src/test/librados/testcase_cxx.cc
- src/test/librados/testcase_cxx.h
- src/test/pybind/test_rados.py
backport tracker: https://tracker.ceph.com/issues/66137
---
backport of https://github.com/ceph/ceph/pull/55008
parent tracker: https://tracker.ceph.com/issues/53240
> reef: osd: full-object read CRC mismatch due to 'truncate' modifying oi.size w/o clearing 'data_digest'

- qa/tasks/cephfs/test_nfs.py
- src/pybind/mgr/cephadm/templates/services/nfs/ganesha.conf.j2
- src/pybind/mgr/cephadm/tests/test_services.py
- src/pybind/mgr/nfs/ganesha_conf.py
- src/pybind/mgr/nfs/tests/test_nfs.py
To allow users to use NFSv3 with cephadm deployed
nfs daemons and nfs module created exports …
> mgr/nfs: add NFSv3 protocol to default protocols

- src/osd/OSDMap.cc
backport tracker: https://tracker.ceph.com/issues/67129
---
backport of https://github.com/ceph/ceph/pull/57777
parent tracker: https://tracker.ceph.com/issues/66285
> reef: osd: bump versions of decoders for upmap-primary

- doc/rados/operations/health-checks.rst
- qa/standalone/osd/osd-rep-recov-eio.sh
- src/osd/OSD.cc
- src/osd/OSD.h
This command will allow us to clear the `OSD_TOO_MANY_REPAIRS` alert by setting the shard repair count to 0. This will help in cases where the alert was a false positive, or a condition that has since cleared at the disk level. Often, zeroing out the repair count is better than muting the alert or restarting the OSD.
Fixes: https://tracker.ceph.com/issues/54182
<details> …
> osd: add clear_shards_repaired command

- src/librados/librados_cxx.cc
i'm not sure why this compiles in the first place. but a lot of librados function definitions name the class twice
<details>
</details>
> librados: dont duplicate class names in member definitions

- src/include/uuid.h
Boost 1.86.0 includes a significant rewrite of the UUID library. The Changelog[^1] notes that:
> u.data(), where u is of type uuid, now returns a pointer to the first uint8_t of the representation (same as u.begin().) For backward compatibility, data is a function object with operator(), rather than a member function, which allows most existing uses of data as a public member to remain valid, if no longer encouraged.
I don't know enough about C++ to judge how that should have worked, but it leads to a compile error here. This patch uses BOOST_VERSION to decide whether to access .data as a member or .data() as a function.
[^1]: https://www.boost.org/doc/libs/1_86_0/libs/uuid/doc/html/uuid.html#changes …
> src/include/uuid.h: fix for boost 1.86.0

- doc/cephadm/host-management.rst
- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/tests/test_cephadm.py
- src/pybind/mgr/orchestrator/_interface.py
- src/pybind/mgr/orchestrator/module.py
The maintenance exit command now will check if the host
is offline before attempting to take it out of maintenance
mode (previously this case would cause the command to fail
and print a not very useful traceback). Additionally, if users
would like to have cephadm officially consider an offline host to
be no longer in maintenance mode this patch allows users to
pass a --offline and --force flag to do so. The expected use
case for those flags being a host that is considered to be
permanently online that users want to mark as no longer being
in maintenance mode before the host is removed from the cluster.
Additionally, if users do remove a host from the cluster that is in maintenance
mode, we will now make sure to clear the relevant health warning. …
> mgr/cephadm: offline host handling for maintenance exit command

- src/pybind/mgr/smb/handler.py
- src/pybind/mgr/smb/internal.py
First two patches are minor refactors of the existing cluster change validation. They're mostly just code moves for clarity and organization.
Then...
Prevent users from changing the cluster resource values such that a    cluster is changed from not using CTDB to using CTDB and vice versa.     This avoids complex situations that arise when making these sorts of     changes, in particular going from CTDB to non-CTDB which I am very sure     will mess up the tdb files.
Blocking these changes limits the need to test changing clustering    behavior on the fly. We can always revisit this in the future if needed.
Fixes: https://tracker.ceph.com/issues/68511
<details> …
> smb: prevent switching between clustering modes

- src/cephadm/cephadmlib/daemons/smb.py
While working on the smb.py file I began to be annoyed at the Config class and the need to repeat myself. Now that cephadm is not expected to run on python versions older than 3.7 I think it's safe to convert Config to use a dataclass.
While making the change to a dataclass I also chose to make it a frozen dataclass to help eliminate any future bugs wrt mutating the config object. …
> cephadm/smb: convert config object to use a dataclass

- src/osd/PeeringState.cc
The reverted commit unconditionally copies the Info data from the primary-info message to the replica, causing multiple tests failures.
For example:
compare the failures in
https://pulpito.ceph.com/?branch=wip-rf-store2-steps to
https://pulpito.ceph.com/?branch=wip-rf-store2-steps-reverted (with said PR reverted).
Revert "src/osd: pg stat are not synced between osds after deep-scrub. So if primary osd is killed, next primary osd has wrong stats. Reason behind it is PeeringState::proc_primary_info does not process or update any pg stats."
This reverts commit a24f3cf1e9088c30899ee6f4a8cbda6b0f350518.
Fixes: https://tracker.ceph.com/issues/68589
> osd: revert PR#57582

- src/test/rgw/bucket_notification/test_bn.py
fixing code that was done as part of this backport: https://github.com/ceph/ceph/pull/59303
<details>
</details>
> squid: test/rgw/notification: fixing backport issues in the tests

- qa/workunits/suites/fsx.sh
backport tracker: https://tracker.ceph.com/issues/68804
---
backport of https://github.com/ceph/ceph/pull/55983 and https://github.com/ceph/ceph/pull/57275
parent tracker: https://tracker.ceph.com/issues/64572
> quincy: qa/fsx: use a specified sha1 to build the xfstest-dev

- src/crimson/osd/pg.cc
Fixes: https://tracker.ceph.com/issues/68661 …
> crimson/osd/pg: make sure ops are sent to backfill targets if and only if the object has been pushed.

- src/mds/CDir.cc
All we want to know is whether we're above the `fast_limit`; if we're above that, we don't need to know how many exactly.
> mds: return as early as possible from CDir::should_split_fast()

- src/mds/MDSDaemon.cc
- src/mds/MDSDaemon.h
- src/mgr/DaemonServer.cc
- src/mgr/DaemonServer.h
- src/mon/MonClient.cc
- src/mon/Monitor.cc
- src/mon/Monitor.h
- src/msg/Dispatcher.h
- src/osd/OSD.cc
- src/osd/OSD.h
- src/test/fio/fio_ceph_messenger.cc
- src/test/msgr/perf_msgr_client.cc
- src/test/msgr/perf_msgr_server.cc
- src/test/msgr/test_msgr.cc
backport tracker: https://tracker.ceph.com/issues/67613
---
backport of https://github.com/ceph/ceph/pull/52939
parent tracker: https://tracker.ceph.com/issues/62382
> squid: mon/MonClient: handle ms_handle_fast_authentication return

- qa/tasks/mgr/dashboard/test_cephfs.py
- src/client/Client.cc
- src/pybind/mgr/dashboard/controllers/cephfs.py
backport tracker: https://tracker.ceph.com/issues/64606
---
backport of https://github.com/ceph/ceph/pull/52258
parent tracker: https://tracker.ceph.com/issues/61844
> squid: client: check mds down status before getting mds_gid_t from mdsmap

- src/kv/KeyValueDB.h
- src/kv/RocksDBStore.h
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/test/ObjectMap/KeyValueDBMemory.h
This might be helpful to troubleshoot issues with slow ops caused by bulky client transactions.
Related-to:  https://tracker.ceph.com/issues/67339 …
> os/bluestore: log txc details in slow op notification on committed_kv

- src/blk/BlockDevice.h
- src/blk/kernel/KernelDevice.cc
- src/blk/kernel/KernelDevice.h
- src/common/options/global.yaml.in
- src/os/bluestore/BlueStore.cc
1. blk: mul-thread discard support
2. NCB fix for leaked space when bdev_async_discard is enabled
3. React to bdev_enable_discard changes in handle_conf_change(); Fix several issues with stopping discard threads
backport tracker: https://tracker.ceph.com/issues/67139
backport tracker: https://tracker.ceph.com/issues/67404
---
backport of https://github.com/ceph/ceph/pull/55469, https://github.com/ceph/ceph/pull/56744, https://github.com/ceph/ceph/pull/58409
parent tracker: https://tracker.ceph.com/issues/65298, https://tracker.ceph.com/issues/66817 …
> squid: a series of optimizations for kerneldevice discard

- src/librados/IoCtxImpl.cc
backport tracker: https://tracker.ceph.com/issues/65042
---
backport of https://github.com/ceph/ceph/pull/55348
parent tracker: https://tracker.ceph.com/issues/64558
> squid: librados: use CEPH_OSD_FLAG_FULL_FORCE for IoCtxImpl::remove

- src/mon/MonCommands.h
- src/mon/OSDMonitor.cc
backport tracker: https://tracker.ceph.com/issues/67664
---
backport of https://github.com/ceph/ceph/pull/57548
parent tracker: https://tracker.ceph.com/issues/66122
> squid: mon/OSDMonitor: Add force-remove-snap mon command

- src/osd/OSD.cc
- src/osd/OSD.h
- src/osd/PG.cc
- src/osd/PG.h
- src/osd/PrimaryLogPG.cc
backport tracker: https://tracker.ceph.com/issues/65141
---
backport of https://github.com/ceph/ceph/pull/54872
parent tracker: https://tracker.ceph.com/issues/65139
> reef: osd: Change PG Deletion cost for mClock

- src/osd/OSD.cc
- src/osd/OSD.h
- src/osd/scheduler/OpScheduler.h
- src/osd/scheduler/mClockScheduler.h
- src/osd/scrubber/pg_scrubber.cc
- src/osd/scrubber/pg_scrubber.h
backport tracker: https://tracker.ceph.com/issues/66422
---
backport of https://github.com/ceph/ceph/pull/51171
parent tracker: https://tracker.ceph.com/issues/66420
> reef: osd/scrub: Change scrub cost to average object size

- qa/standalone/osd/osd-recovery-space.sh
backport tracker: https://tracker.ceph.com/issues/67351
---
backport of https://github.com/ceph/ceph/pull/57193
parent tracker: https://tracker.ceph.com/issues/44510
> reef: Test: osd-recovery-space.sh extends the wait time for "recovery toofull"

- src/blk/BlockDevice.h
- src/blk/kernel/KernelDevice.cc
- src/blk/kernel/KernelDevice.h
- src/common/options/global.yaml.in
- src/os/bluestore/BlueStore.cc
1. blk: mul-thread discard support
2. NCB fix for leaked space when bdev_async_discard is enabled
3. React to bdev_enable_discard changes in handle_conf_change(); Fix several issues with stopping discard threads
backport tracker: https://tracker.ceph.com/issues/67140
backport tracker: https://tracker.ceph.com/issues/67405
---
backport of https://github.com/ceph/ceph/pull/55469, https://github.com/ceph/ceph/pull/56744, https://github.com/ceph/ceph/pull/58409
parent tracker: https://tracker.ceph.com/issues/65298, https://tracker.ceph.com/issues/66817 …
> reef: a series of optimizations for kerneldevice discard

- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
Add slow count as below:
- l_bluestore_slow_aio_wait_count
- l_bluestore_slow_committed_kv_count
- l_bluestore_slow_read_onode_meta_count
- l_bluestore_slow_read_wait_aio_count
We can get a count while bluestore happens slowly, in some cases, this is more useful than average latency. Add it to prometheus, we can get it from the dashboard.
Signed-off-by: Yite Gu <yitegu0@gmail.com>
(cherry picked from commit 5132683228ef18d44a7a65f9b391b3f19a48e751) …
> reef: os/bluestore: add some slow count for bluestore

- src/osd/OSD.cc
backport tracker: https://tracker.ceph.com/issues/64410
---
backport of https://github.com/ceph/ceph/pull/50422
parent tracker: https://tracker.ceph.com/issues/58915
> quincy: osd: don't send stale hb msgr's addresses in MOSDBoot

- src/mon/Monitor.cc
- src/mon/MonitorDBStore.h
backport tracker: https://tracker.ceph.com/issues/65257
---
backport of https://github.com/ceph/ceph/pull/53858
parent tracker: https://tracker.ceph.com/issues/57515
> quincy: mon: add created_at and ceph_version_when_created meta

- src/mon/AuthMonitor.cc
- src/mon/AuthMonitor.h
- src/mon/KVMonitor.cc
- src/mon/OSDMonitor.cc
- src/mon/OSDMonitor.h
backport tracker: https://tracker.ceph.com/issues/65376
---
backport of https://github.com/ceph/ceph/pull/52733
parent tracker: https://tracker.ceph.com/issues/59813
> quincy: osd/OSDMonitor: check svc is writeable before changing pending

- qa/suites/upgrade/octopus-x/parallel/1-tasks.yaml
- qa/suites/upgrade/octopus-x/stress-split/1-start.yaml
- qa/suites/upgrade/pacific-x/parallel/1-tasks.yaml
- qa/suites/upgrade/pacific-x/stress-split/1-start.yaml
backport tracker: https://tracker.ceph.com/issues/67578
---
backport of https://github.com/ceph/ceph/pull/58415
parent tracker: https://tracker.ceph.com/issues/66809
> quincy: qa/suites/upgrade: ignore PG_AVAILABILITY and MON_DOWN for quincy-x and reef-x upgrade suites

- qa/valgrind.supp
backport tracker: https://tracker.ceph.com/issues/67056
---
backport of https://github.com/ceph/ceph/pull/52639
parent tracker: https://tracker.ceph.com/issues/61774
> quincy: qa: suppress Leak_StillReachable mon leak in centos 9 jobs

- qa/tasks/cephfs/test_fscrypt.py
backport tracker: https://tracker.ceph.com/issues/67806
---
backport of https://github.com/ceph/ceph/pull/59310
parent tracker: https://tracker.ceph.com/issues/67511
> squid: qa: load all dirfrags before testing altname recovery

- src/mds/MDSRankQuiesce.cc
- src/messages/MMDSQuiesceDbAck.h
- src/messages/MMDSQuiesceDbListing.h
backport tracker: https://tracker.ceph.com/issues/67745
---
backport of https://github.com/ceph/ceph/pull/59176
parent tracker: https://tracker.ceph.com/issues/67406
> squid: mds: encode quiesce payload on demand

- src/client/Client.cc
backport tracker: https://tracker.ceph.com/issues/67775
---
backport of https://github.com/ceph/ceph/pull/59300
parent tracker: https://tracker.ceph.com/issues/67565
> squid: client: calls to _ll_fh_exists() should hold client_lock

- doc/cephfs/cephfs-mirroring.rst
- qa/tasks/cephfs/test_mirroring.py
- src/tools/cephfs_mirror/PeerReplayer.cc
- src/tools/cephfs_mirror/PeerReplayer.h
backport tracker: https://tracker.ceph.com/issues/67668
---
backport of https://github.com/ceph/ceph/pull/56816
parent tracker: https://tracker.ceph.com/issues/65317
> squid: cephfs_mirror: update peer status for invalid metadata in remote snapshot

- doc/man/8/radosgw-admin.rst
- doc/radosgw/notifications.rst
also remove obsolete admin commands
Fixes: https://tracker.ceph.com/issues/68818
<details>
</details>
> doc/rgw/notification: add missing admin commands

- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/tests/test_cephadm.py
Fixes: https://tracker.ceph.com/issues/68681 
Testing logs:
```
[ceph: root@ceph-node-0 /]# ceph orch host drain 192.168.100.102
Error EINVAL: Cannot find host '192.168.100.102' in the inventory. 
[ceph: root@ceph-node-0 /]# ceph orch host drain ceph-node-3    
Error EINVAL: Cannot find host 'ceph-node-3' in the inventory. 
[ceph: root@ceph-node-0 /]# ceph orch host drain ceph-node-2
Scheduled to remove the following daemons from host 'ceph-node-2'
type                 id             
-------------------- ---------------
crash                ceph-node-2    
osd                  2              
mon                  ceph-node-2    
[ceph: root@ceph-node-0 /]#
```
```
(env) shwetabhosale:mgr$ tox -e py3.8 -- cephadm …
```
> mgr/cephadm: ceph orch host drain command to return error for invalid hostname

- ceph.spec.in
We disabled dwz in 2017, then re-enabled it in 2021. In my tests I observe dwz adding about 50% to build times in exchange for 33% space-saving. …
> ceph.spec.in: Add an option to disable dwz

- src/pybind/mgr/dashboard/ci/cephadm/bootstrap-cluster.sh
- src/pybind/mgr/dashboard/ci/cephadm/ceph_cluster.yml
- src/pybind/mgr/dashboard/ci/cephadm/dnf.conf.tpl
- src/pybind/mgr/dashboard/ci/cephadm/initial-ceph.conf
- src/pybind/mgr/dashboard/ci/cephadm/load-podman-image.sh
- src/pybind/mgr/dashboard/ci/cephadm/quick-bootstrap.sh
- src/pybind/mgr/dashboard/ci/cephadm/start-cluster.sh
I have a new script added for starting the kcli cluster called quick-bootstrap.sh
The goal is to use that script to download the ceph image on local (rather than inside vm) and then copy them over to all the vms that is being spawned by the kcli. This way all the hosts will get the ceph image which will make the deployment loads faster.
Another thing I added is to add some dnf.conf to improve parallel_downlaods and get the fastest server to install deps
eg:
```
╰─$ ./quick-bootstrap.sh -h                                                                                    255 ↵
+ set +x
Usage: ./quick-bootstrap.sh [OPTIONS]
Options:
-u, --use-cached-image     Uses the existing podman image in local. Only use this if there is such an image present.
-dir, --ceph-dir             Use this to …
```
> mgr/dashboard: improve the kcli bootstrap process

- src/ceph_fuse.cc
Show '--client_fs <fsname>' option in fuse usage
which is required to mount a specific fs in multifs cluster.
https://tracker.ceph.com/issues/67283 …
> ceph-fuse: Improve fuse mount usage message

- qa/standalone/scrub/osd-scrub-test.sh
To prevent test timeouts.
Also - remove a failing assertion on a specific 'pg query' output, as it is not central to the test.
Original tracker: https://tracker.ceph.com/issues/64346
Backport tracker: https://tracker.ceph.com/issues/68218
(cherry picked from commit 6850bce554330d09f476d4e2aa8ac6d5e3f8bf12)
> squid: qa/standalone/scrub: increase status updates frequency

- doc/rados/operations/stretch-mode.rst
- qa/suites/rados/singleton/all/stretch-mode-5-mons-8-osds.yaml
- qa/tasks/ceph_manager.py
- qa/tasks/stretch_mode_disable_enable.py
- qa/workunits/mon/mon-stretch-mode-5-mons-8-osds.sh
- src/mon/MonCommands.h
- src/mon/MonMap.cc
- src/mon/Monitor.cc
- src/mon/Monitor.h
- src/mon/MonmapMonitor.cc
- src/mon/OSDMonitor.cc
- src/mon/OSDMonitor.h
Problem:
Currently, Ceph lacks the ability
to exit stretch mode and move back
to normal cluster (non-stretched).
Solution:
Provide a command to allow
the user to exit stretch mode gracefully:
`ceph mon disable_stretch_mode <crush_rule> --yes-i-really-mean-it`
Users can either specify a crush rule that
they want all pools to move to or not specify
a rule and Ceph will use a default replicated crush rule.
Fixes: https://tracker.ceph.com/issues/67467 …
> mon [stretch mode]: support disable_stretch_mode

- qa/suites/rgw/sts/tasks/first.yaml
backport tracker: https://tracker.ceph.com/issues/63024
---
backport of https://github.com/ceph/ceph/pull/53608
parent tracker: https://tracker.ceph.com/issues/62536
> reef: qa/rgw/sts: keycloak task installs java manually

- doc/cephadm/operations.rst
Fixed typo 'no' to 'not' in sentence "If this test fails, cephadm will no be able to manage services on that host."
Signed-off-by: rhkelson <119636079+rhkelson@users.noreply.github.com> …
> doc/cephadm: Update operations.rst

- doc/rados/configuration/mclock-config-ref.rst
- qa/suites/rados/valgrind-leaks/1-start.yaml
- qa/suites/rados/verify/validater/valgrind.yaml
- src/common/options/osd.yaml.in
- src/osd/OSD.cc
The OSD's IOPS capacity is used by the mClock scheduler to determine the quantum of bandwidth allocation for the various operations on the OSD. Prior to this commit, maybe_override_max_osd_capacity_for_qos() only checked if the measured IOPS capacity exceeded the higher threshold defined by 'osd_mclock_iops_capacity_threshold_[hdd|ssd]' and if so fall back to the last valid or the default IOPS capacity as defined by osd_mclock_max_capacity_iops_[hdd|ssd].
It's quite possible that the reported IOPS is unrealistically low. This could be due to transient factors on the underlying device or it could indicate bad health of the device. Either way, the safer option would be to fall back to the last valid or the default IOPS setting for that OSD in order to avoid cluster performance (slow or …
> common,osd: Use last valid OSD IOPS value if measured IOPS is unrealistic

- qa/standalone/mon/mon-cluster-log.sh
Issue: [This test](https://github.com/ceph/ceph/blob/main/qa/standalone/mon/mon-cluster-log.sh#L145-L154) in qa/standalone/mon-cluster-log.sh was failing 
in one of the teuthology runs with the error: 
`Failed : Could not find INF log in the journalctl log file`
Cause: The test was failing as we were checking for the osd boot
log before it was actually emitted in the log file. 
Solution: We retry checking for the desired string in the log file
for a duration of 60s after OSD has come up successfully.
Fixes: https://tracker.ceph.com/issues/67282
Latest teuthology run: https://pulpito.ceph.com/shraddhaag-2024-10-10_04:16:33-rados:standalone-main-distro-default-smithi/ …
> qa/standalone/mon/mon_cluster_log.sh: retry check for log line

- qa/tasks/thrashosds-health.yaml
This integration test failed due to an "osd down" warning, but we intentionally mark OSDs down in this test, so the warning should be ignored.
Fixes: https://tracker.ceph.com/issues/67820 …
> qa/tasks: added "is down" warning to thrash-old-clients ignorelist

- doc/rados/configuration/osd-config-ref.rst
- doc/rados/operations/monitoring-osd-pg.rst
- src/common/options/osd.yaml.in
Not only in the mClock docs, but also in the reference of the options that are disabled.
Otherwise users are bound to miss it, and surprised why their options are ignored or reset.
<details>
- `jenkins …
> doc: Document which options are disabled by mClock.

- qa/suites/rados/verify/validater/valgrind.yaml
backport tracker: https://tracker.ceph.com/issues/67108
---
backport of https://github.com/ceph/ceph/pull/57485
parent tracker: https://tracker.ceph.com/issues/65768
> squid: qa/suites/rados/verify/validater: increase heartbeat grace timeout

- src/osd/scheduler/mClockScheduler.cc
- src/osd/scheduler/mClockScheduler.h
- src/test/osd/TestMClockScheduler.cc
backport tracker: https://tracker.ceph.com/issues/67355
---
backport of https://github.com/ceph/ceph/pull/58302
parent tracker: https://tracker.ceph.com/issues/66714
> squid: osd/scheduler: add mclock queue length perfcounter

- src/rgw/rgw_s3select.cc
upon a user wishes to build RGW without parquet (option is off), the parquet code-lines should be masked.   
fixes: https://tracker.ceph.com/issues/68829 …
> rgw: hiding parquet dependencies upon parquet-select option is off

- doc/cephadm/services/osd.rst
Clean the English grammar and the .RST in the section "Advanced OSD Service Specifications" in the file doc/cephadm/services/osd.rst.
(cherry picked from commit f6b56f9ee5d9f0b54dcaf1832d7a977895eb9c94) …
> quincy: doc/cephadm: clean "Adv. OSD Service Specs"

- qa/suites/fs/multiclient/clusters/1-mds-2-client.yaml
- qa/tasks/cephfs/test_misc.py
- src/mds/MDSDaemon.cc
- src/mds/MDSRank.cc
- src/mds/SessionMap.cc
backport tracker: https://tracker.ceph.com/issues/67077
---
backport of https://github.com/ceph/ceph/pull/49974
parent tracker: https://tracker.ceph.com/issues/58619
> reef: mds: fix session/client evict command.

- src/client/Client.cc
backport tracker: https://tracker.ceph.com/issues/67740
---
backport of https://github.com/ceph/ceph/pull/59162
parent tracker: https://tracker.ceph.com/issues/67491
> reef: client: Prevent race condition when printing Inode in ll_sync_inode

- qa/tasks/cephfs/caps_helper.py
The first commit on this backport PR fixes https://tracker.ceph.com/issues/65970.
And rest of the commits bring caps_helper.py in reef branch as close as
possbile to caps_helper.py in main branch, so that such bugs can be avoided
in future.
These latter backports also ensure future backports since these commits will
already be present on reef branch hereonwards.
First commit is somewhat related to #54468. …
> reef: qa/cephfs: a bug fix and few missing backport for caps_helper.py

- src/rgw/rgw_rest.cc
backport tracker: https://tracker.ceph.com/issues/67100
---
backport of https://github.com/ceph/ceph/pull/58572
parent tracker: https://tracker.ceph.com/issues/66938
> reef: [RGW] Fix the handling of HEAD requests that do not comply with RFC standards

- src/rgw/driver/rados/rgw_bucket.cc
backport tracker: https://tracker.ceph.com/issues/62748
---
backport of https://github.com/ceph/ceph/pull/53027
parent tracker: https://tracker.ceph.com/issues/62474
> reef: rgw: add versioning status during `radosgw-admin bucket stats`

- src/rgw/driver/rados/rgw_cr_rados.cc
- src/rgw/driver/rados/rgw_cr_rados.h
- src/rgw/driver/rados/rgw_data_sync.cc
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
backport tracker: https://tracker.ceph.com/issues/61436
---
backport of https://github.com/ceph/ceph/pull/50841
parent tracker: https://tracker.ceph.com/issues/59184
> reef: rgw/archive: avoid duplicating objects when syncing from multiple zones

- src/rgw/rgw_op.cc
backport tracker: https://tracker.ceph.com/issues/59607
---
backport of https://github.com/ceph/ceph/pull/49965
parent tracker: https://tracker.ceph.com/issues/58628
> reef: rgw/sts: changing identity to boost::none, when role policy

- src/rgw/rgw_file.cc
backport tracker: https://tracker.ceph.com/issues/63423
---
backport of https://github.com/ceph/ceph/pull/54309
parent tracker: https://tracker.ceph.com/issues/63409
> reef: rgwfile: fix lock_guard decl

- qa/suites/rgw/verify/tasks/cls.yaml
- qa/workunits/rgw/test_rgw_throttle.sh
- src/librados/librados_asio.h
- src/rgw/driver/rados/rgw_d3n_datacache.h
- src/rgw/driver/rados/rgw_putobj_processor.cc
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
- src/rgw/driver/rados/rgw_tools.cc
- src/rgw/driver/rados/rgw_tools.h
- src/rgw/rgw_aio.cc
- src/rgw/rgw_aio.h
- src/rgw/rgw_aio_throttle.cc
- src/rgw/rgw_aio_throttle.h
- src/rgw/rgw_d3n_cacherequest.h
- src/rgw/services/svc_sys_obj_core.cc
- src/test/librados/asio.cc
- src/test/rgw/CMakeLists.txt
- src/test/rgw/test_rgw_throttle.cc
backport tracker: https://tracker.ceph.com/issues/68331
---
backport of https://github.com/ceph/ceph/pull/59998
parent tracker: https://tracker.ceph.com/issues/63935
> reef: rgw/rados: don't rely on IoCtx::get_last_version() for async ops

- qa/tasks/vstart_runner.py
See [tracker](https://tracker.ceph.com/issues/68368) for more details. Commands issued and processed via LocalRemoteProcess in vstart_runner.py have their outputs trimmed of any non-ASCII characters. This does not seem to make sense for scenarios where non-string-based data is being processed e.g. the output from an Object Store Tool get-bytes call to an OSD.
Signed-off-by: Connor Fawcett <connorfa@uk.ibm.com>
Fixes: https://tracker.ceph.com/issues/68368 …
> qa/vstart-runner: Only remove non-ASCII characters from string-based command outputs

- doc/rados/operations/add-or-rm-osds.rst
Correct a note that directed users not to add an OSD after the cluster has reached its "full ratio". The note now says "Do not let your cluster reach its full ratio before adding an OSD."
Hat tip: Oskar Berggren
Fixes: https://tracker.ceph.com/issues/68900 …
> doc/rados: correct "full ratio" note

- src/mds/QuiesceDbEncoding.h
Fixes duplicate symbols because every source that includes this header contains a copy:
```
mold: error: duplicate symbol: lib/libceph-common.a(Message.cc.o): lib/libmds.a(MDSRankQuiesce.cc.o): encode(QuiesceDbVersion const&, ceph::buffer::v15_2_0::list&, unsigned long)
mold: error: duplicate symbol: lib/libceph-common.a(Message.cc.o): lib/libmds.a(MDSRankQuiesce.cc.o): encode(QuiesceState const&, ceph::buffer::v15_2_0::list&, unsigned long)
```
(and many more)
> mds/QuiesceDbEncoding: add `inline` to work around linker error

- src/mds/Beacon.cc
This eliminates the `wait_for()` delay and speeds up MDS shutdown.
This used to be part of https://github.com/ceph/ceph/pull/60320
> mds/Beacon: wake up the thread in shutdown()

- src/mon/MDSMonitor.cc
During shutdown, the MDS sends a `MSG_MDS_BEACON` with `MDSMap::STATE_DNE` (in `MDSDaemon::suicide()`) and then waits for a `MSG_MDS_BEACON` reply from the MON.
The MON, however, suppresses replies to `STATE_DNE`; in `MDSMonitor::preprocess_beacon()`, it returns early on `STATE_DNE` and `MDSMonitor::prepare_beacon()` silently evicts the dying MDS without any reply.
This delays the MDS shutdown until the MDS times out.
Since `MDSDaemon::suicide()` has code to wait for a beacon reply, I figure that the MON reply was suppressed accidently, therefore I suggest adding it.
This used to be part of https://github.com/ceph/ceph/pull/60320
> mon/MDSMonitor: send reply to beacons with `state=DNE`

- qa/tasks/mgr/dashboard/test_cephfs.py
- src/pybind/mgr/dashboard/controllers/cephfs.py
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/cephfs.py
Introduce rename for the cephfs REST API controller, we can rename the existing file or directory by it.
backport tracker: https://tracker.ceph.com/issues/67094
Signed-off-by: Yite Gu <yitegu0@gmail.com>
(cherry picked from commit bac2689fdd0221a9b77833f20b0c512115f9d9e5)
---
backport of https://github.com/ceph/ceph/pull/58386
parent tracker: https://tracker.ceph.com/issues/66797 …
> squid: mgr/dashboard: add cephfs rename REST API

- src/pybind/mgr/cephadm/services/ingress.py
- src/pybind/mgr/cephadm/tests/test_services.py
Backport of https://github.com/ceph/ceph/pull/57848
<details>
</details>
> squid: cephadm/services/ingress: fixed keepalived config bug

- qa/suites/upgrade/quincy-x/parallel/upgrade-sequence.yaml
- qa/suites/upgrade/quincy-x/stress-split/1-start.yaml
- qa/suites/upgrade/reef-x/parallel/upgrade-sequence.yaml
- qa/suites/upgrade/reef-x/stress-split/1-start.yaml
- qa/suites/upgrade/telemetry-upgrade/quincy-x/1-tasks.yaml
- qa/suites/upgrade/telemetry-upgrade/reef-x/1-tasks.yaml
backport tracker: https://tracker.ceph.com/issues/67462
---
backport of https://github.com/ceph/ceph/pull/58605
parent tracker: https://tracker.ceph.com/issues/65546
> squid: qa/upgrade: fix checks to make sure upgrade is still in progress

- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/ssh.py
Backport of https://github.com/ceph/ceph/pull/59610
<details>
</details>
> squid: mgr/cephadm: make ssh keepalive settings configurable

- src/cephadm/cephadm.py
backport tracker: https://tracker.ceph.com/issues/68019
---
backport of https://github.com/ceph/ceph/pull/59485
parent tracker: https://tracker.ceph.com/issues/67778
> squid: cephadm: emit warning if daemon's image is not to be used

- qa/suites/orch/cephadm/workunits/task/test_monitoring_stack_basic.yaml
backport tracker: https://tracker.ceph.com/issues/68114
---
backport of https://github.com/ceph/ceph/pull/59373
parent tracker: https://tracker.ceph.com/issues/67183
> squid: qa/task: update alertmanager endpoints version

- doc/cephadm/install.rst
- src/cephadm/cephadmlib/templates/ceph.service.j2
- src/cephadm/cephadmlib/templates/init_ctr.service.j2
- src/cephadm/cephadmlib/templates/sidecar.service.j2
- src/cephadm/tests/test_unit_file.py
backport tracker: https://tracker.ceph.com/issues/68159
---
backport of https://github.com/ceph/ceph/pull/59730
parent tracker: https://tracker.ceph.com/issues/68028
> squid: cephadm: Support Docker Live Restore

- qa/suites/orch/cephadm/workunits/task/test_iscsi_container/test_iscsi_container.yaml
- qa/workunits/cephadm/test_iscsi_setup.sh
Backport of https://github.com/ceph/ceph/pull/54334
<details>
</details>
> squid: qa/cephadm: extend iscsi teuth test

- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/orchestrator/_interface.py
- src/pybind/mgr/orchestrator/module.py
Backport of https://github.com/ceph/ceph/pull/59860 
<details>
</details>
> squid: mgr/cephadm: add --no-exception-when-missing flag to cert-store cert/key get

- src/pybind/mgr/cephadm/serve.py
backport tracker: https://tracker.ceph.com/issues/68203
---
backport of https://github.com/ceph/ceph/pull/59728
parent tracker: https://tracker.ceph.com/issues/68027
> squid: mgr/cephadm: use host address while updating rgw zone endpoints

- qa/tasks/cephfs/cephfs_test_case.py
- qa/tasks/cephfs/filesystem.py
- qa/tasks/cephfs/test_exports.py
- src/mds/Migrator.cc
- src/mds/Server.cc
- src/mds/Server.h
- src/mds/SessionMap.cc
- src/mds/SessionMap.h
The related sessions in the importer are in the importing state(`Session::is_importing` return true) when the state of importer is `acking`, `Migrator::import_reverse` called by `MDCache::handle_resolve` should reverse the process to clear the importing state if the exporter restarts at this time, but it doesn't do that actually because of its bug. And it will cause these sessions to not be cleared when the client is unmounted(evicted or timeout) until the mds is restarted.
Fixes: https://tracker.ceph.com/issues/61459
Signed-off-by: Zhansong Gao <zhsgao@hotmail.com>
- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to …
> mds: session in the importing state cannot be cleared if an export subtree task is interrupted while the state of importer is acking

- src/ceph-volume/ceph_volume/objectstore/lvmbluestore.py
`ceph.with_tpm` tag is actually a `str`, which means that `bool('0')` will return `True`.
Fixes: https://tracker.ceph.com/issues/68944
> ceph-volume: fix dmcrypt activation regression

- src/osd/scrubber/osd_scrub_sched.cc
Extend the information provided for operator dump commands, to include the basic identity and scheduling information of the entries in the scrub queue.
This change mostly benefits automatic QA and our internal testing.
> osd/scrub: list additional information when dumping the queue

- doc/rados/configuration/osd-config-ref.rst
- doc/rados/operations/monitoring-osd-pg.rst
- src/common/options/osd.yaml.in
Not only in the mClock docs, but also in the reference of the options that are disabled.
Otherwise users are bound to miss it, and surprised why their options are ignored or reset.
Signed-off-by: Niklas Hambüchen <mail@nh2.me>
(cherry picked from commit 790afd277730f24801a3b59c08d2dce0f2a9659f) …
> reef: doc: Document which options are disabled by mClock.

- doc/rados/configuration/osd-config-ref.rst
- doc/rados/operations/monitoring-osd-pg.rst
- src/common/options/osd.yaml.in
Not only in the mClock docs, but also in the reference of the options that are disabled.
Otherwise users are bound to miss it, and surprised why their options are ignored or reset.
Signed-off-by: Niklas Hambüchen <mail@nh2.me>
(cherry picked from commit 790afd277730f24801a3b59c08d2dce0f2a9659f) …
> squid: doc: Document which options are disabled by mClock.

- src/crimson/os/seastore/cache.cc
- src/crimson/os/seastore/cache.h
- src/crimson/os/seastore/random_block_manager/block_rb_manager.cc
- src/crimson/os/seastore/root_meta.h
- src/crimson/os/seastore/seastore_types.cc
- src/crimson/os/seastore/seastore_types.h
- src/crimson/os/seastore/transaction_manager.cc
- src/crimson/os/seastore/transaction_manager.h
- src/test/crimson/seastore/test_object_data_handler.cc
- src/test/crimson/seastore/test_transaction_manager.cc
During massive data backfilling, new osdmaps keep being created due to
frequent pg status changes, which can lead to frequent osd meta updates.
Those updates will be translated into "SeaStore::write_meta"s, which
modifies the root block's meta field and invalidates all inflight
transactions. Since the osd meta updates can be very frequent, long
transactions may be kept invalidated and the corresponding IO requests
hang.
This commit moves the root meta out of the root block, so that updates
to it won't invalidate irrelevant transactions …
> crimson/os/seastore: move the root meta out of the root block

- src/rgw/rgw_rest.cc
backport tracker: https://tracker.ceph.com/issues/67099
---
backport of https://github.com/ceph/ceph/pull/58572
parent tracker: https://tracker.ceph.com/issues/66938
> squid: [RGW] Fix the handling of HEAD requests that do not comply with RFC standards

- src/rgw/driver/daos/rgw_sal_daos.cc
- src/rgw/driver/daos/rgw_sal_daos.h
- src/rgw/driver/motr/rgw_sal_motr.cc
- src/rgw/driver/motr/rgw_sal_motr.h
- src/rgw/driver/posix/rgw_sal_posix.cc
- src/rgw/driver/posix/rgw_sal_posix.h
- src/rgw/driver/rados/rgw_bucket.cc
- src/rgw/driver/rados/rgw_object_expirer_core.cc
- src/rgw/driver/rados/rgw_putobj_processor.cc
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
- src/rgw/driver/rados/rgw_sal_rados.cc
- src/rgw/driver/rados/rgw_sal_rados.h
- src/rgw/rgw_op.cc
- src/rgw/rgw_sal.h
- src/rgw/rgw_sal_dbstore.cc
- src/rgw/rgw_sal_dbstore.h
- src/rgw/rgw_sal_filter.cc
- src/rgw/rgw_sal_filter.h
- src/rgw/rgw_sal_store.h
backport tracker: https://tracker.ceph.com/issues/67959
---
backport of https://github.com/ceph/ceph/pull/58082
parent tracker: https://tracker.ceph.com/issues/66516
> squid: rgw/multipart: use cls_version to avoid racing between part upload and multipart complete

- src/rgw/driver/rados/rgw_rados.cc
backport tracker: https://tracker.ceph.com/issues/68399
---
backport of https://github.com/ceph/ceph/pull/60019
parent tracker: https://tracker.ceph.com/issues/68292
> squid: rgw: decrypt multipart get part when encrypted

- src/ceph-volume/ceph_volume/objectstore/lvmbluestore.py
backport tracker: https://tracker.ceph.com/issues/68961
---
backport of https://github.com/ceph/ceph/pull/60727
parent tracker: https://tracker.ceph.com/issues/68944
> squid: ceph-volume: fix dmcrypt activation regression

- src/rgw/driver/dbstore/README.md
- src/rgw/driver/posix/README.md
Updated README for DBStore and Posix drivers to use new config option "--rgw_store" with vstart. 
<details>
</details>
> rgw: Update README for DBStore and Posix drivers

- src/rgw/rgw_pubsub.cc
- src/test/rgw/bucket_notification/test_bn.py
backport tracker: https://tracker.ceph.com/issues/67574
---
backport of https://github.com/ceph/ceph/pull/59218
parent tracker: https://tracker.ceph.com/issues/67525
> squid: rgw/notifications: fixing radosgw-admin notification json

- src/cls/user/cls_user.cc
backport tracker: https://tracker.ceph.com/issues/68425
---
backport of https://github.com/ceph/ceph/pull/59884
parent tracker: https://tracker.ceph.com/issues/51786
> squid: cls/user: reset stats only returns marker when truncated

- src/rgw/rgw_rest_pubsub.cc
This PR resolves two issues in `RGWPSListTopicsOp::execute()`:
1. **Segmentation Fault:** Resolved a segmentation fault caused by dereferencing a null bucket pointer. Updated the code to use `get_account_or_tenant(s->owner.id)` to handle the bucket owner safely and prevent crashes.
2. **Fix for Topic Listing Logic:** Fixed an issue where v2 notifications were not retrieved when v2 support was enabled. The logic now uses `get_topics_v2` when available, and falls back to `get_topics_v1` in cases v1 system or migration.
Fixes: https://tracker.ceph.com/issues/68756
<details> …
> rgw/notification: Fix segmentation fault in RGWPSListTopicsOp::execute() and correct topic listing to use get_topics_v2

- src/osd/scrubber/pg_scrubber.cc
The existing implementation of the 'schedule-deepscrub' Asok command uses the set_last_deep_scrub_stamp() method to "fake" the last-deep-scrub stamp. Unfortunately, this method also updates the last-scrub stamp (as required for non-test usage).
Commit 9f3e18b fixed the comparator used when sorting the scrub targets. An unintended side effect is that
following 'schedule-deepscrub' - the shallow target is the one to be scrubbed next, instead of the deep target.
This is fixed in the current PR.
> osd/scrub: fix 'schedule-deepscrub' test asok command

- src/crimson/osd/backfill_state.cc
Fixes: https://tracker.ceph.com/issues/68787 …
> crimson/osd/backfill_state: don't try to do object backfills when primary_bi is empty

- src/common/config_cacher.h
- src/common/options/osd.yaml.in
- src/osd/PrimaryLogPG.cc
- src/osd/scrubber/pg_scrubber.cc
- src/osd/scrubber/pg_scrubber.h
using the md_config_cacher_t, which is a cache object that registers
itself to the config observer and caches the up-to-date configuration
value.
> osd/scrub: cache frequently used configuration parameters

- qa/tasks/mgr/dashboard/test_cephfs.py
- src/pybind/mgr/dashboard/controllers/cephfs.py
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/cephfs.py
backport tracker: https://tracker.ceph.com/issues/68935
---
backport of https://github.com/ceph/ceph/pull/58386
parent tracker: https://tracker.ceph.com/issues/66797
> reef: mgr/dashboard: add cephfs rename REST API

- src/cephadm/cephadm.py
- src/cephadm/cephadmlib/call_wrappers.py
- src/cephadm/cephadmlib/daemon_identity.py
- src/cephadm/cephadmlib/daemons/ingress.py
- src/cephadm/cephadmlib/daemons/nfs.py
- src/cephadm/cephadmlib/daemons/nvmeof.py
- src/cephadm/cephadmlib/data_utils.py
- src/cephadm/cephadmlib/file_utils.py
- src/cephadm/cephadmlib/systemd.py
- src/cephadm/tests/test_agent.py
- src/cephadm/tests/test_cephadm.py
- src/cephadm/tests/test_deploy.py
- src/cephadm/tox.ini
- src/pybind/mgr/cephadm/tests/test_cephadm.py
- src/pybind/mgr/mgr_module.py
- src/python-common/CMakeLists.txt
- src/python-common/ceph/deployment/drive_group.py
- src/python-common/ceph/deployment/drive_selection/filter.py
- src/python-common/ceph/deployment/drive_selection/matchers.py
- src/python-common/ceph/deployment/drive_selection/selector.py
- src/python-common/ceph/deployment/inventory.py
- src/python-common/ceph/deployment/service_spec.py
- src/python-common/ceph/deployment/translate.py
- src/python-common/ceph/fs/earmarking.py
- src/python-common/ceph/tests/utils.py
- src/python-common/requirements-lint.txt
- src/python-common/tox.ini
The goal for this set of patches was to get all default tox envs (so `tox r`) succeeding for src/{pybind/mgr,python-common,cephadm} for python 3.12.
Most of these changes are mechanical and should be pretty obvious. None of them should change any behavior. In a couple places I took the opportunity to update the type annotations from comments to actual annotations. But in some cases I simply did `noqa` hacks if the file had lots of old style comments and/or it was a file largely unfamiliar to me.
One judgement call that I made was to not pin the flake8 version in all tox.ini files. src/pybind/mgr was alredy this way. The other two were both using old versions of flake8 that caused it to do strange things like consider backtick characters in fstrings as invalid (it was treating the entire …
> various python 3.12 fixes

- src/pybind/mgr/cephadm/inventory.py
- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/orchestrator/_interface.py
- src/pybind/mgr/orchestrator/module.py
Added fix for Modifying Profiles(add-setting and rm-setting) to allow multiple setting changes
Fix: https://tracker.ceph.com/issues/68751
```
Testing logs:
[ceph: root@ceph-node-0 ~]# ceph orch tuned-profile ls 
profile_name: 23-mon-tuned-profile
placement: ceph-node-0;ceph-node-1
settings:
vm.swappiness: 10
vm.user_reserve_kbytes: 116851
vm.numa_stat: 1
vm.page-cluster: 3
---
[ceph: root@ceph-node-0 ~]# ceph orch tuned-profile rm-settings 23-mon-tuned-profile vm.swappiness,vm.numa_stat
Removed setting ['vm.swappiness', 'vm.numa_stat'] from tuned profile 23-mon-tuned-profile
[ceph: root@ceph-node-0 ~]# ceph orch tuned-profile ls
profile_name: 23-mon-tuned-profile
placement: ceph-node-0;ceph-node-1
settings:
vm.user_reserve_kbytes: 116851
vm.page-cluster: 3
---
[ceph: root@ceph-node-0 ~]# …
```
> Added fix for Modifying Profiles(add-setting and rm-setting) to allow multiple setting changes

- src/pybind/mgr/cephadm/cert_mgr.py
- src/pybind/mgr/cephadm/services/cephadmservice.py
- src/pybind/mgr/cephadm/ssl_cert_utils.py
- src/python-common/ceph/deployment/service_spec.py
Previously the "generate_cert" field would just cause cephadm to generate self-signed certificates. This was an issue when trying to sync the secondary site in a multisite situation, resulting in
```
SL peer certificate or SSH remote key was not OK req_data->error_buf=SSL
certificate problem: self-signed certificate request failed: (2200) Unknown error 2200
```
This change makes it so the certificate are signed by cephadm's root CA cert so that users may grab that cert via
`ceph orch cert-store get cert cephadm_root_ca_cert` and set that as a trusted CA cert on their secondary cluster.
Additionally, we now generate a cert per RGW daemon so that we can include the hostname/addr of the node we are deploying the RGW daemon on in the cert. …
> mgr/cephadm: sign generated RGW certs

- src/mon/OSDMonitor.cc
backport tracker: https://tracker.ceph.com/issues/67245
---
backport of https://github.com/ceph/ceph/pull/58470
parent tracker: https://tracker.ceph.com/issues/66867
> squid: mon: Remove any pg_upmap_primary mapping during remove a pool

- doc/rados/operations/balancer.rst
- src/pybind/mgr/balancer/module.py
backport tracker: https://tracker.ceph.com/issues/68910
---
backport of https://github.com/ceph/ceph/pull/60523
parent tracker: https://tracker.ceph.com/issues/68657
> squid: mgr/balancer: optimize 'balancer status detail'

- qa/standalone/osd-backfill/osd-backfill-space.sh
qa/.../osd-backfill-space.sh: fix TEST_backfill_grow num_bytes check
Need to ignore "num_bytes mismatch" messages during throw backfill/recovery progress.
Fixes: https://tracker.ceph.com/issues/68585 …
> TEST_backfill_grow fails after finding "num_bytes mismatch" in osd log

- src/osd/scrubber/osd_scrub.cc
Headers were missing in the faulty dump output. This commit fixes the section type to 'object section'.
> osd/scrub: fixing reservations dump format

- src/mon/MonMap.cc
backport tracker: https://tracker.ceph.com/issues/68937
---
backport of https://github.com/ceph/ceph/pull/60554
parent tracker: https://tracker.ceph.com/issues/68743
> squid: Make mon addrs consistent with mon info

- src/mds/CDir.cc
fnode_t is set in the omap header during directory commit operation which isn't accounted when tracking operation size.
Could be a reason for the file system to become read-only. …
> mds: account for header size during omap commit

- src/rgw/rgw_common.cc
squid added the new `bool active` member that defaults to true, but `RGWAccessKey::decode_json()` sets it to false when `"active"` isn't present
this is an issue for multisite when a squid zone replicates user metadata from a master zone running reef
Fixes: https://tracker.ceph.com/issues/68985
<details> …
> rgw: RGWAccessKey::decode_json() preserves default value of 'active'

- doc/rados/operations/add-or-rm-osds.rst
Correct a note that directed users not to add an OSD after the cluster has reached its "full ratio". The note now says "Do not let your cluster reach its full ratio before adding an OSD."
Hat tip: Oskar Berggren
Fixes: https://tracker.ceph.com/issues/68900
Co-authored-by: Oskar Berggren <oskar.berggren@gmail.com>
(cherry picked from commit f1a2637c79a15c26a769661dd72ca68d766b2f0d)
- …
> squid: doc/rados: correct "full ratio" note

- doc/cephfs/cephfs-mirroring.rst
- qa/tasks/cephfs/test_mirroring.py
- src/pybind/mgr/mirroring/fs/snapshot_mirror.py
- src/pybind/mgr/mirroring/module.py
backport tracker: https://tracker.ceph.com/issues/68415
---
backport of https://github.com/ceph/ceph/pull/58966
parent tracker: https://tracker.ceph.com/issues/67292
> reef: cephfs_mirror: 'ceph fs snapshot mirror ls' command

- src/tools/cephfs/shell/cephfs-shell
backport tracker: https://tracker.ceph.com/issues/68593
---
backport of https://github.com/ceph/ceph/pull/55808
parent tracker: https://tracker.ceph.com/issues/63700
> reef: cephfs-shell: fixing cephfs-shell test failures

- src/mds/MDSDaemon.cc
- src/mds/MDSDaemon.h
- src/mgr/DaemonServer.cc
- src/mgr/DaemonServer.h
- src/mon/MonClient.cc
- src/mon/Monitor.cc
- src/mon/Monitor.h
- src/msg/Dispatcher.h
- src/osd/OSD.cc
- src/osd/OSD.h
- src/test/fio/fio_ceph_messenger.cc
- src/test/msgr/perf_msgr_client.cc
- src/test/msgr/perf_msgr_server.cc
- src/test/msgr/test_msgr.cc
backport tracker: https://tracker.ceph.com/issues/67477
---
backport of https://github.com/ceph/ceph/pull/52939
parent tracker: https://tracker.ceph.com/issues/62382
> reef: mon/MonClient: handle ms_handle_fast_authentication return

- src/rgw/rgw_admin.cc
- src/rgw/rgw_pubsub.cc
- src/rgw/rgw_pubsub.h
- src/rgw/rgw_rest_pubsub.cc
- src/test/rgw/bucket_notification/test_bn.py
backport tracker: https://tracker.ceph.com/issues/68984
---
backport of https://github.com/ceph/ceph/pull/60045
parent tracker: https://tracker.ceph.com/issues/68102
> squid: RGW|Bucket notification: fix for v2 topics rgw-admin list operation

- .github/workflows/stale.yml
The stale bot doesn't close certain PRs, even if they have been inactive for several years, because almost all of these PRs have a milestone
> .github/workflows: Do not exempt PRs with milestone

- qa/tasks/cephfs/test_snap_schedules.py
- src/pybind/mgr/snap_schedule/fs/schedule_client.py
backport tracker: https://tracker.ceph.com/issues/67941
---
backport of https://github.com/ceph/ceph/pull/57388
parent tracker: https://tracker.ceph.com/issues/65895
> reef: mgr/snap_schedule: correctly fetch mds_max_snaps_per_dir from mds

- qa/tasks/cephfs/test_snapshots.py
- src/mds/Server.cc
- src/mds/SessionMap.cc
backport tracker: https://tracker.ceph.com/issues/67750
---
backport of https://github.com/ceph/ceph/pull/58419
parent tracker: https://tracker.ceph.com/issues/66828
> reef: mds: cephx path restriction incorrectly rejects snapshots of deleted directory

- src/crimson/os/alienstore/alien_store.cc
- src/crimson/os/alienstore/alien_store.h
- src/crimson/os/cyanstore/cyan_store.cc
- src/crimson/os/cyanstore/cyan_store.h
- src/crimson/os/futurized_store.h
- src/crimson/os/seastore/seastore.cc
- src/crimson/os/seastore/seastore.h
- src/crimson/osd/osd.cc
- src/crimson/osd/osd.h
Implement a wrapper for different backend storage to set device_class during spawn of a process
Fixes: https://tracker.ceph.com/issues/66627 …
> crimson: Set device class during spawn of a crimson osd

- src/os/bluestore/BtreeAllocator.cc
- src/test/objectstore/Allocator_bench.cc
- src/test/objectstore/Allocator_test.cc
backport tracker: https://tracker.ceph.com/issues/62781
---
backport of https://github.com/ceph/ceph/pull/52485
parent tracker: https://tracker.ceph.com/issues/61949
> reef: os/bluestore: fix btree allocator

- doc/rados/configuration/mclock-config-ref.rst
- qa/suites/rados/valgrind-leaks/1-start.yaml
- qa/suites/rados/verify/validater/valgrind.yaml
- src/common/options/osd.yaml.in
- src/osd/OSD.cc
backport tracker: https://tracker.ceph.com/issues/68857
---
backport of https://github.com/ceph/ceph/pull/59743
parent tracker: https://tracker.ceph.com/issues/67421
> reef: common,osd: Use last valid OSD IOPS value if measured IOPS is unrealistic

- doc/cephfs/cephfs-mirroring.rst
- qa/tasks/cephfs/test_mirroring.py
- src/tools/cephfs_mirror/PeerReplayer.cc
- src/tools/cephfs_mirror/PeerReplayer.h
backport tracker: https://tracker.ceph.com/issues/67386
---
backport of https://github.com/ceph/ceph/pull/56782
parent tracker: https://tracker.ceph.com/issues/65171
> reef: cephfs_mirror: provide metrics for last successful snapshot sync

- qa/cephfs/overrides/ignorelist_health.yaml
backport tracker: https://tracker.ceph.com/issues/67121
---
backport of https://github.com/ceph/ceph/pull/58214
parent tracker: https://tracker.ceph.com/issues/66612
> reef: qa/cephfs: ignore variant of MDS_UP_LESS_THAN_MAX

- qa/tasks/cephfs/test_admin.py
- src/mds/MDBalancer.cc
- src/mds/MDBalancer.h
- src/mds/MDSDaemon.cc
- src/mds/MDSRank.cc
backport tracker: https://tracker.ceph.com/issues/57281
---
backport of https://github.com/ceph/ceph/pull/46685
parent tracker: https://tracker.ceph.com/issues/56058
> quincy: mds/MDBalancer: add an arg to limit depth when dump loads for dirfrags

- PendingReleaseNotes
- doc/mgr/restful.rst
- src/pybind/mgr/restful/module.py
backport tracker: https://tracker.ceph.com/issues/67646
---
backport of https://github.com/ceph/ceph/pull/54984
parent tracker: https://tracker.ceph.com/issues/67642
> squid: mgr/rest: Trim  requests array and limit size

- doc/rados/configuration/mclock-config-ref.rst
- qa/suites/rados/valgrind-leaks/1-start.yaml
- qa/suites/rados/verify/validater/valgrind.yaml
- src/common/options/osd.yaml.in
- src/osd/OSD.cc
backport tracker: https://tracker.ceph.com/issues/68856
---
backport of https://github.com/ceph/ceph/pull/59743
parent tracker: https://tracker.ceph.com/issues/67421
> squid: common,osd: Use last valid OSD IOPS value if measured IOPS is unrealistic

- src/blk/kernel/KernelDevice.cc
- src/blk/kernel/KernelDevice.h
backport tracker: https://tracker.ceph.com/issues/68790
---
backport of https://github.com/ceph/ceph/pull/59479
parent tracker: https://tracker.ceph.com/issues/67766
> squid: blk/KernelDevice: using join() to wait thread end is more safe

- src/pybind/mgr/cephadm/inventory.py
cephadm: Add multiple labels in single command to host
Fixes: https://tracker.ceph.com/issues/68748
Signed-off-by: Anuradha Gadge <anuradha.gadge@ibm.com> …
> cephadm: Add multiple labels in single command to host

- src/mds/Server.cc
- src/mds/Server.h
backport tracker: https://tracker.ceph.com/issues/64619
---
backport of https://github.com/ceph/ceph/pull/55207
parent tracker: https://tracker.ceph.com/issues/64061
> quincy: mds: check file layout in mknod

- PendingReleaseNotes
- doc/cephfs/add-remove-mds.rst
- doc/cephfs/administration.rst
- qa/suites/fs/functional/tasks/admin.yaml
- qa/tasks/cephfs/filesystem.py
- qa/tasks/cephfs/test_admin.py
- src/mon/FSCommands.cc
- src/mon/FSCommands.h
- src/mon/MDSMonitor.cc
- src/mon/MDSMonitor.h
- src/mon/MonCommands.h
**BACKPORTS 3 related trackes together**
* backport tracker: https://tracker.ceph.com/issues/65928
* backport of https://github.com/ceph/ceph/pull/56066
* parent tracker: https://tracker.ceph.com/issues/61866
* backport tracker https://tracker.ceph.com/issues/66199
* parent tracker https://tracker.ceph.com/issues/65864
* PR #57493
* backport tracker https://tracker.ceph.com/issues/66410
* parent tracker https://tracker.ceph.com/issues/65841
* PR #57333
---
> quincy: mon,cephfs: require confirmation flag to bring down unhealthy MDS

- src/mds/MDCache.cc
- src/mds/MDSRank.cc
backport tracker: https://tracker.ceph.com/issues/65406
---
backport of https://github.com/ceph/ceph/pull/56629
parent tracker: https://tracker.ceph.com/issues/65260
> quincy: mds: log at a lower level when stopping

- src/mds/CInode.cc
- src/mds/CInode.h
- src/mds/SnapRealm.cc
backport tracker: https://tracker.ceph.com/issues/65293
---
backport of https://github.com/ceph/ceph/pull/55768
parent tracker: https://tracker.ceph.com/issues/53192
> quincy: mds: skip sr moves when target is an unlinked dir

- PendingReleaseNotes
- doc/cephfs/mds-config-ref.rst
- qa/tasks/cephfs/test_misc.py
- src/common/options/mds.yaml.in
- src/mds/Server.cc
backport tracker: https://tracker.ceph.com/issues/65677
---
backport of https://github.com/ceph/ceph/pull/52024
parent tracker: https://tracker.ceph.com/issues/61660
> quincy: mds: fix the description for inotable testing only options

- src/mds/MDLog.cc
backport tracker: https://tracker.ceph.com/issues/64760
---
backport of https://github.com/ceph/ceph/pull/55639
parent tracker: https://tracker.ceph.com/issues/57048
> quincy: mds: relax certain asserts in mdlog replay thread

- cmake/modules/BuildISAL.cmake
- cmake/modules/BuildISALCrypto.cmake
- src/crypto/isa-l/CMakeLists.txt
- src/erasure-code/isa/CMakeLists.txt
backport tracker: https://tracker.ceph.com/issues/68379
---
backport of https://github.com/ceph/ceph/pull/59513
parent tracker: https://tracker.ceph.com/issues/67943
> reef: cmake: use ExternalProjects to build isa-l and isa-l_crypto libraries

- src/common/options/global.yaml.in
- src/osd/PeeringState.cc
backport tracker: https://tracker.ceph.com/issues/68501
---
backport of https://github.com/ceph/ceph/pull/55147
parent tracker: https://tracker.ceph.com/issues/64002
> reef: osd/PeeringState: introduce osd_skip_check_past_interval_bounds

- src/vstart.sh
when running vstart with for example EC 8+3 and one device goes bad, 
this log saves the time of manually searching which of the 11 devices disappeared. …
> vstart: log faulty physical disk device

- qa/tasks/cephfs/test_mirroring.py
- src/tools/cephfs_mirror/PeerReplayer.cc
backport tracker: https://tracker.ceph.com/issues/68409
---
backport of https://github.com/ceph/ceph/pull/56118
parent tracker: https://tracker.ceph.com/issues/64711
> reef: cephfs_mirror, qa: fix test failure test_cephfs_mirror_cancel_mirroring_and_readd

- qa/suites/rados/dashboard/tasks/e2e.yaml
backport tracker: https://tracker.ceph.com/issues/67473
---
backport of https://github.com/ceph/ceph/pull/58205
parent tracker: https://tracker.ceph.com/issues/64870
> squid: suites: test should ignore osd_down warnings

- cmake/modules/BuildISAL.cmake
- cmake/modules/BuildISALCrypto.cmake
- src/crypto/isa-l/CMakeLists.txt
- src/erasure-code/isa/CMakeLists.txt
backport tracker: https://tracker.ceph.com/issues/68378
---
backport of https://github.com/ceph/ceph/pull/59513
parent tracker: https://tracker.ceph.com/issues/67943
> squid: cmake: use ExternalProjects to build isa-l and isa-l_crypto libraries

- doc/radosgw/s3/commons.rst
Update doc/radosgw/s3/commons.rst with the changes made by Jiffin Tony Thottan in https://github.com/ceph/ceph/pull/54524 and the suggestions made in that same PR by Anthony D'Atri.
Explain how to set rgw_dns_name to a domain name in order to configure access to virtual hosted buckets. …
> doc/radosgw: update rgw_dns_name doc

- doc/radosgw/s3/commons.rst
Update doc/radosgw/s3/commons.rst with the changes made by Jiffin Tony Thottan in https://github.com/ceph/ceph/pull/54524 and the suggestions made in that same PR by Anthony D'Atri.
Explain how to set rgw_dns_name to a domain name in order to configure access to virtual hosted buckets.
(cherry picked from commit 45ff7e3365eaaa01ccb4ead71a14dd1dd9741c2f)
<details>
- `jenkins …
> quincy: doc/radosgw: update rgw_dns_name doc

- doc/cephadm/services/mgmt-gateway.rst
- doc/cephadm/services/monitoring.rst
- doc/man/8/cephadm.rst
- src/cephadm/cephadmlib/container_types.py
- src/cephadm/cephadmlib/daemons/ingress.py
- src/cephadm/cephadmlib/daemons/mgmt_gateway.py
- src/cephadm/cephadmlib/daemons/monitoring.py
- src/cephadm/cephadmlib/daemons/nvmeof.py
- src/cephadm/cephadmlib/daemons/oauth2_proxy.py
- src/cephadm/cephadmlib/daemons/smb.py
- src/cephadm/cephadmlib/daemons/snmp.py
- src/cephadm/cephadmlib/daemons/tracing.py
- src/pybind/mgr/cephadm/module.py
- src/python-common/ceph/cephadm/images.py
cephadm: Modify the structure of the default container images
Fixes: https://tracker.ceph.com/issues/68605
<details> …
> cephadm: Modify the structure of the default container images

- src/rgw/driver/rados/rgw_data_sync.cc
Pass the requested gen than the bucket_status.incremental_gen to RGWSyncBucketShardCR as the old gen (bucket_status.incremental_gen) is stored in the error repo and will retried later.
Fixes: https://tracker.ceph.com/issues/68805
> rgw/multisite: revert "rgw/multisite: avoid redundant error repo entry logging

- src/rgw/rgw_op.cc
- src/rgw/rgw_sal.h
When creating a bucket from a secondary zonegroup and forwarding the request to the master zonegroup
(i.e., when `bucket_zonegroup != &my_zonegroup`), the `createparams.zone_placement` may remain uninitialized. This can lead to garbage values and result in a segmentation fault due to invalid memory access.
By explicitly initializing `zone_placement` to `nullptr`, we can eliminate this issue in cases where zone_placement is referenced like `init_default_bucket_layout`.
Fixes: https://tracker.ceph.com/issues/68500
> rgw: initialize createparams zone_placement to avoid garbage value

- src/rgw/rgw_rest.cc
The input can be logged at level 20 rather than zero.
Fixes: https://tracker.ceph.com/issues/69093
> rgw: relax RGWPutACLs_ObjStore::get_params read data log

- src/rgw/rgw_lc.cc
Fixes: https://tracker.ceph.com/issues/65772
> rgw/lc: Fix lifecycle not working while bucket versioning is suspended

- qa/valgrind.supp
backport tracker: https://tracker.ceph.com/issues/67054
---
backport of https://github.com/ceph/ceph/pull/52639
parent tracker: https://tracker.ceph.com/issues/61774
> reef: qa: suppress Leak_StillReachable mon leak in centos 9 jobs

- qa/suites/rados/verify/validater/valgrind.yaml
backport tracker: https://tracker.ceph.com/issues/67109
---
backport of https://github.com/ceph/ceph/pull/57485
parent tracker: https://tracker.ceph.com/issues/65768
> reef: qa/suites/rados/verify/validater: increase heartbeat grace timeout

- src/osd/scheduler/mClockScheduler.cc
- src/osd/scheduler/mClockScheduler.h
- src/test/osd/TestMClockScheduler.cc
backport tracker: https://tracker.ceph.com/issues/67357
---
backport of https://github.com/ceph/ceph/pull/58302
parent tracker: https://tracker.ceph.com/issues/66714
> reef: osd/scheduler: add mclock queue length perfcounter

- src/json_spirit/CMakeLists.txt
This library is built with `BOOST_SPIRIT_THREADSAFE` and thus it requires linking with Boost::thread.
This mistake usually had no effect because other build targets had this dependency already, but this is fragile and depends on the linker command parameter order.
> json_spirit: add missing dependency on Boost::thread

- src/osd/scrubber/scrub_job.cc
This commit removes the unused add_double function which was giving a compiler warning.
Fixes: https://tracker.ceph.com/issues/68009 …
> osd/scrubber: Clean up unused function add_double

- src/mon/Monitor.cc
- src/mon/Monitor.h
If mon store.db very big, scrub will be a very
time-consuming operation.
Fixes: https://tracker.ceph.com/issues/66873 …
> mon/scrub: add mon scrub latency

- doc/rados/operations/health-checks.rst
> doc/rados: fix sentences in health-checks (2 of x)

- src/test/rgw/test-rgw-common.sh
- src/test/rgw/test-rgw-multisite.sh
the script can now be used to create multiple zonegroups.
`MON=1 OSD=1 MGR=0 MDS=0 src/test/rgw/test-rgw-multisite.sh <num_zones> <num_zonegroups>`
creates `num_zonegroups` with `num_zones` in each zonegroup. 
for example, `MON=1 OSD=1 MGR=0 MDS=0 src/test/rgw/test-rgw-multisite.sh 2 2`
for default configuration with just one zonegroup use:
`MON=1 OSD=1 MGR=0 MDS=0 src/test/rgw/test-rgw-multisite.sh <num_zones> 1`
- When filling …
> rgw/multisite: test-rgw-multisite.sh can create multiple zonegroups

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-bucket.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
- src/pybind/mgr/dashboard/services/cluster.py
Till now we are calculating the total number of objects and the average object size in the RGW Overview Page using `ceph df` command's output. As per the discussion with RGW team, this data is not correct as S3 objects in rgw can occupy more than one rados object. This PR tends to make the overview page's info in sync with the RGW bucket page's info by using s3 api's buckets related data.
Also fixes the issue where For a version enabled bucket every single new object upload, object count got doubled in overview page.
Fixes: https://tracker.ceph.com/issues/68733
https://github.com/user-attachments/assets/ceca26fa-b121-40ad-a9a4-2f398c4ca335 …
> mgr/dashboard: fix total objects/Avg object size in RGW Overview Page

- doc/rados/operations/health-checks.rst
Note to (I hope soon) future Zac: There are a a couple of places near the end of this file where the sentences are ungrammatical. Update these in a separate PR (in isolation, so that the grammar and technical accuracy of these sentences can be the primary focus of the reviewers). …
> doc/rados: fix sentences in health-checks (3 of x)

- doc/dev/development-workflow.rst
Update the link to the backporter manual, in
doc/dev/development-workflow.rst. Laura Flores requested this change on 04 Dec 2024. …
> doc/dev: update link to backporter manual

- doc/rados/operations/health-checks.rst
Note to (I hope soon) future Zac: There are a a couple of places near the end of this file where the sentences are ungrammatical. Update these in a separate PR (in isolation, so that the grammar and technical accuracy of these sentences can be the primary focus of the reviewers).
(cherry picked from commit 97df4479d90b7f1b659b71ac172ff1094d58a50e) …
> squid: doc/rados: fix sentences in health-checks (3 of x)

- doc/rados/operations/health-checks.rst
Note to (I hope soon) future Zac: There are a a couple of places near the end of this file where the sentences are ungrammatical. Update these in a separate PR (in isolation, so that the grammar and technical accuracy of these sentences can be the primary focus of the reviewers).
(cherry picked from commit 97df4479d90b7f1b659b71ac172ff1094d58a50e) …
> reef: doc/rados: fix sentences in health-checks (3 of x)

- doc/rados/operations/health-checks.rst
Note to (I hope soon) future Zac: There are a a couple of places near the end of this file where the sentences are ungrammatical. Update these in a separate PR (in isolation, so that the grammar and technical accuracy of these sentences can be the primary focus of the reviewers).
(cherry picked from commit 97df4479d90b7f1b659b71ac172ff1094d58a50e) …
> quincy: doc/rados: fix sentences in health-checks (3 of x)

- src/crimson/osd/ops_executer.h
I encountered the following issue when running vstart.sh
/home/mwoh/ceph_mount/ceph/ceph/src/crimson/osd/ops_executer.h:526:27: runtime error: member access within null pointer of type 'struct CloningContext'
Segmentation fault on shard 0.
Backtrace:
It seems the conditional operator isn't working as intended due to gcc bug. I’ve confirmed that this commit resolves the issue. …
> crimson/osd/ops_executer: prevent access to null pointers caused by gcc bug

- src/cls/rbd/cls_rbd_client.cc
- src/test/cls_rbd/test_cls_rbd.cc
The rbd-mirror image map is stored in the rbd_mirror_leader object. Fixed mirror_image_map_list() to operate on the correct object.
Fixes: [69112](https://tracker.ceph.com/issues/69112) …
> cls/rbd: fix mirror_image_map_list object

- src/msg/async/AsyncMessenger.cc
backport tracker: https://tracker.ceph.com/issues/68665
---
backport of https://github.com/ceph/ceph/pull/57951
parent tracker: https://tracker.ceph.com/issues/66231
> squid: AsyncMessenger: Don't decrease l_msgr_active_connections if it is negative

- container/Containerfile
- container/build.sh
- container/make-manifest-list.py
backport tracker: https://tracker.ceph.com/issues/69119
---
backport of https://github.com/ceph/ceph/pull/60755
parent tracker: https://tracker.ceph.com/issues/69116
> squid: Modify container/ software to support release containers and the promotion of prerelease containers

- container/Containerfile
- container/build.sh
- container/make-manifest-list.py
backport tracker: https://tracker.ceph.com/issues/69118
---
backport of https://github.com/ceph/ceph/pull/60755
parent tracker: https://tracker.ceph.com/issues/69116
> reef: Modify container/ software to support release containers and the promotion of prerelease containers

- container/Containerfile
- container/build.sh
- container/make-manifest-list.py
backport tracker: https://tracker.ceph.com/issues/69117
---
backport of https://github.com/ceph/ceph/pull/60755
parent tracker: https://tracker.ceph.com/issues/69116
> quincy: Modify container/ software to support release containers and the promotion of prerelease containers

- src/test/rgw/rgw_multi/tests.py
several tests were calling create_bucket_per_zone_in_realm() then operating on the buckets without a meta checkpoint
add a checkpoint so that metadata sync of the bucket creation doesn't race to undo those operations
Fixes: https://tracker.ceph.com/issues/68396
<details>
</details>
> test/rgw/multisite: add meta checkpoint after bucket creation

- qa/tasks/radosgw_admin.py
- src/rgw/driver/rados/rgw_bucket.cc
- src/rgw/driver/rados/rgw_bucket.h
- src/rgw/driver/rados/rgw_rest_bucket.cc
buckets are owned by accounts instead of their individual users
add support for --account-id to 'bucket link' and 'bucket unlink'
reject 'bucket link' when the requested --uid belongs to an account
Fixes: https://tracker.ceph.com/issues/69042
<details>
</details>
> radosgw-admin: bucket link/unlink support accounts

- PendingReleaseNotes
- doc/mgr/nfs.rst
- qa/tasks/cephfs/test_nfs.py
- src/pybind/mgr/nfs/export.py
- src/pybind/mgr/nfs/ganesha_conf.py
- src/pybind/mgr/nfs/module.py
- src/pybind/mgr/nfs/tests/test_nfs.py
backport tracker: https://tracker.ceph.com/issues/68166
---
backport of https://github.com/ceph/ceph/pull/54277
parent tracker: https://tracker.ceph.com/issues/68165
> squid: mgr/nfs: generate user_id & access_key for apply_export(CephFS)

- src/test/common/test_time.cc
> test/common/test_time: add missing `using ceph::mono_clock`

- src/common/Formatter.cc
- src/common/Formatter.h
- src/test/common/test_json_formatter.cc
backport tracker: https://tracker.ceph.com/issues/68324
--------
backport of #58598
parent tracker: https://tracker.ceph.com/issues/66215
> reef: common/Formatter: dump inf/nan as null

- qa/suites/rados/singleton/all/stretch-mode-5-mons-8-osds.yaml
- qa/workunits/mon/mon-stretch-mode-5-mons-8-osds.sh
The election strategy is randomly chosen for this type of test. Sometimes, the test passes if the "connectivity" election strategy happens to be picked. But if a different strategy, i.e. "classic", is picked, then the test will fail.
We can ensure that the election strategy is "connectivity" by setting it in the workunit with the ceph CLI command. Although connectivity was specified in `stretch-mode-5-mons-8-osds.yaml`, that config ultimately gets overridden by the "qa/mon_config" yaml.
Fixes: https://tracker.ceph.com/issues/69107 …
> qa/workunits/mon: ensure election strategy is "connectivity" for stretch mode

- src/common/sstring.hh
- src/tools/ceph-dencoder/sstring.h
This fixes a build failure with libc++ (clang/LLVM).  This build failure is correct: there exists no specialization for `std::char_traits<unsigned char>`.  The standards-compliant way to use unsigned chars in strings is to use `char8_t`.
> tools/ceph-dencoder/sstring.h: use `char8_t` instead of `unsigned char`

- src/mon/MonMap.cc
backport tracker: https://tracker.ceph.com/issues/68938
---
backport of https://github.com/ceph/ceph/pull/60554
parent tracker: https://tracker.ceph.com/issues/68743
> reef: Make mon addrs consistent with mon info

- qa/suites/rgw/crypt/2-kms/barbican.yaml
- qa/suites/rgw/tempest/0-install.yaml
the openstack branches that the rgw suite depends on disappeared again:
> Remote branch stable/2023.1 not found in upstream origin
Fixes: https://tracker.ceph.com/issues/69134
<details>
</details>
> qa/rgw: bump keystone/barbican from 2023.1 to 2024.1

- src/pybind/mgr/dashboard/plugins/feature_toggles.py
- src/pybind/mgr/mgr_util.py
would be helpful if we want to notify user about certain issues when enabling something.
```
[root@ceph ceph]# ceph dashboard feature enable iscsi
WARNING: iscsi warning message
Feature 'iscsi': enabled
```
also I saw the permission and feature toggle is not applied in nvmeof navigation. …
> mgr/dashboard: add a custom warning message when enabling feature

- qa/tasks/s3tests_java.py
During testing sets JAVA_HOME to refer to the java interpreter for Java 8, so there aren't any issues with gradle.
Fixes: https://tracker.ceph.com/issues/69204 …
> qa/rgw: fix s3 java tests by forcing gradle to run on Java 8

- src/rgw/driver/rados/rgw_rados.cc
When listing a bucket and the parameters are such that we're not listing namespaced entries, this commit adds an optimization to advance the marker such that we skip past a whole region of namespaced entries rather than evaluating each entry one-by-one.
Fixes: https://tracker.ceph.com/issues/69063 …
> rgw: optimize bucket listing to skip past regions of namespaced entries

- doc/cephfs/mount-using-kernel-driver.rst
Edit the first third of doc/cephfs/mount-using-kernel-driver.rst in preparation for correcting mount commands that may not work in Reef as described in this documentation. …
> doc/cephfs: edit first 3rd of mount-using-kernel-driver

- src/rgw/driver/rados/rgw_putobj_processor.cc
- src/rgw/driver/rados/rgw_rados.cc
rgw: fix data corruption when rados op return ETIMEDOUT
when rados op return ETIMEOUT, rgw can't determine whether or not the rados op succeeded, To avoid data corruption, when return -ETIMEDOUT, we should clear all objects in RadosWriter
Signed-off-by: Shasha Lu <lu.shasha@aishu.cn> …
> rgw: fix data corruption when rados op return ETIMEDOUT

- doc/cephfs/mount-using-kernel-driver.rst
Edit the second third of doc/cephfs/mount-using-kernel-driver.rst in preparation for correcting mount commands that may not work in Reef as described in this documentation. …
> doc/cephfs: edit 2nd 3rd of mount-using-kernel-driver

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-migrate/rgw-multisite-migrate.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-migrate/rgw-multisite-migrate.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
- src/pybind/mgr/dashboard/services/rgw_client.py
1. Automate the process of replication user creation during single site to multi-site migration
2. Provide a support for automatic restart post creation of default realm/zone group/zone as a part of multisite migrate
Fixes: https://tracker.ceph.com/issues/69052
https://github.com/user-attachments/assets/be7b9256-db32-402a-b830-2541cda73083 …
> mgr/dashboard: Automate system user creation and restart of rgw daemons on Migrate to Multisite

- doc/dev/development-workflow.rst
Add a note to doc/dec/development-workflow.rst that instructs developers to do their own backports. This change was requested by Laura Flores on 04 Dec 2024.
(cherry picked from commit 5d584b4badb606d372c266424f59076408f62f40) …
> quincy: doc/dev: instruct devs to backport

- doc/dev/development-workflow.rst
Add a note to doc/dec/development-workflow.rst that instructs developers to do their own backports. This change was requested by Laura Flores on 04 Dec 2024.
(cherry picked from commit 5d584b4badb606d372c266424f59076408f62f40) …
> reef: doc/dev: instruct devs to backport

- qa/suites/upgrade/quincy-x/filestore-remove-check/1-ceph-install/quincy.yaml
- qa/suites/upgrade/quincy-x/parallel/0-start.yaml
- qa/suites/upgrade/quincy-x/stress-split/1-start.yaml
backport tracker: https://tracker.ceph.com/issues/67138
---
backport of https://github.com/ceph/ceph/pull/58277
parent tracker: https://tracker.ceph.com/issues/65422
> squid: suites/upgrade/quincy-x: update the ignore list

- ceph.spec.in
- debian/.gitignore
- debian/control
- debian/libcephfs-daemon.install
- debian/libcephfs-dev.install
- debian/libcephfs-proxy2.install
- debian/rules
- doc/dev/libcephfs_proxy.rst
- src/CMakeLists.txt
- src/libcephfs_proxy/CMakeLists.txt
- src/libcephfs_proxy/libcephfs_proxy.c
- src/libcephfs_proxy/libcephfsd.c
- src/libcephfs_proxy/proxy.h
- src/libcephfs_proxy/proxy_helpers.c
- src/libcephfs_proxy/proxy_helpers.h
- src/libcephfs_proxy/proxy_link.c
- src/libcephfs_proxy/proxy_link.h
- src/libcephfs_proxy/proxy_list.h
- src/libcephfs_proxy/proxy_log.c
- src/libcephfs_proxy/proxy_log.h
- src/libcephfs_proxy/proxy_manager.c
- src/libcephfs_proxy/proxy_manager.h
- src/libcephfs_proxy/proxy_mount.c
- src/libcephfs_proxy/proxy_mount.h
- src/libcephfs_proxy/proxy_requests.h
The libcephfs proxy is composed by a new daemon process (libcephfsd) and a new library (libcephfs_proxy.so) that allow client applications to work without directly connecting to the libcephfs.so library.
The libcephfs_proxy.so library exports binary compatible versions of the libcephfs.so functions. These functions forward the application requests to the libcephfsd daemon running on the same machine through a UNIX socket. The daemon, which is linked to the real libcephfs.so library, executes the incoming requests and sends back the answers.
The client application doesn't need to be modified to use the proxy. It just needs to link against libcephfs_proxy.so instead of libcephfs.so, or even use LD_PRELOAD when executing it.
The main advantage of using the proxy is that all ceph mounts are …
> Initial version of the libcephfs proxy

- doc/cephfs/mount-using-kernel-driver.rst
Edit the third third of doc/cephfs/mount-using-kernel-driver.rst in preparation for correcting mount commands that may not work in Reef as described in this documentation.
This PR follows the following two PRs:
https://github.com/ceph/ceph/pull/61048 - 1st 3rd
https://github.com/ceph/ceph/pull/61049 - 2nd 3rd …
> doc/cephfs: edit 3rd 3rd of mount-using-kernel-driver

- qa/suites/rados/objectstore/backends/ceph_test_bluefs.yaml
- src/test/CMakeLists.txt
- src/test/objectstore/CMakeLists.txt
- src/test/objectstore/test_bluefs.cc
The idea of this PR is to make it more lightweight for jenkins to run "very_large_write" tests.
Jenkins runner often crashes doing it.
It turned out that unittest_bluefs was clone into ceph_test_bluefs
1) unittest_bluefs is run on jenkins, with exclusion of "very_large_write" tests.
2) ceph_test_bluefs is now part of packaging and gets into builds. This one is run on teuthology, including "very_large_write" tests.
- When filling …
> os/bluestore: Make some unittest_bluefs runs lighter on jenkins

- doc/cephfs/mount-using-kernel-driver.rst
Edit the third third of doc/cephfs/mount-using-kernel-driver.rst in preparation for correcting mount commands that may not work in Reef as described in this documentation.
This PR follows the following two PRs:
https://github.com/ceph/ceph/pull/61048 - 1st 3rd
https://github.com/ceph/ceph/pull/61049 - 2nd 3rd
(cherry picked from commit 9c7580a2935511d009c9e66885e76635aa504ee8) …
> quincy: doc/cephfs: edit 3rd 3rd of mount-using-kernel-driver

- doc/cephfs/mount-using-kernel-driver.rst
Edit the third third of doc/cephfs/mount-using-kernel-driver.rst in preparation for correcting mount commands that may not work in Reef as described in this documentation.
This PR follows the following two PRs:
https://github.com/ceph/ceph/pull/61048 - 1st 3rd
https://github.com/ceph/ceph/pull/61049 - 2nd 3rd
(cherry picked from commit 9c7580a2935511d009c9e66885e76635aa504ee8) …
> reef: doc/cephfs: edit 3rd 3rd of mount-using-kernel-driver

- doc/cephfs/mount-using-kernel-driver.rst
Edit the third third of doc/cephfs/mount-using-kernel-driver.rst in preparation for correcting mount commands that may not work in Reef as described in this documentation.
This PR follows the following two PRs:
https://github.com/ceph/ceph/pull/61048 - 1st 3rd
https://github.com/ceph/ceph/pull/61049 - 2nd 3rd
(cherry picked from commit 9c7580a2935511d009c9e66885e76635aa504ee8) …
> squid: doc/cephfs: edit 3rd 3rd of mount-using-kernel-driver

- qa/tasks/mgr/dashboard/test_rgw.py
- src/pybind/mgr/dashboard/controllers/rgw.py
Subusers couldn't be created through the dashboard, because the get call was overwritten with Python magic due to it being the function under the HTTP call. The get function was therefore split into an "external" and "internal" function, whereas one can be used by functions without triggering the magic. Since the user object was then returned correctly, json.loads could be removed.
Also thanks to @aaSharma14
<details>
- …
> mgr: fix subuser creation via dashboard

- monitoring/ceph-mixin/dashboards/rgw.libsonnet
- monitoring/ceph-mixin/dashboards_out/radosgw-overview.json
- monitoring/ceph-mixin/tests_dashboards/features/radosgw_overview.feature
Currently rgw_servers filtering is not working in RGW Overview garfana graphs. It is showing data of all the RGW services, even though filter set to single service. This PR intends to solve this issue
Fixes: https://tracker.ceph.com/issues/69074
https://github.com/user-attachments/assets/6d7efb77-996d-4e2f-8732-090dd4625942 …
> mgr/dashboard: Add ceph_daemon filter to rgw overview grafana panel queries

- qa/suites/rgw/notifications/tasks/kafka/test_kafka.yaml
- qa/tasks/kafka.py
- qa/tasks/s3a_hadoop.py
Currently maven and kafka are pulled from archive.apache.org. This uses Apache's "closer" calculator to find a mirror to use instead.
Fixes: https://tracker.ceph.com/issues/69235 …
> qa/rgw: pull Apache artifacts from mirror instead of archive.apache.org

- src/rgw/rgw_sal_dbstore.h
This commit refactors the 'DBZone' class to utilize 'std::unique_ptr' instead of raw pointers and manual memory management with 'new' and 'delete'.
Fixes: https://tracker.ceph.com/issues/57501
<details>
- …
> rgw/dbstore: Cleanup - use unique_ptr instead of new/delete in DBZone

- src/rgw/rgw_asio_frontend.cc
Fixes: https://tracker.ceph.com/issues/68352
continuing the work https://github.com/ceph/ceph/pull/57659#issuecomment-2388021917
below are screen recordings with this PR of realm-reloads and
`rgw_graceful_stop=[false/true]` 
on left side of the split terminal is the realm reload operation triggered by:
```
sudo ./bin/radosgw-admin zonegroup modify --rgw-zonegroup=us --[enable/disable]-feature=resharding | jq
sudo ./bin/radosgw-admin period update --rgw-realm=gold --commit | jq
```
executed while an `s3cmd put` of an 4GB objects is performed in the right terminal
1. `rgw_graceful_stop=false` note that the `s3cmd` transfer is interrupted as it would be before this PR:
2. `rgw_graceful_stop=true` note that the `s3cmd` transfer is NOT interrupted: …
> rgw: respect rgw_graceful_stop on realm reload

- src/rgw/rgw_bucket_layout.cc
f19347d43b7cd4bb1e009e66305f6e736c4c5d89 has broken the bucket layout JSON output by printing `judge_reshard_lock_time` inside the logs array.
Fixes: https://tracker.ceph.com/issues/68726
> rgw: fix json output for bucket layout

- src/common/Formatter.cc
- src/common/HTMLFormatter.cc
- src/test/common/CMakeLists.txt
- src/test/common/test_htmlformatter.cc
- src/test/common/test_json_formatter.cc
- src/test/common/test_tableformatter.cc
- src/test/common/test_xmlformatter.cc
The length of buf in Formatter is 1024. If the output was truncated due to size limit, then the return value is the number of characters (excluding the terminating null byte) which would have been written to the final string if enough space had been available. So XMLFormatter::dump_format_va will create a string_view that out of bounds of buf.
https://tracker.ceph.com/issues/68658 …
> <common> fix formatter buffer out-of-bounds

- doc/dev/crimson/pipeline.rst
- src/common/intrusive_lru.h
- src/crimson/osd/object_context.h
- src/crimson/osd/object_context_loader.cc
- src/crimson/osd/object_context_loader.h
- src/crimson/osd/ops_executer.cc
- src/crimson/osd/ops_executer.h
- src/crimson/osd/osd_operation.h
- src/crimson/osd/osd_operation_external_tracking.h
- src/crimson/osd/osd_operations/client_request.cc
- src/crimson/osd/osd_operations/client_request.h
- src/crimson/osd/osd_operations/internal_client_request.cc
- src/crimson/osd/osd_operations/internal_client_request.h
- src/crimson/osd/osd_operations/logmissing_request.cc
- src/crimson/osd/osd_operations/logmissing_request.h
- src/crimson/osd/osd_operations/logmissing_request_reply.cc
- src/crimson/osd/osd_operations/logmissing_request_reply.h
- src/crimson/osd/osd_operations/replicated_request.cc
- src/crimson/osd/osd_operations/replicated_request.h
- src/crimson/osd/osd_operations/snaptrim_event.cc
- src/crimson/osd/osd_operations/snaptrim_event.h
- src/crimson/osd/pg.cc
- src/crimson/osd/pg.h
- src/crimson/osd/pg_backend.cc
- src/crimson/osd/pg_backend.h
- src/test/common/test_intrusive_lru.cc
This PR reworks the client IO pipeline to allow one request per object to be processed concurrently.  Writes still need to serialize at submission time.
For random reads with high concurrency, this seems to be good for a ~8-10% throughput increase on a single OSD with seastore in my environment.  Further refinement may well improve things further, but this branch has gotten large as is.
Teuthology run looks good, all tests passed: https://pulpito.ceph.com/sjust-2024-12-06_21:24:24-crimson-rados-wip-sjust-crimson-testing-2024-12-06-distro-default-smithi/
<details>
- …
> crimson: rework request pipeline to allow for per-object processing

- src/test/cls_log/test_cls_log.cc
This line in the unit test get flagged by -Werror which is enabled by default when compiling the unit tests in a container based environment. Examining the code the warning appears correct and it should be enough to just remove this variable. …
> test/cls_log: remove unused variable

- src/pybind/mgr/cephadm/services/nvmeof.py
- src/python-common/ceph/deployment/service_spec.py
Added gateway and discovery address maps to the service specification. These maps store per-node service addresses. The address is first searched in the map, then in the spec address configuration. If neither is defined, the host IP is used as a fallback. …
> cephadm/nvmeof: support per-node gateway addresses

- ceph.spec.in
- debian/libcephfs-dev.install
- src/CMakeLists.txt
- src/cephfs.pc.in
It is a common practice to include a pkgconfig file for a library when installed on a system to contain necessary information for that library to be compiled against other programs. These files typically include entries like name, version, description, location of header files, dependent libraries, compilation flags and so on. Utilities like `pkg-config`, `pkgconf`, `autoconf` or even CMake can query those details to compile and link against such libraries.
Here we attempt to introduce a pkgconfig file for libcephfs.
ref: https://people.freedesktop.org/~dbn/pkg-config-guide.html
> cephfs: Add pkgconfig file for libcephfs

- src/pybind/mgr/dashboard/controllers/pool.py
backport tracker: https://tracker.ceph.com/issues/69201
---
backport of https://github.com/ceph/ceph/pull/56006
parent tracker: https://tracker.ceph.com/issues/64724
> squid: mgr/dashboard: handle infinite values for pools

- qa/tasks/mgr/dashboard/test_rbd.py
- src/pybind/mgr/dashboard/controllers/cluster_configuration.py
- src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/configuration.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/configuration.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration-form/configuration-form-create-request.model.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration-form/configuration-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration-form/configuration-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/config-option/config-option.model.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/critical-confirmation-modal/critical-confirmation-modal.component.html
- src/pybind/mgr/dashboard/openapi.yaml
Fixes: https://tracker.ceph.com/issues/68976
Signed-off-by: Naman Munet <namanmunet@li-ff83bccc-26af-11b2-a85c-a4b04bfb1003.ibm.com>
**Previously**: users are not able to edit the configuration which have the 'can_update_at_runtime' flag as false.
**Now**: 
1) Users will be able to edit the configuration related with 'rgw' by forcefully editing the configuration if the 'can_update_at_runtime' flag is false for it.
2) After navigating to Administration >> Configuration, by default configuration with filter level:basic is seen
**Fixes Includes**: 
1) by-passing 'can_update_at_runtime' flag for 'rgw' related configurations as the same can be updated at runtime via CLI. Also implemented a warning popup for user to make force edit to rgw related configurations.
2) when navigated to …
> mgr/dashboard: Administration > Configuration > rgw_dns_name and rgw_dns_s3website_name not updatable via dashboard

- src/client/Client.cc
- src/include/cephfs/ceph_ll_client.h
- src/include/cephfs/libcephfs.h
- src/libcephfs.cc
- src/test/libcephfs/test.cc
man [fchownat(2)](https://www.man7.org/linux/man-pages/man2/fchownat.2.html) and man [statx(2)](https://www.man7.org/linux/man-pages/man2/statx.2.html) explains about the special case where empty _pathnames_ are valid with `AT_EMPTY_PATH` flag specified. But current client code crashes for _ceph_chownat()_ and _ceph_statxat()_ under this situation which should be gracefully handled as per the standards.
Fixes: https://tracker.ceph.com/issues/68189
Review with: `git show -w`
> client: Handle empty pathnames for `ceph_chownat()` and `ceph_statxat()`

- src/pybind/mgr/cephadm/services/nvmeof.py
- src/pybind/mgr/dashboard/services/nvmeof_cli.py
- src/pybind/mgr/dashboard/services/nvmeof_conf.py
backport tracker: https://tracker.ceph.com/issues/68811
---
backport of https://github.com/ceph/ceph/pull/60451
parent tracker: https://tracker.ceph.com/issues/68697
> squid: mgr/dashboard: rm nvmeof conf based on its daemon name

- src/test/objectstore/allocsim/ops_replayer.cc
ops_replayer
Fixes signedness warning and adds range checking to related worker thread parameters.
Signed-off-by: Jesse F. Williamson <1643380+chardan@users.noreply.github.com>
<details> …
> ops_replayer: fix signed/unsigned warning and add parameter range checking.

- src/test/objectstore/allocsim/ops_replayer.cc
Reverts ceph/ceph#61024
from build log https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos9,DIST=centos9,MACHINE_SIZE=gigantic/85258//consoleFull
```
src/test/objectstore/allocsim/ops_replayer.cc:46:47: error: ‘format’ is not a member of ‘std’; did you mean ‘fmt::v11::format’?
46 |                  throw std::out_of_range(std::format("value expected between {} and {}, but got {}", min, max, x));
|                                               ^~~~~~
In file included from src/test/objectstore/allocsim/ops_replayer.cc:20:
src/fmt/include/fmt/format.h:4376:13: note: ‘fmt::v11::format’ declared here
4376 | inline auto format(const Locale& loc, format_string<T...> fmt, T&&... args)
|             ^~~~~~
```
> Revert "ops_replayer: fix signed/unsigned warning and add parameter range checking."

- src/osd/PG.cc
- src/osd/scrubber/pg_scrubber.cc
- src/osd/scrubber_common.h
Following https://github.com/ceph/ceph/pull/59942
("osd/scrub: separate shallow vs deep errors storage"), the ScrubStore
now holds two separate error databases, one for the shallow
errors and one for the deep errors.
There is no longer a need to prevent (or warn about) shallow scrubs
being performed when deep errors are present.
> osd/scrub: remove the 'has_deep_errors' scheduling flag

- qa/standalone/scrub/osd-scrub-repair.sh
A bogus change introduced as part of PR#54363 (commit fbb7d73) changed multiple 'scrub' commands to 'scheduled-scrub'. In this one instance - that was wrong.
Fixes: https://tracker.ceph.com/issues/69276
> qa/standalone/scrub: fix TEST_periodic_scrub_replicated

- qa/suites/rbd/migration/6-prepare/qcow2-https.yaml
- src/librbd/migration/HttpClient.cc
backport tracker: https://tracker.ceph.com/issues/69243
---
backport of https://github.com/ceph/ceph/pull/61079
parent tracker: https://tracker.ceph.com/issues/69178
> squid: librbd/migration/HttpClient: avoid reusing ssl_stream after shut down

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/prometheus.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/dashboard-promqls.enum.ts
Issue: The Latency chart in the rgw overview page shows incorrect data unit as the unit that we are passing as an input to the dashboard-area chart component is `ms` whereas the data that we get from the metrics is in seconds. Due to this if we pass a value like 0.725s to the dashboard chart component it will show the value in the chart as 0.725ms whereas it should be 725ms.
Fix: Pass the value in ms as expected to the dashboard area chart component
Fixes: https://tracker.ceph.com/issues/69144
https://github.com/user-attachments/assets/91b9e8cf-8331-41b4-a55e-fade3f2eff13
- If you are submitting a …
> mgr/dashboard: Fix Latency chart data units in rgw overview page

- src/osdc/CMakeLists.txt
Was part of https://github.com/ceph/ceph/pull/60175 (split upon @batrick's request)
> CMakeLists.txt: do not compile {Objecter,Striper}.cc twice

- src/rgw/rgw_op.cc
When a request contains an empty list of objects, the current implementation returns a 200 OK. However, this behavior may raise security concerns, as it could imply the user has access to the bucket, even though access policies are only evaluated per object. To mitigate this risk, returning a 400 Bad Request would be a more secure approach. This ensures that no assumption is made about the user’s access to the bucket or its objects. Furthermore, this adjustment aligns with AWS behavior, enhancing compatibility.
Fixes: https://tracker.ceph.com/issues/68799
> rgw: return MalformedXML for empty objects list in DeleteObjects

- src/rgw/rgw_rest.cc
Ensure that a "?" is added to the redirect URL when query strings are present.
Fixes: https://tracker.ceph.com/issues/69139
> rgw: append query string to redirect URL if present

- src/rgw/rgw_admin.cc
Added the option to specify `--format=json` for `radosgw-admin bucket sync status` while maintaining the legacy plain text option. A sample output looks like: 
```
$ radosgw-admin bucket sync status --bucket=test --format=json | jq
{
"realm": "11dfb207-7990-4b54-b06c-86e6c361352e",
"realm_name": "earth",
"zonegroup": "390c4922-2772-4fb8-a5df-15aa1c755fc4",
"zonegroup_name": "zg1",
"zone": "703ace20-2cdf-4edc-8aeb-1841781f8c3b",
"zone_name": "zg1-2",
"bucket": "test",
"bucket_instance_id": "e6de5e2d-7ff3-4c76-8698-22a2b5887c7a.4244.1",
"current_time": "2024-11-08T20:54:39Z",
"sources": [
{
"source_zone": "e6de5e2d-7ff3-4c76-8698-22a2b5887c7a",
"source_name": "zg1-1",
"source_bucket": "test",
"source_bucket_id": "e6de5e2d-7ff3-4c76-8698-22a2b5887c7a.4244.1",
"total_shards": 11, …
```
> rgw-admin: Add --format option for bucket sync status

- src/rgw/rgw_op.cc
Hi, We have encountered a bug related to object metadata. Here is how this issue appears from the user’s perspective:
- The object can be listed.
- The head object operation returns the metadata.
- The get object request returns a 404 (NoSuchKey) error.
I can confirm that this issue is present in **v17.2.8**.
```
parallels@ubuntu-linux-22-04-desktop:~$ ./s3-multipart-fuzzer --rgw2 http://localhost:8000 
Found object: fuzzobject_000016
parallels@ubuntu-linux-22-04-desktop:~$ s3cmd get s3://test/fuzzobject_000016
download: 's3://test/fuzzobject_000016' -> './fuzzobject_000016'  [1 of 1]
ERROR: Download of './fuzzobject_000016' failed (Reason: 404 (NoSuchKey))
ERROR: S3 error: 404 (NoSuchKey)
parallels@ubuntu-linux-22-04-desktop:~$ s3cmd info s3://test/fuzzobject_000016 …
```
> rgw/abortmp: Race condition on AbortMultipartUpload

- src/test/rgw/bucket_notification/api.py
- src/test/rgw/bucket_notification/test_bn.py
**Test Additions:**
Added new test cases for `RGWPSListTopicsOp::execute()` to cover the following scenarios:
- Migration case: Verifying support_all_zones with v1 topics to ensure proper handling during migration.
- v2 notification case: Ensuring correct behavior when v2 notifications are supported.
- v1 notification case: Verifying fallback behavior when v2 notifications are unavailable.
**Version Handling for delete_all_topics:**
Updated the `delete_all_topics` function to include a version parameter, allowing for better control over topic deletions in v1 and v2 systems. The logic now correctly handles v1 responses, which include a result key in topics_json.
<details> …
> tests/rgw/notifications: Add tests for RGWPSListTopicsOp::execute()

- src/rgw/driver/posix/notify.h
```
/ceph/src/rgw/driver/posix/notify.h: In member function 'void file::listing::Inotify::signal_shutdown()': /ceph/src/rgw/driver/posix/notify.h:215:19: error: ignoring return value of 'ssize_t write(int, const void*, size_t)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
215 |       (void) write(efd, &msg, sizeof(uint64_t));
|              ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
Fixes: https://tracker.ceph.com/issues/69241
<details>
- …
> rgw/posix: std::ignore return value of write()

- qa/tasks/s3tests_java.py
backport tracker: https://tracker.ceph.com/issues/69210
---
backport of https://github.com/ceph/ceph/pull/61010
parent tracker: https://tracker.ceph.com/issues/69204
> squid: qa/rgw: fix s3 java tests by forcing gradle to run on Java 8

- qa/tasks/s3a_hadoop.py
backport tracker: https://tracker.ceph.com/issues/69269
---
backport of https://github.com/ceph/ceph/pull/61106
parent tracker: https://tracker.ceph.com/issues/68992
> squid: qa/rgw: force Hadoop to run under Java 1.8

- src/rgw/rgw_lc.cc
backport tracker: https://tracker.ceph.com/issues/69308
---
backport of https://github.com/ceph/ceph/pull/59449
parent tracker: https://tracker.ceph.com/issues/65772
> squid: rgw/lc: Fix lifecycle not working while bucket versioning is suspended

- src/rgw/driver/rados/rgw_rados.cc
When listing a bucket and the parameters are such that we're not listing namespaced entries, this commit adds an optimization to advance the marker such that we skip past a whole region of namespaced entries rather than evaluating each entry one-by-one.
(cherry picked from commit 91488321277d15b877d8b5c5a5204e18d7ab7fad)
Fixes: https://tracker.ceph.com/issues/69209
- When …
> squid: rgw: optimize bucket listing to skip past regions of namespaced entries

- src/script/ceph-backport.sh
This will allow the fork deduction code to recognize project names that include a hyphen, such as:
git@github.com:USERNAME/ceph-fork.git …
> script/ceph-backport: allow hyphen in project during ceph fork deduction

- src/librbd/ObjectMap.cc
- src/librbd/ObjectMap.h
- src/librbd/operation/FlattenRequest.cc
- src/test/librbd/test_internal.cc
backport tracker: https://tracker.ceph.com/issues/69327
---
backport of https://github.com/ceph/ceph/pull/61129
parent tracker: https://tracker.ceph.com/issues/68998
> squid: librbd: avoid data corruption on flatten when object map is inconsistent

- qa/workunits/rbd/cli_generic.sh
- src/test/cli/rbd/help.t
- src/tools/rbd/Utils.cc
- src/tools/rbd/Utils.h
- src/tools/rbd/action/Group.cc
backport tracker: https://tracker.ceph.com/issues/69332
---
backport of https://github.com/ceph/ceph/pull/61155
parent tracker: https://tracker.ceph.com/issues/69324
> squid: rbd: handle --{group,image}-namespace in "rbd group image {add,rm}"

- src/osd/osd_types.cc
- src/osd/osd_types.h
- src/osd/scrubber/pg_scrubber.cc
- src/osd/scrubber/scrub_machine.cc
- src/osd/scrubber/scrub_machine.h
- src/osd/scrubber/scrub_reservations.h
Whenever a PG is selected for scrubbing, and is waiting for remote reservations, the 'pg dump' output will include the following text (under the 'SCRUB_SCHEDULING' column):
Reserving. Waiting Ns for OSD.k (n/m)
> osd/scrub: show reservation status in 'pg dump' output

- doc/cephfs/snap-schedule.rst
- src/mon/FSCommands.cc
- src/pybind/mgr/snap_schedule/fs/schedule_client.py
- src/pybind/mgr/snap_schedule/module.py
- src/pybind/mgr/volumes/fs/operations/volume.py
Remove references to timers and db connection that refer to paths in the deleted volume.
This is a best case effort and not 100% safe. There can be race conditions where the db connection is closed while the module is executing a query on the db while the volume itself is deleted.
Hopefully there won't be many tracebacks seen.
Fixes: https://tracker.ceph.com/issues/63999
- When …
> mgr/snap_schedule: handle volume delete

- src/mds/MetricsHandler.cc
- src/mds/MetricsHandler.h
So that the MDS can transition faster to up:active without spending much time in processing metrics message during reconnect.
Fixes: http://tracker.ceph.com/issues/68865 …
> mds: do not process client metrics message with fast dispatch

- src/crimson/os/seastore/async_cleaner.cc
- src/crimson/os/seastore/backref_entry.h
- src/crimson/os/seastore/cache.cc
- src/crimson/os/seastore/cache.h
- src/crimson/os/seastore/cached_extent.cc
- src/crimson/os/seastore/cached_extent.h
- src/crimson/os/seastore/journal.h
- src/crimson/os/seastore/journal/circular_bounded_journal.cc
- src/crimson/os/seastore/journal/circular_bounded_journal.h
- src/crimson/os/seastore/journal/segmented_journal.cc
- src/crimson/os/seastore/journal/segmented_journal.h
- src/crimson/os/seastore/seastore_types.h
- src/crimson/os/seastore/transaction.h
- src/crimson/os/seastore/transaction_manager.cc
- src/test/crimson/seastore/test_block.h
- src/test/crimson/seastore/test_btree_lba_manager.cc
- src/test/crimson/seastore/test_cbjournal.cc
- src/test/crimson/seastore/test_seastore_journal.cc
This PR is supposed to be cleanup only, reworking https://github.com/ceph/ceph/pull/59775.
@zhscn @xxhdx1985126 
For the specific issue https://tracker.ceph.com/issues/66941, seems to me propagating remapped extents upon `prepare_record()` (PR59775) cannot address the issue, because the backref entries of fresh extents are still updated upon `complete_commit()`, and they have the same issue. And they cannot be simply moved to `prepare_record()` because their paddrs are unknown at that time.
So, IIUC a new segment state "COMMITTED" is still necessary to fix reclaiming, for both inline and ool segments.
~~TODO/Draft: still some cleanups to add.~~ Done. …
> crimson/os/seastore/cache: improve committing allocations by backref entries

- doc/mgr/dashboard.rst
With `ssl` set on the `server` option, HAProxy strips the TLS protocol for all clients. You would need to connect to it with `http://<ip>:443`.
To have an active health check, which uses SSL, but does not strip it for clients, you'd need to add:
- `check` to enable active health checks.
- `check-ssl` to instruct the health check to use TLS
- `verify none` to skip verification on the health check requests from HAProxy
- _REMOVE_ `ssl` to stop stripping TLS
The active health checks are required to not route any requests to the inactive managers. These would redirect to any unusable IP from the active mgr.
---
Alternatively you could add another certificate in the frontend and then re-encrypt the traffic.
--- …
> doc/mgr/dashboard: Fix HAProxy TLS example

- src/client/Client.cc
When osd is full, the client receives the notification and cancels the ongoing writes. If the ongoing writes are async, it could cause a dead lock as the async callback registered also takes the 'client_lock' which the handle_osd_map takes at the beginning.
Stripped down version of Traceback:
```
0  0x00007f4d77274960 in __lll_lock_wait ()
1  0x00007f4d7727aff2 in pthread_mutex_lock@@GLIBC_2.2.5 () 2  0x00007f4d7491b0a1 in __gthread_mutex_lock (__mutex=0x7f4d200f99b0) 3  std::mutex::lock (this=<optimized out>)
4  std::scoped_lock<std::mutex>::scoped_lock (__m=..., this=<optimized out>, this=<optimized out>, __m=...)
5  Client::C_Lock_Client_Finisher::finish (this=0x7f4ca0103550, r=-28)
6  0x00007f4d74888dfd in Context::complete (this=0x7f4ca0103550, r=<optimized out>)
7 …
```
> client: Fix a deadlock when osd is full

- src/tools/cephfs_mirror/FSMirror.h
Fixes the crash:
```
std::scoped_lock<std::mutex>::scoped_lock (__m=..., this=<optimized out>, this=<optimized out>, __m=...) at /usr/include/c++/11/mutex:655
cephfs::mirror::MirrorWatcher::is_failed (this=0x0) at /usr/src/debug/ceph-19.0.0-1578.g3d482f42.el9.x86_64/src/tools/cephfs_mirror/MirrorWatcher.h:56
cephfs::mirror::FSMirror::is_failed (this=0x557478284340) at /usr/src/debug/ceph-19.0.0-1578.g3d482f42.el9.x86_64/src/tools/cephfs_mirror/FSMirror.h:52
cephfs::mirror::Mirror::update_fs_mirrors (this=0x5574773c3e60) at /usr/src/debug/ceph-19.0.0-1578.g3d482f42.el9.x86_64/src/tools/cephfs_mirror/Mirror.cc:515
```
Fixes: https://tracker.ceph.com/issues/64751
(cherry picked from commit 5b8b9c2f7738e0341807c1e0971c3dec90ac5491)
> quincy: cephfs_mirror: fix crash in update_fs_mirrors()

- src/client/Client.cc
backport tracker: https://tracker.ceph.com/issues/66630
---
backport of https://github.com/ceph/ceph/pull/55659
parent tracker: https://tracker.ceph.com/issues/64503
> quincy: client: log debug message when requesting unmount

- src/mds/CDentry.cc
backport tracker: https://tracker.ceph.com/issues/66634
---
backport of https://github.com/ceph/ceph/pull/55412
parent tracker: https://tracker.ceph.com/issues/64058
> quincy: mds: ensure snapclient is synced before corruption check

- qa/tasks/mgr/dashboard/test_rbd.py
- src/pybind/mgr/dashboard/controllers/cluster_configuration.py
- src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/configuration.e2e-spec.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/configuration.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration-form/configuration-form-create-request.model.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration-form/configuration-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration-form/configuration-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/config-option/config-option.model.ts
- src/pybind/mgr/dashboard/openapi.yaml
backport tracker: https://tracker.ceph.com/issues/69273
backport of: #60798
parent tracker: https://tracker.ceph.com/issues/68976
<hr style="border:2px solid #eeeeee" />
Fixes: https://tracker.ceph.com/issues/68976
Fixes Includes:
1) by-passing 'can_update_at_runtime' flag for 'rgw' related configurations as the same can be updated at runtime via CLI. Also implemented a warning popup for user to make force edit to rgw related configurations. 2) when navigated to Administration >> Configuration, modified configuration will be seen as we see in cli "ceph config dump", instead of configuration with filter level:basic
(cherry picked from commit 3181acc223dafd04e3fc56d418389ad50c5868e4) …
> Squid: mgr/dashboard: Administration > Configuration > Some of the config options are not updatable at runtime

- src/client/Client.cc
- src/test/client/nonblocking.cc
backport of https://github.com/ceph/ceph/pull/55144
backport tracker: https://tracker.ceph.com/issues/67674
parent tracker: https://tracker.ceph.com/issues/63896 …
> squid: client: contiguous read fails for non-contiguous write (in async I/O api)

- qa/tasks/cephfs/test_mirroring.py
backport tracker: https://tracker.ceph.com/issues/68408
---
backport of https://github.com/ceph/ceph/pull/56118
parent tracker: https://tracker.ceph.com/issues/64711
> squid: qa: fix test failure test_cephfs_mirror_cancel_mirroring_and_readd

- src/tools/cephfs/top/cephfs-top
backport tracker: https://tracker.ceph.com/issues/68168
---
backport of https://github.com/ceph/ceph/pull/59566
parent tracker: https://tracker.ceph.com/issues/67859
> squid: cephfs-top: fix exceptions on small/large sized windows

- qa/workunits/fs/snaps/snaptest-double-null.sh
backport tracker: https://tracker.ceph.com/issues/67744
---
backport of https://github.com/ceph/ceph/pull/59095
parent tracker: https://tracker.ceph.com/issues/67408
> squid: qa: wait for file creation before changing mode
