src/test/rgw/rgw_multi/tests.py

https://tracker.ceph.com/issues/67207 …

qa/multisite: add extra checkpoints in datalog_autotrim testcase

---

qa/suites/rgw/multisite/realms/two-zonegroup.yaml

qa/multisite: enable two zonegroup yaml

---

container/Containerfile
container/build.sh
container/make-manifest-list.py

Modify container/ software to support release containers and the promotion of prerelease containers

---

doc/rados/operations/health-checks.rst

(cherry picked from commit ee0ef765349ed8e170f8cd31c4fa0c7570105a96) …

quincy: doc/rados: fix sentences in health-checks (2 of x)

---

doc/rados/operations/health-checks.rst

(cherry picked from commit ee0ef765349ed8e170f8cd31c4fa0c7570105a96) …

squid: doc/rados: fix sentences in health-checks (2 of x)

---

doc/rados/operations/erasure-code.rst

erasure code overhead table m-numbering contained 4 twice.
Signed-off-by: Danny Al-Gaaf <danny.al-gaaf@bisect.de>
- …

doc: fix EC overhead table m-numbering

---

src/os/bluestore/BlueStore.cc
src/test/objectstore/store_test.cc

Parent tracker: https://tracker.ceph.com/issues/64443
Backport tracker: https://tracker.ceph.com/issues/64647
Backports: https://github.com/ceph/ceph/pull/55594
(cherry picked from commit ac4a48c4be1791a32cfd2cf3cf5af51eee581d21) …

reef: test/store_test: fix DeferredWrite test when prefer_deferred_size=0

---

.github/labeler.yml

Label PRs for the new `container` directory.

labeler: add container labelers

---

qa/suites/upgrade/quincy-x/parallel/workload/rados_api.yaml
qa/suites/upgrade/quincy-x/stress-split/2-first-half-tasks/rbd-cls.yaml
qa/suites/upgrade/quincy-x/stress-split/3-stress-tasks/rbd-cls.yaml
qa/suites/upgrade/reef-x/parallel/workload/rados_api.yaml
qa/suites/upgrade/reef-x/stress-split/2-first-half-tasks/rbd-cls.yaml
qa/suites/upgrade/reef-x/stress-split/3-stress-tasks/rbd-cls.yaml

qa/suites/upgrade/*-x: skip TestClsRbd.group_snap_{set,remove}

---

doc/dev/release-process.rst

doc/dev/release-process.rst: New container build/release process

---

doc/dev/release-process.rst

(cherry picked from commit 178036924e7d1ec8eb62663f00f82d0b092c7ca1) …

squid: doc/dev/release-process.rst: New container build/release process

---

doc/dev/release-process.rst

(cherry picked from commit 178036924e7d1ec8eb62663f00f82d0b092c7ca1) …

reef: doc/dev/release-process.rst: New container build/release process

---

doc/dev/release-process.rst

(cherry picked from commit 178036924e7d1ec8eb62663f00f82d0b092c7ca1) …

quincy: doc/dev/release-process.rst: New container build/release process

---

qa/tasks/check_counter.py

Fixes: https://tracker.ceph.com/issues/67360 …

qa: restrict 'perf dump' on active mds only

---

src/rgw/driver/dbstore/README.md
src/rgw/driver/dbstore/tests/dbstore_tests.cc
src/test/objectstore/test_deferred.cc

Bumped into these whilst running the test ctest suite.
Fixes should be pretty straightforward. …

tests: Improve unittest_dbstore_tests and unittest_deferred to be suitable for reruns.

---

src/pybind/rbd/rbd.pyx

Noticed while reviewing https://github.com/ceph/ceph/pull/60844. …

pybind/rbd: fix a type comment for p_snapshot of clone()

---

qa/tasks/nvme_loop.py

Specifically on some centos 9 tests, we've seen that a newer version of some nvme related package is causing this task to fail with "KeyError: 'DevicePath'" due to the format of the output of the nvme list command changing. This patch adds handling for the new format we've seen while also still supporting the old format (necessary for the tests running on ubuntu).
Fixes: https://tracker.ceph.com/issues/69067 …

qa/tasks/nvme_loop: update task to work with new nvme list format

---

doc/foundation.rst

This is for reef since the new foundation structure has changed. …

reef: doc/foundation.rst: update Intel point of contact

---

doc/releases/quincy.rst

Signed-off-by: Enrico Bocchi <enrico.bocchi@cern.ch>
- …

doc/releases: fix formatting for the 17.2.8 release (el8 CERN)

---

src/rgw/driver/rados/rgw_bucket.cc

Allow linking unlinked bucket.
Fixes: https://tracker.ceph.com/issues/69060
- …

rgw: fix bucket link operation

---

src/rgw/driver/rados/rgw_rados.cc

rgw: Delete stale entries in bucket indexes while deleting obj
If rados_osd_op_timeout is set, the primary osd is slow, the rgw_rados_operate for deleting the rgw head obj may return -110. 
But the primary osd may deleting the rgw head obj sucessfully. Thus the bucket index_op for deleting will canceld, the delete request return with HTTP 408. When client retrying the delete request, rgw would return with HTTP 204, but the bucket index still exist. If rgw head obj not exist, the bucket index entry should alsl be deleted.
Fixes: https://tracker.ceph.com/issues/58965
Signed-off-by: Shasha Lu <lu.shasha@aishu.cn> …

rgw: Delete stale entries in bucket indexes while deleting obj

---

doc/dev/development-workflow.rst

doc/dev: instruct devs to backport

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-multisite-zonegroup-deletion-form/rgw-multisite-zonegroup-deletion-form.component.ts

while deleting zone group from dashboard, notification message says "zone <zg_name> deleted successfully" instead of "zone group <zg_name> deleted successfully"
Fixes: https://tracker.ceph.com/issues/69121 …

mgr/dashboard: Update and correct zonegroup delete notification

---

qa/tasks/nvme_loop.py

backport tracker: https://tracker.ceph.com/issues/69184
---
backport of https://github.com/ceph/ceph/pull/60928
parent tracker: https://tracker.ceph.com/issues/69067

squid: qa/tasks/nvme_loop: update task to work with new nvme list format

---

src/crimson/admin/osd_admin.cc
src/crimson/common/logclient.cc
src/crimson/common/tmap_helpers.cc
src/crimson/mon/MonClient.cc
src/crimson/net/Socket.cc
src/crimson/os/alienstore/thread_pool.cc
src/crimson/os/cyanstore/cyan_store.cc
src/crimson/os/seastore/cached_extent.h
src/crimson/os/seastore/seastore_types.h
src/crimson/osd/heartbeat.cc
src/crimson/osd/main.cc
src/crimson/osd/main_config_bootstrap_helpers.cc
src/crimson/osd/pg.h
src/crimson/osd/shard_services.h
src/crimson/tools/perf_crimson_msgr.cc
src/os/bluestore/BlueFS.cc

crimson: add missing includes

---

qa/config/crimson_qa_overrides.yaml

qa/config/crimson_qa_overrides: enable alienstore debug

---

qa/config/crimson_qa_overrides.yaml
src/crimson/net/io_handler.cc
src/crimson/net/io_handler.h

More information is necessary to debug issues such as https://tracker.ceph.com/issues/66606 …

crimson/net: log adjustment / enable ms debug

---

qa/suites/rbd/migration/6-prepare/qcow2-https.yaml
src/librbd/migration/HttpClient.cc

librbd/migration/HttpClient: avoid reusing ssl_stream after shut down

---

src/client/Client.h
src/tools/cephfs_mirror/PeerReplayer.cc
src/tools/cephfs_mirror/PeerReplayer.h

Fixes: https://tracker.ceph.com/issues/68853 …

tools/cephfs-mirror: eliminate redundant ceph_close() call

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.ts

In the buckets table add a new column to show the number of shards in the bucket
Fixes: https://tracker.ceph.com/issues/69016 …

mgr/dashboard: Display bucket's number of shards on the ceph dashboard

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-list/multi-cluster-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-list/multi-cluster-list.component.ts

Currently wrong date is being displayed if we hover of the Token Expires filed in the Clusters list table in Manage Clusters page. This PR intends to fix this issue.
Fixes: https://tracker.ceph.com/issues/69172
https://github.com/user-attachments/assets/3dfe551b-888f-4e4c-b82e-13544cc29da1 …

mgr/dashboard: Show correct token expiration date in Manage Clusters page

---

src/pybind/mgr/dashboard/frontend/package-lock.json
src/pybind/mgr/dashboard/frontend/package.json

To fix NG0100: ExpressionChangedAfterItHasBeenCheckedError on `<input/>`
see: https://github.com/carbon-design-system/carbon-components-angular/pull/3069
Fixes: https://tracker.ceph.com/issues/69039 …

mgr/dashboard: update carbon-components-angular package

---

src/tools/monmaptool.cc

Fixes: https://tracker.ceph.com/issues/53751
------
RCA: https://tracker.ceph.com/issues/53751#note-16.
- Tracker …

tools: respect set features when adding addresses

---

src/rgw/rgw_rest_sts.cc

while authenticating AssumeRoleWithWebIdentity using JWT obtained from an external IDP.
fixes: https://tracker.ceph.com/issues/68836 …

rgw/sts: fix to disallow unsupported JWT algorithms

---

src/python-common/ceph/deployment/service_spec.py

🧹cephadm/nvmeof: fix ports when default values are overridden

---

src/pybind/mgr/dashboard/controllers/rgw_iam.py
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/rgw_iam.py
src/pybind/mgr/dashboard/tests/test_rgw_iam.py

Fixes: https://tracker.ceph.com/issues/69110
PR Changes:
Added CRUD & managing quota endpoints for RGW user accounts management …

mgr/dashboard: RGW user accounts CRUD api's 

---

doc/radosgw/uadk-accel.rst

Make most of the changes to doc/radosgw/uadk-accel.rst suggested by Anthony D'Atri in https://github.com/ceph/ceph/pull/59514. …

doc/radosgw: edit uadk-accel.rst

---

src/mon/NVMeofGwMon.cc
src/mon/NVMeofGwMon.h

nvmeofgw* : fix publishing rebalance index

---

src/msg/async/Event.cc

This avoids a stack allocation and assignment.
(Splitted from https://github.com/ceph/ceph/pull/60105 because this change is trivial, and the eventfd hasn't seen a review yet after more than 2 months.)

msg/async/Event: make the pipe byte static

---

qa/suites/nvmeof/basic/workloads/nvmeof_initiator.yaml
qa/suites/nvmeof/basic/workloads/nvmeof_namespaces.yaml
qa/suites/nvmeof/basic/workloads/nvmeof_scalability.yaml
qa/suites/nvmeof/thrash/gateway-initiator-setup/10-subsys-90-namespace-no_huge_pages.yaml
qa/suites/nvmeof/thrash/gateway-initiator-setup/120-subsys-8-namespace.yaml
qa/suites/nvmeof/thrash/thrashers/nvmeof_mon_thrash.yaml
qa/suites/nvmeof/thrash/thrashers/nvmeof_thrash.yaml
qa/suites/nvmeof/thrash/workloads/fio.yaml
qa/tasks/nvmeof.py
qa/workunits/nvmeof/basic_tests.sh
qa/workunits/nvmeof/fio_test.sh
qa/workunits/nvmeof/scalability_test.sh
qa/workunits/nvmeof/setup_subsystem.sh

~~results: https://pulpito.ceph.com/vallariag-2024-10-30_17:41:56-nvmeof-main-distro-default-smithi/~~
teuthology results:
- https://pulpito.ceph.com/vallariag-2024-11-25_12:07:35-nvmeof-wip-vallari2-2024-11-25-1535-distro-default-smithi/
- with no huge pages config: https://pulpito.ceph.com/vallariag-2024-11-21_07:48:13-nvmeof-wip-baum-no-huge-20241120-02-distro-default-smithi/ …

qa: fix nvmeof scalability and namespace test

---

src/pybind/mgr/dashboard/frontend/src/app/core/auth/auth.module.ts
src/pybind/mgr/dashboard/frontend/src/app/core/auth/user-form/user-form-role.model.ts
src/pybind/mgr/dashboard/frontend/src/app/core/auth/user-form/user-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/core/auth/user-form/user-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/date-time-picker/date-time-picker.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/date-time-picker/date-time-picker.component.scss
src/pybind/mgr/dashboard/frontend/src/app/shared/components/date-time-picker/date-time-picker.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/helper/helper.component.html
src/pybind/mgr/dashboard/frontend/src/styles/themes/_content.scss

Fixes: https://tracker.ceph.com/issues/67979
Signed-off-by: Puja Shahu <pshahu@redhat.com> …

mgr/dashboard: carbonize user management form

---

src/test/rgw/bucket_notification/test_bn.py

from commit: 05e2ade13292e7d924e6385ea234f58c13eb2d51
<details>
</details>

squid: test/rgw/notifications: fix test regression

---

monitoring/ceph-mixin/prometheus_alerts.libsonnet
monitoring/ceph-mixin/prometheus_alerts.yml
monitoring/ceph-mixin/tests_alerts/test_alerts.yml

NVMeoFMultipleNamespacesOfRBDImage alerts the user if a RBD image is used for multiple namespaces. This is important alerts for cases where namespaces are created on same image for different gateway group.
https://shaman.ceph.com/builds/ceph/wip-nvmeof-prometheus-rbd-image-reused-fix2-centos9-only/c17d297148142a06bfa794129f9cb8a70a35faae/default/418104/ …

monitoring: Add prometheus alert NVMeoFMultipleNamespacesOfRBDImage

---

PendingReleaseNotes

We merged a fix for v19.2.1 that fixes a performance bottleneck in the balancer module: https://tracker.ceph.com/issues/68657 …

PendingReleaseNotes: add note about tracker #69012

---

src/librbd/ObjectMap.cc
src/librbd/ObjectMap.h
src/librbd/operation/FlattenRequest.cc
src/test/librbd/test_internal.cc

librbd: avoid data corruption on flatten when object map is inconsistent

---

src/tools/rbd/action/MirrorPool.cc

rbd: open images in read-only mode for "rbd mirror pool status --verbose"

---

qa/workunits/rbd/cli_generic.sh
src/test/cli/rbd/help.t
src/tools/rbd/Utils.cc
src/tools/rbd/Utils.h
src/tools/rbd/action/Group.cc

rbd: handle --{group,image}-namespace in "rbd group image {add,rm}"

---

src/compressor/lz4/LZ4Compressor.cc

Although simplifying the things, the main rationale is going towards `bufferlist` with tight restrictions on modyfying stored data, and thus enabling e.g. deduplication of padding zeros. This in turn can be very interesting for some further optimizations of EC support which have in common increasing the chunk size.
Currently `bufferlist` allows to mess its content and cause crosstalks through at least three mechanisms:
* the `bufferlist::c_str()` returning non-`const` pointer to `char`,
* the iterator's `get_current_ptr()` returning a writable bptr,
* the iterator's `copy_in()`. …

compressor: switch out of get_current_ptr() for the sake of const-stricter bufferlist

---

doc/start/hardware-recommendations.rst

Fixes a typo in the  `Controllers` section of hardware recommendations in the Ceph Intro. …

doc/start: Fixes a typo in controllers section of hardware recommendations

---

doc/start/hardware-recommendations.rst

Signed-off-by: Kevin Niederwanger <k.niederwanger@gmail.com>
(cherry picked from commit 089636224910e1cd6231cadd2c422a78c3d08fea) …

doc: Fixes a typo in controllers section of hardware recommendations

---

doc/start/hardware-recommendations.rst

Signed-off-by: Kevin Niederwanger <k.niederwanger@gmail.com>
(cherry picked from commit 089636224910e1cd6231cadd2c422a78c3d08fea) …

reef: doc: Fixes a typo in controllers section of hardware recommendations

---

doc/start/hardware-recommendations.rst

Signed-off-by: Kevin Niederwanger <k.niederwanger@gmail.com>
(cherry picked from commit 089636224910e1cd6231cadd2c422a78c3d08fea) …

quincy: doc: Fixes a typo in controllers section of hardware recommendations

---

qa/suites/fs/nfs/tasks/nfs.yaml
qa/tasks/cephfs/test_nfs.py

Fixes: https://tracker.ceph.com/issues/69311 …

qa: Add async io test to nfs ganesha using fio

---

doc/radosgw/notifications.rst
qa/suites/rgw/notifications/tasks/kafka_failover/0-install.yaml
qa/suites/rgw/notifications/tasks/kafka_failover/supported-distros
qa/suites/rgw/notifications/tasks/kafka_failover/test_kafka.yaml
qa/tasks/kafka_failover.py
qa/tasks/notification_tests.py
src/rgw/driver/rados/rgw_pubsub_push.cc
src/rgw/rgw_kafka.cc
src/rgw/rgw_kafka.h
src/test/rgw/bucket_notification/requirements.txt
src/test/rgw/bucket_notification/test_bn.py

reopen: #57052 
tracker: [issue 65830](https://tracker.ceph.com/issues/65830)

rgw: allow bucket notification send message to kafka with multiple brokers

---

qa/suites/fs/workload/tasks/6-workunit/kernel_untar_build.yaml

Fixes: http://tracker.ceph.com/issues/68855 …

qa: use a larger timeout for kernel_untar_build workunit

---

PendingReleaseNotes
doc/cephfs/health-messages.rst
qa/suites/fs/multifs/tasks/failover.yaml
qa/tasks/cephfs/test_failover.py
src/common/options/mds.yaml.in
src/mds/Beacon.cc
src/mds/MDLog.cc
src/mds/MDLog.h
src/mds/mdstypes.cc
src/mds/mdstypes.h
src/messages/MMDSBeacon.h

It is helpful to get an estimate of how much time it might take to finish replaying the journal.
Fixes: https://tracker.ceph.com/issues/61863
Supersedes #52527  …

mds: emit warning with estimated replay time

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-form/rgw-multisite-sync-policy-form.component.html

backport tracker: https://tracker.ceph.com/issues/69366
backport of: https://github.com/ceph/ceph/pull/60862
parent tracker: https://tracker.ceph.com/issues/69072
<hr style="border: 2px solid #eeeeee" />
Fixes: https://tracker.ceph.com/issues/69072
Signed-off-by: Naman Munet <namanmunet@li-ff83bccc-26af-11b2-a85c-a4b04bfb1003.ibm.com>
(cherry picked from commit 3ae0e6d05375e41e002c262fec526e40120500ec) …

Squid: mgr/dashboard: fix multisite e2e failures

---

doc/radosgw/uadk-accel.rst

Line edit the first half of doc/radosgw/uadk-accel.rst.
This is one of a series of pull requests intended to improve the content of uadk-accel.rst. This series includes the following PRs:
https://github.com/ceph/ceph/pull/59514
https://github.com/ceph/ceph/pull/60953
https://github.com/ceph/ceph/pull/61128 …

doc/radosgw: line edit uadk-accel.rst (1st half)

---

README.md

doc: Gave more details about tips and tricks and troubleshooting for Vstsrt in the readme file.

doc: Update vstart section in readme.md

---

README.md

Format an admonition correctly. This commit is a prelude to a cleanup of a recent addition to README.md.
- Tracker …

doc: README.md - format admonition

---

doc/cephfs/index.rst
doc/cephfs/purge-queue.rst

Fixes: https://tracker.ceph.com/issues/68571 …

doc/cephfs: document purge queue and its perf counters

---

doc/cephfs/index.rst
doc/cephfs/purge-queue.rst

Fixes: https://tracker.ceph.com/issues/68571
(cherry picked from commit ae9277398840bf8576ea5a8c4a2ba4e23f8b9613) …

squid: doc/cephfs: document purge queue and its perf counters

---

doc/cephfs/index.rst
doc/cephfs/purge-queue.rst

Fixes: https://tracker.ceph.com/issues/68571
(cherry picked from commit ae9277398840bf8576ea5a8c4a2ba4e23f8b9613) …

quincy: doc/cephfs: document purge queue and its perf counters

---

doc/cephfs/index.rst
doc/cephfs/purge-queue.rst

Fixes: https://tracker.ceph.com/issues/68571
(cherry picked from commit ae9277398840bf8576ea5a8c4a2ba4e23f8b9613) …

reef: doc/cephfs: document purge queue and its perf counters

---

src/test/rgw/bucket_notification/test_bn.py

for persistent topic stats tests
<details>
</details>

test/rgw/noitifications: fix test names

---

src/mds/MDSRank.cc
src/mds/MDSRank.h
src/mds/MetricsHandler.cc

Backport of https://github.com/ceph/ceph/pull/57084
Backport tracker: https://tracker.ceph.com/issues/66620
Parent tracker: https://tracker.ceph.com/issues/65660 …

squid: mds: drop client metrics during recovery

---

src/client/Client.cc

Backport tracker: https://tracker.ceph.com/issues/67587
- …

squid: client: flush the caps release in filesystem sync

---

src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
src/pybind/mgr/cephadm/tests/test_services.py
src/python-common/ceph/deployment/service_spec.py

mgr/cephadm/nvmeof: Add key verification field to NVMeOF configuration
Fixes https://tracker.ceph.com/issues/69413 …

mgr/cephadm/nvmeof: Add key verification field to NVMeOF configuration

---

README.md

Format "Tips and Tricks" into its own section so that it doesn't confuse readers of the vstart installation procedure. …

doc: README.md - format "Tips and Tricks"

---

src/crimson/osd/osd_operation.h
src/crimson/osd/osd_operation_external_tracking.h
src/crimson/osd/osd_operations/replicated_request.cc
src/crimson/osd/osd_operations/replicated_request.h
src/crimson/osd/pg.cc
src/crimson/osd/pg.h

Based on https://github.com/ceph/ceph/pull/61005
<details>
</details>

crimson: allow replica side write commits to pipeline

---

src/crimson/osd/replicated_recovery_backend.cc

Fixes: https://tracker.ceph.com/issues/68806 …

crimson/osd/replicated_recovery_backend: call on_global_recover() only when all replicas and the primary have been recovered

---

src/crimson/osd/backfill_facades.h
src/crimson/osd/backfill_state.cc
src/crimson/osd/backfill_state.h
src/test/crimson/test_backfill.cc

Fixes: https://tracker.ceph.com/issues/67888 …

crimson/osd/backfill_state: treat `Cancelled` as a pause of the ongoing backfilling

---

doc/cephfs/index.rst
doc/cephfs/snapshots.rst

Fixes: https://tracker.ceph.com/issues/68974
- Tracker …

doc: add snapshots under cephfs concepts

---

src/script/run-make.sh

Fixes: https://tracker.ceph.com/issues/68394 …

script/run-make: stop args duplication

---

src/rgw/rgw_op.cc

https://github.com/ceph/ceph/pull/56583 recently fixed merge_and_store_attrs() to preserve existing attrs, but this broke the swift api's ability to remove container metadata. RGWCreateBucket handles this merging itself with prepare_add_del_attrs(), so we should just assign createparams.attrs to the bucket and store it with bucket->put_info()
make the same change for RGWPutMetadataBucket which swift uses to add/remove existing metadata
Fixes: https://tracker.ceph.com/issues/69301
<details> …

rgw: don't use merge_and_store_attrs() when recreating a bucket

---

src/crimson/os/alienstore/alien_store.cc
src/crimson/os/alienstore/alien_store.h
src/crimson/os/cyanstore/cyan_store.cc
src/crimson/os/cyanstore/cyan_store.h
src/crimson/os/futurized_store.h
src/crimson/os/seastore/async_cleaner.cc
src/crimson/os/seastore/async_cleaner.h
src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/cache.h
src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/seastore.h
src/crimson/os/seastore/seastore_types.h
src/crimson/os/seastore/transaction.h
src/crimson/os/seastore/transaction_manager.cc
src/crimson/os/seastore/transaction_manager.h
src/crimson/osd/pg_backend.cc
src/crimson/osd/pg_backend.h
src/crimson/osd/replicated_recovery_backend.cc
src/crimson/tools/store_nbd/tm_driver.cc
src/test/crimson/seastore/test_btree_lba_manager.cc
src/test/crimson/seastore/test_seastore_cache.cc

crimson/os/seastore: add fadvise support to SeaStore and prevent recovery/backfill from polluting the cache of SeaStore

---

src/vstart.sh

https://github.com/user-attachments/assets/8aa2d6bd-6a78-48e1-b24d-b742a6d20d71
Added support for optionally launching the ceph-exporter daemon in vstart.sh via a new --exporter command-line option. Implemented start_exporter function to handle exporter startup, similar to start_mon and other daemons, and bound it to the --exporter input flag.
Related changes for this task in ceph-dev too. (https://github.com/rhcs-dashboard/ceph-dev/pull/89) …

vstart: add ceph-exporter support

---

qa/tasks/nvmeof.py
qa/workunits/nvmeof/basic_tests.sh
qa/workunits/nvmeof/fio_test.sh

There seems to be change in 'nvme list' json output which caused failures in asserts after 'nvme connect-all' command. …

qa/workunits/nvmeof/basic_tests.sh: fix nvme list assert

---

src/crimson/osd/backfill_state.cc
src/crimson/osd/backfill_state.h
src/crimson/osd/osd_operation.h
src/crimson/osd/pg_recovery.cc
src/crimson/osd/pg_recovery.h
src/crimson/osd/shard_services.h

crimson/osd/pg_recovery: throttle backfills together with pglog based recoveries

---

src/rgw/rgw_op.cc
src/rgw/rgw_op.h
src/rgw/rgw_rest_s3.cc

rgw/multisite:  include request body when CreateBucket op is forwarded to master

---

qa/tasks/rgw_multisite.py
src/rgw/driver/daos/rgw_sal_daos.cc
src/rgw/driver/daos/rgw_sal_daos.h
src/rgw/driver/motr/rgw_sal_motr.cc
src/rgw/driver/motr/rgw_sal_motr.h
src/rgw/driver/rados/rgw_period.cc
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/driver/rados/rgw_sal_rados.h
src/rgw/driver/rados/rgw_zone.h
src/rgw/rgw_common.cc
src/rgw/rgw_common.h
src/rgw/rgw_op.cc
src/rgw/rgw_sal.h
src/rgw/rgw_sal_dbstore.cc
src/rgw/rgw_sal_dbstore.h
src/rgw/rgw_sal_filter.h
src/rgw/services/svc_zone.cc
src/rgw/services/svc_zone.h
src/test/rgw/rgw_multi/tests.py

Check the location constraint of the request when the zonegroup is master
Fixes: https://tracker.ceph.com/issues/62309

rgw: check for location constraint on master zonegroup

---

src/rgw/driver/rados/rgw_tools.cc

Fixes: https://tracker.ceph.com/issues/69303 …

rgw: Don't crash on exceptions from pool listing

---

doc/rados/operations/stretch-mode.rst

Added more content and rewrite some sections for stretch mode
- …

doc/rados/operations/stretch-mode: Improve doc

---

src/rgw/driver/rados/rgw_tools.cc

Fixes: https://tracker.ceph.com/issues/69303
(cherry picked from commit 4318b188740634ead65a986680f9186541c9d1b0)
Fixes: https://tracker.ceph.com/issues/69476 …

squid: rgw: Don't crash on exceptions from pool listing

---

src/test/objectstore/allocsim/ops_replayer.cc

ops_replayer
Fixes signedness warning and adds range checking to related worker thread parameters.
Reviewed-by: adamemerson
Signed-off-by: Jesse F. Williamson <jfw@ibm.com> …

ops_replayer: fix signed/unsigned warning and add parameter range checking.

---

src/exporter/ceph_exporter.cc

src/exporter: improve usage message
- …

src/exporter: improve usage message

---

src/exporter/ceph_exporter.cc

(cherry picked from commit 725b4e184798dc38ec60ab81766577b39fd6e488) …

squid: src/exporter: improve usage message

---

src/crimson/osd/backfill_state.cc
src/crimson/osd/backfill_state.h
src/crimson/osd/pg.cc
src/crimson/osd/pg.h
src/crimson/osd/replicated_backend.cc
src/crimson/osd/replicated_recovery_backend.cc

Fixes: https://tracker.ceph.com/issues/69027 …

crimson/osd/replicate_backend: add standalone delete to the push queue if the object is deleted while it's being backfilled

---

src/crimson/osd/backfill_state.cc

Fixes: https://tracker.ceph.com/issues/69120 …

crimson/osd/backfill_state: recheck whether needs to scan the primary at the end of Enqueuing::Enqueuing

---

qa/suites/rados/verify/validater/valgrind.yaml

In these tests, we are intentionally stopping and restoring OSDs, so it makes sense to ignore these warnings.
Fixes: https://tracker.ceph.com/issues/67181 …

qa/suites/rados/verify/validater: ignore OSD_DOWN

---

src/common/ceph_time.h
src/crimson/os/alienstore/alien_store.cc
src/kv/KeyValueDB.h
src/kv/RocksDBStore.cc
src/kv/RocksDBStore.h
src/os/DBObjectMap.cc
src/os/DBObjectMap.h
src/os/ObjectStore.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/os/kstore/KStore.cc
src/os/kstore/KStore.h
src/os/memstore/MemStore.cc
src/os/memstore/MemStore.h
src/osd/PrimaryLogPG.cc
src/test/ObjectMap/KeyValueDBMemory.cc
src/test/objectstore/ObjectStoreImitator.h

os, osd: bring the lightweight OMAP iteration

---

src/pybind/mgr/diskprediction_local/predictor.py

Patch is for reef ONLY, not a traditional backport. Disable mypy check for the given line. This check is triggerin all reef CI jobs to fail.
Fixes: https://tracker.ceph.com/issues/69471 …

reef: mgr/diskprediction_local: avoid mypy error

---

src/pybind/mgr/cephadm/templates/services/alertmanager/alertmanager.yml.j2
src/pybind/mgr/cephadm/templates/services/mgmt-gateway/nginx.conf.j2
src/pybind/mgr/cephadm/templates/services/prometheus/prometheus.yml.j2
src/pybind/mgr/cephadm/tests/test_services.py

when mgmt-gateway is enabled mTLS is enforced and all the communication peers (monitoring daemons in this case) have to provide a valid certificate (signed by cephadm Root CA). …

mgr/cephadm: fixing config files for prometheus and alertmanager

---

doc/releases/index.rst
qa/crontab/teuthology-cronjobs

Remove "Quincy" from the list of "Active Releases" in doc/releases/index.rst.
- …

doc/releases: remove Quincy from "Active"

---

qa/suites/rados/monthrash/workloads/rados_mon_osdmap_prune.yaml

Issue: mon/test_mon_osdmap_prune.sh is failing due to PG_DEGRADED state.
Cause: We are writing an objects to a newly created PG before it has enough OSDs in acting set to create enough replicas. This is expected behaviour, thus the solution is to add the warning to ignorelist.
Fixes: https://tracker.ceph.com/issues/69288
QA run successfully testing fix: [ref](https://pulpito.ceph.com/shraddhaag-2025-01-09_14:32:12-rados:monthrash-main-distro-default-smithi/) …

rados/monthrash: add PG_DEGRADED to ignorelist

---

src/librbd/migration/HttpClient.cc
src/librbd/migration/HttpClient.h
src/mgr/PyModule.cc
src/test/librbd/migration/test_mock_HttpClient.cc

Fixes to unbreak compilation on Boost above 1.85.
Fixes: https://tracker.ceph.com/issues/69495 …

{mgr, rbd, tests/os}: Fixes for Boost 1.86

---

src/osd/ExtentCache.h
src/osd/Session.h
src/osd/osd_types.h
src/osdc/Objecter.cc

OSD-specific parts of https://github.com/ceph/ceph/pull/60175 (split upon @batrick's request)

OSD: Small optimizations

---

doc/releases/releases.yml

Add the actual EOL date for the Quincy release (it's 2025-01-13).
- Component …

doc/releases: add actual_eol for quincy

---

src/rgw/rgw_auth.cc
src/rgw/rgw_auth.h
src/rgw/rgw_auth_filters.h
src/rgw/rgw_auth_s3.h
src/rgw/rgw_rest_s3.cc
src/rgw/rgw_swift_auth.cc
src/rgw/rgw_swift_auth.h

calling to `s->user->read_attrs(...);` similar to the way it was before commit https://github.com/ceph/ceph/pull/54333/commits/582970a69399d989370bb1ced6e42de724509622
which then is used by `get_attrs()` in `rate_limit(...)` at:
https://github.com/ceph/ceph/blob/4bd2fdc114e266aa67d09c9dda86e5fcc8da5d0c/src/rgw/rgw_process.cc#L115-L124
Fixes: https://tracker.ceph.com/issues/68346 …

rgw: fix user rate limit is not enforced w/ global rate limit set

---

src/pybind/mgr/dashboard/HACKING.rst
src/test/pybind/test_ceph_argparse.py
src/tools/cephfs/top/cephfs-top

Minor fixes to documentation and test cases. …

Doc and test fixes

---

doc/radosgw/bucket_logging.rst
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/driver/rados/rgw_sal_rados.h
src/rgw/radosgw-admin/radosgw-admin.cc
src/rgw/rgw_bucket_logging.cc
src/rgw/rgw_bucket_logging.h
src/rgw/rgw_common.h
src/rgw/rgw_rest_bucket_logging.cc
src/rgw/rgw_s3_filter.h
src/rgw/rgw_sal.h
src/rgw/rgw_sal_filter.h
src/rgw/rgw_sal_store.h
src/test/cli/radosgw-admin/help.t

tests are done in this PR: https://github.com/ceph/s3-tests/pull/607
<details>
</details>

rgw/logging: add more validations to conf, cross tenant support and cleanup

---

container/Containerfile

CEPH_VERSION used to be present to hold the ref.  Other projects relied on this.  Make life easier for them.
- …

container/Containerfile: replace CEPH_VERSION label for backward compat

---

.githubmap
.mailmap
.organizationmap
.peoplemap

Add Abhishek Kane into peoplemap, githubmap, organizationmap, mailmap
Signed-off-by: abhishek-kane <abhishek.kane@ibm.com>
<details>
</details>

Add Abhishek Kane into peoplemap, githubmap, organizationmap, mailmap

---

src/os/bluestore/BlueFS.cc
src/test/objectstore/test_bluefs.cc

Adapted after additional review.
Added unittest.
Fixes: https://tracker.ceph.com/issues/68385 …

os/bluestore: Make truncate() drop unused allocations - addendum

---

qa/suites/rados/verify/clusters/fixed-4.yaml

Fixes: https://tracker.ceph.com/issues/67489 …

qa/suites: Make fixed-4 an option for verify tests

---

doc/cephfs/disaster-recovery-experts.rst

Edit the first two sections of doc/cephfs/disaster-recovery-experts.rst in preparation for adding deeper explanations of the contexts in which one should use the various commands listed on that page. …

doc/cephfs: edit disaster-recovery-experts

---

src/rgw/driver/rados/rgw_rados.cc

Fixes: https://tracker.ceph.com/issues/69536 …

rgw: RGWRados::get_olh() needs to use the correct attr

---

src/rgw/rgw_op.cc

In handle_replication_status_header() when the COMPLETED status is being set to object's attr, it needs to be reflected to the current live attrs for the corresponding request so it can be reflected in the first try than the second.
Fixes: https://tracker.ceph.com/issues/69549

rgw: update attrs with replication status to reflect in response

---

doc/releases/squid.rst

Rephrase the balancer-related warning issued to people upgrading to Ceph 19.2.0.
Follows https://github.com/ceph/ceph/pull/61429 …

doc/releases: edit warning for balancer issues

---

src/msg/async/AsyncMessenger.cc

(cherry picked from commit 3d36a3b9bbeb8b21b99046aab0d0bdf8f1c30aa2) …

squid: AsyncMessenger.cc : improve error messages

---

src/msg/async/AsyncMessenger.cc

(cherry picked from commit 3d36a3b9bbeb8b21b99046aab0d0bdf8f1c30aa2) …

reef: AsyncMessenger.cc : improve error messages

---

doc/cephfs/disaster-recovery-experts.rst

Edit the first two sections of doc/cephfs/disaster-recovery-experts.rst in preparation for adding deeper explanations of the contexts in which one should use the various commands listed on that page.
(cherry picked from commit cc8cfeddbd290ef9b5e4e0c68ae94cefb34e1be9) …

squid: doc/cephfs: edit disaster-recovery-experts

---

doc/cephfs/disaster-recovery-experts.rst

Edit the first two sections of doc/cephfs/disaster-recovery-experts.rst in preparation for adding deeper explanations of the contexts in which one should use the various commands listed on that page.
(cherry picked from commit cc8cfeddbd290ef9b5e4e0c68ae94cefb34e1be9) …

reef: doc/cephfs: edit disaster-recovery-experts

---

doc/cephfs/disaster-recovery-experts.rst

Edit the first two sections of doc/cephfs/disaster-recovery-experts.rst in preparation for adding deeper explanations of the contexts in which one should use the various commands listed on that page.
(cherry picked from commit cc8cfeddbd290ef9b5e4e0c68ae94cefb34e1be9) …

quincy: doc/cephfs: edit disaster-recovery-experts

---

doc/cephfs/disaster-recovery-experts.rst

Remove a link to a tracker for a planned-but-never-developed tool that would have facilitated the importation or exportation of a RADOS pool to a file. This is a part of a project to improve the CephFS Disaster Recovery documentation, which was requested by Eugen Block. See the tracker issue below for more on this project.
Follows https://github.com/ceph/ceph/pull/61411
See https://github.com/ceph/ceph/pull/61411#discussion_r1918525109
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatch …

doc/cephfs: remove link to undeveloped tool

---

doc/cephfs/disaster-recovery-experts.rst

Edit the third and fourth sections of
Follows https://github.com/ceph/ceph/pull/61426 …

doc/cephfs: edit disaster-recovery-experts (2 of x)

---

doc/cephfs/disaster-recovery-experts.rst

Properly wrap a poorly-formatted paragraph that looks just awful in an 80-column viewport and change MDS to "MDS daemons" where the latter makes the sentence a lot clearer. …

doc/cephfs: disaster-recovery-experts cleanup

---

doc/cephfs/disaster-recovery-experts.rst

Edit the third and fourth sections of
Follows https://github.com/ceph/ceph/pull/61426
(cherry picked from commit 4f3a69eb919fc0d99cdf943f095ca3a951c82897) …

squid: doc/cephfs: edit disaster-recovery-experts (2 of x)

---

doc/cephfs/disaster-recovery-experts.rst

Edit the third and fourth sections of
Follows https://github.com/ceph/ceph/pull/61426
(cherry picked from commit 4f3a69eb919fc0d99cdf943f095ca3a951c82897) …

reef: doc/cephfs: edit disaster-recovery-experts (2 of x)

---

doc/cephfs/disaster-recovery-experts.rst

Properly wrap a poorly-formatted paragraph that looks just awful in an 80-column viewport and change MDS to "MDS daemons" where the latter makes the sentence a lot clearer.
(cherry picked from commit dceaab9a1a479ea3a10b6eff5bb4ae23d2ad6aa0) …

squid: doc/cephfs: disaster-recovery-experts cleanup

---

doc/cephfs/disaster-recovery-experts.rst

Edit the fifth and sixth sections of
The sections edited in this commit are
- MDS Map Reset
- Recovery From Mission Metadata Objects
Follows https://github.com/ceph/ceph/pull/61427 …

doc/cephfs: edit disaster-recovery-experts (3 of x)

---

doc/cephfs/disaster-recovery-experts.rst

Edit the fifth and sixth sections of
The sections edited in this commit are
- MDS Map Reset
- Recovery From Mission Metadata Objects
Follows https://github.com/ceph/ceph/pull/61427
(cherry picked from commit a69c4142b7f99146af690933b3cfe897a64c7c59) …

squid: doc/cephfs: edit disaster-recovery-experts (3 of x)

---

doc/cephfs/disaster-recovery-experts.rst

Edit the fifth and sixth sections of
The sections edited in this commit are
- MDS Map Reset
- Recovery From Mission Metadata Objects
Follows https://github.com/ceph/ceph/pull/61427
(cherry picked from commit a69c4142b7f99146af690933b3cfe897a64c7c59) …

reef: doc/cephfs: edit disaster-recovery-experts (3 of x)

---

src/exporter/ceph_exporter.cc

(cherry picked from commit 725b4e184798dc38ec60ab81766577b39fd6e488) …

reef: src/exporter: improve usage message

---

doc/radosgw/account.rst

clarify the following error when migrating a user into an account:
> could not modify user: unable to modify user, UserName contains invalid characters
Fixes: https://tracker.ceph.com/issues/69470
(cherry picked from commit afa2b83687de96bfe9ae90c73744f71217dabcbe) …

squid: doc/rgw: document UserName requirements for account migration

---

doc/cephfs/index.rst
doc/cephfs/snapshots.rst

Fixes: https://tracker.ceph.com/issues/68974
(cherry picked from commit 885b1bf88ee28b05cc9ed91e8ea5146511b6cf34) …

squid: doc: add snapshots in docs under Cephfs concepts

---

doc/cephfs/index.rst
doc/cephfs/snapshots.rst

Fixes: https://tracker.ceph.com/issues/68974
(cherry picked from commit 885b1bf88ee28b05cc9ed91e8ea5146511b6cf34) …

reef: doc: add snapshots in docs under Cephfs concepts

---

doc/cephfs/index.rst
doc/cephfs/snapshots.rst

Fixes: https://tracker.ceph.com/issues/68974
(cherry picked from commit 885b1bf88ee28b05cc9ed91e8ea5146511b6cf34) …

quincy: doc: add snapshots in docs under Cephfs concepts

---

src/rgw/rgw_asio_frontend.cc
src/rgw/rgw_auth_s3.cc
src/rgw/rgw_auth_s3.h
src/rgw/rgw_bucket_logging.cc

RGW\logging: added missing fields

---

qa/tasks/thrashosds-health.yaml

Problem:
thrash tests will make Ceph warn about OSDs being down.
Solution:
ignore the `osds down` warning since we know that
the OSDs are expected to be down
Fixes: https://tracker.ceph.com/issues/68602 …

qa/tasks/thrashosds-health.yaml: Add osds down to ignorelist

---

doc/releases/releases.yml

Add the actual EOL date for the Quincy release (it's 2025-01-13).
(cherry picked from commit 2c4ab9c571218bc09d14de0b101166fbab965f85) …

squid: doc/releases: add actual_eol for quincy

---

doc/releases/releases.yml

Add the actual EOL date for the Quincy release (it's 2025-01-13).
(cherry picked from commit 2c4ab9c571218bc09d14de0b101166fbab965f85) …

reef: doc/releases: add actual_eol for quincy

---

src/rgw/rgw_lc.cc

Fixes: https://tracker.ceph.com/issues/69459 …

rgw/lc: make lc worker thread name shorter

---

src/os/bluestore/Allocator.cc
src/os/bluestore/Allocator.h
src/os/bluestore/BlueStore.cc
src/test/objectstore/allocator_replay_test.cc

Backport of #51820
Fixes: https://tracker.ceph.com/issues/69474 …

[reef] os/bluestore: introduce allocator state histogram

---

src/test/librbd/test_Migration.cc

Fixes: https://tracker.ceph.com/issues/65743 …

test/librbd: add unit test for flatten migration

---

src/crimson/mgr/client.cc
src/crimson/mgr/client.h
src/crimson/osd/osd.cc
src/crimson/osd/osd.h
src/crimson/osd/osd_operation.cc
src/crimson/osd/osd_operation.h
src/crimson/osd/osd_operations/client_request.cc
src/crimson/osd/osd_operations/client_request.h

Fixes: https://tracker.ceph.com/issues/63766 …

crimson/mgr/client.cc: daemon_health_metrics support

---

src/crimson/common/tri_mutex.h
src/crimson/osd/object_context.h
src/crimson/osd/pg.cc

Should help with debugging issues as:  https://tracker.ceph.com/issues/69406.
- …

crimson/common/tri_mutex: improve logging

---

src/ceph-volume/ceph_volume/api/lvm.py
src/ceph-volume/ceph_volume/devices/lvm/activate.py
src/ceph-volume/ceph_volume/devices/lvm/batch.py
src/ceph-volume/ceph_volume/devices/lvm/common.py
src/ceph-volume/ceph_volume/devices/lvm/create.py
src/ceph-volume/ceph_volume/devices/lvm/deactivate.py
src/ceph-volume/ceph_volume/devices/lvm/listing.py
src/ceph-volume/ceph_volume/devices/lvm/main.py
src/ceph-volume/ceph_volume/devices/lvm/prepare.py
src/ceph-volume/ceph_volume/devices/lvm/trigger.py
src/ceph-volume/ceph_volume/devices/lvm/zap.py
src/ceph-volume/ceph_volume/objectstore/baseobjectstore.py
src/ceph-volume/ceph_volume/objectstore/bluestore.py
src/ceph-volume/ceph_volume/objectstore/lvmbluestore.py
src/ceph-volume/ceph_volume/objectstore/rawbluestore.py
src/ceph-volume/ceph_volume/tests/api/test_lvm.py
src/ceph-volume/ceph_volume/tests/conftest.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_batch.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_listing.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_prepare.py
src/ceph-volume/ceph_volume/tests/objectstore/test_lvmbluestore.py
src/ceph-volume/ceph_volume/tests/objectstore/test_rawbluestore.py
src/ceph-volume/ceph_volume/tests/util/test_device.py
src/ceph-volume/ceph_volume/util/device.py

This PR consolidates all ongoing Python type annotation changes to ceph-volume into a single submission to optimize CI resource usage.

ceph-volume: type annotations

---

src/pybind/mgr/cephadm/cert_mgr.py
src/pybind/mgr/cephadm/ssl_cert_utils.py
src/pybind/mgr/cephadm/tests/test_node_proxy.py

cephadm orch mgr: Add fsid detail when ca certificate is created to identify cluster in multi cluster ceph.
Fixes: https://tracker.ceph.com/issues/69081
Signed-off-by: Anuradha Gadge [anuradha.gadge@ibm.com](mailto:anuradha.gadge@ibm.com) …

mgr/cephadm: Changes for creating root cert with manager cluster fsid

---

doc/cephfs/disaster-recovery-experts.rst

Put the procedure in the section called "Using an alternate metadata pool for recovery" into an ordered list, so that it is in a proper procedure format.
This commit is meant only to break the procedure into steps. The English language in each of these steps could be improved, but that improvement will be done after this formatting has been merged and backported.
Follows https://github.com/ceph/ceph/pull/61462. …

doc/cephfs: edit disaster-recovery-experts (5 of x)

---

doc/cephadm/host-management.rst

Correct the English in a note in doc/cephadm/host-management.rst.
This commit was made in response to
https://github.com/ceph/ceph/pull/50340, which corrected some of this note in Quincy.
(cherry picked from commit d15f1f6869465a8cc3191169f038217baecf2c4f) …

squid: doc/cephadm: correct note

---

doc/cephadm/host-management.rst

Correct the English in a note in doc/cephadm/host-management.rst.
This commit was made in response to
https://github.com/ceph/ceph/pull/50340, which corrected some of this note in Quincy.
(cherry picked from commit d15f1f6869465a8cc3191169f038217baecf2c4f) …

reef: doc/cephadm: correct note

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html

Typo in the text for the "Unmanaged" option in Create Service.
Fixes: https://tracker.ceph.com/issues/69550
- …

mgr/dashboard: Typo in NVMe-oF create service

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-bucket.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
src/pybind/mgr/dashboard/services/cluster.py

backport tracker: https://tracker.ceph.com/issues/69596
---
backport of https://github.com/ceph/ceph/pull/60514
parent tracker: https://tracker.ceph.com/issues/68733

squid: mgr/dashboard: fix total objects/Avg object size in RGW Overview Page

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-bucket.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
src/pybind/mgr/dashboard/services/cluster.py

backport tracker: https://tracker.ceph.com/issues/69597
---
backport of https://github.com/ceph/ceph/pull/60514
parent tracker: https://tracker.ceph.com/issues/68733

reef: mgr/dashboard: fix total objects/Avg object size in RGW Overview Page

---

src/pybind/mgr/dashboard/controllers/smb.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-list/smb-cluster-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-list/smb-cluster-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/tests/test_smb.py

Tracker: https://tracker.ceph.com/issues/69191
https://tracker.ceph.com/issues/69605
https://github.com/user-attachments/assets/eec27c8e-daf0-425e-ba6f-891abd26a6c2 …

mgr/dashboard: delete smb cluster

---

src/client/Client.cc

client: Fix signed comparison warning

---

src/test/rgw/rgw_multi/conn.py
src/test/rgw/rgw_multi/multisite.py

some reef multisite tests like `copy_object` need boto3 support.
this is already present on squid and main added by https://github.com/ceph/ceph/pull/55657.  …

reef: qa/multisite: add boto3.client to the library

---

src/test/neorados/pool.cc

The test case itself call CoTearDown function by the end of every test case and the function call delete_pool on the basis of pool name exists in local set <created_pools> and if the pool does not exist during CoTearDown it throws an exception so the test case expects the pool should be exists before leaving the test case.
Solution: Call create_pool to avoid an error during CoTearDown
Fixes: https://tracker.ceph.com/issues/69405
- …

neorados_pool_test: Call create_pool at the end of NeoRados delete_pool related test

---

src/mon/NVMeofGwMon.cc

nvmeofgw*: change log level of critical nvmeof monitor events to 1

---

doc/radosgw/multisite.rst

s/zonegroup/pools/, where this change makes the text clearer.
This change was made in reponse to an upstream comment on https://pad.ceph.com/p/Report_Documentation_Bugs.
Fixes: https://tracker.ceph.com/issues/69689 …

doc/radosgw: s/zonegroup/pools/

---

src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-trash-move-modal/rbd-trash-move-modal.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-form/cephfs-snapshotschedule-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-form/smb-cluster-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-form/smb-cluster-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-form/smb-cluster-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-list/smb-cluster-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-list/smb-cluster-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-domain-setting-modal/smb-domain-setting-modal.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-domain-setting-modal/smb-domain-setting-modal.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-domain-setting-modal/smb-domain-setting-modal.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb.model.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/service.interface.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts

Fixes-: https://tracker.ceph.com/issues/69156
https://github.com/user-attachments/assets/7e57ccf4-8da3-4817-9417-0622bd41fc53
https://github.com/user-attachments/assets/62b66f91-f37b-4150-b114-7c436d54ebaa
28/01/2025 …

mgr/dashboard: create smb cluster

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html

Fixes: https://tracker.ceph.com/issues/69485 …

mgr/dashboard: add warning message on smb service management

---

doc/radosgw/multisite.rst

s/zonegroup/pools/, where this change makes the text clearer.
This change was made in reponse to an upstream comment on https://pad.ceph.com/p/Report_Documentation_Bugs.
Fixes: https://tracker.ceph.com/issues/69689
(cherry picked from commit ea576ccd037ee0336f01342c86ea9b1468f67cc3) …

reef: doc/radosgw: s/zonegroup/pools/

---

doc/radosgw/multisite.rst

s/zonegroup/pools/, where this change makes the text clearer.
This change was made in reponse to an upstream comment on https://pad.ceph.com/p/Report_Documentation_Bugs.
Fixes: https://tracker.ceph.com/issues/69689
(cherry picked from commit ea576ccd037ee0336f01342c86ea9b1468f67cc3) …

squid: doc/radosgw: s/zonegroup/pools/

---

qa/erasure-code/ec-rados-plugin=isa-k=10-m=4.yaml
qa/erasure-code/ec-rados-plugin=isa-k=4-m=2.yaml
qa/erasure-code/ec-rados-plugin=isa-k=6-m=3.yaml
qa/erasure-code/ec-rados-plugin=jerasure-k=4-m=2.yaml
qa/suites/rados/thrash-erasure-code-isa/workloads/ec-rados-plugin=isa-k=10-m=4.yaml
qa/suites/rados/thrash-erasure-code-isa/workloads/ec-rados-plugin=isa-k=4-m=2.yaml
qa/suites/rados/thrash-erasure-code-isa/workloads/ec-rados-plugin=isa-k=6-m=3.yaml

Signed-off-by: Jamie Pryde <jamiepry@uk.ibm.com> …

qa/erasure-code: add new teuthology isa configs

---

src/rgw/rgw_rest_pubsub.cc
src/test/rgw/bucket_notification/test_bn.py

https://tracker.ceph.com/issues/62783 …

RGW | bucket notifications: support cross tenant operations

---

src/pybind/mgr/cephadm/services/cephadmservice.py

Allow passing ssl_certificate as an rgw_frontend_extra_arg.
Without this change, it is not possible to pass `ssl_certificate` as an argument of the `rgw_frontend_extra_args` field. Doing so results in the RGW being configured with two `ssl_certificate` parameters, and failing to start. This enables this in a backwards compatible manner.
Fixes: https://tracker.ceph.com/issues/69567
Signed-off-by: Alexander Hussein-Kershaw alexhus@microsoft.com

cephadm: rgw: allow specifying the ssl_certificate by filepath

---

container/build.sh

container/build.sh: don't require repo creds on NO_PUSH

---

src/rgw/rgw_op.cc
src/rgw/rgw_op.h
src/rgw/rgw_rest_s3.cc

Fixes: https://tracker.ceph.com/issues/53016
Signed-off-by: Raja Sharma <raja@ibm.com> …

RGW:fix obj by multipart upload cant get tag

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/model/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml

Added new endpoints to ceph cli and dashboard API to align with cli commands that already exist in existing nvmeof cli.
fixes: https://tracker.ceph.com/issues/62705 …

mgr/dashboard: Add additional cli endpoints

---

qa/workunits/rbd/permissions.sh
src/mon/OSDMonitor.cc
src/osd/OSDCap.cc

mon/OSDMonitor: relax cap enforcement for unmanaged snapshots

---

src/libcephfs_proxy/libcephfs_proxy.c

libcephfs_proxy: implement ceph_readdir_r()

---

src/pybind/mgr/cephadm/agent.py
src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/serve.py
src/pybind/mgr/cephadm/services/cephadmservice.py
src/pybind/mgr/cephadm/services/container.py
src/pybind/mgr/cephadm/services/ingress.py
src/pybind/mgr/cephadm/services/iscsi.py
src/pybind/mgr/cephadm/services/jaeger.py
src/pybind/mgr/cephadm/services/mgmt_gateway.py
src/pybind/mgr/cephadm/services/monitoring.py
src/pybind/mgr/cephadm/services/nfs.py
src/pybind/mgr/cephadm/services/node_proxy.py
src/pybind/mgr/cephadm/services/nvmeof.py
src/pybind/mgr/cephadm/services/oauth2_proxy.py
src/pybind/mgr/cephadm/services/osd.py
src/pybind/mgr/cephadm/services/service_registry.py
src/pybind/mgr/cephadm/services/smb.py
src/pybind/mgr/cephadm/tests/test_services.py
src/pybind/mgr/cephadm/upgrade.py

This is a follow-up PR from the comment https://github.com/ceph/ceph/pull/60800#discussion_r1887513733
- Tracker …

mgr/cephadm: using service registry pattern for cephadm services

---

doc/architecture.rst

Remove a sentence that is more marketing than reference.
- …

doc/architecture: remove sentence

---

src/osd/scrubber/scrub_backend.cc

Only the Primary data is consulted. No need to go over all the scrub-maps.

osd/scrub: remove unnecessary loop

---

qa/workunits/dencoder/test_readable.py

This PR addresses issues in the dencoder tests related to backward compatibility checks. 
It improves the handling of type skipping and testing logic by ensuring compatibility is properly checked across versions. Types introduced in newer versions are now correctly skipped for older decoder versions, following cascading backward compatibility rules. …

dencoder tests fix type backwards incompatible checks 

---

src/osd/PG.cc
src/osd/SnapMapper.cc
src/osd/SnapMapper.h

Added while debugging new possible issue, will post tracker once identified:
```
2025-01-20T16:05:49.057+0000 7f446f08f640 20 snap_mapper  [pg_id:7f, match:127, mask_bits:7, last_key_checked:, pool:2, shard:-1, shard_prefix: , prefixes: {"0000000000000002.F7", "0000000000000002.FF"}] update_bits prefix updated
``` …

osd/SnapMapper: Improve logging

---

src/crimson/osd/backfill_state.cc
src/crimson/osd/backfill_state.h
src/crimson/osd/pg.h
src/crimson/osd/pg_recovery.cc
src/crimson/osd/pg_recovery.h
src/osd/PG.cc
src/osd/PG.h
src/osd/PeeringState.cc
src/osd/PeeringState.h
src/osd/PrimaryLogPG.cc
src/test/crimson/test_backfill.cc

Signed-off-by: Xuehan Xu [xuxuehan@qianxin.com](mailto:xuxuehan@qianxin.com)
- …

osd/PeeringState: rename "cancel_backfill" to "suspend_backfill"

---

doc/rados/operations/stretch-mode.rst

Degraded stretch mode should only half the "min_size" not "size".
Fixes: No tracker (doc changes) …

doc/rados/operations/stretch-mode: fix mistake in stretch mode

---

src/test/osd/RadosModel.h

Tier_flush can return ENOENT if the recovery procedure for adjacent clones are in progress. 
To prevent the false alarm, this commit allows ENOENT to be returned in the case of tier_flush.
Allowing ENOENT might not cover some cases, but this has a advantage:
1) No need to change OSD code.
Also, the other cases can be covered because:
1) tier_flush is a write operation that rarely returns ENOENT 
2) other operations in combination test can cover ENOENT case, minimizing OSD changes.
fix: https://tracker.ceph.com/issues/68518
result: 
https://pulpito.ceph.com/myoungwon-2024-12-30_01:15:36-rados-fix-68518-distro-default-smithi/
https://pulpito.ceph.com/myoungwon-2024-12-27_14:52:24-rados-fix-68518-distro-default-smithi/
https://pulpito.ceph.com/myoungwon-2024-12-26_04:25:39-rados-fix-68518-dis …

src/test: allow ENOENT if target object of tier_flush has snapshots

---

src/mds/MDBalancer.cc

When option `mds_bal_overload_epochs` was added by PR #53332,
two positions should have been modified, but one of them was overlooked.
Fixes: https://tracker.ceph.com/issues/68953
Signed-off-by: Zhansong Gao <zhsgao@hotmail.com> …

mds: fix option mds_bal_overload_epochs

---

qa/suites/rbd/cli/workloads/rbd_cli_migration.yaml
qa/workunits/rbd/cli_migration.sh
src/librbd/Operations.cc

librbd: stop filtering async request error codes

---

src/sample.ceph.conf

src: modernize sample.ceph.conf
This file is referenced in multiple other places, so it seems prudent minimize it to reflect central config than to attempt to completely excise it.
Fixes: https://tracker.ceph.com/issues/69757 …

src: modernize sample.ceph.conf

---

win32_deps_build.sh

backport tracker: https://tracker.ceph.com/issues/69775
---
backport of https://github.com/ceph/ceph/pull/61627
parent tracker: https://tracker.ceph.com/issues/69768

reef: win32_deps_build.sh: pin zlib tag

---

qa/suites/nvmeof/basic/workloads/nvmeof_scalability.yaml
qa/suites/nvmeof/thrash/base/install.yaml
qa/suites/nvmeof/thrash/gateway-initiator-setup/2-subsys-8-namespace.yaml
qa/tasks/nvmeof.py
qa/workunits/nvmeof/fio_test.sh
qa/workunits/nvmeof/scalability_test.sh

qa: fix nvmeof teuthology thrasher fix

---

monitoring/ceph-mixin/config.libsonnet
monitoring/ceph-mixin/prometheus_alerts.libsonnet
monitoring/ceph-mixin/prometheus_alerts.yml
monitoring/ceph-mixin/tests_alerts/test_alerts.yml

Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2342282
- …

monitoring: add NVMeoFMaxGatewayGroups alert 

---

monitoring/ceph-mixin/dashboards/ceph-cluster.libsonnet
monitoring/ceph-mixin/dashboards/cephfs.libsonnet
monitoring/ceph-mixin/dashboards/host.libsonnet
monitoring/ceph-mixin/dashboards/osd.libsonnet
monitoring/ceph-mixin/dashboards/pool.libsonnet
monitoring/ceph-mixin/dashboards/rbd.libsonnet
monitoring/ceph-mixin/dashboards/rgw-s3-analytics.libsonnet
monitoring/ceph-mixin/dashboards/rgw.libsonnet
monitoring/ceph-mixin/dashboards_out/ceph-cluster-advanced.json
monitoring/ceph-mixin/dashboards_out/cephfs-overview.json
monitoring/ceph-mixin/dashboards_out/host-details.json
monitoring/ceph-mixin/dashboards_out/hosts-overview.json
monitoring/ceph-mixin/dashboards_out/osd-device-details.json
monitoring/ceph-mixin/dashboards_out/osds-overview.json
monitoring/ceph-mixin/dashboards_out/pool-detail.json
monitoring/ceph-mixin/dashboards_out/pool-overview.json
monitoring/ceph-mixin/dashboards_out/radosgw-detail.json
monitoring/ceph-mixin/dashboards_out/radosgw-overview.json
monitoring/ceph-mixin/dashboards_out/radosgw-sync-overview.json
monitoring/ceph-mixin/dashboards_out/rbd-details.json
monitoring/ceph-mixin/dashboards_out/rbd-overview.json
monitoring/ceph-mixin/dashboards_out/rgw-s3-analytics.json

Fixes: https://tracker.ceph.com/issues/69727
Signed-off-by:- Piyush Agarwal [piyushagarwal14.pa@gmail.com](mailto:piyushagarwal14.pa@gmail.com)
https://github.com/user-attachments/assets/a453e725-6fad-4514-aaf0-b1fd0c72f228
https://github.com/user-attachments/assets/13535e53-abff-4717-aef6-e7549041dc4b …

mgr/dashboard: Add 'Browse Dashboards' button in Grafana dashboards

---

src/test/CMakeLists.txt
src/test/common/CMakeLists.txt
src/test/mgr/CMakeLists.txt

Fixes: https://tracker.ceph.com/issues/67065 …

test: fix ld link errors

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-storage-class.model.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-list/rgw-storage-class-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-list/rgw-storage-class-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-list/rgw-storage-class-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
src/pybind/mgr/dashboard/frontend/src/styles/themes/_content.scss

Fixes: https://tracker.ceph.com/issues/69606
**Added a option in navigation under Object as "**Tiering**"
And listing Storage class based on tier type as s3-cloud
https://github.com/user-attachments/assets/98da414a-c541-42b1-9753-48427c88ea69 …

mgr/dashboard: Storage Class Management

---

src/test/objectstore/test_bluefs.cc

std::string(" ", number) -> std::string(number, ' ')
- …

os/bluestore: Fix unittest_bluefs

---

src/rgw/rgw_rest_s3.cc

As PutBucketReplication requests are forwarded to the master, it needs to use the effective owner to set the correct (client) uid for the sync pipe rather than the system user.
Fixes: https://tracker.ceph.com/issues/68172

rgw: use effective owner in PutBucketReplication

---

src/rgw/driver/rados/rgw_rados.cc

No associated tracker. This is about enhancing debug log events of the function `fetch_remote_obj()`. 
We build alarming on some error events including the ones from this function and in a recent io_load/network test received the below event 
<pre>
2024-09-17T10:37:39.954+0000 7f58a10c9700  0 rgw async rados processor: ERROR: source and destination objects don't match. Expected etag:... Computed etag:...
</pre>
It's not directly obvious which `bucket:object` such events are for. Raised this PR to see whether we can add src/dest object info to fetch_remote_obj()'s log events to facilitate debugging.
<s>Gathered below modified events in a controlled environment so the new events would look like as follows for an object obj123456789 found in the bucket u1b1.</s>
Re-tested after adding [10/21 …

RGW: add src/dest object info to fetch_remote_obj()'s debug log events

---

src/pybind/mgr/cephadm/services/nfs.py

The test_nfs task we run in teuthology creates and removes a number of nfs clusters during the task. I think it's possible based on timing for it to end up in a situation where it tries to remove an nfs service before the grace file has been created. In that case, cephadm doesn't know it hasn't created the grace file and just repeatedly fails forever attempting to remove the nonexistent file. This patch adds handling for the error case where we get a nonzero rc but the error message implies the command failed because the file already does not exist.
Fixes: https://tracker.ceph.com/issues/69736 …

mgr/cephadm: continue in nfs service purge if grace file is already deleted

---

src/rgw/radosgw-admin/orphan.cc
src/rgw/radosgw-admin/radosgw-admin.cc

Correcting a mistake I made in an earlier PR that moved copyright notice before editor tags. …

rgw: fixup for emacs/vim modes, moved to top of file.

---

src/os/bluestore/BlueFS.cc

Fixes: https://tracker.ceph.com/issues/67932 …

tools/ceph-bluestore-tool: optimize offline trim report info

---

doc/cephadm/services/osd.rst

Change "Remove an OSD" to "Monitoring OSD State During OSD Removal" and reword a sentence so that it more clearly refers to the process under discussion. …

doc/cephadm: clarify "Monitoring OSD State"

---

src/client/Client.h
src/tools/cephfs_mirror/PeerReplayer.cc
src/tools/cephfs_mirror/PeerReplayer.h

Fixes: https://tracker.ceph.com/issues/69245 …

squid: tools/cephfs-mirror: eliminate redundant ceph_close() call

---

qa/tasks/check_counter.py

backport tracker: https://tracker.ceph.com/issues/69142
---
backport of https://github.com/ceph/ceph/pull/59383
parent tracker: https://tracker.ceph.com/issues/67360

squid: qa: restrict 'perf dump' on active mds only

---

qa/tasks/cephfs/test_damage.py
src/mds/MDCache.cc

mds: do not path traverse a damaged dirfrag

---

qa/workunits/rbd/permissions.sh
src/mon/OSDMonitor.cc
src/osd/OSDCap.cc

backport tracker: https://tracker.ceph.com/issues/69730
---
backport of https://github.com/ceph/ceph/pull/61540
parent tracker: https://tracker.ceph.com/issues/69679

reef: mon/OSDMonitor: relax cap enforcement for unmanaged snapshots

---

doc/cephadm/services/osd.rst

Improve the section "Activate Existing OSDs".
Supplement the information in the "Activate Existing OSDs" section with a procedure developed by Eugen Block, here:
https://heiterbiswolkig.blogs.nde.ag/2025/02/06/cephadm-activate-existing-osds/
This procedure explains how to activate OSDs on a host that, for whatever reason, has had to have its operating system reinstalled.
Co-authored by Eugen Block. …

doc/cephadm: improve "Activate Existing OSDs"

---

doc/architecture.rst
doc/rados/operations/pools.rst

(cherry picked from commit e261155a8a0234897803d38e899d10ec89b2b08f) …

squid: doc: Clarify that there are no tertiary OSDs

---

doc/architecture.rst
doc/rados/operations/pools.rst

(cherry picked from commit e261155a8a0234897803d38e899d10ec89b2b08f) …

reef: doc: Clarify that there are no tertiary OSDs

---

doc/cephadm/services/osd.rst

Improve the section "Activate Existing OSDs".
Supplement the information in the "Activate Existing OSDs" section with a procedure developed by Eugen Block, here:
https://heiterbiswolkig.blogs.nde.ag/2025/02/06/cephadm-activate-existing-osds/
This procedure explains how to activate OSDs on a host that, for whatever reason, has had to have its operating system reinstalled.
Co-authored by Eugen Block.
(cherry picked from commit 2de592e2f0b8b76aac706703dc44078d5ebb6ab8) …

squid: doc/cephadm: improve "Activate Existing OSDs"

---

doc/cephadm/services/osd.rst

Improve the section "Activate Existing OSDs".
Supplement the information in the "Activate Existing OSDs" section with a procedure developed by Eugen Block, here:
https://heiterbiswolkig.blogs.nde.ag/2025/02/06/cephadm-activate-existing-osds/
This procedure explains how to activate OSDs on a host that, for whatever reason, has had to have its operating system reinstalled.
Co-authored by Eugen Block.
(cherry picked from commit 2de592e2f0b8b76aac706703dc44078d5ebb6ab8) …

reef: doc/cephadm: improve "Activate Existing OSDs"

---

do_cmake.sh

Otherwise the `EXACT`check for Python version in the root `CMakeList.txt` fails.
- …

do_cmake.sh: add support for Fedora 41

---

doc/rados/operations/pools.rst

(cherry picked from commit b1e5da594a662e0037459489fbbd449685ad9854) …

squid: doc/rados/operations: Improve pools.rst

---

doc/rados/operations/pools.rst

(cherry picked from commit b1e5da594a662e0037459489fbbd449685ad9854) …

reef: doc/rados/operations: Improve pools.rst

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/cluster.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/host-form/host-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/host-form/host-form.component.ts

Addressing the review comments in https://github.com/ceph/ceph/pull/60355#pullrequestreview-2391335490
Issues fixing
- cluster expansion host form not closing form when submitting it
- cluster expansion host form changing the location when closing it
- put the helper text inside helper component since its longer
- maintenance field should be hidden in cluster expansion form since its not a valid option while expanding a cluster. We already add host in _no_schedule
https://github.com/user-attachments/assets/01264d10-7a41-426c-aa0c-b2fe8aebecb9
Fixes: https://tracker.ceph.com/issues/69020 …

mgr/dashboard: fix host form issues

---

src/pybind/mgr/dashboard/controllers/smb.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-list/smb-cluster-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-tabs/smb-cluster-tabs.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-tabs/smb-cluster-tabs.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-tabs/smb-cluster-tabs.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-share-list/smb-share-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-share-list/smb-share-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-share-list/smb-share-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb.model.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.ts
src/pybind/mgr/dashboard/tests/test_smb.py

Fixes: https://tracker.ceph.com/issues/69449
[screen-capture (44).webm](https://github.com/user-attachments/assets/d2921945-7545-4d91-bc12-0e53948278ea) …

mgr/dashboard: add smb share listing in UI

---

src/blk/kernel/KernelDevice.cc
src/blk/kernel/KernelDevice.h

This will cause discard threads to wake up each other if bdev_async_discard_threads >= 2. …

blk/kerneldevice: notify_all only required when discard_drain wait for condition

---

src/log/test.cc

Fix building a unit test with -Werror enabled.
Based on @cbodley's fix for a similar build failure.
Based-on: a2ebc00a56fcffc57b04fad1e5d134f75ae753eb …

log: ignore return value of write in unit test

---

doc/cephadm/services/osd.rst

Make three minor changes to doc/cephadm/services/osd.rst. These three changes were suggested by Eugen Block, who reviewed this procedure after developing it. …

doc/cephadm: improve "Activate Existing OSDs".

---

doc/cephadm/services/osd.rst

Make three minor changes to doc/cephadm/services/osd.rst. These three changes were suggested by Eugen Block, who reviewed this procedure after developing it.
(cherry picked from commit abc4a197f7849922bc6a1cd0a45e82f7e93a0a39) …

reef: doc/cephadm: improve "Activate Existing OSDs".

---

doc/mgr/progress.rst

docs/mgr: fix typo

---

src/pybind/mgr/dashboard/controllers/smb.py
src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-form/smb-cluster-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-tabs/smb-cluster-tabs.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-join-auth-list/smb-join-auth-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-join-auth-list/smb-join-auth-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-join-auth-list/smb-join-auth-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-tabs/smb-tabs.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-tabs/smb-tabs.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-tabs/smb-tabs.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-usersgroups-details/smb-usersgroups-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-usersgroups-details/smb-usersgroups-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-usersgroups-details/smb-usersgroups-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-usersgroups-list/smb-usersgroups-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-usersgroups-list/smb-usersgroups-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-usersgroups-list/smb-usersgroups-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb.model.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.ts
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/tests/test_smb.py

Fixes: https://tracker.ceph.com/issues/69361
[screen-capture (56).webm](https://github.com/user-attachments/assets/95e85e17-7d63-417e-8f2e-64fa06d7ca66) …

mgr/dashboard: smb join-auth and usersgroups resources listing

---

src/common/SubProcess.cc
src/common/fork_function.h

This is backport of an original fix https://github.com/ceph/ceph/pull/50622.
Fixes: https://tracker.ceph.com/issues/69777
-----
Fix rook/rook#10110, which occurs when _SC_OPEN_MAX/RLIMIT_NOFILE is set to very large values (2^30), leaving fork_function pegging a core busylooping.
The glibc wrappers closefrom(3)/close_range(3) are not available before glibc 2.34, so we invoke the syscall directly. When glibc 2.34 is old enough to be a reasonable hard minimum dependency, we should switch to using closefrom.
If we're not running on (recent enough) Linux, we fall back to the existing approach.
Fixes: https://tracker.ceph.com/issues/59125
Signed-off-by: edef <edef@edef.eu>
(cherry picked from commit 1a33cefa1980a18b11479275c1f708c1de24ee37) …

reef: common: use close_range on Linux

---

src/client/Client.cc
src/common/ceph_fs.cc
src/test/libcephfs/CMakeLists.txt
src/test/libcephfs/client_cache.cc

Reproduces: https://tracker.ceph.com/issues/69092
Fixes: https://tracker.ceph.com/issues/69092 …

libcephfs/client: pin inode/dentry for an opened directory

---

doc/radosgw/placement.rst
src/common/options/rgw.yaml.in

Improve rgw_max_chunk_size descriptions with respect to HEAD inlining …

Improve rgw_max_chunk_size descriptions with respect to HEAD inlining

---

src/kv/RocksDBStore.cc

Modify to include both files and memtables.
Gives better prediction of data size, especially gives non-zero size when all data is still in memtables. …

kv/RocksDBStore: Improve estimate_prefix_size.

---

src/os/bluestore/BlueStore.cc

Fixes: https://tracker.ceph.com/issues/69240 …

os/bluestore: Fix signed comparison warning

---

src/script/clean-ci

looks like: https://github.com/ceph/ceph-ci/actions/runs/13267198669/job/37037530512#logs …

script/clean-ci: updates for github action

---

doc/rados/operations/pools.rst

doc/rados/operations: Improve pools.rst
- …

doc/rados/operations: Improve pools.rst

---

src/tools/cephfs/top/cephfs-top

Fixes: https://tracker.ceph.com/issues/69669 …

cephfs-top: exception when terminal size greater than PAD_WIDTH

---

src/blk/aio/aio.h
src/client/barrier.cc
src/client/barrier.h

Misc optimizations

---

src/rgw/driver/rados/rgw_rados.cc

in a multi-zonegroup multisite configuration, CopyObject can name buckets in other zonegroups. we call fetch_remote_obj() to perform this copy, but it was crashing due to interaction with the beast frontend's coroutines
Fixes: https://tracker.ceph.com/issues/69169
<details>
</details>

rgw/rados: resolve CopyObject crash from remote zonegroup

---

src/messages/MClientQuota.h
src/messages/MExportCaps.h
src/messages/MExportDirDiscover.h
src/messages/MGetPoolStatsReply.h
src/messages/MHeartbeat.h
src/messages/MMDSOpenIno.h
src/messages/MMonCommand.h
src/messages/MMonCommandAck.h
src/messages/MMonMgrReport.h
src/messages/MOSDMap.h
src/messages/PaxosServiceMessage.h

More like https://github.com/ceph/ceph/pull/60253

messages/*: add missing includes

---

src/common/Graylog.cc
src/exporter/DaemonMetricCollector.cc
src/rgw/driver/rados/rgw_notify.cc
src/test/common/test_ceph_timer.cc
src/test/neorados/completions.cc
src/tools/immutable_object_cache/CacheClient.cc
src/tools/immutable_object_cache/CacheClient.h
src/tools/immutable_object_cache/CacheServer.cc

This does *not* pull up to Boost 1.87. It merely makes it possible to compile on systems with Boost 1.87.
- Tracker …

Boost 1.87 Build Fixes

---

src/crimson/os/seastore/backref_entry.h

crimson/backref_entry: add missing includes

---

src/common/Formatter.cc
src/common/Formatter.h

Formatter code cleanup

---

src/blk/kernel/KernelDevice.cc

This change addresses the 200ms delay observed in the _aio_stop function during the completion of bdev operations.
The _aio_stop function was modified to introduce a wakeup mechanism using a dummy operation
Fixes : [#68881](https://tracker.ceph.com/issues/68881) …

blk/kernel : Make bdev stop immediately

---

src/mds/MDCache.cc

Fixes: https://tracker.ceph.com/issues/69844 …

mds: do not schedule quiesce for non-head imported inodes

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-list/rgw-storage-class-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-list/rgw-storage-class-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-list/rgw-storage-class-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-storage-class.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-storage-class.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/rgw_client.py

Fixes: https://tracker.ceph.com/issues/69733
https://github.com/user-attachments/assets/a684f157-3a48-4a60-88b8-0d40242971e1 …

mgr/dashboard: RGW - Delete storage class

---

qa/workunits/rbd/rbd_mirror_bootstrap.sh
qa/workunits/rbd/rbd_mirror_helpers.sh
src/librbd/api/Mirror.cc
src/tools/rbd/action/MirrorImage.cc
src/tools/rbd/action/MirrorPool.cc

librbd: fix mirror image status summary in a namespace

---

src/cls/2pc_queue/cls_2pc_queue.cc
src/cls/cephfs/cls_cephfs_client.h
src/cls/journal/cls_journal.cc
src/cls/numops/cls_numops.cc
src/cls/rbd/cls_rbd.cc
src/cls/rbd/cls_rbd_client.h
src/cls/rbd/cls_rbd_types.cc
src/cls/rbd/cls_rbd_types.h
src/journal/Entry.h
src/journal/JournalPlayer.cc
src/journal/ObjectRecorder.cc

cls: add missing includes

---

doc/radosgw/bucket_logging.rst

this is updating documentation based on the change in this PR: https://github.com/ceph/ceph/pull/61388
<details>
</details>

doc/rgw/logging: update field description

---

src/pybind/mgr/dashboard/controllers/smb.py
src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-form/smb-cluster-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-list/smb-cluster-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-share-form/smb-share-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-share-form/smb-share-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-share-form/smb-share-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-share-list/smb-share-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-share-list/smb-share-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb.model.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
src/pybind/mgr/dashboard/openapi.yaml

Fixes: https://tracker.ceph.com/issues/69733
https://github.com/user-attachments/assets/11d26e8b-dee5-49b4-9acb-71a72e2d6617
https://github.com/user-attachments/assets/5b82cebb-302a-4eb0-9cac-5dede6524ea6
Note: In my screenshoot as my cluster is not up and recently running on local one so 500 error can be seen but share is being created. …

mgr/dashboard: SMB Create Share

---

src/os/bluestore/BitmapFreelistManager.cc
src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/os/bluestore/Writer.cc

os/bluestore: include cleanup

---

src/common/ceph_strings.cc

Fixes: 8970fef4ecc4dc28011bb57c5150fbdc691279d0
Fixes: 7f1d066756383adae37d61cc2b2f5d99bc167f65 …

common: add missing mds op names

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/pluralize.pipe.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts

Fixes https://tracker.ceph.com/issues/69900
https://github.com/user-attachments/assets/8f002eaf-be82-44d1-8e96-c5a623438598 …

Add namespace counter in nvmeof namepsaces 

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-storage-class.model.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.scss
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-list/rgw-storage-class-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-storage-class.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-storage-class.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/directives/directives.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/directives/optional-field.directive.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/directives/optional-field.directive.ts
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/rgw_client.py
src/pybind/mgr/dashboard/services/service.py

Fixes: https://tracker.ceph.com/issues/69750
Signed-off-by: Dnyaneshwari Talwekar<dtalweka@redhat.com>
https://github.com/user-attachments/assets/0660a504-9f37-455a-bc85-77ee9ac50b1c …

mgr/dashboard: RGW - Create Storage Class

---

src/osd/ReplicatedBackend.cc

Added to help debug: https://tracker.ceph.com/issues/50608
More information: https://gist.github.com/Matan-B/24b49e9b734259f06edf17fdfea5d24d …

osd/ReplicatedBackend: assert non trivial obc existence

---

doc/glossary.rst
doc/start/index.rst

doc/start: Mention RGW in Intro to Ceph
Reaction to a comment made by @nhoad in the community Slack workspace. …

doc/start: Mention RGW in Intro to Ceph

---

doc/cephadm/services/osd.rst

doc/cephadm/services: Improve osd.rst
- …

doc/cephadm/services: Improve osd.rst

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-lifecycle-list/rgw-bucket-lifecycle-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-lifecycle-list/rgw-bucket-lifecycle-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-lifecycle-list/rgw-bucket-lifecycle-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-tiering-form/rgw-bucket-tiering-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-tiering-form/rgw-bucket-tiering-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-tiering-form/rgw-bucket-tiering-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-list/rgw-storage-class-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/utils/rgw-bucket-tiering.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
src/pybind/mgr/dashboard/frontend/src/styles/_carbon-defaults.scss
src/pybind/mgr/dashboard/frontend/src/styles/ceph-custom/_forms.scss
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/rgw_client.py

NOTE:
===
1) On creating a lifecycle rule with filter option selected as both 'Prefix' and 'tags' is not giving correct JSON from rest client. Needs more investigation and will be updated in following PR's. 
2) Deleting all lifecycle rule is not working, will be covered as part of follow up PR.
(https://github.com/ceph/ceph/pull/61781)
https://github.com/user-attachments/assets/2d865713-f462-430e-96d0-c229227e9d06
Fixes: https://tracker.ceph.com/issues/69649 …

mgr/dashboard: bucket lifecycle policy management

---

qa/suites/orch/cephadm/smb/tasks/deploy_smb_basic.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_domain.yaml
src/pybind/mgr/smb/handler.py

mgr/smb: Add profiling configuration to global definition

---

qa/tasks/cephadm.py

We recommend this generally when tearing down a cluster and do so in cephadm-ansible. Doing this avoids any potential timings where the cephadm mgr module attempts to undo any daemon removals as we're cleaning up …

qa/cephadm: stop cephadm mgr module during cleanup

---

src/crimson/common/interruptible_future.h
src/crimson/common/operation.h
src/crimson/os/seastore/onode_manager/staged-fltree/stages/stage.h
src/crimson/osd/ops_executer.cc
src/crimson/osd/ops_executer.h
src/crimson/osd/osd_operations/replicated_request.cc
src/crimson/osd/pg_shard_manager.cc
src/crimson/tools/perf_crimson_msgr.cc

Tested with clang 19 and gcc 13. …

crimson: fix compile errors in clang 19

---

Dockerfile.build
install-deps.sh
make-debs.sh
run-make-check.sh
src/script/build-with-container.py
src/script/buildcontainer-setup.sh
src/script/lib-build.sh
src/script/run-make.sh

backport tracker: https://tracker.ceph.com/issues/69856
---
backport of https://github.com/ceph/ceph/pull/59841
parent tracker: https://tracker.ceph.com/issues/69847

reef: containerized build tools [V2]

---

src/librbd/mirror/snapshot/Utils.cc

get_rollback_snap_id() did not check if the snapshot it was accessing was a mirror snapshot, causing it to crash if it wasn't.
Fixes: https://tracker.ceph.com/issues/70075 …

librbd: fix a crash in get_rollback_snap_id

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-list/smb-cluster-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-share-list/smb-share-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-share-list/smb-share-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-share-list/smb-share-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts

[screen-capture (38).webm](https://github.com/user-attachments/assets/e48bcafa-0ef5-4137-95b7-8b6545d358ec)
- …

mgr/dashboard: add smb delete share action

---

.readthedocs.yml
admin/doc-requirements.txt

https://access.redhat.com/security/cve/CVE-2022-34749
https://bugzilla.redhat.com/show_bug.cgi?id=2255448
Fixes https://github.com/ceph/ceph/pull/44222
Signed-off-by: David Galloway <david.galloway@ibm.com>
(cherry picked from commit 4e2924433612263ae0dee3fc11d9ffa37a1c0346) …

reef: doc: Upgrade and unpin some python versions

---

doc/cephadm/services/osd.rst

doc/cephadm/services: Re-improve osd.rst
Incorporate fixes suggested by @Thingee in #61837  …

doc/cephadm/services: Re-improve osd.rst

---

src/common/options/rgw.yaml.in

src/common/options: Improve descriptions in rgw.yaml.in …

src/common/options: Improve descriptions in rgw.yaml.in

---

src/crimson/osd/backfill_state.h
src/crimson/osd/osd_operation_external_tracking.h
src/crimson/osd/osd_operations/background_recovery.cc
src/crimson/osd/osd_operations/background_recovery.h
src/crimson/osd/osd_operations/peering_event.h
src/crimson/osd/pg.h
src/crimson/osd/pg_recovery.cc
src/crimson/osd/recovery_backend.cc
src/osd/PeeringState.cc

Fixes: https://tracker.ceph.com/issues/68306 …

crimson/osd/pg_recovery: trigger BackfillState events synchronously

---

src/crimson/mgr/client.cc
src/crimson/mgr/client.h
src/crimson/osd/CMakeLists.txt
src/crimson/osd/ops_executer.h
src/crimson/osd/osd.cc
src/crimson/osd/osd.h
src/crimson/osd/osd_operations/client_request.cc
src/crimson/osd/osd_operations/client_request.h
src/crimson/osd/pg.h
src/crimson/osd/shard_services.h
src/osd/DynamicPerfStats.h
src/osd/PrimaryLogPG.cc

crimson/osd: support mgr's dynamic perf stats

---

qa/suites/rados/verify/clusters/openstack.yaml

Fixes: https://tracker.ceph.com/issues/69639 …

qa/suites/rados/verify: Allow selection of 2 or 4 node cluster

---

qa/tasks/thrashosds-health.yaml

The thrash-old-client suite is expected to generate a few warnings that can be safely ignored.
Fixes: https://tracker.ceph.com/issues/67970 …

suite: thrash old client ignore list expend

---

src/CMakeLists.txt

Fixes https://tracker.ceph.com/issues/69732 …

Isolate the absl flags to ceph-mon & ceph-nvmeof-monitor-client targets

---

src/pybind/mgr/cephadm/services/cephadmservice.py

backport tracker: https://tracker.ceph.com/issues/69711
---
backport of https://github.com/ceph/ceph/pull/61530
parent tracker: https://tracker.ceph.com/issues/69567

reef: cephadm: rgw: allow specifying the ssl_certificate by filepath

---

src/client/Client.h

client/Client: add missing include and forward declaration

---

qa/cephfs/overrides/ignorelist_health.yaml

Fixes: https://tracker.ceph.com/issues/70107 …

qa: ignore variant of down fs

---

src/script/ceph-backport.sh

script/ceph-backport: remove upstream remote inferencing

---

doc/cephadm/services/osd.rst

reef: doc/cephadm/services: Re-improve osd.rst

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.scss
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-lifecycle-list/rgw-bucket-lifecycle-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.ts

Fixes: https://tracker.ceph.com/issues/69988
https://github.com/user-attachments/assets/222ccfc2-22d4-4abf-b78f-21b993036a4c …

mgr/dashboard: Update bucket details section after making bucket lifecycle changes

---

doc/releases/releases.yml

Put the releases of Squid in descending order. This change alters the order of the Squid releases so that it is the same as the order of the other Ceph releases. …

doc/releases: correct squid release order

---

src/pybind/mgr/dashboard/controllers/smb.py
src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-share-form/smb-share-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-share-form/smb-share-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-share-list/smb-share-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb.model.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
src/pybind/mgr/dashboard/openapi.yaml

Fixes: https://tracker.ceph.com/issues/70094
https://github.com/user-attachments/assets/73e93fec-5d3b-4782-9d96-f2897217a53c …

mgr/dashboard: SMB - Edit Share

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-bucket-encryption.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-config-modal/rgw-config-modal.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-config-modal/rgw-config-modal.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-configuration-page/rgw-configuration-page.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/rgw-encryption-config-keys.ts
src/pybind/mgr/dashboard/model/rgw.py
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/ceph_service.py

Fixes: https://tracker.ceph.com/issues/67075
Signed-off-by: Prachi prgoel@redhat.com
Changes for GKLM dropdown UI:
1.Added option kmip in KMS dropdown in configuration page RGW
2.Made API dynamic for setting form data for Vault, kmip both for (S3 and
KMS)
3.Both Getdata and setdata API for RGW config page is modified …

mgr/dashboard: Add GKLM(KMIP) option to SSE-KMS dropdown Menu in the RGW configuration

---

src/erasure-code/shec/ErasureCodeShec.cc

erasure-code: add missing include

---

src/kv/RocksDBStore.cc

kv: add missing includes

---

src/os/kstore/KStore.cc
src/os/memstore/MemStore.cc
src/os/memstore/MemStore.h

os/memstore: add missing includes

---

doc/radosgw/dynamicresharding.rst

By https://github.com/ceph/ceph/pull/31686, `radosgw-admin reshard stale-instances rm` was renamed `radosgw-admin reshard stale-instances delete`. This PR follows the change. Similar PR is https://github.com/ceph/ceph/pull/47475. …

doc: fix incorrect radosgw-admin subcommand

---

src/pybind/mgr/dashboard/tox.ini

`tox -e gen-nvmeof-proto` to generate the tox files
Fixes: https://tracker.ceph.com/issues/69995 …

mgr/dashboard: tox command to generate the nvmeof proto files

---

doc/radosgw/dynamicresharding.rst

Signed-off-by: Toshikuni Fukaya <toshikuni-fukaya@cybozu.co.jp>
(cherry picked from commit c3b7d6f19360af90ead61cd5ef8bc73ca1c7fe8f) …

squid: doc: fix incorrect radosgw-admin subcommand

---

doc/rbd/nvmeof-requirements.rst

doc/rbd: Improve nvmeof-requirements.rst with proxy and other info
Informed by a user who reported gRPC-related errors when deploying gateways. …

doc/rbd: Improve nvmeof-requirements.rst with proxy and other info

---

src/pybind/mgr/dashboard/controllers/smb.py
src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-form/smb-cluster-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-form/smb-cluster-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-list/smb-cluster-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb.model.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/smb.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
src/pybind/mgr/dashboard/openapi.yaml

Fixes: https://tracker.ceph.com/issues/69964
https://github.com/user-attachments/assets/3a256c74-11dc-4f77-ae7c-2beda080703e
https://github.com/user-attachments/assets/95d0ac8a-d4fd-432e-ba65-a138daef8f07 …

mgr/dashboard: SMB - Edit Cluster

---

src/common/options/rgw.yaml.in
src/rgw/rgw_appmain.cc
src/rgw/rgw_realm_reloader.cc

Fixes: https://tracker.ceph.com/issues/69617
<details>
</details>

rgw/lua: Add rgw config to enable/disable lua

---

doc/releases/releases.yml

Put the releases of Squid in descending order. This change alters the order of the Squid releases so that it is the same as the order of the other Ceph releases.
(cherry picked from commit 2bd1cc13700cc0e5a92f4d968c3b0e861a5157db) …

squid: doc/releases: correct squid release order

---

qa/suites/orch/cephadm/mgr-nfs-upgrade/1-bootstrap/18.2.0.yaml

Since main should be the T release and we only
support N+2 upgrades, it should start from the
R release
- Tracker …

qa/cephadm: start mgr-nfs-upgrade test from reef

---

src/cephadm/cephadmlib/daemons/smb.py
src/python-common/ceph/deployment/service_spec.py

cephadm/smb: add ctdb ports to smb daemon endpoint

---

qa/tasks/cephfs/test_data_scan.py

call to `self.fs.journal_tool(["journal", "reset", "--force", "--yes-i-really-really-mean-it"], 0)` is already made below it, the same call under `if False` is unreachable. …

qa: remove unreacheable/redundant code from test_data_scan.py

---

doc/rbd/nvmeof-requirements.rst

Address quibbles raised in the course of assessing https://github.com/ceph/ceph/pull/61982. …

doc/rbd: improve nvmeof-requirements.rst

---

src/test/crimson/seastore/CMakeLists.txt

See: https://tracker.ceph.com/issues/70202 …

test/crimson/seastore/CMakeLists: disable unittest-transaction-manager (arm)

---

qa/tasks/cephfs/test_mds_metrics.py

* Fix _setup_fs to reconfigure only the appropriate client auth caps,
by avoiding iterating the self.mounts.
* Delete unused filesystems in test_perf_stats_stale_metrics_with_multiple_filesystem. …

qa: reconfigure only the appropriate client auth caps

---

src/pybind/mgr/volumes/fs/async_job.py

mgr/vol: add a helpful comment in async_job.py

---

src/common/config_cacher.h

In its get_tracked_conf_keys() member function, the cacher (in the existing code) initializes
a static function-block variable ('keys'), and uses it for registering the observer.
But the cacher is instantiated on the type of the configuration value. Thus, multiple cacher
objects for which the configuration values are of the same type - share the static 'keys'. Only
one of the observers is registered.
Note that the code could have been simplified somewhat, if the signature of the
get_tracked_conf_keys() function was changed to return 'const char* const *'.
Backport of https://github.com/ceph/ceph/pull/61289
Original tracker: https://tracker.ceph.com/issues/69236
Backport tracker: https://tracker.ceph.com/issues/69531
(cherry picked from commit 8ac04704574671e72de6f3ba30c1c3baa39a6319)

reef: common: fix md_config_cacher_t

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/model/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml

A trash_image param is introduced to create namespace API. When that is
set, if the user force remove the namepsace it'll also remove the rbd
image.
https://github.com/user-attachments/assets/5bce9f7f-4c13-4316-9d56-956ea11245e7
Fixes: https://tracker.ceph.com/issues/69787 …

mgr/dashboard: nvmeof trash rbd image on namespace rm

---

doc/rados/operations/stretch-mode.rst

(cherry picked from commit 75be0272e8469ed214302b8f354bed675cdcaed6) …

squid: doc/rados/operations: Clarify stretch mode vs device class

---

src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.cc
src/crimson/os/seastore/omap_manager/btree/string_kv_node_layout.h

crimson/os/seastore/omap_manager: do binary search on omap nodes

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-storage-class.model.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-list/rgw-storage-class-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-list/rgw-storage-class-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-storage-class.service.ts
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/rgw_client.py

Fixes: https://tracker.ceph.com/issues/70016
https://github.com/user-attachments/assets/1d1b80af-9734-4a18-9c02-4923f73fc05f …

mgr/dashboard: RGW - Edit Storage Class

---

src/crimson/admin/osd_admin.cc
src/crimson/common/config_proxy.h
src/crimson/common/errorator-loop.h
src/crimson/common/interruptible_future.h
src/crimson/osd/main.cc
src/crimson/osd/main_config_bootstrap_helpers.cc
src/crimson/osd/osd_operations/pg_advance_map.cc
src/crimson/osd/shard_services.cc
src/crimson/osd/stop_signal.h
src/test/crimson/seastore/CMakeLists.txt
src/test/crimson/test_alienstore_thread_pool.cc
src/test/crimson/test_crimson_scrub.cc

Bump up seastar submodule to https://github.com/ceph/seastar/commits/wip-matanb-seastar-feb-25/
~https://github.com/ceph/seastar/commit/b4271a0b7db54032a2803ad6e14b8c5c8ee5b1c2 is also pushed to allow boost upgrade to 1.87 (until the fixes will be merged in the main repo)  - CC: @adamemerson~
edit: https://github.com/scylladb/seastar/pull/2639 was merged, rebasing.
Fixes: https://tracker.ceph.com/issues/66905
- When filling out …

seastar: bump up seastar submodule

---

src/rgw/rgw_zone.cc

added a check and set inline_data to true if the default value was not true
Fixes: https://tracker.ceph.com/issues/67933
Signed-off-by: umesh-mv <umeshmuthuvara@gmail.com> …

rgw/rgw_zone : fixing inline-data default value

---

qa/suites/rgw/multisite/tasks/test_multi.yaml
src/rgw/rgw_auth_filters.h
src/test/rgw/rgw_multi/tests.py

fixes https://tracker.ceph.com/issues/69124 …

rgw/multisite: fix forwarded requests for tenanted buckets

---

src/tools/ceph_objectstore_tool.cc

Fixes: https://tracker.ceph.com/issues/66802
Backport of: https://tracker.ceph.com/issues/66802
tracker: https://tracker.ceph.com/issues/67080
Signed-off-by: Pere Diaz Bou <pere-altea@hotmail.com>
(cherry picked from commit eb538ebd5955940ef2d7752e4e710d76c4ed4f5d) …

squid: tools/objectstore: check for wrong coll open_collection #58353

---

qa/tasks/cephfs/test_journal_repair.py
src/tools/cephfs/Dumper.cc

Fixes: https://tracker.ceph.com/issues/68928 …

cephfs-journal-tool: fix segfault during 'journal import' from invalid dump file

---

src/os/bluestore/BlueStore.cc

do_write_v2 insert extentmap by aligned offset, if fault_range use original offet~length,
may not cover the proper extentmap range. …

os/bluestore: fix fault_range for _do_write_v2

---

src/os/bluestore/BlueStore.cc

Assigning a named variable to ceph::time_guard to prevent immediate destruction
Tracker Ticket : https://tracker.ceph.com/issues/70132 …

os/bluestore : Assigning a named variable to ceph::time_guard to prevent immediate destruction

---

src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/test/objectstore/store_test.cc

Fixes: https://tracker.ceph.com/issues/69507 …

os/bluestore: do cache locally compressor engines ever used.

---

src/tools/ceph_objectstore_tool.cc

Parent tracker: https://tracker.ceph.com/issues/66802
Backports: https://github.com/ceph/ceph/pull/58353
Backport tracker: https://tracker.ceph.com/issues/67080
(cherry picked from commit eb538ebd5955940ef2d7752e4e710d76c4ed4f5d)
This is a full replica of https://github.com/ceph/ceph/pull/58732/ as Pere is apparently not planning to maintain it. …

squid: tools/objectstore: check for wrong coll open_collection

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts
src/pybind/mgr/dashboard/openapi.yaml

backport tracker: https://tracker.ceph.com/issues/70124
---
backport of https://github.com/ceph/ceph/pull/61698
parent tracker: https://tracker.ceph.com/issues/69864

squid: mgr/dashboard: (refactor)fix image size in nvmeof namespace create/update api

---

qa/tasks/mgr/dashboard/helper.py
qa/tasks/mgr/dashboard/test_mgr_module.py

based on the pointer from Bill in https://tracker.ceph.com/issues/62972#note-75
Fixes: https://tracker.ceph.com/issues/62972 …

qa/tests: retry the api call after making the request

---

src/common/options/global.yaml.in
src/os/CMakeLists.txt
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h

squid: os/bluestore: Add health warning for bluestore fragmentation

---

ContainerBuild.md
Dockerfile.build
README.md
src/script/build-with-container.py
src/script/buildcontainer-setup.sh

Fixes: https://tracker.ceph.com/issues/70103
A set of features and enhancements for the build-with-container.py tool (and related).
<details>
</details>

build-with-container: fixes and enhancements

---

qa/tasks/ceph.py
qa/tasks/cephadm.py
qa/tasks/rook.py

backport tracker: https://tracker.ceph.com/issues/69572
---
backport of https://github.com/ceph/ceph/pull/48539
parent tracker: https://tracker.ceph.com/issues/57864

squid: qa/tasks: Include stderr on tasks badness check.

---

src/rgw/rgw_lc.cc

This PR is backport of fixes of the below tracker-
https://tracker.ceph.com/issues/65160
https://tracker.ceph.com/issues/57162
Fixes: https://tracker.ceph.com/issues/65667
Signed-off-by:  Soumya Koduri <skoduri@redhat.com>
<details>
- `jenkins test ceph-volume …

reef: rgw: Fix LC process stuck issue

---

doc/radosgw/layout.rst

doc/radosgw: Improve layout.rst
- Tracker …

doc/radosgw: Improve layout.rst

---

src/include/rbd/librbd.h
src/include/rbd/librbd.hpp
src/librbd/api/DiffIterate.cc
src/librbd/api/DiffIterate.h
src/librbd/api/Trash.cc
src/librbd/librbd.cc
src/pybind/rbd/c_rbd.pxd
src/pybind/rbd/mock_rbd.pxi
src/pybind/rbd/rbd.pyx
src/test/librbd/test_internal.cc
src/test/pybind/test_rbd.py

backport tracker: https://tracker.ceph.com/issues/70304
---
backport of https://github.com/ceph/ceph/pull/60844
parent tracker: https://tracker.ceph.com/issues/65720

reef: librbd: add rbd_diff_iterate3() API to take source snapshot by ID

---

qa/suites/big/rados-thrash/openstack.yaml
qa/suites/rados/basic/clusters/openstack.yaml
qa/suites/rados/perf/openstack.yaml
qa/suites/rados/thrash-erasure-code-big/cluster/openstack.yaml
qa/suites/rados/thrash-erasure-code-shec/clusters/openstack.yaml
qa/suites/rados/thrash-old-clients/clusters/openstack.yaml
qa/suites/rados/thrash/clusters/openstack.yaml
qa/suites/rados/verify/clusters/openstack.yaml
qa/suites/rbd/basic/clusters/openstack.yaml
qa/suites/rbd/device/cluster/openstack.yaml
qa/suites/rbd/encryption/clusters/openstack.yaml
qa/suites/rbd/immutable-object-cache/clusters/openstack.yaml
qa/suites/rbd/iscsi/cluster/openstack.yaml
qa/suites/rbd/librbd/clusters/openstack.yaml
qa/suites/rbd/maintenance/clusters/openstack.yaml
qa/suites/rbd/migration/2-clusters/openstack.yaml
qa/suites/rbd/mirror-thrash/cluster/openstack.yaml
qa/suites/rbd/pwl-cache/home/2-cluster/openstack.yaml
qa/suites/rbd/pwl-cache/tmpfs/2-cluster/openstack.yaml
qa/suites/rbd/qemu/clusters/openstack.yaml
qa/suites/rbd/singleton-bluestore/openstack.yaml
qa/suites/rbd/singleton/openstack.yaml
qa/suites/rbd/thrash/clusters/openstack.yaml
qa/suites/smoke/basic/clusters/openstack.yaml
qa/suites/upgrade/quincy-x/filestore-remove-check/0-cluster/openstack.yaml

Fixes: https://tracker.ceph.com/issues/69834 …

qa: Remove openstack.yaml file which is no longer relevant

---

doc/releases/releases.yml

doc/releases: Add ordering comment to releases.yml
Followup to PR #61985 nothing that for the Gantt chart to properly reflect the latest version in a release train the releases must be in descending order within the release's list. …

doc/releases: Add ordering comment to releases.yml

---

doc/releases/releases.yml

(cherry picked from commit 2290a904bd6a3194f77b76d7deb0c9d24c8b4b93) …

squid: doc/releases: Add ordering comment to releases.yml

---

doc/releases/releases.yml

(cherry picked from commit 2290a904bd6a3194f77b76d7deb0c9d24c8b4b93) …

reef: doc/releases: Add ordering comment to releases.yml

---

src/pybind/mgr/dashboard/services/proto/gateway.proto
src/pybind/mgr/dashboard/services/proto/gateway_pb2.py
src/pybind/mgr/dashboard/services/proto/gateway_pb2_grpc.py

Fixes: https://tracker.ceph.com/issues/70330 …

mgr/dashboard: update dashboard nvmeof proto files

---

src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/test/objectstore/test_deferred.cc

Fixes known problems with deferred write replay.
Based on unittest for deferred writes #60732
Fixes: https://tracker.ceph.com/issues/68060 …

os/bluestore: Fix problem with deferred writes replay

---

qa/workunits/rbd/luks-encryption.sh
qa/workunits/rbd/rbd-nbd.sh

Implement the same logic as in commit 6f3d0f570f1a ("test/librbd/fsx: wait for resize to propagate in krbd_resize()").
Fixes: https://tracker.ceph.com/issues/66419 …

qa/workunits/rbd: wait for resize to be applied in rbd-nbd

---

src/pybind/mgr/cephadm/schedule.py
src/pybind/mgr/cephadm/serve.py
src/pybind/mgr/cephadm/services/cephadmservice.py
src/pybind/mgr/cephadm/services/nvmeof.py
src/pybind/mgr/cephadm/tests/test_cephadm.py
src/pybind/mgr/cephadm/tests/test_scheduling.py

mgr/cephadm: block deploying nvmeof daemons of different groups on same host

---

monitoring/ceph-mixin/dashboards/cephfs.libsonnet
monitoring/ceph-mixin/dashboards/timeseries_panel.libsonnet
monitoring/ceph-mixin/dashboards_out/cephfs-overview.json

Fixes:- https://tracker.ceph.com/issues/69404
Grafana Dashboard before changing SimpleGraphPanel to TimeSeriesPanel and changing SpanNulls Value to True:-
https://github.com/user-attachments/assets/8862bba0-eaea-4f3c-9949-0bcc47405d8f
Grafana Dashboard after changing SimpleGraphPanel to TimeSeriesPanel and changing SpanNulls Value to True:-
https://github.com/user-attachments/assets/75be0896-fb56-4c72-955e-4646555e7735
- When …

mgr/dashboard: Changing SimpleGraphPanel to TimeSeries Panel in cephfs.libsonnet to fix inconsistency in Line Graphs

---

monitoring/ceph-mixin/dashboards/host.libsonnet
monitoring/ceph-mixin/dashboards_out/host-details.json
monitoring/ceph-mixin/dashboards_out/hosts-overview.json

Fixes:- https://tracker.ceph.com/issues/70228
Grafana Dashboard before changing SimpleGraphPanel to TimeSeriesPanel and changing SpanNulls Value to True:-
https://github.com/user-attachments/assets/188a431e-db56-4fab-a5e7-3ed804a37c95
Grafana Dashboard after changing SimpleGraphPanel to TimeSeriesPanel and changing SpanNulls Value to True:-
https://github.com/user-attachments/assets/c9568fa3-8aba-4a2d-98af-a00887931dee
- When …

mgr/dashboard: Changing SimpleGraphPanel to TimeSeries Panel in host.libsonnet to fix inconsistency in Line Graphs

---

monitoring/ceph-mixin/dashboards/osd.libsonnet
monitoring/ceph-mixin/dashboards_out/osd-device-details.json
monitoring/ceph-mixin/dashboards_out/osds-overview.json

Fixes:- https://tracker.ceph.com/issues/70227
Grafana Dashboard before changing SimpleGraphPanel to TimeSeriesPanel and changing SpanNulls Value to True:-
https://github.com/user-attachments/assets/606d9751-26c5-48b9-97f7-08f0b537fdd7
Grafana Dashboard after changing SimpleGraphPanel to TimeSeriesPanel and changing SpanNulls Value to True:-
https://github.com/user-attachments/assets/c5b013a1-8bf0-41e0-9188-d9ec02c85fac
- When …

mgr/dashboard: Changing SimpleGraphPanel to TimeSeries Panel in osd.libsonnet to fix inconsistency in Line Graphs 

---

monitoring/ceph-mixin/dashboards/pool.libsonnet
monitoring/ceph-mixin/dashboards_out/pool-detail.json
monitoring/ceph-mixin/dashboards_out/pool-overview.json

Fixes:- https://tracker.ceph.com/issues/70229
Grafana Dashboard before changing SimpleGraphPanel to TimeSeriesPanel and changing SpanNulls Value to True:-
https://github.com/user-attachments/assets/2ce76e7a-8035-4cf3-bad9-f424014f11a0
Grafana Dashboard after changing SimpleGraphPanel to TimeSeriesPanel and changing SpanNulls Value to True:-
https://github.com/user-attachments/assets/afc38bb7-bf88-4bc6-b2ec-32c2942f8904
- When …

mgr/dashboard: Changing SimpleGraphPanel to TimeSeries Panel in pool.libsonnet to fix inconsistency in Line Graphs

---

src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/test/objectstore/test_deferred.cc

Revert https://github.com/ceph/ceph/pull/60753 …

Revert "os/bluestore: Fix problem with deferred writes replay"

---

doc/cephadm/services/mgmt-gateway.rst
src/pybind/mgr/orchestrator/module.py
src/python-common/ceph/deployment/service_spec.py

mgr/cephadm: Add virtual_ip as a param for mgmt-gateway apply cmd

---

src/crimson/osd/recovery_backend.cc
src/crimson/osd/recovery_backend.h
src/crimson/osd/replicated_recovery_backend.cc
src/test/crimson/test_crimson_coroutine.cc

* move scan_for_backfill to coroutine 
* let obc_loader get the relevant obc and avoid duplicating the loading logic.
* Fixes: https://tracker.ceph.com/issues/69154 …

crimson/osd/recovery_backend: scan_for_backfill to use obc_manager

---

src/os/bluestore/bluestore_tool.cc

Backports: https://github.com/ceph/ceph/pull/45384
Fixes: https://tracker.ceph.com/issues/69261
Parent tracker: https://tracker.ceph.com/issues/54555 …

squid: tool/ceph-bluestore-tool: fix wrong keyword for 'free-fragmentation' command

---

doc/monitoring/index.rst

doc/monitoring: Improve index.rst
Formatting, capitalization, tighten up wording, etc. …

doc/monitoring: Improve index.rst

---

doc/monitoring/index.rst

(cherry picked from commit 1bc67295c8b75475455ff702998ae4d7fb2ec749) …

reef: doc/monitoring: Improve index.rst

---

src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.e2e-spec.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/multisite.po.ts
src/pybind/mgr/dashboard/frontend/cypress/support/e2e.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.html

**BEFORE**
**AFTER**
Fixes: https://tracker.ceph.com/issues/69925
- Component …

mgr/dashboard: fix multisite wizard form not showing 

---

doc/rados/operations/crush-map-edits.rst

(cherry picked from commit 59a894713a9e3540ed74c763cf856636bf300099) …

squid: doc/rados/operations: improve crush-map-edits.rst

---

doc/rados/operations/crush-map-edits.rst

(cherry picked from commit 59a894713a9e3540ed74c763cf856636bf300099) …

reef: doc/rados/operations: improve crush-map-edits.rst

---

doc/rados/troubleshooting/troubleshooting-pg.rst

(cherry picked from commit 56a21cbc03e352867608c4cf0623d5566fb60cc8) …

squid: doc/rados/troubleshooting: Improve troubleshooting-pg.rst

---

doc/rados/troubleshooting/troubleshooting-pg.rst

(cherry picked from commit 56a21cbc03e352867608c4cf0623d5566fb60cc8) …

reef: doc/rados/troubleshooting: Improve troubleshooting-pg.rst

---

src/crimson/os/seastore/omap_manager/btree/btree_omap_manager.h
src/crimson/os/seastore/onode.h
src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/seastore.h
src/crimson/os/seastore/seastore_types.h

Follow-up:
https://github.com/ceph/ceph/pull/59213#discussion_r1915937112
https://github.com/ceph/ceph/pull/59213#discussion_r1915978794 …

crimson/os/seastore: cleanups related to managing omap and log tree 

---

src/pybind/mgr/volumes/fs/async_cloner.py
src/pybind/mgr/volumes/fs/async_job.py

Fixes: https://tracker.ceph.com/issues/70376 …

mgr/vol: correct logger names

---

src/pybind/mgr/volumes/fs/stats_util.py

mgr/vol: use error number instead of error message

---

src/pybind/mgr/dashboard/frontend/package-lock.json
src/pybind/mgr/dashboard/frontend/package.json
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-migrate/rgw-multisite-migrate.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-migrate/rgw-multisite-migrate.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zonegroup-form/rgw-multisite-zonegroup-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zonegroup-form/rgw-multisite-zonegroup-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.ts

When configuring the RGW Multisite endpoints from the UI allow FQDN, at the moment when using a FQDN it's not allowed
Fixes: https://tracker.ceph.com/issues/69055
https://github.com/user-attachments/assets/d4976a45-1379-4404-8ea5-a5f6a95aa787 …

mgr/dashboard: When configuring the RGW Multisite endpoints from the UI allow FQDN(Not only IP)

---

doc/dev/developer_guide/essentials.rst

Update information for subscribing to Ceph development mailing lists as current documentation is outdated.
Fixes: https://tracker.ceph.com/issues/64580
(cherry picked from commit e7bf607269335ac40d91cb4b8f265064ffaac402) …

squid: doc/dev/developer_guide/essentials: update mailing lists

---

doc/dev/developer_guide/essentials.rst

Update information for subscribing to Ceph development mailing lists as current documentation is outdated.
Fixes: https://tracker.ceph.com/issues/64580
(cherry picked from commit e7bf607269335ac40d91cb4b8f265064ffaac402) …

reef: doc/dev/developer_guide/essentials: update mailing lists

---

src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/users.e2e-spec.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/users.po.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.ts

Fixes: https://tracker.ceph.com/issues/70450
https://github.com/user-attachments/assets/944819ea-9869-43b1-aeac-12a2535cb239 …

mgr/dashboard: Fix rgw user key modal not shown

---

monitoring/ceph-mixin/dashboards.libsonnet
monitoring/ceph-mixin/dashboards/smb-overview.libsonnet
monitoring/ceph-mixin/dashboards_out/smb-overview.json
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-overview/smb-overview.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-overview/smb-overview.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-overview/smb-overview.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-tabs/smb-tabs.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-tabs/smb-tabs.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-tabs/smb-tabs.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb.module.ts

[screen-capture (84).webm](https://github.com/user-attachments/assets/65ca62c2-862f-477e-bb4d-d20f0f1b5ae5)
- …

monitoring: add SMB overview grafana dashboard

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/rgw_client.py
src/pybind/mgr/dashboard/tests/test_rgw.py

Fixes: https://tracker.ceph.com/issues/69229
Signed-off-by: Puja Shahu <pshahu@redhat.com> …

mgr/dashboard: Add RGW topics endpoint creation for create ,delete and list in dashboard

---

src/client/Client.cc
src/client/Client.h
src/common/ceph_strings.cc
src/common/options/mds-client.yaml.in
src/common/options/mds.yaml.in
src/include/ceph_fs.h
src/include/cephfs/libcephfs.h
src/libcephfs.cc
src/mds/MDCache.cc
src/mds/MDCache.h
src/mds/Server.cc
src/mds/Server.h
src/mds/mdstypes.cc
src/mds/mdstypes.h
src/test/libcephfs/snapdiff.cc
src/tools/rados/rados.cc

mds/client: file blockdiff support

---

src/pybind/mgr/dashboard/controllers/nfs.py
src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/models/nfs-cluster-config.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-cluster-details/nfs-cluster-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-cluster-details/nfs-cluster-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-cluster-details/nfs-cluster-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-cluster/nfs-cluster.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-cluster/nfs-cluster.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-cluster/nfs-cluster.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-list/nfs-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-list/nfs-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-list/nfs-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nfs.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nfs.service.ts
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/nfs/module.py

Fixes: https://tracker.ceph.com/issues/70022
Signed-Off-by: Achint Kaur<ackaur@redhat.com>
https://github.com/user-attachments/assets/89981bad-fdec-4850-ab3d-9a9913f0b9b2 …

mgr/dashboard: NFS Cluster and Export Listing

---

CMakeLists.txt
cmake/modules/BuildBoost.cmake
cmake/modules/FindBoost.cmake
install-deps.sh
make-dist
src/CMakeLists.txt
win32_deps_build.sh

For reasons of Python and Asio valgrinding. …

Boost 1.87

---

doc/cephadm/services/osd.rst

doc/cephadm/services: Correct indentation in osd.rst
Also add an example of ``ceph orch device ls --wide`` and several minor tweaks. …

doc/cephadm/services: Correct indentation in osd.rst

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.ts

Fixes: https://tracker.ceph.com/issues/70284
Issue - As path was disabled. Request body was not having path in it. So api was failing and we were not able to submit edit request.
Response -> {
"status": "500 Internal Server Error",
"detail": "The server encountered an unexpected condition which prevented it from fulfilling the request.",
"request_id": "af7a97da-3174-422f-85e5-d039075766c8"
}
Solution - Including path and fsal in the request body for edit nfs export.
Subvolume Group and Subvolume will be hidden while editing.
https://github.com/user-attachments/assets/dd7ff125-436c-4cc7-ba3a-6b521862bf3e …

mgr/dashboard: NFS - Fix Edit NFS export request 

---

doc/cephadm/services/osd.rst

(cherry picked from commit 7b5f73f4c17acc7cd0aab87db528e5232c8f05e1) …

reef: doc/cephadm/services: Correct indentation in osd.rst

---

doc/cephadm/services/osd.rst

doc/cephadm/services: Add mention of --zap for OSD removal …

doc/cephadm/services: Add mention of --zap for OSD removal

---

doc/cephadm/services/osd.rst

(cherry picked from commit 20b621fceb865403e19e1d7876f81e670829ff59) …

reef: doc/cephadm/services: Add mention of --zap for OSD removal

---

doc/cephadm/services/osd.rst

(cherry picked from commit 20b621fceb865403e19e1d7876f81e670829ff59) …

squid: doc/cephadm/services: Add mention of --zap for OSD removal

---

doc/radosgw/layout.rst

(cherry picked from commit a7e2fab008519416d5bd91f2163ea51e82c440af) …

squid: doc/radosgw: Improve layout.rst

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-initiators-list/nvmeof-initiators-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-list/nvmeof-listeners-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-list/nvmeof-namespaces-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-details/rgw-multisite-sync-policy-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy/rgw-multisite-sync-policy.component.html

Resolved the misalignment issue of the Create-action button.
Fixes:https://tracker.ceph.com/issues/70433
Signed-off-by: Ankit Kumar <51ankitkp@gmail.com>
before:
after: 

mgr/dashboard:fixed alignment of create action button

---

src/pybind/mgr/dashboard/controllers/rgw_iam.py
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-user-accounts.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-user-accounts.service.ts
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/rgw_iam.py
src/pybind/mgr/dashboard/tests/test_rgw_iam.py

Fixes: https://tracker.ceph.com/issues/69487
**Performance** of API got significantly improved from fetching 10 account details in 10sec to fetching them in just 1sec.
https://github.com/user-attachments/assets/82ce771e-54be-4162-bd60-ae59b0258f4f …

mgr/dashboard: Use admin ops API for rgw accounts

---

src/pybind/mgr/dashboard/frontend/src/app/shared/components/notifications-sidebar/notifications-sidebar.component.html

Fixes: https://tracker.ceph.com/issues/70583
**BEFORE**
**AFTER**
- Component …

mgr/dashboard: fix notification icon size 

---

src/tools/rados/rados.cc

tools/rados: generalize the OMAP benchmarking to cover listing as well

---

doc/rados/configuration/network-config-ref.rst

doc/rados/configuration: Add iptables change admonition to network-config.rst …

doc/rados/configuration: Add iptables change admonition to network-config.rst

---

src/cephadm/cephadm.py
src/cephadm/cephadmlib/container_engines.py
src/cephadm/cephadmlib/container_lookup.py
src/cephadm/cephadmlib/listing.py
src/cephadm/cephadmlib/listing_updaters.py
src/cephadm/tests/test_cephadm.py
src/cephadm/tox.ini

cephadm: refactor the core of list_daemons

---

qa/cephfs/mount/kclient/overrides/distro/stock/rhel_8.yaml
qa/cephfs/mount/kclient/overrides/distro/stock/ubuntu_22.04.yaml

reef: qa/cephfs: switch to ubuntu 22.04 for stock kernel testing

---

doc/dev/developer_guide/essentials.rst
doc/start/get-involved.rst

The invite links expires after 30 days. Here's a new one.
- …

doc: Update Slack invite links

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/core/layouts/workbench-layout/workbench-layout.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/api/mgr-module.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/mgr-module.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/telemetry-notification/telemetry-notification.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/module-status-guard.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/shared.module.ts

Enable/Disable mgr modules from SMB page, Rgw multisite Page and Mgr Modules page doesn't give proper message and doesn't block the UI This PR intends to fix this issue
Fixes: https://tracker.ceph.com/issues/70557
https://github.com/user-attachments/assets/a1ac3649-bb43-4935-8919-8881478bbd11 …

mgr/dashboard: fix blockUI implementation 

---

qa/suites/crimson-rados/basic/objectstore/seastore-segmented.yaml
qa/suites/crimson-rados/basic/objectstore/seastore/seastore-rbm.yaml
qa/suites/crimson-rados/basic/objectstore/seastore/seastore-segmented.yaml
qa/suites/crimson-rados/perf/objectstore/seastore-segmented.yaml
qa/suites/crimson-rados/perf/objectstore/seastore/seastore-rbm.yaml
qa/suites/crimson-rados/perf/objectstore/seastore/seastore-segmented.yaml
qa/suites/crimson-rados/rbd/objectstore/seastore-segmented.yaml
qa/suites/crimson-rados/rbd/objectstore/seastore/seastore-rbm.yaml
qa/suites/crimson-rados/rbd/objectstore/seastore/seastore-segmented.yaml
qa/suites/crimson-rados/singleton/objectstore/seastore-segmented.yaml
qa/suites/crimson-rados/singleton/objectstore/seastore/seastore-rbm.yaml
qa/suites/crimson-rados/singleton/objectstore/seastore/seastore-segmented.yaml

https://pulpito.ceph.com/myoungwon-2025-03-18_06:34:20-crimson-rados:basic-wip-qa-seastore-rbm-remaining-distro-default-smithi/
https://pulpito.ceph.com/myoungwon-2025-03-18_07:40:36-crimson-rados:perf-wip-qa-seastore-rbm-remaining-distro-default-smithi/
https://pulpito.ceph.com/myoungwon-2025-03-18_08:31:33-crimson-rados:singleton-wip-qa-seastore-rbm-remaining-distro-default-smithi/
https://pulpito.ceph.com/myoungwon-2025-03-18_09:17:53-crimson-rados:rbd-wip-qa-seastore-rbm-remaining-distro-default-smithi/ …

qa/suites/crimson-rados: add seastore with RBM test under the remaining tests

---

doc/rados/configuration/bluestore-config-ref.rst

Commit 3879e4ad417d lowercased several commands. This fixes the remaining typos.
Signed-off-by: Dan van der Ster <dan.vanderster@clyso.com>
(cherry picked from commit 5e40ec969cdca758263c9f59ca6613a280b6f2a2) …

reef: doc/rados/configuration/bluestore-config-ref: Fix lowercase typos

---

doc/rados/configuration/bluestore-config-ref.rst

Commit 3879e4ad417d lowercased several commands. This fixes the remaining typos.
Signed-off-by: Dan van der Ster <dan.vanderster@clyso.com>
(cherry picked from commit 5e40ec969cdca758263c9f59ca6613a280b6f2a2) …

squid: doc/rados/configuration/bluestore-config-ref: Fix lowercase typos

---

doc/architecture.rst

Remove a sentence that is more marketing than reference.
(cherry picked from commit 00b530fc975a1f364a58f7c1ed1cf9dcf28ef299) …

reef: doc/architecture: remove sentence

---

doc/cephadm/services/osd.rst

Change "Remove an OSD" to "Monitoring OSD State During OSD Removal" and reword a sentence so that it more clearly refers to the process under discussion.
(cherry picked from commit 4ab3bed3f6aa466a1d11aec0d9bd8687ccfb0125) …

reef: doc/cephadm: clarify "Monitoring OSD State"

---

doc/cephadm/services/osd.rst

Change "Remove an OSD" to "Monitoring OSD State During OSD Removal" and reword a sentence so that it more clearly refers to the process under discussion.
(cherry picked from commit 4ab3bed3f6aa466a1d11aec0d9bd8687ccfb0125) …

squid: doc/cephadm: clarify "Monitoring OSD State"

---

doc/rados/operations/stretch-mode.rst

Added more content and rewrite some sections
Signed-off-by: Kamoltat Sirivadhna <ksirivad@redhat.com>
(cherry picked from commit 8cc7fdbd29e1bf936b33256c74d48e23d75eaf96) …

reef: doc/rados/operations/stretch-mode: Improve doc

---

doc/radosgw/s3/commons.rst

instead of referring to "vhost-style", copy the "path-style" and "virtual-hosted-style" language from https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html
expand the FQDN acronym to avoid potential confusion
"The second method is deprecated by AWS" had incorrectly referred to the vhost-style method - clarify that it refers to path-style access
(cherry picked from commit c61c314ed6482cc26cf69ed7e2af4af20bebd676) …

reef: doc/rgw: clarify path-style vs virtual-hosted-style access

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/cluster.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-v3.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard/dashboard.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard/health/health.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard/health/health.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-sync-data-info/rgw-sync-data-info.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-sync-data-info/rgw-sync-data-info.component.scss
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-sync-data-info/rgw-sync-data-info.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-sync-metadata-info/rgw-sync-metadata-info.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-sync-metadata-info/rgw-sync-metadata-info.component.scss
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-sync-metadata-info/rgw-sync-metadata-info.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
src/pybind/mgr/dashboard/frontend/src/styles/_carbon-defaults.scss

Fixes: https://tracker.ceph.com/issues/68259
Signed-off-by: Prachi prgoel@redhat.com
Below are the changes from bootstrap popover to carbon popover:
1. Dashboard v3
2. Health Component
3. RGW sync data component
4. RGW sync metadata component …

mgr/dashboard: replace ngb-popover with carbon popover

---

doc/rados/operations/erasure-code.rst

doc/rados/operations: Improve erasure-code.rst …

doc/rados/operations: Improve erasure-code.rst

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-user.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-list/rgw-user-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-list/rgw-user-list.component.ts
src/pybind/mgr/dashboard/openapi.yaml

PR Introduces:
====
This PR introduces the feature to link a user with an account and can also make changes to make a user as a "Account Root User "
https://github.com/user-attachments/assets/6f5e4020-0489-403a-a36d-9d467cf14d1e
**Updated screencast:**
1) If user is using accounts then only show them on top of the user form
2) move account name after tenant in user list table
https://github.com/user-attachments/assets/e3602fce-0ded-4600-83b2-6f334f4f9a6d
Fixes: https://tracker.ceph.com/issues/69529 …

mgr/dashboard: Link rgw user with account

---

src/pybind/mgr/snap_schedule/fs/schedule.py

mgr/snap_schedule: fix typo in timestamp format exception

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-form/smb-cluster-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-advanced-fieldset/form-advanced-fieldset.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-advanced-fieldset/form-advanced-fieldset.component.ts

Fixes: https://tracker.ceph.com/issues/70693
[screen-capture (88).webm](https://github.com/user-attachments/assets/0b4aa0c8-0c28-4a23-9d7d-e98ed6d95bc2) …

mgr/dashboard: add separation for service section in smb cluster form

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-list/smb-cluster-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-tabs/smb-cluster-tabs.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-tabs/smb-cluster-tabs.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-join-auth-list/smb-join-auth-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-share-list/smb-share-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-tabs/smb-tabs.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-usersgroups-list/smb-usersgroups-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts
src/pybind/mgr/dashboard/frontend/src/styles/_carbon-defaults.scss

Fixes: https://tracker.ceph.com/issues/70695
[screen-capture (87).webm](https://github.com/user-attachments/assets/14ad8616-bd22-4390-adc4-c5bf367510e6)
Also updates share tab …

mgr/dashboard: carbonize smb tabs

---

PendingReleaseNotes

PendingReleaseNotes: add note to change default EC plugin from Jerasure to ISA-L

---

qa/suites/rados/objectstore/backends/objectcacher-stress.yaml
qa/workunits/osdc/object_cacher_misc.sh
src/osdc/ObjectCacher.cc
src/osdc/ObjectCacher.h
src/test/osdc/CMakeLists.txt
src/test/osdc/object_cacher_misc.cc

Fixes: https://tracker.ceph.com/issues/62918 …

osdc/ObjectCacher: avoid io blocking for bufferheads exceed limit

---

doc/radosgw/cloud-restore.rst
doc/radosgw/cloud-transition.rst

doc/radosgw: Improve cloud-restore and cloud-transition …

doc/radosgw: Improve cloud-restore and cloud-transition

---

doc/radosgw/cloud-restore.rst
doc/radosgw/cloud-transition.rst

(cherry picked from commit 6a6807470850ea972c5c3786be3735d26875b221) …

squid: doc/radosgw: Improve cloud-restore and cloud-transition

---

doc/radosgw/cloud-restore.rst
doc/radosgw/cloud-transition.rst

(cherry picked from commit 6a6807470850ea972c5c3786be3735d26875b221) …

reef: doc/radosgw: Improve cloud-restore and cloud-transition

---

PendingReleaseNotes
src/rgw/driver/rados/rgw_bucket.cc
src/rgw/driver/rados/rgw_bucket.h
src/rgw/driver/rados/rgw_cr_rados.cc
src/rgw/driver/rados/rgw_cr_rados.h
src/rgw/driver/rados/rgw_data_sync.cc
src/rgw/driver/rados/rgw_data_sync.h
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/driver/rados/rgw_service.cc
src/rgw/driver/rados/rgw_sync_module.cc
src/rgw/driver/rados/rgw_sync_module.h
src/rgw/driver/rados/rgw_sync_module_aws.h
src/rgw/driver/rados/rgw_sync_module_es.cc
src/rgw/driver/rados/rgw_trim_bilog.cc
src/rgw/rgw_bucket_layout.cc
src/rgw/rgw_bucket_layout.h
src/rgw/rgw_common.cc
src/rgw/rgw_common.h
src/rgw/rgw_metadata.cc
src/rgw/rgw_sync_policy.cc
src/rgw/rgw_sync_policy.h
src/rgw/services/svc_bucket_sobj.cc
src/test/rgw/rgw_multi/tests.py

https://tracker.ceph.com/issues/20802
<details>
- `jenkins …

rgw/multisite: bucket instance cleanup after deletion

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-area-chart/dashboard-area-chart.component.ts

backport tracker: https://tracker.ceph.com/issues/70790
---
backport of https://github.com/ceph/ceph/pull/58963
parent tracker: https://tracker.ceph.com/issues/67009

reef: mgr/dashboard: Dashboard not showing Object/Overview correctly.

---

src/test/librbd/test_notify.py

In 2020, commit 01ff1530544c ("librbd: make all maintenance op notifications async") introduced a backwards compatibility issue where if exclusive lock is held by an older (octopus and below) client and a maintenance op is proxied to it from a newer client, the newer client interprets the notification for the in-place completion of the op as the notification for the acceptance of an async request and expects another notification for the completion of the op which never comes. In 2021, this bug was discovered and test_notify.py was amended to ignore it in commit 9c0b239d70cd ("qa/upgrade: conditionally disable update_features tests").
However the two update_features tests that started hanging and got disabled weren't the only ones to misbehave.  Rename, create_snap and remove_snap tests …

reef: test/librbd/test_notify.py: conditionally ignore some errors

---

src/test/crimson/test_crimson_coroutine.cc

This came up in https://github.com/ceph/ceph/pull/62530 (https://github.com/ceph/ceph/pull/62530#discussion_r2025477892).
Showcase an awaited throwing coroutine and a passed_further error. …

test/crimson/test_crimson_coroutines: showcase errorator examples

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/block/block.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-gateway/nvmeof-gateway.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-gateway/nvmeof-gateway.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-details/nvmeof-subsystems-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-details/nvmeof-subsystems-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems-details/nvmeof-subsystems-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.ts

Fixes: https://tracker.ceph.com/issues/70793
https://github.com/user-attachments/assets/d2a97a76-263f-4952-8e56-89f65db09898 …

mgr/dashboard: add nvmeof performance and overview grafana dashboard to Block -> Nvme/TCP tab in dashboard 

---

src/test/crimson/test_errorator.cc

test/crimson/test_errorator: showcase assert_all/handle/pass_furhter

---

.githubmap
.mailmap

he's not affiliated to Red Hat anymore, so map his contribution to his private email address. …

mailmap: update affiliation for Kefu Chai

---

src/os/ObjectStore.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/os/bluestore/bluestore_tool.cc
src/test/objectstore/store_test.cc
src/test/objectstore/store_test_fixture.h
src/tools/ceph_kvstore_tool.cc
src/tools/ceph_objectstore_tool.cc
src/tools/ceph_objectstore_tool.h
src/tools/kvstore_tool.cc
src/tools/kvstore_tool.h

reef: tools/ceph-objectstore-tool: tricks to tolerate disk errors for "pg export" command

---

src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h

os/bluestore: print the first RocksDB level which doesn't fit into fast

---

src/rgw/driver/d4n/rgw_sal_d4n.cc
src/rgw/driver/d4n/rgw_sal_d4n.h
src/rgw/driver/daos/rgw_sal_daos.cc
src/rgw/driver/daos/rgw_sal_daos.h
src/rgw/driver/motr/rgw_sal_motr.cc
src/rgw/driver/motr/rgw_sal_motr.h
src/rgw/driver/posix/rgw_sal_posix.cc
src/rgw/driver/posix/rgw_sal_posix.h
src/rgw/driver/rados/rgw_bucket_sync.cc
src/rgw/driver/rados/rgw_bucket_sync.h
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/driver/rados/rgw_sal_rados.h
src/rgw/rgw_op.cc
src/rgw/rgw_op.h
src/rgw/rgw_rest_s3.cc
src/rgw/rgw_sal.h
src/rgw/rgw_sal_dbstore.cc
src/rgw/rgw_sal_dbstore.h
src/rgw/rgw_sal_filter.cc
src/rgw/rgw_sal_filter.h
src/rgw/rgw_sal_store.h
src/rgw/rgw_sync_policy.cc
src/rgw/rgw_sync_policy.h
src/test/rgw/rgw_multi/tests.py
src/test/rgw/rgw_multi/zone_rados.py
src/test/rgw/test_d4n_filter.cc

backport tracker: https://tracker.ceph.com/issues/68995
---
backport of https://github.com/ceph/ceph/pull/57060
parent tracker: https://tracker.ceph.com/issues/64436

squid: rgw: implement x-amz-replication-status for PENDING & COMPLETED

---

src/pybind/mgr/dashboard/controllers/nvmeof.py

fix a new bug introduced in https://github.com/ceph/ceph/pull/61649
fixes: https://tracker.ceph.com/issues/70873
- …

mgr/dashboard: fix subsystems list api response

---

src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-list/smb-cluster-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-list/smb-cluster-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-join-auth-list/smb-join-auth-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-join-auth-list/smb-join-auth-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-overview/smb-overview.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-tabs/smb-tabs.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-tabs/smb-tabs.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-usersgroups-list/smb-usersgroups-list.component.html

https://github.com/user-attachments/assets/11e4c3ce-df91-4220-9170-ca9e2b2abcac
- …

mgr/dashboard: make smb tabs routable

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.ts

Fixes: https://tracker.ceph.com/issues/70888
Signed-off-by: Dnyaneshwari Talwekar <dtalwekar@redhat.com>
- Tracker …

mgr/dashboard: RGW - Tiering form - secret key fix 

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-topic-details/rgw-topic-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-topic-details/rgw-topic-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-topic-details/rgw-topic-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-topic-list/rgw-topic-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-topic-list/rgw-topic-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-topic-list/rgw-topic-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-topic.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-topic.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/topic.model.ts
src/pybind/mgr/dashboard/tests/test_rgw.py

Depends on https://github.com/ceph/ceph/pull/61075
Fixes:  https://tracker.ceph.com/issues/69143
Signed-off-by:  Puja Shahu <pshahu@redhat.com> …

mgr/dashboard: Add RGW topic listing in dashboard

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-storage-class.model.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/utils/rgw-bucket-tiering.ts
src/pybind/mgr/dashboard/services/rgw_client.py

Fixes: https://tracker.ceph.com/issues/70871
Signed-off-by: Dnyaneshwari Talwekar <dtalwekar@redhat.com>
1. Retain Head Object was not passed in the form.
https://github.com/user-attachments/assets/f505d9a1-d051-4416-bfb4-95fcfb4762f1 …

mgr/dashboard: RGW - Reatin Head Object Fix

---

doc/cephadm/services/osd.rst

doc/cephadm/services: Fix formatting in osd.rst
reStructuredText vs Markdown vs Slack vs GitHub vs GitLab vs Atlassian = cognitive dissonance …

doc/cephadm/services: Fix formatting in osd.rst

---

doc/cephadm/services/osd.rst

(cherry picked from commit c56d2a5aaf79a3440607946a55b9e59ca8a6de5b) …

squid: doc/cephadm/services: Fix formatting in osd.rst

---

doc/cephadm/services/osd.rst

(cherry picked from commit c56d2a5aaf79a3440607946a55b9e59ca8a6de5b) …

reef: doc/cephadm/services: Fix formatting in osd.rst

---

src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/accounts.e2e-spec.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/accounts.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/users.e2e-spec.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/users.po.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-accounts-form/rgw-user-accounts-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-list/rgw-user-list.component.html

Fixes: https://tracker.ceph.com/issues/69674 …

mgr/dashboard: rgw accounts UI e2e tests

---

src/pybind/mgr/dashboard/frontend/src/app/core/navigation/about/about.component.html
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/about/about.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/local-storage-enum.ts

- add i18n
- cleanup unused variable
- use constants
https://tracker.ceph.com/issues/70900 …

mgr/dashboard: refactor about.component.ts

---

src/pybind/mgr/cephadm/services/smb.py

This change effectively disables fencing for the smb service because the previous attempt to implement fencing would destroy the only cephx key. Deleting this key would prevent any smb service part of the logical cluster from talking to cephfs, even ones that were not to be fenced.
The whole concept of fencing and ranks needs a bit of a rethink in regards to smb. For now, we're just going to rely on ctdb and not cephadm for smb's HA.
Fixes: https://github.com/ceph/ceph/commit/60300360cc500091e9dadf929d00bb72afad033c …

mgr/cephadm: do not delete smb fs cephx keys

---

doc/releases/index.rst
doc/releases/reef.rst
doc/releases/releases.yml

Fixes https://tracker.ceph.com/issues/70938
Signed-off-by: Yuri Weinstein <yweinste@redhat.com> …

doc: reef 18.2.6 release notes

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-cluster/nfs-cluster.component.html

fixes:https://tracker.ceph.com/issues/70964
Issue:
- …

mgr/dashboard: Fix virtual IP:port in NFS list

---

src/pybind/mgr/cephadm/services/monitoring.py

cephadm: Add pre_remove logic to clean up configs for grafana
Test logs:
```
[ceph: root@ceph-node-0 ~]# ceph orch apply grafana --placement="ceph-node-0,ceph-node-1"
Scheduled grafana update...
[ceph: root@ceph-node-0 ~]# ceph orch ls
NAME                       PORTS        RUNNING  REFRESHED  AGE  PLACEMENT                
alertmanager               ?:9093,9094      1/1  3m ago     49m  count:1                  
crash                                       3/3  3m ago     83m  *                        
grafana                    ?:3000           2/2  11s ago    22s  ceph-node-0;ceph-node-1  
mgr                                         2/2  11s ago    83m  count:2                  
mon                                         3/5  3m ago     83m  count:5                  
node-exporter …
```

cephadm: Add pre_remove logic to clean up configs for grafana

---

src/mon/MDSMonitor.cc

mon: Fix cast warning

---

src/rgw/rgw_auth.cc

backport tracker: https://tracker.ceph.com/issues/70535
---
backport of https://github.com/ceph/ceph/pull/61821
parent tracker: https://tracker.ceph.com/issues/69924

squid: rgw/sts: replacing load_stats with list_buckets

---

qa/tasks/cephfs/test_journal_repair.py
src/tools/cephfs/Dumper.cc

Fixes: https://tracker.ceph.com/issues/68954 …

cephfs-journal-tool: check the headers in dump file after journal recovery

---

src/rgw/rgw_rest_pubsub.cc

backport tracker: https://tracker.ceph.com/issues/69410
---
backport of https://github.com/ceph/ceph/pull/59980
parent tracker: https://tracker.ceph.com/issues/68227

squid: rgw/notification: Forward Topic & Notification creation request to master when notification_v2 enabled

---

qa/tasks/cephfs/test_dir_charmap.py
src/common/strtol.cc
src/common/strtol.h
src/mds/Server.cc
src/mds/Server.h

mds: check for snapshots on parent snaprealms

---

doc/radosgw/layout.rst

doc/radosgw: Improve formatting in layout.rst …

doc/radosgw: Improve formatting in layout.rst

---

doc/radosgw/oidc.rst

Empty line after starting a pre-formatted block with the double-colon syntax is required, otherwise the double-colon does nothing and is just rendered as-is as "::" and there would be no following pre-formatted block.
Add empty lines after the double-colon syntax so that the following block is rendered pre-formatted.
Also add bash privileged prompts to a block with 2 example CLI commands.
(cherry picked from commit b4fb5dc4030b4de477942630ebe3b98b882ae978) …

reef: doc/radosgw: Fix RST syntax rendeded as text in oidc.rst

---

doc/cephfs/cephfs-journal-tool.rst

Fixes: https://tracker.ceph.com/issues/70953 …

doc: update cephfs-journal-tool docs

---

doc/radosgw/layout.rst

(cherry picked from commit a7dcc3cf24239a9728d9622e4a980894e7741e48)
- Component …

squid: doc/radosgw: Improve formatting in layout.rst

---

src/rgw/jwt-cpp/jwt.h
src/rgw/rgw_auth.cc
src/rgw/rgw_rest_sts.cc
src/rgw/rgw_rest_sts.h

rgw/sts: Implementation of validating JWT using modulus and exponent

---

src/test/common/test_hobject.cc

test/common: Fix signed comparison

---

src/rgw/jwt-cpp/jwt.h
src/rgw/rgw_auth.cc
src/rgw/rgw_rest_sts.cc
src/rgw/rgw_rest_sts.h

backport tracker: https://tracker.ceph.com/issues/71108
---
backport of https://github.com/ceph/ceph/pull/61796
parent tracker: https://tracker.ceph.com/issues/54562

tentacle: rgw/sts: Implementation of validating JWT using modulus and exponent

---

src/pybind/mgr/prometheus/module.py

mgr/dashboard: Added application label to pool_metadata query

---

src/pybind/mgr/nfs/ganesha_conf.py

mgr/nfs: make sure sectype is a list when parsed

---

doc/cephfs/cephfs-journal-tool.rst

Fixes: https://tracker.ceph.com/issues/70953
(cherry picked from commit 7ae0c22dfd63d14773966ab3796c68f1be913534) …

tentacle: doc: update cephfs-journal-tool docs

---

doc/cephfs/cephfs-journal-tool.rst

Fixes: https://tracker.ceph.com/issues/70953
(cherry picked from commit 7ae0c22dfd63d14773966ab3796c68f1be913534) …

squid: doc: update cephfs-journal-tool docs

---

doc/cephfs/cephfs-journal-tool.rst

Fixes: https://tracker.ceph.com/issues/70953
(cherry picked from commit 7ae0c22dfd63d14773966ab3796c68f1be913534) …

reef: doc: update cephfs-journal-tool docs

---

doc/radosgw/lua-scripting.rst

* remove duplicate contexts
* trim trailing spaces
- …

doc/rgw/lua: add info on luarocks package

---

doc/radosgw/index.rst

Change to title case the few remaining index entries that weren't already.
I believe "Multi-factor" is the more common spelling instead of "Multi factor", also index has "Multi-tenancy" so seems appropriate.
The "troubleshooting" entry would be fine as-is, but changed it also for consistency with other such cases ("Role", "Compression", ...).
- Before: https://docs.ceph.com/en/latest/radosgw/
- Rendered PR (left sidebar menu): https://ceph--63157.org.readthedocs.build/en/63157/radosgw/ …

doc/radosgw: Use Title Case consistently in index.rst

---

src/crush/CrushWrapper.h

backport tracker: https://tracker.ceph.com/issues/70177
---
backport of https://github.com/ceph/ceph/pull/56428
- …

reef: crush: use std::vector instead of variable length arrays

---

src/pybind/mgr/dashboard/.pylintrc

Fixes https://tracker.ceph.com/issues/71246
Pr are failing with errors import errors running pylint
- Tracker …

mgr/dashboard: fix make check tests

---

doc/scripts/gen_state_diagram.py

Allow non-const events and abbreviating 'boost::statechart' as 'sc'
This makes gen_state_diagram work for crimson again, as documented in https://docs.ceph.com/en/latest/dev/crimson/backfillmachine/

doc/script/gen_state_diagram.py: adapt for crimson BackfillMachine

---

src/client/Client.cc
src/mds/cephfs_features.cc
src/mds/cephfs_features.h

Fixes: http://tracker.ceph.com/issues/70584 …

mds: introduce BLOCKDIFF feature bit

---

src/crimson/osd/pg_recovery.cc

ce4e9aaad, as part of the start_recovery_ops changed the call to reset_pglog_based_recovery_op to occur unconditionally rather than only if recovery has completed.
Note, this fix only restores the prior behavior.  There's actually still a race here where a DeferRecovery could be processed between the call to reset_pglog_based_recovery_op and the RequestBackfill or AllReplicasRecovered being processed.
Introduced: ce4e9aaad8f2cafae24511fe1687c61dc41affc1
Related: https://tracker.ceph.com/issues/71267
Fixes: https://tracker.ceph.com/issues/70337
<details>
- `jenkins test classic perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-classic/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull- …

crimson/osd/pg_recovery: only reset_pglog_based_recovery_op if complete

---

doc/dev/cephfs-mirroring.rst

This commit edits the second quarter of the doc/dev/cephfs-mirroring.rst file. This commit encompasses about one-hundred lines of RST. …

doc/dev/cephfs-mirroring: edit file 2 of x

---

doc/dev/cephfs-mirroring.rst

This commit edits the second quarter of the doc/dev/cephfs-mirroring.rst file. This commit encompasses about one-hundred lines of RST.
(cherry picked from commit 0768ef3fcab69392635d32ed6c4c7051b27afd37) …

tentacle: doc/dev/cephfs-mirroring: edit file 2 of x

---

doc/dev/cephfs-mirroring.rst

This commit edits the second quarter of the doc/dev/cephfs-mirroring.rst file. This commit encompasses about one-hundred lines of RST.
(cherry picked from commit 0768ef3fcab69392635d32ed6c4c7051b27afd37) …

squid: doc/dev/cephfs-mirroring: edit file 2 of x

---

doc/dev/cephfs-mirroring.rst

This commit edits the second quarter of the doc/dev/cephfs-mirroring.rst file. This commit encompasses about one-hundred lines of RST.
(cherry picked from commit 0768ef3fcab69392635d32ed6c4c7051b27afd37) …

reef: doc/dev/cephfs-mirroring: edit file 2 of x

---

doc/radosgw/adminops.rst
src/common/options/rgw.yaml.in
src/rgw/driver/motr/rgw_sal_motr.cc
src/rgw/driver/rados/rgw_bucket.cc
src/rgw/driver/rados/rgw_bucket.h
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rest_bucket.cc
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/rgw_admin.cc
src/rgw/rgw_auth.cc
src/rgw/rgw_op.cc
src/test/rgw/rgw_multi/tests.py

backport tracker: https://tracker.ceph.com/issues/71041
---
backport of https://github.com/ceph/ceph/pull/60227
parent tracker: https://tracker.ceph.com/issues/68190

squid: rgw: skip empty check on non-owned buckets by zonegroup

---

doc/mgr/dashboard_plugins/motd.inc.rst

Edit doc/mgr/dashboard_plugins/motd.inc.rst. …

doc/mgr: edit motd.inc.rst

---

qa/standalone/scrub/osd-scrub-test.sh

Modify TEST_just_deep_scrubs():
The test turns 'no-deep' off, and expects the scrub to be concluded and reported within a short period. But the PG already had a chance to try scrubbing (and fail due to the 'no-deep'), and its 'not-before' was pushed out by osd_scrub_retry_after_noscrub.
The fix is to reduce the value of osd_scrub_retry_after_noscrub for this test, and to increase the timeout for the test itself.
Fixes: https://tracker.ceph.com/issues/71404

qa/standalone/scrub: extra delay in osd-scrub-test.sh

---

doc/mgr/dashboard_plugins/motd.inc.rst

Edit doc/mgr/dashboard_plugins/motd.inc.rst.
(cherry picked from commit 8661509c16441d60778bc084df8231daa149a04b) …

tentacle: doc/mgr: edit motd.inc.rst

---

doc/mgr/dashboard_plugins/motd.inc.rst

Edit doc/mgr/dashboard_plugins/motd.inc.rst.
(cherry picked from commit 8661509c16441d60778bc084df8231daa149a04b) …

squid: doc/mgr: edit motd.inc.rst

---

doc/radosgw/account.rst

Use double backticks consistently when referring to data, commands etc.
Change links pointing to existing labels to use ref.
Use title case consistently in section titles.
Use ordered lists instead of hardcoding list numbers.
Use inline strong for emphasis instead of inline preformatted.
Change several tab to four spaces for indent.
Call it "RADOS Gateway" instead of "RadosGW".
Before: https://docs.ceph.com/en/latest/radosgw/account/
Rendered PR: https://ceph--63426.org.readthedocs.build/en/63426/radosgw/account/ …

doc/radosgw: Cosmetic improvements and ref links in account.rst

---

doc/cephadm/services/snmp-gateway.rst
doc/rados/configuration/osd-config-ref.rst
src/common/options/osd.yaml.in

src/common/options: Clarify scope of scrub intervals in osd.yaml.in
Prompted by a ceph-users thread. …

src/common/options: Clarify scope of scrub intervals in osd.yaml.in

---

doc/architecture.rst

Remove a sentence that is more marketing than reference.
(cherry picked from commit 00b530fc975a1f364a58f7c1ed1cf9dcf28ef299) …

squid: doc/architecture: remove sentence

---

doc/radosgw/layout.rst

(cherry picked from commit a7e2fab008519416d5bd91f2163ea51e82c440af) …

reef: doc/radosgw: Improve layout.rst

---

doc/rados/operations/pgcalc/index.rst

s/enpty/empty/ in doc/rados/operations/pgcalc/index.rst.
- …

doc/rados: s/enpty/empty/ in pgcalc doc

---

doc/mgr/insights.rst

Edit doc/mgr/insights.rst. Improve the English where necessary. …

doc/mgr: edit insights.rst

---

doc/mgr/insights.rst

Edit doc/mgr/insights.rst. Improve the English where necessary.
(cherry picked from commit 31d7dac8ff62ca31ffe86d8ef07a6f16047f2a64) …

squid: doc/mgr: edit insights.rst

---

doc/rados/operations/pgcalc/index.rst

s/enpty/empty/ in doc/rados/operations/pgcalc/index.rst.
(cherry picked from commit 50dc9f1a04c13faa3d5e7971ec7f0724ddf70709) …

tentacle: doc/rados: s/enpty/empty/ in pgcalc doc

---

doc/rados/operations/pgcalc/index.rst

s/enpty/empty/ in doc/rados/operations/pgcalc/index.rst.
(cherry picked from commit 50dc9f1a04c13faa3d5e7971ec7f0724ddf70709) …

reef: doc/rados: s/enpty/empty/ in pgcalc doc

---

doc/releases/index.rst
doc/releases/quincy.rst
doc/releases/releases.yml

doc: quincy 17.2.9 release notes

---

src/rgw/driver/rados/rgw_rados.cc

When listing a bucket and the parameters are such that we're not listing namespaced entries, this commit adds an optimization to advance the marker such that we skip past a whole region of namespaced entries rather than evaluating each entry one-by-one.
(cherry picked from commit 91488321277d15b877d8b5c5a5204e18d7ab7fad)
Fixes: https://tracker.ceph.com/issues/69208
- When …

reef: rgw: optimize bucket listing to skip past regions of namespaced entries

---

qa/suites/crimson-rados/singleton/all/osd-pg-splitting.yaml
qa/workunits/rados/test_pg_splitting.sh
src/crimson/osd/osd_operations/pg_advance_map.cc
src/crimson/osd/osd_operations/pg_advance_map.h
src/crimson/osd/pg.h
src/crimson/osd/shard_services.cc
src/crimson/osd/shard_services.h
src/mon/OSDMonitor.cc

Crimson PG Splitting 

---

src/test/objectstore/test_bluestore_types.cc

Previously, we had memory leak in the test_bluestore_types.cc tests where `BufferCacheShard` and `OnodeCacheShard` objects were allocated with raw pointers but never freed, causing leaks detected by AddressSanitizer.
ASan rightly pointed this out:
```
Direct leak of 224 byte(s) in 1 object(s) allocated from:
#0 0x55a7432a079d in operator new(unsigned long) (/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/unittest_bluestore_types+0xf2e79d) (BuildId: c3bec647afa97df6bb147bc82eac937531fc6272)
#1 0x55a743523340 in BlueStore::BufferCacheShard::create(BlueStore*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, ceph::common::PerfCounters*) /home/jenkins-build/build/workspace/ceph-pull-requests/src/os/bluestore/Bl
ueStore.cc:1678:9
#2 …
```

test/objectstore: fix memory leak test_bluestore_types.cc

---

doc/mgr/nfs.rst

Edit doc/mgr/nfs.rst. Improve some of the English.
This commit and the PR of which it is a part includes the changes made in https://github.com/ceph/ceph/pull/62782 and some corrections to glaring grammatical errors. However, this file could use a careful grammar pass.
(cherry picked from commit 1c2544d8e1df8b9fcd53617f2b5cb1d6a5814f22)
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backport …

reef: doc/mgr: edit nfs.rst

---

qa/standalone/scrub/osd-scrub-test.sh

Modify TEST_just_deep_scrubs():
The test turns 'no-deep' off, and expects the scrub to be concluded and reported within a short period. But the PG already had a chance to try scrubbing (and fail due to the 'no-deep'), and its 'not-before'
was pushed out by osd_scrub_retry_after_noscrub.
The fix is to reduce the value of osd_scrub_retry_after_noscrub for this test, and to increase the timeout for the test itself.
Fixes: https://tracker.ceph.com/issues/71426
Original tracker: https://tracker.ceph.com/issues/71404
Backport of https://github.com/ceph/ceph/pull/63400
(cherry picked from commit cb91678ab09723088b10525952333b20810e8eb9)

tentacle: qa/standalone/scrub: extra delay in osd-scrub-test.sh

---

doc/rados/operations/placement-groups.rst

doc/rados/operations: Additional improvements to placement-groups.rst …

doc/rados/operations: Additional improvements to placement-groups.rst

---

doc/dev/cephfs-mirroring.rst

This commit edits the fourth (and final) quarter of the doc/dev/cephfs-mirroring.rst file.
Further refinements to the English in this file are possible. …

doc/dev/cephfs-mirroring: edit file 4 of x

---

doc/dev/cephfs-mirroring.rst

This commit edits the fourth (and final) quarter of the doc/dev/cephfs-mirroring.rst file.
Further refinements to the English in this file are possible.
(cherry picked from commit 26dabda592f8fa2e3a388a474860eb3966aaaac8)
- When …

tentacle: doc/dev/cephfs-mirroring: edit file 4 of x

---

doc/dev/cephfs-mirroring.rst

This commit edits the fourth (and final) quarter of the doc/dev/cephfs-mirroring.rst file.
Further refinements to the English in this file are possible.
(cherry picked from commit 26dabda592f8fa2e3a388a474860eb3966aaaac8)
- When …

squid: doc/dev/cephfs-mirroring: edit file 4 of x

---

doc/dev/cephfs-mirroring.rst

This commit edits the fourth (and final) quarter of the doc/dev/cephfs-mirroring.rst file.
Further refinements to the English in this file are possible.
(cherry picked from commit 26dabda592f8fa2e3a388a474860eb3966aaaac8)
- When …

reef: doc/dev/cephfs-mirroring: edit file 4 of x

---

doc/mgr/iostat.rst

Rewrite the first sentence in doc/mgr/iostat.rst. This follows up on a request made by Anthony D'Atri in
https://github.com/ceph/ceph/pull/63418#discussion_r2102806688.
(cherry picked from commit 766a58ce7bc725d37b642df56465b28bde4f2f4a) …

reef: doc/mgr: edit iostat.rst

---

doc/mgr/iostat.rst

Rewrite the first sentence in doc/mgr/iostat.rst. This follows up on a request made by Anthony D'Atri in
https://github.com/ceph/ceph/pull/63418#discussion_r2102806688.
(cherry picked from commit 766a58ce7bc725d37b642df56465b28bde4f2f4a) …

squid: doc/mgr: edit iostat.rst

---

doc/cephadm/services/snmp-gateway.rst
doc/rados/configuration/osd-config-ref.rst
src/common/options/osd.yaml.in

(cherry picked from commit 1a2290d85af6840000e97cfd0a11c574da419c15)
- Component …

reef: src/common/options: Clarify scope of scrub intervals in osd.yaml.in

---

doc/rados/operations/erasure-code.rst

(cherry picked from commit 0c89feba998423dc99f335921403e4c313b12869) …

reef: doc/rados/operations: Improve erasure-code.rst

---

doc/glossary.rst

Change "OMAP" to "omap" to match the capitalization established by Eleanor Cawthon in her 2012 omap paper, here:
https://ceph.io/assets/pdfs/CawthonKeyValueStore.pdf.
(cherry picked from commit 2872986f9a581539b2aafe11a6cc085683623419) …

squid: doc/glossary: s/OMAP/omap/

---

src/sample.ceph.conf

(cherry picked from commit 01502bb23e796eaa92e2a1671cb611b21978c158) …

squid: doc: src: modernize sample.ceph.conf

---

src/sample.ceph.conf

(cherry picked from commit 01502bb23e796eaa92e2a1671cb611b21978c158) …

reef: src: modernize sample.ceph.conf

---

doc/rados/operations/stretch-mode.rst

doc/rados/operations: Improve stretch-mode.rst …

doc/rados/operations: Improve stretch-mode.rst

---

src/rgw/rgw_lua_utils.cc

Previously, error messages passed to luaL_error() were formatted using std::string concatenation. Since luaL_error() never returns (it throws a Lua exception via longjmp), the allocated std::string memory was leaked, as detected by AddressSanitizer:
```
Direct leak of 105 byte(s) in 1 object(s) allocated from:
#0 0x7fc5f1921a2d in operator new(unsigned long) /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_new_delete.cpp:86
#1 0x563bd89144c7 in std::__new_allocator<char>::allocate(unsigned long, void const*) /usr/include/c++/15.1.1/bits/new_allocator.h:151
#2 0x563bd89144c7 in std::allocator<char>::allocate(unsigned long) /usr/include/c++/15.1.1/bits/allocator.h:203
#3 0x563bd89144c7 in std::allocator_traits<std::allocator<char> >::allocate(std::allocator<char>&, unsigned long) …
```

rgw/rgw_lua_utils: fix memory leak in luaL_error() formatting

---

src/pybind/mgr/dashboard/services/hardware.py

backport tracker: https://tracker.ceph.com/issues/71575
---
backport of https://github.com/ceph/ceph/pull/63721
parent tracker: https://tracker.ceph.com/issues/71558

tentacle: mgr/dashboard: fix KeyError exception in HardwareService.get_summary()

---

doc/rados/operations/cache-tiering.rst

Add material to doc/rados/operations/cache-tiering.rst, as suggested by Anthony D'Atri in
https://github.com/ceph/ceph/pull/63745#discussion_r2127887785. …

doc/rados/ops: edit cache-tiering.rst

---

doc/radosgw/cloud-transition.rst

Add a link to the "Versioned Objects" section from a place in the docs where that section is referred to. This change was requested by Anthony D'Atri in
https://github.com/ceph/ceph/pull/63447#discussion_r2104492552. …

doc/radosgw: edit cloud-transition.rst

---

doc/radosgw/layout.rst

(cherry picked from commit a7dcc3cf24239a9728d9622e4a980894e7741e48)
- Component …

reef: doc/radosgw: Improve formatting in layout.rst

---

doc/mgr/telemetry.rst

This commit edits the final part of doc/mgr/telemetry.rst.
(cherry picked from commit b199d75763baf654fe1b21a780a4f6bcd0c4735b) …

tentacle: doc/mgr: edit telemetry (4 of x)

---

doc/mgr/telemetry.rst

This commit edits the final part of doc/mgr/telemetry.rst.
(cherry picked from commit b199d75763baf654fe1b21a780a4f6bcd0c4735b) …

reef: doc/mgr: edit telemetry (4 of x)

---

doc/rados/operations/stretch-mode.rst

fixup
(cherry picked from commit 3f5bf8dedd18f2f6d4afc0583be124be879667f2) (cherry picked from commit 660d163271fd6a984be15524df6652f6aeb4b5c0) …

squid: doc/rados/operations: Address suggestions for stretch-mode.rst

---

doc/rados/operations/user-management.rst

Edit an sentence in the imperative mood so that it matches the general form of imperative sentences immediately preceding commands that contain replaceable portions.
This commit targets only the Squid release branch.
Follows up on https://github.com/ceph/ceph/pull/58235/.
Tracker: https://tracker.ceph.com/issues/66617
(cherry picked from commit 20e630460a0368d8e08120b0e7cf523248a06040) …

tentacle: doc/rados: edit ops/user-management.rst

---

doc/rados/operations/user-management.rst

Edit an sentence in the imperative mood so that it matches the general form of imperative sentences immediately preceding commands that contain replaceable portions.
This commit targets only the Squid release branch.
Follows up on https://github.com/ceph/ceph/pull/58235/.
Tracker: https://tracker.ceph.com/issues/66617
(cherry picked from commit 20e630460a0368d8e08120b0e7cf523248a06040) …

reef: doc/rados: edit ops/user-management.rst

---

doc/rados/operations/balancer.rst

Edit doc/rados/operations/balancer.rst. Follow up on matters raised in https://github.com/ceph/ceph/pull/63530. Make the English clearer.
(cherry picked from commit 7bf5196e7037a89e6a04c770241ef25b53d2a809) …

tentacle: doc/rados: edit balancer.rst

---

doc/rados/configuration/ceph-conf.rst

doc/rados/configuration: Improve ceph-conf.rst …

doc/rados/configuration: Improve ceph-conf.rst

---

doc/rados/configuration/ceph-conf.rst

(cherry picked from commit ac1547f587774b6f5d16e7bbb7b10deef6eb9a2c)
- Component …

reef: doc/rados/configuration: Improve ceph-conf.rst

---

doc/rados/configuration/ceph-conf.rst

(cherry picked from commit ac1547f587774b6f5d16e7bbb7b10deef6eb9a2c)
- Component …

tentacle: doc/rados/configuration: Improve ceph-conf.rst

---

src/test/librados/aio_cxx.cc

In the PoolEIOFlag test we now track whether any async writes were still in flight at the moment we flipped the pool’s `eio=true` flag using an atomic `missed_eio` flag set inside the helper thread.  If we never actually overlapped any in-flight AIOs (we completed all aio successfully) with the flag flip, we `GTEST_SKIP()` the final `max_success+1 == min_failed` boundary assertion, avoiding spurious failures when all writes complete before EIO takes effect.
Fixes: https://tracker.ceph.com/issues/70852 …

test/librados/aio_cxx: skip EIO boundary assertion when no in-flight I/Os

---

qa/tasks/radosgw_admin_rest.py
src/rgw/driver/rados/rgw_rest_bucket.cc

backport tracker: https://tracker.ceph.com/issues/71171
---
backport of https://github.com/ceph/ceph/pull/63081
parent tracker: https://tracker.ceph.com/issues/71159

tentacle: rgw-admin: report correct error code for non-existent bucket on deletion

---

src/pybind/mgr/dashboard/frontend/src/app/shared/components/components.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/side-panel/side-panel.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/side-panel/side-panel.component.scss
src/pybind/mgr/dashboard/frontend/src/app/shared/components/side-panel/side-panel.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/side-panel/side-panel.component.ts
src/pybind/mgr/dashboard/frontend/src/styles/_carbon-defaults.scss
src/pybind/mgr/dashboard/frontend/src/styles/defaults/_bootstrap-defaults.scss

https://github.com/user-attachments/assets/a7e57feb-2ca2-45aa-8462-cc08860000c7
- …

mgr/dashboard: introduce side panel as a reusable component

---

doc/cephfs/disaster-recovery.rst

Document the use of first-damage.py.
Fixes: https://tracker.ceph.com/issues/71628
- …

doc/cephfs: document first-damage.py

---

doc/cephfs/disaster-recovery.rst

Document the use of first-damage.py.
Fixes: https://tracker.ceph.com/issues/71628
(cherry picked from commit d88cdf039d02055d3379eb91a5a9bab655d40d2d) …

squid: doc/cephfs: document first-damage.py

---

src/osd/PeeringState.cc

Currently when PG in `Backfilling` state receives a `DeferBackfill` event, there are cases when that event could race with `MOSDPGBackfill::OP_BACKFILL_FINISH` becasue the PG has already finished backfilling. In such case, the following happens:
1. PG state set to `PG_STATE_BACKFILL_WAIT`
2. Suspend backfilling
3. Discard the event
Notice that we do not reschedule backfill in the above steps, this can lead to a situation where the PG gets stuck in a `backfill_wait` state forever. This bug got introduced due to the  commit https://github.com/ceph/ceph/commit/865839faa49a83675c4f946aa79d47ac3154a5c0 which is a part of this https://github.com/ceph/ceph/pull/60185
This commit, fixes that by making sure that in race conditions such as above - we only discard the event.
Fixes: …

osd/PeeringState: handle race condition of DeferBackfill event for Backfilling state

---

src/mon/Monitor.cc

Revert commits of PR https://github.com/ceph/ceph/pull/61624
Fixes: https://tracker.ceph.com/issues/71435
- Tracker …

mon: Revert "mon: Add nvmeof group/gateway name in "ceph -s""

---

doc/mgr/dashboard.rst

doc: mgr/dashboard: add OAuth2 SSO documentation

---

doc/man/8/CMakeLists.txt
doc/man/8/rgw-gap-list.rst

(cherry picked from commit 12eb87463cdf952b9d16eac899f1ca40670ca2bc)
- Component …

reef: doc/rgw: add man documentation for the rgw-gap-list tool

---

doc/dev/developer_guide/debugging-gdb.rst

(cherry picked from commit 682b806efa39784c8ef67b46f4ac628f40aa15d9)
- Component …

squid: doc/dev: Debuggging with gdb

---

doc/mgr/telemetry.rst

This commit edits down to the line "Note that telemetry must be on for these commands to take effect.", inclusive.
(cherry picked from commit b3e2ce500f3903a039b9ad442a3d4f4ffa9492e4) …

reef: doc/mgr: edit telemetry (1 of x)

---

doc/mgr/telemetry.rst

This commit edits down to the line "Note that telemetry must be on for these commands to take effect.", inclusive.
(cherry picked from commit b3e2ce500f3903a039b9ad442a3d4f4ffa9492e4) …

squid: doc/mgr: edit telemetry (1 of x)

---

doc/mgr/iostat.rst

Rewrite the first sentence in doc/mgr/iostat.rst. This follows up on a request made by Anthony D'Atri in
https://github.com/ceph/ceph/pull/63418#discussion_r2102806688.
(cherry picked from commit 766a58ce7bc725d37b642df56465b28bde4f2f4a) …

tentacle: doc/mgr: edit iostat.rst

---

PendingReleaseNotes
monitoring/ceph-mixin/dashboards/ceph-cluster.libsonnet
monitoring/ceph-mixin/dashboards_out/ceph-cluster-advanced.json
monitoring/ceph-mixin/tests_dashboards/features/ceph-cluster.feature

monitoring/ceph-mixin/dashboards_out: Correct panel title in ceph-cluster-advanced.json
Noted by Eugen Block earlier this year. …

monitoring/ceph-mixin/dashboards_out: Correct panel title in ceph-cluster-advanced.json

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.ts

Fixes: https://tracker.ceph.com/issues/70413 …

mgr/dashboard: Show notification for multi-site sync status in case there is some error

---

doc/mgr/dashboard.rst

(cherry picked from commit 3e63860433a53d7d92d593beb3a4a02643b6ea98)
doc: mgr/dashboard: add --enable-auth flag
Add an instruction that includes the --enable-auth flag in a "git orch apply mgmt-gateway" command, in accordance with a request made by afreen23 here: https://github.com/ceph/ceph/pull/60440#discussion_r1953530599
(cherry picked from commit 30dc60b81493537daf0805faf50b47460c2f80d1) …

tentacle: doc: mgr/dashboard: add OAuth2 SSO documentation

---

doc/mgr/dashboard.rst

(cherry picked from commit 3e63860433a53d7d92d593beb3a4a02643b6ea98)
doc: mgr/dashboard: add --enable-auth flag
Add an instruction that includes the --enable-auth flag in a "git orch apply mgmt-gateway" command, in accordance with a request made by afreen23 here: https://github.com/ceph/ceph/pull/60440#discussion_r1953530599
(cherry picked from commit 30dc60b81493537daf0805faf50b47460c2f80d1) …

reef: doc: mgr/dashboard: add OAuth2 SSO documentation

---

doc/radosgw/cloud-transition.rst

Edit the first hundred lines of doc/radosgw/cloud-transition.rst.
(cherry picked from commit 9ad5a65fe6cf883cf34bceae0314f55bcf599c96) …

squid: doc/radosgw: edit cloud-transition (1 of x)

---

src/test/rgw/test_d4n_filter.cc

test/rgw/test_d4n_filter: remove unused captures

---

src/librbd/cache/pwl/AbstractWriteLog.cc

Previously, SyncPoint allocated two C_Gather instances tracked by raw
pointers but failed to properly clean them up when only a single sync
point existed, causing memory leaks detected by AddressSanitizer.
This change fixes the leak by modifying AbstractWriteLog::shut_down()
to check for prior sync points in the chain. When the current sync point
is the only one present, we now activate the m_prior_log_entries_persisted
context to ensure:
- The onfinish callback executes and releases the captured strong
reference to the enclosing SyncPoint
- The parent m_sync_point_persist context completes and gets properly
released
This ensures all allocated contexts are cleaned up correctly during
shutdown, eliminating the memory leak.
The ASan report:
```
Indirect leak of 2064 byte(s) in 1 object(s) …
```

librbd/cache/pwl: fix memory leak in SyncPoint persist context cleanup

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/proto/gateway.proto

adding some endpoints which already exist in the old nvmeof cli
fixes: https://tracker.ceph.com/issues/71481
- …

mgr/dashboard: add missing namespace CLI commands

---

src/rgw/driver/rados/rgw_notify.cc

IMPORTANT: This is not a backport PR.
Introduced-by: [e53c2311fdebdfb830b771c608ecb0c10ebf886e](https://github.com/ceph/ceph/commit/e53c2311fdebdfb830b771c608ecb0c10ebf886e)
Fixes: https://tracker.ceph.com/issues/71156 …

reef: rgw: correctly set worker thread names

---

src/test/mds/TestQuiesceDb.cc

test/mds: Fix catch by value

---

doc/rados/operations/stretch-mode.rst

(cherry picked from commit 8c27efcf0e41e5ed14a578a271b457ed3758cbda)
- Component …

reef: doc/rados/operations: Improve stretch-mode.rst

---

doc/radosgw/bucket_logging.rst

Edit doc/radosgw/bucket_logging.rst so that it is not solecistic and so that its punctuation is corrected and its use of articles is corrected. This file remains in my judgment demotic and maybe demotic enough to warrant another editorial pass in the future.
Fixes: https://tracker.ceph.com/issues/70758 …

doc/radosgw: line edit bucket_logging.rst

---

src/common/options/global.yaml.in

common/options: fix typo in option description

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/mgr-modules/mgr-module-list/mgr-module-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-details/rgw-multisite-sync-policy-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-form/rgw-multisite-sync-policy-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/mgr-module.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/mgr-module.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-realm.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/progress/progress.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/progress/progress.component.ts
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/rgw_client.py

1. Enable rgw module automatically in the primary and secondary cluster if not enabled during multi-site automation
2. Improve progress bar descriptions and add sub-descriptions for steps
Fixes: https://tracker.ceph.com/issues/71033
https://github.com/user-attachments/assets/1488830f-390c-4e66-a68b-93b803fd5623 …

mgr/dashboard: Enable rgw module automatically in the primary and secondary cluster if not enabled during multi-site automation

---

doc/radosgw/bucket_logging.rst
doc/radosgw/s3/bucketops.rst
examples/rgw/boto3/service-2.sdk-extras.json
qa/rgw/s3tests-branch.yaml
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/driver/rados/rgw_sal_rados.h
src/rgw/radosgw-admin/radosgw-admin.cc
src/rgw/rgw_bucket_logging.cc
src/rgw/rgw_bucket_logging.h
src/rgw/rgw_common.h
src/rgw/rgw_op.cc
src/rgw/rgw_op.h
src/rgw/rgw_process.cc
src/rgw/rgw_rest.h
src/rgw/rgw_rest_bucket_logging.cc
src/rgw/rgw_rest_s3.h
src/rgw/rgw_sal.h
src/rgw/rgw_sal_filter.h
src/rgw/rgw_sal_store.h

Fixes: https://tracker.ceph.com/issues/71452
Fixes: https://tracker.ceph.com/issues/71492
Fixes: https://tracker.ceph.com/issues/71454
Fixes: https://tracker.ceph.com/issues/71453
Fixes: https://tracker.ceph.com/issues/71555
Fixes: https://tracker.ceph.com/issues/71557
Fixes: https://tracker.ceph.com/issues/71537
Fixes: https://tracker.ceph.com/issues/71563
Fixes: https://tracker.ceph.com/issues/71652
Fixes: https://tracker.ceph.com/issues/71652
Fixes: https://tracker.ceph.com/issues/71749

tentacle: rgw: bucket logging backports

---

doc/rados/operations/stretch-mode.rst

Corrected communicte to communicate
(cherry picked from commit c328902e3929d9841f952948b0336ec5b20d36fa)
- Tracker …

squid: doc: Fixed a spelling error.

---

doc/rados/operations/stretch-mode.rst

Corrected communicte to communicate
(cherry picked from commit c328902e3929d9841f952948b0336ec5b20d36fa)
- Tracker …

tentacle: doc: Fixed a spelling error.

---

doc/dev/release-process.rst

The manual instructions for building release containers were complex and required access to an arm64 host; that was just too much, so I've created a Jenkins job to build all of the prerelease artifacts (see https://github.com/ceph/ceph-build/pull/2342). Change the documentation to reflect that.
(cherry picked from commit e20c09aab190c98995ccd7e7686e9100397081b6) …

squid: doc/dev/release-process.rst: document new Jenkins job for containers

---

doc/rados/operations/stretch-mode.rst

Corrected communicte to communicate
(cherry picked from commit c328902e3929d9841f952948b0336ec5b20d36fa)
- Tracker …

reef: doc: Fixed a spelling error.

---

doc/rados/operations/user-management.rst

Add a command that restores caps to client.admin after they have been accidentally destroyed or removed.
Fixes: https://tracker.ceph.com/issues/23594
(cherry picked from commit de8c148a2f99db3a1dc4eb70a19aca19a0e9bacf) …

reef: doc/rados/ops: add caps restore command

---

doc/rados/operations/user-management.rst

Add a command that restores caps to client.admin after they have been accidentally destroyed or removed.
Fixes: https://tracker.ceph.com/issues/23594
(cherry picked from commit de8c148a2f99db3a1dc4eb70a19aca19a0e9bacf) …

squid: doc/rados/ops: add caps restore command

---

doc/rados/operations/user-management.rst

Add a command that restores caps to client.admin after they have been accidentally destroyed or removed.
Fixes: https://tracker.ceph.com/issues/23594
(cherry picked from commit de8c148a2f99db3a1dc4eb70a19aca19a0e9bacf) …

tentacle: doc/rados/ops: add caps restore command

---

doc/mgr/telemetry.rst

Incorporate the suggestions made by Anthony D'Atri in https://github.com/ceph/ceph/pull/63735.
(cherry picked from commit 97ef126e4b6a9dcdf9872cf37cdebec289e84acd) …

tentacle: doc/mgr: edit telemetry.rst

---

doc/mgr/telemetry.rst

Incorporate the suggestions made by Anthony D'Atri in https://github.com/ceph/ceph/pull/63735.
(cherry picked from commit 97ef126e4b6a9dcdf9872cf37cdebec289e84acd) …

reef: doc/mgr: edit telemetry.rst

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/model/nvmeof.py
src/pybind/mgr/dashboard/services/nvmeof_cli.py
src/pybind/mgr/dashboard/services/nvmeof_client.py
src/pybind/mgr/dashboard/tests/test_nvmeof_cli.py

backport tracker: https://tracker.ceph.com/issues/71882
---
backport of https://github.com/ceph/ceph/pull/63327
parent tracker: https://tracker.ceph.com/issues/71352

tentacle: mgr/dashboard: Nvmeof CLI plain format support

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-storage-class.model.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-list/rgw-storage-class-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-list/rgw-storage-class-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/utils/rgw-bucket-tiering.ts
src/pybind/mgr/dashboard/services/rgw_client.py

Fixes: https://tracker.ceph.com/issues/71460
Signed-off-by: Dnyaneshwari Talwekar <dtalwekar@redhat.com>
https://github.com/user-attachments/assets/70745b8c-3276-41a3-b735-711440aae4dc
Description: 
Added Storage Class Type to the exisiting tiering configuration which include "Local" and "Clous S3" storage class. …

mgr/dashboard: Local Storage Class - create and list

---

src/rgw/driver/rados/rgw_notify.cc

this should allow for proper shutdown of the queue handling code of persistent notifications.
Fixes: https://tracker.ceph.com/issues/71390
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull-requests/config/definitions/ceph-perf-pull-req …

rgw/notifications: replace timer waiter with async waiter

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/model/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml

backport tracker: https://tracker.ceph.com/issues/71934
---
backport of https://github.com/ceph/ceph/pull/64215
parent tracker: https://tracker.ceph.com/issues/71864

tentacle: mgr/dashboard: NVMeoF CLI migrate prs

---

src/rgw/rgw_op.cc

Since storage class is cloud tier s3 cp of temporary object was failing.
Fixes: https://tracker.ceph.com/issues/71121
(cherry picked from commit 6a3fecab1ffed2a9e9e7885e1625be3ccc745545)
Reviewed-by: Soumya Koduri <skoduri@redhat.com> …

tentacle: rgw/cloud-restore: allow copy of temporary object

---

src/common/options/global.yaml.in

(cherry picked from commit aa54c08eb01efa4f048cc8fba9f909e0226ac905)
- Component …

reef: common/options: fix typo in description

---

src/common/options/global.yaml.in

(cherry picked from commit aa54c08eb01efa4f048cc8fba9f909e0226ac905)
- Component …

squid: common/options: fix typo in description

---

src/common/options/global.yaml.in

(cherry picked from commit aa54c08eb01efa4f048cc8fba9f909e0226ac905)
- Component …

tentacle: common/options: fix typo in description

---

src/pybind/mgr/dashboard/requirements-extra.txt

which brings in python3-saml and is not needed anymore after https://github.com/ceph/ceph/pull/62239
Fixes: https://tracker.ceph.com/issues/70937 …

mgr/dashboard: rm requirements-extra file

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-tabs/cephfs-tabs.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs.module.ts

fixes: https://tracker.ceph.com/issues/72039
https://github.com/user-attachments/assets/ada5cc83-6978-4656-b4f6-b8ace4e91549
Signed-off-by: Abhishek Desai <abhishek.desai1@ibm.com> …

mgr/dashboard: add tab structure to File Systems page and embed Ceph-Filesystem Overview dashboard

---

doc/cephfs/ceph-dokan.rst
doc/install/windows-install.rst
doc/rbd/rbd-windows.rst
doc/start/os-recommendations.rst

doc: Clarify the status of MS Windows client support
As discussed in the CSC meeting 2025/7/7 …

doc: Clarify the status of MS Windows client support

---

src/script/redmine-upkeep.py

Leave a comment on the issue so a human can fix it.
- …

script/redmine-upkeep: handle invalid PRs

---

doc/cephfs/ceph-dokan.rst
doc/install/windows-install.rst
doc/rbd/rbd-windows.rst
doc/start/os-recommendations.rst

(cherry picked from commit 89eabfc3f0c8db3501b3ea3097e2983617c5234a)
- Component …

tentacle: doc: Clarify the status of MS Windows client support

---

doc/cephfs/ceph-dokan.rst
doc/install/windows-install.rst
doc/rbd/rbd-windows.rst
doc/start/os-recommendations.rst

(cherry picked from commit 89eabfc3f0c8db3501b3ea3097e2983617c5234a)
- Component …

squid: doc: Clarify the status of MS Windows client support

---

doc/cephfs/ceph-dokan.rst
doc/install/windows-install.rst
doc/rbd/rbd-windows.rst
doc/start/os-recommendations.rst

(cherry picked from commit 89eabfc3f0c8db3501b3ea3097e2983617c5234a)
- Component …

reef: doc: Clarify the status of MS Windows client support

---

src/script/redmine-upkeep.py

To add priority and clarity of organization. …

script/redmine-upkeep: add Filter class

---

doc/cephfs/ceph-dokan.rst
doc/rbd/rbd-windows.rst

Add note admonitions when discussing client package support in the context of OS Recommendations in the following two files:
- doc/cephfs/ceph-dokan.rst
- doc/rbd/rbd-windows.rst
This addresses a change requested by Ilya Dryomov in https://github.com/ceph/ceph/pull/64374#discussion_r2199756581.
(cherry picked from commit 69d641f0207d803cd9a3c3e102d5b2073e6b0f77) …

tentacle: doc: add note admonitions in two files

---

doc/cephfs/ceph-dokan.rst
doc/rbd/rbd-windows.rst

Add note admonitions when discussing client package support in the context of OS Recommendations in the following two files:
- doc/cephfs/ceph-dokan.rst
- doc/rbd/rbd-windows.rst
This addresses a change requested by Ilya Dryomov in https://github.com/ceph/ceph/pull/64374#discussion_r2199756581.
(cherry picked from commit 69d641f0207d803cd9a3c3e102d5b2073e6b0f77) …

squid: doc: add note admonitions in two files

---

doc/cephfs/ceph-dokan.rst
doc/rbd/rbd-windows.rst

Add note admonitions when discussing client package support in the context of OS Recommendations in the following two files:
- doc/cephfs/ceph-dokan.rst
- doc/rbd/rbd-windows.rst
This addresses a change requested by Ilya Dryomov in https://github.com/ceph/ceph/pull/64374#discussion_r2199756581.
(cherry picked from commit 69d641f0207d803cd9a3c3e102d5b2073e6b0f77) …

reef: doc: add note admonitions in two files

---

doc/rados/operations/cache-tiering.rst

Add material to doc/rados/operations/cache-tiering.rst, as suggested by Anthony D'Atri in
https://github.com/ceph/ceph/pull/63745#discussion_r2127887785.
(cherry picked from commit d3c46820a5fc72391ef46ab4b03bbe867e0e51d2) …

squid: doc/rados/ops: edit cache-tiering.rst

---

src/pybind/mgr/rgw/module.py
src/python-common/ceph/rgw/rgwam_core.py

This PR has two commits. The first improves the error reporting of failures like this, and the second fixes the actual issue of realm bootstrap failing if the system user for the zone already exists. The commit messages and tracker include more info (much of which is also included in code comments added as part of the commits).
Fixes: https://tracker.ceph.com/issues/70914 …

mgr/rgw: don't fail realm bootstrap if system user exists already

---

qa/tasks/cephadm.py

By default, container image name is tagged by branch name or by sha1, i.e. corresponding values suffixed ':' are appended to the image value.
This patch allows to override the tagging just by providing desired tag with the standard notation using ':' separator in the container image parameter value of cephadm task. …

qa/tasks/cephadm: override container image tags

---

src/crimson/os/alienstore/alien_store.cc
src/crimson/os/alienstore/alien_store.h
src/crimson/os/cyanstore/cyan_store.cc
src/crimson/os/cyanstore/cyan_store.h
src/crimson/os/futurized_store.h
src/crimson/os/seastore/omap_manager.h
src/crimson/os/seastore/omap_manager/btree/btree_omap_manager.cc
src/crimson/os/seastore/omap_manager/btree/btree_omap_manager.h
src/crimson/os/seastore/omap_manager/btree/omap_btree_node.h
src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.cc
src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.h
src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/seastore.h
src/crimson/osd/osd_operations/scrub_events.cc
src/crimson/osd/pg_backend.cc
src/crimson/osd/replicated_recovery_backend.cc
src/osd/PGLog.cc
src/osd/SnapMapper.cc
src/test/crimson/seastore/test_omap_manager.cc
src/test/crimson/seastore/test_seastore.cc

https://tracker.ceph.com/issues/69612
https://tracker.ceph.com/issues/69990
For ceph_test_cls_rbd test, original omap list will cause slow request when osd_op_complaint_time <=3s, by this PR, don't meet omap list slow request even setting osd_op_complaint_time = 1s.  …

crimson: implement crimson Omap iterate interface

---

qa/suites/fs/workload/ranks/multi/balancer/random.yaml

Fixes: https://tracker.ceph.com/issues/65770

qa: increase the randomness to trigger the directory import/export

---

doc/rados/operations/cache-tiering.rst

Add material to doc/rados/operations/cache-tiering.rst, as suggested by Anthony D'Atri in
https://github.com/ceph/ceph/pull/63745#discussion_r2127887785.
(cherry picked from commit d3c46820a5fc72391ef46ab4b03bbe867e0e51d2) …

reef: doc/rados/ops: edit cache-tiering.rst

---

qa/suites/upgrade/reef-x/parallel/overrides/ignorelist_health.yaml
qa/suites/upgrade/squid-x/parallel/overrides/ignorelist_health.yaml

Fixes: https://tracker.ceph.com/issues/70487 …

qa: Add "osds down" in log-ignorelist to avoid the test case failure during upgrade

---

src/pybind/mgr/prometheus/module.py

Exposed SMB metadata metric including labels:
- CephFS volume, subvolume group and subvolume
- SMB cluster ID (as netbiosname)
- SMB version
Prometheus UI with SMB metadata metric added: 
Fixes: https://tracker.ceph.com/issues/72068 …

mgr/prometheus: add smb_metadata metric

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/model/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/nvmeof_cli.py
src/pybind/mgr/dashboard/tests/test_nvmeof_cli.py
src/pybind/mgr/mgr_module.py

backport tracker: https://tracker.ceph.com/issues/72181
---
backport of https://github.com/ceph/ceph/pull/64363
parent tracker: https://tracker.ceph.com/issues/71980

tentacle: mgr/dashboard: nvmeof cli feedback fixes

---

doc/cephfs/disaster-recovery.rst

Follow up on the suggestions made by Anthony D'Atri in https://github.com/ceph/ceph/pull/64604.
(cherry picked from commit 37df8e43baa1e75587686fd661310dfb4ad30312) …

tentacle: doc/cephfs: edit disaster-recovery.rst

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-user.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-user.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/rgw_client.py

backport tracker: https://tracker.ceph.com/issues/72104
---
backport of https://github.com/ceph/ceph/pull/64362
parent tracker: https://tracker.ceph.com/issues/71523

tentacle: mgr/dashboard: differentiate account users from rgw users in bucket form

---

src/pybind/mgr/dashboard/frontend/src/app/core/error/error.component.html

- taking to dashboard page due to remains of `buttonToEnableModule`
**Before**:
**After**:
https://github.com/user-attachments/assets/257e6245-4f94-4b2f-af10-2c1ad5445067 …

mgr/dashboard: Fix redirection of SMB enable module

---

qa/tasks/cephadm.py

Backport of https://github.com/ceph/ceph/pull/64184
<details> …

tentacle: qa/tasks/cephadm: override container image tags

---

src/pybind/mgr/dashboard/frontend/package-lock.json
src/pybind/mgr/dashboard/frontend/package.json

This reverts commit c7053dff52bc1a93af45b8017a6e13a578a2f71e.
- …

Revert "mgr/dashboard: Fix stylus issue"

---

src/librbd/mirror/EnableRequest.cc

In the EnableRequest state machine, clean up the handling of the async request to fetch the mirror image, particularly when a non-primary image is being created by the rbd-mirror daemon. …

librbd/mirror: cleanup EnableRequest::handle_get_mirror_image()

---

qa/tasks/cephfs/test_admin.py

The test intended to validate the failure of 'mds fail'
cmd on any active mds when one of them has warning.
The commit https://github.com/ceph/ceph/commit/221700273a82658c642a282c5761c0cbb00ec5b6
(PR 61554) changes this behavior and allows 'mds fail'
on mds without the warning. The test should have always
failed with this commit. But the test never failed until
tested extensively because the test mostly generated
warnings for both active mdses. Occasionaly, the test
generated a warning on single mds and failed. So it's a
race. This patch fixes the same by changing the following.
a. Changed the mds_cache_memory_limit to '50K' from '1K'
as '1K' was to less and generating warning on both the mdses.
b. Create a directory and pin it a single mds and open 400 files
in the backend to create …

qa: Fix test_with_health_warn_with_2_active_MDSs

---

doc/radosgw/bucket_logging.rst
src/rgw/rgw_bucket_logging.cc
src/rgw/rgw_common.cc
src/rgw/rgw_common.h

backport tracker: https://tracker.ceph.com/issues/72166
---
backport of https://github.com/ceph/ceph/pull/64251
parent tracker: https://tracker.ceph.com/issues/71730

tentacle: rgw: fix aclRequired for bucket-logging

---

qa/tasks/cephfs/test_mirroring.py

Fixes: https://tracker.ceph.com/issues/71487

tentacle: qa: fix test_cephfs_mirror_stats failure

---

src/rgw/driver/dbstore/common/dbstore.h
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/rgw_multi_del.cc
src/rgw/rgw_multi_del.h
src/rgw/rgw_op.cc
src/rgw/rgw_op.h
src/rgw/rgw_rest_s3.cc
src/rgw/rgw_sal.h
src/rgw/rgw_sal_dbstore.cc

https://tracker.ceph.com/issues/68183
https://bugzilla.redhat.com/show_bug.cgi?id=2350732 …

RGW | fix conditional Delete, MultiDelete and Put

---

doc/man/8/rbd.rst
qa/suites/krbd/unmap/ceph/ceph.yaml

Backport https://github.com/ceph/ceph/pull/64711 to tentacle.

tentacle: qa/suites/krbd: request msgr1 explicitly in unmap subsuite

---

src/librbd/mirror/EnableRequest.cc

Backport https://github.com/ceph/ceph/pull/64545 to tentacle.

tentacle: librbd/mirror: cleanup EnableRequest::handle_get_mirror_image()

---

src/crimson/osd/osd.cc
src/crimson/osd/osd.h

~Drafted until https://github.com/ceph/ceph/pull/60428 is merged to not cause conflicts.~ …

crimson/osd: committed/handle_osd_maps into coroutines

---

src/common/options/mds.yaml.in
src/mds/MDCache.cc
src/mds/MDSRank.cc
src/mds/Server.cc
src/mds/Server.h

https://tracker.ceph.com/issues/69682
(not using ceph-backport.sh as the script misbehaves somehow in my repo -- will deal with it later) …

reef: mds: prevent duplicate wrlock acquisition for a single request

---

doc/cephfs/ceph-dokan.rst

Edit the last half of doc/cephfs/ceph-dokan.rst. This is part of a larger project whose goal is the improvement of the CephFS documentation.
Follows https://github.com/ceph/ceph/pull/64690.
(cherry picked from commit 9dc57f9e2da72c6de92fc0e3bb52ddc8f4a50f65) …

reef: doc/cephfs: edit ceph-dokan.rst (2 of x)

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-notification-list/rgw-bucket-notification-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-notification-list/rgw-bucket-notification-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-notification-list/rgw-bucket-notification-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-notification-form/rgw-notification-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-notification-form/rgw-notification-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-notification-form/rgw-notification-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-topic-list/rgw-topic-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-topic.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-topic.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/notification-configuration.model.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/task-message.service.ts
src/pybind/mgr/dashboard/services/rgw_client.py

Fixes: https://tracker.ceph.com/issues/70955
Signed-off-by:  pujaoshahu <pshahu@redhat.com>
https://github.com/user-attachments/assets/60465b27-2434-40cd-8f02-ac88b1eebc83
Updated Screencast
https://github.com/user-attachments/assets/3075bd81-35ab-4098-a7ac-9f0e8a3b5eb7 …

mgr/dashboard: Create and delete and update s3 notification in dashboard

---

src/pybind/mgr/dashboard/frontend/src/app/shared/components/alert-panel/alert-panel.component.ts

fixes: https://tracker.ceph.com/issues/72250
PR includes: support to change variant of alert panel
variant=inline (default)
===
variant=toast
=== …

mgr/dashboard: alert panel enhancements

---

ceph.spec.in
install-deps.sh
src/script/build-with-container.py
src/script/buildcontainer-setup.sh

reef: Rocky 9/10 support backports

---

src/pybind/mgr/dashboard/frontend/cypress/e2e/block/mirroring.e2e-spec.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/multi-cluster/multi-cluster.e2e-spec.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/pools/pools.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/buckets.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/users.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/ui/notification.e2e-spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.html

Tests fixed: 
Reference: https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/19779/#showFailuresLink
1. should generate and import the bootstrap token between clusters.Mirroring page rbd mirroring bootstrap should generate and import the bootstrap token between clusters
2. should switch to the second cluster and back to hub.Muti-cluster management page should switch to the second cluster and back to hub, should reconnect the second cluster.Muti-cluster management page should reconnect the second cluster, should edit the second cluster.Muti-cluster management page should edit the second cluster,
should disconnect the second cluster.Muti-cluster management page should disconnect the second cluster
3. should show user key details.RGW users page create, edit & delete user tests should …

Fix cypress tests 

---

doc/cephfs/ceph-dokan.rst

Incorporate into doc/cephfs/ceph-dokan.rst the suggestions made by Anthony D'Atri in https://github.com/ceph/ceph/pull/64737, and make a few other small improvements to the English language in that file.
(cherry picked from commit c7f418eecbfa6209cc38e7107905ae503cd28f82) …

squid: doc/cephfs: edit ceph-dokan.rst (3 of x)

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard/health/health.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-sync-data-info/rgw-sync-data-info.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-sync-metadata-info/rgw-sync-metadata-info.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/components.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/helper/helper.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/helper/helper.component.scss
src/pybind/mgr/dashboard/frontend/src/app/shared/components/helper/helper.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/cd-helper.enum.ts
src/pybind/mgr/dashboard/frontend/src/styles/_carbon-defaults.scss

https://tracker.ceph.com/issues/72002 …

mgr/dashboard: add reusable carbon popover

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/package-lock.json
src/pybind/mgr/dashboard/frontend/package.json
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-list/rgw-user-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-list/rgw-user-list.component.scss
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-list/rgw-user-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/utils/constants.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-user.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/icons.enum.ts
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/rgw_iam.py

backport tracker: https://tracker.ceph.com/issues/72414
---
backport of https://github.com/ceph/ceph/pull/64628
parent tracker: https://tracker.ceph.com/issues/72072

tentacle: mgr/dashboard: user accounts enhancements

---

src/test/crimson/seastore/test_omap_manager.cc

The `basic` test has now been split into four separate tests: `set_key`, `set_keys`, `rm_key`, and `rm_key_range`, each with a clear and distinct testing purpose. The `set_keys` test has been newly added to cover a previously untested area. …

test/crimson/seastore/test_omap_manager: redesign test basic

---

doc/cephfs/troubleshooting.rst

Edit the section "Slow/Stuck Operations" in
doc/cephfs/troubleshooting.rst.
- …

doc/cephfs: edit troubleshooting.rst

---

doc/cephfs/troubleshooting.rst

Edit "Avoiding Recovery Roadblocks" in the "Stuck During Recovery" section of doc/cephfs/troubleshooting.rst.
This commit follows https://github.com/ceph/ceph/pull/64832.
(cherry picked from commit d67639986d72aa5723f39073053f701601d9b053) …

tentacle: doc/cephfs: edit troubleshooting.rst

---

src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts

don't stop loading until all the data is properly fetched
**BEFORE**
[Ceph Dashboard_ Object _ Tiering.webm](https://github.com/user-attachments/assets/ca70fe64-cace-4a63-9ccb-014778edfd1a)
**AFTER**
[Ceph Dashboard_ Cluster _ Hosts.webm](https://github.com/user-attachments/assets/9043f760-823a-4ee4-b5a9-7f04bec0abb1)
Fixes: https://tracker.ceph.com/issues/64170 …

mgr/dashboard: fix table loading while fetching data

---

src/test/crimson/seastore/test_omap_manager.cc

Judging from the log messages like "set big keys" and "set small keys," it seems that this test was originally intended to validate variable key/value sizes. However, the current implementation uses a fixed length defined by `STR_LEN`. I've updated the logic and the name of UT to reflect the original intention.
| Test  | Previous | This PR |
| ------------- | ------------- | --- |
| unittest-omap-manager.all | 456 s | 451 s |
- …

test/crimson/seastore/test_omap_manager: redesign test variable sizes

---

src/pybind/mgr/dashboard/frontend/src/app/shared/api/prometheus.service.ts

Prometheus API calls in the Cluster Utilization call is subscribed in
the for loop multiple times but this is not properly unsubscribed. As we
stay in the dashboard page for longer time, it produces a significant
memory leak which eventually lags the UI. Attempting to fix it by
properly handling the subscription
An example of overalapping prometheus API call in the graph below (in a dashboard that is run over 8 hours). The `/prometheus/data` API call produces a lot of spike eventually overlapping into itself. Its more visible as the dashboard is open for a longer time.
After the fix, we can see a clear difference in it.
Fixes: https://tracker.ceph.com/issues/72511 …

mgr/dashboard: fix memory leak in prometheus service

---

src/neorados/cls/fifo/detail/fifo.h

Recently edited: https://github.com/ceph/ceph/pull/63698/commits/a2d26647c011274b61805f8ac17c3422e9b9b63c
makecheck failures: https://jenkins.ceph.com/job/ceph-pull-requests/164567/consoleFull#1958952479e4bfde06-44c1-4b3c-8379-d9ee175fb257 …

neorados/cls/fifo/detail/fifo: include strtol.h

---

src/pybind/mgr/prometheus/module.py

prometheus: Add OSD full and nearfull ratio to prometheus 

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-v3.module.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/pg-summary.pipe.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/card-row/card-row.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/card-row/card-row.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/components.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/health.interface.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/mds-summary.pipe.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/mds-summary.pipe.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/mgr-summary.pipe.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/mgr-summary.pipe.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/osd-summary.pipe.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/pipes/osd-summary.pipe.ts

show loading state when inventory details are being loaded. also don't block the UI when inventories are not loaded.
[Ceph Dashboard.webm](https://github.com/user-attachments/assets/db39cd50-2da8-4b86-85f8-be4a8a3e670c)
Fixes: https://tracker.ceph.com/issues/72494 …

mgr/dashboard: loading state for inventory card

---

src/test/crimson/seastore/test_omap_manager.cc

This test simulate a real-world common pattern of inserting
monotonically increasing new keys and sequentially deleting
the oldest keys. The goal is to detect any abnormal splits
(imbalances) that may occur during right-skewed growth, and
then repeatedly delete the oldest keys to trigger left-skewed
deletions, checking for bugs in repeated left-side rebalancing. …

test/crimson/seastore/test_omap_manager: add monotonic inc UT

---

src/test/crimson/seastore/test_omap_manager.cc

* Add `check_mappings_fastpath` with O(n) complexity
* Rename previous O(nlogn) `check_mappings` to `check_mappings_slowpath`
* Fall back to the slow path if fast path verification fails
```
Previous : 1/1 Test #277: unittest-omap-manager ............   Passed  1310.91 sec
This PR  : 1/1 Test #277: unittest-omap-manager ............   Passed  904.02 sec (-31%)
``` …

test/crimson/seastore/test_omap_manager: faster check mappings

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/prometheus.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/dashboard-promqls.enum.ts

- Fixes https://tracker.ceph.com/issues/72519
- the osd dump metrics is used in /api/osd/settings
- this metrics creates perf bottleneck when osds are 1000s
- replacing with similar prometheus metrics
- minor refactors - including renaming, comments. …

Replace capacity threshold data with prometheus metrics 

---

doc/cephfs/quota.rst

Make the user aware to adapt the client capabilities to enable the configuration of quotas.
doc/cephfs: fix broken link
(cherry picked from commit 99fe86670fc23dd98b6e583ac4de6a5dcd8f8e28) …

tentacle: doc/cephfs: Update quota.rst

---

src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts

backport tracker: https://tracker.ceph.com/issues/72548
---
backport of https://github.com/ceph/ceph/pull/64710
parent tracker: https://tracker.ceph.com/issues/72491

tentacle: mgr/dashboard: fix table dom re-rendering

---

PendingReleaseNotes

Improve pending release notes
- Tracker …

doc: Improve PendingReleaseNotes

---

src/common/options/mgr.yaml.in

src/common/options: Clarify mon_target_pg_per_osd in mgr.yaml.in …

src/common/options: Clarify mon_target_pg_per_osd in mgr.yaml.in

---

src/mon/MonClient.cc

This fixes a regression that was introduced in https://github.com/ceph/ceph/pull/62770. …

mon/MonClient: post version request completions outside of monc_lock

---

src/rgw/rgw_rest_s3.cc

PutObject stores some of the generic http request headers in object attrs so they can be returned as response headers in Get/HeadObject
S3 has its own `aws-chunked` value for the `Content-Encoding` header, which it says does _not_ get stored with the object or returned with Get/HeadObject
from https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html:
> Amazon S3 stores the resulting object without the aws-chunked value in the content-encoding header. If aws-chunked is the only value that you pass in the content-encoding header, S3 considers the content-encoding header empty and does not return this header when your retrieve the object.
we've been storing this header with objects forever, so omitting the value on PutObject doesn't fix the issue for existing objects. instead, …

rgw/s3: remove 'aws-chunked' from Content-Encoding response

---

src/exporter/DaemonMetricCollector.cc

backport tracker: https://tracker.ceph.com/issues/72688
---
backport of https://github.com/ceph/ceph/pull/64335
parent tracker: https://tracker.ceph.com/issues/72686

tentacle: Handle failures in metric parsing

---

doc/cephfs/troubleshooting.rst

Edit the section "The MDS" in the file doc/cephfs/troubleshooting.rst.
(cherry picked from commit a17fd3f41b3e4a7ea5160bcdfe7a8b43b4b0f2e3) …

reef: doc/cephfs: edit troubleshooting.rst

---

doc/rados/configuration/mon-config-ref.rst

Repair a too-short underline that was introduced in https://github.com/ceph/ceph/commit/babd3c00341c59cb82e66f93f41c687ab4fc6928.
(cherry picked from commit ff93fcd28046e65a54368308f60308e84f93aa38) …

tentacle: doc/rados: repair short underline

---

doc/rados/configuration/mon-config-ref.rst

Repair a too-short underline that was introduced in https://github.com/ceph/ceph/commit/babd3c00341c59cb82e66f93f41c687ab4fc6928.
(cherry picked from commit ff93fcd28046e65a54368308f60308e84f93aa38) …

squid: doc/rados: repair short underline

---

doc/man/8/mount.ceph.rst

(cherry picked from commit 230d91c2e28f3df27dd5007b937b477922cb7655)
- Component …

tentacle: doc/man/8: Improve mount.ceph.rst

---

doc/man/8/mount.ceph.rst

(cherry picked from commit 230d91c2e28f3df27dd5007b937b477922cb7655)
- Component …

reef: doc/man/8: Improve mount.ceph.rst

---

src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts

**Before:**
https://github.com/user-attachments/assets/e2a561ab-2a8c-4dbf-874e-345fb722cd35
**After:**
https://github.com/user-attachments/assets/83d8a237-b753-48f7-a05e-34222a9bb2b7
Fixes: https://tracker.ceph.com/issues/72656 …

mgr/dashboard: Fix duplicate selection on multi-select in table component

---

src/pybind/mgr/dashboard/frontend/src/app/core/navigation/about/about.component.html
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/about/about.component.scss
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/about/about.component.ts
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/dashboard-help/dashboard-help.component.ts
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation.module.ts

Fixes: https://tracker.ceph.com/issues/70500
Signed-off-by:  pujaoshahu <pshahu@redhat.com>
---
https://github.com/user-attachments/assets/9dbb4db8-1d31-41d1-ae54-7d1ebee3e381 …

mgr/dashboard: About panel showing other icons in background while open

---

doc/rados/operations/health-checks.rst

(cherry picked from commit ba5cb7b8d63040730934a06d13baf2968952e813)
- Component …

tentacle: doc/rados/operations: Improve health-checks.rst

---

src/tools/rados/rados.cc

Fixes: https://tracker.ceph.com/issues/71966
RCA: https://tracker.ceph.com/issues/71966#note-5
Verification: https://tracker.ceph.com/issues/71966#note-8 …

tools: make rados ls aware about the locator concept

---

src/common/mutex_debug.h

The mutex_debugging_base::is_locked_by_me() member function was experiencing random SIGBUS and segfault on ARM64 due to a data race on the non-atomic locked_by member.
The racing occurs when:
- Thread A writes to locked_by during lock acquisition
- Thread B reads from locked_by in is_locked_by_me()
- These accesses happen concurrently without synchronization
On ARM64, std::thread::id (8 bytes when using libstdc++) writes/reads are not atomic, causing the reader to potentially see partially written or corrupted thread ID values, leading to undefined behavior in the comparison operator.
Fix by making locked_by atomic and using proper memory ordering in is_locked_by_me() to ensure synchronized access.
Fixes: https://tracker.ceph.com/issues/71547
- To sign and title your commits, please refer …

common/mutex_debug: fix arm64 SIGBUS/segfault due to data race

---

src/mds/CDir.h
src/mds/Server.cc
src/test/libcephfs/snapdiff.cc

Fixes: https://tracker.ceph.com/issues/72518 …

mds: fix snapdiff result fragmentation

---

make-debs.sh

This uses the logic from: https://github.com/ceph/ceph-build/blob/f074f1ce7fc05a5ac69e06fa9fa7ae45858b0110/scripts/build_utils.sh#L1411-L1435
CEPH-BUILD-JOB: ceph-dev-pipeline
ARCHS: x86_64
DISTROS: jammy noble
FLAVORS: default …

make-debs.sh: Avoid OOM errors during build

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-storage-class.model.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/utils/rgw-bucket-tiering.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-storage-class.service.spec.ts
src/pybind/mgr/dashboard/services/rgw_client.py

Fixes: https://tracker.ceph.com/issues/72362
Signed-off-by: Dnyaneshwari Talwekar dtalwekar@redhat.com
https://github.com/user-attachments/assets/b8fbd41b-39da-431a-867c-9ad7d0804e44
https://github.com/user-attachments/assets/c20f51bf-d723-4173-a77a-cc660df6942c …

mgr/dashboard:RGW- Storage Class ACL Mapping

---

doc/cephadm/services/rgw.rst

certmgr PR: https://github.com/ceph/ceph/pull/62106
With the introduction of certmgr, RGW services now support three certificate sources: cephadm-signed (default), inline, and reference. Docs have been updated to:
- Show how to provide inline certificates using the new ssl_cert/ssl_key fields instead of the deprecated rgw_frontend_ssl_certificate.
- Explain how to register and reference user-provided certs/keys
- Clarify that cephadm-signed certificates remain the default, with optional wildcard SANs support.
The usage of rgw_frontend_ssl_certificate is still supported for backward compatibility, but is now documented as deprecated.
- If you are …

doc: update RGW HTTPS configuration to use certmgr and new fields

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-storage-class.model.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/utils/rgw-bucket-tiering.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-storage-class.service.spec.ts
src/pybind/mgr/dashboard/services/rgw_client.py

backport tracker: https://tracker.ceph.com/issues/72928
backport of https://github.com/ceph/ceph/pull/64788
parent tracker: https://tracker.ceph.com/issues/72362
(cherry picked from commit 38b237c8cb12cb77fd29a560c10c7e2225786955) …

tentacle: mgr/dashboard:RGW- Storage Class ACL Mapping

---

doc/rados/operations/balancer.rst

Backport of https://github.com/ceph/ceph/pull/64157

tentacle: doc: Fixes a typo in balancer operations

---

.github/workflows/pr-checklist.yml

This newer version of the action does not fail mysteriously if a contributer removes the example Jenkins commands from the end of the PR description.

.github/workflows/pr-checklist.yml: Update

---

src/mds/MDSDaemon.cc

backport tracker: https://tracker.ceph.com/issues/72391
---
backport of https://github.com/ceph/ceph/pull/60326
parent tracker: https://tracker.ceph.com/issues/68760

tentacle: mds/MDSDaemon: unlock `mds_lock` while shutting down Beacon and others

---

src/crimson/os/seastore/random_block_manager/nvme_block_device.h

Follow-ups: https://github.com/ceph/ceph/pull/65071 …

crimson/os/seastore/rbm: switch to coroutine in state_device

---

src/crimson/os/seastore/transaction_manager.h

Fixes: https://tracker.ceph.com/issues/72902 …

crimson/os/seastore/transaction_manager: read_pin_by_type read the whole extent if it's not fully loaded

---

qa/workunits/rbd/rbd_mirror_group_simple.sh

…ce promote
Validating the status of group snapshot in resync scenario, where primary group is first demoted and then (force) promoted.
Test case validates fix proposed in commit:
https://github.com/ceph/ceph/commit/b162d7df0c06970d1d7fc24f88b28a4e00e577c1 …

qa/workunits/rbd: add test_resync_after_relocate_and_force_promote

---

doc/cephfs/scrub.rst
qa/suites/fs/functional/tasks/scrub.yaml
qa/tasks/cephfs/test_scrub_checks.py
src/mds/ScrubStack.cc
src/mds/ScrubStack.h

Fixes: https://tracker.ceph.com/issues/69345
Signed-off-by: Md Mahamudur Rahaman Sajib <mahamudur.sajib@croit.io>
- …

mds: for an irreparable hard link scrub is not able to identify the damage

---

doc/glossary.rst
doc/rados/operations/control.rst
doc/rados/operations/monitoring.rst

doc: Enhance the ceph df and ceph osd commands …

doc: Enhance the ceph df and ceph osd commands

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/active-alert-list/active-alert-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/active-alert-list/active-alert-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/silence-form/silence-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/silence-form/silence-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/models/prometheus-alerts.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/prometheus-alert.service.ts

fixes : https://tracker.ceph.com/issues/72944
Depends on https://github.com/ceph/ceph/pull/65312
Suppreded alert : 
landing page : 
Video : 
https://github.com/user-attachments/assets/72310166-4eae-4913-9948-5fb738953598 …

mgr/dashboard : Hide suppressed  alert on landing page

---

src/common/options/global.yaml.in

doc: Fix typo in src/common/options/global.yaml.in …

doc: Fix typo in src/common/options/global.yaml.in

---

qa/suites/upgrade/reef-x/parallel/0-start.yaml
qa/suites/upgrade/reef-x/stress-split/1-start.yaml
qa/suites/upgrade/squid-x/parallel/0-start.yaml
qa/suites/upgrade/squid-x/parallel/overrides/ignorelist_health.yaml
qa/suites/upgrade/squid-x/stress-split/1-start.yaml
qa/suites/upgrade/squid-x/stress-split/overrides/ignorelist_health.yaml

qa/tests: added messages to the whitelist

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml

fixes: https://tracker.ceph.com/issues/72679 …

mgr/dashboard: raise exception if both size and rbd_image_size are being passed in ns add
