ceph/ceph

- src/client/Client.cc
backport tracker: https://tracker.ceph.com/issues/68694
---
backport of https://github.com/ceph/ceph/pull/59027
parent tracker: https://tracker.ceph.com/issues/65971
> squid: client: fixed a bug that read operation hung

- src/mds/Server.cc
backport tracker: https://tracker.ceph.com/issues/67693
---
backport of https://github.com/ceph/ceph/pull/56602
parent tracker: https://tracker.ceph.com/issues/63906
> squid: mds: getattr just waits the xlock to be released by the previous client

- qa/tasks/cephfs/test_backtrace.py
- src/mds/CInode.cc
- src/mds/CInode.h
- src/mds/LogSegment.h
- src/mds/MDLog.cc
- src/mds/journal.cc
backport tracker: https://tracker.ceph.com/issues/68112
---
backport of https://github.com/ceph/ceph/pull/55421
parent tracker: https://tracker.ceph.com/issues/63259
> squid: mds: batch backtrace updates by pool-id when expiring a log segment

- src/tools/rados/rados.cc
backport tracker: https://tracker.ceph.com/issues/67532
---
backport of https://github.com/ceph/ceph/pull/59025
parent tracker: https://tracker.ceph.com/issues/67336
> squid: tools/rados: Fix extra NL in getxattr

- qa/tasks/cephfs/test_misc.py
- src/mds/MDSRank.cc
backport tracker: https://tracker.ceph.com/issues/68321
---
backport of https://github.com/ceph/ceph/pull/59874
parent tracker: https://tracker.ceph.com/issues/68132
> squid: mds: invalid id for client eviction is to be treated as success

- qa/workunits/cephtool/test.sh
- src/mon/FSCommands.cc
backport tracker: https://tracker.ceph.com/issues/67374
---
backport of https://github.com/ceph/ceph/pull/58582
parent tracker: https://tracker.ceph.com/issues/66960
> squid: mon: fix `fs set down` to adjust max_mds only when cluster is not down

- qa/tasks/cephfs/test_snapshots.py
- src/mds/Server.cc
- src/mds/SessionMap.cc
backport tracker: https://tracker.ceph.com/issues/67751
---
backport of https://github.com/ceph/ceph/pull/58419
parent tracker: https://tracker.ceph.com/issues/66828
> squid: mds: cephx path restriction incorrectly rejects snapshots of deleted directory

- doc/man/8/radosgw-admin.rst
- doc/radosgw/admin.rst
- src/bash_completion/radosgw-admin
- src/rgw/rgw_admin.cc
- src/test/cli/radosgw-admin/help.t
Add an option `--no-credentials` for radosgw-admin cli to create user without credentials.
Fixes: https://tracker.ceph.com/issues/67930
Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com> …
> radosgw-admin: create user without creds cli

- src/cls/rgw/cls_rgw_types.cc
Some multipart uploads do not have a stored storage class, however the code is written such that an empty storage class is treated as the "STANDARD" storage class. So when encoding the storage class in JSON, use the canonical storage.
Note: an additional fix is needed for the deeper problem that would store the string at rest.
Fixes: https://tracker.ceph.com/issues/68659 …
> rgw: fix empty storage class on display of multipart uploads

- src/rgw/rgw_rest_pubsub.cc
Fixes: (https://tracker.ceph.com/issues/68227) …
> rgw/notification: Forward Topic & Notification creation request to master when notification_v2 enabled

- src/rgw/rgw_auth_keystone.cc
- src/rgw/rgw_auth_keystone.h
- src/rgw/rgw_rest_s3.cc
backport tracker: https://tracker.ceph.com/issues/64398
---
backport of https://github.com/ceph/ceph/pull/55458
parent tracker: https://tracker.ceph.com/issues/64308
> reef: rgw/auth: ignoring signatures for HTTP OPTIONS calls

- src/cls/user/cls_user.cc
backport tracker: https://tracker.ceph.com/issues/68426
---
backport of https://github.com/ceph/ceph/pull/59884
parent tracker: https://tracker.ceph.com/issues/51786
> reef: cls/user: reset stats only returns marker when truncated

- qa/cephfs/conf/mgr.yaml
- qa/suites/fs/functional/tasks/snap-schedule.yaml
backport tracker: https://tracker.ceph.com/issues/67826
---
backport of https://github.com/ceph/ceph/pull/58547
parent tracker: https://tracker.ceph.com/issues/66009
> squid: qa: failfast mount for better performance and unblock `fs volume ls`

- PendingReleaseNotes
- doc/cephfs/quota.rst
- qa/tasks/cephfs/mount.py
- qa/tasks/cephfs/test_subvolume.py
- qa/workunits/fs/misc/general_vxattrs.sh
- qa/workunits/fs/misc/layout_vxattrs.sh
- src/mds/Server.cc
- src/mds/Server.h
backport tracker: https://tracker.ceph.com/issues/68942
---
backport of https://github.com/ceph/ceph/pull/53755
parent tracker: https://tracker.ceph.com/issues/62793
> squid: mds: Implement remove for ceph vxattrs 

- src/rgw/driver/rados/rgw_data_sync.cc
- src/rgw/rgw_auth.cc
- src/rgw/rgw_auth.h
- src/rgw/rgw_common.cc
- src/rgw/rgw_common.h
- src/rgw/rgw_op.cc
In the data sync phase, both source and destination object permissions are evaluated locally on the destination zone, leading to two issues:
1. Source object policies aren't evaluated, causing access to be denied when the uid is bound to an account or IAM policies are involved. This can be fixed by passing the UID as `rgwx-uid`, allowing the source zone to handle policy evaluation.
2. Destination object policies are skipped, resulting in access denial when IAM policies grant access to the UID. This can be resolved by using `verify_bucket_permission()` instead of `verify_bucket_permission_no_policy()`.
Fixes: https://tracker.ceph.com/issues/68884
> rgw: respect policies in data sync in user mode

- src/rgw/driver/rados/rgw_datalog.cc
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/services/svc_zone.cc
- src/rgw/services/svc_zone.h
Updated is_syncing_bucket_meta() to account for multi-zone and multi-zonegroup scenarios during this check.
Fixes: https://tracker.ceph.com/issues/69049
> rgw: consider multi zonegroup for is_syncing_bucket_meta

- src/rgw/rgw_rest.cc
backport tracker: https://tracker.ceph.com/issues/62255
---
backport of https://github.com/ceph/ceph/pull/52341
parent tracker: https://tracker.ceph.com/issues/52363
> reef: rgw: fix the Content-Length in response header of static website

- README.md
Format "Troubleshooting" into its own section so that it doesn't confuse readers of the vstart installation procedure.
This PR is part of a series of PRs meant to preserve the integrity of the README.md file after some recent additions that break the flow of the document.
This PR follows https://github.com/ceph/ceph/pull/61221. …
> doc: README.md - format "Troubleshooting"

- qa/standalone/scrub/osd-scrub-test.sh
- qa/standalone/scrub/scrub-helpers.sh
- src/osd/OSD.cc
- src/osd/scrubber/pg_scrubber.cc
- src/osd/scrubber/scrub_machine.h
Handling the case of receiving an operator command while the target PG is scrubbing, but
is waiting for replicas' reservations:
Now that the reservations are queued, the wait may be a very prolonged one. Usually - an operator direct scrub command has a priority high enough to not require waiting for reservations. But in the current implementation, it would wait until the running scrub session terminates, and only then will rerun at that high priority. This is not the intended behavior.
The solution is to abort the existing scrub session, and start the new one.
> osd/scrub: abort running scrub in replica-reservation if an operator-initiated scrub is requested

- README.md
Improve the formatting and English language in the sections "Troubleshooting" and "Tips and Tricks", and move those sections to a place where they don't interrupt the flow of the vstart cluster installation instructions. Some of the strings in "Tips and Tricks" are not yet unambiguous sentences that will make sense to the uninitiated, but this PR represents a step in that direction.
This PR is part of a series of PRs meant to preserve the integrity of the README.md file after some recent additions that break the flow of the document.
This PR follows https://github.com/ceph/ceph/pull/61226 and https://github.com/ceph/ceph/pull/61221.
- If you are …
> doc: README.md - improve "Tshooting" and "Tips & Tricks"

- src/crimson/osd/osd_operation.h
- src/crimson/osd/osd_operations/client_request.h
- src/crimson/osd/osd_operations/logmissing_request.h
- src/crimson/osd/osd_operations/logmissing_request_reply.h
- src/crimson/osd/osd_operations/peering_event.h
- src/crimson/osd/osd_operations/pg_advance_map.h
- src/crimson/osd/osd_operations/recovery_subrequest.h
- src/crimson/osd/osd_operations/replicated_request.h
- src/crimson/osd/osd_operations/scrub_events.h
- src/crimson/osd/pg_shard_manager.h
- src/crimson/osd/shard_services.cc
- src/crimson/osd/shard_services.h
Fixes: https://tracker.ceph.com/issues/68286 …
> crimson/osd/pg_shard_manager: discard outdated operations when the corresponding pgs are already removed

- qa/tasks/cephfs/test_exports.py
- src/common/options/mds.yaml.in
With the trimming changes by 9d2b3aa, ESubtreeMap wasn't written reliably often enough to pass the test.
- Tracker …
> qa: write out ESubtreeMap more frequently to find large events

- qa/standalone/scrub/osd-scrub-repair.sh
A bogus change introduced as part of PR#54363 (commit fbb7d73) changed multiple 'scrub' commands to 'scheduled-scrub'. In this one instance - that was wrong.
Backport of https://github.com/ceph/ceph/pull/61115.
Original tracker: https://tracker.ceph.com/issues/69276
Backport tracker: https://tracker.ceph.com/issues/69279
(cherry picked from commit ca189fb511f18fc82c62702bf904201b6347395b)
> squid: qa/standalone/scrub: fix TEST_periodic_scrub_replicated

- src/ceph-volume/ceph_volume/devices/lvm/zap.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/data_zap.py
When an OSD creation fails, ceph-volume can zaps unrelated existing raw based OSD as part of the 'rollback step'.
Fixes: https://tracker.ceph.com/issues/69430
> ceph-volume: fix Zap.ensure_associated_raw()

- debian/control
One can attach lua scripts as sort of hooks to implement dynamic checks or transformations of RGW requests since Ceph Pacific. Thus, a lua library is now required for base support and optionally one can use the luarocks deployment and management system for Lua modules to use more advanced scripts/modules.
With commit 46500cace6c ("rgw/test/lua: add lua integration tests suite") the dependency relations got cleaned up, as the respective entries were missing completely from debian/control.
But that commit is pulling in much more than required due to adding the devel package `liblua5.3-dev` instead of the library-only `liblua5.3-0` one, and having `luarocks` as hard dependency compared to an optional Suggests. Fixing that avoids pulling in a whole build/compiler/autotools/... stack with 65 …
> debian packaging: fix overly broad lua dependency declaration for librgw2 package

- qa/suites/rgw/crypt/2-kms/barbican.yaml
- qa/suites/rgw/tempest/0-install.yaml
backport tracker: https://tracker.ceph.com/issues/69181
---
backport of https://github.com/ceph/ceph/pull/60968
parent tracker: https://tracker.ceph.com/issues/69134
> squid: qa/rgw: bump keystone/barbican from 2023.1 to 2024.1

- src/ceph-volume/ceph_volume/util/prepare.py
This commit introduces type annotations to the `create_id` function in `ceph_volume.util.prepare`. The parameters and return value are now typed as follows:
- `fsid` is a `str`.
- `json_secrets` is a `str`.
- `osd_id` is an optional `str` (`Optional[str]`).
- The function returns a `str`.
> ceph-volume: add python hints to util.prepare.create_id()

- src/ceph-volume/ceph_volume/util/disk.py
This commit updates the `is_device` function to correctly handle loop devices.
The function now validates loop devices when they are explicitly allowed, by checking their type (`loop`) in addition to `disk` and `mpath`.
Changes include:
- Extending the type check to include `loop` in the list of supported device types.
- Enhancing the docstring for better documentation of the function's purpose and behavior.
These changes ensure that loop devices are properly recognized and handled when configuring OSDs in ceph-volume.
Fixes: https://tracker.ceph.com/issues/69432
> ceph-volume: fix loop devices support

- src/mon/OSDMonitor.cc
backport tracker: https://tracker.ceph.com/issues/67246
---
backport of https://github.com/ceph/ceph/pull/58470
parent tracker: https://tracker.ceph.com/issues/66867
> reef: mon: Remove any pg_upmap_primary mapping during remove a pool

- doc/rados/operations/health-checks.rst
- src/common/options/mon.yaml.in
- src/mon/NVMeofGwMap.cc
- src/mon/NVMeofGwMap.h
- src/mon/NVMeofGwMon.h
Add a warning when NVMeoF gateways are in DELETING state. This happens when there are namespaces under the deleted gateway's ANA group ID.
The gateways are removed completely after users manually move these namespaces to another load balancing group. Or if a new gateway is deployed on that host. …
> mon/NVMeofGwMap: add healthcheck warning NVMEOF_GATEWAY_DELETING

- PendingReleaseNotes
- src/include/rados/librados.hpp
- src/librados/librados_asio.h
- src/librados/librados_cxx.cc
- src/test/librados/aio.cc
- src/test/librados/aio_cxx.cc
- src/test/librados/asio.cc
`librados::AioCompletion::cancel()` calls `Objecter::op_cancel()` to cancel the operation. this is thread-safe, and does nothing if the op already completed
the asio interfaces in librados/librados_asio.h hook this up to asio's [per-op cancellation](https://www.boost.org/doc/libs/1_85_0/doc/html/boost_asio/overview/core/cancellation.html) support
<details> …
> librados/asio: forward asio cancellations to AioCompletion::cancel()

- PendingReleaseNotes
the user account feature was intended to cover all of the use cases of the previous tenant-based IAM/STS integration. announce deprecation of tenant-based IAM for the T release and removal for T+2
<details>
</details>
> docs/rgw: deprecate tenant-based IAM in favor of accounts

- src/common/options/global.yaml.in
backport tracker: https://tracker.ceph.com/issues/67607
---
backport of https://github.com/ceph/ceph/pull/57120
parent tracker: https://tracker.ceph.com/issues/65678
> reef: os/bluestore: allow use BtreeAllocator 

- src/os/bluestore/BlueStore.cc
- src/test/objectstore/store_test.cc
Parent tracker: https://tracker.ceph.com/issues/62330
Partial backport of: https://github.com/ceph/ceph/pull/53178
Backport tracker: https://tracker.ceph.com/issues/64860
After introduction of lazy statfs updates and mechanism to store them at exit, some tests required tune-up.
(cherry picked from commit 85f03d314e7ea5a3ed22fdd3eaca1349e5c23710) …
> reef: os/store_test: Retune tests to current code

- doc/_ext/ceph_commands.py
- doc/conf.py
commit a54f5710456345b797eabf2a8b6d09f8aa7e6dd5 (HEAD -> main, drunkard-fork/main)
Author: Drunkard Zhang <gongfan193@gmail.com>
Date:   Sat Dec 7 11:38:48 2024 +0800
doc/conf.py: try to provide real jar path
The path got by shutil.which is usually a hook, not real jar, so try to
provide real jar. And fallback to the hook detected when failed.
Signed-off-by: Drunkard Zhang <gongfan193@gmail.com>
commit cf48fddbc6afd43536c0cdf4c2a091287b5257ba
Author: Drunkard Zhang <gongfan193@gmail.com>
Date:   Sat Dec 7 11:32:38 2024 +0800
doc/_ext: mute syntax check warn E711
According to E711 of PEP0008:
When compare to None, should use 'is' instead of '=='
Signed-off-by: Drunkard Zhang <gongfan193@gmail.com> …
> doc: fixes in doc building

- src/common/pick_address.cc
- src/common/pick_address.h
- src/osd/OSDMap.cc
- src/test/test_ipaddr.cc
Updated the is_addr_in_subnet function to work with both IPv4 and IPv6 addresses. Previously, it only supported IPv4, which caused failures when IPv6 addresses were passed in.
Changes:
- Use inet_pton to detect IPv4 (AF_INET) or IPv6 (AF_INET6).
- Added sockaddr_in6 for IPv6 handling while keeping sockaddr_in for IPv4.
- Adjust the family and ifa_addr dynamically based on the address type.
Fixes: https://tracker.ceph.com/issues/67517 …
> common/pick_address: Add IPv6 support to is_addr_in_subnet

- PendingReleaseNotes
- doc/mgr/restful.rst
- src/pybind/mgr/restful/module.py
backport tracker: https://tracker.ceph.com/issues/67644
---
backport of https://github.com/ceph/ceph/pull/54984
parent tracker: https://tracker.ceph.com/issues/67642
> reef: mgr/rest: Trim  requests array and limit size

- src/mon/MonCommands.h
- src/mon/OSDMonitor.cc
backport tracker: https://tracker.ceph.com/issues/67666
---
backport of https://github.com/ceph/ceph/pull/57548
parent tracker: https://tracker.ceph.com/issues/66122
> reef: mon/OSDMonitor: Add force-remove-snap mon command

- src/pybind/mgr/pg_autoscaler/module.py
backport tracker: https://tracker.ceph.com/issues/67721
---
backport of https://github.com/ceph/ceph/pull/54968
parent tracker: https://tracker.ceph.com/issues/63860
> reef: src/pybind/mgr/pg_autoscaler/module.py: fix 'pg_autoscale_mode' output

- src/mon/AuthMonitor.cc
- src/mon/AuthMonitor.h
- src/mon/KVMonitor.cc
- src/mon/OSDMonitor.cc
- src/mon/OSDMonitor.h
backport tracker: https://tracker.ceph.com/issues/65377
---
backport of https://github.com/ceph/ceph/pull/52733
parent tracker: https://tracker.ceph.com/issues/59813
> reef: osd/OSDMonitor: check svc is writeable before changing pending

- src/common/TrackedOp.cc
- src/common/TrackedOp.h
backport tracker: https://tracker.ceph.com/issues/67458
---
backport of https://github.com/ceph/ceph/pull/52068
parent tracker: https://tracker.ceph.com/issues/67456
> reef: common/TrackedOp: rename and raise prio of slow op perfcounter

- qa/suites/upgrade/quincy-x/parallel/0-start.yaml
- qa/suites/upgrade/quincy-x/parallel/1-tasks.yaml
- qa/suites/upgrade/quincy-x/stress-split/1-start.yaml
- qa/suites/upgrade/reef-x/parallel/0-start.yaml
- qa/suites/upgrade/reef-x/parallel/1-tasks.yaml
- qa/suites/upgrade/reef-x/parallel/overrides/ignorelist_health.yaml
- qa/suites/upgrade/reef-x/stress-split/1-start.yaml
- qa/suites/upgrade/reef-x/stress-split/overrides/ignorelist_health.yaml
Daemons are terminated by cephadm during the upgrade, so health checks like OSD_DOWN must be ignored.  Since there shouldn't be any fundamental difference between upgrading from quincy and upgrading from reef, make quincy-x and reef-x ignorelists the same.
Fixes: https://tracker.ceph.com/issues/69135 …
> qa/suites/upgrade/reef-x: sync log-ignorelist with quincy-x

- doc/radosgw/account.rst
clarify the following error when migrating a user into an account:
> could not modify user: unable to modify user, UserName contains invalid characters
Fixes: https://tracker.ceph.com/issues/69470
<details>
</details>
> doc/rgw: document UserName requirements for account migration

- qa/suites/upgrade/quincy-x/parallel/1-tasks.yaml
- qa/suites/upgrade/quincy-x/stress-split/1-start.yaml
- qa/suites/upgrade/reef-x/parallel/1-tasks.yaml
- qa/suites/upgrade/reef-x/stress-split/1-start.yaml
backport tracker: https://tracker.ceph.com/issues/67577
---
backport of https://github.com/ceph/ceph/pull/58415
parent tracker: https://tracker.ceph.com/issues/66809
> squid: qa/suites/upgrade: ignore PG_AVAILABILITY and MON_DOWN for quincy-x and reef-x upgrade suites

- src/osd/PrimaryLogPG.cc
Improve the performance of finish_extent_cmp by using bufferlist iterators instead of array access operator[]. This change:
- Replaces O(N) array access with O(1) iterator operations
The original implementation used array access which has O(N) complexity for each access in bufferlist (N being the number of buffers in a bufferlist). The new version uses iterators which wprovide O(1) increment operations, reducing the overall function complexity from O(M*N) to O(M) with M being the length of the bufferlist.
Fixes: https://tracker.ceph.com/issues/69014
Tested in my local vstart cluster, the patch showed a 60 times performance improvement when running rbd sparsify against EC image:
First, create two thick-provisioned 1 GB rbd images in an EC pool with K+M=2+1; 
Then run rbd sparsify against …
> osd: optimize extent comparison in PrimaryLogPG

- qa/suites/upgrade/reef-x/parallel/overrides/ignorelist_health.yaml
- qa/suites/upgrade/reef-x/stress-split/overrides/ignorelist_health.yaml
backport tracker: https://tracker.ceph.com/issues/68825
---
backport of https://github.com/ceph/ceph/pull/59568
parent tracker: https://tracker.ceph.com/issues/66602
> squid: qa: Add ignorelist entries for reef-x tests

- qa/standalone/ceph-helpers.sh
Recent changes to the scrub scheduling mechanism, especially
regarding the 'must_scrub' flag, cause operator scrub commands
issued on a not-clean PG to be rejected - and forgotten.
This commit changes the tests to issue a scrub command only
after the target PG is clean.
Backport of https://github.com/ceph/ceph/pull/59437.
Original tracker: https://tracker.ceph.com/issues/64346
Backport tracker: https://tracker.ceph.com/issues/68218
Note:
1. this is the 2'nd attempt to solve the specific issue in Squid. The original PR that was marked as a solution, https://github.com/ceph/ceph/pull/59974, was not enough.
2. the current PR may be enough to also fix https://tracker.ceph.com/issues/68833 , but as I wasn't able to reproduce it - it is not guaranteed. …
> squid: test/scrub: only instruct clean PGs to scrub

- src/mgr/PyModule.h
The way these methods used the lock is completely wrong: in the protected code block, they do not access anything that needs to be protected.  All they effectively do is return the `this` pointer with an offset to the `module_name` or `error_string` field; but they do not actually access these fields.  The actual access is done by the caller, after the mutex has been unlocked already.
But anyway, these fields do not need any protection.  Both fields are `const` and thus cannot be modified by other threads.  So instead of fixing the return value (removing the `&`), let's just remove the lock.
> mgr/PyModule: do not lock in get_name(), get_error_string()

- qa/workunits/rados/test_rados_tool.sh
backport tracker: https://tracker.ceph.com/issues/67914
---
backport of https://github.com/ceph/ceph/pull/59165
parent tracker: https://tracker.ceph.com/issues/67419
> squid: test: test_rados_tools compare output without trimming newline

- doc/rados/operations/stretch-mode.rst
- qa/suites/rados/singleton/all/stretch-mode-5-mons-8-osds.yaml
- qa/tasks/ceph_manager.py
- qa/tasks/stretch_mode_disable_enable.py
- qa/workunits/mon/mon-stretch-mode-5-mons-8-osds.sh
- src/mon/MonCommands.h
- src/mon/MonMap.cc
- src/mon/Monitor.cc
- src/mon/Monitor.h
- src/mon/MonmapMonitor.cc
- src/mon/OSDMonitor.cc
- src/mon/OSDMonitor.h
backport tracker: https://tracker.ceph.com/issues/68840
---
backport of https://github.com/ceph/ceph/pull/59483
parent tracker: https://tracker.ceph.com/issues/67467
> squid: mon [stretch mode]: support disable_stretch_mode

- src/test/pybind/pytest.ini
- src/test/pybind/test_rados.py
```
2024-05-21T14:06:10.464 INFO:tasks.workunit.client.0.smithi031.stdout:../../../clone.client.0/src/test/pybind/assertions.py:2: AssertionError
2024-05-21T14:06:10.464 INFO:tasks.workunit.client.0.smithi031.stdout:=============================== warnings summary ===============================
2024-05-21T14:06:10.465 INFO:tasks.workunit.client.0.smithi031.stdout:../../../clone.client.0/src/test/pybind/test_rados.py:210
2024-05-21T14:06:10.465 INFO:tasks.workunit.client.0.smithi031.stdout:  /home/ubuntu/cephtest/clone.client.0/src/test/pybind/test_rados.py:210: DeprecationWarning: invalid escape sequence \-
2024-05-21T14:06:10.465 INFO:tasks.workunit.client.0.smithi031.stdout:    assert re.match('[0-9a-f\-]{36}', fsid, re.I)
2024-05-21T14:06:10.465 …
```
> test/pybind/test_rados.py: fix warnings

- src/os/bluestore/BlueStore.cc
if one object has many `internal keys` at its omap beginning, it maybe very slow for the underlying seek to reach the first `user key` when initializing a omapiter.
this may stuck osd when build_push_op, seek recovering object's first omap key again and again. …
> os/bluestore: record omapiter init latency

- doc/radosgw/config-ref.rst
This PR commit updates RGW Config Reference - Lifecycle Settings section. In particular it addresses an incorrect suggestion to decrease parallel threads in the workers pool for a more aggressive/accelerated per-bucket lifecycle processing. A more aggressive lifecycle processing for a bucket containing higher number of objects is achieved by increasing, not decreasing parallel threads. 
Current suggestion is miss-leading.
Fixes: https://tracker.ceph.com/issues/63659
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-back …
> doc/radosgw/config-ref: fix lc worker thread tuning

- doc/cephadm/services/rgw.rst
- src/pybind/mgr/cephadm/services/cephadmservice.py
- src/pybind/mgr/cephadm/tests/test_services.py
- src/python-common/ceph/deployment/service_spec.py
This is desirable for an RGW service that you don't want to send multisite sync data so the RGW daemons can focus more on handling IO. Note they may still receive multisite sync data unless they are removed from the zone and zonegroup replication endpoints …
> mgr/cephadm: allow disabling rgw_run_sync_thread through spec

- doc/cephadm/services/osd.rst
- doc/man/8/cephadm.rst
- src/cephadm/cephadm.py
- src/cephadm/cephadmlib/file_utils.py
- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/orchestrator/_interface.py
- src/pybind/mgr/orchestrator/module.py
Issue: ceph orch <start/stop/restart> does not work for OSDs when deployment name is "osd", It fails with error Error EINVAL: Invalid service name "osd".
Solution: 
1. To fix this just added exception when service name is 'osd'
2. Added ceph command to make osd tied with certain service, by updating service name in unit.meta file. The 'ceph orch osd set-spec-affinity <service_name> <osd_id>...' command will call below cephadm command on respective host with all osd's of that host.
```
root@ceph-node-0 ~]# cephadm update-osd-service -h
usage: cephadm update-osd-service [-h] [--fsid FSID] --name NAME --service_name SERVICE_NAME
options:
-h, --help            show this help message and exit
--fsid FSID           cluster FSID
--name NAME           Comma seperated daemon name …
```
> mgr/cephadm:  ceph orch <start/stop/restart> commands should work for service name osd  and command to updated service name for osd

- src/pybind/mgr/orchestrator/module.py
Ceph orch apply command was showing exception trace back if yaml file has tailing tab
Fixes: https://tracker.ceph.com/issues/69192
Testing logs:
```
[ceph: root@ceph-node-0 /]# ceph orch apply -i iscsi-gw.yml 
Error EINVAL: Invalid YAML received : while scanning for the next token
found character '\t' that cannot start any token
in "<unicode string>", line 6, column 46:
... testceph.lab.pnq2.cee.redhat.com	
^
[ceph: root@ceph-node-0 /]# vi nfs.yml
[ceph: root@ceph-node-0 /]# ceph orch apply -i nfs.yml      
Error EINVAL: Invalid YAML received : while scanning for the next token
found character '\t' that cannot start any token
in "<unicode string>", line 6, column 12:
- host2	
^
[ceph: root@ceph-node-0 /]# …
```
> mgr/cephadm: mgr orchestrator module raise exception if there is trailing tab in yaml file

- src/pybind/mgr/cephadm/inventory.py
- src/pybind/mgr/cephadm/tests/test_cephadm.py
the previous code was not saving the certificates correctly, it just overwritten the same entry reducing all the certificates to only one. The new logic traverse and save all the certificates from the cert dictionary.
Fixes: https://tracker.ceph.com/issues/69252 …
> mgr/cephadm: fixing logic in cert-store save_cert method

- src/pybind/mgr/cephadm/ssh.py
When cephadm writes client files to hosts, the new files are created in /tmp/cephadm-<fsid> and then moved to their target directory. This makes the client files receive the usr_tmp_t context, which is different then their original context.
Restorecon will restore the type portion of the security context to be as defined in the SELinux policy for that file path.
Fixes: https://tracker.ceph.com/issues/69395 …
> mgr/cephadm: Restore client file(s) default SELinux context type

- PendingReleaseNotes
- qa/standalone/ceph-helpers.sh
- qa/standalone/mon/mon-cluster-log.sh
- src/common/options/mon.yaml.in
- src/mon/LogMonitor.cc
- src/mon/LogMonitor.h
backport tracker: https://tracker.ceph.com/issues/68690
---
backport of https://github.com/ceph/ceph/pull/47502
parent tracker: https://tracker.ceph.com/issues/57061
> squid: mon/LogMonitor: Use generic cluster log level config

- src/os/bluestore/BlueFS.cc
- src/os/bluestore/bluefs_types.cc
- src/os/bluestore/bluefs_types.h
- src/test/objectstore/test_bluefs.cc
In `struct bluefs_fnode_t` there is a vector `extents` and the vector `extents_index` that is a log2 seek cache.
Until modifications to truncate() we never removed extents from files. Modified truncate() did not update extents_index.
For example 10 extents long files when truncated to 0 will have: 0 extents, 10 extents_index.
After writing some data to file:
1 extents, 11 extents_index.
Now, `bluefs_fnode_t::seek` will binary search extents_index, lets say it located seek at item #3.
It will then jump up from #0 extent (that exists) to #3 extent which does not exist at.
The worst part is that code is now broken, as #3 != extent.end().
There are 3 parts of the fix:
1) assert in `bluefs_fnode_t::seek` to protect against
jumping outside extents
2) code in BlueFS::truncate to sync up …
> os/bluestore: Fix BlueFS::truncate()

- src/ceph-volume/ceph_volume/main.py
The importlib.metadata library removed older shims in releases >5.0.0 where EntryPoints objects use .select() instead of dict-like access.
Fixes: https://tracker.ceph.com/issues/68032
> [ceph-volume] fix importlib.metadata compat

- qa/standalone/scrub/osd-recovery-scrub.sh
- qa/standalone/scrub/osd-scrub-test.sh
- qa/standalone/scrub/scrub-helpers.sh
- src/common/config_cacher.h
In its get_tracked_conf_keys() member function, the cacher (in the existing code)
initializes a static function-block variable ('keys'), and uses it for
registering the observer.
But the cacher is instantiated on the type of
the configuration value. Thus, multiple cacher
objects for which the configuration values are
of the same type - share the static 'keys'. Only
one of the observers is registered.
Note that the code could have been simplified
somewhat, if the signature of the
get_tracked_conf_keys() function
was changed to return 'const char* const *'.
Fixes: https://tracker.ceph.com/issues/69236
Note:
Related to https://tracker.ceph.com/issues/69362
(which was errouneously marked as fixed by
https://github.com/ceph/ceph/pull/61184),
and its backport: …
> common: fix md_config_cacher_t

- src/msg/async/AsyncMessenger.cc
AsyncMessenger.cc : improve error messages
Thanks to Frank Schilder for calling this to my attention. …
> AsyncMessenger.cc : improve error messages

- examples/rgw/boto3/head_bucket_stats.py
- examples/rgw/boto3/service-2.sdk-extras.json
```
$ aws s3api head-bucket help
...
OPTIONS
...
--read-stats | --no-read-stats (boolean)
Read  additional  usage  statistics for ObjectCount and BytesUsed in
the response.
NOTE:
This request parameter is a Ceph RGW extension.
...
OUTPUT
...
ObjectCount -> (integer)
Total number of objects/versions in the bucket.
BytesUsed -> (integer)
Total size in bytes of all objects/versions in the bucket.
```
<details>
- …
> examples/rgw: register boto extension for HeadBucket stats

- qa/standalone/mon/mon-cluster-log.sh
backport tracker: https://tracker.ceph.com/issues/68948
---
backport of https://github.com/ceph/ceph/pull/60071
parent tracker: https://tracker.ceph.com/issues/67282
> reef: qa/standalone/mon/mon_cluster_log.sh: retry check for log line

- src/mon/Monitor.cc
NVMeoF gateway version is independent of ceph version so remove nvmeof in 'ceph versions' output.
To check for gateway version, use 'gw info' command.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2323851 …
> mon: do not show nvmeof in 'ceph versions' output

- src/os/bluestore/bluestore_tool.cc
It was possible to give multiple devices to cbt:
> ceph-bluestore-tool show-label --dev /dev/sda --dev /dev/sdb
But is any of devices cannot provide valid label, nothing was printed.
Now, always print results. Non readable labels are output as empty dictionaries. Exit code:
- 0 if any label properly read
- 1 if all labels failed
Fixes: https://tracker.ceph.com/issues/68680
(cherry picked from commit 8ebcb2dd46e5dc37a3e1ff6cc073351c4a2b5760) …
> squid: os/bluestore/ceph-bluestore-tool: Modify show-label for many devs

- qa/tasks/ceph.py
- qa/tasks/cephadm.py
- qa/tasks/rook.py
Badness check silently ignores when file does not exist on tasks ceph, cephadm, and rook. Due to this scenario, cephadm uses  incorrect file for check and has false positive.
Fixes: https://tracker.ceph.com/issues/57864
Signed-off-by: Christopher Hoffman <choffman@redhat.com>
<details> …
> qa/tasks: Include stderr on tasks badness check.

- src/msg/async/EventEpoll.cc
- src/msg/async/EventPoll.cc
- src/msg/async/Timeout.h
Currently, we always round down, which has a bad side effect: when a timer comes closer, we have lots of early wakeups, and eventually we'll run into a busy loop (timeout=0) when the timeout is less than one millisecond; the process will remain this busy loop for one millisecond, wasting lots of CPU time.
> msg/async: round timeouts up (fix busy loops)

- src/pybind/mgr/cephadm/services/nvmeof.py
- src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
- src/python-common/ceph/deployment/service_spec.py
mgr/cephadm/nvmeof: Add SPDK iobuf options field to NVMeOF configuration
Fixes https://tracker.ceph.com/issues/69554 …
> mgr/cephadm/nvmeof: Add SPDK iobuf options field to NVMeOF configuration

- src/common/CMakeLists.txt
- src/common/crc32c.cc
- src/common/crc32c_intel_fast.c
- src/common/crc32c_intel_fast.h
backport tracker: https://tracker.ceph.com/issues/67657
---
backport of https://github.com/ceph/ceph/pull/57271
parent tracker: https://tracker.ceph.com/issues/65791
> squid: common: Leverage a better CRC32C implementation

- doc/radosgw/config-ref.rst
This PR updates RGW Config Reference - Lifecycle Settings section.  
In particular it changes the section where two different tunings for two different workloads are suggested. It aims for a more understandable description as asked by the contributors in [#61272](https://github.com/ceph/ceph/pull/61272/).
Signed-off-by: Laimis Juzeliūnas <laimis.juzeliunas@oxylabs.io> …
> doc/radosgw/config-ref: fix lifecycle workload tuning description

- src/osd/OSDMap.cc
It appears adding 'reef' to pending_require_osd_release has been forgotten. This PR adds it
Signed-off-by: Philipp Hufangl <p.hufnagl@proxmox.com>
(cherry picked from commit e443ef3562f9718b224acb550206497b5fdfe82e)
(cherry picked from commit a6dc3b6e69ee591b08943fd00aef4d3e2fad9964)
This is a Reef backport PR
Fixes: https://tracker.ceph.com/issues/69150 …
> reef: osd: adding 'reef' to pending_require_osd_release

- qa/standalone/osd/osd-bluefs-volume-ops.sh
- src/os/bluestore/BlueStore.cc
When expansion crosses potential location of multi bdev label, we need to initialize the new label.
https://tracker.ceph.com/issues/68577 …
> os/bluestore: Create additional bdev labels when expanding block device.

- src/common/ceph_context.cc
backport tracker: https://tracker.ceph.com/issues/65924
---
backport of https://github.com/ceph/ceph/pull/54433
parent tracker: https://tracker.ceph.com/issues/63494
> reef: CephContext: acquire _fork_watchers_lock in notify_post_fork()

- qa/tasks/mgr/dashboard/test_rbd.py
- src/pybind/mgr/dashboard/controllers/__init__.py
- src/pybind/mgr/dashboard/controllers/_docs.py
- src/pybind/mgr/dashboard/controllers/cluster_configuration.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration-form/configuration-form-create-request.model.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration-form/configuration-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration-form/configuration-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/components/config-option/config-option.model.ts
- src/pybind/mgr/dashboard/openapi.yaml
backport tracker: https://tracker.ceph.com/issues/69272
backport of: #60798
parent tracker: https://tracker.ceph.com/issues/68976
<hr style="border: 2px solid #eeeee">
Fixes: https://tracker.ceph.com/issues/68976
Fixes Includes:
1) by-passing 'can_update_at_runtime' flag for 'rgw' related configurations as the same can be updated at runtime via CLI. Also implemented a warning popup for user to make force edit to rgw related configurations.
(cherry picked from commit 3181acc223dafd04e3fc56d418389ad50c5868e4)
https://github.com/user-attachments/assets/b4eb3357-2320-41f4-9400-1fe25e168a3c
- If you are …
> reef: mgr/dashboard: Administration > Configuration > Some of the config options are not updatable at runtime

- qa/suites/rbd/migration/6-prepare/qcow2-https.yaml
- src/librbd/migration/HttpClient.cc
backport tracker: https://tracker.ceph.com/issues/69242
---
backport of https://github.com/ceph/ceph/pull/61079
parent tracker: https://tracker.ceph.com/issues/69178
> reef: librbd/migration/HttpClient: avoid reusing ssl_stream after shut down

- src/librbd/ObjectMap.cc
- src/librbd/ObjectMap.h
- src/librbd/operation/FlattenRequest.cc
- src/test/librbd/test_internal.cc
backport tracker: https://tracker.ceph.com/issues/69328
---
backport of https://github.com/ceph/ceph/pull/61129
parent tracker: https://tracker.ceph.com/issues/68998
> reef: librbd: avoid data corruption on flatten when object map is inconsistent

- qa/workunits/rbd/cli_generic.sh
- src/test/cli/rbd/help.t
- src/tools/rbd/Utils.cc
- src/tools/rbd/Utils.h
- src/tools/rbd/action/Group.cc
backport tracker: https://tracker.ceph.com/issues/69331
---
backport of https://github.com/ceph/ceph/pull/61155
parent tracker: https://tracker.ceph.com/issues/69324
> reef: rbd: handle --{group,image}-namespace in "rbd group image {add,rm}"

- src/test/librbd/fsx.cc
The default was flipped in commit fcbf7367d285 ("rbd-nbd: map using netlink interface by default") in squid.  This is a reef-only fixup for fsx to counter failures like "Size error: expected 0xa5cac00 stat 0x0" which seem to be quite persistent on CentOS Stream 9.
This popped up in https://tracker.ceph.com/issues/69414.
> reef: test/librbd/fsx: switch to netlink interface for rbd-nbd

- src/osd/OSD.cc
- src/osd/OSD.h
backport tracker: https://tracker.ceph.com/issues/64168
---
backport of https://github.com/ceph/ceph/pull/52530
parent tracker: https://tracker.ceph.com/issues/59531
> reef: osd: Add memstore to unsupported objstores for QoS

- src/os/bluestore/BlueFS.cc
- src/os/bluestore/BlueRocksEnv.cc
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/os/bluestore/bluefs_types.cc
- src/os/bluestore/bluefs_types.h
- src/test/objectstore/store_test.cc
- src/test/objectstore/test_bluefs.cc
Now when truncate() drops unused allocations.
Modified Close() in BlueRocksEnv to unconditionally call truncate.
Fixes: https://tracker.ceph.com/issues/68486
Now also includes #61314 …
> squid: os/bluestore: Make truncate() drop unused allocations

- src/rgw/radosgw-admin/radosgw-admin.cc
Converted `std::string_view` members to `std::string` to avoid use after free. `std::string_view` does not own the underlying data so the temporarily created strings for error/status go out of scope before it gets printed as part of the status. 
Regression was introduced in commit e84c7fcc57f6e6f453b6d6c4dbeffa7b1154d793 ([link](https://github.com/ceph/ceph/commit/e84c7fcc57f6e6f453b6d6c4dbeffa7b1154d793)). …
> rgw: fix radosgw-admin use after free in bucket sync status

- src/rgw/driver/rados/rgw_user.cc
the admin api uses a separate `dump_user_info()` function that wasn't updated with the account changes to `RGWUserInfo::dump()`
Fixes: https://tracker.ceph.com/issues/69462
<details>
</details>
> rgw: /admin/user api dumps account-related user info

- src/rgw/rgw_op.cc
Currently, RGW returns a 200 on a successful DELETE on a bucket policy but the S3 API expects a 204:
https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteBucketPolicy.html
The sample response in the example above is a 204.
This patch checks the op_ret in `RGWDeleteBucketPolicy::send_response()` and on a success we turn it to a 204 (or STATUS_NO_CONTENT).
(Basically a copy of https://github.com/ceph/ceph/pull/35059 which handled the same for PUT Bucket Policy)
Fixes: https://tracker.ceph.com/issues/69539 …
> rgw: S3 Delete Bucket Policy should return 204 on success

- src/test/osd/TestOSDMap.cc
backport tracker: https://tracker.ceph.com/issues/67235
---
backport of https://github.com/ceph/ceph/pull/58406
parent tracker: https://tracker.ceph.com/issues/42884
> reef: test: Create ParallelPGMapper object before start threadpool

- src/rgw/rgw_common.h
- src/rgw/rgw_rest_swift.cc
- src/rgw/services/svc_bucket_sobj.cc
Fixes: https://tracker.ceph.com/issues/68195
This PR adds `last_modified` JSON field to the Swift bucket listing response.
It is present in [Swift API spec](https://docs.openstack.org/api-ref/object-store/), but currently is missing in the RGW response.
Result looks the following way
```bash
curl -v -XGET 127.0.0.1:8080/swift/v1/AUTH_2421cecf177b41f683bdcd09338f1ebd -H "X-Auth-Token: ${OS_AUTH_TOKEN}" -H "Accept: application/json" 
…
[{"name":"bucket1","count":1,"bytes":2814,"last_modified":"2024-12-11T13:44:15.761Z"}]
curl -v -XGET 127.0.0.1:8080/swift/v1/AUTH_2421cecf177b41f683bdcd09338f1ebd/bucket1 -H "X-Auth- Token: ${OS_AUTH_TOKEN}" -H "Accept: application/json" 
…
Last-Modified: Wed, 11 Dec 2024 13:44:15 GMT 
…
``` …
> rgw: add missing last_modified field to swift api

- src/rgw/driver/rados/rgw_data_sync.cc
- On destination bucket `verify_bucket_permission()` in `RGWObjFetchCR()` use `set_cr_error()` to return `-EPERM` so it can be reflected in `RGWBucketSyncSingleEntryCR()` for skipping on `-EPERM`.
- As of offloading source bucket perm check to the source cluster by (a3f40b4) the http result of 403 would be translated to EACCES by rgw_http_error_to_errno() so we need to also consider EACCES to be skipped in RGWBucketSyncSingleEntryCR().
Fixes: https://tracker.ceph.com/issues/69450
> rgw: set retcode on verify_bucket_permission in RGWObjFetchCR

- src/rgw/driver/rados/rgw_rest_log.cc
- src/rgw/radosgw-admin/sync_checkpoint.cc
`bucket_source_sync_checkpoint()` requires bucket id to lookup for full-sync object and the dest pipe doesn't have it. by replcaning the bucket key in the pipe with the bucket info we will ensure the bucket id is set.
Fixes: https://tracker.ceph.com/issues/69548
> rgw: set dest bucket id in bucket sync checkpoint

- doc/releases/squid.rst
This change is to update 19.2.0 Squid release documentation with a warning for users regarding potential placement group balancer issues.
Ceph 19.2.0 has a known pg balancer bug that requires users to disable the balancer completely for the cluster to operate. While there is a potential fix introduced in 19.2.1 release the number of users encountering this issue during/post upgrade to 19.2.0 is still growing. Users should be warned before upgrading of possible issues.
Tracker issue mentioned in the warning: https://tracker.ceph.com/issues/68657
A portion of users seeking advice from Ceph mailing list regarding 19.2.0 balancer issues below:
https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/message/PLCIMVZYXT2QPHZGVTMBJ4OIJ2QGSAJC/ …
> doc/releases /squid: add warning for balancer issues

- src/pybind/mgr/dashboard/HACKING.rst
- src/test/pybind/test_ceph_argparse.py
- src/tools/cephfs/top/cephfs-top
Signed-off-by: Paulo E. Castro <pecastro@wormholenet.com>
(cherry picked from commit aec8ca8b2688be5b460c822cab7ae6ba47bf4c80)
test/pybind: Test method has been renamed in unittest 3.2
Signed-off-by: Paulo E. Castro <pecastro@wormholenet.com>
(cherry picked from commit 560d66e34edacef0bed3c44ff8a02be6f79b5fbe)
doc: Fix typo.
Signed-off-by: Paulo E. Castro <pecastro@wormholenet.com>
(cherry picked from commit 5a886ee6ce9e55e9f66da6cff45945fba354bd69)
tools/cephfs: fix flake8 f-string formatting for py3.12
Signed-off-by: Paulo E. Castro <pecastro@wormholenet.com>
(cherry picked from commit 2b2ce7871579252074eff7b6072890196b1e4f2c)
- If you are …
> squid: test/pybind: Clean whitespace. (Doc and test fixes)

- src/exporter/ceph_exporter.cc
Revert part of 99f4eccb6bef444f86e6d6cbf579dc3ba975af98. The lines removed here were reported to me by Anthony D'Atri, who says that Juan Miguel Olmo told him that they should not be in the Squid branch.
See https://github.com/ceph/ceph/pull/61331#issuecomment-2596058701 …
> squid: src/exporter: revert incorrect lines

- doc/radosgw/config-ref.rst
This commit updates RGW Config Reference - Lifecycle Settings section. In particular it addresses an incorrect suggestion to decrease parallel threads in the workers pool for a more aggressive/accelerated per-bucket lifecycle processing. A more aggressive lifecycle processing for a bucket containing higher number of objects is achieved by increasing, not decreasing parallel threads. Current suggestion is miss-leading.
Fixes: https://tracker.ceph.com/issues/63659
(cherry picked from commit b7ae18a292c7d1d5139dfb74c575f1af0de29a3e) …
> squid: doc/radosgw/config-ref: fix lc worker thread tuning

- doc/radosgw/config-ref.rst
This commit updates RGW Config Reference - Lifecycle Settings section. In particular it addresses an incorrect suggestion to decrease parallel threads in the workers pool for a more aggressive/accelerated per-bucket lifecycle processing. A more aggressive lifecycle processing for a bucket containing higher number of objects is achieved by increasing, not decreasing parallel threads. Current suggestion is miss-leading.
Fixes: https://tracker.ceph.com/issues/63659
(cherry picked from commit b7ae18a292c7d1d5139dfb74c575f1af0de29a3e) …
> reef: doc/radosgw/config-ref: fix lc worker thread tuning

- doc/radosgw/config-ref.rst
This commit updates RGW Config Reference - Lifecycle Settings section. In particular it addresses an incorrect suggestion to decrease parallel threads in the workers pool for a more aggressive/accelerated per-bucket lifecycle processing. A more aggressive lifecycle processing for a bucket containing higher number of objects is achieved by increasing, not decreasing parallel threads. Current suggestion is miss-leading.
Fixes: https://tracker.ceph.com/issues/63659
(cherry picked from commit b7ae18a292c7d1d5139dfb74c575f1af0de29a3e) …
> quincy: doc/radosgw/config-ref: fix lc worker thread tuning

- src/pybind/mgr/dashboard/controllers/smb.py
- src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/mgr-modules/mgr-module-details/mgr-module-details.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/mgr-modules/mgr-module-list/mgr-module-list.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/mgr-modules/mgr-module-list/mgr-module-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-list/smb-cluster-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/error/error.component.html
- src/pybind/mgr/dashboard/frontend/src/app/core/error/error.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/mgr-module.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/mgr-module.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/module-status-guard.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/services/module-status-guard.service.ts
This PR intorduces the SMB module status check to check and display the missing smb module frontend page where is displayed a button to enable the smb module. As can be seen in the video below.
To do this, to two new options are added to the `error.component`; `button_to_enable_module` to add the button to enable the specified module in this variable, and also `navigate_to` which allows to redirect to the specifed path.
[screen-capture (35).webm](https://github.com/user-attachments/assets/f0b6b8c1-d14b-464e-82de-812b730a3297)
Fixes: https://tracker.ceph.com/issues/69202
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer …
> mgr/module: Smb module check

- src/crimson/osd/osd_operations/replicated_request.cc
02b70a62a4 moved the call to handle.complete() into the finally, but didn't extend the pg ref lifetime until after the complete resolved.
<details>
</details>
> crimson/.../replicated_request: fix pg lifetime in with_pg finally

- doc/cephfs/snapshots.rst
This commit improves the grammar in doc/cephfs/snapshots.rst. The PR associated with this commit follows from
https://github.com/ceph/ceph/pull/61240, the PR raised by Neeraj Pratap Singh to introduce information about snapshots into the CephFS documentation.
See also https://tracker.ceph.com/issues/68974. …
> doc/cephfs: edit grammar in snapshots.rst

- doc/cephfs/snapshots.rst
This commit improves the grammar in doc/cephfs/snapshots.rst. The PR associated with this commit follows from
https://github.com/ceph/ceph/pull/61240, the PR raised by Neeraj Pratap Singh to introduce information about snapshots into the CephFS documentation.
See also https://tracker.ceph.com/issues/68974.
(cherry picked from commit 9a34ae55ede6dea5bb784a3e6cd45b9e60d4475d)
- When …
> reef: doc/cephfs: edit grammar in snapshots.rst

- doc/cephfs/snapshots.rst
This commit improves the grammar in doc/cephfs/snapshots.rst. The PR associated with this commit follows from
https://github.com/ceph/ceph/pull/61240, the PR raised by Neeraj Pratap Singh to introduce information about snapshots into the CephFS documentation.
See also https://tracker.ceph.com/issues/68974.
(cherry picked from commit 9a34ae55ede6dea5bb784a3e6cd45b9e60d4475d)
- When …
> squid: doc/cephfs: edit grammar in snapshots.rst

- doc/radosgw/lua-scripting.rst
- src/common/options/rgw.yaml.in
- src/rgw/rgw_lua.cc
- src/rgw/rgw_lua_background.cc
- src/rgw/rgw_lua_data_filter.cc
- src/rgw/rgw_lua_request.cc
- src/rgw/rgw_lua_utils.cc
- src/rgw/rgw_lua_utils.h
- src/test/rgw/test_rgw_lua.cc
These changes improve the robustness and reliability of Lua script execution in the RADOS Gateway by enforcing configurable limit on execution time. By enforcing a maximum execution time, this change ensures that Lua scripts do not cause performance degradation or resource exhaustion.
- Enhanced `lua_state_guard` to support configurable runtime limits for Lua scripts.
- Utilized `lua_sethook` to enforce execution time limits by setting a hook that interrupts scripts when the limit is exceeded.
- Updated rgw.yaml.in to include new configuration options for Lua runtime limits.
- Added tests in `test_rgw_lua.cc` to verify Lua script execution with different runtime constraints.
- Updated `Lua scripting` documentation to reflect the new runtime limit configuration. …
> rgw/lua: add configurable runtime limit for the lua state

- src/nvmeof/NVMeofGwMonitorClient.cc
Removing compiler warnings:
```
Building CXX object src/CMakeFiles/ceph-nvmeof-monitor-client.dir/nvmeof/NVMeofGwMonitorClient.cc.o
..../src/nvmeof/NVMeofGwMonitorClient.cc:154:34: warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
154 |   monc.register_config_callback([this](const std::string &k, const std::string &v){
|                                  ^~~~
..../src/nvmeof/NVMeofGwMonitorClient.cc:160:41: warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
160 |   monc.register_config_notify_callback([this]() {
|                                         ^~~~
```
> mon/nvme: fix unused lambda capture warnings

- ceph.spec.in
- container/Containerfile
#58376 is merged and **libcephfs proxy** is now available with the development branch. We had a temporary change https://github.com/ceph/ceph/commit/517a3458af887defafa5e98481dc1f83a6fa1889 inside rpm spec file to get `libcephfs-daemon` installed within container builds. Given the nature of the package, it is not a strict requirement but would be preferable going forward. Replacing `Requires` with `Recommends` may not help in container build process where `--setopt=install_weak_deps=False` is commonly used. Therefore we specifically add `libcephfs-daemon` to the list of packages to be installed in containers.
Also see https://github.com/ceph/ceph-container/issues/2240.
> Containerfile: Add `libcephfs-daemon` package

- doc/dev/erasure-coded-pool.rst
- doc/dev/osd_internals/erasure_coding/developer_notes.rst
- doc/rados/operations/erasure-code-isa.rst
- doc/rados/operations/erasure-code-jerasure.rst
- doc/rados/operations/erasure-code-lrc.rst
- doc/rados/operations/erasure-code-profile.rst
- doc/rados/operations/erasure-code.rst
- qa/standalone/erasure-code/test-erasure-code-plugins.sh
- qa/standalone/mon/osd-erasure-code-profile.sh
- qa/standalone/mon/osd-pool-create.sh
- qa/tasks/ceph.conf.template
- qa/tasks/cephadm.conf
- qa/tasks/mgr/dashboard/test_erasure_code_profile.py
- src/common/options/global.yaml.in
- src/erasure-code/lrc/ErasureCodeLrc.cc
- src/test/ceph-erasure-code-tool/test_ceph-erasure-code-tool.sh
- src/test/erasure-code/TestErasureCodeLrc.cc
- src/test/erasure-code/ceph_erasure_code_benchmark.cc
- src/test/erasure-code/ceph_erasure_code_non_regression.cc
- src/vstart.sh
This PR changes the default plugin for erasure coded pools from Jerasure to ISA-L. Until now, Jerasure has been Ceph's default plugin due to its flexibility and genericism. However, the jerasure and gf-complete libraries no longer appear to be maintained, and they have not been updated to use modern CPU instructions such as AVX2 and AVX512. Using these instructions for erasure coding can result in performance improvements. ISA-L on the other hand is still maintained and receives updates to take advantage of modern CPU features. ISA-L also offers comparable flexibility to Jerasure.
Testing with the ceph_erasure_code_benchmark tool shows the potential for performance improvements when using ISA-L instead of Jerasure.
This benchmark data was captured by compiling Ceph from source and then …
> core: Change the default plugin for Ceph erasure coded pools from Jerasure to ISA-L

- src/mon/Monitor.cc
- src/mon/Monitor.h
During handle of scrub operation if scrub_state is reset via bootstrap then a process might be crash.
Solution: Create a local copy of scrub_state shared_ptr. By doing this the refcounter will be increment 
and object will not be destroyed in that scope.
Fixes: https://tracker.ceph.com/issues/67270
Credits: Radoslaw Zarzynski <rzarzyns@redhat.com> …
> mon: Create a local copy of scrub_state to avoid a crash

- src/rgw/driver/daos/rgw_sal_daos.cc
- src/rgw/driver/daos/rgw_sal_daos.h
- src/rgw/driver/motr/rgw_sal_motr.cc
- src/rgw/driver/motr/rgw_sal_motr.h
- src/rgw/driver/posix/rgw_sal_posix.cc
- src/rgw/driver/posix/rgw_sal_posix.h
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
- src/rgw/driver/rados/rgw_sal_rados.cc
- src/rgw/driver/rados/rgw_sal_rados.h
- src/rgw/radosgw-admin/radosgw-admin.cc
- src/rgw/rgw_lc.cc
- src/rgw/rgw_sal.h
- src/rgw/rgw_sal_dbstore.cc
- src/rgw/rgw_sal_dbstore.h
- src/rgw/rgw_sal_filter.cc
- src/rgw/rgw_sal_filter.h
Add the API `process_expired_objects` which is used to process and delete the expired objects (swift or temporarily restored from cloud) to the Zipper interface.
Fixes: https://tracker.ceph.com/issues/68862
<details>
- `jenkins test ceph-volume …
> rgw: Add object expirer API to the SAL interface

- src/rgw/driver/dbstore/common/dbstore.cc
- src/rgw/driver/dbstore/common/dbstore.h
- src/rgw/driver/dbstore/sqlite/sqliteDB.cc
- src/rgw/rgw_sal_dbstore.cc
With commit#8c025045332a8005c6e82308fc17a33d38058734, changes were made to call put_info while erasing bucket attrs. But DBStore wasn't updating attrs as part of put_info operation. This commit addresses the same.
Fixes: https://tracker.ceph.com/issues/69441
<details> …
> rgw/dbstore: Update bucket attrs as part of put_info()

- doc/cephfs/disaster-recovery-experts.rst
Edit the seventh and final section of
The section edited in this commit is
* Using an alternate metadata pool for recovery
A future commit might beneficially put this section into the format of an ordered list. If so, such a commit should only reformat the content and should not make any changes to the English. It's enough to verify content or format. Let's not overload our editorial faculties by forcing ourselves to walk and chew gum at the same time.
Follows https://github.com/ceph/ceph/pull/61442 …
> doc/cephfs: edit disaster-recovery-experts (4 of x)

- doc/man/8/mount.ceph.rst
Change the default from "wsync" to "nowsync". "nowsync" has been the default since kernel version 5.16.
This information was reported on
https://pad.ceph.com/p/Report_Documentation_Bugs by Benjamin Mare on 07 Oct 2024.
The commit relevant to this change can be seen here, in Linus's main branch:
https://github.com/torvalds/linux/commit/f7a67b463fb83a4b9b11ceaa8ec4950b8fb7f902
(cherry picked from commit 9f0af5d75dc64ef0520fd78f29815d2a824a859b) …
> squid: doc/man: supplant "wsync" with "nowsync" as the default

- doc/cephfs/mount-using-kernel-driver.rst
Edit the first third of doc/cephfs/mount-using-kernel-driver.rst in preparation for correcting mount commands that may not work in Reef as described in this documentation.
This commit is a cherry-pick from a branch that targeted the Reef release branch. After some thought I realized that there was no reason that the Engliish grammar shouldn't be clean in this branch too.
(cherry picked from commit 7fc0ead36cadb7a10e57c50b2064b71124c9e288) …
> squid: doc/cephfs: edit first 3rd of mount-using-kernel-driver

- doc/cephfs/mount-using-kernel-driver.rst
Edit the first third of doc/cephfs/mount-using-kernel-driver.rst in preparation for correcting mount commands that may not work in Reef as described in this documentation.
This commit is a cherry-pick from a branch that targeted the Reef release branch. After some thought I realized that there was no reason that the Engliish grammar shouldn't be clean in this branch too.
(cherry picked from commit 7fc0ead36cadb7a10e57c50b2064b71124c9e288) …
> quincy: doc/cephfs: edit first 3rd of mount-using-kernel-driver

- doc/cephfs/mount-using-kernel-driver.rst
Edit the second third of doc/cephfs/mount-using-kernel-driver.rst in preparation for correcting mount commands that may not work in Reef as described in this documentation.
(cherry picked from commit 0526124b60500f97f536060ba372d2753b936c9e) …
> squid: doc/cephfs: edit 2nd 3rd of mount-using-kernel-driver

- doc/cephfs/mount-using-kernel-driver.rst
Edit the second third of doc/cephfs/mount-using-kernel-driver.rst in preparation for correcting mount commands that may not work in Reef as described in this documentation.
(cherry picked from commit 0526124b60500f97f536060ba372d2753b936c9e) …
> reef: doc/cephfs: edit 2nd 3rd of mount-using-kernel-driver

- doc/cephfs/mount-using-kernel-driver.rst
Edit the second third of doc/cephfs/mount-using-kernel-driver.rst in preparation for correcting mount commands that may not work in Reef as described in this documentation.
(cherry picked from commit 0526124b60500f97f536060ba372d2753b936c9e) …
> quincy: doc/cephfs: edit 2nd 3rd of mount-using-kernel-driver

- doc/cephfs/disaster-recovery-experts.rst
Edit the seventh and final section of
The section edited in this commit is
* Using an alternate metadata pool for recovery
A future commit might beneficially put this section into the format of an ordered list. If so, such a commit should only reformat the content and should not make any changes to the English. It's enough to verify content or format. Let's not overload our editorial faculties by forcing ourselves to walk and chew gum at the same time.
Follows https://github.com/ceph/ceph/pull/61442 …
> squid: doc/cephfs: edit disaster-recovery-experts (4 of x)

- doc/cephfs/disaster-recovery-experts.rst
Edit the seventh and final section of
The section edited in this commit is
* Using an alternate metadata pool for recovery
A future commit might beneficially put this section into the format of an ordered list. If so, such a commit should only reformat the content and should not make any changes to the English. It's enough to verify content or format. Let's not overload our editorial faculties by forcing ourselves to walk and chew gum at the same time.
Follows https://github.com/ceph/ceph/pull/61442 …
> reef: doc/cephfs: edit disaster-recovery-experts (4 of x)

- src/rgw/rgw_lc.cc
backport tracker: https://tracker.ceph.com/issues/69564
---
backport of https://github.com/ceph/ceph/pull/61277
parent tracker: https://tracker.ceph.com/issues/69459
> reef: rgw/lc: make lc worker thread name shorter

- container/build.sh
release builds were using the wrong container repo name because of confused variable naming and inadequate separation.  Keep the hostname, org name, and repo name in separate variables, and assemble the full path with a version when tagging is done. …
> container/build.sh: fix up org vs. repo naming

- src/os/bluestore/BlueFS.cc
- src/os/bluestore/BlueRocksEnv.cc
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/os/bluestore/bluefs_types.cc
- src/os/bluestore/bluefs_types.h
- src/test/objectstore/store_test.cc
- src/test/objectstore/test_bluefs.cc
Now when truncate() drops unused allocations.
Modified Close() in BlueRocksEnv to unconditionally call truncate.
Fixes: https://tracker.ceph.com/issues/68488 …
> reef: os/bluestore: Make truncate() drop unused allocations

- src/script/ceph-backport.sh
GNU grep v3.8 [release notes](https://git.savannah.gnu.org/cgit/grep.git/tree/NEWS#n85) has the following mention about the usage of backslashes:
> Regular expressions with stray backslashes now cause warnings, as their unspecified behavior can lead to unexpected results.
. . .
> The warnings are intended as a transition aid; they are likely to be errors in future releases.
As a result we see the warning "grep: warning: stray \ before /" during script execution. Therefore remove the extra `\` from grep command.
> script/ceph-backport: Remove stray `\` from grep command

- src/pybind/mgr/cephadm/serve.py
Handle scenarios where the SSH connection is closed or broken. Ensure commands like exiting maintenance attempt to reconnect rather than throwing an error to the user.
Fixes: https://tracker.ceph.com/issues/67905 …
> mgr/cephadm: Retry command when SSH connection closes

- doc/cephadm/upgrade.rst
- src/pybind/mgr/cephadm/inventory.py
- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/upgrade.py
- src/pybind/mgr/orchestrator/_interface.py
- src/pybind/mgr/orchestrator/module.py
- src/python-common/ceph/cephadm/images.py
mgr/cephadm: Command to upgrade non-ceph image services with custom image
Added a command to upgrade non-ceph image services, it will combine 'ceph config set mgr/cephadm/container_image_<daemon-type>' and 'ceph orch redeploy <service-of-that-daemon-type>' functionality.
Fixes: https://tracker.ceph.com/issues/68979
Testing logs:
```
[ceph: root@ceph-node-0 /]# ceph orch upgrade-image smb quay.io/samba.org/samba-server:latest 
Processing "smb.test1" service
Scheduled to redeploy smb.test1.ceph-node-0.xeffdz on host 'ceph-node-0'
Processing "smb.test2" service
Scheduled to redeploy smb.test2.ceph-node-0.hioiam on host 'ceph-node-0'
[ceph: root@ceph-node-0 /]# ceph orch upgrade-image prometheus …
```
> mgr/cephadm: Command to upgrade non-ceph image services with custom image

- src/pybind/mgr/orchestrator/module.py
cephadm: ceph orch upgrade status - Display easily understandable message
Tracker: https://tracker.ceph.com/issues/68999
Test logs:
```
[ceph: root@ceph-node-0 ~]# ceph orch upgrade start --image quay.io/kdeb/ceph:upgrade_status-2 --daemon_types mgr
Initiating upgrade to quay.io/kdeb/ceph:upgrade_status-2
[ceph: root@ceph-node-0 ~]# ceph orch ls
NAME                       PORTS  RUNNING  REFRESHED  AGE   PLACEMENT  
crash                                 3/3  8m ago     103m  *          
mgr                                   2/2  8m ago     103m  count:2    
mon                                   3/5  8m ago     103m  count:5    
osd.all-available-devices               3  8m ago     101m  *          
[ceph: root@ceph-node-0 ~]# ceph orch upgrade status
{
"target_image": …
```
> cephadm: ceph orch upgrade status - Display easily understandable message

- src/cephadm/cephadmlib/daemons/ceph.py
- src/python-common/ceph/deployment/service_spec.py
Fixes: https://tracker.ceph.com/issues/69475
It turns out the sock-dir for ceph-exporter only needs to exist within the container, not on the host. Previous code, including the validation function this commit removes and previous patches trying to fix the ceph-exporter asok file not appearing on the host, were all done assuming it mattered what was on the host. This patch changes things so all we do with the sock dir is mount it to /var/run/ceph/<fsid> and don't worry about whether that dir exists on the host. Additionally, the patch makes it so /var/run/ceph/<fsid> is created during ceph-exporter deployment. …
> cephadm: fix handling of ceph-exporter sock-dir

- src/pybind/mgr/cephadm/tests/test_services.py
- src/python-common/ceph/deployment/service_spec.py
mgr/cephadm: Open prometheus port 10008, as part of nvmeof gateway deployment
Fixes: https://tracker.ceph.com/issues/69541
Testing logs:
```
[ceph: root@ceph-node-0 /]# ceph osd pool create nvmeof_pool01
pool 'nvmeof_pool01' created
[ceph: root@ceph-node-0 /]#  ceph orch apply nvmeof nvmeof_pool01 grp01 --placement="*"
Scheduled nvmeof.nvmeof_pool01.grp01 update...
[ceph: root@ceph-node-0 /]# ceph orch ls
NAME                        PORTS                   RUNNING  REFRESHED  AGE  PLACEMENT  
crash                                                   3/3  5s ago     39m  *          
mgr                                                     2/2  5s ago     39m  count:2    
mon …
```
> mgr/cephadm: After deploying nvmeof gateway group, the prometheus port 10008/tcp is not opened

- src/osd/PrimaryLogPG.cc
- src/test/librados/io_cxx.cc
- src/test/librados/test_cxx.cc
- src/test/librados/test_cxx.h
- src/test/librados/testcase_cxx.cc
- src/test/librados/testcase_cxx.h
- src/test/pybind/test_rados.py
backport tracker: https://tracker.ceph.com/issues/66139
---
backport of https://github.com/ceph/ceph/pull/55008
parent tracker: https://tracker.ceph.com/issues/53240
> squid: osd: full-object read CRC mismatch due to 'truncate' modifying oi.size w/o clearing 'data_digest'

- src/mgr/Mgr.cc
backport tracker: https://tracker.ceph.com/issues/65622
---
backport of https://github.com/ceph/ceph/pull/56047
parent tracker: https://tracker.ceph.com/issues/64799
> squid: mgr: process map before notifying clients

- doc/cephfs/disaster-recovery-experts.rst
Put the procedure in the section called "Using an alternate metadata pool for recovery" into an ordered list, so that it is in a proper procedure format.
This commit is meant only to break the procedure into steps. The English language in each of these steps could be improved, but that improvement will be done after this formatting has been merged and backported.
Follows https://github.com/ceph/ceph/pull/61462.
(cherry picked from commit 9af7d9786a11e2b07a095c95ae911dfb13e4a61b) …
> squid: doc/cephfs: edit disaster-recovery-experts (5 of x)

- doc/cephfs/disaster-recovery-experts.rst
Put the procedure in the section called "Using an alternate metadata pool for recovery" into an ordered list, so that it is in a proper procedure format.
This commit is meant only to break the procedure into steps. The English language in each of these steps could be improved, but that improvement will be done after this formatting has been merged and backported.
Follows https://github.com/ceph/ceph/pull/61462.
(cherry picked from commit 9af7d9786a11e2b07a095c95ae911dfb13e4a61b) …
> reef: doc/cephfs: edit disaster-recovery-experts (5 of x)

- src/common/options/osd.yaml.in
Modifying the default value of osd_scrub_load_threshold from 0.5 to 10.0, rendering it mostly irrelevant.
That is done following a combination of reasons:
- the new mclock scheduler, which provides a better mechanism to control scrub load under all conditions;
- the inapplicability of the existing mechanism to Crimson; and
- users` requests.
> osd/scrub: increase the default scrub load limit

- qa/tasks/s3tests_java.py
backport tracker: https://tracker.ceph.com/issues/69211
---
backport of https://github.com/ceph/ceph/pull/61010
parent tracker: https://tracker.ceph.com/issues/69204
> reef: qa/rgw: fix s3 java tests by forcing gradle to run on Java 8

- qa/suites/rgw/notifications/tasks/test_kafka.yaml
- qa/tasks/kafka.py
- qa/tasks/s3a_hadoop.py
Currently maven and kafka are pulled from archive.apache.org. This uses Apache's "closer" calculator to find a mirror to use instead.
(cherry picked from commit 3aae66611dd7f05612056a757cb7a87dfcf95de0)
Fixes: https://tracker.ceph.com/issues/69255 …
> reef: qa/rgw: pull Apache artifacts from mirror instead of archive.apache.org

- src/librbd/librbd.cc
Image::aio_close() must clear ctx before initiating close.  Otherwise the provided callback may see a non-NULL ctx and attempt to close the image again from Image destructor, leading to an invalid memory access as ImageCtx and ImageState are both freed immediately after the image is closed (i.e. before AioCompletion is completed and the callback is executed).
The same adjustment is made to Image::close() just for consistency.
Fixes: https://tracker.ceph.com/issues/69619
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches- …
> librbd: clear ctx before initiating close in Image::{aio_,}close()

- doc/cephfs/disaster-recovery-experts.rst
In doc/cephfs/disaster-recovery-experts.rst, incorporate Anthony's suggestions in
https://github.com/ceph/ceph/pull/61462#discussion_r1923917812 and
https://github.com/ceph/ceph/pull/61462#discussion_r1923920724
and reword the sentences in the section "Using an alternate metadata pool for recovery" to be in the imperative mood, which better suits the ordered list format that was introduced in
https://github.com/ceph/ceph/pull/61493.
Follows https://github.com/ceph/ceph/pull/61493. …
> doc/cephfs: edit disaster-recovery-experts (6 of x)

- doc/rados/operations/user-management.rst
For the "profile {name}" syntax, pool and namespace restrictions are independent of each other (i.e. specifying namespace doesn't also require specifying pool like is currently suggested).  A cap can look like "profile rbd namespace=myns", signifying that the RBD profile is to be allowed in myns namespace of any pool.
For the "allow {access-spec}" syntax, pool restriction is optional. A cap can look like "allow r namespace=myns", "allow w object_prefix myprefix" or "allow rw namespace=myns object_prefix myprefix", for example. …
> doc/rados: pool and namespace are independent osdcap restrictions

- doc/rados/operations/user-management.rst
For the "profile {name}" syntax, pool and namespace restrictions are independent of each other (i.e. specifying namespace doesn't also require specifying pool like is currently suggested).  A cap can look like "profile rbd namespace=myns", signifying that the RBD profile is to be allowed in myns namespace of any pool.
For the "allow {access-spec}" syntax, pool restriction is optional. A cap can look like "allow r namespace=myns", "allow w object_prefix myprefix" or "allow rw namespace=myns object_prefix myprefix", for example.
(cherry picked from commit 67f5769ce6e110b89362763cfb41a0e00e595cdf)
- If …
> reef: doc/rados: pool and namespace are independent osdcap restrictions

- doc/rados/operations/user-management.rst
For the "profile {name}" syntax, pool and namespace restrictions are independent of each other (i.e. specifying namespace doesn't also require specifying pool like is currently suggested).  A cap can look like "profile rbd namespace=myns", signifying that the RBD profile is to be allowed in myns namespace of any pool.
For the "allow {access-spec}" syntax, pool restriction is optional. A cap can look like "allow r namespace=myns", "allow w object_prefix myprefix" or "allow rw namespace=myns object_prefix myprefix", for example.
(cherry picked from commit 67f5769ce6e110b89362763cfb41a0e00e595cdf)
- If …
> squid: doc/rados: pool and namespace are independent osdcap restrictions

- doc/cephadm/host-management.rst
"... will be only affect ..." should read as "... will only affect ..." "...host will no remove any..." should read as "...host will not remove any..."
Signed-off-by: Stephen Wilson <swilson@redhat.com>
<details> …
> doc/cephadm: correct grammar in host-management.rst

- doc/cephfs/disaster-recovery-experts.rst
In doc/cephfs/disaster-recovery-experts.rst, incorporate Anthony's suggestions in
https://github.com/ceph/ceph/pull/61462#discussion_r1923917812 and
https://github.com/ceph/ceph/pull/61462#discussion_r1923920724
and reword the sentences in the section "Using an alternate metadata pool for recovery" to be in the imperative mood, which better suits the ordered list format that was introduced in
https://github.com/ceph/ceph/pull/61493.
Follows https://github.com/ceph/ceph/pull/61493.
(cherry picked from commit 5670054bd0533c8f2507d0596797214da8ba489a) …
> squid: doc/cephfs: edit disaster-recovery-experts (6 of x)

- doc/cephfs/disaster-recovery-experts.rst
In doc/cephfs/disaster-recovery-experts.rst, incorporate Anthony's suggestions in
https://github.com/ceph/ceph/pull/61462#discussion_r1923917812 and
https://github.com/ceph/ceph/pull/61462#discussion_r1923920724
and reword the sentences in the section "Using an alternate metadata pool for recovery" to be in the imperative mood, which better suits the ordered list format that was introduced in
https://github.com/ceph/ceph/pull/61493.
Follows https://github.com/ceph/ceph/pull/61493.
(cherry picked from commit 5670054bd0533c8f2507d0596797214da8ba489a) …
> reef: doc/cephfs: edit disaster-recovery-experts (6 of x)

- src/osd/scrubber/osd_scrub.cc
- src/osd/scrubber/osd_scrub_sched.cc
- src/osd/scrubber/pg_scrubber.cc
- src/osd/scrubber/scrub_job.cc
Use the RAII wrappers for the dump Formatters,
instead of manually opening and closing sections.
> osd/scrub: use ObjectSection & ArraySection

- doc/cephadm/host-management.rst
Correct the English in a note in doc/cephadm/host-management.rst.
This commit was made in response to
https://github.com/ceph/ceph/pull/50340, which corrected some of this note in Quincy. …
> doc/cephadm: correct note

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/prometheus.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/dashboard-promqls.enum.ts
backport tracker: https://tracker.ceph.com/issues/69292
---
backport of https://github.com/ceph/ceph/pull/60976
parent tracker: https://tracker.ceph.com/issues/69144
> squid: mgr/dashboard: Fix Latency chart data units in rgw overview page

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-multisite-zonegroup-deletion-form/rgw-multisite-zonegroup-deletion-form.component.ts
backport tracker: https://tracker.ceph.com/issues/69223
---
backport of https://github.com/ceph/ceph/pull/60959
parent tracker: https://tracker.ceph.com/issues/69121
> squid: mgr/dashboard: Update and correct zonegroup delete notification

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-multisite-zonegroup-deletion-form/rgw-multisite-zonegroup-deletion-form.component.ts
backport tracker: https://tracker.ceph.com/issues/69222
---
backport of https://github.com/ceph/ceph/pull/60959
parent tracker: https://tracker.ceph.com/issues/69121
> reef: mgr/dashboard: Update and correct zonegroup delete notification

- src/pybind/mgr/dashboard/plugins/feature_toggles.py
- src/pybind/mgr/mgr_util.py
backport tracker: https://tracker.ceph.com/issues/69194
---
backport of https://github.com/ceph/ceph/pull/60749
parent tracker: https://tracker.ceph.com/issues/68969
> reef: mgr/dashboard: add a custom warning message when enabling feature

- src/pybind/mgr/dashboard/.gitignore
- src/pybind/mgr/dashboard/ci/cephadm/bootstrap-cluster.sh
- src/pybind/mgr/dashboard/ci/cephadm/ceph_cluster.yml
- src/pybind/mgr/dashboard/ci/cephadm/load-podman-image.sh
- src/pybind/mgr/dashboard/ci/cephadm/quick-bootstrap.sh
a new `clusters` and `nodes` parameters, which can be used to provide how many clusters you want and how many nodes you want in each clusters.
```
./quick-bootstrap.sh -dir=/home/nia/projects/ceph -u -n=2 -c=2
```
the above will create 2 clusters with 2 nodes each so total 4 vms …
> mgr/dashboard: adapt kcli plan to improve multi-cluster deployment

- src/include/types.h
- src/journal/Entry.cc
- src/tools/cephfs/Dumper.cc
This kludge has been obsolete for a long time and GCC 4.3 cannot compile Ceph anymore these days.
> include/types.h, tools/cephfs: remove _BACKWARD_BACKWARD_WARNING_H

- src/common/options/mds.yaml.in
- src/mds/MDCache.cc
- src/mds/MDSRank.cc
- src/mds/Server.cc
- src/mds/Server.h
Take over of abandoned PR https://github.com/ceph/ceph/pull/58474. 
In case the current request has lock cache attached and then the
lock cache must have already acquired the wrlock of filelock. So
currently the path_traverse() will acquire the wrlock twice and
possibly caused deadlock by itself. …
> mds: prevent duplicate wrlock acquisition for a single request

- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/module.py
- src/pybind/mgr/dashboard/services/nvmeof_cli.py
- src/pybind/mgr/dashboard/services/nvmeof_client.py
- src/pybind/mgr/dashboard/tests/test_nvmeof_cli.py
- Added nvmeof cli commands to ceph. 
- Added support for json and yaml formats. 
- Added unit tests for the decorator.
examples: 
`ceph nvmeof gw info` -> 
```
{"cli_version": "", "version": "1.4.2", "name": "client.nvmeof.mypool.mygroup1.xxxxxx.yyyyy", "group": "mygroup1", "addr": "x.x.x.x", "port": "5500", "load_balancing_group": 1, "spdk_version": "24.09"}
```
`ceph nvmeof gw info --format=yaml` -> 
```
addr: x.x.x.x
cli_version: ''
group: mygroup1
load_balancing_group: 1
name: client.nvmeof.mypool.mygroup1.xxxxxx.yyyyy
port: '5500'
spdk_version: '24.09'
version: 1.4.2
``` …
> Dashboard: Introduce nvmeof cli commands

- src/common/Formatter.cc
- src/common/HTMLFormatter.cc
- src/test/common/CMakeLists.txt
- src/test/common/test_htmlformatter.cc
- src/test/common/test_json_formatter.cc
- src/test/common/test_tableformatter.cc
- src/test/common/test_xmlformatter.cc
backport tracker: https://tracker.ceph.com/issues/69259
---
backport of https://github.com/ceph/ceph/pull/60429
parent tracker: https://tracker.ceph.com/issues/68658
> reef: <common> fix formatter buffer out-of-bounds

- src/rgw/rgw_op.cc
backport tracker: https://tracker.ceph.com/issues/69298
---
backport of https://github.com/ceph/ceph/pull/60771
parent tracker: https://tracker.ceph.com/issues/68982
> reef: rgw/abortmp: Race condition on AbortMultipartUpload

- src/rgw/rgw_rest.cc
backport tracker: https://tracker.ceph.com/issues/69296
---
backport of https://github.com/ceph/ceph/pull/60970
parent tracker: https://tracker.ceph.com/issues/69139
> reef: rgw: append query string to redirect URL if present

- src/rgw/driver/rados/rgw_user.cc
- src/rgw/driver/rados/rgw_user.h
backport tracker: https://tracker.ceph.com/issues/63250
---
backport of https://github.com/ceph/ceph/pull/53750
parent tracker: https://tracker.ceph.com/issues/63134
> reef: rgw: fix user.rgw.user-policy attr remove by modify user

- src/rgw/rgw_http_client.cc
- src/test/rgw/rgw_multi/tests.py
backport tracker: https://tracker.ceph.com/issues/64551
---
backport of https://github.com/ceph/ceph/pull/55565
parent tracker: https://tracker.ceph.com/issues/64366
> reef: rgw/http/client-side: disable curl path normalization

- src/rgw/rgw_op.cc
backport tracker: https://tracker.ceph.com/issues/63585
---
backport of https://github.com/ceph/ceph/pull/54528
parent tracker: https://tracker.ceph.com/issues/63580
> reef: rgw/notifications: cleanup all coroutines after sending the notification

- src/rgw/driver/rados/rgw_rados.cc
backport tracker: https://tracker.ceph.com/issues/62757
---
backport of https://github.com/ceph/ceph/pull/52866
parent tracker: https://tracker.ceph.com/issues/59400
> reef: rgw: when there are a large number of multiparts, the unorder list result may miss objects

- src/rgw/CMakeLists.txt
In particular, do not link intermediate dependencies nor librgw.so.2 with a custom allocator (normally tcmalloc).
This prevents illegal behavior due to mismatched allocators when run under nfs-ganesha or other consumers.
Fixes: https://tracker.ceph.com/issues/63623
Parent tracker: https://tracker.ceph.com/issues/63394
Backports: https://github.com/ceph/ceph/pull/54297
Signed-off-by: Matt Benjamin <mbenjamin@redhat.com>
(cherry picked from commit c4b4ba554d285d9342cf16e4ce6782f18bd405ce) …
> reef: rgw: link only radosgw with ALLOC_LIBS

- src/rgw/driver/rados/rgw_sync.cc
backport tracker: https://tracker.ceph.com/issues/69004
---
backport of https://github.com/ceph/ceph/pull/52568
parent tracker: https://tracker.ceph.com/issues/61743
> reef: rgw/multisite: metadata polling event based on unmodified mdlog_marker

- src/osd/PrimaryLogPG.cc
backport tracker: https://tracker.ceph.com/issues/69500
---
backport of https://github.com/ceph/ceph/pull/60795
parent tracker: https://tracker.ceph.com/issues/69014
> squid: osd: optimize extent comparison in PrimaryLogPG

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/prometheus.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/enum/dashboard-promqls.enum.ts
backport tracker: https://tracker.ceph.com/issues/69291
---
backport of https://github.com/ceph/ceph/pull/60976
parent tracker: https://tracker.ceph.com/issues/69144
> reef: mgr/dashboard: Fix Latency chart data units in rgw overview page

- src/os/bluestore/BlueRocksEnv.h
backport tracker: https://tracker.ceph.com/issues/68735
---
backport of https://github.com/ceph/ceph/pull/58334
parent tracker: https://tracker.ceph.com/issues/66717
> reef: os/bluestore: Fix BlueRocksEnv attempts to use POSIX

- qa/suites/rados/dashboard/tasks/e2e.yaml
backport tracker: https://tracker.ceph.com/issues/67443
---
backport of https://github.com/ceph/ceph/pull/58736
parent tracker: https://tracker.ceph.com/issues/66922
> squid: qa/rados/dashboard: Add PG_DEGRADED to ignorelist

- src/mon/Monitor.cc
backport tracker: https://tracker.ceph.com/issues/69505
---
backport of https://github.com/ceph/ceph/pull/58472
parent tracker: https://tracker.ceph.com/issues/64824
> squid: mon/scrub: log error details of store access failures

- qa/tasks/cephfs/caps_helper.py
- qa/tasks/cephfs/test_admin.py
- src/client/Client.cc
backport tracker: https://tracker.ceph.com/issues/67294
---
backport of https://github.com/ceph/ceph/pull/58878
parent tracker: https://tracker.ceph.com/issues/67212
Also backported a required qa fix https://github.com/ceph/ceph/commit/7626bd5d37b6f24fe60840c225ef917356f8dfc4
> reef: client: Fix leading / issue with mds_check_access

- qa/workunits/fs/snaps/snaptest-double-null.sh
backport tracker: https://tracker.ceph.com/issues/67743
---
backport of https://github.com/ceph/ceph/pull/59095
parent tracker: https://tracker.ceph.com/issues/67408
> reef: qa: wait for file creation before changing mode

- src/mds/Server.cc
backport tracker: https://tracker.ceph.com/issues/67691
---
backport of https://github.com/ceph/ceph/pull/56602
parent tracker: https://tracker.ceph.com/issues/63906
> reef: mds: getattr just waits the xlock to be released by the previous client

- src/test/osd/TestOSDMap.cc
backport tracker: https://tracker.ceph.com/issues/67237
---
backport of https://github.com/ceph/ceph/pull/58406
parent tracker: https://tracker.ceph.com/issues/42884
> squid: test: Create ParallelPGMapper object before start threadpool

- src/mds/MDSRank.cc
- src/mds/MDSRank.h
Fixes: https://tracker.ceph.com/issues/66047
Backport.
(cherry picked from commit a4dc88140071f9cdfe5654402067434728fee469) 
Original-Issue: https://tracker.ceph.com/issues/65803
Original-PR: #57274
<details>
</details>
> reef: mds: don't stall the asok thread for flush commands

- qa/cephfs/conf/mgr.yaml
- qa/suites/fs/functional/tasks/snap-schedule.yaml
backport tracker: https://tracker.ceph.com/issues/67827
---
backport of https://github.com/ceph/ceph/pull/58547
parent tracker: https://tracker.ceph.com/issues/66009
> reef: qa: failfast mount for better performance and unblock `fs volume ls`

- src/pybind/mgr/dashboard/controllers/smb.py
- src/pybind/mgr/dashboard/openapi.yaml
Adds a decorator to raise a DashboardException with the msg error of an unsucessful smb resource update
Fixes: https://tracker.ceph.com/issues/69286 …
> mgr/dashboard: smb raise exception for unsucessful resource update

- qa/workunits/cephtool/test.sh
- src/mon/FSCommands.cc
backport tracker: https://tracker.ceph.com/issues/67375
---
backport of https://github.com/ceph/ceph/pull/58582
parent tracker: https://tracker.ceph.com/issues/66960
> reef: mon: fix `fs set down` to adjust max_mds only when cluster is not down

- src/exporter/ceph_exporter.cc
Restore the documentation of "--prio-limit" in
src/exporter/ceph_exporter.cc and remove the documentation of "--cert-file" in src/exporter/ceph_exporter.cc. These two changes are made to repair damage done to this file as a result of a miscommunication in https://github.com/ceph/ceph/pull/61331. …
> exporter: repair Squid ceph_exporter.cc

- src/erasure-code/ErasureCode.cc
- src/test/bufferlist.cc
Fixes: https://tracker.ceph.com/issues/61573
We want the buffers used for erasure coding to be 64-byte aligned. This should ensure that they fit a single 64 byte cache line for AVX512 instructions. If the buffers are misaligned then we can see a reduction in performance as the CPU has to do extra loads from memory.
The testing in the tracker does show a performance gain using 64-byte alignment. I wasn't able to see any improvement in my own testing, but this could be down to the CPU I used (Xeon Gold 6336Y). …
> erasure-code: Increase SIMD_ALIGN from 32 to 64

- src/rgw/driver/rados/rgw_rados.cc
backport tracker: https://tracker.ceph.com/issues/69217
---
backport of https://github.com/ceph/ceph/pull/60907
parent tracker: https://tracker.ceph.com/issues/58965
> reef: rgw: Delete stale entries in bucket indexes while deleting obj

- container/Containerfile
Add a label used by cephadm internally that was always set by ceph-container [1] back to the new containerfile. This should prevent issues with cephadm shell command thinking official ceph images are not official ceph images.
[1] https://github.com/ceph/ceph-container/blob/30dc8b9a55f70a40983fd2da6ac31e1b9e977143/src/__DOCKERFILE_TRACEABILITY_LABELS__#L5 …
> container: add label ceph=True back

- src/common/options/rgw.yaml.in
- src/rgw/rgw_kafka.cc
backport tracker: https://tracker.ceph.com/issues/64885
---
backport of https://github.com/ceph/ceph/pull/55952
parent tracker: https://tracker.ceph.com/issues/64710
> reef: rgw/kafka: set message timeout to 5 seconds

- src/rgw/driver/rados/rgw_notify.cc
- src/rgw/rgw_admin.cc
- src/rgw/rgw_pubsub.cc
- src/rgw/rgw_pubsub.h
- src/test/cli/radosgw-admin/help.t
backport tracker: https://tracker.ceph.com/issues/66496
---
backport of https://github.com/ceph/ceph/pull/57898
parent tracker: https://tracker.ceph.com/issues/66404
> reef: rgw/admin/notification: add command to dump notifications

- src/rgw/rgw_rest.cc
backport tracker: https://tracker.ceph.com/issues/65544
---
backport of https://github.com/ceph/ceph/pull/56866
parent tracker: https://tracker.ceph.com/issues/65469
> reef: rgw: increase log level on abort_early

- src/rgw/driver/rados/rgw_sal_rados.cc
- src/test/rgw/rgw_multi/tests.py
- src/test/rgw/rgw_multi/zone_cloud.py
- src/test/rgw/rgw_multi/zone_es.py
- src/test/rgw/rgw_multi/zone_rados.py
backport tracker: https://tracker.ceph.com/issues/63969
---
backport of https://github.com/ceph/ceph/pull/54829
parent tracker: https://tracker.ceph.com/issues/63755
> reef: rgw/iam: fix role deletion replication

- src/rgw/rgw_appmain.cc
- src/rgw/rgw_lua.cc
backport tracker: https://tracker.ceph.com/issues/61191
---
backport of https://github.com/ceph/ceph/pull/51415
parent tracker: https://tracker.ceph.com/issues/59698
> reef: rgw/lua: add more info on package install errors

- src/msg/Messenger.h
backport tracker: https://tracker.ceph.com/issues/69652
---
backport of https://github.com/ceph/ceph/pull/58631
parent tracker: https://tracker.ceph.com/issues/66336
> reef: msg: insert PriorityDispatchers in sorted position

- src/cls/rbd/cls_rbd_client.cc
This is a follow-up for commit af176311c476 (objclass: change objclass exec read calls to write ones where needed) which missed mirror_uuid_set and raced with the addition of mirror_remote_namespace_set.
Fixes: https://tracker.ceph.com/issues/65889 …
> cls/rbd: don't use read API for write-like methods

- container/Containerfile
backport tracker: https://tracker.ceph.com/issues/69721
---
backport of https://github.com/ceph/ceph/pull/61218
parent tracker: https://tracker.ceph.com/issues/69698
> squid: container/Containerfile: replace CEPH_VERSION label for backward compat

- container/Containerfile
Same as https://github.com/ceph/ceph-container/pull/2253
- …
> container/Containerfile: use ganesha-4 from proper path

- container/build.sh
backport tracker: https://tracker.ceph.com/issues/69717
---
backport of https://github.com/ceph/ceph/pull/61510
parent tracker: https://tracker.ceph.com/issues/69700
> squid: container/build.sh: don't require repo creds on NO_PUSH

- container/build.sh
backport tracker: https://tracker.ceph.com/issues/69719
---
backport of https://github.com/ceph/ceph/pull/61489
parent tracker: https://tracker.ceph.com/issues/69699
> squid: container/build.sh: fix up org vs. repo naming

- src/osd/ECBackend.cc
- src/osd/ECCommon.cc
- src/osd/ECCommon.h
- src/osd/ECUtil.cc
- src/osd/ECUtil.h
- src/test/crimson/test_crimson_scrub.cc
- src/test/osd/TestECBackend.cc
- src/test/osd/test_ec_transaction.cc
- src/tools/erasure-code/ceph-erasure-code-tool.cc
osd: further EC partial stripe read fixes
* More fixes for multi-region reads
* Enable partial stripe reads that span stripes
ECUtil::stripe_info_t::chunk_aligned_offset_len_to_chunk is fixed to return the correct span of a shard that needs to be read to obtain all the data for a specified range of the object. Previously this did not read enough data if the range was multiple stripes and was not stripe aligned.
finish_single_request is fixed to trim the data that is read. For partial reads of more than one stripe the shards that are read (wanted_to_read) is a union of the requirements for each range. This means there can be excess data that needs to be trimmed.
Example 1: chunksize = 4K, 2+2 profile. read offset 4K for length 8K
* chunk_aligned_offset_len_to_chunk calculates that we need …
> Further EC partial stripe read fixes

- src/common/interval_map.h
- src/include/interval_set.h
- src/test/common/test_interval_map.cc
- src/test/common/test_interval_set.cc
These commits enhance the insert/erase function of interval sets.  The main intent is to enhance flexibility to callers, but in many cases, performance is likely also improved.  Where performance is not improved, there should be no performance reduction. 
There is also a new "align" method which allows for all intervals within a set to be aligned to an arbitrary alignment. This will be consumed by the new optimised erasure code.  …
> include: interval_set: Relax requirements and enhance performance of interval sets

- src/rgw/rgw_lc.cc
Fixes: https://tracker.ceph.com/issues/66111 …
> rgwlc: send pool transition notifications too

- doc/rbd/rbd-live-migration.rst
Even though it's explicitly said that "http" stream can be used to import via both HTTP and HTTPS, it can still be confusing that "type": "http" is expected to go with "url": "https://...".  Switch example URLs from HTTP to HTTPS to make it more obvious. …
> doc/rbd: use https links in live import examples

- doc/rbd/rbd-live-migration.rst
Backport https://github.com/ceph/ceph/pull/61598 to squid.
> squid: doc/rbd: use https links in live import examples

- doc/rbd/rbd-live-migration.rst
Backport https://github.com/ceph/ceph/pull/61598 to reef.
> reef: doc/rbd: use https links in live import examples

- src/tools/rbd/action/MirrorPool.cc
backport tracker: https://tracker.ceph.com/issues/69333
---
backport of https://github.com/ceph/ceph/pull/61150
parent tracker: https://tracker.ceph.com/issues/69319
> reef: rbd: open images in read-only mode for "rbd mirror pool status --verbose"

- src/crimson/osd/object_context_loader.h
- src/crimson/osd/recovery_backend.cc
- src/crimson/osd/recovery_backend.h
- src/crimson/osd/replicated_recovery_backend.cc
- src/crimson/osd/replicated_recovery_backend.h
See https://tracker.ceph.com/issues/69412
Follow up PR will address replica side.
Test run looks good, failures listed below:
https://pulpito.ceph.com/sjust-2025-01-28_06:26:29-crimson-rados-wip-sjust-crimson-testing-2025-01-27-distro-default-smithi/
- 8098636 - https://tracker.ceph.com/issues/69438
- 8098656 - https://tracker.ceph.com/issues/69701 
<details> …
> crimson: take obc lock during push commit on primary

- src/osd/OSD.cc
- src/osd/OSD.h
backport tracker: https://tracker.ceph.com/issues/66146
--------
backport of #56804
parent tracker: https://tracker.ceph.com/issues/64373
> squid: osd: fix for segmentation fault on OSD fast shutdown

- src/common/ceph_context.cc
- src/common/perf_counters.cc
- src/common/perf_counters.h
- src/common/perf_counters_collection.cc
- src/common/perf_counters_collection.h
- src/crimson/admin/osd_admin.cc
- src/crimson/common/perf_counters_collection.cc
- src/crimson/common/perf_counters_collection.h
- src/kv/RocksDBStore.cc
- src/libcephsqlite.cc
- src/librbd/cache/pwl/AbstractWriteLog.cc
- src/os/bluestore/BlueFS.cc
- src/os/bluestore/BlueStore.h
- src/os/kstore/KStore.h
- src/test/fio/fio_ceph_messenger.cc
- src/test/fio/fio_ceph_objectstore.cc
- src/tools/ceph_objectstore_tool.cc
Multiple style and performance tweaks. The important one:
Modifying reset() to directly locate the named logger.
As most of the code here predates C++14, "transparent
comparators" were not used. Instead, we looped through
the list of loggers.
With the updated C++ we are using today, the comparator
can be fixed to allow a find() based on the name.
Also: avoiding the use of 3 consecutive 'bool's as arguments to
some dump functions.
> common/perf_counters: enabling 'find()' by logger name

- src/common/ceph_context.cc
- src/common/config_cacher.h
- src/common/config_obs.h
- src/common/config_obs_mgr.h
Modify the md_config_cacher_t to implement the new get_tracked_conf_key() API.
Apart from resulting in a clearer code, this also solves the potential for a dangling
pointer issue that was present in the existing code.
This is a continuation of https://github.com/ceph/ceph/pull/61289. That PR was
enough to solve existing config-cacher bugs, and was created with backporting
in mind - but it was just one step on the road of improving the cacher. The current
PR is the next step.
> common: modify md_config_obs_impl API

- src/osd/scrubber/pg_scrubber.cc
- src/osd/scrubber/pg_scrubber.h
- src/osd/scrubber/scrub_backend.cc
`repair_oinfo_oid()`, called every scrub, has a very specific functionality:
fix the object ID specified in the Object Info attribute, if different from the ID of the owning object.
This fix was added in 2017, as a response to a unique failure scenario that was observed in Sepia -
probably following a filesystem bug.
See https://tracker.ceph.com/issues/18409 & https://tracker.ceph.com/issues/20471.
The limited functionality of `repair_oinfo_oid()` -
only repairing this one specific issue, and only if the OI_ATTR exists and is decodable -
does not justify the overhead of running it every scrub.
> osd/scrub: discard repair_oinfo_oid()

- src/mon/NVMeofGwMap.cc
- src/mon/NVMeofGwMap.h
- src/mon/NVMeofGwMon.cc
1. fix duplicated optimized host's pathes - trigger process_gw_down upon fast-gw reboot, removed old fast-reboot handlers
2. fix GW startup - trigger process_gw_down when expired WAIT_BLOCKLIST timer …
> nvmeofgw* : fix duplicated optimized host's pathes

- qa/standalone/osd/pg-split-merge.sh
backport tracker: https://tracker.ceph.com/issues/69622
---
backport of https://github.com/ceph/ceph/pull/57201
parent tracker: https://tracker.ceph.com/issues/65737
> reef: test: ceph daemon command with asok path

- src/test/neorados/common_tests.h
This is a bug in Boost that's fixed in 1.87. Once we upgrade to that, this can be reverted.
Fixes: https://tracker.ceph.com/issues/64191 …
> test/neorados: Silence mismatched new/delete warning

- qa/workunits/mon/test_mon_osdmap_prune.sh
In the test, we assume the trimming of osdmaps is done if osdmap_first_committed is equal to the epoch of the map upto which we had to trim. osdmap_first_committed however returns the value of cached_first_committed which is updated before the Paxos proposal for trim goes through. Normally, this is not a problem as when a refresh() happens, cached_first_committed will be corrected to the value before the trim was proposed if the Paxos proposal failed. But for this test, we encounter a failure in this case as the osdmap_first_committed will not be equal to the osdmap_manifest.first_pinned as the trim never went through. Changing the test to verify that osdmap_manifest.first_pinned has changed to the correct value is a better way to signify that the trim is complete for the purpose of this …
> mon/test_mon_osdmap_prune: Use first_pinned instead of first_committed

- doc/rados/operations/stretch-mode.rst
backport tracker: https://tracker.ceph.com/issues/69167
---
backport of https://github.com/ceph/ceph/pull/60831
parent tracker: https://tracker.ceph.com/issues/68338
> squid: doc/rados/operations/stretch-mode.rst: Added Limitations to stretch pool configurations

- doc/rados/operations/stretch-mode.rst
This backports two commits to the squid branch that were not properly backported before. This is done to ensure that the Squid documentation can be updated with the standard backport procedure. …
> squid: Backport two commits to the Squid branch

- container/Containerfile
Backport of https://github.com/ceph/ceph/pull/61511
<details>
</details>
> reef: container: add label ceph=True back

- win32_deps_build.sh
The zlib Windows build started to fail, probably because of this: https://github.com/madler/zlib/issues/1038
Cloning into 'zlib'...
make: *** No rule to make target 'zconf.h', needed by 'adler32.o'.
We'll pin the zlib version for now to unblock the Windows build.
Fixes: https://tracker.ceph.com/issues/69768 …
> win32_deps_build.sh: pin zlib tag

- src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
- src/pybind/mgr/cephadm/tests/test_services.py
- src/python-common/ceph/deployment/service_spec.py
mgr/cephadm/nvmeof: Add max_hosts field to NVMeOF configuration and update default values
Fixes https://tracker.ceph.com/issues/69759 …
> mgr/cephadm/nvmeof: Add max_hosts field to NVMeOF configuration

- src/pybind/mgr/dashboard/plugins/feature_toggles.py
- src/pybind/mgr/mgr_util.py
backport tracker: https://tracker.ceph.com/issues/69195
---
backport of https://github.com/ceph/ceph/pull/60749
parent tracker: https://tracker.ceph.com/issues/68969
> squid: mgr/dashboard: add a custom warning message when enabling feature

- qa/cephfs/overrides/ignorelist_health.yaml
backport tracker: https://tracker.ceph.com/issues/67837
---
backport of https://github.com/ceph/ceph/pull/59309
parent tracker: https://tracker.ceph.com/issues/67601
> reef: qa: ignore warnings variations

- src/tools/cephfs/top/cephfs-top
backport tracker: https://tracker.ceph.com/issues/68167
---
backport of https://github.com/ceph/ceph/pull/59566
parent tracker: https://tracker.ceph.com/issues/67859
> reef: cephfs-top: fix exceptions on small/large sized windows

- qa/tasks/cephfs/test_admin.py
- src/pybind/mgr/status/module.py
backport tracker: https://tracker.ceph.com/issues/68413
---
backport of https://github.com/ceph/ceph/pull/59699
parent tracker: https://tracker.ceph.com/issues/67978
> reef: mgr/status: Fix 'fs status' json output

- src/mds/MDSAuthCaps.cc
- src/test/libcephfs/access.cc
backport tracker: https://tracker.ceph.com/issues/68455
---
backport of https://github.com/ceph/ceph/pull/54381
parent tracker: https://tracker.ceph.com/issues/68453
> reef: mds: misc fixes for MDSAuthCaps code

- qa/suites/fs/upgrade/mds_upgrade_sequence/overrides/ignorelist_upgrade.yaml
backport tracker: https://tracker.ceph.com/issues/68616
---
backport of https://github.com/ceph/ceph/pull/58486
parent tracker: https://tracker.ceph.com/issues/66877
> reef: qa/cephfs: ignore when specific OSD is reported down during upgrade

- qa/tasks/cephfs/test_backtrace.py
- src/mds/CInode.cc
- src/mds/CInode.h
- src/mds/LogSegment.h
- src/mds/MDLog.cc
- src/mds/journal.cc
backport tracker: https://tracker.ceph.com/issues/68110
---
backport of https://github.com/ceph/ceph/pull/55421
parent tracker: https://tracker.ceph.com/issues/63259
> reef: mds: batch backtrace updates by pool-id when expiring a log segment

- src/rgw/driver/rados/rgw_log_backing.cc
Fitting a retry loop around a call that took the lock changed the logic to potentially have the lock be used after moving.
Thanks to Suyash Dongre suyashd999@gmail.com for finding it.
This patch also fixes a lock being held across an I/O operation.
Fixes: https://tracker.ceph.com/issues/66340
(cherry picked from commit 80cf2ca3b44246ad8f2e333182b3c8b1835a71f7)
Fixes: https://tracker.ceph.com/issues/68054 …
> reef: rgw/multisite: Fix use-after-move in retry logic in logbacking

- src/common/config.cc
- src/common/config.h
This field is `const` and we need only one global instance, and not one copy per `md_config_t` instance.
> common/config: make `legacy_values` static

- src/librados/CMakeLists.txt
- src/librados/librados_c.cc
When building internal libraries statically with `-DENABLE_SHARED=no`, linking `librados.a` always fails because the
`LIBRADOS_C_API_DEFAULT_F` macro inserts an underscore prefix to all exported symbols.  It does this so a versioned symbol with the real name can be created.  Symbol versions however only work with shared libraries, and the linker fails to find the prefix-less symbols:
```
FAILED: bin/ceph_radosacl
: && /usr/bin/c++ -O0 -fPIC -fuse-ld=mold -Og -g -rdynamic src/tools/CMakeFiles/ceph_radosacl.dir/radosacl.cc.o -o bin/ceph_radosacl  -Wl,-rpath,:::::::::::::::::::::::::::::::  lib/liblibrados.a  lib/libglobal.a  lib/liblibrados_impl.a  lib/libosdc.a  lib/libcls_lock_client.a  lib/libceph-common.a  /usr/lib/aarch64-linux-gnu/libblkid.so  /usr/lib/aarch64-linux-gnu/libcrypto.so …
```
> librados: disable symbol versions when building statically

- qa/standalone/scrub/osd-scrub-test.sh
- src/common/config_cacher.h
In its get_tracked_conf_keys() member function, the cacher (in the existing code)
initializes a static function-block variable ('keys'), and uses it for
registering the observer.
But the cacher is instantiated on the type of
the configuration value. Thus, multiple cacher
objects for which the configuration values are
of the same type - share the static 'keys'. Only
one of the observers is registered.
Backport of https://github.com/ceph/ceph/pull/61289
Original tracker: https://tracker.ceph.com/issues/69236
Backport tracker: https://tracker.ceph.com/issues/69530
> squid: common: fix md_config_cacher_t

- examples/rgw/boto3/service-2.sdk-extras.json
0f55c1759d4f959f4de448289b5f31fc95ae88d5 added an override for the "HeadBucketOutput" shape, but that didn't exist until botocore 1.33.2. s3-tests is pinned to botocore <1.28.0
Fixes: https://tracker.ceph.com/issues/69582
<details>
</details>
> examples/rgw: add type to HeadBucketOutput for old boto

- src/rgw/radosgw-admin/radosgw-admin.cc
- src/rgw/rgw_sal.cc
- src/rgw/rgw_sal.h
The restore attrs directly stored at the backend which make it difficult to understand via `radosgw-admin object stat` cli. Make it more human readable form. …
> rgw/rgw_admin.cc : Make restore attrs readable in admin cli

- src/rgw/rgw_acl_s3.cc
fixes "Invalid group uri" errors from `s3cmd setacl --acl-public s3://bucketname` introduced by account changes for squid
Fixes: https://tracker.ceph.com/issues/69527
<details>
</details>
> rgw/s3: remove local variable 'uri' that shadows member variable

- src/pybind/mgr/cephadm/services/monitoring.py
cephadm: Add pre_remove and ensure deployment values are reset and API settings are updated when  removing Prometheus or Alertmanager daemons
Fixes: https://tracker.ceph.com/issues/69088
Logs:
**Alertmanager Scenario 1: Removing the daemon which is not active.**
```
[ceph: root@ceph-node-0 ~]# ceph orch apply alertmanager --placement '*'
Scheduled alertmanager update...
[ceph: root@ceph-node-0 ~]# ceph orch ls
NAME                       PORTS        RUNNING  REFRESHED  AGE  PLACEMENT  
alertmanager               ?:9093,9094      3/3  31s ago    91s  *          
crash                                       3/3  31s ago    11m  *          
mgr                                         2/2  31s ago    11m  count:2    
mon                                         3/5  31s ago    11m  count:5 …
```
> cephadm: Add pre_remove and ensure deployment values are reset and API settings are updated when  removing Prometheus or Alertmanager daemons

- src/pybind/mgr/nfs/cluster.py
Show ingress mode in output of 'ceph nfs cluster info' command
Fixes: https://tracker.ceph.com/issues/69153
Testing logs:
```
[ceph: root@ceph-node-0 /]# ceph nfs cluster info
{
"mynfs": {
"backend": [
{
"hostname": "ceph-node-0",
"ip": "192.168.100.100",
"port": 12345
},
{
"hostname": "ceph-node-1",
"ip": "192.168.100.101",
"port": 12345
},
{
"hostname": "ceph-node-2",
"ip": "192.168.100.102",
"port": 12345
}
],
"ingress_mode": "haproxy-standard",
"monitor_port": 9000,
"port": 2049,
"virtual_ip": "192.168.100.123"
},
"mynfs1": {
"backend": [
{
"hostname": "ceph-node-0",
"ip": "192.168.100.100",
"port": 12345
},
{
"hostname": "ceph-node-1",
"ip": "192.168.100.101",
"port": 12345
},
{
"hostname": "ceph-node-2",
"ip": …
```
> mgr/nfs: Show ingress mode in output of 'ceph nfs cluster info' command

- src/pybind/mgr/cephadm/services/nfs.py
- src/pybind/mgr/cephadm/templates/services/nfs/ganesha.conf.j2
- src/pybind/mgr/cephadm/tests/test_services.py
From the ganesha team
"""
In the NFSv4 param block, we need a parameter Server_Scope set to some value common among all servers in a cluster.
The default with it blank is to use the hostname which may be different for each server in the cluster. 
"""
This is related to ongoing work on high availability nfs. From the cephadm side we just need to make sure all nfs daemons in the cluster end up with the same value for the Server_Scope field. Since the cluster fsid already exists as a cluster wide identifier, I'm re-using that for this purpose. …
> mgr/cephadm: add Server_Scope = <fsid> to NFSv4 section of ganesha conf

- src/pybind/mgr/cephadm/services/nfs.py
- src/pybind/mgr/cephadm/templates/services/nfs/ganesha.conf.j2
- src/pybind/mgr/cephadm/tests/test_services.py
- src/python-common/ceph/deployment/service_spec.py
Currently the NFS spec does not allow providing a custom port for the monitoring/metrics server deployed by ganesha, this PR allows for that in the service spec.
`9587` default is same as ganesha's default https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/doc/man/ganesha-core-config.rst
```
Monitoring_Port (uint16, range 0 to UINT16_MAX, default 9587)
Port number used to export monitoring metrics.
```
Signed-off-by: Omid Yoosefi <omidyoosefi@ibm.com>
> pybind/mgr/cephadm: allow setting custom monitoring_port for nfs

- src/cephadm/cephadm.py
- src/cephadm/cephadmlib/container_engines.py
- src/cephadm/cephadmlib/data_utils.py
- src/cephadm/tests/fixtures.py
- src/cephadm/tests/test_agent.py
- src/cephadm/tests/test_cephadm.py
There were three functions I recently noticed were good candidates for moving out of cephadm.py as they didn't have complex dependencies:
* get_legacy_daemon_fsid
* _parse_mem_usage  (and the command that gets called to generate the output)
* _parse_cpu_perc  (and the command that gets called to generate the output)
The first one was easy. The others needed a bunch of test updates to make them work properly (applied when _parse_mem_usage is replaced).
This work is in preparation for a bigger refactor of the list_daemons function. …
> cephadm: move three functions out of cephadm.py

- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/services/osd.py
That function handles setting up the extra container/entrypoint args for the daemon during initial deployment. Having the CephadmDaemonDeploySpec made directly in the OSD deployment workflow means initial deployments of OSDs won't have the extra container/entrypoint args from the spec
Fixes: https://tracker.ceph.com/issues/69734 …
> mgr/cephadm: create OSD daemon deploy specs through make_daemon_spec

- src/common/ceph_time.h
- src/crimson/os/alienstore/alien_store.cc
- src/kv/KeyValueDB.h
- src/kv/RocksDBStore.cc
- src/kv/RocksDBStore.h
- src/os/DBObjectMap.cc
- src/os/DBObjectMap.h
- src/os/ObjectStore.h
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/os/kstore/KStore.cc
- src/os/kstore/KStore.h
- src/os/memstore/MemStore.cc
- src/os/memstore/MemStore.h
- src/osd/PrimaryLogPG.cc
- src/test/ObjectMap/KeyValueDBMemory.cc
- src/test/objectstore/ObjectStoreImitator.h
backport tracker: https://tracker.ceph.com/issues/69523
---
backport of https://github.com/ceph/ceph/pull/60278
parent tracker: https://tracker.ceph.com/issues/68457
> squid: os, osd: bring the lightweight OMAP iteration

- src/test/objectstore/store_test.cc
Cover all Bluestore specific code.  Fixes build failures with `WITH_BLUESTORE=no`.
> test/objectstore: extend `#ifdef WITH_BLUESTORE`

- qa/standalone/osd/osd-bluefs-volume-ops.sh
- src/os/bluestore/BlueStore.cc
It turned out that original fix #60363 misplaced the code.
Expanded and fixed testing.
Improved dout on bdev label decoding failure. …
> os/bluestore: CBT bluefs-bdev-expand addendum

- qa/standalone/osd-backfill/osd-backfill-space.sh
backport tracker: https://tracker.ceph.com/issues/69085
---
backport of https://github.com/ceph/ceph/pull/60636
parent tracker: https://tracker.ceph.com/issues/68585
> squid: TEST_backfill_grow fails after finding "num_bytes mismatch" in osd log

- qa/suites/rados/verify/validater/valgrind.yaml
backport tracker: https://tracker.ceph.com/issues/67915
---
backport of https://github.com/ceph/ceph/pull/54492
parent tracker: https://tracker.ceph.com/issues/62992
> squid: qa/suites/rados/verify/validater/valgrind: increase op thread timeout

- Dockerfile.build
- make-debs.sh
- src/script/build-with-container.py
- src/script/buildcontainer-setup.sh
- src/script/lib-build.sh
After a series of discussions, particularly with Zack C and Dan Mick, I've created a new patch series to replace those in #56711.
This version simplifies the (Container|Docker)file and and replaces the harder to maintain shell script wrapper with a more logical and well constructed python script. Right now there are also a couple of patches present in the branch that I needed to make it compile the unit tests. I plan on moving these out eventually as separate PRs.
PRs and issues related to building in containers:
* <s>https://github.com/ceph/ceph/pull/61030</s>
* <s>https://github.com/ceph/ceph/pull/61031</s>
* https://tracker.ceph.com/issues/68552 - pr https://github.com/ceph/ceph/pull/61327
* https://tracker.ceph.com/issues/69240 - pr https://github.com/ceph/ceph/pull/61326
* …
> containerized build tools [V2]

- src/common/TracepointProvider.cc
- src/common/TracepointProvider.h
- src/common/WorkQueue.cc
- src/common/WorkQueue.h
- src/common/ceph_context.cc
- src/common/pick_address.cc
- src/osd/OSD.cc
- src/osd/OSD.h
- src/osd/scheduler/mClockScheduler.cc
- src/osd/scheduler/mClockScheduler.h
- src/osdc/Objecter.cc
- src/osdc/Objecter.h
... with get_tracked_keys().
Following https://github.com/ceph/ceph/pull/61394, all
uses of the deprecated interface will be updated, and that old interface will be
removed.
> common,osd: replace obsolete get_tracked_conf_keys()

- qa/standalone/osd/pg-split-merge.sh
backport tracker: https://tracker.ceph.com/issues/69623
---
backport of https://github.com/ceph/ceph/pull/57201
parent tracker: https://tracker.ceph.com/issues/65737
> squid: test: ceph daemon command with asok path

- doc/cephfs/mds-journaling.rst
- src/common/options/mds.yaml.in
- src/mds/Beacon.cc
- src/mds/MDLog.cc
- src/mds/MDLog.h
backport tracker: https://tracker.ceph.com/issues/68919
---
backport of https://github.com/ceph/ceph/pull/60381
parent tracker: https://tracker.ceph.com/issues/66948
> squid: mds: trim mdlog when segments exceed threshold and trim was idle

- src/mds/Beacon.cc
backport tracker: https://tracker.ceph.com/issues/68915
---
backport of https://github.com/ceph/ceph/pull/60325
parent tracker: https://tracker.ceph.com/issues/68759
> squid: mds/Beacon: wake up the thread in shutdown()

- src/msg/DispatchQueue.cc
When adding one message, only one thread needs to be woken up.  Waking up all is a more expensive operation and leads to unnecessary lock contention and context switches.
> msg/DispatchQueue: wake up only one dispatch thread

- qa/workunits/rgw/test_rgw_orphan_list.sh
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
- src/rgw/driver/rados/rgw_sal_rados.cc
- src/tools/rados/rados.cc
backport tracker: https://tracker.ceph.com/issues/67268
---
backport of https://github.com/ceph/ceph/pull/58213
parent tracker: https://tracker.ceph.com/issues/66286
> reef: rgw/rgw_rados: fix server side-copy orphans tail-objects

- src/common/fs_types.cc
- src/mds/Anchor.cc
- src/mds/CInode.cc
- src/mds/journal.cc
The `denc` library allows appending multiple values in a single `buffer::list` call by wrapping them in a `std::tuple`.  This reduces overhead because the buffer bounds checks have to be performed only once.
This PR optimizes a few hot code paths that were visible in the profiler.
> common, mds: combine several `encode()` calls

- src/common/io_exerciser/RadosIo.cc
- src/common/io_exerciser/RadosIo.h
- src/librados/librados_asio.h
- src/rgw/driver/rados/rgw_tools.cc
- src/rgw/rgw_aio.cc
- src/test/librados/asio.cc
when called with [boost::asio::use_awaitable](https://www.boost.org/doc/libs/1_85_0/doc/html/boost_asio/reference/use_awaitable.html) for c++20 coroutines, these functions fail to compile because async_initiate() tries to pass the IoCtx argument by rvalue reference, but our lambda expects lvalue reference:
```
src/librados/librados_asio.h:196:7: note:   template argument deduction/substitution failed:
boost/asio/impl/use_awaitable.hpp:276:26: note:   cannot convert ‘std::move<librados::v14_2_0::IoCtx&>((* & args#1))’ (type ‘std::remove_reference<librados::v14_2_0::IoCtx&>::type’ {aka ‘librados::v14_2_0::IoCtx’}) to type ‘librados::v14_2_0::IoCtx&’
276 |     std::move(initiation)(std::move(handler), std::move(args)...);
|     ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
> librados/asio: support 'deferred' and 'use_awaitable' completions

- qa/suites/rados/valgrind-leaks/1-start.yaml
- qa/tasks/ceph.py
- src/msg/async/ProtocolV1.cc
- src/msg/async/ProtocolV2.cc
teuthology PR that related: https://github.com/ceph/teuthology/pull/2014
This PR addresses two issues:
1. The 'stop-daemon-timeout' parameter in the YAML file can now be used to configure the stop function timeout. This resolves timeout failures observed when running monitors under Valgrind.
2. Fixed a race condition during connection shutdown by ensuring messages are processed within the appropriate locking scope. This prevents hangs caused by improper lock handling during shutdown.
Fixes: https://tracker.ceph.com/issues/63501 …
> memory lock issues causing hangs during connection shutdown

- src/msg/async/ProtocolV1.cc
- src/msg/async/ProtocolV2.cc
PR #60176 was mistakenly merged though there had been regressions found in teuthology. …
> Revert PR 60176

- src/pybind/mgr/cephadm/services/nfs.py
Currently even if ingress and virtual_ip are used, the port_in_use check in cephadm fails when the same port is used. This PR fixes the issue by ensuring that the daemon spec includes the virtual ip address for the endpoint to be checked is included so it doesn't default to checking `0.0.0.0:port` only.
Fixes: https://tracker.ceph.com/issues/69744
Signed-off-by: Omid Yoosefi <omidyoosefi@ibm.com>
```
nfs.nfs0.0.0.ceph-1.pathwr                                     ceph-1  *:2049   running (26s)     1s ago  25s    50.7M        -  5.7               b8cbbe39e657  2d821b2ab87f
nfs.nfs0.1.0.ceph-2.rwqvnb                                     ceph-2  *:2049   running (24s)     1s ago  24s    52.7M        -  5.7               b8cbbe39e657  af0e33576754
nfs.nfs0.2.0.ceph-3.ygcgnf …
```
> pybind/mgr/cephadm: fix issue with multiple nfs clusters on the same port

- doc/architecture.rst
- doc/rados/operations/pools.rst
doc: Clarify that there are no tertiary OSDs
The use of "tertiary" when discussing OSD replication implies that a secondary OSD chains subops to a tertiary OSD, or that the tertiary OSD subops are send from the primary only after the secondary commits.  Moreover that nomenclature is rooted in the concept of 3R and fails to accommodate EC.  Would we have quaternary OSDs?  I won't even speculate the adjectives for an 8+4 EC profile.
A prior PR adjusts RGW multisite replication documentation in the same fashion.
This PR also implements suggestions from Zac with respect to rados/operations/pools.rst as a followup to https://github.com/ceph/ceph/pull/61660 …
> doc: Clarify that there are no tertiary OSDs

- src/librbd/Operations.cc
backport tracker: https://tracker.ceph.com/issues/69782
---
backport of https://github.com/ceph/ceph/pull/61567
parent tracker: https://tracker.ceph.com/issues/58185
> reef: librbd: stop filtering async request error codes

- qa/tasks/ceph_manager.py
- qa/tasks/daemonwatchdog.py
- qa/tasks/mon_thrash.py
- qa/tasks/scrub.py
- qa/tasks/thrasher.py
- qa/tasks/thrashosds.py
backport tracker: https://tracker.ceph.com/issues/67502
---
backport of https://github.com/ceph/ceph/pull/58282
parent tracker: https://tracker.ceph.com/issues/66698
> reef: qa/tasks: watchdog should terminate thrasher

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/rgw_client.py
When a default realm is already present in a secondary cluster, the multi-site automation wizard breaks and shows the progress as 0% again. This happens because the last step of the wizard is to confirm the presence of replication user created as a part of the wizard to be present in the secondary cluster and then do the further processing. We fetch the user list from the secondary cluster using get_user_list method which takes the zoneName as input param. In case there is a default realm in the secondary cluster, we need this method to take the realm name as input param as well.
Fixes: https://tracker.ceph.com/issues/69670
https://github.com/user-attachments/assets/7d2d5ee5-ca98-4227-a621-6263f9da1cc7 …
> mgr/dashboard: Multi-site replication wizard breaks when a default realm is already present in the secondary cluster.

- qa/suites/rados/singleton/all/mon-connection-score.yaml
- qa/tasks/ceph_test_case.py
- qa/tasks/mon_connection_score.py
- src/mon/ConnectionTracker.cc
backport tracker: https://tracker.ceph.com/issues/68281
---
backport of https://github.com/ceph/ceph/pull/57146
parent tracker: https://tracker.ceph.com/issues/65695
<details>
- `jenkins …
> reef: src/mon/ConnectionTracker.cc: Fix dump function

- src/mon/Monitor.cc
backport tracker: https://tracker.ceph.com/issues/69504
---
backport of https://github.com/ceph/ceph/pull/58472
parent tracker: https://tracker.ceph.com/issues/64824
> reef: mon/scrub: log error details of store access failures

- src/msg/DispatchQueue.cc
- src/msg/DispatchQueue.h
This replaces the two containers `marrival` and `marrival_map` which needs lookups with one single `std::multiset` and eliminates all lookups completely; only `add_arrival()` ever needs to walk the tree.
To do that, an iterator field is added to `class QueueItem` which is later used to erase the `std::multiset` item.
This is not only simpler and faster, but also smaller: the resulting binary is 2.5 kB smaller.
> msg/Dispatcher: simplify and optimize the `marrival` tree

- qa/suites/rados/singleton/all/test-crash.yaml
Issue: rados/test_crash.sh is failing due to PG_DEGRADED state.
Cause: This is expected as we are intentionally killing OSDs and testing for crashes. Adding the PG_DEGRADED warning to the ignorelist will prevent the test from failing when this warning is raised.
Fixes: https://tracker.ceph.com/issues/69010
<details>
- …
> rados/test_crash.sh: add PG_DEGRADED to ignorelist

- src/os/Transaction.h
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
`os::Transaction::decode_bp()` has only one user: `_setattrs()` of `BlueStore`. It uses that for optimization purposes: keeping up contigous space instead of potentially fragmented `bufferlist` that would require rectifying memcpy later.
The problem is `_setattrs()` also needs to avoid keeping large raw buffers with only small subset being referenced. It achieves this by copying the data if `bufferptr:::is_partial()` returns `true`. However, this means the memcpy happens virtually always as it's hard to even imagine the `val`, decoded from the wire, can fulfill the requirement 0 waste.
Therefore the optimization doesn't make sense; it only imposes costs in terms of complexity breaking the symmetry between encode and decode in `os::Transation` (there is no `encode_bp()`).
This commit kills …
> os: simplify os::Transaction -- get rid of the Transaction::decode_bp()

- src/client/Client.cc
- src/test/libcephfs/test.cc
backport tracker: https://tracker.ceph.com/issues/68573
---
backport of https://github.com/ceph/ceph/pull/59503
parent tracker: https://tracker.ceph.com/issues/67833
> squid: client: Fix opening and reading of symlinks

- src/tools/cephfs/shell/cephfs-shell
backport tracker: https://tracker.ceph.com/issues/68595
---
backport of https://github.com/ceph/ceph/pull/55808
parent tracker: https://tracker.ceph.com/issues/63700
> squid: cephfs-shell: fixing cephfs-shell test failures

- qa/tasks/cephfs/test_quota.py
- src/common/strtol.cc
- src/test/strtol.cc
backport tracker: https://tracker.ceph.com/issues/68708
---
backport of https://github.com/ceph/ceph/pull/58898
parent tracker: https://tracker.ceph.com/issues/67169
> squid: src/common : proper handling of units in `strict_iec_cast`

- qa/tasks/fwd_scrub.py
backport tracker: https://tracker.ceph.com/issues/68699
---
backport of https://github.com/ceph/ceph/pull/59002
parent tracker: https://tracker.ceph.com/issues/65820
> squid: qa/tasks/fwd_scrub: remove unnecessary traceback

- qa/workunits/fs/snaps/snaptest-git-ceph.sh
backport tracker: https://tracker.ceph.com/issues/68763
---
backport of https://github.com/ceph/ceph/pull/59072
parent tracker: https://tracker.ceph.com/issues/66991
> squid: qa: increase the http.maxRequestBuffer to 100MB and enable the git debug logs

- qa/tasks/cephfs/test_exports.py
- src/mds/CDir.h
- src/mds/MDSCacheObject.h
- src/mds/MDSDaemon.cc
- src/mds/MDSRank.cc
- src/mds/Migrator.cc
- src/mds/Migrator.h
backport tracker: https://tracker.ceph.com/issues/68766
---
backport of https://github.com/ceph/ceph/pull/50105
parent tracker: https://tracker.ceph.com/issues/58835
> squid: mds: add an asok command to dump export states

- src/cephadm/cephadm.py
- src/cephadm/cephadmlib/container_engines.py
- src/cephadm/cephadmlib/container_types.py
- src/cephadm/tests/test_cephadm.py
Depends on #61579
Move the ContainerInfo class, and the get_container_stats and the (equivalent of) get_container_stats_by_image_name functions out of cephadm.py.
This reduces the size of cephadm.py. As part of the move I refactored the functions so that the commands are run and parsed as a unit. Note that parsing code in the libraries are kept seperate and could be tested alone in unit tests.  But the current tests mix all the things together and I wasn't trying to resolve that situation, just keep thing working while reorganizing a bit.
This work is in preparation for a bigger refactor of the list_daemons function.
- If you are submitting a fix …
> cephadm: move a few other small things out of cephadm.py

- src/osd/PrimaryLogPG.cc
backport tracker: https://tracker.ceph.com/issues/69499
---
backport of https://github.com/ceph/ceph/pull/60795
parent tracker: https://tracker.ceph.com/issues/69014
> reef: osd: optimize extent comparison in PrimaryLogPG

- src/cephadm/tests/test_listing.py
- src/cephadm/tox.ini
Add new tests to specifically cover various behaviors of list_daemons.
Plus a tox config tweak …
> cephadm: add a new set of specific tests for list_daemons

- src/crimson/common/smp_helpers.h
- src/crimson/net/ProtocolV2.cc
- src/crimson/net/io_handler.cc
- src/crimson/net/io_handler.h
io_state_t::none was introduced to resemble async msgr and used by the
single-shard crimson msgr to mark that the connection is invisible by
any user during accepting. But it isn't simple in multi-shard crimson
msgr because the ordering is impossible to predict among the connection
user, connection and the msgr shards if they are in 3 different shards.
So drop io_state_t::none.
Fixes: https://tracker.ceph.com/issues/66606
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPa …
> crimson/net/io_handler: drop io_state_t::none

- src/blk/kernel/io_uring.cc
When using vstart.sh to deploy ceph cluster w/ bdev_ioring=true, met the following error messages:
> /root/ceph/build/bin/ceph-osd -i 0 -c /root/ceph/build/ceph.conf --mkfs --key AQByU/JmoSTAExAApXM0Q6Et9xgfMJ3MJg7wSw== --osd-uuid e135fff2-a02c-415a-b1fe-c154a4e61c13
>2024-09-24T13:51:46.770+0800 7c71966245c0 -1 bdev(0x5c937f62f000 /root/ceph/build/dev/osd0/block) open open w/ O_EXCL
> 2024-09-24T13:51:46.772+0800 7c71966245c0 -1 bluestore(/root/ceph/build/dev/osd0/block) _read_bdev_label unable to decode label /root/ceph/build/dev/osd0/block at offset 102: void bluestore_bdev_label_t::decode(ceph::buffer::v15_2_0::list::const_iterator&) decode past end of struct encoding: Malformed input [buffer:3]
> 2024-09-24T13:51:46.772+0800 7c71966245c0 -1 bluestore(/root/ceph/build/dev/osd0/block) …
> blk: Don't forget call io_uring_unregister_files.

- PendingReleaseNotes
- qa/workunits/fs/misc/fallocate.sh
- src/client/Client.cc
- src/pybind/cephfs/cephfs.pyx
- src/test/pybind/test_cephfs.py
backport tracker: https://tracker.ceph.com/issues/68816
---
backport of https://github.com/ceph/ceph/pull/59725
parent tracker: https://tracker.ceph.com/issues/68026
> squid: client: return EOPNOTSUPP for fallocate with mode 0

- .github/workflows/stale.yml
This reverts commit 6054be59c56a13670abd7d00b828d43730c535c8.
follows discussion from https://github.com/ceph/ceph/pull/60736#issuecomment-2578815921 and consensus from the ceph steering committee
<details>
</details>
> Revert ".github/workflows: Do not exempt PRs with milestone"

- Dockerfile.build
- make-debs.sh
- src/script/build-with-container.py
- src/script/buildcontainer-setup.sh
- src/script/lib-build.sh
backport tracker: https://tracker.ceph.com/issues/69857
---
backport of https://github.com/ceph/ceph/pull/59841
parent tracker: https://tracker.ceph.com/issues/69847
> squid: containerized build tools [V2]

- qa/crontab/teuthology-cronjobs
Now that it's released, we should go back to typical release branch cadence (teuthology queue is also growing).
Also, update the priority (ahead of reef) now that it's released. …
> qa: cut squid nightlies to one-per-week

- qa/suites/upgrade/telemetry-upgrade/reef-x/1-tasks.yaml
- qa/suites/upgrade/telemetry-upgrade/squid-x/1-tasks.yaml
- qa/tasks/thrashosds-health.yaml
In these commits, I added some pattern matching for warnings that show up in the cluster log detail that are related to degraded PGs. In these tests, we are intentionally marking down, killing, or restarting OSDs, which leads to these states showing up in the cluster log. So, the warnings are intended and can be ignored in the context of OSD thrashing and upgrades.
Fixes: https://tracker.ceph.com/issues/67881
Fixes: https://tracker.ceph.com/issues/67913 …
> qa/tasks: improve ignorelist for thrashing OSDs

- src/rgw/rgw_process.cc
The log entry for "starting new request" may display the same hexadecimal value across multiple requests, making it difficult to pinpoint the exact start time of a request. Including the request ID in this log would facilitate easier identification of individual request start times.
Fixes: https://tracker.ceph.com/issues/69715
> rgw: log request_id on start new request

- doc/radosgw/admin.rst
- src/rgw/rgw_common.cc
This commit enables the management of `accounts` user capabilities, as required by `RGWOp_Account_Create`, `RGWOp_Account_Modify`, etc. REST operations.
Bug (if you can call it that) was introduced in commit 10ef9b967435dda86dfa19a29fe6420d7dbb0cc0. …
> rgw: allow management of `accounts` user caps

- src/rgw/driver/rados/rgw_lc_tier.cc
While fetching object from the cloud-endpoint, we need not set headers used internally within RGW. Some of these headers are resulting in 403 error for GET response while using PoINT S3 cloud service.
Fixes: https://tracker.ceph.com/issues/69238
<details>
- `jenkins …
> rgw/cloud-restore: Do not send internal headers to cloud-endpoint

- PendingReleaseNotes
- src/rgw/rgw_rest.cc
- src/rgw/rgw_rest.h
- src/rgw/rgw_rest_s3.cc
Fixes: https://tracker.ceph.com/issues/67846
With this change, LastModified timestamp in S3 responses will be in seconds granularity: i.e., milliseconds+ portion will be normalized.
Given an S3 object
<pre>
>>> pprint(c1_s3.list_objects(Bucket="u1b1")["Contents"][0])
{'ETag': '"24f682f769992022dba3cf73550b7da0"',
'Key': 'obj1',
'LastModified': datetime.datetime(2025, 1, 8, 21, 43, 13, 558000, tzinfo=tzlocal()),
'Owner': {'DisplayName': 'myuser1', 'ID': 'myuser1'},
'Size': 4,
'StorageClass': 'STANDARD'}
</pre> 
<pre>
>>> pprint(c1_s3.list_objects(Bucket="u1b1")["Contents"][0])
{'ETag': '"24f682f769992022dba3cf73550b7da0"',
'Key': 'obj1',
'LastModified': datetime.datetime(2025, 1, 8, 21, 43, 13, tzinfo=tzlocal()),
'Owner': {'DisplayName': 'myuser1', 'ID': 'myuser1'},
'Size': 4, …
> RGW/S3: truncate S3 LastModified response (timestamp) to exact seconds

- src/rgw/radosgw-admin/radosgw-admin.cc
- src/rgw/rgw_rest_bucket_logging.cc
and not the next pending log object name
<details>
</details>
> rgw/logging: flush command should print flushed log object name

- src/blk/CMakeLists.txt
If all the libraries which `libblk` wraps (i.e. Bluestore, AIO, SPDK, ZBD) are disabled, then the build aborts with a linker failure:
```
c++ [...] -o bin/ceph-mon [...] -lblk [...]
mold: fatal: library not found: blk
collect2: error: ld returned 1 exit status
```
This is because `blk` is used (via `os`) but if the `add_library()` directive is skipped, `cmake` attempts to look up a library with that name.
> blk/CMakeLists.txt: generate interface library if `libblk` is disabled

- examples/rgw/boto3/service-2.sdk-extras.json
when URI has the form: "/{Bucket}?<action>"
the "Bucket" parameter has to be added as context parameter for botocore based clients to send the operation as a bucket operation
<details> …
> rgw/notification/logging: add bucket as context param

- src/script/lib-build.sh
In attempt to update to clang16 some of the code is not yet adapted due to deprecated functions.
Let's disable clang 16 usage until https://github.com/ceph/ceph/pull/61740 is merged.
Machines that has clang-16 already installed will fail makecheck until this is merged. …
> script/lib-build: Use clang 14

- src/common/StackStringStream.h
backport tracker: https://tracker.ceph.com/issues/65870
---
backport of https://github.com/ceph/ceph/pull/56810
parent tracker: https://tracker.ceph.com/issues/65805
> reef: common/StackStringStream: update pointer to newly allocated memory in overflow()

- src/rgw/driver/rados/rgw_sal_rados.cc
- src/test/rgw/rgw_multi/tests.py
backport tracker: https://tracker.ceph.com/issues/66920
---
backport of https://github.com/ceph/ceph/pull/56275
parent tracker: https://tracker.ceph.com/issues/64022
> reef: rgw/multisite: allow PutACL replication.

- qa/tasks/cephfs/test_pool_perm.py
Linux will optimize out reads to a file known to be empty.
Fixes: https://tracker.ceph.com/issues/53859
- Tracker …
> qa: do read checks with non-empty file

- doc/dev/release-process.rst
Document that container images are not built by the ceph-build job, but must be done manually after the package signing and upload to download.ceph.com. …
> doc/dev/release-process.rst: release builds cannot build containers

- src/pybind/mgr/mgr_module.py
I misunderstood autocommit=False in prior patches. The sqlite3 binding will still create transactions automatically which confused newer bindings using autocommit.
So, turn off automatic transaction management completely to maintain backwards compatibility.
Fixes: https://tracker.ceph.com/issues/69912 …
> pybind/mgr/mgr_module: turn off all automatic transactions

- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
- Different name is used in POST and PATCH for `rbd_image_size`
- Using same name in both requests
- fixing typing issues in frontend
Fixes https://tracker.ceph.com/issues/69864
<details> …
> mgr/dashboard: (refactor)fix image size in nvmeof namespace create/update api

- src/common/perf_counters.cc
Using Formatter::ObjectSection & Formatter::ArraySection to
guarantee consistent opening & closing of dump sections.
> common/perf_counters: use the RAII helpers when dumping

- src/krbd.cc
- src/mon/ConfigMap.cc
- src/mon/ConfigMap.h
- src/mon/ConfigMonitor.cc
- src/mon/ConfigMonitor.h
- src/mon/ElectionLogic.cc
- src/mon/ElectionLogic.h
- src/mon/FSCommands.cc
- src/mon/FSCommands.h
- src/mon/MDSMonitor.cc
- src/mon/MgrMap.h
- src/mon/MonClient.h
- src/mon/MonMap.h
- src/mon/Monitor.cc
- src/mon/MonmapMonitor.cc
- src/mon/PGMap.cc
- src/mon/PGMap.h
- src/mon/Paxos.cc
- src/mon/Session.h
- src/mon/mon_types.h
Another PR split from https://github.com/ceph/ceph/pull/60490; this time the "mon" subsystem.
<details>
</details>
> mon: include cleanup

- src/tools/rbd_mirror/ImageReplayer.cc
Fixes a crash in the ImageReplayer shut down sequence. Credit to idryomov@gmail.com.
Fixes: https://tracker.ceph.com/issues/69978 …
> rbd-mirror: fix possible recursive lock of ImageReplayer::m_lock

- src/pybind/mgr/dashboard/controllers/nvmeof.py
Made sure the namespace update endpoint will fail if no action was requested or if more than one action was requested, as well as made it not suppress errors but let them propagate.
It seems like the current behavior implicitly allows only one update operation executed(update operations available: resize, change lb group, set qos limits). if the user requested more than 1, it will succeed although only 1 operation was executed which might be very confusing. Also, I let it return also responses with status != so the `@handle_nvmeof_error` will catch error cases. I hope it makes sense :) 
I will be glad to hear your thoughts :)
Thanks!
fixes: https://tracker.ceph.com/issues/62705 …
> mgr/dashboard: namespace update route robustness

- qa/workunits/rbd/permissions.sh
- src/mon/OSDMonitor.cc
- src/osd/OSDCap.cc
backport tracker: https://tracker.ceph.com/issues/69729
---
backport of https://github.com/ceph/ceph/pull/61540
parent tracker: https://tracker.ceph.com/issues/69679
> squid: mon/OSDMonitor: relax cap enforcement for unmanaged snapshots

- src/tools/rbd/action/MirrorPool.cc
backport tracker: https://tracker.ceph.com/issues/69334
---
backport of https://github.com/ceph/ceph/pull/61150
parent tracker: https://tracker.ceph.com/issues/69319
> squid: rbd: open images in read-only mode for "rbd mirror pool status --verbose"

- src/librbd/librbd.cc
backport tracker: https://tracker.ceph.com/issues/69653
---
backport of https://github.com/ceph/ceph/pull/61492
parent tracker: https://tracker.ceph.com/issues/69619
> squid: librbd: clear ctx before initiating close in Image::{aio_,}close()

- src/librbd/Operations.cc
backport tracker: https://tracker.ceph.com/issues/69783
---
backport of https://github.com/ceph/ceph/pull/61567
parent tracker: https://tracker.ceph.com/issues/58185
> squid: librbd: stop filtering async request error codes

- src/script/ceph-debug-docker.sh
looks like centos9 image is not present on https://hub.docker.com/_/centos therefore it fails to get image and instantiate debug 
```
container: Step 1/4 : FROM centos:stream9
manifest for centos:stream9 not found: manifest unknown: manifest unknown
```
hence switching to `quay.io/centos/centos:stream9` …
> script/ceph-debug-docker.sh: fix manifest unknown error

- src/script/ceph-backport.sh
this script uses `pgrep firefox` to determine whether a browser is open, and will pause the ceph-backport script waiting for the commands `firefox "${backport_pr_url}` and `firefox "${redmine_url}"` to exit
on Fedora release 41 with Mozilla Firefox 133.0, `pgrep firefox` always finds a process even if no browser window is open:
> /usr/lib64/firefox/firefox --dbus-service /usr/bin/firefox
the ceph-backport script prints these URLs as output, so it's easy enough to open them in a browser where desired
<details>
- …
> script: ceph-backport no longer launches firefox

- container/Containerfile
backport tracker: https://tracker.ceph.com/issues/69720
---
backport of https://github.com/ceph/ceph/pull/61218
parent tracker: https://tracker.ceph.com/issues/69698
> reef: container/Containerfile: replace CEPH_VERSION label for backward compat

- container/build.sh
backport tracker: https://tracker.ceph.com/issues/69718
---
backport of https://github.com/ceph/ceph/pull/61489
parent tracker: https://tracker.ceph.com/issues/69699
> reef: container/build.sh: fix up org vs. repo naming

- container/build.sh
backport tracker: https://tracker.ceph.com/issues/69716
---
backport of https://github.com/ceph/ceph/pull/61510
parent tracker: https://tracker.ceph.com/issues/69700
> reef: container/build.sh: don't require repo creds on NO_PUSH

- PendingReleaseNotes
- qa/standalone/mon/osd-pool-df.sh
- src/crush/CrushWrapper.cc
If there are multiple takes in a crush rule that place a different
number of objects we do not take that into account. This creates
a MAX AVAIL stat inconsistency for a given pool from crush rule
having multiple takes. Merge weights before normalizing the
weight map.
Signed-off-by: Prashant D <pdhange@redhat.com> …
> crush/CrushWrapper: Merge weights if rule contains multiple take

- src/pybind/mgr/volumes/fs/operations/versions/metadata_manager.py
- src/pybind/mgr/volumes/fs/operations/versions/subvolume_v1.py
backport tracker: https://tracker.ceph.com/issues/68590
---
backport of https://github.com/ceph/ceph/pull/58292
parent tracker: https://tracker.ceph.com/issues/66815
> reef: mgr/vol : shortening the name of helper method

- src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
- src/pybind/mgr/cephadm/tests/test_services.py
- src/python-common/ceph/deployment/service_spec.py
mgr/cephadm/nvmeof: Add QOS timeslice field to NVMeOF configuration
Fixes https://tracker.ceph.com/issues/69952
- …
> mgr/cephadm/nvmeof: Add QOS timeslice field to NVMeOF configuration

- src/crimson/osd/object_context_loader.h
I encountered the following error message while debugging the log.
> crimson::osd::ObjectContextLoader::Orderer::~Orderer(): failed to log message: fmt='{}: releasing obc {}, {}': fmt::v11::format_error (argument not found) …
> crimson/osd: remove invalid an argument when printing log

- src/common/options/global.yaml.in
- src/os/CMakeLists.txt
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
Changed "bluestore/fragmentation_micros" from quick imprecise to slow but more representative score.
Introduced config "bluestore_warn_on_free_fragmentation" that controls when free space fragmentation score becomes a health warning.
Currently calculation of fragmentation score might be non-instant for severly fragmented disks. It might induce stalls to write IO. Config value "bluestore_fragmentation_check_period" control score calculation period.
In future, costly score calculation will be replaced with method that continously updates score. …
> os/bluestore: Add health warning for bluestore fragmentation

- src/test/rbd_mirror/test_ImageReplayer.cc
TestImageReplayer establishes its own (i.e. outside of the SUT code) watch on the header of the remote image to be able to synchronize the execution of the test with certain notifications.  This watch is established before the remote image is opened and is teared down until after the remote image is closed but while the image replayer is still running.  The flush that is part of image close sequence thus isn't guaranteed to cover all callbacks, especially for snapshot-based mirroring where UnlinkPeerRequest spawned from Replayer::unlink_peer() generates a notification on the remote image for each completed unlink. Since TestImageReplayer further immediately deletes C_WatchCtx, pretty much any test can segfault when C_WatchCtx::handle_notify() is invoked by TestWatchNotify infrastructure. …
> test/rbd_mirror: flush watch/notify callbacks in TestImageReplayer

- src/pybind/mgr/dashboard/requirements-test.txt
It disables the specific pinning to a Python xmlsec version.
Shaman [build](https://shaman.ceph.com/builds/ceph/fix-70019-main/):
* CentOS 9 - default x86_64 🆗 (using `xmlsec-1.3.14-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`)
* CentOS 9 - default arm64 🆗  (using `xmlsec-1.3.14-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl`)
* CentOS 9 - crimson x86_64 🆗  (using `xmlsec-1.3.14-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`)
* Ubuntu Jammy - default x86_64 🆗 (using `xmlsec-1.3.14-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`)
---
Fixes: https://tracker.ceph.com/issues/70019
Fixes: 37e633384b7c18893bc0e30a8f3967f6496da00b
Fixes: https://github.com/ceph/ceph/pull/61089 …
> mgr/dashboard: fix Python xmlsec build issue

- src/os/bluestore/BlueStore.cc
- src/os/bluestore/Writer.cc
do_write_v2 insert extentmap by aligned offset which is adjusted in writer.do_write, if use original offset will cause extentmap can't do compress. …
> os/bluestore: fix do_write_v2 extentmap compress issue

- doc/mgr/rgw.rst
Add documentation for adding fs_id in root_ca_cert upgrade path
Fixes: https://tracker.ceph.com/issues/70014
Signed-off-by: Anuradha Gadge <anuradha.gadge@ibm.com>
(cherry picked from commit 76106dd9890fdbd9440a5f7de85e9d5de6d0a2b4)
doc/mgr: edit grammar and formatting of rgw.rst
Improve the grammar and correct the formatting of the "Upgrading root ca certificates" procedure that was added to the documentation in https://github.com/ceph/ceph/pull/61867
Fixes: https://tracker.ceph.com/issues/70014
(cherry picked from commit 7d9298e3de74e91db116c79a7087f559464ae52d) …
> reef: doc/mgr: Add root CA cert instructions to rgw.rst

- doc/mgr/rgw.rst
Add documentation for adding fs_id in root_ca_cert upgrade path
Fixes: https://tracker.ceph.com/issues/70014
Signed-off-by: Anuradha Gadge <anuradha.gadge@ibm.com>
(cherry picked from commit 76106dd9890fdbd9440a5f7de85e9d5de6d0a2b4)
doc/mgr: edit grammar and formatting of rgw.rst
Improve the grammar and correct the formatting of the "Upgrading root ca certificates" procedure that was added to the documentation in https://github.com/ceph/ceph/pull/61867
Fixes: https://tracker.ceph.com/issues/70014
(cherry picked from commit 7d9298e3de74e91db116c79a7087f559464ae52d) …
> squid: doc/mgr: Add root CA cert instructions to rgw.rst

- src/script/lib-build.sh
Updating to newer clang requires multiple fixes.
Don't use newer clang than 14 in squid.
If needed, we could backport the fixes from [1] and then use newer releases.
[1] https://github.com/ceph/ceph/pull/61740 …
> squid: script/lib-build: Use clang 14

- doc/mgr/telemetry.rst
- qa/workunits/test_telemetry_reef_x.sh
- qa/workunits/test_telemetry_squid_x.sh
- src/pybind/mgr/telemetry/module.py
Closes: https://tracker.ceph.com/issues/67812
[Stretch Mode](https://docs.ceph.com/en/reef/rados/operations/stretch-mode/) information helps us learn how deployments are done for stretch clusters. We add a `basic_stretch_cluster` collection to the `basic` channel for this purpose.
The newly added `basic_stretch_cluster` collection in the `basic` channel looks like:
```json
"stretch_cluster": {
"degraded_stretch_mode": 0,
"recovering_stretch_mode": 0,
"stretch_bucket_count": 2,
"stretch_mode_bucket": 9,
"stretch_mode_enabled": true
},
```
<details>
Telemetry module is used to send anonymous data about the Ceph cluster to us which helps us understand how Ceph is being used in the wild. The code for this is present in [here](https://github.com/ceph/ceph/blob/main/src/pybind/mgr/telemetry/modu …
> mgr/telemetry: add stretch cluster data

- qa/tasks/cephadm_cases/test_cli.py
The test before the pause test ends with `ceph orch daemon restart osd.0`
which may temporarily cause a CEPHADM_FAILED_DAEMON warning for that
OSD. It seems to be failing with "status=219/CGROUP", logging nothing
else of note, and coming up totally fine when restarted by systemd
a second later (see the linked tracker for more info/logs). This
sleep is me thinking this may be timing related and that if we
separate the start from the restart by a few more seconds it might
avoid the error.
Fixes: https://tracker.ceph.com/issues/69526 …
> qa/cephadm: wait between starting and restarting osd in test_daemon_restart test

- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/services/cephadmservice.py
- src/pybind/mgr/rook/rook_cluster.py
- src/python-common/ceph/deployment/service_spec.py
Cephadm: Display comma separated ports for RGW services
In this change, `get_port` has been modified  to return both frontend and SSL ports when applicable, ensuring that `ceph orch ls` correctly displays both ports.
Fixes: https://tracker.ceph.com/issues/69664
Test logs:
```
> cat rgw_spec.yaml
service_type: rgw
service_id: foo
placement:
label: rgw
count_per_host: 1
spec:
ssl: true  # Required for SSL
generate_cert: true  
rgw_frontend_port: 8080  # Regular HTTP port
rgw_frontend_extra_args:
- ssl_port=9443
> ceph orch apply -i rgw_spec.yaml
```
```
> ceph orch host ls
HOST         ADDR             LABELS      STATUS
ceph-node-0  192.168.100.100  _admin,rgw           
ceph-node-1  192.168.100.101  rgw                  
ceph-node-2  192.168.100.102  
```
```
> ceph config dump | grep rgw …
```
> Display comma separated ports for RGW services

- src/pybind/mgr/cephadm/services/nfs.py
- src/pybind/mgr/cephadm/templates/services/nfs/ganesha.conf.j2
- src/pybind/mgr/cephadm/tests/test_services.py
For NFS HA changes, nodeid should be numeric for RADOS_KV block in ganesha.conf file. Refer Ganesha code change - https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1207554
Fixes: https://tracker.ceph.com/issues/69808
Testing logs:
```
[root@ceph-node-0 fe8d97b8-e3a3-11ef-af91-525400b09e9f]# cat /var/lib/ceph/fe8d97b8-e3a3-11ef-af91-525400b09e9f/nfs.mynfs.1.1.ceph-node-0.shngry/etc/ganesha/ganesha.conf | grep -i nodeid
nodeid = 1;
[root@ceph-node-0 fe8d97b8-e3a3-11ef-af91-525400b09e9f]# 
[root@ceph-node-1 ~]# cat /var/lib/ceph/fe8d97b8-e3a3-11ef-af91-525400b09e9f/nfs.mynfs.0.1.ceph-node-1.dbtjwv/etc/ganesha/ganesha.conf | grep -i nodeid
nodeid = 0;
[root@ceph-node-1 ~]# 
ceph.cephadm.log:480:2025-02-05T11:16:12.733412+0000 …
```
> mgr/nfs: nodeid should be numeric for RADOS_KV block in ganesha.conf file

- src/pybind/mgr/cephadm/services/ingress.py
This was intended to be vrrp_interfaces, the variable actually used later in the code. Instead, due to a typo, it was setting a variable that is unused other than in the log line right after it is set. Issue was introduced in
https://github.com/ceph/ceph/commit/58ddc4e20f7cead1f2594241450f4beb5230c746 …
> mgr/cephadm: fix typo with vrrp_interfaces in keepalive setup

- src/test/rgw/bucket_notification/test_bn.py
the get_ip() function now uses the get_ip_http() implementation. (without that test are sometimes failing with multiple RGWs). however, the name was modified to get_ip(), and this was not updated in all tests. …
> reef: fix issue with bucket notification test

- qa/workunits/cephadm/test_cephadm.sh
This patch is intended directly for the reef branch. On reef, we should be running tests using the reef image. This should have been updated at some point after reef branched off from main. The only reason the issue wasn't immediately apparent is the test continued to succeed until the version on main went from 18 -> 19
Fixes: https://tracker.ceph.com/issues/64208
<details>
- …
> reef: qa/cephadm: use reef image as default for test_cephadm workunit

- src/pybind/mgr/cephadm/serve.py
backport tracker: https://tracker.ceph.com/issues/68202
---
backport of https://github.com/ceph/ceph/pull/59728
parent tracker: https://tracker.ceph.com/issues/68027
> reef: mgr/cephadm: use host address while updating rgw zone endpoints

- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/serve.py
- src/pybind/mgr/cephadm/services/cephadmservice.py
backport tracker: https://tracker.ceph.com/issues/68547
---
backport of https://github.com/ceph/ceph/pull/60221
parent tracker: https://tracker.ceph.com/issues/68461
> reef: mgr/cephadm: Update multi-site configs before deploying  daemons on rgw service create

- qa/tasks/nvme_loop.py
backport tracker: https://tracker.ceph.com/issues/69186
---
backport of https://github.com/ceph/ceph/pull/60928
parent tracker: https://tracker.ceph.com/issues/69067
> reef: qa/tasks/nvme_loop: update task to work with new nvme list format

- qa/suites/orch/cephadm/workunits/task/test_rgw_multisite.yaml
- qa/suites/upgrade/pacific-x/parallel/1-tasks.yaml
- qa/tasks/thrashosds-health.yaml
backport tracker: https://tracker.ceph.com/issues/66476
---
backport of https://github.com/ceph/ceph/pull/56619
parent tracker: https://tracker.ceph.com/issues/64864
> reef: qa/suites: add "mon down" log variations to ignorelist

- src/cephadm/cephadm.py
- src/cephadm/tests/test_enclosure.py
- src/cephadm/tests/test_host_facts.py
backport tracker: https://tracker.ceph.com/issues/66529
---
backport of https://github.com/ceph/ceph/pull/57955
parent tracker: https://tracker.ceph.com/issues/66389
> reef: cephadm: fix apparmor profiles with spaces in the names

- src/pybind/mgr/rgw/module.py
- src/python-common/ceph/rgw/rgwam_core.py
backport tracker: https://tracker.ceph.com/issues/66647
---
backport of https://github.com/ceph/ceph/pull/58142
parent tracker: https://tracker.ceph.com/issues/66568
> reef: mgr/rgw: fix error handling in rgw zone create

- src/pybind/mgr/cephadm/tests/test_services.py
- src/python-common/ceph/deployment/service_spec.py
cephadm: ceph orch ls to Display SMB Service Ports
The ceph orch ls command does not list the ports for SMB services, while ceph orch ps correctly displays them. This discrepancy occurs because ServiceDescription in describe_service() relies on spec.get_port_start(), but SMBSpec does not define this method. As a result, the ports field remains empty in ceph orch ls. …
> cephadm: ceph orch ls to Display SMB Service Ports

- src/pybind/mgr/cephadm/services/cephadmservice.py
- src/pybind/mgr/cephadm/services/ingress.py
Now updating the rgw_frontend_ssl_cert will cause us to reocnfigure rgw daemons that are part of the service. This will additionally cause us to redo the service level config operations which for rgw includes storing the cert in the config-key store where rgw will look for it. Similarly if the user changes the cert/key of ingress spec cephadm will automatically reconfigure the corresponding daemons.
Fixes: https://tracker.ceph.com/issues/69863
Co-authored by: Adam King <adking@redhat.com>
(cherry picked from commit 74ca2e71888f9b49d803a2ee0e1658b5e9acf30a) …
> mgr/cephadm: reconfig rgw and ingress daemons when certificate changes

- src/pybind/mgr/cephadm/templates/services/nfs/ganesha.conf.j2
- src/pybind/mgr/cephadm/tests/test_services.py
This came directly from someone on the ganesha team. We've actually had this use single quotes for a long time (at least since mid 2020) but I believe recent feature work on the ganesha side exposed the issue
```
ganesha.nfsd-2[main] config_errs_to_log :CONFIG :WARN :Config File (/etc/ganesha/ganesha.conf:13): Unknown token ('rados_cluster')
```
Fixes: https://tracker.ceph.com/issues/69930 …
> mgr/cephadm: use double quotes for NFSv4 RecoveryBackend in ganesha conf

- src/pybind/mgr/cephadm/inventory.py
- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/tests/test_services.py
This came as a recommendation from the nvmeof team because
1) users shouldn't have multiple nvmeof services with the same group
and
2) some users may take an existing nvmeof service spec and modify
the service id to point to another group but forget to update
the actual group parameter. This makes it look at a glance like
the two services are using different groups when they are in fact not.
Usually I'd write a spec migration for this, but if we were to find
users had two specs with duplicate groups or specs where the service
id doesn't match the group name, I don't think there's a clear path
of action to take to remedy the situation. Even just forcing the
service id of an nvmeof service to be pool_name.group_name I think
could cause a lot of confusion during an upgrade so I'm tentative …
> mgr/cephadm: validate no duplicate groups and group vs. service id for nvmeof

- src/cephadm/cephadm.py
backport tracker: https://tracker.ceph.com/issues/66788
---
backport of https://github.com/ceph/ceph/pull/57975
parent tracker: https://tracker.ceph.com/issues/66436
> reef: cephadm: disable ms_bind_ipv4 if we will enable ms_bind_ipv6

- src/python-common/ceph/rgw/rgwam_core.py
backport tracker: https://tracker.ceph.com/issues/66891
---
backport of https://github.com/ceph/ceph/pull/58326
parent tracker: https://tracker.ceph.com/issues/66824
> reef: mgr/rgw: fix setting rgw realm token in secondary site rgw spec

- src/cephadm/cephadm.py
backport tracker: https://tracker.ceph.com/issues/66959
---
backport of https://github.com/ceph/ceph/pull/58379
parent tracker: https://tracker.ceph.com/issues/66848
> reef: cephadm: turn off cgroups_split setting  when bootstrapping with --no-cgroups-split

- qa/suites/upgrade/pacific-x/parallel/upgrade-sequence.yaml
- qa/suites/upgrade/pacific-x/stress-split/1-start.yaml
- qa/suites/upgrade/quincy-x/parallel/upgrade-sequence.yaml
- qa/suites/upgrade/quincy-x/stress-split/1-start.yaml
- qa/suites/upgrade/telemetry-upgrade/pacific-x/1-tasks.yaml
- qa/suites/upgrade/telemetry-upgrade/quincy-x/1-tasks.yaml
backport tracker: https://tracker.ceph.com/issues/67463
---
backport of https://github.com/ceph/ceph/pull/58605
parent tracker: https://tracker.ceph.com/issues/65546
> reef: qa/upgrade: fix checks to make sure upgrade is still in progress

- src/pybind/mgr/cephadm/service_discovery.py
- src/pybind/mgr/cephadm/services/monitoring.py
- src/pybind/mgr/cephadm/services/nfs.py
- src/pybind/mgr/cephadm/templates/services/prometheus/prometheus.yml.j2
- src/pybind/mgr/cephadm/tests/test_service_discovery.py
- src/pybind/mgr/cephadm/tests/test_services.py
backport tracker: https://tracker.ceph.com/issues/67498
---
backport of https://github.com/ceph/ceph/pull/55050
parent tracker: https://tracker.ceph.com/issues/62558
> reef: mgr/nfs: scrape nfs monitoring endpoint

- src/cephadm/cephadm.py
backport tracker: https://tracker.ceph.com/issues/68018
---
backport of https://github.com/ceph/ceph/pull/59485
parent tracker: https://tracker.ceph.com/issues/67778
> reef: cephadm: emit warning if daemon's image is not to be used

- src/osd/PeeringState.cc
- src/osd/PeeringState.h
It's know that the `md_config_t::get_val<>()` method template is costly and should be avoided on hot paths.
Recent profiling[1] by Mark Kogan has shown that, on RGW's bucket listing, an OSD had burnt 2,87% of CPU cycles on `get_val<long>()` in `PG::prepare_stats_for_publish()`.
[1]: https://github.com/ceph/ceph/pull/60278#issuecomment-2415718353 …
> osd: avoid costly md_config_t::get_val<>() when preparing stats

- qa/standalone/ceph-helpers.sh
- qa/standalone/osd/divergent-priors.sh
- qa/standalone/osd/repeer-on-acting-back.sh
- qa/standalone/scrub/osd-scrub-test.sh
Multiple tests use /etc/fstab whenever a small data file is required as input. After all, as some comments say:
Alas - it's not always there. Not in containers.
Replacing with a newly-created temporary file filled with random bytes.
> qa/standalone: do not use /etc/fstab as an always-there bytes source

- src/crimson/osd/backfill_facades.h
- src/crimson/osd/backfill_state.cc
- src/crimson/osd/backfill_state.h
- src/crimson/osd/pg_recovery.cc
- src/crimson/osd/recovery_backend.cc
- src/test/crimson/test_backfill.cc
Fixes: https://tracker.ceph.com/issues/67916 …
> crimson/osd/recovery_backend: always set the primary osd's BackfillInterval::version to the last_update before the backfill scan

- src/test/rbd_mirror/test_mock_PoolReplayer.cc
TestMockPoolReplayer.Namespaces and NamespacesError tests leave behind a dangling pointer to a stack-allocated MockNamespace which leads to an easily reproducible use-after-free and segfault when tests are shuffled.
Fixes: https://tracker.ceph.com/issues/70041 …
> test/rbd_mirror: clear Namespace::s_instance at the end of a test

- src/python-common/ceph/deployment/utils.py
Backport of https://github.com/ceph/ceph/pull/52678 as I saw this start happening in make check on reef
<details>
</details>
> reef: python-common: fix valid_addr on python 3.11

- src/pybind/mgr/dashboard/controllers/ceph_users.py
- src/pybind/mgr/dashboard/openapi.yaml
This PR updates the current openapi specification for mgr/dashboard module alligning current /api/cluster/user/export endpoint with its actual behaviour. The current API expects a entities array of strings for exporting Ceph users but is documented as a single string in the documentation.
A proof of current behaviour can be obtained by trying API calls or checking already existing [user service](https://github.com/ceph/ceph/blob/main/src/pybind/mgr/dashboard/frontend/src/app/shared/api/ceph-user.service.ts) code which expects `entities: string[]` as an array. …
> mgr/dashboard: update openapi specification for /api/cluster/user/export

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
Before:
===
Users were able to delete the bucket from dashboard or using API even if they have objects in them.
Now:
===
Users will unable to delete the bucket if it has objects
Fixes: https://tracker.ceph.com/issues/70078
https://github.com/user-attachments/assets/a73f64e6-7fa6-4820-9a03-565a432adb75 …
> mgr/dashboard: disable deleting bucket with objects

- src/test/rbd_mirror/test_ImageReplayer.cc
backport tracker: https://tracker.ceph.com/issues/70038
---
backport of https://github.com/ceph/ceph/pull/61847
parent tracker: https://tracker.ceph.com/issues/63798
> reef: test/rbd_mirror: flush watch/notify callbacks in TestImageReplayer

- src/test/rbd_mirror/test_mock_PoolReplayer.cc
backport tracker: https://tracker.ceph.com/issues/70102
---
backport of https://github.com/ceph/ceph/pull/61880
parent tracker: https://tracker.ceph.com/issues/70041
> reef: test/rbd_mirror: clear Namespace::s_instance at the end of a test

- src/test/rbd_mirror/test_ImageReplayer.cc
backport tracker: https://tracker.ceph.com/issues/70039
---
backport of https://github.com/ceph/ceph/pull/61847
parent tracker: https://tracker.ceph.com/issues/63798
> squid: test/rbd_mirror: flush watch/notify callbacks in TestImageReplayer

- src/test/rbd_mirror/test_mock_PoolReplayer.cc
backport tracker: https://tracker.ceph.com/issues/70101
---
backport of https://github.com/ceph/ceph/pull/61880
parent tracker: https://tracker.ceph.com/issues/70041
> squid: test/rbd_mirror: clear Namespace::s_instance at the end of a test

- qa/standalone/scrub/osd-scrub-test.sh
- qa/standalone/scrub/scrub-helpers.sh
The scenario created in the test requires two PGs that share the same Primary and at least one more member of their active sets. The PR handles the (unlikely) case where the first PG tried does not have a counterpart that matches the requirements.
A minor related fix in scrub-helpers.sh: using 'printf' to return a value, instead of an out (ref) parameter.
Fixes: https://tracker.ceph.com/issues/69837
> qa/standalone/scrub: retry in TEST_abort_periodic_for_operator()

- src/ceph-volume/ceph_volume/devices/lvm/batch.py
- src/ceph-volume/ceph_volume/tests/api/test_lvm.py
- src/ceph-volume/ceph_volume/tests/conftest.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_activate.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_batch.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_deactivate.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_listing.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_migrate.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_prepare.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_zap.py
- src/ceph-volume/ceph_volume/tests/devices/raw/test_list.py
- src/ceph-volume/ceph_volume/tests/devices/raw/test_prepare.py
- src/ceph-volume/ceph_volume/tests/devices/simple/test_activate.py
- src/ceph-volume/ceph_volume/tests/devices/test_zap.py
- src/ceph-volume/ceph_volume/tests/objectstore/test_baseobjectstore.py
- src/ceph-volume/ceph_volume/tests/objectstore/test_bluestore.py
- src/ceph-volume/ceph_volume/tests/objectstore/test_lvmbluestore.py
- src/ceph-volume/ceph_volume/tests/objectstore/test_rawbluestore.py
- src/ceph-volume/ceph_volume/tests/test_inventory.py
- src/ceph-volume/ceph_volume/tests/util/test_arg_validators.py
- src/ceph-volume/ceph_volume/tests/util/test_device.py
- src/ceph-volume/ceph_volume/tests/util/test_disk.py
- src/ceph-volume/ceph_volume/tests/util/test_encryption.py
- src/ceph-volume/ceph_volume/tests/util/test_prepare.py
- src/ceph-volume/ceph_volume/tests/util/test_system.py
- src/ceph-volume/ceph_volume/util/disk.py
- src/ceph-volume/tox.ini
This change enables ceph-volume to create OSDs where the DB is
explicitly placed on a separate LVM partition, even in collocated
scenarios (i.e., block and DB on the same device).
This helps mitigate BlueStore fragmentation issues.
Given that ceph-volume can't automatically predict a proper default size for the db device,
the idea is to use the `--block-db-size` parameter:
Passing `--block-db-size` and `--db-devices` makes ceph-volume create db devices
on dedicated devices (current implementation):
```
Total OSDs: 2
Type            Path                                                    LV Size         % of device
----------------------------------------------------------------------------------------------------
data            /dev/vdb …
```
> ceph-volume: support splitting db even on collocated scenario

- src/msg/async/ProtocolV1.cc
- src/msg/async/ProtocolV1.h
- src/msg/async/ProtocolV2.cc
backport tracker: https://tracker.ceph.com/issues/65947
---
backport of https://github.com/ceph/ceph/pull/49619
parent tracker: https://tracker.ceph.com/issues/52657
> reef: msg/async: Encode message once features are set

- doc/rados/operations/health-checks.rst
- src/mon/HealthMonitor.cc
- src/mon/HealthMonitor.h
- src/mon/OSDMonitor.cc
**Problem:**
In stretch mode, we encountered
an assert failure when checking for
dead crush zones when we have a none-existing
CRUSH bucket.
**Solution:**
Ignore the non-existent crush bucket, instead
of asserting. We then warn the user about a particular
MON contains a non-existent CRUSH bucket.
The tiebreaker monitor is the only exception where
we would allow having non-existent Crush location
Fixes: https://tracker.ceph.com/issues/63861 …
> src/mon/OSDMonitor.cc: [Stretch Mode] WRN non-existent CRUSH location assigned to MON

- do_cmake.sh
- install-deps.sh
Two necessary but not sufficient changes to build ceph on centos 10 stream.
<details>
</details>
> build: a pair of needed changes to build on centos 10 stream

- src/pybind/mgr/rgw/module.py
- src/python-common/ceph/rgw/rgwam_core.py
backport tracker: https://tracker.ceph.com/issues/67111
---
backport of https://github.com/ceph/ceph/pull/58343
parent tracker: https://tracker.ceph.com/issues/66750
> reef: mgr/rgw: Adding a retry config while calling zone_create()

- src/pybind/mgr/cephadm/services/ingress.py
Backport of https://github.com/ceph/ceph/pull/61663
<details>
</details>
> reef: mgr/cephadm: fix typo with vrrp_interfaces in keepalive setup

- src/pybind/mgr/orchestrator/module.py
backport tracker: https://tracker.ceph.com/issues/68081
---
backport of https://github.com/ceph/ceph/pull/59752
parent tracker: https://tracker.ceph.com/issues/68045
> reef: orch: refactor boolean handling in drive group spec

- qa/suites/orch/cephadm/upgrade/3-upgrade/staggered.yaml
backport tracker: https://tracker.ceph.com/issues/68647
---
backport of https://github.com/ceph/ceph/pull/59470
parent tracker: https://tracker.ceph.com/issues/67758
> reef: qa/cephadm: wait a bit before checking rgw daemons upgraded w/ `ceph versions`

- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/tests/test_cephadm.py
backport tracker: https://tracker.ceph.com/issues/68822
---
backport of https://github.com/ceph/ceph/pull/60425
parent tracker: https://tracker.ceph.com/issues/68681
> reef: mgr/cephadm: ceph orch host drain command to return error for invalid hostname

- src/pybind/mgr/orchestrator/module.py
backport tracker: https://tracker.ceph.com/issues/69515
---
backport of https://github.com/ceph/ceph/pull/61035
parent tracker: https://tracker.ceph.com/issues/69192
> reef: mgr/cephadm: mgr orchestrator module raise exception if there is trailing tab in yaml file

- src/blk/kernel/KernelDevice.cc
- src/blk/kernel/KernelDevice.h
- src/common/options/global.yaml.in
Some disks have a discard performance that is too low to keep up with write workloads. Using async discard in this case will cause the OSD to run out of capacity due to the number of outstanding discards preventing allocations from being freed. While sync discard could be used in this case to cause backpressure, this might have unacceptable performance implications.
For the most part, as long as enough discards are getting through to a device, then it will stay trimmed enough to maintain acceptable performance. Thus, we can introduce a cap on the pending discard count, ensuring that the queue of allocations to be freed doesn't get too long while also issuing sufficient discards to disk. The default value of 1000000 has ample room for discard spikes (e.g. from snaptrim); it could result in …
> blk/KernelDevice: Introduce a cap on the number of pending discards

- src/os/bluestore/Allocator.cc
Use allocator's unit size instead of 4096 as default value. This makes "bluefs-db" and "bluefs-wal" histograms work on defaults.
+ Fixed error printout
Fixes: https://tracker.ceph.com/issues/69855 …
> os/bluestore: Fix default base size for histogram

- qa/suites/fs/fscrypt/tasks/1-tests/fscrypt-common.yaml
- qa/suites/fs/fscrypt/tasks/1-tests/fscrypt-dbench.yaml
- qa/suites/fs/fscrypt/tasks/1-tests/fscrypt-ffsb.yaml
- qa/suites/fs/fscrypt/tasks/1-tests/fscrypt-iozone.yaml
- qa/suites/fs/fscrypt/tasks/1-tests/fscrypt-pjd.yaml
- qa/tasks/cephfs/test_fscrypt.py
- qa/workunits/fs/fscrypt.sh
- qa/workunits/fs/fscrypt_cli_setup.sh
This PR addresses the folliowing case:
**Currently, fuse cannot use ioctls defined in the kernel because they have incorrect input/output definitions and are restricted. This affects the set|get policy ioctls[1](https://tracker.ceph.com/issues/68776?tab=history#fn1). Now we are using custom ioctls defined only in userspace to handle these operations. These new ioctls are defined in custom fscrypt commands.**
The fix contains 3 parts:
- new script `fscrypt_cli_setup.sh` which installs our custom fscrypt branch
- updated `fscrypt.sh` workunit, which initializes the fscrypt instead of xfsdev
- updated `fscrypt-common.yaml` that runs the `fscrypt_cli_setup.sh` on the client machines when running tests
The current state of the teuthology tests for the fs/fscrypt suite:
This branch fails …
> client: Use custom fscrypt cli in fs/fscrypt suite

- container/Containerfile
Two improvements to the container build process that I noticed:
Fixes: https://tracker.ceph.com/issues/69869
Fixes: https://tracker.ceph.com/issues/69868
Avoid installing and then deleting docs/manpages.
Stop deleting pyc files.
I discovered these issues by running `rpm -Va` inside the ceph container. While it's not 100% now, and probably will (should) never be... it generates a lot less noise now and we're buiding things in a more "standard" way. …
> container: small container image improvements

- src/crush/CrushWrapper.cc
- src/crush/CrushWrapper.h
The `crush_objs` library is not part of the `libceph-common` ABI, so applications linking with `libceph-common` may fail to build because the linker cannot find `crush_destroy()`.
See https://github.com/ceph/ceph/pull/61697#discussion_r1958810091 for an instance of the bug fixed by this PR. (@batrick)
<details>
- …
> crush/CrushWrapper: un-inline methods to fix linker errors

- src/client/Client.h
- src/crush/CrushWrapper.cc
- src/crush/CrushWrapper.h
- src/osdc/Filer.cc
- src/osdc/Filer.h
- src/osdc/Journaler.cc
- src/osdc/Journaler.h
- src/osdc/ObjectCacher.cc
- src/osdc/ObjectCacher.h
- src/osdc/Objecter.cc
- src/osdc/Objecter.h
- src/osdc/Striper.h
Another PR split from https://github.com/ceph/ceph/pull/60490; this time the "osdc" subsystem.
<details>
</details>
> osdc: include cleanup

- src/libcephsqlite.cc
> libcephsqlite: add missing includes

- src/python-common/ceph/deployment/service_spec.py
- src/python-common/ceph/tests/test_service_spec.py
backport tracker: https://tracker.ceph.com/issues/65725
---
backport of https://github.com/ceph/ceph/pull/56928
parent tracker: https://tracker.ceph.com/issues/65511
> reef: python-common: handle "anonymous_access: false" in to_json of Grafana spec

- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/services/osd.py
backport tracker: https://tracker.ceph.com/issues/69821
---
backport of https://github.com/ceph/ceph/pull/61593
parent tracker: https://tracker.ceph.com/issues/69734
> reef: mgr/cephadm: create OSD daemon deploy specs through make_daemon_spec

- doc/radosgw/s3/commons.rst
instead of referring to "vhost-style", copy the "path-style" and "virtual-hosted-style" language from https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html
expand the FQDN acronym to avoid potential confusion
"The second method is deprecated by AWS" had incorrectly referred to the vhost-style method - clarify that it refers to path-style access
<details>
- …
> doc/rgw: clarify path-style vs virtual-hosted-style access

- qa/suites/nvmeof/basic/workloads/nvmeof_scalability.yaml
- qa/suites/nvmeof/thrash/workloads/fio.yaml
- qa/workunits/nvmeof/fio_test.sh
- qa/workunits/nvmeof/scalability_test.sh
Results: 
https://pulpito.ceph.com/vallariag-2025-02-13_09:19:48-nvmeof-main-distro-default-smithi/ - the errors are unrelated to the PR. 
scalability test: https://pulpito.ceph.com/vallariag-2025-02-13_07:36:22-nvmeof-main-distro-default-smithi/
TODO: also print more details from host if fio fails:
- "nvme list-subsys /dev/nvme2n2" 
- nvme list from the initiator
- nvme list | wc -l
- `nvme id-ns /dev/nvme1n2` - this will help us map these devices to the nvmeof namespaces created. …
> qa/suite/nvmeof: Add asserts to scalability_test and extra logs in fio_test

- src/ceph-volume/ceph_volume/util/disk.py
backport tracker: https://tracker.ceph.com/issues/69445
---
backport of https://github.com/ceph/ceph/pull/61251
parent tracker: https://tracker.ceph.com/issues/69432
> squid: ceph-volume: fix loop devices support

- qa/workunits/rbd/rbd_mirror.sh
- qa/workunits/rbd/rbd_mirror_helpers.sh
Add a reproducer for the crash on a bad variant access which was fixed in commit 7d75161051da ("librbd: fix a crash in get_rollback_snap_id").
The reproducer deliberately works around many other issues with force promote in snapshot-based mirroring: stopping rbd-mirror daemon shouldn't be necessary (let alone with SIGKILL), get_rollback_snap_id() and its caller can_create_primary_snapshot() are flawed and can pick the wrong snapshot to roll back to or skip rollback when it's actually required, the user snapshot in this scenario should be removed as part of force promoting because it's incomplete and won't be usable after the image is promoted, etc. …
> qa/workunits/rbd: add a test for force promote with a user snapshot

- src/crush/CrushLocation.cc
- src/crush/CrushLocation.h
- src/crush/CrushTester.cc
- src/crush/CrushTreeDumper.h
- src/crush/CrushWrapper.cc
- src/crush/CrushWrapper.h
> crush: include cleanup

- src/perfglue/heap_profiler.cc
> perfglue: add missing include

- qa/cephfs/overrides/pg_health.yaml
Health warning "pg .* is stuck peering" is seen while a Ceph cluster is
under upgrade process. Being an expected warning, it should be added
to the ignorelist.
And besisdes this one, we already ignore more severe warnings ("pg is
stuck inactive" and "pg is degrarded") for fs/upgrade jobs.
Fixes: https://tracker.ceph.com/issues/70023 …
> qa/cephfs: ignore warning that pg is stuck peering for upgrade jobs

- src/msg/Message.cc
- src/msg/Message.h
- src/msg/async/ProtocolV1.cc
- src/msg/async/ProtocolV1.h
- src/msg/async/Stack.cc
- src/msg/async/Stack.h
- src/msg/async/crypto_onwire.cc
- src/msg/async/crypto_onwire.h
- src/msg/async/frames_v2.h
- src/msg/msg_types.h
Another PR split from https://github.com/ceph/ceph/pull/60490; this time the "msg/async" subsystem.
<details>
</details>
> msg/async: include cleanup

- src/crimson/osd/object_context.cc
- src/crimson/osd/object_context.h
- src/crimson/osd/osd.cc
- src/crimson/osd/osd.h
- src/crimson/osd/osd_operation.cc
- src/crimson/osd/osd_operation.h
- src/crimson/osd/scheduler/mclock_scheduler.cc
- src/crimson/osd/scheduler/mclock_scheduler.h
- src/crimson/osd/shard_services.cc
- src/crimson/osd/shard_services.h
This PR is but one of a set. Following
https://github.com/ceph/ceph/pull/61394, all uses of the deprecated interface will be updated, and that old interface will be removed.
> crimson/osd: replace obsolete get_tracked_conf_keys()

- src/rgw/driver/rados/account.cc
- src/rgw/driver/rados/buckets.cc
- src/rgw/driver/rados/cls_fifo_legacy.cc
- src/rgw/driver/rados/config/impl.cc
- src/rgw/driver/rados/groups.cc
- src/rgw/driver/rados/rgw_bucket.cc
- src/rgw/driver/rados/rgw_datalog.cc
- src/rgw/driver/rados/rgw_gc.cc
- src/rgw/driver/rados/rgw_log_backing.cc
- src/rgw/driver/rados/rgw_notify.cc
- src/rgw/driver/rados/rgw_object_expirer_core.cc
- src/rgw/driver/rados/rgw_putobj_processor.cc
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
- src/rgw/driver/rados/rgw_reshard.cc
- src/rgw/driver/rados/rgw_sal_rados.cc
- src/rgw/driver/rados/rgw_sal_rados.h
- src/rgw/driver/rados/rgw_tools.cc
- src/rgw/driver/rados/rgw_tools.h
- src/rgw/driver/rados/roles.cc
- src/rgw/driver/rados/topic.cc
- src/rgw/driver/rados/topics.cc
- src/rgw/driver/rados/users.cc
- src/rgw/radosgw-admin/orphan.cc
- src/rgw/services/svc_cls.cc
- src/rgw/services/svc_notify.cc
- src/rgw/services/svc_sys_obj_core.cc
- src/test/rgw/test_cls_fifo_legacy.cc
- src/test/rgw/test_log_backing.cc
issue was probably there all the time (using the same op object more than once). but was exposed in:
8b3479e2bd70bc036dc0ca527636b71ea233c395
Fixes: https://tracker.ceph.com/issues/69944
<details>
- …
> rgw: be explicit on moving rados op in APIs

- src/rgw/driver/d4n/rgw_sal_d4n.cc
- src/rgw/driver/d4n/rgw_sal_d4n.h
- src/rgw/driver/daos/rgw_sal_daos.cc
- src/rgw/driver/daos/rgw_sal_daos.h
- src/rgw/driver/motr/rgw_sal_motr.cc
- src/rgw/driver/motr/rgw_sal_motr.h
- src/rgw/driver/posix/rgw_sal_posix.cc
- src/rgw/driver/posix/rgw_sal_posix.h
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_sal_rados.cc
- src/rgw/driver/rados/rgw_sal_rados.h
- src/rgw/radosgw-admin/radosgw-admin.cc
- src/rgw/rgw_common.h
- src/rgw/rgw_op.cc
- src/rgw/rgw_sal.h
- src/rgw/rgw_sal_dbstore.cc
- src/rgw/rgw_sal_dbstore.h
- src/rgw/rgw_sal_filter.cc
- src/rgw/rgw_sal_filter.h
The cloud objects (restore/transitioned) are not handled properly for multisite scenarios. We cannot rely on mtime for this usecase for syncing the object across the site. Hence a xattr known as internal_mtime introduce and give weightage during mulitisite
Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com> …
> rgw/cloudrestore: sync cloud restore objects accoridngly

- examples/rgw/boto3/create_bucket_indexless.py
- examples/rgw/boto3/create_bucket_shards.py
- examples/rgw/boto3/service-2.sdk-extras.json
- src/rgw/driver/rados/rgw_bucket.cc
- src/rgw/driver/rados/rgw_bucket.h
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
- src/rgw/driver/rados/rgw_sal_rados.cc
- src/rgw/rgw_op.cc
- src/rgw/rgw_rest_s3.cc
- src/rgw/rgw_sal.h
- src/rgw/services/svc_bi_rados.cc
extend s3's [CreateBucketConfiguration](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html#API_CreateBucket_RequestSyntax) with a custom `BucketIndex` element that can override rgw's default bucket index type and shard count
to create an indexless bucket:
```xml
<CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<BucketIndex>
<Type>Indexless</Type>
</BucketIndex>
</CreateBucketConfiguration>
```
to create a normal pre-sharded bucket:
```xml
<CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<BucketIndex>
<Type>Normal</Type>
<NumShards>1023</NumShards>
</BucketIndex>
</CreateBucketConfiguration>
```
----
this also registers the extension for boto. the following output is from `aws s3api create-bucket help`:
``` …
```
> rgw/s3: CreateBucket extension for layout type and shard count

- qa/standalone/ceph-helpers.sh
- src/erasure-code/jerasure/ErasureCodePluginJerasure.cc
- src/test/erasure-code/TestErasureCodePluginJerasure.cc
This PR will set the default technique for Jerasure to be reed_sol_van if none is specified as per the documentation. This used to work for jerasure because the profile would inherit the options from the osd_pool_default_erasure_code_profile conf file setting which set the default plugin to jerasure, which meant that the erasure code profile was successfully created. When the conf file setting is changed to isal this stops working because it is invalid to create a jerasure profile without specifying a technique.
This PR also makes a small change to the erasure_code_plugin_exists function, this issue highlighted the function does not properly cases where the plugin exists but the command fails for some other reason e.g. missing technique parameter. I have added a special case for this, …
> erasure-code: Set reed_sol_van to be the default technique for Jerasure if none is specified.

- qa/suites/upgrade/reef-x/parallel/0-start.yaml
- qa/suites/upgrade/reef-x/stress-split/1-start.yaml
- qa/suites/upgrade/telemetry-upgrade/reef-x/1-tasks.yaml
- qa/suites/upgrade/telemetry-upgrade/squid-x/1-tasks.yaml
This warning is part of PG_AVAILABILITY, which we already ignore. This is part of the "detail" in the warning, so we need to add an extra bit to the ignorelist when PG_AVAILABILITY isn't explicitly present.
Note: I did not add this to the `quincy-x` upgrade suite since Quincy is EOL and we will be retiring that suite soon.
Fixes: https://tracker.ceph.com/issues/69456 …
> qa/suites/upgrade: ignore when pg is stuck peering

- qa/workunits/rbd/rbd_mirror_bootstrap.sh
- qa/workunits/rbd/rbd_mirror_helpers.sh
- src/librbd/api/Mirror.cc
- src/tools/rbd/action/MirrorImage.cc
- src/tools/rbd/action/MirrorPool.cc
backport tracker: https://tracker.ceph.com/issues/69968
---
backport of https://github.com/ceph/ceph/pull/61768
parent tracker: https://tracker.ceph.com/issues/69911
> reef: librbd: fix mirror image status summary in a namespace

- src/pybind/mgr/dashboard/controllers/nvmeof.py
backport tracker: https://tracker.ceph.com/issues/70131
---
backport of https://github.com/ceph/ceph/pull/61597
parent tracker: https://tracker.ceph.com/issues/70125
> squid: mgr/dashboard: namespace update route robustness

- src/pybind/mgr/dashboard/controllers/nvmeof.py
- src/pybind/mgr/dashboard/model/nvmeof.py
- src/pybind/mgr/dashboard/openapi.yaml
backport tracker: https://tracker.ceph.com/issues/70130
---
backport of https://github.com/ceph/ceph/pull/61545
parent tracker: https://tracker.ceph.com/issues/70126
> squid: mgr/dashboard: Add additional NVME API endpoints

- .github/workflows/retrigger-rtd.yml
> doc: Support to retrigger docs/readthedocs.org:ceph PR build

- doc/radosgw/lua-scripting.rst
- src/rgw/rgw_lua_background.cc
- src/rgw/rgw_lua_background.h
- src/rgw/rgw_lua_utils.cc
- src/rgw/rgw_lua_utils.h
This PR includes two fixes for the Lua background thread in RADOS Gateway:
1. **Reset start time for accurate execution time limit:**  
- Fixed an issue where the execution time limit was incorrectly applied across multiple runs.  
- Introduced `reset_start_time()` in `rgw_lua_utils.h`.  
- Updated `rgw_lua_background.cc` to call `reset_start_time()` before each script execution.  
2. **Ensure background thread updates config changes dynamically:**  
- Added setters/getters for max memory and runtime limits in `lua_state_guard`.  
- Implemented logic to update limits when configuration changes.  
- Apply the new memory limit within the same Lua state when possible; otherwise, reset Lua state with new memory limit.
3. **memory leak check:**  
- Added a memory leak check after Lua cleanup …
> rgw/lua: Fix Lua background thread execution timing and config updates

- src/pybind/mgr/orchestrator/_interface.py
- src/pybind/mgr/orchestrator/module.py
cephadm: orch upgrade status to return output according to the format specified
Fixes: https://tracker.ceph.com/issues/69122
Testing logs:
```
[ceph: root@ceph-node-0 ~]# ceph orch upgrade status
{
"in_progress": false,
"target_image": null,
"services_complete": [],
"which": "<unknown>",
"progress": null,
"message": "",
"is_paused": false
}
[ceph: root@ceph-node-0 ~]# ceph orch upgrade status --format json
{"in_progress": false, "is_paused": false, "message": "", "progress": null, "services_complete": [], "target_image": null, "which": "<unknown>"}
[ceph: root@ceph-node-0 ~]# ceph orch upgrade status --format yaml
in_progress: false
target_image: null
which: <unknown>
services_complete: []
progress: null
message: ''
is_paused: false
```
```
> tox -e py39 -- cephadm     
================= …
```
> cephadm: orch upgrade status to return output according to the format specified

- qa/suites/orch/cephadm/smoke-roleless/2-services/rgw-ingress.yaml
This ~~won't~~ shouldn't make the test pass in and of itself, but it should stop the test from running until it hits the max job timeout and should help see where it's failing …
> qa/cephadm: add timeouts and debug commands to rgw-ingress test

- qa/suites/rgw/bucket-logging/overrides.yaml
- qa/suites/rgw/cloud-transition/overrides.yaml
- qa/suites/rgw/crypt/overrides.yaml
- qa/suites/rgw/lifecycle/overrides.yaml
- qa/suites/rgw/multifs/overrides.yaml
- qa/suites/rgw/sts/overrides.yaml
- qa/suites/rgw/tempest/tasks/s3/s3tests.yaml
- qa/suites/rgw/thrash/workload/rgw_s3tests.yaml
- qa/suites/rgw/website/overrides.yaml
the rgw/verify suite configures accounts for some s3test users. in particular, the [iam root] and [iam alt root] users need to specify an account for use in the iam tests. add accounts to these users in all other subsuites (except dbstore which doesn't support accounts)
Fixes: https://tracker.ceph.com/issues/70077
<details> …
> qa/rgw: configure 'iam root' accounts outside of rgw/verify

- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/tests/test_cephadm.py
- src/pybind/mgr/orchestrator/_interface.py
- src/pybind/mgr/orchestrator/module.py
Adds a pre-check to verify if a daemon can be safely stopped before restarting via orch daemon. Introduces a --force flag to override the check when necessary.
Fixes: [https://tracker.ceph.com/issues/70058](https://tracker.ceph.com/issues/70058)
Example:
```
root@kb-test-1:/# ceph osd ok-to-stop osd.2
{"ok_to_stop":false,"osds":[2],"num_ok_pgs":13,"num_not_ok_pgs":31,"bad_already_inactive":["3.1f"],"bad_become_inactive":["1.0","2.c","2.f","2.14","2.16","2.18","2.19","3.2","3.e","3.f","4.1","4.d","4.1c","4.1d","5.0","5.d","5.11","5.14","5.18","5.1e","5.1f","6.a","6.10","6.15","6.20","6.23","6.25","6.30","6.32","6.3d"],"ok_become_degraded":["2.4","2.8","2.a","2.e","2.10","3.4","3.8","4.f","5.1c","6.2","6.17","6.1a","6.1d"]}
Error EBUSY: unsafe to stop osd(s) at this time (31 PGs are or …
```
> mgr/cephadm: Check if a daemon is ok-to-stop before scheduling a restart

- .github/pull_request_template.md
> Links to Jenkins jobs in PR comment commands / Remove deprecated commands

- qa/tasks/cephfs/test_volumes.py
- src/pybind/mgr/volumes/fs/operations/versions/auth_metadata.py
When combination of subvolume group name and subvolume name is longer
than 248 characters, it leads to a failure because the metadata file is
a combination of both of these along with ":", "_" and ".meta".
Currently, when this comibnation longer than 248 characters, a bunch
stacktraces are printed along with multiple errors. This confuses the
user as well as looks bad.
Fixes: https://tracker.ceph.com/issues/69865
- When filling …
> mgr/vol: print proper message when subvolume metadata filename is too long

- qa/tasks/cephfs/test_admin.py
- src/mon/FSCommands.cc
- src/mon/MDSMonitor.cc
- src/mon/MDSMonitor.h
Fixes: https://tracker.ceph.com/issues/69694
Fixes: https://tracker.ceph.com/issues/69707 …
> cephfs,mon: don't disallow "mds/fs fail" when other MDS/FS has health warning

- src/rgw/rgw_rest_s3.cc
if we send response headers containing full-object checksums, clients will compare them with the returned data and fail with:
> botocore.exceptions.FlexibleChecksumError: Expected checksum 4AAr8A== did not match calculated checksum: WbxXZw==
the only thing [aws docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html#Part-level-checksums) say about Range requests refers to multipart uploads:
> For completed uploads, you can get an individual part's checksum by using the GetObject or HeadObject operations and specifying a part number or byte range that aligns with a single part.
Fixes: https://tracker.ceph.com/issues/69936
<details>
- `jenkins …
> rgw/cksum: GetObject omits checksum headers for Range requests

- doc/rados/operations/placement-groups.rst
Improve the guidance around setting pg_num, and clear up confusion around whether pgp_num should be set manually or, indeed, if it even can be set manually.
This PR was raised in response to Mark Schouten's email here: https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/CBDJTLTTIEZVG7GVZBX37UAWGYNSSMPD/
(cherry picked from commit c43e7337212fe38e8db63d00345fa9858b3cb10a) …
> squid: doc/rados: improve pg_num/pgp_num info

- PendingReleaseNotes
- src/rgw/rgw_op.cc
AWS now allows `PutObjectLockConfiguration` on existing buckets, even if `x-amz-bucket-object-lock-enabled` was not specified on bucket creation: https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-s3-enabling-object-lock-buckets/
object lock still requires the bucket to be versioning-enabled, so such requests are rejected otherwise. if the bucket is versioning-enabled but not object-lock-enabled, enable the `BUCKET_OBJ_LOCK_ENABLED` flag
this logic was moved into `retry_raced_bucket_write()` in case the request races with `PutBucketVersioning`
Fixes: https://tracker.ceph.com/issues/70013
<details> …
> rgw: PutObjectLockConfiguration can enable object lock on existing buckets

- container/build.sh
Optionally, for those that want to run build.sh locally and use the images.  The default is to remove, for Jenkins builders, which will build, push, and rmi.
Fixes: https://tracker.ceph.com/issues/70196 …
> container/build.sh: remove local container images

- src/test/test_not_before_queue.cc
Silencing
```
/mnt/igor/github/salieri11/ceph/src/common/not_before_queue.h:134:18: error: comparison of integer expressions of different signedness: 'const int' and 'const unsigned int' [-Werror=sign-compare]
134 |       return lhs < project_removal_class(rhs.v);
|              ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Fixes: https://tracker.ceph.com/issues/69525
> test/test_not_before_queue: fix Signed-vs-Unsigned warnings

- src/common/not_before_queue.h
- src/osd/scrubber/osd_scrub_sched.cc
- src/test/test_not_before_queue.cc
The OSD's scrub queue uses a specialized container: not_before_queue_t.
The container maintains a cut-off point between "eligible" and "non-eligible" queue entries. In the
case of the scrub queue - the cutoff is based on the "Ceph clock".
The NBQ expects the cutoff updates to be monotonic-increasing. But the clock used by the
scrub queue may, in some rare cases, jump backwards a bit.
This PR modifies the NBQ to tolerate (and ignore) backward updates, and modifies the
scrub queue to log such failures to update the cutoff point.
Fixes: https://tracker.ceph.com/issues/70055
> osd/scrub: tolerate non-monotonic scrub queue cutoff updates

- doc/radosgw/dynamicresharding.rst
- src/rgw/driver/rados/rgw_bucket.cc
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
- src/rgw/driver/rados/rgw_reshard.cc
- src/rgw/driver/rados/rgw_reshard.h
- src/rgw/radosgw-admin/radosgw-admin.cc
- src/rgw/rgw_bucket_layout.cc
- src/rgw/rgw_bucket_layout.h
- src/rgw/rgw_common.h
- src/rgw/rgw_sal.h
- src/test/cli/radosgw-admin/help.t
- src/test/rgw/test_rgw_reshard.cc
Dynamic resharding can now reduce the number of shards. The code currently has a hard-coded value of 11 as the minimum number of shards dynamic resharding can reshard to. There may be cases where the user wants to set an alternate minimum, such as when they have a sense of how many objects the bucket will eventually hold.
This PR builds off of https://github.com/ceph/ceph/pull/61269 .
That PR allows the user to specify an initial number of shards during bucket creation. This PR then takes that number to be the minimum and saves it in the layout field of the bucket instance object (RGWBucketInfo).
When dynamic resharding is triggered, it will use that stored value as a minimum number of shards for resharing.
Fixes: https://tracker.ceph.com/issues/69464 …
> rgw: allow per-bucket minimum number of shards

- doc/rados/operations/stretch-mode.rst
doc/rados/operations: Clarify stretch mode vs device class
Clarify device classes themselves are compatible with stretch mode, but that CRUSH rules that specify one are not, because all OSDs have a device class in recent releases.  This is informed by conversation with @gregsfortytwo and @likid0 . …
> doc/rados/operations: Clarify stretch mode vs device class

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
NOTE:
===
Considering only single selection would be there for buckets with this https://github.com/ceph/ceph/pull/61961, so multiselection flows should be ignored while testing this PR
backport tracker: https://tracker.ceph.com/issues/70122
backport of: https://github.com/ceph/ceph/pull/61899
parent tracker: https://tracker.ceph.com/issues/70078
<hr  style="2px solid #eeeeee"/>
Fixes: https://tracker.ceph.com/issues/70078
(cherry picked from commit 11677c29ee6ee60d9191edfdbfbe37b5308eb45e)
Conflicts:
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.ts
https://github.com/user-attachments/assets/8e21352b-4af3-4f80-ba12-dc78c6a99cf3 …
> reef: mgr/dashboard: disable deleting bucket with objects

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
NOTE:
===
Considering only single selection would be there for buckets with this https://github.com/ceph/ceph/pull/61961, so multiselection flows should be ignored while testing this PR
backport tracker: https://tracker.ceph.com/issues/70121
backport of: https://github.com/ceph/ceph/pull/61899
parent tracker: https://tracker.ceph.com/issues/70078
<hr style="2px solid #eeeeee"/>
Fixes: https://tracker.ceph.com/issues/70078
(cherry picked from commit 11677c29ee6ee60d9191edfdbfbe37b5308eb45e)
Conflicts:
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.ts
https://github.com/user-attachments/assets/39ff2c89-70ad-4004-94ca-6aad0b2c7895 …
> squid: mgr/dashboard: disable deleting bucket with objects

- src/common/options/crimson.yaml.in
- src/crimson/osd/main_config_bootstrap_helpers.cc
Implement a new mechanism to introduce a new seastar parameter in future and add options to configure parameters like task_quota_ms, io_latency_goal_ms and idle_poll_time_us.
Fixes: https://tracker.ceph.com/issues/69595 …
> crimson: Provide an options to configure several seastar parameters

- src/pybind/mgr/cephadm/module.py
This was incorrectly handled as part of
https://github.com/ceph/ceph/commit/85d2633310c3a66415358a9872732473ac34d345 which intended to block having multiple nvmeof services with the same group, but forgot to verify the spec being applied wasn't just an update on a previously applied service …
> mgr/cephadm: don't block matching group for identical nvmeof services

- qa/suites/rgw/verify/tasks/rados-pool-quota.yaml
- qa/workunits/rgw/run-rados-pool-quota.sh
- qa/workunits/rgw/test_rgw_rados_pool_quota.py
- src/rgw/driver/rados/rgw_gc.cc
- src/rgw/driver/rados/rgw_rados.cc
adds the `librados::OPERATION_FULL_TRY` flag via `IoCtx::set_pool_full_try()` to object delete operations so that Objecter sends them even if the rados pool has reached its quota. this covers both the initial head object deletion and the deletion/garbage collection of tail objects
Fixes: https://tracker.ceph.com/issues/69723
<details>
- `jenkins …
> rgw/rados: enable object deletion at rados pool quota

- src/test/rgw/bucket_notification/test_bn.py
backport tracker: https://tracker.ceph.com/issues/63630
---
backport of https://github.com/ceph/ceph/pull/54637
parent tracker: https://tracker.ceph.com/issues/62136
> reef: rgw/test/kafka: let consumer read events from the beginning

- src/tools/rbd_mirror/ImageReplayer.cc
backport tracker: https://tracker.ceph.com/issues/69983
---
backport of https://github.com/ceph/ceph/pull/61835
parent tracker: https://tracker.ceph.com/issues/69978
> reef: rbd-mirror: fix possible recursive lock of ImageReplayer::m_lock

- src/rgw/rgw_rest_s3.cc
The S3 ReplicationConfiguration's destination bucket must be treated as an ARN, per the AWS S3 documentation:
https://docs.aws.amazon.com/AmazonS3/latest/API/API_Destination.html#AmazonS3-Type-Destination-Bucket
Fixes: https://tracker.ceph.com/issues/69568
> rgw: handle destination bucket as an ARN in ReplicationConfiguration

- qa/workunits/rbd/rbd_mirror_helpers.sh
- qa/workunits/rbd/rbd_mirror_journal.sh
- qa/workunits/rbd/rbd_mirror_snapshot.sh
- src/librbd/mirror/snapshot/Utils.cc
backport tracker: https://tracker.ceph.com/issues/70098
---
backport of https://github.com/ceph/ceph/pull/61906 and https://github.com/ceph/ceph/pull/61955
parent tracker: https://tracker.ceph.com/issues/70075
> reef: librbd: fix a crash in get_rollback_snap_id

- src/rgw/rgw_rest_sts.cc
backport tracker: https://tracker.ceph.com/issues/69257
---
backport of https://github.com/ceph/ceph/pull/60624
parent tracker: https://tracker.ceph.com/issues/68836
> reef: rgw/sts: fix to disallow unsupported JWT algorithms

- src/common/options/global.yaml.in
backport tracker: https://tracker.ceph.com/issues/67605
---
backport of https://github.com/ceph/ceph/pull/57120
parent tracker: https://tracker.ceph.com/issues/65678
> squid: os/bluestore: allow use BtreeAllocator 

- qa/tasks/barbican.py
backport tracker: https://tracker.ceph.com/issues/67620
---
backport of https://github.com/ceph/ceph/pull/59241
parent tracker: https://tracker.ceph.com/issues/67444
> squid: qa: barbican: restrict python packages with upper-constraints

- qa/cephfs/conf/mon.yaml
- qa/tasks/mgr/dashboard/test_health.py
- src/common/options/mon.yaml.in
- src/mon/HealthMonitor.cc
- src/mon/Monitor.cc
- src/mon/Monitor.h
backport tracker: https://tracker.ceph.com/issues/65082
---
backport of https://github.com/ceph/ceph/pull/56271
parent tracker: https://tracker.ceph.com/issues/64968
> reef: mon: do not log MON_DOWN if monitor uptime is less than threshold

- src/os/bluestore/BlueRocksEnv.h
backport tracker: https://tracker.ceph.com/issues/68734
---
backport of https://github.com/ceph/ceph/pull/58334
parent tracker: https://tracker.ceph.com/issues/66717
> squid: os/bluestore: Fix BlueRocksEnv attempts to use POSIX

- qa/standalone/osd/osd-bluefs-volume-ops.sh
- src/os/bluestore/BlueStore.cc
When expansion crosses potential location of multi bdev label, we need to initialize the new label.
Expanded and fixed testing.
Improved dout on bdev label decoding failure.
This is backport of #60363
Fixes:
https://tracker.ceph.com/issues/69829 …
> squid: os/bluestore: Create additional bdev labels when expanding block device.

- doc/cephadm/services/osd.rst
s/This means that the exact device size is 3.64 * 1000, or 3640GB"/This means that the exact device size is 3.64TB, or 3640 GB"/
In the original text, the number "3.64" appears to refer to a quantity (and indeed, it is a quantity of Terabytes), but it is unlabeled. Also, on repeated recent readings of this sentence I found it more puzzling than enlightening. So I made this commit.
(cherry picked from commit d9e96c44f63e1ef81248c74e5b126316e99eff6f) …
> squid: doc/cephadm: simplify confusing math proposition

- doc/cephadm/services/osd.rst
s/This means that the exact device size is 3.64 * 1000, or 3640GB"/This means that the exact device size is 3.64TB, or 3640 GB"/
In the original text, the number "3.64" appears to refer to a quantity (and indeed, it is a quantity of Terabytes), but it is unlabeled. Also, on repeated recent readings of this sentence I found it more puzzling than enlightening. So I made this commit.
(cherry picked from commit d9e96c44f63e1ef81248c74e5b126316e99eff6f) …
> reef: doc/cephadm: simplify confusing math proposition

- qa/workunits/dencoder/test_readable.py
backport tracker: https://tracker.ceph.com/issues/69165
---
backport of https://github.com/ceph/ceph/pull/58961
parent tracker: https://tracker.ceph.com/issues/67263
> squid: workunit/dencoder: dencoder test forward incompat fix

- qa/tasks/cephfs/test_mirroring.py
Caused by https://github.com/ceph/ceph/pull/59875.
100MB files would take less than a second to sync, which makes no difference
in 'last_synced_end' and the test fails intermittently. We need to increase the
size of the files, as the time/duration is determined only in seconds.
Because of this, it also needs more sleep time before checking the status.
Fixes: https://tracker.ceph.com/issues/69232 …
> qa: fix test_cephfs_mirror_stats failure

- qa/suites/fs/upgrade/mds_upgrade_sequence/tasks/6-verify.yaml
After upgrading from a prior release to squid, we see the following warning in the cluster log if we do not set `require-osd-release=squid`:
[WRN] OSD_UPGRADE_FINISHED: all OSDs are running squid or later but require_osd_release < squid
Fixes: https://tracker.ceph.com/issues/69098 …
> qa/suites/fs/upgrade/mds_upgrade_sequence/tasks: set require-osd-release

- src/tools/cephfs_mirror/PeerReplayer.cc
> cephfs_mirror: do not log the previous error

- qa/tasks/s3tests.py
- src/rgw/radosgw-admin/radosgw-admin.cc
- src/rgw/rgw_account.cc
- src/rgw/rgw_account.h
the if condition was backwards, preventing non-keystone users from being removed after the s3tests task runs
with the addition of user accounts for squid, any created buckets were no longer cleaned up by `user rm --purge-data` because the buckets are owned by the account instead. this caused the `account rm` command to fail with:
> The account cannot be deleted until all buckets are removed.
added a `account rm --purge-data` to handle this cleanup for account buckets
Fixes: https://tracker.ceph.com/issues/69741
<details> …
> qa/rgw: fix user cleanup in s3tests task

- doc/man/8/ceph-bluestore-tool.rst
- src/os/bluestore/BlueFS.cc
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/os/bluestore/bluestore_tool.cc
- src/test/objectstore/store_test.cc
Adds printing label locations in show-label cmd output.
Adds "show-label-at" command.
Fixes crashing fsck on "incompletely" expanded device.
Fixes: https://tracker.ceph.com/issues/67966
Fixes: https://tracker.ceph.com/issues/69981
Fixes: https://tracker.ceph.com/issues/69997
Fixes: https://tracker.ceph.com/issues/69999 …
> os/bluestore: fix bdev expansion and more

- src/librbd/api/Mirror.cc
With Mirror::image_disable() taking image_lock for write and calling list_children() under it, the following deadlock is possible:
1. Mirror::image_disable() takes image_lock for write and calls list_children()
2. AbstractWriteLog::periodic_stats() timer fires (it runs every 5 seconds) and ImageCacheState::write_image_cache_state() is called under a global timer_lock
3. ImageCacheState::write_image_cache_state() successfully takes owner_lock and blocks attempting to take image_lock for read because it's already held for write by Mirror::image_disable()
4. list_children() blocks inside of a call to ImageState::close() on a descendant image
5. The descendant image close can't proceed because TokenBucketThrottle requires a global timer_lock to complete QosImageDispatch shutdown
6. safe_timer …
> librbd: fix a deadlock on image_lock caused by Mirror::image_disable()

- src/include/rbd/librbd.h
- src/include/rbd/librbd.hpp
- src/librbd/api/DiffIterate.cc
- src/librbd/api/DiffIterate.h
- src/librbd/api/Trash.cc
- src/librbd/librbd.cc
- src/pybind/rbd/c_rbd.pxd
- src/pybind/rbd/mock_rbd.pxi
- src/pybind/rbd/rbd.pyx
- src/test/librbd/test_internal.cc
- src/test/pybind/test_rbd.py
Allow a diff to start from a non-user snapshot.  This would be used by "rbd du" command to account for non-user snapshots which are currently just skipped potentially resulting in underreported space usage and in other places.
Fixes: https://tracker.ceph.com/issues/65720 …
> librbd: add rbd_diff_iterate3() API to take source snapshot by ID

- qa/suites/orch/cephadm/smb/tasks/deploy_smb_ctdb_node_gone_state.yaml
- src/pybind/mgr/cephadm/services/smb.py
**Problem Statement:**
Old SMB service ranks must be fenced to update the rank map with the correct node states  in the cluster. Without this update, the rank map may contain stale or incorrect states. Nodes in the GONE state should be marked as such and excluded from the cluster, consistent with the behavior implemented in [sambacc#143](https://github.com/samba-in-kubernetes/sambacc/pull/143).
**Solution:** 
- Added functionality to fence old SMB service ranks.
- Updated the rank map to transition outdated ranks to the GONE state.
- Ensured that the rank map accurately reflects the current state of nodes in the cluster.
Fixes: https://tracker.ceph.com/issues/68512 …
> cephadm: fence old ranks for SMB service

- qa/tasks/s3tests.py
partial backport of 2390788b89037bf5121adf4251b980dc20a8f269 did not include a nearby change from ff81a31ad678472e6847ad39f57e14efd89b0ead
Fixes: https://tracker.ceph.com/issues/70152
<details> …
> reef: qa/rgw: avoid 'user rm' of keystone users

- src/rgw/rgw_rest_account.cc
radosgw-admin commands accept negative values for the quota limits to mean unlimited, but the corresponding admin apis were parsing the values as uint32_t
Fixes: https://tracker.ceph.com/issues/70084
<details>
</details>
> rgw: /admin/account APIs accept negative values

- src/rgw/radosgw-admin/radosgw-admin.cc
the thread pool controlled by rgw_thread_pool_size was added to radosgw-admin for squid, but the default value of 512 wastes a lot of time starting/stopping threads. change the default value to 8 for radosgw-admin commands only
<details>
</details>
> radosgw-admin: lower default thread pool size

- src/rgw/rgw_appmain.cc
- src/rgw/rgw_lib.cc
- src/rgw/rgw_main.h
- src/rgw/rgw_process.cc
- src/rgw/rgw_process_env.h
Fixes: https://tracker.ceph.com/issues/70104
This was regression due to this [commit](https://github.com/ceph/ceph/commit/dc262061fed890f1c69a5569b040cddbbeb8c741), which moved the frontend destruction at bottom without moving the other destructions that need to happen after frontend is stopped.
Ensure the olog member variable is destructed at last, once all the frontends have stopped accepting new connections and have finished processing the existing connections.  Hence convert the olog from raw pointer to unique_ptr, so its destructed last.
Currently there were 2 olog ptr maintained, 1 inside the `AppMain` class and other inside the `RGWProcessEnv` class and both pointer pointed at same object and only `env.olog` was used in the code. So remove the olog from the AppMain class and use …
> rgw/log: Fix crash during shutdown with ops-log enable.

- src/rgw/driver/rados/rgw_pubsub_push.cc
- src/rgw/rgw_http_client.cc
- src/rgw/rgw_http_client.h
this fix ensures clients gracefully time out when the endpoint url is wrongly configured.
Fixes: https://tracker.ceph.com/issues/51855
Signed-off-by: Adarsh Ashokan <dev.9401adarsh@gmail.com>
<details>
- …
> rgw: add parameter for clients to time out incase they hit wrong url

- src/cls/rgw/cls_rgw_client.cc
- src/cls/rgw/cls_rgw_client.h
- src/cls/rgw/cls_rgw_ops.cc
- src/cls/rgw/cls_rgw_ops.h
- src/rgw/driver/rados/rgw_rados.cc
- src/rgw/driver/rados/rgw_rados.h
- src/test/cls_rgw/test_cls_rgw.cc
- src/test/cls_rgw/test_cls_rgw_stats.cc
The log_op information is not utilized by rgw_cls_obj_prepare_op, so it has been removed to clean up the code.
> rgw: remove unused log op info from prepare_op

- src/blk/kernel/KernelDevice.cc
Sometimes devices can be 0-sized, where I/O is impossible.
This change skips _aio_start() in open() if the device size is 0. This avoids unnecessary AIO setup.
This issue was introduced in PR : https://github.com/ceph/ceph/pull/60791 …
> blk/kernel : skip AIO thread for zero-sized devices

- src/librados/RadosClient.cc
- src/librados/RadosClient.h
- src/msg/compressor_registry.cc
- src/msg/compressor_registry.h
- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
_keys().
Following https://github.com/ceph/ceph/pull/61394,
all uses of the deprecated interface will be updated,
and that old interface will be removed.
> bluestore, librados, msg: replace obsolete get_tracked_conf_keys()

- src/common/StackStringStream.h
backport tracker: https://tracker.ceph.com/issues/65869
---
backport of https://github.com/ceph/ceph/pull/56810
parent tracker: https://tracker.ceph.com/issues/65805
> squid: common/StackStringStream: update pointer to newly allocated memory in overflow()

- src/crush/CrushWrapper.h
backport tracker: https://tracker.ceph.com/issues/70112
---
backport of https://github.com/ceph/ceph/pull/56428
- …
> squid: crush: use std::vector instead of variable length arrays

- src/common/io_exerciser/DataGenerator.cc
- src/common/io_exerciser/DataGenerator.h
- src/common/io_exerciser/EcIoSequence.cc
- src/common/io_exerciser/IoOp.cc
- src/common/io_exerciser/IoOp.h
- src/common/io_exerciser/IoSequence.cc
- src/common/io_exerciser/IoSequence.h
- src/common/io_exerciser/ObjectModel.cc
- src/common/io_exerciser/OpType.h
- src/common/io_exerciser/RadosIo.cc
- src/test/osd/ceph_test_rados_io_sequence.cc
- src/test/osd/ceph_test_rados_io_sequence.h
Reviewer NOTES:
None of these sequences will run in teuthology YET, so there is a low risk to these changes either breaking production or infrastructure. 
This change adds some new sequences to test erasure coding:
1. Appends - specific and awkward appends to objects. Including writing off the end of object to make them large, overlapping, writes. 
2. Truncates - reduce the size of an object. Sequences associated with this which are awkward for EC pools. 
3. Write-object-filling-gap sequence (14) - this sequence creates an object with a hole in it, then fills the hole afterwards.  …
> test: Add new sequences to the IO sequencer. 

- qa/tasks/cephadm.conf
https://tracker.ceph.com/issues/64470
> reef: qa/tasks/cephadm: enable mon_cluster_log_to_file

- qa/suites/upgrade/quincy-x/parallel/0-start.yaml
- qa/suites/upgrade/quincy-x/parallel/1-tasks.yaml
- qa/suites/upgrade/quincy-x/stress-split/1-start.yaml
- qa/suites/upgrade/reef-x/parallel/0-start.yaml
- qa/suites/upgrade/reef-x/parallel/1-tasks.yaml
- qa/suites/upgrade/reef-x/parallel/overrides/ignorelist_health.yaml
- qa/suites/upgrade/reef-x/stress-split/1-start.yaml
- qa/suites/upgrade/reef-x/stress-split/overrides/ignorelist_health.yaml
backport tracker: https://tracker.ceph.com/issues/69496
---
backport of https://github.com/ceph/ceph/pull/59045 and https://github.com/ceph/ceph/pull/60969
parent tracker: https://tracker.ceph.com/issues/69135
> squid: qa/suites/upgrade/reef-x: sync log-ignorelist with quincy-x

- qa/tasks/thrashosds-health.yaml
This yaml file is used in rados/thrash-old-clients. In this commit, I added some pattern matching for
warnings that show up in the cluster log detail that are related to degraded PGs. In these tests, we are intentionally marking down or killing OSDs, which leads to these states showing up in the cluster log. So, the warnings are intended and can be ignored in the context of OSD thrashing.
This directly aligns the squid ignorelist with main's, rather than just a direct backport of
https://github.com/ceph/ceph/pull/61723/commits/ec50fc720c4fc0bdd3165d0014f19c36e9819012.
Fixes: https://tracker.ceph.com/issues/69962 …
> squid: qa/tasks: improve ignorelist for thrashing OSDs

- src/rgw/rgw_op.cc
from https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html#mpuAndPermissions:
> You must be allowed to perform the s3:PutObject action on an object to create a multipart upload request.
but it was calling the verify_bucket_permission() overload which defaulted to the bucket ARN. pass the object ARN instead, like we do for RGWPutObj and RGWCompleteMultipart
Fixes: https://tracker.ceph.com/issues/70191
<details>
- …
> rgw: use object ARN for InitMultipart permissions

- monitoring/ceph-mixin/prometheus_alerts.libsonnet
- monitoring/ceph-mixin/prometheus_alerts.yml
Alert is not triggered as expected, change the query to fix that.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2282348 …
> monitoring: fix NVMeoFSubsystemNamespaceLimit

- src/ceph-volume/ceph_volume/api/lvm.py
- src/ceph-volume/ceph_volume/tests/api/test_lvm.py
- src/ceph-volume/ceph_volume/tests/util/test_device.py
This pull request brings several refactors and improvements to `ceph-volume` to simplify error handling, reduce code duplication, and improve maintainability:
1. **Refactor `_format_tag_args` in `Volume`**  
- Modifies the implementation of `api.lvm.Volume._format_tag_args`.  
- Replaces the old approach using `list(sump(zip(repeat(op), tag_args), ()))` with a more explicit loop-based implementation, improving readability.
2. **Introduction of the `Lvm` base class**  
- Add a new `Lvm` base class to unify and simplify the handling of LVM-related objects (`PVolume`, `VolumeGroup`, and `Volume`).  
- Centralizes common attributes like `name`, `tags`, `path`, and `binary_change` in `Lvm`.  
- Move `clear_tags`, `clear_tag`, `set_tag`, and `set_tags` methods into `Lvm`, reducing code …
> ceph-volume: Refactor LVM object handling

- src/crimson/osd/osd_operation.cc
The background recovery is not showing any progress for crimson when crimson_osd_scheduler_concurrency is set more than 0. After read the source code it seems the recovery was not showing any progress because initially the queue is empty it was waiting for a future that eventually available after call wake() so call a wake() operation while a queue is empty before enqueue an entry to avoid a circuler dependency issue.
Fixes: https://tracker.ceph.com/issues/69788
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backport …
> crimson: Trigger a wake operation via acquire_throttle 

- src/crimson/mgr/client.cc
- src/crimson/mgr/client.h
Client::reconnect nullifies the connection used by the mgr client
before setting a new one.
In this time, we might re-use the nullptr connection due to tasks
that are being run in the background (See: dispatch_in_background).
To avoid this, we had multiple `if (!conn)` checks, some methods
even checked this condition twice to reduce the possibilty of using
undefined the connection.
Instead of introducing an additional check in Client::_send_report,
Introduce Client::send which would be responsible for:
a) Veryfing the connection is set
b) Trying to get a shared access to conn_lock
Client::reconnect will lock conn_lock exclusivly until the
connection is set. If we send is called while reconnecting,
sending will be dropped - same as before.
Fixes: https://tracker.ceph.com/issues/70179
- To …
> crimson/mgr/client: fix _send_report empty conn usage

- src/pybind/cephfs/c_cephfs.pxd
- src/pybind/cephfs/cephfs.pyx
For some newer versions of cython, it appears it tries to choose noexcept by default. …
> pybind/cephfs: use legacy noexcept for cdefs for cython 3.Y.Z

- src/crimson/CMakeLists.txt
This was used to fix issue (https://github.com/boostorg/asio/issues/312) with gcc10 and clang.
Should not be relevant anymore as we require for gcc13 (and clang 16 in the future).
Partially reverts: b556e42e20b13f76a6878b5bd2ade19b886d16e9 …
> crimson/CMakeLists: cleanup BOOST_ASIO_DISABLE_CONCEPTS

- qa/tasks/thrashosds-health.yaml
Fixes: https://tracker.ceph.com/issues/65450
rados/thrash-old-clients tests are failing due to PG_BACKFILL error. The low space error hindering backfill error is a expected transitory state which resolves by itself when the PGs are migrated out of the OSD during the test runs, freeing up the needed space.
Yet, teuthology seems to pick up these PG_BACKFILL errors and error out the test. The solution is to add these expected errors into the ignore list. …
> qa/tasks/thrashosds-health: whitelist PG_BACKFILL_FULL

- src/mon/LogMonitor.cc
On streach mod clusters we can see slow ops when
removing and adding osds with --zap --force when osds connected to peon monitor and forwarding the MLog to leader. the no_reply is set only when we are connected to the leader, this fix will add also the other option - so no_reply set anyway.
Fixes: https://tracker.ceph.com/issues/54489 …
> LogMonitor: set no_reply for forward MLog commands

- src/librbd/api/Mirror.cc
backport tracker: https://tracker.ceph.com/issues/70302
---
backport of https://github.com/ceph/ceph/pull/62072
parent tracker: https://tracker.ceph.com/issues/70190
> reef: librbd: fix a deadlock on image_lock caused by Mirror::image_disable()

- src/blk/kernel/KernelDevice.cc
Fixes: https://tracker.ceph.com/issues/70335 …
> blk/kerneldevice: count ops not bytes in discard_op perf counter

- container/build.sh
backport tracker: https://tracker.ceph.com/issues/70241
---
backport of https://github.com/ceph/ceph/pull/62021
parent tracker: https://tracker.ceph.com/issues/70196
> reef: container/build.sh: remove local container images

- src/mon/Monitor.cc
- src/mon/NVMeofGwMon.h
In "ceph status" command output, show gateway
group names and gateway names.
Before:
```
services:
mon:    4 daemons, quorum ceph-nvme-vm8,ceph-nvme-vm1,ceph-nvme-vm7,ceph-nvme-vm6 (age 71m)
mgr:    ceph-nvme-vm8.tgytdq(active, since 73m), standbys: ceph-nvme-vm6.tequqo, ceph-nvme-vm1.pxrofr, ceph-nvme-vm7.lbxrea
osd:    4 osds: 4 up (since 70m), 4 in (since 70m)
nvmeof: 4 gateways active (4 hosts)
```
After:
```
services:
mon:                      4 daemons, quorum ceph-nvme-vm31,ceph-nvme-vm28,ceph-nvme-vm30,ceph-nvme-vm29 (age 16m)
mgr:                      ceph-nvme-vm31.wnfclf(active, since 18m), standbys: ceph-nvme-vm29.iuwqin, ceph-nvme-vm28.lnnyui, ceph-nvme-vm30.fitwnw
osd:                      4 osds: 4 up (since 14m), 4 in (since 15m)
nvmeof (mypool.mygroup1): 2 gateways: 1 …
```
> mon: Add nvmeof group/gateway name in  "ceph -s"

- container/build.sh
backport tracker: https://tracker.ceph.com/issues/70242
---
backport of https://github.com/ceph/ceph/pull/62021
parent tracker: https://tracker.ceph.com/issues/70196
> squid: container/build.sh: remove local container images

- src/ceph-volume/ceph_volume/devices/lvm/zap.py
- src/ceph-volume/ceph_volume/tests/devices/test_zap.py
ceph-volume refuses to zap a device if it is a partition on a multipath device due to an overly strict condition. This change ensures that only full mapper devices (excluding partitions) are blocked from being zapped, allowing partitions on multipath devices to be processed correctly.
Fixes: https://tracker.ceph.com/issues/70363
> ceph-volume: allow zapping partitions on multipath devices

- src/test/librados_test_stub/TestRadosClient.cc
- src/test/librados_test_stub/TestRadosClient.h
- src/test/msgr/test_async_networkstack.cc
Following https://github.com/ceph/ceph/pull/61394, all uses of the deprecated interface
will be updated, and that old interface will be removed.
> tests: replace obsolete get_tracked_conf_keys()

- src/auth/AuthRegistry.cc
- src/auth/AuthRegistry.h
- src/client/Client.cc
- src/client/Client.h
- src/mgr/DaemonServer.cc
- src/mgr/DaemonServer.h
- src/mgr/MgrStandby.cc
- src/mgr/MgrStandby.h
- src/mon/LogMonitor.cc
- src/mon/LogMonitor.h
- src/mon/Monitor.cc
- src/mon/Monitor.h
- src/mon/NVMeofGwMon.cc
- src/mon/NVMeofGwMon.h
- src/mon/OSDMonitor.cc
- src/mon/OSDMonitor.h
This PR is but one of a set. Following
https://github.com/ceph/ceph/pull/61394, all uses of
the deprecated interface will be updated, and that
old interface will be removed.
> mon,mgr,auth,client: replace obsolete get_tracked_conf_keys()

- src/common/bitset_set.h
- src/common/mini_flat_map.h
- src/test/common/CMakeLists.txt
- src/test/common/test_bitset_set.cc
- src/test/common/test_mini_flat_map.cc
For optimised EC, we are adding more complex algorithms to generate smaller reads and writes.  For most IO, this is faster, but certain IO patterns (for example, full-stripe appends), there are no optimisations possible and as such, the more complex algorithms are actually slowing down the code. 
Our performance measurements showed that this was around a 10% drop in IOPs for a 16k sequential write append pattern on a 4+2/ 4k chunk size EC.  Analysis of profiling showed that the bottle neck is a combination of CPU time and amount of time spent processing maps and sets. 
To address this, we are optimising many areas of code, but one part is to improve the data structures being used by the new EC code and the new data structures are being generically introduced by this PR. 
Essentially EC …
> common: Introduce efficient map and set structure useful for EC.

- src/dokan/utils.cc
`Int32x32To64` macro internally truncates the arguments to int32, while `time_t` is 64-bit on most/all modern platforms. Therefore, usage of this macro creates a Year 2038 bug.
I detailed this issue a while ago in a writeup, and spotted the same issue in this repository when updating the list of affected repositories:
<https://cookieplmonster.github.io/2022/02/17/year-2038-problem/>
> dokan: fix a Y2038 bug by replacing `Int32x32To64` with multiplication

- src/crimson/osd/ec_backend.cc
- src/crimson/osd/osd_operations/client_request.h
- src/crimson/osd/pg.cc
- src/crimson/osd/pg.h
- src/crimson/osd/pg_backend.h
- src/crimson/osd/replicated_backend.cc
- src/crimson/osd/replicated_backend.h
Instead of updating last complete on disk and calling complete_write
in PG::submit_transacion (chained to all_completed).
Move the completion handling earlier as soon as all the peers acked.
This essentially means that we move the handling to
ReplicatedBackend::get_rep_op_reply, unless replication size is 1 -
then we would mark completion in ReplicatedBackend::submit_transaction.
Fixes: https://tracker.ceph.com/issues/69439
Rework of: https://github.com/ceph/ceph/pull/61381
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatc …
> crimson: Handle peer replies handling once received 

- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/test/objectstore/test_deferred.cc
Replicates deferred overwrite corruptions.
This is related to https://tracker.ceph.com/issues/68060 .
The procedure to reliably corrupt is somehow extensive and required:
- introduction of trace points to BlueStore
- ability to dynamically register new allocator
It should be decided whether we want to merge this work, or just use it for verifying correctness of a bugfix. …
> os/bluestore: Unittest for deferred overwrite

- src/client/Client.cc
- src/test/libcephfs/suidsgid.cc
An unprivileged user can `chmod 777` a directory owned by root and gain access. Fix this bug and also add a test case for the same. …
> reef: client: disallow unprivileged users to escalate root privileges

- PendingReleaseNotes
- qa/workunits/rbd/rbd-nbd.sh
- src/test/librbd/fsx.cc
- src/tools/rbd_nbd/rbd-nbd.cc
backport tracker: https://tracker.ceph.com/issues/70364
---
backport of https://github.com/ceph/ceph/pull/55234
parent tracker: https://tracker.ceph.com/issues/64063
> reef: rbd-nbd: use netlink interface by default

- src/crimson/osd/ops_executer.cc
- src/crimson/osd/osd_operations/client_request.cc
- src/crimson/osd/osd_operations/replicated_request.cc
- src/test/crimson/test_interruptible_future.cc
Now that we require for clang16/gcc13 for Crimson we can cleanup the workarounds used.
See: https://tracker.ceph.com/issues/64375
https://github.com/ceph/ceph/pull/61376
https://github.com/ceph/ceph/pull/61740 …
> crimson: revert coroutine workarounds 

- src/pybind/mgr/cephadm/services/cephadmservice.py
- src/pybind/mgr/cephadm/tests/test_services.py
mgr/cephadm: Open port 4721 while deployling cephadm agent
Fixes: https://tracker.ceph.com/issues/70060
Testing logs:
```
[ceph: root@ceph-node-0 /]# ceph config set mgr mgr/cephadm/use_agent true
[ceph: root@ceph-node-0 /]#
[root@ceph-node-1 ~]# firewall-cmd --list-ports
4721/tcp
[root@ceph-node-1 ~]# exit
logout
shwetabhosale:ceph-cluster-setup$ kcli ssh -u root ceph-node-0
Last login: Wed Feb 19 07:18:35 2025 from 192.168.100.1
[root@ceph-node-0 ~]# firewall-cmd --list-ports
4721/tcp
[root@ceph-node-0 ~]# 
``` …
> mgr/cephadm: Open port 4721 while deployling cephadm agent

- src/librbd/api/Mirror.cc
backport tracker: https://tracker.ceph.com/issues/70301
---
backport of https://github.com/ceph/ceph/pull/62072
parent tracker: https://tracker.ceph.com/issues/70190
> squid: librbd: fix a deadlock on image_lock caused by Mirror::image_disable()

- qa/workunits/rbd/rbd_mirror.sh
- qa/workunits/rbd/rbd_mirror_helpers.sh
- src/librbd/mirror/snapshot/Utils.cc
backport tracker: https://tracker.ceph.com/issues/70096
---
backport of https://github.com/ceph/ceph/pull/61906 and https://github.com/ceph/ceph/pull/61955
parent tracker: https://tracker.ceph.com/issues/70075
> squid: librbd: fix a crash in get_rollback_snap_id

- src/tools/rbd_mirror/ImageReplayer.cc
backport tracker: https://tracker.ceph.com/issues/69982
---
backport of https://github.com/ceph/ceph/pull/61835
parent tracker: https://tracker.ceph.com/issues/69978
> squid: rbd-mirror: fix possible recursive lock of ImageReplayer::m_lock

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-details/rbd-details.component.ts
backport tracker: https://tracker.ceph.com/issues/67935
---
backport of https://github.com/ceph/ceph/pull/59575
parent tracker: https://tracker.ceph.com/issues/67849
> squid: mgr/dashboard: Fix variable capitalization in embedded rbd-details panel  

- src/mds/Server.cc
- src/test/libcephfs/snapdiff.cc
> mds: include deleted file dentry in snapdiff readdir result 

- src/test/objectstore/CMakeLists.txt
- src/test/objectstore/run_test_deferred.sh
There is no value in invoking unittest_deferred expect via run_test_deferred.sh script.
Fixes: https://tracker.ceph.com/issues/68718 …
> os/bluestore: Disable invoking unittest_deferred

- src/os/bluestore/Writer.cc
- src/os/bluestore/Writer.h
- src/os/bluestore/bluestore_types.h
- src/test/objectstore/test_bluestore_types.cc
The function was used only by writer v2, but it was returning 0 always. 
Now it properly returns the mask of used and unused blob regions. 
Changed returned type unused_t (16 bits) -> uint64_t.
+ new unittest bluestore_blob_t.get_unused_mask
+ fixed unittest ExtentMapFixture.rain …
> os/bluestore: implemented bluestore_blob_t::get_unused_mask

- src/os/bluestore/bluestore_types.cc
Fill onode test instances with sample data …
> os/bluestore : Fill onode test instances with sample data

- src/os/bluestore/BlueFS.cc
backport tracker: https://tracker.ceph.com/issues/70068
---
backport of https://github.com/ceph/ceph/pull/56515
parent tracker: https://tracker.ceph.com/issues/65176
> reef: os/bluestore: fix the problem that _estimate_log_size_N calculates the log size incorrectly

- qa/tasks/rgw_multisite_tests.py
- src/rgw/driver/rados/rgw_data_sync.cc
- src/test/rgw/rgw_multi/conn.py
- src/test/rgw/rgw_multi/tests.py
- src/test/rgw/test_multi.py
Issue https://tracker.ceph.com/issues/68884 revealed that because user_acl is initialized by default in RGWUserPermHandler::Init with the same identity, calling verify_bucket_permission_no_policy() would mistakenly allow the request since the user ACL matches the identity. Removing the default creation of user_acl would align the behavior with other S3 operations (leaving user_acl uninitialized) to prevent unauthorized data replication.
Fixes: https://tracker.ceph.com/issues/69972
> rgw: prevent data sync from replicating to buckets not owned by the user

- src/common/bitset_set.h
Minor compiler warning caused by unsigned comparison with zero. …
> common:  Remove unnecessary assert checking unsigned number is 0 or greater in bitset_set.h

- qa/standalone/mon/mon-cluster-log.sh
backport tracker: https://tracker.ceph.com/issues/68949
---
backport of https://github.com/ceph/ceph/pull/60071
parent tracker: https://tracker.ceph.com/issues/67282
> squid: qa/standalone/mon/mon_cluster_log.sh: retry check for log line

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-details/rbd-details.component.ts
backport tracker: https://tracker.ceph.com/issues/67936
---
backport of https://github.com/ceph/ceph/pull/59575
parent tracker: https://tracker.ceph.com/issues/67849
> reef: mgr/dashboard: Fix variable capitalization in embedded rbd-details panel  

- src/common/bitset_set.h
- src/common/mini_flat_map.h
- src/test/common/test_bitset_set.cc
- src/test/common/test_mini_flat_map.cc
Note: both classes have begin()/end() methods, which
required an explicit opt-out of fmt/range default handling.
> common: fmt support for bitset_set & mini_flat_map

- src/common/pick_address.cc
backport tracker: https://tracker.ceph.com/issues/66141
---
backport of https://github.com/ceph/ceph/pull/56640
parent tracker: https://tracker.ceph.com/issues/65186
> reef: common/pick_address: check if address in subnet all public address

- qa/tasks/cephfs/test_volumes.py
> qa/cephfs: avoid unnecessary importing in test_volumes.py

- src/librbd/ConfigWatcher.cc
- src/mds/MDSRank.cc
- src/mds/MDSRank.h
- src/nvmeof/NVMeofGwMonitorClient.cc
- src/nvmeof/NVMeofGwMonitorClient.h
- src/tools/rbd_mirror/Throttler.cc
- src/tools/rbd_mirror/Throttler.h
This PR is but one of a set. Following
https://github.com/ceph/ceph/pull/61394, all uses of
the deprecated interface will be updated, and that
old interface will be removed.
> mds,nvmeof,rbd: replace obsolete get_tracked_conf_keys()

- src/ceph-volume/ceph_volume/devices/lvm/zap.py
- src/ceph-volume/ceph_volume/tests/devices/test_zap.py
backport tracker: https://tracker.ceph.com/issues/70367
---
backport of https://github.com/ceph/ceph/pull/62173
parent tracker: https://tracker.ceph.com/issues/70363
> squid: ceph-volume: allow zapping partitions on multipath devices

- doc/rados/configuration/mclock-config-ref.rst
- doc/rados/configuration/osd-config-ref.rst
- src/common/options/osd.yaml.in
- src/osd/OSD.cc
- src/osd/OSD.h
- src/osd/PG.h
`osd_recovery_sleep_degraded`, `osd_recovery_sleep_degraded_ssd`, `osd_recovery_sleep_degraded_hdd` added in the configuration to throttle the data movement while recovery when pg is degraded
Fixes: https://tracker.ceph.com/issues/67700 …
> OSD: Split osd_recovery_sleep into settings applied to degraded or clean PGs

- src/pybind/mgr/dashboard/requirements.txt
backport tracker: https://tracker.ceph.com/issues/70425
---
backport of https://github.com/ceph/ceph/pull/62242
parent tracker: https://tracker.ceph.com/issues/70411
> squid: mgr/dashboard: pin lxml to fix run-dashboard-tox-make-check failure

- src/pybind/mgr/dashboard/requirements.txt
backport tracker: https://tracker.ceph.com/issues/70424
---
backport of https://github.com/ceph/ceph/pull/62242
parent tracker: https://tracker.ceph.com/issues/70411
> reef: mgr/dashboard: pin lxml to fix run-dashboard-tox-make-check failure

- qa/tasks/mgr/dashboard/test_rgw.py
Fixes https://tracker.ceph.com/issues/46735
Disabling the test due to flakiness
- …
> mgr/dashboard: Disable MFA test

- qa/tasks/mgr/dashboard/test_rgw.py
- src/pybind/mgr/dashboard/controllers/rgw.py
backport tracker: https://tracker.ceph.com/issues/70251
---
backport of https://github.com/ceph/ceph/pull/60635
parent tracker: https://tracker.ceph.com/issues/68964
> squid: mgr: fix subuser creation via dashboard

- qa/tasks/mgr/dashboard/helper.py
- qa/tasks/mgr/dashboard/test_mgr_module.py
- qa/tasks/mgr/dashboard/test_osd.py
- qa/tasks/mgr/mgr_test_case.py
- src/pybind/mgr/dashboard/run-backend-api-tests.sh
backport tracker: https://tracker.ceph.com/issues/67928, https://tracker.ceph.com/issues/67900, https://tracker.ceph.com/issues/68889
---
backport of https://github.com/ceph/ceph/pull/58995, https://github.com/ceph/ceph/pull/59530, https://github.com/ceph/ceph/pull/61744/, https://github.com/ceph/ceph/pull/60511
parent tracker: https://tracker.ceph.com/issues/66844, https://tracker.ceph.com/issues/47612, https://tracker.ceph.com/issues/62972
> reef: qa/mgr/dashboard: fix test race condition  

- doc/monitoring/index.rst
(cherry picked from commit 1bc67295c8b75475455ff702998ae4d7fb2ec749) …
> squid: doc/monitoring: Improve index.rst

- qa/suites/rgw/crypt/2-kms/vault_kv.yaml
- qa/tasks/vault.py
the vault task creates some keys on startup for use in s3-tests. on cleanup, check that rgw has removed any temporary bucket keys that were created during testing. fail with an assertion if the listed keys differ
<details> …
> qa/vault: create_secrets() cleanup checks for orphaned keys

- qa/tasks/mgr/dashboard/helper.py
- qa/tasks/mgr/dashboard/test_mgr_module.py
- qa/tasks/mgr/dashboard/test_osd.py
- qa/tasks/mgr/mgr_test_case.py
- src/pybind/mgr/dashboard/run-backend-api-tests.sh
backport tracker: https://tracker.ceph.com/issues/67929, https://tracker.ceph.com/issues/67901, https://tracker.ceph.com/issues/68890
---
backport of https://github.com/ceph/ceph/pull/58995, https://github.com/ceph/ceph/pull/59530, https://github.com/ceph/ceph/pull/61744/, https://github.com/ceph/ceph/pull/60511
parent tracker: https://tracker.ceph.com/issues/66844, https://tracker.ceph.com/issues/47612, https://tracker.ceph.com/issues/62972
> squid: qa/mgr/dashboard: fix test race condition 

- src/common/Finisher.h
- src/common/Formatter.h
- src/common/PriorityCache.cc
- src/common/SloppyCRCMap.h
- src/common/TrackedOp.h
- src/common/ceph_time.h
- src/common/cmdparse.cc
- src/common/cmdparse.h
- src/common/convenience.h
- src/common/fair_mutex.h
- src/common/obj_bencher.cc
- src/common/obj_bencher.h
- src/common/perf_counters.cc
- src/common/perf_counters.h
- src/common/perf_counters_cache.h
- src/include/denc.h
- src/include/types.h
> common: add missing includes

- PendingReleaseNotes
- doc/rados/operations/monitoring.rst
- qa/workunits/cephtool/test.sh
- src/common/CMakeLists.txt
- src/common/ceph_context.cc
- src/common/ceph_context.h
- src/common/tcp_info.cc
- src/common/tcp_info.h
- src/msg/Messenger.h
- src/msg/async/AsyncConnection.cc
- src/msg/async/AsyncConnection.h
- src/msg/async/AsyncMessenger.cc
- src/msg/async/AsyncMessenger.h
- src/msg/async/Protocol.h
- src/msg/async/ProtocolV1.cc
- src/msg/async/ProtocolV1.h
- src/msg/async/ProtocolV2.cc
- src/msg/async/ProtocolV2.h
- src/msg/async/compression_onwire.cc
- src/msg/async/compression_onwire.h
- src/msg/async/crypto_onwire.cc
- src/msg/async/crypto_onwire.h
- src/test/msgr/test_msgr.cc
Make connection information and statistics of a running Ceph Messenger easily accessible for field debugging.
Export data as JSON to allow tools to display the information.
Add `dump(Formatter..)` methods to the Async Messenger and Connection to dump snapshots of the current state of connections, dispatch queue, workers, listen sockets and TCP socket statistics via TCP_INFO.
Add a utility to get TCP information and statistics from the kernel.
Add a `dump_messenger` command to MON, MGR, OSD, MDS, Objecter and librados.
<details>
<summary>bin/ceph tell mgr.x dump_messenger</summary>
```json
{
"messenger": {
"mgr": {
"nonce": 2755615045626245882,
"my_name": {
"type": "mgr",
"num": 4133
},
"my_addrs": {
"addrvec": [
{
"type": "v2",
"addr": "192.168.101.23:6800",
"nonce": 3158717178
},
{ …
```
> Add Asok Command: Dump Messenger Status (Connections, TCP stats, ..)

- src/common/interval_map.h
- src/include/interval_set.h
- src/test/common/test_interval_map.cc
- src/test/common/test_interval_set.cc
Interval_sets have the ability to choose the underlying data structure for the set, through a template selection. This changes allows similar behaviour in interval_map.  This not only gives potential performance enhancements for some applications by using flat maps, but also allows better interop between interval_set and inverval_map. 
There are also a couple of tweaks to interval_set in here around the previous introduction of strict mode.  …
> common/include: Add map type selection to interval_map

- qa/suites/fs/upgrade/mds_upgrade_sequence/tasks/6-verify.yaml
> qa/cephfs: require-osd-release should now be tentacle

- PendingReleaseNotes
- doc/man/8/ceph.rst
- doc/rados/configuration/common.rst
- qa/workunits/cephtool/test.sh
- src/ceph.in
- src/common/Formatter.h
- src/common/admin_socket.cc
- src/common/config.cc
- src/common/options/global.yaml.in
- src/test/cli/ceph-conf/show-config.t
backport tracker: https://tracker.ceph.com/issues/66185
---
backport of https://github.com/ceph/ceph/pull/57215
parent tracker: https://tracker.ceph.com/issues/65747
> squid: common,ceph: add output file switch to dump json to

- PendingReleaseNotes
- doc/cephfs/fs-volumes.rst
- doc/cephfs/troubleshooting.rst
- qa/suites/fs/volumes/tasks/volumes/test/async.yaml
- qa/tasks/cephfs/mount.py
- qa/tasks/cephfs/test_volumes.py
- src/pybind/mgr/volumes/fs/async_job.py
- src/pybind/mgr/volumes/module.py
Add a new mgr config options that allows pausing async purge threads and async cloner threads.
Fixes: https://tracker.ceph.com/issues/61903
Fixes: https://tracker.ceph.com/issues/68630
TODO
<details>
- …
> mgr/volumes: allow disabling async job threads

- src/librbd/ConfigWatcher.cc
> librbd/ConfigWatcher: fix a missing 'override'

- src/script/build-with-container.py
- src/script/buildcontainer-setup.sh
Ensure that curl is installed in all build containers regardless of
ceph's dependencies or other factors. This allows us to use curl in
any subsequent build steps/scripts.
Fixes: https://tracker.ceph.com/issues/70451 …
> build-with-container: two small fixes

- src/include/cephfs/types.h
For inspection from `dump tree` MDS command. …
> include/cephfs: dump optmetadata

- doc/rados/configuration/bluestore-config-ref.rst
Commit 3879e4ad417d lowercased several commands. This fixes the remaining typos.
Needs to be backported whereever 3879e4ad417d was backported.
> doc/rados/configuration/bluestore-config-ref: Fix lowercase typos

- src/pybind/mgr/dashboard/services/auth/oauth2.py
Fixes https://tracker.ceph.com/issues/70454
Due to PR linter updates, this place remained not updated hence failing …
> mgr/dashboard: fix OAuth2 SSO when roles_path is empty

- src/client/Client.cc
- src/client/Client.h
- src/client/SyntheticClient.cc
- src/include/filepath.h
- src/libcephfs.cc
- src/test/libcephfs/test.cc
Mostly this is a fix for unwrapping dentry names for getcwd. I've also included a second fix for mkdir and recursive path walks needed for userspace encryption (see #61137). …
> client: correctly unwrap getcwd dentries

- doc/dev/libcephfs_proxy.rst
- src/libcephfs_proxy/libcephfs_proxy.c
- src/libcephfs_proxy/libcephfsd.c
- src/libcephfs_proxy/proxy.h
- src/libcephfs_proxy/proxy_link.c
- src/libcephfs_proxy/proxy_link.h
- src/libcephfs_proxy/proxy_requests.h
This PR adds a negotiation framework for the CephFS proxy that is backward compatible and allows extensions to be added in the future, also in a backward compatible way.
This will be used to add a feature that will allow the daemon to send notifications and callbacks back to the client in an asynchronous way. …
> libcephfs_proxy: add negotiation support to the CephFS proxy

- doc/dev/libcephfs_proxy.rst
- src/libcephfs_proxy/CMakeLists.txt
- src/libcephfs_proxy/libcephfs_proxy.c
- src/libcephfs_proxy/libcephfsd.c
- src/libcephfs_proxy/proxy.h
- src/libcephfs_proxy/proxy_async.c
- src/libcephfs_proxy/proxy_async.h
- src/libcephfs_proxy/proxy_helpers.h
- src/libcephfs_proxy/proxy_link.c
- src/libcephfs_proxy/proxy_link.h
- src/libcephfs_proxy/proxy_requests.h
This PR implements a callback mechanism that allows the proxy daemon to send notifications to the clients. This mechanism is used to implement the `ceph_ll_nonblocking_readv_writev()` function.
The client side, when the feature is also supported by the server, creates a new thread that will wait for incoming notifications from the daemon. When the daemon receives a nonblocking rw opeation, it processes the request normally using libcephfs, and then it sends back a notification with the result to the client when libcephfs executes the callback.
This PR depends on #61757.
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer …
> libcephfs_proxy: add support for nonblocking read/write

- src/pybind/mgr/dashboard/controllers/multi_cluster.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-list/multi-cluster-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/multi-cluster.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
the req sends the details of every cluster's token in a GET req which is insecure and gets logged in browser and server logs.. fixing that and also stop polling token status every 5s and resort to the 10m interval
Fixes: https://tracker.ceph.com/issues/70371 …
> mgr/dashboard: fix token polling req in multi-cluster UI

- qa/tasks/cephfs/test_dir_charmap.py
- src/mds/journal.cc
> mds: set alternate_name for new fullbit dentries

- qa/suites/rgw/crypt/2-kms/vault_kv.yaml
- qa/suites/rgw/crypt/2-kms/vault_old.yaml
- qa/suites/rgw/crypt/2-kms/vault_transit.yaml
- src/rgw/rgw_kms.cc
On bucket key deletion when the request to change the property of the key for deletion_allowed to true is made, it is expected that the response body be empty. But this assumption is false and there would be a dump of the new config in the response. this condition would prevent the key deletion from being done.
Fixes: https://tracker.ceph.com/issues/65626
> rgw: false assumption on vault bucket key deletion

- src/blk/kernel/KernelDevice.cc
- src/blk/kernel/KernelDevice.h
backport tracker: https://tracker.ceph.com/issues/68792
---
backport of https://github.com/ceph/ceph/pull/59479
parent tracker: https://tracker.ceph.com/issues/67766
> reef: blk/KernelDevice: using join() to wait thread end is more safe

- qa/workunits/rbd/luks-encryption.sh
- qa/workunits/rbd/rbd-nbd.sh
backport tracker: https://tracker.ceph.com/issues/70378
---
backport of https://github.com/ceph/ceph/pull/62189
parent tracker: https://tracker.ceph.com/issues/66419
> reef: qa/workunits/rbd: wait for resize to be applied in rbd-nbd

- qa/suites/rados/basic/tasks/libcephsqlite.yaml
- qa/suites/rados/basic/tasks/rados_api_tests.yaml
- qa/suites/rados/basic/tasks/rados_cls_all.yaml
- qa/suites/rados/basic/tasks/rados_python.yaml
- qa/suites/rados/basic/tasks/rados_stress_watch.yaml
- qa/suites/rados/basic/tasks/rados_striper.yaml
- qa/suites/rados/basic/tasks/rados_workunit_loadgen_big.yaml
- qa/suites/rados/basic/tasks/rados_workunit_loadgen_mix.yaml
- qa/suites/rados/basic/tasks/rados_workunit_loadgen_mostlyread.yaml
- qa/suites/rados/basic/tasks/readwrite.yaml
- qa/suites/rados/basic/tasks/repair_test.yaml
- qa/suites/rados/basic/tasks/scrub_test.yaml
We already ignore POOL_APP_NOT_ENABLED, but the detail in the cluster health still gets picked up by the badness check, so we have to ignore that too.
Fixes: https://tracker.ceph.com/issues/62776 …
> qa/suites/rados/basic: ignore POOL_APP_NOT_ENABLED detail in cluster log

- doc/rados/troubleshooting/troubleshooting-pg.rst
doc/rados/troubleshooting: Improve troubleshooting-pg.rst
Bash code block had extraneous explicit `$` that rendered confusingly. …
> doc/rados/troubleshooting: Improve troubleshooting-pg.rst

- src/test/crimson/test_config.cc
Following https://github.com/ceph/ceph/pull/61394, all uses of the deprecated interface will be updated, and that old interface will be removed.
> test/crimson/test_config: replace obsolete get_tracked_conf_keys()

- src/mon/OSDMonitor.cc
After destroying an OSD, the command "ceph node ls" still listed the destroyed OSD, causing confusion. This fix ensures that the status of the OSD is checked before adding it to the output, aligning its behavior with "ceph osd tree," which already displays the correct status.
Fixes: https://tracker.ceph.com/issues/70400 …
> OSDMonitor: exclude destroyed OSDs from "ceph node ls" output

- systemd/ceph-crash.service.in
- systemd/ceph-exporter.service.in
- systemd/ceph-fuse@.service.in
- systemd/ceph-immutable-object-cache@.service.in
- systemd/ceph-mds@.service.in
- systemd/ceph-mgr@.service.in
- systemd/ceph-mon@.service.in
- systemd/ceph-osd@.service.in
- systemd/ceph-radosgw@.service.in
- systemd/ceph-rbd-mirror@.service.in
- systemd/ceph-volume@.service
- systemd/cephfs-mirror@.service.in
- systemd/rbdmap.service.in
The current systemd services use hard-coded paths. This commit uses the CMake install prefix in the templates to set up paths to executables where they are actually installed.
> systemd: use CMake install prefix in templates

- qa/tasks/mgr/dashboard/test_rgw.py
- src/pybind/mgr/dashboard/controllers/rgw.py
backport tracker: https://tracker.ceph.com/issues/70252
---
backport of https://github.com/ceph/ceph/pull/60635
parent tracker: https://tracker.ceph.com/issues/68964
> reef: mgr: fix subuser creation via dashboard

- monitoring/ceph-mixin/dashboards/rgw.libsonnet
- monitoring/ceph-mixin/dashboards_out/radosgw-overview.json
- monitoring/ceph-mixin/tests_dashboards/features/radosgw_overview.feature
backport tracker: https://tracker.ceph.com/issues/70436
---
backport of https://github.com/ceph/ceph/pull/60873
parent tracker: https://tracker.ceph.com/issues/69074
> squid: mgr/dashboard: Add ceph_daemon filter to rgw overview grafana panel queries

- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/os/bluestore/Writer.cc
- src/os/bluestore/Writer.h
- src/os/bluestore/bluestore_types.h
We should mark dirty and signal for reshard region before we trim the data by _try_reuse_allocated.
Punching hole and writing to already existing blobs is still modification.
The problem was detected using:
`./bin/ceph_test_objectstore --log-to-stderr=false --bluestore_write_v2=true --plugin_dir=./lib --gtest_filter=\*SyntheticMatrixShardingLimited\*`
Problem was introduced in #61762 …
> os/bluestore: write_v2 resharding misplaced

- src/python-common/ceph/cephadm/images.py
> nvmeof: bump image version to 1.5

- src/mds/MetricsHandler.cc
- src/mds/MetricsHandler.h
backport tracker: https://tracker.ceph.com/issues/69359
---
backport of https://github.com/ceph/ceph/pull/60653
parent tracker: https://tracker.ceph.com/issues/68865
> squid: mds: do not process client metrics message with fast dispatch

- qa/suites/rgw/verify/tasks/rados-pool-quota.yaml
- qa/workunits/rgw/test_rgw_rados_pool_quota.py
- src/rgw/driver/rados/rgw_cr_rados.cc
- src/rgw/driver/rados/rgw_tools.cc
- src/rgw/rgw_common.cc
- src/rgw/rgw_rest.cc
* avoid direct calls to `ioctx_create()` so `rgw_init_ioctx()` can set appropriate flags globally
* add `librados::OPERATION_FULL_TRY` globally so we never hang waiting for space when the pool reaches its quota limit
Fixes: https://tracker.ceph.com/issues/69842
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull-requests/config/definitions/ceph-perf-pull …
> rgw: rgw_init_ioctx() adds set_pool_full_try()

- src/mon/MonCommands.h
- src/mon/OSDMonitor.cc
- src/osd/OSDMap.cc
- src/osd/OSDMap.h
The current rm-pg-upmap-primary command checks that the pgid exists in the pgmap before continuing to remove it. Due to https://tracker.ceph.com/issues/66867, some invalid pg-upmap-primary entires may exist for pools that have been removed. Currently, these mappings are impossible to remove since the pgids no longer exist in the pgmap.
This new command, rm-pg-upmap-primary-all, allows users the ability to remove any and all pg-upmap-primary mappings in the osdmap at once, which includes valid and invalid entries.
This command may also be helpful when upgrading from versions where users are plagued by https://tracker.ceph.com/issues/61948. Users may use an upgraded mon to remove all pg-upmap-primray entries (valid and invalid) so they continue to upgrade to a safe version.
See manual …
> mon, osd: add command to remove invalid pg-upmap-primary entries

- src/extblkdev/CMakeLists.txt
this header is required when building the extended block device plugins on linux, without it the build fails like:
```
/home/kefu/dev/ceph/src/extblkdev/ExtBlkDevInterface.h:38:10: fatal error: 'sys/capability.h' file not found
38 | #include <sys/capability.h>
|          ^~~~~~~~~~~~~~~~~~
```
so, let's mark this package REQUIRED, so that we can fail early when generating the building system. …
> cmake: make libcap REQUIRED

- src/pybind/mgr/volumes/fs/operations/charmap_util.py
Fixes: https://tracker.ceph.com/issues/70480 …
> mgr/volumes: fix issues pointed by flake8

- monitoring/ceph-mixin/prometheus_alerts.libsonnet
- monitoring/ceph-mixin/prometheus_alerts.yml
- monitoring/ceph-mixin/tests_alerts/test_alerts.yml
Rename the alert to NVMeoFSingleGateway.
The original name was confusing because it
accidently might convey that alert would be
triggered if there is a single gateway group.
Though 'NVMeoFSingleGatewayGroup' alert means that there is single gateway in a group.
Fixes: https://jsw.ibm.com/browse/ISCE-848?focusedId=23443948&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23443948 …
> monitoring: rename NVMeoFSingleGatewayGroup alert

- src/common/config_cacher.h
- src/common/config_obs.h
- src/common/config_obs_mgr.h
This is the last step in a set of PRs that replaced the deprecated get_tracked_conf_keys()
with the new get_tracked_keys().
Now that no clients of the old interface remain, it is removed from md_config_obs_impl
(which means: removed from md_config_obs_t)
> common: md_config_obs_impl: remove deprecated get_tracked_conf_keys()

- src/librbd/internal.cc
- src/librbd/io/ImageDispatchSpec.h
- src/librbd/io/ImageDispatcher.cc
- src/test/librbd/crypto/luks/test_mock_FlattenRequest.cc
- src/test/librbd/crypto/luks/test_mock_FormatRequest.cc
- src/test/librbd/crypto/luks/test_mock_LoadRequest.cc
- src/test/librbd/crypto/test_mock_FormatRequest.cc
- src/test/librbd/crypto/test_mock_LoadRequest.cc
- src/test/librbd/deep_copy/test_mock_ObjectCopyRequest.cc
- src/test/librbd/exclusive_lock/test_mock_PreReleaseRequest.cc
- src/test/librbd/image/test_mock_RefreshRequest.cc
- src/test/librbd/io/test_mock_CopyupRequest.cc
- src/test/librbd/operation/test_mock_ResizeRequest.cc
This change is part of a broader effort to reduce dependencies on third-party libraries by leveraging C++ standard library alternatives.
Migrating from boost::variant to std::variant improves code readability and maintainability while reducing external dependencies. …
> librbd: migrate from boost::variant to std::variant 

- src/os/bluestore/BlueFS.cc
backport tracker: https://tracker.ceph.com/issues/70067
---
backport of https://github.com/ceph/ceph/pull/56515
parent tracker: https://tracker.ceph.com/issues/65176
> squid: os/bluestore: fix the problem that _estimate_log_size_N calculates the log size incorrectly

- src/rgw/rgw_rest_s3.cc
When multiple replication rules target the same bucket, the rule with the highest priority should be applied. While this logic is already in place, the configuration does not enforce priority settings, which could lead to confusion. This behavior aligns with AWS's implementation for multiple destination buckets as outlined https://aws.amazon.com/blogs/aws/new-amazon-s3-replication-adds-support-for-multiple-destination-buckets/
Fixes: https://tracker.ceph.com/issues/69946
> rgw: check for duplicate rule priorities in replication configuration

- src/rgw/driver/rados/sync_fairness.cc
other implementations of `librados::WatchCtx2` in radosgw reconnect the watch on any error code, not just `-ENOTCONN`
Fixes: https://tracker.ceph.com/issues/70270
<details> …
> rgw: sync fairness watcher reconnects on any error

- src/rgw/services/svc_notify.cc
IF we get `-ENOENT` from unwatch just stop trying to renew.
Otherwise, schedule retry on watch failure, but add a maximum retry timeout.
https://tracker.ceph.com/issues/70422 …
> rgw: Try to handle unwatch errors sensibly

- src/crypto/openssl/openssl_crypto_accel.cc
openssl_crypto_accel.cc does not need the declarations included by openssl/engine.h, also, openssl/engine.h was deprecated in favor of the provider API, the engine support was removed in fedora 41.
so, let's avoid including it. please note, the "ENGINE" struct's definition is available in openssl/types.h. …
> crypto: remove unused include

- src/rgw/rgw_auth.cc
to correctly create a federated user in oidc namespace.
The idea was to check if the federated user had any buckets associated with it from the time when the logic for creating a shadow user was not in place, and this was done by calling read_stats which returned -ENOENT when the user did not exist, which was erroneously interpreted as buckets not existing for the user - but this logic correctly led to creation of user in oidc namespace. Later read_stats() was replaced by load_stats() and load_stats() does not return -ENOENT when a user does not exist, hence according to the code, the federated user was not getting created in 'oidc' namespace. Hence replaced load_stats() with list_buckets() and corrected the code to create a user in oidc namespace if the user did not own any bucket. …
> rgw/sts: replacing load_stats with list_buckets

- src/osd/osd_types.cc
- src/osd/osd_types.h
- src/test/osd/types.cc
This is a resurrection of https://github.com/ceph/ceph/pull/52022.
- Component …
> osd_type: decouple is_stretch_pool() from versioning of pg_pool_t's schema

- doc/cephfs/charmap.rst
There was confusion about whether setting the charmap on a directory also affects the name of the directory itself. …
> doc: add clarification note on how charmap is applied

- PendingReleaseNotes
- src/rgw/rgw_auth.cc
- src/rgw/rgw_auth.h
- src/rgw/rgw_auth_filters.h
- src/rgw/rgw_common.h
- src/rgw/rgw_op.cc
- src/test/rgw/test_rgw_iam_policy.cc
- src/test/rgw/test_rgw_lua.cc
According to https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketPolicy.html root user should always have access to do Put/Get/DeleteBucketPolicy. By implementing the `x-amz-confirm-remove-self-bucket-access` header this privilege can also be dropped from the root user.
Fixes: https://tracker.ceph.com/issues/66177
> rgw: implement ConfirmRemoveSelfBucketAccess header for bucket policy

- doc/dev/developer_guide/essentials.rst
This PR updates developer guide essentials with a working and up-to-date way to subscribe to Ceph mailing lists. The [current docummentation](https://docs.ceph.com/en/latest/dev/developer_guide/essentials/#mailing-lists) mentions ways of sending e-mails for subscription that no longer work as mentioned in [Tracker #64580](https://tracker.ceph.com/issues/64580). Users are either prompted with "Majordomo no longer supported" or "subscribe bad argument: ceph-devel" messages with the currently documented method. This change points to the ceph community page and details ways to subscribe to both mailing lists that are important for developers to follow.
<details>
<summary>Show …
> doc/dev/developer_guide/essentials: update mailing lists

- src/mon/MonCommands.h
- src/mon/OSDMonitor.cc
- src/osd/OSDMap.cc
- src/osd/OSDMap.h
Early Reef backport of https://github.com/ceph/ceph/pull/62190 (needed for v18.2.5). …
> reef: mon, osd: add command to remove invalid pg-upmap-primary entries

- src/pybind/mgr/dashboard/frontend/package-lock.json
- src/pybind/mgr/dashboard/frontend/package.json
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-migrate/rgw-multisite-migrate.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-migrate/rgw-multisite-migrate.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zonegroup-form/rgw-multisite-zonegroup-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zonegroup-form/rgw-multisite-zonegroup-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.ts
backport tracker: https://tracker.ceph.com/issues/70524
---
backport of https://github.com/ceph/ceph/pull/60843
parent tracker: https://tracker.ceph.com/issues/69055
> squid: mgr/dashboard: When configuring the RGW Multisite endpoints from the UI allow FQDN(Not only IP)

- src/common/options/osd.yaml.in
osd_max_scrubs takes effect even though mclock is used.
```
$ ceph config show-with-defaults osd.0 | grep '^osd_max_scrubs' | sed -E -e 's/( +)/ /g'
osd_max_scrubs 3 default
$ ceph config show-with-defaults osd.0 | grep '^osd.* override ' | sed -E -e 's/( +)/ /g'
osd_delete_sleep 0.000000 override
osd_delete_sleep_hdd 0.000000 override
osd_delete_sleep_hybrid 0.000000 override
osd_delete_sleep_ssd 0.000000 override
osd_pg_delete_cost 15728640 override
osd_recovery_sleep 0.000000 override
osd_recovery_sleep_hdd 0.000000 override
osd_recovery_sleep_hybrid 0.000000 override
osd_recovery_sleep_ssd 0.000000 override
osd_scrub_sleep 0.000000 override
osd_snap_trim_sleep 0.000000 override
osd_snap_trim_sleep_hdd 0.000000 override
osd_snap_trim_sleep_hybrid 0.000000 override …
```
> common/options: fix the description of osd_max_scrubs

- doc/cephadm/upgrade.rst
doc/cephadm: Add PG autoscaler advice to upgrade.rst …
> doc/cephadm: Add PG autoscaler advice to upgrade.rst

- src/common/hobject.cc
- src/common/scrub_types.cc
- src/crimson/admin/osd_admin.cc
- src/crimson/os/seastore/onode_manager/staged-fltree/stages/key_layout.h
- src/crimson/osd/scrub/scrub_validator.cc
- src/include/types.h
- src/osd/ECBackend.cc
- src/osd/ECBackend.h
- src/osd/ECBackendL.cc
- src/osd/ECBackendL.h
- src/osd/ECCommon.cc
- src/osd/ECCommonL.cc
- src/osd/ECTransaction.cc
- src/osd/ECTransactionL.cc
- src/osd/OSD.cc
- src/osd/OSDMap.cc
- src/osd/PGBackend.cc
- src/osd/PeeringState.cc
- src/osd/PeeringState.h
- src/osd/osd_types.cc
- src/osd/osd_types.h
- src/osd/osd_types_fmt.h
- src/test/crimson/test_crimson_scrub.cc
- src/tools/rados/rados.cc
In new EC code, we want to be strict about usage of shard_id_t, to avoid confusion with raw_shard_id_t (to be added later), OSD ids, and other objects where ints are frequently used as IDs. 
This required adding quite a few explicit casts, which can potentially be removed the code owner thinks that these will provide some useful policing.
TO REVIEWER: Please only pay attention to the last commit. This is intentionally based on [another PR ](https://github.com/ceph/ceph/pull/61263), which I hope to push soon.  …
> osd: Require explicit casting for shard_id_t

- src/pybind/mgr/dashboard/frontend/package-lock.json
- src/pybind/mgr/dashboard/frontend/package.json
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-migrate/rgw-multisite-migrate.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-migrate/rgw-multisite-migrate.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zonegroup-form/rgw-multisite-zonegroup-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zonegroup-form/rgw-multisite-zonegroup-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.ts
backport tracker: https://tracker.ceph.com/issues/70523
---
backport of https://github.com/ceph/ceph/pull/60843
parent tracker: https://tracker.ceph.com/issues/69055
> reef: mgr/dashboard: When configuring the RGW Multisite endpoints from the UI allow FQDN(Not only IP)

- monitoring/ceph-mixin/dashboards/cephfs.libsonnet
- monitoring/ceph-mixin/dashboards/timeseries_panel.libsonnet
- monitoring/ceph-mixin/dashboards_out/cephfs-overview.json
backport tracker: https://tracker.ceph.com/issues/70549
---
backport of https://github.com/ceph/ceph/pull/61210
parent tracker: https://tracker.ceph.com/issues/69404
> squid: mgr/dashboard: Changing SimpleGraphPanel to TimeSeries Panel in cephfs.libsonnet to fix inconsistency in Line Graphs

- monitoring/ceph-mixin/dashboards/host.libsonnet
- monitoring/ceph-mixin/dashboards_out/host-details.json
- monitoring/ceph-mixin/dashboards_out/hosts-overview.json
backport tracker: https://tracker.ceph.com/issues/70547
---
backport of https://github.com/ceph/ceph/pull/61463
parent tracker: https://tracker.ceph.com/issues/70228
> squid: mgr/dashboard: Changing SimpleGraphPanel to TimeSeries Panel in host.libsonnet to fix inconsistency in Line Graphs

- monitoring/ceph-mixin/dashboards/osd.libsonnet
- monitoring/ceph-mixin/dashboards_out/osd-device-details.json
- monitoring/ceph-mixin/dashboards_out/osds-overview.json
backport tracker: https://tracker.ceph.com/issues/70548
---
backport of https://github.com/ceph/ceph/pull/61474
parent tracker: https://tracker.ceph.com/issues/70227
> squid: mgr/dashboard: Changing SimpleGraphPanel to TimeSeries Panel in osd.libsonnet to fix inconsistency in Line Graphs 

- monitoring/ceph-mixin/dashboards/pool.libsonnet
- monitoring/ceph-mixin/dashboards_out/pool-detail.json
- monitoring/ceph-mixin/dashboards_out/pool-overview.json
backport tracker: https://tracker.ceph.com/issues/70546
---
backport of https://github.com/ceph/ceph/pull/61476
parent tracker: https://tracker.ceph.com/issues/70229
> squid: mgr/dashboard: Changing SimpleGraphPanel to TimeSeries Panel in pool.libsonnet to fix inconsistency in Line Graphs

- doc/cephadm/upgrade.rst
(cherry picked from commit ee69f52193996d528410a71c2c67fc27b47dee31) …
> reef: doc/cephadm: Add PG autoscaler advice to upgrade.rst

- doc/cephadm/upgrade.rst
(cherry picked from commit ee69f52193996d528410a71c2c67fc27b47dee31) …
> squid: doc/cephadm: Add PG autoscaler advice to upgrade.rst

- qa/suites/orch/cephadm/smb/tasks/deploy_smb_basic.yaml
- qa/suites/orch/cephadm/smb/tasks/deploy_smb_domain.yaml
- src/pybind/mgr/smb/handler.py
In order to expose and manage snapshots as previous versions from Windows we make use of the existing _ceph_snapshots_ vfs module from Samba. _vfs_ceph_snapshots_ by default assumes the snap directory to be named "_.snap_" with an option to configure a different name to match the value for '_client_snapdir_' parameter for CephFS client. We follow the default behaviour to avoid further complications on a live running cluster and thereby recommend to keep the default for '_client_snapdir_'. This limitation may slightly change in future to dynamically detect the current snap directory name while shares are created and not afterwards.
ref: https://www.samba.org/samba/docs/current/man-html/vfs_ceph_snapshots.8.html
> mgr/smb: Add ceph_snapshots vfs module to share definition

- src/script/build-with-container.py
- src/script/buildcontainer-setup.sh
backport tracker: https://tracker.ceph.com/issues/70507
---
backport of https://github.com/ceph/ceph/pull/62274
parent tracker: https://tracker.ceph.com/issues/70451
> squid: build-with-container: two small fixes

- src/script/build-with-container.py
- src/script/buildcontainer-setup.sh
backport tracker: https://tracker.ceph.com/issues/70506
---
backport of https://github.com/ceph/ceph/pull/62274
parent tracker: https://tracker.ceph.com/issues/70451
> reef: build-with-container: two small fixes

- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notifications/notifications.component.html
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notifications/notifications.component.ts
mgr/dashboard: Fix issue with notification icon click area
Previously, users had to click precisely on the bell icon to open the notification drawer.
This commit expands the clickable area, allowing users to open the notification drawer by clicking anywhere within the container.
Fixes: https://tracker.ceph.com/issues/70253
Signed-off-by: Ankit Kumar <51ankitkp@gmail.com>
Reference Video: [fixVideo.webm](https://github.com/user-attachments/assets/ac6964e8-4abe-4091-bda0-aa224b6eeb7d)
> mgr/dashboard:fixed issue with notification icon

- qa/suites/rgw/cloud-transition/overrides.yaml
- qa/suites/rgw/crypt/overrides.yaml
- qa/suites/rgw/lifecycle/overrides.yaml
- qa/suites/rgw/multifs/overrides.yaml
- qa/suites/rgw/sts/overrides.yaml
- qa/suites/rgw/tempest/tasks/s3tests.yaml
- qa/suites/rgw/thrash/workload/rgw_s3tests.yaml
- qa/suites/rgw/website/overrides.yaml
backport tracker: https://tracker.ceph.com/issues/70207
---
backport of https://github.com/ceph/ceph/pull/61897
parent tracker: https://tracker.ceph.com/issues/70077
> squid: qa/rgw: configure 'iam root' accounts outside of rgw/verify

- PendingReleaseNotes
- src/rgw/rgw_op.cc
backport tracker: https://tracker.ceph.com/issues/70239
---
backport of https://github.com/ceph/ceph/pull/61946
parent tracker: https://tracker.ceph.com/issues/70013
> squid: rgw: PutObjectLockConfiguration can enable object lock on existing buckets

- qa/suites/rgw/verify/tasks/rados-pool-quota.yaml
- qa/workunits/rgw/run-rados-pool-quota.sh
- qa/workunits/rgw/test_rgw_rados_pool_quota.py
- src/rgw/driver/rados/rgw_gc.cc
- src/rgw/driver/rados/rgw_rados.cc
backport tracker: https://tracker.ceph.com/issues/70264
---
backport of https://github.com/ceph/ceph/pull/61650
parent tracker: https://tracker.ceph.com/issues/69723
> squid: rgw/rados: enable object deletion at rados pool quota

- src/rgw/rgw_appmain.cc
- src/rgw/rgw_lib.cc
- src/rgw/rgw_main.h
- src/rgw/rgw_process.cc
- src/rgw/rgw_process_env.h
backport tracker: https://tracker.ceph.com/issues/70311
---
backport of https://github.com/ceph/ceph/pull/61944
parent tracker: https://tracker.ceph.com/issues/70104
> squid: rgw/log: Fix crash during shutdown with ops-log enable.

- src/rgw/rgw_rest_sts.cc
Backport of: https://tracker.ceph.com/issues/68836
https://tracker.ceph.com/issues/69258 …
> [CVE-2024-48916] rgw/sts: fix to disallow unsupported JWT algorithms

- src/libcephfs_proxy/proxy_async.c
Fix a clang warning in proxy_async.c where an unsigned value was being unnecessarily compared against 0:
```
/home/kefu/dev/ceph/src/libcephfs_proxy/proxy_async.c:29:12: warning: result of comparison of unsigned expression >= 0 is always true [-Wtautological-unsigned-zero-compare]
29 |         if ((size >= 0) && !info->write) {
|              ~~~~ ^  ~
1 warning generated.
```
Since unsigned values are always >= 0 by definition, remove this tautological check to resolve the "-Wtautological-unsigned-zero-compare" warning. …
> libcephfs_proxy: remove redundant unsigned >= 0 comparison

- doc/radosgw/notifications.rst
This PR fixes current docs about many-to-many topic relationship for notifications. Currently the sentence is two duplicated statements instead of a vice-versa relationship as mentioned in [Tracker #64956](https://tracker.ceph.com/issues/64956) and does not reflect the intented explanation.
<details> …
> doc/radosgw/notifications: fix topic details

- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard-pie/dashboard-pie.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/utils/constants.ts
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/administration/administration.component.html
- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/mgr-module.service.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/models/mgr-modules.interface.ts
- src/pybind/mgr/dashboard/services/access_control.py
**AFTER**
**BEFORE**
Since prometheus is being used in the dashboard page we need to make sure every role has prometheus read only access so that the dashboard page can load the utilization metrics.
I also saw permission issue with the osd settings endpoint when its trying to get the nearfull/full ratio. so instead of failing the entire page i am proceeding with a chart that doesn't have those details when the user doesn't have permission to access the config opt.
Multisite page was not accessible in the case of rgw-manager or read-only user because its trying to show the status of rgw module. This si also now gracefully handled to show the alert only when the user has sufficient permission.
Fixes: https://tracker.ceph.com/issues/70331 …
> mgr/dashboard: fix access control permissions for roles

- src/rgw/driver/rados/rgw_data_sync.cc
- src/rgw/rgw_rest_s3.cc
- src/test/rgw/rgw_multi/tests.py
`PutBucketReplication` is now rejecting policies that name a destination bucket with a different status.
If the status changes after `PutBucketReplication`, the corresponding bucket sync processes will skip those entries.
Fixes: https://tracker.ceph.com/issues/70486 _(partially - the status change is tracked in https://github.com/ceph/ceph/pull/62147)_
> rgw: reject PutBucketReplication policies with mismatched statuses, skip sync on update

- src/common/cmdparse.h
- src/osd/OSD.cc
- src/test/objectstore/test_bluestore_types.cc
This slight variation of cmd_getval_or() can be used where
the object type is different from the configuration item
type (as when the object is a wrapper around an integer).
It allows specifying the 'default' value in the object type.
A first use of cmd_getval_cast_or() was added in OSD.cc,
which was the trigger for this PR.
> common, osd: add cmd_getval_cast_or()

- src/test/common/test_interval_set.cc
CI Pipelines are being broken because this test is creating a number of core dumps. This does not make the test fail, but it does create some core dumps. This appears to be breaking something in the CI pipeline.  This commit is a workaround and I will find a better solution later.
Fixes: https://tracker.ceph.com/issues/70543 …
> test/common: skip google tests which create core dumps in test_interval_set

- src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/users.po.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.html
Fixes: https://tracker.ceph.com/issues/70554
https://github.com/user-attachments/assets/4ccdcf09-afe8-4add-88fd-ab8d4b21c5e9
PR that introduced regression - https://github.com/ceph/ceph/pull/59429 …
> mgr/dashboard: Not able to edit user display/full name in user form

- doc/radosgw/notifications.rst
This commit fixes documentation about many-to-many topic relationship for notifications. The current sentence states the same fact twice instead of clarifying.
Fixes: https://tracker.ceph.com/issues/64956
(cherry picked from commit 058b95abe62893c5c13f02cdf7dd438b0a95a128) …
> squid: doc/radosgw /notifications: fix topic details

- doc/radosgw/notifications.rst
This commit fixes documentation about many-to-many topic relationship for notifications. The current sentence states the same fact twice instead of clarifying.
Fixes: https://tracker.ceph.com/issues/64956
(cherry picked from commit 058b95abe62893c5c13f02cdf7dd438b0a95a128) …
> reef: doc/radosgw /notifications: fix topic details

- src/rgw/rgw_op.cc
backport tracker: https://tracker.ceph.com/issues/70340
---
backport of https://github.com/ceph/ceph/pull/62020
parent tracker: https://tracker.ceph.com/issues/70191
> squid: rgw: use object ARN for InitMultipart permissions

- src/rgw/rgw_lc.cc
backport tracker: https://tracker.ceph.com/issues/68983
---
backport of https://github.com/ceph/ceph/pull/55203
parent tracker: https://tracker.ceph.com/issues/63995
> squid: rgw/lc: delete expired delete-marker when processing Expiration lc action with Days specified

- doc/radosgw/notifications.rst
- src/rgw/driver/rados/rgw_pubsub_push.cc
- src/rgw/rgw_kafka.cc
- src/rgw/rgw_kafka.h
- src/rgw/rgw_rest_pubsub.cc
- src/rgw/rgw_rest_s3.cc
- src/test/rgw/bucket_notification/test_bn.py
backport tracker: https://tracker.ceph.com/issues/65912
---
backport of https://github.com/ceph/ceph/pull/56493
parent tracker: https://tracker.ceph.com/issues/65050
> squid: rgw/s3-notifications: use user-name/password topic attributes for SASL authentication

- src/rgw/rgw_admin.cc
backport tracker: https://tracker.ceph.com/issues/69146
---
backport of https://github.com/ceph/ceph/pull/60415
parent tracker: https://tracker.ceph.com/issues/68645
> squid: radosgw-admin: allow 'sync group pipe modify' with existing user

- src/rgw/driver/rados/rgw_user.cc
backport tracker: https://tracker.ceph.com/issues/69145
---
backport of https://github.com/ceph/ceph/pull/60830
parent tracker: https://tracker.ceph.com/issues/69043
> squid: radosgw-admin: 'user create' rejects uids matching the account id format

- src/rgw/rgw_rest_account.cc
backport tracker: https://tracker.ceph.com/issues/70312
---
backport of https://github.com/ceph/ceph/pull/61907
parent tracker: https://tracker.ceph.com/issues/70084
> squid: rgw: /admin/account APIs accept negative values

- src/rgw/radosgw-admin/orphan.cc
- src/rgw/radosgw-admin/orphan.h
The `radosgw-admin bucket radoslist ...` tool was not reporting missing oids for head objects, likely because it was originally written to find orphans and not gaps. Yet we need those reported to find gaps. So that is now fixed.
Furthermore a bug dealing with SLO objects was inadvertently introduced during the zipper conversion, and that's now fixed.
Fixes: https://tracker.ceph.com/issues/70539 …
> rgw: radoslist improvements primarily to better support gap list tool

- PendingReleaseNotes
- src/rgw/rgw_arn.cc
- src/rgw/rgw_common.cc
- src/rgw/rgw_common.h
- src/rgw/rgw_iam_policy.cc
- src/test/rgw/test_rgw_iam_policy.cc
arn-based conditions[1] like ArnEquals etc are recognized by the policy parser, but not enforced during policy evaluation
[1] https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_ARN
Fixes: https://tracker.ceph.com/issues/70481
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull-requests/config/ …
> rgw/iam: add policy evaluation for Arn-based Conditions

- PendingReleaseNotes
- doc/cephfs/fs-volumes.rst
- doc/cephfs/multifs.rst
- qa/suites/fs/volumes/tasks/volumes/test/basic.yaml
- qa/tasks/cephfs/test_volumes.py
- src/pybind/mgr/volumes/fs/operations/volume.py
- src/pybind/mgr/volumes/fs/volume.py
- src/pybind/mgr/volumes/module.py
Allow passing names of existing data pool and metadata pool to `ceph fs volume create` command so that the command will use these pools for creating volume/FS instead of creating new pools. Passing name of a non-empty pool will cause the command to abort.
Fixes: https://tracker.ceph.com/issues/69878 …
> mgr/vol: allow passing pool names to "fs volume create" cmd

- src/os/bluestore/BlueStore.cc
- src/os/bluestore/BlueStore.h
- src/test/objectstore/store_test.cc
Backports: https://github.com/ceph/ceph/pull/61364
Parent tracker: https://tracker.ceph.com/issues/69507
Fixes: https://tracker.ceph.com/issues/70292 …
> reef: os/bluestore: do cache locally compressor engines ever used 

- src/blk/kernel/KernelDevice.cc
- src/blk/kernel/KernelDevice.h
- src/common/options/global.yaml.in
Some disks have a discard performance that is too low to keep up with write workloads. Using async discard in this case will cause the OSD to run out of capacity due to the number of outstanding discards preventing allocations from being freed. While sync discard could be used in this case to cause backpressure, this might have unacceptable performance implications.
For the most part, as long as enough discards are getting through to a device, then it will stay trimmed enough to maintain acceptable performance. Thus, we can introduce a cap on the pending discard count, ensuring that the queue of allocations to be freed doesn't get too long while also issuing sufficient discards to disk. The default value of 1000000 has ample room for discard spikes (e.g. from snaptrim); it could result in …
> reef: blk/KernelDevice: Introduce a cap on the number of pending discards

- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-bucket-lifecycle.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-lifecycle-list/rgw-bucket-lifecycle-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-tiering-form/rgw-bucket-tiering-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-tiering-form/rgw-bucket-tiering-form.component.ts
- src/pybind/mgr/dashboard/services/rgw_client.py
NOTE:
===
This PR is based on commits from this [PR](https://github.com/ceph/ceph/pull/61781/), after using xmltodict package, we can now edit/add tags in lifecycle rule.
Fixes: https://tracker.ceph.com/issues/70275
https://github.com/user-attachments/assets/d73497bd-0582-4b02-bd24-a3bd911ca217 …
> mgr/dashboard: bucket lifecycle fixes after using xmltodict package

- src/mon/LogMonitor.cc
backport tracker: https://tracker.ceph.com/issues/70379
---
backport of https://github.com/ceph/ceph/pull/61933
parent tracker: https://tracker.ceph.com/issues/54489
> reef: LogMonitor: set no_reply for forward MLog commands

- doc/rados/operations/pools.rst
- qa/tasks/stretch_cluster.py
- qa/tasks/test_netsplit_3az_stretch_pool.py
- qa/workunits/mon/mon-stretch-pool.sh
- src/mon/MonCommands.h
- src/mon/OSDMonitor.cc
**Problem:**
When we enable stretched mode on the pools,
we modify 6 configs on the pool,
namely peering_crush_bucket_count,
peering_crush_bucket_target,
peering_crush_bucket_barrier,
crush_rule, size, min_size.
Out of these, only 3 configs,
namely peering_crush_bucket_count,
peering_crush_bucket_target,
peering_crush_bucket_barrier is reset to 0.
The remaining 3 configs,
namely crush_rule, size,
min_size are not reverted back,
and are still the values that were set with stretch set command.
**Solution:**
The unset command now is required
to specify `crush_rule`, `size`, `min_size`.
New command:
ceph osd pool stretch unset {pool-name} {crush_rule} {size} {min_size}
Fixes: https://tracker.ceph.com/issues/68842 …
> [3AZ] src/mon : Allow user to specify crush_rule, size and min_size when unsetting a stretch pool

- src/mgr/Mgr.cc
backport tracker: https://tracker.ceph.com/issues/65623
---
backport of https://github.com/ceph/ceph/pull/56047
parent tracker: https://tracker.ceph.com/issues/64799
> reef: mgr: process map before notifying clients

- qa/standalone/osd-backfill/osd-backfill-space.sh
backport tracker: https://tracker.ceph.com/issues/69086
---
backport of https://github.com/ceph/ceph/pull/60636
parent tracker: https://tracker.ceph.com/issues/68585
> reef: TEST_backfill_grow fails after finding "num_bytes mismatch" in osd log

- doc/rados/troubleshooting/log-and-debug.rst
This PR updates the [troubeshooting/log-and-debug](https://docs.ceph.com/en/latest/rados/troubleshooting/log-and-debug/) documentation with monitor dedicated logging configurations. It adds all the **mon_cluster_log** config items (addressing [#63354](https://tracker.ceph.com/issues/63354) issue) as well as 3 more items that might be useful to bring forward. All configuration items have been created/moved under a separate **Monitors** section adding it as a new entity to existing OSD, Filestore, MDS and RADOS Gateway sections for better documentation layout.  
More advanced monitor logging setups that are found under /src/common/options/mon.yaml.in have not been added here to keep the documentation comprehensive and straightforward for end-users.
- …
> doc/rados/troubleshooting/log-and-debug: add separate section for Monitors

- .github/workflows/create-backport-trackers.yml
- .github/workflows/stale.yml
Fixes https://www.wiz.io/blog/new-github-action-supply-chain-attack-reviewdog-action-setup …
> workflows: Pin specific SHAs

- src/os/bluestore/BlueFS.cc
- src/test/objectstore/test_bluefs.cc
when extending the log, the sequence was left on a bad state because it would first create a transaction to update with the current seq number but leave the "real" transaction with the same sequence number which should be `extend_log_transaction.seq + 1`.
Signed-off-by: Pere Diaz Bou <pdiabou@redhat.com>
(cherry picked from commit 63f0a0df14c9d8e68be61e374438bc75cef45a1f)
Fixes: https://tracker.ceph.com/issues/69764
- When filling …
> [reef] os/bluestore: fix _extend_log seq advance

- src/mon/MonCommands.h
- src/mon/OSDMonitor.cc
- src/osd/OSDMap.cc
- src/osd/OSDMap.h
backport tracker: https://tracker.ceph.com/issues/70592
---
backport of https://github.com/ceph/ceph/pull/62190
parent tracker: https://tracker.ceph.com/issues/67179
> squid: mon, osd: add command to remove invalid pg-upmap-primary entries

- qa/workunits/rgw/test_rgw_versioning.py
- src/cls/rgw/cls_rgw.cc
- src/test/rgw/rgw_multi/tests.py
Please see the following links for more discussion and info:
https://tracker.ceph.com/issues/63799
https://docs.aws.amazon.com/AmazonS3/latest/userguide/ManagingDelMarkers.html
The PR has been (partially) reverted: https://github.com/ceph/ceph/pull/41897
Tests have been done on the following operations/processes that involve delete markers, and all work well.
- lc
- multisite replication
- delete object with delete marker(s)
- delete delete markers
Fixes: https://tracker.ceph.com/issues/63799
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer …
> rgw: revert PR #41897 to allow multiple delete markers to be created

- src/tools/rbd/action/MirrorPool.cc
The api calls in the mirror pool cli do not always print the error code. Doing so no to make debugging easier.
- …
> rbd: print the return codes on error for mirror pool commands

- PendingReleaseNotes
- doc/rados/operations/read-balancer.rst
Added a release note for "ceph osd rm-pg-upmap-primary" and documentation to complement https://github.com/ceph/ceph/pull/62190. …
> PendingReleaseNotes; doc/rados/operations: document "rm-pg-upmap-primary-{all}" commands

- src/librbd/Utils.cc
- src/librbd/Utils.h
- src/librbd/api/Group.cc
- src/librbd/librbd.cc
> librbd: respect rbd_default_snapshot_quiesce_mode in group_snap_create()

- src/mon/OSDMonitor.cc
backport tracker: https://tracker.ceph.com/issues/70496
---
backport of https://github.com/ceph/ceph/pull/62243
parent tracker: https://tracker.ceph.com/issues/70400
> squid: OSDMonitor: exclude destroyed OSDs from "ceph node ls" output

- src/crimson/os/seastore/btree/btree_range_pin.h
- src/crimson/os/seastore/cache.cc
- src/crimson/os/seastore/cache.h
- src/crimson/os/seastore/cached_extent.cc
- src/crimson/os/seastore/cached_extent.h
- src/crimson/os/seastore/lba_manager.h
- src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.cc
- src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.h
- src/crimson/os/seastore/linked_tree_node.h
- src/crimson/os/seastore/transaction.h
- src/crimson/os/seastore/transaction_manager.cc
- src/crimson/os/seastore/transaction_manager.h
- src/test/crimson/seastore/test_btree_lba_manager.cc
- src/test/crimson/seastore/test_transaction_manager.cc
Cleanups related to cache, extent and transaction, should be straightforward.
- …
> crimson/os/seastore: misc cleanups

- src/pybind/mgr/dashboard/controllers/rgw.py
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-lifecycle-list/rgw-bucket-lifecycle-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-tiering-form/rgw-bucket-tiering-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-tiering-form/rgw-bucket-tiering-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
Fixes: https://tracker.ceph.com/issues/70588
Before:
===
As the tenant was not passed in lifecycle calls made through bucket details > tiering tab, & also account_id was not resolved to the user of the bucket, hence not able to manage the Tiering configuration lifecycle changes
After:
=== 
Account_id is resolved to user_id and tenant is additionally passed to the lifecycle API so as to handle the tenanted bucket scenario
https://github.com/user-attachments/assets/036bd024-d3aa-4874-836c-3b6e0324c38d …
> mgr/dashboard: tenanted bucket lifecycle management fix

- src/pybind/mgr/dashboard/controllers/cephfs.py
- src/pybind/mgr/dashboard/frontend/cypress/e2e/common/forms-helper.feature.po.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/common/urls.po.ts
- src/pybind/mgr/dashboard/frontend/cypress/e2e/filesystems/filesystems.e2e-spec.feature
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.spec.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.html
- src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts
- src/pybind/mgr/dashboard/frontend/src/app/shared/api/cephfs.service.ts
- src/pybind/mgr/dashboard/openapi.yaml
- src/pybind/mgr/dashboard/services/cephfs.py
We can use the newly introduced data and metadata params to create a vol
with those pools.
UI is being intelligent by filtering out the used pools and only uses
the pools that are labeled by cephfs and also not in use. To figure out
a pool is in use or not, we are fetching the pool stats and checking its
used_bytes.
Note: Using ec pools for data pool layout is something discouraged
according to offical doc: https://docs.ceph.com/en/latest/cephfs/createfs/#creating-a-file-system
We can force it but for now I have disabled it entirely in the dashboard
unless people say its okay to do it.
One more extra thing I am doing here is to add a note on deleting a
filesystem that the underlying pools and mds daemons will be removed.
Fixes: https://tracker.ceph.com/issues/70600 …
> mgr/dashboard: use existing pools for cephfs vol creation 

- doc/cephadm/certmgr.rst
Improve the formatting in the section "Configuration" in doc/cephadm/certmgr/cephadm.rst. …
> doc/cephadm: format "Configuration" in cephadm.rst

- src/cephadm/cephadm.py
- src/cephadm/cephadmlib/packagers.py
- src/cephadm/cephadmlib/systemd.py
- src/cephadm/tests/test_util_funcs.py
Log rotation does not happen if logrotate.timer is disabled. It does daily log rotation once enabled.
Fixes: https://tracker.ceph.com/issues/70373
Testing logs:
```
[root@ceph-node-0 ~]# systemctl status logrotate.timer
● logrotate.timer - Daily rotation of log files
Loaded: loaded (/usr/lib/systemd/system/logrotate.timer; enabled; preset: enabled)
Active: active (waiting) since Mon 2025-03-10 10:48:32 UTC; 4min 18s ago
Trigger: Tue 2025-03-11 00:00:00 UTC; 13h left
Triggers: ● logrotate.service
Docs: man:logrotate(8)
man:logrotate.conf(5)
Mar 10 10:48:32 ceph-node-0 systemd[1]: Started logrotate.timer - Daily rotation of log files.
[root@ceph-node-0 ~]# 
```
```
----------
cephadm ['--timeout', '895', 'check-host']
2025-03-20 …
```
> cephadm: Enable logroate.timer service in bootstrap process

- doc/cephadm/services/osd.rst
- qa/suites/orch/cephadm/smoke-small/start.yaml
- qa/suites/orch/cephadm/smoke/start.yaml
- qa/suites/orch/cephadm/upgrade/4-wait.yaml
- src/pybind/mgr/cephadm/module.py
cephadm: link new OSDs to existing managed services
Added logic for new OSDs to correctly link to existing managed services. The create_osds function now dynamically assigns service_id based on matching entries in the spec_store.
Fixes: https://tracker.ceph.com/issues/69378
Test log:
```
[ceph: root@ceph-node-0 ~]# ceph orch ls
NAME                       PORTS  RUNNING  REFRESHED  AGE  PLACEMENT        
osd.all-available-devices               7  10m ago    23h  *            
osd.default                             1  4m ago     -    <unmanaged>  
osd.foo                                 5  10m ago    22h  *        
[ceph: root@ceph-node-0 ~]# ceph orch restart osd.all-available-devices
Scheduled to restart osd.0 on host 'ceph-node-0'
Scheduled to restart osd.8 on host 'ceph-node-0' …
```
> cephadm: link new OSDs to existing managed services

- doc/cephadm/services/rgw.rst
- src/pybind/mgr/cephadm/services/cephadmservice.py
- src/python-common/ceph/deployment/service_spec.py
cephadm: Ensure wildcard SAN is included in RGW self-signed certs
Fix:
- Updated `RgwService` in `cephadmservice.py` to append `*.` before each hostname in `zonegroup_hostnames` when generating certificates if wildcard_enabled flag is set to true.
- This ensures that both the entries including the wildcard entry (example: 's3.cephlab.com' and '*.s3.cephlab.com') are included in the SAN.
- After this fix, virtual host bucket access works without SSL errors.
Tracker: https://tracker.ceph.com/issues/69875
Logs:
```
[ceph: root@ceph-node-0 ~]# cat rgw_spec.yaml 
service_type: rgw 
service_id: foo 
placement: 
label: rgw 
count_per_host: 1 
spec: 
ssl: true  # Required for SSL 
generate_cert: true  
rgw_frontend_port: 8080
wildcard_enabled: true
zonegroup_hostnames:
- s3.cephlab.com
[ceph: …
```
> cephadm: Ensure wildcard SAN is included in RGW self-signed certs

- qa/tasks/radosgw_admin.py
- src/rgw/driver/rados/rgw_bucket.cc
- src/rgw/driver/rados/rgw_bucket.h
- src/rgw/driver/rados/rgw_rest_bucket.cc
backport tracker: https://tracker.ceph.com/issues/69152
---
backport of https://github.com/ceph/ceph/pull/60829
parent tracker: https://tracker.ceph.com/issues/69042
> squid: radosgw-admin: bucket link/unlink support accounts

- src/rgw/driver/rados/rgw_bucket.cc
backport tracker: https://tracker.ceph.com/issues/69213
---
backport of https://github.com/ceph/ceph/pull/60845
parent tracker: https://tracker.ceph.com/issues/69060
> squid: rgw: fix bucket link operation

- src/common/Formatter.cc
- src/common/HTMLFormatter.cc
- src/test/common/CMakeLists.txt
- src/test/common/test_htmlformatter.cc
- src/test/common/test_json_formatter.cc
- src/test/common/test_tableformatter.cc
- src/test/common/test_xmlformatter.cc
backport tracker: https://tracker.ceph.com/issues/69260
---
backport of https://github.com/ceph/ceph/pull/60429
parent tracker: https://tracker.ceph.com/issues/68658
> squid: <common> fix formatter buffer out-of-bounds

- src/rgw/rgw_op.cc
backport tracker: https://tracker.ceph.com/issues/69297
---
backport of https://github.com/ceph/ceph/pull/60771
parent tracker: https://tracker.ceph.com/issues/68982
> squid: rgw/abortmp: Race condition on AbortMultipartUpload
