ceph/ceph

src/rgw/driver/posix/notify.h

backport tracker: https://tracker.ceph.com/issues/69317
---
backport of https://github.com/ceph/ceph/pull/61107
parent tracker: https://tracker.ceph.com/issues/69241

squid: rgw/posix: std::ignore return value of write()

---

src/test/rgw/rgw_multi/tests.py

(cherry picked from commit 55860520b3f44ce3111ee3994495dd018fa8ca92)
Fixes: https://tracker.ceph.com/issues/69131
- …

squid: qa/multisite: add extra checkpoints in datalog_autotrim testcase

---

src/cls/rgw/cls_rgw.cc
src/cls/rgw/cls_rgw_client.cc
src/cls/rgw/cls_rgw_client.h
src/cls/rgw/cls_rgw_ops.h
src/cls/rgw/cls_rgw_types.h
src/rgw/driver/rados/rgw_bucket.cc
src/rgw/driver/rados/rgw_cr_rados.cc
src/rgw/driver/rados/rgw_data_sync.cc
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/rgw_op.cc
src/rgw/rgw_sal.h
src/test/rgw/rgw_multi/tests.py

Fixes tracker.ceph.com/issues/55179 …

squid: rgw: Deleting an object with null version fix

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.ts

Fixes https://tracker.ceph.com/issues/70106 …

mgr/dashboard: KiB not supported size for namespace creation

---

src/client/Client.cc
src/test/client/CMakeLists.txt
src/test/client/ll_api.cc

 client: ll_walk will process absolute paths as relative

---

PendingReleaseNotes
doc/rados/operations/read-balancer.rst

Backport of #62422
Complement to https://github.com/ceph/ceph/pull/62421.
*Note: PendingReleaseNotes was modified to have the release note under the v19.2.2 section. …

squid: PendingReleaseNotes; doc/rados/operations: document "rm-pg-upmap-primary-{all}" commands

---

src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/serve.py
src/pybind/mgr/cephadm/tests/test_cephadm.py
src/pybind/mgr/cephadm/tests/test_spec.py
src/pybind/mgr/orchestrator/_interface.py
src/pybind/mgr/orchestrator/tests/test_orchestrator.py

mgr/cephadm: Deploying prometheus service for the first time, does not update PROMETHEUS_API_HOST url under mgr module
**RCA**: We are seeing this issue only when cluster is deployed with  --skip-monitoring-stack, it is happening because while deploying prometheus, we maintain a daemon list for which post deploy operations are required (which is self.mgr.requires_post_actions), but then prometheus module  gets enabled and because of that mgr gets respawned before performing post deploy operations (on self.mgr.requires_post_actions set) of that service. 
**Fix** : Added a new parameter 'pending_daemon_config: bool' in DaemonDescription class. While daemon creation, if daemon has post config actions then it will be set to true, and once actions are performed it will be set to false. And we …

mgr/cephadm: Deploying prometheus service for the first time, does not update PROMETHEUS_API_HOST url under mgr module

---

qa/suites/orch/cephadm/smb/tasks/deploy_smb_ctdb_node_gone_state.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_clustering_ips.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_ctdb_res_basic.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_ctdb_res_dom.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_ctdb_res_ips.yaml

Try to use the virt_sandbox_use_netlink selinux boolean to avoid getting selinux AVC errors in smb tests using ctdb. Some tests run ctdb with public addresses and the scripts that ctdb uses to manage those IPs calls ss which uses netlink which can cause selinux denials. Attempt to work around that problem by using a selinux boolean documented in `container_selinux(8)`. …

qa/cephadm/smb: set virt_sandbox_use_netlink selinux bool on ctdb tests

---

src/rgw/driver/rados/rgw_putobj_processor.cc
src/rgw/driver/rados/rgw_rados.cc

rgw: fix data corruption when rados op return ETIMEDOUT
when rados op return ETIMEOUT, rgw can't determine whether or not the rados op succeeded, To avoid data corruption, when return -ETIMEDOUT, we should clear all objects in RadosWriter
Signed-off-by: Shasha Lu <lu.shasha@aishu.cn>
backport tracker: https://tracker.ceph.com/issues/69248 …

squid: rgw: fix data corruption when rados op return ETIMEDOUT

---

src/common/options/global.yaml.in

"mon_warn_pg_not_deep_scrubbed_ratio" to the confval definition of that variable. Although this variable contains the string "mon", it is set on the Manager. I have added a note to direct users to set this value on the Manager. …

src/common: add guidance for deep-scrubbing ratio warning

---

src/rgw/rgw_rest.cc

backport tracker: https://tracker.ceph.com/issues/69295
---
backport of https://github.com/ceph/ceph/pull/60970
parent tracker: https://tracker.ceph.com/issues/69139

squid: rgw: append query string to redirect URL if present

---

src/common/versioned_variant.h
src/include/ceph_assert.h
src/include/denc.h
src/include/encoding.h
src/librbd/journal/Types.cc
src/mds/CInode.cc
src/mds/FSMap.cc
src/mds/MDCache.cc
src/messages/MClientReply.h
src/mon/MgrMap.h
src/mon/mon_types.h
src/osd/ECMsgTypes.cc
src/osd/OSDMap.cc
src/osd/osd_types.cc
src/rgw/driver/rados/rgw_obj_manifest.h
src/rgw/rgw_lc.h
src/rgw/rgw_meta_sync_status.h
src/rgw/rgw_pubsub.h
src/rgw/rgw_zone_types.h
src/test/common/CMakeLists.txt
src/test/common/test_decode_start_v_checker.cpp

Typical problem found in recent reviews of dencoding changes is missed increment of the version number passed to `DECODE_START()` macro in a decoder.
It's easy to overlook and hard to find as the number is used for rarely happening explicit breaks of schema compatibility.
This commit brings compile-time checks for `struct_v` in decoders (and for `denc` also in encoders) to find a situation when it's compared against version higher than declared using the `DECODE_START(v, ...)` macro.
Additionally, the patch fixes the currently existing issues of this genre buried across the entire code base.
--------------
The goldbot snippet is available [here](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0 …

dencoding: check struct_v against DECODE_START(v, ...) at compile-time

---

src/common/options.h

clang 20 complains when compiling a user-defined literal operator with spaces before the underscore. so let's drop the space to be compliant to
[CWG2521](https://cplusplus.github.io/CWG/issues/2521.html).
```
/home/kefu/dev/ceph/src/common/options.h:415:41: warning: identifier '_min' preceded by whitespace in a literal operator declaration is deprecated [-Wdeprecated-literal-operator]
415 | constexpr unsigned long long operator"" _min (unsigned long long min) {
|                              ~~~~~~~~~~~^~~~
|                              operator""_min
``` …

common: remove spaces before literal operator

---

qa/workunits/rbd/cli_generic.sh
src/pybind/mgr/rbd_support/schedule.py

mgr/rbd_support: always parse interval and start_time in Schedules::remove()

---

src/librbd/Journal.cc
src/librbd/journal/OpenRequest.cc
src/librbd/journal/Replay.cc
src/librbd/journal/Types.cc
src/librbd/journal/Types.h
src/librbd/mirror/DisableRequest.cc
src/test/librbd/journal/test_Entries.cc
src/test/rbd_mirror/image_replayer/journal/test_mock_EventPreprocessor.cc
src/tools/rbd_mirror/image_replayer/Utils.cc
src/tools/rbd_mirror/image_replayer/journal/EventPreprocessor.cc
src/tools/rbd_mirror/image_replayer/journal/PrepareReplayRequest.cc

migrate from boost::variant to std::variant
Complete migration started in commit 017f3339c, replacing boost::variant with std::variant throughout the librbd codebase. This change is part of our ongoing effort to reduce third-party dependencies by leveraging C++ standard library alternatives where possible.
Benefits include:
- Improved code readability and maintainability
- Reduced external dependency surface
- More consistent API usage with other components
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst …

librbd: migrate from boost::variant to std::variant

---

src/rgw/rgw_admin.cc

backport tracker: https://tracker.ceph.com/issues/70343
---
backport of https://github.com/ceph/ceph/pull/62018
parent tracker: https://tracker.ceph.com/issues/70219

squid: radosgw-admin: lower default thread pool size

---

src/rgw/rgw_zone_types.h

This commit fixes an undetected merge conflict between PRs #61745 and #60159. The dencoding problem has been introduced very recently, it is straightforward and causes failures of the make check bot everywhere, therefore -- if no objections -- I want to merge this patch without the Teuthology testing.
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_zone_types.h:650:21: error: call to consteval function 'StructVChecker<'\x03'>::CheckingWrapper::CheckingWrapper' is not a constant expression
650 |     if (struct_v >= 4) {
|                     ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/include/denc.h:1804:7: note: subexpression not valid in a constant expression
1804 |       consteval_assert(
|       ^~~~~~~~~~~~~~~~~
1805 |         c <= MaxV,
| …
```

rgw: fix the version in DECODE_START() of RGWZoneGroupPlacementTier

---

src/ceph-volume/ceph_volume/devices/lvm/zap.py
src/ceph-volume/ceph_volume/tests/devices/test_zap.py

backport tracker: https://tracker.ceph.com/issues/70368
---
backport of https://github.com/ceph/ceph/pull/62173
parent tracker: https://tracker.ceph.com/issues/70363

reef: ceph-volume: allow zapping partitions on multipath devices

---

container/Containerfile

backport tracker: https://tracker.ceph.com/issues/70154
---
backport of https://github.com/ceph/ceph/pull/61733
parent tracker: https://tracker.ceph.com/issues/69869

squid: container: small container image improvements

---

container/Containerfile

backport tracker: https://tracker.ceph.com/issues/70153
---
backport of https://github.com/ceph/ceph/pull/61733
parent tracker: https://tracker.ceph.com/issues/69869

reef: container: small container image improvements

---

qa/suites/rgw/verify/validater/lockdep.yaml

lockdep.yaml was only enabling lockdep for osd/mon. if it's actually worth running, we should enable it for radosgws too
<details> …

qa/rgw: enable lockdep config for radosgw

---

install-deps.sh
run-make-check.sh
src/script/build-with-container.py
src/script/buildcontainer-setup.sh
src/script/lib-build.sh
src/script/run-make.sh

Alternative to #62308 
---
Fixes: https://tracker.ceph.com/issues/70470
Fix building the image on docker where --pull=always is not a valid option.
---
Fix a build issue on ubuntu where the clang version was too low. This was a recent regression in the bwc container image after commit https://github.com/ceph/ceph/commit/9614ad3834ad275e15eb7572b7ad6c19c9b17ab6 and subsequent changes to use C++20 were merged.
---
Fix a couple additional speed bumps found immediately after the build issues were resolved. This doesn't mean make check runs to success but I'm confident that make check will run now. …

 build-with-container: fix container build on docker and clang setup on ubuntu jammy  [v2]

---

src/rgw/radosgw-admin/radosgw-admin.cc
src/test/rgw/bucket_notification/api.py
src/test/rgw/bucket_notification/test_bn.py

https://tracker.ceph.com/issues/70661 …

RGW|Bucket Notification: fix for v2 topics rgw-admin list operation

---

src/common/ceph_context.h

Previously, we relied on the __GNUC__ macro to check for std::atomic<std::shared_ptr>
support, which was inaccurate. This approach failed with Clang builds using libstdc++,
even when the feature was implemented. The warning looks like:
```
/usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/shared_ptr_atomic.h:131:5: note: 'atomic_load_explicit<std::vector<entity_addrvec_t>>' has been explicitly marked deprecated here
131 |     _GLIBCXX20_DEPRECATED_SUGGEST("std::atomic<std::shared_ptr<T>>")
|     ^
```
This change uses a standard-compliant feature test macro (__cpp_lib_atomic_shared_ptr)
to correctly detect support for std::atomic<std::shared_ptr>. This resolves compilation
issues and improves portability across different compilers and standard library
implementations. …

common/ceph_context: Fix std::atomic<std::shared_ptr> compatibility

---

monitoring/ceph-mixin/dashboards/rbd.libsonnet
monitoring/ceph-mixin/dashboards_out/rbd-details.json

The image filter on the RBD Details grafana panel is using a query with a typo "label_values(ceph_rbd_read_ops{cluster=~\"$cluster\", , pool=\"$pool\"}, image)". The extra comma needs to be removed.
Fixes: https://tracker.ceph.com/issues/70653 …

mgr/dashboard: fix image filter's query on rbd-details grafana panel

---

doc/cephfs/fs-volumes.rst
qa/tasks/cephfs/test_volumes.py
src/pybind/mgr/volumes/fs/operations/subvolume.py
src/pybind/mgr/volumes/fs/operations/versions/subvolume_base.py
src/pybind/mgr/volumes/fs/operations/versions/subvolume_v1.py
src/pybind/mgr/volumes/fs/operations/versions/subvolume_v2.py
src/pybind/mgr/volumes/fs/volume.py
src/pybind/mgr/volumes/module.py

pybind/mgr/volumes: configure case sensitivity

---

src/common/options/osd.yaml.in

osd_max_scrubs takes effect even though mclock is used.
```
$ ceph config show-with-defaults osd.0 | grep '^osd_max_scrubs' | sed -E -e 's/( +)/ /g'
osd_max_scrubs 3 default
$ ceph config show-with-defaults osd.0 | grep '^osd.* override ' | sed -E -e 's/( +)/ /g'
osd_delete_sleep 0.000000 override
osd_delete_sleep_hdd 0.000000 override
osd_delete_sleep_hybrid 0.000000 override
osd_delete_sleep_ssd 0.000000 override
osd_pg_delete_cost 15728640 override
osd_recovery_sleep 0.000000 override
osd_recovery_sleep_hdd 0.000000 override
osd_recovery_sleep_hybrid 0.000000 override
osd_recovery_sleep_ssd 0.000000 override
osd_scrub_sleep 0.000000 override
osd_snap_trim_sleep 0.000000 override
osd_snap_trim_sleep_hdd 0.000000 override
osd_snap_trim_sleep_hybrid 0.000000 override …
```

squid: common/options: fix the description of osd_max_scrubs

---

doc/dev/release-process.rst

Document that container images are not built by the ceph-build job, but must be done manually after the package signing and upload to download.ceph.com.
(cherry picked from commit 8abba8b150346ffc6486efb3520c6445c56560a3) …

reef: doc/dev/release-process.rst: release builds cannot build containers

---

doc/dev/release-process.rst

Document that container images are not built by the ceph-build job, but must be done manually after the package signing and upload to download.ceph.com.
(cherry picked from commit 8abba8b150346ffc6486efb3520c6445c56560a3) …

squid: doc/dev/release-process.rst: release builds cannot build containers

---

qa/workunits/rbd/luks-encryption.sh
qa/workunits/rbd/rbd-nbd.sh

backport tracker: https://tracker.ceph.com/issues/70377
---
backport of https://github.com/ceph/ceph/pull/62189
parent tracker: https://tracker.ceph.com/issues/66419

squid: qa/workunits/rbd: wait for resize to be applied in rbd-nbd

---

src/common/options/global.yaml.in

"mon_warn_pg_not_deep_scrubbed_ratio" to the confval definition of that variable. Although this variable contains the string "mon", it is set on the Manager. I have added a note to direct users to set this value on the Manager.
(cherry picked from commit aeef59a50ee31072648ba0c7436b6522137614cd) …

reef: src/common: add guidance for deep-scrubbing ratio warning

---

src/rgw/rgw_acl_s3.cc

backport tracker: https://tracker.ceph.com/issues/69811
---
backport of https://github.com/ceph/ceph/pull/61368
parent tracker: https://tracker.ceph.com/issues/69527

squid: rgw/s3: remove local variable 'uri' that shadows member variable

---

src/tools/rbd/action/MirrorImage.cc
src/tools/rbd/action/MirrorPool.cc

rbd: "rbd mirror pool status --verbose" output fixups

---

src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/buckets.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/configuration.e2e-spec.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/rgw/configuration.po.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts

The condition to disable/enable encryption checkbox on bucket form is broken because of the new structure of the get encryption config API response.
Fixes: https://tracker.ceph.com/issues/70646 …

mgr/dashboard: fix bucket form encryption checkbox

---

src/osd/OSD.cc

We keep superblock bitstream in 2 places:
- "osd_superblock" object's data stream
- "osd_superblock" object's omap key named "osd_superblock"
The recovery procedure works fine.
But if data stream is corrupted on ObjectStore::write() request BlueStore might require to read the old data from object's allocation unit.
This will cause assert like:
"BlueStore.cc: 15865: FAILED ceph_assert(r >= 0 && r <= (int)tail_read)"
The solution is to remove object before writing to it, clearing any reason for the read-on-write.
Replication, using vstart cluster:
```
> OSD=1 MON=1 FS=0 RGW=0 ../src/vstart.sh -l -n
>  ../src/stop.sh
> OBJECT=$(./bin/ceph-objectstore-tool --no-mon-config --data-path dev/osd0/ --op meta-list |grep osd_superblock)
> ./bin/ceph-objectstore-tool --no-superblock --no-mon-config …
```

osd/OSD.cc: make osd_superblock recovery more robust

---

src/common/options/global.yaml.in

"mon_warn_pg_not_scrubbed_ratio" to the confval definition of that variable. Although this variable contains the string "mon", it is set on the Manager. I have added a note to direct users to set this value on the Manager.
This issue is part of a small project that also encompasses https://github.com/ceph/ceph/pull/62459, which is associated with commit aeef59a50ee31072648ba0c7436b6522137614cd …

src/common: add guidance for mon_warn_pg_not_scrubbed

---

src/blk/kernel/KernelDevice.cc
src/blk/kernel/KernelDevice.h

blk/kernel: New perf counter to view amount of discard threads.

---

src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/bluefs_types.cc
src/os/bluestore/bluefs_types.h
src/os/bluestore/bluestore_tool.cc
src/test/objectstore/store_test.cc
src/test/objectstore/test_bluefs.cc

Effective allocation unit is still bluefs_alloc_size to avoid performance penalties.
Unaligned tailing part of device's space  is marked as non-free if no allocations exist in this ares. This allows to maintain relevant allocation map unfragmented if all allocation requests are aligned with use bluefs_alloc_size.
Plus some cleanup.
Plus some helpers.
Fixes: https://tracker.ceph.com/issues/68772 …

os/bluestore: use block size (4K) as minimal allocation unit for dedicated DB/WAL volumes

---

src/erasure-code/isa/ErasureCodeIsaTableCache.cc

before this change, we allocate coefficients table with malloc() in ErasureCodeIsaDefault::prepare(), but free them using delete.
so, in this change, we use new [] and delete [] to allocate and free them, to be more consistent, and to silence this warning.
this issue was identified by AddressSanitizer:
```
2025-03-22T04:27:58.210 INFO:tasks.ceph.osd.3.smithi102.stderr:==42899==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs free) on 0x611000570d40
2025-03-22T04:27:58.253 DEBUG:teuthology.orchestra.run.smithi102:> sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 120 env ASAN_OPTIONS=detect_leaks=0,detect_odr_violation=0,alloc_dealloc_mismatch=0 LD_PRELOAD=/lib64/libasan.so.6 ceph --cluster ceph osd pool set cephfs_data_ec …
```

erasure-code: use new/delete to alloc/free coefficients array

---

src/osd/OSD.cc

Fixes: https://tracker.ceph.com/issues/69724 …

osd: fix the tiering agent's shutdown wrt the OSD fast shutdown

---

src/common/bitset_set.h
src/common/fmt_common.h
src/common/interval_map.h
src/common/mini_flat_map.h
src/crimson/osd/scrub/scrub_machine.h
src/include/interval_set.h
src/osd/scrubber/scrub_machine.h

Replace custom has_formatter concept with fmtlib's fmt::formattable
- Deprecate usage of fmt::has_formatter
- Resolve compiler warnings with recent fmtlib versions
The custom concept of has_formatter is no longer necessary with recent updates to the fmtlib library, as fmt::formattable was introduced in fmtlib v11.0.0. By switching to fmt::formattable, we simplify our code and stop using the deprecated `fmt::has_formatter` template. …

src: migrate to fmt::formattable for format support

---

src/librbd/ImageCtx.cc
src/librbd/ImageCtx.h

Update shared pointer atomic operations to use C++20's std::atomic<std::shared_ptr<T>> instead of the deprecated atomic_store functions. This change addresses deprecation warnings from GCC-15's libstdc++ where atomic shared pointer operations outside the std::atomic class are being phased out:
```
/home/kefu/dev/ceph/src/librbd/ImageCtx.cc:1010:5: warning: 'atomic_store<neorados::IOContext>' is deprecated: use 'std::atomic<std::shared_ptr<T>>' instead [-Wdeprecated-declarations]
1010 |     atomic_store(&data_io_context, ctx);
|     ^
/usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/shared_ptr_atomic.h:181:5: note: 'atomic_store<neorados::IOContext>' has been explicitly marked deprecated here
181 |     _GLIBCXX20_DEPRECATED_SUGGEST("std::atomic<std::shared_ptr<T>>")
| …
```

librbd: replace deprecated atomic_store with std::atomic<shared_ptr>

---

qa/tasks/radosgw_admin.py
qa/workunits/dencoder/test_readable.py
src/tools/cephfs/top/cephfs-top

Removes unused `global` statements to fix flake8 F824 errors.
Recent flake8 runs were failing with:
```
./tasks/radosgw_admin.py:330:5: F824 `global log` is unused: name is never assigned in scope
./workunits/dencoder/test_readable.py:99:5: F824 `global incompat_paths` is unused: name is never assigned in scope
./workunits/dencoder/test_readable.py:164:5: F824 `global backward_compat` is unused: name is never assigned in scope
./workunits/dencoder/test_readable.py:165:5: F824 `global fast_shouldnt_skip` is unused: name is never assigned in scope
```
Since these variables are only being referenced and not assigned within their scopes, the `global` declarations are unnecessary and can be safely removed. This change:
- Removes all flagged `global` statements
- Fixes the failing flake8 checks …

cephfs-top, qa: Remove unnecessary global statements in tests

---

qa/suites/rgw/verify/tasks/rados-pool-quota.yaml

Fixes: https://tracker.ceph.com/issues/70712
<details>
- `jenkins test signed` [Jenkins Job](https://jenkins.ceph.com/job/ceph-pr-commits/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-pr-commits/config/definitions/ceph-pr-co …

qa/rgw: fix ignorelist entry for 'HEALTH_WARN 1 pool(s) full'

---

src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/services/oauth2_proxy.py

mgr/cephadm: making mgmt-gateway an oauth2-proxy dependency

---

src/pybind/mgr/cephadm/services/smb.py

Change the warning level for the unexpected uri scheme detected log event when determining caps based off of the uri. The log gets triggered by `rados:mon-config-key:*` type uris and those are common now so the warning is just noise. …

mgr/cephadm: do not log unexpected uri scheme at warning level

---

src/rgw/rgw_rest_swift.cc

There is a critical ACL-related swift issue in Squid and main branch which doesn't allow one to share containers with users from different tenants.
The issue was introduced in https://github.com/ceph/ceph/commit/d82ff164505cd7a7abe6937879052ad03f1da939 and backported to Squid by: https://github.com/ceph/ceph/commit/f0fb48d19409c012ae8422304b63ca013c1055db
As a result rgw couldn't find the correct bucket in case the user from different tenant was given access to the container using ACL, because rgw started to look inside the user's tenant, but not the tenant from the request.
The change has broken 10 tests in [Tempest ACL](https://github.com/openstack/tempest/blob/master/tempest/api/object_storage/test_container_acl.py) and [Tempest ACL …

rgw: fixing tempest ObjectTestACLs and ObjectACLsNegativeTest cases

---

src/rgw/driver/rados/rgw_sal_rados.cc

Unlink the bucket in bucket creation request if the bucket entry point has been deleted in a concurrent bucket deletion request.
This issue is a racing condition that can only be consistently reproducible through hacking the code so it's hard to create a test case for it.  
Fixes: https://tracker.ceph.com/issues/69738 …

rgw: cleanup orphaned bucket entry in <user>.buckets OMAP

---

src/cephadm/cephadmlib/daemons/ceph.py

Previous work increased the aio-max-nr to 1048576 [1].
Crimson-osd might need this value to be larger in order to deploy correctly.
In future work, if this turns out to be tricky, we can update cephadm to make use of `90-ceph-osd.conf` file which changes between build types. See possible usage in sysctl.py.
For now, increasing the value for any "Class OSD" should work and is the simplest solution.
[1] https://github.com/ceph/ceph/pull/41264 …

cephadm/cephadmlib/daemons/ceph.py: increase aio-max-nr

---

CMakeLists.txt
src/common/options/CMakeLists.txt

Removes the invalid PRE_BUILD argument from add_custom_command(OUTPUT) calls that was triggering CMake warnings. The PRE_BUILD option is only valid for target-based custom commands and specifically with Visual Studio generators.
Additionally sets the CMP0175 policy to NEW to ensure CMake fails on invalid arguments to add_custom_command(), helping catch similar issues earlier in the development process.
This change:
- Removes unnecessary PRE_BUILD argument from OUTPUT-based custom commands
- Sets CMP0175 policy to enforce validation of add_custom_command() arguments
- Resolves CMake warning in src/common/options/CMakeLists.txt
Reference:
https://cmake.org/cmake/help/latest/command/add_custom_command.html#build-events
The CMake warning looks like:
```
CMake Warning (dev) at …
```

cmake: do not pass PRE_BUILD to add_custom_command(OUTPUT)

---

src/dmclock/sim/src/ssched/ssched_server.h
src/dmclock/src/dmclock_recs.h
src/dmclock/src/dmclock_server.h
src/dmclock/test/test_dmclock_server.cc

This change is part of a broader effort to reduce dependencies on third-party libraries by leveraging C++ standard library alternatives.
Migrating from boost::variant to std::variant improves code readability and maintainability while reducing external dependencies. …

dmclock: migrate from boost::variant to std::variant

---

src/osd/scrubber/pg_scrubber.cc
src/osd/scrubber/pg_scrubber.h
src/osd/scrubber/scrub_machine.h
src/osd/scrubber/scrub_machine_if.h

Reducing the amount of mocking required when creating an instance
of class PgScrubber for unit-tests.
1. (a minor change) removing the unneeded PG ref from the preemption_data_t subobject;
2. decoupling the PgScrubber objects from the scrub FSM:
The scrubber FSM has always been accessing the PgScrubber
object via an abstract interface (ScrubMachineListener).
But the reverse was not true: the PgScrubber owned a unique_ptr
directly to an instance of Scrubber::ScrubMachine.
This PR introduces a new interface, ScrubFsmIf, that is
implemented by the ScrubMachine. This simplifies
unit-testing the PgScrubber, as we can now inject a mock
implementation of the FSM interface.

osd/scrub: improve PgScrubber testability

---

src/libcephfs_proxy/proxy_mount.c

When ceph_ll_lookup() is done on ".", it returns a new reference to the parent inode itself. However this may cause some delays or problems on disconnect (see https://tracker.ceph.com/issues/70553).
However, if "." is replaced by "", we still get a new reference to the parent inode (which is what we really need), without causing any side effect.
This patch uses this alternative in the libcephfs proxy to avoid the problem.
- When …

libcephfs_proxy: workaround for delays and hangs in the proxy

---

ceph.spec.in
etc/sysctl/90-crimson-osd.conf.in
etc/sysctl/CMakeLists.txt

See https://github.com/ceph/ceph/commit/36326dc7104fc2f20f19d51b6f618a029ba072d7.
Clasical osd packages are adjusting the aio-max-nr value
from the default of 65536 to 1048576 as the default is too low
for some deployments. The same should be applied for Crimson's
packages. …

ceph.spec.in,debian/rules: aio-max-nr for Crimson

---

src/crimson/osd/object_context.h
src/crimson/osd/object_context_loader.cc
src/crimson/osd/object_context_loader.h
src/crimson/osd/pg.cc
src/crimson/osd/recovery_backend.cc
src/crimson/osd/recovery_backend.h
src/crimson/osd/replicated_recovery_backend.cc
src/crimson/osd/replicated_recovery_backend.h

crimson: take read lock on replica during final push commit

---

src/rgw/rgw_op.cc

backport tracker: https://tracker.ceph.com/issues/69576
---
backport of https://github.com/ceph/ceph/pull/61384
parent tracker: https://tracker.ceph.com/issues/69539

squid: rgw: S3 Delete Bucket Policy should return 204 on success

---

src/rgw/driver/rados/rgw_user.cc

backport tracker: https://tracker.ceph.com/issues/69580
---
backport of https://github.com/ceph/ceph/pull/61285
parent tracker: https://tracker.ceph.com/issues/69462

squid: rgw: /admin/user api dumps account-related user info

---

src/rgw/driver/rados/rgw_log_backing.cc

Fitting a retry loop around a call that took the lock changed the logic to potentially have the lock be used after moving.
Thanks to Suyash Dongre suyashd999@gmail.com for finding it.
This patch also fixes a lock being held across an I/O operation.
Fixes: https://tracker.ceph.com/issues/66340
(cherry picked from commit 80cf2ca3b44246ad8f2e333182b3c8b1835a71f7)
Fixed: https://tracker.ceph.com/issues/68053 …

squid: rgw/multisite: Fix use-after-move in retry logic in logbacking

---

doc/dev/release-process.rst

The manual instructions for building release containers were complex and required access to an arm64 host; that was just too much, so I've created a Jenkins job to build all of the prerelease artifacts (see https://github.com/ceph/ceph-build/pull/2342). Change the documentation to reflect that. …

doc/dev/release-process.rst: document new Jenkins job for containers

---

doc/dev/release-process.rst

Make minor usage and markup changes to doc/dev/release-process.rst to follow up on Dan Mick's contribution in https://github.com/ceph/ceph/pull/62610. …

doc/dev/release-process: followup on PR#62610

---

doc/rados/configuration/ceph-conf.rst

doc/rados/configuration: Correct admonition in ceph-conf.rst …

doc/rados/configuration: Correct admonition in ceph-conf.rst

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml

Fixes: https://tracker.ceph.com/issues/70745 …

mgr/dashboard: enable ha by default on subsystem POST API

---

monitoring/ceph-mixin/dashboards/host.libsonnet
monitoring/ceph-mixin/dashboards_out/host-details.json

OSDs panel in host-details grafana dashboard shows total of all OSDs across all hosts even if a particular host is selected from the ceph_hosts filter. This PR intends to fix this issue
Fixes: https://tracker.ceph.com/issues/70226
https://github.com/user-attachments/assets/9b7e155e-4113-499c-a4c1-12847031a039
- When filling out the below checklist, you may click boxes directly in …

monitoring: Fix OSDs panel in host-details grafana dashboard

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-domain-setting-modal/smb-domain-setting-modal.component.html

Fixes: https://tracker.ceph.com/issues/70692
NEW:
[screen-capture (88).webm](https://github.com/user-attachments/assets/0ce093b1-b62f-4805-9382-953ace7c32ad)
OLD:
[scroll-bug.webm](https://github.com/user-attachments/assets/371f4af8-899d-42bc-b39c-2c5c8aeef963) …

mgr/dashboard: fix domain settings modal scrollable

---

src/pybind/mgr/cephadm/services/nvmeof.py
src/pybind/mgr/dashboard/services/nvmeof_conf.py
src/pybind/mgr/dashboard/tests/__init__.py
src/pybind/mgr/dashboard/tests/test_nvmeof_cli.py

Happens from 19.2.0 to any of the latest upgrade
During upgrade I get
```
Failed to set Dashboard config for nvmeof: dashboard nvmeof-gateway-add failed: JSON array/object not allowed {"prefix": "dashboard nvmeof-gateway-add", "name": "nvmeof.rbd", "group": null, "daemon_name": "nvmeof.rbd.ceph-node-01.irpssg"} retval: -22
```
which is fixed by handling the group_name when its not there in spec.
And the other error was
```
Failed to set Dashboard config for nvmeof: dashboard nvmeof-gateway-add failed: Traceback (most recent call last): File "/usr/share/ceph/mgr/mgr_module.py", line 1864, in _handle_command return CLICommand.COMMANDS[cmd['prefix']].call(self, cmd, inbuf) File "/usr/share/ceph/mgr/mgr_module.py", line 499, in call return self.func(mgr, **kwargs) File …
```

mgr/dashboard: upgrading nvmeof doesn't update configuration

---

src/os/bluestore/Writer.cc

We should not use 'unused' when allocation unit = disk block.
Blobs with 'unused' cannot be split which makes shard resharding more problematic and spanning blobs more pronounced. …

os/bluestore/write-v2: Tune down usage of 'unused'

---

qa/tasks/radosgw_admin.py
qa/workunits/dencoder/test_readable.py
src/tools/cephfs/top/cephfs-top

backport tracker: https://tracker.ceph.com/issues/70754
---
backport of https://github.com/ceph/ceph/pull/62567
parent tracker: https://tracker.ceph.com/issues/70752

reef: cephfs-top, qa: Remove unnecessary global statements in tests

---

qa/tasks/radosgw_admin.py
qa/workunits/dencoder/test_readable.py
src/tools/cephfs/top/cephfs-top

backport tracker: https://tracker.ceph.com/issues/70753
---
backport of https://github.com/ceph/ceph/pull/62567
parent tracker: https://tracker.ceph.com/issues/70752

squid: cephfs-top, qa: Remove unnecessary global statements in tests

---

doc/rados/configuration/ceph-conf.rst

(cherry picked from commit 5ff8e3e4381764822383ba769b2c4e73876fbc0c) …

squid: doc/rados/configuration: Correct admonition in ceph-conf.rst

---

doc/rados/configuration/ceph-conf.rst

(cherry picked from commit 5ff8e3e4381764822383ba769b2c4e73876fbc0c) …

reef: doc/rados/configuration: Correct admonition in ceph-conf.rst

---

src/pybind/mgr/cephadm/module.py

If a host was in maintenance mode, we should make sure to check
all of the host information again once it's taken out even if
it hasn't been long enough for the daemon/device/facts etc. cache
to timeout. Some users may make changes to things like the node's
hardware or OS during maintenance mode that we should make sure to
pick up as soon as possible …

mgr/cephadm: trigger host metadata refresh when taking host out of maintenance

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/crush-rule-form-modal/crush-rule-form-modal.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/crush-rule-form-modal/crush-rule-form-modal.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/erasure-code-profile-form/erasure-code-profile-form-modal.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/erasure-code-profile-form/erasure-code-profile-form-modal.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/classes/crush.node.selection.class.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/erasure-code-profile.ts

[screen-capture (95).webm](https://github.com/user-attachments/assets/8606ba02-1298-4eb5-a62f-2e50ed3efb39)
Fixes: https://tracker.ceph.com/issues/70764 …

mgr/dashboard: add enhancements for pool rulest

---

src/pybind/mgr/rgw/module.py
src/python-common/ceph/deployment/service_spec.py

Specifically by setting the data_pool_attributes field in the RGW spec. For example
```
service_type: rgw
service_id: my_realm.my_zone
placement:
count: 2
spec:
data_pool_attributes:
type: ec
k: 6
m: 2
rgw_realm: my_realm
rgw_zone: my_zone
rgw_zonegroup: my_zonegroup
```
would create the my_zone.rgw.buckets.data pool as an ec pool with a new ec porfile with k=8 and m=2. Currently the ec profile fields this spec will make use of
are only "k", "m", "pg_num" and "crush-device-class". If other attributes are set, or if the pool type is "replicated" the key value pairs are assumed to
be ones that can be passed to the "ceph osd pool create" command. The other pools for the rgw zone (e.g. buckets index pool) are all made as replicated pool with
defaults settings …

mgr/rgw: add ability for rgw realm bootstrap to create pools

---

src/common/assert.cc
src/common/options/global.yaml.in
src/common/perf_histogram.cc
src/crimson/os/alienstore/alien_store.cc
src/crimson/osd/scheduler/mclock_scheduler.cc
src/include/ceph_assert.h
src/librbd/crypto/CryptoContextPool.h
src/mon/Monitor.cc
src/os/bluestore/BlueStore.cc
src/os/bluestore/bluestore_types.h
src/osd/scheduler/OpScheduler.cc
src/test/CMakeLists.txt
src/test/ceph_assert.cc
src/test/crimson/seastore/test_extent_allocator.cc
src/tools/immutable_object_cache/ObjectCacheStore.cc

The worry I had was about that the cold handlers of `ceph_assert` cannot be marked as `noreturn`.
As bypassing the `abort()` within them requires the ability to resume execution after the assert is hit, compilers are
not allowed anymore to optimize these returns out.
To estimate the impact on performance, let's analyze a snippet and the differences in the correpsonding machine codes.
```cpp
void PeeringState::clear_blocked_outgoing() {
ceph_assert(orig_ctx);
ceph_assert(rctx);
messages_pending_flush = std::optional<BufferedRecoveryMessages>();
}
```
```
0000000000e3cf90 <PeeringState::clear_blocked_outgoing()>:
e3cf90:       48 83 ec 08             sub    $0x8,%rsp
e3cf94:       48 83 bf e0 00 00 00    cmpq   $0x0,0xe0(%rdi)
e3cf9b:       00
e3cf9c:       74 3d                   je …
```

common, *: make the abort() in ceph_assert() bypassable

---

qa/workunits/rados/test-clay-profiles.sh
src/erasure-code/clay/ErasureCodeClay.cc

Fix validation logic for `d` in CLAY erasure code profiles
Updated validation to ensure `d` satisfies `k + 1 <= d <= k + m - 1`.
This change aligns the implementation with the documented constraints
for CLAY erasure code profiles, ensuring consistent behavior and avoiding
undefined scenarios.
Fixes: https://tracker.ceph.com/issues/69506 …

erasure-code: clay wrong d calculation

---

doc/mgr/smb.rst
src/pybind/mgr/smb/enums.py
src/pybind/mgr/smb/module.py
src/pybind/mgr/smb/resources.py
src/pybind/mgr/smb/results.py
src/pybind/mgr/smb/tests/test_smb.py

Add a `--results=[collapsed|full]` option to the `ceph smb show` command. This can be used to request/prevent the show command from collapsing a single valued list result to just the resource in the list.
Add `--password-filter=[none|base64|hidden]` to the `ceph smb show` command as well as `--password-filter` and `--password-filter-out` options to `ceph smb apply`, `ceph smb cluster create` and a few other related commands. The password filter is not a security mechanism - but can be used to obscure passwords and prevent casual shoulder surfers from seeing password values. Note that `hidden` intentionally loses information - replacing the password with a fixed number of asterisks. This filter mode is _not_ supported for --password-filter for input values but will be supported by …

mgr/smb: additional input and output controls

---

src/pybind/mgr/cephadm/services/cephadmservice.py
src/python-common/ceph/deployment/service_spec.py

This means with a spec like
```
service_type: rgw
service_id: foo
service_name: rgw.foo
placement:
hosts:
- vm-00
networks:
- 192.168.122.0/24
spec:
only_bind_port_on_networks: true
```
cephadm will search for an IP address within 192.168.122.0/24 and have the RGW daemon only bind on that IP rather than on all networks. What RGW binds to is controlled by the "rgw_frontends" setting for the rgw daemon, so what cephadm write there is all that is modified by this commit.
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-ba …

mgr/cephadm: add only_bind_port_on_networks support for rgw

---

qa/suites/rados/mgr/tasks/3-mgrmodules.yaml
src/mgr/MgrStandby.cc
src/mgr/MgrStandby.h

backport tracker: https://tracker.ceph.com/issues/70667
---
backport of https://github.com/ceph/ceph/pull/62465
parent tracker: https://tracker.ceph.com/issues/70571

squid: mgr: add status command

---

doc/cephadm/upgrade.rst

Correct a misspelled command.
Re: https://github.com/ceph/ceph/pull/62367#discussion_r2025832937 …

doc/cephadm: s/confg/config/

---

doc/cephadm/upgrade.rst

Correct a misspelled command.
Re: https://github.com/ceph/ceph/pull/62367#discussion_r2025832937
(cherry picked from commit 0f4d9a9ea29f12333609045928499963b37ba5f3) …

squid: doc/cephadm: s/confg/config/

---

doc/cephadm/upgrade.rst

Correct a misspelled command.
Re: https://github.com/ceph/ceph/pull/62367#discussion_r2025832937
(cherry picked from commit 0f4d9a9ea29f12333609045928499963b37ba5f3) …

reef: doc/cephadm: s/confg/config/

---

src/pybind/mgr/dashboard/services/access_control.py

Fixes: https://tracker.ceph.com/issues/70768 …

mgr/dashboard: add prometheus read permission to cluster_mgr role

---

src/osd/scrubber/pg_scrubber.cc
src/osd/scrubber/pg_scrubber.h
src/osd/scrubber/scrub_backend.cc

repair_oinfo_oid(), called every scrub, has a very specific functionality: fix the object ID specified in the Object Info attribute, if different from the ID of the owning object.
This fix was added in 2017, as a response to a unique failure scenario that was observed in Sepia - probably following a filesystem bug. See https://tracker.ceph.com/issues/18409 & https://tracker.ceph.com/issues/20471.
The limited functionality of repair_oinfo_oid() -
only repairing this one specific issue, and only if the OI_ATTR exists and is decodable - does not justify the overhead of running it every scrub.
(cherry picked from commit 7853731a83769ef643659390725d2be077999b8f) 
(cherry picked from commit aa22f19831731185e3c115a2b4e5603e8ef2634f)

reef: osd/scrub: discard repair_oinfo_oid()

---

src/CMakeLists.txt

In commit 27e9d563, we attempted to disable deprecated warnings when building googletest, but the implementation contained two errors:
1. The `set_property()` call occurred before adding the target directory, making it impossible to set properties on non-existent objects.
2. The `-Wno-deprecated-declarations` flag was incorrectly passed as an `APPEND` argument instead of a `PROPERTY` argument.
This caused build failures with libstdc++-12 and newer Clang versions:
```
CMake Error at src/CMakeLists.txt:772 (set_property):
set_property given invalid argument "-Wno-deprecated-declarations".
```
This commit fixes both issues by:
- Moving the `set_property()` call after `add_subdirectory()`
- Correctly passing the warning flag as a `PROPERTY` argument …

cmake: Fix warning suppression for googletest build

---

src/common/options/mon.yaml.in
src/mon/NVMeofGwMap.cc
src/mon/NVMeofGwMap.h
src/mon/NVMeofGwMon.cc
src/mon/NVMeofGwMon.h
src/mon/NVMeofGwTypes.h

nvmeofgw* :do not allow failover for gws during redeploy (fast-reboot)

---

doc/mgr/smb.rst

Add a warning to the docs highlighting that `clustering` is an advanced option and setting it without out also setting a compatible placement value may lead to unexpected behavior. …

doc/mgr: add a warning about the smb clustering option & placement

---

qa/suites/orch/cephadm/smb/tasks/deploy_smb_ctdb_node_gone_state.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_clustering_ips.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_ctdb_res_basic.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_ctdb_res_dom.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_ctdb_res_ips.yaml

Change 06fc55b0a4d994550f05625f10d8f7f0b11863eb added a setsebool command to nodes setup on ctdb enabled test. This should have prevented additional errors like:
```
failure_reason: 'SELinux denials found on
ubuntu@smithi066.front.sepia.ceph.com: [''type=AVC
msg=audit(1743168241.024:10142): avc:  denied  { nlmsg_read } for
pid=60223 comm="ss"
scontext=system_u:system_r:container_t:s0:c491,c612
tcontext=system_u:system_r:container_t:s0:c491,c612
tclass=netlink_tcpdiag_socket permissive=1'', ''type=AVC
msg=audit(1743168185.768:10101):
avc:  denied  { nlmsg_read } for  pid=58817 comm="ss"
scontext=system_u:system_r:container_t:s0:c491,c612
tcontext=system_u:system_r:container_t:s0:c491,c612
tclass=netlink_tcpdiag_socket
permissive=1'', ''type=AVC msg=audit(1743168210.896:10137): avc:
denied …
```

qa/cephadm/smb: run setsebool with sudo

---

src/rgw/rgw-gap-list

rgw-gap-list would fail if it it reached the end of the second file before the first, thereby causing an infinite loop.
Fixes: https://tracker.ceph.com/issues/70680 …

rgw: fix bug with rgw-gap-list

---

doc/radosgw/cloud-restore.rst
doc/radosgw/cloud-transition.rst
doc/radosgw/index.rst

Added a doc with details about cloud-restore feature and its usage.
<details>
- …

rgw: Updating doc for cloud-restore feature

---

src/test/ObjectMap/test_keyvaluedb_atomicity.cc

The `CONTROL_PREFIX` constant in `test_keyvaluedb_atomicity.cc` has never been used since its introduction in commit 6a624b960a.
Clang's warning highlights the unused variable:
```
warning: unused variable 'CONTROL_PREFIX' [-Wunused-const-variable]
```
Remove the unnecessary constant to clean up the code and eliminate the compiler warning.
Refs 6a624b960a …

test/ObjectMap: Remove unused CONTROL_PREFIX variable

---

src/os/bluestore/BlueStore.cc

backport tracker: https://tracker.ceph.com/issues/67124
---
backport of https://github.com/ceph/ceph/pull/57890
parent tracker: https://tracker.ceph.com/issues/66361

squid: os/bluestore: Fix ExtentDecoderPartial::_consume_new_blob

---

src/os/ObjectStore.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/os/bluestore/bluestore_tool.cc
src/test/objectstore/store_test.cc
src/tools/ceph_kvstore_tool.cc
src/tools/ceph_objectstore_tool.cc
src/tools/ceph_objectstore_tool.h
src/tools/kvstore_tool.cc
src/tools/kvstore_tool.h

squid: tools/ceph-objectstore-tool: tricks to tolerate disk errors for "pg export" command

---

src/CMakeLists.txt

Previously, we attempted to disable deprecated declarations warnings when building gtest by adding `-Wno-deprecated-declarations` to the COMPILE_OPTIONS property of the googletest directory. However, this approach failed to apply the option when actually building gtest.
This change applies the compile option directly to the `gtest` target using target_compile_options() instead. Verified by forcing the condition to TRUE and confirming the option is included when building `gtest-all.cc` through `cmake --build ~/dev/ceph/build --target gtest --verbose`. …

cmake: Fix googletest deprecated warnings by using target_compile_options()

---

qa/workunits/rgw/test_rgw_orphan_list.sh
src/rgw/driver/dbstore/common/dbstore.h
src/rgw/driver/rados/rgw_putobj_processor.cc
src/rgw/driver/rados/rgw_putobj_processor.h
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/rgw_sal.cc
src/rgw/rgw_sal.h

backport tracker: https://tracker.ceph.com/issues/70784
---
backport of https://github.com/ceph/ceph/pull/62604
parent tracker: https://tracker.ceph.com/issues/70746

reef: rgw: keep the tails when copying object to itself

---

src/mon/LogMonitor.cc

backport tracker: https://tracker.ceph.com/issues/70380
---
backport of https://github.com/ceph/ceph/pull/61933
parent tracker: https://tracker.ceph.com/issues/54489

squid: LogMonitor: set no_reply for forward MLog commands

---

doc/cephadm/services/rgw.rst

doc/cephadm/services: improve rgw.rst and snmp-gateway.rst
Eye YAML what I YAML. …

doc/cephadm/services: improve rgw.rst and snmp-gateway.rst

---

doc/cephadm/services/rgw.rst

(cherry picked from commit 3d18222b46d65784335b4af0d651118b5e588d5e) …

squid: doc/cephadm/services: improve rgw.rst and snmp-gateway.rst

---

doc/cephadm/services/rgw.rst

(cherry picked from commit 3d18222b46d65784335b4af0d651118b5e588d5e) …

reef: doc/cephadm/services: improve rgw.rst and snmp-gateway.rst

---

monitoring/ceph-mixin/dashboards/host.libsonnet
monitoring/ceph-mixin/dashboards_out/host-details.json

backport tracker: https://tracker.ceph.com/issues/70763
---
backport of https://github.com/ceph/ceph/pull/62047
parent tracker: https://tracker.ceph.com/issues/70226

squid: monitoring: Fix OSDs panel in host-details grafana dashboard

---

src/crimson/osd/backfill_state.cc
src/crimson/osd/backfill_state.h
src/crimson/osd/osd_operation.cc
src/crimson/osd/osd_operation.h
src/crimson/osd/osd_operations/background_recovery.cc
src/crimson/osd/osd_operations/background_recovery.h
src/crimson/osd/pg_recovery.cc
src/crimson/osd/pg_recovery.h
src/crimson/osd/shard_services.h

@Matan-B @athanatos This PR reverts 14463aa7a493dc6903d18af960aac24e8ab8153b and use `OperationThrottler` to throttle recovery/backfill pushes/pulls instead of recovery/backfill operations.
Fixes: https://tracker.ceph.com/issues/70180 …

crimson/osd/pg_recovery: use OperationThrottler to throttle object pushes/pulls

---

doc/mgr/dashboard.rst
src/pybind/mgr/dashboard/module.py
src/pybind/mgr/dashboard/services/rgw_client.py
src/pybind/mgr/dashboard/services/service.py
src/pybind/mgr/dashboard/settings.py
src/pybind/mgr/dashboard/tests/test_rgw_client.py

drops using the `rgw_dns_name` to resolve the rgw hosts in dashboard and
introduces a command `ceph dashboard set-rgw-hostname <daemon>
<hostname>` to set custom dns names for each gateways. Once set
dashboard will pick up that address for the selected gateway.
And a config can be unset by
`ceph dashboard unset-rgw-hostname <daemon>`
Fixes: https://tracker.ceph.com/issues/70744 …

mgr/dashboard: introduce dashboard setting to resolve rgw hostname

---

src/cephadm/cephadm.py
src/cephadm/cephadmlib/container_engines.py
src/cephadm/cephadmlib/container_lookup.py
src/cephadm/cephadmlib/listing.py
src/cephadm/tests/fixtures.py
src/cephadm/tests/test_cephadm.py

Depends on #61761 
Refactor the infer_local_ceph_image function to use the low level
daemons_matching function and avoid ever looping over the list of
running daemons multiple times. Clean up the logic in
infer_local_ceph_image such that it better matches the behavior
in the original doc string as well as cleaning up said doc string.
Fixes: https://tracker.ceph.com/issues/69278 …

cephadm: update and improve container image infer function

---

src/osd/OSD.h

Update shared pointer atomic operations to use C++20's `std::atomic<std::shared_ptr>` instead of the deprecated `atomic_store` functions. This change addresses deprecation warnings from GCC-15's libstdc++ where atomic shared pointer operations outside the `std::atomic` class are being phased out:
```
In file included from /home/kefu/dev/ceph/src/osd/Watch.cc:9:
/home/kefu/dev/ceph/src/osd/OSD.h:1675:10: warning: 'atomic_store<const OSDMap>' is deprecated: use 'std::atomic<std::shared_ptr<T>>' instead [-Wdeprecated-declarations]
1675 |     std::atomic_store(&_osdmap, osdmap);
|          ^
/usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/shared_ptr_atomic.h:181:5: note: 'atomic_store<const OSDMap>' has been explicitly marked deprecated here
181 | …
```

osd: replace deprecated atomic_store with std::atomic<shared_ptr>

---

doc/man/8/radosgw-admin.rst
src/cls/rgw/cls_rgw.cc
src/rgw/driver/rados/rgw_bucket.cc
src/rgw/driver/rados/rgw_bucket.h
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/radosgw-admin/radosgw-admin.cc
src/rgw/rgw_sal.h
src/test/cli/radosgw-admin/help.t

The `radosgw-admin object rm ...` sub-command will give up if it determines that there's an issue with the head object. This can make it difficult for an admin to clean up a bucket index when there's a damaged or missing head object.
When the user adds the "--yes-i-really-mean-it" command-line option, it enables the "force mode". The bucket index entry(ies) will be removed. If the object being removed is the current version in a versioned bucket, the appropriate changes to the OLH will take place.
Fixes: https://tracker.ceph.com/issues/70776 …

rgw: add force option to `radosgw-admin object rm ...`

---

src/crimson/osd/ops_executer.cc
src/crimson/osd/osd_operations/client_request.cc
src/crimson/osd/pg.cc
src/crimson/osd/pg.h
src/osd/PeeringState.h
src/osd/osd_types.h
src/test/osd/types.cc

```
When handling a client request on a clone object, m->get_hobj() might
not actually represent the "actual" object from the OSD's prespective.
See: ObjectContext::resolve_oid for how this logic is handled.
If this replica has any missing clone objects that are either this object head
or any of this object's clones - drop this replicted read and bounce back to primary.
Keep the head missing check in order to avoid trying to find any
missing clones if this is not a clone.
We could possibly check if the head is not missing and then wait for
resolve_oid to lookup for the actual clone object (Which might exist!).
However, this seems to not be worth the complexity as the niche scenario
of being able to serve reads while having (possibly) releated missing objects.
Fixes (3/3): …
```

osd/../client_request: Fix clone replicated reads

---

qa/crontab/teuthology-cronjobs

qa/crontab: Update Crimson's Cron Jobs

---

src/rgw/driver/rados/rgw_cr_rados.cc
src/rgw/driver/rados/rgw_trim_bilog.cc

RGWRadosBILogTrimCR() returns ENODATA when nothing is found:
```
4 trim: failed to trim bilog shard: (61) No data available
```

rgw: BucketTrimShardCollectCR expect ENODATA as empty

---

qa/suites/rados/singleton/all/stretch-mode-5-mons-8-osds.yaml
qa/workunits/mon/mon-stretch-mode-5-mons-8-osds.sh

backport tracker: https://tracker.ceph.com/issues/69168
---
backport of https://github.com/ceph/ceph/pull/60927
parent tracker: https://tracker.ceph.com/issues/69107

squid: qa/workunits/mon: ensure election strategy is "connectivity" for stretch mode

---

ceph.spec.in
debian/ceph-exporter.install
debian/control
debian/rules
systemd/CMakeLists.txt
systemd/ceph-exporter.service.in

backport tracker: https://tracker.ceph.com/issues/70445
---
backport of https://github.com/ceph/ceph/pull/55409
parent tracker: https://tracker.ceph.com/issues/64095

squid: debian: add ceph-exporter package

---

src/include/rangeset.h
src/msg/async/dpdk/circular_buffer.h

This trait has been deprecated in C++17, with users instructed to migrate to defining each associated type when implementing an iterator.
This quiets the _GLIBCXX17_DEPRECATED warnings when compiling the project on a sufficiently new gcc.
This follows on from previous efforts in 8b8a96d (#45198).
- https://github.com/ceph/ceph/pull/45198
- https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/ …

include,dpdk: fix two usages of std::iterator (deprecated)

---

src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h

Backports: https://github.com/ceph/ceph/pull/61843
That's a partial backport as half of the commits in the above PR fix multi-label issues not applicable to Reef.
Fixes: https://tracker.ceph.com/issues/70294
Fixes: https://tracker.ceph.com/issues/70290 …

reef: os/bluestore: fix bdev expansion and more

---

PendingReleaseNotes
qa/cephfs/overrides/ignorelist_health.yaml
qa/tasks/cephfs/test_admin.py
src/mgr/PyModuleRegistry.cc
src/mon/MgrMap.h
src/mon/MgrMonitor.cc
src/mon/MonCommands.h

NOTE: this backport PR has one less commit compared to parent PR because it was backported separately by backport team. See: https://github.com/ceph/ceph/pull/60496.
---
backport tracker: https://tracker.ceph.com/issues/68678
---
backport of https://github.com/ceph/ceph/pull/58647
parent tracker: https://tracker.ceph.com/issues/66005

squid: mgr: allow disabling always-on modules

---

src/blk/kernel/KernelDevice.cc
src/blk/kernel/KernelDevice.h
src/common/options/global.yaml.in

Some disks have a discard performance that is too low to keep up with write workloads. Using async discard in this case will cause the OSD to run out of capacity due to the number of outstanding discards preventing allocations from being freed. While sync discard could be used in this case to cause backpressure, this might have unacceptable performance implications.
For the most part, as long as enough discards are getting through to a device, then it will stay trimmed enough to maintain acceptable performance. Thus, we can introduce a cap on the pending discard count, ensuring that the queue of allocations to be freed doesn't get too long while also issuing sufficient discards to disk. The default value of 1000000 has ample room for discard spikes (e.g. from snaptrim); it could result in …

squid: blk/KernelDevice: Introduce a cap on the number of pending discards

---

src/pybind/mgr/mgr_module.py

backport tracker: https://tracker.ceph.com/issues/69960
---
backport of https://github.com/ceph/ceph/pull/61763
parent tracker: https://tracker.ceph.com/issues/69912

squid: pybind/mgr/mgr_module: turn off all automatic transactions

---

src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/test/objectstore/store_test.cc

Backports: https://github.com/ceph/ceph/pull/61364
Parent tracker: https://tracker.ceph.com/issues/69507
Fixes: https://tracker.ceph.com/issues/70293 …

squid: os/bluestore: do cache locally compressor engines ever used

---

src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/test/objectstore/store_test.cc

Commit 2:
Fixes race between BlueFS::truncate and BlueFS::unlink.
Fixes: https://tracker.ceph.com/issues/70747
Commit 1:
Created test that exposes race between BlueFS::truncate and BlueFS::unlink.
Test requires injection of 1ms sleep to BlueFS::truncate.
Therefore, in this form, it is unsuitable for merge.
Running:
```
./bin/ceph_test_objectstore --gtest_filter=\*truncate_remove_race\*
```
It will assert.
Observe results:
```
$ ./bin/ceph-bluestore-tool --path bluestore.test_temp_dir/ fsck
2025-03-31T20:53:54.241+0000 7efd9b60ccc0 -1 bluefs _check_allocations OP_FILE_UPDATE_INC invalid extent 1: 0x1ec2000~20000: duplicate reference, ino 28
2025-03-31T20:53:54.241+0000 7efd9b60ccc0 -1 bluefs mount failed to replay log: (14) Bad address
```
But if we skip checking allocations:
```
$ …
```

os/bluestore: Fix race in BlueFS truncate / remove

---

doc/man/8/ceph-bluestore-tool.rst
src/common/options/global.yaml.in
src/include/buffer.h
src/include/denc.h
src/include/encoding.h
src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/os/bluestore/BlueRocksEnv.cc
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/os/bluestore/bluefs_types.cc
src/os/bluestore/bluefs_types.h
src/os/bluestore/bluestore_tool.cc
src/test/objectstore/test_bluefs.cc

The work here is based on #56927.
It implements the design principles showed there, but with a bit different implementation details. …

os/bluestore: Fast WAL for RocksDB

---

src/test/librbd/test_notify.py

test/librbd/test_notify.py: force line-buffered output

---

qa/objectstore_debug/bluestore/onode-segment$/1M.yaml
qa/objectstore_debug/bluestore/onode-segment$/256K.yaml
qa/objectstore_debug/bluestore/onode-segment$/512K-onoff.yaml
qa/objectstore_debug/bluestore/onode-segment$/512K.yaml
qa/objectstore_debug/bluestore/onode-segment$/none.yaml
src/common/options/global.yaml.in
src/include/denc.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/os/bluestore/bluestore_types.h
src/tools/ceph-dencoder/osd_types.h

This is adaptation of standalone https://github.com/ceph/ceph/pull/55968 for recompression PR.
The original PR will be closed in the future.
https://github.com/ceph/ceph/pull/54075 Nice debugs.
https://github.com/ceph/ceph/pull/54504 New write path.
https://github.com/ceph/ceph/pull/57448 Segmented onode.
https://github.com/ceph/ceph/pull/56975 Main
https://github.com/ceph/ceph/pull/57450 Test …

os/bluestore: Recompression, part 3. Segmented onode.

---

src/pybind/mgr/dashboard/controllers/host.py
src/pybind/mgr/dashboard/tests/test_host.py

backport tracker: https://tracker.ceph.com/issues/70837
---
backport of https://github.com/ceph/ceph/pull/62716
parent tracker: https://tracker.ceph.com/issues/70821

reef: mgr/dashboard: Fix empty ceph version in GET api/hosts

---

src/os/bluestore/BlueStore.cc

backport tracker: https://tracker.ceph.com/issues/67125
---
backport of https://github.com/ceph/ceph/pull/57890
parent tracker: https://tracker.ceph.com/issues/66361

reef: os/bluestore: Fix ExtentDecoderPartial::_consume_new_blob

---

src/test/rgw/rgw_multi/tests.py

adjust the parsing to match changes from 3f0428a017cdf35b7290cf7836eb4baa4eb0e774
Fixes: https://tracker.ceph.com/issues/70729
<details> …

test/rgw/multisite: fix parsing of 'topic list' output

---

qa/suites/rgw/bucket-logging/overrides.yaml
qa/suites/rgw/cloud-transition/overrides.yaml
qa/suites/rgw/cloud-transition/tasks/restore/cloud_restore_s3tests.yaml
qa/suites/rgw/cloud-transition/tasks/transition/cloud_transition_s3tests.yaml
qa/suites/rgw/crypt/overrides.yaml
qa/suites/rgw/lifecycle/overrides.yaml
qa/suites/rgw/lua/overrides.yaml
qa/suites/rgw/multifs/overrides.yaml
qa/suites/rgw/notifications/overrides.yaml
qa/suites/rgw/sts/overrides.yaml
qa/suites/rgw/verify/overrides.yaml
qa/tasks/rgw.py

adjust the rgw task's yaml format for "storage classes" so that the rgw/crypt suite can enable compression
<details> …

qa/rgw: use storage classes for rgw/crypt

---

src/common/async/detail/spawn_throttle_impl.h
src/common/options/rgw.yaml.in
src/librados/librados_asio.h
src/rgw/driver/rados/rgw_tools.cc
src/rgw/driver/rados/rgw_tools.h
src/rgw/services/svc_notify.cc
src/rgw/services/svc_notify.h

accelerate startup and shutdown of radosgw and radosgw-admin by sending concurrent watch/unwatch operations over the rgw_num_control_oid=8 objects
<details> …

rgw: send concurrent watch/unwatch operations

---

PendingReleaseNotes
src/rgw/rgw_common.cc

According to the AWS docs (https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html), If RestrictPublicBuckets is set to true and there are public policies in place, Only access from the bucket owner's account is possible.
Fixes: https://tracker.ceph.com/issues/65741

rgw: implement RestrictPublicBuckets from PublicAccessBlock

---

src/osd/ECTypes.h
src/osd/osd_types.cc
src/osd/osd_types.h

Add new types and make additions to data structures for the EC optimizations feature.
EC optimized pools do not always update every shard for every I/O, this makes recovery (where peering uses the pg log and pg info structures to reconcile differences between the shards) and backfill (where peering uses the object_info_t structure to compare the object version number of different shards to reconcile differences) more complicated.
The pg_log_entry_t, pg_info_t and pg_fast_info_t structures are extended to store extra information that will be required for recovery. The object_info_t structure is extended to store extra information that will be required for backfill and scrubbing.
EC optimized pools restrict the selection of the primary to shards that are always updated. The pg_pool_t …

osd: EC optimizations: new types and additions to data structures

---

doc/radosgw/s3/commons.rst

instead of referring to "vhost-style", copy the "path-style" and "virtual-hosted-style" language from https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html
expand the FQDN acronym to avoid potential confusion
"The second method is deprecated by AWS" had incorrectly referred to the vhost-style method - clarify that it refers to path-style access
(cherry picked from commit c61c314ed6482cc26cf69ed7e2af4af20bebd676) …

squid: doc/rgw: clarify path-style vs virtual-hosted-style access

---

src/rgw/services/svc_notify.cc

IF we get `-ENOENT` from unwatch just stop trying to renew.
Otherwise, schedule retry on watch failure, but add a maximum retry timeout.
Fixes: https://tracker.ceph.com/issues/70422
(cherry picked from commit 34366f0f0d8e13eb8fef1e253794303b699e08b2)
Fixes: https://tracker.ceph.com/issues/70526 …

squid: rgw: Try to handle unwatch errors sensibly

---

src/rgw/rgw_amqp.cc
src/test/rgw/amqp_mock.cc
src/test/rgw/amqp_url.c

Since we have an obscenely wide supported version spread, we have to support the deprecated location, too.
- …

rgw: Fix deprecated amqp includes

---

qa/suites/rados/singleton/all/test-crash.yaml

backport tracker: https://tracker.ceph.com/issues/70135
---
backport of https://github.com/ceph/ceph/pull/60934
parent tracker: https://tracker.ceph.com/issues/69010

squid: rados/test_crash.sh: add PG_DEGRADED to ignorelist

---

src/mon/OSDMonitor.cc

backport tracker: https://tracker.ceph.com/issues/70495
---
backport of https://github.com/ceph/ceph/pull/62243
parent tracker: https://tracker.ceph.com/issues/70400

reef: OSDMonitor: exclude destroyed OSDs from "ceph node ls" output

---

src/crimson/os/seastore/btree/btree_range_pin.h
src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/cache.h
src/crimson/os/seastore/cached_extent.h
src/crimson/os/seastore/lba_manager.cc
src/crimson/os/seastore/lba_manager.h
src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.cc
src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.h
src/crimson/os/seastore/transaction.h
src/crimson/os/seastore/transaction_manager.cc
src/crimson/os/seastore/transaction_manager.h

Cleanups that might be generally benefitial, and some adjustments to make sure the code structure keeps friendly to integrate https://github.com/ceph/ceph/pull/62634. …

crimson/os/seastore: cleanups related to lba and cache

---

src/test/librbd/test_notify.py

backport tracker: https://tracker.ceph.com/issues/70846
---
backport of https://github.com/ceph/ceph/pull/62727
parent tracker: https://tracker.ceph.com/issues/70831

reef: test/librbd/test_notify.py: force line-buffered output

---

src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/bluestore_common.h
src/test/objectstore/test_bluefs.cc

block size.
Signed-off-by: Igor Fedotov <ifedotov@croit.io>
(cherry picked from commit 3cc75e8670d4fb43062ce41744262f858116f764) …

reef: os/bluestore: make BlueFS an exclusive selector for volume reserved

---

doc/cephfs/multimds.rst

Some example commands had double prompts: one `#`
from the `.. prompt` and after that another hardcoded `$` character.
Remove the extra user prompt and leave only the root prompt from the `.. prompt` block. …

doc/cephfs: Fix double prompts in commands in multimds.rst

---

src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
src/pybind/mgr/cephadm/tests/test_services.py
src/python-common/ceph/deployment/service_spec.py

mgr/cephadm/nvmeof: Add OMAP read lock parameters to NVMEoF configuration
Fixes https://tracker.ceph.com/issues/70861 …

mgr/cephadm/nvmeof: Add OMAP read lock parameters to NVMEoF configuration

---

src/rgw/driver/rados/rgw_data_sync.cc

Fixes: https://tracker.ceph.com/issues/63378
And through backport
Fixes: https://tracker.ceph.com/issues/68298
- …

squid: rgw/multisite: handle errors properly in RGWDataFullSyncSingleEntryCR()

---

src/test/cls_2pc_queue/test_cls_2pc_queue.cc

Fixes: https://tracker.ceph.com/issues/63786
(cherry picked from commit 6f9f52033b0bb7b03ef569f12a970793ca65f0e8)
Fixes: https://tracker.ceph.com/issues/67143 …

squid: test/cls_2pc_queue: fix multi-threaded access to non-atomic variables

---

doc/ceph-volume/drive-group.rst
doc/ceph-volume/lvm/list.rst
doc/ceph-volume/lvm/prepare.rst

Use the more modern prompt block for CLI commands instead of adding a hard `# ` character as prompt that is selectable & copyable in modern browsers.
Fix missing preceding empty line in one pre-existing `.. prompt` that caused it to be printed in the rendered document.
Fix messed up line breaks / line continuation backslashes in one command.
Also change existing prompts to all indent with same 3 spaces and not 3 in some place and 4 in other. …

doc/ceph-volume: Promptify commands and fix formatting

---

doc/releases/index.rst
doc/releases/releases.yml
doc/releases/squid.rst

doc: squid 19.2.2 release notes

---

debian/rules
make-debs.sh
src/script/build-with-container.py
src/script/buildcontainer-setup.sh

Enabling containerized debian pipeline builds

---

src/cls/rbd/cls_rbd.cc

cls/rbd: drop overzealous CLS_ERR message in mirror_remote_namespace_get()

---

qa/workunits/rgw/test_rgw_orphan_list.sh
src/rgw/driver/dbstore/common/dbstore.h
src/rgw/driver/rados/rgw_putobj_processor.cc
src/rgw/driver/rados/rgw_putobj_processor.h
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/rgw_sal.cc
src/rgw/rgw_sal.h

backport tracker: https://tracker.ceph.com/issues/70783
---
backport of https://github.com/ceph/ceph/pull/62604
parent tracker: https://tracker.ceph.com/issues/70746

squid: rgw: keep the tails when copying object to itself

---

src/rgw/services/svc_notify.cc

We are getting a compilation issue with accessing an incomplete type.
This fix moves some code around to avoid this issue.
I don't fully understand why we don't see this issue everywhere!
https://tracker.ceph.com/issues/70889 …

rgw: Fix compilation issue with clang on centos

---

doc/man/8/CMakeLists.txt
doc/man/8/rgw-gap-list.rst

Fixes: https://tracker.ceph.com/issues/70854 …

rgw/doc: add man documentation for the rgw-gap-list tool

---

src/osd/scheduler/OpSchedulerItem.cc

The patch fixes calculation of latency perf counters for the following objects:
- PGRecovery
- PGRecoveryContext and
- PGRecoveryMsg
Signed-off-by: Sridhar Seshasayee <sseshasa@redhat.com>
Fixes: https://tracker.ceph.com/issues/70811 …

osd/scheduler/OpSchedulerItem: Fix calculation of recovery latency counters

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form-data.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.ts

Add a description for the default pool application values in the pool creation form i.e cephfs <-> FileSystem, rbd <-> Block, rgw <-> Object.
Fixes: https://tracker.ceph.com/issues/70866 …

mgr/dashboard: add description for default Pool Application select options

---

src/mon/OSDMonitor.cc
src/osd/OSDMap.cc
src/osd/OSDMap.h
src/osd/PeeringState.cc
src/test/osd/TestOSDMap.cc

Pools with ec_optimizations enabled have restrictions on which shards are permitted to become the primary because not all shards are updated for every I/O. …

osd: Restrict choice of primary shard for ec_optimizations pools

---

doc/dev/release-process.rst

doc: minor additions based on the latest mods

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml

allow selecting a specifc gw for your cli command across all API/CLI routes.
This is needed mainly for testing, but might also be useful for production debugging.
I wonder if I should keep the `traddr` terminology or change it to `gw_address`, WDYT? 
in the example below you can see the `addr` field changes according to the `traddr` parameter
`[root@cephnvme-vm29 ~]# ceph nvmeof gw info
{"cli_version": "", "version": "1.5.2", "name": "client.nvmeof.mypool.mygroup1.cephnvme-vm29.ynjpsd", "group": "mygroup1", "addr": "10.242.64.51", "port": "5500", "load_balancing_group": 1, "spdk_version": "SPDK v24.09"}
[root@cephnvme-vm29 ~]# ceph nvmeof gw info --traddr=10.242.64.50
{"cli_version": "", "version": "1.5.2", "name": "client.nvmeof.mypool.mygroup1.cephnvme-vm28.mtzqyc", "group": "mygroup1", …

mgr/dashboard: allow selecting target gw in nvmeof cli/api endpoints

---

doc/cephadm/operations.rst
doc/cephadm/services/osd.rst

doc/cephadm: Add admonition re restarting an OSD service
This came out of a discussion with @michaelalang and Raimund Sacherer.  One might (not entirely unreasonably) presume that an OSD service restart would attend to PG health and CRUSH failure domains, in the sense that Rook sets pod disruption budgets.  This is not the case for `ceph orch`.
- When filling …

doc/cephadm: Add admonition re restarting an OSD service

---

doc/cephadm/operations.rst
doc/cephadm/services/osd.rst

(cherry picked from commit 524db4609f5f0b4639828b327cfc972243e08ce7) …

squid: doc/cephadm: Add admonition re restarting an OSD service

---

doc/cephadm/operations.rst
doc/cephadm/services/osd.rst

(cherry picked from commit 524db4609f5f0b4639828b327cfc972243e08ce7) …

reef: doc/cephadm: Add admonition re restarting an OSD service

---

src/osd/OSD.cc

Adding the following parameters to the (small) set of configuration options that, if changed, trigger re-computation of the next scrub schedule:
- osd_deep_scrub_interval_cv,
- osd_scrub_interval_randomize_ratio, and
- osd_deep_scrub_interval (which was missing in the list of parameters watched by the OSD).
Fixes: https://tracker.ceph.com/issues/70806

osd/scrub: additional configuration parameters to trigger scrub reschedule

---

src/common/pick_address.cc
src/common/pick_address.h
src/osd/OSDMap.cc
src/test/test_ipaddr.cc

backport tracker: https://tracker.ceph.com/issues/69493
---
backport of https://github.com/ceph/ceph/pull/60881
parent tracker: https://tracker.ceph.com/issues/67517

squid: common/pick_address: Add IPv6 support to is_addr_in_subnet

---

ceph.spec.in

https://github.com/ceph/ceph/pull/62749 introduced rgw-gap-list docs which are installed but remain unpackaged. 
```
-- Installing: /home/jenkins-build/build/workspace/ceph-dev-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/20.0.0-1393-g1deacb75/rpm/el9/BUILDROOT/ceph-20.0.0-1393.g1deacb75.el9.x86_64/usr/share/man/man8/rgw-gap-list.8
```
Centos builds fail with:
```
error: Installed (but unpackaged) file(s) found:
/usr/share/man/man8/rgw-gap-list.8.gz
RPM build errors:
Installed (but unpackaged) file(s) found:
/usr/share/man/man8/rgw-gap-list.8.gz
```
https://shaman.ceph.com/builds/ceph/main/1deacb75e081347e1d0a58fa6f9ffa3229b327e8/ …

ceph.spec.in: package man/rgw-gap-list

---

src/test/bufferlist.cc

Long time ago the buffer library had an issue with dangling `last_p` in `bufferlist`. The problem has been eradicated altogether with the `last_p` itself but I missed turning the replicator on. Let's finally do that. …

test/bufferlist: turn the old last_p fix verification on

---

src/pybind/ceph_argparse.py
src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/tests/test_ceph_argtypes.py
src/pybind/mgr/tests/test_cli_command.py

it seems like the default value for size is 1024, which raises must be aligned to MiBs error when the route is being triggered without size value (I mean when using the default value), when I pass size=1048576 (1024*1024= 1MB) It works.
To complicate it a bit, the CLI today doesn't expects integer value but a string that might be of the following forms: "1048576", "1MB", "100GB", etc...
This PR attempts to  solve this issue in way that will satisfy the API and the CLI together.
it seems like CLICommand decorator doesn't support Union[str,int] as a param (it makes sense), so I can't really give the parameter a type of both str and int, I go for now with str (since I must allow "10MB"), I guess it means that we will need to adapt current API clients. Another option is to introduce a new …

mgr/dashboard: Ns create size fix

---

doc/dev/release-process.rst

doc: changed refs from quincy to squid

---

src/blk/kernel/KernelDevice.cc
src/blk/kernel/KernelDevice.h

backport tracker: https://tracker.ceph.com/issues/70148
---
backport of https://github.com/ceph/ceph/pull/59529
parent tracker: https://tracker.ceph.com/issues/67835

squid: blk/kerneldevice: notify_all only required when discard_drain wait for condition

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts

Fixes: https://tracker.ceph.com/issues/70874
PR covers & fixes below scenarios:
Whenever we change the owner of bucket from non-tenanted to tenanted and vice-versa with the rate-limit changes, there was issue in sending bucket name 
Scenario 1: Changing the bucket owner from tenanted to non-tenanted 
Scenario 2: Changing the bucket owner from non-tenanted to tenanted 
Scenario 3: Keeping the owner(tenanted) same and changing only rate limit …

mgr/dashboard: bucket ratelimit API failing while changing owner with ratelimit config

---

src/mds/MDLog.cc
src/mds/MDLog.h
src/mds/MDSRank.cc

Fixes: https://tracker.ceph.com/issues/69953 …

mds: fix heap-use-after-free in C_Flush_Journal

---

qa/tasks/cephfs/mount.py

Instead of satisfying another dependency like 'net-tools' in order to use 'route' command, just use 'ip route' to find out which is the default gateway. …

qa/tasks/cephfs/mount: use 'ip route' instead 'route'

---

qa/tasks/cephfs/test_data_scan.py

doc [0] suggests running cleanup step after scanning extents and inodes which was missing in the func `_rebuild_metadata()`
[0] https://docs.ceph.com/en/latest/cephfs/disaster-recovery-experts/#recovery-from-missing-metadata-objects …

qa: add parallelized cleanup step in _rebuild_metadata()

---

doc/man/8/ceph-bluestore-tool.rst
src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/os/bluestore/bluestore_tool.cc
src/test/objectstore/store_test.cc

Adds printing label locations in show-label cmd output.
Adds "show-label-at" command.
Fixes crashing fsck on "incompletely" expanded device.
Parent tracker: https://tracker.ceph.com/issues/67966
Parent tracker: https://tracker.ceph.com/issues/69981
Parent tracker: https://tracker.ceph.com/issues/69997
Parent tracker: https://tracker.ceph.com/issues/69999
Backports: https://github.com/ceph/ceph/pull/61843
Fixes: https://tracker.ceph.com/issues/70295
Fixes: https://tracker.ceph.com/issues/70291
Fixes: https://tracker.ceph.com/issues/70298
Fixes: https://tracker.ceph.com/issues/70296 …

squid: os/bluestore: fix bdev expansion and more

---

src/pybind/mgr/dashboard/frontend/src/app/core/auth/user-form/user-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/services/change-password-guard.service.ts

mgr/dashboard: fix typo in user form from "logon" to "login"
This commit fixes a minor typo in the user-facing checkbox label,
changing "logon" to "login" in `user-form.component.html`. Also
updates a relevant comment in `change-password-guard.service.ts`
to reflect the correct terminology.
Fixes: https://tracker.ceph.com/issues/70719
Signed-off-by: Priyanshu <prinovac@gmail.com> …

mgr/dashboard: fix typo in User Management form (logon → login)

---

doc/radosgw/cloud-transition.rst

This PR brings in additional fixes for the Ceph [cloud transition documentation](https://docs.ceph.com/en/latest/radosgw/cloud-transition/). The main fix is bringing back the reStructuredText for code block elements as the current setup does not render well for the page making it difficult to read and understand. Additonal fixes go for broken URL links as well as some other minor details.  
Currently the fix is only for the cloud transition documentation, if it proves to work well a new PR for cloud restoration will be raised fixing the same details.
<details>
- `jenkins test classic perf` [Jenkins …

doc/radosgw/cloud-transition: use reStructuredText for code

---

doc/radosgw/cloud-transition.rst

Fix documentation on Ceph cloud storage transitions - broken link urls, returning back reStructuredText and some other details.
Co-authored-by: Anthony D'Atri <anthonyeleven@users.noreply.github.com>
(cherry picked from commit c47b559547326f837dde9dfed9eef526e275fa8e) …

squid: doc/radosgw/cloud-transition: fix details

---

src/osd/osd_perf_counters.cc
src/osd/osd_perf_counters.h
src/osd/scrubber/pg_scrubber.cc
src/osd/scrubber/pg_scrubber.h
src/osd/scrubber/scrub_machine.cc
src/osd/scrubber/scrub_machine.h
src/osd/scrubber/scrub_machine_lstnr.h
src/osd/scrubber/scrub_reservations.cc
src/osd/scrubber/scrub_reservations.h
src/osd/scrubber_common.h

Change most performance counters used by the Scrubber to be the regular, unlabeled, ones.
For the unlabeled counters - use only two sets (EC vs. replicated), as there seems to be
little use for the Primary vs. replica distinction.
This is an extension of the original https://github.com/ceph/ceph/pull/62693 - counting
scrub I/O, but without the "counting I/Os" part (as that is pending EC changes merge).

osd/scrub: performance counters: count I/Os, use unlabeled counters

---

doc/releases/reef.rst
doc/releases/squid.rst

Triple backtick does not create a code block in RST, instead it renders as an inline code (double backtick syntax) with the third backtick rendered as-is.
This makes newlines in multiline code merged to a single line and it makes the whole thing nonsense. …

doc/releases: Fix invalid triple backticks in reef.rst squid.rst

---

src/pybind/mgr/nfs/export.py
src/pybind/mgr/nfs/utils.py

backport trackers: 
https://tracker.ceph.com/issues/66701
https://tracker.ceph.com/issues/67197
---
backport of https://github.com/ceph/ceph/pull/56876 and https://github.com/ceph/ceph/pull/58535
parent trackers: 
https://tracker.ceph.com/issues/56246
https://tracker.ceph.com/issues/66800

squid: mgr/nfs: Don't crash ceph-mgr if NFS clusters are unavailable.

---

src/common/ceph_context.cc

test_perf_counters_cache.cc initializes the CephContext with flag CINIT_FLAG_NO_CCT_PERF_COUNTERS which leaves both _cct_perf and _mempool_perf as nullptrs
the CephContextServiceThread calls _refresh_perf_values() regularly, which guards _cct_perf->set() calls with a nullptr check, but the _mempool_perf->set() calls were unguarded
this led to occasional unittest_perf_counters_cache segfaults in make check
Fixes: https://tracker.ceph.com/issues/64895
<details> …

common: CephContext::_refresh_perf_values() checks for null _mempool_perf

---

doc/radosgw/archive-sync-module.rst
doc/radosgw/cloud-restore.rst
doc/radosgw/cloud-sync-module.rst
doc/radosgw/cloud-transition.rst
doc/radosgw/multisite-sync-policy.rst
doc/radosgw/sync-modules.rst

Use the more modern prompt block for CLI commands and use right one $ vs #.
Fix indentation on JSON example outputs and some CLI command switches.
Add some arguably missing comma in JSON example output.
Add a full stop at the end of a one-sentence paragraph. Remove extra comma mid-sentence in another.
Fix missing backslashes or typo at end of multiline commands.
Lines under section headings as long as heading text.
Fix hyperlinks. Fix list items prefixed with `-` insted of `*`. Format configuration syntax in the middle of text as ``code``.
Fix typo "PI" to "API" and remove extra space between it and the following full stop. Remove colons at the end of section headers in a few places. Use Title Case in section titles consistently with short words lowercase.
Don't try to create code blocks …

doc/radosgw: Promptify CLI, cosmetic fixes

---

doc/radosgw/archive-sync-module.rst
doc/radosgw/cloud-restore.rst
doc/radosgw/cloud-sync-module.rst
doc/radosgw/cloud-transition.rst
doc/radosgw/multisite-sync-policy.rst
doc/radosgw/sync-modules.rst

Use the more modern prompt block for CLI commands
and use right one $ vs #.
Fix indentation on JSON example outputs and
some CLI command switches.
Add some arguably missing comma in JSON example output. Add a full stop at the end of a one-sentence paragraph. Remove extra comma mid-sentence in another.
Fix missing backslashes or typo at end of multiline commands. Lines under section headings as long as heading text. Fix hyperlinks. Fix list items prefixed with - insted of *. Format configuration syntax in the middle of text as code. Fix typo "PI" to "API" and remove extra space.
Remove colons at the end of section headers in a few places. Use Title Case in section titles consistently with short words lowercase. Possibly controversial: don't add whitespace before and after main title …

squid: doc/radosgw: Promptify CLI, cosmetic fixes

---

doc/radosgw/archive-sync-module.rst
doc/radosgw/cloud-restore.rst
doc/radosgw/cloud-sync-module.rst
doc/radosgw/cloud-transition.rst
doc/radosgw/multisite-sync-policy.rst
doc/radosgw/sync-modules.rst

Use the more modern prompt block for CLI commands
and use right one $ vs #.
Fix indentation on JSON example outputs and
some CLI command switches.
Add some arguably missing comma in JSON example output. Add a full stop at the end of a one-sentence paragraph. Remove extra comma mid-sentence in another.
Fix missing backslashes or typo at end of multiline commands. Lines under section headings as long as heading text. Fix hyperlinks. Fix list items prefixed with - insted of *. Format configuration syntax in the middle of text as code. Fix typo "PI" to "API" and remove extra space.
Remove colons at the end of section headers in a few places. Use Title Case in section titles consistently with short words lowercase. Possibly controversial: don't add whitespace before and after main title …

reef: doc/radosgw: Promptify CLI, cosmetic fixes

---

doc/radosgw/cloud-transition.rst

Fix double-colon literal blocks before blocks with prompts, missed in rebase.
Introduced in #62763
- Tracker …

doc/radosgw: Remove extra literal blocks in cloud-transition.rst

---

src/osd/PG.cc
src/osd/PG.h
src/osd/scrubber/osd_scrub.cc
src/osd/scrubber/pg_scrubber.cc
src/osd/scrubber/pg_scrubber.h
src/osd/scrubber/scrub_job.cc
src/osd/scrubber/scrub_job.h
src/osd/scrubber_common.h

The 'delay_ready_t' parameter was used in the past to control whether, when a change in the scrub scheduling inputs occurs (e.g. a configuration change), even those scheduling targets that are already ripe for scrubbing will have their schedule recomputed.
This parameter, however, is ignored: all "regular-periodic" scrubbing targets are always rescheduled when the scheduling inputs change.
The commit removes the 'delay_ready_t' parameter from the code base.

osd/scrub: discard delay_ready_t

---

src/crimson/os/seastore/backref/backref_tree_node.h
src/crimson/os/seastore/btree/fixed_kv_btree.h
src/crimson/os/seastore/btree/fixed_kv_node.h
src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/cache.h
src/crimson/os/seastore/cached_extent.h
src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.cc
src/crimson/os/seastore/lba_manager/btree/lba_btree_node.h
src/crimson/os/seastore/linked_tree_node.h
src/crimson/os/seastore/logical_child_node.h
src/crimson/os/seastore/omap_manager/btree/btree_omap_manager.cc
src/crimson/os/seastore/omap_manager/btree/btree_omap_manager.h
src/crimson/os/seastore/omap_manager/btree/omap_btree_node.h
src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.cc
src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.h
src/crimson/os/seastore/omap_manager/btree/string_kv_node_layout.h
src/crimson/os/seastore/onode.h
src/crimson/os/seastore/transaction_manager.h

This PR is based on https://github.com/ceph/ceph/pull/61866.
Compared to https://github.com/ceph/ceph/pull/61866, this PR offers about 20% perf improvement.
This test was done as follows:
1. Only one single-core crimson osd was involved.
2. The size of the SeaStore device was 1TB.
3. The test rbd image was 10GB in its size.
4. We used FIO to issue 64-depth uniformal random writes to the rbd image
The result was as follows:
The fio result of https://github.com/ceph/ceph/pull/61866:
```
randwrite-4k: (groupid=0, jobs=1): err= 0: pid=1587874: Fri Feb 21 10:11:23 2025
write: IOPS=2926, BW=11.4MiB/s (12.0MB/s)(14.7GiB/1319635msec); 0 zone resets
slat (usec): min=2, max=2006, avg= 6.11, stdev= 2.53
clat (usec): min=604, max=2074.8k, avg=21860.05, stdev=20657.49
lat (usec): min=614, max=2074.8k, …
```

crimson/os/seastore/omap_manager: apply linked tree nodes to omap trees

---

doc/radosgw/cloud-restore.rst
doc/radosgw/cloud-sync-module.rst
doc/radosgw/cloud-transition.rst

Remove stray example command block leftover from rebase in cloud-transition.rst.
Remove extra character > in cloud-sync-module.rst.
Add missing formatting char ` in cloud-sync-module.rst.
Remove extra empty line between example commands that resulted in a line with just a "#" prompt.
The first one is another one introduced in #62763. …

doc/radosgw: Fix formatting, cosmetic issues, typos

---

src/os/bluestore/Writer.cc

Fixes: https://tracker.ceph.com/issues/70802 …

os/bluestore: eliminate build warning

---

src/rgw/driver/rados/rgw_data_sync.cc
src/rgw/driver/rados/rgw_sync.cc

Addresses https://tracker.ceph.com/issues/70270.
This is another fix, along with the earlier fix https://github.com/ceph/ceph/pull/62156, to complete the fix for https://tracker.ceph.com/issues/70270. 
Testing has been done manually in an mstart env. Some details at [slack](https://ceph-storage.slack.com/archives/C05LPHSKVPG/p1740001077034029). Below is a slice of the slack discussion.
For testing purpose, added a custom event before & after the [RGWRadosNotifyCR call](https://github.com/ceph/ceph/blob/0da914551cb031ecafd417b13a0055e09a6083d7/src/rgw/driver/rados/sync_fairness.cc#L330) and saw that when an instance restarts it sometimes get timeout, also added some custom events within [RGWDataSyncShardNotifyCR inifinite notification …

rgw: metadata and data sync notification to retry upon any failure case

---

src/rgw/driver/rados/rgw_datalog.cc

When debugging crashes related to `RGWDataChangesLog` shutdown, I fixed the crashes, but broke the logic that decides whether to print the error.
Fixes: https://tracker.ceph.com/issues/70864 …

rgw: Don't print spurious error on `radosgw-admin` exit

---

src/rgw/rgw_rest_oidc_provider.cc

rgw/iam: correcting the caps for OIDC Provider for a user.

---

src/blk/kernel/KernelDevice.cc
src/blk/kernel/io_uring.cc
src/blk/kernel/io_uring.h
src/extblkdev/vdo/ExtBlkDevVdo.cc

blk: add missing includes

---

src/cephadm/cephadm.py

Fixes: https://tracker.ceph.com/issues/70870
- Tracker …

cephadm: Updated log message for enabling logrotate.timer service while bootstrap

---

src/crimson/osd/ops_executer.cc
src/crimson/osd/pg.cc
src/crimson/osd/replicated_backend.cc
src/crimson/osd/replicated_backend.h
src/include/encoding.h
src/messages/MOSDECSubOpReadReply.h
src/messages/MOSDECSubOpWrite.h
src/messages/MOSDRepOp.h
src/msg/Message.h
src/os/Transaction.h
src/osd/ECCommon.cc
src/osd/ECListener.h
src/osd/ECMsgTypes.cc
src/osd/ECMsgTypes.h
src/osd/ReplicatedBackend.cc
src/osd/ReplicatedBackend.h
src/test/objectstore/ObjectStoreTransactionBenchmark.cc
src/test/objectstore/test_transaction.cc

Align write data in Objectstore::Transaction encoded buffers so that RepOp and ECSubOpWrite messages align data on the receiving OSD to avoid a later memmove.  Also fix ECSubOpReadReply messages in a similar way so that read data is aligned on the receiving OSD.
Version 2 - A more complicated set of changes to Transaction.h to allow all write data to be aligned by avoiding placing the data buffer length in the data buffer. This requires the transaction to be created with two sets of bufferlists, one for the old format (used for backwards compatibility) and one for the new format.
See https://github.com/ceph/ceph/pull/57738 (version 1) for details of why data alignment is a performance issue and the concept of encoding/decoding ObjectStore::Transaction's into the payload buffer and data …

os/transaction: page align write data buffers to improve performance - version 2

---

src/osd/ECBackend.h
src/osd/ECBackendL.h
src/osd/ECSwitch.h
src/osd/PGBackend.cc
src/osd/PGBackend.h
src/osd/osd_types.cc
src/osd/osd_types.h

Changes to rollback to support optimized EC pools.
Optimized pools do not update all shards the same way, avoiding writing data that has not changed and only storing attribute updates on a subset of shards. Rollback uses a single ObjectModDesc entry in the PG log entry to work out how to undo the changes to a shard. This entry is extended to store extra details about the update so it can work out what
needs to be undo on each shard.
The changes are designed to be backwards compatible, the legacy EC code still updates all shards the same way and needs rollback to perform the same updates to all shards. When optimizations are enabled the PG log may consist of a mixture of log entries written by the legacy and new code. …

osd: EC optimizations: changes to rollback to support partial writes

---

qa/workunits/rgw/run-s3tests.sh

this workunit is supposed to work out of the box against vstart, so needs to track new markers that fail by default
<details>
</details>

qa/rgw: run-s3tests.sh disables bucket_logging tests

---

doc/radosgw/admin.rst

document the use of admin users and discourage use of system users
<details>
- `jenkins test signed` [Jenkins Job](https://jenkins.ceph.com/job/ceph-pr-commits/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-pr-commits/config/ …

doc/rgw: document Admin and System Users

---

src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h

backport of https://github.com/ceph/ceph/pull/62588
Fixes: https://tracker.ceph.com/issues/70855 …

reef: os/bluestore: Fix race in BlueFS truncate / remove

---

src/rgw/driver/rados/rgw_tools.h
src/rgw/radosgw-admin/radosgw-admin.cc
src/rgw/services/svc_bi_rados.h

This subcommand is used to ask radosgw-admin which bucket index shard a given object in a given bucket would have its bucket index entry on. The user is required to supply the number of shards (i.e., the command doesn't look that up). If 0 is provided it would result in a divide by zero runtime exception. Values less than or equal to zero are now protected.
Fixes: https://tracker.ceph.com/issues/70956 …

rgw: prevent crash in `radosgw-admin bucket object shard ...`

---

doc/radosgw/admin.rst

document the use of admin users and discourage use of system users
backport of https://github.com/ceph/ceph/pull/62871
<details> …

reef: doc/rgw: document Admin and System Users

---

doc/radosgw/admin.rst

document the use of admin users and discourage use of system users
backport of https://github.com/ceph/ceph/pull/62871
<details> …

squid: doc/rgw: document Admin and System Users

---

src/rgw/driver/rados/rgw_pubsub_push.cc
src/rgw/rgw_kafka.cc
src/rgw/rgw_kafka.h
src/test/rgw/bucket_notification/test_bn.py

backport tracker: https://tracker.ceph.com/issues/66805
---
backport of https://github.com/ceph/ceph/pull/57537
parent tracker: https://tracker.ceph.com/issues/66036
This commit was not cherrypicked and backported in https://github.com/ceph/ceph/pull/58851, so making a new PR for that commit.
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull-requests/c …

squid: rgw/notification: For kafka include user-id & password as part of the key along with endpoint for connection pooling.

---

src/pybind/cephfs/setup.py
src/pybind/rados/setup.py
src/pybind/rbd/setup.py
src/pybind/rgw/setup.py

Replace pkgutil.find_loader() with importlib.util.find_spec() throughout Python bindings. This addresses the deprecation warning in Python 3.10 (scheduled for removal in 3.14) that appeared when generating librbd Python bindings.
The importlib.util.find_spec() API has been available since Python 3.4 and is compatible with our minimum required Python version (3.9, since commit 51f71fc1).
The warning resolved:
```
/home/kefu/dev/ceph/src/pybind/rbd/setup.py:8: DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
if not pkgutil.find_loader('setuptools'):
```
- If you are …

pybind: switch from pkgutil.find_loader() to importlib.util.find_spec()

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml

backport tracker: https://tracker.ceph.com/issues/70762
---
backport of https://github.com/ceph/ceph/pull/62598
parent tracker: https://tracker.ceph.com/issues/70745

squid: mgr/dashboard: enable ha by default on subsystem POST API

---

doc/mgr/administrator.rst
doc/mgr/alerts.rst
doc/mgr/ceph_api/index.rst
doc/mgr/cli_api.rst
doc/mgr/crash.rst
doc/mgr/dashboard.rst
doc/mgr/dashboard_plugins/debug.inc.rst
doc/mgr/dashboard_plugins/feature_toggles.inc.rst
doc/mgr/dashboard_plugins/motd.inc.rst
doc/mgr/diskprediction.rst
doc/mgr/hello.rst
doc/mgr/influx.rst
doc/mgr/insights.rst
doc/mgr/iostat.rst
doc/mgr/localpool.rst
doc/mgr/mds_autoscaler.rst
doc/mgr/modules.rst
doc/mgr/nfs.rst
doc/mgr/orchestrator.rst
doc/mgr/progress.rst
doc/mgr/prometheus.rst
doc/mgr/rgw.rst
doc/mgr/smb.rst
doc/mgr/telegraf.rst
doc/mgr/telemetry.rst

For CLI commands use the "prompt" block feature consistently. And remove preceding text block ending of double colon where applicable to facilitate that.
Use the right prompt either # or $ depending if privileges needed.
Indent all CLI commands by 3 spaces which seems to be commonly the majority.
Indent some CLI command output blocks by 4 spaces, same rationale.
Fix paragraphs before CLI commands ending in rendered `.:` or `,:`.
Fix some hyperlink missing underscore at end and make it a link instead of italic text.
Use double backtick inline code formatting for filenames, paths, command parameters, function name etc.
Change some single backticks to double backticks where the item obviously seems to be from the aforementioned list.
Fix a typo in example CLI command IP address 0.0.0.0 …

doc/mgr: Promptify CLI commands and other formatting fixes

---

src/common/pick_address.cc
src/common/pick_address.h
src/osd/OSDMap.cc
src/test/test_ipaddr.cc

This is a reef backport of [#60881](https://github.com/ceph/ceph/pull/60881).
Backport tracker: https://tracker.ceph.com/issues/70922
Parent tracker: https://tracker.ceph.com/issues/67517 …

reef: common/pick_address: Add IPv6 support to is_addr_in_subnet

---

src/ceph-volume/ceph_volume/tests/util/test_encryption.py
src/ceph-volume/ceph_volume/util/encryption.py

With 18.2.5, it seems we can't activate dmcrypt'd OSDs using the upstream containers, at least `quay.io/ceph/ceph:v18.2.5`.
Backports commit [here](https://github.com/ceph/ceph/commit/607eb34b2c278566c386efcbf3018629cf08ccfd), simply cherry-picked.
In the referenced mailing list post, I suggested a dirty workaround, and am posting it being used below:
```
[root@prod-storage-001 /]# ceph-volume lvm activate --no-systemd 60 44f6ec4e-c272-4f96-951c-c9604ffcedd9
-->  RuntimeError: ('Error while checking cryptsetup version.\n', '`cryptsetup --version` output:\n', 'cryptsetup 2.7.2 flags: UDEV BLKID KEYRING FIPS KERNEL_CAPI PWQUALITY ')
[root@prod-storage-001 /]# sed -i "s/pattern:.*/pattern: str = r'(\\\d+\\\.?)+'/g" /usr/lib/python3.9/site-packages/ceph_volume/util/encryption.py …
```

reef: ceph-volume: fix regex usage in `set_dmcrypt_no_workqueue`

---

src/cephadm/cephadm.py

This field was renamed as part of
https://github.com/ceph/ceph/commit/4941d098e337f2b7ad8c6f7c90be3ae252d22f7b but the cephadm piece was still looking for "ceph_device" meaning we would never zap any devices. Worth noting this won't get caught by teuthology as we make OSDs in that env directly on top of LVs made out of a split up nvme drive and ceph-volume inventory doesn't list LVs. …

cephadm: check "ceph_device_lvm" field instead of "ceph_device" during zap

---

qa/suites/orch/cephadm/osds/1-start.yaml
qa/suites/orch/cephadm/smoke/start.yaml

Issue: tests are failing in rados/cephadm due toPG_DEGRADED warning in cluster log.
Cause: This is expected as we are intentionally killing OSDs. Adding PG_DEGRADED warning to ignorelist will prevent the test from failing when this warning is raised.
Fixes: https://tracker.ceph.com/issues/70466
<details> …

qa/suites/orch/cephadm: add PG_DEGRADED to ignorelist

---

doc/cephadm/services/rgw.rst
src/cephadm/cephadmlib/daemons/ceph.py
src/cephadm/tests/test_cephadm.py
src/pybind/mgr/cephadm/services/cephadmservice.py
src/pybind/mgr/cephadm/tests/test_cephadm.py
src/pybind/mgr/cephadm/tests/test_migration.py
src/pybind/mgr/cephadm/tests/test_spec.py
src/python-common/ceph/deployment/service_spec.py
src/python-common/ceph/tests/test_service_spec.py

Specifically through the spec file. This was added recently on the RGW side by https://github.com/ceph/ceph/commit/575f5d461706b02a596d5ce959e5fb1aa87c1d8c
This commit is to make it easier to take advantage of for users in cephadm deployments …

mgr/cephadm: allow setting up RGW delaying shutdown to complete client connections

---

src/cephadm/cephadmlib/container_lookup.py
src/cephadm/cephadmlib/listing_updaters.py
src/cephadm/tests/test_cephadm.py
src/cephadm/tests/test_listing.py

When testing an unrelated thing with rm-cluster cleaning up OSD devices, I was hitting
```
File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/sbin/cephadm/__main__.py", line 5400, in <module>
File "/usr/sbin/cephadm/__main__.py", line 5388, in main
File "/usr/sbin/cephadm/__main__.py", line 3996, in command_rm_cluster
File "/usr/sbin/cephadm/__main__.py", line 4034, in _rm_cluster
File "/usr/sbin/cephadm/__main__.py", line 428, in _infer_image
File "/usr/sbin/cephadm/cephadmlib/container_lookup.py", line 127, in infer_local_ceph_image
File "/usr/sbin/cephadm/cephadmlib/container_lookup.py", line …
```

cephadm: still set keep_container_info key in CoreStatusUpdater when cinfo is None

---

src/rgw/rgw_rest_swift.cc

backport tracker: https://tracker.ceph.com/issues/70738
---
backport of https://github.com/ceph/ceph/pull/62286
parent tracker: https://tracker.ceph.com/issues/70540

squid: rgw: fixing tempest ObjectTestACLs and ObjectACLsNegativeTest cases

---

src/rgw/driver/rados/rgw_rados.cc

backport tracker: https://tracker.ceph.com/issues/69218
---
backport of https://github.com/ceph/ceph/pull/60907
parent tracker: https://tracker.ceph.com/issues/58965

squid: rgw: Delete stale entries in bucket indexes while deleting obj

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.ts
src/pybind/mgr/dashboard/frontend/src/testing/activated-route-stub.ts

**Issue**: Pool field was blank on editing namespace form and user needs to type out pool
**Reason**: `image` field is no longer supported in form yet edit function trying to fetch it and failing on that, hence no following updates for pool
**Fix**: Removed stale `image` field
**Additional changes:**
- included unit tests for edit to capture such errors
- enhanced unit tests to sue ActivatedRouteStub and `router.url`
- pre populating pool form on create with first rbd pool in the list
Fixes https://tracker.ceph.com/issues/70966
Regression by: https://tracker.ceph.com/issues/69900
**Before:**
**After:** …

mgr/dashboard: Fix pool update on edit

---

doc/radosgw/admin.rst
doc/radosgw/cloud-sync-module.rst
doc/radosgw/metrics.rst
doc/radosgw/multisite-sync-policy.rst
doc/radosgw/multisite.rst

Use inline code formatting consistently for command line switches, data, hostnames, etc. And specifically don't inline code Ceph release names (not seen anywhere else in `docs/`).
Correctly indent text and child lists inside list items.
Remove a mid-sentence double spaces.
Capitalize "RGW" and "API" in text.
Remove unordered lists that are just regular text everywhere else.
Use correct prompt # instead of $ for privileged commands.
Use line continuation for multi-line example commands instead of render them incorrectly as separate single-line commands.
Use Title Case in few section header text that missed it.
multisite.rst: Don't repeat "(RGW)" after "RADOS gateway" beyond the first instance in the same paragraph.
multisite.rst: Change one "multisite" to "multi-site" because all other …

doc/radosgw: Improve and more consistent formatting

---

src/mds/MDCache.h

close object section only if it was opened
Fixes: https://tracker.ceph.com/issues/70707 …

mds: fix dump stray command

---

src/common/options/mon.yaml.in
src/mon/NVMeofGwMap.cc
src/mon/NVMeofGwMon.cc
src/mon/NVMeofGwTypes.h

This commit fixes the issue when during redeploy hosts might stuck due to
many failover/failbacks during very short time frame
this commit improves the previous redeploy fix since it allows to use the
short beacon timeout - no impact on the failover time …

nvmeofgw: fix host issue during redeploy, improves previous redeploy fix

---

cmake/modules/BuildBoost.cmake

Previously, the build process used `bootstrap.sh` to build the b2 tool, which automatically selected the compiler based on the specified toolset. This failed when the compiler executable had a version postfix (e.g., /usr/bin/clang++-19) without a symlink at the expected name, producing errors like:
```
A C++11 capable compiler is required for building the B2 engine.
Toolset 'clang' does not appear to support C++11.
> clang++ -x c++ -std=c++11 -pthread  check_clib.cpp check_cxx11.cpp
./tools/build/src/engine/build.sh: 120: clang++: not found
> clang++ -x c++ -std=c++11  check_clib.cpp check_cxx11.cpp
./tools/build/src/engine/build.sh: 120: clang++: not found
** Note, the C++11 capable compiler is _only_ required for building the B2
** engine. The B2 build system allows for using any C++ …
```

cmake: Fix b2 build with postfixed compiler versions

---

src/crimson/osd/CMakeLists.txt
src/crimson/osd/osd.cc
src/crimson/osd/osd.h
src/crimson/osd/osd_operation.h
src/crimson/osd/osd_operation_external_tracking.h
src/crimson/osd/osd_operations/pgpct_request.cc
src/crimson/osd/osd_operations/pgpct_request.h
src/crimson/osd/pg.cc
src/crimson/osd/pg.h
src/crimson/osd/replicated_backend.cc
src/crimson/osd/replicated_backend.h
src/osd/pg_features.h

crimson: add MOSDPGPCT support

---

src/crimson/osd/osd_operation.h
src/crimson/osd/pg.h
src/crimson/osd/pg_recovery.cc
src/crimson/osd/pg_recovery.h
src/crimson/osd/pg_recovery_listener.h
src/crimson/osd/recovery_backend.cc
src/crimson/osd/shard_services.h

- https://tracker.ceph.com/issues/70935
- https://tracker.ceph.com/issues/70936
- https://tracker.ceph.com/issues/70939
<details> …

crimson: fix several bugs causing stuck backfills

---

monitoring/ceph-mixin/dashboards/rbd.libsonnet
monitoring/ceph-mixin/dashboards_out/rbd-details.json

backport tracker: https://tracker.ceph.com/issues/70686
---
backport of https://github.com/ceph/ceph/pull/62489
parent tracker: https://tracker.ceph.com/issues/70653

squid: mgr/dashboard: fix image filter's query on rbd-details grafana panel

---

src/mon/Elector.cc
src/mon/Elector.h
src/mon/Monitor.cc

https://github.com/ceph/ceph/pull/59248 is dependent on this PR as it uses the connection score feature and this PR solves some of the issues related to connection scores.
Monitors stop pinging each other when quorum_mon_feature flag is empty. This happens when the monitor freshly starts up and never formed a quorum before, or when you restart the monitors in the cluster. Basically, Monitor startups.
This problem can easily be reproduced everytime.
Steps to reproduce:
1. Start 3 MONs with `connectivity` election strategy
2. Fail 1 mon.
3. Restart all the monitors (including the down monitor)
4. Observe that the connection scores of each monitor will tell you that not all monitors are alive. Which is not true because all 3 Monitors are in quorum.
What happened was during monitor startups, …

mon: Track and process pending pings after election

---

doc/mgr/administrator.rst
doc/mgr/alerts.rst
doc/mgr/ceph_api/index.rst
doc/mgr/cli_api.rst
doc/mgr/crash.rst
doc/mgr/dashboard.rst
doc/mgr/dashboard_plugins/debug.inc.rst
doc/mgr/dashboard_plugins/feature_toggles.inc.rst
doc/mgr/dashboard_plugins/motd.inc.rst
doc/mgr/diskprediction.rst
doc/mgr/hello.rst
doc/mgr/influx.rst
doc/mgr/insights.rst
doc/mgr/iostat.rst
doc/mgr/localpool.rst
doc/mgr/mds_autoscaler.rst
doc/mgr/modules.rst
doc/mgr/nfs.rst
doc/mgr/orchestrator.rst
doc/mgr/progress.rst
doc/mgr/prometheus.rst
doc/mgr/rgw.rst
doc/mgr/smb.rst
doc/mgr/telegraf.rst
doc/mgr/telemetry.rst

This reverts commit c4f0f8edad46c852961a622795d14b735f660d94.
- …

doc: Revert "doc/mgr: Promptify CLI commands and other formatting fixes"

---

doc/radosgw/admin.rst

Indent the CLI command continuation lines correctly to start at the same position as the other such commands, add one space on 2 lines.
Introduced in #62877. …

doc/radosgw: Fix indentation in admin.rst

---

src/nvmeof/NVMeofGwMonitorClient.cc

- return ACKNOWLEDGED/HANDLED
- remove registration for unwanted keys
shaman: https://shaman.ceph.com/builds/ceph/wip-baum-20250422-02/f7fae5679c7386cb8a5fa82af1ed6db65a13764d/
Gateway integration CI: https://github.com/ceph/ceph-nvmeof/pull/1243  …

src/nvmeof/NVMeofGwMonitorClient.cc: ms_dispatch2 clean up

---

qa/suites/nvmeof/basic/clusters/4-gateways-2-initiator.yaml
qa/suites/nvmeof/thrash/gateway-initiator-setup/16-subsys-4-namespace.yaml
qa/suites/nvmeof/thrash/thrashers/nvmeof_mon_thrash.yaml
qa/suites/nvmeof/thrash/thrashers/nvmeof_thrash.yaml
qa/suites/nvmeof/thrash/workloads/fio.yaml
qa/tasks/nvmeof.py
qa/workunits/nvmeof/fio_test.sh

qa/suites/nvmeof: Fix thrasher and fio script

---

src/crimson/common/errorator.h
src/crimson/os/cyanstore/cyan_store.h
src/crimson/os/seastore/onode_manager/staged-fltree/node.cc
src/crimson/os/seastore/onode_manager/staged-fltree/node_extent_accessor.h
src/crimson/os/seastore/onode_manager/staged-fltree/node_layout.h
src/crimson/osd/osd.cc
src/crimson/osd/osd_operations/client_request.cc
src/crimson/osd/osd_operations/internal_client_request.cc
src/crimson/osd/osd_operations/snaptrim_event.cc
src/crimson/osd/pg.cc
src/crimson/osd/pg_backend.cc
src/crimson/osd/recovery_backend.cc
src/crimson/osd/replicated_recovery_backend.cc
src/crimson/tools/store_nbd/fs_driver.cc
src/test/crimson/CMakeLists.txt
src/test/crimson/test_errorator_abort.cc

This came up during: https://tracker.ceph.com/issues/69406#note-25
Where an "assert_all" was called but didn't cause an abort.
This PR is a rework of errorator aborting paths with fixes and some cleanups. …

crimson/common/errorator: rework aborts error handlers

---

src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/test/rgw/rgw_multi/tests.py

When an object is copied from a remote bucket in a different zonegroup, a replication trace attribute (RGW_ATTR_OBJ_REPLICATION_TRACE) is added to the object's metadata. If the trace includes the same zone as the current one, subsequent attempts to serve the object may incorrectly return -ERR_NOT_MODIFIED, preventing access to the object content.
Making it optional would let us not store anything replication related when calling fetch_remote_obj() from copy object.
Fixes: https://tracker.ceph.com/issues/70839

rgw: dont store replication attrs on remote copy obj

---

doc/radosgw/adminops.rst
src/common/options/rgw.yaml.in
src/rgw/driver/motr/rgw_sal_motr.cc
src/rgw/driver/rados/rgw_bucket.cc
src/rgw/driver/rados/rgw_bucket.h
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rest_bucket.cc
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/radosgw-admin/radosgw-admin.cc
src/rgw/rgw_auth.cc
src/rgw/rgw_op.cc
src/test/rgw/rgw_multi/tests.py

Compare RGW's zonegroup with the bucket's zonegroup and only do the empty check when the bucket is owned by the RGW running the delete.
Fixes: https://tracker.ceph.com/issues/68190

rgw: skip empty check on non-owned buckets by zonegroup

---

src/test/common/CMakeLists.txt

these test cases appear to be the cause of many 'make check' failures:
> error while loading shared libraries: path/to/libceph-common.so.2: file too short
Reported in https://tracker.ceph.com/issues/70700
disable the tests until we can fix them
<details>
- …

cmake/common: temporarily remove decode_start_v_checker tests

---

src/neorados/cls/fifo.h
src/rgw/driver/rados/rgw_datalog.cc

Don't log failure if no data is there to be trimmed. This can be seen by running `radosgw-admin datalog autotrim` as well as normal auto trimming in radosgw logs.
```
2025-04-19T21:11:48.142+0000 7f46997cb640 -1 neorados::cls::fifo::FIFO::trim<const boost::asio::use_awaitable_t<>&>(const DoutPrefixProvider*, std::string, bool, const boost::asio::use_awaitable_t<>&)::<lambda(auto:318, const DoutPrefixProvider*, std::string, bool, neorados::cls::fifo::FIFO*)> [with auto:318 = boost::asio::detail::co_composed_state<void(boost::asio::io_context::basic_executor_type<std::allocator<void>, 0>), boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code>, boost::asio::detail::co_composed_returns<void(boost::system::error_code)> >; std::string = …
```

neorados: relax fifo trim error for ENODATA

---

src/rgw/rgw_rest_client.cc

RGWRESTSimpleRequest::forward_request() translates EINVAL to a 503 status code to reflect connection errors as internal errors rather than client errors. However, if the master is explicitly returning EINVAL (which corresponds to an HTTP 400 status code), this translation incorrectly converts it to 503, hiding the true client error.
To address this, we now check the HTTP status code to ensure the error originates from easy_curl and not from a valid HTTP response, preserving the intended 400 status when appropriate.
Fixes: https://tracker.ceph.com/issues/69084

rgw: handle EINVAL translation in forward_request

---

src/osd/ECBackend.cc
src/osd/ECBackend.h
src/osd/ECBackendL.cc
src/osd/ECBackendL.h
src/osd/ECSwitch.h
src/osd/PGBackend.cc
src/osd/PGBackend.h
src/osd/ReplicatedBackend.cc
src/osd/ReplicatedBackend.h
src/osd/scrubber/pg_scrubber.cc

Define two sets of performance counters to track I/O performed
by the scrubber - one set to be used when the I/O is performed
when acting as a primary, and the other when acting as a
replica (inc. EC secondary).

osd/scrub: performance counters for I/O performed by the scrubber

---

doc/rados/operations/health-checks.rst
src/mon/ConnectionTracker.cc
src/mon/ConnectionTracker.h
src/mon/Elector.cc
src/mon/Elector.h
src/mon/HealthMonitor.cc
src/mon/HealthMonitor.h

This PR is dependent on https://github.com/ceph/ceph/pull/62416 and should always be tested together.
Currently, Ceph cannot detect and report network partitions (netsplits)
between monitors in different topology locations in a consolidated way.
While stretch mode can handle partitions through monitor elections,
users lack visibility into the topology-level view of network
disconnections, making troubleshooting difficult.
This implementation adds a hierarchical netsplit detection mechanism that:
- Uses DirectedGraph structure for netsplit detection
- Maps monitor disconnections to relevant CRUSH topology levels
- Aggregates individual disconnections into location-level reports when appropriate
- Detects complete location-level netsplits when ALL monitors between locations
cannot …

HealthMonitor: Add topology-aware netsplit detection and warning

---

src/mds/Locker.cc

This ceph_assert() always fails, but depending on the configuration value `ceph_assert_supresssions`, execution may continue, but the `dir` variable is left uninitialized.  This leads to a compiler warning:
/home/jenkins-build/build/workspace/ceph-api/src/mds/Locker.cc:451:22: error: variable 'dir' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
clang then suggests to nullptr-initialize the variable:
/home/jenkins-build/build/workspace/ceph-api/src/mds/Locker.cc:447:11: note: initialize the variable 'dir' to silence this warning
447 |         CDir *dir;
|                  ^
|                   = nullptr
This, however, is a very bad idea because all this does is suppress the warning; it still crashes the process.
Since there's no recovery from …

mds/Locker: use ceph_abort_msg() instead of ceph_assert()

---

src/rgw/rgw_rest.cc

backport tracker: https://tracker.ceph.com/issues/69136
---
backport of https://github.com/ceph/ceph/pull/60910
parent tracker: https://tracker.ceph.com/issues/69093

squid: rgw: relax RGWPutACLs_ObjStore::get_params read data log

---

qa/suites/rgw/verify/inline-data$/off-no-gc.yaml

extends the `inline-data$` dimension of the rgw/verify subsuite to run with both inline data and garbage collection disabled
this improves the likelihood for test cases to detect bugs that trigger accidental deletion of tail objects
Fixes: https://tracker.ceph.com/issues/70823
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull-requests/config/definition …

qa/rgw: run verify tests with garbage collection disabled

---

PendingReleaseNotes

document support for s3 GetObjectAttributes in T, previously merged in https://github.com/ceph/ceph/pull/55259
<details> …

doc/rgw: release note for GetObjectAttributes

---

src/rgw/rgw_lc.h

This is backport of fix for the below mainline tracker
https://tracker.ceph.com/issues/68288
Fixes: https://tracker.ceph.com/issues/68424
<details>
- …

squid: rgw: Fix a bug in LCOpAction_Transition::check()

---

src/rgw/driver/dbstore/common/dbstore.cc
src/rgw/driver/dbstore/common/dbstore.h
src/rgw/driver/dbstore/sqlite/sqliteDB.cc
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/rgw_op.cc
src/rgw/rgw_sal_dbstore.cc

backport tracker: https://tracker.ceph.com/issues/70170
---
backport of https://github.com/ceph/ceph/pull/56583
parent tracker: https://tracker.ceph.com/issues/70115

squid: rgw: fix to correctly store updated attrs in backend store after erasing an attr/attrs for delete ops on a bucket.

---

src/rgw/rgw_common.h
src/rgw/rgw_rest_swift.cc
src/rgw/services/svc_bucket_sobj.cc

Fixes: https://tracker.ceph.com/issues/69588
Upstream PR: https://github.com/ceph/ceph/pull/61157
Upstream issue: https://tracker.ceph.com/issues/68195
This PR is a backport of mentioned upstream PR. 
It adds `last_modified` JSON field to the Swift bucket listing response.
It is present in [Swift API spec](https://docs.openstack.org/api-ref/object-store/), but currently is missing in the RGW response.
Result looks the following way
```bash
curl -v -XGET 127.0.0.1:8080/swift/v1/AUTH_2421cecf177b41f683bdcd09338f1ebd -H "X-Auth-Token: ${OS_AUTH_TOKEN}" -H "Accept: application/json" 
…
[{"name":"bucket1","count":1,"bytes":2814,"last_modified":"2024-12-11T13:44:15.761Z"}]
curl -v -XGET 127.0.0.1:8080/swift/v1/AUTH_2421cecf177b41f683bdcd09338f1ebd/bucket1 -H "X-Auth- Token: ${OS_AUTH_TOKEN}" -H …
```

squid: rgw: add missing last_modified field to swift api

---

doc/cephadm/services/mgmt-gateway.rst
qa/suites/orch/cephadm/workunits/task/test_mgmt_gateway.yaml
src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/services/mgmt_gateway.py
src/pybind/mgr/cephadm/services/oauth2_proxy.py
src/pybind/mgr/cephadm/templates/services/mgmt-gateway/external_server.conf.j2
src/pybind/mgr/cephadm/tests/test_services.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
src/pybind/mgr/orchestrator/module.py
src/python-common/ceph/deployment/service_spec.py

Let's rename the spec fields for `mgmt-gateway` and `oauth2-proxy` from `ssl_certificate` to `ssl_cert`, and from `ssl_certificate_key` to `ssl_key`, and `disable_https` to simply `ssl` to align with the naming conventions used by other Cephadm services such as iscsi and ingress.
Fixes: https://tracker.ceph.com/issues/70359 …

mgr/cephadm: harmonize mgmt-gateway and oauth2-proxy spec fields

---

src/libcephfs_proxy/CMakeLists.txt
src/libcephfs_proxy/libcephfsd.c
src/libcephfs_proxy/proxy_link.c

GCC 14 warns as this is apparently widely supported but Technically Incorrect.
- …

libcephfs_proxy: Remove arithmetic on `void*`

---

src/pybind/mgr/cephadm/serve.py

backport tracker: https://tracker.ceph.com/issues/65956
---
backport of https://github.com/ceph/ceph/pull/57259
parent tracker: https://tracker.ceph.com/issues/65799

reef: mgr/cephadm: Fix unfound progress events

---

src/cephadm/cephadmlib/daemons/nvmeof.py
src/cephadm/cephadmlib/sysctl.py
src/pybind/mgr/cephadm/services/nvmeof.py
src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
src/python-common/ceph/deployment/service_spec.py

mgr/cephadm/nvmeof: Allow setting NVMEoF gateway huge pages count in the spec file
Fixes https://tracker.ceph.com/issues/71043 …

mgr/cephadm/nvmeof: Allow setting NVMEoF gateway huge pages count in the spec file

---

qa/standalone/mon/availability.sh
src/mon/MgrStatMonitor.cc
src/mon/MgrStatMonitor.h
src/mon/MonCommands.h
src/mon/OSDMonitor.cc
src/mon/PGMap.cc
src/mon/PGMap.h
src/mon/mon_types.h
src/osd/PeeringState.cc
src/tools/ceph-dencoder/osd_types.h

Builds on top of: https://github.com/ceph/ceph/pull/54249
Tracker: https://tracker.ceph.com/issues/67777 
Trello: https://trello.com/c/MNmj6CgJ/764-mon-mgr-track-availability-over-time 
This PR introduces the command `ceph osd pool availability-status`. It outputs the availability score for each pool. The score is calculated every 5 seconds (this is currently not configurable but will be made so in followup PRs). 
A sample output of the command looks like this: 
```
$ ceph osd pool availability-status
2024-10-07T05:23:14.840+0000 7fd35b178640 -1 WARNING: all dangerous and experimental features are enabled.
2024-10-07T05:23:14.856+0000 7fd35b178640 -1 WARNING: all dangerous and experimental features are enabled.
POOL           UPTIME  DOWNTIME  NUMFAILURES  MTBF  MTTR  SCORE     AVAILABLE …
```

monitor: add availability score feature

---

src/crimson/os/seastore/backref/btree_backref_manager.cc
src/crimson/os/seastore/btree/fixed_kv_btree.h
src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/cache.h
src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.cc
src/crimson/os/seastore/seastore_types.cc
src/crimson/os/seastore/seastore_types.h

Don't distinguish between cache_absent and load_absent.
Drop cache_access_stats_t::cache_absent and unify with
extent_access_stats_t. …

crimson/os/seastore: simplify cache access metrics

---

src/crimson/os/seastore/async_cleaner.cc
src/crimson/os/seastore/backref/btree_backref_manager.cc
src/crimson/os/seastore/btree/fixed_kv_node.h
src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/cache.h
src/crimson/os/seastore/cached_extent.h
src/crimson/os/seastore/extent_placement_manager.h
src/crimson/os/seastore/journal/segmented_journal.cc
src/crimson/os/seastore/lba_mapping.h
src/crimson/os/seastore/record_scanner.h
src/crimson/os/seastore/seastore_types.cc
src/crimson/os/seastore/seastore_types.h
src/crimson/os/seastore/transaction.h
src/crimson/os/seastore/transaction_manager.cc
src/crimson/os/seastore/transaction_manager.h

In short:
* Refine the paddr type categories.
* Fix or improve the existing paddr type checks.
* Add checks related to cache(lru, dirty, extent-index) and transaction.
* Refine fake paddr related logic.
* Make sure root is always dirty. …

crimson/os/seastore: improve checks to the paddr types

---

src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/cached_extent.cc
src/crimson/os/seastore/cached_extent.h
src/crimson/os/seastore/logical_child_node.h
src/crimson/os/seastore/omap_manager/btree/btree_omap_manager.cc
src/crimson/os/seastore/omap_manager/btree/omap_btree_node.h
src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.h
src/crimson/os/seastore/seastore_types.h
src/crimson/os/seastore/transaction_manager.h

Also see https://github.com/ceph/ceph/pull/62876 …

crimson/os/seastore/omap_manager: simplify maybe_init from tolerating duplicated calls

---

src/test/librbd/test_notify.py

backport tracker: https://tracker.ceph.com/issues/70845
---
backport of https://github.com/ceph/ceph/pull/62727
parent tracker: https://tracker.ceph.com/issues/70831

squid: test/librbd/test_notify.py: force line-buffered output

---

PendingReleaseNotes
src/rgw/rgw_process.cc

backport tracker: https://tracker.ceph.com/issues/70210
---
backport of https://github.com/ceph/ceph/pull/61504
parent tracker: https://tracker.ceph.com/issues/69616

squid: rgw:lua: Skip the healthchecks and system requests from going to backend storage

---

qa/suites/rgw/verify/tasks/rados-pool-quota.yaml
qa/workunits/rgw/test_rgw_rados_pool_quota.py
src/rgw/driver/rados/rgw_cr_rados.cc
src/rgw/driver/rados/rgw_tools.cc
src/rgw/rgw_common.cc
src/rgw/rgw_rest.cc

backport tracker: https://tracker.ceph.com/issues/70517
---
backport of https://github.com/ceph/ceph/pull/62110
parent tracker: https://tracker.ceph.com/issues/69842

squid: rgw: rgw_init_ioctx() adds set_pool_full_try()

---

doc/radosgw/multisite-sync-policy.rst

The section header levels are reversed so the hierarchy in the TOC is incorrect. Switch around the section header levels to make the TOC hierarchy correct, for example individual examples are children of the "Examples" section.
- Original: https://docs.ceph.com/en/latest/radosgw/multisite-sync-policy/#s3-replication-api
- Rendered PR: https://ceph--62966.org.readthedocs.build/en/62966/radosgw/multisite-sync-policy/#s3-replication-api …

doc/radosgw: Fix section header levels in multisite-sync-policy.rst

---

qa/workunits/fs/misc/mkpool_layout_vxattrs.sh

This cleanup is at the very least incorrect as it can cause the MDS to throw read-only errors because the data pool is removed before it can write out backtraces.
We've not yet finalized a truly safe workflow to remove a data pool -- even flushing the MDS journals first may not be enough (considering a large purge queue).
Fixes: https://tracker.ceph.com/issues/70919 …

qa/workunits/fs/misc: remove data pool cleanup

---

doc/radosgw/STS.rst

Some text uses hardcoded ordered list numbers and as a result have duplicate list numbers (more than 1 instance of dupes). Move to use RST ordered lists and indent the contents of each list item correctly. Fix referenced list item number in text that pointed to a wrong list item.
Format references to parameter names, user IDs, file names etc as inline code.  
I think there is possibly space for more of these, like namespaces etc but I'm not sure about those.
Add prompts to example commands.
Change instances of "rgw" or "Radosgw" in text to "RGW".
Indent the title text with one space at beginning and the end which seems common.
- Before: https://docs.ceph.com/en/latest/radosgw/STS/
- Rendered PR: https://ceph--62987.org.readthedocs.build/en/62987/radosgw/STS/ …

doc/radosgw: Improve formatting in STS.rst

---

doc/radosgw/oidc.rst

Empty line after starting a pre-formatted block with the double-colon syntax is required, otherwise the double-colon does nothing and is just rendered as-is as "::" and there would be no following pre-formatted block.
Add empty lines after the double-colon syntax so that the following block is rendered pre-formatted.
Also add bash privileged prompts to a block with 2 example CLI commands. …

doc/radosgw: Fix RST syntax rendered as text in oidc.rst

---

doc/radosgw/oidc.rst

Set the length of the RST syntax underlining for section headers to be as long as the section header text.
Also it seems common to indent the document title with one space at both the beginning and the end so do that.
- Before: https://docs.ceph.com/en/latest/radosgw/oidc/
- Rendered PR: https://ceph--62986.org.readthedocs.build/en/62986/radosgw/oidc/
No visible change in rendered docs. …

doc/radosgw: Fix length of section header underlines in oidc.rst

---

doc/radosgw/config-ref.rst

The section named "QoS Settings" looks like it should not be a child of the section "SSE-S3 Settings". Move it to be a sibling to it, on the same level instead.
- Before: https://docs.ceph.com/en/latest/radosgw/config-ref/
- Rendered PR: https://ceph--62970.org.readthedocs.build/en/62970/radosgw/config-ref/ …

doc/radosgw: Fix section header level in config-ref.rst

---

doc/radosgw/oidc.rst

Empty line after starting a pre-formatted block with the double-colon syntax is required, otherwise the double-colon does nothing and is just rendered as-is as "::" and there would be no following pre-formatted block.
Add empty lines after the double-colon syntax so that the following block is rendered pre-formatted.
Also add bash privileged prompts to a block with 2 example CLI commands.
(cherry picked from commit b4fb5dc4030b4de477942630ebe3b98b882ae978) …

squid: doc/radosgw: Fix RST syntax rendeded as text in oidc.rst

---

src/osd/scrubber/scrub_machine.cc

as expected by some tests, and as is clearer for the user.
Fixes: https://tracker.ceph.com/issues/68833

osd/scrub: always round up reported scrub duration

---

qa/standalone/scrub/osd-scrub-test.sh
qa/standalone/scrub/scrub-helpers.sh

following changes in scrub code
Squid tracker:
Fixes: https://tracker.ceph.com/issues/70310
(cherry picked from commit 24647e87e8fba9b16d81730662b22798ed1885cb)
NOTE: the 'standalone' combined scrub test still fails, but now due to https://tracker.ceph.com/issues/68833.
That one will be handled in a separate PR.

squid: qa/standalone/scrub: fix osd-scrub-test.sh

---

src/osd/OSD.cc

Adding the following parameters to the (small) set of configuration options that, if changed, trigger re-computation of the next scrub schedule:
- osd_scrub_interval_randomize_ratio, (not cherry-picked) - osd_deep_scrub_interval_cv, and
- osd_deep_scrub_interval (which was missing in the list of parameters watched by the OSD).
Fixes: https://tracker.ceph.com/issues/70909
Original tracker: https://tracker.ceph.com/issues/70806
(cherry picked from commit d56f613) 
Conflicts resolved by removing refs to the deep_scrub_interval_cv parameter, which does not yet exist in this version.

squid: osd/scrub: additional configuration parameters to trigger scrub reschedule

---

src/osd/scrubber/pg_scrubber.cc

... as expected by some tests, and clearer for the user.
Fixes: https://tracker.ceph.com/issues/71099

squid: osd/scrub: always round up reported scrub duration

---

src/common/containers.h

std::aligned_storage_t was deprecated in C++23, to be prepared for it, let's use alignas for the same behavior.
- …

common: avoid using std::aligned_storage_t

---

src/libcephfs_proxy/proxy_async.c

this change is created in the same spirit of bb1fa818.
when building the tree with clang-21, following warning was raised:
```
/home/kefu/dev/ceph/src/libcephfs_proxy/proxy_async.c:43:9: warning: arithmetic on a pointer to void is a GNU extension [-Wgnu-pointer-arith]
43 |                         data += iov->iov_len;
|                         ~~~~ ^
1 warning generated.
```
this change should address this warning by casting a `void*` pointer to `char*` pointer before performing arithmetic operation on it. …

libcephfs_proxy: remove arithmetic on void*

---

src/crimson/osd/osd.cc
src/mds/MetricAggregator.cc
src/mgr/DaemonServer.cc
src/mgr/MDSPerfMetricCollector.cc
src/mgr/MetricTypes.h
src/mgr/MgrClient.cc
src/mgr/OSDPerfMetricCollector.cc
src/osd/OSD.cc

Replace `boost::variant` with `std::variant` as part of our effort to reduce third-party dependencies in favor of C++ standard library alternatives.
Benefits include:
- Improved code readability and maintainability
- Reduced external dependency surface
- More consistent API usage with other components …

mgr: migrate from boost::variant to std::variant

---

src/erasure-code/ErasureCode.cc
src/erasure-code/ErasureCodeInterface.h
src/erasure-code/isa/ErasureCodeIsa.cc
src/erasure-code/jerasure/ErasureCodeJerasure.cc
src/erasure-code/jerasure/ErasureCodeJerasure.h
src/erasure-code/lrc/ErasureCodeLrc.cc
src/erasure-code/shec/ErasureCodeShec.cc
src/osd/ECTypes.h
src/test/erasure-code/ErasureCodeExample.h

erasure-code: Handle review comments from #61804 to tidy up EC plugin changes

---

doc/radosgw/bucketpolicy.rst

Don't spell out the release that added the feature, instead use RST macro for it, like other documents do.
- Before: https://docs.ceph.com/en/latest/radosgw/bucketpolicy/
- Rendered PR: https://ceph--63009.org.readthedocs.build/en/63009/radosgw/bucketpolicy/ …

doc/radosgw: Use macro for release info in bucketpolicy.rst

---

doc/radosgw/bucketpolicy.rst

Add a missing empty line before an unordered list that caused it to be rendered as just normal text in a single paragraph, instead of a list.
Use inline code for CLI command names and other such identifiers.
Capitalize "s3" correctly as "S3" when it refers to the S3 service/API.
- Before: https://docs.ceph.com/en/latest/radosgw/bucketpolicy/
- Rendered PR: https://ceph--63006.org.readthedocs.build/en/63006/radosgw/bucketpolicy/
- …

doc/radosgw: Improve formatting in bucketpolicy.rst

---

doc/radosgw/keystone.rst

Use blocks with bash privileged command prompt for CLI command examples.  
Separate example command output to a preformatted block.  
Previously a hard-coded prompt in some place inconsistently while no prompts in others.
Indent multi-line CLI command examples consistently.
Use Title Case consistency in section titles, instead of some capitalized only first letter of title text.
Use double-backtick inline code for syntax strings, HTTP header names etc as seems common.
- Before: https://docs.ceph.com/en/latest/radosgw/keystone/
- Rendered PR: https://ceph--63007.org.readthedocs.build/en/63007/radosgw/keystone/ …

doc/radosgw: Promptify commands and improve formatting in keystone.rst

---

doc/radosgw/compression.rst

Use the bash prompt block for example CLI command.  
Separate command output from the CLI command.
Indent the multiline CLI example command the same way as in other RGW docs.
Use the correct privileged bash prompt on an already promptified example command, instead of an
unprivileged bash prompt.
- Before: https://docs.ceph.com/en/latest/radosgw/compression/
- Rendered PR: https://ceph--63008.org.readthedocs.build/en/63008/radosgw/compression/ …

doc/radosgw: Promptify CLI commands in compression.rst

---

src/osd/scrubber/scrub_machine.cc

as expected by some tests, and clearer for the user.
Backport of https://github.com/ceph/ceph/pull/62996
(cherry picked from commit b7fca3676eec20371e0735650a91add065f8faa0)
Fixes: https://tracker.ceph.com/issues/71104
Original tracker:  https://tracker.ceph.com/issues/68833

tentacle: osd/scrub: always round up reported scrub duration

---

PendingReleaseNotes
src/rgw/rgw_rest_s3.cc

backport tracker: https://tracker.ceph.com/issues/70750
---
backport of https://github.com/ceph/ceph/pull/60477
parent tracker: https://tracker.ceph.com/issues/68712

squid: <rgw> Ensure the ETag format is consistent with AWS S3 API

---

src/rgw/rgw_orphan.cc
src/rgw/rgw_orphan.h

backport tracker: https://tracker.ceph.com/issues/70594
---
backport of https://github.com/ceph/ceph/pull/62368
parent tracker: https://tracker.ceph.com/issues/70539

squid: rgw: radoslist improvements primarily to better support gap list tool

---

.github/workflows/qa-symlink.yml

 .github: run verify-qa when PR HEAD is updated

---

src/librbd/Utils.cc
src/librbd/Utils.h
src/librbd/api/Group.cc
src/librbd/librbd.cc

backport tracker: https://tracker.ceph.com/issues/70641
---
backport of https://github.com/ceph/ceph/pull/62464
parent tracker: https://tracker.ceph.com/issues/70632

squid: librbd: respect rbd_default_snapshot_quiesce_mode in group_snap_create()

---

PendingReleaseNotes
src/librbd/api/Trash.cc
src/pybind/rbd/rbd.pyx
src/test/pybind/test_rbd.py
src/tools/rbd/action/Trash.cc

backport tracker: https://tracker.ceph.com/issues/71064
---
backport of https://github.com/ceph/ceph/pull/62921
parent tracker: https://tracker.ceph.com/issues/71026

squid: librbd: disallow "rbd trash mv" if image is in a group

---

src/librbd/Utils.cc
src/librbd/Utils.h
src/librbd/api/Group.cc
src/librbd/librbd.cc

backport tracker: https://tracker.ceph.com/issues/70642
---
backport of https://github.com/ceph/ceph/pull/62464
parent tracker: https://tracker.ceph.com/issues/70632

reef: librbd: respect rbd_default_snapshot_quiesce_mode in group_snap_create()

---

qa/workunits/rbd/cli_generic.sh
src/pybind/mgr/rbd_support/schedule.py

backport tracker: https://tracker.ceph.com/issues/70674
---
backport of https://github.com/ceph/ceph/pull/62484
parent tracker: https://tracker.ceph.com/issues/70640

reef: mgr/rbd_support: always parse interval and start_time in Schedules::remove()

---

PendingReleaseNotes
src/librbd/api/Trash.cc
src/pybind/rbd/rbd.pyx
src/test/pybind/test_rbd.py
src/tools/rbd/action/Trash.cc

backport tracker: https://tracker.ceph.com/issues/71063
---
backport of https://github.com/ceph/ceph/pull/62921
parent tracker: https://tracker.ceph.com/issues/71026

reef: librbd: disallow "rbd trash mv" if image is in a group

---

doc/dev/release-checklists.rst

Handling some post-kickoff checks. …

tentacle kickoff v2

---

qa/tasks/cephfs/test_volumes.py
src/pybind/mgr/volumes/fs/operations/versions/subvolume_base.py

pybind/mgr/volumes: fix typo in casesensitive vxattr

---

src/blk/BlockDevice.cc
src/blk/BlockDevice.h
src/blk/kernel/KernelDevice.cc
src/blk/kernel/KernelDevice.h
src/common/options/global.yaml.in
src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/os/bluestore/BlueStore.cc

To ensure backword compatibility for clusters with this parameter  previously set to true.
Partially fixes: https://tracker.ceph.com/issues/70327
Additionally brings perf counters to bdev. This includes a new one to track discard threads. …

squid: blk/kernel: bring "bdev_async_discard" config parameter back.

---

src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/test/objectstore/store_test.cc

backport of #62588
Fixes: https://tracker.ceph.com/issues/70856 …

squid: os/bluestore: Fix race in BlueFS truncate / remove

---

doc/rados/configuration/mclock-config-ref.rst
doc/rados/configuration/osd-config-ref.rst
src/common/options/osd.yaml.in
src/osd/OSD.cc
src/osd/OSD.h
src/osd/PG.h

backport tracker: https://tracker.ceph.com/issues/70427
--------
backport of #59516
parent tracker: https://tracker.ceph.com/issues/67700

reef: OSD: Split osd_recovery_sleep into settings applied to degraded or clean PGs

---

qa/standalone/scrub/osd-scrub-repair.sh

Modified chunks of 'expected output' in osd-scrub-repair.sh,
following changes to various dump formats (mostly related
to changes in EC code).
Fixes:  https://tracker.ceph.com/issues/70851

qa/standalone/scrub: fix expected outputs in repair tests

---

src/pybind/mgr/dashboard/frontend/cypress/e2e/block/images.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/cluster/configuration.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/common/forms-helper.feature.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/ui/role-mgmt.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/ui/user-mgmt.po.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-button-panel/form-button-panel.component.html

This commit fixes inconsistencies in Cypress test IDs.
Both data-testid and data-cy were being used — this change replaces all data-cy attributes with data-testid to keep it 
consistent across the codebase.
Fixes: https://tracker.ceph.com/issues/70986 …

mgr/dashboard: Replace data-cy with data-testid for cypress IDs

---

src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/bluefs_types.cc
src/os/bluestore/bluefs_types.h
src/os/bluestore/bluestore_tool.cc
src/test/objectstore/store_test.cc
src/test/objectstore/test_bluefs.cc

Fixes: https://tracker.ceph.com/issues/70711
Parent tracker: https://tracker.ceph.com/issues/68772
Backports: https://github.com/ceph/ceph/pull/62174 …

squid: os/bluestore: use block size (4K) as minimal allocation unit for dedicated DB/WAL volumes

---

src/mon/PGMap.cc
src/test/mon/PGMap.cc

Fixes: https://tracker.ceph.com/issues/67907
(cherry picked from commit 5ae09aedbd15575686f3e4531aad519fac3bc537)
The scaling of max_avail by the ratio of non-degraded to total objects count results in the reported max_avail increasing proportionally to the number of OSDs marked `down` but not `out`.  This is counter intuitive since OSDs going `down` should never result in more space being available.
Removing the scale factor allows max_avail to remain unchanged until the OSDs are marked `out`.
Signed-off-by: Michael J. Kidd <linuxkidd@gmail.com> …

squid: PGMap: remove pool max_avail scale factor

---

src/osd/scheduler/OpSchedulerItem.cc

backport tracker: https://tracker.ceph.com/issues/70904
---
backport of https://github.com/ceph/ceph/pull/62704
parent tracker: https://tracker.ceph.com/issues/70811

squid: osd/scheduler/OpSchedulerItem: Fix calculation of recovery latency counters

---

qa/tasks/ceph_manager.py
qa/tasks/daemonwatchdog.py
qa/tasks/mon_thrash.py
qa/tasks/scrub.py
qa/tasks/thrasher.py
qa/tasks/thrashosds.py

backport tracker: https://tracker.ceph.com/issues/67504
---
backport of https://github.com/ceph/ceph/pull/58282
parent tracker: https://tracker.ceph.com/issues/66698

squid: qa/tasks: watchdog should terminate thrasher

---

src/common/not_before_queue.h

common/not_before_queue: Fix signed comparison warning

---

doc/radosgw/compression.rst

Remove a full stop that seems to be a typo in the middle of a sentence.
Someone better versed in the English language might debate whether it should instead be a comma or a semicolon, feedback is welcome. …

doc/radosgw: Remove stray full stop mid-sentence in compression.rst

---

doc/radosgw/admin.rst

Instead of not defining a prompt to use in CLI commands and falling back to the default unprivileged prompt, use explicit privileged bash prompt for CLI commands that require privileges.
- Before: https://docs.ceph.com/en/latest/radosgw/admin/#admin-and-system-users
- Rendered PR: https://ceph--63029.org.readthedocs.build/en/63029/radosgw/admin/#admin-and-system-users …

doc/radosgw: Use privileged prompt for CLI commands in admin.rst

---

doc/radosgw/d3n_datacache.rst

Change to a full stop one comma that is followed by capital case and looks like a separate sentence otherwise too.
Add missing inline code formatting consistently for file names, config data, etc.
Use a boxed "note" RST admonition instead of spelling out "NOTE" in the beginning of the paragraph.
For one sentence capitalize first letter & add full stop at the end.
Use Title Case instead of ALL CAPS in a section title text.  
The TOC shows this the same way as it is capitalized in the source even if the rendered section titles are always all caps.
- Before: https://docs.ceph.com/en/latest/radosgw/d3n_datacache/
- Rendered PR: https://ceph--63028.org.readthedocs.build/en/63028/radosgw/d3n_datacache/ …

doc/radosgw: Improve formatting in d3n_datacache.rst

---

doc/radosgw/placement.rst

Use preformatted blocks with a privileged bash prompt instead of hardcoding prompts in the beginning of each line for CLI commands.
Indent continuation lines of multi-line CLI example commands the same way they are indented elsewhere.
Indent for one line included a tab character, changed it to spaces instead.
Use inline code formatting consistently, add double-backticks for inside text references to CLI commands, configuration data, etc.
- Before: https://docs.ceph.com/en/latest/radosgw/placement/
- Rendered PR: https://ceph--63033.org.readthedocs.build/en/63033/radosgw/placement/ …

doc/radosgw: Promptify cmds and improve formatting in placement.rst

---

src/crimson/osd/recovery_backend.cc

```
scan_for_backfill was seperated to scan_for_backfill_primary and scan_for_backfill_replica.
The fix from:
https://github.com/ceph/ceph/pull/62837/commits/88432ebd7432c513ccd495e77425401beddb9953 was only copied to the replica version.
Fixes: https://tracker.ceph.com/issues/71124
``` …

crimson/osd/recovery_backend: scan_for_backfill_primary correctly handle missing object

---

qa/standalone/scrub/osd-scrub-repair.sh

Modified chunks of 'expected output' in osd-scrub-repair.sh,
following changes to various dump formats (mostly related
to changes in EC code).
A backport of https://github.com/ceph/ceph/pull/63010
Fixes: https://tracker.ceph.com/issues/71126
Original tracker: https://tracker.ceph.com/issues/70851
(cherry picked from commits:
https://github.com/ceph/ceph/commit/3aceb1fd44876877a6ddca7cd14eb3c2f8ed8790
https://github.com/ceph/ceph/commit/139967011d98d0cc75584750e19192573c8421a3
https://github.com/ceph/ceph/commit/4816832555d9f3034d2cd4c399e74c262d098e22
)

tentacle: qa/standalone/scrub: fix expected outputs in repair tests

---

doc/cephfs/fs-volumes.rst
qa/tasks/cephfs/test_volumes.py
src/pybind/mgr/volumes/fs/operations/subvolume.py
src/pybind/mgr/volumes/fs/operations/versions/subvolume_base.py
src/pybind/mgr/volumes/fs/operations/versions/subvolume_v1.py
src/pybind/mgr/volumes/fs/operations/versions/subvolume_v2.py
src/pybind/mgr/volumes/fs/volume.py
src/pybind/mgr/volumes/module.py

pybind/mgr/volumes: make casesensitive attr uniform in interface

---

src/ceph-volume/ceph_volume/tests/util/test_disk.py
src/ceph-volume/ceph_volume/util/disk.py

backport tracker: https://tracker.ceph.com/issues/71109
---
backport of https://github.com/ceph/ceph/pull/63004
parent tracker: https://tracker.ceph.com/issues/71101

tentacle: ceph-volume: Fix splitting with too many parts

---

doc/rados/configuration/mclock-config-ref.rst

Describe the steps involved to
- Specify a global value for osd_mclock_max_capacity_iops_{ssd,hdd}, and
- Override existing individually scoped values for OSDs determined during
start-up for osd_mclock_max_capacity_iops_{ssd,hdd}.
The above is to help with the following:
- Steps to override existing setting with a global value.
- reduce the number of entries in the mon store and instead use a single
global specification for all OSDs in the cluster in case the underlying
hardware is the same for all OSDs.
Signed-off-by: Sridhar Seshasayee <sseshasa@redhat.com>
Fixes: https://tracker.ceph.com/issues/70774 …

doc/rados: Update mClock doc on steps to override OSD IOPS capacity config

---

src/crimson/os/seastore/btree/fixed_kv_btree.h
src/crimson/os/seastore/journal/circular_journal_space.h
src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.h
src/crimson/os/seastore/linked_tree_node.h
src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.cc
src/crimson/osd/pg_map.cc
src/crimson/osd/pg_recovery.cc

crimson: fix unused variable warnings due to assert() and NDEBUG builds

---

src/crimson/osd/recovery_backend.h
src/crimson/osd/replicated_recovery_backend.cc

There were two main issues due to that backfill not showing any progress 
1) The registry hash was not correctly handled in complete_to function.
After completion of the tracked objects the object was not erased correctly
from the registry.
2) There was a race condition in wait_for_pushes and set_pushed. set_pushed is called
before wait_for_pushes so it was not able to get a future to complete an operation.
Fixes: https://tracker.ceph.com/issues/70502
Credits: Radoslaw Zarzynski <rzarzyns@redhat.com> …

crimson: PG backfill is not showing any progress

---

qa/tasks/cephfs/test_volumes.py
src/pybind/mgr/volumes/fs/operations/volume.py

If one of the pool names passed to "ceph fs volume create" command
(through --data-pool and --meta-pool name) is absent, don't delete the
pool that is present and passed to this command during the cleanup code
of this command.
IOW, "volume create" command should continue deleting pool created by it
but not delete pool created by the user.
Fixes: https://tracker.ceph.com/issues/70945 …

mgr/vol: don't delete user-created pool in "volume create" command

---

doc/radosgw/metrics.rst

The document uses mostly the term Ceph Object Gateway except in three places where "Radosgw", "rgw" or obviously typod "radogw" is used.
Change those instances to Ceph Object Gateway consistent with the rest of the document.
- Before: https://docs.ceph.com/en/latest/radosgw/metrics/
- Rendered PR: https://ceph--63062.org.readthedocs.build/en/63062/radosgw/metrics/ …

doc/radosgw: Use Ceph Object Gateway as term in metrics.rst

---

doc/cephadm/services/rgw.rst

Correct the presentation of an example string in doc/cephadm/rgw.rst in order to obviate an error reading "rgw.rst:202: WARNING: Inline emphasis start-string without end-string." …

doc/cephadm: correct markup in rgw.rst

---

doc/rados/configuration/mclock-config-ref.rst

backport tracker: https://tracker.ceph.com/issues/71143
---
backport of https://github.com/ceph/ceph/pull/62826
parent tracker: https://tracker.ceph.com/issues/70774

tentacle: doc/rados: Update mClock doc on steps to override OSD IOPS capacity config

---

doc/rados/configuration/mclock-config-ref.rst

backport tracker: https://tracker.ceph.com/issues/71141
---
backport of https://github.com/ceph/ceph/pull/62826
parent tracker: https://tracker.ceph.com/issues/70774

reef: doc/rados: Update mClock doc on steps to override OSD IOPS capacity config

---

doc/rados/configuration/mclock-config-ref.rst

backport tracker: https://tracker.ceph.com/issues/71142
---
backport of https://github.com/ceph/ceph/pull/62826
parent tracker: https://tracker.ceph.com/issues/70774

squid: doc/rados: Update mClock doc on steps to override OSD IOPS capacity config

---

qa/crontab/teuthology-cronjobs

And delete reef nightlies. This is primarily because we do not have capacity to also test reef. …

qa/crontab: add tentacle nightlies

---

src/rgw/driver/rados/rgw_bucket.cc
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/rgw_lc.cc
src/rgw/rgw_lc.h
src/rgw/rgw_op.cc

merge_and_store_attrs() is no longer able to remove xattrs. change the sal::Bucket's attrs manually and call put_info() to write them back
revives https://github.com/ceph/ceph/pull/57530 but with the `bool update_attrs` argument preserved
Fixes: https://tracker.ceph.com/issues/71083
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull-requests/config/defi …

rgw/lc: stop using merge_and_store_attrs in remove_bucket_config

---

src/rgw/rgw_auth_keystone.cc

Ceph RGW admin credentials must not be a requirement. Both ec2 auth and keystone token validation work without an admin token.
And the user token verification will use its own token. The only requirement for the service admin user token is the allow_expired, but in our case we don't use this parameter.
fixes: https://tracker.ceph.com/issues/68327
Co-authored-by: @kayrus …

rgw: make keystone work without admin token(service ac requirement)

---

doc/cephadm/services/rgw.rst

Correct the presentation of an example string in doc/cephadm/rgw.rst in order to obviate an error reading "rgw.rst:202: WARNING: Inline emphasis start-string without end-string."
(cherry picked from commit 64bb1cffe3dd2fc495f9f4ddab1dc6c512eda624) …

reef: doc/cephadm: correct markup in rgw.rst

---

doc/radosgw/metrics.rst

Use inline code formatting for label syntax examples inside text.
- Before: https://docs.ceph.com/en/latest/radosgw/metrics/
- Rendered PR: https://ceph--63064.org.readthedocs.build/en/63064/radosgw/metrics/ …

doc/radosgw: Use inline code for label syntax in metrics.rst

---

doc/radosgw/admin.rst
doc/radosgw/d3n_datacache.rst
doc/radosgw/layout.rst
doc/radosgw/lua-scripting.rst
doc/radosgw/rgw-cache.rst

Use "RADOS Gateway" instead of "Rados Gateway", "rados gateway" etc.  
I am aware of the term "Ceph Object Gateway" but this change intends to be an uncontroversial low hanging fruit fix of obviously incorrectly capitalized terms.
Use "RGW daemon" instead of "Gateway", "Rados Gateway" etc.  
Use "RGW instance" instead of "rados gateway" for consistency with exactly similar other instance.
If referring obviously clearly to an instance of the daemon with an obviously not preferred term, change it to "RGW daemon"; for example when talking about restarting the RGW.  
Do not touch other instances that are not 100% clear.
The files touched mostly do not use "Ceph Object Gateway" so changing the term to it would create inconsistency, or several more changes would need to be done to update all …

doc/radosgw: Improve language, capitalization and use config database

---

qa/suites/rados/singleton/all/test-crash.yaml

backport tracker: https://tracker.ceph.com/issues/70136
---
backport of https://github.com/ceph/ceph/pull/60934
parent tracker: https://tracker.ceph.com/issues/69010

reef: rados/test_crash.sh: add PG_DEGRADED to ignorelist

---

src/ceph-volume/ceph_volume/tests/util/test_disk.py
src/ceph-volume/ceph_volume/util/disk.py

backport tracker: https://tracker.ceph.com/issues/71105
---
backport of https://github.com/ceph/ceph/pull/63004
parent tracker: https://tracker.ceph.com/issues/71101

squid: ceph-volume: Fix splitting with too many parts

---

src/osd/OSD.cc

Likely build-in OSD benchmarking is a source for bluestore slow ops in BlueStore at Teuthology runs.
Let's have more logging for this procedure.
Related-to: https://tracker.ceph.com/issues/68337 …

osd: be more verbose in OSD::run_osd_bench_test

---

src/osd/PrimaryLogPG.cc
src/osd/PrimaryLogPG.h

In replicated read scenario we first check if is_unreadable_object for the head object. If so, l_osd_replica_read_redirect_missing is incremented.
Later on, we check if can_serve_replica_read, if we've seen any writes on this object(head) l_osd_replica_read_redirect_conflict is incremented.
Lastly, the object context is needed to be obtained (find_object_context), if the requested object is a clone object - we will need to resolve it to the corresponding actual object from the OSD prespective.
There could be cases where the clone object is actually missing and we would have to drop the replicated read rather late in the flow - only once find_object_context will fail to get the relevant obc.
Moreover, in this case l_osd_replica_read_redirect_missing is not incremented while …

osd/PrimaryLogPG: Relax replicated reads when recovering

---

src/osd/ECBackend.cc
src/osd/ECBackendL.cc
src/osd/ECCommon.h
src/osd/ECCommonL.h
src/osd/ReplicatedBackend.cc
src/osd/ReplicatedBackend.h

Fixing the very minor irritation of having the constant fadvise flags declared as a function-scope variable.

osd/scrub: making Scrub's fadvide flags a constant

---

src/rgw/driver/rados/rgw_bucket.cc
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/rgw_lc.cc
src/rgw/rgw_lc.h
src/rgw/rgw_op.cc

backport tracker: https://tracker.ceph.com/issues/71151
---
backport of https://github.com/ceph/ceph/pull/62980
parent tracker: https://tracker.ceph.com/issues/71083

tentacle: rgw/lc: stop using merge_and_store_attrs in remove_bucket_config

---

doc/cephfs/charmap.rst

The charmap is not applied to snapshot names! …

doc/cephfs: add snapshot name note

---

src/rgw/driver/rados/rgw_rados.cc
src/rgw/rgw_asio_frontend.cc

rgw_beast_enable_async=0 can be used to run process_request() without a coroutine context, which can make stack traces easier to view and debug
however, the frontend's reads/writes through ClientIO were still using the yield_context to suspend/resume. so after ClientIO, the stack traces came from the coroutine resume instead of process_request()
the beast frontend's ClientIO now issues synchronous reads/writes when rgw_beast_enable_async is disabled
<details> …

rgw: frontend reads/writes respect rgw_beast_enable_async

---

PendingReleaseNotes
doc/radosgw/frontends.rst
src/rgw/rgw_asio_frontend.cc

Allow running multiple rgw processed on the same port/host.
Fixes https://tracker.ceph.com/issues/71155
- Tracker …

rgw/frontend: Allow multiple RGWs to run on same port on same host

---

src/rgw/driver/daos/rgw_sal_daos.cc
src/rgw/driver/motr/rgw_sal_motr.cc
src/rgw/driver/rados/rgw_cr_rados.cc
src/rgw/driver/rados/rgw_lc_tier.cc
src/rgw/driver/rados/rgw_putobj_processor.cc
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/driver/rados/rgw_sal_rados.h
src/rgw/rgw_op.cc
src/rgw/rgw_rest_s3.cc
src/rgw/rgw_rest_swift.cc
src/rgw/rgw_sal.h
src/rgw/rgw_sal_dbstore.cc
src/rgw/rgw_sal_filter.h
src/rgw/rgw_sal_store.h

I didn't add a test case for this since it requires injecting a artificial delay into the code in order to create the racing condition, and I can't think of any way to consistently create the situation without the code change. Please see the reproducing steps in the tracker issue.
Fixes: https://tracker.ceph.com/issues/70992 …

rgw: prefetch data from versioned object instance head

---

src/rgw/driver/rados/rgw_bucket.cc
src/rgw/driver/rados/rgw_rest_bucket.cc
src/rgw/driver/rados/rgw_rest_user.cc
src/rgw/radosgw-admin/radosgw-admin.cc
src/rgw/rgw_common.cc
src/rgw/rgw_op.cc
src/rgw/rgw_op.h
src/rgw/rgw_period_puller.cc
src/rgw/rgw_rest_account.cc
src/rgw/rgw_rest_client.cc
src/rgw/rgw_rest_client.h
src/rgw/rgw_rest_conn.cc
src/rgw/rgw_rest_conn.h
src/rgw/rgw_rest_iam.cc
src/rgw/rgw_rest_iam.h
src/rgw/rgw_rest_iam_group.cc
src/rgw/rgw_rest_iam_user.cc
src/rgw/rgw_rest_pubsub.cc
src/rgw/rgw_rest_role.cc
src/rgw/rgw_rest_user_policy.cc
src/test/rgw/rgw_multi/tests.py

when a forwarded request fails on the master zone, the local zone should return that same error response back to the client. this means reproducing both the http error and the aws xml `<Error>` response
`rgw_forward_request_to_master()` stores these errors in `s->err`, and `set_req_state_err()` now avoids overwriting existing an error
Fixes: https://tracker.ceph.com/issues/71098
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | …

rgw/multisite: rgw_forward_request_to_master() preserves Error responses

---

qa/tasks/radosgw_admin_rest.py
src/rgw/driver/rados/rgw_rest_bucket.cc

admin api should return the correct error code when the bucket doesn't exist on bucket deletion. apparently a regression by 9ae2d8c4e95807179fc17f84be6754d2b19fe639. reported by https://github.com/ceph/go-ceph/issues/1107#issuecomment-2840986935
Fixes: https://tracker.ceph.com/issues/71159
<details> …

rgw-admin: report correct error code for non-existent bucket on deletion

---

CMakeLists.txt
cmake/modules/CPM.cmake
src/test/CMakeLists.txt
src/test/common/CMakeLists.txt
src/test/rgw/CMakeLists.txt
src/test/rgw/test_rgw_hex.cc

This adds initial support for the popular Catch2 C++ unit test framework.
- [x ] …

Add Support for Catch2 unit tests

---

src/osd/osd_types.h

Recent changes (PR #29893) removed the “new_object” parameter from missing.add() and the pg_missing_item constructor. As a result, when processing delete log entries, if an object is found on disk, its on‑disk version is stored as “have” instead of the default eversion_t() (0'0). The invariant in read_log_and_missing() then fails because delete entries are expected to have “have” set to eversion_t().
This patch reintroduces the following check:
if (have == eversion_t())
clean_regions.mark_object_new();
By doing so, we ensure that when the on‑disk “have” is default, the missing record is marked as new—restoring the previous behavior and satisfying the invariant for delete operations.
Fixes: https://tracker.ceph.com/issues/45702 …

osd_types: Restore new_object marking for delete missing entries

---

src/osd/OSD.cc

Fixes: https://tracker.ceph.com/issues/70878 …

osd: fix init of op_queue_type_t due to returnable ceph_assert()

---

src/pybind/mgr/volumes/fs/async_cloner.py
src/pybind/mgr/volumes/fs/stats_util.py
src/pybind/mgr/volumes/fs/volume.py

Fixes: https://tracker.ceph.com/issues/71019 …

mgr/vol: some improvements for stats_util.py and async_cloner.py

---

src/pybind/mgr/cephadm/services/nvmeof.py

Previously, we had added a commit to block deploying nvmeof daemons on hosts with other nvmeof daemons that share a group. However, after discussion with the nvmeof team, they'd prefer we blocking co-locating nvmeof daemon entirely …

mgr/cephadm: block deploying nvmeof daemons on the same host

---

src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/utils.py

No docs as I think upgrading each daemon is the expectation anyway, and no tests as we need a version that has SMB to upgrade from for that. Once Tentacle branches off and has its own builds, we should definitely add SMB to some Tentacle --> main upgrade tests …

mgr/cephadm: add smb to upgrade order

---

src/pybind/mgr/cephadm/services/nfs.py
src/pybind/mgr/nfs/cluster.py

Add VIP to HAProxy_Hosts list for ingress type haproxy-protocol
Fixes: https://tracker.ceph.com/issues/70985
Testing logs:
```
[ceph: root@ceph-node-0 /]# ceph nfs cluster create mynfs '1 ceph-node-2 ceph-node-3' --ingress --virtual_ip 192.168.100.110 --ingress_mode haproxy-protocol
[ceph: root@ceph-node-0 /]# ceph nfs cluster info mynfs
{
"mynfs": {
"backend": [
{
"hostname": "ceph-node-2",
"ip": "192.168.100.102",
"port": 12049
}
],
"ingress_mode": "haproxy-protocol",
"monitor_port": 9049,
"port": 2049,
"virtual_ip": "192.168.100.110"
}
}
[ceph: root@ceph-node-0 /]# ceph orch ps | grep nfs
haproxy.nfs.mynfs.ceph-node-3.jickgu     ceph-node-3  *:2049,9049  running (63s)    36s ago  63s    2935k        - …
```

mgr/nfs: Add VIP to HAProxy_Hosts list for ingress type haproxy-protocol

---

qa/workunits/rgw/test_rgw_datacache.py
src/rgw/driver/rados/rgw_d3n_datacache.cc
src/rgw/rgw_d3n_cacherequest.h

storing S3 objects under deep directory hierarchy
resulted in a long path which iafter URL encoding resulted in a long cached filename that is longer than the POSIX max of 256 chars manifesting as writes to D3N cache failing with:
```
❯ errno 36
ENAMETOOLONG 36 File name too long
```
Fixes: https://tracker.ceph.com/issues/70333 …

rgw/d3n: store cached objects using hash digest

---

monitoring/ceph-mixin/prometheus_alerts.libsonnet
monitoring/ceph-mixin/prometheus_alerts.yml
monitoring/ceph-mixin/tests_alerts/test_alerts.yml

Change NVMeoFTooManyNamespaces and NVMeoFTooManySubsystems 
alert to trigger for ">= $limit" instead of "> $limit".
Will add BZ link here soon …

monitoring: Fix NVMeoF subsys/namespace limit alerts

---

src/crimson/common/interruptible_future.h
src/crimson/osd/backfill_state.cc
src/crimson/osd/osd_operations/background_recovery.cc
src/crimson/osd/osd_operations/background_recovery.h
src/crimson/osd/pg.cc
src/crimson/osd/pg.h
src/crimson/osd/pg_recovery.cc
src/crimson/osd/pg_recovery.h
src/crimson/osd/pg_recovery_listener.h

We had few confusions around the return value usage from start_recovery_ops.
Rewriting start_recovery_ops and changing the return type of do_recovery should help avoid future mistakes.
new logs should help with https://tracker.ceph.com/issues/70501#note-3 …

crimson/osd/pg_recovery: rework start_recovery_ops

---

src/crimson/osd/recovery_backend.cc

missing object
scan_for_backfill was seperated to scan_for_backfill_primary and scan_for_backfill_replica.
The fix from:
https://github.com/ceph/ceph/pull/62837/commits/88432ebd7432c513ccd495e77425401beddb9953 was only copied to the replica version.
Fixes: https://tracker.ceph.com/issues/71124
backport of https://github.com/ceph/ceph/pull/63035
(cherry picked from commit 2848bc8ce33bb786e4be3ea52559660282544881)
- When filling out …

tentacle: crimson/osd/recovery_backend: scan_for_backfill_primary correctly handle

---

qa/tasks/cephfs/mount.py

Most of wifi routers are using 192.168.0.0/16 network by default, as well as in many lab setup this is most popular network range.. If someone tries and establish libvirt based teuthology setup at home pc or laptop, for example, using downburst, they may experience unnecessary troubles with executing tests which use ceph-fuse tasks and cephfs/mount code.
It is better to use some unique range to avoid conflicts and extra configuration of network environment.
Fixes: https://tracker.ceph.com/issues/70817 …

tasks/cephfs/mount: use 192.168.144.0.0/20 for brxnet

---

doc/_ext/ceph_commands.py
qa/suites/fs/volumes/tasks/volumes/test/basic.yaml
qa/tasks/cephfs/filesystem.py
qa/tasks/cephfs/test_volumes.py
src/pybind/ceph_argparse.py
src/pybind/mgr/volumes/module.py

test subvolgroup and subvol names and declare empty/whitespace strings as bad names
Fixes: https://tracker.ceph.com/issues/58645
Signed-off-by: Milind Changire mchangir@redhat.com
<details>
- `jenkins …

mgr/volumes: handle bad arguments during subvolume create

---

doc/cephadm/upgrade.rst

doc/cephadm: Correct formatting in upgrade.rst …

doc/cephadm: Correct formatting in upgrade.rst

---

src/cls/rbd/cls_rbd.cc

It can take upto 30s for the image mirror status to be written to rbd_mirroring on the secondary for a newly created image. This fix attempts to reduce the time by writing the status to rbd_mirroring even if the image state is set to CREATING. …

cls/rbd: write image mirror status if state is CREATING

---

doc/radosgw/frontends.rst

Capitalize terms like IPv4, SSL, URI consistently.
Title case for "Ceph Monitor".
Fix "Nagel" to "Nagle".
Use inline code consistently in references to configuration values and reference to "beast" front-end.
- Before: https://docs.ceph.com/en/latest/radosgw/frontends/
- Rendered PR: https://ceph--63156.org.readthedocs.build/en/63156/radosgw/frontends/ …

doc/radosgw: Cosmetic and formatting improvements in frontends.rst

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/model/nvmeof.py
src/pybind/mgr/dashboard/services/nvmeof_client.py
src/pybind/mgr/dashboard/tests/test_nvmeof_client.py

* migrate `finalize` param functinality to the `convert_to_model` decorator
* use `convert_to_model` with `finalize` in host list API\CLI endpoint
* remove the old `map_collection` and `map_model` decorators as these are no longer being used.
```
[myuser@myvm ~]# ceph nvmeof host list --nqn=nqn.2016-06.io.spdk:cnode1.mygroup1
{"status": 0, "error_message": "Success", "allow_any_host": true, "subsystem_nqn": "nqn.2016-06.io.spdk:cnode1.mygroup1", "hosts": [{"nqn": "*"}]}
```
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatc …

Remove map collection dec

---

do_cmake.sh

and is particularly annoying in jenkins logs …

do_cmake.sh: remove --progress, it's just noise

---

src/os/bluestore/BlueStore_debug.cc

It was not printed at all. Sometimes it is important.
- …

os/bluestore: Add printing shards to Onode::printer

---

src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/tests/test_cephadm.py

Also run ok_to_stop logic for daemons when
stopping a daemon with "ceph orch daemon stop <daemon>"
```
[root@cephnvme-devel-server-vallari ~]# ceph orch ps
NAME                                                        HOST                           PORTS                   STATUS        REFRESHED  AGE  MEM USE  MEM LIM  VERSION                IMAGE ID      CONTAINER ID
alertmanager.cephnvme-devel-server-vallari                  cephnvme-devel-server-vallari  *:9093,9094             running (5m)     3m ago   6m    14.7M        -  0.27.0                 11f11916f8cd  cae7a194f273
ceph-exporter.cephnvme-devel-server-vallari                 cephnvme-devel-server-vallari  *:9926                  running (6m)     3m ago   6m    7963k        -  20.0.0-1260-gf20e4428  baa96de07d1f  1c5ce2eb38fe …
```

mgr/cephadm/module.py: Run ok_to_stop logic for stop

---

src/python-common/ceph/cephadm/images.py

backport tracker: https://tracker.ceph.com/issues/71158
---
backport of https://github.com/ceph/ceph/pull/62827
parent tracker: https://tracker.ceph.com/issues/70929

tentacle: mgr/dashboard: Bump grafana version to 11.6.0 

---

qa/tasks/mgr/dashboard/helper.py
qa/tasks/mgr/dashboard/test_rgw.py

Failure in https://jenkins.ceph.com/job/ceph-api/95185/
```
dashboard.rest_client.RequestException: RGW REST API GET timed out after 45 seconds (url=http://172.21.5.32:8000/admin/realm?list).
``` …

qa/tests: skip rgw site tests in api

---

doc/mgr/ceph_api/index.rst

Edit doc/mgr/ceph_api/index.rst as part of the project to determine where the error is in https://github.com/ceph/ceph/pull/62782 that prevents the Jenkins tests from passing. …

doc/mgr/ceph_api: edit index.rst

---

src/pybind/mgr/dashboard/.pylintrc

backport tracker: https://tracker.ceph.com/issues/71257
---
backport of https://github.com/ceph/ceph/pull/63180
parent tracker: https://tracker.ceph.com/issues/71246

reef: mgr/dashboard: fix make check tests

---

src/pybind/mgr/dashboard/.pylintrc

backport tracker: https://tracker.ceph.com/issues/71256
---
backport of https://github.com/ceph/ceph/pull/63180
parent tracker: https://tracker.ceph.com/issues/71246

tentacle: mgr/dashboard: fix make check tests

---

doc/mgr/administrator.rst

Edit doc/mgr/administrator.rst. Add prompts and correct some of the inelegant English present in the file. …

doc/mgr: edit administrator.rst

---

doc/radosgw/account.rst
doc/radosgw/admin.rst
doc/radosgw/cloud-transition.rst
doc/radosgw/config-ref.rst
doc/radosgw/frontends.rst

Use validated `:ref:` hyperlinks instead of "external links" in "target definitions" when linking within the Ceph docs:
- Add a label at beginning of referenced files if missing.
Hyperlinks were changed to `:ref:`s in three files: `admin.rst` `cloud-transition.rst` `frontends.rst`.  
After editing it was confirmed that no occurrences of "`_" using the old target definitions remained in the file.  
The other two modified files had label added at the beginning of the file.
The rendered PR should look mostly the same as the old docs, only differing in the source RST.  
One link text is changed from "Config Reference" to the full automatic section title "Ceph Object Gateway Config Reference" which seems fine.
Labels for `account.rst` and `frontends.rst` …

doc/radosgw: Use ref for hyperlinks, 1st batch

---

doc/mgr/administrator.rst

Edit doc/mgr/administrator.rst. Add prompts and correct some of the inelegant English present in the file.
(cherry picked from commit 859950180f0b7314b097ee9b2f9f192f4cfb3ed4) …

tentacle: doc/mgr: edit administrator.rst

---

doc/mgr/administrator.rst

Edit doc/mgr/administrator.rst. Add prompts and correct some of the inelegant English present in the file.
(cherry picked from commit 859950180f0b7314b097ee9b2f9f192f4cfb3ed4) …

squid: doc/mgr: edit administrator.rst

---

doc/mgr/administrator.rst

Edit doc/mgr/administrator.rst. Add prompts and correct some of the inelegant English present in the file.
(cherry picked from commit 859950180f0b7314b097ee9b2f9f192f4cfb3ed4) …

reef: doc/mgr: edit administrator.rst

---

doc/mgr/alerts.rst

Edit doc/mgr/alerts.rst as part of the project to determine where the error is in https://github.com/ceph/ceph/pull/62782 that prevents the Jenkins tests from passing.
This commit adds to the work done in
https://github.com/ceph/ceph/pull/62782 by correcting some of the English that was present in that PR.
(cherry picked from commit db28c1f32ff67bd1087866c7976233e8ab23fa2c) …

tentacle: doc/mgr: edit alerts.rst

---

doc/mgr/alerts.rst

Edit doc/mgr/alerts.rst as part of the project to determine where the error is in https://github.com/ceph/ceph/pull/62782 that prevents the Jenkins tests from passing.
This commit adds to the work done in
https://github.com/ceph/ceph/pull/62782 by correcting some of the English that was present in that PR.
(cherry picked from commit db28c1f32ff67bd1087866c7976233e8ab23fa2c) …

squid: doc/mgr: edit alerts.rst

---

doc/mgr/alerts.rst

Edit doc/mgr/alerts.rst as part of the project to determine where the error is in https://github.com/ceph/ceph/pull/62782 that prevents the Jenkins tests from passing.
This commit adds to the work done in
https://github.com/ceph/ceph/pull/62782 by correcting some of the English that was present in that PR.
(cherry picked from commit db28c1f32ff67bd1087866c7976233e8ab23fa2c) …

reef: doc/mgr: edit alerts.rst

---

doc/mgr/ceph_api/index.rst

Edit doc/mgr/ceph_api/index.rst as part of the project to determine where the error is in https://github.com/ceph/ceph/pull/62782 that prevents the Jenkins tests from passing.
(cherry picked from commit 5c17f2242318d57e9faaafc83774a8f8a36f6e0e) …

squid: doc/mgr/ceph_api: edit index.rst

---

doc/mgr/ceph_api/index.rst

Edit doc/mgr/ceph_api/index.rst as part of the project to determine where the error is in https://github.com/ceph/ceph/pull/62782 that prevents the Jenkins tests from passing.
(cherry picked from commit 5c17f2242318d57e9faaafc83774a8f8a36f6e0e) …

reef: doc/mgr/ceph_api: edit index.rst

---

.github/workflows/retrigger-rtd.yml

.github: Fix RTD build retrigger

---

src/crimson/os/seastore/cache.h
src/crimson/os/seastore/seastore_types.h

Don't update num_extents when a partial extent is already in LRU.
Fixes: https://tracker.ceph.com/issues/69986
- …

crimson/os/seastore/cache/LRU: account the empty extent when adding it to LRU

---

src/osd/osd_types.h

backport tracker: https://tracker.ceph.com/issues/71223
---
backport of https://github.com/ceph/ceph/pull/62705
parent tracker: https://tracker.ceph.com/issues/45702

tentacle: osd_types: Restore new_object marking for delete missing entries

---

src/tools/ceph_dedup/ceph_dedup_daemon.cc
src/tools/ceph_dedup/ceph_dedup_tool.cc
src/tools/ceph_dedup/common.cc
src/tools/ceph_dedup/common.h

Remove 'using namespace std' from common.h to maintain consistent coding practices. Although common.h is only used by ceph_dedup implementation, keeping namespace declarations out of header files prevents potential name conflicts and follows best practices for C++ code organization.
This change improves code clarity and reduces the risk of symbol collisions when standard library elements are used alongside custom implementations. …

tools/ceph_dedup: remove 'using namespace std'

---

qa/suites/fs/volumes/tasks/volumes/test/snapshot.yaml
qa/tasks/cephfs/test_volumes.py

Fixes: https://tracker.ceph.com/issues/70834 …

mgr/vol: make "snapshot getpath" cmd work with v1 and legacy

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-sync-data-info/rgw-sync-data-info.component.scss

Fixes:https://tracker.ceph.com/issues/71248
Signed-off-by: Prachi <prgoel@redhat.com>
Changes:
Fixes for RGW multi-site-sync-status UI distortion in data sync …

mgr/dashboard: Multi-site-sync-status UI distortion for status in data sync

---

doc/radosgw/vault.rst

Use generated "contents" instead of repeating section titles in an ordered list.
Use Title Case for section titles.
Capitalize consistently "Ceph" and "Object Gateway", "Vault".
Use consistently all caps for acronyms.
Change one entry of "kms" to "SSE-KMS", seems obvious from the context. Use "certificates" instead of "certs".
Use double backticks for file paths, commands, config options etc.
Improve language in one sentence, several words missing.
Call it consistently "the Object Gateway" and not sometimes "the Gateway".
Add pre-formatted block for CLI command examples where missing (should be promptified in the future).
- Before: https://docs.ceph.com/en/latest/radosgw/vault/
- Rendered PR: https://ceph--63209.org.readthedocs.build/en/63209/radosgw/vault/ …

doc/radosgw: Cosmetic and formatting improvements in vault.rst

---

doc/radosgw/vault.rst

Use generated "contents" instead of repeating section titles in an ordered list.
Use Title Case for section titles.
Capitalize consistently "Ceph" and "Object Gateway", "Vault".
Use consistently all caps for acronyms.
Change one entry of "kms" to "SSE-KMS", seems obvious from the context. Use "certificates" instead of "certs".
Use double backticks for file paths, commands, config options etc.
Improve language in one sentence, several words missing.
Call it consistently "the Object Gateway" and not sometimes "the Gateway".
Add pre-formatted block for CLI command examples where missing (should be promptified in the future).
(cherry picked from commit aa2e91ff70ea37a56f4013e6087f7e790f527329) …

tentacle: doc/radosgw: Cosmetic and formatting improvements in vault.rst

---

doc/radosgw/vault.rst

Use generated "contents" instead of repeating section titles in an ordered list.
Use Title Case for section titles.
Capitalize consistently "Ceph" and "Object Gateway", "Vault".
Use consistently all caps for acronyms.
Change one entry of "kms" to "SSE-KMS", seems obvious from the context. Use "certificates" instead of "certs".
Use double backticks for file paths, commands, config options etc.
Improve language in one sentence, several words missing.
Call it consistently "the Object Gateway" and not sometimes "the Gateway".
Add pre-formatted block for CLI command examples where missing (should be promptified in the future).
(cherry picked from commit aa2e91ff70ea37a56f4013e6087f7e790f527329) …

squid: doc/radosgw: Cosmetic and formatting improvements in vault.rst

---

src/cls/rbd/cls_rbd.cc

backport tracker: https://tracker.ceph.com/issues/71241
---
backport of https://github.com/ceph/ceph/pull/63050
parent tracker: https://tracker.ceph.com/issues/71138

tentacle: cls/rbd: write image mirror status if state is CREATING

---

qa/config/crimson_qa_overrides.yaml
src/common/options/crimson.yaml.in

crimson: bump defaults to be more appropriate

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-list/nvmeof-listeners-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/nvmeof.ts

- pass gw_group to delete API in frontend
- when more than one gw groups present delete listener failing with error message: Multiple NVMe-oF gateway groups are configured. Please specify the 'gw_group' parameter in the request.
- added missing types, i18n
Fixes https://tracker.ceph.com/issues/71236 …

mgr/dashboard: Fix delete listener

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-gateway/nvmeof-gateway.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-gateway/nvmeof-gateway.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-gateway/nvmeof-gateway.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-subsystems/nvmeof-subsystems.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts

Fixes https://tracker.ceph.com/issues/71247
- after upgrades the nvmeof service spec does not contain `group` field
- this causes UI combobox internal errors
- checking for `group` in spec and disabling the selector
https://github.com/user-attachments/assets/3fb460d0-7729-403c-89bb-a0e11dba24a7 …

mgr/dashboard: Add default state when gateway groups are empty

---

doc/dev/cephfs-mirroring.rst

doc: fix formatting in cephfs_mirror dev doc

---

doc/rados/operations/pools.rst
qa/standalone/scrub/osd-scrub-test.sh
src/osd/scrubber/osd_scrub_sched.cc
src/osd/scrubber/pg_scrubber.cc
src/osd/scrubber/scrub_job.cc
src/osd/scrubber/scrub_job.h
src/osd/scrubber/scrub_queue_entry.h
src/osd/scrubber_common.h

The scrub scheduling deadlines are calculated based on pool and OSD configuration parameters. The specifics of the calculations are modified to match the new scrub scheduling design.
Comments and documentation are updated to reflect the fact that the deadlines no longer have any meaningful effect on scrub scheduling.

osd/scrub: fix deadline calculations

---

doc/radosgw/admin.rst
doc/radosgw/cloud-sync-module.rst
doc/radosgw/metrics.rst
doc/radosgw/multisite-sync-policy.rst
doc/radosgw/multisite.rst

Use inline code formatting consistently for command line switches, data, hostnames, etc.
Correctly indent text and child lists in list items. Remove a mid-sentence double spaces.
Capitalize "RGW" and "API" in text.
Remove unordered lists that are just regular text
everywhere else.
Use correct prompt # instead of $ for privileged
commands.
Use line continuation for multi-line example commands instead of render them incorrectly as separate
single-line commands.
Use Title Case in few section header text that
missed it.
multisite.rst: Don't repeat "(RGW)" after "RADOS
Gateway" beyond the first instance in the same
paragraph.
multisite.rst: Change one "multisite" to "multi-site" because all other instances use this spelling (EXCEPT the title of the document??).
multisite.rst: Fix indentation …

reef: doc/radosgw: Improve and more consistent formatting

---

qa/tasks/mgr/dashboard/test_cephfs.py

Skipping this in all PRs except the dashboard
Fixes: https://tracker.ceph.com/issues/70791 …

qa/tests: skipping test_cephfs_clients_get_after_mds_down in test_cephfs

---

src/client/Client.cc
src/test/libcephfs/suidsgid.cc

An unprivileged user can `chmod 777` a directory owned by root and gain access. Fix this bug and also add a test case for the same. …

client: disallow unprivileged users to escalate root privileges

---

src/osd/scrubber/osd_scrub.cc
src/osd/scrubber/osd_scrub.h

Modified OsdScrub::restrictions_on_scrubbing() to check all(*) conditions, instead of stopping at the first one that is true. The "new" (since Tentacle) scrub-type-to-conditions mapping is no longer a simple one (is not "monotonic" in the sense of restrictions always being removed as the scrub type is more important), and the caller may want to know them all.
(*) The somewhat costly check for the random backoff is still only
performed if the OSD is not already running too many scrubs.
A backport of https://github.com/ceph/ceph/pull/63093
Original tracker: https://tracker.ceph.com/issues/71169
Backport tracker: https://tracker.ceph.com/issues/71185
(cherry picked from commit 5a3a4f73476580b44442a30c8404a62b5055c96d)

tentacle: osd/scrub: check all(*) conditions in restrictions_on_scrubbing()

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-list/nvmeof-listeners-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/nvmeof.ts

backport tracker: https://tracker.ceph.com/issues/71289
---
backport of https://github.com/ceph/ceph/pull/63165
parent tracker: https://tracker.ceph.com/issues/71236

tentacle: mgr/dashboard: Fix delete listener

---

src/crimson/osd/osd_operations/client_request.cc
src/crimson/osd/pg.cc

Before this patch, we would first send the MOSDPGUpdateLogMissing to
all peers and only then insert this rep_tid to log_entry_update_waiting_on.
This could have resulted in race where we receive the reply prior to
actually inserting the rep_tid.
The reply would have been discarded with "reply on unknown tid" (which
is now aborting).
The un-handled reply would have not let submit_error to return and would
keep holding the lock on this obc.
Debugging: https://tracker.ceph.com/issues/71204#note-2
Fixes: https://tracker.ceph.com/issues/71204
Fixes: https://tracker.ceph.com/issues/69460 …

crimson/osd/pg: set log_entry_update_waiting_on prior to sending requests

---

doc/mgr/dashboard.rst

doc/mgr/dashboard: s/promt/prompt/ in dashboard.rst.

---

doc/cephfs/fs-volumes.rst
doc/cephfs/troubleshooting.rst

Correct the links to cross-references in the cases of the following two directives:
1. pause-clone-threads
2. pause-purge-threads
(cherry picked from commit e59364f152847eabbedfe7fc72dfb66e7378b72b) …

doc/cephfs: correct reference structure in fs-volumes.rst

---

doc/monitoring/index.rst

Correct list formatting in doc/monitoring/index.rst.
- …

doc/monitoring: correct list formatting

---

doc/dev/cephfs-mirroring.rst

(cherry picked from commit 8280d334b9b3ee98cb1372d91991fa476a89424b)
- Component …

tentacle: doc: fix formatting in cephfs_mirror dev doc

---

doc/dev/cephfs-mirroring.rst

(cherry picked from commit 8280d334b9b3ee98cb1372d91991fa476a89424b)
- Component …

squid: doc: fix formatting in cephfs_mirror dev doc

---

doc/dev/cephfs-mirroring.rst

(cherry picked from commit 8280d334b9b3ee98cb1372d91991fa476a89424b)
- Component …

reef: doc: fix formatting in cephfs_mirror dev doc

---

src/script/clean-ci

Addresses failures like:
Deleting refs: refs/heads/main refs/heads/wip-athakkar-testing-2025-02-11-1344 refs/heads/wip-choffman-fscrypt-021225 refs/heads/wip-dang-68336 refs/heads/wip-leonidc-7_1_hotfix refs/heads/wip-nia-testing-2025-02-12-0101 refs/heads/wip-nitzan-gil-perf-count-and-contention-detect refs/heads/wip-rf-perf-sections refs/heads/wip-sseshasa-test-stuck-backfill-squid-feb11-2024 refs/heads/wip-sseshasa-test-stuck-backfill-squid-feb12-2024 refs/heads/wip-yuri8-testing-2025-02-10-2350
To https://github.com/ceph/ceph-ci
- [deleted]           wip-athakkar-testing-2025-02-11-1344
- [deleted]           wip-choffman-fscrypt-021225
- [deleted]           wip-dang-68336
- [deleted]           wip-leonidc-7_1_hotfix
- [deleted]           wip-nia-testing-2025-02-12-0101
- [deleted] …

script: ignore main branch when cleaning ci

---

.github/workflows/retrigger-rtd.yml

tentacle: .github: Fix RTD build retrigger

---

doc/rados/operations/pools.rst
qa/standalone/scrub/osd-scrub-test.sh
src/osd/scrubber/osd_scrub_sched.cc
src/osd/scrubber/pg_scrubber.cc
src/osd/scrubber/scrub_job.cc
src/osd/scrubber/scrub_job.h
src/osd/scrubber/scrub_queue_entry.h
src/osd/scrubber_common.h

The scrub scheduling deadlines are calculated based on pool and OSD configuration parameters. The specifics of the calculations are modified to match the new scrub scheduling design.
Comments and documentation are updated to reflect the fact that the deadlines no longer have any meaningful effect on scrub scheduling.
Fixes: https://tracker.ceph.com/issues/71295
Backport of https://github.com/ceph/ceph/pull/63183

tentacle: osd/scrub: remove (was: fix) deadline calculations

---

src/os/bluestore/BlueStore.cc
src/os/bluestore/Compression.cc
src/os/bluestore/Compression.h

When data is very very compressible (95%+ , like all zeros) recompression scanner gets confused and
wants to get large already compressed blobs for recompression.
This is because it really seems to make sens - the compressed size is so small it all should fit together with next extents together on single allocation unit.
However - due to our blob split policy we need to cut it much earlier.
This is fixed now - large compressed blobs are penalized and effectively excluded.
Fixes: https://tracker.ceph.com/issues/71244 …

[tentacle] os/bluestore: Do not recompress large compressed blobs

---

qa/suites/crimson-rados/thrash/thrashers/default.yaml
qa/suites/crimson-rados/thrash_simple/thrashers/simple.yaml

Avoid "no valid command" in teuthology logs.
trim stale osdmaps is not planned to be introduced soon: See: https://tracker.ceph.com/issues/65288 …

qa/suites/crimson-rados: disable chance_trim_stale_osdmaps

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.ts

Previously, there was only a text input field for size. The updated design now includes both a text input for the size value and a unit selector.
Fixes: https://tracker.ceph.com/issues/66995
Signed-off-by: Ankit Kumar <51ankitkp@gmail.com>
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job …

mgr/dashboard:Added a dropdown menu for all size inputs.

---

doc/radosgw/dynamicresharding.rst

Make reference to config section a hyperlink.
Capitalization consistency: use title case in section titles, fix two invalid capitalizations in text.
Promptify CLI example commands.
A JSON key-value pair is a "property" and not an "object".
Use an ordered list instead of inline code with hardcoded list numbers.
Use the American "canceled" (majority of occurrences in doc/) instead of "cancelled".
Use admonitions instead of spelling out "Note:".
Clarify language on sharding cleanup for multisite.
Format JSON keys as inline code.
Indent example JSON output from radosgw-admin correctly (same as real
output) with 4 spaces.
Use colon instead of full stop at the end of text that describes the
following example command. Move admonition to after such example
command.
- Before: …

doc/radosgw: Cosmetic improvements in dynamicresharding.rst

---

doc/dev/cephfs-mirroring.rst

This commit edits the first quarter of the doc/dev/cephfs-mirroring.rst file. This commit encompasses about one-hundred lines of RST. …

doc/dev/cephfs-mirroring: edit file 1 of x

---

src/crimson/common/interruptible_future.h
src/crimson/osd/backfill_state.cc
src/crimson/osd/osd_operations/background_recovery.cc
src/crimson/osd/osd_operations/background_recovery.h
src/crimson/osd/pg.cc
src/crimson/osd/pg.h
src/crimson/osd/pg_recovery.cc
src/crimson/osd/pg_recovery.h
src/crimson/osd/pg_recovery_listener.h

backport of: https://github.com/ceph/ceph/pull/62847
backport of: https://github.com/ceph/ceph/pull/63215 (avoid regression in pr above)  …

tentacle: crimson/osd/pg_recovery: rework start_recovery_ops

---

qa/config/crimson_qa_overrides.yaml
src/common/options/crimson.yaml.in

tentacle: crimson: bump defaults to be more appropriate

---

qa/suites/rados/mgr/tasks/3-mgrmodules.yaml
src/mgr/MgrStandby.cc
src/mgr/MgrStandby.h

backport tracker: https://tracker.ceph.com/issues/70666
---
backport of https://github.com/ceph/ceph/pull/62465
parent tracker: https://tracker.ceph.com/issues/70571

reef: mgr: add status command

---

src/mon/Elector.cc
src/mon/Elector.h
src/mon/Monitor.cc

backport tracker: https://tracker.ceph.com/issues/71029
---
backport of https://github.com/ceph/ceph/pull/62416
parent tracker: https://tracker.ceph.com/issues/70587

reef: mon: Track and process pending pings after election

---

qa/suites/orch/cephadm/osds/1-start.yaml
qa/suites/orch/cephadm/smoke/start.yaml

backport tracker: https://tracker.ceph.com/issues/70998
---
backport of https://github.com/ceph/ceph/pull/62652
parent tracker: https://tracker.ceph.com/issues/70466

reef: qa/suites/orch/cephadm: add PG_DEGRADED to ignorelist

---

doc/mgr/dashboard.rst

Edit doc/mgr/crash.rst. Add prompts.
This changes eighty-nine prompts. Because this makes so many changes, all other edits included in https://github.com/ceph/ceph/pull/63255 will be made in a separate commit. This done for the sake of the patience of the reviewers (probably Anthony, if history is any guide). …

doc/mgr: edit dashboard.rst

---

doc/dev/cephfs-mirroring.rst

This commit edits the first quarter of the doc/dev/cephfs-mirroring.rst file. This commit encompasses about one-hundred lines of RST.
(cherry picked from commit e9a27051a7c0f4884e685a4105e45273aef0abe0) …

squid: doc/dev/cephfs-mirroring: edit file 1 of x

---

doc/dev/cephfs-mirroring.rst

This commit edits the first quarter of the doc/dev/cephfs-mirroring.rst file. This commit encompasses about one-hundred lines of RST.
(cherry picked from commit e9a27051a7c0f4884e685a4105e45273aef0abe0) …

tentacle: doc/dev/cephfs-mirroring: edit file 1 of x

---

monitoring/ceph-mixin/dashboards_out/ceph-application-overview.json

There is a test collision in "promql-query-test" test suite because two different IOPS panels with the same title and legend labels (Read, Write) are present, and the test framework is not able to distinguish between them. There are two panels with the same title IOPS and legends Read / Write, but different expressions:\
1. ceph-application-overview.json
2. ceph-cluster-advanced.json
https://github.com/ceph/ceph/pull/63266#issuecomment-2879214898
Fixes: https://tracker.ceph.com/issues/71318 …

mgr/dashboard: fix flaky promql query test

---

doc/radosgw/multisite.rst
doc/radosgw/placement.rst
doc/radosgw/pools.rst
doc/radosgw/s3/commons.rst

- Update to use existing label in multisite.rst.
Also use existing label for linking from `multisite.rst`.  
Fix a broken link within `multisite.rst`. *This changes the rendered text to use automatic link text from the section title*.
Otherwise the rendered PR should look the same as the old docs, only differing in the source RST.
- Before/after (no change in rendered PR): https://docs.ceph.com/en/latest/radosgw/multisite/#requirements-and-assumptions https://ceph--63293.org.readthedocs.build/en/63293/radosgw/multisite/#requirements-and-assumptions
- Before/after (link works now, use automatic link text from section title), scroll …

doc/radosgw: Use ref for hyperlinking to multisite

---

doc/mgr/dashboard.rst

Edit doc/mgr/crash.rst. Add prompts.
This changes eighty-nine prompts. Because this makes so many changes, all other edits included in https://github.com/ceph/ceph/pull/63255 will be made in a separate commit. This done for the sake of the patience of the reviewers (probably Anthony, if history is any guide).
(cherry picked from commit 1f587883a671775b44b656cf6b7c641d02319b5f) …

tentacle: doc/mgr: edit dashboard.rst

---

doc/mgr/dashboard.rst

Edit doc/mgr/crash.rst. Add prompts.
This changes eighty-nine prompts. Because this makes so many changes, all other edits included in https://github.com/ceph/ceph/pull/63255 will be made in a separate commit. This done for the sake of the patience of the reviewers (probably Anthony, if history is any guide).
(cherry picked from commit 1f587883a671775b44b656cf6b7c641d02319b5f) …

squid: doc/mgr: edit dashboard.rst

---

doc/mgr/dashboard.rst

Edit doc/mgr/dashboard.rst. Add prompts.
This changes eighty-nine prompts. Because this makes so many changes, all other edits included in https://github.com/ceph/ceph/pull/63255 will be made in a separate commit. This done for the sake of the patience of the reviewers (probably Anthony, if history is any guide).
(cherry picked from commit 1f587883a671775b44b656cf6b7c641d02319b5f) …

reef: doc/mgr: edit dashboard.rst

---

src/pybind/mgr/tox.ini

backport of https://github.com/ceph/ceph/pull/59845
For some reason mypy on python 3.12 can no longer automatically find imports from python-common. Help it out by expanding the MYPYPATH value for the tox.ini.
(cherry picked from commit d1c942a98499560bb15c50db4498f12f4916866f)

reef: pybind/mgr: attempt to fix mypy importing from python-common

---

doc/cephfs/mount-using-kernel-driver.rst

The example command for mounting CephFS was missing the local mount path. Updated the command to include "/mnt/mycephfs".

doc/cephfs: specify mount path in example command

---

doc/radosgw/s3/bucketops.rst
src/common/options/rgw.yaml.in
src/rgw/rgw_common.cc
src/rgw/rgw_op.cc
src/rgw/rgw_rest_s3.cc

S3: conditionally override 200, OK result for same-owner CreateBucket requests
Fixes: https://tracker.ceph.com/issues/70369 …

rgw: introduce rgw_bucket_eexist_override

---

doc/radosgw/cloud-transition.rst

Indent the second paragraph of a list item at the same level as the previous paragraph. The unexpected indentation resulted in an ERROR from Sphinx but it was still rendered with increased indentation looking rather out of place.
Capitalize the first letter similarly to the previous paragraph.
This was detected as ERROR in the Sphinx CI job output. Last such ERROR, several WARNINGs remain.
```console
/home/docs/checkouts/readthedocs.org/user_builds/ceph/checkouts/63294/doc/radosgw/cloud-transition.rst:356: ERROR: Unexpected indentation.
```
- Before: https://docs.ceph.com/en/latest/radosgw/cloud-transition/#object-modification-and-limitations
- Rendered PR: https://ceph--63321.org.readthedocs.build/en/63321/radosgw/cloud-transition/#object-modification-and-limitations
- To sign and title …

doc/radosgw: Fix indentation in cloud-transition.rst

---

doc/rados/operations/health-checks.rst

Fix missing empty line before an unordered list that caused it to be rendered wrong.
Also, the sentences in each list item start with a capital case letter so add the missing full stop at the end.  
Feedback on this would be great, I'm not 100% sure this is a good idea or that they are complete sentences.
This was detected as ERROR in the Sphinx CI job output. More such fix PRs incoming soon.
```console
/home/docs/checkouts/readthedocs.org/user_builds/ceph/checkouts/63294/doc/rados/operations/health-checks.rst:168: ERROR: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/ceph/checkouts/63294/doc/rados/operations/health-checks.rst:169: WARNING: Block quote ends without a blank line; unexpected unindent.
```
- Before: …

doc/rados/operations: Fix unordered list in health-checks.rst

---

doc/rados/operations/crush-map-edits.rst

Fix attempted use of underscores for inline emphasis which resulted in the text being emphasized to be considered a link. The text was rendered partially as a link to an invalid anchor "#id3".
Instead use inline italic for formatting emphasis.
This was detected as ERROR in the Sphinx CI job output. More such fix PRs incoming soon.
```console
/home/docs/checkouts/readthedocs.org/user_builds/ceph/checkouts/63294/doc/rados/operations/crush-map-edits.rst:255: ERROR: Unknown target name: "domain".
```
- Before: https://docs.ceph.com/en/latest/rados/operations/crush-map-edits/#crush-map-bucket-hierarchy
- Rendered PR: https://ceph--63318.org.readthedocs.build/en/63318/rados/operations/crush-map-edits/#crush-map-bucket-hierarchy
- Scroll down to the paragraph after the admonition.
- To sign and …

doc/rados/operations: Fix invalid hyperlink in crush-map-edits.rst

---

doc/radosgw/multisite.rst
doc/radosgw/placement.rst
doc/radosgw/pools.rst
doc/radosgw/s3/commons.rst

- Update to use existing label in multisite.rst.
Also use existing label for linking from multisite.rst. Fix a broken link within multisite.rst.
The rendered PR should look the same as the old docs, only differing in the source RST.
(cherry picked from commit e296c756ca191753080cb65e3df4bf3bb160398b) …

reef: doc/radosgw: Use ref for hyperlinking to multisite

---

doc/radosgw/multisite.rst
doc/radosgw/placement.rst
doc/radosgw/pools.rst
doc/radosgw/s3/commons.rst

- Update to use existing label in multisite.rst.
Also use existing label for linking from multisite.rst. Fix a broken link within multisite.rst.
The rendered PR should look the same as the old docs, only differing in the source RST.
(cherry picked from commit e296c756ca191753080cb65e3df4bf3bb160398b) …

squid: doc/radosgw: Use ref for hyperlinking to multisite

---

doc/radosgw/multisite.rst
doc/radosgw/placement.rst
doc/radosgw/pools.rst
doc/radosgw/s3/commons.rst

- Update to use existing label in multisite.rst.
Also use existing label for linking from multisite.rst. Fix a broken link within multisite.rst.
The rendered PR should look the same as the old docs, only differing in the source RST.
(cherry picked from commit e296c756ca191753080cb65e3df4bf3bb160398b) …

tentacle: doc/radosgw: Use ref for hyperlinking to multisite

---

qa/suites/crimson-rados/thrash/thrashers/default.yaml
qa/suites/crimson-rados/thrash_simple/thrashers/simple.yaml

backport of: #63226
Avoid "no valid command" in teuthology logs.
trim stale osdmaps is not planned to be introduce soon: See: https://tracker.ceph.com/issues/65288
(cherry picked from commit aa3ff63b6fa9c51e540d1768a2dbb8c267b9d2c4) …

tentacle: qa/suites/crimson-rados: disable chance_trim_stale_osdmaps

---

src/crimson/os/seastore/cache.h
src/crimson/os/seastore/seastore_types.h

backport tracker: https://tracker.ceph.com/issues/71273
---
backport of https://github.com/ceph/ceph/pull/62969
parent tracker: https://tracker.ceph.com/issues/69986

tentacle: crimson/os/seastore/cache/LRU: account the empty extent when adding it to LRU

---

src/common/assert.cc

Previously, in __ceph_abort and related abort handlers, we allocated ClibBackTrace instances using raw pointers without proper cleanup. Since these handlers terminate execution, the leaks didn't affect production systems but were correctly flagged by ASan during testing:
```
Direct leak of 288 byte(s) in 1 object(s) allocated from:
#0 0x55aefe8cb65d in operator new(unsigned long) (/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/unittest_ceph_assert+0x1f465d) (BuildId: a4faeddac80b0d81062bd53ede3388c0c10680bc)
#1 0x7f3b84da988d in ceph::__ceph_assertf_fail(char const*, char const*, int, char const*, char const*, ...) /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/assert.cc:157:21
#2 0x55aefe8cf04b in supressed_assertf_line22() …
```

common: fix backtrace leak in __ceph_abort and friends

---

doc/man/8/ceph-bluestore-tool.rst

A space is missing between a token with emphasis and the following token:
- Not consistent with other commands like "show-label" (has space).
- Inline formatting is rendered verbatim in the second occurrence, without the formatting being applied.
- Warning from Sphinx.
Fixes a WARNING from Sphinx:
```console
/home/docs/checkouts/readthedocs.org/user_builds/ceph/checkouts/63294/doc/man/8/ceph-bluestore-tool.rst:119: WARNING: Inline emphasis start-string without end-string.
```
- Search `lba` with browser.
- Before: https://docs.ceph.com/en/latest/man/8/ceph-bluestore-tool/
- Rendered PR: https://ceph--63330.org.readthedocs.build/en/63330/man/8/ceph-bluestore-tool/ …

doc/man: Fix inline formatting in ceph-bluestore-tool.rst

---

doc/architecture.rst
doc/start/hardware-recommendations.rst

- Update to use existing labels when linkin from architecture.rst.
Also use title case for section titles in `doc/start/hardware-recommendations.rst` because change to use link text generated from section title.
Other than generated link texts the rendered PR should look the same as the old docs, only differing in the source RST.
Fixes a duplicate target definition.  
Only links with destinations that already have existing labels were updated to `:ref:`.
- Before/after (no change in rendered PR): https://docs.ceph.com/en/latest/architecture/#high-availability-monitors https://ceph--63294.org.readthedocs.build/en/63294/architecture/#hi …

doc: Use existing labels and ref for hyperlinks in architecture.rst

---

src/tools/ceph_dedup/ceph_dedup_daemon.cc
src/tools/ceph_dedup/ceph_dedup_tool.cc

-  Replace iterator loops with range-based loops 
- Add const qualifiers and reference parameters …

tools/ceph_dedup: improve const-ness and use ranged-for loop when appropriate 

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.ts

fixes: https://tracker.ceph.com/issues/71341
Before:
===
Used_id was not accepting (.) in it
Tenant was accepting other characters other than alphanumeric or '_'
After:
===
User_id is accepting (.)
Tenant is accepting only alphanumberic or '_' …

mgr/dashboard: accept dot(.) in user_id & restrict tenant validation in user form

---

src/blk/BlockDevice.cc
src/blk/BlockDevice.h
src/blk/kernel/KernelDevice.cc
src/blk/kernel/KernelDevice.h
src/common/options/global.yaml.in
src/include/interval_set.h
src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/os/bluestore/BlueStore.cc

1. blk/kernel: bring "bdev_async_discard" config parameter back.
2. blk/kerneldevice: add perfcounter for block async discard.
3. blk/kerneldevice: count ops not bytes in discard_op perf counter.
4. blk/kerneldevice: fix invalid iterator usage after erase in discard_queued traversal.
5.  blk/kernel: New perf counter to view amount of discard threads
---
backport of https://github.com/ceph/ceph/pull/62254, https://github.com/ceph/ceph/pull/58952, https://github.com/ceph/ceph/pull/62150, https://github.com/ceph/ceph/pull/62471, https://github.com/ceph/ceph/pull/62251
parent tracker: https://tracker.ceph.com/issues/70335, https://tracker.ceph.com/issues/70636
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches …

reef: blk/kerneldevice: some fix for device discard

---

doc/cephfs/troubleshooting.rst
doc/dev/cephfs-mirroring.rst

Fix four warnings from Sphinx about missing blank line after explicit markup.
Indent content in list items correctly, fixing formatting errors.
(cherry picked from commit 5e1b3cd566fd700b36001551d1c7e092fc850def) …

reef: doc: Fix missing blank line Sphinx warnings

---

doc/cephfs/troubleshooting.rst
doc/dev/cephfs-mirroring.rst

Fix four warnings from Sphinx about missing blank line after explicit markup.
Indent content in list items correctly, fixing formatting errors.
(cherry picked from commit 5e1b3cd566fd700b36001551d1c7e092fc850def) …

squid: doc: Fix missing blank line Sphinx warnings

---

doc/cephfs/troubleshooting.rst
doc/dev/cephfs-mirroring.rst

Fix four warnings from Sphinx about missing blank line after explicit markup.
Indent content in list items correctly, fixing formatting errors.
(cherry picked from commit 5e1b3cd566fd700b36001551d1c7e092fc850def) …

tentacle: doc: Fix missing blank line Sphinx warnings

---

src/rgw/services/svc_zone.cc
src/rgw/services/svc_zone.h

SiteConfig had already loaded the correct configuration without all of the crazy search_realm_with_zone() stuff which is now confused by defaults. remove all of this duplicated logic and rely on SiteConfig
removes functions search_realm_with_zone() create_default_zg() and init_default_zone() which are no longer used
Fixes: https://tracker.ceph.com/issues/71291
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job …

rgw/zone: remove duplicated startup logic in RGWSI_Zone

---

src/mon/OSDMonitor.cc

If mon_memory_target is set in the config database and mon_memory_autotune is left at default the mon_memory_target change can be lost. Check whether mon_memory_target is currently true and initialise pcm if it is.
Fixes: https://tracker.ceph.com/issues/70645 …

OSDMonitor: Make sure pcm is initialised

---

src/rgw/rgw_rest.h
src/rgw/rgw_rest_s3.cc

Instead of relying only on SERVER_PORT_SECURE.
This is useful when a proxy is used in front of the rgw for ssl terminations.
Fixes: https://tracker.ceph.com/issues/71229 …

rgw/rgw_rest: determine the domain uri prefix by rgw_transport_is_secure

---

qa/workunits/libcephfs/test.sh
src/client/Client.cc
src/client/Client.h
src/include/cephfs/libcephfs.h
src/libcephfs.cc
src/test/libcephfs/CMakeLists.txt
src/test/libcephfs/perfcounters.cc

This refactor is done so as to be able to fetch the perf counters
via client APIs (say, libcephfs). The current mechanism of exporting
perf counters is via formatters (JSON, etc..) makes it a little
weird to expose the perf counters via a library API. This change
adds a mechanism to get perf counters by type packed in a struct. …

Wip libcephfs perf dump

---

src/mds/SessionMap.cc

Fixes: https://tracker.ceph.com/issues/70770 …

cephfs: session tracker accounts for killing sessions

---

src/crimson/common/fixed_kv_node_layout.h
src/crimson/os/seastore/backref/backref_tree_node.h
src/crimson/os/seastore/btree/fixed_kv_btree.h
src/crimson/os/seastore/btree/fixed_kv_node.h
src/crimson/os/seastore/lba_manager/btree/lba_btree_node.h
src/crimson/os/seastore/linked_tree_node.h
src/crimson/os/seastore/omap_manager.h
src/crimson/os/seastore/omap_manager/btree/omap_btree_node.h
src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.cc
src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.h
src/crimson/os/seastore/omap_manager/btree/string_kv_node_layout.h
src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/seastore.h
src/test/crimson/test_fixed_kv_node_layout.cc

crimson/os/seastore/linked_tree_node: correct balance pivots calculation for both fixed-kv tree and omap tree

---

src/osd/scheduler/OpSchedulerItem.cc

backport tracker: https://tracker.ceph.com/issues/70903
---
backport of https://github.com/ceph/ceph/pull/62704
parent tracker: https://tracker.ceph.com/issues/70811

reef: osd/scheduler/OpSchedulerItem: Fix calculation of recovery latency counters

---

src/rgw/rgw_cksum.cc

clang complains that `cck3` might not be initialized:
```
/home/jenkins-build/build/workspace/ceph-api/src/rgw/rgw_cksum.cc:74:2: error: variable 'cck3' is used uninitialized whenever switch default is taken [-Werror,-Wsometimes-uninitialized]
74 |         default:
|         ^~~~~~~
/home/jenkins-build/build/workspace/ceph-api/src/rgw/rgw_cksum.cc:78:31: note: uninitialized use occurs here
78 |         cck3 = rgw::digest::byteswap(cck3);
|                                      ^~~~
/home/jenkins-build/build/workspace/ceph-api/src/rgw/rgw_cksum.cc:61:15: note: initialize the variable 'cck3' to silence this warning
61 |         uint32_t cck3;
|                      ^
|                       = 0
```
The `default:` case however is not reachable because `ck1.type` has already been checked. …

rgw/rgw_cksum: work around -Wsometimes-uninitialized

---

PendingReleaseNotes
doc/rados/operations/monitoring.rst

This PR adds release notes and docs for how to use the availability score
feature. It also details when we consider a pool available
and when not and how we calculate the availability score.
Fixes: https://tracker.ceph.com/issues/67777
Related PR: https://github.com/ceph/ceph/pull/59673 
<details> …

docs: add release notes and docs for availability score feature 

---

doc/mgr/hello.rst

Edit doc/mgr/hello.rst. This includes the rewriting of sentences so that they now appear in grammatically-correct English. …

doc/mgr: edit hello.rst

---

debian/cephadm.postinst
doc/cephadm/install.rst

This patch removes the assumption that user home directories always live under /home. If the user has set home directories to live under a different directory by changing /etc/adduser.conf, this will honor that setting.
Signed-off-by: Shawn Edwards <shedwards@nvidia.com>

[Packaging]: Use system-defined location for home directories

---

src/pybind/mgr/dashboard/frontend/CMakeLists.txt

When testing ceph builds in a container we discovered that certain files could not be deleted by jenkins after a build. This was due to the way the container maps IDs - files owned by the root user in the container become owned by the "real" user/jenkins user on the "host". However, the node tarball that is fetched and unpacked by nodeenv has a different owner name/uid that is preserved in the tree and this id gets mapped to something that can be managed by the "fake root" of the container but not by the "regular" user outside the container.
The simplest workaround I can think of is to chown the tree back to the current user and avoid leaving files on disk with uncleanly mapped uids. …

dashboard: ensure nodeenv downloaded content is owned by current user

---

src/mds/MDCache.cc
src/mds/ScrubStack.cc

Fixes: https://tracker.ceph.com/issues/70624 …

mds: use available CInode* for uninline data

---

src/include/cephfs/libcephfs.h
src/libcephfs.cc
src/pybind/cephfs/cephfs.pyx
src/pybind/cephfs/types.pxd

allows for setting `uid`/`gid` over 2^31-1 through `libcephfs` and `pybind/libcephfs`
Fixes: https://tracker.ceph.com/issues/71015 …

libcephfs / pybind: use uid_t and gid_t instead of int

---

doc/mgr/dashboard_plugins/debug.inc.rst

Edit doc/mgr/dashboard_plugins/debug.inc.rst. …

doc/mgr: edit debug.inc.rst

---

doc/mgr/dashboard_plugins/feature_toggles.inc.rst

Edit doc/mgr/dashboard_plugins/features_toggles.inc.rst. …

doc/mgr: edit feature_toggles.inc.rst

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/multisite-wizard-steps.enum.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/multi-cluster.ts
src/pybind/mgr/dashboard/services/rgw_client.py
src/pybind/mgr/dashboard/services/service.py

Currently, we just allow the user to create a new realm/zg/zone and setup replication using the multi-site replication wizard. The ask is to allow the user to select the pre-existing realm/zg/zone and setup replication via automatic export and import of token as well.
Fixes: https://tracker.ceph.com/issues/70276
https://github.com/user-attachments/assets/8e075ec3-3f52-4e6e-8615-e357180b4c8d …

mgr/dashboard: Allow the user to re-use existing realm/zg/zone and setup replication

---

doc/mgr/dashboard_plugins/feature_toggles.inc.rst

Edit doc/mgr/dashboard_plugins/features_toggles.inc.rst.
(cherry picked from commit 18e4ca258194238699649857f5f0ba195b67dea2) …

tentacle: doc/mgr: edit feature_toggles.inc.rst

---

doc/mgr/dashboard_plugins/feature_toggles.inc.rst

Edit doc/mgr/dashboard_plugins/features_toggles.inc.rst.
(cherry picked from commit 18e4ca258194238699649857f5f0ba195b67dea2) …

reef: doc/mgr: edit feature_toggles.inc.rst

---

doc/mgr/dashboard_plugins/debug.inc.rst

Edit doc/mgr/dashboard_plugins/debug.inc.rst.
(cherry picked from commit 1e87aa66b9de0a4e74bb4b1fbd806d974e0e8dcf) …

squid: doc/mgr: edit debug.inc.rst

---

doc/mgr/dashboard_plugins/debug.inc.rst

Edit doc/mgr/dashboard_plugins/debug.inc.rst.
(cherry picked from commit 1e87aa66b9de0a4e74bb4b1fbd806d974e0e8dcf) …

reef: doc/mgr: edit debug.inc.rst

---

doc/cephfs/cephfs-mirroring.rst

Don't format an unordered list as preformatted block.
Fix (not linked) reference to a section name that doesn't exist.
Don't call systemd unit files "systemctl unit files", add an "and" between them.
Clarify by means of inline formatting and whitespace that config value is "60" and the unit for that is seconds (as opposed to value being "60s").
Use double backticks consistently when listing commands, file names or paths, command parameters, syntaxes, etc.
Use star for inline italic instead of single backtick (to differentiate from the previous).
Don't use double backticks for "cephadm" when talking about the concept.
Don't capitalize a few words that didn't need it.
Capitalize table data for consistency.
All caps for "MDS".
Call it "cephfs-mirror" everywhere and not "cephfs_mirror" at one …

doc/cephfs: Cosmetic changes and small fixes in cephfs-mirroring.rst

---

src/pybind/mgr/dashboard/model/nvmeof.py
src/pybind/mgr/dashboard/services/nvmeof_client.py
src/pybind/mgr/dashboard/tests/test_nvmeof_client.py

These fields appears in the old cli, so I added them to the new one as well.
example output:
```
[myuser@myvm ~]# ceph nvmeof subsystem list | jq
{
"status": 0,
"error_message": "Success",
"subsystems": [
{
"nqn": "nqn.2016-06.io.spdk:cnode1.mygroup1",
"enable_ha": true,
"serial_number": "Ceph49004842768254",
"model_number": "Ceph bdev Controller",
"min_cntlid": 1,
"max_cntlid": 2040,
"namespace_count": 4,
"subtype": "NVMe",
"max_namespaces": 1024,
"has_dhchap_key": false,
"allow_any_host": true,
"created_without_key": false
},
{
"nqn": "nqn.2016-06.io.spdk:cnode2.mygroup1",
"enable_ha": true,
"serial_number": "Ceph4136752652420",
"model_number": "Ceph bdev Controller",
"min_cntlid": 1,
"max_cntlid": 2040,
"namespace_count": 4,
"subtype": "NVMe",
"max_namespaces": 1024,
"has_dhchap_key": …
```

mgr/dashboard: Add missing fields to subsytem list API/CLI

---

doc/mgr/diskprediction.rst

Edit doc/mgr/diskpredictor.rst. This includes the rewriting of sentences so that they now appear in grammatically-correct English. …

doc/mgr: edit diskpredictor.rst

---

src/test/test_not_before_queue.cc

Fix memory leak in test_not_before_queue identified by AddressSanitizer. Previously, the test was terminating without properly dequeueing all elements, causing resource leaks during teardown.
This change implements a proper cleanup mechanism that:
1. Advances the queue's time until all elements become eligible for processing
2. Dequeues all remaining elements to ensure proper destruction
3. Guarantees clean teardown even for elements with future timestamps
The fix eliminates ASan-reported leaks occurring in the not_before_queue_t::enqueue method when test cases were torn down prematurely.
A sample of the error from ASan:
```
Direct leak of 1800 byte(s) in 15 object(s) allocated from:
#0 0x7f71b1f1ab5b in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:86 …
```

test/test_not_before_queue: Fix memory leak by freeing ineligible items in destructor

---

src/os/bluestore/BlueStore.cc
src/os/bluestore/Compression.cc
src/os/bluestore/Compression.h

When data is very very compressible (95%+ , like all zeros) recompression scanner gets confused and
wants to get large already compressed blobs for recompression.
This is because it really seems to make sens - the compressed size is so small it all should fit together with next extents together on single allocation unit.
However - due to our blob split policy we need to cut it much earlier.
This is fixed now - large compressed blobs are penalized and effectively excluded.
Fixes: https://tracker.ceph.com/issues/71168 …

os/bluestore: Do not recompress large compressed blobs

---

doc/radosgw/adminops.rst
qa/suites/rgw/verify/tasks/admin-pagination.yaml
qa/workunits/rgw/run-admin-pagination.sh
qa/workunits/rgw/test_rgw_admin_pagination.py
src/rgw/driver/rados/rgw_bucket.cc
src/rgw/driver/rados/rgw_bucket.h
src/rgw/driver/rados/rgw_rest_bucket.cc
src/test/rgw/test_rgw_admin_bucket.py

This adds pagination to the /admin/bucket endpoint for the Admin API.
If a user has a lot of buckets the /admin/bucket endpoint that is listing buckets can be so long that the HTTP request gets a timeout.
This adds the ``max-entries`` and ``marker`` query parameters to the API to support pagination. If ``max-entries`` is given we introduce a new format for the HTTP response body the same way that metadata API does, if it's not given we return the response with the same body as before and thus retaining the backward compatibility of the API.
This adds a Python3 based test suite that tests all of this functionality to verify the behaviour and the HTTP response body itself.
This fixes the pagination mentioned in tracker [1] and thus fixes (or atleast partially fixes) that.
[1] …

rgw/admin: Add max-entries and marker to bucket list

---

make-debs.sh

This will allow us to get consistent cache hits in CI builds without disturbing other workflows. …

make-debs.sh: Optionally rm version from build dir

---

src/osd/scrubber/osd_scrub.cc
src/osd/scrubber/osd_scrub.h

Previously, there were two conditions under which the CPU load was considered
low enough to allow scrubbing:
- the CPU load was below the configured threshold, or
- the load was below a calculated "daily" average, and lower than the
15-min average.
That second condition was confusing and surprising, and is now removed.
Original tracker: https://tracker.ceph.com/issues/71347
Fixes: https://tracker.ceph.com/issues/71366
Backport of https://github.com/ceph/ceph/pull/63325

tentacle: osd/scrub: remove the 2'nd option for determining 'low load' for scrub

---

src/mon/PGMap.cc
src/test/mon/PGMap.cc

Fixes: https://tracker.ceph.com/issues/67906
(cherry picked from commit 4de57e904cffbf134b25b28f46caccebfc4456b1)
The scaling of max_avail by the ratio of non-degraded to total objects count results in the reported max_avail increasing proportionally to the number of OSDs marked `down` but not `out`.  This is counter intuitive since OSDs going `down` should never result in more space being available.
Removing the scale factor allows max_avail to remain unchanged until the OSDs are marked `out`. …

reef: PGMap: remove pool max_avail scale factor

---

doc/radosgw/cloud-transition.rst

Indent text that should belong to list items so they are formatted as list items.
Add missing full stop for a few sentences.
Move "the" outside of inline preformatted.
Format S3 API operation name with inline preformatted which seems common.
Before: https://docs.ceph.com/en/latest/radosgw/cloud-transition/
Rendered PR: https://ceph--63446.org.readthedocs.build/en/63446/radosgw/cloud-transition/ …

doc/radosgw: Cosmetic improvements in cloud-transition.rst

---

src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.ts

**What was done?**
This commit ensures that when users click on a tab in the side navigation and the displayed menu goes out of their view (e.g., "Administration") , the menu will automatically scroll up by default. This prevents users from manually scrolling to view the full side navigation menu.
The `<cds-sidenav>` is the tag that receives the event because it has the `<cds-sidenav-item>` tags that are the display menus. `onMenuClick($event)` function gets which menu element was clicked by proximity. Once displayed, the overflow is verified with the user view. This user view is acquired with `getBoundingClientRect()`. Finally, if it is out of the user view we scroll the side navigation until clicked menu shows all its content.
**Video demonstration:**
[Screencast from 2025-04-04 …

scroll up by default when clicking on side navigation

---

doc/mgr/influx.rst

doc/mgr: edit influx.rst.

---

doc/mgr/influx.rst

Edit doc/mgr/influx.rst.
(cherry picked from commit 32bdcaab3c4cad830fa05d192a35954ce846a9ae) …

squid: doc/mgr: edit influx.rst.

---

doc/mgr/influx.rst

Edit doc/mgr/influx.rst.
(cherry picked from commit 32bdcaab3c4cad830fa05d192a35954ce846a9ae) …

reef: doc/mgr: edit influx.rst.

---

doc/mgr/mds_autoscaler.rst

Edit mds_autoscaler.rst. Improve the English where necessary. …

doc/mgr: edit mds_autoscaler.rst

---

src/include/any.h

std::aligned_storage_t was deprecated in C++23, to be prepared for it, let's use alignas for the same behavior. because we do not always pass a power-of-2 number to `immobile_any`, while `alignas()` requires an alignment of power of 2. so we use `std::bit_ceil()` to calculate the minimum alignment greater or equal to the given number. …

include/any.h: avoid using std::aligned_storage_t

---

doc/mgr/rgw.rst

doc/mgr: edit rgw.rst

---

doc/cephfs/cephfs-mirroring.rst

Don't format an unordered list as preformatted block.
Fix (not linked) reference to a section name that doesn't exist.
Don't call systemd unit files "systemctl unit files", add an "and" between them.
Clarify by means of inline formatting and whitespace that config value is "60" and the unit for that is seconds (as opposed to value being "60s").
Use double backticks consistently when listing commands, file names or paths, command parameters, syntaxes, etc.
Use star for inline italic instead of single backtick (to differentiate from the previous).
Don't use double backticks for "cephadm" when talking about the concept.
Don't capitalize a few words that didn't need it.
Capitalize table data for consistency.
All caps for "MDS".
Small updates to language in text.
Call it "cephfs-mirror" …

tentacle: doc/cephfs: Cosmetic changes and small fixes in cephfs-mirroring.rst

---

doc/cephfs/cephfs-mirroring.rst

Don't format an unordered list as preformatted block.
Fix (not linked) reference to a section name that doesn't exist.
Don't call systemd unit files "systemctl unit files", add an "and" between them.
Clarify by means of inline formatting and whitespace that config value is "60" and the unit for that is seconds (as opposed to value being "60s").
Use double backticks consistently when listing commands, file names or paths, command parameters, syntaxes, etc.
Use star for inline italic instead of single backtick (to differentiate from the previous).
Don't use double backticks for "cephadm" when talking about the concept.
Don't capitalize a few words that didn't need it.
Capitalize table data for consistency.
All caps for "MDS".
Small updates to language in text.
Call it "cephfs-mirror" …

squid: doc/cephfs: Cosmetic changes and small fixes in cephfs-mirroring.rst

---

doc/cephfs/cephfs-mirroring.rst

Don't format an unordered list as preformatted block.
Fix (not linked) reference to a section name that doesn't exist.
Don't call systemd unit files "systemctl unit files", add an "and" between them.
Clarify by means of inline formatting and whitespace that config value is "60" and the unit for that is seconds (as opposed to value being "60s").
Use double backticks consistently when listing commands, file names or paths, command parameters, syntaxes, etc.
Use star for inline italic instead of single backtick (to differentiate from the previous).
Don't use double backticks for "cephadm" when talking about the concept.
Don't capitalize a few words that didn't need it.
Capitalize table data for consistency.
All caps for "MDS".
Small updates to language in text.
Call it "cephfs-mirror" …

reef: doc/cephfs: Cosmetic changes and small fixes in cephfs-mirroring.rst

---

doc/mgr/smb.rst

doc/mgr: edit smb.rst

---

doc/mgr/telegraf.rst

doc/mgr: edit telegraf.rst

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.ts

backport tracker: https://tracker.ceph.com/issues/71362
---
backport of https://github.com/ceph/ceph/pull/63319
parent tracker: https://tracker.ceph.com/issues/71341

tentacle: mgr/dashboard: accept dot(.) in user_id & restrict tenant validation in user form

---

src/common/options/osd.yaml.in

osd_max_scrubs takes effect even though mclock is used.
```
$ ceph config show-with-defaults osd.0 | grep '^osd_max_scrubs' | sed -E -e 's/( +)/ /g'
osd_max_scrubs 3 default
$ ceph config show-with-defaults osd.0 | grep '^osd.* override ' | sed -E -e 's/( +)/ /g'
osd_delete_sleep 0.000000 override
osd_delete_sleep_hdd 0.000000 override
osd_delete_sleep_hybrid 0.000000 override
osd_delete_sleep_ssd 0.000000 override
osd_pg_delete_cost 15728640 override
osd_recovery_sleep 0.000000 override
osd_recovery_sleep_hdd 0.000000 override
osd_recovery_sleep_hybrid 0.000000 override
osd_recovery_sleep_ssd 0.000000 override
osd_scrub_sleep 0.000000 override
osd_snap_trim_sleep 0.000000 override
osd_snap_trim_sleep_hdd 0.000000 override
osd_snap_trim_sleep_hybrid 0.000000 override …
```

reef: common/options: fix the description of osd_max_scrubs

---

PendingReleaseNotes
doc/rados/operations/monitoring.rst

backport tracker: https://tracker.ceph.com/issues/71440
---
backport of https://github.com/ceph/ceph/pull/63181
parent tracker: https://tracker.ceph.com/issues/71439

tentacle: docs: add release notes and docs for availability score feature 

---

src/test/rgw/CMakeLists.txt
src/test/rgw/test_rgw_lua.cc

test_rgw_lua.cc was allocating a CephContext without initializing it, so log statements from the tests/rgw code weren't actually being logged
the unit-main target links in the main() function from test/unit.cc which initializes the CephContext via global_init(). use the resulting global g_ceph_context instead of managing a separate one
Related-to: https://tracker.ceph.com/issues/70673
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | …

test/rgw: link lua test against unit-main for g_ceph_context

---

doc/radosgw/cloud-restore.rst
doc/radosgw/cloud-transition.rst

Add a label in file cloud-transition.rst for linking to it.
Change a link using full URL of Ceph docs to use :ref: and said label.
Indent text in unordered lists so that they are rendered as list items.
Use consistently double backticks for references to configuration values.
Change one external link pointing to old v1 of AWS CLI to the recommended v2 docs.
Change another external link pointing to old v1 of AWS CLI to the current AWS API doc instead and add link text instead of rendering the whole URL.
However, both the old and the new text (which are the same) do not currently seem to explicitly confirm the claim "storage class of restored objects should remain unchanged".
Change one CLI command prompt to privileged prompt because it uses radosgw-admin.
Use "lifecycle" consistently …

doc/radosgw: Small improvements in cloud-restore.rst

---

src/crimson/os/seastore/omap_manager/btree/omap_btree_node.h
src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.h

So that whether the omap node is root can be determined at the time of extent load
Fixes: https://tracker.ceph.com/issues/71383 …

crimson/os/seastore/omap_manager: handle the cases in which omap nodes are rewritten before seen by users

---

src/crimson/os/seastore/async_cleaner.h

This commit updates seastore to increment used_bytes only when allocation is successful.
Without this commit, the seatore reports incorrect size if alloc_paddr fails (e.g., due to insufficient space)
before:
usage:   47 GiB used, 16 EiB / 47 GiB avail
after:
usage:   47 GiB used, 18 KiB / 47 GiB avail …

crimson/os/seastore/rbm: prevent incorrect space calculation at maximum capacity

---

src/common/options/global.yaml.in

"mon_warn_pg_not_scrubbed_ratio" to the confval definition of that variable. Although this variable contains the string "mon", it is set on the Manager. I have added a note to direct users to set this value on the Manager.
This issue is part of a small project that also encompasses https://github.com/ceph/ceph/pull/62459, which is associated with commit aeef59a50ee31072648ba0c7436b6522137614cd
(cherry picked from commit 5754906c3bd15a63855b8265a3ac93ae2a1a3c8c) …

reef: src/common: add guidance for mon_warn_pg_not_scrubbed

---

doc/cephadm/host-management.rst

Improve the English in the section "Maintenance Mode" in the file doc/cephadm/host-management.rst.
- Tracker …

doc/cephadm: improve "Maintenance Mode"

---

doc/rados/operations/cache-tiering.rst

Correct ill-formatted markup in cache-tiering.rst.
- …

doc/rados: improve markup in cache-tiering.rst

---

doc/mgr/iostat.rst

Edit doc/mgr/iostat.rst. Improve the English where necessary. …

doc/mgr: edit iostat.rst

---

src/crimson/os/seastore/onode.h

Due to a recent change (adding shard_versions in object_info_t, https://github.com/ceph/ceph/commit/88ac6d938ff28041d92b8ce828e59cd08a791387), the size of OI has increased. As a result, the OI can no longer be embedded directly in the onode, since its size now exceeds OI_MAX_LENGTH. This causes the OI data to be stored in the omap tree instead, leading to a performance drop in small random writes. …

crimson/os/seastore: increase OI_MAX_LENGTH to avoid storing OI data in the omap tree

---

src/rgw/rgw_bucket_logging.cc
src/rgw/rgw_op.cc
src/rgw/rgw_op.h
src/rgw/rgw_process.cc
src/rgw/rgw_rest.h

(in standard mode)
Fixes: https://tracker.ceph.com/issues/71312
<details> …

rgw/logging: part upload operation name should be REST.PUT.PART

---

doc/radosgw/s3/bucketops.rst
src/rgw/rgw_common.h
src/rgw/rgw_rest_bucket_logging.cc

Fixes: https://tracker.ceph.com/issues/71385
<details> …

rgw/logging: add mtime to get-bucket-logging response

---

src/rgw/radosgw-admin/radosgw-admin.cc
src/rgw/rgw_bucket_logging.cc
src/rgw/rgw_bucket_logging.h
src/rgw/rgw_rest_bucket_logging.cc

test instructions:
https://gist.github.com/yuvalif/adfa186fdbe9ad4c5b689753a15ec480
bug was introduced in: 790c38eacc52cc4c14beb48fca8b204235632793
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull-requests/config/definitions/ceph-perf …

rgw/logging: extract tenant from bucket name on admin flush

---

doc/mgr/iostat.rst

Edit doc/mgr/iostat.rst. Improve the English where necessary.
(cherry picked from commit 98708a7f7f3c470758063e21e840393440450381) …

squid: doc/mgr: edit iostat.rst

---

doc/mgr/iostat.rst

Edit doc/mgr/iostat.rst. Improve the English where necessary.
(cherry picked from commit 98708a7f7f3c470758063e21e840393440450381) …

reef: doc/mgr: edit iostat.rst

---

doc/rados/operations/cache-tiering.rst

Correct ill-formatted markup in cache-tiering.rst.
(cherry picked from commit 2c3815aadb45eb607608e6390a48e1eaa5e4f034) …

squid: doc/rados: improve markup in cache-tiering.rst

---

doc/rados/operations/cache-tiering.rst

Correct ill-formatted markup in cache-tiering.rst.
(cherry picked from commit 2c3815aadb45eb607608e6390a48e1eaa5e4f034) …

reef: doc/rados: improve markup in cache-tiering.rst

---

doc/cephadm/host-management.rst

Improve the English in the section "Maintenance Mode" in the file doc/cephadm/host-management.rst.
(cherry picked from commit 2d4ee6aea3a3003eff910feb130110a6588fb384) …

squid: doc/cephadm: improve "Maintenance Mode"

---

doc/mgr/mds_autoscaler.rst

Edit mds_autoscaler.rst. Improve the English where necessary.
(cherry picked from commit efc438bd9f5753b42c74bf8f53ff94ebba1d4fb8) …

tentacle: doc/mgr: edit mds_autoscaler.rst

---

doc/mgr/mds_autoscaler.rst

Edit mds_autoscaler.rst. Improve the English where necessary.
(cherry picked from commit efc438bd9f5753b42c74bf8f53ff94ebba1d4fb8) …

reef: doc/mgr: edit mds_autoscaler.rst

---

PendingReleaseNotes
src/rgw/driver/rados/rgw_obj_manifest.cc
src/rgw/driver/rados/rgw_obj_manifest.h
src/rgw/driver/rados/rgw_putobj_processor.cc
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/rgw_op.cc
src/rgw/rgw_op.h
src/rgw/rgw_rest_s3.cc
src/rgw/rgw_sal.h

backport tracker: https://tracker.ceph.com/issues/70696
---
backport of https://github.com/ceph/ceph/pull/50148
parent tracker: https://tracker.ceph.com/issues/69226

reef: rgw: Head/GetObject support partNumber

---

src/test/rgw/rgw_multi/tests.py

backport tracker: https://tracker.ceph.com/issues/69130
---
backport of https://github.com/ceph/ceph/pull/60591
parent tracker: https://tracker.ceph.com/issues/67207

reef: qa/multisite: add extra checkpoints in datalog_autotrim testcase

---

doc/rados/operations/balancer.rst

doc/rados/operations: Add settings advice to balancer.rst …

doc/rados/operations: Add settings advice to balancer.rst

---

doc/mgr/localpool.rst

Edit doc/mgr/localpool.rst. Improve the English where necessary. …

doc/mgr: edit localpool.rst

---

src/mgr/Mgr.cc

backport tracker: https://tracker.ceph.com/issues/65621
---
backport of https://github.com/ceph/ceph/pull/56047
parent tracker: https://tracker.ceph.com/issues/64799

quincy: mgr: process map before notifying clients

---

doc/mgr/localpool.rst

Edit doc/mgr/localpool.rst. Improve the English where necessary.
(cherry picked from commit 9e7246b74075da557012b0744167011ca43eedb1) …

tentacle: doc/mgr: edit localpool.rst

---

doc/mgr/localpool.rst

Edit doc/mgr/localpool.rst. Improve the English where necessary.
(cherry picked from commit 9e7246b74075da557012b0744167011ca43eedb1) …

squid: doc/mgr: edit localpool.rst

---

doc/mgr/localpool.rst

Edit doc/mgr/localpool.rst. Improve the English where necessary.
(cherry picked from commit 9e7246b74075da557012b0744167011ca43eedb1) …

reef: doc/mgr: edit localpool.rst

---

doc/dev/cephfs-mirroring.rst

This commit edits the third quarter of the doc/dev/cephfs-mirroring.rst file. This commit edits down to the line beginning "`Peers` section in the command output".
(cherry picked from commit 3915238f21cd82896e6cda9cc90b68fee5d12750)
- …

tentacle: doc/dev/cephfs-mirroring: edit file 3 of x

---

doc/dev/cephfs-mirroring.rst

This commit edits the third quarter of the doc/dev/cephfs-mirroring.rst file. This commit edits down to the line beginning "`Peers` section in the command output".
(cherry picked from commit 3915238f21cd82896e6cda9cc90b68fee5d12750)
- …

reef: doc/dev/cephfs-mirroring: edit file 3 of x

---

doc/cephfs/fs-volumes.rst
doc/cephfs/troubleshooting.rst

Correct the links to cross-references in the cases of the following two directives:
1. pause-clone-threads
2. pause-purge-threads
(cherry picked from commit e59364f152847eabbedfe7fc72dfb66e7378b72b) (cherry picked from commit 2c76845a2108f449e1295aebce02a97e04a64b6a) …

tentacle: doc/cephfs: correct reference structure in fs-volumes.rst

---

doc/cephfs/fs-volumes.rst
doc/cephfs/troubleshooting.rst

Correct the links to cross-references in the cases of the following two directives:
1. pause-clone-threads
2. pause-purge-threads
(cherry picked from commit e59364f152847eabbedfe7fc72dfb66e7378b72b) (cherry picked from commit 2c76845a2108f449e1295aebce02a97e04a64b6a) …

reef: doc/cephfs: correct reference structure in fs-volumes.rst

---

doc/monitoring/index.rst

Correct list formatting in doc/monitoring/index.rst.
(cherry picked from commit b7889dc4f088ce2a5fa8165c21fa2d0a75700f56) …

squid: doc/monitoring: correct list formatting

---

doc/mgr/crash.rst

Edit doc/mgr/crash.rst. Add prompts and correct some of the inelegant English present in the file.
(cherry picked from commit aa2d9f98676928df02f898512f6eedc7c2bccd69) …

tentacle: doc/mgr: edit crash.rst

---

doc/mgr/crash.rst

Edit doc/mgr/crash.rst. Add prompts and correct some of the inelegant English present in the file.
(cherry picked from commit aa2d9f98676928df02f898512f6eedc7c2bccd69) …

squid: doc/mgr: edit crash.rst

---

PendingReleaseNotes
doc/radosgw/frontends.rst
src/rgw/rgw_asio_frontend.cc

backport tracker: https://tracker.ceph.com/issues/71173
---
backport of https://github.com/ceph/ceph/pull/62011
parent tracker: https://tracker.ceph.com/issues/71155

tentacle: rgw/frontend: Allow multiple RGWs to run on same port on same host

---

src/pybind/mgr/cephadm/services/nvmeof.py

Backport of https://github.com/ceph/ceph/pull/62585
<details> …

tentacle: mgr/cephadm: block deploying nvmeof daemons on the same host

---

src/rgw/rgw_orphan.cc
src/rgw/rgw_orphan.h

backport tracker: https://tracker.ceph.com/issues/70593
---
backport of https://github.com/ceph/ceph/pull/62368
parent tracker: https://tracker.ceph.com/issues/70539

reef: rgw: radoslist improvements primarily to better support gap list tool

---

src/rgw/driver/rados/rgw_tools.h
src/rgw/rgw_admin.cc
src/rgw/services/svc_bi_rados.h

backport tracker: https://tracker.ceph.com/issues/70982
---
backport of https://github.com/ceph/ceph/pull/62850
parent tracker: https://tracker.ceph.com/issues/70956

reef: rgw: prevent crash in `radosgw-admin bucket object shard ...`

---

qa/suites/rgw/verify/inline-data$/off-no-gc.yaml

backport tracker: https://tracker.ceph.com/issues/71062
---
backport of https://github.com/ceph/ceph/pull/62715
parent tracker: https://tracker.ceph.com/issues/70823

reef: qa/rgw: run verify tests with garbage collection disabled

---

src/rgw/driver/rados/rgw_tools.h
src/rgw/rgw_admin.cc
src/rgw/services/svc_bi_rados.h

backport tracker: https://tracker.ceph.com/issues/70981
---
backport of https://github.com/ceph/ceph/pull/62850
parent tracker: https://tracker.ceph.com/issues/70956

squid: rgw: prevent crash in `radosgw-admin bucket object shard ...`

---

src/rgw/driver/rados/rgw_lc_tier.cc
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/rgw_lc.cc

This PR addresses backport of below PRs
- https://github.com/ceph/ceph/pull/61090
- https://github.com/ceph/ceph/pull/60157
Fixes: https://tracker.ceph.com/issues/69940
Fixes: https://tracker.ceph.com/issues/71120
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | …

[squid] RGW backports

---

src/rgw/jwt-cpp/jwt.h
src/rgw/rgw_auth.cc
src/rgw/rgw_rest_sts.cc
src/rgw/rgw_rest_sts.h

backport tracker: https://tracker.ceph.com/issues/71107
---
backport of https://github.com/ceph/ceph/pull/61796
parent tracker: https://tracker.ceph.com/issues/54562

squid: rgw/sts: Implementation of validating JWT using modulus and exponent

---

src/mds/DamageTable.cc

due to mds_damage_table_max_entries has been reached.
Fixes: https://tracker.ceph.com/issues/71270
- Tracker …

mds: log meaningful error message when entering damaged state

---

src/include/cephfs/metrics/Types.h
src/mds/MetricsHandler.cc
src/tools/cephfs_mirror/ServiceDaemon.cc
src/tools/cephfs_mirror/Types.h

Replacing boost::variant with std::variant throughout the cephfs related codebase. This change is part of our ongoing effort to reduce third-party dependencies by leveraging C++ standard library alternatives where possible.
Benefits include:
- Improved code readability and maintainability
- Reduced external dependency surface
- More consistent API usage with other components …

cephfs, tools/cephfs_mirror: migrate from boost::variant to std::variant

---

src/client/Client.cc
src/client/Client.h
src/include/cephfs/libcephfs.h
src/libcephfs.cc
src/test/libcephfs/test.cc

Provide an easy and convenient API to update the reference to the inode. Please note that this is built on top of existing internal __ll_get()_ function used almost everywhere in the client code base. Newly introduced `ceph_ll_get()` just exposes the __ll_get()_ functionality to outside consumers.

libcephfs: Implement `ceph_ll_get()` API

---

monitoring/ceph-mixin/dashboards_out/ceph-application-overview.json

backport tracker: https://tracker.ceph.com/issues/71345
---
backport of https://github.com/ceph/ceph/pull/63279
parent tracker: https://tracker.ceph.com/issues/71318

tentacle: mgr/dashboard: fix flaky promql query test 

---

doc/radosgw/bucket_logging.rst
doc/radosgw/s3/bucketops.rst
src/rgw/rgw_op.cc
src/rgw/rgw_rest.h
src/rgw/rgw_rest_s3.h

Fixes: https://tracker.ceph.com/issues/71255
<details> …

rgw/logging: support object metadata changes in journal mode

---

doc/mgr/modules.rst

Edit doc/mgr/modules.rst. Improve some of the English.
This commit and the PR of which it is a part includes the changes made in https://github.com/ceph/ceph/pull/62782 and some corrections to glaring grammatical errors. However, this file could use a careful grammar pass. As it currently stands, it contains run-on sentences and English that is acceptable in conversation but not acceptable in written communication. …

doc/mgr: edit modules.rst.

---

doc/mgr/nfs.rst

Edit doc/mgr/nfs.rst. Improve some of the English.
This commit and the PR of which it is a part includes the changes made in https://github.com/ceph/ceph/pull/62782 and some corrections to glaring grammatical errors. However, this file could use a careful grammar pass. …

doc/mgr: edit nfs.rst

---

doc/mgr/progress.rst

doc/mgr: edit progress.rst

---

doc/mgr/rgw.rst

Edit doc/mgr/rgw.rst.
(cherry picked from commit e7f2a4b5b22280b32800930a5707791360e68f59) …

squid: doc/mgr: edit rgw.rst

---

doc/mgr/prometheus.rst

Edit doc/mgr/prometheus.rst.
(cherry picked from commit 7cae041f46b010694c6c40b31e36719af1f3fb26) …

reef: doc/mgr: edit prometheus.rst

---

doc/mgr/nfs.rst

Edit doc/mgr/nfs.rst. Improve some of the English.
This commit and the PR of which it is a part includes the changes made in https://github.com/ceph/ceph/pull/62782 and some corrections to glaring grammatical errors. However, this file could use a careful grammar pass.
(cherry picked from commit 1c2544d8e1df8b9fcd53617f2b5cb1d6a5814f22)
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backport …

tentacle: doc/mgr: edit nfs.rst

---

src/osd/scrubber/osd_scrub.cc
src/osd/scrubber/osd_scrub.h
src/osd/scrubber/pg_scrubber.cc
src/osd/scrubber/scrub_job.cc
src/osd/scrubber/scrub_job.h

fix get_scrub_sleep_time() call parameters, to use the correct
logic (observes_extended_sleep()) for sleep time calculations.

osd/scrub: only periodic_regular scrubs should suffer extended sleeps

---

monitoring/ceph-mixin/dashboards_out/ceph-application-overview.json

backport tracker: https://tracker.ceph.com/issues/71444
---
backport of https://github.com/ceph/ceph/pull/63347
parent tracker: https://tracker.ceph.com/issues/71361

tentacle: mgr/dashboard: Fix applicatin pool table for filtered pools 

---

doc/radosgw/cloud-transition.rst

Indent text that should belong to list items so they are formatted as list items.
Add missing full stop for a few sentences.
Move "the" outside of inline preformatted.
Format S3 API operation name with inline preformatted which seems common.
(cherry picked from commit 863d57de735b3ad2d22adf065d86a92fc6b57261) …

reef: doc/radosgw: Cosmetic improvements in cloud-transition.rst

---

doc/radosgw/cloud-transition.rst

Indent text that should belong to list items so they are formatted as list items.
Add missing full stop for a few sentences.
Move "the" outside of inline preformatted.
Format S3 API operation name with inline preformatted which seems common.
(cherry picked from commit 863d57de735b3ad2d22adf065d86a92fc6b57261) …

squid: doc/radosgw: Cosmetic improvements in cloud-transition.rst

---

doc/mgr/progress.rst

Edit doc/mgr/progress.rst.
(cherry picked from commit 9bada3be2f49377bec06f4a270dea7174777b763) …

tentacle: doc/mgr: edit progress.rst

---

cmake/modules/AddCephTest.cmake
src/test/rgw/CMakeLists.txt

Makes it less tedious to add a new Catch2 test with CMake by adding functions that handle some
of the bookkeeping tedium.
Adding a new test should be easy and let programmers get to writing tests, not fiddling with the
build system; before this PR, adding a new Catch2 test was a bit of a pain and required more focus
on CMake and the build system than one might hope for-- discouraging the addition of new tests and
making for sad programmers. 
But, the sadness is no more! This PR adds a cmake module function that may in turn 
be wrapped to give you a joyful test-adding experience:
touch rgw_hex.cc foo_test.cc
...and then in CMakelists.txt:
add_catch2_test_rgw(rgw_hex)
add_catch2_test_rgw(foo_test NO_CATCH2_MAIN)
Signed-off-by: Jesse Williamson <jfw@ibm.com> …

make adding Catch2 tests straightforward

---

doc/mgr/orchestrator.rst

Edit doc/mgr/orchestrator.rst.
(cherry picked from commit 31ce3058fbc06709759e4c129a1af8678b257a6e) …

tentacle: doc/mgr: edit orchestrator.rst

---

doc/mgr/progress.rst

Edit doc/mgr/progress.rst.
(cherry picked from commit 9bada3be2f49377bec06f4a270dea7174777b763) …

squid: doc/mgr: edit progress.rst

---

win32_build.sh
win32_deps_build.sh

The Windows build is using a very old OpenSSL version (1.1.1c), we'll bump the version to 3.0.16. …

win32_deps_bild: bump openssl version

---

doc/mgr/prometheus.rst

Edit doc/mgr/prometheus.rst.
(cherry picked from commit 7cae041f46b010694c6c40b31e36719af1f3fb26) …

squid: doc/mgr: edit prometheus.rst

---

src/osd/OSD.cc
src/osd/scrubber/osd_scrub.cc
src/osd/scrubber/osd_scrub.h

As we no longer maintain a 'daily average', and as the interaction
between the load tracker and the scrub scheduler is now much simplified,
we can remove the load tracker entirely.
This is more than a cleanup: after https://github.com/ceph/ceph/pull/63349 was merged, the CPU load update frequency is, by default, too low.
Fixes: https://tracker.ceph.com/issues/71422
Backport of https://github.com/ceph/ceph/pull/63379

tentacle: osd/scrub: remove OsdScrub::LoadTracker

---

doc/mgr/rgw.rst

Use double backticks consistently for module name, CLI commands and parameters etc.
Use title case in section titles and underline them only until end of title text.
Use "command line" instead of "cmd line" in text.
Capitalize RGW consistently.
Delete one paragraph that included a strange out of place text fragment.
Call it "Manager" consistently instead of "MGR" in text one time.
Improve language in CA cert upgrade.
(cherry picked from commit 7a3c6b563bb39e2adde4d3211cb603161fd46f02) …

tentacle: doc/mgr: Small improvements in rgw.rst

---

doc/mgr/rgw.rst

Use double backticks consistently for module name, CLI commands and parameters etc.
Use title case in section titles and underline them only until end of title text.
Use "command line" instead of "cmd line" in text.
Capitalize RGW consistently.
Delete one paragraph that included a strange out of place text fragment.
Call it "Manager" consistently instead of "MGR" in text one time.
Improve language in CA cert upgrade.
(cherry picked from commit 7a3c6b563bb39e2adde4d3211cb603161fd46f02) …

squid: doc/mgr: Small improvements in rgw.rst

---

doc/mgr/rgw.rst

Use double backticks consistently for module name, CLI commands and parameters etc.
Use title case in section titles and underline them only until end of title text.
Use "command line" instead of "cmd line" in text.
Capitalize RGW consistently.
Delete one paragraph that included a strange out of place text fragment.
Call it "Manager" consistently instead of "MGR" in text one time.
Improve language in CA cert upgrade.
(cherry picked from commit 7a3c6b563bb39e2adde4d3211cb603161fd46f02) …

reef: doc/mgr: Small improvements in rgw.rst

---

doc/rados/operations/placement-groups.rst

doc/rados/operations: Improve placement-groups.rst
Clarify PG autoscaler terms and practices.
Modernize ``pg_num`` guidance.
Correct ``pgp_num`` to ``pg_num`` in multiple places. …

doc/rados/operations: Improve placement-groups.rst

---

src/CMakeLists.txt

CMake newer than 3.30 appears to require more annotation for add_custom_command(). This adds PRE_BUILD.
- Tracker …

Add PRE_BUILD to breakpad command (fix for CMake > 3.30)

---

doc/mgr/modules.rst

s/called/named/ as requested by Anthony D'Atri in
https://github.com/ceph/ceph/pull/63451#discussion_r2104487962.
- …

doc/mgr: edit modules.rst

---

monitoring/ceph-mixin/dashboards.libsonnet
monitoring/ceph-mixin/dashboards/cephfsdashboard.libsonnet
monitoring/ceph-mixin/dashboards/timeseries_panel.libsonnet
monitoring/ceph-mixin/dashboards/utils.libsonnet
monitoring/ceph-mixin/dashboards_out/cephfsdashboard.json

backport tracker: https://tracker.ceph.com/issues/71477
---
backport of https://github.com/ceph/ceph/pull/62164
parent tracker: https://tracker.ceph.com/issues/70901

tentacle: mgr/dashboard: Creating CephFS dashboard for Grafana

---

doc/mgr/modules.rst

s/called/named/ as requested by Anthony D'Atri in
https://github.com/ceph/ceph/pull/63451#discussion_r2104487962.
(cherry picked from commit 02621f7683b9296dccf943326cc555052aa5a2ab) …

squid: doc/mgr: edit modules.rst

---

doc/mgr/nfs.rst

Edit the "Updating an NFS Cluster" section of doc/mgr/nfs.rst. This commit includes changes requested by Anthony D'Atri in https://github.com/ceph/ceph/pull/63452.
(cherry picked from commit a4a29fe23fe721c9a3f8d4efc746d0250df4db58) …

squid: doc/mgr: edit nfs.rst

---

src/pybind/mgr/cephadm/inventory.py

ce360a4a introduced a regression.
`ceph orch hardware status` fails when no hostname is passed (global cluster hw status report).
Typical failure:
```
Error EINVAL: Traceback (most recent call last):
File "/usr/share/ceph/mgr/mgr_module.py", line 1928, in _handle_command
return self.handle_command(inbuf, cmd)
File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 186, in handle_command
return dispatch[cmd['prefix']].call(self, cmd, inbuf)
File "/usr/share/ceph/mgr/mgr_module.py", line 527, in call
return self.func(mgr, **kwargs)
File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 122, in <lambda>
wrapper_copy = lambda *l_args, **l_kwargs: wrapper(*l_args, **l_kwargs)  # noqa: E731
File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 111, in wrapper
return func(*args, …
```

node-proxy: address `ceph orch hardware status` cmd

---

doc/mgr/cli_api.rst

Edit doc/mgr/cli_api.rst as part of the project to determine where the error is in https://github.com/ceph/ceph/pull/62782 that prevents the Jenkins tests from passing.
https://github.com/ceph/ceph/pull/62782 and this commit represents one of what will be at least twenty-five other commits made to track this error down. …

doc/mgr: edit cli_api.rst

---

doc/radosgw/metrics.rst

Change the wording of a sentence in doc/radosgw/metrics.rst so that its articles read as though they were written by a native speaker of the English language.
This commit is being raised as part of a diagnostic process aimed at discovering why the ReadtheDocs check is failing on PR https://github.com/ceph/ceph/pull/62877. …

doc/radosgw: edit sentence in metrics.rst

---

doc/radosgw/metrics.rst

Change the wording of a sentence in doc/radosgw/metrics.rst so that its articles read as though they were written by a native speaker of the English language.
This commit is being raised as part of a diagnostic process aimed at discovering why the ReadtheDocs check is failing on PR https://github.com/ceph/ceph/pull/62877.
(cherry picked from commit 90ac0bdf7d6b1cda3a7e99a91bbeddbc8511c815) …

tentacle: doc/radosgw: edit sentence in metrics.rst

---

doc/rados/operations/placement-groups.rst

(cherry picked from commit 201e34119ab8628f5c99763212613678ec29dde3)
- Component …

reef: doc/rados/operations: Additional improvements to placement-groups.rst

---

doc/rados/operations/cache-tiering.rst

Strengthen the warning against deploying cache tiering in releases after Reef. This follows up on Anthony D'Atri's request in https://github.com/ceph/ceph/pull/63465.
(cherry picked from commit f4de34f4bdbc7b3930afd8c034064675640df202) …

tentacle: doc/rados/operations: edit cache-tiering.rst

---

doc/mgr/telemetry.rst

The English in this file is unacceptably demotic and exhibits a curious but all-too-familiar lack here and there of definite articles.
(cherry picked from commit be67afcfcb51d07251f8a2be86de8dd7f45c713f)
- When filling out the below checklist, you may click boxes directly in …

squid: doc/mgr: edit telemetry.rst

---

doc/mgr/telemetry.rst

The English in this file is unacceptably demotic and exhibits a curious but all-too-familiar lack here and there of definite articles.
(cherry picked from commit be67afcfcb51d07251f8a2be86de8dd7f45c713f)
- When filling out the below checklist, you may click boxes directly in …

reef: doc/mgr: edit telemetry.rst

---

doc/mgr/cli_api.rst

Edit doc/mgr/cli_api.rst as part of the project to determine where the error is in https://github.com/ceph/ceph/pull/62782 that prevents the Jenkins tests from passing.
https://github.com/ceph/ceph/pull/62782 and this commit represents one of what will be at least twenty-five other commits made to track this error down.
(cherry picked from commit 2ae483840ae1629677446150f649ca484b613dbe) …

tentacle: doc/mgr: edit cli_api.rst

---

doc/mgr/cli_api.rst

Edit doc/mgr/cli_api.rst as part of the project to determine where the error is in https://github.com/ceph/ceph/pull/62782 that prevents the Jenkins tests from passing.
https://github.com/ceph/ceph/pull/62782 and this commit represents one of what will be at least twenty-five other commits made to track this error down.
(cherry picked from commit 2ae483840ae1629677446150f649ca484b613dbe) …

squid: doc/mgr: edit cli_api.rst

---

doc/mgr/cli_api.rst

Edit doc/mgr/cli_api.rst as part of the project to determine where the error is in https://github.com/ceph/ceph/pull/62782 that prevents the Jenkins tests from passing.
https://github.com/ceph/ceph/pull/62782 and this commit represents one of what will be at least twenty-five other commits made to track this error down.
(cherry picked from commit 2ae483840ae1629677446150f649ca484b613dbe) …

reef: doc/mgr: edit cli_api.rst

---

doc/radosgw/cloud-transition.rst

Indent text that should belong to list items so they are formatted as list items.
Add missing full stop for a few sentences.
Move "the" outside of inline preformatted.
Format S3 API operation name with inline preformatted which seems common.
(cherry picked from commit 863d57de735b3ad2d22adf065d86a92fc6b57261) …

tentacle: doc/radosgw: Cosmetic improvements in cloud-transition.rst

---

doc/mgr/diskprediction.rst

Edit doc/mgr/diskpredictor.rst. This includes the rewriting of sentences so that they now appear in grammatically-correct English.
(cherry picked from commit 4d628d93ce7d56e26e381bae2fcbfc5dfd78fa7e) …

tentacle: doc/mgr: edit diskpredictor.rst

---

doc/mgr/diskprediction.rst

Edit doc/mgr/diskpredictor.rst. This includes the rewriting of sentences so that they now appear in grammatically-correct English.
(cherry picked from commit 4d628d93ce7d56e26e381bae2fcbfc5dfd78fa7e) …

reef: doc/mgr: edit diskpredictor.rst

---

src/client/Client.cc
src/test/libcephfs/suidsgid.cc

An unprivileged user can `chmod 777` a directory owned by root and gain access. Fix this bug and also add a test case for the same.
(cherry picked from commit fb1b72d5cbfb285620a2ae632f1b4d75b8fb8336) …

squid: client: disallow unprivileged users to escalate root privileges

---

doc/start/documenting-ceph.rst

Edit the section "Build the Source (First Time)" in doc/start/documenting-ceph.rst.
- remove references to RHEL7 (it's old)
- improve sentences (they were first-draft-like)
- improve RST formatting
(cherry picked from commit 24771aecdcfb43c01bf3b54c87ce329b90d13389) …

reef: doc/start: edit documenting-ceph.rst

---

src/ceph-volume/ceph_volume/objectstore/lvmbluestore.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_prepare.py
src/ceph-volume/ceph_volume/tests/objectstore/test_lvmbluestore.py

This refactores redundant device setup calls in LvmBlueStore class: Calling the same function twice with different arguments for WAL and DB devices was inefficient and unnecessary.
The new implementation simplifies the logic by directly accessing `self.args`, it removes the need for passing arguments manually.

ceph-volume: refactor LvmBlueStore.setup_device()

---

.github/labeler.yml
.github/workflows/diff-ceph-config.yml
.github/workflows/scripts/config-diff-post-comment.js
src/script/config-diff/README.md
src/script/config-diff/config_diff.py
src/script/config-diff/requirements.txt

---
There are two problems with the visibility of the changes done to Ceph configuration options.
- Changes to the configuration are missed in our release notes
- No easy way to know what configuration have changed/added/deleted between two releases
More information about the above problems and the discussions surrounding it are present here:
1. https://pad.ceph.com/p/ceph-config-diff
2. [Ceph Dev Mailing list](https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/7PQ5GWNX4NVWYP2UZLC34BEUH6GSRYBT/#7ZF5HZMY3C7J3GHHBVTHLW725G3L4HHO)
This PR addresses the above problem
1. A `config-diff` python script to allow users to compare configuration changes across different Ceph branches, tags and forked repositories
2. A GitHub action using the above script that check for any configurations …

script: add configuration diff tool

---

src/test/client/CMakeLists.txt
src/test/fs/CMakeLists.txt
src/test/libcephfs/CMakeLists.txt

test/libcephfs: copy DT_NEEDED entries from input libraries

---

debian/control

Back in 2020 the '/etc/mime.types' file was split out into its own leaner 'media-types' Debian package [0], the previous 'mime-support' was kept as transitional package to handle upgrades, but it did its job and isn't included in Debian Trixie repos anymore.
So accept both, the new 'media-types' package or the legacy 'mime-support' one as valid dependency for radosgw, this ensures one can install radosgw on newer Debian based releases while keeping it also working for older ones.
[0]: https://salsa.debian.org/debian/media-types/-/commit/4d6ff19de5720196b40cf65f1173bd9333dfecf9
Fixes: https://tracker.ceph.com/issues/71545
- If you are submitting a …

debian: radosgw: add media-types packages as alternative for mime-support

---

.github/labeler.yml

github: add rgw label for changes in doc/radosgw

---

.github/milestone.yml
doc/dev/release-checklists.rst

pull requests based on the tentacle branch aren't setting the milestone
<details>
- `jenkins test signed` [Jenkins Job](https://jenkins.ceph.com/job/ceph-pr-commits/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-pr-commits/co …

github: add tentacle milestone

---

src/cephadm/cephadmlib/container_lookup.py

This was missed as part of
https://github.com/ceph/ceph/commit/49405967620c9dbb69a1ea4660af46c240fcd298 as this particular bit seems to only cause an issue when you pass in --name to shell and the daemon
you pass to --name is not running. That procedure (stopping the daemon and then passing it's name to shell) is what is used to run tools like ceph-objectstore-tool and ceph-monstore-tool for debugging
Fixes: https://tracker.ceph.com/issues/70989
NOTE: for the tracker, the actual specific issue this change fixes is the one shown in https://tracker.ceph.com/issues/70989#note-2 The original reported issue was fixed by the linked commit
- If you are …

cephadm: don't collect image ids for daemons with no container info

---

doc/mgr/cli_api.rst

Improve the English in doc/mgr/cli_api.rst. Incorporate the changes suggested by Anthony D'Atri in https://github.com/ceph/ceph/pull/63195.
(cherry picked from commit 7722272c35044cd4e735427352cd4cef791091ee) …

squid: doc/mgr: edit cli_api

---

doc/mgr/cli_api.rst

Improve the English in doc/mgr/cli_api.rst. Incorporate the changes suggested by Anthony D'Atri in https://github.com/ceph/ceph/pull/63195.
(cherry picked from commit 7722272c35044cd4e735427352cd4cef791091ee) …

reef: doc/mgr: edit cli_api

---

src/include/cephfs/libcephfs.h

We recently had ABI changes https://github.com/ceph/ceph/pull/62934 with respect to APIs from _chown()_ family which calls for a change in major version. Native users of the library may not have to change their code but expected sizes differ when data type for parameters are changed. However go-ceph, Go bindings for ceph, couldn't build https://github.com/ceph/go-ceph/issues/1119 unless the ABI change is made visible to the consumers of the API. Following the Semantic Versioning [guidelines](https://semver.org/#spec-item-8) we reset minor and patch (extra) versions to 0.
Fixes: https://tracker.ceph.com/issues/71519

libcephfs: Bump API major version

---

.github/milestone.yml
doc/dev/release-checklists.rst

tentacle backport required by release checklist from https://github.com/ceph/ceph/pull/63596 
> [x] add release name to .github/milestone.yml for github actions to automatically add milestone to backports (this commit must be backported to the release branch)
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull-requests/config/definitions/ceph-perf-pull-r …

tentacle: github: add tentacle milestone

---

src/mon/FSCommands.cc

In file included from /home/pdonnell/ceph/src/mds/FSMap.h:31,
from /home/pdonnell/ceph/src/mon/PaxosFSMap.h:20,
from /home/pdonnell/ceph/src/mon/MDSMonitor.h:26,
from /home/pdonnell/ceph/src/mon/FSCommands.cc:17:
/home/pdonnell/ceph/src/mds/MDSMap.h: In member function ‘int FileSystemCommandHandler::set_val(Monitor*, FSMap&, MonOpRequestRef, const cmdmap_t&, std::ostream&, FileSystemCommandHandler::fs_or_fscid, std::string, std::string)’:
/home/pdonnell/ceph/src/mds/MDSMap.h:223:40: warning: ‘fsp’ may be used uninitialized in this function [-Wmaybe-uninitialized]
223 |   bool test_flag(int f) const { return flags & f; }
|                                        ^~~~~
/home/pdonnell/ceph/src/mon/FSCommands.cc:417:21: note: ‘fsp’ was declared here
417 |   const Filesystem* fsp;
| …

mon/FSCommands: avoid unreachable code triggering compiler warning

---

src/rgw/rgw-gap-list

backport tracker: https://tracker.ceph.com/issues/70826
---
backport of https://github.com/ceph/ceph/pull/62524
parent tracker: https://tracker.ceph.com/issues/70680

reef: rgw: fix bug with rgw-gap-list

---

src/common/options/mgr.yaml.in

Improve the "desc" field under the "mgr_data" entry in src/common/options/mgr.yaml.in.
This is a test to determine whether the Jenkins tests can be passed. This test is made after the mystifying failure of
https://github.com/ceph/ceph/pull/62983. …

doc/src/common/options: mgr.yaml.in edit

---

doc/rados/operations/placement-groups.rst

(cherry picked from commit 201e34119ab8628f5c99763212613678ec29dde3)
- Component …

tentacle: doc/rados/operations: Additional improvements to placement-groups.rst

---

doc/start/documenting-ceph.rst

Edit the section "Build the Source" in doc/start/documenting-ceph.rst. Also correct a misuse of the word "presently", which means "in a little while", not "now".
(cherry picked from commit dd66c9e68b3518058382454949021504c65efe4b) …

tentacle: doc/start: edit documenting-ceph.rst

---

doc/mgr/dashboard_plugins/feature_toggles.inc.rst

Follow up on the suggestions made by Anthony D'Atri in https://github.com/ceph/ceph/pull/63367.
- Add "nvmeof" to the list of enabled features.
- Remove an extraneous space.
(cherry picked from commit 6117c4eff3721a995612329cf51c25968371d48d) …

squid: doc/mgr/dashboard_plugins: edit feature_toggles.inc.rst

---

doc/mgr/dashboard_plugins/feature_toggles.inc.rst

Follow up on the suggestions made by Anthony D'Atri in https://github.com/ceph/ceph/pull/63367.
- Add "nvmeof" to the list of enabled features.
- Remove an extraneous space.
(cherry picked from commit 6117c4eff3721a995612329cf51c25968371d48d) …

reef: doc/mgr/dashboard_plugins: edit feature_toggles.inc.rst

---

doc/mgr/telemetry.rst

This commit edits down to the line "Note that telemetry must be on for these commands to take effect.", inclusive. …

doc/mgr: edit telemetry (1 of x)

---

doc/mgr/telemetry.rst

This commit edits the second hundred lines in doc/mgr/telemetry.rst. …

doc/mgr: edit telemetry (2 of x)

---

doc/mgr/telemetry.rst

This commit edits the final part of doc/mgr/telemetry.rst. …

doc/mgr: edit telemetry (4 of x)

---

src/cls/CMakeLists.txt

Just a minor cmake change, can probably be merged on the basis of make check.
<details> …

cls/CMakeLists.txt: find_package Lua for cls_lua

---

src/osd/scrubber/pg_scrubber.cc
src/osd/scrubber/scrub_machine.cc
src/osd/scrubber/scrub_machine.h

Currently, `scrubMachine::get_time_scrubbing()` must access the Session object to compute the scrub duration. But the State data is not externally accessible before its ctor has completed.
As we always happen to try to access that data inside the ctor, this always results in a warning log message.
Here we move `m_session_started_at` into the outer state, simplifying the logic required to access it.
Fixes: https://tracker.ceph.com/issues/64955

osd/scrub: make m_session_started_at at Session state ctor

---

src/CMakeLists.txt
src/common/CMakeLists.txt
src/common/ceph_context.cc
src/common/ceph_context.h
src/crimson/CMakeLists.txt
src/crimson/os/alienstore/CMakeLists.txt
src/global/CMakeLists.txt
src/global/global_init.cc
src/rgw/CMakeLists.txt
src/test/CMakeLists.txt

Previously, Breakpad was being built in its source tree instead of the user-specified build directory, inconsistent with other external projects and potentially causing source tree pollution.
in this change,
- Replace dedicated target for LSS submodule symlink with PATCH_COMMAND Simplifies build process by handling symlink creation during patch phase
- Remove -Wno-array-bounds and similar flags from CFLAGS (breakpad is C++, uses CXXFLAGS)
- Remove compiler-specific flags from LDFLAGS (these are compile-time, not link-time flags)
- Use "BINARY_DIR" as the root directory of the build directory. …

cmake: enable out-of-source build of breakpad

---

doc/mgr/telemetry.rst

Incorporate Anthony D'Atri's suggestions from
https://github.com/ceph/ceph/pull/63739. …

doc/mgr: edit telemetry.rst

---

src/common/ceph_context.cc

backport tracker: https://tracker.ceph.com/issues/70957
---
backport of https://github.com/ceph/ceph/pull/62754
parent tracker: https://tracker.ceph.com/issues/64895

squid: common: CephContext::_refresh_perf_values() checks for null _mempool_perf

---

src/rgw/rgw_op.cc

Fixes: https://tracker.ceph.com/issues/71563
<details> …

rgw/logging: log only object ACls in journal mode

---

src/rgw/driver/dbstore/common/dbstore.cc

Memory leak was detected by AddressSanitizer in dbstore tests. Objects inserted into a static objectmap were not being properly freed when tests completed without explicitly deleting buckets.
The leak occurred because:
- Objects were preserved in a static map after insertion
- Objects were only freed by DB::objectmapDelete() when deleting the corresponding bucket
- In tests, buckets weren't always deleted after insertion, leaving objects allocated
ASan rightly pointed this out:
```
Direct leak of 200 byte(s) in 1 object(s) allocated from:
#0 0x55c420f5274d in operator new(unsigned long) (/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/unittest_dbstore_tests+0x4df74d) (BuildId: c19ed2d2b1ead306fdc59fc311f546a287300010)
#1 0x55c42143cfaf in …
```

rgw/dbstore: free objectmap in DB::Destroy()

---

src/common/options/global.yaml.in

"mon_warn_pg_not_deep_scrubbed_ratio" to the confval definition of that variable. Although this variable contains the string "mon", it is set on the Manager. I have added a note to direct users to set this value on the Manager.
(cherry picked from commit aeef59a50ee31072648ba0c7436b6522137614cd) …

squid: src/common: add guidance for deep-scrubbing ratio warning

---

doc/radosgw/admin.rst
doc/radosgw/cloud-sync-module.rst
doc/radosgw/metrics.rst
doc/radosgw/multisite-sync-policy.rst
doc/radosgw/multisite.rst

Use inline code formatting consistently for command line switches, data, hostnames, etc.
Correctly indent text and child lists in list items. Remove a mid-sentence double spaces.
Capitalize "RGW" and "API" in text.
Remove unordered lists that are just regular text
everywhere else.
Use correct prompt # instead of $ for privileged
commands.
Use line continuation for multi-line example commands instead of render them incorrectly as separate
single-line commands.
Use Title Case in few section header text that
missed it.
multisite.rst: Don't repeat "(RGW)" after "RADOS
Gateway" beyond the first instance in the same
paragraph.
multisite.rst: Change one "multisite" to "multi-site" because all other instances use this spelling (EXCEPT the title of the document??).
multisite.rst: Fix indentation …

squid: doc/radosgw: Improve and more consistent formatting

---

src/ceph-volume/ceph_volume/tests/devices/lvm/test_migrate.py
src/ceph-volume/ceph_volume/tests/util/test_device.py
src/ceph-volume/ceph_volume/util/device.py
src/ceph-volume/ceph_volume/util/disk.py

backport tracker: https://tracker.ceph.com/issues/67289
---
backport of https://github.com/ceph/ceph/pull/58424
parent tracker: https://tracker.ceph.com/issues/61597

reef: ceph-volume: do not convert LVs's symlink to real path

---

doc/rados/operations/stretch-mode.rst

doc/rados/operations: Address suggestions for stretch-mode.rst
(cherry picked from commit 3f5bf8dedd18f2f6d4afc0583be124be879667f2) …

doc/rados/operations: Address suggestions for stretch-mode.rst

---

doc/rados/operations/pools.rst
doc/rbd/rbd-mirroring.rst

Add a note to doc/rbd/rbd-mirroring.rst that directs the reader to set both "site-a" and "site-b" to have the same pool names in the event that rbd throws the error message "failed to import peer bootstrap token".
This information was reported to the Ceph upstream by Petr Tlapa in June of 2025, and credit for its development goes to Petr.
(cherry picked from commit 83345afa898ebc2daf9a18d725447aa0c738af57) …

squid: doc/rbd: add mirroring troubleshooting info

---

doc/rados/operations/pools.rst
doc/rbd/rbd-mirroring.rst

Add a note to doc/rbd/rbd-mirroring.rst that directs the reader to set both "site-a" and "site-b" to have the same pool names in the event that rbd throws the error message "failed to import peer bootstrap token".
This information was reported to the Ceph upstream by Petr Tlapa in June of 2025, and credit for its development goes to Petr.
(cherry picked from commit 83345afa898ebc2daf9a18d725447aa0c738af57) …

tentacle: doc/rbd: add mirroring troubleshooting info

---

doc/rados/operations/pools.rst

Add a link to the instructions for modifying a user's caps for a given pool. Add this link where it makes sense to add it. Add this link where the reader would naturally want to have the link. …

doc/rados: enhance "pools.rst"

---

doc/mgr/telemetry.rst

Edit doc/mgr/telemetry.rst (lines 300-400).
Follow up on the suggestions made by Anthony D'Atri in https://github.com/ceph/ceph/pull/63741 (except for the one about including Lovecraftian lore in the dummy user data in this file). …

doc/mgr: edit telemetry.rst (lines 300-400)

---

doc/rados/operations/user-management.rst

Edit an sentence in the imperative mood so that it matches the general form of imperative sentences immediately preceding commands that contain replaceable portions.
This commit targets only the Squid release branch.
Follows up on https://github.com/ceph/ceph/pull/58235/.
Tracker: https://tracker.ceph.com/issues/66617 …

doc/rados: edit ops/user-management.rst

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/logs/logs.component.scss

mgr/dashboard: Aligned the download and copy buttons in the logs component for a consistent appearance.
Fixes: https://tracker.ceph.com/issues/71539
Signed-off-by: prik73 [prinovac@gmail.com](mailto:prinovac@gmail.com) …

mgr/dashboard: fix alignment of log action buttons

---

src/common/options/mon.yaml.in
src/mon/NVMeofGwMap.cc
src/mon/NVMeofGwMap.h
src/mon/NVMeofGwMon.cc
src/nvmeof/NVMeofGwMonitorClient.cc
src/nvmeof/NVMeofGwMonitorClient.h

fix assert of NVmeofGWMonClient …

fix duplicated entity addr in the map during reboot of several GWs

---

PendingReleaseNotes
doc/rados/operations/user-management.rst
qa/workunits/cephtool/test.sh
src/mon/AuthMonitor.cc
src/mon/MonCommands.h

backport tracker: https://tracker.ceph.com/issues/66618
---
backport of https://github.com/ceph/ceph/pull/58121
parent tracker: https://tracker.ceph.com/issues/66509

reef: mon/AuthMonitor: provide command to rotate the key for a user credential

---

doc/mgr/telemetry.rst

Edit doc/mgr/telemetry.rst (lines 300-400).
Follow up on the suggestions made by Anthony D'Atri in https://github.com/ceph/ceph/pull/63741 (except for the one about including Lovecraftian lore in the dummy user data in this file).
(cherry picked from commit 4587f330e455ca77294c84fd61add5d62f548a60) …

reef: doc/mgr: edit telemetry.rst (lines 300-400)

---

doc/mgr/telemetry.rst

Edit doc/mgr/telemetry.rst (lines 300-400).
Follow up on the suggestions made by Anthony D'Atri in https://github.com/ceph/ceph/pull/63741 (except for the one about including Lovecraftian lore in the dummy user data in this file).
(cherry picked from commit 4587f330e455ca77294c84fd61add5d62f548a60) …

squid: doc/mgr: edit telemetry.rst (lines 300-400)

---

doc/mgr/telemetry.rst

Edit doc/mgr/telemetry.rst (lines 300-400).
Follow up on the suggestions made by Anthony D'Atri in https://github.com/ceph/ceph/pull/63741 (except for the one about including Lovecraftian lore in the dummy user data in this file).
(cherry picked from commit 4587f330e455ca77294c84fd61add5d62f548a60) …

tentacle: doc/mgr: edit telemetry.rst (lines 300-400)
