ceph/ceph

doc/mgr/telemetry.rst

Follow up on the suggestions made by Anthony D'Atri in https://github.com/ceph/ceph/pull/63740.
Make several changes that were not earmarked in that PR, but that nonetheless improve the quality of the English in telemetry.rst.
(cherry picked from commit fc25b1ed12a98eace4c0665a529b69e86fcc9dc5) …

tentacle: doc/mgr: edit telemetry.rst

---

.github/workflows/diff-ceph-config.yml
.github/workflows/scripts/config-diff-post-comment.js
src/script/config-diff/README.md
src/script/config-diff/config_diff.py

The following are some fixes to the ceph configuration diff GH action that was added here: https://github.com/ceph/ceph/pull/63136
In the original PR, we were comparing the HEAD commit of the PR with the latest commit of the PR base (`main` branch of ceph upstream). This resulted in a problem such as this: https://github.com/ceph/ceph/pull/63214#issuecomment-2939195579. Since we were comparing the latest state of the PR with the `main` branch, the script was detecting configuration changes that were not made as part of the PR. This happens in the case when the PR branch is running behind the upstream branch. This is similar to the [two-dot git diff comparision](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about- …

.github/workflow/diff-ceph-config.yml: only detect the configuration changes that were made in the PR

---

doc/rados/operations/cache-tiering.rst

Remove part of a sentence that might have led readers to think that it is a good idea to deploy cache tiering on releases prior to Reef.
This incorporates Anthony D'Atri's suggestion from here: https://github.com/ceph/ceph/pull/63614#discussion_r2116020937
(cherry picked from commit 3618b1bbbb0096a8a08f59aeb6b7436ef9d0c12e) …

squid: doc/rados/ops: edit cache-tiering.rst

---

doc/rados/operations/pools.rst

Add a link to the instructions for modifying a user's caps for a given pool. Add this link where it makes sense to add it. Add this link where the reader would naturally want to have the link.
(cherry picked from commit e4979709dd09d087cf15a314b21be049fbea5e74) …

tentacle: doc/rados: enhance "pools.rst"

---

doc/rados/operations/pools.rst

Add a link to the instructions for modifying a user's caps for a given pool. Add this link where it makes sense to add it. Add this link where the reader would naturally want to have the link.
(cherry picked from commit e4979709dd09d087cf15a314b21be049fbea5e74) …

squid: doc/rados: enhance "pools.rst"

---

doc/rados/operations/pools.rst

Add a link to the instructions for modifying a user's caps for a given pool. Add this link where it makes sense to add it. Add this link where the reader would naturally want to have the link.
(cherry picked from commit e4979709dd09d087cf15a314b21be049fbea5e74) …

reef: doc/rados: enhance "pools.rst"

---

doc/mgr/telemetry.rst

This commit edits the second hundred lines in doc/mgr/telemetry.rst.
(cherry picked from commit f8975b05a6cff674ad5fb6ce93c839ca1856464c) …

squid: doc/mgr: edit telemetry (2 of x)

---

doc/radosgw/s3/bucketops.rst
examples/rgw/boto3/service-2.sdk-extras.json
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/driver/rados/rgw_sal_rados.h
src/rgw/radosgw-admin/radosgw-admin.cc
src/rgw/rgw_bucket_logging.cc
src/rgw/rgw_bucket_logging.h
src/rgw/rgw_rest_bucket_logging.cc
src/rgw/rgw_sal.h
src/rgw/rgw_sal_filter.h
src/rgw/rgw_sal_store.h

Fixes: https://tracker.ceph.com/issues/71219
<details> …

rgw/logging: send flushed object name in API reply

---

doc/radosgw/layout.rst

Move two example CLI command blocks to use a bash prompt block with the correct privileged prompt instead of hardcoded unprivileged prompt.
Don't use the directory "bin/" in command "bin/radosgw-admin" especially when the next commands also don't use it.
Fix 2 instances of double-backtick missing the second backtick that caused the rendered doc to be jumbled.
Do not use _ emphasis _ that renders as underscores, instead use RST syntax for italic for the word.
- Before: https://docs.ceph.com/en/latest/radosgw/layout/
- Rendered PR: https://ceph--63005.org.readthedocs.build/en/63005/radosgw/layout/
- If you are submitting a fix for a stable branch …

doc/radosgw: Promptify CLI commands and fix formatting in layout.rst

---

doc/start/documenting-ceph.rst

Edit the section "Build the Source" in doc/start/documenting-ceph.rst. Also correct a misuse of the word "presently", which means "in a little while", not "now".
(cherry picked from commit dd66c9e68b3518058382454949021504c65efe4b) …

squid: doc/start: edit documenting-ceph.rst

---

src/rgw/driver/posix/rgw_sal_posix.cc

Previously, we had Resource leak in Directory::for_each() where directory streams opened with fdopendir() were never properly closed, causing a 32KB leak per unclosed directory handle.
In this change, we add closedir() call to properly release directory stream resources after enumeration completes.
ASan report:
```
Direct leak of 32816 byte(s) in 1 object(s) allocated from:
#0 0x738387320e15 in malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:67
#1 0x738381383514  (/usr/lib/libc.so.6+0xe3514) (BuildId: 468e3585c794491a48ea75fceb9e4d6b1464fc35)
#2 0x738381383418 in fdopendir (/usr/lib/libc.so.6+0xe3418) (BuildId: 468e3585c794491a48ea75fceb9e4d6b1464fc35)
#3 0x6433e1aefac4 in for_each<rgw::sal::Directory::fill_cache(const DoutPrefixProvider*, optional_yield, …
```

rgw/driver/posix: closedir() to free dir handle

---

qa/crontab/teuthology-cronjobs

Once https://github.com/ceph/ceph-build/pull/2369 merges we should also update the cronjobs definitions.
- Tracker …

qa/crontab/teuthology-cronjobs: Use Crimson flavors

---

doc/mgr/telemetry.rst

This commit edits the third hundred lines in doc/mgr/telemetry.rst.
(cherry picked from commit 3ce61e065121e07e2c37097f1fe6736bdf985e8e) …

squid: doc/mgr: edit telemetry (3 of x)

---

src/rgw/radosgw-admin/radosgw-admin.cc

Probably a result of a refactor …

src: typo in radosgw-admin.cc

---

src/script/build-with-container.py

Oops.
Tested it as best as I could. …

script/build-with-container: add workarounds for older python versions

---

doc/cephadm/services/snmp-gateway.rst
doc/dev/cephfs-mirroring.rst
doc/mgr/telemetry.rst

`doc/cephadm/services/snmp-gateway.rst`:  
Don't use double backticks for links. Makes it a link instead of rendering syntax verbatim.  
Also for consistency add single backticks for links instead of a plain trailing underscore.
- Before: https://docs.ceph.com/en/latest/cephadm/services/snmp-gateway/
- Rendered PR: https://ceph--63920.org.readthedocs.build/en/63920/cephadm/services/snmp-gateway/
```console
/home/docs/checkouts/readthedocs.org/user_builds/ceph/checkouts/63919/doc/cephadm/services/snmp-gateway.rst:5: WARNING: Inline literal start-string without end-string.
```
`doc/dev/cephfs-mirroring.rst`:  
Add missing empty line before preformatted blocks. No change in rendered docs.
- Before: https://docs.ceph.com/en/latest/dev/cephfs-mirroring/
- Rendered PR: …

doc: Fix sphinx warnings and one error

---

doc/cephfs/experimental-features.rst

The "inline data" feature was not removed in Quincy so update deprecation notice to refer to "a future release" instead.
- Before: https://docs.ceph.com/en/latest/cephfs/experimental-features/#inline-data
- Rendered PR: https://ceph--63918.org.readthedocs.build/en/63918/cephfs/experimental-features/#inline-data …

doc/cephfs: Update deprecation notice in experimental-features.rst

---

doc/radosgw/layout.rst

Move two example CLI command blocks to use a bash prompt block with the correct privileged prompt instead of hardcoded unprivileged prompt.
Don't use the directory "bin/" in command "bin/radosgw-admin" especially when the next commands also don't use it.
Fix 2 instances of double-backtick missing the second backtick that caused the rendered doc to be jumbled.
Do not use _emphasis_ that renders as underscores, instead use RST syntax for italic for the word.
(cherry picked from commit 6783245e98be4bd83be754fa39353d268e25b896) …

squid: doc/radosgw: Promptify CLI commands and fix formatting in layout.rst

---

qa/tasks/s3a_hadoop.py

all rgw/hadoop-s3a jobs started failing because the hard-coded maven version 3.9.9 disappeared. default to 3.9.10
Fixes: https://tracker.ceph.com/issues/71584
<details>
- `jenkins test signed` [Jenkins Job](https://jenkins.ceph.com/job/ceph-pr-commits/) | …

qa/rgw: bump maven version in hadoop task to resolve 404 Not Found

---

.gitmodules

The version of the opentelemetry-cpp we currently use has a missing include in the Jaeger exporter.
Newer versions remove the Jaeger exporter entirely.
While upgrading sometime would be good, it doesn't have to happen right now.
Fixes: https://tracker.ceph.com/issues/62804 …

build: Fix opentelemetry-cpp build failure on Noble

---

PendingReleaseNotes
src/rgw/rgw_arn.cc
src/rgw/rgw_common.cc
src/rgw/rgw_common.h
src/rgw/rgw_iam_policy.cc
src/test/rgw/test_rgw_iam_policy.cc

backport tracker: https://tracker.ceph.com/issues/70596
---
backport of https://github.com/ceph/ceph/pull/62285
parent tracker: https://tracker.ceph.com/issues/70481

squid: rgw/iam: add policy evaluation for Arn-based Conditions

---

src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts

- changes from 'Smb' to 'SMB
Fixes https://tracker.ceph.com/issues/71538
Before:
After: …

mgr/dashboard: Fix capitalization in SMB

---

container/Containerfile
container/build.sh
qa/config/crimson_qa_overrides.yaml
qa/suites/crimson-rados-experimental/thrash/deploy/ceph.yaml
qa/suites/crimson-rados/basic/deploy/ceph.yaml
qa/suites/crimson-rados/perf/deploy/ceph.yaml
qa/suites/crimson-rados/rbd/deploy/ceph.yaml
qa/suites/crimson-rados/singleton/all/osd-backfill.yaml
qa/suites/crimson-rados/singleton/all/osd-pg-splitting.yaml
qa/suites/crimson-rados/thrash/deploy/ceph.yaml
qa/suites/crimson-rados/thrash_seastore_radosbench/deploy/ceph.yaml
qa/suites/crimson-rados/thrash_simple/deploy/ceph.yaml
qa/tasks/ceph.py
qa/tasks/cephadm.py
qa/tasks/rook.py

flavor crimson is deprecated, let the flavor to be set when passing --flavor/-f when scheduling jobs instead.
- …

qa/suites/crimson-rados: Accommodate to new crimson flavors

---

qa/standalone/scrub/osd-scrub-test.sh
src/osd/scrubber/osd_scrub_sched.cc
src/osd/scrubber/osd_scrub_sched.h
src/osd/scrubber/pg_scrubber.cc
src/osd/scrubber/pg_scrubber.h
src/osd/scrubber/scrub_machine.cc
src/osd/scrubber/scrub_machine.h
src/osd/scrubber/scrub_machine_lstnr.h

Fixes: https://tracker.ceph.com/issues/66988
backport of 50199

reef: scrub: use a generic interface for scheduling timer based events

---

doc/mgr/telemetry.rst

This commit edits down to the line "Note that telemetry must be on for these commands to take effect.", inclusive.
(cherry picked from commit b3e2ce500f3903a039b9ad442a3d4f4ffa9492e4) …

tentacle: doc/mgr: edit telemetry (1 of x)

---

src/osd/osd_types.h

backport tracker: https://tracker.ceph.com/issues/71222
---
backport of https://github.com/ceph/ceph/pull/62705
parent tracker: https://tracker.ceph.com/issues/45702

reef: osd_types: Restore new_object marking for delete missing entries

---

src/rgw/rgw_op.cc

Since storage class is cloud tier s3 cp of temporary object was failing.
Fixes: https://tracker.ceph.com/issues/71121
<details>
- …

rgw/cloud-restore: allow copy of temporary object

---

qa/suites/nvmeof/basic/workloads/nvmeof_initiator.yaml
qa/suites/nvmeof/basic/workloads/nvmeof_mtls.yaml
qa/suites/nvmeof/basic/workloads/nvmeof_namespaces.yaml
qa/suites/nvmeof/basic/workloads/nvmeof_scalability.yaml
qa/suites/nvmeof/thrash/gateway-initiator-setup/10-subsys-90-namespace-no_huge_pages.yaml
qa/suites/nvmeof/thrash/gateway-initiator-setup/120-subsys-8-namespace.yaml
qa/suites/nvmeof/thrash/gateway-initiator-setup/16-subsys-4-namespace.yaml
qa/suites/nvmeof/thrash/gateway-initiator-setup/2-subsys-8-namespace.yaml
qa/suites/nvmeof/thrash/thrashers/nvmeof_mon_thrash.yaml
qa/suites/nvmeof/thrash/thrashers/nvmeof_thrash.yaml
qa/suites/nvmeof/thrash/workloads/fio.yaml
qa/tasks/nvmeof.py
qa/workunits/nvmeof/basic_tests.sh
qa/workunits/nvmeof/fio_test.sh
qa/workunits/nvmeof/mtls_test.sh
qa/workunits/nvmeof/scalability_test.sh

This is because teuthology machines are not
powerful enough to support fio on huge amount of
devices.
This commit also adds CEPHADM_STRAY_DAEMON and
CEPHADM_DAEMON_PLACE_FAIL to thrasher ignorelist.
Fixes: https://tracker.ceph.com/issues/70927 …

qa: reduce nvmeof thrasher fio to 32 devices from 200 

---

src/common/options/osd.yaml.in

Improve the English in the "desc" field of the
"osd_deep_scrub_interval_cv" variable, as suggested by Anthony D'Atri in https://github.com/ceph/ceph/pull/63490#discussion_r2124893516. …

doc/src: edit osd.yaml.in (osd_deep_scrub_interval_cv)

---

src/mgr/PyModule.cc

mgr: PyModule memory leaks fix

---

src/rgw/driver/daos/rgw_sal_daos.cc
src/rgw/driver/motr/rgw_sal_motr.cc
src/rgw/driver/rados/rgw_cr_rados.cc
src/rgw/driver/rados/rgw_lc_tier.cc
src/rgw/driver/rados/rgw_putobj_processor.cc
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/driver/rados/rgw_sal_rados.h
src/rgw/rgw_op.cc
src/rgw/rgw_rest_s3.cc
src/rgw/rgw_rest_swift.cc
src/rgw/rgw_sal.h
src/rgw/rgw_sal_dbstore.cc
src/rgw/rgw_sal_filter.h
src/rgw/rgw_sal_store.h

backport tracker: https://tracker.ceph.com/issues/71176
---
backport of https://github.com/ceph/ceph/pull/62903
parent tracker: https://tracker.ceph.com/issues/70992

tentacle: rgw: prefetch data from versioned object instance head

---

qa/workunits/rgw/test_rgw_datacache.py
src/rgw/driver/rados/rgw_d3n_datacache.cc
src/rgw/rgw_d3n_cacherequest.h

backport tracker: https://tracker.ceph.com/issues/71202
---
backport of https://github.com/ceph/ceph/pull/62516
parent tracker: https://tracker.ceph.com/issues/70333

tentacle: rgw/d3n: store cached objects using hash digest

---

src/common/options/osd.yaml.in
src/osd/scrubber/scrub_machine.cc

Increase the two timeouts associated with replica responses to scrub requests.
This change addresses cases where a cluster event—such as an OSD in the active set going down—triggers re-peering. In such scenarios, scrub requests may time out before a new replica interval is established. While this does not cause data loss or crashes, it does result in log warnings and test failures.
Fixes: https://tracker.ceph.com/issues/68698

reef: osd/scrub: allow longer waits for replicas to respond

---

doc/rados/operations/health-checks.rst

Fix missing empty line before an unordered list that caused it to be rendered wrong.
Also, the sentences in each list item start with a capital case letter so add the missing full stop at the end.
(cherry picked from commit 0dc5f4632cb3a83cfdd9985cadb9ae953949a5b8) …

squid: doc/rados/operations: Fix unordered list in health-checks.rst

---

doc/cephfs/experimental-features.rst

The "inline data" feature was not removed on Quincy so update deprecation notice to refer to "a future release" instead.
(cherry picked from commit c15f7e414d2145005974a7ddb385a9b76bfec101) …

tentacle: doc/cephfs: Update deprecation notice in experimental-features.rst

---

doc/cephfs/experimental-features.rst

The "inline data" feature was not removed on Quincy so update deprecation notice to refer to "a future release" instead.
(cherry picked from commit c15f7e414d2145005974a7ddb385a9b76bfec101) …

squid: doc/cephfs: Update deprecation notice in experimental-features.rst

---

doc/cephfs/experimental-features.rst

The "inline data" feature was not removed on Quincy so update deprecation notice to refer to "a future release" instead.
(cherry picked from commit c15f7e414d2145005974a7ddb385a9b76bfec101) …

reef: doc/cephfs: Update deprecation notice in experimental-features.rst

---

src/rgw/rgw-gap-list

backport tracker: https://tracker.ceph.com/issues/70827
---
backport of https://github.com/ceph/ceph/pull/62524
parent tracker: https://tracker.ceph.com/issues/70680

squid: rgw: fix bug with rgw-gap-list

---

src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/rgw_op.cc
src/rgw/rgw_sal_dbstore.cc

backport tracker: https://tracker.ceph.com/issues/70171
---
backport of https://github.com/ceph/ceph/pull/56583
parent tracker: https://tracker.ceph.com/issues/70115

reef: rgw: fix to correctly store updated attrs in backend store after erasing an attr/attrs for delete ops on a bucket.

---

PendingReleaseNotes
src/rgw/rgw_arn.cc
src/rgw/rgw_common.cc
src/rgw/rgw_common.h
src/rgw/rgw_iam_policy.cc
src/test/rgw/test_rgw_iam_policy.cc

backport tracker: https://tracker.ceph.com/issues/70595
---
backport of https://github.com/ceph/ceph/pull/62285
parent tracker: https://tracker.ceph.com/issues/70481

reef: rgw/iam: add policy evaluation for Arn-based Conditions

---

src/rgw/driver/rados/rgw_rados.cc
src/rgw/rgw_quota.cc
src/rgw/rgw_quota.h

Versioned buckets require more keys per object. So influence the calculation of whether resharding is needed by using a lower max_objs_per_shard value for versioned buckets.
Note: this code is a re-implementation of https://github.com/ceph/ceph/pull/60403, which couldn't be trivially duplicated due to significant underlying code changes.
Fixes: https://tracker.ceph.com/issues/70375 …

reef: rgw: trigger resharding of versioned buckets sooner

---

qa/suites/rgw/verify/tasks/rados-pool-quota.yaml
qa/workunits/rgw/run-rados-pool-quota.sh
qa/workunits/rgw/test_rgw_rados_pool_quota.py
src/rgw/driver/rados/rgw_cr_rados.cc
src/rgw/driver/rados/rgw_gc.cc
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_tools.cc
src/rgw/rgw_common.cc
src/rgw/rgw_rest.cc

backport tracker: https://tracker.ceph.com/issues/70265
---
backport of https://github.com/ceph/ceph/pull/61650
parent tracker: https://tracker.ceph.com/issues/69723

reef:  rgw/rados: enable object deletion at rados pool quota

---

qa/suites/rgw/multisite/overrides.yaml
src/rgw/rgw_auth.cc
src/rgw/rgw_auth.h
src/rgw/rgw_auth_s3.h
src/rgw/rgw_rest_s3.cc
src/test/rgw/rgw_multi/conn.py
src/test/rgw/rgw_multi/multisite.py
src/test/rgw/rgw_multi/tests.py
src/test/rgw/rgw_multi/zone_cloud.py
src/test/rgw/rgw_multi/zone_es.py
src/test/rgw/rgw_multi/zone_rados.py

backport tracker: https://tracker.ceph.com/issues/71113
---
backport of https://github.com/ceph/ceph/pull/56576
parent tracker: https://tracker.ceph.com/issues/71112

squid: rgw/sts: correcting authentication in case s3 ops are directed to a primary from secondary after  assumerole.

---

src/rgw/driver/rados/rgw_data_sync.cc
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_sync.cc
src/rgw/rgw_coroutine.cc
src/rgw/rgw_rest_conn.h

Fixes: http://tracker.ceph.com/issues/71337 …

rgw/multisite: change HTTP error handling from EIO to ERR_INTERNAL_ERROR

---

src/rgw/rgw_asio_frontend.cc

Backport https://github.com/ceph/ceph/pull/58378 to squid.
The original PR had no tracker -- none here either.

squid: rgw: Changed discard buffer size

---

src/test/common/CMakeLists.txt

unittest_fault_injector includes death tests for InjectAbort coverage, and death tests don't play nicely with threads. the unit-main target provides a main() function that initializes a g_ceph_context and starts its associated threads. omit unit-main to prevent the log thread from starting
Fixes: https://tracker.ceph.com/issues/71600
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job …

test/common: unittest_fault_injector omits unit-main target

---

src/rgw/rgw_rest_oidc_provider.cc

backport tracker: https://tracker.ceph.com/issues/70969
---
backport of https://github.com/ceph/ceph/pull/62819
parent tracker: https://tracker.ceph.com/issues/70926

squid: rgw/iam: correcting the caps for OIDC Provider for a user.

---

src/crimson/os/seastore/async_cleaner.cc
src/crimson/os/seastore/async_cleaner.h

At present, the trim_dirty starts and stops at the same threshold *target_dirty_bytes*, which leads to very frequent *trim_dirty* operations that further invalidate transactions.
We've observed that long read transactions kept being invalidated by *trim_dirty*, which led to starvations.
Fixes: https://tracker.ceph.com/issues/71443 …

crimson/os/seastore/async_cleaner: set different threshold for starting and stopping trimming dirty

---

src/os/bluestore/Compression.cc

Backport of: https://github.com/ceph/ceph/pull/63373
Fixes: https://tracker.ceph.com/issues/71531 …

tentacle: os/bluestore/compression: Fix Estimator::split_and_compress

---

qa/suites/orch/cephadm/smb/tasks/deploy_smb_basic.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_domain.yaml
src/pybind/mgr/smb/handler.py

-  Inorder to support Microsoft Management Console (MMC) plugin feature, ceph manager must handle all fields supported by `add share command` and related smb.conf options.
Added "comment" and "max connections" entries to the Samba configuration generated by the Ceph Manager module. These fields are required for MMC integration and will be made configurable in a future update. …

mgr/smb: Add new configs to share definition

---

CMakeLists.txt
cmake/modules/FindMake.cmake
src/CMakeLists.txt
src/rgw/CMakeLists.txt

Since upgrading minimum CMake version to 3.22.1 (commit 469d82a1f387f342797636fdfff84f570b22f928), we can now use find_program(REQUIRED) which was introduced in CMake 3.18.
This change replaces manual FATAL_ERROR checks with the REQUIRED option and adds it to programs that are actually needed during the build. This ensures the build fails early during configuration rather than later during compilation when missing programs are invoked.
Changes:
- Replace find_program() + message(FATAL_ERROR) patterns with REQUIRED
- Add REQUIRED to programs that are used during build but previously had no error checking
Reference: https://cmake.org/cmake/help/latest/command/find_program.html …

cmake: use find_program(REQUIRED) to fail early on missing programs

---

src/mds/CInode.cc

Fix test instance generation for InodeStoreBare and InodeStore to properly set the mode field to S_IFLNK for symlink inodes.
Previously, generated test instances with symlink inodes had unset mode fields, creating inconsistent data. This issue was masked because ceph-dencoder reused existing instances during encode/decode consistency tests, leaving stale values intact.
The problem would surface when check-generated.sh and readable.sh allocate fresh instances for decoding tests, as the missing mode field would cause decode/encode inconsistencies.
This change fixes generate_test_instances() to set the mode field to S_IFLNK for symlink inodes, creating valid InodeStore and InodeStoreBare instances with consistent field values for proper encode/decode testing. …

mds: generate symlink inode with correct mode

---

qa/suites/fs/mirror/overrides/ignorelist_health.yaml
qa/tasks/cephfs/test_mirroring.py
src/client/Client.cc
src/client/Client.h
src/common/ceph_strings.cc
src/common/options/mds-client.yaml.in
src/common/options/mds.yaml.in
src/include/ceph_fs.h
src/include/cephfs/libcephfs.h
src/libcephfs.cc
src/mds/MDCache.cc
src/mds/MDCache.h
src/mds/Server.cc
src/mds/Server.h
src/mds/cephfs_features.cc
src/mds/cephfs_features.h
src/mds/mdstypes.cc
src/mds/mdstypes.h
src/test/libcephfs/snapdiff.cc
src/tools/cephfs_mirror/PeerReplayer.cc
src/tools/cephfs_mirror/PeerReplayer.h
src/tools/rados/rados.cc

https://tracker.ceph.com/issues/70585
https://tracker.ceph.com/issues/70584
https://tracker.ceph.com/issues/70392
- …

squid: integrate blockdiff with cephfs-mirror daemon

---

src/client/Client.h

Commit 1210ddf7a ("Client: Add non-blocking helper classes") introduced Client::C_Read_Finisher Context object for async READ operations, but it has a read-after-free bug which may cause memory leak when calling libcephf's non-blocking ceph_ll_nonblocking_readv_writev API with async READ:
ceph_ll_nonblocking_readv_writev (READ)
Client::ll_preadv_pwritev
...
Client::_read_async
Context::complete
Client::CRF_iofinish::complete
Client::CRF_iofinish::finish
CRF->finish_io()
Client::C_Read_Finisher::finish_io
...
delete this; // frees CRF_iofinish->CRF
if (CRF->iofinished) // use-after-free of CRF
delete this; // may not get here
A possible memory leak depends on timing and race with other thread allocation which alters the memory address of CRF->iofinished to false, thus skipping the last …

client: fix memory leak in Client::CRF_iofinish::complete

---

src/client/Client.cc

After the asynchronous execution context is woken up when waiting for Fb caps reference to be released.
Fixes: http://tracker.ceph.com/issues/71510 …

client: asynchronous fsync can decrement request ref twice

---

debian/ceph-base.install
debian/ceph-common.install
debian/ceph-exporter.install
debian/ceph-fuse.install
debian/ceph-immutable-object-cache.install
debian/ceph-mds.install
debian/ceph-mgr.install
debian/ceph-mon.install
debian/ceph-osd.install
debian/ceph-volume.install
debian/cephfs-mirror.install
debian/radosgw.install
debian/rbd-mirror.install

Ubuntu changed the systemd unit directory location between releases:
- Jammy (22.04): /lib/systemd/system
- Noble (24.04): /usr/lib/systemd/system
To maintain compatibility across both versions, update .install files to use brace expansion pattern {usr/,}lib/systemd/system/<service>.
This pattern works because dh_install uses bsd_glob() with GLOB_CSH flags, which expands braces and matches files in both locations depending on where CMakeLists.txt actually installed them.
Fixes installation issues when building packages on Noble while maintaining backward compatibility with Jammy builds. …

deb: use glob match to support systemd unit dir changes

---

src/mds/Beacon.cc

backport tracker: https://tracker.ceph.com/issues/68916
---
backport of https://github.com/ceph/ceph/pull/60325
parent tracker: https://tracker.ceph.com/issues/68759

reef: mds/Beacon: wake up the thread in shutdown()

---

src/mds/Server.cc

backport tracker: https://tracker.ceph.com/issues/69555
---
backport of https://github.com/ceph/ceph/pull/60889
parent tracker: https://tracker.ceph.com/issues/69059

reef: mds: Fix invalid access of mdr->dn[0].back()

---

doc/cephfs/snap-schedule.rst
src/mon/FSCommands.cc
src/pybind/mgr/snap_schedule/fs/schedule_client.py
src/pybind/mgr/snap_schedule/module.py
src/pybind/mgr/volumes/fs/operations/volume.py

backport tracker: https://tracker.ceph.com/issues/69354
---
backport of https://github.com/ceph/ceph/pull/55145
parent tracker: https://tracker.ceph.com/issues/63999

reef: mgr/snap_schedule: handle volume delete

---

doc/man/8/CMakeLists.txt
doc/man/8/rgw-gap-list.rst

(cherry picked from commit 12eb87463cdf952b9d16eac899f1ca40670ca2bc)
- Component …

squid: doc/rgw: add man documentation for the rgw-gap-list tool

---

PendingReleaseNotes
doc/rados/configuration/mon-config-ref.rst
doc/rados/operations/monitoring.rst
qa/standalone/mon/availability.sh
src/common/options/mon.yaml.in
src/mon/MgrStatMonitor.cc
src/mon/MgrStatMonitor.h
src/mon/OSDMonitor.cc

This PR allows users to disable tracking availability feature. For the same it adds a new config option to enable/disable tracking availability
score. This config option can be modified dynamically at runtime as well.
When the feature is disabled, the score is preserved and not updated. We only start updating the score when the feature is turned on. History is preserved not cleared. 
To enable tracking availability score, we can run the
following command:
```
ceph config set mon enable_availability_tracking true
```
By default, tracking availability score is enabled (as discussed in the RADOS call with the team).
To disable tracking availability score:
```
ceph config set mon enable_availablity_tracking false
```
Updated docs: 
* …

mon: add config option to toggle availability score feature

---

ceph.spec.in

Introduced in https://github.com/ceph/ceph/pull/62749 Centos builds fail with:
```
error: Installed (but unpackaged) file(s) found:
/usr/share/man/man8/rgw-gap-list.8.gz
RPM build errors:
Installed (but unpackaged) file(s) found:
/usr/share/man/man8/rgw-gap-list.8.gz
```
(cherry picked from commit 8d0ec7666be7c7eeced525b5772c6be973f54a25) …

squid: ceph.spec.in: add man/rgw-gap-list

---

doc/dev/development-workflow.rst

Update the link to the backporter manual, in
doc/dev/development-workflow.rst. Laura Flores requested this change on 04 Dec 2024.
(cherry picked from commit c4868ff2d1e4257ae081b51a5cdc87313e01e17c) …

reef: doc/dev: update link to backporter manual

---

doc/dev/development-workflow.rst

Update the link to the backporter manual, in
doc/dev/development-workflow.rst. Laura Flores requested this change on 04 Dec 2024.
(cherry picked from commit c4868ff2d1e4257ae081b51a5cdc87313e01e17c) …

squid: doc/dev: update link to backporter manual

---

src/common/options/osd.yaml.in

Improve the English in the "desc" field of the
"osd_deep_scrub_interval_cv" variable, as suggested by Anthony D'Atri in https://github.com/ceph/ceph/pull/63490#discussion_r2124893516.
(cherry picked from commit 32cd44300882947310d2419279fe7f950ddac17b) …

squid: doc/src: edit osd.yaml.in (osd_deep_scrub_interval_cv)

---

doc/rados/operations/cache-tiering.rst

Strengthen the warning against deploying cache tiering in releases after Reef. This follows up on Anthony D'Atri's request in https://github.com/ceph/ceph/pull/63465.
(cherry picked from commit f4de34f4bdbc7b3930afd8c034064675640df202) …

reef: doc/rados/operations: edit cache-tiering.rst

---

doc/rados/operations/placement-groups.rst

(cherry picked from commit 201e34119ab8628f5c99763212613678ec29dde3)
- Component …

squid: doc/rados/operations: Additional improvements to placement-groups.rst

---

doc/cephadm/certmgr.rst

Wrong path was passed to automodule and no documentation was generated. Use the right file name.
One of the Sphinx WARNINGs, work will continue to fix all these.
```console
WARNING: autodoc: failed to import module 'certmgr' from module 'mgr.cephadm'; the following exception was raised:
No module named 'mgr.cephadm.certmgr'
``` …

doc/cephadm: Fix automodule generation in certmgr.rst

---

.github/workflows/scripts/config-diff-post-comment.js

Currently, we use the "Check ceph config" CI check to remind users about any configuration changes that were detected in the PR. There's no easy way for the script to detect if the relevant docuemtations has been updated for the config change that was detected.
Users might get confused to still see the CI check failing even after updating the relevant docs. We update the text message to help diffuse the confusion. If the users will still like to see the CI check go green, they can comment `/config check ok` and re-run the failed test.
This will be removed, once we trasnform the "Check ceph config" CI check to be a required check.
- If you are …

.github/workflows/config-diff-post-comments.js: introduce "/config check ok" command

---

src/osd/scrubber/pg_scrubber.cc
src/osd/scrubber/scrub_machine.cc
src/osd/scrubber/scrub_machine.h

ScrubMachine::get_time_scrubbing() must access the Session object to compute the scrub duration. But the State data is not externally accessible before its ctor has completed.
As we always happen to try to access that data inside the ctor, this always results in a warning log message.
Here we move m_session_started_at into the outer state, simplifying the logic required to access it.
Fixes: https://tracker.ceph.com/issues/71586
Original tracker: https://tracker.ceph.com/issues/64955
Backport of https://github.com/ceph/ceph/pull/63758
(cherry picked from commit 38057ce2c14ca9a6b81617399480510fb0eae951)

tentacle: osd/scrub: move m_session_started_at out of Session ctor

---

doc/radosgw/admin.rst

Clarify behavior of bucket and uid flags when setting a quota with quota-scope=bucket.
(cherry picked from commit d5c7b4d62c71ca2a57b7d9a552eae03f0f620cef) …

tentacle: doc/radosgw/admin.rst: explain bucket and uid flags for bucket quota

---

doc/radosgw/admin.rst

Clarify behavior of bucket and uid flags when setting a quota with quota-scope=bucket.
(cherry picked from commit d5c7b4d62c71ca2a57b7d9a552eae03f0f620cef) …

squid: doc/radosgw/admin.rst: explain bucket and uid flags for bucket quota

---

qa/config/rados.yaml
qa/suites/rados/monthrash/ceph.yaml
qa/tasks/mon_thrash.py
src/msg/async/ProtocolV2.cc
src/vstart.sh

**Problem:**
```
When a monitor daemon (e.g., mon.c) is killed and restarts, its
attempt to re-establish a session with a peer (mon.a) is incorrectly
rejected. This happens because mon.a retains stale connection state,
including a higher peer_global_seq, from the previous session.
When the newly restarted mon.c sends a ClientIdentFrame with a fresh
client_cookie and a low global_seq (e.g., 1), mon.a compares this
against the old connection’s peer_global_seq (e.g., 61) and mistakenly
concludes that the connection is stale. As a result, mon.a terminates
the incoming connection from mon.c, delaying session recovery and
triggering a transient MON_NETSPLIT warning. The connection is only
recovered once mon.a's backoff timer expires and it initiates a new
connection to mon.c OR when mon.c tries …
```

[DNM] ProtocolV2: make handle_existing_connection check for cookie mismatch first

---

src/pybind/mgr/diskprediction_local/predictor.py

Currently on python 3.12 mypy detects one of the variables used in the expression as an zero-element tuple. This module is not getting a lot of attention so I'm doing the bare minimum to stop the tests from failing here and silencing mypy with a magic comment. …

pybind/mgr: disable mypy error in diskprediction_local module

---

src/cephadm/cephadm.py

Backport of https://github.com/ceph/ceph/pull/62733
<details> …

squid: cephadm: check "ceph_device_lvm" field instead of "ceph_device" during zap

---

src/test/fs/CMakeLists.txt

Avoids:
FAILED: bin/ceph_test_trim_caps
...
undefined reference to symbol '_ZNSt15basic_streambufIcSt11char_traitsIcEE8overflowEi@@GLIBCXX_3.4'
Fixes: https://tracker.ceph.com/issues/71658
<details> …

test/fs/CMakeLists.txt: add ceph-common to ceph_test_trim_caps and ceph_test_ino_release_cb

---

src/rgw/rgw_aio.h

std::aligned_storage_t was deprecated in C++23, to be prepared for it, let's use alignas for the same behavior. because the 3 * 8 (with LP64 data model) is not power-of-2, while `alignas()` requires an alignment of power of 2. so we use `std::bit_ceil()` to calculate the minimum alignment greater or equal to this number. …

rgw: avoid using std::aligned_storage_t

---

src/crimson/osd/lsan_suppressions.cc
src/include/function2.hpp
src/osd/ReplicatedBackend.cc

Introduced recently in https://github.com/ceph/ceph/pull/60890/commits/b92c919fdb94dc1a284ed9b24d0b4929afa15b7e. _NDEBUG is a typo for NDEBUG. Possibly confused with _DEBUG which is a Visual Studio concept. …

src: fix NDEBUG typo

---

src/crimson/os/seastore/cache.h

Fixes: https://tracker.ceph.com/issues/71719 …

crimson/os/seastore/cache: fix inappropriate lambda by-reference captures in get_extent_viewable_by_trans()

---

src/tools/erasure-code/ceph-erasure-code-tool.cc

The erasure code tool has been updated to work with the new EC, the do_encode function which enables the encode option of the tool has a bug which stops the parity shards being generated:
```
(venv-3.12) [root@connorfaukibmcom-san-motoko-centos9base2025010615010000 build]# ceph-erasure-code-tool encode k=4,m=2,technique=reed_sol_van,plugin=jerasure,w=8 4096 0,1,2,3,4,5 /tmp/ec/obj-no-fix
(venv-3.12) [root@connorfaukibmcom-san-motoko-centos9base2025010615010000 build]# ls /tmp/ec/obj-no-fix*
/tmp/ec/obj-no-fix  /tmp/ec/obj-no-fix.0  /tmp/ec/obj-no-fix.1    /tmp/ec/obj-no-fix.2  /tmp/ec/obj-no-fix.3
```
Here an object of 4 shards should be encoded to produce 4 data shards + 2 parity shards, but only the data shards are produced by the tool.
This happens because the parity buffers have not …

tools/ceph-erasure-code-tool: Fix issue stopping parity shards being generated when running encode.

---

doc/radosgw/dynamicresharding.rst

Make reference to config section a hyperlink.
Capitalization consistency: use title case in section titles, fix two invalid capitalizations in text.
Promptify CLI example commands.
A JSON key-value pair is a "property" and not an "object".
Use an ordered list instead of inline code with hardcoded list numbers.
Use the American "canceled" (majority of occurrences in doc/) instead of "cancelled".
Use admonitions instead of spelling out "Note:".
Clarify language on sharding cleanup for multisite.
Format JSON keys as inline code.
Indent example JSON output from radosgw-admin correctly (same as real output) with 4 spaces.
Use colon instead of full stop at the end of text that describes the following example command. Move admonition to after such example command. …

tentacle: doc/radosgw: Cosmetic improvements in dynamicresharding.rst

---

doc/radosgw/dynamicresharding.rst

Make reference to config section a hyperlink.
Capitalization consistency: use title case in section titles, fix two invalid capitalizations in text.
Promptify CLI example commands.
A JSON key-value pair is a "property" and not an "object".
Use an ordered list instead of inline code with hardcoded list numbers.
Use the American "canceled" (majority of occurrences in doc/) instead of "cancelled".
Use admonitions instead of spelling out "Note:".
Clarify language on sharding cleanup for multisite.
Format JSON keys as inline code.
Indent example JSON output from radosgw-admin correctly (same as real output) with 4 spaces.
Use colon instead of full stop at the end of text that describes the following example command. Move admonition to after such example command. …

squid: doc/radosgw: Cosmetic improvements in dynamicresharding.rst

---

doc/radosgw/dynamicresharding.rst

Make reference to config section a hyperlink.
Capitalization consistency: use title case in section titles, fix two invalid capitalizations in text.
Promptify CLI example commands.
A JSON key-value pair is a "property" and not an "object".
Use an ordered list instead of inline code with hardcoded list numbers.
Use the American "canceled" (majority of occurrences in doc/) instead of "cancelled".
Use admonitions instead of spelling out "Note:".
Clarify language on sharding cleanup for multisite.
Format JSON keys as inline code.
Indent example JSON output from radosgw-admin correctly (same as real output) with 4 spaces.
Use colon instead of full stop at the end of text that describes the following example command. Move admonition to after such example command. …

reef: doc/radosgw: Cosmetic improvements in dynamicresharding.rst

---

src/os/bluestore/bluefs_types.cc
src/test/objectstore/test_bluefs.cc

The new code on BlueFS envelope mode has uncovered decade old bug in bluefs_fnode_t::seek.
When offset is larger than 2^63 the function logic thought valid extent has been found.
Fixes: https://tracker.ceph.com/issues/71532 …

tentacle: os/bluestore: Fix bluefs_fnode_t::seek 

---

src/rgw/driver/daos/rgw_sal_daos.cc
src/rgw/driver/motr/rgw_sal_motr.cc
src/rgw/driver/rados/rgw_cr_rados.cc
src/rgw/driver/rados/rgw_lc_tier.cc
src/rgw/driver/rados/rgw_object_expirer_core.cc
src/rgw/driver/rados/rgw_putobj_processor.cc
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/driver/rados/rgw_sal_rados.h
src/rgw/rgw_op.cc
src/rgw/rgw_rest_s3.cc
src/rgw/rgw_rest_swift.cc
src/rgw/rgw_sal.h
src/rgw/rgw_sal_dbstore.cc
src/rgw/rgw_sal_filter.h
src/rgw/rgw_sal_store.h

backport tracker: https://tracker.ceph.com/issues/71177
---
backport of https://github.com/ceph/ceph/pull/62903
parent tracker: https://tracker.ceph.com/issues/70992

squid: rgw: prefetch data from versioned object instance head

---

src/rgw/driver/rados/rgw_d3n_datacache.cc

backport tracker: https://tracker.ceph.com/issues/71421
---
backport of https://github.com/ceph/ceph/pull/63352
parent tracker: https://tracker.ceph.com/issues/64835

squid: rgw/d3n: fix valgrind invalid read during exit

---

src/rgw/rgw_rest.h
src/rgw/rgw_rest_s3.cc

backport tracker: https://tracker.ceph.com/issues/71375
---
backport of https://github.com/ceph/ceph/pull/63151
parent tracker: https://tracker.ceph.com/issues/71229

squid: rgw/rgw_rest: determine the domain uri prefix by rgw_transport_is_secure

---

src/rgw/driver/rados/rgw_rados.cc

When we have a versioned bucket, we reduce max_objs_per_shard by a factor of 3 to account for the extra bucket index entries required in such buckets. And during debugging, we may want to induce early resharding by setting max_objs_per_shard to an artificially low value. Combined, that math could result in max_objs_per_shard with a value of 0 that would cause a division by zero crash. This fixes that.
Fixes: https://tracker.ceph.com/issues/71423 …

rgw: make sure max_objs_per_shard is appropriate in debugging scenarios

---

src/mgr/MgrOpRequest.h

Fix use-after-free issue with MgrOpRequest.
Fixes: https://tracker.ceph.com/issues/70618 …

mgr: avoid explicit dropping of ref

---

src/common/options/osd.yaml.in
src/osd/scrubber/pg_scrubber.cc

'osd_scrub_auto_repair_num_errors' limits the number of damaged objects that we will try to auto-repair during a scrub. Its documentation referred to "number of errors", which did not fit the implementation.
Original tracker: https://tracker.ceph.com/issues/71754
Backport tracker: https://tracker.ceph.com/issues/71770
Backported from https://github.com/ceph/ceph/pull/64048
(cherry picked from commit 680b58ffd0bf5b213ec525f8d783297fb0b14343)

tentacle: osd/scrub: clarify that osd_scrub_auto_repair_num_errors counts objects

---

src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
src/pybind/mgr/cephadm/tests/test_services.py
src/python-common/ceph/deployment/service_spec.py

mgr/cephadm/nvmeof: Allow setting NVMEoF gateway read notifications interval in the spec file
Fixes https://tracker.ceph.com/issues/71675 …

mgr/cephadm/nvmeof: Allow setting NVMEoF gateway notifications interval in the spec file

---

src/common/options/osd.yaml.in
src/osd/scrubber/pg_scrubber.cc

'osd_scrub_auto_repair_num_errors' limits the number of damaged objects that we will try to auto-repair during a scrub. Its documentation referred to "number of errors", which did not fit the implementation.
Original tracker: https://tracker.ceph.com/issues/71754
Backport tracker: https://tracker.ceph.com/issues/71771
Backported from https://github.com/ceph/ceph/pull/64048
(cherry picked from commit 680b58ffd0bf5b213ec525f8d783297fb0b14343)

squid: osd/scrub: clarify that osd_scrub_auto_repair_num_errors counts objects

---

src/test/crimson/gtest_seastar.h
src/test/crimson/seastore/test_transaction_manager.cc

Locally, the test time of test_transaction_manager has reduced by ~35% after the improvement.
Relieves https://tracker.ceph.com/issues/71704 …

test/crimson/seastore/test_transaction_manager: improve check_available()

---

doc/radosgw/s3select.rst

Update the link to the AWS specification format.
Fixes: https://tracker.ceph.com/issues/68619 …

doc/radosgw: update aws specification link

---

src/test/osd/CMakeLists.txt
src/test/osd/ceph_test_rados_io_sequence/ceph_test_rados_io_sequence.cc

Addressing issues presented in https://tracker.ceph.com/issues/71644
Improves readability of error messages in ceph_test_rados_io_sequence so errors caused by configuration errors produce human understandable errors instead of stack traces and core dumps.
I've also added a dependancy to the application for erasure code plugins to ensure when built in isolation these are built as well. …

test/osd: Improve readability of errors in ceph_test_rados_io_sequence

---

src/crimson/osd/osd.cc
src/crimson/osd/shard_services.cc
src/osd/OSD.cc
src/osd/osd_types.cc
src/osd/osd_types.h

The OSDSuperblock object access/modify epoch maps in multiple threads simultaneously due to that OSD is getting crashed. To avoid the crash access the maps under mutex.
Fixes: https://tracker.ceph.com/issues/66819 …

osd: Access/Modify epoch maps under mutex in OSDSuperblock class

---

doc/radosgw/s3select.rst

Update the link to the AWS specification format.
Fixes: https://tracker.ceph.com/issues/68619
(cherry picked from commit cca1a17d07fd31ccf13acf846ad13e6fad85d5f2) …

tentacle: doc/radosgw: update aws specification link

---

doc/radosgw/s3select.rst

Update the link to the AWS specification format.
Fixes: https://tracker.ceph.com/issues/68619
(cherry picked from commit cca1a17d07fd31ccf13acf846ad13e6fad85d5f2) …

squid: doc/radosgw: update aws specification link

---

doc/cephadm/certmgr.rst

Wrong path was passed to automodule and no documentation was generated. Use the right file name.
(cherry picked from commit f36746c2a472ef6876279a4d0d13b449327b95a1) …

tentacle: doc/cephadm: Fix automodule generation in certmgr.rst

---

src/mon/NVMeofGwMap.cc
src/mon/NVMeofGwMon.cc

nvmeofgw: fix sending acks during upgrade

---

Dockerfile.build
install-deps.sh
src/script/build-with-container.py
src/script/buildcontainer-setup.sh

A few hopefully non-controversial changes to get things closer to a working EL10 build.
Highlights:
* a few changes to enable a rocky 10 build image (`-d rocky10`)
* add a way for devs to generate a build image without crimson deps
Note that this doesn't make a rocky (or centos) 10 build image successfully. There are other things that still need updating before a build image gets created successfully - I have a hacky version of this branch in #63965 - a "never merge" PR that's mostly just a test platform and possibly a place to discuss some of the hacks. :-) …

script/build-with-container.: fixes and improvments towards el10

---

debian/ceph-base.install
debian/ceph-common.install
debian/ceph-exporter.install
debian/ceph-fuse.install
debian/ceph-immutable-object-cache.install
debian/ceph-mds.install
debian/ceph-mgr.install
debian/ceph-mon.install
debian/ceph-osd.install
debian/ceph-volume.install
debian/cephfs-mirror.install
debian/radosgw.install
debian/rbd-mirror.install

backport tracker: https://tracker.ceph.com/issues/71715
---
backport of https://github.com/ceph/ceph/pull/64001
parent tracker: https://tracker.ceph.com/issues/71713

tentacle: deb: use glob match to support systemd unit dir changes

---

doc/rados/operations/health-checks.rst
src/mon/HealthMonitor.cc
src/mon/HealthMonitor.h
src/mon/OSDMonitor.cc

backport tracker: https://tracker.ceph.com/issues/70221
---
backport of https://github.com/ceph/ceph/pull/55103
parent tracker: https://tracker.ceph.com/issues/63861

reef: src/mon/OSDMonitor.cc: [Stretch Mode] WRN non-existent CRUSH location assigned to MON

---

.gitmodules

backport tracker: https://tracker.ceph.com/issues/71674
---
backport of https://github.com/ceph/ceph/pull/62616
parent tracker: https://tracker.ceph.com/issues/62804

squid: build: Fix opentelemetry-cpp build failure on Noble

---

qa/workunits/mon/test_mon_osdmap_prune.sh

backport tracker: https://tracker.ceph.com/issues/69774
---
backport of https://github.com/ceph/ceph/pull/61397
parent tracker: https://tracker.ceph.com/issues/47838

squid: mon/test_mon_osdmap_prune: Use first_pinned instead of first_committed

---

src/osd/osd_types.h

backport tracker: https://tracker.ceph.com/issues/71224
---
backport of https://github.com/ceph/ceph/pull/62705
parent tracker: https://tracker.ceph.com/issues/45702

squid: osd_types: Restore new_object marking for delete missing entries

---

doc/radosgw/notifications.rst

Remove "pubsub_event_lost" from the list of "Notification Performance Statistics" in doc/radosgw/notifications.rst. "pubsub_event_lost" is now obsolete.
Fixes: https://tracker.ceph.com/issues/71790 …

doc/radosgw: remove "pubsub_event_lost"

---

doc/rados/operations/stretch-mode.rst

Corrected "communicte" to "communicate"

[Docs]: Corrected spelling mistake

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-list/nvmeof-listeners-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts

Fixes https://tracker.ceph.com/issues/71685 …

mgr/dashboard: Add --force flag for listeners

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-form/nvmeof-listeners-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-form/nvmeof-listeners-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/smb/smb-cluster-form/smb-cluster-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/host.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/host.interface.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/service.interface.ts

Fixes https://tracker.ceph.com/issues/71686
* Currently, listeners cannot be added with the Ceph Dashboard if the gateway nodes are selected by label instead of hosts.
* Refactored the code to incorporate nodes with labels
* Also added missing typings and removed 'any'
https://github.com/user-attachments/assets/ed5897f7-46eb-44c0-95ea-6c15458a59ce …

mgr/dashboard: Allow host with labels in listener form

---

doc/radosgw/notifications.rst

Remove "pubsub_event_lost" from the list of "Notification Performance Statistics" in doc/radosgw/notifications.rst. "pubsub_event_lost" is now obsolete.
Fixes: https://tracker.ceph.com/issues/71790
(cherry picked from commit b308f50d1e0c2d238c3b2bf54df99cc7ac2ac679) …

reef: doc/radosgw: remove "pubsub_event_lost"

---

doc/radosgw/notifications.rst

Add the labeled counter "persistent_topic_len" to the list of "Notification Performance Statistics" in doc/radosgw/notifications.rst.
Fixes: https://tracker.ceph.com/issues/71791 …

doc/radosgw: add "persistent_topic_len"

---

doc/rados/operations/balancer.rst
src/common/options/global.yaml.in

Clarify the threshold set by "upmap_max_deviation" and add the information about this configurable that is currently in src/pybind/mgr/balancer/module.py to src/common/options/global.yaml.in, so that it will be accessible by means of ".. confval::" declarations.
Fixes: https://tracker.ceph.com/issues/71796 …

doc/rados: clarify "upmap_max_deviation"

---

src/tools/rbd/action/Kernel.cc

Guard print_error_description() and get_unsupported_features() with `#ifdef WITH_KRBD` to prevent compiler warnings when KRBD support is not enabled.
These functions are only called by do_kernel_map(), which is itself conditionally compiled. When WITH_KRBD is not defined, the compiler generates unused function warnings for these helper functions.
Fixes warning:
```
/home/kefu/dev/ceph/src/tools/rbd/action/Kernel.cc:305:13: warning: ‘void rbd::action::kernel::print_error_description(const char*, const char*, const char*, const char*, int)’ defined but not used [-Wunused-function]
305 | static void print_error_description(const char *poolname,
|             ^~~~~~~~~~~~~~~~~~~~~~~
```
this silences the warning. …

rbd: fix unused function warning when WITH_KRBD is disabled

---

doc/radosgw/notifications.rst

Remove "pubsub_event_triggered" from the list of "Notification Performance Statistics". It is obsolete.
Fixes: https://tracker.ceph.com/issues/71789 …

doc/radosgw: remove "pubsub_event_triggered"

---

qa/tasks/s3a_hadoop.py

backport tracker: https://tracker.ceph.com/issues/71671
---
backport of https://github.com/ceph/ceph/pull/63793
parent tracker: https://tracker.ceph.com/issues/71584

squid: qa/rgw: bump maven version in hadoop task to resolve 404 Not Found

---

doc/radosgw/notifications.rst

Explain in greater detail what the counter "pubsub_push_pending" counts.
Fixes: https://tracker.ceph.com/issues/71793
(cherry picked from commit 26f2c0ebbe364cd27f8f0ae1adc954ce206371b7) …

tentacle: doc/radosgw: improve "pubsub_push_pending" info

---

src/crimson/common/assert.cc
src/crimson/common/fatal_signal.cc
src/crimson/common/log.h

Currently  crashes caused by signals are *very* hard to detect, we only get a "Segmentation fault" which gets hidden in random log lines from other shards due to missing newlines:
```
Segmentation faultDEBUG 2025-05-29 12:03:35,878 [shard 2:main]
seastore_t - ...
```
Rework aborting from signals path to be more informative. 
See segfaults trackers examples below:
https://tracker.ceph.com/issues/66818
https://tracker.ceph.com/issues/71457 …

crimson/common/fatal_signal: Rework signals

---

doc/rados/configuration/ceph-conf.rst

Add missing space after closing backticks to properly terminate inline literal.
Sphinx was generating a warning due to an unterminated inline literal string:
```
/home/kefu/dev/ceph/doc/rados/configuration/ceph-conf.rst:320: WARNING: Inline literal start-string without end-string.
```
This fix ensures the inline literal is properly closed and eliminates the build warning. …

doc: Fix unterminated inline literal in ceph-conf.rst

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-listeners-list/nvmeof-listeners-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts

backport tracker: https://tracker.ceph.com/issues/71808
---
backport of https://github.com/ceph/ceph/pull/63961
parent tracker: https://tracker.ceph.com/issues/71685

squid: mgr/dashboard: Add --force flag for listeners

---

doc/radosgw/notifications.rst

Remove "pubsub_event_triggered" from the list of "Notification Performance Statistics". It is obsolete.
Fixes: https://tracker.ceph.com/issues/71789
(cherry picked from commit 44dc57fc15749583fc13560c9409b7687df7c223) …

squid: doc/radosgw: remove "pubsub_event_triggered"

---

src/rgw/rgw_common.cc
src/rgw/rgw_op.cc

backport tracker: https://tracker.ceph.com/issues/71752
---
backport of https://github.com/ceph/ceph/pull/63521
parent tracker: https://tracker.ceph.com/issues/71458

tentacle: fix: the RGW crash caused by special characters

---

src/osd/scrubber/pg_scrubber.cc

Replace fmt::localtime() with localtime_r() to fix build failure with fmt 11.2.0. The fmt::localtime() function was deprecated in favor of std::localtime, causing build errors when treating warnings as errors:
```
[1/3] Building CXX object src/osd/CMakeFiles/osd.dir/scrubber/pg_scrubber.cc.o
/home/kefu/dev/ceph/src/osd/scrubber/pg_scrubber.cc: In member function ‘virtual void PgScrubber::update_scrub_stats(ceph::coarse_real_clock::time_point)’:
/home/kefu/dev/ceph/src/osd/scrubber/pg_scrubber.cc:2767:41: warning: ‘tm fmt::v11::localtime(time_t)’ is deprecated [-Wdeprecated-declarations]
2767 |     auto printable_last = fmt::localtime(clock::to_time_t(m_last_stat_upd));
|                           ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from …
```

osd/scrubber: replace deprecated fmt::localtime() with localtime_r()

---

.github/workflows/retrigger-rtd.yml

reef: .github: Fix RTD build retrigger

---

src/librbd/migration/QCOWFormat.cc

librbd/migration/QCOWFormat: don't complete read_clusters() inline

---

src/mds/flock.cc

Commit 09f3c879 added ceph_lock_state_t to ceph-dencoder verification, but some fields are intentionally not persisted, causing test failures in readable.sh and check-generated.sh due to encode/decode mismatches.
The following fields are excluded from dump() as they are not persisted:
- type: always set in constructor, no need to persist
- waiting_locks: runtime-only field for active lock management
- client_waiting_lock_counts: runtime-only field for client tracking
Current tests pass by reusing instances (preserving non-persisted fields), but upcoming changes will use fresh instances per decode, exposing this inconsistency.
This change ensures dump() output matches what is actually encoded/decoded, fixing test compatibility with the new allocation strategy. …

mds/flock: exclude non-persisted fields from ceph_lock_state_t::dump()

---

src/osd/osd_perf_counters.cc

Some scrub perf counters were created without specifying individual priorities, assuming by mistake that the default priority is '_INTERESTING'. That was not the case, and those perf counters were not reported.
Fixes: https://tracker.ceph.com/issues/71842
Backport of https://github.com/ceph/ceph/pull/64182
(cherry picked from commit cf1864a61061bc9de05eedd987f64307bcf7c501)

tentacle: osd/scrub: some perf counters had their priority set to '0'

---

src/tools/rbd_mirror/InstanceReplayer.cc
src/tools/rbd_mirror/InstanceReplayer.h

backport tracker: https://tracker.ceph.com/issues/70978
---
backport of https://github.com/ceph/ceph/pull/62849
parent tracker: https://tracker.ceph.com/issues/70951

reef: rbd-mirror: release lock before calling m_async_op_tracker.finish_op()

---

doc/dev/release-checklists.rst

doc: Add branch protection step to new release checklist

---

ceph.spec.in

To support EL 10 distros, update the source of the pathfix tool (on EL 9+ distros) and use the macro for updating python shebangs that has been available since at least EL 9. …

ceph.spec.in: use rpm macro for python shebang pathfix

---

doc/radosgw/notifications.rst

Remove "pubsub_event_triggered" from the list of "Notification Performance Statistics". It is obsolete.
Fixes: https://tracker.ceph.com/issues/71789
(cherry picked from commit 44dc57fc15749583fc13560c9409b7687df7c223) …

tentacle: doc/radosgw: remove "pubsub_event_triggered"

---

src/pybind/mgr/dashboard/controllers/nfs.py
src/pybind/mgr/dashboard/openapi.yaml

Remove trailing space from summary field that was causing Sphinx build warning.
Sphinx was generating a warning due to malformed inline markup:
```
/home/kefu/dev/ceph/doc/mgr/ceph_api/index.rst:3349: WARNING: Inline strong start-string without end-string.`
```
The openapi directive appears to convert trailing spaces into asterisk markers, creating unterminated strong markup. This change removes the trailing space to eliminate the warning and maintain consistency with other entries in the file. …

mgr/dashboard: Fix inline markup warning in API documentation

---

src/osd/scrubber/scrub_machine.cc

By mistake, the 'scrub starts' log message included the (irrelevant) shard ID of the primary OSD, instead of just the PG ID.
Fixes: https://tracker.ceph.com/issues/71780

osd/scrub: 'starts' messages should name PGs, not shards

---

src/tools/rbd_mirror/InstanceReplayer.cc
src/tools/rbd_mirror/InstanceReplayer.h

backport tracker: https://tracker.ceph.com/issues/70977
---
backport of https://github.com/ceph/ceph/pull/62849
parent tracker: https://tracker.ceph.com/issues/70951

squid: rbd-mirror: release lock before calling m_async_op_tracker.finish_op()

---

PendingReleaseNotes
src/librbd/api/Mirror.cc
src/librbd/mirror/PromoteRequest.cc
src/pybind/mgr/dashboard/controllers/rbd.py
src/pybind/mgr/dashboard/controllers/rbd_mirroring.py
src/pybind/mgr/dashboard/services/rbd.py
src/pybind/mgr/rbd_support/mirror_snapshot_schedule.py
src/test/librbd/test_librbd.cc
src/test/librbd/test_mirroring.cc
src/test/pybind/test_rbd.py
src/tools/rbd/action/MirrorPool.cc

backport tracker: https://tracker.ceph.com/issues/71758
---
backport of https://github.com/ceph/ceph/pull/63149
parent tracker: https://tracker.ceph.com/issues/71226

tentacle: librbd/api/Mirror: return EINVAL from image_get_mode() when the image is disabled for mirroring 

---

src/librbd/group/ListSnapshotsRequest.cc
src/librbd/group/ListSnapshotsRequest.h

backport tracker: https://tracker.ceph.com/issues/71774
---
backport of https://github.com/ceph/ceph/pull/63302
parent tracker: https://tracker.ceph.com/issues/67984

tentacle: librbd: retry list_snap_orders() once instead of failing sort_snaps()

---

src/pybind/mgr/mgr_module.py

The inline method documentation needs an empty
line between description and metadata.
Otherwise automethod from docs renders the
metadata as text together with the description instead
of rendering it as function metadata, e.g. parameters
and return value.
This PR adds missing empty lines in all inline
documentation in `mgr_module.py` and that seems
to fix the documentation.
- Before: https://docs.ceph.com/en/latest/mgr/modules/#mgr_module.MgrModule.set_localized_module_option
- After: https://ceph--62785.org.readthedocs.build/en/62785/mgr/modules/#mgr_module.MgrModule.set_localized_module_option
Notice how the "before" has metadata rendered as
gibberish that is appended to the description;
and how "after" shows the metadata rendered as
properly formatted.
These same changes should be done …

pybind/mgr: Fix missing empty lines in documentation in mgr_module.py

---

src/client/Client.cc
src/client/Client.h
src/test/libcephfs/test.cc

commit 6dc7756
https://tracker.ceph.com/issues/71510
https://tracker.ceph.com/issues/70726 …

tentacle: client: cephfs user-space client fixes

---

src/rgw/rgw_dedup.cc
src/rgw/rgw_dedup.h
src/rgw/rgw_dedup_cluster.cc
src/rgw/rgw_dedup_cluster.h
src/rgw/rgw_dedup_store.cc
src/rgw/rgw_dedup_table.cc
src/rgw/rgw_dedup_table.h
src/rgw/rgw_dedup_utils.cc
src/rgw/rgw_dedup_utils.h
src/rgw/rgw_zone.cc
src/rgw/rgw_zone.h
src/test/rgw/dedup/pytest.ini
src/test/rgw/dedup/test_dedup.py

Moved all control objects (EPOCH, WATCH, Tokens) to default.rgw.control pool.
rgw.dedup pool is created on dedup start and removed when the scan is over
report duplicated space after dedup because of the head-object
report potential dedup for smaller objects (64KB-4MB)
code cleanup  …

rgw/dedup: full object dedup continuous work

---

qa/cephfs/overrides/ignorelist_health.yaml
qa/cephfs/overrides/ignorelist_wrongly_marked_down.yaml

Runs have started failing a lot with the human friendly variant of the warning. OSD_DOWN is in the ignore list, however, the human friendly warning (osds down) isn't.
Fixes: http://tracker.ceph.com/issues/71446
(cherry picked from commit 6bdda0bb3411773a2fea5d4ff83db6be295c5a1f) …

tentacle: qa/cephfs: ignore `OSD_DOWN/osds down` warning

---

doc/rados/configuration/ceph-conf.rst

Fix a missing space typo.
Use title case in section titles.
Use ref for hyperlink to a section that already has a label instead of linking to title text of the section.
Use privileged command prompt for all ceph commands except ceph commands that invoke help.
Use INI preformatted block for last remaining block that was just using plain preformatted.
Add a missing comma between different example config values.
- Before: https://docs.ceph.com/en/latest/rados/configuration/ceph-conf/
- Rendered PR: https://ceph--64255.org.readthedocs.build/en/64255/rados/configuration/ceph-conf/ …

doc/rados/configuration: Small improvements in ceph-conf.rst

---

src/pybind/mgr/prometheus/module.py
src/pybind/mgr/rook/module.py

This commit is introduced to generate self signed certificated for Prometheus and dashboard. https://github.com/ceph/ceph/pull/58402
In above mentioned commit tls for prometheus works only with cephadm orchestrator. And it also generates selfsigned certificate with cephadm-root CA that is genereated every time function is called. 
However when using rook orch certificates are not generated. This PR implements getting certificates for rook orch. 
Solution is following:
Certificates are read from rook namespace via kubernetes api client. 
Name of the secrets are provided by following parameters:
- prometheus_tls_secret_name (default secret name "rook-ceph-prometheus-server-tls")
- dashboard_tls_secret_name (default secret name "rook-ceph-dashboard-server-tls")
In simple words when cephadm …

Make prometheus TLS config work with Rook orchestrator

---

src/pybind/mgr/cephadm/services/cephadmservice.py
src/pybind/mgr/cephadm/tests/test_services.py
src/python-common/ceph/deployment/service_spec.py

Backport of https://github.com/ceph/ceph/pull/58604
<details>
</details>

squid: mgr/cephadm: allow disabling rgw_run_sync_thread through spec

---

src/pybind/mgr/cephadm/services/ingress.py

Backport of https://github.com/ceph/ceph/pull/61663
<details>
</details>

squid: mgr/cephadm: fix typo with vrrp_interfaces in keepalive setup

---

qa/tasks/cephadm.py

Backport of https://github.com/ceph/ceph/pull/61722
<details>
</details>

squid: qa/cephadm: stop cephadm mgr module during cleanup

---

src/cephadm/cephadm.py

Backport of https://github.com/ceph/ceph/pull/62525
<details> …

squid: cephadm: stop sidecar systemd units when restarting main units

---

src/pybind/mgr/cephadm/service_discovery.py
src/pybind/mgr/cephadm/services/monitoring.py
src/pybind/mgr/cephadm/services/nfs.py
src/pybind/mgr/cephadm/templates/services/prometheus/prometheus.yml.j2
src/pybind/mgr/cephadm/tests/test_service_discovery.py
src/pybind/mgr/cephadm/tests/test_services.py

backport tracker: https://tracker.ceph.com/issues/67499
---
backport of https://github.com/ceph/ceph/pull/55050
parent tracker: https://tracker.ceph.com/issues/62558

squid: mgr/nfs: scrape nfs monitoring endpoint

---

src/test/librados/aio_cxx.cc

GTEST_SKIP() does not return and causes early test exit, which skips any following cleanup logic.
In this case, the test skipped before releasing my_lock, causing pthread_mutex_destroy() to fail with EBUSY and trigger a ceph_assert() in the mutex debug wrapper.
Fix by explicitly unlocking the mutex before calling GTEST_SKIP(). …

test/librados/aio_cxx: Fix potential mutex destruction failure on Pool EIOFlag

---

src/osdc/error_code.h

Remove unnecessary `#include "include/rados.h"` from error_code.h as it's not used by the header and error_code.h doesn't need to expose any RADOS declarations.
This improves compilation time and reduces unnecessary dependencies. …

osdc: remove unused rados.h include from error_code.h

---

src/pybind/mgr/dashboard/model/nvmeof.py

backport tracker: https://tracker.ceph.com/issues/71883
---
backport of https://github.com/ceph/ceph/pull/63335
parent tracker: https://tracker.ceph.com/issues/71355

tentacle: mgr/dashboard: align gw info, gw version, spdk_log_level get with old cli

---

.github/workflows/scripts/config-diff-post-comment.js

Currently, whenever a "config diff tool output" comment is created it also has the string `/config check ok` string in it. The next time the test run it see's this text and assumes that the user has commented it. We fix the logic to makes sure that we ignore such cases.
This bug got introduced as part of this: https://github.com/ceph/ceph/pull/64015
One can see this happening in this run: https://github.com/ceph/ceph/actions/runs/16014805821/job/45179304245?pr=64291
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-back …

.github/workflows/scripts/config-diff-post-comment.js: fix config check ok logic

---

doc/rados/configuration/ceph-conf.rst

Add missing space after closing backticks to properly terminate inline literal.
Sphinx was generating a warning due to an unterminated inline literal string:
```
/home/kefu/dev/ceph/doc/rados/configuration/ceph-conf.rst:320: WARNING: Inline literal start-string without end-string.
```
This fix ensures the inline literal is properly closed and eliminates the build warning.
(cherry picked from commit 7f79f3d6aa7f71c9b2434b843036a3f1da660231) …

tentacle: doc: Fix unterminated inline literal in ceph-conf.rst

---

doc/rados/configuration/ceph-conf.rst

Add missing space after closing backticks to properly terminate inline literal.
Sphinx was generating a warning due to an unterminated inline literal string:
```
/home/kefu/dev/ceph/doc/rados/configuration/ceph-conf.rst:320: WARNING: Inline literal start-string without end-string.
```
This fix ensures the inline literal is properly closed and eliminates the build warning.
(cherry picked from commit 7f79f3d6aa7f71c9b2434b843036a3f1da660231) …

squid: doc: Fix unterminated inline literal in ceph-conf.rst

---

doc/rados/configuration/ceph-conf.rst

Fix a missing space typo.
Use title case in section titles.
Use ref for hyperlink to a section that already has a label instead of linking to title text of the section.
Use privileged command prompt for all ceph commands except ceph commands that invoke help.
Use INI preformatted block for last remaining block that was just using plain preformatted.
(cherry picked from commit 6687c9767d9764f34d7099ba6980992dd8ae8737)
- When …

squid: doc/rados/configuration: Small improvements in ceph-conf.rst

---

doc/rados/configuration/ceph-conf.rst

Fix a missing space typo.
Use title case in section titles.
Use ref for hyperlink to a section that already has a label instead of linking to title text of the section.
Use privileged command prompt for all ceph commands except ceph commands that invoke help.
Use INI preformatted block for last remaining block that was just using plain preformatted.
(cherry picked from commit 6687c9767d9764f34d7099ba6980992dd8ae8737)
- When …

tentacle: doc/rados/configuration: Small improvements in ceph-conf.rst

---

doc/radosgw/metrics.rst

Edit doc/radosgw/metrics.rst.
Incorporate Anthony D'Atri's suggestion from
https://github.com/ceph/ceph/pull/62893#discussion_r2124662981 into the RADOSGW documentation.
This commit clarifies the English that explains the behavior of rgw-multitenancy.
(cherry picked from commit c7e49b85997369c5c29fb64da89fa676cb84e989) …

reef: doc/radosgw: edit metrics.rst

---

src/pybind/mgr/dashboard/model/nvmeof.py
src/pybind/mgr/dashboard/services/nvmeof_client.py
src/pybind/mgr/dashboard/tests/test_nvmeof_client.py

backport tracker: https://tracker.ceph.com/issues/71880
---
backport of https://github.com/ceph/ceph/pull/63308
parent tracker: https://tracker.ceph.com/issues/71351

tentacle: mgr/dashboard: Add missing fields to subsytem list API/CLI

---

src/common/options/global.yaml.in

"mon_warn_pg_not_scrubbed_ratio" to the confval definition of that variable. Although this variable contains the string "mon", it is set on the Manager. I have added a note to direct users to set this value on the Manager.
This issue is part of a small project that also encompasses https://github.com/ceph/ceph/pull/62459, which is associated with commit aeef59a50ee31072648ba0c7436b6522137614cd
(cherry picked from commit 5754906c3bd15a63855b8265a3ac93ae2a1a3c8c) …

squid: src/common: add guidance for mon_warn_pg_not_scrubbed

---

doc/radosgw/metrics.rst

Edit doc/radosgw/metrics.rst.
Incorporate Anthony D'Atri's suggestion from
https://github.com/ceph/ceph/pull/62893#discussion_r2124662981 into the RADOSGW documentation.
This commit clarifies the English that explains the behavior of rgw-multitenancy.
(cherry picked from commit c7e49b85997369c5c29fb64da89fa676cb84e989) …

squid: doc/radosgw: edit metrics.rst

---

doc/radosgw/admin.rst

Clarify behavior of bucket and uid flags when setting a quota with quota-scope=bucket.
(cherry picked from commit d5c7b4d62c71ca2a57b7d9a552eae03f0f620cef) …

reef: doc/radosgw/admin.rst: explain bucket and uid flags for bucket quota

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-storage-class.model.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-details/rgw-storage-class-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/utils/rgw-bucket-tiering.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-storage-class.service.spec.ts

Fixes: https://tracker.ceph.com/issues/71053
Signed-off-by: Dnyaneshwari Talwekar <dtalwekar@redhat.com>
Description:
1.Moved "Allow Read Through" and "Head Object" to general section from Advanced section.
2.Enable Head Object checkbox by default
3.When Allow Read through is enabled, enable Head Object checkbox and disable the checkbox so user doesn't change it.
4.Added description to Head Object to mention about Stub File.
https://github.com/user-attachments/assets/f376ebfe-d992-4b63-83a8-a9108259f7d7 …

mgr/dashboard: Tieiring - allow read through

---

src/pybind/mgr/nfs/ganesha_conf.py

Backport of https://github.com/ceph/ceph/pull/62718
<details> …

squid: mgr/nfs: make sure sectype is a list when parsed

---

src/cephadm/cephadmlib/container_lookup.py

backport tracker: https://tracker.ceph.com/issues/71571
---
backport of https://github.com/ceph/ceph/pull/62935
parent tracker: https://tracker.ceph.com/issues/70989

tentacle: cephadm: don't collect image ids for daemons with no container info

---

doc/radosgw/config-ref.rst

Add rgw_enable_lc_threads and rgw_enable_gc_threads to doc/radosgw/config-ref.rst.
Fixes: https://tracker.ceph.com/issues/58092 …

doc/radosgw: add rgw_enable_lc_threads & rgw_enable_gc_threads

---

src/blk/BlockDevice.cc
src/blk/BlockDevice.h
src/blk/kernel/KernelDevice.cc
src/common/ceph_context.h
src/common/options/global.yaml.in
src/extblkdev/ExtBlkDevPlugin.cc
src/mon/PGMap.cc

Added a health warning mechanism to monitor the discard queue for potential overload.
Emits a warning if the accumulated discarded bytes in the queue exceed the configured threshold.
Introduced a debugging tool to simulate slow discard operations by adding a configurable delay.
Tracker Ticket : [69082](https://tracker.ceph.com/issues/69082) …

blk:Warning added for discard queue overflow

---

debian/control

backport tracker: https://tracker.ceph.com/issues/71564
---
backport of https://github.com/ceph/ceph/pull/63702
parent tracker: https://tracker.ceph.com/issues/71545

tentacle: debian: radosgw: add media-types packages as alternative for mime-support

---

qa/tasks/s3a_hadoop.py

backport tracker: https://tracker.ceph.com/issues/71672
---
backport of https://github.com/ceph/ceph/pull/63793
parent tracker: https://tracker.ceph.com/issues/71584

tentacle: qa/rgw: bump maven version in hadoop task to resolve 404 Not Found

---

qa/suites/rgw/multifs/0-install.yaml
qa/suites/rgw/multifs/tasks/rgw_bucket_quota.yaml
qa/suites/rgw/multifs/tasks/rgw_multipart_upload.yaml
qa/suites/rgw/multifs/tasks/rgw_user_quota.yaml
qa/suites/rgw/thrash/install.yaml
qa/suites/rgw/thrash/workload/rgw_bucket_quota.yaml
qa/suites/rgw/thrash/workload/rgw_multipart_upload.yaml
qa/suites/rgw/thrash/workload/rgw_user_quota.yaml
qa/workunits/rgw/s3_bucket_quota-run.sh
qa/workunits/rgw/s3_multipart_upload-run.sh
qa/workunits/rgw/s3_user_quota-run.sh
qa/workunits/rgw/s3_utilities.pm

backport tracker: https://tracker.ceph.com/issues/71906
---
backport of https://github.com/ceph/ceph/pull/63760
parent tracker: https://tracker.ceph.com/issues/71577

tentacle: qa/rgw: fix perl tests missing Amazon::S3 module 

---

doc/radosgw/config-ref.rst

Add rgw_enable_lc_threads and rgw_enable_gc_threads to doc/radosgw/config-ref.rst.
Fixes: https://tracker.ceph.com/issues/58092
(cherry picked from commit 45e5468ea7fc57b1cb60f1936558dc2678adc6fd) …

tentacle: doc/radosgw: add rgw_enable_lc_threads & rgw_enable_gc_threads

---

doc/radosgw/config-ref.rst

Add rgw_enable_lc_threads and rgw_enable_gc_threads to doc/radosgw/config-ref.rst.
Fixes: https://tracker.ceph.com/issues/58092
(cherry picked from commit 45e5468ea7fc57b1cb60f1936558dc2678adc6fd) …

reef: doc/radosgw: add rgw_enable_lc_threads & rgw_enable_gc_threads

---

src/test/common/CMakeLists.txt

backport tracker: https://tracker.ceph.com/issues/71689
---
backport of https://github.com/ceph/ceph/pull/63822
parent tracker: https://tracker.ceph.com/issues/71600

reef: test/common: unittest_fault_injector omits unit-main target

---

src/crimson/os/seastore/backref/btree_backref_manager.cc
src/crimson/os/seastore/btree/fixed_kv_btree.h
src/crimson/os/seastore/cache.h
src/crimson/os/seastore/lba/btree_lba_manager.cc
src/crimson/os/seastore/linked_tree_node.h
src/test/crimson/seastore/test_btree_lba_manager.cc

crimson/os/seastore/btree: bottom-up search capability

---

src/pybind/mgr/dashboard/model/nvmeof.py

backport tracker: https://tracker.ceph.com/issues/71885
---
backport of https://github.com/ceph/ceph/pull/63366
parent tracker: https://tracker.ceph.com/issues/71378

tentacle: mgr/dashboard: align cli commands listener list, ns list, host list

---

src/mon/NVMeofGwMap.cc
src/mon/NVMeofGwMon.cc

backport tracker: https://tracker.ceph.com/issues/71894
---
backport of https://github.com/ceph/ceph/pull/63883
parent tracker: https://tracker.ceph.com/issues/71890

tentacle: nvmeofgw: fix sending acks during upgrade

---

src/common/options/mon.yaml.in
src/mon/NVMeofGwMap.cc
src/mon/NVMeofGwMap.h
src/mon/NVMeofGwMon.cc
src/nvmeof/NVMeofGwMonitorClient.cc
src/nvmeof/NVMeofGwMonitorClient.h

backport tracker: https://tracker.ceph.com/issues/71893
---
backport of https://github.com/ceph/ceph/pull/63003
parent tracker: https://tracker.ceph.com/issues/71889

tentacle: fix duplicated entity addr in the map during reboot of several GWs

---

src/erasure-code/ErasureCode.cc
src/erasure-code/ErasureCodeInterface.h
src/erasure-code/isa/ErasureCodeIsa.cc
src/erasure-code/jerasure/ErasureCodeJerasure.cc
src/erasure-code/jerasure/ErasureCodeJerasure.h
src/erasure-code/lrc/ErasureCodeLrc.cc
src/erasure-code/shec/ErasureCodeShec.cc
src/osd/ECTypes.h
src/test/erasure-code/ErasureCodeExample.h

Addresses review comments from #61804
Backport of #62657
(cherry picked from commit 87ff016584e3354f98a7129e760f41870142d262) …

tentacle: erasure-code: reformat EC plugins

---

src/test/osd/CMakeLists.txt
src/test/osd/ceph_test_rados_io_sequence/ceph_test_rados_io_sequence.cc

backport tracker: https://tracker.ceph.com/issues/71798
---
backport of https://github.com/ceph/ceph/pull/64046
parent tracker: https://tracker.ceph.com/issues/71644

tentacle: test/osd: Improve readability of errors in ceph_test_rados_io_sequence

---

src/crimson/osd/lsan_suppressions.cc
src/include/function2.hpp
src/osd/ReplicatedBackend.cc

backport tracker: https://tracker.ceph.com/issues/71821
---
backport of https://github.com/ceph/ceph/pull/63486
parent tracker: https://tracker.ceph.com/issues/71456

tentacle: src: fix NDEBUG typo

---

src/test/librados/aio_cxx.cc

backport tracker: https://tracker.ceph.com/issues/71867
---
backport of https://github.com/ceph/ceph/pull/63177
parent tracker: https://tracker.ceph.com/issues/70852

tentacle: test/librados/aio_cxx: skip EIO boundary assertion when no in-flight I/Os

---

src/librbd/migration/QCOWFormat.cc

backport tracker: https://tracker.ceph.com/issues/71846
---
backport of https://github.com/ceph/ceph/pull/64174
parent tracker: https://tracker.ceph.com/issues/71838

tentacle: librbd/migration/QCOWFormat: don't complete read_clusters() inline

---

qa/suites/crimson-rados/basic/tasks/cls.yaml
src/crimson/osd/pg_backend.cc

for omap_get_vals_by_keys
fix ./bin/ceph_test_cls_cmpomap error for noexist tests
https://tracker.ceph.com/issues/71225 …

crimson/osd/pg_backend: needn't check if os.exist 

---

src/common/json/OSDStructures.cc
src/common/json/OSDStructures.h
src/erasure-code/CMakeLists.txt
src/erasure-code/consistency/CMakeLists.txt
src/erasure-code/consistency/ConsistencyChecker.cc
src/erasure-code/consistency/ConsistencyChecker.h
src/erasure-code/consistency/ECEncoder.cc
src/erasure-code/consistency/ECEncoder.h
src/erasure-code/consistency/ECEncoderSwitch.cc
src/erasure-code/consistency/ECEncoderSwitch.h
src/erasure-code/consistency/ECReader.cc
src/erasure-code/consistency/ECReader.h
src/erasure-code/consistency/Pool.cc
src/erasure-code/consistency/Pool.h
src/erasure-code/consistency/RadosCommands.cc
src/erasure-code/consistency/RadosCommands.h
src/erasure-code/consistency/ceph_ec_consistency_checker.cc
src/osd/ECBackend.cc
src/osd/ECBackendL.cc
src/osd/ECCommon.cc
src/osd/ECCommon.h
src/osd/ECCommonL.cc
src/osd/ECCommonL.h
src/osd/ECInject.cc
src/osd/ECInject.h
src/osd/OSD.cc

This pull request introduces an online version of the consistency checking tool for erasure coded objects in ceph. The objective of the tool is to provide a means of live checking for cases where a parity update has not been properly applied to an EC object. It achieves this by reading back both the data and parity shards of an object that are stored on the OSDs, encoding the data shards and comparing these to the read-in parity shards.
A new inject called a parity read inject is defined in the OSD code. When armed, this new inject will modify the read result of the next read for the specified object so that the entire object is returned to the client, both data and parity chunks combined. A simple command line utility has been added, this takes the pool name, length, offset, oid, block …

Erasure code online consistency checker

---

monitoring/ceph-mixin/config.libsonnet
monitoring/ceph-mixin/prometheus_alerts.libsonnet
monitoring/ceph-mixin/prometheus_alerts.yml
monitoring/ceph-mixin/tests_alerts/test_alerts.yml

Fixes: https://tracker.ceph.com/issues/71772 …

monitoring: Add alert NVMeoFHostKeepAliveTimeout

---

qa/config/crimson_bluestore.yaml
qa/config/crimson_seastore_rbm.yaml
qa/config/crimson_seastore_segmented.yaml
src/common/options/crimson.yaml.in
src/crimson/osd/main.cc
src/vstart.sh

The osd_objectstore supports all type of objectstores (bluestore/filestore/memstore/seastore/cyanstore) so there is no benefit to keep separate option for crimson.
Fixes: https://tracker.ceph.com/issues/71593 …

crimson: Use osd_objectstore instead of using crimson_osd_objectstore

---

CMakeLists.txt
src/CMakeLists.txt
src/include/config-h.in.cmake

Remove the deprecated WITH_SEASTAR CMake option and replace all references with WITH_CRIMSON for consistency. Although WITH_SEASTAR was functionally replaced in commit 23c33f69, it remained in the source tree. This change completes the migration by removing the old option entirely and standardizing on WITH_CRIMSON throughout the codebase. …

cmake: replace WITH_SEASTAR with WITH_CRIMSON

---

src/pybind/mgr/cephadm/services/nfs.py
src/pybind/mgr/nfs/cluster.py

backport tracker: https://tracker.ceph.com/issues/71195
---
backport of https://github.com/ceph/ceph/pull/62891
parent tracker: https://tracker.ceph.com/issues/70985

tentacle: mgr/nfs: Add VIP to HAProxy_Hosts list for ingress type haproxy-protocol

---

src/CMakeLists.txt
src/crimson/CMakeLists.txt
src/crimson/common/smp_helpers.h
src/crimson/os/alienstore/CMakeLists.txt

crimson/common/smp_helpers: fix missing include

---

PendingReleaseNotes
doc/rados/operations/monitoring.rst
qa/standalone/mon/availability.sh
src/mon/MgrStatMonitor.cc
src/mon/MgrStatMonitor.h
src/mon/MonCommands.h
src/mon/OSDMonitor.cc

backport tracker: https://tracker.ceph.com/issues/71858
---
backport of https://github.com/ceph/ceph/pull/63552
parent tracker: https://tracker.ceph.com/issues/71495

tentacle: mon: add command osd pool clear-availability-status

---

src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/tests/test_cephadm.py
src/pybind/mgr/orchestrator/_interface.py
src/pybind/mgr/orchestrator/module.py

backport tracker: https://tracker.ceph.com/issues/71196
---
backport of https://github.com/ceph/ceph/pull/62848
parent tracker: https://tracker.ceph.com/issues/70950

tentacle: mgr/cephadm: Add command to stop host drain

---

src/pybind/mgr/cephadm/services/cephadmservice.py

backport tracker: https://tracker.ceph.com/issues/69712
---
backport of https://github.com/ceph/ceph/pull/61530
parent tracker: https://tracker.ceph.com/issues/69567

squid: cephadm: rgw: allow specifying the ssl_certificate by filepath

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/nvmeof-namespaces-form/nvmeof-namespaces-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/nvmeof.service.ts
src/pybind/mgr/dashboard/model/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml

backport tracker: https://tracker.ceph.com/issues/71884
---
backport of https://github.com/ceph/ceph/pull/63410
parent tracker: https://tracker.ceph.com/issues/71393

tentacle: mgr/dashboard: align response of subsystem add and ns add with old cli

---

src/rgw/driver/rados/rgw_data_sync.cc
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_sync.cc
src/rgw/rgw_coroutine.cc
src/rgw/rgw_rest_conn.h

backport tracker: https://tracker.ceph.com/issues/71699
---
backport of https://github.com/ceph/ceph/pull/63303
parent tracker: https://tracker.ceph.com/issues/71337

tentacle: rgw/multisite: change HTTP error handling from EIO to ERR_INTERNAL_ERROR

---

qa/suites/crimson-rados/singleton/all/osd-backfill.yaml
qa/suites/crimson-rados/singleton/all/osd-pg-splitting.yaml

This should fix the chmod 777 /var/log/ceph failures.
We were missing the install task which resulted in no /var/log/ceph:
```
2025-07-07T08:55:44.586 INFO:teuthology.run_tasks:Running task ceph...
2025-07-07T08:55:44.679 INFO:tasks.ceph:Making ceph log dir writeable by
non-root...
2025-07-07T08:55:44.679 DEBUG:teuthology.orchestra.run.smithi144:> sudo
chmod 777 /var/log/ceph
2025-07-07T08:55:44.711
INFO:teuthology.orchestra.run.smithi144.stderr:chmod: cannot access
'/var/log/ceph': No such file or directory
```
See failures example:
https://pulpito.ceph.com/matan-2025-07-07_08:42:18-crimson-rados-wip-matanb-crimson-only-testing-6-jul-distro-crimson-debug-smithi/
Fixes: https://tracker.ceph.com/issues/71990 …

qa/suites/crimson-rados/singleton: add install task

---

qa/tasks/thrashosds-health.yaml

Fixes: https://tracker.ceph.com/issues/70307 …

qa/tasks: generalize stuck pg ignorelist entry

---

src/test/neorados/watch_notify.cc

Since we seem to be hitting timeouts on teuthology.
Fixes: https://tracker.ceph.com/issues/70916 …

neorados: Increase timeouts in watch/notify poll tests

---

ceph.spec.in
debian/ceph-test.install

Fix for build break [here](https://jenkins.ceph.com/job/ceph-dev-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos9,DIST=centos9,MACHINE_SIZE=gigantic/57985//consoleFull) cause by [this commit](https://github.com/ceph/ceph/pull/62170/commits/14a11dedc0db05052879771ad849be79678e529a).
```
error: Installed (but unpackaged) file(s) found:
/usr/bin/ceph_ec_consistency_checker
/usr/lib/debug/usr/bin/ceph_ec_consistency_checker-20.3.0-1388.gc706bacd.el9.x86_64.debug
```
Still pending a clean shaman run before review and merge. See [here](https://shaman.ceph.com/builds/ceph/wip-consistency-build-fix/). …

erasure-code: Add ceph_ec_consistency_checker into ceph_test_package

---

.gitmodules

backport tracker: https://tracker.ceph.com/issues/71673
---
backport of https://github.com/ceph/ceph/pull/62616
parent tracker: https://tracker.ceph.com/issues/62804

tentacle: build: Fix opentelemetry-cpp build failure on Noble

---

doc/man/8/rados.rst

Remove the "clonedata" command from the rados manpage.
The "clonedata" command was removed in
https://github.com/ceph/ceph/pull/13008.
Fixes: https://tracker.ceph.com/issues/71943
(cherry picked from commit 1eff1c1147bdb683701a55fbe3ea846fde6937f0) …

reef:  doc/rados: remove clonedata command

---

doc/man/8/rados.rst

Remove the "clonedata" command from the rados manpage.
The "clonedata" command was removed in
https://github.com/ceph/ceph/pull/13008.
Fixes: https://tracker.ceph.com/issues/71943
(cherry picked from commit 1eff1c1147bdb683701a55fbe3ea846fde6937f0) …

tentacle: doc/rados: remove clonedata command

---

src/tools/cephfs/top/cephfs-top

backport tracker: https://tracker.ceph.com/issues/69927
---
backport of https://github.com/ceph/ceph/pull/61621
parent tracker: https://tracker.ceph.com/issues/69669

squid: cephfs-top: exception when terminal size greater than PAD_WIDTH

---

doc/dev/config.rst
doc/mgr/modules.rst

Add comprehensive documentation for defining configuration options in ceph-mgr modules, including all supported properties and their usage.
Previously, the documentation did not explain how to define ceph-mgr module configuration options, despite subtle differences from other Ceph components. This change documents all supported Option properties, their types, and provides clear examples to help module developers properly configure their options.
(cherry picked from commit 121192f4c95df0ee282cecc7237c8ca788e9cfba) …

squid: doc: Document ceph-mgr module configuration options

---

src/include/buffer_raw.h

std::aligned_storage_t was deprecated in C++23, to be prepared for it, let's use alignas for the same behavior.
- …

include/buffer_raw: avoid using std::aligned_storage_t

---

qa/tasks/cephfs/test_mirroring.py

backport tracker: https://tracker.ceph.com/issues/70280
backport tracker: https://tracker.ceph.com/issues/71489
---
backport of https://github.com/ceph/ceph/pull/61076
parent tracker: https://tracker.ceph.com/issues/69232

reef: qa: fix test_cephfs_mirror_stats failure

---

qa/tasks/cephfs/test_journal_repair.py
src/tools/cephfs/Dumper.cc

backport tracker: https://tracker.ceph.com/issues/70285
backport tracker: https://tracker.ceph.com/issues/71037
---
backport of https://github.com/ceph/ceph/pull/60726
parent tracker: https://tracker.ceph.com/issues/68928

squid: cephfs-journal-tool: fix segfault during 'journal import' from invalid dump file

---

qa/tasks/cephfs/test_journal_repair.py
src/tools/cephfs/Dumper.cc

backport tracker: https://tracker.ceph.com/issues/70286
backport tracker: https://tracker.ceph.com/issues/71036
---
backport of https://github.com/ceph/ceph/pull/60726
parent tracker: https://tracker.ceph.com/issues/68928

reef: cephfs-journal-tool: fix segfault during 'journal import' from invalid dump file

---

src/crimson/admin/admin_socket.cc
src/crimson/admin/osd_admin.cc
src/crimson/common/smp_helpers.h
src/crimson/osd/pg_shard_manager.h
src/crimson/osd/shard_services.cc

backport tracker: https://tracker.ceph.com/issues/71843
---
backport of https://github.com/ceph/ceph/pull/63523
parent tracker: https://tracker.ceph.com/issues/71457

tentacle: crimson/osd: Admin Socket fixes

---

src/pybind/mgr/orchestrator/module.py

backport tracker: https://tracker.ceph.com/issues/69514
---
backport of https://github.com/ceph/ceph/pull/61035
parent tracker: https://tracker.ceph.com/issues/69192

squid: mgr/cephadm: mgr orchestrator module raise exception if there is trailing tab in yaml file

---

src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
src/pybind/mgr/cephadm/tests/test_services.py
src/python-common/ceph/deployment/service_spec.py

mgr/cephadm/nvmeof: Add susbsystem cache expiration field to NVMeOF spec file
Fixes https://tracker.ceph.com/issues/72019 …

mgr/cephadm/nvmeof: Add susbsystem cache expiration field to NVMeOF spec file

---

src/os/bluestore/BlueStore.cc
src/test/objectstore/store_test.cc

backport tracker: https://tracker.ceph.com/issues/71874
---
backport of https://github.com/ceph/ceph/pull/63839
parent tracker: https://tracker.ceph.com/issues/71623

tentacle: Fix _setattr() with rare memory alignments

---

src/mon/OSDMonitor.cc

If mon_memory_target is set in the config database and mon_memory_autotune is left at default the mon_memory_target change can be lost. Make sure _set_cache_autotuning() is explicity called any time pcm related settings are changed.
Fixes: https://tracker.ceph.com/issues/70645
(cherry picked from commit b3316073b0f64b4dc49b4fd959a7cbbb21b5778f) …

Reef: OSDMonitor: Make sure pcm is initialised

---

doc/dev/config.rst
doc/mgr/modules.rst

Add comprehensive documentation for defining configuration options in ceph-mgr modules, including all supported properties and their usage.
Previously, the documentation did not explain how to define ceph-mgr module configuration options, despite subtle differences from other Ceph components. This change documents all supported Option properties, their types, and provides clear examples to help module developers properly configure their options.
(cherry picked from commit 121192f4c95df0ee282cecc7237c8ca788e9cfba) …

reef: doc: Document ceph-mgr module configuration options

---

src/crimson/os/seastore/omap_manager/btree/omap_btree_node.h
src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.h

backport of https://github.com/ceph/ceph/pull/63376
- …

tentacle: crimson/os/seastore/omap_manager: handle the cases in which omap nodes are rewritten before seen by users

---

src/rgw/rgw_zone.h

`struct RGWZoneParams` variable `restore_pool` was added with v16 in an earlier release. So to be compatible with those releases, retain that version for `restore_pool` and update version of `dedup_pool` to v17.
Fixes: https://tracker.ceph.com/issues/70628
Signed-off-by: Soumya Koduri [skoduri@redhat.com](mailto:skoduri@redhat.com)
<details> …

 rgw: Fix the version of restore_pool and dedup_pool

---

.github/workflows/redmine-upkeep.yml
src/script/redmine-upkeep.py

Warning: Encountered an error when evaluating display name ${{ format('python3 ceph/src/script/redmine-upkeep.py --github-action --git-dir=./ceph/ {0} {1}
', github.event_name == 'workflow_dispatch' && (inputs.debug && '--debug' || '') || '', github.event_name == 'workflow_dispatch' && format('--limit={}', inputs.limit) || '') }}. The template is not valid. .github/workflows/redmine-upkeep.yml (Line: 54, Col: 14): The following format string is invalid: --limit={}
Error: The template is not valid. .github/workflows/redmine-upkeep.yml (Line: 54, Col: 14): The following format string is invalid: --limit={} …

.github: fix workflow format error

---

src/rgw/driver/rados/rgw_rados.cc

backport tracker: https://tracker.ceph.com/issues/71777
---
backport of https://github.com/ceph/ceph/pull/63443
parent tracker: https://tracker.ceph.com/issues/71423

tentacle: rgw: make sure max_objs_per_shard is appropriate in debugging scenarios

---

src/crimson/osd/scrub/scrub_validator.cc
src/erasure-code/consistency/ECEncoder.cc
src/osd/ECBackend.cc
src/osd/ECBackend.h
src/osd/ECCommon.cc
src/osd/ECCommon.h
src/osd/ECTransaction.cc
src/osd/ECTransaction.h
src/osd/ECUtil.cc
src/osd/ECUtil.h
src/osd/scrubber/scrub_backend.cc
src/test/osd/TestECBackend.cc
src/test/osd/test_ec_transaction.cc
src/tools/CMakeLists.txt
src/tools/ceph-dencoder/osd_types.h
src/tools/ceph_objectstore_tool.cc
src/tools/erasure-code/ceph-erasure-code-tool.cc
src/tools/rados/rados.cc

depends on #63873 (Please only look at final commit)
Tracker: https://tracker.ceph.com/issues/71813
Legacy EC used hinfo attribute to store two things:
1.  Shard size
2. CRCs of the shards
However:
-  Optimized EC stores different object sizes on each shard
-  Optimized EC scrub calculates the correct sizes of shards and checks them, so shard size checks are not needed in hinfo.
-  Bluestore checks the CRC.
-  Seastore checks the CRC:
Seastore supports CRC checks for both meta and data internally.
Upon overwriting an object, Seastore will update CRC and will verify it on full object reads.
As such, the hinfo object is redundant. As such we remove it in  optimized EC:
1. Remove all references/upgrades to hinfo.
2 Delete hinfo attribute if found on recovery/backfill.
3 Redirect all scrub …

osd: Remove all references to hinfo from optimized EC

---

src/rgw/rgw_rest_s3.cc

We came across this issue when running s3-tests suite against a cluster which uses custom "max number of objects per bucket". The custom default value is set as follows
<pre>
sudo ceph config set client.rgw rgw_bucket_default_quota_max_objects 2000000
</pre>
which sets the bucket quota for new users as follows:
<pre>
"bucket_quota": {
"enabled": true,
"check_on_raw": false,
"max_size": -1,
"max_size_kb": 0,
"max_objects": 2000000
},
</pre>
However, test_s3.py::test_account_usage is failing as follows
<pre>
>       assert summary['QuotaMaxBytesPerBucket'] == '-1'
E       AssertionError: assert '2000000' == '-1'
E
E         - -1
E         + 2000000
</pre>
and "summary" objects report
<pre>
{'QuotaMaxBytes': '-1', 'QuotaMaxBuckets': '1000', 'QuotaMaxObjCount': '-1', 'QuotaMaxBytesPerBucket': …

rgw_rest_s3.cc: update how we report bucket quota cfg info for max size (bytes) and max objects

---

qa/suites/fs/workload/tasks/3-snaps/yes.yaml

Fixes: https://tracker.ceph.com/issues/70441 …

qa: increase the wait time to prevent check_counter failing

---

qa/suites/rgw/multifs/tasks/rgw_bucket_quota.yaml
qa/suites/rgw/multifs/tasks/rgw_multipart_upload.yaml
qa/suites/rgw/multifs/tasks/rgw_user_quota.yaml
qa/suites/rgw/thrash/install.yaml
qa/suites/rgw/thrash/workload/rgw_bucket_quota.yaml
qa/suites/rgw/thrash/workload/rgw_multipart_upload.yaml
qa/suites/rgw/thrash/workload/rgw_user_quota.yaml
qa/workunits/rgw/s3_bucket_quota-run.sh
qa/workunits/rgw/s3_multipart_upload-run.sh
qa/workunits/rgw/s3_user_quota-run.sh
qa/workunits/rgw/s3_utilities.pm

backport tracker: https://tracker.ceph.com/issues/71904
---
backport of https://github.com/ceph/ceph/pull/63760
parent tracker: https://tracker.ceph.com/issues/71577

reef: qa/rgw: fix perl tests missing Amazon::S3 module 

---

src/mon/MgrStatMonitor.cc
src/mon/MgrStatMonitor.h

backport tracker: https://tracker.ceph.com/issues/72027
---
backport of https://github.com/ceph/ceph/pull/64004
parent tracker: https://tracker.ceph.com/issues/71857

tentacle: mon/MgrStatMonitor.cc: cleanup pool_availability

---

src/cls/rgw/cls_rgw_types.cc

backport tracker: https://tracker.ceph.com/issues/69409
---
backport of https://github.com/ceph/ceph/pull/60430
parent tracker: https://tracker.ceph.com/issues/68659

reef: rgw: fix empty storage class on display of multipart uploads

---

src/pybind/mgr/dashboard/frontend/src/app/shared/components/grafana/grafana.component.html

fixes: https://tracker.ceph.com/issues/71907
```
Redundant Grafana time picker 
```
```
Grafana iframe has inbuilt time picker , need to remove the angular  time picker 
```
Removed timepicker from all grafana iframes.
Before 
After :  …

mgr/dashboard: Remove the time dropdown from grafana iframe.

---

src/CMakeLists.txt

Adopt C++23 to leverage new standard library features and reduce dependencies on third-party implementations:
Standard library improvements:
- std::expected<> replaces third-party implementation at src/include/expected.hpp
- std::flat_map/std::flat_set replace boost alternatives
- std::stacktrace replaces homebrew implementation at src/common/BackTrace.h
Language improvements:
- Deducing this enables elimination of code duplication
Benefits:
- Reduced maintenance overhead
- Fewer third-party dependencies
- Simplified codebase
This upgrade is supported by our migration to clang-19 (0e5a51b6) and libstdc++ from GCC-11, which provide sufficient C++23 feature coverage for our needs. …

cmake: upgrade CMAKE_CXX_STANDARD from 20 to 23

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-snapshotschedule-list/cephfs-snapshotschedule-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/card-row/card-row.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/components.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/copy2clipboard-button/copy2clipboard-button.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/copy2clipboard-button/copy2clipboard-button.component.scss
src/pybind/mgr/dashboard/frontend/src/app/shared/components/copy2clipboard-button/copy2clipboard-button.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/icon/icon.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/icon/icon.component.scss
src/pybind/mgr/dashboard/frontend/src/app/shared/components/icon/icon.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/icon/icon.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/icons.enum.ts
src/pybind/mgr/dashboard/frontend/src/styles/_carbon-defaults.scss

Fixes https://tracker.ceph.com/issues/71947
Fixes https://tracker.ceph.com/issues/71933
```html
<cd-icon type="success" [size]="Iconsize.size32"></cd-icon >
<cd-icon type="danger"></cd-icon >
<cd-icon type="info"></cd-icon >
```
```typescript
export const ICON_TYPE = {
danger: 'danger',
info: 'info',
success: 'success',
warning: 'warning'
} as const;
```
https://github.com/user-attachments/assets/5b6c1229-4ce6-476d-8a17-a2eb9a4fff3b
- updated icons in inventory card
- adds a type const which needs to be updated further covering more pages in future Prs
- clipboard icon not displaying breaking several places
- clipboard icon on click gets filed primary green color losing the visibility of icon. The icon now remain visible on click
- clipboard button for path and copy in tables on mouseover …

mgr/dashboard: Add generic component for icons

---

src/rgw/rgw_op.cc

backport tracker: https://tracker.ceph.com/issues/72026
---
backport of https://github.com/ceph/ceph/pull/61136
parent tracker: https://tracker.ceph.com/issues/69301

squid: rgw: don't use merge_and_store_attrs() when recreating a bucket

---

doc/cephfs/mount-using-fuse.rst

doc/cephfs: Improve mount-using-fuse.rst
- …

doc/cephfs: Improve mount-using-fuse.rst

---

src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/rgw_op.cc
src/test/rgw/rgw_multi/tests.py

https://tracker.ceph.com/issues/70920 …

rgw/multisite: sync object tagging deletion

---

src/cls/rbd/cls_rbd_client.cc
src/test/cls_rbd/test_cls_rbd.cc

- Remove unused #include "cls/lock/cls_lock_client.h" from cls_rbd_client.cc.
- Remove unused includes in test_cls_rbd.cc …

cls/rbd: remove unused includes

---

src/crimson/os/seastore/seastore_types.h
src/crimson/os/seastore/segment_manager/block.cc

To validate the seastore device by cephadm write a signature "seastore block device" during superblock creation.
Fixes: https://tracker.ceph.com/issues/71954 …

crimson/os/seastore: write "seastore block device" signature in write_superblock

---

doc/radosgw/rgw-cache.rst

Try to improve the language by completely rewriting some sentences. Attempt to format the document more like the rest of the docs. Fix several errors in punctuation, capitalization, spaces etc. Use blocks with bash prompts for CLI commands instead of hardcoded prompts.
Fix section hierarchy and section title underline lengths. Use admonition.
(cherry picked from commit 6e836f8f1e1e53bc7f8d8b497960b100e6b625d6)
- When filling out …

squid: doc/radosgw: Improve rgw-cache.rst

---

doc/radosgw/rgw-cache.rst

Try to improve the language by completely rewriting some sentences. Attempt to format the document more like the rest of the docs. Fix several errors in punctuation, capitalization, spaces etc. Use blocks with bash prompts for CLI commands instead of hardcoded prompts.
Fix section hierarchy and section title underline lengths. Use admonition.
(cherry picked from commit 6e836f8f1e1e53bc7f8d8b497960b100e6b625d6)
- When filling out …

reef: doc/radosgw: Improve rgw-cache.rst

---

doc/cephfs/mount-using-fuse.rst

(cherry picked from commit 329ee7b3038e49cf0def2f2628444e3e90796c05)
- Component …

reef: doc/cephfs: Improve mount-using-fuse.rst

---

qa/suites/crimson-rados/rbd/tasks/rbd_python_api_tests.yaml
qa/suites/crimson-rados/rbd/tasks/rbd_python_api_tests_old_format.yaml
src/test/pybind/pytest.ini
src/test/pybind/test_rbd.py

https://pulpito.ceph.com/matan-2025-07-10_12:44:05-crimson-rados-wip-matanb-crimson-only-enable-tests-distro-crimson-debug-smithi/ …

test/pybind/test_rbd.py: remove skip_if_crimson

---

src/script/redmine-upkeep.py

As it can vary depending on repository size. On my development machine, it produces 8 character abbreviations but the github action is producing 7 character abbreviations. This triggers unnecessary updates. …

script/redmine-upkeep: codify commit abbreviation

---

src/cls/rgw/cls_rgw_types.cc

backport tracker: https://tracker.ceph.com/issues/69408
---
backport of https://github.com/ceph/ceph/pull/60430
parent tracker: https://tracker.ceph.com/issues/68659

squid: rgw: fix empty storage class on display of multipart uploads

---

qa/workunits/mon/test_mon_osdmap_prune.sh

backport tracker: https://tracker.ceph.com/issues/69773
---
backport of https://github.com/ceph/ceph/pull/61397
parent tracker: https://tracker.ceph.com/issues/47838

reef: mon/test_mon_osdmap_prune: Use first_pinned instead of first_committed

---

install-deps.sh
src/crimson/tools/perf_crimson_msgr.cc
src/crimson/tools/perf_staged_fltree.cc
src/test/crimson/test_messenger.cc

Update branch to wip-amat-seastar-may-25
Fixes: https://tracker.ceph.com/issues/71184 …

seastar: bump up seastar submodule

---

qa/suites/orch/cephadm/workunits/task/test_monitoring_stack_basic.yaml
src/pybind/mgr/prometheus/module.py

https://github.com/ceph/ceph/pull/61468 unintentionally broke the http metric service while it removed the code that starts the metrics. adding them back up.
Regression from https://github.com/ceph/ceph/pull/61468/commits/64f590cc8f03c9aab909c3ea5b9f53271ba3c15b#diff-031e09c4297d84a407cf55f8981d38764efc3c37e9827e12e638521f69284e1f …

mgr/prometheus: fix metrics service not coming up

---

src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/tests/test_cephadm.py

Prevent accidental or invalid service type changes for OSD daemons by enforcing that an OSD's service type cannot be changed to a different service type (e.g., mon, mds, etc.)
Fixes: https://tracker.ceph.com/issues/71087
```
root@debian-1:/# ceph orch ls
NAME                       PORTS        RUNNING  REFRESHED  AGE  PLACEMENT
mgr                                         2/2  3m ago     10m  count:2
osd.all-available-devices                     6  3m ago     34s  *
osd.oogabooga                                 0  -          5s   *
root@debian-1:/# ceph orch osd set-spec-affinity mgr 1 2 3 4
Error EINVAL: Service 'mgr' is not an OSD service (type: mgr). OSDs can only be assigned to OSD service specs.
root@debian-1:/# ceph orch osd set-spec-affinity osd.oogabooga 1 2 3 4
Updated service for …
```

mgr/cephadm: disallow changing OSD service type to non-OSD types

---

doc/cephadm/services/nfs.rst
src/pybind/mgr/cephadm/inventory.py
src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/schedule.py
src/pybind/mgr/cephadm/service_discovery.py
src/pybind/mgr/cephadm/services/nfs.py
src/pybind/mgr/cephadm/templates/services/nfs/ganesha.conf.j2
src/pybind/mgr/cephadm/tests/test_service_discovery.py
src/pybind/mgr/cephadm/tests/test_services.py
src/python-common/ceph/deployment/service_spec.py

Changes for this PR:
1. Monitoring_Addr: This is a new requirement form NFS team. NFS always bind monitoring port to any ip. To bind 
monitoring port on specific IP, NFS has introduced a new field 'Monitoring_Addr' in ganesha.conf. 
This PR is updating  NFSSpec to accept monitoring IP/Network from user and update ganesha.conf. Also updating service discovery of NFS for prometheus.
Below parameters are added for monitoring:
```
Spec:
monitoring_ip_addrs:
ceph-node-0: 192.167.100.100
ceph-node-1: 192.167.100.101
monitoring_networks:
- 192.168.124.0/24
```
2. Currently NFS spec have networks section, if network is passed then Bind Addr for NFS will be picked from that network. We are adding a new section ip_addrs to accept bind addr ip.
```
ip_addrs:
ceph-node-0: 192.168.124.100
ceph-node-1: …
```

mgr/nfs: Add Monitoring_Addr parameter to ganesha.conf and provide option for user to provide ips for bind_addr

---

src/pybind/ceph_argparse.py

Ceph orch apply command does not give error if 'placement' is passed as both positional and keyword argument, It uses keyword argument value for configuration
Fixes: https://tracker.ceph.com/issues/69174
Testing logs:
```
[ceph: root@ceph-node-0 /]# ceph orch apply nfs mynfs --port 9090 nfs-ganesha-pool --placement='2'
Invalid command: Duplicate argument 'placement' found.
orch apply nfs <svc_id> [<placement>] [--format {plain|json|json-pretty|yaml|xml-pretty|xml}] [--port <int>] [--dry-run] [--unmanaged] [--no-overwrite] :  Scale an NFS service
Error EINVAL: invalid command
[ceph: root@ceph-node-0 /]# ceph orch apply nfs mynfs --port 9090 nfs-ganesha-pool                
Error EINVAL: Cannot place …
```

mgr/cephadm: Ceph orch apply command does not give error if 'placement' is passed as both positional and keyword argument

---

src/cls/CMakeLists.txt
src/test/cls_rbd/CMakeLists.txt

Remove unused cls_lock_client linkage from cls_rbd_client and ceph_test_cls_rbd
This makes the dependency relationship more explicit and maintainable. …

cmake: Remove unused cls_lock_client linkage 

---

qa/workunits/rgw/test_rgw_d4n.py
src/rgw/driver/d4n/d4n_policy.h
src/rgw/driver/d4n/rgw_sal_d4n.cc
src/rgw/driver/d4n/rgw_sal_d4n.h
src/test/rgw/test_d4n_filter.cc
src/test/rgw/test_d4n_policy.cc
src/test/rgw/test_ssd_driver.cc

These fixes allow the D4N suite and unit test programs to pass. Note: removal of D4N subsuite from RGW suite must be reversed in Tentacle branch. Backports to the Tentacle branch are necessary.
The most recent commit addresses the following tracker issue: https://tracker.ceph.com/issues/71088 …

D4N Test Updates

---

src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.h

preparing commit if the prior are seen by users after the nodes are rewritten
Fixes: https://tracker.ceph.com/issues/71976 …

crimson/os/seastrore/omap_manager: initialize rewritten omap nodes when

---

src/include/cephfs/types.h

This is to print export_ephemeral_random_pin as Double (instead of Integer) with MDS `dump inode` command
Fixes: https://tracker.ceph.com/issues/71944 …

mds: dump export_ephemeral_random_pin as double

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/rgw_client.py

Fixes:  https://tracker.ceph.com/issues/70313
Signed-off-by:  pujaoshahu<pshahu@redhat.com>
Summary:
Request format for creating a bucket notification:
```
{
"bucket_name": "testbucket1",
"notification": "<NotificationConfiguration xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\">\n  <TopicConfiguration>\n    <Id>4</Id>\n    <Topic>arn:aws:sns:default::t7</Topic>\n    <Event>s3:ObjectCreated:*</Event>\n    <Filter>\n      <S3Key>\n        <FilterRule>\n          <Name>prefix</Name>\n          <Value>uploads/</Value>\n        </FilterRule>\n        <FilterRule>\n          <Name>suffix</Name>\n          <Value>.jpg</Value>\n        </FilterRule>\n      </S3Key>\n      <S3Metadata>\n        <FilterRule>\n          <Name>category</Name>\n          <Value>image</Value>\n …
```

mgr/dashboard: Notification endpoints for create ,list and delete

---

src/librados/librados_c.cc

Remove unused header includes from librados_c.cc to reduce unnecessary dependencies. This cleanup was initially motivated by removing unused linkage of cls_lock_client, but expanded to address all unused includes in the file. …

librados: remove unused includes in librados_c.cc

---

doc/radosgw/s3_objects_dedup.rst

Fix sentence that had "different same" to just "different" (verified the right one from the original author).
Remove colon at the end of section titles.
Remove rendered horizontal lines between sections.
Use double backticks for command name.
Use regular apostrophe in one sentence to be consistent with the rest.
Add missing full stop at the end of several sentences.
Very small language improvements in a few sentences.
Use consistent indent in one line.
Remove hyphens from many word pairs and don't capitalize few terms. For consistency with rest of the docs.
Fix typos "spliting" to "splitting", "underlined" to "underlying".
Spell out "thousands" instead of using an apostrophe after the number.
Reformat table to use row separators like rest of the docs instead of empty columns.
Separate …

doc/radosgw: Small improvements in s3_objects_dedup.rst

---

doc/mgr/modules.rst

(cherry picked from commit fc4396d6280fcbf0a95567cff144052d81dcd964)
- Component …

squid: doc: update mgr modules notify_types

---

doc/radosgw/bucket_logging.rst
src/rgw/rgw_bucket_logging.cc
src/rgw/rgw_common.cc
src/rgw/rgw_common.h

The aclRequired field in the bucket log is meant to indicate that an acl was required to authorize the operation. This change introduces a new field in the req_state to track whether an acl was checked to authorize the request.
Fixes: https://tracker.ceph.com/issues/71730 …

rgw: fix aclRequired for bucket-logging

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/nvmeof_cli.py
src/pybind/mgr/dashboard/tests/test_nvmeof_cli.py

added the description needed to register the NVMeoF CLI commands to `ceph --help`
to avoid code duplication, I added the ability to use `EndpointDoc` decorator description as the help string.
fixes: https://tracker.ceph.com/issues/72150 …

mgr/dashboard: add help for nvmeof cli

---

doc/radosgw/config-ref.rst

Edit the section "Lifecycle Settings" in the file
doc/radosgw/config-ref.rst. Remove solecisms and pleonasms and plain old infelicitious formulations. …

doc/radosgw: edit "Lifecycle Settings"

---

doc/radosgw/config-ref.rst

Edit the section "Lifecycle Settings" in the file
doc/radosgw/config-ref.rst. Remove solecisms and pleonasms and plain old infelicitious formulations.
(cherry picked from commit ac2e5f502523d1bf326303e904ccb47236c81fcb) …

squid: doc/radosgw: edit "Lifecycle Settings"

---

doc/mgr/telemetry.rst

This commit edits the third hundred lines in doc/mgr/telemetry.rst.
(cherry picked from commit 3ce61e065121e07e2c37097f1fe6736bdf985e8e) …

tentacle: doc/mgr: edit telemetry (3 of x)

---

src/pybind/mgr/dashboard/frontend/src/app/app-routing.module.ts
src/pybind/mgr/dashboard/frontend/src/app/core/error/error.component.html
src/pybind/mgr/dashboard/frontend/src/app/core/error/error.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/module-status-guard.service.ts

backport tracker: https://tracker.ceph.com/issues/72146
---
backport of https://github.com/ceph/ceph/pull/64447
parent tracker: https://tracker.ceph.com/issues/72145

tentacle: mgr/dashboard: Fix smb module enablement 

---

doc/radosgw/bucket_logging.rst

Trim trailing extra line characters around main title.
Add missing full stops in list items.
Use double backticks for configuration options, data etc.
Linkify reference to REST API.
No hyphen in "regular expression".
Fix section hierarchy by moving "Log Records" up 2 levels and try to make the section title more consistent with another section title.
Try to improve partial sentences and try to simplify one sentence.
Remove whitespace at otherwise empty line.
(cherry picked from commit a19834c2bbdef6feb7b4bf5266d40f4d427a8247) …

tentacle: doc/radosgw: Improve formatting and language in bucket_logging.rst

---

src/common/options/rgw.yaml.in
src/rgw/rgw_lc.cc

We are upstreaming a change we worked on in-house to modify and improve rgw lc processing. As part of a series of changes, we are introducing this change to support sorted listing to improve lc delete performance.
This commit introduces two new configuration variables, rgw_lc_allow_ordered_list and rgw_lc_list_cnt. Which sets the ordered listing, and allows configuring the number of objects per a list request for lc processing.
By default rgw_lc_allow_ordered_list is set to false, and rgw_lc_list_cnt is set to 1000 to match previous behavior.
Signed-off-by: Matthew H [mheler@akmai.com](mailto:mheler@akmail.com) …

rgw: allow lc listing order to be configurable

---

src/mon/MgrMonitor.cc

Formatting of "ceph mgr module force disable" output is missing a space.
Fixes:https://tracker.ceph.com/issues/71262 …

mon/MgrMonitor: add a space before "is already disabled"

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/model/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/nvmeof_cli.py
src/pybind/mgr/dashboard/tests/test_nvmeof_cli.py
src/pybind/mgr/mgr_module.py

Fixed early feedback from @caroav 
* remove not neededceph `gateway info` columns
* add missing parameters to `subsystem add` command
* change `host list` to use  exclusive list annotation and remove not needed column
* change gw to gateway in related commands
* change ns to namespace in related commands
* in text fomat show '' instead of the string 'None' in columns values
* nvme alias commands support
fixes: https://tracker.ceph.com/issues/71980 …

mgr/dashboard: nvmeof cli feedback fixes

---

qa/tasks/thrashosds-health.yaml

backport tracker: https://tracker.ceph.com/issues/72023
---
backport of https://github.com/ceph/ceph/pull/62112
parent tracker: https://tracker.ceph.com/issues/70307

tentacle: qa/tasks: generalize stuck pg ignorelist entry

---

src/script/backport-create-issue

This suppresses the message:
```
./src/script/backport-create-issue:180: SyntaxWarning: invalid escape sequence '\w'
issue['backports'] = set(re.findall('\w+', field['value']))
```
Fixes: https://tracker.ceph.com/issues/71212 …

script/backport-create-issue: fix the syntax warning

---

src/msg/async/AsyncMessenger.cc

`AsyncMessenger::shutdown()` called WorkerProcessor::stop() first, killing the worker threads, then queued a C_drain callback via stack->drain().  If a worker had already exited its event loop it never processed the callback, so drain.wait() blocked forever and the monitor shutdown hung for minutes.
Move stack->drain() ahead of the processors->stop() loop.  With the new order the workers are still alive to acknowledge the drain.
Fixes: https://tracker.ceph.com/issues/<ID>
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatche …

msg: drain stack before stopping processors to avoid shutdown hang

---

debian/cephadm.postinst

cephadm.postinst fails on ubuntu 24.04, because the cephadm user it creates ends up with a `/nonexistent` home directory:
> mkdir: cannot create directory '/nonexistent/.ssh': No such file or directory
on ubuntu 22.04, this user's home directory is `/home/cephadm`
the `adduser` man page for 24.04 includes this new text:
> If no home directory is specified, the default home directory for a new system user is /nonexistent. This directory should never exist on any Debian system, and adduser will never create it automatically.
~~add the explicit `--home /home/cephadm` to preserve the existing behavior~~
commit https://github.com/cbodley/ceph/commit/90bc0369243077c2aaf67f0de2bab5810b217f4e had previously added `--home /home/cephadm`, but that was later removed by commit …

deb/cephadm: add explicit --home for cephadm user

---

src/mon/Elector.cc
src/mon/Elector.h
src/mon/Monitor.cc

backport tracker: https://tracker.ceph.com/issues/71028
---
backport of https://github.com/ceph/ceph/pull/62416
parent tracker: https://tracker.ceph.com/issues/70587
Note: this PR must backported before or together with https://github.com/ceph/ceph/pull/63024

squid: mon: Track and process pending pings after election

---

src/mds/CInode.cc
src/mds/CInode.h
src/mds/ScrubStack.cc
src/messages/MMDSScrub.h

The in-memory and on-disk stats might not match on a directory inode if any of the dirfrag is dirty.
So don't fail the scrub  and mark it as passed if
the dirfrag is dirty.
Fixes: https://tracker.ceph.com/issues/65020 …

mds: mark the scrub passed if dirfrag is dirty

---

PendingReleaseNotes
doc/cephfs/fs-volumes.rst
qa/tasks/cephfs/test_volumes.py
src/pybind/mgr/volumes/fs/async_cloner.py
src/pybind/mgr/volumes/fs/operations/versions/subvolume_base.py
src/pybind/mgr/volumes/fs/operations/versions/subvolume_v1.py

Fixes: https://tracker.ceph.com/issues/71266 …

mgr/vol: keep and show clone source info

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/nvmeof_cli.py
src/pybind/mgr/dashboard/tests/test_nvmeof_cli.py

backport tracker: https://tracker.ceph.com/issues/72165
---
backport of https://github.com/ceph/ceph/pull/64517
parent tracker: https://tracker.ceph.com/issues/72150

tentacle: mgr/dashboard: add help for nvmeof cli

---

qa/suites/rbd/iscsi/cluster/fixed-3.yaml

These seem to be popping up very briefly and don't appear to be relevant to what is being tested
Example failure: https://pulpito.ceph.com/adking-2025-05-21_03:17:03-orch:cephadm-wip-adk-testing-2025-05-20-1959-distro-default-smithi/8291650 …

qa/rbd/iscsi: ignore MON_DOWN warning in logs

---

src/mon/OSDMonitor.cc

If mon_memory_target is set in the config database and mon_memory_autotune is left at default the mon_memory_target change can be lost. Make sure _set_cache_autotuning() is explicity called any time pcm related settings are changed.
Fixes: https://tracker.ceph.com/issues/70645
(cherry picked from commit b3316073b0f64b4dc49b4fd959a7cbbb21b5778f) …

Tentacle: OSDMonitor: Make sure pcm is initialised

---

src/osd/PrimaryLogPG.cc
src/osdc/Objecter.h

backport tracker: https://tracker.ceph.com/issues/72119
---
backport of https://github.com/ceph/ceph/pull/62806
parent tracker: https://tracker.ceph.com/issues/70715

tentacle: mixed balance read and rwordered in read ops

---

src/librbd/api/Group.cc

Fixing the memory leak in error code path of group_snap_remove_by_record and group_snap_rollback_by_record
Changes verified using rbd_mirror.sh unit test
Fixes: https://tracker.ceph.com/issues/71961
Signed-off-by: Miki Patel <miki.patel132@gmail.com> …

librbd: images aren't closed in group_snap_*_by_record() on error

---

src/pybind/mgr/dashboard/frontend/src/app/shared/components/components.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/inline-message/inline-message.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/inline-message/inline-message.component.scss
src/pybind/mgr/dashboard/frontend/src/app/shared/components/inline-message/inline-message.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/inline-message/inline-message.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/enum/icons.enum.ts
src/pybind/mgr/dashboard/frontend/src/styles/_carbon-defaults.scss

Added new component for `inline-message`, which is a custom component based on below design
https://tracker.ceph.com/issues/71870
https://github.com/user-attachments/assets/09668517-f3f2-4365-9b7e-5e62627cc538
**Reference**
https://ibm-products.carbondesignsystem.com/?path=/docs/experimental-onboarding-inlinetip--docs&globals=viewport:basic …

mgr/dashboard: add support for inline-tip notification

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-notification-list/rgw-bucket-notification-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-notification-list/rgw-bucket-notification-list.component.scss
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-notification-list/rgw-bucket-notification-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-notification-list/rgw-bucket-notification-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-topic-list/rgw-topic-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-topic.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/notification-configuration.model.ts
src/pybind/mgr/dashboard/services/rgw_client.py

Fixes:  https://tracker.ceph.com/issues/70880
Signed-off-by:  pujaoshahu <pshahu@redhat.com>
https://github.com/user-attachments/assets/58f535ea-82a2-4731-a95f-cf546fdd5062
Updated UI based on changes made to the filter column. Screencast has also been updated accordingly (details below).
https://github.com/user-attachments/assets/d531b319-d093-4833-90b6-0cf5365dd50e …

mgr/dashboard: Add RGW bucket notification listing in dashboard

---

doc/man/8/radosgw-admin.rst
src/cls/rgw/cls_rgw.cc
src/rgw/driver/rados/rgw_bucket.cc
src/rgw/driver/rados/rgw_bucket.h
src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_rados.h
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/rgw_admin.cc
src/rgw/rgw_sal.h

backport tracker: https://tracker.ceph.com/issues/70824
---
backport of https://github.com/ceph/ceph/pull/62640
parent tracker: https://tracker.ceph.com/issues/70776

reef: rgw: add force option to `radosgw-admin object rm ...`

---

qa/suites/fs/workload/ranks/multi/balancer/random.yaml

backport tracker: https://tracker.ceph.com/issues/72184
---
backport of https://github.com/ceph/ceph/pull/64549
parent tracker: https://tracker.ceph.com/issues/65770

tentacle: qa: increase the randomness to trigger the directory import/export

---

doc/cephfs/mds-config-ref.rst
src/common/options/mds.yaml.in
src/common/options/y2c.py
src/mds/Locker.cc
src/mds/Locker.h
src/mds/MDSRank.cc
src/mds/Server.cc
src/mds/Server.h
src/mds/SimpleLock.h

backport tracker: https://tracker.ceph.com/issues/72164
---
backport of https://github.com/ceph/ceph/pull/64229
parent tracker: https://tracker.ceph.com/issues/71876

tentacle:  mds: nudge log for unstable locks after early reply

---

qa/suites/fs/workload/tasks/3-snaps/yes.yaml

backport tracker: https://tracker.ceph.com/issues/72085
---
backport of https://github.com/ceph/ceph/pull/64305
parent tracker: https://tracker.ceph.com/issues/70441

tentacle: qa: increase the wait time to prevent check_counter failing

---

PendingReleaseNotes
doc/cephfs/fs-volumes.rst
qa/tasks/cephfs/test_volumes.py
src/pybind/mgr/volumes/fs/operations/versions/subvolume_base.py

backport tracker: https://tracker.ceph.com/issues/71853
---
backport of https://github.com/ceph/ceph/pull/62668
parent tracker: https://tracker.ceph.com/issues/70668

tentacle: mgr/vol: include group name in subvolume's pool namespace name

---

src/pybind/mgr/mgr_module.py

The inline function documentation needs an empty
line between description and metadata.
Otherwise automethod from docs renders the metadata as text together with the description instead of
rendering it as function metadata, e.g. parameters and return value.
(cherry picked from commit b521e969b94b93b41a37ef5f9726ed63cb77a97c) …

squid: pybind/mgr: Fix missing empty lines in mgr_module.py

---

doc/cephfs/disaster-recovery.rst

Edit the section "Data Pool Damage" in doc/cephfs/disaster-recovery.rst. This commit is part of the project of improving the data-recovery parts of the CephFS documentation, as requested in the Ceph Power Users Feedback Summary in mid-2025.
(cherry picked from commit 891e9cf2492ad250936171e9b510e8df4996faf9) …

squid: doc/cephfs: edit disaster-recovery.rst

---

doc/cephfs/disaster-recovery.rst

Edit the section "Data Pool Damage" in doc/cephfs/disaster-recovery.rst. This commit is part of the project of improving the data-recovery parts of the CephFS documentation, as requested in the Ceph Power Users Feedback Summary in mid-2025.
(cherry picked from commit 891e9cf2492ad250936171e9b510e8df4996faf9) …

reef: doc/cephfs: edit disaster-recovery.rst

---

qa/suites/rbd/iscsi/cluster/fixed-3.yaml

Backport https://github.com/ceph/ceph/pull/63407 to reef.

reef: qa/rbd/iscsi: ignore MON_DOWN warning in logs

---

src/cephadm/cephadmlib/daemons/smb.py

To start with, all this while, `testparm -s` used to spit out the following lines:
> WARNING: state directory /var/lib/samba should have permissions 0755  for browsing to work
> WARNING: cache directory /var/lib/samba should have permissions 0755 for browsing to work
Putting aside security sensitive stuff like secrets.tdb inside state directory, others by design are expected to be accessed by configured samba users and thus permissions differ between the directory and its contents. With **0770** we denied the access for others and in certain scenarios this denial resulted in real world problems like failure to close file handles and other not so obvious return statuses.
Going by the design and corresponding warning emitted by the `testparm` tool, it is safe and correct to change the mode …

cephadm: Bind mount /var/lib/samba with 0755

---

src/rgw/rgw_auth_keystone.cc

backport tracker: https://tracker.ceph.com/issues/71153
---
backport of https://github.com/ceph/ceph/pull/60515
parent tracker: https://tracker.ceph.com/issues/68327

reef: rgw: make keystone work without admin token(service ac requirement)

---

src/pybind/mgr/cephadm/module.py
src/pybind/mgr/orchestrator/_interface.py
src/pybind/mgr/orchestrator/module.py
src/pybind/mgr/orchestrator/tests/test_orchestrator.py

mgr/cephadm: Provide appropriate exit codes for orch operations
This fix standardized the return behavior of below commands:
- `ceph orch host ok-to-stop`
- `ceph orch host maintenance enter`
- `ceph orch host maintenance exit`
- `ceph orch daemon rm`
To include: 
- exit code 0 on success
- non-zero codes with proper errno mappings (e.g., EINVAL, EBUSY, EALREADY, etc.)
Fixes: 
- https://tracker.ceph.com/issues/70984
- https://bugzilla.redhat.com/show_bug.cgi?id=2302464
Test logs:
```
[ceph: root@ceph-node-0 ~]# ceph -s
cluster:
id:     0b35e016-1cec-11f0-9b67-525400ce7cff
health: HEALTH_OK
services:
mon: 3 daemons, quorum ceph-node-0,ceph-node-1,ceph-node-2 (age 119m) [leader: ceph-node-0]
mgr: ceph-node-0.luupzj(active, since 39s), standbys: ceph-node-1.ivpfjo
osd: 4 osds: 4 up (since …
```

mgr/cephadm: Provide appropriate exit codes for orch operations

---

qa/suites/orch/cephadm/workunits/task/test_monitoring_stack_basic.yaml
src/pybind/mgr/prometheus/module.py
src/pybind/mgr/rook/module.py

backport tracker:
https://tracker.ceph.com/issues/71924
backport  of https://github.com/ceph/ceph/pull/61468
original tracker issue: 
https://tracker.ceph.com/issues/69610 …

tentacle: orch: Pass TLS certificates when Rook orchestrator is used

---

src/krbd.cc

Making msgr2 and ms_mode=prefer-crc as default option for "rbd device map" command
Fixes: https://tracker.ceph.com/issues/72134 …

krbd: "rbd device map" command should use msgr2 by default

---

qa/suites/rbd/iscsi/cluster/fixed-3.yaml

Backport https://github.com/ceph/ceph/pull/63407 to tentacle.

tentacle: qa/rbd/iscsi: ignore MON_DOWN warning in logs

---

src/librbd/api/Group.cc

backport tracker: https://tracker.ceph.com/issues/72229
---
backport of https://github.com/ceph/ceph/pull/64505
parent tracker: https://tracker.ceph.com/issues/71961

tentacle: librbd: images aren't closed in group_snap_*_by_record() on error

---

ceph.spec.in

removing the ceph-common package should not remove ceph configs or logs. rpm -e removes configuration files properly declared if they have not been changed, and if logs need to be removed (eg. for CI), then that should be handled separately.
Fixes: https://tracker.ceph.com/issues/11389 …

ceph.spec.in: don't rm ceph conf and logs in ceph-common postun

---

src/pybind/mgr/smb/handler.py
src/pybind/mgr/smb/internal.py
src/pybind/mgr/smb/proto.py
src/pybind/mgr/smb/staging.py

Backport of https://github.com/ceph/ceph/pull/64310
<details> …

tentacle: mgr/smb: general refactoring with the intent of making future additions easier

---

src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h
src/test/objectstore/test_bluestore_vselector.cc

Hence one can change 'bluestore_volume_selection_reserved' and 'bluestore_volume_selection_reserved_factor' on the fly …

os/bluestore: make vselector reserved* parameters applicable in run-time

---

qa/workunits/rados/test.sh

This commit adds a 90-minute timeout (configurable) for each test in the RADOS test suite
when running in parallel mode. Previously, if a test hung, the entire test
script would hang indefinitely,
causing teutholgoy jobs to time out without useful diagnostic information.
The implementation:
Adds a timeout check in the process monitoring loop
Forcibly terminates tests that run longer than 90 minutes (or whatever
is configured)
Ensures wait is only called after a process has ended or been killed
Improves error reporting to identify which specific test caused the issue
This change prevents indefinite hanging of the test script and provides
better visibility into which test is problematic when timeouts occur.
Also, we added XML output support for the `neorados` test suite,
ensuring test …

qa/workunits/rados/test.sh: add timeout mechanism and more info to workloads with parallel tests

---

src/os/bluestore/BlueStore.cc
src/os/bluestore/BlueStore.h

This macro is never defined and it cannot be defined because it would produce legacy, incompatible encoding.
- …

os/bluestore: Get rid of unused CACHE_BLOB_BL

---

src/os/bluestore/BitmapAllocator.h
src/os/bluestore/HybridAllocator.h
src/os/bluestore/HybridAllocator_impl.h

Fix a memory leak where HybridAllocator's embedded BitmapAllocator (bmap_alloc) was not properly cleaned up during destruction. The issue occurred because virtual function calls in destructors don't dispatch to derived class implementations - when AvlAllocator::~AvlAllocator() calls shutdown(), it invokes AvlAllocator::shutdown() rather than HybridAllocatorBase::shutdown(), leaving bmap_alloc unfreed.
This issue only affects unit tests and does not impact production, as BlueFS always calls shutdown() explicitly when stopping allocators in BlueFS::_stop_alloc()
This change has minimal impact on existing code that already calls shutdown() explicitly, since shutdown() has idempotent behavior and can be safely called multiple times. Additionally, destructors are only invoked during system …

os/bluestore: fix memory leak in HybridAllocator destructor

---

src/common/buffer.cc
src/include/buffer.h
src/include/interval_set.h
src/osd/ECBackend.cc
src/osd/ECCommon.cc
src/osd/ECTransaction.cc
src/osd/ECUtil.cc
src/osd/ECUtil.h
src/test/bufferlist.cc
src/test/osd/TestECBackend.cc
src/test/osd/TestECUtil.cc

Optimised EC already performs "sparse writes":
- Writes are padded out to 4k with zeros if required. 
- Where encoding is required, unmapped is interpreted as zeros.
- Optimised EC does not yet support or use sparse reads. 
The problem is that when recovering a missing shard from coding, we cannot tell the difference between a 4k extent containing zeros to an unmapped 4k region.  This is a major issue because the size of the data on the OSDs will increase significantly when being recovered.
To solve the space issue, this PR plans to convert any recovered 4k buffer to be "unmapped" at the backend. 
There are two techniques that could be employed here:
- Scan for aligned 4k buffers that are zeros
- Perform a sparse read during recovery and skip decode where all shards are unmapped. 
This PR …

OSD: EC recovery zero detect

---

src/cephadm/cephadmlib/daemons/nvmeof.py
src/pybind/mgr/cephadm/services/nvmeof.py
src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
src/pybind/mgr/cephadm/tests/test_services.py
src/python-common/ceph/deployment/service_spec.py

Backport of https://github.com/ceph/ceph/pull/63974
<details> …

tentacle: cephadm/nvmeof: add DSA acceleration support with conditional mounts and privileges

---

qa/suites/fs/workload/tasks/3-snaps/yes.yaml

backport tracker: https://tracker.ceph.com/issues/72084
---
backport of https://github.com/ceph/ceph/pull/64305
parent tracker: https://tracker.ceph.com/issues/70441

squid: qa: increase the wait time to prevent check_counter failing

---

doc/cephfs/cephfs-mirroring.rst
qa/tasks/cephfs/test_mirroring.py
src/pybind/mgr/mirroring/fs/snapshot_mirror.py
src/pybind/mgr/mirroring/module.py

backport tracker: https://tracker.ceph.com/issues/68414
---
backport of https://github.com/ceph/ceph/pull/58966
parent tracker: https://tracker.ceph.com/issues/67292

squid: cephfs_mirror: 'ceph fs snapshot mirror ls' command

---

src/mds/CDentry.cc
src/mds/CDentry.h
src/mds/CDir.cc
src/mds/CDir.h
src/mds/CInode.cc
src/mds/CInode.h
src/mds/LogEvent.h
src/mds/LogSegmentRef.h
src/mds/MDCache.cc
src/mds/MDCache.h
src/mds/MDLog.cc
src/mds/MDLog.h
src/mds/MDSTableClient.cc
src/mds/MDSTableClient.h
src/mds/Migrator.cc
src/mds/Migrator.h
src/mds/Mutation.h
src/mds/Server.cc
src/mds/Server.h
src/mds/events/EMetaBlob.h
src/mds/journal.cc

Fixes: https://tracker.ceph.com/issues/70723 …

mds: add ref counting to LogSegment

---

qa/tasks/cephfs/test_dir_charmap.py
src/mds/Server.cc

 mds: wrong snap check for directory with parent snaps

---

src/mds/SessionMap.cc

This looks like:
[
{
"id": 4446,
"auth_name": {
"type": 16,
"id": "x"
},
...
Which would indicate it's a ceph-mgr with id "x". …

mds: include auth credential in session dump

---

qa/suites/upgrade/reef-x/stress-split/1-start.yaml
qa/suites/upgrade/squid-x/stress-split/1-start.yaml

Since this warning is expected when monitors replace an active MDS daemon due to an higher affinity standby.
Fixes: http://tracker.ceph.com/issues/50279 …

qa/suites/upgrade: add "Replacing daemon mds" to ignorelist

---

doc/cephfs/ceph-dokan.rst

Edit the first 62 lines of doc/cephfs/ceph-dokan. This is part of a larger project whose goal is the improvement of the CephFS documentation. …

doc/cephfs: edit ceph-dokan.rst (1 of x)

---

src/test/rgw/test_d4n_filter.cc

backport tracker: https://tracker.ceph.com/issues/71993
---
backport of https://github.com/ceph/ceph/pull/64017
parent tracker: https://tracker.ceph.com/issues/71711

tentacle: test/d4n: Change D4N filter test cleaning interval values to ints

---

qa/rgw/s3tests-branch.yaml

revert this commit: 46b22fcea6aa8fe6bd18dceaff8eebe6c9e7246b
- …

tentacle: rgw: point to the correct s3test repo and branch

---

qa/tasks/cephfs/test_mds_metrics.py

backport tracker: https://tracker.ceph.com/issues/71948
backport tracker: https://tracker.ceph.com/issues/71951
---
backport of https://github.com/ceph/ceph/pull/62842
parent tracker: https://tracker.ceph.com/issues/68446

tentacle: qa: fix multi-fs tests in test_mds_metrics.py

---

src/blk/BlockDevice.h
src/blk/kernel/KernelDevice.cc
src/blk/kernel/KernelDevice.h
src/common/options/global.yaml.in
src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueStore.cc

We might want to trim OSD devices on mkfs by default if supported. This wouldn't hurt in prod environment and might be helpful for test labs (e.g. teuthology) which frequently recreate OSDs …

os/bluestore: make full device discard on mkfs a default behavior

---

src/crimson/os/seastore/extent_placement_manager.cc
src/crimson/os/seastore/extent_placement_manager.h

This is helpful for us to understand for how much time in some past
period of running the io requests are blocked. …

crimson/os/seastore/async_cleaner: measure io block time

---

src/crimson/os/seastore/extent_placement_manager.cc

In large chunk workload, for instance, when 4MB data is divided into 64KB chunks, the current implementation writes sequentially one by one. On general NVMe SSD, writing large chunk (>=64KB) can lead to relatively higher latency compared to a small write case, resulting in performance degradation. Although NVMe SSD shows the increased latency in such cases, this does not mean that they reach their performance limit, as they can handle multiple concurrent requests.
This commit improves parallelism by using parallel_for_each() to issue writes in parallel.
Performance result:
FIO (1 job, 4 iodepth, 2MB block size)
Before: 200 ~ 300 MB/s
After: 1400 ~ 1600 MB/s …

crimson/os/seastore/rbm: improve large sequential write by issuing writes in parallel

---

src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.cc
src/test/crimson/seastore/test_omap_manager.cc

Fixes: https://tracker.ceph.com/issues/72202 …

crimson/.../omap_btree_node_impl: fix inner node iterate

---

qa/standalone/scrub/osd-scrub-test.sh

The specific test looks for a 'last scrub duration' higher than 0 as a sign that the scrub actually ran.  Previous code fixes guaranteed that even a scrub duration as low as 1ms would be reported as "1" (1s).  However, none of the 15 objects created in this test were designated for the tested PG, which remained empty.  As a result, the scrub duration was reported as "0".
The fix is to create a large enough number of objects so that at least one of them is mapped to the tested PG.
**Note: not a water-tight solution to the '0 seconds scrubs' problem,
as the PR solving https://tracker.ceph.com/issues/71587 wasn't yet
backported into Squid.**
Original tracker: https://tracker.ceph.com/issues/71801
Backport tracker: https://tracker.ceph.com/issues/72067
A backport of …

squid: qa/standalone/scrub: fix "scrubbed in 0ms" in osd-scrub-test.sh

---

src/ceph_osd.cc
src/osd/OSD.cc
src/osd/OSD.h
src/vstart.sh

This PR implements phase 1 of the solution described in the associated tracker.
1. Adds an option called "--run-benchmark" to the ceph-osd process to enable running the existing osd benchmark during the creation of the OSD but before it's added to the cluster. If the option is specified, the benchmark is run just after 'mkfs' is performed on the OSD.
2.  A separate `OSDBenchTest` class is created that can be instantiated when the benchmark is needed to be run. The class has interfaces to perform precheck, prefill, run the actual randwrite test and do the cleanup. It also has interfaces to extract the metrics.
3. The new class in used where applicable and maintains the existing behavior of the "bench" command.
4. The vstart.sh script is modified to run the benchmark if specified and store …

src/ceph_osd, osd: Implement running benchmark during OSD creation - Phase 1

---

doc/radosgw/STS.rst

Tracker: https://tracker.ceph.com/issues/72157 …

doc/radosgw: get caller identity docs

---

src/client/Client.cc
src/test/libcephfs/suidsgid.cc

Prior to fb1b72d, unprivileged users could add mode bits as long as S_ISUID and S_ISGID were not included in the change.
After fb1b72d, unprivileged users were allowed to modify S_ISUID and S_ISGID bits only when no other mode bits were changed in the same operation. This inadvertently permitted unprivileged users to set S_ISUID and/or S_ISGID bits when they were the sole bits being modified.
This behavior should not be allowed. Unprivileged users should be prohibited from setting S_ISUID and/or S_ISGID bits under any circumstances.
This change tightens the permission check to prevent unprivileged users from setting these privileged bits in all cases.
(cherry picked from commit 7028ed21138522495df1e9f8b01195a3c43d47ff)
- To sign and title your commits, please refer to [Submitting Patches …

tentacle: client: prohibit unprivileged users from setting sgid/suid bits

---

src/mds/SessionMap.cc

backport tracker: https://tracker.ceph.com/issues/71380
---
backport of https://github.com/ceph/ceph/pull/62631
parent tracker: https://tracker.ceph.com/issues/70770

tentacle: cephfs: session tracker accounts for killing sessions

---

src/pybind/mgr/volumes/fs/async_cloner.py
src/pybind/mgr/volumes/fs/stats_util.py
src/pybind/mgr/volumes/fs/volume.py

backport tracker: https://tracker.ceph.com/issues/71188
---
backport of https://github.com/ceph/ceph/pull/62638
parent tracker: https://tracker.ceph.com/issues/71019

tentacle: mgr/vol: some improvements for stats_util.py and async_cloner.py

---

qa/workunits/libcephfs/test.sh
src/client/Client.cc
src/client/Client.h
src/include/cephfs/libcephfs.h
src/libcephfs.cc
src/test/libcephfs/CMakeLists.txt
src/test/libcephfs/perfcounters.cc

backport tracker: https://tracker.ceph.com/issues/71377
---
backport of https://github.com/ceph/ceph/pull/62632
parent tracker: https://tracker.ceph.com/issues/71233

tentacle: Wip libcephfs perf dump

---

qa/tasks/cephfs/mount.py

backport tracker: https://tracker.ceph.com/issues/71213
---
backport of https://github.com/ceph/ceph/pull/62709
parent tracker: https://tracker.ceph.com/issues/70817

tentacle: tasks/cephfs/mount: use 192.168.144.0.0/20 for brxnet

---

qa/suites/fs/volumes/tasks/volumes/test/snapshot.yaml
qa/tasks/cephfs/test_volumes.py

backport tracker: https://tracker.ceph.com/issues/71277
---
backport of https://github.com/ceph/ceph/pull/63127
parent tracker: https://tracker.ceph.com/issues/70834

tentacle: mgr/vol: make "snapshot getpath" cmd work with v1 and legacy

---

src/crimson/osd/osd_operations/client_request.cc
src/crimson/osd/osd_operations/client_request.h

* added logs
* rwordered case (https://tracker.ceph.com/issues/71007)
- Component …

crimson/osd/../client_request: fix is_misdirected

---

src/mds/MDCache.cc
src/mds/ScrubStack.cc

backport tracker: https://tracker.ceph.com/issues/71395
---
backport of https://github.com/ceph/ceph/pull/62684
parent tracker: https://tracker.ceph.com/issues/70624

tentacle: mds: use available CInode* for uninline data

---

src/pybind/mgr/cephadm/templates/services/nvmeof/ceph-nvmeof.conf.j2
src/pybind/mgr/cephadm/tests/test_services.py
src/python-common/ceph/deployment/service_spec.py

Backport of https://github.com/ceph/ceph/pull/64382
<details> …

tentacle: mgr/cephadm/nvmeof: Add susbsystem cache expiration field to NVMeOF spec file

---

src/krbd.cc

backport tracker: https://tracker.ceph.com/issues/72266
---
backport of https://github.com/ceph/ceph/pull/64635
parent tracker: https://tracker.ceph.com/issues/72134

tentacle: krbd: "rbd device map" command should use msgr2 by default

---

qa/suites/rbd/iscsi/cluster/fixed-3.yaml

Backport https://github.com/ceph/ceph/pull/63407 to squid.

squid: qa/rbd/iscsi: ignore MON_DOWN warning in logs

---

src/crimson/os/seastore/logical_child_node.h
src/crimson/os/seastore/omap_manager/btree/omap_btree_node_impl.h

Although this is not causing any damage for now, it's violating the invariant that invalid linked child nodes mustn't have parents. …

crimson/os/seastore/logical_child_node: LogicalChildNode should respond to the invalidation event

---

qa/config/crimson_qa_overrides.yaml
src/common/options/crimson.yaml.in
src/crimson/os/seastore/CMakeLists.txt
src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/cache.h
src/crimson/os/seastore/cached_extent.cc
src/crimson/os/seastore/cached_extent.h
src/crimson/os/seastore/extent_pinboard.cc
src/crimson/os/seastore/extent_pinboard.h
src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/seastore_types.h

crimson/os/seastore: introduce 2Q cache replacement algorithm

---

src/client/Client.cc

backport tracker: https://tracker.ceph.com/issues/68693
---
backport of https://github.com/ceph/ceph/pull/59027
parent tracker: https://tracker.ceph.com/issues/65971

reef: client: fixed a bug that read operation hung

---

src/blk/kernel/KernelDevice.cc
src/blk/kernel/KernelDevice.h

This will eliminate a potential race between thread startup and its removal.
Relates-to: https://tracker.ceph.com/issues/71800 …

blk/kernel: improve DiscardThread life cycle.

---

doc/cephfs/ceph-dokan.rst

Edit the first 62 lines of doc/cephfs/ceph-dokan. This is part of a larger project whose goal is the improvement of the CephFS documentation.
(cherry picked from commit 803140e92113ee7919b8188ea3677b472d91ac48) …

tentacle: doc/cephfs: edit ceph-dokan.rst (1 of x)

---

src/rgw/driver/dbstore/common/dbstore.cc
src/rgw/driver/dbstore/common/dbstore.h
src/rgw/driver/dbstore/sqlite/sqliteDB.cc
src/rgw/rgw_sal_dbstore.cc

With commit#8c025045332a8005c6e82308fc17a33d38058734, changes were made to call put_info while erasing bucket attrs. But DBStore wasn't updating attrs as part of put_info operation. This commit addresses the same.
This is backport of [PR#61436](https://github.com/ceph/ceph/pull/61436)
Fixes: https://tracker.ceph.com/issues/72117
<details>
- `jenkins test classic perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-classic/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull-requests/config/definitions/ceph-perf-pull-request …

[reef] rgw/dbstore: Update bucket attrs as part of put_info()

---

src/pybind/mgr/cephadm/tests/test_services.py
src/python-common/ceph/cephadm/images.py

Require all samba images to use the same tag (and share the same base image): avoids version-mismatch confusions & bugs.

mgr/cephadm: use same tag for all samba images

---

doc/rados/configuration/osd-config-ref.rst

(cherry picked from commit 0a2d4b096af168b6646e54a1a5772ad8b6a3c8d6)

squid: doc: Fix links to mClock config reference

---

doc/man/8/rgw-restore-bucket-index.rst
src/rgw/rgw-restore-bucket-index

backport tracker: https://tracker.ceph.com/issues/64772
backport tracker: https://tracker.ceph.com/issues/63459 (bringing tool up to date, so handles this too)
---
backport of https://github.com/ceph/ceph/pull/55885
parent tracker: https://tracker.ceph.com/issues/64765

reef: rgw: make rgw-restore-bucket-index more robust

---

src/rgw/rgw_http_client.cc

backport tracker: https://tracker.ceph.com/issues/71958
---
backport of https://github.com/ceph/ceph/pull/44283
parent tracker: https://tracker.ceph.com/issues/53588

tentacle: rgw: allow specifying ssl certificate for radosgw-admin operations

---

src/pybind/mgr/dashboard/frontend/cypress/e2e/block/mirroring.e2e-spec.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/common/table-helper.feature.po.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/orchestrator/workflow/09-services.e2e-spec.ts
src/pybind/mgr/dashboard/frontend/cypress/e2e/pools/pools.po.ts
src/pybind/mgr/dashboard/frontend/cypress/support/e2e.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.html

- the on 'fail' requires errors to be thrown explicitly
- this is causing all tests to pass as of now irrespective of failures
Ideally we should avoid fail as its discouraged to throw errors but  this require deeper debugging (was introduced for multi-site)
For now, adding this interim fix. …

mgr/dashboard: cypress tests do not fail on failures 

---

src/pybind/mgr/dashboard/frontend/src/app/shared/components/modal/modal.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/modal/modal.component.scss
src/pybind/mgr/dashboard/frontend/src/styles.scss

backport tracker: https://tracker.ceph.com/issues/72098
backport of: https://github.com/ceph/ceph/pull/64445
parent tracker: https://tracker.ceph.com/issues/70720
---
fixes: https://tracker.ceph.com/issues/70720
(cherry picked from commit 89e5e65ace6a303b134d8cad9e2db4988ae4602b)abhidesai6
Signed-off-by: Abhishek Desai [abhishek.desai1@ibm.com](mailto:abhishek.desai1@ibm.com)
```
1. Input field goes black after selecting an input from browser history
2. Tooltip bg-color turns black on hover
```
[Issue 1 ref](https://stackoverflow.com/questions/68250137/why-is-the-background-color-of-my-input-field-changing-after-text-is-entered)
```
1. Browser autofill CSS overrides angular CSS which turns the input field color to black after selecting it. 
2. content-theme for modal dialog was missing, …
```

tentacle: mgr/dashboard: fixed input field black after selecting an autofill browser input 

---

src/mon/MonCommands.h
src/mon/Monitor.cc

Dumping monitor historic operations currently yields no results and incorrectly issues an error message indicating that "mon_enable_op_tracker" is not enabled, even when it should be.
This commit addresses these issues by:
- Adding previously missing commands for historic operations.
- Correcting the dump operations check to only issue an error when "mon_enable_op_tracker" is genuinely not enabled.
- Tracking "mon_enable_op_tracker" changes
- Refactoring and organizing the historic operations dump command code.
- Improving the appearance and clarity of error messages.
Fixes: https://tracker.ceph.com/issues/71725 …

monitor: Enhance historic ops command output and error handling

---

doc/rados/operations/monitoring-osd-pg.rst

Inspired by #64752 these are the last few external link definitions in main that incorrectly include the `.rst` extension.
There is a strong case for eventually moving all internal links to `:doc:` and/or `:ref:`.
- Before: https://docs.ceph.com/en/latest/rados/operations/monitoring-osd-pg/#back-filling
- Rendered PR: https://ceph--64790.org.readthedocs.build/en/64790/rados/operations/monitoring-osd-pg/#back-filling
- When filling …

doc/rados: Fix more mClock links in ops/monitoring-osd-pg.rst

---

src/librbd/api/Group.cc

backport tracker: https://tracker.ceph.com/issues/72232
---
backport of https://github.com/ceph/ceph/pull/64505
parent tracker: https://tracker.ceph.com/issues/71961

reef: librbd: images aren't closed in group_snap_*_by_record() on error

---

doc/man/8/rgw-policy-check.rst

Fix a link to the Ceph docs website that resulted in a 404.
Remove an unused external link definition that was broken anyways due to inclusion of the `.rst` extension.
- Before: https://docs.ceph.com/en/latest/man/8/rgw-policy-check/
- Rendered PR: https://ceph--64789.org.readthedocs.build/en/64789/man/8/rgw-policy-check/ …

doc/man/8: Fix links in rgw-policy-check.rst

---

doc/rados/operations/erasure-code.rst

Answers on the question at https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/APNVQH5LEFM3Y7SQ6MYAQU5TF4HYR3GG/ (_Changing the failure domain of an EC cluster still shows old profile_)
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull-requests/config/d …

doc: Erasure Code: Document set CRUSH rule precedence vs EC profile

---

doc/jaegertracing/index.rst
doc/man/8/ceph.rst
doc/rados/operations/devices.rst
doc/rados/troubleshooting/log-and-debug.rst
doc/radosgw/lua-scripting.rst
doc/radosgw/multisite.rst
doc/radosgw/pools.rst
doc/rbd/iscsi-target-cli.rst
doc/start/hardware-recommendations.rst

Labels mostly existed already but add labels in 2 files.
Add missing closing quotation mark in `rados/troubleshooting/log-and-debug.rst`.
Also fixes the link in `doc/radosgw/lua-scripting.rst` to anchor in `doc/jaegertracing/index.rst` that used a wrong anchor.
Links to each individual hunk of the patch, hopefully this makes reviewing faster:
`doc/jaegertracing/index.rst` `doc/man/8/ceph.rst` just adding a label, no change in rendered docs:
- https://ceph--64803.org.readthedocs.build/en/64803/jaegertracing/
- https://ceph--64803.org.readthedocs.build/en/64803/man/8/ceph/
`doc/rados/operations/devices.rst`:
- Before: https://docs.ceph.com/en/latest/rados/operations/devices/#identifying-physical-devices
- Rendered PR: https://ceph--64803.org.readthedocs.build/en/64803/rados/operations/device …

doc: Use ref instead of full URLs for intra-docs links

---

qa/suites/upgrade/reef-x/stress-split/1-start.yaml
qa/suites/upgrade/squid-x/stress-split/1-start.yaml

The warnings are expected as the MDSs are upgraded and restarted.
Fixes: http://tracker.ceph.com/issues/71615
- …

qa/suites/upgrade: update ignorelist with cephfs specific warnings (under stress-split)

---

src/test/run-cli-tests

Previously, run-cli-tests ignored all environment variables from the parent process to ensure a clean test environment. However, this also dropped sanitizer settings (ASAN_OPTIONS and LSAN_OPTIONS) needed when AddressSanitizer is enabled.
This causes test failures with TCMalloc due to false-positive leak reports from TCMalloc's internal objects, which is a known issue documented in Google's C++ style guide. While recent gperftools releases have fixed this, Ubuntu Jammy still ships with an older version that triggers these warnings.
This change preserves sanitizer environment variables while maintaining the clean test environment for other variables.
Note: Once we upgrade to newer gperftools, we can remove the related suppression rule in qa/lsan.supp.
The test failure with TCMalloc looks …

test/run-cli-tests: inherit ASAN_OPTIONS and LSAN_OPTIONS

---

doc/rados/operations/health-checks.rst
qa/standalone/osd/osd-rep-recov-eio.sh
src/osd/OSD.cc
src/osd/OSD.h

backport tracker: https://tracker.ceph.com/issues/68780
---
backport of https://github.com/ceph/ceph/pull/54954
parent tracker: https://tracker.ceph.com/issues/54182

reef: osd: add clear_shards_repaired command

---

CMakeLists.txt
doc/dev/release-checklists.rst
src/ceph_release

ceph_release, doc, CMakeLists.txt: update tentacle to rc phase

---

doc/radosgw/barbican.rst
doc/radosgw/compression.rst
doc/radosgw/d3n_datacache.rst
doc/radosgw/encryption.rst
doc/radosgw/keystone.rst
doc/radosgw/kmip.rst
doc/radosgw/multisite.rst
doc/radosgw/s3/authentication.rst
doc/radosgw/vault.rst
doc/radosgw/zone-features.rst

- Add a label at beginning of referenced files if missing.
- Updated links targeting files: compression encryption keystone
Cleaned hyperlinks usage in `kmip.rst`:
- Some links were using anonymous links (double underscore) unnecessarily (also in `multisite.rst`).
- Some links were not using backticks, add for consistency.
- Move anonymous link definition to after the ordered list to avoid unnecessary empty line between list items.
Use an already existing label for 2 intra-docs links that used full URLs in `multisite.rst` `pools.rst`.  
Use an already existing label for intra-docs link instead of file name reference in …

doc/radosgw: Use ref for hyperlinks, 2nd batch

---

doc/radosgw/kmip.rst

Major rewrite of the last section that is a copypasta from `vault.rst`:
- "engines" are relevant only to Hashicorp Vault and not KMIP
- leave only 1 copy of the 2 identical CLI examples
- talk about KMIP and not Vault, it is an alternative to Vault
Also fix other mention of "Vault" into "KMIP".
Auto-generate contents list instead of hardcoding it.
Use '=' in `ceph.conf` example, I believe ':' cannot be used.
Capitalize "Ceph", "Python", "KMIP", "OpenSSL", "PyKMIP" consistently.  
Call it consistently "Ceph Object Gateway".
Format "pykmip" in italic when referring to the binary.  
Hyphen in "PEM-encoded" along with capitalization.  
Use double backticks for data.
Spell out a lonesome number "1" in text.  
Fix typo "correspondent" to "corresponding".
Promptify CLI commands.
Use title case …

doc/radosgw: Small improvements in kmip.rst

---

doc/rados/operations/erasure-code.rst
doc/rados/operations/pools.rst
doc/rados/troubleshooting/troubleshooting-osd.rst

Instead of external links use :ref: where dst labels exist already in: 
- `operations/erasure-code.rst`
- `operations/pools.rst` - also fixes 1 broken anchor in the link
- `troubleshooting/troubleshooting-osd.rst`
Use link text generation where it is reasonably close to previous manual link text.
Delete some unused link definitions.
`operations/erasure-code.rst`:
- Before: https://docs.ceph.com/en/latest/rados/operations/erasure-code/
- Rendered PR: https://ceph--64838.org.readthedocs.build/en/64838/rados/operations/pools/
`operations/pools.rst`:
- Before: https://docs.ceph.com/en/latest/rados/operations/pools/
- Rendered PR: https://ceph--64838.org.readthedocs.build/en/64838/rados/operations/pools/
`troubleshooting/troubleshooting-osd.rst`:
- Before: …

doc/rados: Use ref instead of relative external links

---

doc/cephfs/createfs.rst
doc/rados/configuration/pool-pg-config-ref.rst
doc/rados/operations/erasure-code-profile.rst
doc/rados/operations/erasure-code.rst
doc/rados/operations/pools.rst

Documentation updates for the new erasure coding optimizations. This just makes updates to the main part of the docs, will have a separate PR to make updates to the internals/design documentation
* Document new pool flag allow_ec_optimizations
* Reference new conf setting osd_pool_default_flag_ec_optimizations
* Add section describing Erasure Code Optimizations …

Doc: Erasure Coding enhancements for tentacle

---

doc/rados/operations/add-or-rm-osds.rst
doc/rados/troubleshooting/troubleshooting-osd.rst

2 files linked to filesystem-recommendations.rst which was removed around the year 2017.
I understand this was relevant only for Filestore. So simply remove the references to this file & the link definition if one was used.
`troubleshooting/troubleshooting-osd.rst`:
- Before: https://docs.ceph.com/en/latest/rados/troubleshooting/troubleshooting-osd/#filesystem-issues
- Rendered PR: https://ceph--64840.org.readthedocs.build/en/64840/rados/troubleshooting/troubleshooting-osd/#filesystem-issues
`operations/add-or-rm-osds.rst`:
- Before: https://docs.ceph.com/en/latest/rados/operations/add-or-rm-osds/#deploying-your-hardware
- Rendered PR: https://ceph--64840.org.readthedocs.build/en/64840/rados/operations/add-or-rm-osds/#deploying-your-hardware
- To sign and title your commits, please refer …

doc/rados: Remove obsolete fs-recommendations links

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-list/rbd-list.component.ts

fixes: https://tracker.ceph.com/issues/72288
```
Mirrored images have incorrect info in the GUI
```
```
Epoch time generated was in milliseconds, but dateCoversion pipe expects it to be in seconds. 
Changed the epoch into seconds instead of milliseconds. 
``` …

mgr/dashboard: Fixed incorrect snapshot scheduled date for rbd block in GUI

---

src/common/options/rgw.yaml.in
src/rgw/rgw_rest_sts.cc
src/rgw/rgw_rest_sts.h

Addresses a couple of issues including:
- When checking if a JWT can be validated with a JWK, if the validation fails, an exception is thrown instead of trying other keys. This would mean that unless the correct key is first in the JWKS array, validation would fail. To address this, I removed the exceptions inside of the loop and only throw if no JWKs match the JWT
- The certificate endpoint was being validated each time inside of the loop. I moved this to the beginning of validation as this only needs to be done once.
Tracker: https://tracker.ceph.com/issues/54562 …

rgw: check all JWKS for STS

---

doc/cephfs/troubleshooting.rst

Edit "Stuck in up:replay" under the "Stuck During Recovery" section of doc/cephfs/troubleshooting.rst. I had planned to edit the entire "Stuck During Recovery" section in a single commit, but I think that the material is too involved for that.
(cherry picked from commit 969c01fd54741679ec52e081e99ca523bf83ec88) …

tentacle: doc/cephfs: edit troubleshooting.rst

---

doc/cephfs/troubleshooting.rst

Edit "Stuck in up:replay" under the "Stuck During Recovery" section of doc/cephfs/troubleshooting.rst. I had planned to edit the entire "Stuck During Recovery" section in a single commit, but I think that the material is too involved for that.
(cherry picked from commit 969c01fd54741679ec52e081e99ca523bf83ec88) …

squid: doc/cephfs: edit troubleshooting.rst

---

doc/cephfs/troubleshooting.rst

Edit "Stuck in up:replay" under the "Stuck During Recovery" section of doc/cephfs/troubleshooting.rst. I had planned to edit the entire "Stuck During Recovery" section in a single commit, but I think that the material is too involved for that.
(cherry picked from commit 969c01fd54741679ec52e081e99ca523bf83ec88) …

reef: doc/cephfs: edit troubleshooting.rst

---

doc/install/clone-source.rst
doc/install/get-packages.rst
doc/install/index_manual.rst
doc/install/install-storage-cluster.rst
doc/install/manual-deployment.rst
doc/install/manual-freebsd-deployment.rst

Linkify first mention of config file to ceph.conf docs in:
- install-storage-cluster.rst
- manual-deployment.rst
- manual-freebsd-deployment.rst
Use ref instead of an external link in:
- clone-source.rst
- get-packages.rst
- index_manual.rst
- install-storage-cluster.rst
- manual-deploymen.rst
- manual-freebsd-deployment.rst
Only where a label already exists at the destination.  
Delete the old link definition if one was used previously.  
That should be about all external links in install/ that can use existing labels for ref.
Fix an instance of "the a" into just "a" that is consistent with other similar mentions in manual-freebsd-deployment.rst.
Links to individual hunks:
`doc/install/clone-source.rst`:
- Before: https://docs.ceph.com/en/latest/install/clone-source/#choose-a-branch
- …

doc/install: Linkify mention of ceph.conf and use ref for links

---

src/common/json/OSDStructures.cc
src/common/json/OSDStructures.h
src/test/osd/ceph_test_rados_io_sequence/ceph_test_rados_io_sequence.cc
src/test/osd/ceph_test_rados_io_sequence/ceph_test_rados_io_sequence.h

Fix preventing sequence 10 working correctly in ceph_test_rados_io_sequence due to test_recovery not being passed through correctly. Also adds an error message for when trying to use the --parallel command with --testrecovery due to the two not being compatible.
Finally adds a small change to set an application for any pools created by the IO Sequence tool to prevent Ceph giving warnings that no application is set.
Fixes issue introduced in commit d8712e67221d4ca27c024adad4628829df425970 …

test/osd: Fix pack for minor issues in ceph_test_rados_io_sequence

---

src/crimson/os/seastore/async_cleaner.h

This commit fixes incorrect total space reporting when using multiple shards in RBM. Only reporting is incorrect, while underlying RBM mechanism works correctly.
The following output shows a case where 2 shards are used on a 930GB device.
Before:
cluster:
id:     05af346a-e3b2-47a4-93c3-637287ebef6a
health: HEALTH_WARN
11 mgr modules have failed dependencies
services:
mon: 1 daemons, quorum a (age 12s) [leader: a]
mgr: x(active, since 11s)
osd: 1 osds: 1 up (since 6s), 1 in (since 9s)
data:
pools:   0 pools, 0 pgs
objects: 0 objects, 0 B
usage:   30 GiB used, 1.8 TiB / 1.8 TiB avail
pgs:
After:
cluster:
id:     57b57c65-5d8a-4203-8a75-a6829b573edb
health: HEALTH_WARN
11 mgr modules have failed dependencies
services:
mon: 1 daemons, quorum a (age 13s) [leader: a]
mgr: x(active, since 11s) …

crimson/os/seastore: fix incorrect total space reporting when using multiple shards in RBM

---

doc/rados/operations/erasure-code.rst

Add a note to doc/rados/operations/erasure-code.rst to warn future backporters against adding the section "Erasure Coding Optimizations" to versions of the documentation prior to the Tentacle release. …

reef: doc/rados: document section absent in release < T

---

doc/rados/configuration/mon-config-ref.rst
src/common/options/mon.yaml.in
src/nvmeof/NVMeofGwMonitorClient.cc
src/nvmeof/NVMeofGwMonitorClient.h

This change introduces a timeout (in seconds) after which the NVMeoF gateway will panic if it does not receive the initial map from the monitor. …

src/nvmeof/NVMeofGwMonitorClient: connect panic

---

src/cephadm/cephadmlib/daemons/nvmeof.py
src/pybind/mgr/cephadm/tests/test_services.py
src/python-common/ceph/deployment/service_spec.py

The NVMe-oF gateway fails to start with podman when DSA acceleration is enabled but the DSA device file (/dev/dsa) doesn't exist on the host. While docker automatically creates missing source files during mount operations, podman is stricter and requires the source path to exist beforehand.
- changed default behavior: set `enable_dsa_acceleration` to `False` by default, making DSA acceleration opt-in rather than opt-out.
- added prepare_data_dir method: Implemented a method that creates the /dev/dsa directory when DSA acceleration is enabled and the device file is missing, to make podman happy.
- updated tests: modified test configurations to reflect the new default value. …

nvmeof: create /dev/dsa if DSA acceleration is enabled and the device is missing

---

src/crimson/os/seastore/btree/fixed_kv_node.h
src/crimson/os/seastore/lba/lba_btree_node.h
src/crimson/os/seastore/linked_tree_node.h
src/test/crimson/seastore/test_omap_manager.cc

I believe the `pivot_idx` should be understood as defined in the global index space of the combined left and right nodes. Since each key may vary in byte size, a `pivot_idx` equal to `r_size` can still lead to a valid rebalancing. From this perspective, I think it's sufficient to only exclude the case where `pivot_idx == l_size`, as that would result in no actual redistribution between the nodes.
Fixes: https://tracker.ceph.com/issues/72303 …

crimson/.../linked_tree_node: fix pivot_idx assertion in balancing

---

.mailmap
.organizationmap
src/client/Client.cc
src/client/Client.h
src/include/cephfs/libcephfs.h
src/libcephfs.cc
src/test/libcephfs/CMakeLists.txt
src/test/libcephfs/recordlock_hl.cc

This PR extends the Ceph Client and the libcephfs library with high-level functions that perform record locking. Those functions work on file descriptors rather than on file handles as the low-level functions, ceph_ll_setlk and ceph_ll_getlk, do.
Fixes: https://tracker.ceph.com/issues/69277
Signed-off-by: Giorgos Kappes <giorgos@giorgoskappes.com

libcephfs: New feature - add ceph_setlk and ceph_getlk functions

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/rules-list/rules-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/rules-list/rules-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/prometheus-alert.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/prometheus-alert.service.ts

- /rules ar epolled every 5 seconds on every page
- it is only required for alerts page where full rules list is shown in `Alerts` tab
- also added observable for getting rules instead of plain array
It has significant perf improvement:
https://github.com/user-attachments/assets/b961e2c3-d4eb-411b-aa8e-2b2be0825dc9

mgr/dashboard: Stop rules api being polled on every page

---

doc/radosgw/notifications.rst

Fix ordering of list items so that the sub-list is after the parent list item referring to it.
Also fix multiple formatting errors in the same unordered list.
Fix unordered list rendered as a single sentence due to missing empty line.
Break many long lines around standard line length.
Don't use hyphen for "regular expressions".
Use double backticks for data like configuration parameters.
Fix double space in an example CLI command.
Don't list same parameter "user/password" in multiple list items, instead just list all concerns under the same list item.
Start sentences with capital case and end in full stop consistently.
Trim section title formatting syntax to text length.
Capitalize "URI" and "Kafka" consistently.
Use quotation marks in one occurrence of the value "true" instead of single …

doc/radosgw: Small fixes and improvements in notifications.rst, part 1

---

monitoring/ceph-mixin/dashboards_out/smb-overview.json

backport tracker: https://tracker.ceph.com/issues/72538
---
backport of https://github.com/ceph/ceph/pull/64719
parent tracker: https://tracker.ceph.com/issues/72308

tentacle: monitoring: Add per share metrics to SMB dashboard

---

src/common/interval_map.h
src/osd/ECUtil.h
src/test/common/test_interval_map.cc

backport tracker: https://tracker.ceph.com/issues/72367
---
backport of https://github.com/ceph/ceph/pull/63844
parent tracker: https://tracker.ceph.com/issues/72366

tentacle: interval_map: Add non-const iterators 

---

src/crimson/os/seastore/segment_manager/ephemeral.cc

- Anonymous mmap is zero-filled on first access by the kernel, so the 1 GB memset(0) performed on every init routine was redundant and has been removed
- Replaced fixed 1ms sleep calls with seastar::yield() to eliminate wall-clock delays while still yielding execution to the scheduler
This patches does not bring as big of a win as #64810, but still provides a meaningful improvement.
#64810 only
```
1/12 Test #276: unittest-transaction-manager ............   Passed  603.54 sec
2/12 Test #277: unittest-omap-manager ...................   Passed  973.02 sec
3/12 Test #278: unittest-btree-lba-manager ..............   Passed   99.77 sec
4/12 Test #279: unittest-seastore-journal ...............   Passed    4.89 sec
5/12 Test #280: unittest-seastore-cache .................   Passed    2.59 sec …
```

crimson/.../ephemeral: faster seastore eph dev

---

src/test/librbd/fsx.cc

Fixes: https://tracker.ceph.com/issues/72454 …

test/librbd/fsx: initialize effective_size variable

---

container/Containerfile
container/build.sh

Update the Containerfile and the build.sh script such that an environment variable `CUSTOM_CEPH_REPO_URL` specifying the URL of a YUM/DNF repo file will be used instead of the typical Ceph CI infrastructure as the source for ceph project packages in the image.
I tried to keep the changes as minimal as possible while allowing me to build images based on local builds of RPMs (using build-with-container.py).
Hosting the RPMs and the repo file are left as an exercise for the reader.
<details>
- `jenkins test classic perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-classic/) | [Jenkins Job …

container: support building a container image with custom packages

---

doc/man/8/cephadm.rst

Update the docs to reflect the true behavior of `--orphan-initial-daemons` flag. See the code for [reference](https://github.com/ceph/ceph/blob/main/src/cephadm/cephadm.py#L5004): 
```python
parser_bootstrap.add_argument(
'--orphan-initial-daemons',
action='store_true',
help='Set mon and mgr service to `unmanaged`, Do not create the crash service')
``` …

doc/man/cephadm: update `--orphan-initial-daemons` argument description

---

doc/cephfs/troubleshooting.rst

Edit the "Dynamic Debugging" section of doc/cephfs/troubleshooting.rst.
- Component …

doc/cephfs: edit troubleshooting.rst

---

.github/dependabot.yml

dependabot: stop dashboard npm upgrade PRs

---

src/rgw/driver/rados/rgw_datalog.cc

Recovery is so conservative it creates many, many datalog entries, slowing sync.
Fixes: https://tracker.ceph.com/issues/72174 …

tentacle: rgw/multisite: Don't rerun recovery periodically

---

doc/cephadm/services/smb.rst
doc/mgr/smb.rst
src/cephadm/cephadmlib/daemons/smb.py
src/pybind/mgr/cephadm/schedule.py
src/pybind/mgr/cephadm/serve.py
src/pybind/mgr/cephadm/services/smb.py
src/pybind/mgr/smb/handler.py
src/pybind/mgr/smb/resources.py
src/python-common/ceph/deployment/service_spec.py

Backport of https://github.com/ceph/ceph/pull/64142
<details> …

tentacle: smb: support custom ip address binds

---

src/pybind/mgr/dashboard/services/nvmeof_client.py
src/pybind/mgr/dashboard/services/nvmeof_conf.py

backport tracker: https://tracker.ceph.com/issues/72560
---
backport of https://github.com/ceph/ceph/pull/64753
parent tracker: https://tracker.ceph.com/issues/71640

tentacle: mgr/dashboard: fix nvmeof mtls

---

src/mds/MDCache.cc
src/mds/MDCache.h

In MDCacheIOContext subclasses, the track parameter, when set to false, is ignored due to C++ virtual inheritance. Only the most-derived class can initialize virtual bases.
This commit ensures all subclasses adopt the default track = true, eliminating confusion and potential errors from non-functional constructor parameters. …

mds: fix ineffective 'false' parameter due to virtual inheritance

---

qa/tasks/cephfs/volumes/test_clone_stats.py

test_for_6_ongoing_clones fails some times in testing with teuthology
since clones finish sooner than expected causing progress bar message
to have less than 6 clones which results in test failure.
Fixes: https://tracker.ceph.com/issues/71434 …

qa/cephfs: increase clones for test_for_6_ongoing_clones

---

src/pybind/mgr/dashboard/frontend/src/app/shared/api/multi-cluster.service.ts

Since its not returning any subscription back to the `this.subs` property, those subscriptions are not properly closed in the workbench-layout when its destroyed. So ensuring proper return
Fixes: https://tracker.ceph.com/issues/72530 …

mgr/dashboard: close token status subscription properly

---

src/pybind/rados/c_rados.pxd
src/pybind/rados/mock_rados.pxi
src/pybind/rados/rados.pyx
src/test/pybind/test_rados.py

pybind/rados: Add list_lockers() and break_lock() to Rados Python interface
Fixes: https://tracker.ceph.com/issues/72544 …

pybind/rados: Add list_lockers() and break_lock() to Rados Python interface

---

qa/standalone/scrub/osd-scrub-dump.sh
qa/standalone/scrub/scrub-helpers.sh

… functionality.
The new version of osd-scrub-dump.sh is designed to allow multiple "corruption methods" on a subset of objects. The functionality includes specifying:
- the number of objects created;
- the number to have their Primary version modified;
- the number to have their Replicas modified;
- the set of "manipulations" to perform on the objects.

qa/standalone/scrub: re-code osd-scrub-dump.sh to test scrub repair

---

src/client/Client.cc

backport tracker: https://tracker.ceph.com/issues/68248
---
backport of https://github.com/ceph/ceph/pull/56776
parent tracker: https://tracker.ceph.com/issues/65389

reef: client: fix d_reclen for readdir

---

qa/tasks/cephfs/cephfs_test_case.py
qa/tasks/cephfs/filesystem.py
qa/tasks/cephfs/test_exports.py
src/mds/Migrator.cc
src/mds/Server.cc
src/mds/Server.h
src/mds/SessionMap.cc
src/mds/SessionMap.h

backport tracker: https://tracker.ceph.com/issues/68955
---
backport of https://github.com/ceph/ceph/pull/51766
parent tracker: https://tracker.ceph.com/issues/61459

reef: mds: session in the importing state cannot be cleared if an export subtree task is interrupted while the state of importer is acking

---

qa/suites/fs/workload/tasks/5-workunit/kernel_untar_build.yaml

backport tracker: https://tracker.ceph.com/issues/69368
---
backport of https://github.com/ceph/ceph/pull/60640
parent tracker: https://tracker.ceph.com/issues/68855

reef: qa: use a larger timeout for kernel_untar_build workunit

---

src/mds/MetricsHandler.cc
src/mds/MetricsHandler.h

backport tracker: https://tracker.ceph.com/issues/69360
---
backport of https://github.com/ceph/ceph/pull/60653
parent tracker: https://tracker.ceph.com/issues/68865

reef: mds: do not process client metrics message with fast dispatch

---

src/crimson/osd/scrub/scrub_validator.cc
src/osd/ECBackend.cc
src/osd/ECBackend.h
src/osd/ECCommon.cc
src/osd/ECCommon.h
src/osd/ECTransaction.cc
src/osd/ECTransaction.h
src/osd/ECUtil.cc
src/osd/ECUtil.h
src/osd/scrubber/scrub_backend.cc
src/test/osd/TestECBackend.cc
src/test/osd/test_ec_transaction.cc
src/tools/CMakeLists.txt
src/tools/ceph-dencoder/osd_types.h
src/tools/ceph_objectstore_tool.cc
src/tools/erasure-code/ceph-erasure-code-tool.cc
src/tools/rados/rados.cc

backport tracker: https://tracker.ceph.com/issues/72363
---
backport of https://github.com/ceph/ceph/pull/63960
parent tracker: https://tracker.ceph.com/issues/71813

tentacle: osd: Remove all references to hinfo from optimized EC

---

src/pybind/mgr/dashboard/frontend/src/app/shared/api/multi-cluster.service.ts

backport tracker: https://tracker.ceph.com/issues/72633
---
backport of https://github.com/ceph/ceph/pull/64980
parent tracker: https://tracker.ceph.com/issues/72530

tentacle: mgr/dashboard: close token status subscription properly

---

src/crimson/os/seastore/extent_pinboard.cc

fix https://tracker.ceph.com/issues/72529 …

crimson/os/seastore/2Q: don't add empty extents to the warm out queue

---

src/osd/scrubber/pg_scrubber.cc

'auto-repair' scrubs are limited to a maximum of
'scrub_auto_repair_num_errors' damaged objects.
However, operator-initiated repairs should not be limited by that number. Alas, a bug in a previous commit
(3904b67) modified the code in such a way that it applied the 'scrub_auto_repair_num_errors' limit to all repairs, including operator-initiated ones. This commit fixes that.
Fixes: https://tracker.ceph.com/issues/72438
Note: the fix is similar to 'Tentacle' & 'main' fixes (PR#64860 & PR#64849), but - as the surrounding code was changed, this is not a backport.

squid: osd/scrub: do not limit operator-initiated repairs

---

src/cephadm/cephadmlib/daemons/smb.py
src/pybind/mgr/smb/tests/test_validation.py
src/pybind/mgr/smb/validation.py
src/python-common/ceph/deployment/service_spec.py
src/python-common/ceph/smb/constants.py

Fixes a mistake in 09da84fe1879 when we added a new service/port for the remote-control and fixes a mistake in 4180cddc1a08 where the port name is based on lowercasing the enum name (as that value will have an underscore instead of dash as generated by the mgr).
Take the opportunity to use common constants for some of these smb related things by creating a new directory under python-common/ceph, specifically so these common things can be used by the mgr code, cephadm code, and/or other parts of python-common. …

smb: fix custom ports feature with remote-control sidecar

---

src/pybind/mgr/dashboard/frontend/CMakeLists.txt
src/script/build-with-container.py

Add an optional NPM_CACHEDIR environment variable to serve as the cache parameter for npm in the dashboard frontend build.  The idea is to allow it to persist across builds so that we decrease the load on registry.npmjs.org, which has been throttling our requests when using build-with-container.py, and also hopefully improve the time of the frontend npm operations.
build-with-container.py also grows a --npm-cache-path option to allow setting it for container builds and passing the envvar to the build.
Fixes: https://tracker.ceph.com/issues/72298 …

pybind/mgr/dashboard/frontend: add NPM_CACHEDIR envvar, use in bwc

---

src/ceph-volume/ceph_volume/devices/raw/list.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_zap.py
src/ceph-volume/ceph_volume/tests/devices/raw/test_list.py

ceph-volume: avoid RuntimeError on ceph-volume raw list with non-existent loop devices

---

src/os/Transaction.h

Initialize unused1, unused2, and unused3 fields to zero in TransactionData to ensure consistent encoding/decoding behavior.
Background:
In commit a0c9fec7, we updated TransactionData encoding/decoding and bumped the Transaction encoding version from 9 to 10. As part of this change, we renamed three fields to mark them as unused:
- largest_data_len → unused1
- largest_data_off → unused2
- largest_data_off_in_data_bl → unused3
The move constructor was also updated to stop setting these fields, leaving them uninitialized after move operations.
Problem:
This worked with existing tests because check-generated.sh reused struct instances, preserving stale values across encode/decode cycles. However, an upcoming test change will stop reusing instances and compare hexdumps of encoded/re-encoded …

os/Transaction: initialize unused fields in TransactionData

---

src/pybind/mgr/cephadm/tests/test_services.py
src/python-common/ceph/cephadm/images.py

The samba-containers project is now producing images that are based on samba + ceph tentacle packages (for libcephfs, etc). Use that as the image used for the samba server.
Same for samba-metrics. …

tentacle: switch samba container images to use "ceph20" packages

---

src/crimson/os/seastore/btree/fixed_kv_node.h

Cache::mark_transaction_conflicted calls get_delta(), which in turn calls FixedKVNodeLayout::copy_out for lba nodes. If the mutation_pending extent happens not to have any deltas, it'll fail in memcpy in FixedKVNodeLayout::copy_out.
I think this is valid because a transaction may become conflicted between when duplicate_for_write is called and when the actual mutation is performed on the extent.
Fixes: https://tracker.ceph.com/issues/72579
<details> …

crimson/.../fixed_kv_node: don't call copy_out if delta_buffer is empty

---

src/common/perf_counters.cc
src/common/perf_counters.h
src/os/bluestore/BlueFS.cc
src/os/bluestore/BlueFS.h
src/test/perf_counters.cc

counters
This e.g. allows to track maximum observed latencies along with average values which might be helpful for bottleneck detection.
This is a resurrection of https://github.com/ceph/ceph/pull/53511 …

common/perf_counters: track maximum increment value for LONGRUNAVG perf

---

doc/man/8/mount.ceph.rst

doc/man/8: Improve mount.ceph.rst
Improve the descriptions of the `dirstats` and `nodirstats` mount options. …

doc/man/8: Improve mount.ceph.rst

---

make-debs.sh

Now that we're using make-debs.sh as a builder inside containers, the default should be to build all the packages, including debug. (Also, fix a typo.) …

make-debs.sh: make "skip debug packages" conditional

---

src/pybind/mgr/dashboard/services/nvmeof_client.py
src/pybind/mgr/dashboard/services/nvmeof_conf.py

backport tracker: https://tracker.ceph.com/issues/72678
---
backport of https://github.com/ceph/ceph/pull/64753
parent tracker: https://tracker.ceph.com/issues/71640

squid: mgr/dashboard: fix nvmeof mtls

---

src/pybind/mgr/dashboard/services/nvmeof_cli.py

old output:
```
[xxxxxx]# ceph --format json nvmeof gw set_log_level --gw_group group1 | jq .
Error EINVAL: Traceback (most recent call last):
File "/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 503, in _GetIntegerEnumValue
return enum_type.values_by_name[value].number
KeyError: 'none'
During handling of the above exception, another exception occurred:
File "/usr/share/ceph/mgr/mgr_module.py", line 2007, in _handle_command
return CLICommand.COMMANDS[cmd['prefix']].call(self, cmd, inbuf)
File "/usr/share/ceph/mgr/dashboard/services/nvmeof_cli.py", line 221, in call
ret = super().call(mgr, cmd_dict, inbuf)
File "/usr/share/ceph/mgr/mgr_module.py", line 531, in call
return self.func(mgr, **kwargs)
File …
```

mgr/dashboard: catch broader exception to show relevant cli output

---

src/crimson/os/seastore/journal/circular_journal_space.cc

* Remove redundant assertion
* Fix boundary check (CBJ does not assume `written_to` can be `get_journal_end`). 
See #65108 …

crimson/.../circular_journal_space: fix boundary check

---

doc/cephfs/troubleshooting.rst

Move the "Slow requests (MDS)" section immediately after the first section in this document ("Slow/Stuck Operations"), because the first procedure on the page directs the reader to undertake the operation in "Slow requests (MDS)" before trying anything else. …

doc/cephfs: edit troubleshooting.rst (Slow MDS)

---

src/pybind/mgr/dashboard/controllers/host.py
src/pybind/mgr/dashboard/tests/test_host.py

fixes : https://tracker.ceph.com/issues/72608
Before removing unwanted API resp.
after removing unwanted API resp. …

mgr/dashboard : Optimized /host API to minimum resp

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-tabs/cephfs-tabs.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs.module.ts

backport tracker: https://tracker.ceph.com/issues/72622
---
backport of https://github.com/ceph/ceph/pull/64405
parent tracker: https://tracker.ceph.com/issues/72039
https://github.com/user-attachments/assets/ada5cc83-6978-4656-b4f6-b8ace4e91549
Signed-off-by: Abhishek Desai <abhishek.desai1@ibm.com>

tentacle: mgr/dashboard: add tab structure to File Systems page and embed Ceph-Filesystem Overview dashboard

---

doc/rados/configuration/ceph-conf.rst

A small improvement based on
"Why is it still so difficult to just dump all config and where it comes from?" https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/EZSLRYBYEWDA6YIARQVMUKQUWHAE3PGR/
`show-with-defaults` is very useful, and `ceph-conf` is mentioned so that it's clear that it's legacy, and the user doesn't have to wonder if it's actually useful but was forgotten in the list.
<details>
- `jenkins test classic perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-classic/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull-requests/config/definitions/ce …

doc/rados/configuration: Mention show-with-defaults and ceph-conf

---

.github/workflows/redmine-upkeep.yml
src/script/redmine-upkeep.py

script: import github token for redmine-upkeep

---

src/test/mds/TestQuiesceDb.cc

rocky 10 build error fixes

---

src/pybind/mgr/dashboard/tests/test_host.py

fixes: https://tracker.ceph.com/issues/72717
```
__________________________________ summary ___________________________________________
py3: commands succeeded
lint: commands succeeded
check: commands succeeded
openapi-check: commands succeeded
congratulations :)
```
Signed-off-by: Abhishek Desai <abhishek.desai1@ibm.com> …

mgr/dashboard: Fix test_host.py test case

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-config-modal/rgw-config-modal.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.ts

backport tracker: https://tracker.ceph.com/issues/72716
---
backport of https://github.com/ceph/ceph/pull/64827
parent tracker: https://tracker.ceph.com/issues/72408

tentacle: mgr/dashboard: rgw_crypt_kmip_addr in SSE-KMS kmip address input field validation updated

---

src/pybind/mgr/prometheus/module.py

backport tracker: https://tracker.ceph.com/issues/72639
---
backport of https://github.com/ceph/ceph/pull/64835
parent tracker: https://tracker.ceph.com/issues/72421

tentacle: prometheus: Add RBD image metadata to prometheus

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form-client/nfs-form-client.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form-client/nfs-form-client.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form-client/nfs-form-client.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.ts

Fixes https://tracker.ceph.com/issues/72660
https://github.com/user-attachments/assets/90e8af37-8a2c-4657-9a7c-aae034f7a488 …

mgr/dashboard: Dashboard nfs export editor rejects ipv6 addresses

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/rules-list/rules-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/rules-list/rules-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/prometheus-alert.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/prometheus-alert.service.ts

backport tracker: https://tracker.ceph.com/issues/72525
---
backport of https://github.com/ceph/ceph/pull/64773
parent tracker: https://tracker.ceph.com/issues/72524

tentacle: mgr/dashboard: Stop rules api being polled on every page

---

ceph.spec.in

followup to https://github.com/ceph/ceph/pull/58881 which only covered crimson:
* el9 builds set gts_version to 13 for all flavors
* remove checks for gts_version < 13 now that we don't use 11
* require gcc >= 13.3 for non-gts builds too (el10 and later)
Fixes: https://tracker.ceph.com/issues/72643
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull-requ …

rpm: default to gcc-toolset-13, not just for crimson

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form-client/nfs-form-client.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form-client/nfs-form-client.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form-client/nfs-form-client.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/forms/cd-validators.ts

backport tracker: https://tracker.ceph.com/issues/72733
---
backport of https://github.com/ceph/ceph/pull/65169
parent tracker: https://tracker.ceph.com/issues/72660

tentacle: mgr/dashboard: Dashboard nfs export editor rejects ipv6 addresses

---

src/test/osd/ceph_test_rados_io_sequence/ceph_test_rados_io_sequence.h

Suppress linkage warning for SelectMappingAndLayers. electMapping and SelectLayers definitions in a header file, which usually means that it is intended to be included in multiple translation units.
SelectMappingAndLayers::sma and SelectMappingAndLayers::sly have internal storage duration, because it is a non-template, non-inline, non-extern const-qualified variable.
As a consequence, in each translation unit sma and sly is a different object. And because ProgramOptionSelector takes a reference as template argument, then ProgramOptionSelector<...> are different specializations of ProgramOptionSelector in different translation units, because the template parameter references different objects in each.
Then, if you include the header in two different translation units, the program will have …

test/osd: Suppress subobject-linkage warning in SelectMappingAndLayers

---

make-debs.sh

Backport of https://github.com/ceph/ceph/pull/65178, https://github.com/ceph/ceph/pull/65190 and https://github.com/ceph/ceph/pull/65222. …

squid: Recent pipeline backports

---

doc/cephfs/troubleshooting.rst

Move the "Slow requests (MDS)" section immediately after the first section in this document ("Slow/Stuck Operations"), because the first procedure on the page directs the reader to undertake the operation in "Slow requests (MDS)" before trying anything else.
(cherry picked from commit 55af6643c9a119afc4e22e2591774e1d68ef5580) …

reef: doc/cephfs: edit troubleshooting.rst (Slow MDS)

---

src/pybind/mgr/cephadm/module.py

When creating the first OSD in a cluster, the method requested was being ignored - meaning an LVM OSD would be created in all cases. If a given cluster couldn't support LVM, it could not be deployed. If we relay the method value requested by the cephadm invocation, we can create OSDs as expected.
Fixes: https://tracker.ceph.com/issues/72381 …

cephadm: Use specified method for osd.default

---

src/ceph-volume/ceph_volume/tests/conftest.py
src/ceph-volume/ceph_volume/tests/devices/lvm/data_zap.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_migrate.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_zap.py
src/ceph-volume/ceph_volume/tests/objectstore/test_lvm.py
src/ceph-volume/ceph_volume/tests/test_inventory.py
src/ceph-volume/ceph_volume/tests/util/test_device.py
src/ceph-volume/ceph_volume/tests/util/test_disk.py
src/ceph-volume/ceph_volume/util/device.py
src/ceph-volume/ceph_volume/util/disk.py

Calling udevadm via subprocess can cause processes to pile up under heavy load on production clusters.
This commit switches to reading udev data directly from /run/udev/data, which is mounted as tmpfs.

ceph-volume: drop udevadm subprocess calls

---

src/test/rgw/test_d4n_directory.cc

causing centos 9 build failure and is debug
only code.
- …

rgw/d4n: removing fmt related code as it is

---

qa/tasks/cephfs/mount.py

backport tracker: https://tracker.ceph.com/issues/71208
---
backport of https://github.com/ceph/ceph/pull/62259
parent tracker: https://tracker.ceph.com/issues/71206

squid: qa/tasks/cephfs/mount: use 'ip route' instead 'route'

---

.github/workflows/redmine-upkeep.yml

This `if` was filtering out merges for release branches like squid.
- Component …

.github/workflows: run redmine-upkeep for release branches

---

cmake/modules/AddCephTest.cmake

LeakSanitizer prints matched suppressions by default, which causes CLI tests to fail when built with LSan enabled. The tests compare actual output against expected output, and the additional LSan messages break this comparison.
Example failure:
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/cli/ceph-kvstore-tool/help.t: failed
--- /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/cli/ceph-kvstore-tool/help.t
+++ /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/cli/ceph-kvstore-tool/help.t.err
@@ -21,3 +21,9 @@
stats
histogram [prefix]
+  -----------------------------------------------------
+  Suppressions used:
+    count      bytes template
+        1         45 ^MallocExtension::Initialize
+ …
```

cmake: disable LeakSanitizer suppression output to fix CLI tests

---

src/mon/MonCommands.h
src/mon/Monitor.cc

backport tracker: https://tracker.ceph.com/issues/72419
---
backport of https://github.com/ceph/ceph/pull/64038
parent tracker: https://tracker.ceph.com/issues/71725

reef: monitor: Enhance historic ops command output and error handling

---

doc/dev/blkin.rst

fixes:https://tracker.ceph.com/issues/72059
(cherry picked from commit 3029cc9afdee352fb22db0895c5d3ec4a35277d3)
- …

squid: doc/dev:update blkin.rst doc for lttng trace

---

doc/dev/blkin.rst

fixes:https://tracker.ceph.com/issues/72059
(cherry picked from commit 3029cc9afdee352fb22db0895c5d3ec4a35277d3)
- …

tentacle: doc/dev:update blkin.rst doc for lttng trace

---

doc/rados/configuration/ceph-conf.rst

A small improvement based on
"Why is it still so difficult to just dump all config and where it comes from?" https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/EZSLRYBYEWDA6YIARQVMUKQUWHAE3PGR/
`show-with-defaults` is very useful, and `ceph-conf` is mentioned so that it's clear that it's legacy, and the user doesn't have to wonder if it's actually useful but was forgotten in the list.
(cherry picked from commit 978ab834c464b993ec77c914cb36da47211a1cd4)
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backp …

reef: doc/rados/configuration: Mention show-with-defaults and ceph-conf

---

doc/rados/configuration/ceph-conf.rst

A small improvement based on
"Why is it still so difficult to just dump all config and where it comes from?" https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/EZSLRYBYEWDA6YIARQVMUKQUWHAE3PGR/
`show-with-defaults` is very useful, and `ceph-conf` is mentioned so that it's clear that it's legacy, and the user doesn't have to wonder if it's actually useful but was forgotten in the list.
(cherry picked from commit 978ab834c464b993ec77c914cb36da47211a1cd4)
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backp …

squid: doc/rados/configuration: Mention show-with-defaults and ceph-conf

---

doc/cephfs/troubleshooting.rst

Move the "Slow requests (MDS)" section immediately after the first section in this document ("Slow/Stuck Operations"), because the first procedure on the page directs the reader to undertake the operation in "Slow requests (MDS)" before trying anything else.
(cherry picked from commit 55af6643c9a119afc4e22e2591774e1d68ef5580) …

squid: doc/cephfs: edit troubleshooting.rst (Slow MDS)

---

src/pybind/mgr/dashboard/services/nvmeof_cli.py

backport tracker: https://tracker.ceph.com/issues/72719
---
backport of https://github.com/ceph/ceph/pull/65028
parent tracker: https://tracker.ceph.com/issues/72060

tentacle: mgr/dashboard: catch broader exception to show relevant cli output

---

src/pybind/mgr/dashboard/controllers/_base_controller.py
src/pybind/mgr/dashboard/controllers/rbd_mirroring.py
src/pybind/mgr/dashboard/openapi.yaml

Introduce a new API for getting per image summary
```
╰─$ curl -kX GET "https://localhost:4200/api/block/mirroring/rbd/test/summary" \
-H "Accept: application/vnd.ceph.api.v1.0+json" \
-H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" | jq .
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   637  100   637    0     0  14597      0 --:--:-- --:--:-- --:--:-- 14813
{
"name": "test2",
"id": "10d618ea1a58",
"info": {
"global_id": "f25678be-64a2-481f-b96c-9bcc566dcbfe",
"state": 1,
"primary": true
},
"remote_statuses": [
{
"state": "Replaying",
"description": {
"bytes_per_second": 0.0,
"bytes_per_snapshot": 0.0,
"last_snapshot_bytes": 0,
"last_snapshot_sync_seconds": 0,
"local_snapshot_timestamp": …
```

mgr/dashboard: expose image summary API

---

src/msg/async/AsyncMessenger.cc

backport tracker: https://tracker.ceph.com/issues/72213
---
backport of https://github.com/ceph/ceph/pull/63261
parent tracker: https://tracker.ceph.com/issues/71303

tentacle: msg: drain stack before stopping processors to avoid shutdown hang

---

qa/cephfs/clusters/1-node-4-mds-1-osd.yaml
qa/suites/fs/full/clusters/1-node-1-mds-1-osd.yaml
qa/suites/fs/full/clusters/1-node-4-mds-1-osd.yaml
qa/suites/fs/full/overrides.yaml
qa/suites/fs/full/tasks/mgr-osd-full.yaml
qa/workunits/fs/full/subvolume_ls.sh
src/mds/Server.cc

Problem:
The readdir wouldn't list all the entries in the directory when the osd is full with rstats enabled.
Cause:
The issue happens only in multi-mds cephfs cluster. If rstats is enabled, the readdir would request 'Fa' cap on every dentry, basically to fetch the size of the directories. Note that 'Fa' is CEPH_CAP_GWREXTEND which maps to CEPH_CAP_FILE_WREXTEND and is used by CEPH_STAT_RSTAT.
The request for the cap is a getattr call and it need not go to the auth mds. If rstats is enabled, the getattr would go with the mask CEPH_STAT_RSTAT which mandates the requirement for auth-mds in 'handle_client_getattr', so that the request gets forwarded to auth mds if it's not the auth. But if the osd is full, in the 'dispatch_client_request' before calling the  handler function of respective …

mds: Fix readdir when osd is full.

---

qa/tasks/cephfs/caps_helper.py
qa/tasks/cephfs/test_admin.py
src/client/Client.cc
src/mds/MDSAuthCaps.cc
src/mds/MDSAuthCaps.h
src/mds/Server.cc
src/mds/SessionMap.cc
src/mds/SessionMap.h
src/test/mds/TestMDSAuthCaps.cc

The fsname is not take into consideration while validating
the access check for the operations. This patch fixes
the same.
Fixes: https://tracker.ceph.com/issues/72167 …

Fix multifs auth caps check

---

src/script/redmine-upkeep.py

The update log link would appear as preformatted text.
- …

script/redmine-upkeep: fix formatting of comment

---

src/mon/PGMap.cc

Fixes: https://tracker.ceph.com/issues/72092
Add a user friendly description for BLUESTORE_FREE_FRAGMENTATION warning. 
This is displayed in `ceph -s` and `ceph health detail` to help the user understand what BLUESTORE_FREE_FRAGMENTATION means.
Signed-off-by: Michael J. Kidd [linuxkidd@gmail.com](mailto:linuxkidd@gmail.com)
<details> …

mon/PGmap: Add warn description for bluestore fragmentation

---

src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/seastore_types.h

Fixes: https://tracker.ceph.com/issues/72580 …

crimson/os/seastore: add retire alloc remarks for backref extents to skip replay invalid deltas

---

cmake/modules/Builduadk.cmake
make-debs.sh

Backport of https://github.com/ceph/ceph/pull/65161, https://github.com/ceph/ceph/pull/65178, https://github.com/ceph/ceph/pull/65190 and https://github.com/ceph/ceph/pull/65222.
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull-reques …

tentacle: Recent pipeline backports

---

src/mgr/DaemonState.h

Calling back into python functions whilst holding the lock can result in this thread being queued for the GIL and resulting in extended delays for threads waiting to acquire the lock.
Fixes: https://tracker.ceph.com/issues/72337 …

mgr/DaemonState: Minimise time we hold the DaemonStateIndex lock

---

src/mon/NVMeofGwMon.cc
src/mon/NVMeofGwMon.h

fixes https://tracker.ceph.com/issues/72434 …

nvmeofgw: cleanup pending map upon monitor restart

---

qa/suites/orch/cephadm/workunits/task/test_host_drain.yaml

This task intentionally marks OSDs down, which are eventually marked back up. So, we can ignore this warning.
Fixes: https://tracker.ceph.com/issues/70468 …

qa/suites/orch/cephadm: ignore intentional OSD_DOWN warning from test_host_drain task

---

src/CMakeLists.txt

backport tracker: https://tracker.ceph.com/issues/72859
---
backport of https://github.com/ceph/ceph/pull/65371
parent tracker: https://tracker.ceph.com/issues/72361
This backport was staged using copy and paste because I have never gotten the backport script to work

tentacle: cmake: remove _FORTIFY_SOURCE define

---

cmake/modules/Builduadk.cmake

backport tracker: https://tracker.ceph.com/issues/72821
---
backport of https://github.com/ceph/ceph/pull/65316
parent tracker: https://tracker.ceph.com/issues/72722

tentacle: Fix uadk build (arm64 only) on debian (conflict with DESTDIR)

---

src/script/build-with-container.py

When the npm cache path option is passed the npm cache dir is passed to all container `run` commands, ensure the dir has been created before the first container command (configure) is used. …

build-with-container: ensure npm dir is set up before configure

---

src/pybind/mgr/dashboard/run-backend-api-tests.sh

Backport of https://github.com/ceph/ceph/pull/65414
(cherry picked from commit 22a87d959bca74478de1e2d9f86859676385491d)

squid: pybind/mgr/dashboard: Use teuthology's actual requirements

---

src/pybind/mgr/dashboard/run-backend-api-tests.sh

pybind/mgr/dashboard: Use teuthology's actual requirements

---

src/pybind/mgr/dashboard/run-backend-api-tests.sh

Backport of https://github.com/ceph/ceph/pull/65414
(cherry picked from commit 22a87d959bca74478de1e2d9f86859676385491d)

reef: pybind/mgr/dashboard: Use teuthology's actual requirements

---

src/rgw/driver/rados/rgw_rados.cc

When bucket indexes are purged (e.g., via `radosgw-admin bi purge`), reindex operations fail because they attempt to update non-existent bucket index shards 
update_idx.complete() seems to be calling an async rados operations, causing reindex to fail with -ENOENT when shards are missing. I added this check before to create the missing index shards. 
Fixes: https://tracker.ceph.com/issues/68750
Alternatively the solution was to write the index shards manually into the rados pool for rgw.index then run this rgw-restore-bucket-index tool
Ran into this issue where operator ran radosgw-admin bi purge --bucket="test' and used this rgw-restore-bucket-index tool. Added this debug statement when I was testing and it seemed that update_idx.complete() was returning fine but was failing later on. …

rgw: auto-create missing bucket index shards during reindex operations

---

src/test/test_cors.cc

A pointer to RGWCORSConfiguration is cast to RGWCORSConfiguration_S3 which leads to out of bounds access. Replace the pointer ref with the proper data structure
Fixes: https://tracker.ceph.com/issues/72452 …

test/rgw: Refactor CORS configuration handling for S3

---

src/osd/scrubber/scrub_backend.cc

... in ScrubBackend::inconsistents()
Existing code was using a reference to a moved-from `auth_and_obj_errs_t` object, which is undefined behavior.
The change here was tested locally. No noticeable performance degradation was observed, and the code is now more robust.
Fixes: https://tracker.ceph.com/issues/72426

osd/scrub: avoid using moved-from auth_n_errs

---

src/osd/scrubber/scrub_backend.cc

Instead of constructing an std::string, let's check the digest emptiness with bufferlist::empty() to avoid reading beyond buffer boundaries.
In commit 92ccbff1, we introduced a bug when checking if a digest was empty by constructing a std::string from bufferlist:
```
std::string(digest.second.c_str()).empty()
```
This is unsafe because bufferlist data is not guaranteed to be null- terminated. The std::string constructor searches for a null terminator and may read beyond the bufferlist's allocated memory, causing a heap-buffer-overflow detected by AddressSanitizer:
```
==66092==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7e0c65215004 at pc 0x7fbc6e27c597 bp 0x7ffe29fb6100 sp 0x7ffe29fb58b8
READ of size 5 at 0x7e0c65215004 thread T0
#0 0x7fbc6e27c596 in strlen …
```

osd/scrub: fix heap-buffer-overflow when checking digest emptiness

---

src/pybind/mgr/cephadm/services/monitoring.py
src/pybind/mgr/cephadm/services/nvmeof.py
src/pybind/mgr/cephadm/services/service_registry.py
src/pybind/mgr/cephadm/tests/test_services.py

The changes on this PR fixes some regression related to nvmeof Prometheus config generation (introduced by the PR https://github.com/ceph/ceph/pull/61770). Basically in the past nvmeof section was always included regardless of whether the service exists or not. With the recent config generation improvement this behavior was changed to only include the sections corresponding to configured services leading to the regression. 
Among other changes, the new code calls `service_registry.get_services_requiring_monitoring` to make sure we are including as dependency all the monitored services making the whole config generation code more robust and generic. 
Fixes: https://tracker.ceph.com/issues/72811 …

mgr/cepahdm: fixing nvmeof scraping Prometheus config generation

---

src/osd/scrubber/scrub_backend.cc

Fixing a bug introduced by commit 4c61079e931
("calculate EC digest map size only once").
Fixes: https://tracker.ceph.com/issues/72897

osd/scrub: clear m_ec_digest_map between objects

---

src/common/buffer.cc
src/include/buffer.h
src/include/interval_set.h
src/osd/ECBackend.cc
src/osd/ECCommon.cc
src/osd/ECTransaction.cc
src/osd/ECUtil.cc
src/osd/ECUtil.h
src/test/bufferlist.cc
src/test/osd/TestECBackend.cc
src/test/osd/TestECUtil.cc

depends on #64794
backport tracker: https://tracker.ceph.com/issues/72369
---
backport of https://github.com/ceph/ceph/pull/63408
parent tracker: https://tracker.ceph.com/issues/72368

tentacle: OSD: EC recovery zero detect

---

src/rgw/rgw_bucket_logging.cc

Multiple threads attempting to roll over the same log object can result in the creation of numerous orphan tail objects, each with a single record. This occurs when a NULL RGWObjVersionTracker is used during the creation of a new logging object. These records are inaccessible, leading to data loss, which is particularly critical in Journal mode.
Furthermore, valid log tail objects may be added to the Garbage Collection (GC) list, exacerbating data loss.
Fixes: https://tracker.ceph.com/issues/72740 …

rgw/logging: fixes data loss during rollover

---

src/common/io_exerciser/RadosIo.cc
src/common/io_exerciser/RadosIo.h
src/common/json/OSDStructures.cc
src/common/json/OSDStructures.h
src/erasure-code/consistency/RadosCommands.cc
src/erasure-code/consistency/ceph_ec_consistency_checker.cc
src/test/osd/ceph_test_rados_io_sequence/ceph_test_rados_io_sequence.cc
src/test/osd/ceph_test_rados_io_sequence/ceph_test_rados_io_sequence.h

Make 'ceph_test_rados_io_sequenece --pool rbd' work, replica pools don't have an erasure code profile and do not have the ec_allow_overwrites or ec_allow_optimizations flags
Fixes: https://tracker.ceph.com/issues/70844
PR is rebased on top of [#64564](https://github.com/ceph/ceph/pull/64564) …

test: add replica pool support to ceph_test_rados_io_sequence

---

src/pybind/mgr/dashboard/controllers/_base_controller.py
src/pybind/mgr/dashboard/controllers/rbd_mirroring.py
src/pybind/mgr/dashboard/openapi.yaml

backport tracker: https://tracker.ceph.com/issues/72798
---
backport of https://github.com/ceph/ceph/pull/65079
parent tracker: https://tracker.ceph.com/issues/72520

tentacle: mgr/dashboard: expose image summary API

---

qa/suites/orch/cephadm/osds/1-start.yaml

gnore-list have "but is still running" instead of "but it is still running" message.
Fixes: https://tracker.ceph.com/issues/72501 …

suites/rados/cephadm: typo in ignotr list for still running message

---

src/pybind/cephfs/cephfs.pyx
src/test/pybind/test_cephfs.py

When chown() in libcephfs call receives -1 as the value of UID/GID, it
is implicitly converted from signed integer to unsigned integeer but
CephFS cython instead of doing that errors out during complilation.
Therefore make this conversion explicitly to allow users to pass -1
(which they do to indicate that UID/GID value shouldn't be changed) and
also for sake of uniformity and consistency between between CephFS
cython and libcephfs interface.
Fixes: https://tracker.ceph.com/issues/72547
Introduced-by: 65328aca31f2f5038cb602148120b9427370ed4f …

cephfs.pyx: handle when UID/GID passed to chown() is -1

---

src/client/Client.cc
src/client/Client.h
src/common/options/mds-client.yaml.in
src/include/cephfs/libcephfs.h
src/libcephfs.cc
src/test/libcephfs/test.cc

~~Still a WIP (kind of).~~
Reproducer test case. …

test/libcephfs: validate asynchronous write and fsync executing concurrently

---

monitoring/ceph-mixin/dashboards/rgw.libsonnet
monitoring/ceph-mixin/dashboards_out/radosgw-overview.json

backport tracker: https://tracker.ceph.com/issues/72910
---
backport of https://github.com/ceph/ceph/pull/65384
parent tracker: https://tracker.ceph.com/issues/72868

tentacle: mgr/dashboard: fix RGW Bucket Notification Dashboard units

---

src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation.module.ts
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.ts
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notification-panel/header/notification-header.component.html
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notification-panel/header/notification-header.component.scss
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notification-panel/header/notification-header.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notification-panel/header/notification-header.component.ts
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notification-panel/notification-panel.component.html
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notification-panel/notification-panel.component.scss
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notification-panel/notification-panel.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notification-panel/notification-panel.component.ts
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notifications/notifications.component.html
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notifications/notifications.component.scss
src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notifications/notifications.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/notifications-sidebar/notifications-sidebar.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/notifications-sidebar/notifications-sidebar.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/notification.service.ts

This PR introduces a new notification panel component built with Carbon Design System (CDS) components, providing a  alternative to the existing notification sidebar. The implementation includes a boolean flag system to toggle between the new panel and legacy sidebar.
Also added unread notification counter on bell icon.
https://github.com/user-attachments/assets/033a0f5f-2475-45ee-a8a2-da017e56faf0
- Panel behavior: New panel is shown (`useNewPanel: true`)
In the NotificationService - to set the  panel type:
Go to src/pybind/mgr/dashboard/frontend/src/app/shared/services/notification.service.ts
Find line ~26 where useNewPanel: true is set
Change it to `useNewPanel: false` to use the old sidebar 
- In the NavigationComponent - to control which panel opens when clicking the notification …

mgr/dashboard: Carbonised Notification Header

---

src/ceph-volume/ceph_volume/tests/conftest.py
src/ceph-volume/ceph_volume/tests/devices/lvm/data_zap.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_migrate.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_zap.py
src/ceph-volume/ceph_volume/tests/objectstore/test_lvmbluestore.py
src/ceph-volume/ceph_volume/tests/test_inventory.py
src/ceph-volume/ceph_volume/tests/util/test_device.py
src/ceph-volume/ceph_volume/tests/util/test_disk.py
src/ceph-volume/ceph_volume/util/device.py
src/ceph-volume/ceph_volume/util/disk.py

backport tracker: https://tracker.ceph.com/issues/72782
---
backport of https://github.com/ceph/ceph/pull/65029
parent tracker: https://tracker.ceph.com/issues/72780

tentacle: ceph-volume: drop udevadm subprocess calls

---

qa/tasks/thrashosds-health.yaml

These warnings, part of the Ceph health detail, are expected in osd thrashing tests. In the original test failure, the cluster eventually got back to HEALTH_OK after the thrashing task completed.
Fixes: https://tracker.ceph.com/issues/72312 …

qa/tasks/thrashosds-health: fine tune ignorelist for degraded and undersized pgs

---

src/ceph-volume/ceph_volume/tests/conftest.py
src/ceph-volume/ceph_volume/tests/devices/lvm/data_zap.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_migrate.py
src/ceph-volume/ceph_volume/tests/devices/lvm/test_zap.py
src/ceph-volume/ceph_volume/tests/objectstore/test_lvmbluestore.py
src/ceph-volume/ceph_volume/tests/test_inventory.py
src/ceph-volume/ceph_volume/tests/util/test_device.py
src/ceph-volume/ceph_volume/tests/util/test_disk.py
src/ceph-volume/ceph_volume/util/device.py
src/ceph-volume/ceph_volume/util/disk.py

backport tracker: https://tracker.ceph.com/issues/72781
---
backport of https://github.com/ceph/ceph/pull/65029
parent tracker: https://tracker.ceph.com/issues/72780

squid: ceph-volume: drop udevadm subprocess calls

---

src/common/options/rgw.yaml.in
src/rgw/rgw_rest_sts.cc
src/rgw/rgw_rest_sts.h

backport tracker: https://tracker.ceph.com/issues/72465
---
backport of https://github.com/ceph/ceph/pull/63047
parent tracker: https://tracker.ceph.com/issues/72457

tentacle: rgw: check all JWKS for STS

---

debian/cephadm.postinst
doc/cephadm/install.rst

backport tracker: https://tracker.ceph.com/issues/72191
---
backport of https://github.com/ceph/ceph/pull/64459
parent tracker: https://tracker.ceph.com/issues/72083

tentacle: deb/cephadm: add explicit --home for cephadm user

---

src/rgw/driver/rados/rgw_bucket.cc
src/rgw/driver/rados/rgw_sal_rados.cc
src/rgw/rgw_lc.cc
src/rgw/rgw_lc.h
src/rgw/rgw_op.cc

backport tracker: https://tracker.ceph.com/issues/71544
---
backport of https://github.com/ceph/ceph/pull/62980
parent tracker: https://tracker.ceph.com/issues/71083

squid: rgw/lc: stop using merge_and_store_attrs in remove_bucket_config

---

monitoring/ceph-mixin/tests_alerts/validate_rules.py

The documentation started raising 403 suddenly. Adding User-Agent headers to the request
Fixes: https://tracker.ceph.com/issues/72960 …

monitoring: add user-agent headers to the urllib

---

src/rgw/driver/rados/rgw_rados.cc

Fixes: https://tracker.ceph.com/issues/72667 …

rgw: discard olh_ attributes when copying object from a versioning-suspended bucket to a versioning-disabled bucket

---

PendingReleaseNotes
doc/rados/configuration/mon-config-ref.rst
doc/rados/operations/monitoring.rst
src/common/options/mon.yaml.in
src/mon/MgrStatMonitor.cc
src/mon/MgrStatMonitor.h

This commit adds the dynamic config option to change the interval at which the data availability score is updated.
Fixes: https://tracker.ceph.com/issues/72619
`calc_pool_availability` is responsible for updating the availability score. This is invoked inside `MgrStatMonitor::update_from_paxos`. 
`MgrStatMonitor::update_from_paxos` is called at the end of each paxos update. This essentially means frequency of availablity score update is currently tied to paxos update frequency. Looking at `PaxosService::should_propose` it seems like `paxos_propose_interval` config option determines how often paxos updates happen. 
There are two ways I can implement the ability to give users the flexibility to change frequency of how often the score is calculated: 
1. Decouple the two, score update freq & …

mon: add config option to change availability score update interval 

---

src/common/TracepointProvider.cc

fixes:https://tracker.ceph.com/issues/72059 …

rados/lttng: add lttng open *tp.so error message

---

src/osd/ECTransaction.cc

We currently only choose to do a parity delta write if the number of reads required is fewer than for a traditional read modify write. Performance testing shows a small benefit to doing PDW for random I/O workloads when the number of reads is the same.
See performance results here: https://github.com/lee-j-sanders/perfresults/blob/main/reports/cbt_29thAug_o01_4%2B2_squid_vs_16k_pdwauto_vs_pdwon/comparitive_performance_report_250829_145341.md …

osd: Choose PDW over traditional RMW if number of reads required is equal

---

src/pybind/mgr/dashboard/controllers/rgw.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/mgr-modules/mgr-module-list/mgr-module-list.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-details/rgw-multisite-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-details/rgw-multisite-sync-policy-details.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-sync-policy-form/rgw-multisite-sync-policy-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-wizard/rgw-multisite-wizard.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-overview-dashboard/rgw-overview-dashboard.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/mgr-module.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/mgr-module.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-multisite.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/api/rgw-realm.service.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/components/progress/progress.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/components/progress/progress.component.ts
src/pybind/mgr/dashboard/openapi.yaml
src/pybind/mgr/dashboard/services/rgw_client.py

backport tracker: https://tracker.ceph.com/issues/71903
---
backport of https://github.com/ceph/ceph/pull/62929
parent tracker: https://tracker.ceph.com/issues/71033

tentacle: mgr/dashboard: Enable rgw module automatically in the primary and secondary cluster if not enabled during multi-site automation

---

doc/cephfs/mds-config-ref.rst
src/common/options/mds.yaml.in
src/common/options/y2c.py
src/mds/Locker.cc
src/mds/Locker.h
src/mds/MDSRank.cc
src/mds/Server.cc
src/mds/Server.h
src/mds/SimpleLock.h

backport tracker: https://tracker.ceph.com/issues/72163
---
backport of https://github.com/ceph/ceph/pull/64229
parent tracker: https://tracker.ceph.com/issues/71876

squid:  mds: nudge log for unstable locks after early reply

---

src/libcephfs_proxy/libcephfs_proxy.c
src/libcephfs_proxy/libcephfsd.c
src/libcephfs_proxy/proxy_async.c
src/libcephfs_proxy/proxy_requests.h

backport tracker: https://tracker.ceph.com/issues/72952
---
backport of https://github.com/ceph/ceph/pull/65320
parent tracker: https://tracker.ceph.com/issues/72800

tentacle: libcephfs_proxy: fix backward compatibility issue

---

PendingReleaseNotes

doc: update data availability release notes

---

qa/tasks/cephadm.py

Backport of https://github.com/ceph/ceph/pull/64185
<details> …

tentacle: qa/tasks/cephadm: allow to select from 'cephadm' and 'cephadm.py'

---

src/pybind/mgr/cephadm/templates/services/ingress/haproxy.cfg.j2

Backport of https://github.com/ceph/ceph/pull/63825
<details> …

tentacle: mgr/cephadm: handle possibly undefined template variable in haproxy.cfg.j2

---

src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/tests/test_cephadm.py

backport tracker: https://tracker.ceph.com/issues/72135
---
backport of https://github.com/ceph/ceph/pull/62984
parent tracker: https://tracker.ceph.com/issues/71087

tentacle: mgr/cephadm: disallow changing OSD service type to non-OSD types

---

doc/mgr/smb.rst
src/cephadm/cephadmlib/daemons/smb.py
src/cephadm/cephadmlib/file_utils.py
src/pybind/mgr/cephadm/services/smb.py
src/pybind/mgr/cephadm/tests/test_services.py
src/pybind/mgr/smb/enums.py
src/pybind/mgr/smb/external.py
src/pybind/mgr/smb/handler.py
src/pybind/mgr/smb/internal.py
src/pybind/mgr/smb/mon_store.py
src/pybind/mgr/smb/proto.py
src/pybind/mgr/smb/resourcelib.py
src/pybind/mgr/smb/resources.py
src/pybind/mgr/smb/sqlite_store.py
src/pybind/mgr/smb/staging.py
src/pybind/mgr/smb/tests/test_resources.py
src/pybind/mgr/smb/tests/test_smb.py
src/pybind/mgr/smb/tests/test_validation.py
src/pybind/mgr/smb/validation.py
src/python-common/ceph/deployment/service_spec.py
src/python-common/ceph/smb/constants.py

Backport of https://github.com/ceph/ceph/pull/64372 and https://github.com/ceph/ceph/pull/65069
<details> …

tentacle: smb: add remote control server

---

src/cephadm/cephadmlib/sysctl.py

backport tracker: https://tracker.ceph.com/issues/72668
---
backport of https://github.com/ceph/ceph/pull/65147
parent tracker: https://tracker.ceph.com/issues/72657

tentacle: cephadm/cephadmlib: Eliminate false warnings about old sysctl conf files

---

src/crush/mapper.c

Mark 'pushed' variable as maybe_unused to suppress compiler messages
Fixes: https://tracker.ceph.com/issues/72479
- …

crush/mapper: Mark pushed variable as maybe unused

---

doc/cephadm/services/monitoring.rst

**This should not be backported because the `certmgr` stuff doesn't exist in the Tentacle docs.**
Add that certmgr is new in version Tentacle.
Fix broken links with formatting rendered as text.
Capitalize consistently in text HTTP, YAML, URL, Alertmanager, Grafana, centralized logging; Prometheus or use inline preformat with lower case when referring to the module name.
Use inline preformat consistently for CLI commands within text paragraphs.
Use title case in section titles.
Trim section title underline syntax.
Use consistently pre-formatted blocks bash prompt, YAML.
Start all block formatting paragraphs at the left margin of the surrounding paragraphs instead of indenting just the formatted paragraph.
- Before: https://docs.ceph.com/en/latest/cephadm/services/monitoring/
- Rendered PR: …

doc/cephadm: Fix errors and improvements in services/monitoring.rst

---

doc/radosgw/adminops.rst
qa/suites/rgw/verify/tasks/admin-pagination.yaml
qa/workunits/rgw/run-admin-pagination.sh
qa/workunits/rgw/test_rgw_admin_pagination.py
src/rgw/driver/rados/rgw_bucket.cc
src/rgw/driver/rados/rgw_bucket.h
src/rgw/driver/rados/rgw_rest_bucket.cc
src/rgw/rgw_admin.cc
src/test/rgw/test_rgw_admin_bucket.py

backport of https://github.com/ceph/ceph/pull/62777
also includes backport of https://github.com/ceph/ceph/pull/64683 to fix regression in first PR
Fixes: https://tracker.ceph.com/issues/71476 …

squid: rgw/admin: Add max-entries and marker to bucket list

---

src/rgw/rgw_rest_client.cc
src/test/rgw/rgw_multi/tests.py

backport tracker: https://tracker.ceph.com/issues/72570
---
backport of https://github.com/ceph/ceph/pull/64376
parent tracker: https://tracker.ceph.com/issues/71998

tentacle: rgw/multisite: url-encode list_bucket query param 'key-marker'

---

src/rgw/rgw_bucket_logging.cc

backport tracker: https://tracker.ceph.com/issues/72905
---
backport of https://github.com/ceph/ceph/pull/65281
parent tracker: https://tracker.ceph.com/issues/72740

tentacle: rgw/logging: fixes data loss during rollover

---

doc/rados/operations/balancer.rst

Backport of https://github.com/ceph/ceph/pull/64157

squid: doc: Fixes a typo in balancer operations

---

qa/workunits/rbd/rbd_mirror_group.sh
qa/workunits/rbd/rbd_mirror_group_simple.sh
src/librbd/mirror/snapshot/GroupUnlinkPeerRequest.cc
src/librbd/mirror/snapshot/GroupUnlinkPeerRequest.h
src/tools/rbd_mirror/group_replayer/Replayer.cc
src/tools/rbd_mirror/group_replayer/Replayer.h

- rbd_mirror: order the user group snaps and the mirror group snaps syncing
```
In case of user group snap addition:
* Wait for the user group snap to sync to complete and only then mark
the mirror group snap to complete
In case of user group snap removal:
* Wait for the user group snap to get pruned and only then mark the
mirror group snap to complete
Updated tests:
• test_create_group_with_images_then_mirror_with_regular_snapshots   
enable scenario 1 as with the recent changes it works, also remove
additional mirror group snapshot as it is no more required.
```
- librbd/mirror: remove peer UUID of group snapshot before attempting removal
```
Problem:
When the number of snapshots exceeds the configured limit
(rbd_mirroring_max_mirroring_snapshots), the cleanup process remove the last …
```

rbd-mirror: fix group snapshot sync ordering and also properly remove peer UUIDs

---

src/cls/rgw/cls_rgw.cc
src/cls/rgw/cls_rgw_ops.h
src/cls/rgw/cls_rgw_types.cc
src/cls/rgw/cls_rgw_types.h
src/common/strtol.cc
src/common/strtol.h
src/rgw/driver/rados/rgw_rados.cc
src/test/rgw/rgw_multi/tests.py
src/test/rgw/rgw_multi/tests_es.py

rgw: implements timestamp-based epochs for objects in versioned buckets.
Fixes: https://tracker.ceph.com/issues/68466
Signed-off-by: Igor Gomon [igomon@bloomberg.net](mailto:igomon@bloomberg.net) …

rgw: implements timestamp-based epochs for versioned objects

---

src/pybind/mgr/dashboard/controllers/pool.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form-create-request.model.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.model.ts
src/pybind/mgr/dashboard/services/rbd.py

Fetching the rbd image schedule interval through the rbd_support module schedule list command
`GET /api/block/image` and `GET /api/rbd` will have the following field per image
```
"schedule_info": {
"image": "rbd/rbd_1",
"schedule_time": "2025-09-11 03:00:00",
"schedule_interval": [
{
"interval": "5d",
"start_time": null
},
{
"interval": "3h",
"start_time": null
}
]
},
```
Also fixes the UI where schedule interval was missing in the form and
also disable editing the schedule_interval.
Fixes: https://tracker.ceph.com/issues/72977 …

mgr/dashboard: fix missing schedule interval in rbd API

---

src/common/options/rgw.yaml.in
src/rgw/rgw_rest_sts.cc
src/rgw/rgw_rest_sts.h

backport tracker: https://tracker.ceph.com/issues/72464
---
backport of https://github.com/ceph/ceph/pull/63047
parent tracker: https://tracker.ceph.com/issues/72457

squid: rgw: check all JWKS for STS

---

src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/serve.py
src/pybind/mgr/cephadm/service_discovery.py
src/pybind/mgr/cephadm/tests/test_service_discovery.py

Backport of https://github.com/ceph/ceph/pull/64763
<details> …

tentacle:  mgr/cephadm: limit calls to list_servers

---

src/pybind/mgr/prometheus/module.py

backport tracker: https://tracker.ceph.com/issues/72209
---
backport of https://github.com/ceph/ceph/pull/64437, https://github.com/ceph/ceph/pull/64671, https://github.com/ceph/ceph/pull/65084
parent tracker: https://tracker.ceph.com/issues/72068

tentacle: mgr/prometheus: add smb_metadata metric

---

src/mon/NVMeofGwMon.cc
src/mon/NVMeofGwMon.h

backport tracker: https://tracker.ceph.com/issues/73045
---
backport of https://github.com/ceph/ceph/pull/64863
parent tracker: https://tracker.ceph.com/issues/73043

tentacle: nvmeofgw: cleanup pending map upon monitor restart

---

PendingReleaseNotes
doc/rados/configuration/mon-config-ref.rst
doc/rados/operations/monitoring.rst
src/common/options/mon.yaml.in
src/mon/MgrStatMonitor.cc
src/mon/MgrStatMonitor.h

backport tracker: https://tracker.ceph.com/issues/73013
---
backport of https://github.com/ceph/ceph/pull/65172
parent tracker: https://tracker.ceph.com/issues/72619

tentacle: mon: add config option to change availability score update interval 

---

.github/pull_request_template.md

When I started using ceph I also thought it would be natural to issue >1 command per comment, but it doesn't work. I saw someone else doing it recently and thought it would be good to have this reminder in the PR template. …

github: add a note reminding to use one command per comment

---

src/crimson/os/seastore/cache.cc
src/crimson/os/seastore/cache.h
src/crimson/os/seastore/cached_extent.h
src/crimson/os/seastore/extent_placement_manager.cc
src/crimson/os/seastore/journal/circular_bounded_journal.cc
src/crimson/os/seastore/journal/circular_bounded_journal.h
src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/seastore.h
src/crimson/os/seastore/transaction_manager.cc
src/crimson/os/seastore/transaction_manager.h
src/test/crimson/seastore/test_cbjournal.cc

seastore: misc cleanups, coroutine conversions

---

qa/suites/fs/nfs/conf

backport tracker: https://tracker.ceph.com/issues/70031
---
backport of https://github.com/ceph/ceph/pull/54406
parent tracker: https://tracker.ceph.com/issues/63482

reef: qa: enable debug mds/client for fs/nfs suite

---

src/common/options/rgw.yaml.in

changing the default flags to O_DSYNC
a small performance improvement is observable …

rgw/d4n: change cache write ::open() flags

---

src/common/ceph_context.cc

backport tracker: https://tracker.ceph.com/issues/65923
---
backport of https://github.com/ceph/ceph/pull/54433
parent tracker: https://tracker.ceph.com/issues/63494

squid: CephContext: acquire _fork_watchers_lock in notify_post_fork()

---

src/rgw/rgw_rest_s3.cc

backport tracker: https://tracker.ceph.com/issues/72715
---
backport of https://github.com/ceph/ceph/pull/64440
parent tracker: https://tracker.ceph.com/issues/21128

squid: rgw/s3: remove 'aws-chunked' from Content-Encoding response

---

PendingReleaseNotes
doc/radosgw/notifications.rst
src/common/options/rgw.yaml.in
src/rgw/driver/rados/rgw_notify.cc
src/rgw/driver/rados/rgw_notify.h
src/rgw/radosgw-admin/radosgw-admin.cc
src/rgw/rgw_pubsub.cc
src/rgw/rgw_pubsub.h
src/rgw/rgw_rest_pubsub.cc
src/test/rgw/bucket_notification/api.py
src/test/rgw/bucket_notification/test_bn.py
src/test/rgw/test-rgw-common.sh

This PR contains changes to add support for sharded persistent bucket notifications. 
Fixes: https://tracker.ceph.com/issues/71677
Signed-off-by: Adarsh Ashokan [dev.9401adarsh@gmail.com](mailto:dev.9401adarsh@gmail.com) …

rgw/notifications: add support for sharded persistent bucket notifications

---

doc/man/8/cephadm.rst
src/cephadm/cephadm.py
src/cephadm/cephadmlib/context_getters.py
src/cephadm/tests/test_cephadm.py
src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/serve.py
src/pybind/mgr/cephadm/tests/test_cephadm.py

Changes of this PR:
1. cephadm registry-login command to accept multiple registry credentials, the registry json will look like below
```
cephadm -v registry-login  --registry-json '{"registry_credentials":[{"url":"cp.stg.icr.io","username":"cp","password":"xxx"}, {"url":"quay.io/rh-ee-shbhosal/ceph","username":"aa","password":"xxx"}]}'
```
2. ceph cephadm registry-login will accept multiple registries in input file
```
{
"registry_credentials": [
{
"url": "cp.stg.icr.io",
"username": "cp",
"password": "xxx"
},
{
"url": "quay.io/rh-ee-shbhosal/ceph",
"username": "rh-ee-shbhosal",
"password": "xxx"
}
]
}
```
Fixes: https://tracker.ceph.com/issues/72206 …

mgr/cephadm: Allow registry credentials to define multiple container registries

---

src/pybind/mgr/cephadm/module.py

Set health warning 'CEPHADM_HOST_TIMEOUT_ERROR' for SSH timeout and remove the host name/warning when SSH to that host is successful. 
Fixes: https://tracker.ceph.com/issues/72345
Testing logs:
```
HEALTH_WARN SSH command execution failed with TimeoutError for 2 hosts; failed to probe daemons or devices; OSD count 2 < osd_pool_default_size 3
[WRN] CEPHADM_HOST_TIMEOUT_ERROR: SSH command execution failed with TimeoutError for 2 hosts
ceph-node-2
ceph-node-3
``` …

mgr/cephadm: set health warning for host SSH timeout

---

src/cephadm/cephadmlib/daemons/ceph.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade.component.html
src/pybind/mgr/dashboard/frontend/src/locale/messages.cs.xlf
src/pybind/mgr/dashboard/frontend/src/locale/messages.de-DE.xlf
src/pybind/mgr/dashboard/frontend/src/locale/messages.es-ES.xlf
src/pybind/mgr/dashboard/frontend/src/locale/messages.fr-FR.xlf
src/pybind/mgr/dashboard/frontend/src/locale/messages.id-ID.xlf
src/pybind/mgr/dashboard/frontend/src/locale/messages.it-IT.xlf
src/pybind/mgr/dashboard/frontend/src/locale/messages.ja-JP.xlf
src/pybind/mgr/dashboard/frontend/src/locale/messages.ko-KR.xlf
src/pybind/mgr/dashboard/frontend/src/locale/messages.pl-PL.xlf
src/pybind/mgr/dashboard/frontend/src/locale/messages.pt-BR.xlf
src/pybind/mgr/dashboard/frontend/src/locale/messages.zh-CN.xlf
src/pybind/mgr/dashboard/frontend/src/locale/messages.zh-TW.xlf

src/cephadm/cephadmlib/daemons: Fix typos in ceph.py and Dashboard files.
Pointed out by Eugen Block.
Fixes: https://tracker.ceph.com/issues/64242 …

src/cephadm/cephadmlib/daemons: Fix typos in ceph.py and elsewhere

---

PendingReleaseNotes
qa/standalone/mon/availability.sh
src/common/options/mon.yaml.in

Backport of https://github.com/ceph/ceph/pull/65545
<details> …

tentacle: options/mon: disable availability tracking by default

---

src/cephadm/build.py

Instead of raising an exception on a failure the compileall.compile_dir returns a boolean indicating if all files compiled successfully or not. Fail the build.py script if byte compiling fails as that usually indicates some sort of syntax error.
Fixes: https://tracker.ceph.com/issues/72850 …

cephadm: fail the script if byte-compile step fails

---

src/pybind/mgr/cephadm/serve.py

Added an additional look up for if a match with the ceph networks is not found it will check the virtual_interface_networks list from the config that will enable matching to those networks, enabling dummy IP usage as described in the docs: https://docs.ceph.com/en/reef/cephadm/services/rgw/#selecting-network-interfaces-for-the-virtual-ip.
Fixes: https://tracker.ceph.com/issues/66874
Config being applied:
```
root@server-03~# cat ./ingress-rgw-ha.yaml 
service_type: ingress
service_id: rgw.cdn
placement:
label: rgw
spec:
backend_service: rgw.cdn
virtual_ip: 192.168.0.80/24                        
frontend_port: 8080
monitor_port: 1967
virtual_interface_networks: ["10.10.0.0/16"]
```
Error logs:
```
Aug 29 14:25:33 server-03.domain.tld ceph-mgr[3581]: [cephadm INFO cephadm.serve] Filtered …
```

mgr/cephadm: Add check for virtual_interface_networks

---

src/python-common/ceph/deployment/translate.py

When provisioning new OSD nodes, apply configured WAL/db slot counts to their 
respective devices.
Fixes: https://tracker.ceph.com/issues/57939
Likely require backports to previous stable versions.
<details>
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job …

cephadm: pass wal/db slot count to ceph-volume

---

src/pybind/mgr/dashboard/controllers/pool.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form-create-request.model.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.model.ts
src/pybind/mgr/dashboard/services/rbd.py

backport tracker: https://tracker.ceph.com/issues/73063
---
backport of https://github.com/ceph/ceph/pull/65481
parent tracker: https://tracker.ceph.com/issues/72977

tentacle: mgr/dashboard: fix missing schedule interval in rbd API

---

src/global/signal_handler.cc
src/mds/MDBalancer.cc
src/mds/MDCache.cc
src/mds/MDCache.h
src/mds/MDSRank.cc
src/mds/MDSRank.h
src/mds/MDSRankQuiesce.cc
src/mds/MDSTableClient.cc
src/mds/MDSTableClient.h
src/mds/MDSTableServer.cc
src/mds/MDSTableServer.h
src/mds/Migrator.cc
src/mds/Migrator.h
src/mds/Mutation.cc
src/mds/Mutation.h
src/mds/PurgeQueue.h
src/mds/SnapClient.cc
src/mds/SnapClient.h
src/mds/SnapRealm.cc
src/mds/SnapServer.cc
src/mds/SnapServer.h
src/mds/snap.h
src/tools/cephfs/DataScan.cc

mds: uninline methods to reduce header dependencies and compile times

---

src/exporter/DaemonMetricCollector.cc

backport tracker: https://tracker.ceph.com/issues/73134
---
backport of https://github.com/ceph/ceph/pull/64335
parent tracker: https://tracker.ceph.com/issues/72686

reef: Handle failures in metric parsing

---

qa/workunits/rbd/rbd_mirror_group_simple.sh
src/librbd/CMakeLists.txt
src/librbd/api/Group.cc
src/librbd/api/Mirror.cc
src/librbd/mirror/GroupEnableRequest.cc
src/librbd/mirror/GroupEnableRequest.h
src/librbd/mirror/snapshot/GroupImageCreatePrimaryRequest.cc
src/librbd/mirror/snapshot/GroupImageCreatePrimaryRequest.h

Notable enhancements have been made to the mirror group_enable API:
* Previously, member images were enabled for mirroring synchronously
and one after another. They are now enabled asynchronously and
concurrently, making  the time to enable a group independent of the
number of member images it contains.
* Intermediate steps involved in enabling an image, such as fetching
mirror peers, acquiring an exclusive lock, creating a mirror snapshot,
among other operations, run asynchronously but are synchronized
across all the group member images using C_Gather callbacks. An
asynchronous operation on an image proceeds to the next step only
after that operation completes for all member images. This allows for
easier cleanup of member images and the group when an intermediate
operation fails for one …

librbd: make mirror group enable asynchronous

---

src/librbd/api/Group.cc
src/librbd/api/Group.h
src/librbd/api/Mirror.cc
src/librbd/librbd.cc

librbd/api: restrict APIs on secondary mirror groups

---

src/blk/kernel/KernelDevice.cc
src/blk/kernel/KernelDevice.h

This will eliminate a potential race between thread startup and its removal.
Relates-to: https://tracker.ceph.com/issues/71800
(cherry picked from commit 69369b151b96ca74bffb9d72f4c249f48fde2845) …

tentacle: blk/kernel: improve DiscardThread life cycle.

---

qa/tasks/thrashosds-health.yaml

backport tracker: https://tracker.ceph.com/issues/72819
---
backport of https://github.com/ceph/ceph/pull/64603
parent tracker: https://tracker.ceph.com/issues/70972

tentacle: qa/suites/rados/thrash-old-clients: Add OSD warnings to ignore list

---

qa/workunits/rados/test.sh
src/test/librados/CMakeLists.txt

backport tracker: https://tracker.ceph.com/issues/72996
---
backport of https://github.com/ceph/ceph/pull/64504
parent tracker: https://tracker.ceph.com/issues/71930

tentacle: qa/workunits/rados: remove cache tier test

---

src/crimson/tools/store_bench/store-bench.cc

Fix issue where coll_refs index could go out of bounds.
- …

crimson/.../store-bench: fix coll_refs index error

---

doc/rados/operations/monitoring.rst
src/mon/OSDMonitor.cc

This commit enables users to specify the format option for the data availability feature. Now if the users specific json-pretty, output will be displayed in the given format.
Command: `ceph osd pool availability-status --format json-pretty`
Output: 
```
[
{
"pool": ".mgr",
"uptime": 67,
"downtime": 0,
"mtbf": 0,
"mttr": 0,
"num_failures": 0,
"score": 1,
"available": true
},
{
"pool": "cephfs.a.meta",
"uptime": 59,
"downtime": 0,
"mtbf": 0,
"mttr": 0,
"num_failures": 0,
"score": 1,
"available": true
},
{
"pool": "cephfs.a.data",
"uptime": 56,
"downtime": 0,
"mtbf": 0,
"mttr": 0,
"num_failures": 0,
"score": 1,
"available": true
}
]
```
Command: `ceph osd pool availability-status --format json`
Output: 
```
[{"pool":".mgr","uptime":52,"downtime":0,"mtbf":0,"mttr":0,"num_failures":0,"score":1, …
```

mon/OSDMonitor.cc: optionally display availability status in json

---

doc/cephadm/services/osd.rst

Exact 5 GiB block devices are also considered as an available device.

doc: fix osd min size

---

qa/cephfs/overrides/pg_health.yaml

backport tracker: https://tracker.ceph.com/issues/68451
---
backport of https://github.com/ceph/ceph/pull/60012
parent tracker: https://tracker.ceph.com/issues/68284

reef: qa: ignore pg availability/degraded warnings

---

qa/tasks/cephfs/test_volumes.py
src/pybind/mgr/volumes/fs/operations/access.py

backport tracker: https://tracker.ceph.com/issues/71831
---
backport of https://github.com/ceph/ceph/pull/59435
parent tracker: https://tracker.ceph.com/issues/67708

tentacle: mgr/volumes: Keep mon caps if auth key has remaining mds/osd caps

---

qa/tasks/cephfs/test_volumes.py
src/pybind/mgr/volumes/fs/operations/access.py

backport tracker: https://tracker.ceph.com/issues/71832
---
backport of https://github.com/ceph/ceph/pull/59435
parent tracker: https://tracker.ceph.com/issues/67708

reef: mgr/volumes: Keep mon caps if auth key has remaining mds/osd caps

---

doc/cephfs/fs-volumes.rst
qa/tasks/cephfs/test_volumes.py
src/pybind/mgr/volumes/fs/operations/group.py
src/pybind/mgr/volumes/fs/volume.py
src/pybind/mgr/volumes/module.py

backport tracker: https://tracker.ceph.com/issues/73075
---
backport of https://github.com/ceph/ceph/pull/64324
parent tracker: https://tracker.ceph.com/issues/73074

tentacle: Add normalization and casesensitive options to the subvolume group creation command

---

qa/cephfs/clusters/1-node-4-mds-1-osd.yaml
qa/suites/fs/full/clusters/1-node-1-mds-1-osd.yaml
qa/suites/fs/full/clusters/1-node-4-mds-1-osd.yaml
qa/suites/fs/full/overrides.yaml
qa/suites/fs/full/tasks/mgr-osd-full.yaml
qa/workunits/fs/full/subvolume_ls.sh
src/mds/Server.cc

backport tracker: https://tracker.ceph.com/issues/72803
---
backport of https://github.com/ceph/ceph/pull/64663
parent tracker: https://tracker.ceph.com/issues/72260

tentacle: mds: Fix readdir when osd is full.

---

src/include/cephfs/types.h

backport tracker: https://tracker.ceph.com/issues/72153
---
backport of https://github.com/ceph/ceph/pull/64325
parent tracker: https://tracker.ceph.com/issues/71944

tentacle: mds: dump export_ephemeral_random_pin as double

---

qa/tasks/cephfs/test_cephfs_shell.py
src/client/Client.cc
src/client/Client.h
src/test/libcephfs/test.cc

backport tracker: https://tracker.ceph.com/issues/72644
---
backport of https://github.com/ceph/ceph/pull/64864
parent tracker: https://tracker.ceph.com/issues/72355

tentacle: client: use path supplied in statfs

---

qa/suites/upgrade/reef-x/stress-split/1-start.yaml
qa/suites/upgrade/squid-x/stress-split/1-start.yaml

backport tracker: https://tracker.ceph.com/issues/72285
backport tracker: https://tracker.ceph.com/issues/72388
---
backport of https://github.com/ceph/ceph/pull/64523
parent tracker: https://tracker.ceph.com/issues/50279
backport of https://github.com/ceph/ceph/pull/64494
parent tracker: https://tracker.ceph.com/issues/71615

tentacle: qa/suites/upgrade: add "Replacing daemon mds" to ignorelist

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-form/multi-cluster-form.component.ts

Allow the user to enter URL with FQDN in the Cluster API URL filed in the Connect Cluster form inside Multi-cluster tab.
Fixes: https://tracker.ceph.com/issues/73077
https://github.com/user-attachments/assets/1f0f942f-6ee3-4916-9d38-2d1979e5d187 …

mgr/dashboard: Allow FQDN in Connect Cluster form -> Cluster API URL

---

doc/mgr/smb.rst

backport of https://github.com/ceph/ceph/pull/63088
(cherry picked from commit 742659b18a21cd8ccc36a0f0a53bea265a13a541) …

tentacle: doc/mgr/smb: document the 'provider' option for smb share

---

src/pybind/mgr/cephadm/services/nvmeof.py

Backport of https://github.com/ceph/ceph/pull/63170
<details> …

tentacle: mgr/cephadm: don't mark nvmeof daemons without pool and group in name as stray

---

doc/radosgw/adminops.rst
qa/suites/rgw/verify/tasks/admin-pagination.yaml
qa/workunits/rgw/run-admin-pagination.sh
qa/workunits/rgw/test_rgw_admin_pagination.py
src/rgw/driver/rados/rgw_bucket.cc
src/rgw/driver/rados/rgw_bucket.h
src/rgw/driver/rados/rgw_rest_bucket.cc
src/rgw/radosgw-admin/radosgw-admin.cc
src/test/rgw/test_rgw_admin_bucket.py

backport of https://github.com/ceph/ceph/pull/62777
also includes backport of https://github.com/ceph/ceph/pull/64683 to fix regression in first PR
Fixes: https://tracker.ceph.com/issues/71475 …

tentacle: rgw/admin: Add max-entries and marker to bucket list

---

src/erasure-code/ErasureCode.cc
src/test/bufferlist.cc

Fixes: https://tracker.ceph.com/issues/72710 …

erasure-code: make bufferlist contiguous in ErasureCode::encode_prepare

---

src/pybind/mgr/mirroring/module.py

The command `fs snapshot mirror ls` is used to present state data to client.
This does not require Write semantics. …

pybind/mgr/mirroring: modifies the cli command type to read

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-notification-form/rgw-notification-form.component.ts

Fixes: https://tracker.ceph.com/issues/72989
Signed-off-by: pujashahu <pshahu@redhat.com>
---
Before fix
In the bucket notification form, old data is retained when switching from 'edit' mode to 'create' mode.
https://github.com/user-attachments/assets/5550274f-3794-4ec2-a002-7f226369ab0f
---
After Fix
https://github.com/user-attachments/assets/4f08d616-731e-47ae-9008-23e439e47d0f
Summery: 
--- …

mgr/dashboard: Form retains old data when switching from edit to create mode

---

src/mds/CDir.h
src/mds/Server.cc
src/test/libcephfs/snapdiff.cc

Backports: https://github.com/ceph/ceph/pull/64995
Parent tracker: https://tracker.ceph.com/issues/72518
Backport tracker: https://tracker.ceph.com/issues/72825 …

tentacle: mds: fix snapdiff result fragmentation

---

src/client/Client.cc
src/test/libcephfs/test.cc

backport tracker: https://tracker.ceph.com/issues/72505
---
backport of https://github.com/ceph/ceph/pull/62488
parent tracker: https://tracker.ceph.com/issues/70553

tentacle: client: fix unmount hang after lookups

---

monitoring/ceph-mixin/dashboards/ceph-cluster.libsonnet
monitoring/ceph-mixin/dashboards_out/ceph-cluster-advanced.json

fix "In" OSDs in Cluster-Advanced grafana panel. Also change units from decbytes to bytes wherever used in the panel
Fixes: https://tracker.ceph.com/issues/72810 …

monitoring: fix "In" OSDs in Cluster-Advanced grafana panel. Also change units from decbytes to bytes wherever used in the panel

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-mount-details/cephfs-mount-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/cephfs.model.ts

Fixes: https://tracker.ceph.com/issues/73137
Signed-off-by: Dnyaneshwari Talwekar dtalwekar@redhat.com
Before:-
After: -  …

mgr/dashboard: FS - Attach Command showing undefined for MountData

---

src/pybind/mgr/dashboard/controllers/prometheus.py
src/pybind/mgr/dashboard/services/orchestrator.py
src/pybind/mgr/dashboard/settings.py
src/pybind/mgr/dashboard/tests/test_prometheus.py

fixes : https://tracker.ceph.com/issues/72635
```
❯ kcli ssh -u root -- ceph-node-00 'cephadm logs -n \$(cephadm ls | grep -Eo "mgr\.ceph[0-9a-z.-]+" | head -n 1) -- -f' | grep 'get-credentials'
Inferring fsid d25bdf1a-83f8-11f0-9471-525400a4c5e1
Aug 28 10:39:34 ceph-node-00 ceph-mgr[3236]: log_channel(audit) log [DBG] : from='mon.? -' entity='mon.' cmd=[{"prefix": "orch alertmanager get-credentials"}]: dispatch
Aug 28 10:39:38 ceph-node-00 ceph-mgr[3236]: log_channel(audit) log [DBG] : from='mon.? -' entity='mon.' cmd=[{"prefix": "orch alertmanager get-credentials"}]: dispatch
Aug 28 10:39:38 ceph-node-00 ceph-mgr[3236]: log_channel(audit) log [DBG] : from='mon.? -' entity='mon.' cmd=[{"prefix": "orch alertmanager get-credentials"}]: dispatch
Aug 28 10:39:38 ceph-node-00 ceph-mgr[3236]: …
```

mgr/dashboard : Skip calls until secure_monitoring_stack is enabled

---

doc/rados/operations/stretch-mode.rst
qa/suites/rados/singleton/all/stretch-mode-5-mons-8-osds.yaml
qa/tasks/ceph_manager.py
qa/tasks/stretch_mode_disable_enable.py
qa/workunits/mon/mon-stretch-mode-5-mons-8-osds.sh
src/mon/MonCommands.h
src/mon/MonMap.cc
src/mon/Monitor.cc
src/mon/Monitor.h
src/mon/MonmapMonitor.cc
src/mon/OSDMonitor.cc
src/mon/OSDMonitor.h
src/osd/osd_types.cc

backport tracker: https://tracker.ceph.com/issues/68841
backport tracker: https://tracker.ceph.com/issues/72588
---
backport of https://github.com/ceph/ceph/pull/59483
parent tracker: https://tracker.ceph.com/issues/67467
backport of https://github.com/ceph/ceph/pull/60927
parent tracker: https://tracker.ceph.com/issues/69107

reef: mon [stretch mode]: support disable_stretch_mode & qa/workunits/mon: ensure election strategy is "connectivity" for stretch mode

---

src/include/cephfs/ceph_ll_client.h
src/include/cephfs/libcephfs.h
src/libcephfs.cc
src/test/libcephfs/test.cc

backport tracker: https://tracker.ceph.com/issues/69306
---
backport of https://github.com/ceph/ceph/pull/59936
parent tracker: https://tracker.ceph.com/issues/68189
**NOTE**: `path_walk()` refactor from https://github.com/ceph/ceph/pull/60746 included the core changes required here and thus _src/client/Client.cc_ changes have been removed from the cherry-pick as they conflict at the same time.

squid: client: Handle empty pathnames for `ceph_chownat()` and `ceph_statxat()`

---

qa/valgrind.supp

These leaks started happening when OpenSSL v3.5.0
was released. We determined they are safe to suppress.
Fixes: https://tracker.ceph.com/issues/71182 …

qa: suppress OpenSSL valgrind leaks

---

src/CMakeLists.txt

backport tracker: https://tracker.ceph.com/issues/72859
backport of https://github.com/ceph/ceph/pull/65371
parent tracker: https://tracker.ceph.com/issues/72361

squid: cmake: remove _FORTIFY_SOURCE define

---

cmake/modules/Builduadk.cmake

See https://github.com/ceph/ceph/pull/65371
Signed-off-by: David Galloway <david.galloway@ibm.com>
Uses https://github.com/ceph/uadk/commits/no-fortify-source/

uadk: Build with ceph fork (for FORTIFY_SOURCE fix)

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/nfs/nfs-form/nfs-form.component.ts

backport tracker: https://tracker.ceph.com/issues/73199
backport of https://github.com/ceph/ceph/pull/64858
parent tracker: https://tracker.ceph.com/issues/72435
(cherry picked from commit https://github.com/ceph/ceph/commit/38b237c8cb12cb77fd29a560c10c7e2225786955) …

tentacle: mgr/dashboard:[NFS] add Subvolume Groups and Subvolumes in "Edit NFS Export form"

---

src/pybind/mgr/cephadm/migrations.py

This was logging "running migration" every
single iteration of the serve loop previously
as we always call migrate even if there are
no migrations to do. This commit moves that
logging to log only when doing a migration and
includes which numeric migration is happening …

mgr/cephadm: fix migrations logging

---

monitoring/ceph-mixin/dashboards/ceph-cluster.libsonnet
monitoring/ceph-mixin/dashboards_out/ceph-cluster-advanced.json

backport tracker: https://tracker.ceph.com/issues/73229
---
backport of https://github.com/ceph/ceph/pull/65561
parent tracker: https://tracker.ceph.com/issues/72810

tentacle: monitoring: fix "In" OSDs in Cluster-Advanced grafana panel. Also change units from decbytes to bytes wherever used in the panel

---

monitoring/ceph-mixin/dashboards/ceph-cluster.libsonnet
monitoring/ceph-mixin/dashboards_out/ceph-cluster-advanced.json

backport tracker: https://tracker.ceph.com/issues/73231
---
backport of https://github.com/ceph/ceph/pull/65561
parent tracker: https://tracker.ceph.com/issues/72810

squid: monitoring: fix "In" OSDs in Cluster-Advanced grafana panel. Also change units from decbytes to bytes wherever used in the panel

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-mount-details/cephfs-mount-details.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-subvolume-list/cephfs-subvolume-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/models/cephfs.model.ts

backport tracker: https://tracker.ceph.com/issues/73234
---
backport of https://github.com/ceph/ceph/pull/65600
parent tracker: https://tracker.ceph.com/issues/73137

tentacle: mgr/dashboard: FS - Attach Command showing undefined for MountData

---

PendingReleaseNotes
doc/cephfs/fs-volumes.rst
doc/cephfs/troubleshooting.rst
qa/suites/fs/volumes/tasks/volumes/test/async.yaml
qa/tasks/cephfs/mount.py
qa/tasks/cephfs/test_volumes.py
src/pybind/mgr/volumes/fs/async_job.py
src/pybind/mgr/volumes/module.py

Original PR - https://github.com/ceph/ceph/pull/54396
Fixes: https://tracker.ceph.com/issues/70461
Parent tracker: https://tracker.ceph.com/issues/68630
Fixes: https://tracker.ceph.com/issues/70459
Parent tracker: https://tracker.ceph.com/issues/61903 …

reef: mgr/volumes: allow disabling async job threads

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/multi-cluster/multi-cluster-form/multi-cluster-form.component.ts

backport tracker: https://tracker.ceph.com/issues/73168
---
backport of https://github.com/ceph/ceph/pull/65566
parent tracker: https://tracker.ceph.com/issues/73077

tentacle: mgr/dashboard: Allow FQDN in Connect Cluster form -> Cluster API URL

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-multisite-zone-form/rgw-multisite-zone-form.component.ts
src/pybind/mgr/dashboard/services/rgw_client.py

backport tracker: https://tracker.ceph.com/issues/73166
---
backport of https://github.com/ceph/ceph/pull/65579
parent tracker: https://tracker.ceph.com/issues/73105

tentacle: mgr/dashboard: fix zone update API forcing STANDARD storage class

---

src/pybind/mgr/cephadm/inventory.py
src/pybind/mgr/cephadm/migrations.py
src/pybind/mgr/cephadm/tests/test_migration.py
src/pybind/mgr/cephadm/utils.py
src/python-common/ceph/deployment/service_spec.py

This PR includes four changes aimed at simplifying the cephadm migration logic by leveraging the new `certmgr` capabilities.
1. **Add mgmt-gateway and oauth2-proxy to the upgrade list**
> Ensures these newly introduced services are upgraded alongside other cephadm-managed services.
2. **Fix RGW spec validation for deprecated certificate field**
> The rgw_frontend_ssl_certificate field has been deprecated in favor of ssl_cert and ssl_key. The validation logic has been updated to run after automatic field transformation, ensuring correct validation of RGW specs.
3. **Remove specific SSL RGW migration logic**
> The special-case code for migrating RGW services is no longer needed. certmgr now populates the certstore by reading values directly from the spec during service redeployment as part …

mgr/cephadm: cleaning up old migration logic and improving upgrade handling with certmgr

---

PendingReleaseNotes
doc/cephfs/cephfs-mirroring.rst
doc/dev/cephfs-mirroring.rst
src/pybind/mgr/mirroring/module.py

cephfs_mirror: deprecate peer_add command

---

src/mgr/DaemonState.h

backport tracker: https://tracker.ceph.com/issues/72851
---
backport of https://github.com/ceph/ceph/pull/64764
parent tracker: https://tracker.ceph.com/issues/72337

tentacle: mgr/DaemonState: Minimise time we hold the DaemonStateIndex lock

---

src/osd/OSD.cc
src/osd/OSD.h

backport tracker: https://tracker.ceph.com/issues/72911
---
backport of https://github.com/ceph/ceph/pull/64837
parent tracker: https://tracker.ceph.com/issues/72412

tentacle: osd: stop scrub_purged_snaps() from ignoring osd_beacon_report_interval

---

debian/ceph-mgr.requires

backport tracker: https://tracker.ceph.com/issues/72090
---
backport of https://github.com/ceph/ceph/pull/64386
parent tracker: https://tracker.ceph.com/issues/72020

squid: deb/mgr: remove deprecated distutils from ceph-mgr.requires

---

src/rgw/rgw_bucket_logging.cc

Fixes typos in error messages. …

rgw/bucket-logging: fix typos 

---

src/pybind/mgr/prometheus/module.py

By exposing `cephadm orch ps` output as a Prometheus metric, we can track Ceph services and daemon states directly in Grafana, with clear labels for host, service type, daemon name, and version. This would allow us to move away from relying on the generic ceph_health_detail metric and instead trigger alerts on specific service or daemon failures. Such alerts would carry actionable context, significantly improving our time to detect and resolve issues. …

prometheus: Add Cephadm orch ps output metric to prometheus

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-storage-class-form/rgw-storage-class-form.component.ts

backport tracker: https://tracker.ceph.com/issues/73251
backport of https://github.com/ceph/ceph/pull/65170
parent tracker: https://tracker.ceph.com/issues/72641 …

tentacle: mgr/dashboard: fix data mismatch in Advance section in Tiering.

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster-review.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/create-cluster/create-cluster-review.component.ts

backport tracker: https://tracker.ceph.com/issues/73274
---
backport of https://github.com/ceph/ceph/pull/65652
parent tracker: https://tracker.ceph.com/issues/73220

squid: mgr/dashboard: Blank entry for Storage Capacity in dashboard under Cluster > Expand Cluster > Review

---

src/pybind/mgr/dashboard/controllers/nvmeof.py
src/pybind/mgr/dashboard/openapi.yaml

backport tracker: https://tracker.ceph.com/issues/73257
---
backport of https://github.com/ceph/ceph/pull/65504
parent tracker: https://tracker.ceph.com/issues/72757

tentacle: mgr/dashboard: --no-group-append default value to False, aligned with old cli

---

src/mds/MDSRank.cc

way to reproduce
../src/vstart.sh --debug --new -x --localhost --bluestore 
./bin/ceph tell mds.<rank 0> config set mds_kill_shutdown_at 10 
./bin/ceph fs set <fs name> down true
wait for a few seconds and will see the following log from take-over mds and rank 0 is mark damaged
2025-09-11T16:47:24.591+0800 785dabeaa6c0 -1 log_channel(cluster) log [ERR] : No subtrees found for root MDS rank! 2025-09-11T16:47:24.591+0800 785dabeaa6c0  5 mds.beacon.b set_want_state: up:rejoin -> down:damaged
During shutdown_pass after submitting Elid and trimming mdlog, mds log will now have  only ELid event which doesn't do anything at replay. so after replay, no subtree is found.
Fix this by checking MDLog if there's only ELid event. If so, don't check subtree for rank 0, and let it request STATE_STOPPED …

mds: fix rank 0 marked damaged if stopping fails after Elid flush.

---

doc/rados/operations/erasure-code.rst

doc/rados/operations: Clarify overwrites in erasure-code.rst
Prompted by a mailing list thread on 2025/09/05. …

doc/rados/operations: Clarify overwrites in erasure-code.rst

---

qa/suites/fs/full/tasks/mgr-osd-full.yaml
qa/workunits/fs/full/subvol_rm_retained_snap_when_cluster_is_full.sh
src/pybind/mgr/volumes/fs/operations/versions/subvolume_v2.py

The order of operation done for subvolume removal is reversed. The metadata is updated first followed by a rename operation on the uuid directory. If the metadata update operation fails, then the remove operations is failed thereby, keeping the subvolume metadata consistent with the uuid path.
Fixes: https://tracker.ceph.com/issues/67330 …

mgr/vol: handling the failed non-atomic operation

---

monitoring/ceph-mixin/prometheus_alerts.yml
monitoring/ceph-mixin/tests_alerts/test_alerts.yml
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/active-alert-list/active-alert-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/active-alert-list/active-alert-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table-key-value/table-key-value.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table-key-value/table-key-value.component.scss
src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table-key-value/table-key-value.component.ts

backport tracker: https://tracker.ceph.com/issues/73293
---
backport of https://github.com/ceph/ceph/pull/64467
parent tracker: https://tracker.ceph.com/issues/73290

squid: monitoring: fix MTU Mismatch alert rule and expr

---

monitoring/ceph-mixin/prometheus_alerts.yml
monitoring/ceph-mixin/tests_alerts/test_alerts.yml
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/active-alert-list/active-alert-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/active-alert-list/active-alert-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table-key-value/table-key-value.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table-key-value/table-key-value.component.scss
src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table-key-value/table-key-value.component.ts

backport tracker: https://tracker.ceph.com/issues/73294
---
backport of https://github.com/ceph/ceph/pull/64467
parent tracker: https://tracker.ceph.com/issues/73290

reef: monitoring: fix MTU Mismatch alert rule and expr

---

src/crimson/CMakeLists.txt

Move Jounald.cc into block that checks for WITH_SYSTEMD before adding to sources for crimson-common
Fixes: https://tracker.ceph.com/issues/73148 …

crimson: fix building without systemd

---

src/pybind/mgr/dashboard/services/rbd.py

backport tracker: https://tracker.ceph.com/issues/72986
---
backport of https://github.com/ceph/ceph/pull/64855
parent tracker: https://tracker.ceph.com/issues/72431

tentacle: mgr/dashboard : Fixed mirrored image usage info bar 

---

src/rgw/driver/rados/rgw_rados.cc
src/rgw/driver/rados/rgw_sal_rados.cc
src/test/rgw/rgw_multi/tests.py

resolves https://tracker.ceph.com/issues/72950
the fix here resets RGW_ATTR_OBJ_REPLICATION_TRACE during object attr changes.
otherwise, if a zone receives request for any s3 object api requests like PutObjectAcl, PutObjectTagging etc. and this zone was originally the source zone for the object put request, then such subsequent sync ops will fail. this is because the zone id was added to the replication trace to ensure that we don't sync the object back to it. for example in a put/delete race during full sync(https://tracker.ceph.com/issues/58911) so, if the same zone ever becomes the destination for subsequent sync requests on the same object, we compare this zone as the destination zone against the zone entries in replication trace and because it's entry is already present in the trace, …

rgw/multisite: fix sync requests on existing objects

---

qa/suites/crimson-rados/thrash_simple/thrashers/simple.yaml
src/crimson/os/seastore/lba/btree_lba_manager.cc
src/crimson/os/seastore/lba/btree_lba_manager.h
src/crimson/os/seastore/lba_manager.h
src/crimson/os/seastore/lba_mapping.h
src/crimson/os/seastore/object_data_handler.cc
src/crimson/os/seastore/object_data_handler.h
src/crimson/os/seastore/onode.h
src/crimson/os/seastore/onode_manager/staged-fltree/fltree_onode_manager.cc
src/crimson/os/seastore/onode_manager/staged-fltree/fltree_onode_manager.h
src/crimson/os/seastore/seastore.cc
src/crimson/os/seastore/seastore.h
src/crimson/os/seastore/seastore_types.h
src/crimson/os/seastore/transaction_manager.h
src/crimson/osd/osd_meta.cc
src/test/crimson/seastore/test_object_data_handler.cc
src/test/crimson/seastore/test_seastore.cc
src/test/crimson/seastore/test_transaction_manager.cc

This is another approach in implementing `OP_CLONERANGE2` support in SeaStore than #57735 .
Before this PR, we have implemented the support for `OP_CLONE` and `OP_CLONERANGE2` in a way which requires maintaining strict symmetric indirect lba mapping relations at any time. This means we have to create two sets of indirect lba mappings when dealing with `OP_CLONE` and move the direct mapping out when dealing with `OP_CLONERANGE2`, which makes the mechanism of `clone` and `clone_range` very complex, error prone and inefficient in terms of performance.
This PR takes another approach, which also ensures that modifications to any clone won't affect other clones that are sharing data with it, but doesn't require strict symmetric indirect lba mapping relations at any time, only at the time when …

crimson/os/seastore: OP_CLONERANGE2 support ---- another approach

---

doc/man/8/mount.ceph.rst

Fix two cases of a stray space in the middle of syntax causing invalid rendering (introduced in #49630).
Fix a missing apostrophe in "its" and expand another "it's" to the same "it is".
Harmonize usage of single and double backticks (for ceph commands and parameters respectively) and quotation marks (for reference to single characters in syntax).
Harmonize command parameter descriptions to always begin with capital case and end in full stop.
Other minor capitalization fixes.
Fix "scale with" that supposedly should be "scales with".
- Before: https://docs.ceph.com/en/latest/man/8/mount.ceph/
- Rendered PR: https://ceph--64727.org.readthedocs.build/en/64727/man/8/mount.ceph/ …

doc/man/8: Fix small errors and small improvements in mount.ceph.rst

---

src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/active-alert-list/active-alert-list.component.html
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/active-alert-list/active-alert-list.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/silence-form/silence-form.component.spec.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/silence-form/silence-form.component.ts
src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.html
src/pybind/mgr/dashboard/frontend/src/app/shared/models/prometheus-alerts.ts
src/pybind/mgr/dashboard/frontend/src/app/shared/services/prometheus-alert.service.ts

backport tracker: https://tracker.ceph.com/issues/73320
---
backport of https://github.com/ceph/ceph/pull/65459
parent tracker: https://tracker.ceph.com/issues/72944

tentacle: mgr/dashboard : Hide suppressed  alert on landing page

---

src/cephadm/cephadmlib/packagers.py
src/cephadm/tests/test_util_funcs.py

Backport of https://github.com/ceph/ceph/pull/65599
<details> …

tentacle: cephadm: support custom distros by falling back to ID_LIKE

---

.github/workflows/qa-symlink.yml
src/script/pin-gh-workflow-deps.sh

GitHub Workflows & Actions are increasingly becoming the target of SCM attacks. After a recent attack, Ceph org repos were restricted to use only allow-listed GH Actions and specific SHA-1 pins. However, GitHub Official (checkout/setup-python/etc.) Actions continued to be fully trusted. 
Github recently introduced a setting that requires [all deps to be pinned to a full SHA-1 hash](https://github.blog/changelog/2025-08-15-github-actions-policy-now-supports-blocking-and-sha-pinning-actions/).
This change addresses the only dependency left still using tag versions instead of SHA-1 pins. Additionally, it provides a script to scan a repo and replace version tags with SHA-1 deps.
Fixes: https://tracker.ceph.com/issues/73307
- To sign and title your commits, please refer to [Submitting Patches …

.github: pin GH Actions to SHA-1 commit

---

src/test/rgw/test_rgw_posix_driver.cc

Theoretically, the "existed" bools in the test could have had junk in them.  Since the driver only writes to them when writing "true", this could have had a false positive return.  Initialize them all.
Fixes: https://tracker.ceph.com/issues/73327 …

RGW - Posix Test - initialize "existed" bools

---

qa/suites/nvmeof/thrash/gateway-initiator-setup/10-subsys-90-namespace-no_huge_pages.yaml
qa/suites/orch/cephadm/mgr-nfs-upgrade/2-nfs.yaml
qa/suites/orch/cephadm/mgr-nfs-upgrade/4-final.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_basic.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_ctdb_node_gone_state.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_domain.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_basic.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_clustering_ips.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_ctdb_res_basic.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_ctdb_res_dom.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_ctdb_res_ips.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_ctdb_res_ports2c.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_domain.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_res_basic.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_res_dom.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_mgr_res_ports.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_proxy_disabled.yaml
qa/suites/orch/cephadm/smb/tasks/deploy_smb_proxy_enabled.yaml
qa/suites/orch/cephadm/smoke-roleless/2-services/nfs-haproxy-proto.yaml
qa/suites/orch/cephadm/smoke-roleless/2-services/nfs-ingress-rgw-bucket.yaml
qa/suites/orch/cephadm/smoke-roleless/2-services/nfs-ingress-rgw-user.yaml
qa/suites/orch/cephadm/smoke-roleless/2-services/nfs-ingress.yaml
qa/suites/orch/cephadm/smoke-roleless/2-services/nfs-ingress2.yaml
qa/suites/orch/cephadm/smoke-roleless/2-services/nfs-keepalive-only.yaml
qa/suites/orch/cephadm/smoke-roleless/2-services/nfs.yaml
qa/suites/orch/cephadm/smoke-roleless/2-services/nfs2.yaml
qa/tasks/cephadm.py
qa/tasks/python.py
qa/tasks/template.py
qa/tasks/vip.py

Extract the general templating functions that we had added to cephadm.py a while ago into a proper module that doesn't really have any functionality specific to cephadm. …

qa: Add new task module template.py

---

src/mds/FSMap.cc

Fix bug where active MDS daemons in remaining filesystems incorrectly have their join_fscid cleared to FS_CLUSTER_ID_NONE when any other filesystem is removed.
The issue was caused by variable name shadowing in erase_filesystem() where the loop variable 'fscid' shadowed the function parameter 'fscid': Inside loop: if (info.join_fscid == fscid) compared against the loop variable (remaining FS ID) instead of parameter (removed FS ID)
Renamed the loop variable to 'remaining_fscid' to eliminate the shadowing and ensure the comparison uses the correct filesystem ID.
Reproducer:
../src/vstart.sh --new -x --localhost --bluestore
FS=b
./bin/ceph osd pool create cephfs.${FS}.meta 64 64 replicated
./bin/ceph osd pool create cephfs.${FS}.data 64 64 replicated
./bin/ceph fs new ${FS} …

mds/FSMap: fix join_fscid being incorrectly reset for active MDS during filesystem removal

---

qa/tasks/cephfs/test_subvolume.py
src/mds/Server.cc
src/mds/Server.h

This introduces handling for the "ceph.dir.subvolume" virtual xattr on directories.
- Returns ASCII "1" when the directory is a subvolume root, "0" otherwise.
- Uses srnode->is_subvolume() for the determination.
- Returns -ENOTDIR for non-directory targets.
- Uses a lightweight rdlock on the directory’s snaplock to guard the read-only check.
- If the rdlock cannot be acquired immediately, returns -EBUSY to avoid blocking; callers can retry.
- Caches success of rd-only checks within the request via mdr->more()->rdonly_checks to prevent re-acquiring locks in the same op.
- Drops the rdlock once the check is complete.
QA:
- Extend CephFS subvolume tests to validate vxattr retrieval and behavior around setting/removal. …

mds: Return ceph.dir.subvolume vxattr

---

src/auth/AuthServer.h
src/crimson/auth/AuthServer.h
src/crimson/auth/DummyAuth.h
src/crimson/mon/MonClient.cc
src/crimson/mon/MonClient.h
src/crimson/net/ProtocolV2.cc
src/msg/async/ProtocolV2.cc

backport tracker: https://tracker.ceph.com/issues/72818
---
backport of https://github.com/ceph/ceph/pull/64717
parent tracker: https://tracker.ceph.com/issues/72265

tentacle: auth: msgr2 can return incorrect allowed_modes through AuthBadMethodFrame

---

src/mgr/MgrOpRequest.h

backport tracker: https://tracker.ceph.com/issues/72562
---
backport of https://github.com/ceph/ceph/pull/62445
parent tracker: https://tracker.ceph.com/issues/70618

tentacle: mgr: avoid explicit dropping of ref

---

src/CMakeLists.txt
src/rgw/rgw_s3select_private.h

Fixes: https://tracker.ceph.com/issues/72480 …

rgw/s3select: Disable stringop truncation warning for s3select.h

---

src/rgw/rgw_iam_policy.cc
src/rgw/rgw_iam_policy.h
src/test/rgw/test_rgw_iam_policy.cc

rgw/iam: fix NotEquals handling for multiple values

---

PendingReleaseNotes
qa/standalone/mon/availability.sh
src/common/options/mon.yaml.in

options/mon: disable availability tracking by default

---

src/pybind/mgr/dashboard/frontend/src/app/shared/api/prometheus.service.ts

Error in the below endpoint which is newly introduced for the osd nearfull ratio
```
Request URL
https://localhost:4200/api/prometheus/prometheus_query_data?params=%7B__name__=~%22ceph_osd_full_ratio%7Cceph_osd_nearfull_ratio%22%7D
Request Method
GET
Status Code
404 Not Found
Remote Address
[::1]:4200
Referrer Policy
strict-origin-when-cross-origin
```
Fixes: https://tracker.ceph.com/issues/73174 …

mgr/dashboard: fix prometheus API error when not configured

---

src/blk/kernel/KernelDevice.cc
src/blk/kernel/KernelDevice.h

This will eliminate a potential race between thread startup and its removal.
Relates-to: https://tracker.ceph.com/issues/71800
(cherry picked from commit 69369b151b96ca74bffb9d72f4c249f48fde2845) …

squid: blk/kernel: improve DiscardThread life cycle.

---

src/mgr/DaemonState.h

backport tracker: https://tracker.ceph.com/issues/72853
---
backport of https://github.com/ceph/ceph/pull/64764
parent tracker: https://tracker.ceph.com/issues/72337

squid: mgr/DaemonState: Minimise time we hold the DaemonStateIndex lock

---

qa/workunits/fs/test_python.sh
src/client/Client.cc
src/client/Client.h
src/common/strescape.h
src/include/filepath.cc
src/include/filepath.h
src/mds/CDentry.cc
src/mds/CDentry.h
src/mds/CDir.cc
src/mds/CDir.h
src/mds/CInode.cc
src/mds/CInode.h
src/mds/MDSAuthCaps.cc
src/mds/MDSAuthCaps.h
src/mds/ScrubStack.cc
src/mds/Server.cc
src/mds/SessionMap.cc
src/pybind/cephfs/cephfs.pyx
src/pybind/mgr/volumes/fs/operations/trash.py
src/test/mds/TestMDSAuthCaps.cc
src/test/pybind/test_cephfs.py

Method purge() in trash.py calls rmtree() which is recursive method. To
avoid Python's recurision limit, switch to non-recursive approach.
Fixes: https://tracker.ceph.com/issues/71648
Also fixes https://tracker.ceph.com/issues/72779 and https://tracker.ceph.com/issues/72993. …

pybind/cephfs, mgr/volumes: introduce non-recurisve rmtree(), refactor purge() to use it and add MDS optimizations

---

doc/dev/release-process.rst

doc/dev: Fix typo in release-process.rst

---

cmake/modules/AddCephTest.cmake

Add a pair of default test labels (`PurePython` and `PythonTox`) to the tests generated by the add_tox_test cmake function. In addition, the function can extend the set of labels applied with a new LABELS argument to the cmake function.
Using the label can be done with something like:
```
ctest -L PythonTox -j8
```
Note that these tests are labeled PurePython because they do not require C extensions to be built. The above example command can be run successfully immediately after configuring, without having to build the C++ sources first. …

pybind/mgr: add default set of cmake/ctest labels to tests

---

doc/cephfs/cache-configuration.rst

Fix two Sphinx warnings about :ref: links in troubleshooting.rst to undefined labels.  
Missed earlier these 2 fixable warnings in Sphinx output.
```console
/home/docs/checkouts/readthedocs.org/user_builds/ceph/checkouts/65809/doc/cephfs/troubleshooting.rst:282: WARNING: undefined label: 'cephfs_cache_configuration_mds_cache_memory_limit'
/home/docs/checkouts/readthedocs.org/user_builds/ceph/checkouts/65809/doc/cephfs/troubleshooting.rst:282: WARNING: undefined label: 'cephfs_mds_cache_configuration'
```
The PR #64928 added one label in another file but missed these two labels.  
I've tried to interpret where these labels should go & this (`cache-configuration.rst`) is the only doc that talks about the tunable `mds_cache_memory_limit`.
As per the referenced PR this seems to need …

doc/cephfs: Add missing labels in cache-configuration.rst

---

doc/cephfs/scrub.rst

Don't use a space in "subdirectory" or "kick-start".
Change command syntax introduction text to the common "To [...], run a command of the following form:" when the syntax has placeholders.
Use double backticks consistently (same as sections in the beginning) for CLI commands, parameters etc.
Linkify "cluster health warnings" to the CephFS health warnings doc.
Use admonition and fix two articles.
Use title case for section titles and trim overly long underline.
Minor improvements to language.
Don't use unordered lists in two cases when there's no real need, especially when there is only a single item in the latter case.
- Before: https://docs.ceph.com/en/latest/cephfs/scrub/
- Rendered PR: https://ceph--65809.org.readthedocs.build/en/65809/cephfs/scrub/ …

doc/cephfs: Typos and small improvements in scrub.rst

---

src/mds/CDir.h
src/mds/Server.cc
src/test/libcephfs/snapdiff.cc

Backports: https://github.com/ceph/ceph/pull/64995
Parent tracker: https://tracker.ceph.com/issues/72518
Backport tracker: https://tracker.ceph.com/issues/72824 …

reef: mds: fix snapdiff result fragmentation

---

qa/cephfs/clusters/1-node-4-mds-1-osd.yaml
qa/suites/fs/full/clusters/1-node-1-mds-1-osd.yaml
qa/suites/fs/full/clusters/1-node-4-mds-1-osd.yaml
qa/suites/fs/full/overrides.yaml
qa/suites/fs/full/tasks/mgr-osd-full.yaml
qa/workunits/fs/full/subvolume_ls.sh
src/mds/Server.cc

backport tracker: https://tracker.ceph.com/issues/72804
---
backport of https://github.com/ceph/ceph/pull/64663
parent tracker: https://tracker.ceph.com/issues/72260

reef: mds: Fix readdir when osd is full.

---

qa/tasks/cephfs/test_snap_schedules.py
src/pybind/mgr/snap_schedule/fs/schedule.py

backport tracker: https://tracker.ceph.com/issues/71436
---
backport of https://github.com/ceph/ceph/pull/59161
parent tracker: https://tracker.ceph.com/issues/64042

reef: mgr/snap_schedule: fix typo in error message during retention add

---

doc/cephadm/services/nfs.rst
doc/mgr/nfs.rst
src/cephadm/cephadmlib/daemons/nfs.py
src/pybind/mgr/cephadm/agent.py
src/pybind/mgr/cephadm/cert_mgr.py
src/pybind/mgr/cephadm/module.py
src/pybind/mgr/cephadm/serve.py
src/pybind/mgr/cephadm/services/cephadmservice.py
src/pybind/mgr/cephadm/services/ingress.py
src/pybind/mgr/cephadm/services/mgmt_gateway.py
src/pybind/mgr/cephadm/services/monitoring.py
src/pybind/mgr/cephadm/services/nfs.py
src/pybind/mgr/cephadm/services/nvmeof.py
src/pybind/mgr/cephadm/templates/services/nfs/ganesha.conf.j2
src/pybind/mgr/cephadm/tests/test_certmgr.py
src/pybind/mgr/cephadm/tests/test_services.py
src/pybind/mgr/cephadm/tlsobject_types.py
src/pybind/mgr/nfs/cluster.py
src/pybind/mgr/nfs/ganesha_conf.py
src/pybind/mgr/nfs/module.py
src/pybind/mgr/nfs/tests/test_nfs.py
src/python-common/ceph/deployment/service_spec.py

Fixes: https://tracker.ceph.com/issues/73035
This PR adds TLS (Transport Layer Security) support for NFS-Ganesha services in Cephadm, enabling secure connections with client certificate authentication. 
Changes of PR:
1. Updates get_certificates method to support CA certs
2. Adds TLS certificate support (server cert, key, CA cert) to NFSServiceSpec
3. Updates NFS service deployment to handle TLS configuration and file placement
4. Extends security types to include "tls" and "mtls" for NFS exports
Testing logs:
```
Ganesha.conf: 
TLS_CONFIG{
Enable_TLS = True;
TLS_Cert_File = /etc/ganesha/tls/tls_cert.pem;
TLS_Key_File = /etc/ganesha/tls/tls_key.pem;
TLS_CA_File = /etc/ganesha/tls/tls_ca_cert.pem;
TLS_Ciphers = "AES-256"; …
```

mgr/cephadm: Cephadm support for NFS-Ganesha TLS configuration
